salto-io/salto

packages/adapter-components/src/references/field_references.ts
packages/adapter-utils/src/utils.ts
packages/zendesk-support-adapter/e2e_test/mock_elements.ts
packages/zendesk-support-adapter/src/adapter.ts
packages/zendesk-support-adapter/src/config.ts
packages/zendesk-support-adapter/src/filters/field_references.ts
packages/zendesk-support-adapter/src/filters/reorder/automation.ts
packages/zendesk-support-adapter/src/filters/reorder/creator.ts
packages/zendesk-support-adapter/src/filters/reorder/organization_field.ts
packages/zendesk-support-adapter/src/filters/reorder/trigger.ts
packages/zendesk-support-adapter/system_config_doc.md
packages/zendesk-support-adapter/test/adapter.test.ts
packages/zendesk-support-adapter/test/filters/reorder/trigger.test.ts

_Support reorder of triggers_
---
* We use [this](https://developer.zendesk.com/api-reference/ticketing/business-rules/trigger_categories/#create-batch-job-for-trigger-categories) API to reorder the triggers and their categories.  According to [this](https://support.zendesk.com/hc/en-us/articles/4408834781594-Creating-categories-to-organize-triggers), the order of categories effect the order of the triggers as well (all the triggers of one category will be done before the triggers of another category with higher position)
* Removed positions field for ticket_field, macro and view
* inactive objects will be last in the order element
---
* support reorder of triggers
---
A new trigger order …

SALTO-2148: support reorder of triggers

---

packages/workspace/src/parser/internal/native/errors.ts
packages/workspace/src/parser/internal/native/lexer.ts
packages/workspace/src/parser/internal/native/parse.ts
packages/workspace/test/parser/errors.test.ts

Changed unresolved merge conflict message
---
---
---

SAAS-3619 Change unresolved merge conflict message

---

packages/zendesk-support-adapter/src/adapter.ts
packages/zendesk-support-adapter/src/config.ts
packages/zendesk-support-adapter/src/filters/field_references.ts
packages/zendesk-support-adapter/src/filters/reorder/creator.ts
packages/zendesk-support-adapter/src/filters/reorder/view.ts
packages/zendesk-support-adapter/src/filters/view.ts
packages/zendesk-support-adapter/system_config_doc.md
packages/zendesk-support-adapter/test/adapter.test.ts
packages/zendesk-support-adapter/test/filters/reorder/automation.test.ts
packages/zendesk-support-adapter/test/filters/reorder/view.test.ts

_support reordering of views_
---
---
_Zendesk_support adapter_:
* support reordering of views
---
_A new view order element will appear_

SALTO-2153: support reordering of views

---

packages/cli/src/formatter.ts
packages/cli/test/formatter.test.ts
packages/cli/test/mocks.ts
packages/cli/test/workspace/workspace.test.ts
packages/lang-server/src/diagnostics.ts
packages/lang-server/src/workspace.ts
packages/lang-server/test/diagnostics.test.ts
packages/workspace/index.ts
packages/workspace/src/workspace/workspace.ts
packages/workspace/test/workspace/workspace.test.ts

Remove the actual code fragments attached to the workspace errors, and keep only the location of the error.  
This should help with readability, and should improve the performance so that we can increase the limit of errors returned. Currently we limit only to 30 errors. 
---
None
---
Core - Errors will now contain only the location of the error, without the of the source file
---
None

SALTO-1691: Remove code fragments from workspace errors

---

packages/zendesk-support-adapter/e2e_test/adapter.test.ts
packages/zendesk-support-adapter/src/config.ts
packages/zendesk-support-adapter/test/adapter.test.ts

_Remove organizations from the default type list_
---
---
* Remove organizations from the default include type list
---
_None_

SALTO-2162: remove organizations from the default type list

---

packages/lang-server/src/workspace.ts
packages/lang-server/test/workspace.test.ts
packages/vscode/src/events.ts
packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
packages/workspace/src/workspace/workspace.ts
packages/workspace/test/workspace/adapters_config.test.ts
packages/workspace/test/workspace/multi_env/multi_env_source.test.ts
packages/workspace/test/workspace/nacl_files/nacl_files_source.state.test.ts
packages/workspace/test/workspace/workspace.test.ts

_change setNaclFiles to receive array_
---
Fetch on one of our customers failed due to the fact that we passed 150k elements to setNaclFiles that use the spread notation. Changing the parameters to list instead of the spread notation fixes the problem. More details in the ticket
---
_None_
---
_None_

SALTO-2161: change setNaclFiles to receive array

---

packages/netsuite-adapter/src/change_validator.ts
packages/netsuite-adapter/src/change_validators/account_specific_values.ts
packages/netsuite-adapter/src/change_validators/not_yet_supported_values.ts
packages/netsuite-adapter/src/change_validators/utils.ts
packages/netsuite-adapter/src/constants.ts
packages/netsuite-adapter/test/change_validators/not_yet_supported.test.ts

Add a change validator to create an error when trying to deploy instances with a "NOT YET SUPPORTED" value, as they would fail to deploy them anyway. 
---
None
---
NetSuite Adapter: Prevent deploying instances which contain a "NOT_YET_SUPPORTED" value 
---
None

SALTO-2090: Change Validator for "NOT_YET_SUPPORTED" values in NetSuite

---

packages/workspace/src/workspace/nacl_files/elements_cache.ts
packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
packages/workspace/src/workspace/nacl_files/parsed_nacl_file.ts
packages/workspace/src/workspace/nacl_files/parsed_nacl_files_cache.ts
packages/workspace/test/common/nacl_file_source.ts
packages/workspace/test/workspace/multi_env/multi_env_source.test.ts

Before this change, if there was no semantic change in a nacl file source, the other caches
(multi env and workspace) would not be updated, which meant the hash would become out of sync
leading to incorrect cache invalidation the next time a semantic change is detected.
The fix here keeps the hash as a non-semantic meaning (unfortunately) which means there are still
many different hashes that can all represent to same elements.
this is not ideal, but hopefully now the nacl source and multi env source would both be updated
so they do not lose sync of which hash is the current hash.
---
Note that this re-calculation of the cache, when it happened in "updateNaclFiles", would cause us to report
an incorrect number of changes. so, if this cache invalidation would happen on fetch for example, …

SALTO-2156: Fix unneeded cache invalidation in multi-env source

---

packages/core/src/core/fetch.ts
packages/core/test/core/fetch.test.ts

---
*Core*:
* Removed a restriction from FetchFromWorkspace that failed if the adapter configs were different
---
None

SALTO-2159 - Remove the different config restriction from FetchFromWorkspace

---

packages/salesforce-adapter/src/change_validators/ref_to_instance_of_same_type.ts
packages/salesforce-adapter/test/change_validators/ref_to_instance_of_same_type.test.ts

This is a short term solution for an issue we currently have with deploys of Custom Object Instances.
When deploying additions of two instances, that one has a reference to the other, because they are grouped together in the same group we have an issue with deploying the one that has the instance.
Thus we add an Error to it and direct the user to deploy twice, and the second deploy should work for it.
The longer term solution for this is to change the grouping or handle refs inside groups somehow different.
---
*Salesforce*: 
* Added a change validator to detect Instances with dependencies on other instances of the same type that were not yet deployed. Since our grouping does not split them at the moment and causes issues on deploy.

SALTO-1804 - Validate no addition instances are dependent on other instances of the same type that were not deployed yet

---

packages/netsuite-adapter/e2e_test/adapter.test.ts
packages/netsuite-adapter/package.json
packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/change_validator.ts
packages/netsuite-adapter/src/change_validators/undeployable_config_features.ts
packages/netsuite-adapter/src/client/client.ts
packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/src/constants.ts
packages/netsuite-adapter/src/errors.ts
packages/netsuite-adapter/src/filters/config_features.ts
packages/netsuite-adapter/src/group_changes.ts
packages/netsuite-adapter/src/query.ts
packages/netsuite-adapter/src/transformer.ts
packages/netsuite-adapter/src/types.ts
packages/netsuite-adapter/src/types/configuration_types.ts
packages/netsuite-adapter/test/adapter.test.ts
packages/netsuite-adapter/test/change_validators/undeployable_config_features.test.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts
packages/netsuite-adapter/test/filters/config_features.test.ts
packages/netsuite-adapter/test/transformer.test.ts
packages/netsuite-adapter/test/types.test.ts
yarn.lock

Import features config type using SDF
---
This PR is rebased on https://github.com/salto-io/salto/pull/2882
Please review this one starting this commit - [SALTO-1387 import features](https://github.com/salto-io/salto/pull/2887/commits/47d6f7eeffff0008e6ef6e176ed8073b6d952c1a)
---
- Support `companyFeatures` config type using SDF
---
Netsuite - new features config type will be added to the workspace
Type example: `netsuite/Types/companyFeatures.nacl`
```
settings netsuite.companyFeatures {
boolean DEPARTMENTS {
label = "Departments"
}
boolean LOCATIONS {
label = "Locations"
}
boolean CLASSES {
label = "Classes"
}
boolean JOBS {
label = "Projects"
}
}
```
Instance example: …

SALTO-1387 import features

---

packages/jira-adapter/src/config.ts
packages/jira-adapter/system_config_doc.md

Fixed the field type in gadgets.
---
It looks like the incorrect type caused `Unexpected hidden part found in array:` for some reason
---
- Fixed incorrect gadgets field type
---
None

SALTO-2171: Fixed gadgets field type

---

packages/cli/e2e_test/helpers/workspace.ts
packages/cli/src/command_builder.ts
packages/cli/src/commands/env.ts
packages/cli/src/commands/fetch.ts
packages/cli/test/command_builder.test.ts
packages/cli/test/commands/fetch.test.ts
packages/core/src/local-workspace/workspace.ts
packages/core/test/workspace/local/workspace.test.ts
packages/vscode/src/extension.ts

Add optional parameter allowing the caller to use an alternative credentials source.
This can be useful for runtimes that would like to use a different credential storage option.
---
Given the amount of arguments that `loadLocalWorkspace` now gets and since a lot of them are optional, changing the interface to an argument object seems justified.
However, since this is a central API, I tried to avoid breaking it right now.
We should probably remove the old function format in a few weeks
---
- Add ability to pass a custom credentials source to `loadLocalWorkspace`
---
_None_

SALTO-2166: Allow overriding the credential source in loadLocalWorkspace

---

packages/workspace/src/workspace/nacl_files/elements_cache.ts
packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
packages/workspace/src/workspace/nacl_files/parsed_nacl_file.ts
packages/workspace/src/workspace/nacl_files/parsed_nacl_files_cache.ts
packages/workspace/test/common/nacl_file_source.ts
packages/workspace/test/workspace/multi_env/multi_env_source.test.ts

This reverts commit cfa72e575c17bca9274e2b3dd9893157e2098ea5.
Fix failures in fetch from workspace flows

SAAS-4713: Revert "SALTO-2156: Fix unneeded cache invalidation in multi-env source"

---

packages/cli/src/commands/deploy.ts
packages/cli/src/prompts.ts
packages/cli/test/commands/workspace.test.ts

change prompt msg
---
In SAAS-3481 I've changed SHOULD_EXECUTE_PLAN prompt message to fit the desire text (by product decision) to execute deploy plan.
When invoking a clean ws we want the old prompt msg, so I've split it into two different prompts
---
None
---
None

SALTO-2157 change prompt message for invoking clean workspace

---

packages/jira-adapter/src/config.ts
packages/jira-adapter/system_config_doc.md
packages/jira-adapter/test/adapter.test.ts

We changed the url of the Jira swagger to work with a temporary branch `next-main` to handle a breaking change in the swagger. Now that it is in production, we can return it to `main`
---
None
---
None

Restored jira swagger url to main

---

packages/zendesk-support-adapter/src/adapter.ts
packages/zendesk-support-adapter/src/filters/dynamic_content_references.ts
packages/zendesk-support-adapter/test/filters/dynamic_content_references.test.ts

Added generated_dependencies to dynamic content items
---
_Zendesk Support Adapter_:
- Added references to dynamic content items if their placeholder is used
---
_Zendesk Support Adapter_:
- After the next fetch, `_generated dependecies` value will be added to instances that use placeholders of dynamic content items

SALTO-2157: Added generated_dependencies to dynamic content items

---

packages/salesforce-adapter/src/change_validator.ts
packages/salesforce-adapter/src/types.ts

Add the validator that was merged in https://github.com/salto-io/salto/pull/2896 to the ChangeValidators config so it will actually run 🤦‍♂️

SALTO-1804 - Add the refToInstanceSameType validator to the salesforce config

---

packages/salesforce-adapter/src/change_validator.ts
packages/salesforce-adapter/src/change_validators/sbaa_approval_rules_custom_condition.ts
packages/salesforce-adapter/src/constants.ts
packages/salesforce-adapter/src/types.ts
packages/salesforce-adapter/test/change_validators/sbaa_approval_rules_custom_condition.test.ts

We currently know it's impossible to add an ApprovalRule with ConditionMet valued Custom that has an incoming reference from an ApprovalCondition that is also being added, due to a package Trigger validation that is impossible to disable at the moment.
Our current workaround is to modify the value to "All", deploy, and then change back to "Custom" and deploy again. This is currently only in our memories, this validator is here is Warn the users and remind them of this painful solution so we and they won't forget.
There are longer term possible solutions for this but this has been the case for a while so a validator seems reasonable.
This is a Warning and not an Error cause someone might have another way to work around this and an Error can be painful if that's the case.
---
_Release …

Salto-1578 - sbaa ApprovalRule with Custom ConditionsMet validate no incoming ref on addition

---

packages/adapter-api/src/elements.ts
packages/adapter-api/src/values.ts
packages/adapter-api/test/change.test.ts
packages/adapter-api/test/elements.test.ts
packages/adapter-components/src/elements/type_elements.ts
packages/adapter-components/test/elements/ducktype/deployment_placeholder_types.test.ts
packages/adapter-components/test/elements/type_elements.test.ts
packages/adapter-utils/src/utils.ts
packages/adapter-utils/test/utils.test.ts
packages/core/test/core/fetch.test.ts
packages/salesforce-adapter/test/filters/author_information/custom_objects.test.ts
packages/salesforce-adapter/test/filters/author_information/data_instances.test.ts
packages/workspace/src/element_adapter_rename.ts
packages/workspace/src/workspace/hidden_values.ts
packages/workspace/src/workspace/nacl_files/nacl_file_update.ts
packages/workspace/test/validator.test.ts
packages/workspace/test/workspace/workspace.test.ts

Currently TypeReference stores its value both in .type and in .value that is inherited from ReferenceExpression
This leads to confusion in the code where some places use .value and others use .type
Aligning all places to use .type (since that is the more strongly typed option)
---
---
_None_
---
_None_

SALTO-2176: Detach TypeReference from ReferenceExpression

---

packages/netsuite-adapter/e2e_test/adapter.test.ts
packages/netsuite-adapter/src/client/client.ts
packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/src/errors.ts
packages/netsuite-adapter/src/group_changes.ts
packages/netsuite-adapter/test/client/client.test.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts

Support SDF partial successful deploy:
- Retry deploying when specific change(s) fails (without the failed changes)
---
- Support SDF partial successful deploy - retry deploying when specific change(s) fails
---
None

SALTO-837 sdf partial successful deploy

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/filters/unresolved_parents.ts
packages/jira-adapter/test/filters/unresolved_parents.test.ts

Fixed to remove instances with unresolved parents
---
In the Jira adapter we remove instances has a non-unique name. We didn't remove so far also their children instances which caused unresolved references
---
- Fixed a bug where duplicated names of dashboards in the service would cause unresolved references in the workspace
---
None

SALTO-2196: Fixed to remove instance with unresolved parents

---

packages/netsuite-adapter/src/filters/suiteapp_config_elements.ts

Omit "undefined" string values in SuiteApp config instances
---
- Omit "undefined" string values in SuiteApp config instances
---
- Omit "undefined" string values in SuiteApp config instances

SALTO-1387 omit undefined values in suiteapp config instances

---

packages/core/src/core/plan/change_validators/check_deployment_annotations.ts
packages/core/test/core/plan/change_validators/check_deployment_annotations.test.ts

changed error text for deploying a change in a not supported field.
---
---
---

SALTO-2084/changed error text

---

packages/jira-adapter/e2e_test/instances/workflow.ts
packages/jira-adapter/src/filters/sort_lists.ts

Added sort to workflow transition to remove noise diff between envs
---
- Fixed a bug where a workflow transition order can be different between envs
---
- After the next fetch, order of transitions can be changed in workflow instances

SALTO-2088: Sort workflow transitions

---

packages/netsuite-adapter/src/config.ts
packages/netsuite-adapter/test/config.test.ts

SALTO-2206: Exclude instances of "items" that are fetched using the SuiteApp from the default adapter config

SALTO-2206: Exclude instances of "items" that are fetched using the SuiteApp from the default adapter config

---

packages/core/src/core/fetch.ts

--
*Core*:
* Change Fetch From workspace logic to optimize for certain workspaces when used remotely

Load the pathIndex to an inMemory remoteMap in fetchFrom to significantly reduce # of calls for certain workspaces

---

packages/stripe-adapter/README.md

Update authentication instructions in stripe's README due to Stripe's UI changes.
---
Stripe adapter: update authentication instructions in stripe's README
---
None

update authentication instructions in stripe's README

---

packages/jira-adapter/src/filters/fields/contexts.ts
packages/jira-adapter/test/filters/fields/contexts.test.ts

Jira e2e fails sporadically with https://app.circleci.com/pipelines/github/salto-io/salto/12551/workflows/5a2f21e9-5ea3-4879-b9de-b8548414e775/jobs/92507  because we receive different message than expected. I think this is because we delete the field and the field context in parallel (which only happens in the e2e because in the full flow we have dependency between the field and the context)
Even though it's only relevant for the e2e I fixed it in `src` because it's generally better to look for the HTTP status and not the message
---
None
---
None

Fixed Jira e2e

---

packages/salesforce-adapter/e2e_test/custom_object_instances.test.ts
packages/salesforce-adapter/src/client/client.ts
packages/salesforce-adapter/src/constants.ts
packages/salesforce-adapter/src/custom_object_instances_deploy.ts
packages/salesforce-adapter/test/custom_object_instances_deploy.test.ts

Deleting a custom object instance is not considered an error, just like for metadata object instances. 
---
None
---
Salesforce - Trying to delete an already deleted Custom Object instance now isn't considered as an error
---
None

SALTO-1690: Salesforce - Silence error for Custom Object instance deletion if it's already deleted

---

packages/jira-adapter/src/filters/workflow/workflow_deploy_filter.ts
packages/jira-adapter/test/filters/workflow/workflow_deploy_filter.test.ts

Workflow modification right after creation (without a fetch in the middle) would fail because the instance would miss a required value `operations`
---
- Fixed an issue with editing a workflow right after creating it (without a fetch in the middle)
---
None

SALTO-2208: Fix workflow modification

---

packages/adapter-utils/src/references.ts
packages/jira-adapter/src/dependency_changers/index.ts
packages/jira-adapter/src/dependency_changers/removals.ts
packages/jira-adapter/test/dependency_changers/removals.test.ts

Deleting a workflow fails if it is used in a workflow scheme. So far if the user will try to delete a workflow and remove it from its workflow scheme in the same deployment, it will fail because it will try to do it in parallel and not first remove the workflow from the workflow scheme. Added dependency changer so references will be removed before the referenced element is removed
---
- Fixed a bug where deleting a workflow its workflow scheme at the same deployment would fail
---
None

SALTO-2085: Deleting an active workflow fails

---

packages/adapter-components/package.json
packages/adapter-components/src/config/index.ts
packages/adapter-components/src/config/transformation.ts
packages/adapter-components/src/elements/instance_elements.ts
packages/adapter-components/src/filters/index.ts
packages/adapter-components/src/filters/referenced_instance_names.ts
packages/adapter-components/test/config/transformation.test.ts
packages/adapter-components/test/filters/referenced_instance_name.test.ts
packages/adapter-components/tsconfig.json

Add a filter that replaces internal ID's from instances names with the referenced instances names
This PR continues https://github.com/salto-io/salto/pull/2812 (which is split to a few PRs)
---
The PR includes the following changes:
1. Add a new configuration symbol '&' in idFields, which marks an idField as 'referenced idField' - idField that should be replaced with instance name. This includes a validation function that checks that the symbol is being used correctly.
2. A filter that makes the changes in all the relevant instance elements (that contains referenced idFields) names after its references are resolved. This also includes sorting the instances according to the name dependencies.
3. As some of the code relies on the instance name creation on `toBasicInstance`, I made some …

SALTO-1687 add filter that removes internal IDs from instances names

---

packages/adapter-components/src/deployment/change_validators/check_deployment_based_on_config.ts
packages/adapter-components/test/deployment/change_validators/check_deployment.test.ts
packages/zendesk-support-adapter/src/adapter.ts
packages/zendesk-support-adapter/src/change_validator.ts
packages/zendesk-support-adapter/src/filters/field_references.ts
packages/zendesk-support-adapter/src/filters/tag.ts
packages/zendesk-support-adapter/src/filters/user.ts
packages/zendesk-support-adapter/src/filters/utils.ts
packages/zendesk-support-adapter/test/adapter.test.ts
packages/zendesk-support-adapter/test/change_validator.test.ts
packages/zendesk-support-adapter/test/filters/tag.test.ts

_extract tags to references_
---
* Tags are not objects in zendesk (they don't have internal id and such)
* There is an API to list the 500 most popular tags (which doesn't help us)
* We decided to extract it based on all the places that refer to tags
* In those places, tags are defined with space as a separator
* There is no deploy for tags - so I created an empty deploy function
---
_Zendesk_support adapter:_
* Add references to tags
---
_New tags instances will be added and the places that refer to them will be changed_

SALTO-2054: extract tags to references

---

packages/adapter-utils/src/utils.ts
packages/jira-adapter/e2e_test/instances/webhook.ts
packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/filters/jql/jql_references.ts
packages/jira-adapter/src/filters/jql/references_extractor.ts
packages/jira-adapter/src/filters/jql/types.ts
packages/jira-adapter/src/filters/webhook/types.ts
packages/jira-adapter/src/filters/webhook/webhook.ts
packages/jira-adapter/test/filters/jql/jql_references.test.ts
packages/jira-adapter/test/filters/webhook/webhook.test.ts

Parsed JQLs to references and added the references in _generated_dependencies in the relevant types
Also fixed the name of the field `issue_related_events_section` so I can create a reference to it
---
- Added references from JQLs in instances in a _generated_dependencies field
---
- _generated_dependecies will be added to instances with JQLs

SALTO-1932: Create generated_dependencies out of JQL fields

---

packages/jira-adapter/src/config.ts
packages/jira-adapter/src/filters/board/board_columns.ts
packages/jira-adapter/src/filters/board/board_deployment.ts
packages/jira-adapter/test/filters/board/board_deployment.test.ts

It looks like in the CI sometimes the columns of a board are not updated correctly.
Added a retry to try to deploy it again in case this happens
---
- Fix a sporadic bug when in some cases the board columns would not be updated correctly
---
None

SALTO-2213: Jira e2e fails sporadically with incorrect deploy result

---

packages/adapter-components/src/elements/ducktype/add_remaining_types.ts
packages/adapter-components/src/elements/ducktype/standalone_field_extractor.ts
packages/adapter-components/src/elements/ducktype/transformer.ts
packages/adapter-components/src/elements/ducktype/type_elements.ts
packages/adapter-components/src/filters/ducktype/hide_types.ts
packages/adapter-components/src/filters/ducktype/index.ts
packages/adapter-components/test/elements/ducktype/add_remaining_types.test.ts
packages/adapter-components/test/filters/ducktype/hide_types.test.ts
packages/workato-adapter/src/adapter.ts
packages/workato-adapter/src/filters/ducktype_common.ts
packages/zendesk-support-adapter/src/adapter.ts
packages/zendesk-support-adapter/src/filters/ducktype_common.ts
packages/zendesk-support-adapter/src/filters/hardcoded_channel.ts
packages/zendesk-support-adapter/src/filters/hide_types.ts
packages/zendesk-support-adapter/src/filters/macro_attachments.ts
packages/zendesk-support-adapter/src/filters/reorder/creator.ts
packages/zendesk-support-adapter/src/filters/reorder/trigger.ts
packages/zendesk-support-adapter/src/filters/tag.ts
packages/zendesk-support-adapter/test/filters/hide_types.test.ts
packages/zendesk-support-adapter/test/filters/reorder/automation.test.ts
packages/zendesk-support-adapter/test/filters/reorder/ticket_form.test.ts
packages/zendesk-support-adapter/test/filters/reorder/trigger.test.ts
packages/zendesk-support-adapter/test/filters/reorder/view.test.ts

_Move the hide types part to be in a filter_
---
Currently, there is a logic that set a type as hidden in each filter that creates a type. So I moved it to a filter that should runs last.
---
_None_
---
_None_

SALTO-2199: move the hide types part to be in a filter

---

packages/salesforce-adapter/src/change_validators/custom_field_type.ts
packages/salesforce-adapter/test/change_validators/custom_field_type.test.ts

There is no need to return this warning as we won't try to deploy these fields anyway
---
None
---
Salesforce - Remove warning about Id field when deploying new custom objects
---
None

SALTO-2207: Salesforce - Don't warn on adding system fields when cloning custom objects

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/filters/forbidden_permission_schemes.ts
packages/jira-adapter/test/filters/forbidden_permission_schemes.test.ts

omit "VIEW_PROJECTS" and "VIEW_ISSUES" permissions from permission schemes since they are invisible in the ui and cant be deployed.
---
going to suppress notifications in saas aswell
---
Removed redundant values from permission scheme instances to fix the deployment of permission schemes
---
removed "VIEW_PROJECTS" and "VIEW_ISSUES" permissions from permission scheme NaCL files.

SALTO-2226/omit specific permissions from permission schemes

---

packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/change_validators/read_only_project_role.ts
packages/jira-adapter/test/change_validators/read_only_project_role.test.ts

add a change validator for a default Project role that is read only and cant be changed.
---
---
---

SALTO-2224/forbid read only changes

---

packages/jira-adapter/e2e_test/instances/workflow.ts
packages/jira-adapter/src/filters/workflow/conditions_types.ts
packages/jira-adapter/src/filters/workflow/workflow_deploy_filter.ts
packages/jira-adapter/src/filters/workflow/workflow_structure_filter.ts
packages/jira-adapter/src/reference_mapping.ts
packages/jira-adapter/test/filters/workflow/workflow_deploy_filter.test.ts
packages/jira-adapter/test/filters/workflow/workflow_structure_filter.test.ts

Fixed deploying workflows with some kinds of conditions by removing redundant values from the workflows (name) and casting the ids from number to string
---
- Fixed deploying workflow with `previousStatus` condition
---
None

SALTO-2223: Deploying workflows with previousStatus condition fail 

---

packages/netsuite-adapter/src/client/client.ts
packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts

improve soap requests retries - retrying inner functions instead of the "heavy" functions to prevent doing success requests again.
---
- improve soap requests retries
---
None

SALTO-2211 improve soap requests retries

---

packages/zendesk-support-adapter/src/filters/remove_definition_instances.ts
packages/zendesk-support-adapter/test/adapter.test.ts
packages/zendesk-support-adapter/test/filters/remove_definition_instances.test.ts

_Change definition instances to be hidden in order to debug weird trigger definition instance_
---
This PR is for debugging purposes
This PR should be reverted once we figured what caused SALTO-2202
---
_None_
---
_None_

SALTO-2202: Change definition instances to be hidden in order to debug weird trigger definition instance

---

.circleci/config.yml
.github/workflows/notices.yml
README.md
packages/cli/package_native.js

---
This is the newest version that has prebuilt binaries for all the relevant platforms in the [nexe releases page](https://github.com/nexe/nexe/releases)
---
CLI:
- Updated node js version to v14.15.3 in released binaries
---
_None_

SALTO-1243: Bump nodejs version in CLI builds to 14.15.3

---

packages/zendesk-support-adapter/src/client/client.ts
packages/zendesk-support-adapter/test/client/client.test.ts

_Return empty result on 404 responses in zendesk_
---
None
---
_None_
---
_None_

SALTO-2225: return empty result on 404 responses in zendesk

---

packages/jira-adapter/src/filters/project.ts
packages/jira-adapter/test/filters/project.test.ts

Some JSM project, when created, creates some components as a side effect. We would want to remove them so we can deploy the components in the NaCls
---
- Fixed a bug where some project component would be created a side effect of creating the project
---
None

SALTO-2245: Fixed deployment of JSM projects

---

packages/zuora-billing-adapter/src/config.ts
packages/zuora-billing-adapter/system_config_doc.md

There was a change in the schema name (from earlier today) in the `/settings/list` response which is causing the fetch of the revenue recognition rules to fail. mapping it back to the old name, so that no upgrades are needed in existing workspaces.
---
Zuora Billing Adapter:
* Fix fetch failure in the `Settings_revenueRecognitionRuleDtos` type
---
None

SALTO-2247 update revenue recognition type name

---

packages/workspace/src/workspace/nacl_files/elements_cache.ts
packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
packages/workspace/src/workspace/nacl_files/parsed_nacl_file.ts
packages/workspace/src/workspace/nacl_files/parsed_nacl_files_cache.ts
packages/workspace/test/common/nacl_file_source.ts
packages/workspace/test/workspace/multi_env/multi_env_source.test.ts

Before this change, if there was no semantic change in a nacl file source, the other caches
(multi env and workspace) would not be updated, which meant the hash would become out of sync
leading to incorrect cache invalidation the next time a semantic change is detected.
The fix here keeps the hash as a non-semantic meaning (unfortunately) which means there are still
many different hashes that can all represent to same elements.
this is not ideal, but hopefully now the nacl source and multi env source would both be updated
so they do not lose sync of which hash is the current hash.
---
Note that this re-calculation of the cache, when it happened in "updateNaclFiles", would cause us to report
an incorrect number of changes. so, if this cache invalidation would happen on fetch for example, …

Salto 2156 fix unneeded cache invalidation

---

packages/jira-adapter/config_doc.md
packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/adapter_creator.ts
packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/change_validators/masking.ts
packages/jira-adapter/src/config.ts
packages/jira-adapter/src/filters/masking.ts
packages/jira-adapter/test/change_validators/masking.test.ts
packages/jira-adapter/test/filters/masking.test.ts

Added configuration option to replace sensitive header values in Automation with a masked value and a change validator to tell the user to update the values in the service
---
- Added `masking.headers` configuration option to mask sensitive data from Automation NaCls
---
None

SALTO-2220: Omit sensitive Jira Automation fields from UI

---

packages/salesforce-adapter/src/client/client.ts

Add some new errors we have seen in fetch to the list of errors which will cause the element to be excluded with a suggestion, and let the fetch continue.
---
None
---
Salesforce - More error types will now cause an exclude config suggestion instead of just failing a fetch
---
None

SALTO-2231, SALTO-2241: Add more errors to add exclude suggestions

---

packages/core/src/core/diff.ts
packages/core/src/core/plan/plan_item.ts
packages/core/test/core/diff.test.ts
packages/core/test/core/plan/plan_item.test.ts
packages/workspace/src/workspace/element_selector.ts

Removed an unnecessary element transformation that filters the element by selectors. 
---
Core:
- improved env diff logic when using selectors
Workspace:
- avoid iterating `subElementSelectors` when there are only `topLevelSelectors`
---
None

SALTO-2209: improved env diff logic when using selectors

---

packages/netsuite-adapter/src/client/client.ts
packages/netsuite-adapter/test/client/client.test.ts

fail deploy on SettingsDeployError if on changes matched the failedConfigType list
---
- bugfix: SDF deploy caused an endless loop
---
None

SALTO-2250 fail deploy on SettingsDeployError if on changes matched the failedConfigType list

---

packages/adapter-components/src/config/shared.ts
packages/adapter-components/src/references/context.ts
packages/adapter-components/src/references/field_references.ts
packages/adapter-components/src/references/index.ts
packages/adapter-components/src/references/reference_mapping.ts
packages/adapter-components/test/references/field_references.test.ts
packages/zendesk-support-adapter/src/config.ts
packages/zendesk-support-adapter/src/filters/field_references.ts
packages/zendesk-support-adapter/test/filters/field_references.test.ts

_Create missing references_
---
For @netama to review. She got the full context
---
_Zendesk_support adapter:_
* Add missing references with the structure of `zendesk_support.<typeName>.instance.missing_<internalId>` will be added. When this unresolved reference will be added, it means that there is a broken reference. Go to the service and fix it!
---
_Zendesk_support adapter:_
* Add missing references with the structure of `zendesk_support.<typeName>.instance.missing_<internalId>` will be added.

SALTO-2215: create missing references

---

packages/adapter-utils/src/dependencies.ts
packages/adapter-utils/test/dependencies.test.ts

---
---
Core:
- Fix issue where _generated_dependencies would sometimes get an invalid `occurrences = undefined` value in them
---
_None_

SALTO-2256: Do not return undefined occurrences in generated dependencies

---

packages/zendesk-support-adapter/src/filters/hardcoded_channel.ts
packages/zendesk-support-adapter/src/filters/remove_definition_instances.ts
packages/zendesk-support-adapter/test/adapter.test.ts
packages/zendesk-support-adapter/test/filters/hardcoded_channel.test.ts
packages/zendesk-support-adapter/test/filters/remove_definition_instances.test.ts

_better find channels in trigger definition_
---
In some Zendesk instances that their locale is not english, the title of the relevant condition was not Channel but something in the default language. We are now check for the subject which is consistent
---
_None_
---
_None_

SALTO-2202: better find channels in trigger definition

---

packages/jira-adapter/src/config.ts

Removed redundant fields that were recently added to the NaCls
---
None
---
- Redundant fields that were recently added to the NaCls will be removed

SALTO-2276: Removed new values from permission scheme

---

packages/zendesk-support-adapter/src/client/client.ts
packages/zendesk-support-adapter/test/client/client.test.ts

_Wrong message error on invalid credentials in Zendesk_
---
None
---
_None_
---
_None_

SALTO-2274: wrong message error on invalid credentials in Zendesk

---

packages/adapter-components/src/elements/ducktype/transformer.ts
packages/adapter-components/test/elements/ducktype/transformer.test.ts
packages/zendesk-support-adapter/src/adapter.ts
packages/zendesk-support-adapter/src/client/client.ts
packages/zendesk-support-adapter/test/adapter.test.ts
packages/zendesk-support-adapter/test/client/client.test.ts

_fix zendesk config suggestion bug_
---
We wrote `workspaces` instead of `workspace` to the config. We will now use the reverse mapping of the supported types to get the correct typeName.
For this case, we decided to return empty result if we get 403 on workspaces, because we want similar behavior as we have with other unenabled features
---
_None_
---
_None_

SALTO-2288: fix zendesk config suggestion bug

---

packages/salesforce-adapter/src/config_change.ts
packages/salesforce-adapter/src/constants.ts
packages/salesforce-adapter/src/fetch.ts
packages/salesforce-adapter/src/types.ts
packages/salesforce-adapter/test/adapter.discover.test.ts
packages/salesforce-adapter/test/config_change.test.ts
yarn.lock

This reverts commit 28969cf3d60ae7e368716dd20a1ac974fb9ccc56.
---
None
---
None

Revert "SALTO-2234: Salesforce - Handle LIMIT_EXCEEDED on retrieve (#2989)"

---

packages/workspace/src/serializer/elements.ts
packages/workspace/test/serializer/serializer.test.ts

Changed to save referecens in state and not only their value
---
_Core_:
- Fixed a rare merge error issue of instances with inner referneces
---
None

SALTO-2281: changed to save references in state

---

packages/salesforce-adapter/src/fetch.ts
packages/salesforce-adapter/test/fetch_installed_packages_layout.test.ts

replacing both of those closed PRs: https://github.com/salto-io/salto/pull/2412, https://github.com/salto-io/salto/pull/2999
bug: Layouts of objects of installed packages have a namespace field (e.g "SBQQ" ) in their fileprops. They do not get fetched.
This is because the name we receive from `listMetadataObjects` is not the same name that `readMetadata` expects to get in order to fetch those instances.
The fix was to manipulate the name in the fileprops we receive from `listMetadataObjects` so that it will include the namespace prefix in the beginning of the layout name (and not just in the beginning of the related object's name).
---
Salesforce Adapter: bug fix: Layouts of Installed Packages objects will now be fetched.
--- …

SALTO-1463: Fetch layouts of installed packages

---

packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/change_validators/locked_fields.ts
packages/jira-adapter/test/change_validators/locked_fields.test.ts

Added change validator to prevent deploying locked fields
---
- Added a change validator error when attempting to deploy a locked field
---
None

SALTO-2287: added locked fields validator

---

packages/salesforce-adapter/src/client/client.ts
packages/salesforce-adapter/src/types.ts

Added timeout on requests to Salesforce to avoid stuck fetch operations.
---
Decided to set a reasonable default timeout of 15 minutes after discussing with @ori-moisis. This timeout can be configured like the other RetryOptions in Salesforce's adapter config.
---
- Added timeout on requests to service.
---
_None_ (infra change)

Added timeout to each request retry to Salesforce of 15 minutes

---

packages/adapter-api/src/elements.ts
packages/adapter-api/test/elements.test.ts

Clones of primitive types didn't include paths, fixing that. This could theoretically have caused bugs in all sorts of places but specifically caused an issue for the multiple app connections feature:
https://salto-io.atlassian.net/jira/software/c/projects/SAAS/issues/SAAS-5044?filter=myopenissues
This is because that feature uses the clone functionality on all elements from a fetch.
---
---
---

fix clone to include paths

---

packages/jira-adapter/src/filters/automation/automation_deployment.ts
packages/jira-adapter/src/filters/automation/automation_fetch.ts
packages/jira-adapter/test/filters/automation/automation_deployment.test.ts

Fixed automation creation that recently break due to a change in the service
---
Before the change in the service, the request to create an automations would return all the existing automation (including the new one). Now it returns `null` so we need to query all the automations ourself.
---
- Fixed automation creation that recently break due to a change in the service
---
None

SALTO-2304: fixed creating automations

---

packages/jira-adapter/src/config.ts
packages/jira-adapter/system_config_doc.md

Fixed a bug were only the first 50 projects (first page) were fetched
---
- Fixed a bug were only the first 50 projects were fetched
---
- Additional projects might be fetched in the next fetch

SALTO-2306: fixed to fetch all project pages

---

packages/jira-adapter/src/config.ts
packages/jira-adapter/src/filters/avatars.ts
packages/jira-adapter/test/filters/avatars.test.ts

Remove avatar ids from NaCls because they are not env friendly and make it more difficult cloning between envs
---
- Removed avatar ids from the NaCls in the workspace
---
- Removed avatar ids from the NaCls in the workspace

SALTO-2286: removed avatar ids from nacls

---

packages/zendesk-support-adapter/src/adapter.ts
packages/zendesk-support-adapter/src/filters/remove_definition_instances.ts

_change the order of the remove definition instance filter_
---
None
---
_None_
---
_None_

SALTO-2305: change the order of the remove definition instance filter

---

packages/jira-adapter/src/filters/duplicate_ids.ts

Added log for the values of duplicate instances
I don't think I can use here the `getAndLogCollisionWarnings` because of the custom logic for `fallbackToInternalId`
---
None
---
None

Added log for the values of duplicate instances

---

packages/jira-adapter/e2e_test/instances/field.ts
packages/jira-adapter/e2e_test/instances/index.ts
packages/jira-adapter/src/filters/fields/default_values.ts
packages/jira-adapter/test/filters/fields/default_values.test.ts

fixed creating context with default value
---
- Fixed a bug where a context of an options type field would be created without default values
---
None

SALTO-2298: fixed creating context with default value

---

packages/jira-adapter/src/filters/project.ts
packages/jira-adapter/test/filters/project.test.ts

When a JSM project is created, a fieldConfigurationScheme is created automatically with the name "Jira Service Management Field Configuration Scheme for Project <project key>"". There seems to be a bug in Jira that if a fieldConfigurationScheme with that name already exists, the request fails with 500 although the project is created and another fieldConfigurationScheme with the same name is created (although in the UI you can’t create two fieldConfigurationScheme with the same name). To overcome this, we delete the fieldConfigurationScheme that was automatically created and set the right one
---
- Fixed a bug in JSM project creation
---
None

SALTO-2303: fixed JSM project creation

---

packages/logging/package.json
packages/logging/src/internal/pino.ts
yarn.lock

---
Before this fix, we accepted any pino version above 6.3.2, this includes version 6.6.1 where the time string was fixed in pino ([here](https://github.com/pinojs/pino/issues/905) and [here](https://github.com/pinojs/pino/pull/907)).
this would make our code crash when trying to parse it as if it was a json formatted value.
bumping the version and removing the JSON.parse seems like the easiest fix
bumping to version 7 didn't work out of the box (some unit tests failed), but could probably be done with a bit of effort if we ever need it
---
_None_
---
_None_

SALTO-2311: fix code to work with newer pino versions

---

packages/netsuite-adapter/src/filters/config_features.ts
packages/netsuite-adapter/test/filters/config_features.test.ts

Removing `companyFeatures` type from fetched elements if the `companyFeatures` instance wasn't fetched (like in case of partial fetch) because otherwise the current type in the workspace will be override without the real fields.
---
- `companyFeatures` type bugfix on partial fetch
---
None

SALTO-2257 features type bugfix on partial fetch

---

packages/workspace/src/workspace/hidden_values.ts
packages/workspace/test/workspace/hidden_values.test.ts

---
When using the workspace interface programmatically (e.g. - not from our CLI fetch flow), it is possible to create and apply a nacl change on an element that was not deployed yet.
Currently the code that handles hidden values assumes changes only happen for things that exist in the state.
This fix removes this assumption where it caused a crash and defines the behavior such that if something does not exist in the state, it cannot have anything hidden in it
---
_None_ (the affected scenario would not happen in Salto flows)
---
_None_

SALTO-2314: Handle case when a field change is applied for a field that was not deployed yet

---

packages/zendesk-support-adapter/src/config.ts

_add oauth global client for the default skip list_
---
None
---
_Zendesk support adapter:_
* add oauth global client to the default skip list
---
_None_

SALTO-2219: add oauth global client to the default skip list

---

packages/zendesk-support-adapter/src/config.ts
packages/zendesk-support-adapter/test/adapter.test.ts

_add service url to more types in zendesk_
---
None
---
_Zendesk support adapter:_
* Go to service/Open in app will work on more types
---
_None_

SALTO-2321: add service url to more types in zendesk

---

packages/zendesk-support-adapter/src/client/pagination.ts

_fix Zendesk pathChecker to allow url without a suffix of json_
---
None
---
_Zendesk support adapter:_
* Fix a bug that prevent fetches of accounts with more than 100 webhooks to work
---
_None_

SALTO-2330: fix Zendesk pathChecker to allow url without a suffix of json

---

packages/adapter-components/src/client/http_client.ts
packages/jira-adapter/src/filters/workflow/step_ids_filter.ts
packages/jira-adapter/src/filters/workflow/triggers_filter.ts
packages/jira-adapter/test/filters/workflow/step_ids_filter.test.ts
packages/jira-adapter/test/filters/workflow/triggers_filter.test.ts

Changed omit a specific workflow when one of its requests failed instead of failing the whole fetch, and fixed some of the logs to get more information the next time it will fail.
---
None
---
None

SALTO-2331: changed to not fail when getting 400 from workflows requests

---

packages/core/src/local-workspace/remote_map.ts
packages/core/test/workspace/local/remote_map.test.ts
packages/core/test/workspace/local/remote_map_connection.test.ts

_clean temporary databases on init_
---
_The remote map should clean the temporary databases when closed. If a Salto invocation fails to close the connection (sig kill etc.), the temporary databases will remain in place. The remote map implementation will close all dangling temporary databases on startup to avoid stall data accumulation. _
---
_Fix excessive disk space usage due to stale cache not being clean._
---
_NA_

(Salto-1376) clean tmp dbs on init

---

packages/netsuite-adapter/src/client/manifest_utils.ts
packages/netsuite-adapter/test/client/manifest_utils.test.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts

add dependencies tag to manifest.xml if missing
---
- add dependencies tag to manifest.xml if missing
---
none

Salto 2254 add dependencies tag to manifest.xml if missing

---

packages/jira-adapter/config_doc.md
packages/jira-adapter/src/change_validators/masking.ts
packages/jira-adapter/src/config.ts
packages/jira-adapter/src/filters/masking.ts
packages/jira-adapter/test/change_validators/masking.test.ts
packages/jira-adapter/test/filters/masking.test.ts

Added `masking.secretRegexps` configuration option to mask strings that match a given regex all over the workspace.
The names and messages are not final, will discuss @liorn before merging
---
- Added `masking.secretRegexps` configuration option to mask strings that match a given regex all over the workspace
---
None

SALTO-2295: added masking.secretMatchers

---

packages/cli/test/mocks.ts
packages/core/src/core/fetch.ts
packages/core/test/common/workspace.ts
packages/core/test/core/fetch.test.ts
packages/workspace/salto.log
packages/workspace/src/workspace/workspace.ts
packages/workspace/test/workspace/workspace.test.ts

Before this Fetch From Workspace, when being used with the fromState flag, did not fetch the actual content of Static Files that are part of the changes fetched. This is cause the content is not available in the state.
This uses the sourceWorkspace’s staticFileSource as the source and to make sure the hashes match (+ remove the change and add an error if it doesn’t).
This also adds a new function to workspace, `getStaticFile` that is being used here.
---
Context for the reviewer - 
* This should definitely be deleted when we complete the Static Files redesign
* The new workspace function - `getStaticFile`, I am not sure about the interface to be honest. I am not sure it's super aligned with the whole api cause it always requires env, and the encoding has no default so it's a bit explicit …

SaaS-2339 Fetch From Workspace fromState static files fix

---

packages/jira-adapter/e2e_test/instances/index.ts
packages/jira-adapter/src/config.ts
packages/jira-adapter/src/filters/fields/field_name_filter.ts
packages/jira-adapter/test/filters/fields/field_name_filter.test.ts

Added option to add the field type to its Salto ID
---
- Added option to add the field type to its Salto ID
---
None

SALTO-2319: On Jira Field instances, add `type` to the salto id to avoid duplicates

---

packages/adapter-utils/src/utils.ts
packages/adapter-utils/test/utils.test.ts
packages/salesforce-adapter/src/adapter.ts
packages/zendesk-support-adapter/src/adapter.ts

The "before" part of changes cannot really change, so we can use the original change for that value
This solves an issue where in modification changes we would try to restore the "before" value with
the "after" value from the original change
---
This solves a more basic cause for the issue of SAAS-4962 where we'd perform a lot of unnecessary calculations.
The previous fix is still valid, but this takes away the problematic scenario earlier in the flow and saves even more operations
---
_None_ (any noticeable effects of this issue should have been handled in the previous fix)
---
_None_

SAAS-4962: Quick restore of "before" changes in restoreValues

---

packages/workspace/src/workspace/nacl_files/nacl_file_update.ts
packages/workspace/test/workspace/workspace.test.ts

Changed the implementation of building the new content of a nacl file to perform less string manipulations
This increases performance in cases where we have multiple changes in the same file
Also, performing less manipulations on the entire file content means there is less stress on the garbage collector.
in some scenarios this may help us consume less memory overall.
---
---
Core:
- Improve performance of updating nacl files
---
_None_

SAAS-5129: Improve performance of update nacl file with many changes

---

packages/adapter-components/src/elements/swagger/deployment/annotations.ts
packages/adapter-components/src/references/field_references.ts
packages/adapter-components/test/elements/swagger/deployment/annotations.test.ts
packages/adapter-components/test/references/field_references.test.ts
packages/jira-adapter/e2e_test/instances/index.ts
packages/jira-adapter/e2e_test/instances/securityScheme.ts
packages/jira-adapter/src/config.ts
packages/jira-adapter/src/filters/workflow/conditions_types.ts
packages/jira-adapter/src/reference_mapping.ts

Added support for fetching and deploying groups
---
- Added support for managing user groups
---
- Group instances will be added to the workspace after the next fetch

SALTO-1936: Fetch and deploy groups

---

packages/zendesk-support-adapter/src/adapter.ts
packages/zendesk-support-adapter/src/change_validators/duplicate_option_values.ts
packages/zendesk-support-adapter/src/change_validators/index.ts
packages/zendesk-support-adapter/src/dependency_changers/custom_field_option_change.ts
packages/zendesk-support-adapter/src/dependency_changers/index.ts
packages/zendesk-support-adapter/test/dependency_changers/custom_field_option_change.test.ts

Add dependency changer to order changes in zendesk's `custom_field_options` values
---
In Zendesk, `custom_field_options` of the same type (organization, user or ticket) cannot have the same value.
The same applies to `tag` in the organization/user/ticket from type `checkbox`.
We want to allow changes of 2 values in the following way: value_1: a->b , value_2: b->c, and therefore we added a dependency changer to make sure the deploy happens in the right order (value_2 -> value_1).
---
None
---
None

SALTO-1989: Add dependency changer to modification of values in Zendesk's custom fields 

---

packages/core/src/local-workspace/static_files_cache.ts
packages/core/test/workspace/local/static_files_cache.test.ts
packages/core/test/workspace/local/workspace.test.ts
packages/lang-server/test/workspace.ts
packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
packages/workspace/src/workspace/nacl_files/parsed_nacl_file.ts
packages/workspace/src/workspace/nacl_files/parsed_nacl_files_cache.ts
packages/workspace/src/workspace/static_files/cache.ts
packages/workspace/src/workspace/static_files/common.ts
packages/workspace/src/workspace/static_files/index.ts
packages/workspace/src/workspace/static_files/source.ts
packages/workspace/test/common/nacl_file_source.ts
packages/workspace/test/common/nacl_file_store.ts
packages/workspace/test/utils.ts
packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
packages/workspace/test/workspace/static_files/source.test.ts

---
Continuing the chain of reverts to bring back @roironn's original implementation, this time making the interface change less breaking.
@alonstern - the revert is mostly unchanged (only fixing a conflict in the exports of the static files module), my changes are in the second commit
---
Core:
- Fixed issue where errors relating to static files would not be updated properly
---
_None_

SALTO-2232: Revert "Revert "Salto 2232 fix changes in static files are not detected (#3054)" (#3070)"

---

packages/jira-adapter/src/client/client.ts
packages/jira-adapter/src/filters/workflow/workflow_modification_filter.ts

Reduced deploy concurrency in Jira because I saw we sometimes get 500 when deploying many objects in parallel
Also added `?` to fix an error message
---
- Reduced default deploy concurrency
---
None

Reduced deploy concurrency in Jira

---

packages/jira-adapter/src/filters/workflow/workflow_modification_filter.ts
packages/jira-adapter/test/filters/workflow/workflow_modification_filter.test.ts

Fixed deployment of a modification of a workflow and an addition of a workflow scheme that uses that workflow
---
The issue was that when modifying a workflow, we first change the references of the workflow scheme that uses it, and if the workflow scheme is an addition then it was not created yet and does not have an id so we would fail when trying to change it.
---
- Fixed bug in updating workflows
---
None

SALTO-2363: fixed deploying workflow and workflow scheme in one deployment

---

.circleci/build-images/e2e-test/Dockerfile
.circleci/config.yml

---
Missed these in #2885 
---
_None_
---
_None_

Remove usage of deprecated circleci docker images

---

packages/adapter-api/src/values.ts
packages/adapter-utils/src/utils.ts
packages/core/src/local-workspace/dir_store.ts
packages/core/test/common/workspace.ts
packages/core/test/core/fetch.test.ts
packages/core/test/workspace/local/directory_store.test.ts
packages/lang-server/test/workspace.ts
packages/netsuite-adapter/e2e_test/adapter.test.ts
packages/netsuite-adapter/src/change_validators/file_changes.ts
packages/netsuite-adapter/src/group_changes.ts
packages/netsuite-adapter/src/suiteapp_file_cabinet.ts
packages/netsuite-adapter/test/suiteapp_file_cabinet.test.ts
packages/salesforce-adapter/e2e_test/adapter.test.ts
packages/salesforce-adapter/src/filters/static_resource_file_ext.ts
packages/salesforce-adapter/test/adapter.discover.test.ts
packages/salesforce-adapter/test/filters/cpq/custom_script.test.ts
packages/salesforce-adapter/test/filters/static_resource_file_ext.test.ts
packages/salesforce-adapter/test/transformers/xml_transformer.test.ts
packages/workspace/src/workspace/dir_store.ts
packages/workspace/src/workspace/static_files/source.ts
packages/workspace/test/serializer/serializer.test.ts
packages/workspace/test/utils.ts
packages/workspace/test/workspace/static_files/source.test.ts
packages/workspace/test/workspace/workspace.test.ts
packages/zendesk-support-adapter/src/filters/macro_attachments.ts

Removed the sync `content` property from `StaticFile` and removed `getSync` from dirStore.
This is for the static files refactor task.
I will also open a PR in the SaaS for this
---
None
---
None

SALTO-2352: Remove sync content from Static files

---

packages/workspace/src/parser/internal/native/lexer.ts
packages/workspace/test/parser/parse.test.ts

Fix an issue where templates wouldn't be parsed for ids that include "@"
---
This hasn't been an issue in the past because we had no usage of templates. But it's now required for zendesk
---
None
---
None

fix an issue where templates wouldn't parse for ids that include '@'

---

packages/adapter-components/src/elements/constants.ts
packages/adapter-components/src/elements/index.ts
packages/adapter-components/src/elements/instance_elements.ts
packages/adapter-components/test/elements/swagger/instance_elements.test.ts
packages/zendesk-support-adapter/src/filters/reorder/creator.ts
packages/zendesk-support-adapter/src/filters/reorder/trigger.ts

Change path hints for settings instances to be under a `Settings` folder.
This impacts:
1. Jira settings instances
2. Zendesk settings instances, including `x_order` instances
3. Zuora settings instances
4. Workato settings instances
---
* New Settings instances will be created under a `Records/Settings` folder
* New Settings instances will be created under a `Records/Settings` folder
_Zuora-billing adapter_:
* New Settings instances will be created under a `Records/Settings` folder
_Workato adapter_:
* New Settings instances will be created under a `Records/Settings` folder
---
None (existing elements are not impacted)

SALTO-2366 SALTO-2367 settings path

---

yarn.lock

---
version 5.0.0 has a [security alert](https://github.com/salto-io/salto/security/dependabot/30) and we don't actually need it in our yarn.lock since all our dependencies can use 5.0.1 instead
---
_None_
---
_None_

SALTO-2167: remove unneeded version of ansi-regex

---

packages/salesforce-adapter/e2e_test/adapter.test.ts
packages/salesforce-adapter/src/filters/custom_objects.ts
packages/salesforce-adapter/test/filters/custom_objects.test.ts

This is for consistency in the file tree
---
---
- Moved custom object child instances to consistently be inside a folder
---
_None_

SALTO-2360: Move custom object nested instances to folders

---

packages/netsuite-adapter/src/transformer.ts
packages/netsuite-adapter/test/transformer.test.ts

SALTO-2365: Change path-hint of folder instances to sit inside their own folder

SALTO-2365: Change path-hint of folder instances to sit inside their own folder

---

packages/salesforce-adapter/config_doc.md
packages/salesforce-adapter/src/adapter.ts
packages/salesforce-adapter/src/constants.ts
packages/salesforce-adapter/src/fetch_profile/metadata_query.ts
packages/salesforce-adapter/src/filter.ts
packages/salesforce-adapter/src/filters/custom_object_split.ts
packages/salesforce-adapter/src/types.ts
packages/salesforce-adapter/test/config_change.test.ts
packages/salesforce-adapter/test/fetch_profile/metadata_query.test.ts
packages/salesforce-adapter/test/filters/custom_object_split.test.ts
packages/workspace/src/validator.ts
packages/workspace/test/validator.test.ts

Add a configuration option to specify a short list of types which will be split to a file per field (instead of 
the usual 2 files: one for custom fields and one for standard fields). 
This will make committing changes easier when done per file.
---
None
---
Salesforce - Add a configuration to split specific type nacls to one file per field
---
None

SALTO-2358: Salesforce - split specific types to a file per field

---

packages/jira-adapter/src/config.ts

Fixed to fetch all groups pages 🤦‍♂️  
---
- Fixed a bug where only the first page (50) of groups was fetched
---
- Missing groups will be fetched on the next fetch

SALTO-2382: Fixed to fetch all groups pages

---

packages/zuora-billing-adapter/src/config.ts
packages/zuora-billing-adapter/src/filters/field_references.ts
packages/zuora-billing-adapter/system_config_doc.md

See the ticket for full details.
* Omit/hide additional fields that are less relevant to follow in nacls
* Add a few missing references
* Define some fields that are not yet defined in the swagger / settings schemas, so that they are not nested under `additionalProperties`
---
_Zuora-billing Adapter_:
* Add missing references from public notification definitions to email templates and communication profiles
* Remove a few fields that are adding noise and less relevant for tracking purposes
---
* Structural changes will cause noise under `AccountingPeriod`, `PublicEmailTemplate`, `PublicNotificationDefinition`, `Settings_Notification`, `Settings_RuleDetail`, `Settings_Attribute`, `DetailedWorkflow`, `EventTrigger`, `PaymentTerm`, …

SALTO-2328 Zuora config improvements

---

packages/workspace/src/workspace/reference_indexes.ts
packages/workspace/test/workspace/reference_indexes.test.ts

Part of adding support for template content in zendesk fields. This handles adding the references inside templates to the reference index
---
---
None
---
None

SALTO-2267 handle templates in reference index

---

packages/core/src/local-workspace/adapters_config.ts
packages/core/src/local-workspace/remote_map.ts
packages/core/src/local-workspace/static_files_cache.ts
packages/core/src/local-workspace/workspace.ts
packages/core/test/workspace/local/remote_map_connection.test.ts
packages/core/test/workspace/local/static_files_cache.test.ts

Move static files cache to RocksDB, so it will also exist in the operation repo.
---
This PR also tries to fix some races when opening the RocksDB connection 
---
None
---
None

SAAS-4004: Move static files cache to RocksDB 

---

packages/workspace/src/workspace/reference_indexes.ts

Because of the need to add references to TemplateExpression to existing workspaces, we need to increase the version
of ReferenceIndex to make workspaces recalculate their reference index
---
See ticket
---
None (not officially released feature)
---

SALTO-2267 increase reference index to handle new template expressions

---

eslintrc.js
packages/core/src/local-workspace/remote_map.ts
packages/core/src/local-workspace/static_files_cache.ts
packages/core/test/workspace/local/static_files_cache.test.ts
packages/salesforce-adapter/src/change_validators/picklist_promote.ts
packages/salesforce-adapter/src/filters/profile_permissions.ts
packages/salesforce-adapter/src/filters/replace_instance_field_values.ts
packages/workspace/src/parser/dump.ts
packages/workspace/src/parser/functions.ts

Fix a bug where we always assumes the cache was empty (and thus did the migration and deleted the old cache)
Added the relevant lint rule + fixed small similar bugs   
---
None
---
None
---
None

SAAS-4004: Fix issues in static file cache migration

---

packages/core/index.ts
packages/core/src/local-workspace/workspace.ts

Remove unused export, the references to it were deleted from the SAAS 
---
None
---
None
---
None

SALTO-2419: Remove unused export getNaclFilesSourceParams

---

docs/syntax.md
packages/adapter-api/src/builtins.ts
packages/workspace/src/serializer/elements.ts
packages/workspace/src/validator.ts
packages/workspace/test/validator.test.ts

Having only one restriction for both means that the length restriction applies both to the list length and the string length in case we have a list of strings. 
Also added documentation for the list length restriction. 
---
None
---
Core - Added ability to restrict list sizes for specific fields.
---
None

SALTO-2414: Differentiate between string length and list length restrictions

---

packages/salesforce-adapter/src/transformers/transformer.ts
packages/salesforce-adapter/test/transformers/transformer.test.ts

While both the UI and API of salesforce prevent invalid names from being set on fields.
in real life, of course we encountered a case where a field name had a "%" in it...
since naclCase should not have any effect on an valid field name, applying it should do nothing
in all valid cases, and it will fix the invalid strange case...
---
---
- Fix failure on fetch when salesforce field has an invalid character in its api name (a case that should never happen)
---
_None_

SALTO-2425: Apply naclCase of field names in salesforce

---

packages/workspace/src/serializer/elements.ts
packages/workspace/src/validator.ts
packages/workspace/src/workspace/nacl_files/index.ts
packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
packages/workspace/src/workspace/static_files/common.ts
packages/workspace/test/common/nacl_file_store.ts
packages/workspace/test/serializer/serializer.test.ts
packages/workspace/test/validator.test.ts
packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts

- Fix static file index in naclFileSource to include missing static file references as well
- Fix serialization of MissingStaticFile and AccessDeniedStaticFile in elements
- Force parsing of files that are affected by static files changes even if the nacl file itself hasn't changed
---
This should fix the error when a missing static file is created
It does not fix the issue where a static file is deleted - this would still not create a salto error and requires a separate fix
---
Core:
- Fixed issue where missing static file errors would not go away even after the missing static file was created
---
_None_

SALTO-2232: Fix detection of missing static file errors

---

packages/jira-adapter/src/filters/board/board_columns.ts
packages/jira-adapter/test/filters/board/board_columns.test.ts

It looks like in rare cases fetching board returns a duplicated backlog column at the beginning of the columns which fails the Jira e2e
---
None
---
None

SALTO-2213: Fixed duplicated backlog column in fetch

---

packages/jira-adapter/src/filters/jql/jql_references.ts
packages/jira-adapter/src/filters/jql/types.ts
packages/jira-adapter/test/filters/jql/jql_references.test.ts

- Failures in parsing JQLs for references will now not fail the entire fetch
- Parsing the response to log the specific failed jqls and omit only them
---
- Failures in parsing JQLs for references will now not fail the entire fetch
---
None

INCIDENT-494: changed jql parsing errors to not fail fetch

---

packages/jira-adapter/src/filters/board/board_columns.ts
packages/jira-adapter/test/filters/board/board_columns.test.ts
packages/jira-adapter/test/filters/board/board_deployment.test.ts

Accidently write `columnsConfig` instead of `columnConfig` in some places 🤦‍♂️
---
None (no effect on the user)
---
None

SALTO-2213: Fixed columnConfig name

---

packages/zendesk-support-adapter/src/filters/handle_template_expressions.ts
packages/zendesk-support-adapter/test/filters/handle_template_expressions.test.ts

For the zendesk_support adapter - add support for more fields that can contain template values
---
---
Placeholders that reference other zendesk elements will be parsed as references rather than kept as-is.
---
Placeholders that reference other zendesk elements will be parsed as references rather than kept as-is.
This affects: Triggers, macros, automations, webhooks.
e.g:
{{ticket.ticket_field_#NUMBER}} => {{ ${ zendesk_support.ticket_field.instance.THE_RELEVANT_INSTANCE }}}

SALTO-2267 add support for more template values

---

packages/cli/webpack.config.js

Cleanup old webpack workaround that is no longer relevant after the requestretry version bump.
Will merge after https://github.com/salto-io/salto/pull/3138 to separate the vulnerability fix from the cleanup in case there is any regression in webpack (please review only the 2nd commit here).
---
None
---
None

SALTO-2437 remove webpack workaround for old requestretry library

---

packages/jira-adapter/src/filters/jql/types.ts
packages/jira-adapter/test/filters/jql/jql_references.test.ts

Fixed scheme to work with empty queries (which are valid queries)
---
- Fixed JQL references when there are empty JQLs
---
None

SALTO-2438: Invalid query response when parsing JQLs

---

packages/cli/package.json
packages/vscode/package.json
yarn.lock

Bump vsce to resolve vulnerabilities in markdown-it.
Note that the vsce version bump requires node version 14 and up.
---
None
---
None

SALTO-2440 bump nexe and vsce versions

---

packages/core/src/core/plan/change_validators/unresolved_references.ts
packages/core/test/core/plan/change_validators/unresolved_references.test.ts

_SALTO-2452: Allow removal of elements with unresolved elements_
---
Currently, we are preventing any kind of change on elements if they contain unresolved references.
There is no need to do it on removal changes since we do not update the element, we just remove it
---
_None_
---
_None_

SALTO-2452: Allow remove elements with unresolved elements

---

packages/adapter-components/src/elements/soap/type_elements/types_generator.ts

To solve the error of `The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of WSDL` 
---
---
None
---
None

SALTO-2451: Reverse create soap client condition

---

packages/adapter-utils/src/utils.ts
packages/adapter-utils/test/utils.test.ts

When running `transformValues({ values: [<some array>] ... })`,
the result is map and not an array as expected: `{ "0": {...}, "1": {...} }`
---
Adapter Utils:
- handle list value in `transformValues`
---
None

SALTO-2459 handle list value in transformValues

---

packages/core/src/local-workspace/state.ts
packages/core/test/common/helpers.ts
packages/core/test/workspace/local/state.test.ts
packages/workspace/src/workspace/state/in_mem.ts
packages/workspace/src/workspace/workspace.ts

Before this change, when the state cache did not match the state file we would not
mark the state cache as dirty and therefore we whould not update the cache.
this meant that until we ran a command that really updated the state file, we were
doomed to parse the state file over and over again
---
---
Core:
- Improved loadWorkspace performance when external changes are made to the state file (e.g switching git branch)
---
_None_

SAAS-5457: Update state cache when it is not synced

---

package.json
yarn.lock

Needed to get rid of the dependency of a vulnerable version of the parse-url package
---
---
_None_
---
_None_

SALTO-2471: Bump lerna version

---

packages/workspace/src/serializer/elements.ts
packages/workspace/test/serializer/serializer.test.ts

The static files refactor PR caused the full path of static files to be saved in the state which made the state different when it is flushed in different locations (can affect the SaaS operation repo where we copy the workspace to another location in the disk)
---
None (the static files refactor feature is behind ff in the SaaS and we didn't release OSS version yet)
---
None

SALTO-2352: Fixed state inconsistency

---

packages/workspace/src/workspace/changed_at_index.ts
packages/workspace/src/workspace/changed_by_index.ts
packages/workspace/test/workspace/changed_at_index.test.ts
packages/workspace/test/workspace/changed_by_index.test.ts
packages/workspace/test/workspace/workspace.test.ts

after finding a way to retrieve the nacl file paths of field elements (in saas) I changed the code to add the field's element id and not his top level parent.
---
---
---

SALTO-2458/add field support for indexs

---

packages/zendesk-support-adapter/src/filters/dynamic_content_references.ts
packages/zendesk-support-adapter/test/adapter.test.ts
packages/zendesk-support-adapter/test/filters/dynamic_content_references.test.ts

Formerly references to dynamic content were represented only through generated dependencies, but now they will instead be converted to TemplateExpressions
---
part of a bigger task to represent values in zendesk as TemplateExpression
---
Support references to dynamic content instead of generated dependencies
---
In Zendesk application, fields that begin in "raw_" and contain dynamic content references will now not have generated dependencies, and instead the field values will contain references to the element representing the dynamic content.

SALTO-2267 dynamic content references will be created as TemplateExpressions

---

packages/workspace/src/element_adapter_rename.ts
packages/workspace/test/workspace/element_adapter_rename.test.ts

_fix adapter rename to rename TemplateExpressions as well_
---
None
---
_None_
---
_None_

SALTO-2474: fix adapter rename to rename TemplateExpressions as well

---

packages/jira-adapter/src/dependency_changers/global_field_contexts.ts
packages/jira-adapter/src/dependency_changers/index.ts
packages/jira-adapter/src/dependency_changers/removals.ts
packages/jira-adapter/test/dependency_changers/global_field_contexts.test.ts
packages/jira-adapter/test/dependency_changers/removals.test.ts

Fixed a bug with replacing the global context of a field in one deployment.
There can be only one global context (a context without `projectIds` or without `issueTypeIds`) per field, so before if we would try to replace a global context with another, we would first try to add the new one with would fail because we first need to delete the old one
---
- Fixed a bug with replacing the global context of a field in one deployment
---
None

SALTO-2476: Replacing global context of a field with another one failed

---

packages/zendesk-support-adapter/src/filters/app.ts
packages/zendesk-support-adapter/test/filters/app.test.ts

App installation will no longer include unnecessary "settings_object" attribute, which is a duplicate of "settings" attribute
---
---
Zendesk:
App installation will no longer include unnecessary "settings_object" attribute, which is a duplicate of "settings" attribute
---
Zendesk: 
Future fetches of zendesk will no longer include unnecessary "settings_object" attribute, which is a duplicate of "settings" attribute. Current workspaces will continue to work with no need to change.

SALTO-2114 app installation will lose the "settings_object" item

---

package.json
yarn.lock

Needed to fix security alert on parse-path
---
---
_None_
---
_None_

SALTO-2484: Bump lerna version to 5.1.8

---

packages/salesforce-adapter/src/fetch_profile/metadata_query.ts
packages/salesforce-adapter/test/fetch_profile/metadata_query.test.ts

---
_Salesforce_:
* Added logic that fetches the InstalledPackage records even if the config specifies only fetching standard namespace Records of other metadataTypes cause they are system-wide Records and not really part of the namespace
---
_Salesforce_:
* InstalledPackage Records will be added to existing Workspaces on the next fetch

SALTO-2463 - Fetch InstalledPackage Records regardless of namespace config

---

packages/workspace/src/element_adapter_rename.ts
packages/workspace/test/workspace/element_adapter_rename.test.ts

_Fix adapter renaming to work on static files_
---
---
_None_
---
_None_

SALTO-2487: fix adapter renaming to work on static files

---

packages/workspace/src/element_adapter_rename.ts
packages/workspace/test/workspace/element_adapter_rename.test.ts

_Add tests to adapter renaming to work on static files_
---
Based on [this](https://github.com/salto-io/salto/pull/3191/files#r924760691) comment
---
_None_
---
_None_

SALTO-2487: add tests to adapter renaming to work on static files

---

packages/logging/src/internal/log-tags.ts
packages/logging/test/internal/pino_logger.test.ts

Support `string[]` in LogTags
---
Ticket in [here](https://salto-io.atlassian.net/browse/SALTO-2493)
Some local tests:
The log line:
On Json format:
On Text format:
---
-
---
-

SALTO-2493 - List of strings supported in LogTags

---

packages/cli/src/commands/common/accounts.ts
packages/cli/test/commands/commons.test.ts

_Improve CLI error message_
---
None
---
CLI:
* Improve CLI error message when specifying a non existing account name in deploy / fetch commands
---
None

SALTO-2405: Improve CLI error message 

---

packages/netsuite-adapter/src/config.ts

_Remove "account" instances from NS default fetch config_
---
None
---
_Netsuite Adapter_
* "account" instances are not fetched by default
---
None

SALTO-2396: Remove "account" instances from NS default fetch config

---

packages/zendesk-adapter/src/change_validators/order.ts
packages/zendesk-adapter/src/change_validators/trigger_order.ts
packages/zendesk-adapter/src/filters/reorder/creator.ts
packages/zendesk-adapter/src/filters/reorder/trigger.ts
packages/zendesk-adapter/test/change_validators/trigger_order.test.ts
packages/zendesk-adapter/test/filters/reorder/trigger.test.ts

_add safeties to the order instances deploy filters and change validators_
---
Due to another bug that now omits fields with empty values from nacl, we need to add more safeties to make sure we are ok if the order instance' fields are removed
---
_None_
---
_None_

SALTO-2510: add safeties to the order instances deploy filters and change validators

---

packages/zendesk-adapter/src/filters/dynamic_content_references.ts
packages/zendesk-adapter/test/filters/dynamic_content_references.test.ts

_fix zendesk fetch to stop omitting fields with empty list_
---
Zendesk fetches and deploys removed fields from instances if their values was empty list.
---
_None_
---
_None_

SALTO-2508: fix zendesk fetch to stop omitting fields with empty list

---

packages/workspace/src/workspace/nacl_files/nacl_files_source.ts

---
_Bug Fixes_:
_Core_:
* Fixed an issue in the workspace that would crash if there is a big amount of references in a single file, while building the referencesIndex
---
* None

SALTO-2517 - Fix destruction issue in building the referenced index for big # of references in a single file

---

packages/adapter-api/src/element_id.ts
packages/adapter-api/test/elements.test.ts

_fix getRelativePath to work on fields, attrs and annotations_
---
None
---
_None_
---
_None_

SALTO-2495: fix getRelativePath to work on fields, attrs and annotations

---

packages/zendesk-adapter/index.ts
packages/zendesk-adapter/src/client/connection.ts

_export zendesk salto app marketplace headers_
---
We need to send this header in the auth process to zendesk in the SaaS, and therefore, we need to extract those headers
---
_None_
---
_None_

SALTO-2522: export zendesk salto app marketplace headers

---

packages/salesforce-adapter/src/transformers/reference_mapping.ts

_Extract references from a filterItems to recordType_
---
None
---
* Add reference from the value field to recordType in value field from FilterItems_
---
* When creating a workFlow Rule with recordType as criteria, the value field of the criteria will be properly parsed as references off RecordType instance, showing up as ReferenceExpression in nacl

Salto-2470:  Extract references from a filterItems to recordType

---

packages/salesforce-adapter/src/constants.ts
packages/salesforce-adapter/src/filters/field_references.ts
packages/salesforce-adapter/src/transformers/reference_mapping.ts
packages/salesforce-adapter/test/filters/field_references.test.ts

_Extract share to references from ReportFolder_
---
None
---
* Extract references from shrareTo types in Report Folders
---
* ShraredTo field will be properly parsed as references from ReportFolder, showing up as ReferenceExpression in nacl

Salto-2443: Extract share to references from ReportFolder

---

packages/salesforce-adapter/src/transformers/reference_mapping.ts

_Extract references from Salesforce Sharing Rules_
---
None
---
* Extract references from shraredTo and FilterItems types in Sharing Rules
---
* ShraredTo and FilterItems field will be properly parsed as references from Sharing Rules, showing up as ReferenceExpression in nacl

Salto-2410: Extract references from Salesforce Sharing Rules

---

packages/salesforce-adapter/src/transformers/reference_mapping.ts

_Add reference to compactLayout from recordType_
---
None
---
* Add reference to compactLayout from recordType
---
* compactLayoutAssignment field will be properly parsed as references from RecordType, showing up as ReferenceExpression in nacl

SALTO-2521: Add reference to compactLayout from recordType

---

packages/cli/src/formatter.ts
packages/cli/src/workspace/workspace.ts
packages/cli/test/formatter.test.ts

Fixed lacking of space in CLI error messages 
---
---
_CLI_:
In certain error messages (for instance failure to deploy when operation is not supported) a space was added between the header and the main message.
---
None

SALTO-2253: Fixed lacking of space in CLI error messages 

---

packages/adapter-components/src/elements/type_elements.ts

Changing the "could not find type %s, falling back to unknown" log's severity level from error to warning 
---
---
* "unknown type" logs will become warnings.

SALTO-2481-change-severity-to-finding-unknown-type

---

packages/salesforce-adapter/src/client/client.ts
packages/salesforce-adapter/test/client.test.ts

_Change salesforce adapter config default timeout_
---
* after consultation with Tamir, changing configuration shouldn't break any tests, so I only changed the tests that rely on the fact that we retry 5 times.
---
* by lowering the number of time we attempt to do a retry from 5 to 3 and the duration of each try ,we might make the adapter more stable
---
None

SALTO-2478 Change salesforce adapter config default timeout

---

packages/cli/test/mocks.ts
packages/workspace/src/workspace/workspace.ts
packages/workspace/test/workspace/workspace.test.ts

add method to determine size of changed at index.
---
---
---

SALTO-2553/add get changed at index size

---

packages/workspace/src/expressions.ts
packages/workspace/test/core/expressions.test.ts

When resolving references we would not resolve the field's parent type.
this was done as a small performance improvement but now we have a case where
we actually need the field's parent resolved in an adapter.
---
The netsuite adapter will soon require that the field's parent is resolved when deploying `customrecordtype`s
---
_None_
---
_None_

SALTO-820: Resolve field parent when resolving references

---

packages/jira-adapter/e2e_test/instances/index.ts
packages/jira-adapter/e2e_test/instances/status.ts
packages/jira-adapter/src/change_validators/status.ts
packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/filters/statuses/status_deployment.ts
packages/jira-adapter/src/group_change.ts
packages/jira-adapter/test/change_validators/status.test.ts
packages/jira-adapter/test/filters/statuses/status_deployment.test.ts
packages/jira-adapter/test/group_change.test.ts

Change Jira status deployment to the new statuses API
---
Jira created a new API for statuses, we replaces the old deployment of statuses with the new API.
Modification and addition of statuses is done through the client directly, so we can deploy multiple statuses together.
---
None
---
None

SALTO-2302 Change Jira status deployment to the new statuses API

---

packages/cli/src/formatter.ts
packages/cli/test/formatter.test.ts

Added elements IDs list when change validator returns an error.
In addition added the detailed message for each element ID in case the deploy was performed in detailed version (-p)
---
---
CLI:
When a deploy skips several elements with the same error message the elements ID are listed
When such a deploy is performed in "detailed-plan" mode (-p) for each skipped element a detailed message will be added
---
Nnoe

SALTO-1519: Print skipped elements IDs on deploy

---

packages/zendesk-adapter/src/filters/remove_definition_instances.ts

_remove the SALTO-2305 debugging logs_
---
We added those logs back then to debug the bug that is described in the ticket. We solve the bug and I believe that we don't need those logs anymore
---
_None_
---
_None_

SALTO-2305: remove the SALTO-2305 debugging logs

---

packages/salesforce-adapter/src/client/client.ts

_Retry after SERVER_UNAVAILABLE error - upon salesforce fetch_
---
None
---
* automatically retry fetch with sf: SERVER_UNAVAILABLE error
---
None

SALTO-2527 SALTO-2386 Retry after SERVER_UNAVAILABLE error - upon salesforce fetch

---

packages/zendesk-adapter/src/change_validators/duplicate_option_values.ts
packages/zendesk-adapter/test/change_validators/duplicate_option_values.test.ts

_Ignore empty tag in ticket field checkboxes in the change validators_
---
Fixes a bug that returned a change validator error if you added a checkbox with empty tag and one already existed in your account. It started to happen because zendesk changed the value of empty tag from empty string to null
---
_Zendesk Adapter_
* Fixed a bug that created a change validator error if you added a checkbox with empty tag when there was already an existent checkbox with empty tag
---
_None_

SALTO-2551: Ignore empty tag in ticket field checkboxes

---

packages/zendesk-adapter/src/filters/field_references.ts
packages/zendesk-adapter/src/filters/tag.ts
packages/zendesk-adapter/test/adapter.test.ts
packages/zendesk-adapter/test/filters/tag.test.ts

_Extract tags values to references in checkbox fields_
---
There is already a noise reduction code for it
---
_Zendesk Adapter_
* Change tag in checkbox fields to reference instead of strings
---
_Zendesk Adapter_
* tags in checkbox fields will turn into references

SALTO-2551: extract tags values to references in checkbox fields

---

packages/salesforce-adapter/src/client/client.ts

_Retry after 'System may be currently unavailable' and 'Unexpected internal servlet state' errors - upon salesforce fetch_
---
None
---
* automatically retry fetch after 'System may be currently unavailable' and 'Unexpected internal servlet state' errors 
---
None

SALTO-2457 SALTO-2431 Retry after errors - upon salesforce fetch

---

packages/jira-adapter/src/filters/fields/context_options.ts
packages/jira-adapter/test/filters/fields/context_options.test.ts

Fixed a bug when deploying a field with its context in the same deployment
---
The issue was that `.getResolvedValue(elementsSource)` uses the elements source even if the reference is resolved and in the element source we don't eve the field internal id if it was just created in the same deployment
---
Fixed a recent regression in deploying a new field with its contexts in the same deployment
---
None

SALTO-2579: Cryptic error when trying to deploy a CustomFieldContext instance

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/filters/field_configuration/missing_field_descriptions.ts
packages/jira-adapter/test/filters/field_configuration/missing_field_descriptions.test.ts

In the UI, if the field config item description is empty, it shows the field description. This PR to do the same with the NaCl and replace the empty description with the field description
---
- Fixed field config items' description to use the field description when empty
---
- Some field config item's description might change to the correct value after the next fetch

SALTO-2581: Fixed field configuration descriptions

---

packages/zendesk-adapter/src/filters/field_references.ts
packages/zendesk-adapter/test/filters/field_references.test.ts

Extract references from new Lookup field in Zendesk Support
---
---
* Extract references from new Lookup field in Zendesk Support
---
* field and value of user_field/ticket_field/organization_field will become ReferenceExpression in ticket_field .nacl files

SALTO-2413-zendesk-extract-references-from-new-lookup-field

---

packages/adapter-components/src/config/index.ts
packages/adapter-components/src/config/transformation.ts
packages/adapter-components/src/elements/instance_elements.ts
packages/adapter-components/src/filters/referenced_instance_names.ts
packages/adapter-components/test/elements/ducktype/instance_elements.test.ts
packages/adapter-components/test/elements/instance_elements.test.ts
packages/adapter-components/test/elements/swagger/instance_elements.test.ts
packages/adapter-components/test/filters/referenced_instance_name.test.ts
packages/jira-adapter/e2e_test/instances/board.ts
packages/jira-adapter/e2e_test/instances/workflow.ts
packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/system_config_doc.md

Add `nameMapping` option to `TransformationConfig` and set use it to lowercase instance ids for Jira `Status` instances
---
As the same Jira status instance might appear in different cases sometimes, we want to convert all status salto names to lowercase. To enable this change I added `nameMapping` to `TransformationConfig`, and we convert the instance id and filepath when the instance is created.
---
Jira: convert `Status` instance names  lowercase. To update existing status element ids please run `salto fetch --regenerate-salto-ids`
---
Jira: On the next fetch with `--regenerate-salto-ids` status instances ids will change to lowercase.

SALTO-2299: TransformationConfig update & Lowercase status names in Jira

---

packages/core/index.ts

Exports the error type for identification of the error outside of the package itself.
---
---
-
---
-

SALTO-2608 - Exports NoWorkspaceConfig error from core package

---

packages/netsuite-adapter/package.json
yarn.lock

Netsuite Adapter: Upgrade SDF version to 1.5.0-salto-1 so it'll be based on 2022.1 API version
---
Netsuite Adapter: For existing Salto Workspaces, you should reinstall the NetSuite service by creating a temporary Salto Workspace and calling `salto service add netsuite --no-login`. This will download the new SDF version that will be used globally for all WSs. The temporary Salto Workspace can be deleted.

SALTO-2559: Upgrade SDF version to 1.5.0-salto-1 so it'll be based on 2022.1 API version

---

packages/zendesk-adapter/src/change_validators/child_parent/removed_from_parent.ts
packages/zendesk-adapter/test/change_validators/removed_from_parent.test.ts

Rephrase change validation Zendesk error when user removed the option for the ticket field but didn't remove the ticket field option instance.
---
None
---
None
---
None

SALTO-2473: rephrase change validation zendesk error of removed from parent

---

packages/salesforce-adapter/src/filters/custom_objects_instances.ts
packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts

Change custom object instances path from being under the object folder to the records folder where all other instances are
---
---
_Salesforce Adapter:_
* Changed custom object instances path from being under the object folder to the records folder 
---
_None_

SALTO-2277: change custom object instances path

---

packages/jira-adapter/src/config/api_config.ts

_I added an override to the type of the filter from  'jira.FilterSubscriptionsList' to 'List<jira.FilterSubscription>' and omitted the 'id' field_
---
_Jira recently added a 'subscriptions' field to filters and we wanted to change how it appears in the NaCl_
previously:
after the change: 
---
_Jira adapter_
* Change in the NaCl file of filters with subscriptions
---
_Jira Adapter_
* Change in the NaCl file of filters with subscriptions

SALTO-2578: Support Filter Subscriptions - Jira

---

packages/workspace/src/workspace/changed_at_index.ts
packages/workspace/src/workspace/changed_by_index.ts
packages/workspace/test/workspace/changed_at_index.test.ts
packages/workspace/test/workspace/changed_by_index.test.ts

fixed bug in changed by and changed at causing us to ignore changes in objects fields if the object itself did not change his changed by/at value. 
i added tests for that edge case.
and raised the index version to fix the error across workspaces
---
the feature using this is not open to all users so im leaving the release notes empty
---
---

SALTO-2614/fix changed by at index update

---

packages/zendesk-adapter/e2e_test/adapter.test.ts

Temporary disable Zendesk e2e brand_logo deploy test
---
---
-
---
None.

SALTO-2616-skip-zendesk-e2e-brand-logo

---

packages/salesforce-adapter/src/transformers/reference_mapping.ts

_Add reference to emailTemplate under Autoresponse_
---
None
---
* Add reference from the template field to emailTemplate under AutoResponse
---
* Add reference from the template field to emailTemplate under AutoResponse

SALTO-2292 Add reference to emailTemplate under AutoResponse

---

packages/salesforce-adapter/src/transformers/reference_mapping.ts

_Extract field references from actionCalls in Report_
---
None
---
* Add reference to the custom field in ReportGrouping under Report
---
* Add reference to the custom field in ReportGrouping under Report

SALTO-2135 Extract field references from ReportGrouping in Report

---

packages/core/src/core/adapters/adapters.ts
packages/core/test/core/adapters/adapters.test.ts

Fixes adapter config to correctly handle multi app scenario
---
---
- Fixed issue where saved searches would change on fetch when in a multiple-account workspace 
---
_None_

SALTO-2548 fix element source filter

---

packages/workspace/src/workspace/nacl_files/multi_env/routers.ts

Improved memory and runtime performance for applying changes in isolated mode.
Before this change, the code would sometimes request the same top level element
many times more than necessary.
this had a significant effect on performance and on memory consumption in cases
where there were many changes in the same element
---
the scenario where this is relevant is when there are many changes in the same element and that element is relatively large.
when trying to apply that in "isolated" mode, the code would have loaded many copies of that element into memory.
did not add new tests as we do not expect a different result from the new code, it is just the way it is implemented has changed....
---
Core:
- Improved performance for applying changes in isolated mode (fetch -m …

SALTO-2482: improve performance for isolated fetch mode

---

packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts

This fixes an issue where if a nacl source was non-empty once and then became empty
it would be constantly invalidated because we would never set the empty hash
---
No release notes because it is a fairly unlikely scenario and the effect is not visible to the user other than a performance issue
---
_None_
---
_None_

SALTO-2622: Set correct nacl source hash when source is empty

---

packages/zendesk-adapter/src/change_validators/brand_creation.ts
packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/src/constants.ts
packages/zendesk-adapter/src/filters/brand_logo.ts
packages/zendesk-adapter/src/filters/field_references.ts
packages/zendesk-adapter/src/filters/references/missing_references.ts
packages/zendesk-adapter/src/filters/remove_brand_logo_field.ts
packages/zendesk-adapter/test/change_validators/brand_creation.test.ts
packages/zendesk-adapter/test/filters/brand_logo.test.ts
packages/zendesk-adapter/test/filters/field_references.test.ts
packages/zendesk-adapter/test/filters/remove_brand_logo_field.test.ts

Adding missing references for brand, schedule and group values in Trigger instances
To Do:
---
* Changed BRAND_NAME const to BRAND_TYPE_NAME
* Moved missing references strategies to a different file for more order
---
* Adding missing references for brand, schedule and group values in Trigger instances
---
* missing references will convert from string into Salto unresolved references

SALTO-2606 support more zendesk types for missing references- trigger

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/filters/add_restriction.ts
packages/zendesk-adapter/test/filters/add_restriction.test.ts

_Add restriction filter for ticket_field__custom_field_options.value_
---
None
---
_Zendesk adapter_
* Add restriction filter of regex for the type ticket_field__custom_field_options.value
---
_Zendesk adapter_
* Add restriction filter of regex for the type ticket_field__custom_field_options.value

SALTO-2124: add restriction filter for ticket_field__custom_field_options.value

---

packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/change_validators/system_fields.ts
packages/jira-adapter/test/change_validators/system_fields.test.ts

_Add change validator for attempting to deploy a system field_ 
---
Until now, the deploy would fail but appears as an internal error.
In order to determine if the field is a system field I checked if the 'schema' field exists.
---
_Jira Adapter_
* Added an indicative error when attempting to deploy a system field
---
_None_

SALTO-2228: add change validator for attempting to deploy a system field

---

packages/jira-adapter/src/client/connection.ts
packages/jira-adapter/test/client/connection.test.ts

Changed DC authorization to work with password since there are limitation when working with the API key (websudo)
---
None
---
None

SALTO-2520: Changed dc authorization to use password

---

packages/jira-adapter/e2e_test/instances/workflow.ts
packages/jira-adapter/src/filters/sort_lists.ts

Added sort to values in `NotificationScheme`, `FieldConfigurationScheme` and `Workflow`
---
- Fixed order inconsistency in different environments in `NotificationScheme`, `FieldConfigurationScheme` and `Workflow`
---
- The order of values in `NotificationScheme`, `FieldConfigurationScheme` and `Workflow` might change after the next fetch

SALTO-2629: inconsistent order in instances in Jira

---

packages/jira-adapter/src/config/api_config.ts

_Omit the subscriptions field in Jira filters_
---
_Jira_
* filters 'subscriptions' field won't appear in the filter's NaCl any more 
---
_Jira_
* filters 'subscriptions' field won't appear in the filter's NaCl any more

SALTO-2638: Omit the subscriptions field in Jira filters

---

docs/syntax.md
packages/adapter-api/src/core_annotations.ts
packages/workspace/src/serializer/elements.ts
packages/workspace/src/validator.ts
packages/workspace/test/validator.test.ts

Added a support for a new core annotation- `_additional_properties` which issues a warning if there is a field that does not exist in the type definition
---
Core:
A new annotation was added- `_additional_properties`. It allows warning when unexpected values are present in NaCl
---
None

SALTO-2401 Throw validation error for unexpected values in adapters config

---

packages/jira-adapter/e2e_test/instances/board.ts
packages/jira-adapter/e2e_test/instances/fieldConfiguration.ts
packages/jira-adapter/e2e_test/instances/index.ts
packages/jira-adapter/e2e_test/instances/screen.ts
packages/jira-adapter/e2e_test/instances/securityScheme.ts
packages/jira-adapter/e2e_test/instances/workflow.ts
packages/jira-adapter/src/filters/fields/field_name_filter.ts
packages/jira-adapter/test/filters/fields/field_name_filter.test.ts

Changed `addTypeToFieldName` default to true
---
- The default of the configuration option `addTypeToFieldName` was changed to true
---
None

SALTO-2635: Make the Jira addTypeToFieldName option True by default

---

packages/adapter-components/src/config/request.ts
packages/adapter-components/src/elements/swagger/instance_elements.ts
packages/adapter-components/test/elements/swagger/instance_elements.test.ts
packages/jira-adapter/src/config/api_config.ts

(Continuing @shayc331 work from https://github.com/salto-io/salto/pull/3289)
_Add a flag to `RecurseIntoConfig` which won't fail the instance when we fail to retrieve some property from the service and use it for the `contextDefaults` field under `Field` instances_
---
_In some cases we want to allow skipping values where it might happen in order to avoid unintentionally omitting the instances_
---
_Jira_:
* Fixed issue where Field instances were omitted if their default value could not be fetched (e.g. Category)
---
_Jira_:
* Some Field instances that were erroneously omitted due to failure to get some of their attributes will be added (e.g. Category)

SALTO-2615: add option to make recurseInto values not to fail the instance - Jira

---

packages/adapter-components/src/client/config.ts
packages/adapter-components/src/config/index.ts
packages/adapter-components/src/config/request.ts
packages/adapter-components/src/config/shared.ts
packages/adapter-components/src/config/swagger.ts
packages/adapter-components/src/config/transformation.ts
packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/config/config.ts
packages/jira-adapter/system_config_doc.md
packages/netsuite-adapter/config_doc.md
packages/netsuite-adapter/src/config.ts
packages/salesforce-adapter/src/types.ts
packages/stripe-adapter/src/config.ts
packages/workato-adapter/src/config.ts
packages/zendesk-adapter/src/config.ts
packages/zuora-billing-adapter/src/config.ts

Added _additional_properties = false to all configuration types (hopefully...)
Also fixed several configurations that were not defined in the types, and configuration documentation files that contained errors.
To check this I added additional properties in all adapter configuration files (only at the top level), and also added all available apiDefinitions (when apiDefinitions were not available I added the config from the config_doc)
---
---
Core:
Unexpected values in adapter NaCl's will cause validation warnings. It will help avoiding typing errors.
---
None

SALTO-2627: Add "additional_fields = false" annotations to all configuration relevant types

---

packages/netsuite-adapter/src/changes_detector/changes_detectors/custom_record_type.ts
packages/netsuite-adapter/src/changes_detector/changes_detectors/custom_type.ts
packages/netsuite-adapter/src/changes_detector/changes_detectors/file_cabinet.ts
packages/netsuite-adapter/src/changes_detector/changes_detectors/role.ts
packages/netsuite-adapter/src/changes_detector/changes_detectors/script.ts
packages/netsuite-adapter/src/changes_detector/date_formats.ts
packages/netsuite-adapter/test/changes_detector/custom_field.test.ts
packages/netsuite-adapter/test/changes_detector/custom_list.test.ts
packages/netsuite-adapter/test/changes_detector/custom_record_type.test.ts
packages/netsuite-adapter/test/changes_detector/file_cabinet.test.ts
packages/netsuite-adapter/test/changes_detector/role.test.ts
packages/netsuite-adapter/test/changes_detector/script.test.ts

_suiteQL queries changed to support different time formats in user accounts_
---
_None_
---
* Changed formatSuiteQLDate to use TO_DATE with MM/DD/YYYY date format
* Added TO_CHAR to lastmodifieddate to return it in the above date format
---
_None_

SALTO-2424: fix quick fetch failure for accounts with different time formats

---

packages/adapter-components/src/client/http_client.ts
packages/adapter-components/src/client/http_connection.ts
packages/adapter-components/src/client/index.ts
packages/adapter-components/src/client/pagination.ts
packages/adapter-components/test/client/http_client.test.ts

Pass response header to `paginationFunc`
---
Okta's API uses response headers for pagination.
These changes required  in order to implement the new pagination method for Okta (which will be added in a separate PR in the future).
---

SALTO-2648 Pass response header params to paginationFunc

---

packages/salesforce-adapter/src/transformers/reference_mapping.ts

_Extract references from Salesforce Queues_
---
None
---
* Add Group and Role references from queueMembers under Queue type
---
* Add Group and Role references from queueMembers under Queue type

SALTO-2411 Extract references from Salesforce Queues

---

packages/zendesk-adapter/src/filters/user.ts
packages/zendesk-adapter/test/filters/user.test.ts

_Replace user ids to emails zendesk guid_
---
None
---
Zendesk:
* Replace user ids to emails for user_segment and article in zendesk guid.
---
None

Salto 2573 replace user ids to emails zendesk guid

---

packages/jira-adapter/src/filters/workflow/workflow_modification_filter.ts
packages/jira-adapter/test/filters/workflow/workflow_modification_filter.test.ts

Fixed a bug with modifying active workflows
---
To modify active workflow we need to edit the workflow scheme that uses it. Recently we changed `defaultDeployChange` to do nothing if the before and after are equal so when we tried to update the workflow scheme it didn't actually do anything
---
- Fixed a bug with deploying active workflows
---
None

SALTO-2673: Modifying active workflow fails

---

packages/netsuite-adapter/src/transformer.ts
packages/netsuite-adapter/test/transformer.test.ts

should transform boolean values even if field is unknown - `"T" -> true`, `"F" -> false`
---
---
- transform booleans in untyped values- `"T" -> true`, `"F" -> false`
---
None

SALTO-2556 transform booleans in untyped values

---

packages/adapter-components/src/elements/subtypes.ts

Fixed a bug that caused the warning to be issued on the wrong items, and also a typo
---
None
---
None

SALTO-2628 - Warn (in logs) when duplicate type names causes concealment

---

packages/zendesk-adapter/src/config.ts

_Replace user ids to emails zendesk guid_
---
None
---
None
---
None

SALTO-2573: replace user ids to emails zendesk guid fix type

---

packages/cli/src/commands/deploy.ts

_CLI prints deployment url message even if its empty_
---
None
---
_CLI_
* Bugfix: prevent the CLI from print an unnecessary message upon deployment
---
_None_

SALTO-2684: CLI prints deployment url message even if its empty

---

packages/workspace/src/workspace/adapters_config_source.ts

Currently, `updateAccountConfig` doesn't work when calling it without explicit ElementSource (even though it already has the relevant element source - `adapter_config_source`).
This PR fixes the issue :) .
---
---
_None_
---
_None_

SALTO-2697 - updateAccountConfig supported without passing explicit elementSource

---

packages/zendesk-adapter/src/config.ts

_Support deploy for Zendesk Guide permission groups_
---
None
---
_None_
---
_None_

SALTO-2594: add deploy for Zendesk Guide permission groups

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/filters/field_references.ts
packages/zendesk-adapter/src/filters/references/list_values_missing_references.ts
packages/zendesk-adapter/src/filters/references/missing_references.ts
packages/zendesk-adapter/test/filters/references/list_values_missing_references.test.ts

Adding a new Zendesk filter which converts the first element in a 'value' field to a missing references. These paths are taken by a fixed list in the filter.
Supported types & fields:
* Trigger - all group variations, target, ticket_form
* Automation - all group variations, target, ticket_form
* View - ticket_form
* Workspace (new) - group, brand
* Macro - ticket_form
* SLA policy (new) - group, brand, ticket_form
To Do:
---
* Igonring fixed values by checking if they aren't numbers, because it was already supposed to be converted in field_references filter
---
* Adding support for all group variations, target, ticket_form, webhook to the missing references field
* Adding missing references to workspaces and sla_policy types
---
_User …

SALTO-2642-support-Zendesk-missing-references-for-list-values

---

packages/zendesk-adapter/e2e_test/adapter.test.ts

Adding to Zendesk cleanup function that deletes all 'brand' instances which start with 'Testbrand'. This is necessary to verify we have no more 5 brands in the environment
---
---
-
---
-

SALTO-2688 Zendesk E2E cleanup function

---

packages/zendesk-adapter/src/filters/field_references.ts
packages/zendesk-adapter/src/filters/references/missing_references.ts

Add Zendesk routing_attribute_value and user_segment (guide) types to missing references configuration
---
---
* Add Zendesk routing_attribute_value and user_segment (guide) types to missing references configuration
---
* missing references values will be replaced in routing_attribute_value and user_segment instances

SALTO-2702 Support Zendesk missing references in routing_attribute_value and user_segment (guide) types

---

packages/core/index.ts
packages/core/src/app_config.ts
packages/core/src/local-workspace/workspace.ts

Exporting CONFIG_DIR_NAME from `@salto-io/core`.
---
---
-
---
-

SALTO-2709 - Exported CONFIG_DIR_NAME from @salto-io/core

---

packages/jira-adapter/src/reference_mapping.ts
packages/jira-adapter/test/product_settings/reference_mapping.test.ts

_Add references from workflow to Resolution and Priority_
---
_example of the change in the NaCl:_
Resolution: 
Priority: 
---
_Jira_
* add references from workflow to Resolution and Priority
---
_Jira_
* workflow Nacl files will have references to Resolution and Priority elements

SALTO-2039 Add references from workflow to Resolution and Priority - Jira

---

packages/jira-adapter/src/dependency_changers/field_contexts.ts
packages/jira-adapter/src/dependency_changers/index.ts
packages/jira-adapter/test/dependency_changers/field_contexts.test.ts

_Add dependency changer between field that modified to a new context_
---
_When a change validator omitted an adding of a context, the dependency caused omitting the modification change as well_
---
_Jira_
* fixed a bug related to the dependency between adding a new field context to modifying the field
---
None

SALTO-2633: add dependency changer between field that modified to a new context - Jira

---

packages/core/index.ts
packages/core/src/app_config.ts

Removal of `getConfigDir` as now CONFIG_DIR_NAME is the source of truth for getting `salto.config`.
---
This PR is the second step of [SALTO-2709](https://salto-io.atlassian.net/browse/SALTO-2709), as the first PR happened in [here](https://github.com/salto-io/salto/pull/3349)
---
-
---
-

SALTO-2709 - gitConfigDir removed

---

packages/core/src/core/plan/change_validators/check_deployment_annotations.ts
packages/core/test/core/plan/change_validators/check_deployment_annotations.test.ts

Changed messages about unsupported fields from warning to info
---
- Changed messages about unsupported fields from warning to info
---
None

SALTO-2705: Changed messages about unsupported fields from warning to info

---

packages/jira-adapter/src/filters/sort_lists.ts

Fixed inconsistency in the order of statuses and the `from` value in workflows
---
- Fixed inconsistency in the order of statuses and the `from` value in workflows
---
- Order of `statuses` and `from` values in workflow might change

SALTO-2680: Unstable sort order in workflow statuses and "from" statuses

---

packages/adapter-api/src/elements.ts
packages/adapter-api/src/values.ts
packages/adapter-api/test/values.test.ts
packages/adapter-utils/src/compare.ts
packages/core/src/api.ts
packages/core/src/core/plan/plan.ts
packages/core/src/core/plan/plan_item.ts
packages/core/test/core/plan/plan.test.ts
packages/jira-adapter/src/filters/fields/default_values.ts

Added a `compareReferencesValues` to control the element compare behavior when comparing references. This flag is to true in the deploy flow and false in the other cases.
When the flag is false we will never look at the reference value when comparing, only the reference id. When the flag is true we will compare the reference value when it does not point to an Element or a variable.
This solves two issues of the current behavior:
- A change of a value would not add an element with reference to it to the plan
- In fetch, a change from a value to a reference that resolved to the same value would not be applied
---
_Core_:
- Fixed a bug where instances with reference to inner properties that changed would not be added to the plan
- Fixed a bug where in fetch, a change from a …

SALTO-2667: Separate compare logic between deploy and the rest

---

packages/salesforce-adapter/src/adapter.ts

_SALTO-2369 Fix lwc targetConfogs property type_
---
before the change in order, it would first attempt to cast `salesforce.LightningComponentBundle.instance.example.targetConfigs.targetConfig.0.property.0.required` field into boolean and only then remove the attribute_prefix but it wouldnt math the type so the casting didn't occurred.
---
* Fix property.required field casting into boolean under LightningComponentBundle.targetConfigs
---
None

SALTO-2369 Fix lwc targetConfigs property type

---

packages/core/src/core/plan/plan.ts
packages/core/test/core/plan/plan.test.ts

Fixed plan comparison for template expressions
---
When comparing template expression in `compareValuesAndLazyResolveRefs` no condition would match template expressions so it would go to the default comparison of `_.isEqual` [here](https://github.com/salto-io/salto/blob/main/packages/core/src/core/plan/plan.ts#L152)
Besides being inefficient, the templates are not resolved at that point so it always compares `undefined` to `undefined` when looking at the value
---
None (not sure if this has an effect on the user since until now we didn't have inner references inside templates)
---
None

SALTO-2667: Fixed plan comparison for template expressions

---

packages/jira-adapter/package.json

There is a problem in the SaaS with the new jql-ast library dependency ([see](https://app.circleci.com/pipelines/github/salto-io/salto_private/28759/workflows/acdb5c17-636c-4346-bc06-9cc0e5c2b341/jobs/663467)). Looks like it installs a different version of `antlr4ts`, a dependency of `jql-ast`, in the saas which `jql-ast` does not seem to work with.
It seems related to the difference in the yarn version between the two. The resolutions config solves this issue.
This issue can happen with any project that uses yarn2 and has the OSS as its dependency, and therefore the fix is in the OSS
---
None
---
None

SALTO-2687: Fixed jql-ast dependency

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/filters/automation/smart_values/smart_value_reference_filter.ts
packages/jira-adapter/src/filters/automation/smart_values/template_expression_generator.ts
packages/jira-adapter/test/filters/automation/smart_values/smart_value_reference_filter.test.ts
packages/jira-adapter/test/filters/automation/smart_values/template_expression_generator.test.ts

Process some smart values in jira as templates referencing field instances
---
This PR supports parsing the following:
`abc {{fieldName}}`
`abc {{fieldId}}`
`abc {{<fieldName/fieldId>.somethingElse}}`
`abc {{issue.<fieldName/fieldId>}}`
`abc {{issue.fields.<fieldName/fieldId>}}`
`abc {{fields.<fieldName/fieldId>}}`
`abc {{triggerIssue.<fieldName/fieldId>}}`
`abc {{destinationIssue.<fieldName/fieldId>}}`
Does not support yet
things like
`{{or(issue.fieldName,or(equals(issue.fieldName2,null),equals(issue.fieldName3,null)))}}`
---
Parse smart values under automations as template values, that include references to the instances of the fields that the smart value references.
---
Some value fields under Automation …

SALTO-2601: added basic parsing for smart values

---

packages/jira-adapter/package.json

Reverts salto-io/salto#3365
It looks like the `resolutions` config does not have an effect on the SaaS, added this config in the SaaS package.json instead
---
None
---
None

Revert "SALTO-2687: Fixed jql-ast dependency"

---

packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/filters/priority.ts
packages/jira-adapter/system_config_doc.md
packages/jira-adapter/test/filters/priority.test.ts

Removed `isDefault` from Priority when it is false since it causes a change validator warning everytime we create a priority (and the priority is anyway created with isDefault=false)
---
- Removed `isDefault` from Priority when it is false
---
- Removed `isDefault` from Priority when it is false

SALTO-2745: removed isDefault false from Priority

---

packages/core/src/local-workspace/state.ts
packages/core/test/workspace/local/state.test.ts

if the cache is not "dirty" we skip calculating it again and flushing it because of this, we should also avoid this calculation when asked to get a new hash.
---
No release notes as this is a very internal potential performance issue that only affects very specific scenarios
---
_None_
---
_None_

SALTO-2752: fix state hash recalculation when content is unchanged

---

packages/salesforce-adapter/src/filters/custom_object_instances_references.ts
packages/salesforce-adapter/test/filters/custom_object_instances_references.test.ts

---
this is basically a revert of #2421
---
- Removed _parent annotation from custom object records
---
- Removed _parent annotation from custom object records

SALTO-2296: remove _parent annotation from custom object instances

---

packages/adapter-components/src/elements/instance_elements.ts
packages/jira-adapter/e2e_test/instances/automation.ts
packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/filters/automation/automation_deployment.ts
packages/jira-adapter/src/filters/automation/automation_structure.ts
packages/jira-adapter/src/filters/references_by_self_link.ts
packages/jira-adapter/src/filters/remove_empty_values.ts
packages/jira-adapter/src/filters/user.ts
packages/jira-adapter/src/filters/workflow/workflow_modification_filter.ts
packages/jira-adapter/test/filters/remove_empty_values.test.ts

Fix a bug where we would omit empty values from automations when the API on deploy still expected them to exist.
---
Changed all the places in the adapter where we would implicitly omit all the empty values from elements.
Added filter to omit empty values only from the values we really want to
---
- Fixed a bug where empty arrays would be omitted from automations causing the deployment to fail in some cases. 
---
- Some values might be added to automations

SALTO-2751: Empty values removal causes automation deployment to fail

---

packages/zendesk-adapter/src/filters/dynamic_content_references.ts
packages/zendesk-adapter/src/filters/handle_template_expressions.ts
packages/zendesk-adapter/test/filters/dynamic_content_references.test.ts
packages/zendesk-adapter/test/filters/handle_template_expressions.test.ts

_create broken references in template expression_
---
None
---
Zendesk:
* Create broken references for missing references in template expression. 
Will affect types such as macro and ticket_field.
---
Zendesk:
* Create broken references for missing references in template expression. 
Will affect types such as macro and ticket_field.

SALTO-2466: create broken references in template expression

---

packages/jira-adapter/src/filters/remove_empty_values.ts

The notification scheme has a hidden value that in some cases might be empty, i.e. `{}`
For some reason, this causes a pending change in the workspace.
As a quick solution, this PR omits the empty values from notification scheme to avoid this case. Later I will look for the real reason in Core
---
None (this bug did not affect customers so far)
---
None

SALTO-2766: Fixed bug of pending changes on notification scheme

---

packages/workspace/src/parser/internal/native/consumers/values.ts
packages/workspace/test/parser/parse.test.ts

Fixed multiline template expression causing pending changes
---
When there is a multiline string, our parser returns each line as a separate token. When the entire multiline is a string we just join the strings, but when it is a template expression we pass each token as a separate part, and passing multiple strings in a row to new Template expression causes pending changes
So I changed to use createTemplateExpression which handles this case
---
_Core__:
- Fixed a bug where multiline template expression would cause a pending change in the workspace
---
None

SALTO-2765: fixed multiline template expression causing pending changes

---

packages/salesforce-adapter/src/constants.ts
packages/salesforce-adapter/src/filters/custom_objects_instances.ts
packages/salesforce-adapter/test/change_validators/custom_object_instances.test.ts
packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
packages/salesforce-adapter/test/utils.ts

This fixes a new issue where we would try to read fields from the SOAP API even when they did not exist in that API
this was because the queryable annotation behaved differently from the other ones it was assumed "true" if it was missing.
since we do set that annotation on all the fields that come from the SOAP API there is no reason to assume it is true if it is missing
---
---
- Fixed issue with fetching custom object instances with non-queryable fields
---
_None_

SALTO-2767: Change queryable field annotation default beahvior to false

---

packages/salesforce-adapter/src/filters/field_permissions_enum.ts
packages/salesforce-adapter/test/filters/field_permissions_enum.test.ts

As an alternative solution for the issue, we can remove the fieldPermissions enum logic to not run on PermissionSets
---
No reason to merge both this and https://github.com/salto-io/salto/pull/3392
---
* enumFieldPermission support for PermissionSet temporary removed
---
* If there was a fetch with `enumFieldPermission = true` that included PermissionSet instances before, the next fetch will include changes in PermissionSet's fieldPermission values structure

SALTO-2768 - Remove PermissionSet from EnumFieldPermissions filter

---

packages/salesforce-adapter/src/transformers/reference_mapping.ts

Fix issue where references from permission sets are missing
---
This is reverting another part of #3204 
---
_None_
---
_None_

SALTO-2768: fix references from permission sets

---

packages/salesforce-adapter/e2e_test/adapter.test.ts
packages/salesforce-adapter/src/filters/convert_maps.ts
packages/salesforce-adapter/src/filters/hardcoded_lists.json
packages/salesforce-adapter/test/filters/convert_maps.test.ts
packages/salesforce-adapter/test/mock_elements.ts

_Convert LightningComponentBundle resources into map_
---
None
---
* Convert LightningComponentBundle resources into map
* Add support for converting inner fields from array into map.
---
* LightningComponentBundle resources will be saved as map instead of array.

SALTO-1899 Convert LightningComponentBundle resources into map

---

packages/core/src/core/plan/plan.ts
packages/jira-adapter/src/config/config.ts
packages/jira-adapter/src/filters/automation/smart_values/smart_value_reference_filter.ts
packages/jira-adapter/src/filters/jql/jql_references.ts
packages/jira-adapter/test/filters/automation/smart_values/smart_value_reference_filter.test.ts
packages/jira-adapter/test/filters/jql/jql_references.test.ts
packages/workspace/src/expressions.ts

- Added logs to help us identify the problematic value
- Fixed the issue in https://salto-io.atlassian.net/browse/INCIDENT-967?focusedCommentId=48047 (though it seems unrelated, but still 🤷‍♂️)
- Added flag to disable parsing template expression (since it looks like the problem is coming from template expression)
---
There is an issue where a fetch failed `Cannot read property 'createTopLevelParentID' of undefined` because it is getting to [here](https://github.com/salto-io/salto/blob/main/packages/workspace/src/expressions.ts#L223) and somehow elemID is undefined at that point
---
None
---
None

INCIDENT-967: fetch failed with "Cannot read property 'createTopLevelParentID' of undefined"

---

packages/jira-adapter/src/filters/automation/smart_values/template_expression_generator.ts
packages/jira-adapter/src/filters/jql/template_expression_generator.ts
packages/jira-adapter/test/filters/automation/smart_values/template_expression_generator.test.ts
packages/jira-adapter/test/filters/jql/template_expression_generator.test.ts

Smart values with {{toString}} causes fetch to fail
---
Fixed to use `Object.prototype.hasOwnProperty.call` both in the smart values parsing and in the JQL parsing
---
- Fixed a bug that causes fetch to fail with "Cannot read property 'createTopLevelParentID' of undefined"
---
None

SALTO-2775: Smart values with {{toString}} causes fetch to fail

---

packages/workato-adapter/src/filters/cross_service/netsuite/element_index.ts
packages/workato-adapter/test/filters/recipe_references.test.ts

When [SALTO-820](https://github.com/salto-io/salto/pull/3313) is merged, all references to `netsuite.customrecordtype` instances & custom fields (inside the instance) should be replaced with references to custom record types & fields.
---
Workato Adapter:
- Fix Netsuite `customrecordtype` references
---
Workato Adapter:
- References to `netsuite.customrecordtype` instances & custom fields (inside the instance) will be replaced with references to custom record types & fields (e.g. `netsuite.customrecord1`, `netsuite.customrecord1.field.custom_custrecord_field`)

SALTO-820 workato: fix netsuite customrecordtype references

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/change_validators/account_id.ts
packages/jira-adapter/src/filters/account_id/account_id_filter.ts
packages/jira-adapter/src/filters/user.ts
packages/jira-adapter/test/change_validators/account_id.test.ts
packages/jira-adapter/test/filters/account_id/account_id_common.ts
packages/jira-adapter/test/filters/account_id/account_id_filter.test.ts
packages/jira-adapter/test/filters/user.test.ts

_JIRA: changed the display name in a few places with account id to make it unique_
---
This PR is based on https://github.com/salto-io/salto/pull/3387 and https://github.com/salto-io/salto/pull/3348, noly the last commit is relevant
In several places the user filter changed one of 3 user types (User, UserBean, Board_admins) with the display name, which was not unique.
-The display name was changed to account id 
-The scenarios were added to the account id filter to add display names (only in fetch)
-The user filter was refactored from transformValue to walkOnElement (using the walkOnUser function). Time of filter was reduced from ~700 ms to ~130ms (JIRA test env
-The user filter before covered all cases of the 3 user types (including possible future ones). Now we only replace the actual …

SALTO-2541 replace display name with account ID in user filter

---

packages/jira-adapter/e2e_test/instances/automation.ts
packages/jira-adapter/src/filters/automation/automation_structure.ts
packages/jira-adapter/test/filters/automation/automation_structure.test.ts

Fixed an issue where automation with a specific component type would fail with 500 because of a recent API change.
---
A new id value was added under the `value` field and if it is not passed in the request, it fails with 500.
The id can be modified in deploy so it is env safe to show it in the NaCl.
---
- Fixed a bug where deploying automation with certain components fails with 500.
---
- Some id values might be added to automation after the next fetch

SALTO-2784: Deploying automation with a "jira.lookup.issues" component type fails

---

packages/adapter-utils/src/utils.ts
packages/adapter-utils/test/utils.test.ts
packages/workspace/src/workspace/hidden_values.ts
packages/workspace/test/workspace/hidden_values.test.ts

Fixed Salto restore to work with empty values
---
changed filterById not to omit empty value if it was originally an empty value
---
_Core_:
- Fixed Salto restore to work with empty values
---
None

SALTO-2785: Salto restore does not restore empty values

---

packages/salesforce-adapter/src/filters/convert_maps.ts
packages/salesforce-adapter/test/filters/convert_maps.test.ts

_SF - convert_map filter- convert the type even if there are no instances of this type in our WS_
---
In SF adapter under the convert_map filter we only update the type if there are instances of this type in our WS. it can create problems when we later on will try to clone instances of this type from other workspaces.
we need to modify it so it will change the type even if there are no instances of this type.
---
* convert_map filter- convert the type even if there are no instances of this type in our WS
---
* this will cause change in the Nacls of following types: BusinessHoursSettings, EmailTemplate, LightningComponentBundle and Profile

SALTO-2772 SF - convert_map filter- convert the type even if there are no instances of this type in our WS

---

packages/jira-adapter/src/filters/workflow_scheme.ts
packages/jira-adapter/test/filters/workflow_scheme.test.ts

_Jira's error message for workflow scheme migration error included internal IDs. In this PR I replaced them with their Salto name_
---
Example: 
Before:
`Issue type with ID 10008 is missing the mappings required for statuses with IDs 10018,3,4,10165,10005.`
After : 
`Issue type with name Bug is missing the mappings required for statuses with names a_shared_status2@s,in_progress@s,reopened,a_shared_status4@s,done.`
---
_None_
---
_None_

SALTO-2333 replace ids with names in workflow scheme migration error - Jira

---

packages/workspace/src/workspace/workspace.ts
packages/workspace/test/workspace/workspace.test.ts

Currently all nacl source are flushed when flushing a workspace but only the state of the current environment is flushed.
Since loading a workspace requires loading the state of all environments, it would make sense that for symmetry (and to avoid cache invalidations) we would also flush the state of all environments
---
---
Core:
- Fixed issue where the cache on multi-env workspaces would not always be fully updated
---
_None_

SALTO-2832: Flush all state files when flushing workspace

---

packages/zendesk-adapter/src/change_validators/automation_all_conditions.ts
packages/zendesk-adapter/test/change_validators/automation_all_conditions.test.ts

_automation validation should handle reference expression_
---
None
---
Zendesk:
* automation validation should handle reference expression
---
Zendesk:
* automation validation should handle reference expression

SALTO-2851: automation validation should handle reference expression

---

packages/jira-adapter/src/filters/automation/smart_values/smart_value_reference_filter.ts
packages/jira-adapter/src/filters/automation/smart_values/template_expression_generator.ts
packages/jira-adapter/src/filters/jql/jql_references.ts
packages/jira-adapter/src/filters/jql/template_expression_generator.ts
packages/jira-adapter/test/filters/automation/smart_values/smart_value_reference_filter.test.ts
packages/jira-adapter/test/filters/automation/smart_values/template_expression_generator.test.ts
packages/jira-adapter/test/filters/jql/template_expression_generator.test.ts

Now when a token in a JQL or a smart value will match more than one reference (e.g., if there are two fields with the same name), a reference won't be created and a warning will be returned
---
---
- Now when a token in a JQL or a smart value will match more than one reference (e.g., if there are two fields with the same name), a reference won't be created and a warning will be returned
---
None

SALTO-2729: Fix reference by name when there are multiple fields with the same name

---

packages/jira-adapter/src/reference_mapping.ts

The referenced function was removed when the references were changed in https://github.com/salto-io/salto/pull/3312
---
None
---
None
---
None

Fix outdated comments in jira reference rules

---

packages/adapter-utils/package.json
packages/adapter-utils/src/nacl_case_utils.ts
packages/adapter-utils/test/nacl_case_utils.test.ts
packages/zendesk-adapter/src/filters/brand_logo.ts
packages/zendesk-adapter/src/filters/help_center_locale.ts
packages/zendesk-adapter/src/filters/macro_attachments.ts
yarn.lock

Nacl paths appears to exceed the length limit in Zendesk static resource paths (macro_attachment and brand_logo).
This PR adds trim functionality of a file name to comply with filesystem restrictions.
---
---
* Static files with long names would be shortened and would concatenated with the name's hash
---
-

SALTO-2852 bug fix - nacl paths exceed length limit

---

packages/adapter-components/src/references/context.ts
packages/adapter-components/src/references/field_references.ts
packages/adapter-components/src/references/reference_mapping.ts
packages/adapter-components/test/references/field_references.test.ts

Counterpart of https://github.com/salto-io/salto/pull/3438 for the shared infra - allowing to restrict reference rules only to instances of specific types, to help avoid overlaps between rules in a structured way.
---
Will follow up with usages in the relevant adapters.
---
None
---
None

SALTO-2855 Allow restricting reference rules to specific types

---

packages/salesforce-adapter/src/filters/replace_instance_field_values.ts
packages/salesforce-adapter/src/filters/value_to_static_file.ts
packages/salesforce-adapter/src/transformers/reference_mapping.ts
packages/salesforce-adapter/test/filters/field_references.test.ts
packages/salesforce-adapter/test/transformers/transformer.test.ts

Support specifying instance type matchers that will restrict rules for resolving references to only look at source instances of specific types.
This is the salesforce part - see the linked PR for the adapter-components counterpart (we may eventually consolidate these behaviors, but currently the change is in a part that is not shared).
Also change one offending rule to demonstrate how this can be used - there are probably others that should be reviewed, and we may want to consider restricting more rules this way.
---
We had some overlaps between rules in salesforce that caused references to not be serialized correctly on deploy. This does not defend against that, but provides an easier way to restrict rules so that it is easier to avoid overlaps.
--- …

SALTO-2835 Allow restricting reference rules to specific types

---

packages/adapter-utils/src/utils.ts
packages/adapter-utils/test/utils.test.ts
packages/jira-adapter/jest.config.js
packages/zendesk-adapter/src/filters/dynamic_content_references.ts
packages/zendesk-adapter/test/adapter.test.ts

_Change transformValues to use the allowEmpty flag so it wont automatically omit empty values_
---
related to: https://github.com/salto-io/salto/pull/3412#issue-1390450814
---
* Fix transformValues so it wont delete empty values regardless of the allowEmpty flag.
---
None

SALTO-2773 SALTO-2853 Change transformValues to use the allowEmpty flag so it wont automatically omit empty values 

---

packages/salesforce-adapter/src/change_validators/profile_map_keys.ts
packages/salesforce-adapter/src/filters/convert_types.ts
packages/salesforce-adapter/src/filters/custom_object_instances_references.ts
packages/salesforce-adapter/src/filters/custom_objects_to_object_type.ts
packages/salesforce-adapter/src/filters/foreign_key_references.ts
packages/salesforce-adapter/src/filters/remove_fields_and_values.ts
packages/salesforce-adapter/src/filters/replace_instance_field_values.ts
packages/salesforce-adapter/src/filters/value_to_static_file.ts
packages/salesforce-adapter/src/filters/xml_attributes.ts
packages/salesforce-adapter/src/transformers/transformer.ts
packages/salesforce-adapter/src/transformers/xml_transformer.ts
packages/salesforce-adapter/test/adapter.discover.test.ts
packages/salesforce-adapter/test/mock_elements.ts
packages/salesforce-adapter/test/transformers/xml_transformer.test.ts

_Enable deploy QuickAction with only one QuickActionLayoutColumns_
---
Salesforce returns empty objects in XML as `<quickAction></quickAction>` for example, We treat them as "" (empty string), and we don't want to delete them so we should replace them with {} (empty object). in addition we added `allowEmpty: true` param to every `transformValues` func so they wont automatically omit them. 
---
* All Object that are defined as empty in Salesforce service will no longer be omitted and will be shown in the Nacl as empty object.
---
* All Object that are defined as empty in Salesforce service will no longer be omitted and will be shown in the Nacl as empty object.

SALTO-2652 Enable deploy QuickAction with only one QuickActionLayoutColumns

---

packages/core/package.json
packages/core/src/local-workspace/s3_dir_store.ts
packages/core/test/workspace/local/s3_dir_store.test.ts
packages/e2e-credentials-store/test/cli/index.test.ts
packages/persistent-pool/jest.config.js
packages/persistent-pool/package.json
packages/persistent-pool/src/lib/dynamodb/dynamodb_repo.ts
packages/persistent-pool/src/lib/dynamodb/utils.ts
packages/persistent-pool/test/lib/dynamodb/dynamodb_repo.e2e.test.ts
packages/persistent-pool/test/lib/dynamodb/dynamodb_repo.test.ts
packages/persistent-pool/test/lib/dynamodb/environment/globals.d.ts
packages/persistent-pool/test/lib/dynamodb/utils.test.ts
packages/persistent-pool/test/lib/dynamodb/utils.ts
packages/persistent-pool/tsconfig.json
yarn.lock

This reverts commits 6d55d5f2995ea1b52ec10e6ea775b4649a3ce2b4 and 0af90316660e4a4ead6863e7c9156425383d59c3
Reverting https://github.com/salto-io/salto/pull/3428 + https://github.com/salto-io/salto/pull/3401 to see if that fixes an issue that seems to be related to S3 and aws-sdk v3
---
---
None (only impacts S3 usage which has not been enabled in OSS)
---
None

Revert "SALTO-2826: add retries to S3 operations (#3428)" + "AWS SDK v3 (#3401)"

---

packages/jira-adapter/src/filters/workflow/workflow_modification_filter.ts
packages/jira-adapter/test/filters/workflow/workflow_modification_filter.test.ts

We recently changed the error message that is thrown when migration params are needed to deploy a workflow scheme. This caused a regression in the error message we show when we try to deploy a non-backward compatible workflow
---
- Fixed the error message when deploying a non backward compatible workflow
---
None

SALTO-2868: fixed an error message when deploy a non backward compatible workflow

---

packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/change_validator.ts
packages/netsuite-adapter/src/change_validators/currency_exchange_rate.ts
packages/netsuite-adapter/src/config.ts
packages/netsuite-adapter/src/constants.ts
packages/netsuite-adapter/src/filters/currency_exchange_rate.ts
packages/netsuite-adapter/test/change_validators/currency_exchange_rate.test.ts
packages/netsuite-adapter/test/filters/currency_exchange_rate.test.ts

_suppressd noisy exchange rate changes_
---
_None_
---
* exchangeRate will not be fetched by default 
* when deploying a new currency without exchangeRate a default value will be set
---
_exchangeRate will not appear in the nacl by default_

Salto-2397 - suppress noisy exchange rate changes

---

packages/jira-adapter/e2e_test/instances/filter.ts
packages/jira-adapter/e2e_test/instances/index.ts
packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/reference_mapping.ts

_When a Jira filter contained a share permission with a group it could not be deployed as it contains both name and id which might conflict_
---
We now remove the group id, and replace the name with a group reference
---
Jira adapter: 
-Jira's filters with share (view) permissions for groups can now be deployed. Groups' names are now references.
---
_Group id will be removed in filters that have a share permission with a group_

SALTO-2860: Deploy of filters does not work when the element includes  a share permission

---

packages/zendesk-adapter/src/filters/handle_template_expressions.ts
packages/zendesk-adapter/test/filters/handle_template_expressions.test.ts

Changed Zendesk's regex for dynamic content to catch '-' char
---
---
macros that use dynamic content reference with the character '-' will work
---

SALTO-2776 - Fix Zendesk's dynamic content reference regex in macros

---

packages/jira-adapter/src/filters/field_configuration/field_configuration_dependencies.ts
packages/jira-adapter/test/filters/field_configuration/field_configuration_dependencies.test.ts

Removed occurrences from generated dependencies in Jira import the text diff results on generating dependency
---
- Removed occurrences from generated dependencies in projects
---
- Removed occurrences from generated dependencies in projects

SALTO-2876: removed occurrences from generated dependencies

---

packages/netsuite-adapter/src/filters/translation_converter.ts

To reproduce-
1. change an annotation in a custom record type
2. add a field that has a `*Translate` field (that needs to be transformed to `{ ”text”: val, ”@_translate”: ”T” }`)
This will make `transformValues` to throw the error-
`Can not resolve value of reference with ElemID serviceid without elementsSource because value does not exist`
This happens because we need to transform only the root custom record type modification change and not its field addition change.
---
- fix custom record type translation converter bug
---
None

SALTO-2878 fix custom record type translation converter bug

---

packages/adapter-api/src/utils.ts
packages/adapter-api/test/utils.test.ts
packages/salesforce-adapter/src/filters/topics_for_objects.ts

- Fix bug in `getField` where no field is returned when there is an annotation with the same name as the field.
- Added tests to `getField` & `getFieldType` functions, including getting the closest parent field when the rest of the path is map/list keys, and returning `undefined` on path to annotation.
---
---
Adapter API:
- Remove unnecessary export of `getSubElement`
- Remove unused functions `getAnnotationKey`, `getAnnotationValue` (it was used in one place only so I moved the implementation over there)
- Fix bug where no field is returned when there is an annotation with the same name as the field
---
None

SALTO-2800 fix bug in getField

---

packages/adapter-api/src/element_id.ts
packages/adapter-api/test/elements.test.ts
packages/adapter-utils/src/collisions.ts
packages/adapter-utils/src/utils.ts
packages/adapter-utils/test/utils.test.ts
packages/core/src/local-workspace/state.ts
packages/jira-adapter/src/filters/duplicate_ids.ts
packages/workspace/src/serializer/elements.ts
packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
packages/workspace/src/workspace/nacl_files/parsed_nacl_files_cache.ts
packages/workspace/test/serializer/serializer.test.ts
packages/workspace/test/workspace/workspace.test.ts
packages/zendesk-adapter/src/filters/macro_attachments.ts

Two improvements:
- Changed to not create the full name of element id every time, which apparently takes a lot of time
- In https://github.com/salto-io/salto/pull/2172/files#diff-9dbe7ce03ec23e4cbc6ee78890e55f8501df20c904372e2bef6e1c9231784f72R43 we changed `getMergeableParentID` to look at the elements value instead of id to look for arrays, which takes a lot of time. I changed it to check if the value is array only if the id is array
Cloning our entire Jira dev account to another env would take 30 minutes, now it takes 1.2 minutes
---
_Core_:
- Performance improvements to element clone operation
---
None

SALTO-2879: element clone with many elements stuck

---

package.json
yarn.lock

Bump versions of lerna, @xmldom/xmldom and minimatch to avoid security vulnerabilities
---
lerna version bumped through package.json
@xmldom/xmldom and minimatch versions bumped by manually editing yarn.lock
---
_None_
---
_None_

SALTO-2872: upgrade vulnerable dependencies

---

packages/adapter-components/src/references/reference_mapping.ts
packages/adapter-components/test/references/field_references.test.ts
packages/adapter-utils/src/utils.ts
packages/jira-adapter/test/filters/fields/field_type_references.test.ts
packages/netsuite-adapter/test/transformer.test.ts
packages/salesforce-adapter/src/transformers/reference_mapping.ts
packages/salesforce-adapter/test/transformers/transformer.test.ts

From now on `element` will be a required argument for `getLookUpName`, this adds it and fixes all the current usages.
Adding in a separate PR as this adds some noise
---
Follow up for https://github.com/salto-io/salto/pull/3439 and https://github.com/salto-io/salto/pull/3438.
---
None
---
None

Require to pass in element to getLookUpName

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/change_validators/translation_for_default_locale.ts
packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/src/filters/article_body.ts
packages/zendesk-adapter/test/change_validators/translation_for_default_locale.test.ts
packages/zendesk-adapter/test/filters/article_body.test.ts

Adding a Zendesk filter of creating templateExpressions in article body values
To Do:
---
* Bugfix of not running the `onDeploy` filters has been added
---
* Support multi-env article bodies.
---

Salto 2572 handle article bodies

---

packages/adapter-api/src/element_id.ts
packages/adapter-api/test/elements.test.ts

---
Old code would add `field` even if "this" element ID was already a field :(
---
_None_
---
_None_

Fix getRelativeID for nested ids in fields

---

packages/cli/e2e_test/helpers/templates.ts
packages/cli/e2e_test/salto.test.ts
packages/salesforce-adapter/e2e_test/adapter.test.ts
packages/salesforce-adapter/src/filters/utils.ts
packages/salesforce-adapter/test/adapter.crud.test.ts
packages/salesforce-adapter/test/filters/utils.test.ts

_remove hardcoded annotations for custom objects deploy_
---
None
---
* remove hardcoded (pluralLabel, deploymentStatus, sharingModel and nameField) annotations for custom objects deploy
---
* None

SALTO-1444 remove hardcoded annotations for custom objects deploy

---

packages/netsuite-adapter/src/client/manifest_utils.ts
packages/netsuite-adapter/test/client/manifest_utils.test.ts

In some cases we have a NS reference to a customsegment that looks like `[type=customrecordcustomfield, script=customrecord*.cseg*]`. Like other NS references, we add that object dependency to the manifest.
The problem is that `customrecord*.cseg*` is not a real object in NS - It is used as a reference but it shouldn’t be included in the manifest.
---
- Remove wrong customsegment dependencies from manifest.xml
---
None

SALTO-2920 remove wrong customsegment dependencies from manifest.xml

---

packages/netsuite-adapter/src/change_validators/not_yet_supported_values.ts

_Error message in the NOT_YET_SUPPORTED updated_
---
_None_
---
_Netsuite adapter_:
* Error message updated to address the netsuite deploy troubleshooting doc
---
_None_

SALTO-2570: update NOT_YET_SUPPORTED change validator error messages

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/constants.ts
packages/jira-adapter/src/filters/data_center/filters_permissions.ts
packages/jira-adapter/src/filters/data_center/issue_events.ts
packages/jira-adapter/src/product_settings/data_center.ts
packages/jira-adapter/test/filters/data_center/filters_permissions.test.ts
packages/jira-adapter/test/filters/data_center/issue_events.test.ts

_Added support for add (post) for JIRA DC IssueEvents
Plugin part available [here_](https://github.com/salto-io/jira-dc-app/pull/18) and [here](https://github.com/salto-io/jira-dc-app/pull/16) 
---
It seems I did some mess here, did not merge the add part (which was reviewed) and overrode it with a push -f :man-facepalming:
The current push in OSS only involved the changes to delete and put in the data_center.ts file, and one line in the filter file (issue_events)- I removed a line that did not allow to update (I accidentally set before the id to be updateable = false )
Also renamed the folders and files
---
_None_
---
_None_

SALTO-2844: Jira DC support issueEvents- add, edit and delete

---

packages/jira-adapter/src/filters/fields/contexts.ts
packages/jira-adapter/src/product_settings/data_center.ts
packages/jira-adapter/test/filters/fields/field_deployment.test.ts

Added support for fields deployment in Jira DC
Plugin PR: https://github.com/salto-io/jira-dc-app/pull/19
---
None
---
None

SALTO-2843: Support fields deployment in Jira DC

---

packages/jira-adapter/src/filters/automation/automation_label/label_deployment.ts
packages/jira-adapter/src/filters/automation/automation_label/label_fetch.ts
packages/jira-adapter/test/filters/automation/automation_label/label_deployment.test.ts
packages/jira-adapter/test/filters/automation/automation_label/label_fetch.test.ts

Added support for automations labels in Jira DC
---
None
---
None

SALTO-2849: Support automations labels in Jira DC

---

packages/jira-adapter/src/product_settings/data_center.ts

_Add plugin urls for IssueTypeScreenScheme_
---
link to the plugin PR: https://github.com/salto-io/jira-dc-app/pull/20
---
_None_
---
_None_

SALTO-2910: add plugin urls for IssueTypeScreenScheme - Jira DC

---

packages/jira-adapter/src/change_validators/account_id.ts
packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/filters/automation/automation_deployment.ts
packages/jira-adapter/src/filters/automation/automation_fetch.ts
packages/jira-adapter/test/filters/automation/automation_deployment.test.ts
packages/jira-adapter/test/filters/automation/automation_fetch.test.ts

Added support for automation in Jira DC
----
There is a little difference in the requests in DC and Cloud (mainly the URL prefix and sometimes the HTTP method)
---
None
---
None

SALTO-2849: Support automations in Jira DC

---

packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts

---
---
- Delete the default SDF FileCabinet folder to prevent permissions error on deploy
---
None

SALTO-2946 Delete the default SDF FileCabinet folder to prevent permissions error on deploy

---

packages/zendesk-adapter/src/filters/brands_filter.ts
packages/zendesk-adapter/test/filters/categories_order.test.ts

Categories order in brand won't be created if guide isn't activated in Salto
---
_Release Notes:_
None
---
_User Notifications:_
None

Zendesk brand order hotfix

---

packages/adapter-api/src/values.ts
packages/workspace/src/workspace/state/index.ts
packages/workspace/src/workspace/state/static_files_sources/history_static_files_source.ts

Create getStaticFileUniqueName to use in `history_static_files_source.ts` and outside of the OSS
---
---
Adapter API:
- Create `getStaticFileUniqueName` that receives a `StaticFile` and returns a unique name (a concatenation of the filepath & hash) 
---
None

SAAS-6386 create getStaticFileUniqueName

---

packages/zendesk-adapter/src/change_validator.ts
packages/zendesk-adapter/src/change_validators/help_center_activation.ts
packages/zendesk-adapter/src/change_validators/help_center_creation_or_removal.ts
packages/zendesk-adapter/src/change_validators/index.ts
packages/zendesk-adapter/test/change_validators/help_center_activation.test.ts
packages/zendesk-adapter/test/change_validators/help_center_creation_or_removal.test.ts

_Add change validator for creation or removal of help center_
---
None
---
Zendesk:
* Add change validator for creation or removal of help center
---
None

SALTO-2914: change validator for creation or removal of help center

---

packages/salesforce-adapter/src/change_validators/flow_deletion.ts
packages/salesforce-adapter/test/change_validators/flow_deletion.test.ts

_fix the deletion of flows CV_
---
None
---
* fix the flow deletion change validator so it will not be able to delete flows
---
None

SALTO-2811 fix the deletion of flows CV

---

packages/adapter-utils/src/utils.ts
packages/adapter-utils/test/utils.test.ts

Instead of dumping the entire StaticFile object, just print its path (similar to what we do with references and element IDs)
---
_Additional Context_:
N/A
---
Improved logging of static files
---
N/A

SALTO-2891 - Improve logging of static files

---

packages/adapter-components/src/client/base.ts
packages/adapter-components/src/client/config.ts
packages/adapter-components/src/client/http_client.ts
packages/adapter-components/src/client/rate_limit.ts
packages/adapter-components/test/client/config.test.ts
packages/adapter-components/test/client/http_client.test.ts
packages/adapter-components/test/client/rate_limit.test.ts
packages/jira-adapter/config_doc.md
packages/jira-adapter/src/client/client.ts
packages/okta-adapter/config_doc.md
packages/okta-adapter/src/client/client.ts
packages/salesforce-adapter/src/client/client.ts
packages/stripe-adapter/config_doc.md
packages/stripe-adapter/src/client/client.ts
packages/workato-adapter/config_doc.md
packages/workato-adapter/src/client/client.ts
packages/zendesk-adapter/config_doc.md
packages/zendesk-adapter/src/client/client.ts
packages/zuora-billing-adapter/config_doc.md
packages/zuora-billing-adapter/src/client/client.ts

Support limiting requests in a specific timeframe and not only concurrent requests. This is needed at least for Zendesk and Okta, and will likely be useful in other adapters as well.
---
Using the simplest approach for now - one global limit in a constant timeframe, and without parsing headers (I think we should also add better handling for them, but since they will require per-adapter customization and some refactoring, I think it's best to do separately - see details in the ticket).
---
_Adapter Components_:
* Support limiting the number of API requests in a minute
* Limit the number of API requests in a minute
---
None

SALTO-2963 Support limiting requests per minute

---

packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/src/filters/user.ts
packages/zendesk-adapter/test/filters/user.test.ts

_Turn ids to emails in section, category and article translations_
---
None
---
None
---
None

SALTO-2967: turn ids to emails in section, category and article translations

---

packages/zendesk-adapter/src/change_validators/everyone_user_segment_modification.ts
packages/zendesk-adapter/test/change_validators/everyone_user_segment_modification.test.ts

Fix bug that's causing failures in zendesk deployments when Guide is disabled.
---
* Fix bug that caused a crash in deployments
---
None

SALTO-2983 Fix Everyone validator to not assume instance exists

---

packages/adapter-components/src/elements/request_parameters.ts
packages/adapter-components/test/elements/request_parameters.test.ts

When a query depends on other queries, avoid making multiple identical requests.
---
None
---
None

SALTO-2981 Avoid making multiple requests for identical dependsOn parameters

---

packages/zendesk-adapter/package.json
packages/zendesk-adapter/src/filters/custom_field_options/creator.ts
packages/zendesk-adapter/src/filters/handle_template_expressions.ts
packages/zendesk-adapter/test/filters/custom_field_options/ticket_field.test.ts
packages/zendesk-adapter/tsconfig.json

Based on @Eldardar 's analysis and replacing https://github.com/salto-io/salto/pull/3527/files.
This is an edge case - the correct solution would be to complete the support for template expressions in core, _and_ to avoid using `fullValue` to resolve references. But as a quick workaround, adding handling for the two cases where this can happen (we only resolve `fullValue` for ticket field options and user field options).
---
* Fix bug where creating a ticket or user field would fail if some of the options had templates in their name.
---
None

SALTO-2976 Resolve template expressions inside zendesk resolved ticket field options

---

packages/adapter-components/src/references/field_references.ts
packages/adapter-components/src/references/reference_mapping.ts
packages/adapter-components/test/references/field_references.test.ts
packages/zendesk-adapter/src/filters/custom_field_options/creator.ts

1. When using the `fullValue` serialization strategy, we should clone the values to avoid filters subsequently modifying the "referenced" resolved values (as was done in zendesk) and actually modifying the referenced instances' values
2. Fixing an inconsistency in how `getLookUpName`'s default serialization strategy was chosen (explicitly use `fullValue` as the fallback)
---
None (no impact on users)
---
None

SALTO-2988 clone non-primitive values on resolve

---

packages/zendesk-adapter/src/filters/article_body.ts
packages/zendesk-adapter/test/filters/article_body.test.ts

When replacing article's body urls with ReferenceExpression, keep the middle part (that includes the translation) the same
---
This is a temporary fix for now, there will be a follow up PR to handle these cases in a more generic way
---
- bugfix - Article's urls inside articles won't default to en-us, and will keep their original translation
---
None

SALTO-2958 - Zendesk adapter - Keep article ref url middle part the same

---

packages/zendesk-adapter/src/change_validators/child_parent/missing_from_parent.ts
packages/zendesk-adapter/src/change_validators/child_parent/removed_from_parent.ts
packages/zendesk-adapter/src/change_validators/child_parent/utils.ts
packages/zendesk-adapter/src/change_validators/duplicate_option_values.ts
packages/zendesk-adapter/src/change_validators/empty_custom_field_options.ts
packages/zendesk-adapter/src/change_validators/order.ts
packages/zendesk-adapter/src/constants.ts
packages/zendesk-adapter/src/filters/add_field_options.ts
packages/zendesk-adapter/src/filters/custom_field_options/ticket_field.ts
packages/zendesk-adapter/src/filters/custom_field_options/user_field.ts
packages/zendesk-adapter/src/filters/field_references.ts
packages/zendesk-adapter/src/filters/handle_app_installations.ts
packages/zendesk-adapter/src/filters/handle_template_expressions.ts
packages/zendesk-adapter/src/filters/organization_field.ts
packages/zendesk-adapter/src/filters/reorder/organization_field.ts
packages/zendesk-adapter/src/filters/reorder/user_field.ts
packages/zendesk-adapter/src/filters/tag.ts
packages/zendesk-adapter/src/group_change.ts
packages/zendesk-adapter/test/change_validators/missing_from_parent.test.ts
packages/zendesk-adapter/test/change_validators/removed_from_parent.test.ts
packages/zendesk-adapter/test/filters/add_field_options.test.ts
packages/zendesk-adapter/test/filters/organization_field.test.ts

A few improvements that will impact the following parent-child "pairs" in zendesk:
* business_hours_schedule + business_hours_schedule_holiday
* ticket_field + ticket_field__custom_field_options
* user_field + user_field__custom_field_options
* organization_field + organization_field__custom_field_options
* routing_attribute + routing_attribute_value
* dynamic_content_item + dynamic_content_item__variants
* article + article_translation
* section + section_translation
* category + category_translation
* macro + macro_attachment
* brand + brand_logo
1. Improve the change validator that identifies instances that still exist but are no longer referenced from the parent:
* For the _ticket/user/organization fields + options_ - the validator will return a warning, but users will still be able …

SALTO-2932 Improve parent-child change validators and deploy flow

---

packages/salesforce-adapter/src/adapter.ts

_Return fetchMetadataInstances to work in parallel and not sequential_
---
None
---
* Return fetchMetadataInstances to work in parallel and not sequential
---
None

SALTO-2997 Return fetchMetadataInstances to work in parallel and not sequential

---

packages/adapter-utils/src/utils.ts
packages/zendesk-adapter/src/change_validators/one_translation_per_locale.ts
packages/zendesk-adapter/test/change_validators/one_translation_per_locale.test.ts

It seems a combination of the fact that the validator did not expect to receive references + a problematic log + a recent change that added complex type dependency resulted in very slow deployments validations when a new translation instance is created. This should fix it.
---
None (not released yet)
---
None

SALTO-2998 fix one-translation-per-locale validator

---

packages/jira-adapter/src/product_settings/data_center/data_center.ts

_Add fieldConfigurationScheme plugin urls - Jira DC_
---
link to the plugin PR: https://github.com/salto-io/jira-dc-app/pull/25
---
_None_
---
_None_

SALTO-2585: add fieldConfigurationScheme plugin urls - Jira DC

---

eslintrc.js

Linter allows length of lines to be up to 120
---
There are some additional defaults that i've added, they are described in the link below
* I didn't add ignoreComments as a personal reference 
* I added ignoreRegExpLiterals as a personal reference and because we have some long regexes in our code
https://smartdevpreneur.com/how-to-use-and-disable-eslint-max-len-line-length-rule/#ESLint_Max-Len_Defaults:~:text=len%20rule.-,ESLint%20Max%2DLen%20Ignore%20Comments%2C%20URLs%2C%20Strings%2C%20and%20Template%20Literals,%E2%80%9CignoreTemplateLiterals%E2%80%9D%3A%20true,-Here%E2%80%99s%20an%20example
---
None
---
None

Lint max line length 120

---

packages/zendesk-adapter/src/config.ts

Order filters will use the correct client according to their brand's domain
---
None
---
None
---
None

Zendesk adapter - Order api calls will use the correct brand domain

---

packages/workspace/src/workspace/workspace.ts
packages/workspace/test/workspace/workspace.test.ts

Access to the adapter config element is required from the workspace API.
---
---
-
---
-

SALTO-2990 - Added shouldResolve flag to workspace.accountConfig

---

packages/netsuite-adapter/src/change_validators/dependencies.ts
packages/netsuite-adapter/src/change_validators/safe_deploy.ts
packages/netsuite-adapter/src/client/client.ts
packages/netsuite-adapter/src/data_elements/data_elements.ts
packages/netsuite-adapter/src/reference_dependencies.ts
packages/netsuite-adapter/src/suiteapp_config_elements.ts

This is a preparation for https://salto-io.atlassian.net/browse/SALTO-2805 - In order to avoid future casting of `Element[]` to `ChangeDataType[]`
---
---
None
---
None

SALTO-2805 use ChangeDataType instead of Element in proper places

---

packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/change_validator.ts
packages/netsuite-adapter/src/change_validators/client_validation.ts
packages/netsuite-adapter/src/client/client.ts
packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/src/errors.ts
packages/netsuite-adapter/test/adapter.test.ts
packages/netsuite-adapter/test/change_validator.test.ts
packages/netsuite-adapter/test/change_validators/client_validation.test.ts
packages/netsuite-adapter/test/client/client.test.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts

_SDF client validation changed to run server-side_
---
_None_
---
_Netsuite adapter_:
* Client validation now runs server side by default
* client_validation changeErrors severity changed to 'Error' from 'Warning'
* only ObjectValidation and manifestValidation Errors are supported, other validation errors are classified as 'SDF validation error'
---
_None_

SALTO-2804: Improve SDF client validation to run server-side validation

---

packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/product_settings/data_center/data_center.ts

Added support for groups in Jira DC
Plugin PR: https://github.com/salto-io/jira-dc-app/pull/28
---
None
---
None

SALTO-3011: Support groups in Jira DC

---

packages/netsuite-adapter/src/change_validators/client_validation.ts
packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/test/change_validators/client_validation.test.ts

we should return changeErrors for all changes when non of them is in `error.failedConfigTypes`
---
---
None
---
None

SALTO-2804 fix bug in client validation on SettingsDeployError

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/filters/issue_type.ts
packages/jira-adapter/test/filters/issue_type.test.ts

Replaced the value `subtask` in Jira DC with `hierarchyLevel` as it is in cloud.
Did to save work when creating the E2E for DC
---
In cloud the issue type has a `hierarchyLevel` values that is 0 for tasks and -1 for subtasks, this is the value we get from fetch and send to deploy. In DC we get from fetch a boolean value called `subtask` and send to deploy a `type` value that is either `standard` or `subtask`
---
None
---
None

SALTO-2987: Align issue type between Jira DC and Cloud

---

packages/jira-adapter/src/filters/field_configuration/field_configuration_dependencies.ts
packages/jira-adapter/test/filters/field_configuration/field_configuration_dependencies.test.ts

Fixed an issue where excluding FieldConfigurationScheme would cause the fetch the fail
---
- Fixed an issue where excluding FieldConfigurationScheme would cause the fetch the fail
---
None

SALTO-3013: Excluding FieldConfigurationScheme causes fetch to fail

---

packages/netsuite-adapter/src/change_validators/client_validation.ts
packages/netsuite-adapter/src/group_changes.ts
packages/netsuite-adapter/src/types/file_cabinet_types.ts
packages/netsuite-adapter/test/group_changes.test.ts

---
---
- Fix bug in client validation when a FileCabinet instance is referenced
---
None

SALTO-3016 fix bug in client validation when a FileCabinet instance is referenced

---

packages/salesforce-adapter/src/change_validator.ts
packages/salesforce-adapter/src/change_validators/fullname_changed.ts
packages/salesforce-adapter/src/types.ts
packages/salesforce-adapter/test/change_validators/fullname_change.test.ts

Add a change validator that ensures the fullName property was not changed
---
fullName is used to identify entities in SalesForce. If the user changes its value, they're going to have a Bad Time.
---
Deploy will now fail for SalesForce entities whose fullName value was changed
---
N/A

SALTO-2152 - Salesforce: ensure fullName is not changed

---

packages/jira-adapter/src/filters/field_configuration/field_configuration_dependencies.ts

Made the log too spammy in the last PR. It should be printed only when `fieldConfigurationScheme` is present but not reference 
---
None
---
None

SALTO-3013: fixed FieldConfigurationScheme warning log

---

packages/netsuite-adapter/src/filters/author_information/system_note.ts
packages/netsuite-adapter/test/filters/author_information/system_note.test.ts

query customrecords system notes only if needed
---
---
- Query customrecords system notes only if needed
---
None

SALTO-2995 query customrecords system notes only if needed

---

packages/core/src/api.ts
packages/core/test/api.test.ts

Add api exported from core to get adapters' configCreator.optionType by an adapter name
---
---
None
---
None

SAAS-6480_export_getAdapterConfigOptionsType_from_core

---

packages/jira-adapter/src/filters/automation/automation_structure.ts
packages/jira-adapter/test/filters/automation/automation_structure.test.ts

Fixed the automation scheme to work for automation with `value: ''`
I saw it in Jira DC but it's possible that it also affects cloud
---
None
---
None

SALTO-2987: fixed automation scheme

---

packages/salesforce-adapter/src/client/client.ts

Add 'socket hang up' to the list of errors that would cause us to retry
---
---
SalesForce adapter is more resilient in the face of errors from the SalesForce API
---
N/A

SALTO-2806 - SalesForce: Retry on socket hang up

---

packages/zendesk-adapter/src/adapter.ts

If a guide type is in 'SKIP_RESOLVE_TYPE_NAMES', map it to its brand correctly
---
None
---
None
---
None

Zendesk Adapter - Fix SKIP_RESOLVE Guide types to be deployed correctly

---

packages/zendesk-adapter/src/dependency_changers/guide_order_change.ts
packages/zendesk-adapter/src/dependency_changers/guide_order_changer.ts
packages/zendesk-adapter/src/dependency_changers/index.ts
packages/zendesk-adapter/src/dependency_changers/types.ts
packages/zendesk-adapter/test/dependency_changers/guide_order_change.test.ts

When removing guide order instance and it's parent, removed the dependency between them to break a circle
---
None
---
None
---
None

SALTO-3025 - Zendesk Adapter - Remove dependency between a guide order instance and its parent

---

packages/adapter-utils/src/collisions.ts
packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/src/filters/collision_errors.ts

Added a flag to disable the log that stringifies elements values
It will be used to stress test environments with many articles, because for some reason that stringify is really really slow
---
None
---
None
---
None

SALTO-3057 - Zendesk Adapter - Added a flag to disable collision value stringify

---

packages/zendesk-adapter/src/filters/handle_app_installations.ts
packages/zendesk-adapter/src/filters/handle_template_expressions.ts
packages/zendesk-adapter/test/filters/custom_field_options/ticket_field.test.ts
packages/zendesk-adapter/test/filters/handle_template_expressions.test.ts

_fix incorrect template expression to point at drop-down field and not at specific field option_
---
None
---
Zendesk:
* fix incorrect template expression to point at drop-down field and not at specific field option
---
Zendesk:
* fix incorrect template expression to point at drop-down field and not at specific custom field option. 
All placeholders in the form of {{ticket.ticket_field_ID}} or {{ticket.ticket_field_option_title_ID}} will change from {{${ zendesk.ticket_field.instance.<NAME> }}} to {{ticket.ticket_field_${ zendesk.ticket_field.instance.<NAME> }}}. 
This will happen for types: macros, webhooks, automations, triggers, app installations, targets and dynamic content items.

SALTO-3037: fix incorrect template expression to point at drop-down field and not at specific field option

---

packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts

Fix SDF deploy flag typo
---
---
- Fix pre-deploy error on ACCOUNT_SPECIFIC_VALUE
---
None

Fix SDF deploy flag typo

---

packages/okta-adapter/src/config.ts

Solve a bug causing AppUser instances in Okta to disappear every second fetch.
---
`AppUser` instances represent the assignment of user to app, those instances don't have a service id of their own, and the id that the service returns is actually the user id. 
Because the default `serviceIdField` for Okta is the field 'id', users assigned to more than one app created duplication which caused a merge error.
For now I removed the default `serviceIdField`, and later we will add a better solution.
---
_Okta adapter_
* Fix a bug causing AppUser instances to disappear every second fetch
---

SALTO-2755: Fix a bug causing AppUser instances to disappear - Okta

---

packages/salesforce-adapter/src/client/client.ts

For some reason the we are not retrying on this specific SF call even though we properly wrapped with retry logic.
I'm not sure if this will fix the actual root cause. I'm hopeful though.
---
None.
---
Improvement for SF fetch stability.
---
None

SALTO-2430 - Attempt to fix SF fetch stability

---

packages/zendesk-adapter/src/filters/article/utils.ts
packages/zendesk-adapter/test/filters/article/article.test.ts

This PR fix the bug where Zendesk drops article_attachment instances although their elemIDs are different
---
---
---

SALTO-3074 Edit Zendesk article_attachment elem name

---

packages/netsuite-adapter/src/client/sdf_client.ts

`SdfClient.listInstances` returns `savedcsvimport` object names with type `csvimport` so in case that we try to include (or exclude) `savedcsvimport` specifically (e.g. fetchTarget) we fail.
---
---
- Fix savedcsvimport SDF fetch
---
None

Fix savedcsvimport SDF fetch

---

packages/salesforce-adapter/cpq-sbaa-config-doc.md
packages/salesforce-adapter/src/config_creator.ts
packages/salesforce-adapter/src/types.ts

Instead of excluding all email templates, exclude only the problematic ones.
---
Marketo is an add-on for SalesForce that, among other things, handles promotional emails. They made the... interesting choice to create an email template for every email they send, resulting in tens of thousands of email templates. This leads to a less than stellar user experience.
---
Email templates are no longer excluded by default.
---
N/A

SALTO-2793 - SalesForce: only exclude Marketo email templates

---

packages/adapter-components/src/elements/request_parameters.ts
packages/adapter-components/test/elements/request_parameters.test.ts

The `dependsOn` config allows making requests that depend on earlier responses - e.g. making requests to `/workflows/{workflow_id}/export` where `workflow_id` are the resulting ids of earlier queries.
Until now we supported one parameter per URL - now we will be able to query all combinations of multiple parameters, e.g. make requests for `/api/v2/help_center{/locale}/sections/{section_id}/articles` that combine all possible values of locale + section id.
---
None (not user facing)
---
None

SALTO-3072 support multiple parameters in dependsOn configuration in simple adapters

---

packages/salesforce-adapter/src/adapter.ts
packages/salesforce-adapter/src/filters/field_references.ts
packages/salesforce-adapter/src/transformers/reference_mapping.ts

_create missing queues and emailTemplate references in cloud service objects_
---
None
---
* create missing queues and emailTemplate references in cloud service objects
---
* create missing queues and emailTemplate references in cloud service objects

SALTO-2816 SALTO-2820 SALTO-2822 SALTO-2823 create missing queues and emailTemplate references in cloud service objects

---

packages/salesforce-adapter/src/change_validator.ts
packages/salesforce-adapter/src/change_validators/case_assignmentRules.ts
packages/salesforce-adapter/src/types.ts
packages/salesforce-adapter/test/change_validators/case_assignmentRules.test.ts

_Add change Validator to prevent the deploy of Case AssignmentRules with Case team_
---
None
---
* Add change Validator to prevent the deploy of Case AssignmentRules with Case team
---
None

SALTO-2833 Add change Validator to prevent the deploy of Case AssignmentRules with Case team

---

packages/zendesk-adapter/src/change_validators/article_attachment_size.ts
packages/zendesk-adapter/test/change_validators/article_attachment_size.test.ts

_fix article attachment size validator bug_
---
None
---
None
---
None

SALTO-3049: fix article attachment size validator bug

---

packages/zendesk-adapter/e2e_test/adapter.test.ts
packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/adapter_creator.ts
packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/src/config_creator.ts
packages/zendesk-adapter/src/filters/collision_errors.ts
packages/zendesk-adapter/src/filters/everyone_user_segment.ts
packages/zendesk-adapter/src/filters/guide_create_element_translations.ts
packages/zendesk-adapter/src/filters/guide_locale.ts
packages/zendesk-adapter/src/filters/guide_order/article_order.ts
packages/zendesk-adapter/src/filters/guide_order/category_order.ts
packages/zendesk-adapter/src/filters/guide_order/section_order.ts
packages/zendesk-adapter/test/adapter.test.ts
packages/zendesk-adapter/test/config_creator.test.ts
packages/zendesk-adapter/test/filters/article/article.test.ts
packages/zendesk-adapter/test/filters/everyone_user_segment.test.ts
packages/zendesk-adapter/test/filters/guide_create_element_translation.test.ts
packages/zendesk-adapter/test/filters/guide_locale.test.ts
packages/zendesk-adapter/test/filters/guide_orders.test.ts

Replace `enableGuide` flag with with `guide` object and allow specify brands for fetch
---
I replaced the `enableGuide` config flag with `guide` object, so it would be easier to add another config options in the future.
For now, the only config option for `guide` object is `brands` that allows to specify the desired brands (or the unwanted) for fetch.
The brand list can have regex, but support only one negative regex for now.
---
Zendesk adapter
- enable fetch zendesk guide of specific brands.
---
none

SALTO-2964, SALTO-3071-Replace enableGuide flag with object & Allow limit guide for specific brands (Zendesk Guide)

---

packages/jira-adapter/src/product_settings/data_center/data_center.ts

Added support for modifying issue types in issue type scheme in Jira dc
Plugin PR: https://github.com/salto-io/jira-dc-app/pull/43
---
None
---
None

SALTO-3022: Support IssueType to IssueTypeScheme connection changes

---

packages/okta-adapter/src/config.ts

Remove `User` and `AppUser` types from default config 
---
I removed `User` and `AppUser` types from Okta's default config, and also group-user assignments.
The rest of the code still exists, so in case someone adds it to the config file everything should work as before (references, deploy..)
---
None
---
None

SALTO-3093: Remove User and AppUser types from default config (Okta)

---

packages/adapter-utils/src/list_comparison.ts
packages/adapter-utils/test/compare.test.ts

Fixed a bug in list comparison when comparing to lists without primitives
---
None
---
None

SAAS-6766: Wrong changes when comparing lists without primitives

---

packages/adapter-utils/src/compare.ts
packages/adapter-utils/test/compare.test.ts

When there is an object with keys that are numbers, applyDetailedChanges would mistakenly treat it as a list
---
_Core_: 
- Fixed regression in fetch when there is an object with keys that are numbers
---
None

SALTO-3146: apply detailed changes fails when there is an object that looks like a list

---

packages/okta-adapter/src/config.ts

Remove fields with references to `User` type from config 
---
I made 2 changes:
1. remove `recurseInto` for users related to `IdentityProvider`
2. add `createdBy` and `lastUpdatedBy` to `fieldsToOmit` - these fields are reference to `User` instances
---
None
---
None

SALTO-3093: Remove users from config (Okta)

---

packages/zendesk-adapter/src/config.ts

_remove updated and created fields from zendesk guide_
---
None
---
None
---
None

SALTO-3153: remove updated and created fields from zendesk guide

---

packages/zendesk-adapter/src/filters/field_references.ts
packages/zendesk-adapter/test/filters/field_references.test.ts
packages/zendesk-adapter/test/resolve_changes.test.ts

Workspace condition values must be strings - sending integers fails the deploy.
---
The same serialization strategy is used in a lot of other types as well, but so far it seems like the other types support serializing to numbers as well - so starting with the minimal fix to avoid introducing accidental regressions. if we see this happening on any of the other types, we will change the default to serializing to a string instead.
---
* Fix a bug where workspace creation would fail if the workspace had a `group_id` condition
---
None

SALTO-3163 Serialize ids to strings for workspace conditions

---

packages/salesforce-adapter/src/change_validators/multiple_defaults.ts
packages/salesforce-adapter/test/change_validators/multiple_defaults.test.ts

_fix multiple_defaults change validator_
---
None
---
* Fix multiple_defaults change validator that caused problems in deployments of Profiles
---
None

SALTO-2361  Fix multiple_defaults change validator

---

packages/zendesk-adapter/src/filters/field_references.ts

_zendesk add broken reference to view element_
---
None
---
zendesk:
* add broken reference to group id in view restriction
*  add broken reference to via_id in conditions
---
None

SALTO-3168, SALTO-3166: zendesk missing broken reference to group id in view restriction

---

packages/zendesk-adapter/src/filters/guide_arrange_paths.ts
packages/zendesk-adapter/test/filters/guide_arrange_paths.test.ts

_zendesk guide add type folders for order and settings elements_
---
None
---
None
---
None

SALTO-3046: zendesk guide add type folders for order and settings elements

---

packages/zendesk-adapter/src/config.ts

_zendesk guide hide updated and created by fields from translations_
---
None
---
None
---
None

SALTO-3153: zendesk guide hide updated and created by fields from translations

---

packages/adapter-components/src/elements/ducktype/index.ts
packages/adapter-components/src/elements/ducktype/transformer.ts
packages/adapter-components/test/elements/ducktype/transformer.test.ts
packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/test/adapter.test.ts

Change how we fetch guide from fetching each type across brands to fetch brand by brand to prevent unnecessary requests with `recurseInto` and `dependsOn`
---
With the previous fetch method we made unnecessary requests in each brand based on entries that returned from other brands. In this change we create the elements in each brand separately, this way recursive requests are done only on the relevant values.
The main flow of fetch now:
- Create all elements (instances and types) for each brand, ignoring `standaloneFields`
- Regenerate the types based on instances from all brands, ignore the types we created in the last step
- Recreating the instances with the correct type
- Creating instances from `standaloneFields`
I also exported function from …

SALTO-2982: Change guide fetch method to avoid unnecessary requests (Zendesk guide)

---

packages/netsuite-adapter/src/adapter_creator.ts

logging netsuite config without `lockedElementsToExclude`
---
---
None
---
None

log netsuite config

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/filters/guide_order/category_order.ts
packages/zendesk-adapter/src/filters/utils.ts
packages/zendesk-adapter/test/filters/utils.test.ts

Fix a bug causing `categories_order` instanceד of excluded brands to be created
---
Changes:
1. Move `getBrandsForGuide` func to utils.ts so we can use in filters too
2. Use `getBrandsForGuide` to calculate brands before creating `categories_order`  instances
3.  Added some tests
---
None
---
None

SALTO-3155: Fix bug causing categories_order instances of excluded brands to be created (Zendesk guide)

---

packages/netsuite-adapter/e2e_test/adapter.test.ts
packages/netsuite-adapter/scripts/types_generation/types_generator.py
packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/autogen/types/standard_types/entryForm.ts
packages/netsuite-adapter/src/autogen/types/standard_types/transactionForm.ts
packages/netsuite-adapter/src/change_validators/mapped_lists_indexes.ts
packages/netsuite-adapter/src/client/client.ts
packages/netsuite-adapter/src/custom_records/custom_record_type.ts
packages/netsuite-adapter/src/filters/convert_lists.ts
packages/netsuite-adapter/src/filters/convert_lists_to_maps.ts
packages/netsuite-adapter/src/filters/custom_records.ts
packages/netsuite-adapter/src/mapped_lists/mapping.ts
packages/netsuite-adapter/src/mapped_lists/utils.ts
packages/netsuite-adapter/test/adapter.test.ts
packages/netsuite-adapter/test/change_validators/mapped_lists_indexes.test.ts
packages/netsuite-adapter/test/custom_records/custom_record_type.test.ts
packages/netsuite-adapter/test/filters/convert_lists.test.ts
packages/netsuite-adapter/test/filters/convert_lists_to_maps.test.ts
packages/netsuite-adapter/test/filters/custom_records.test.ts
packages/netsuite-adapter/test/filters/omit_fields.test.ts
packages/netsuite-adapter/test/mapped_lists/utils.test.ts

In order to prevent unnecessary diffs between envs:
- Increase coverage of fields to transform from lists to maps
- Remove `index` field from unordered mapped lists
---
---
- Increase coverage of fields to transform from lists to maps
- Remove `index` field from unordered mapped lists
---
- More lists are going to be transformed to maps
- `index` field will be removed from maps that the original list is unordered

SALTO-2884 transform unordered lists to maps

---

packages/netsuite-adapter/src/query.ts
packages/netsuite-adapter/test/query.test.ts

Trying to exclude by a specific suffix in a specific folder makes a fetch throw:
The regex: `"^/SuiteScripts/test/[^/]+\\.xml"`
The Error: `Invalid regular expression: /^^/SuiteScripts/test/[$/: Unterminated character class`
This is caused by the way we create subregexes of file cabinet parent folders - we take all slices of the path but it can be invalid (like `^/SuiteScripts/test/[` ). We need to filter out all invalid subregexes.
---
---
- Support complex file cabinet regexes
---
None

SALTO-3193 Support complex file cabinet regexes

---

packages/jira-adapter/e2e_test/instances/datacenter/index.ts
packages/jira-adapter/e2e_test/instances/datacenter/priorityScheme.ts
packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/client/pagination.ts
packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/constants.ts
packages/jira-adapter/src/filters/data_center/priority_scheme/priority_scheme_deploy.ts
packages/jira-adapter/src/filters/data_center/priority_scheme/priority_scheme_fetch.ts
packages/jira-adapter/src/filters/data_center/priority_scheme/priority_scheme_project_association.ts
packages/jira-adapter/src/filters/data_center/priority_scheme/types.ts
packages/jira-adapter/src/filters/project.ts
packages/jira-adapter/src/filters/service_url/service_url_information.ts
packages/jira-adapter/src/product_settings/data_center/api_config.ts
packages/jira-adapter/src/reference_mapping.ts
packages/jira-adapter/test/filters/data_center/priority_scheme/priority_scheme_deploy.test.ts
packages/jira-adapter/test/filters/data_center/priority_scheme/priority_scheme_fetch.test.ts
packages/jira-adapter/test/filters/data_center/priority_scheme/priority_scheme_project_association.test.ts
packages/jira-adapter/test/filters/project.test.ts

Added support for fetching and deploying priority scheme and the association between project to priority scheme
---
None
---
None

SALTO-2978: Support priority scheme in Jira DC

---

packages/adapter-utils/src/utils.ts
packages/jira-adapter/src/filters/workflow/workflow_deploy_filter.ts
packages/zendesk-adapter/src/filters/app.ts
packages/zendesk-adapter/src/filters/app_owned_convert_list_to_map.ts
packages/zendesk-adapter/src/filters/article/utils.ts
packages/zendesk-adapter/src/filters/brand_logo.ts
packages/zendesk-adapter/src/filters/hardcoded_channel.ts
packages/zendesk-adapter/src/filters/macro_attachments.ts
packages/zendesk-adapter/src/filters/reorder/creator.ts

`safeJsonStringify` can traverse inside the `resValue` of expressions when not using the replacer - this causes very long logs in some cases.
---
None
---
None

SALTO-3115 avoid logging inside expressions

---

packages/adapter-components/src/elements/ducktype/transformer.ts
packages/workato-adapter/src/adapter.ts
packages/zendesk-adapter/config_doc.md
packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/src/filters/guide_default_language_settings.ts
packages/zendesk-adapter/test/adapter.test.ts

Main changes:
- alert the user in case no brand matches the provided `brands` regex list in `guide` config.
- change behavior when `brands = []` in config 
---
I added the option to return fetch error when calling `getAllElements` in ducktype.
In case there's no brand match we'll return the default Zendesk elements & non brand specific guide elements and notify the user about it.
Also, to be consistent with the case of `brands = []`, we will now get guide elements that are not part of specific brand (`user_segments`, `permission_groups` types).
---
None
---
None

SALTO-3181: Return fetch warning when no brand matches brands list in guide config

---

packages/salesforce-adapter/cpq-sbaa-config-doc.md

A small change in the example for CPQ config.
---
_None_
---
_None_

SALTO-3215: Invalid CPQ default config 

---

packages/zuora-billing-adapter/src/client/client.ts
packages/zuora-billing-adapter/test/client/client.test.ts

Zuora sometimes returns 404 - currently this can fail fetching an entire type, but it should just treat the response as empty. 
---
This will align the client with the behavior in zendesk and jira.
---
_Zuora-Billing adapter_:
* When some requests for a specific type return 404, only omit them instead of omitting the response for the entire type
---
_Zuora-Billing adapter_:
* In some accounts, this may bring back `WorkflowExport`, `Workflow` and `Task` instances that were previously omitted

SALTO-3216 gracefully handle Zuora 404 responses

---

.circleci/build-images/e2e-test/.dockerignore
.circleci/build-images/e2e-test/Dockerfile
.circleci/build-images/e2e-test/build.sh
.circleci/config.yml
packages/netsuite-adapter/README.md
packages/netsuite-adapter/package.json
yarn.lock

Tested locally:
1. Fetched Dilly with previous version
2. Fetched Dilly with the new version
3. Verified there are no changes in the nacls
4. Deployed CustomRecord and CustomField.
---
Netsuite Adapter: SALTO-2749: Upgrade NetSuite SDF version to 2022.2.1
---
Netsuite Adapter: For existing Salto Workspaces, you should reinstall the NetSuite service by creating a temporary Salto Workspace and calling salto `service add netsuite --no-login`.
This will download the new SDF version that will be used globally for all WSs. The temporary Salto Workspace can be deleted.
In addition, as part of SDF requirements, Java 17 is required.

SALTO-2749: Upgrade NetSuite SDF version to 2022.2.1

---

packages/jira-adapter/e2e_test/instances/datacenter/automation.ts
packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/change_validators/account_id.ts
packages/jira-adapter/src/change_validators/wrong_user_permission_scheme.ts
packages/jira-adapter/src/config/config.ts
packages/jira-adapter/src/filters/account_id/add_display_name_filter.ts
packages/jira-adapter/src/filters/account_id/user_id_filter.ts
packages/jira-adapter/src/filters/permission_scheme/wrong_user_permission_scheme_filter.ts
packages/jira-adapter/src/users_map.ts
packages/jira-adapter/test/adapter.test.ts
packages/jira-adapter/test/change_validators/account_id.test.ts
packages/jira-adapter/test/change_validators/wrong_user_permission_scheme.test.ts
packages/jira-adapter/test/filters/account_id/account_id_common.ts
packages/jira-adapter/test/filters/account_id/user_id_filter.test.ts
packages/jira-adapter/test/filters/permission_scheme/wrong_user_permission_scheme_filter.test.ts
packages/jira-adapter/test/utils.ts

_Convert users Id with their Username _
---
_changed it by expanding `display_name_filter` functionality, while using Jira DC it will perform:_
before: 
`{
id = "JIRAUSER1000"
}`
after:
`{
id = "username"
}`
---
_None_
---
_None_

SALTO-2947: support user display name in Jira DC

---

packages/salesforce-adapter/src/client/client.ts

added retry on another sf endpoint. We were missing a retry which caused some fetches to fail.
---
None.
---
Stabilize salesforce fetch on sporadic failures
---
None.

SALTO-3087 - added retry on another sf endpoint

---

packages/adapter-components/src/references/field_references.ts
packages/salesforce-adapter/src/transformers/reference_mapping.ts
packages/salesforce-adapter/test/filters/field_references.test.ts
packages/salesforce-adapter/test/mock_elements.ts

_Flows missing references to custom labels_
---
tested fetch and deploy
---
* Add reference to CustomLabel in flow's inputAssignments
---
* create reference in the relevant flow's fields

SALTO-2927 Flows-missing-references-to-custom-labels

---

packages/zendesk-adapter/src/filters/handle_template_expressions.ts
packages/zendesk-adapter/test/filters/handle_template_expressions.test.ts

_fix missing zendesk template expression in macro action value fields_
---
None
---
None
---
None

SALTO-3212: fix missing zendesk template expression in macro action value fields

---

packages/adapter-components/src/deployment/deployment.ts

On deployment of instances, a debug log will be created with the details of the deployment
---
None
---
None
---
None

SALTO-3211 - Added logs to deployments with the data of the deployment

---

packages/adapter-components/src/config/ducktype.ts
packages/adapter-components/src/config/index.ts
packages/adapter-components/src/config/shared.ts
packages/adapter-components/src/filters/hide_types.ts
packages/adapter-components/src/filters/index.ts
packages/adapter-components/test/config/shared.test.ts
packages/adapter-components/test/filters/hide_types.test.ts
packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/adapter_creator.ts
packages/jira-adapter/src/config/config.ts
packages/jira-adapter/src/filters/common.ts
packages/okta-adapter/src/adapter.ts
packages/okta-adapter/src/config.ts
packages/okta-adapter/src/filters/common.ts
packages/stripe-adapter/src/adapter.ts
packages/stripe-adapter/src/config.ts
packages/stripe-adapter/src/filters/common.ts
packages/workato-adapter/src/adapter.ts
packages/workato-adapter/src/config.ts
packages/workato-adapter/src/filters/common.ts
packages/workato-adapter/test/filters/referenced_id_fields.test.ts
packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/src/filters/common.ts
packages/zendesk-adapter/test/filters/referenced_id_fields.test.ts
packages/zuora-billing-adapter/src/adapter.ts
packages/zuora-billing-adapter/src/config.ts
packages/zuora-billing-adapter/src/filters/common.ts
packages/zuora-billing-adapter/test/adapter.test.ts

* support `hideTypes` in swagger-based simple adapters as well
* refactor common filters to include `hideTypes` and `referencedInstanceNames`
---
Will add noise-reduction before merging
---
* The types folder will be hidden by default
_Stripe adapter_:
* The types folder will be hidden by default
* The types folder will be hidden by default
_Zuora-Billing adapter_:
* The system types folder will be hidden by default. Standard and custom object definitions will still be visible.
---
* The types folder will be hidden by default
_Stripe adapter_:
* The types folder will be hidden by default
* The types folder will be hidden by default
_Zuora-Billing adapter_:
* The system types folder …

SALTO-2909 hide types by default in all simple adapters

---

packages/zendesk-adapter/e2e_test/mock_elements.ts

Seems the flags are either getting deprecated or temporarily disabled, and this is causing e2e failures (cc @edenhassid who found this)
---
None
---
None

SALTO-3257 set deprecated flags to false

---

packages/salesforce-adapter/src/fetch_profile/metadata_query.ts

Excluding the `ForecastingCategoryMapping` CustomObject instance to avoid possible conflicts with the MetadataType ForecastingCategoryMapping.
---
_None_
---
_None_

SALTO-2632: Avoid possible type conflicts upon partial fetch

---

packages/adapter-components/src/filters/referenced_instance_names.ts
packages/adapter-components/test/filters/referenced_instance_name.test.ts
packages/zendesk-adapter/src/adapter.ts

Looks like any template expressions created before the rename filter is run are not updated.
---
None (no impact on users)
---
None

SALTO-3254 rename ids inside template expressions

---

packages/adapter-components/src/elements/swagger/swagger.ts
packages/adapter-components/test/elements/swagger/swagger.test.ts
packages/lowerdash/src/promises/timeout.ts
packages/lowerdash/test/promises/timeout.test.ts
packages/salesforce-adapter/src/custom_object_instances_deploy.ts

Add delay before retrying, to improve our chances of succeeding on 503 and similar transient errors.
Also change to only retry on HTTP errors (right now we also retry when there are parsing errors / inconsistency in the swagger)
---
None
---
None

SALTO-3333 Add delay before swagger url retry

---

packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/filters/notification_scheme/notification_scheme_deployment.ts
packages/jira-adapter/src/product_settings/cloud.ts
packages/jira-adapter/src/product_settings/data_center/api_config.ts
packages/jira-adapter/src/product_settings/data_center/data_center.ts
packages/jira-adapter/test/filters/notification_scheme/notification_scheme_deployment.test.ts

_add notificationScheme plugin urls_
---
* few modifications to make Jira DC not using JSP calls when deploying notification schemes
* link to the plugin PR [here](https://github.com/salto-io/jira-dc-app/pull/45)
---
_None_
---
_None_

SALTO-3027: add notificationScheme plugin urls

---

packages/cli/src/commands/account.ts
packages/zendesk-adapter/e2e_test/adapter.ts
packages/zendesk-adapter/e2e_test/jest_environment.ts
packages/zendesk-adapter/specific-cli-options.md
packages/zendesk-adapter/src/adapter_creator.ts
packages/zendesk-adapter/src/auth.ts
packages/zendesk-adapter/src/client/client.ts
packages/zendesk-adapter/src/client/connection.ts
packages/zendesk-adapter/test/adapter_creator.test.ts
packages/zendesk-adapter/test/client/connection.test.ts

To allow custom domains in Zendesk, this PR add a new optional `domain` param in zendesk login that would override the default `zendesk` domain
---
- `domain` field was added to zendesk's credentials types that would override `zendesk` domain
- credentials type fields marked with `_required = false` can be skipped when connecting a new account
will add some tests later
---
zendesk:
- When connecting a new zendesk account via CLI, user can provide custom domain that would replace `zendesk` domain
---
None

SALTO-3267: Add domain as optional login param in Zendesk

---

packages/jira-adapter/src/config/api_config.ts

Fixed Jira API config to avoid creating redundant warnings about the types IssueTypeSchemeMappings FieldsConfigurationIssueTypeItem IssueTypeScreenSchemeItems not having endpoints. This is because the types are in the SUPPORTED_TYPES although they shouldn’t be because they are used only in recurseInto
---
None
---
None

SALTO-3360: Fixed redundant warnings in Jira adapter fetch

---

packages/jira-adapter/src/filters/issue_type_schemas/issue_type_scheme_references.ts
packages/jira-adapter/test/filters/issue_type_schemas/issue_type_scheme_references.test.ts

Fixed Jira first fetch in `atlas-run`
---
None
---
None

SALTO-3083: Jira DC: Fetch fails when creating a new server without adding an issue type 

---

packages/workspace/index.ts
packages/workspace/src/workspace/element_selector.ts
packages/workspace/test/element_selector.test.ts

A synchronous version for selectElementsBySelectors that will improve performance for use cases where there is no need to get referenced elements.
---
also added a small refactor to the existing code since the array matches wasn't in use so that code was redundant.
---
none.
---
none.

Salto 3204 - Performance improvement of Elements By Selectors

---

packages/core/src/core/deploy/deploy_actions.ts

Make NodeSkippedError to contains the skipped node
---
Please see [ticket](https://salto-io.atlassian.net/jira/software/c/projects/SALTO/issues/SALTO-3031?filter=myopenissues)
As I implement this messaging ticket, I see that the error is thrown from dag package which is a graph package that isn't necessarily in deploy context. So I decided to add the parent of skipped node to NodeSkippedError type, and use it to re-messaging the error on deployActions. WDYT?
---
None
---
None

SALTO-3031_NodeSkippedError_does_not_contain_the_skipped_node

---

packages/jira-adapter/src/change_validators/dashboard_layout.ts
packages/jira-adapter/test/change_validators/dashboard_layout.test.ts

Fixed a bug where the dashboard layout validator would throw an error if the dashboard does not have gadgets
---
- Fixed a bug where the dashboard layout validator would throw an error if the dashboard does not have gadgets
---
None

SALTO-3370: fixed dashboard validator where are are not gadgets

---

packages/zendesk-adapter/src/filters/article/article_body.ts
packages/zendesk-adapter/test/filters/article/article_body.test.ts

Avoid creating references in article body for excluded brands
---
When `article_translation` body contains a url and the linked brand wasn't included in our guide config, we replaced it with missing references. 
Now we'll avoid creating this reference (and leave the url as it is), and alert to user about it.
---
None
---
None

SALTO-3306: Avoid creating references in article body for excluded brands

---

packages/jira-adapter/src/change_validators/permission_type.ts
packages/jira-adapter/test/change_validators/permission_type.test.ts

the code crashed trying to map an undefined field, i made sure we dont assume it exists.
added ut for it.
---
---
---

SALTO-3084/fix permission deploy crash

---

packages/salesforce-adapter/src/adapter_creator.ts
packages/salesforce-adapter/src/change_validator.ts
packages/salesforce-adapter/src/change_validators/omit_data.ts
packages/salesforce-adapter/src/types.ts
packages/salesforce-adapter/test/change_validator.test.ts
packages/salesforce-adapter/test/change_validators/omit_data.test.ts

_Allow users to user config on checkOnly CV_
---
None
---
CheckOnly change Validator are now configurable via config overrides
---
None

SALTO-3136 SF - Allow users to user config on checkOnly CV

---

packages/jira-adapter/src/filters/sort_lists.ts
packages/jira-adapter/test/filters/sort_lists.test.ts

sorted the following list fields
project role - actors field - by display name
dashboard - gadgets field - by each gadget's id
workflow Transition - properties field - by each property name (not id because its not in dc).
workflow status - properties field - by key 
---
---
---
jira_adapter:
the following list fields are now being sorted on fetch to avoid file changes noise
dashboard.gadgets
workflow.Transition.properties
workflow.statuses.properties
projectRole.actors

SALTO-2902/sort list fields

---

packages/salesforce-adapter/src/fetch.ts
packages/salesforce-adapter/test/adapter.discover.test.ts
packages/salesforce-adapter/test/fetch_installed_packages_layout.test.ts

Layout instances from installed package to objects from another package were not fetched due to assumption that always added the namespace to the Object name upon fetch.
---
before [this](https://github.com/salto-io/salto_private/pull/4818) noise suppression PR is merged.
I did test this on my CPQ org and removing this statement didn't delete any layouts, so I feel pretty comfortable with removing the problematic code.
---
- Support fetching Layout instances from installed package to Objects outside the package.
---
_None_

SALTO-2427: Support fetch of Layout instances to standard objects within installed packages

---

packages/workato-adapter/src/client/client.ts
packages/workato-adapter/test/client/client.test.ts

Bugfix - repair fetch. This PR ignore the page /roles when it gets 400.
____________________________________________________________________________________
As part of the new Workato environment feature. Team Management is viewd only in dev environment. At another environment all pages of Team managment (/roles only for now) will return 400 (Error - Bad Request). For now, we ignore this page when it gets 400.
____________________________________________________________________________________
Release Notes:
_Workato Adapter_:
* Avoid failing fetch on non-dev environments due to a failure to get roles
____________________________________________________________________________________
User Notifications:
None

SALTO-2701 new getSinglePage for workato

---

packages/jira-adapter/src/filters/workflow_scheme.ts
packages/jira-adapter/test/filters/workflow_scheme.test.ts

Fixed a bug where a deployment of a workflow scheme without items would not change the items in the service
---
__Jira-adapter__:
- Fixed a bug where a deployment of a workflow scheme without items would not change the items in the service
---
None

SALTO-3369: Deploying WorkflowScheme without items does not delete the items in the service

---

packages/jira-adapter/src/change_validators/wrong_user_permission_scheme.ts
packages/jira-adapter/src/filters/account_id/user_id_filter.ts
packages/jira-adapter/src/filters/permission_scheme/wrong_user_permission_scheme_filter.ts
packages/jira-adapter/test/filters/account_id/user_id_filter.test.ts

_fix a bug with Users Id in Jira DC_
---
_The bug came from differences between our development DC local server to a real DC server_
* make the part in `user_id_filter` where we convert the userName to userKey and backwards only for automation instances (`preDeploy` and `onDeploy` - which is needed only for them.
* added a suitable `idMap` to `wrong_user_permission_scheme_filter` and to `wrong_user_permission_scheme` (change validator) to support DC userNames 
---
_None_
---
_None_

SALTO-3303: fix a bug with users Id - Jira DC

---

packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/change_validators/screen_scheme_default.ts
packages/jira-adapter/src/constants.ts
packages/jira-adapter/test/change_validators/screen_scheme_default.test.ts

Added a change validator to prevent deploying a screen scheme without a default screen
---
---
- Added a change validator to prevent deploying a screen scheme without a default screen
---
None

SALTO-3324: Creating a screenScheme without a default screen should be blocked screen

---

packages/jira-adapter/src/filters/screen/screenable_tab.ts

Adding fields to a screen in parallel can cause the next requests on the screen to return 500 (due to a Jira bug) so I change it to run sequentially (just in case I did it also for fields removal)
---
- Fixed a bug where modifying a screen would return 500 sometimes
---
None

SALTO-3357: Internal error 500 is thrown when reordering fields in screen

---

packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/change_validators/workflow_scheme_dups.ts
packages/jira-adapter/test/change_validators/workflow_scheme_dups.test.ts

Added validation for workflow scheme name uniqueness on deploy
---
---
Added validation for workflow scheme name uniqueness on deploy
---
None

SALTO-3343: WorkflowShcemes' names can be modified to existing names 

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/change_validators/order.ts
packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/src/constants.ts
packages/zendesk-adapter/src/filters/field_references.ts
packages/zendesk-adapter/src/filters/reorder/ticket_form.ts
packages/zendesk-adapter/src/filters/ticket_form.ts
packages/zendesk-adapter/test/filters/ticket_form.test.ts

_fix deployment error of ticket form when `required_on_statuses` has both `statuses` and `custom_statuses` fields_
---
---
* zendesk:
fix deployment error of ticket form when `required_on_statuses` has both `statuses` and `custom_statuses` fields
---
None

SALTO-3376: cannot deploy ticket form when `required_on_statuses` has both `statuses` and `custom_statuses` fields

---

packages/zendesk-adapter/src/filters/view.ts
packages/zendesk-adapter/test/filters/view.test.ts

_fix deployment of a view that contains `custom_statuse_id`_
---
---
Zendesk:
* fix deployment of a view that contains `custom_statuse_id`.
---
None

SALTO-3392: fix deployment of a view that contains `custom_statuse_id`

---

packages/salesforce-adapter/src/client/client.ts

retry sf request on INTERNAL_ERROR response
---
None.
---
SF fetch stability improvement.
---

SALTO-3088 - retry sf request on INTERNAL_ERROR response

---

packages/okta-adapter/src/config.ts
packages/okta-adapter/src/reference_mapping.ts

Some config changes to make Okta nacls better 💯 
---
Changes:
- Hide `id` field from all types (except nested types and setting types)
- Omit `_links` field from all relevant types
- Add missing fields from type definitions with `fieldTypeOverrides`
- Omit more secret fields
- remove duplicate type: 'AuthorizationPolicy` (fetched as part of `recurseInto` of `AuthorizationServer`
- Add one reference from `PolicyRule` type to `UserType` type
---
None
---
None

SALTO-2699: Clean Okta nacls

---

packages/adapter-components/src/client/pagination.ts
packages/adapter-components/test/client/pagination.test.ts
packages/jira-adapter/src/client/pagination.ts
packages/jira-adapter/src/users_map.ts
packages/jira-adapter/test/filters/account_id/user_id_filter.test.ts

_get all the pages of users while creating idMap_
---
when I attempt to perform fetch and deploy in DC 9 server (with 21,000 users) I found out few bugs. 
In this PR I fixed those issues: 
* get all the pages of users instead of only the first one
* get the maximum amount of users in each get request (1000) instead of the adapter default (50) 
---
_None_
---
_None_

SALTO-3385: get all the pages of users while creating idMap - Jira DC

---

packages/zendesk-adapter/src/change_validator.ts
packages/zendesk-adapter/src/change_validators/brand_creation.ts
packages/zendesk-adapter/test/change_validators/brand_creation.test.ts

_improve subdomain handling when creating brands_
---
None
---
Zendesk:
* check availability of subdomain before creation of brand
---
None

SALTO-3114: improve subdomain handling when creating brands

---

packages/netsuite-adapter/src/config.ts
packages/netsuite-adapter/src/constants.ts

---
---
SALTO-3402: Omit CustomRecordType's "permissions" field by default for new WSs
---
None

SALTO-3402: Omit CustomRecordType's "permissions" field by default

---

packages/salesforce-adapter/src/metadata_deploy.ts

_changed error logs to be adaptive to validation_
---
---
None
---
None

SALTO-3130 SF - changed error logs to be adaptive to validation

---

packages/salesforce-adapter/src/change_validator.ts
packages/salesforce-adapter/src/change_validators/animation_rule_recordtype.ts
packages/salesforce-adapter/src/types.ts
packages/salesforce-adapter/test/change_validators/animation_rule_recordtype.test.ts

Add a change validator to ensure there's a RecordTypeId if the RecordTypeContext requires one
---
If AnimationRule.RecordTypeContext is 'Custom' then there needs to be a RecordTypeId that refers to the record type. Otherwise we get the following error on deploy:
```
If you don’t specify a RecordTypeId, the value of RecordTypeContext must be All or Master.
```
---
Salesforce: Improved validation of AnimationRule instances
---
N/A

SALTO-3122 - Salesforce: Change validator for AnimationRule.RecordTypeId

---

packages/workato-adapter/src/auth.ts
packages/workato-adapter/src/client/connection.ts
packages/workato-adapter/test/adapter.test.ts
packages/workato-adapter/test/client/client.test.ts
packages/workato-adapter/test/client/connection.test.ts

Update Workato auth headers to the new format:
* API key was replaced by token (but we already called it token)
* Username is no longer needed (but still collecting it for now, until we finish the migration)
* Switching the auth headers from `x-user-email` and `x-user-token` to `Authorization: Bearer <token>`
Note that this will only take effect *when the username is not specified* - in order to allow for a migration period.
Will follow up with a separate documentation PR with auth instructions.
---
Note: Still needs to be tested after the migration happens tonight - but preparing a PR so we can bump this ASAP if it works as expected. 
Existing authentication API keys should remain usable in the new headers (but will confirm before merging)
See additional details in the ticket.
--- …

SALTO-3412 Update Workato auth headers

---

packages/jira-adapter/src/filters/share_permission.ts
packages/jira-adapter/test/filters/share_permission.test.ts

Fixed creating a shared permission of a project role
---
- Fixed creating a shared permission of a project role
---
None

SALTO-3281: project role in filter shared permission is not created

---

packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/change_validators/issue_type_scheme_default_type.ts
packages/jira-adapter/test/change_validators/issue_type_scheme_default_type.test.ts

Added change validator for when setting a default type in an issue type scheme that is not present in the types of the scheme
---
- Added change validator for when setting a default type in an issue type scheme that is not present in the types of the scheme 
---
None

SALTO-3296: deleting issueTypeScheme defaultIssueTypeId from the issueTypeIds list does not delete it from the field defaultIssueTypeId

---

packages/jira-adapter/src/config/api_config.ts

_Removed the `deleted` field, it appears only on DC9 and not cleared why it is there_
---
---
None
---
None

SALTO-3421: Jira DC component deployment fails

---

packages/zendesk-adapter/e2e_test/adapter.test.ts
packages/zendesk-adapter/src/filters/article/article.ts

_fix zendesk e2e second try_
---
---
---

SALTO-3408: fix zendesk e2e second try

---

packages/zendesk-adapter/e2e_test/adapter.test.ts
packages/zendesk-adapter/src/change_validator.ts
packages/zendesk-adapter/src/change_validators/index.ts
packages/zendesk-adapter/src/change_validators/macro.ts
packages/zendesk-adapter/src/change_validators/macro_actions.ts
packages/zendesk-adapter/src/change_validators/side_conversation.ts
packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/src/constants.ts
packages/zendesk-adapter/src/filters/macro_attachments.ts
packages/zendesk-adapter/test/adapter.test.ts
packages/zendesk-adapter/test/change_validators/macro.test.ts
packages/zendesk-adapter/test/change_validators/macro_acitions.test.ts
packages/zendesk-adapter/test/change_validators/side_conversation.test.ts
packages/zendesk-adapter/test/filters/macro_attachments.test.ts

Verify side conversations enabled before deployment of a macro with side conversation action fields
---
Macros have actions that might include side conversations. There're 3 types of side conversations that can be activated in the account, the activation status of each of those features can be found in `account_features` settings instance.
This change adds the `account_features` instance and a change validator that use it to verify that all side conversation fields in the changed `macro` instance are enabled before deployment.
I kept `account_features` instance visible, it's not deployable and there's a change validator alerting this when trying to deploy the instance. will also add noise reduction before merging.
---
- Users will be notified when …

SALTO-3218: Verify side conversations enabled before deployment of a macro with side conversation action fields

---

packages/cli/package.json
packages/cli/src/command_builder.ts
packages/cli/src/command_register.ts
packages/cli/test/cli.test.ts
yarn.lock

Multi-line descriptions of commands are automatically shortened when showing help on parent command. 
---
Updated commander package 6.2.1->10.0.0 and added a `summary` field to be used for a shorter explanation whenever required. 
---
CLI:
* cleaner help view when subcommand has multi-line description
---

SALTO-2406 CLI help message for salto service command use short help message

---

packages/jira-adapter/src/change_validators/account_id.ts
packages/jira-adapter/test/change_validators/account_id.test.ts

_Add a DC option to account_id validator_
---
fix a bug in account_id validator that did not catch that the accountId was invalid while using Jira DC
---
_None_
---
_None_

SALTO-3416: add a DC option to account_id validator  - Jira DC

---

packages/salesforce-adapter/src/change_validators/unknown_users.ts
packages/salesforce-adapter/test/change_validators/unknown_users.test.ts
packages/salesforce-adapter/test/mock_elements.ts

Use the existing infrastructure to ensure that if FolderShare.sharedTo represents a user, that use exists in the target env.
---
N/A
---
Salesforce: Improved validation of FolderShare instances
---
N/A

SALTO-3440 - Salesforce: validate FolderShare.sharedTo user

---

packages/jira-adapter/e2e_test/instances/cloud/filter.ts
packages/jira-adapter/src/config/api_config.ts

_Also add E2E_
---
_tested with all different permission options. Does not impact the cloud. User filter is working properly_
---
**Jira Adapter:**
- Added edit permissions to filters
---
_Jira: Edit permissions will be added to Jira's NaCls (when available)_

Salto-2861: Add edit permissions to Jira cloud's filters

---

packages/jira-adapter/src/filters/security_scheme/security_scheme.ts
packages/jira-adapter/test/filters/security_scheme.test.ts

_were not grouped on delete. In the cloud the API is tolerant to a level delete that does not exist_
---
None
---
None

SALTO-3278: Jira Group Security Level and Scheme on delete

---

packages/jira-adapter/src/deployment/jsp_deployment.ts
packages/jira-adapter/test/deployment/jsp_deployment.test.ts

_Happens on cloud only_
---
None
---
None

SALTO-3463: Delete security level that fails with 500 shown as success

---

packages/zendesk-adapter/src/filters/user.ts
packages/zendesk-adapter/test/filters/user.test.ts

Replace additional fields from user ids to emails in Zendesk
Will add noise reduction pr before merging
---
found 2 more places to replace user ids with emails:
1. `workspace`  instances might have `condition` fields that can have user ids
2. `ticket_field` instance of type "lookup" with target "ticket" might have user ids
---
None
---
Zendesk:
- In workspace instances, internal user ids in conditions will be replaced with email addresses
- In ticket_field instances of type 'lookup' and target type of 'ticket', internal user ids will be replaces with email addresses

SALTO-3444: Replace additional fields from user ids to emails in Zendesk

---

packages/salesforce-adapter/src/client/jsforce.ts
packages/salesforce-adapter/src/metadata_deploy.ts
packages/salesforce-adapter/test/adapter.crud.test.ts
packages/salesforce-adapter/test/connection.ts

Errors that are inside the `errorMessage` field will be propagated to the user
---
---
* Deploy failure with `errorMessage` is now propagated to the user
---
_User Notifications_: _None

SALTO-2828: No errors are displayed upon deployment that fails on UNKNOWN_EXCEPTION from Salesforce

---

packages/jira-adapter/src/config/api_config.ts

Fixed a bug where a new contexts of existing fields would be written not under the field folder
---
The issue was that in existing fields, their path in the element was their element name which is different than their real path. The `fileNameFields` makes the path be by the name value and not by the element name which fixes it
---
- Fixed a bug where a new contexts of existing fields would be written not under the field folder
---
None

SALTO-3469: New contexts of existing fields are created in the wrong locations

---

packages/salesforce-adapter/src/client/types.ts
packages/salesforce-adapter/src/constants.ts
packages/salesforce-adapter/src/transformers/xml_transformer.ts

Deployed `MetadataRelationship` CustomField was missing the `referenceTo` annotation which caused failure.
---
There was special handling for field types that have the `referenceTo` annotations [here](https://github.com/salto-io/salto/blob/main/packages/salesforce-adapter/src/client/types.ts#L227), but there was no handling
for `MetadataRelationship` fields.
---
- Support deployment of `MetadataRelationship` fields.
---
_None_

SALTO-3391: Deployment of Salesforce MetadataRelationship fields

---

packages/adapter-components/src/elements/instance_elements.ts

We should log the type name when there's a missing `idField` in the instance entry
---
None
---
None

SALTO-3465: Add type name to idFields log message on error

---

packages/zendesk-adapter/src/change_validators/missing_users.ts
packages/zendesk-adapter/test/change_validators/missing_users.test.ts

Add more valid user values to fix a bug causing `missingUsersValidator` to prevent deployment of instances with those values.
---
None
---
None

SALTO-3485: Add more valid user values for missing user change validator in Zendesk

---

packages/jira-adapter/src/change_validators/masking.ts
packages/jira-adapter/test/change_validators/masking.test.ts

change validator to always warn according to this [comment](https://salto-io.atlassian.net/browse/SALTO-3403?focusedCommentId=63832)
---
---
---

SALTO-3403/refactor change validator 2

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/constants.ts
packages/zendesk-adapter/src/filters/support_address.ts
packages/zendesk-adapter/test/adapter.test.ts
packages/zendesk-adapter/test/filters/support_address.test.ts

_better handling email addresses in zendesk_
---
---
zendesk:
* zendesk emails in support_address will include a reference expression to the brand subdomain.
---
zendesk:
* zendesk emails in support_address will include a reference expression to the brand subdomain.

SALTO-3030: better handling email addresses in zendesk

---

packages/adapter-utils/src/compare.ts
packages/adapter-utils/test/compare.test.ts
packages/salesforce-adapter/test/adapter.crud.test.ts

_fix calculating changes hash as part of quick deploy_
---
none
---
none

SALTO-3503 fix calculating changes hash as part of quick deploy

---

packages/zendesk-adapter/src/change_validators/article_attachment_size.ts
packages/zendesk-adapter/src/filters/article/utils.ts

_no content for attachment after brand filter in zendesk guide_
---
---
None
---
None

SALTO-3508: no content for attachment after brand filter in zendesk guide

---

packages/adapter-components/src/elements/swagger/swagger.ts
packages/adapter-components/test/elements/swagger/swagger.test.ts
packages/adapter-components/test/elements/swagger/type_elements.test.ts

removed logic that only retried fetching swagger file if the error has status.
now we will retry as the full amount of "numberOfRetries"
---
---
---

salto-3486/swagger retry all the time

---

packages/netsuite-adapter/src/change_validators/client_validation.ts
packages/netsuite-adapter/src/client/client.ts
packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/src/errors.ts
packages/netsuite-adapter/test/change_validators/client_validation.test.ts
packages/netsuite-adapter/test/client/client.test.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts

_manifestValidationError will not fail the entire deploy_
---
* The first PR out of two for this ticket, the second PR will handle removing all dependencies the first time we encounter manifestValidationError instead of removing it with validation iterations.
---
_Netsuite_:
* encountering a manifest validation error due to objects which do not appear in target account will not fail deployment, the elements will be removed to allow deployment of all other elements
---
_None_

SALTO-2926: Use manifest validation error to fix issues prior to deploy

---

packages/adapter-components/src/references/reference_mapping.ts
packages/zendesk-adapter/src/constants.ts
packages/zendesk-adapter/src/filters/field_references.ts
packages/zendesk-adapter/src/filters/references/missing_references.ts
packages/zendesk-adapter/test/filters/field_references.test.ts

_missing reference for ticket field in routing attribute value_
---
---
zendesk
* add missing reference for ticket_field, user_field, and organization_field in routing attribute value
---
zendesk
* add missing reference for ticket_field, user_field, and organization_field in routing attribute value

SALTO-3455: missing reference for ticket field in routing attribute value

---

packages/workspace/src/serializer/elements.ts
packages/workspace/test/serializer/serializer.test.ts

Today, fields are serialized only as part of an `ObjectType` and deserialized to `FieldDefinition` instead of `Field` elements.
In this PR I added the support to deserialize standalone serialized fields, while inside `ObjectType` elements they are deserialized to `FieldDefinition` as it was before.
---
---
Workspace:
- Support deserialization of fields
---
None

Support deserialization of Field elements

---

packages/okta-adapter/src/config.ts

Transformation config for ProfileMapping type in Okta
---
The default `idFields` (`name`) was missing in `ProfileMapping` type
I also added `serviceId` and `fieldsToHide` and `fieldsToOmit`  that were missing too.
---
None
---
None

SALTO-3523: Okta - ProfileMapping type config

---

packages/adapter-components/src/elements/index.ts
packages/okta-adapter/src/adapter.ts
packages/okta-adapter/src/filters/url_references.ts
packages/okta-adapter/src/filters/user_schema.ts
packages/okta-adapter/src/utils.ts
packages/okta-adapter/test/filters/user_schema.test.ts
packages/okta-adapter/test/utils.test.ts

Fetch all UserSchema instances
---
Until now, we fetched only the default `UserSchema` instance.
Okta's API doesn't have a an API to list all userSchema instances, and we have to get each `UserSchema` instance by its id.
We get the ids from the _links object from the matching `UserType` instance.
I added this in a filter as `dependsOn` or `recurseInto` does not support this case atm.
---
None
---
None

SALTO-2653: Okta - Fetch all UserSchema instances

---

packages/jira-adapter/src/filters/jql/template_expression_generator.ts
packages/jira-adapter/test/filters/jql/template_expression_generator.test.ts

Values in JQLs can be either name/key or and id, until now we covered only name/key. This PR adds support for id values
---
- Increased references coverage in JQLs
---
- After the next fetch, values in JQLs might be converted to references

SALTO-3521: Project ids are not converted to reference in JQLs

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/filters/organizations.ts
packages/zendesk-adapter/src/filters/user.ts
packages/zendesk-adapter/src/replacers_utils.ts
packages/zendesk-adapter/src/user_utils.ts
packages/zendesk-adapter/test/filters/organizations.test.ts
packages/zendesk-adapter/test/replacers_utils.test.ts

Replace organization ids with organization names in Zendesk
---
Changes: 
- Add filter which replaces organization ids with a multienv value (unique organization name)
- As most of the code is shared with user filter, I moved shared code to `replacement_utils.ts`.
- `fieldReplacer` func now supports values replacement in arrays as well. This addition also fixes a bug causing field `added_user_ids` (array field) in `user_segment` with one element to be replaced with value + arrays with multiple elements were not replaced
bug fix pics - 
Will add noise reduction for orgIds changes
Added only basic tests that i'll improve later
---
_Zendesk-adapter_
- References to organization ids will be replaced with organization names
---
_Zendesk-adapter_
- …

SALTO-2162: Replace organization ids with organization names in Zendesk

---

packages/zendesk-adapter/src/filters/handle_app_installations.ts
packages/zendesk-adapter/src/filters/handle_template_expressions.ts
packages/zendesk-adapter/test/filters/handle_template_expressions.test.ts

_zendesk support templating for custom fields user and organization_
---
---
zendesk: 
* zendesk support templating for custom fields user and organization
---
zendesk:
* placeholders that looked like this:
`{{ticket.organization.custom_fields.<key>}}` ,` {{ticket.organization.custom_fields.<key>.title}}`, `{{ticket.requester.custom_fields.<key>}}`, `{{ticket.requester.custom_fields.<key>.title}}`
will now have a reference expression instead of the `<key>`.

SALTO-2489: zendesk support templating for custom fields user and organization

---

packages/salesforce-adapter/cpq-sbaa-config-doc.md
packages/salesforce-adapter/src/config_creator.ts
packages/salesforce-adapter/src/types.ts

Fix default market email template exclusion
This is an example of a marketoEmailTemplate from a customer
---
The current implementation doesn't work, please
---
Fix default market email template exclusion.
---
None

SALTo-2793 - Fix default market email template exclusion

---

packages/adapter-components/src/config/index.ts
packages/adapter-components/src/config/shared.ts
packages/adapter-components/test/config/shared.test.ts

Add deploy config with user fallback strategy
---
This PR contains only the adapter-components changes, for full context see https://github.com/salto-io/salto/pull/3846/files
---
None
---
None

SALTO-3143: Add shared deploy config to handle missing users

---

build_utils/verify_tsconfig_references.js

`yarn verify` fails on Windows because `tsconfic_references.js` does a string compare between workspace deps (that always use `/` as path separator) and paths (that use the OS-specific path separator). This works fine on POSIXy systems, but fails miserably on Windows.
---
---
Fix building the Salto project on Windows
---
N/A

SALTO-3475 - Build: fix Windows build

---

packages/jira-adapter/src/change_validators/workflows/empty_validator_workflow.ts
packages/jira-adapter/test/change_validators/workflows/empty_validator_workflow.test.ts

Fixed deploying a workflow without validators
---
None
---
None

SALTO-3542: fixed deploying workflows without validators

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/test/adapter.test.ts

Cache the clients create in the deploy by subdomain, so that all change groups will use the same client, and the same rate limit
---
None
---
None
---
None

SALTO-3541 - Zendesk Adapter - Cache deploy clients by subdomain and use them globally

---

packages/adapter-components/src/client/config.ts
packages/adapter-components/src/client/constants.ts
packages/adapter-components/src/client/http_connection.ts
packages/adapter-components/test/client/http_client.test.ts
packages/adapter-components/test/client/http_connection.test.ts
packages/okta-adapter/src/client/client.ts
packages/zendesk-adapter/src/client/client.ts
packages/zendesk-adapter/test/client/client.test.ts

Zendesk adapter will also retry the request if the status code is 409 or 503
---
None
---
None
---
None

SALTO-2961 - Zendesk Adapter - Retry on more responses statuses

---

packages/salesforce-adapter/src/metadata_deploy.ts

Omit results for the runTestResults that are logged.
---
---
Stability on SF deploy with large results of test coverage.
---
None.

INCIDENT-2811 - Omit results for the runTestResults that are logged

---

packages/workspace/src/workspace/adapters_config_source.ts
packages/workspace/test/workspace/adapters_config.test.ts

Fixed a bug were updating a config files to be invalid would make them to not be returned from `getElementNaclFiles` (resulting them being gone from the SaaS UI(
---
None (does not affect OSS)
---
None

SAAS-7003: invalid nacl files are not returned from config source

---

packages/salesforce-adapter/src/adapter.ts
packages/salesforce-adapter/src/filters/organization_wide_sharing_defaults.ts
packages/salesforce-adapter/test/filters/organization_wide_sharing_defaults.test.ts

Fetch the organization-wide default sharing settings as a hidden instance.
---
https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_organization.htm
We need this information in order to implement a change validator as described in the ticket.
---
N/A
---
N/A

SALTO-3109 - Salesforce: Fetch org wide sharing defaults

---

packages/jira-adapter/src/filters/workflow/workflow_modification_filter.ts
packages/jira-adapter/test/filters/workflow/workflow_modification_filter.test.ts

_Handled cases in which workflow deployment fails and were not properly handled_
---
As a general context  workflows cannot be edited in Jira’s API. We have to delete them and create new ones. Also, active workflows cannot be deleted, so we have to make changes to the scheme references.
We do it by
1. Creating a duplicate of the new workflow (a.k.a temp workflow)
2. Deploying the temp workflow
3.  Switching the relevant schemes to point to the temp workflow
4. Deleting the original old workflow (must be before stage 5 as they have the same name)
5. Deploying the new workflow
6. Switching back the schemes to point to the new workflow
7. deleting the temporary workflows
Failures to steps 2, 4 were not handled before
---
Jira Adapter:
Fixed …

SALTO-3502: Jira increase workflow deployment robustness

---

packages/jira-adapter/src/product_settings/data_center/data_center.ts

_Add customFields default value plugin urls_
---
link to the plugin [PR](https://github.com/salto-io/jira-dc-app/pull/90)
---
_None_
---
_None_

SALTO-2939: add customFields default value plugin urls - Jira DC

---

packages/core/src/core/plan/dependency/reference_dependency.ts
packages/core/test/core/plan/dependency.test.ts

On deploy, when a referenced value is changed, the plan will include the element that was changed (lets call it A) and the element with a reference to that value (B) (because we need to deploy the referencing element with the new value).
In that case, we want to have a dependency from B to A, so that if A has a changeError we won't deploy B (also that A will be deployed before B).
---
---
Core:
- Add a dependency when reference target is a modified non-element value
---
None

SALTO-3537 Add a dependency when reference target is a modified non-element value

---

packages/salesforce-adapter/config_doc.md
packages/salesforce-adapter/src/constants.ts

Increased maxAttempts from 3 to 5. Updated docs.
---
_None_
---
_None_

SALTO-3247: Increased Salesforce data default retry attempts

---

packages/jira-adapter/src/filters/locale.ts
packages/jira-adapter/test/filters/locale.test.ts

Fixed the warning message to be US specific
---
None
---
None

SALTO-3141: Fix local warning message

---

packages/salesforce-adapter/test/utils.test.ts
packages/salesforce-adapter/test/utils.ts

This test utility overrides the annotations passed to it. Make it not do it.
---
---
N/A
---
N/A

SALTO-3560 - Salesforce: Fix the createCustomObjectType test util

---

.circleci/config.yml

archive.ubuntu.com is ultra slow, using [apt-select](https://github.com/jblakeman/apt-select) (which takes mirrors from [launchpad](https://launchpad.net/ubuntu/+archivemirrors)) we can configure it so it won't block us from running CI/CD pipelines.
---
---
---

SALTO-3583: make sources.list configurable

---

packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/filters/account_info.ts
packages/jira-adapter/test/filters/account_info.test.ts

Added the DC license, and logged the license details and the user count (taken from applicationRole)
---
None
---
None

SALTO-3480: bring license information

---

packages/adapter-components/src/config/index.ts
packages/adapter-components/src/config/shared.ts
packages/adapter-components/test/config/shared.test.ts
packages/zendesk-adapter/config_doc.md
packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/adapter_creator.ts
packages/zendesk-adapter/src/change_validator.ts
packages/zendesk-adapter/src/change_validators/missing_users.ts
packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/src/filters/user.ts
packages/zendesk-adapter/src/user_utils.ts
packages/zendesk-adapter/test/adapter_creator.test.ts
packages/zendesk-adapter/test/change_validator.test.ts
packages/zendesk-adapter/test/change_validators/missing_users.test.ts
packages/zendesk-adapter/test/filters/referenced_id_fields.test.ts
packages/zendesk-adapter/test/filters/user.test.ts
packages/zendesk-adapter/test/user_utils.test.ts

Add deploy config option + handle missing users in Zendesk
---
Changes:
Adapter-components
- Add 'defaultMissingUserFallback' config option for fallback when users referenced from elements are missing
Zendesk
- Add deploy config to zendesk by default, and add this config as an optional param for filters & change validator
- Adjust `missingUsersValidator` to notify users in case missing users values are about to change
- Add filter that on `onDeploy` will change all missing users in changed elements to the user provided in deploy config
---
Zendesk
- Add the option to define fallback username for elements with references to missing users.
---
None

SALTO-3143: Deploy config for missing users & handle missing users in Zendesk

---

packages/netsuite-adapter/e2e_test/adapter.test.ts
packages/netsuite-adapter/src/change_validator.ts
packages/netsuite-adapter/src/change_validators/remove_sdf_elements.ts
packages/netsuite-adapter/src/change_validators/remove_standard_types.ts
packages/netsuite-adapter/src/change_validators/types.ts
packages/netsuite-adapter/src/client/client.ts
packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
packages/netsuite-adapter/src/client/types.ts
packages/netsuite-adapter/src/data_elements/types.ts
packages/netsuite-adapter/src/filters/author_information/system_note.ts
packages/netsuite-adapter/src/filters/internal_ids/sdf_internal_ids.ts
packages/netsuite-adapter/src/group_changes.ts
packages/netsuite-adapter/src/types.ts
packages/netsuite-adapter/test/adapter.test.ts
packages/netsuite-adapter/test/change_validators/client_validation.test.ts
packages/netsuite-adapter/test/change_validators/remove_sdf_elements.test.ts
packages/netsuite-adapter/test/change_validators/remove_standard_types.test.ts
packages/netsuite-adapter/test/client/client.test.ts
packages/netsuite-adapter/test/group_changes.test.ts

Add the ability to delete objects received by SDF through SuiteApp API:
custom record types, instances of standard types
---
_None_
---
_Now have the ability to delete custom record types and instances of standard types_
---
_None_

Salto-2501 add the ability to delete SDF objects

---

packages/adapter-components/src/filters/referenced_instance_names.ts
packages/adapter-components/test/filters/referenced_instance_name.test.ts

* Extend the simple-adapters referenced-id-fields logic (which allows ids to be created based on reference expressions) to also correctly support template expressions (see examples in the tests)
* Change some existing fallbacks to be more robust - specifically, allow references to nested ids and to other elements
---
None (not user-facing)
---
None

SALTO-3613 Allow idFields to reference template expressions

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/test/adapter.test.ts

Change the default configuration for `support_address` so that it contains both the name and the email - while keeping the email multienv-friendly, since it often contains the brand's subdomain which is different per env.
---
For example, the following instance
```
zendesk.support_address <...> {
name = "Salto"
email = "support@${ zendesk.brand.instance.Salto.subdomain }.zendesk.com"
...
}
```
will be assigned the id `zendesk.support_address.instance.Salto_support_Salto_subdomain_zendesk_com@umvvv` - concatenating the name `Salto` and the email-with-template `support@Salto.subdomain.zendesk.com`
---
* Support address instance ids now also contain details from the email address, to reduce the chance of conflicting ids in cases where multiple addresses …

SALTO-3612 Improve support address idFIelds to be multienv-friendly and unique

---

packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/test/adapter.test.ts

Fix type mismatch in fields
---
By converting organization ids to organization names, fields with type number caused type mismatch when receiving strings (org name)
---
None
---
None

SALTO-3611: Fix type mismatch in fields

---

packages/adapter-utils/test/utils.test.ts

Without the `await`, these tests just compare promises.
---
Discovered when running the tests with `--detectOpenHandles` on Node.js v18, due to changes to how async hooks are implemented in Node.js >=16.6.0
---
N/A
---
N/A

SALTO-3625: Missing await in adapter utils tests

---

packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/change_validators/workflow_scheme_migration.ts
packages/jira-adapter/test/change_validators/workflow_scheme_migration.test.ts

fixed nit from merged pr requiring the partial status migration to be part of the error message to the user.
---
---
---

SALTO-2347/workflow scheme migration

---

packages/zendesk-adapter/config_doc.md
packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/src/filters/organizations.ts
packages/zendesk-adapter/test/filters/organizations.test.ts

Replace organization IDs with name only when resolveOrganizationIDs config flag enabled
---
Changes:
- Add `resolveOrganizationIDs` config option, which will be false by default
- `organizations` filter will replace organization ids with names when `resolveOrganizationIDs` enabled
---
- Add `resolveOrganizationIDs` fetch config option, when set to `true` references to organization IDs will be replaced with organization names
---
- References to organizations will be replaced with organization IDs, to revert this change edit the `fetch` config options in the config file and set `resolveOrganizationIDs = true`

SALTO-3586: Replace organization IDs with name only when resolveOrganizationIDs config flag enabled

---

packages/jira-adapter/src/filters/account_id/account_id_filter.ts
packages/jira-adapter/src/filters/account_id/types.ts
packages/jira-adapter/test/change_validators/account_id.test.ts
packages/jira-adapter/test/filters/account_id/account_id_common.ts
packages/jira-adapter/test/filters/account_id/account_id_filter.test.ts
packages/jira-adapter/test/filters/account_id/user_id_filter.test.ts

_Added to account id scenarios support in 'accountIds' which covers multi user picker default value_
---
Not sure if we should also add noise suppression, as it can show changes to existing users
---
Jira Adapter:
User account Ids in custom fields of multi user picker will now be added display names
---
Jira Adapter: 
User account ids in custom fields of multi user picker will now be added display names

Salto-3577: Add user account id changes for multi user picker field

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/change_validators/automation_unresolved_references.ts
packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/change_validators/unresolved_references.ts
packages/jira-adapter/src/filters/automation/automation_project_broken_reference.ts
packages/jira-adapter/test/change_validators/automation_unresolved_reference.test.ts
packages/jira-adapter/test/change_validators/unresolved_references.test.ts
packages/jira-adapter/test/filters/automation/automation_project_broken_reference.test.ts

_Allow and handle broken references from automations to projects_
---
* add a predicate function to make `unresolvedReferencesValidator` ignore automation projects
* add change validator to raise error or warning for those unresolved references
* add filter to remove the unresolved references in preDeploy and add them back in onDeploy
* add unit tests for all the above
---
_None_
---
_None_

SALTO-3520: Allow and handle broken references from automations to projects - Jira

---

packages/netsuite-adapter/README.md

Changed "Netsuite" to "NetSuite" in the NetSuite Adapter README
---
This is the correct branding for Oracle NetSuite
---
No effect on usability
---
No effect on usability

Adapter: README: Correct casing of "NetSuite"

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/filters/hide_account_features.ts
packages/zendesk-adapter/test/filters/hide_account_features.test.ts

Hide account_features instance in Zendesk
---
We're hiding account_features instance as it's changes a lot and its noisy.
We hide it rather than delete it because the instance is being used in change validaotrs.
---
None
---
None

SALTO-3509: Hide account_features instance in Zendesk

---

package.json

Since the Node.js v18 upgrade our tests all pass successfully but jest never finishes. `--detectOpenHandles` is no help, and the issue only repros on CircleCI. 
For now, let's have jest force-terminate after all the tests are done.
---
---
N/A
---
N/A

SALTO-3619: use --forceExit when running tests

---

packages/adapter-api/src/values.ts
packages/jira-adapter/src/filters/field_references.ts
packages/jira-adapter/src/filters/fields/field_type_references_filter.ts
packages/jira-adapter/src/reference_mapping.ts
packages/jira-adapter/test/filters/fields/field_type_references.test.ts

_Fix references of Some custom fields default values - Jira_
---
in this PR I added: 
* 4 references rules, 2 for cloud and 2 for DC (in DC there is no id for groups therefore the rules are different)
* refactored `fieldTypeReferencesFilter` so it will handle multiple options as well
---
Jira adapter:
* Added missing references in the default values of custom field context for the following types: select list (multiple), group picker (single and multiple) and project picker.
---
Jira adapter:
The default value of custom fields from the following types: select list (multiple), group picker (single and multiple) and project picker will convert to a reference expression.

SALTO-3571: Fix references of Some custom fields default values  - Jira

---

packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/change_validators/same_issue_type_name.ts
packages/jira-adapter/test/change_validators/same_issue_type_name.test.ts

---
---
jira adapter:
* add change validator to block deployment of issue types with non unique names.
---

SALTO-3551/same issuetype name validator

---

package.json

It looks like the flags making the E2E to run for 2 hours
---
None
---
None

Revert "SALTO-3619: use --forceExit when running tests(workaround)"

---

.circleci/config.yml

In https://github.com/salto-io/salto/pull/3960 I reverted https://github.com/salto-io/salto/commit/c3e977a5de74bd28f70c7d2cbe5984d780d7205f since the flags made the E2E tests take 2 hours.
Here I added the flags back but only in the UTs
---
None
---
None

SALTO-3619: Added jest flags to UTs

---

packages/netsuite-adapter/src/config.ts
packages/netsuite-adapter/src/data_elements/types.ts
packages/netsuite-adapter/src/query.ts
packages/netsuite-adapter/src/types.ts

return a list of supported types for NetSuite partial fetch., in order to support autocomplete and "fetch all" in quick fetch.
(extra work in SaaS has to be done in order to support this)
---
_None_
---
When choosing partial fetch in NetSuite, a list of supported types will be shown, allowing autocomplete and easy configuration
---
_None_

salto-2883 netsuite partial fetch

---

packages/zendesk-adapter/src/filters/field_references.ts

sla_policy does not have missing reference expression for types `ticket_field__custom_field_options`, `user_field__custom_field_options` and `organization_field__custom_field_options`
---
none
---
zendesk:
* add missing reference in sla_policy for types: `ticket_field__custom_field_options`, `user_field__custom_field_options` and `organization_field__custom_field_options`
---
zendesk:
* add missing reference in sla_policy for types: `ticket_field__custom_field_options`, `user_field__custom_field_options` and `organization_field__custom_field_options`

SALTO-3649: sla_policy does not have missing reference expression

---

packages/netsuite-adapter/src/change_validators/client_validation.ts
packages/netsuite-adapter/test/change_validators/client_validation.test.ts

_client_validation.ts manifest error message changed to address locked elements_
---
_None_
---
* client_validation.ts manifest error message updated address locked elements 
---
_None_

Salto-3334: Tell users when missing dependencies are from locked elements

---

packages/zendesk-adapter/src/filters/references/list_values_missing_references.ts
packages/zendesk-adapter/test/filters/references/list_values_missing_references.test.ts

When trying to create a missing reference and the notification value is unexpected, do nothing
---
None
---
None
---
None

INCIDENT-3157 - Handle trigger & automations notifications value not being an array

---

packages/zendesk-adapter/src/change_validators/one_translation_per_locale.ts
packages/zendesk-adapter/test/change_validators/one_translation_per_locale.test.ts

fix getFullName of undefined in zendesk one_translation_per_locale validator
---
---
zendesk:
* fix issue in the validation of Guide translations that could cause failures in deployments.
---
None

SALTO-3651: fix getFullName of undefined in zendesk one_translation_per_locale validator

---

packages/workspace/src/expressions.ts
packages/workspace/test/core/expressions.test.ts

Today we assume that if we got a field and its parent type in the same resolve call, the field's parent will point to the same object type that we got to resolve, so we don't need to resolve both.
The problem is that we clone the elements before we resolve them, so the field’s parent don’t point to the same object type that we got to resolve.
---
---
Workspace:
- Fix field parents resolving
---
None

SALTO-3656 Fix field parents resolving

---

packages/netsuite-adapter/src/filters/additional_changes.ts
packages/netsuite-adapter/src/reference_dependencies.ts
packages/netsuite-adapter/test/filters/additional_changes.test.ts
packages/netsuite-adapter/test/reference_dependencies.test.ts

Instead of returning the referenced elements with the input elements, we should return only the referenced elements.
That let us control the return type of the function (it can be `ObjectType | InstanceElement`), and avoid a case of returning an equivalent to an input element but not the exact same object (if it is also referenced, and we return the referenced element instead of the input element).
The thought behind that change is that we want to use a cloned version of the added changes in `additional_changes.ts` - but we don't want to clone the added field parents, because it will separate the `field.parent` property from the added field parent.
---
---
- Return only added elements in getReferencedElements
---
_User …

Return only added elements in getReferencedElements

---

packages/jira-adapter/src/change_validators/active_scheme_change.ts
packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/test/change_validators/active_scheme_change.test.ts
packages/jira-adapter/test/change_validators/active_workflow_scheme_change.test.ts

modify existing behaviour of a change validator to check not for just changes of workflow schemes in projects that will cause migration but for priority scheme changes aswell
---
modified the tests and text accordingly 
---
jira_adapter:
* data center:
- add change validator to block deployment of project changes to priority schemes when the project has issues.
---

SALTO-3535/priority scheme migration

---

packages/netsuite-adapter/src/data_elements/data_elements.ts
packages/netsuite-adapter/src/filters/remove_unsupported_types.ts
packages/netsuite-adapter/test/filters/remove_unsupported_types.test.ts

There are some SOAP types that we fetch without their instances. We should not remove them in "Remove Unsupported Types" filter.
---
---
- Do not remove additional SOAP types
---
None

Do not remove additional SOAP types

---

packages/adapter-api/src/adapter.ts
packages/core/src/api.ts
packages/core/src/core/fetch.ts
packages/core/test/core/fetch.test.ts
packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/config.ts
packages/netsuite-adapter/test/adapter.test.ts

As part of https://salto-io.atlassian.net/browse/SAAS-6953?focusedCommentId=67080&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-67080
In this PR:
- Adding a new function to adapter-api 'quickFetch' this function is not mandatory and each adapter can implement it or not.
- Make Netsuite adapter to implement quickFetch, with the same logic that it has done with 'useChangesDetection' from the config file.
Note, for now I didn't remove 'useChangesDetection' from the config, since I want to support the old way to run quick fetch
---
---
Core:
Allow adapters to expose a fetchWithChangeDetection function that only fetches changes since the last fetch
Netsuite adapter:
Implement fetchWithChangeDetection to allow fetching only changes since the …

SAAS-6953 add quickFetch to adapter-api and make Netsuite implementing it

---

packages/okta-adapter/src/change_validators/group_rule_actions.ts
packages/okta-adapter/src/change_validators/group_rule_status.ts
packages/okta-adapter/src/change_validators/index.ts
packages/okta-adapter/src/config.ts
packages/okta-adapter/src/filters/expression_language.ts
packages/okta-adapter/test/change_validators/group_rule_actions.test.ts
packages/okta-adapter/test/change_validators/group_rule_status.test.ts
packages/okta-adapter/test/filters/expression_language.test.ts

Support GroupRule deployment + restore template expression to Okta expression language before deployment
---
Changes:
- Add GroupRule deployment
- Add preDeploy and onDeploy for `oktaExpressionLanguageFilter` to restore expressions before deployment
- Add validator that checks GroupRule actions didn't change
- Add validator that checks the change action is allowed based on GroupRule status
- addition / modification / removal of GroupRule with status active is not allowed
- modification of GroupRule with status invalid is not allowed
- changes to GroupRule status is not allowed (this is temporary and we'll support this in the future)
---
None
---
None

SALTO-3563: GroupRule deployment and deploy Okta expression language

---

packages/lowerdash/test/promises/timeout.test.ts

An attempt to fix a flaky timeout test
---
Tried:
- creating the P variable separately in each test in case of a race between the tests
- increased the timeout in the tests
---
None
---
None

Attempt to fix flaky timeout test

---

packages/netsuite-adapter/src/filters/author_information/saved_searches.ts
packages/netsuite-adapter/src/filters/author_information/system_note.ts
packages/netsuite-adapter/test/filters/author_information/saved_searches.test.ts
packages/netsuite-adapter/test/filters/author_information/system_note.test.ts

filter system note/ saved search query results to not include changes from the future.
---
---
netsuite adapter: 
* changed at annotations will no longer be able to be from the future.
---

Salto-3671/validate saved searches dates

---

packages/adapter-utils/src/utils.ts
packages/adapter-utils/test/utils.test.ts

Fixed getPath to work with fields and the rootElement
---
None (no effect on users currently)
---
None

SALTO-3681: `getPath` does not correctly when `rootElement` is a field

---

packages/core/src/core/plan/change_validators/check_deployment_annotations.ts
packages/core/test/core/plan/change_validators/check_deployment_annotations.test.ts

_make change validator message on undeployable values attached to the problematic value_
---
Core:
* change validator message on undeployable values attached to the undeployable value instead of the entire instance
---
None

SALTO-3252: make change validator message on undeployable values attached to the problematic value

---

packages/salesforce-adapter/src/change_validators/cpq_trigger.ts
packages/salesforce-adapter/src/change_validators/custom_field_type.ts
packages/salesforce-adapter/src/change_validators/custom_object_instances.ts
packages/salesforce-adapter/src/change_validators/data_change.ts
packages/salesforce-adapter/src/change_validators/multiple_defaults.ts
packages/salesforce-adapter/src/change_validators/package.ts
packages/salesforce-adapter/src/change_validators/picklist_promote.ts
packages/salesforce-adapter/src/change_validators/picklist_standard_field.ts
packages/salesforce-adapter/src/change_validators/sbaa_approval_rules_custom_condition.ts
packages/salesforce-adapter/src/change_validators/standard_field_label.ts
packages/salesforce-adapter/src/change_validators/unknown_field.ts

Wording changes for Salesforce change validators
---
---
---

CV wording changes

---

packages/jira-adapter/test/filters/dashboard/gadget.test.ts
packages/jira-adapter/test/filters/statuses/status_deployment.test.ts

These lines seem to be leftovers from debugging. Let's remove them.
---
---
N/A
---
N/A

SALTO-3664 - Jira: Remove redundant setTimeout in tests

---

packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/change_validators/issue_type_deletion.ts
packages/jira-adapter/test/change_validators/issue_type_deletion.test.ts

add change validator to block removal of issue types when there are issues of that type in the service.
---
---
jira adapter:
* Add change validator to block removing issue types that are being used in projects
---

SALTO-3489/issue type deletion

---

packages/jira-adapter/src/change_validators/active_scheme_change.ts
packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/change_validators/issue_type_scheme_migration.ts
packages/jira-adapter/test/change_validators/issue_type_scheme_migration.test.ts

handled a migration error for issue type schemes when we either change a project issue type scheme or when we remove an issue type from a scheme that is being used by a project with the same typed issues
---
added tests for the new validator.
---
jira adapter:
* Add change validator to block removal of issue type from a scheme if that issue type is being used in assigned projects.
* Block Issue type scheme changes in active projects.
---

SALTO-3602/issue type scheme migration

---

packages/core/src/core/fetch.ts
packages/core/test/core/fetch.test.ts

---
The bug was: 
In the old code, core saved the fetchFunction as const and call it. If inside the fetch function there are references to some of the adapter propertise (e.g this.someAttribute) 'this' was undefined and thrown an error.
We should call the function directly from the adapter it self (adapter.fetch(...args))
Behavior change:
When calling fetchWithChange detection with adapter that do not support this operation
In the old code a single error were thrown, contains all the unsupported fetchWithChangeDetection adapter names.
In the new code a single error will be thrown, contains only the first unsupported adapter name.
IMO this is good enough since this case shouldn't happen, and if it does the odds that there are more than a single adapter that does not support the operation …

SALTO-3689 fix broken fetch operation

---

packages/adapter-components/src/client/http_client.ts
packages/adapter-components/test/client/http_client.test.ts

Just the adapter-components changes from https://github.com/salto-io/salto/pull/3997
---
None
---
None

SALTO-3050: Clear secrets from response data before writing to log (adapter-components changes)

---

packages/jira-adapter/src/change_validators/workflow_scheme_migration.ts
packages/jira-adapter/test/change_validators/workflow_scheme_migration.test.ts

Fixed bug with workflow scheme change validator that assums that items field is always populated 
---
---
Jira adapter:
* bug fix for failing deployments over workflow schemes with no items. 
---

SALTO-3696/workflow schemes without items

---

packages/jira-adapter/src/change_validators/issue_type_scheme_migration.ts
packages/jira-adapter/src/change_validators/workflow_scheme_migration.ts
packages/jira-adapter/test/change_validators/issue_type_scheme_migration.test.ts
packages/jira-adapter/test/change_validators/workflow_scheme_migration.test.ts

fixed potential bug with workflow scheme migration change validator potentially using workflow statuses when its undefined 
and another one in issue type scheme that might not have issue type ids.
---
---
jira adapter:
* Fixed cases in some change validators that failed on missing fields in instances.
---

SALTO-3698/missing fields

---

packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts

In case that SDF deploy failed on an non-english NS account, no error is thrown from SDF so we need to look for the error format of `***<error in any language>***` and throw an exception.
---
---
- Throw on SDF deploy error in other languages
---
None

SALTO-3148 throw on SDF deploy error in other languages

---

packages/dummy-adapter/src/adapter.ts
packages/dummy-adapter/test/adapter.test.ts

Add `validate` capability to the dummy-adapter
I'm not 100% sure I'm doing this right, or if this is the right approach, so this is WIP.
---
None
---
None
---
None

SAAS-7316: Add validate capability to the dummy-adapter

---

packages/zendesk-adapter/src/filters/view.ts
packages/zendesk-adapter/test/filters/view.test.ts

_zendesk typeError cannot read property toString of undefined_
---
---
zendesk:
* fix error of cannot read property toString of undefined in view filter
---
None

SALTO-3708: zendesk typeError cannot read property toString of undefined

---

packages/okta-adapter/src/client/client.ts
packages/okta-adapter/src/config.ts
packages/okta-adapter/test/client/client.test.ts

Clear secrets from response data before writing to log
---
None
---
None

SALTO-3050: Clear secrets from response data before writing to log

---

packages/adapter-components/src/elements/swagger/type_elements/element_generator.ts
packages/adapter-components/src/elements/swagger/type_elements/swagger_parser.ts
packages/adapter-components/src/elements/swagger/type_elements/type_config_override.ts
packages/adapter-components/src/elements/type_elements.ts
packages/adapter-components/test/elements/swagger/petstore_swagger.v2.yaml
packages/adapter-components/test/elements/swagger/type_config_override.test.ts
packages/adapter-components/test/elements/swagger/type_elements.test.ts
packages/adapter-components/test/elements/type_elements.test.ts

Fetch swagger types defined in fieldTypeOverrides
tasks left
---
None
---
None

SALTO-3701: Get fieldTypeOverrides schemas

---

packages/salesforce-adapter/src/transformers/reference_mapping.ts

Please don't merge without noise suppression
---
Added missing reference in ComponentInstanceProperty as well as in QuickAction
[Reference for flowDefinition](https://github.com/salto-io/adi-ws/blob/master/envs/env1/salesforce/Objects/test_custom_object__c/QuickAction/test_custom_object__c_Test_Action.nacl)
[Reference for LightningComponent (and Visualforce component most likely)](https://github.com/salto-io/adi-ws/blob/master/envs/env1/salesforce/Objects/test_custom_object__c/QuickAction/test_custom_object__c_test_lightning_component.nacl)
[Reference in ComponentInstanceProperty (note the second one, we don't have references for standard flows)](https://github.com/salto-io/adi-ws/blob/master/envs/env1/salesforce/Records/LightningPage/test_page.nacl)
---
Salesforce …

Add reference mapping for user flows

---

packages/netsuite-adapter/src/filters/convert_lists.ts

file&folder instances have no list fields so we can skip them
---
---
- Skip convert-lists for file-cabinet instances
---
None

skip convert-lists for file-cabinet instances

---

packages/salesforce-adapter/src/filters/formula_deps.ts
packages/salesforce-adapter/test/filters/formula_deps.test.ts

Following a training session with @tamtamirr I realized the current way we handle custom labels and custom metadata type records is wrong. This is the fix.
---
Workspace diff: https://github.com/salto-io/tomsellek-sf/pull/3
---
Salesforce: Improved handling of references in formulas
---
N/A

SALTO-1730 - Salesforce: Fix handling of references to instances in formulas

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/filters/script_runner/workflow_dc.ts
packages/jira-adapter/src/filters/script_runner/workflow_ors.ts
packages/jira-adapter/test/filters/script_runner/workflow_cloud.test.ts
packages/jira-adapter/test/filters/script_runner/workflow_dc.test.ts
packages/jira-adapter/test/filters/script_runner/workflow_ors.test.ts

In script runner multiple values are brought as a single string with '|||' in between, we want to make them arrays
Also added support for email and slack post functions in DC
---
None
---
None

SALTO-3634: Some fixes to Scriptrunner

---

packages/jira-adapter/.vscode/launch.json
packages/jira-adapter/src/change_validators/account_id.ts
packages/jira-adapter/src/change_validators/wrong_user_permission_scheme.ts
packages/jira-adapter/src/filters/account_id/user_fallback_filter.ts
packages/jira-adapter/src/filters/account_id/user_id_filter.ts
packages/jira-adapter/src/filters/permission_scheme/wrong_user_permission_scheme_filter.ts
packages/jira-adapter/src/users.ts
packages/jira-adapter/test/change_validators/account_id.test.ts
packages/jira-adapter/test/change_validators/wrong_user_permission_scheme.test.ts
packages/jira-adapter/test/filters/account_id/user_fallback_filter.test.ts
packages/jira-adapter/test/filters/account_id/user_id_filter.test.ts
packages/jira-adapter/test/filters/permission_scheme/wrong_user_permission_scheme_filter.test.ts

users without permission to view other members in the service will fail running "getUserMapFuncCreator"
this change will make this function throw a specific error when it happens and everywhere that uses this code is now expecting this error and fail gracefully
added a log when it happens.
---
---
jira adapter:
* Fixed bug where missing permissions to view other users will fail deploy/fetch
---

SALTO-3669/user list permission failure

---

packages/netsuite-adapter/src/change_validators/remove_sdf_elements.ts
packages/netsuite-adapter/src/filters/internal_ids/sdf_internal_ids.ts
packages/netsuite-adapter/test/change_validators/remove_sdf_elements.test.ts

Return different change errors for the cases that instance doesn't have an `internalId`:
- When we don't fetch internalIds for that type
- When we do fetch internalIds for that type, but for some reason that specific instance doesn't have an internalId
---
---
- Add specific error for sdf instance removal with missing internalId
---
None

add specific error for sdf instance removal with missing internalId

---

packages/netsuite-adapter/src/filters/convert_lists.ts
packages/netsuite-adapter/src/filters/parse_report_types.ts
packages/netsuite-adapter/test/filters/parse_report_types.test.ts

Trying to reduce run time of `convertLists` filter - by not running it on report type instances, because they have parsers that take care of that.
---
---
- Do not run convert-lists filter on report types
---
None

do not run convert-lists filter on report types

---

packages/netsuite-adapter/src/filters/parse_report_types.ts
packages/netsuite-adapter/test/filters/parse_report_types.test.ts

Improve parse-report-types filter by not parsing the current `definition` from the nacl, but taking the already parsed values.
This improves the run time by 50%.
---
---
- Improve parse-report-types filter
---
None

SALTO-3725 improve parse-report-types filter

---

packages/okta-adapter/src/config.ts

Make AuthorizationServerPolicy and AuthorizationServerPolicyRule standalone fields
---
Until now we fetched `AuthorizationServerPolicy` and `AuthorizationServerPolicyRule` as part of `AuthorizationServer` type. This PR makes them standalone fields as we split all other policy and policy rules type & we want to hide fields like `id`
---
None
---
None

SALTO-3522: Make AuthorizationServerPolicy and AuthorizationServerPolicyRule standalone fields

---

packages/adapter-api/src/adapter.ts
packages/core/src/api.ts
packages/core/src/core/fetch.ts
packages/core/test/core/fetch.test.ts
packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/config.ts
packages/netsuite-adapter/test/adapter.test.ts

- Reverting https://github.com/salto-io/salto/pull/3963
- Introduce new flag for core fetch 'withChangeDetection'
- Make Netsuite adapter use 'withChangeDetection' received from core to run quick fetch
---
---
Netsuite_adapter:
When receiving 'withChangeDetection' from core on fetch, will run quick fetch. (not supported on the CLI yet)
---
_Replace me with a short sentence that describes changes that will appear in NaCls and are not caused by user actions (e.g. None

SALTO-3716 create core fetch config as input to core fetch

---

packages/core/src/core/plan/filter.ts
packages/core/src/core/plan/plan.ts
packages/core/test/core/plan/filter.test.ts

Fix some cases in plan/filter.ts:
- If there's a change error on a type annotation and a valid field change, we should return the valid field change with the before version of the type as a parent.
- If there's a change error on a field and a valid type change, we should return the valid type change with the before version of the field that had change error.
---
---
Core:
- Fix filterInvalidChanges (in plan)
---
None

SALTO-3538 Fix filterInvalidChanges (in plan)

---

packages/netsuite-adapter/src/change_validators/client_validation.ts
packages/netsuite-adapter/src/client/language_utils.ts
packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/test/change_validators/client_validation.test.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts

When NS account is configured to other language than English the errors in SDF are in that language too.
We want to be able to detect that and extract the exact errors in that case.
---
---
- Add SDF french support
---
None

SALTO-3148 add SDF french support

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/adapter_creator.ts
packages/zendesk-adapter/src/client/client.ts
packages/zendesk-adapter/test/change_validators/organization_existence.test.ts
packages/zendesk-adapter/test/client/client.test.ts

If resolveOrganizationIDs is false, we will filter the organization names before logging them, so we won't save them anywhere and we will keep the user's privacy requests
---
None
---
None
---
None

SALTO-3711 - Zendesk Adapter - Filter organization names from the logs

---

packages/salesforce-adapter/src/adapter.ts
packages/salesforce-adapter/src/filters/remove_unix_time_zero.ts
packages/salesforce-adapter/test/filters/remove_unix_time_zero.test.ts

add filter to remove unix time zero (1/1/1970) from created and modified dates
---
This does not change the workspace, since the annotations are hidden. 
element print before:
element print after:
---
---

SALTO-3620 add filter to remove unix time zero (1/1/1970) from created and modified dates

---

packages/zendesk-adapter/src/filters/hardcoded_channel.ts
packages/zendesk-adapter/test/filters/hardcoded_channel.test.ts

zendesk revert nacl case from channel name
---
---
zendesk:
* in channel, name will no longer be in nacl case
---
zendesk:
* in channel, name will no longer be in nacl case

SALTO-3724: zendesk revert nacl case from channel name

---

packages/salesforce-adapter/src/change_validators/sbaa_approval_rules_custom_condition.ts
packages/salesforce-adapter/test/change_validators/sbaa_approval_rules_custom_condition.test.ts

Change SBAA AprovalRule CV from warning to error
---
No additional context 
---
Salesforce:
* Change validator for SBAA ApprovalRule now returns an error upon failure
---

SALTO-3425 Change SBAA AprovalRule CV from warning to error

---

packages/zendesk-adapter/src/filters/audit_logs.ts
packages/zendesk-adapter/test/filters/audit_logs.test.ts

zendesk move includeAuditDetails flag to only control the addition of changed_by
---
---
zendesk: 
* move includeAuditDetails flag to only control the addition of changed_by
---
None

SALTO-1714: zendek move includeAuditDetails flag to only control the addition of changed_by

---

packages/salesforce-adapter/src/change_validators/unknown_users.ts
packages/salesforce-adapter/test/change_validators/unknown_users.test.ts
packages/salesforce-adapter/test/mock_elements.ts

Validate that if the recipients are Salesforce users, they actually exist
---
This required a slight modification to the change validator to allow it to extract multiple users from a single field.
---
Salesforce: Improved validation of WorkflowAlerts recipients
---
N/A

SALTO-3694 - Salesforce: Validate recipients of WorkflowAlerts

---

packages/netsuite-adapter/src/client/language_utils.ts
packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts

In order to identify errors for locked objects & unexpected errors.
---
---
- Add support for french fetch errors
---
None

SALTO-3148 add support for french fetch errors

---

packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/config.ts
packages/netsuite-adapter/test/adapter.test.ts

support quick fetch when not selecting fetch target. remove the default value and use only explicit settings
---
https://github.com/salto-io/salto/pull/4035
https://github.com/salto-io/salto/pull/4022
---
Support quick fetch when not selecting fetch target
---
_None_

SAAS-6749 support quick fetch when not selecting fetch target

---

packages/adapter-components/src/client/http_client.ts
packages/adapter-components/test/client/http_client.test.ts
packages/okta-adapter/src/client/client.ts
packages/okta-adapter/src/client/pagination.ts
packages/okta-adapter/test/client/client.test.ts

* Avoid logging headers except where needed (currently only Okta)
* Avoid logging large buffer data
---
None
---
None

SALTO-3783 Avoid logging unneeded data in client

---

packages/adapter-components/src/config/ducktype.ts
packages/adapter-components/src/config/request.ts
packages/adapter-components/src/config/shared.ts
packages/adapter-components/src/config/swagger.ts
packages/adapter-components/test/config/request.test.ts

Allow adding actions for deploy requests
---
This PR is part of - https://github.com/salto-io/salto/pull/4036
---
None
---
None

SALTO-3591- Allow adding actions for deploy requests

---

packages/zendesk-adapter/src/client/client.ts

Optimize the default max concurrency for Guide fetches
---
_Zendesk adapter_
* Increase the default max concurrent requests
---
None

SALTO-3787 increase default concurrency

---

packages/zendesk-adapter/config_doc.md
packages/zendesk-adapter/src/filters/audit_logs.ts
packages/zendesk-adapter/test/filters/audit_logs.test.ts

zendesk remove changed_by from instances where it is not received by the audit_log
add includeAuditDetails to config_doc
---
---
zendesk:
* Remove changed_by from instances where it is not received by the audit_log
---
None

SALTO-3785: zendesk remove changed_by from instances where it is not received by the audit_log

---

packages/jira-adapter/src/users.ts
packages/jira-adapter/test/filters/locale.test.ts

We got a user in a customer account with an empty emailAddress
---
- Fixed failure in getting the current user in some cases
---
None

SALTO-3800: Jira DC user scheme does not match a valid user

---

packages/salesforce-adapter/src/change_validator.ts
packages/salesforce-adapter/src/change_validators/account_settings.ts
packages/salesforce-adapter/src/constants.ts
packages/salesforce-adapter/src/types.ts
packages/salesforce-adapter/test/change_validators/account_settings.test.ts
packages/salesforce-adapter/test/mock_elements.ts

Add a change validator for AccountSettings.enableAccountOwnerReport. This field may only exist if the global account sharing policy is 'Private'
---
The actual value of the global account sharing setting is 'Read', 'Edit', etc. It is never actually set to 'Private' in the API data, but rather translated to other values (including 'Private') in the Salesforce UI.
---
Salesforce: Improved pre-deploy validation of account settings.
---
N/A

SALTO-3109 - Salesforce: validate account settings against org wide defaults

---

packages/netsuite-adapter/src/client/client.ts
packages/netsuite-adapter/src/client/deploy_xml_utils.ts
packages/netsuite-adapter/src/client/graph_utils.ts
packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/src/constants.ts
packages/netsuite-adapter/test/adapter.test.ts
packages/netsuite-adapter/test/client/client.test.ts
packages/netsuite-adapter/test/client/deploy_xml_utils.test.ts
packages/netsuite-adapter/test/client/graph_utils.test.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts

_Before deploying, we now edit the deploy.xml and sort the objects in the deployment according to their reference levels_
---
_None_
---
* Objects in the deploy.xml will be ordered according to their reference level
---
_None_

Salto-2865: Order the objects in deploy.xml according to ref level

---

packages/core/src/core/fetch.ts

Only comparing elements that were changed in the service yields a noticeable performance improvement in the common fetch scenario where only a few elements change
---
---
Salto Core:
- Performance improvements in processing time after fetching elements
---
_None_

SALTO-3811: improve fetch changes calculation performance by filtering the plan

---

packages/jira-adapter/e2e_test/instances/datacenter/fieldConfiguration.ts
packages/jira-adapter/e2e_test/instances/datacenter/index.ts

Updating the plugin in our e2e account broke the tests
---
The error was that `Assignee__user` can have a render so I changed it to a different field
---
None
---
None

Fixed jira DC E2E

---

packages/jira-adapter/package.json
packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/filters/data_center/plugin_version.ts
packages/jira-adapter/src/product_settings/data_center/data_center.ts
packages/jira-adapter/test/filters/data_center/plugin_version.test.ts

relevant PR in the plugin:  https://github.com/salto-io/jira-dc-app/pull/95
---
Jira adapter:
Warn in DC if the plugin and OSS versions do no fit
---
None

SALTO-3688: Add fetch warning if talking to an old version of Jira DC Plugin

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/user_utils.ts
packages/zendesk-adapter/test/change_validators/custom_role_removal.test.ts
packages/zendesk-adapter/test/change_validators/users.test.ts
packages/zendesk-adapter/test/filters/user.test.ts
packages/zendesk-adapter/test/user_utils.test.ts

zendesk ensure the fetching user's locale is set to en us
---
---
zendesk:
* Ensure the fetching user's locale is set to en us
---
None

SALTO-3643: zendesk ensure the fetching user's locale is set to en us

---

packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/change_validator.ts
packages/netsuite-adapter/src/change_validators/remove_sdf_elements.ts
packages/netsuite-adapter/src/change_validators/types.ts
packages/netsuite-adapter/test/adapter.test.ts
packages/netsuite-adapter/test/change_validator.test.ts
packages/netsuite-adapter/test/change_validators/remove_sdf_elements.test.ts

Use `elementSource.list()` instead of `elementSourceIndex` to see if there are existing instances for removed custom record type.
---
---
- Use elementSource in remove_sdf_elements
---
None

SALTO-3766 Use elementSource in remove_sdf_elements

---

packages/netsuite-adapter/src/elements_source_index/elements_source_index.ts
packages/netsuite-adapter/src/elements_source_index/types.ts
packages/netsuite-adapter/src/filters/convert_lists_to_maps.ts
packages/netsuite-adapter/src/mapped_lists/utils.ts
packages/netsuite-adapter/test/elements_source_index.test.ts
packages/netsuite-adapter/test/filters/convert_lists_to_maps.test.ts
packages/netsuite-adapter/test/mapped_lists/utils.test.ts
packages/netsuite-adapter/test/utils.ts

Do not use `elementSourceIndex` to transform maps back to lists.
---
---
- Improve convert-lists-to-maps preDeploy filter
---
None

SALTO-3766 improve convert-lists-to-maps preDeploy filter

---

packages/core/src/local-workspace/s3_dir_store.ts

Added  more logs when uploading files to S3 to help with an incident
---
None
---
None

INCIDENT-3754: Add more logs when uploading files to S3

---

packages/netsuite-adapter/src/reference_dependencies.ts

Should write log only if the result list isn't empty.
---
---
None
---
None

Remove redundant log in NS

---

packages/netsuite-adapter/e2e_test/adapter.test.ts
packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/change_validator.ts
packages/netsuite-adapter/src/change_validators/file_cabinet_internal_ids.ts
packages/netsuite-adapter/src/client/client.ts
packages/netsuite-adapter/src/elements_source_index/elements_source_index.ts
packages/netsuite-adapter/src/elements_source_index/types.ts
packages/netsuite-adapter/src/filters/add_parent_folder.ts
packages/netsuite-adapter/src/service_url/file_cabinet.ts
packages/netsuite-adapter/src/suiteapp_file_cabinet.ts
packages/netsuite-adapter/test/change_validator.test.ts
packages/netsuite-adapter/test/change_validators/file_cabinet_internal_ids.test.ts
packages/netsuite-adapter/test/client/client.test.ts
packages/netsuite-adapter/test/elements_source_index.test.ts
packages/netsuite-adapter/test/filters/add_parent_folder.test.ts
packages/netsuite-adapter/test/filters/service_urls.test.ts
packages/netsuite-adapter/test/service_url/file_cabinet.test.ts
packages/netsuite-adapter/test/suiteapp_file_cabinet.test.ts
packages/netsuite-adapter/test/utils.ts

Some changes in deployment of FileCabinet instances using suiteapp:
- Remove the `pathToInternalIds` index.
- Use the `_parent` annotation to get the parent folder `internalId` instead of `pathToInternalIds` index.
- Add change validator for missing `internalId` on removals/modifications, and missing parent folder `internalId` on additions.
- Remove the `getPathToIdMap` & `getPathInternalId` functions.
---
---
- Improve deployment of FileCabinet instances using SuiteApp
---
None

SALTO-3766 improve suiteapp-file-cabinet deploy

---

packages/cli/src/commands/account.ts

Flipped the account and service actions for some reason.
---
---
CLI: 'account' command will no longer show a deprecation warning.
---
N/A

SALTO-3825 - CLI: Deprecation message is shown when using the account command

---

packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/elements_source_index/elements_source_index.ts
packages/netsuite-adapter/test/elements_source_index.test.ts

Calculate only `changeAt` & `changedBy` indexes in full fetch, and the rest on partial fetch only.
---
This PR is rebased on https://github.com/salto-io/salto/pull/4079, https://github.com/salto-io/salto/pull/4087, https://github.com/salto-io/salto/pull/4088,
Please review only the last commit of this PR.
---
- Calculate only `changeAt` & `changedBy` indexes in full fetch, and the rest on partial fetch only.
---
None

SALTO-3766 improve elementsSourceIndexes

---

packages/cli/test/commands/deploy.test.ts
packages/cli/test/mocks.ts
packages/core/test/common/state.ts
packages/lang-server/test/workspace.ts
packages/workspace/src/workspace/path_index.ts
packages/workspace/src/workspace/state/in_mem.ts
packages/workspace/src/workspace/state/state.ts
packages/workspace/test/common/state.ts
packages/workspace/test/workspace/path_index.test.ts
packages/workspace/test/workspace/state.test.ts
packages/workspace/test/workspace/workspace.test.ts

created a new index which is identical to path index apart from the fact that it only hold paths of elements that are top level.
---
current known issue that is not fixed here is that partial fetch will break the path index and the top level path index, 
it will be fixed in a different pr.
---
core:
* add a new index that will hold top level elements current paths.
---

SALTO-3788/top level element path index

---

packages/adapter-api/src/builtins.ts
packages/adapter-api/src/constants.ts
packages/adapter-api/src/element_id.ts
packages/adapter-api/test/elements.test.ts

Fix issue where builtin type IDs (e.g "string") would be parsed as if they are configuration type IDs ("string._config")
---
---
_None_
---
_None_

SALTO-3842: Fix ElemID.fromFullName for builtin type IDs

---

packages/lowerdash/src/types.ts
packages/salesforce-adapter/src/filters/global_value_sets.ts

The code assumed that `GlobalValueSet.customValue` is an array, even though it can return as single value (When only 1 value exists in the permission set)

SALTO-3479: Bugfix

---

packages/salesforce-adapter/src/client/jsforce.ts
packages/salesforce-adapter/src/metadata_deploy.ts

Apex test failure showed stack trace as [object Object], so changed stack trace interface to be `string | object`
---
---
Salesforce:
* Stack traces for apex test failures will no longer show as [object Object]
---

SALTO-3405 - test failure stack trace can be string or object

---

packages/jira-adapter/src/change_validators/workflow_scheme_migration.ts
packages/jira-adapter/test/change_validators/workflow_scheme_migration.test.ts

missing items on workflow scheme changes caused a bug when we tried to iterate the items.
there was a check for it that missed this flow so i changed it as well.
---
---
---

SALTO-3857/missing items bug

---

packages/okta-adapter/src/adapter_creator.ts
packages/stripe-adapter/src/adapter_creator.ts
packages/zuora-billing-adapter/src/adapter_creator.ts

Hide Okta, Zuora and Stripe types by default
---
_Stripe adapter_:
* The types folder will be hidden by default
* The types folder will be hidden by default
_Zuora-Billing adapter_:
* The system types folder will be hidden by default. Standard and custom object definitions will still be visible.
---
_Stripe adapter_:
* The types folder will be hidden by default
* The types folder will be hidden by default
_Zuora-Billing adapter_:
* The system types folder will be hidden by default. Standard and custom object definitions will still be visible.

SALTO-3713: Hide Okta, Zuora and Stripe types by default

---

packages/salesforce-adapter/src/filters/minify_deploy.ts
packages/salesforce-adapter/test/filters/minify_deploy.test.ts

Fixed a bug upon deployment of `PermissionSet` instances.
---
As part of our previous work on [SALTO-2770](https://salto-io.atlassian.net/browse/SALTO-2770), we implemented support on minifying the deployed PermissionSet instances, similarly to what we do with `Profile` instances. This logic caused the rest of the stuff that were not modified to be completely removed.
I've ran the following scenario:
- Adding `objectPermissions` on my `PermissionSet` instance.
- Deploying.
- Fetching post deploy.
You can see how the rest of the properties were removed from the instance (Which means were deleted in the service)
Here is the workspace diff to demonstrate that: https://github.com/salto-io/tamir-sf/compare/66e1655c4e5690e70a57170f8c995bf96cc0d64a..dbc0e96b64487f5356a305fc07ed6c2137379518
--- …

SALTO-3847: PermissionSet instances deployment bugfix

---

packages/salesforce-adapter/src/change_validators/unknown_picklist_values.ts
packages/salesforce-adapter/test/change_validators/unknown_picklist_values.test.ts

Fixed two issues in this PR:
- The `Change Validator` won't error on optional picklist fields that have no value.
- The `ChangeError` will be attached to the instance instead of the field.
---
This is how the Change Error looks like:
```
Unknown picklist value "Unknown Value" on field SBQQ__Action__c of instance salesforce.SBQQ__CustomAction__c.instance.Add_Favorites@s
envs/sf11/salesforce/InstalledPackages/SBQQ/Records/SBQQ__CustomAction__c/Add_Favorites.nacl(line: 1)
Error: Supported values are ["Add Products","Add Favorites","Upgrade Assets","Renew Subscriptions","Amend Subscriptions","Add Recommendations","Save","Quick Save","Cancel","Calculate","Delete Lines","Add Group","Ungroup","Add Solution Group","Reset Discounts","Optional: All","Optional: None","Clone Group","Delete …
```

SALTO-3858: unknown picklist values Change Validator bugfix

---

packages/netsuite-adapter/src/change_validators/client_validation.ts
packages/netsuite-adapter/src/client/deploy_xml_utils.ts
packages/netsuite-adapter/test/change_validators/client_validation.test.ts

When there are SDF objects being deployed we validate them with the file cabinet instances, but when there are only file cabinet instances being deploy we shouldn't run NS validation using SDF.
---
---
- Skip NS validation when there are only file cabinet instances
---
None

SALTO-3016 skip NS validation when there are only file cabinet instances

---

packages/netsuite-adapter/src/changes_detector/changes_detector.ts
packages/netsuite-adapter/test/changes_detector/changes_detector.test.ts

---
---
- Partial fetch - skip changed file cabinet objects query when no files/folders are included
---
None

Skip changed file cabinet objects query when no files/folders are included

---

packages/adapter-components/src/client/pagination.ts
packages/okta-adapter/config_doc.md
packages/okta-adapter/src/adapter.ts
packages/okta-adapter/src/client/pagination.ts
packages/okta-adapter/src/config.ts
packages/okta-adapter/src/filters/user.ts
packages/okta-adapter/test/adapter.test.ts
packages/okta-adapter/test/filters/user.test.ts

Replace user ids with usernames in Okta
---
Replace user ids in Okta's instances with user login which is a unique identifier for users in Okta.
---
None
---
None

SALTO-3608: Replace user ids with usernames in Okta

---

packages/jira-adapter/src/adapter_creator.ts
packages/jira-adapter/src/config_creator.ts
packages/jira-adapter/test/config_creator.test.ts

Added support to receive the ScriptRunner configuration from the UI
---
_Same as zendesk and salesforce_
---
None
---
None

SAAS-7388: support ScriptRunner checkbox in UI

---

packages/okta-adapter/src/reference_mapping.ts

Added reference from IdentityProviderPolicyRule to Application type in Okta
---
I added reference from conditions.app.include.id and conditions.app.exclude.id to application type in Okta. 
---
None
---
None

SALTO-3846 Add reference  from IdentityProviderPolicyRule to Application type in Okta

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/change_validators/project_category.ts
packages/jira-adapter/src/filters/project.ts
packages/jira-adapter/src/filters/project_category.ts
packages/jira-adapter/test/change_validators/project_category.test.ts
packages/jira-adapter/test/filters/project_category.test.ts

_Add filter to support projectCategory deployment_
---
* as far as I know, DC API does not allow to remove projectCategory form a Project without assign new one to it.
* I added a change validator for the DC case as well.
---
Jira adapter:
* add support in deployment of assigning Project Category to a Project 
---
None

SALTO-3776: add filter to support projectCategory deployment - Jira

---

packages/core/src/core/fetch.ts

**Log the reasons of Config Suggestions**
---
_Additional context for reviewer_ 
I added a log in `fetch.ts` in core that describes the reasons for config suggestions if needed. 
---
None
---
None

SALTO-3793: Log reasons of config suggestion

---

packages/core/src/api.ts
packages/core/src/core/fetch.ts
packages/core/test/api.test.ts
packages/workspace/src/workspace/path_index.ts
packages/workspace/test/workspace/path_index.test.ts

on partial fetches there was a bug that removed the path index and top level path index entries that were not fetched in the partial fetch.
we already had a logic to maintain accounts not fetched that collected all of their elements and then pushed them back inside the index after we cleared it.
I used the same logic to update the partially fetched accounts with a slight change to how we merge the old entires and new entries so we enforce that the new changes make it into the index.
---
tested manually, looking into adding a ut.
---
core
* fixed bug with partial fetches removing entries from path index.
---

SALTO-3835/partial fetch path index bug

---

packages/lowerdash/src/collections/array.ts
packages/lowerdash/test/collections/array.test.ts
packages/salesforce-adapter/src/fetch.ts
packages/salesforce-adapter/test/adapter.discover.test.ts

For some reason, on rare occasions we get the same fullName from listMetadataObjects more than once This leads to duplicate instances which cause colisions and other problems down the line
There is no point to fetch the same fullName more than once, so removing the duplicates seems like the reasonable thing to do
---
---
- Fix rare issue of fetch failing to return some elements due to merge errors
---
_None_

SALTO-3873: Remove duplicates from listMetadataObjects in salesforce

---

packages/zendesk-adapter/src/filters/unordered_lists.ts
packages/zendesk-adapter/test/filters/unordered_lists.test.ts

sort additional zendesk fields to ignore order difference
---
---
zendesk:
* sort additional zendesk fields to ignore order difference
---
zendesk:
* for type `dynamic_content_item` the `variants` array will change its order
* for type `macro` the `restriction.ids` array will change its order
* for type `ticket_form` the arrays `child_fields` , `agent_conditions` and `end_user_conditions` will change their order

SALTO-3799: sort additional zendesk fields to ignore order difference

---

packages/zendesk-adapter/src/filters/organizations.ts

Resolve organizationIDs for views in Zendesk
---
_Zendesk_:
- Fix a bug causing unresolved organization IDs in views when `resolveOrganizationIDs` is enabled
---
_Zendesk_:
- If `resolveOrganizationIDs` flag is enabled, organization IDs in views will be replaced with organization names

SALTO-3888: Resolve organizationIDs for views in Zendesk

---

packages/netsuite-adapter/src/adapter.ts

_enable fetching reports and layouts by default for all users_
---
_None_
---
* reportDefinitions and financialLayouts will be fetched by default and no longer need to be specified explicitly in the config
---
_reportDefinitions and financialLayouts nacls will be added to the WS/Env_

PROD-76: enable fetching reports and layouts by default for all users

---

packages/jira-adapter/src/config_creator.ts
packages/jira-adapter/test/config_creator.test.ts

This reverts commit 9a4bafc6cd7d57ca904e28bd1036bc1650c77ca4.
Returning the fix
---
None
---
None

SAAS-7338: ScriptRunner UI re-revert typo

---

packages/adapter-api/src/element_id.ts
packages/adapter-api/test/elements.test.ts
packages/adapter-components/src/references/context.ts
packages/core/src/core/fetch.ts
packages/lang-server/src/usage.ts
packages/netsuite-adapter/src/adapter.ts
packages/workspace/src/parser/dump.ts
packages/workspace/src/workspace/alias_index.ts
packages/workspace/test/workspace/alias_index.test.ts

fix default alias for instances with config name
---
currently when no alias is provided we calculate the alias from the prettified name. however for setting instances for which their name is `_config` the default alias received is `config` and we don’t want that. So I am changing the default to be the type.
---
None
---
None

SALTO-3872: fix default alias for instances with config name

---

packages/okta-adapter/src/config.ts

Extract AuthorizationServer scopes and claims to standalone fields
---
I didn't deleted `scopes` and `claims` from `fieldTypeOverrides`, because it is crucial for the standAlone field to work. 
---
None
---
None

SALTO-3599 Extract AuthorizationServer scopes and claims to standalone fields

---

packages/netsuite-adapter/src/adapter.ts

The `omitFields` filter should run last so the user will be able to omit values that were added/transformed in other filters.
---
---
- Support omitting settings/data values with fieldsToOmit
---
None

SALTO-3796 Support omitting settings/data values with fieldsToOmit

---

packages/jira-adapter/src/config/api_config.ts

Fixed some projects and issue types of field contexts not being paginated and therefore limited to 50
---
- Fixed a bug when fetching a field context projects and issue types that only the first 50 were fetched
---
- Some additional projects and issue types of field contexts might be fetched (only if there a field contexts with more than 50 issue types or projects)

SALTO-3922: FieldContext projects and issue types are not paginated

---

packages/jira-adapter/src/change_validators/field_contexts/field_contexts.ts
packages/jira-adapter/test/change_validators/field_contexts/field_contexts.test.ts

Fixed field contexts validator to not return errors about elements in the plan
---
- Fixed field contexts validator to not return errors about elements in the plan
---
None

SALTO-3923: fieldContextValidator can return errors on contexts that are not in the plan

---

packages/jira-adapter/src/filters/dashboard/dashboard_layout.ts
packages/jira-adapter/test/filters/dashboard/dashboard_layout.test.ts

Fixed a bug that when we fail to fetch a certain dashboard layout value the entire fetch would fail
---
- Fixed a bug that when we fail to fetch a certain dashboard layout value the entire fetch would fail
---
None

SALTO-3928: 403 when fetching a dashboard fails the entire fetch

---

packages/salesforce-adapter/src/transformers/reference_mapping.ts

Do not merge without noise reduction
---
[workspace diff](https://github.com/salto-io/adi-ws/commit/f4416ae56d93263c34830b4142fc698ae31ed0a3)
---
Salesforce:
* Add references to table and field in DuplicateRuleFilterItem
---
_User Notifications_:  _None_

SALTO-3801 add missing references to DuplicateRuleFilterItem

---

packages/salesforce-adapter/src/transformers/reference_mapping.ts

Add the reference
---
WS Diff: https://github.com/salto-io/tomsellek-sf/pull/5
---
Salesforce: HomePageComponent.links will now correctly refer to the appropriate CustomPageWebLink records
---
N/A

SALTO-3748 - Salesforce: Missing reference in HomePageComponent to CustomLink

---

packages/netsuite-adapter/src/changes_detector/changes_detector.ts
packages/netsuite-adapter/src/changes_detector/changes_detectors/custom_record_type.ts
packages/netsuite-adapter/src/changes_detector/changes_detectors/custom_type.ts
packages/netsuite-adapter/src/changes_detector/changes_detectors/file_cabinet.ts
packages/netsuite-adapter/src/changes_detector/changes_detectors/role.ts
packages/netsuite-adapter/src/changes_detector/changes_detectors/savedsearch.ts
packages/netsuite-adapter/src/changes_detector/changes_detectors/script.ts
packages/netsuite-adapter/src/changes_detector/date_formats.ts
packages/netsuite-adapter/src/changes_detector/types.ts
packages/netsuite-adapter/src/filters/author_information/system_note.ts
packages/netsuite-adapter/test/changes_detector/changes_detector.test.ts
packages/netsuite-adapter/test/changes_detector/custom_field.test.ts
packages/netsuite-adapter/test/changes_detector/custom_list.test.ts
packages/netsuite-adapter/test/changes_detector/custom_record_type.test.ts
packages/netsuite-adapter/test/changes_detector/custom_records.test.ts
packages/netsuite-adapter/test/changes_detector/date_formats.test.ts
packages/netsuite-adapter/test/changes_detector/file_cabinet.test.ts
packages/netsuite-adapter/test/changes_detector/role.test.ts
packages/netsuite-adapter/test/changes_detector/savedsearch.test.ts
packages/netsuite-adapter/test/changes_detector/script.test.ts
packages/netsuite-adapter/test/filters/author_information/system_note.test.ts

Should not query system notes specifically in order to know which objects have been changed - we can get the info from the queries of each type.
---
---
- Improve NS quickFetch changed-objects queries
---
None

SALTO-3856 improve NS quickFetch changed-objects queries

---

packages/netsuite-adapter/src/change_validators/extra_reference_dependencies.ts
packages/netsuite-adapter/src/filters/additional_changes.ts
packages/netsuite-adapter/test/change_validators/extra_reference_dependencies.test.ts
packages/netsuite-adapter/test/filters/additional_changes.test.ts

We should add/warn about additional changes for SDF objects only.
There was a case now when we added additional changes for a file element, because it had generated dependencies for `translationcollection` instance that is required in SDF objects deploy - but for file elements we shouldn't add it.
---
---
- Add/warn about additional changes for SDF objects only
---
None

Add/warn about additional changes for SDF objects only

---

packages/lowerdash/src/types.ts

Add XOR to lowerdash to eventually get rid of all `ts-xor` imports in the code-base and use the better (written by @ori-moisis version)
---
None
---
None

SALTO-3933 - Add XOR to lowerdash

---

packages/salesforce-adapter/src/change_validators/unknown_picklist_values.ts

Reduce severity to warning because of potential false positives Include details in the detailed message
---
Removed validation on multi-select picklist fields because the code did not handle those values
see SALTO-3936 for more details
---
_None_
---
_None_

SALTO-3127: Fix supported values change validator message and severity

---

packages/adapter-components/src/references/field_references.ts
packages/adapter-components/src/references/index.ts
packages/adapter-components/src/references/missing_references.ts
packages/adapter-components/src/references/reference_mapping.ts
packages/adapter-components/test/references/field_references.test.ts
packages/adapter-components/test/references/missing_references.test.ts
packages/okta-adapter/src/reference_mapping.ts
packages/zendesk-adapter/src/filters/article/article_body.ts
packages/zendesk-adapter/src/filters/dynamic_content_references.ts
packages/zendesk-adapter/src/filters/field_references.ts
packages/zendesk-adapter/src/filters/handle_template_expressions.ts
packages/zendesk-adapter/src/filters/references/list_values_missing_references.ts
packages/zendesk-adapter/src/filters/references/missing_references.ts
packages/zendesk-adapter/src/filters/side_conversation.ts
packages/zendesk-adapter/test/filters/article/article_body.test.ts
packages/zendesk-adapter/test/filters/dynamic_content_references.test.ts
packages/zendesk-adapter/test/filters/handle_template_expressions.test.ts
packages/zendesk-adapter/test/filters/side_conversation.test.ts

Add missing references to Okta
---
Add missing references to Okta & move shared code from zendesk to adapter-components
Didn't add config flag as we have in zendesk, if u think it's necessary lmk
---
None
---
None

SALTO-3600, SALTO-3393: Add missing references to Okta

---

packages/adapter-utils/src/references.ts
packages/adapter-utils/test/references.test.ts
packages/okta-adapter/src/change_validators/group_rule_administrator.ts
packages/okta-adapter/src/change_validators/index.ts
packages/okta-adapter/test/change_validators/group_rule_administrator.test.ts
packages/zendesk-adapter/src/change_validators/unique_locale_per_variant.ts
packages/zendesk-adapter/src/filters/macro_attachments.ts
packages/zendesk-adapter/src/filters/utils.ts

1. In this PR I  added a change validator that validates that the target Group for GroupRule has no administrator role.
2. I added test for this CV. 
3. I changed the location of `isArrayOfRefExprToInstances` from zendesk adapter to adapter-utils. 
---
In Order to test the code manually - do as follows:
1. fetch an Okta env
2. Check for a group instance with roles filed or create one yourself. 
Example:
`okta.Group All_IL@s {
objectClass = [
"okta:user_group",
]
type = "OKTA_GROUP"
profile = {
name = "All IL"
description = "all the employees living in israel"
}
roles = [
okta.Role.instance.API_Access_Management_Administrator@s,
]
}`
4. Create new groupRule that points to this group
Example:
`okta.GroupRule Me_to_All_IL {
type = "group_rule"
status = …

SALTO-3573 Validate target Group for GroupRule has no administrator role

---

packages/netsuite-adapter/package.json
yarn.lock

Based on our new SDF release: https://github.com/salto-io/netsuite-suitecloud-sdk/commit/32bce130b7b73ab2450bb0a1710213a76b0d82c4
---
None
---
None

SALTO-3966: Remove vm2 dependency by upgrading SDF version

---

packages/okta-adapter/src/adapter.ts
packages/okta-adapter/src/config.ts
packages/okta-adapter/src/constants.ts
packages/okta-adapter/src/filters/authorization_server_rule.ts
packages/okta-adapter/src/filters/user.ts
packages/okta-adapter/test/filters/authorization_server_rule.test.ts

Support deployment of `AuthorizationServerPolicy` and `AuthorizationServerPolicyRule` instances
---
In order to deploy `AuthorizationServerPolicyRule`, we need the `AuthorizationServerPolicy` id and the `AuthorizationServer` id, which is not a direct parent of `AuthorizationServerPolicyRule`. Therefore, during fetch we add for each `AuthorizationServerPolicyRule` the related `AuthorizationServer` as a second parent.
---
None
---
None

SALTO-3932: Add deploy for AuthorizationServerPolicy & AuthorizationServerPolicyRule

---

packages/workspace/src/merger/internal/common.ts
packages/workspace/src/merger/internal/instances.ts

Avoid logging inside reference expressions etc.
we lose _some_ information, but I think it is usually better than the current state.
---
None
---
None

SALTO-3969 use safeJsonStringify in merge logs

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/filters/macro.ts
packages/zendesk-adapter/test/filters/macro.test.ts

fix deployment of macro restriction modification
---
To modify the macro restriction to all agents we need to pass in the request `restriction = null`
---
zendesk: 
* fix bug where restrictions were not removed from macros that already had restrictions defined
---
None

SALTO-3901: fix deployment of macro restriction modification

---

packages/okta-adapter/src/change_validators/group_rule_status.ts
packages/okta-adapter/src/config.ts
packages/okta-adapter/src/deployment.ts
packages/okta-adapter/src/filters/app_deployment.ts
packages/okta-adapter/src/filters/default_rule_deployment.ts
packages/okta-adapter/test/change_validators/group_rule_status.test.ts
packages/okta-adapter/test/deployment.test.ts

Allow creating instances in any status
---
In Okta, each type has its default status when created. For example `GroupRule` instances are created in status `INACTIVE` by default, and `AccessPolicyRule` created in status `ACTIVE`.
Until now, instances were created with their default status. This PR add the option to created instance in a different status from the default one.
---
None
---
None

SALTO-3809: Deploy addition change of instance in different status from the default status

---

packages/zendesk-adapter/src/change_validator.ts
packages/zendesk-adapter/src/change_validators/guide_disabled.ts
packages/zendesk-adapter/src/change_validators/index.ts
packages/zendesk-adapter/test/change_validators/guide_disabled.test.ts

1. In this PR I added a change validator that validates that the user Cannot add instance when its associated brand has help center disabled.
2. I added test for this CV.
---
In Order to test the code manually - do as follows:
1. Create two environments in Zendesk.
2. Check\create two brands with the same name. 
3. Make sure that one brand has help center enabled and one brand has help center disabled. 
4. clone a sub guide element from the brand in the env with help center enabled to the env with help center disabled. 
5. try to deploy the new env. 
---
I added change validator to validate that it is not possible to add instance when its associated brand has help center disabled.
---
None

SALTO-3786 Add change validator to check that guide is enabled when changing guide elements

---

packages/zendesk-adapter/src/change_validators/automation_all_conditions.ts
packages/zendesk-adapter/src/filters/tag.ts
packages/zendesk-adapter/src/filters/utils.ts
packages/zendesk-adapter/src/replacers_utils.ts
packages/zendesk-adapter/test/change_validators/automation_all_conditions.test.ts
packages/zendesk-adapter/test/filters/tag.test.ts

isCondition schema validation should allow values to be references
---
---
None
---
None

SALTO-3705: isCondition schema validation should allow values to be references

---

packages/adapter-components/src/client/pagination.ts
packages/adapter-components/test/client/pagination.test.ts

Fix bug in the pagination logic, where we would stop pagination not only if a page was empty, but also if the filtered results of the page (when using a custom entry extractor) were empty. this can cause pagination to stop mid-way (e.g. in jira - if a full page of project-scope entries is received).
---
This only impacted Jira, since this is currently the only adapter using a `customEntryExtractor`.
---
* Fix bug where in some cases not all instances would be returned during fetch, when a full page of project-scoped items was returned.
---
* Fix bug where in some cases not all instances would be returned during fetch

SALTO-3978 Avoid stopping pagination on empty filtered page

---

packages/workspace/src/workspace/workspace.ts

When the ignoreFileChanges flag to loadWorkspace is set to true, skip all calculations Before this change there was a case where workspace indices would still be calculated in order to make sure the workspace state is valid once it is loaded.
however, the meaning of ignoreFileChanges is now extended to ignore all changes, including cache invalidation in that case, there is no need to check anything when the workspace is loaded
---
No release notes because no flow in the OSS uses this flag
---
_None_
---
_None_

SAAS-7602: Skip all workspace updates on ignoreFileChanges

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/filters/custom_role_deploy.ts
packages/zendesk-adapter/test/filters/custom_role_deploy.test.ts

fix deploy of custom_role modification
---
---
zendesk:
* fix bug in the deployment of custom_role modification (specifically modifications in roles that cannot be fully edited such as `light_agent`)
---
None

SALTO-3866: fix deploy of custom_role modification

---

packages/netsuite-adapter/src/filters/author_information/system_note.ts
packages/netsuite-adapter/test/filters/author_information/system_note.test.ts

_Systemnotes recordtypes query changed to use IN instead of concatenation of OR's_
---
_None_
---
_None_
---
_None_

SALTO-3763: update system note query

---

packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts

_Removed fixDeployXml call in sdf_client to revert SALTO-2865_
---
_None_
---
_Netsuite Adapter:_
* deploy.xml will no longer be ordered according to reference level
---
_None_

remove fixDeployXml call in sdf_client to revert SALTO-2865

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/test/adapter.test.ts

Fix bug in Zendesk where we would sometimes run into merge conflicts on deploy, due to the `id` values not being hidden properly.
The scenario is very specific:
1. The fetch config has Guide enabled, but no matching brand has Guide enabled in the service
2. An instance is added during deploy for a type that has 0 existing instances (and has an `id` field)
---
The reason this happens is that we use `addRemainingTypes` to ensure all hidden fields are defined properly - and this function did not run in this scenario due to an early return. 
---
_Zendesk Adapter_:
* Fix bug where deploying the first instance of its kind might result in merge errors, for environments with Guide enabled but without Guide elements
---
None

SALTO-3779 Always add remaining types on fetch

---

packages/okta-adapter/src/config.ts

Mainly hide & omit fields from types, split `Brand` type to its subtypes
---
None
---
None

SALTO-3529: Clean nacls in Okta

---

packages/netsuite-adapter/src/filters/internal_ids/sdf_internal_ids.ts

_Add internal id as a hidden field to savedsearch_
---
---
_NS Adapter:_
* Add internal id as a hidden field to savedsearch.
---
_NS Adapter:_
* The saved search type will now have an internal id as a hidden annotation.

Add internal id as a hidden field to savedsearch

---

packages/okta-adapter/src/change_validators/custom_application_status.ts
packages/okta-adapter/src/filters/app_deployment.ts
packages/okta-adapter/test/change_validators/custom_application_status.test.ts
packages/okta-adapter/test/filters/app_deployment.test.ts

Okta's API doesn't support changes of custom apps in status `INACTIVE`, in order to allow it, we activate the app, make the relevant changes and deactivate it 
---
None
---
None

SALTO-3929: Allow modifications of custom apps in status INACTIVE

---

packages/adapter-components/src/config/swagger.ts
packages/adapter-components/test/config/swagger.test.ts
packages/adapter-components/test/elements/swagger/petstore_swagger.v2.yaml
packages/adapter-components/test/elements/swagger/type_elements.test.ts

Change typeNameOverrides validations
---
duplicates across `originalName` and `newName` are supported by the infra so in this PR I changed the validation to validate there are no dups in `newName` and `originalName` separately
---
None
---
None

SALTO-3997: Change typeNameOverrides validations

---

packages/adapter-components/src/elements/ducktype/transformer.ts
packages/adapter-components/src/elements/field_finder.ts
packages/adapter-components/test/elements/ducktype/transformer.test.ts

_fix fetch error for one category in a brand and no articles_
---
---
zendesk:
* fix fetch error for one category in a brand and no articles
---
None

SALTO-4000: fix fetch error for one category in a brand and no articles

---

packages/salesforce-adapter/src/transformers/transformer.ts

Marked the widely used `apiName` utility as deprecated (in favor of `safeApiName`)
This is how it looks like in my IDE:
---
_None_
---
_None_

SALTO-3635: Salesforce `apiName` utility deprecation

---

packages/netsuite-adapter/src/change_validator.ts
packages/netsuite-adapter/src/change_validators/unique_fields.ts
packages/netsuite-adapter/test/change_validators/unique_fields.test.ts

[Netsuite Adapter]
Add a new change validator to the Netsuite adapter.
This validator validates uniqueness of:
-  savedSearch titles (FIELD_DEFAULT_NAME in nacl files).
- financialLayout name
- customrecordtype fields scriptid 
---
Netsuite does not allow duplicated savedSearch titles, duplicated financiallayout name field and inner customrecordtype fields scriptids, even between different customrecordtypes.
Currently there isn't a validator for that and the deployment will fail.
---
Netsuite - validate unique title field in saved search instances, financial layout instances and custom record types during deployment.

SALTO-2915: Netsuite - add change validator for a unique title field in saved search instance

---

packages/zendesk-adapter/src/filters/handle_template_expressions.ts
packages/zendesk-adapter/test/filters/handle_template_expressions.test.ts

If an instance that is being handled by handle_template_expression contains an unresolved reference, convert it to an empty string instead of crashing
---
None
---
* Fixed deploy crashing with a modification of an instance with removal of a reference that contains an unresolved reference
---
None

SALTO-3988 - Handle unresolved references in handle_template_expressions

---

packages/netsuite-adapter/e2e_test/adapter.test.ts
packages/netsuite-adapter/src/suiteapp_file_cabinet.ts
packages/netsuite-adapter/test/suiteapp_file_cabinet.test.ts

_File cabinet query will not contain paths excluded in the adapter config_
---
_None_
---
__Netsuite Adapter__:
* Paths excluded in the adapter config will be filtered out before creating the file cabinet query and will not be queried
---
_None_

Incident-3894: Improve file cabinet long query

---

packages/adapter-api/src/element_id.ts
packages/adapter-api/src/values.ts
packages/workspace/src/merger/internal/common.ts
packages/workspace/src/merger/internal/instances.ts

Alternative to https://github.com/salto-io/salto/pull/4215 (that also reverts it), since it seems using `safeJsonStringify` with a replacer here is not efficient enough (`inspect` truncates after a max depth / array length).
---
there was a problem with adding similar handling for static files that requires more debugging and is not critical to the fix, so starting without it
---
None
---
None

SALTO-3969 Avoid logging inside references in merge logs

---

packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
packages/netsuite-adapter/src/suiteapp_file_cabinet.ts
packages/netsuite-adapter/test/client/suiteapp_client.test.ts
packages/netsuite-adapter/test/suiteapp_file_cabinet.test.ts

Throw an indicative error instead of throwing a generic "Failed to list folders" error.
---
---
- Throw indicative error on missing SuiteBundler feature in SuiteApp FileCabinet fetch
---
None

SALTO-4019 throw on missing SuiteBundler feature in SuiteApp FileCabinet fetch

---

packages/jira-adapter/jest.config.js
packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/change_validators/workflows/circular_transitions.ts
packages/jira-adapter/src/filters/workflow/circular_transitions_filter.ts
packages/jira-adapter/src/filters/workflow/resolution_property_filter.ts
packages/jira-adapter/src/filters/workflow/types.ts
packages/jira-adapter/src/filters/workflow/workflow_deploy_filter.ts
packages/jira-adapter/test/change_validators/workflows/circular_transitions.test.ts
packages/jira-adapter/test/filters/workflow/circular_transitions_filter.test.ts
packages/jira-adapter/test/filters/workflow/steps_deployment.test.ts
packages/jira-adapter/test/filters/workflow/triggers_deployment.test.ts
packages/jira-adapter/test/filters/workflow/workflow_deploy_filter.test.ts
packages/jira-adapter/test/filters/workflow/workflow_properties_filter.test.ts
packages/jira-adapter/test/filters/workflow/workflow_structure_filter.test.ts

added a change validator to warn about circular transitions and a filter to prevent their deployment
---
* Jira Adapter:
Fixed a bug where circular workflow transitions prevented deployment
---
None

SALTO-3986: omit circular transitions from deployment and warn

---

packages/jira-adapter/src/reference_mapping.ts
packages/okta-adapter/src/reference_mapping.ts

Fix for a theoretical bug - we were assuming all lookup functions were sync (which they currently are, but are not required to be)
---
None
---
None

SALTO-4029 correctly support async lookup functions

---

packages/netsuite-adapter/src/filters/author_information/constants.ts
packages/netsuite-adapter/src/filters/author_information/saved_searches.ts
packages/netsuite-adapter/src/filters/author_information/system_note.ts
packages/netsuite-adapter/test/filters/author_information/saved_searches.test.ts
packages/netsuite-adapter/test/filters/author_information/system_note.test.ts

Refactor & use the account's date&time format to check if a date is a future date.
---
---
- Fix date format for future dates validation in saved searches
---
None

Fix date format for future dates validation in saved searches

---

packages/salesforce-adapter/config_doc.md
packages/salesforce-adapter/src/change_validator.ts
packages/salesforce-adapter/src/change_validators/data_category_group.ts
packages/salesforce-adapter/src/constants.ts
packages/salesforce-adapter/src/types.ts
packages/salesforce-adapter/test/change_validators/data_category_group.test.ts
packages/salesforce-adapter/test/mock_elements.ts

add CV for DataCategoryGroup addition or modification, since it could be destructive 
---
---
- Add ChangeValidator for addition or modification of DataCategoryGroup, since metadata changes may be destructive
---
_None_

SALTO-2824 DataCategoryGroup CV

---

packages/okta-adapter/src/change_validators/assigned_policies.ts
packages/okta-adapter/src/change_validators/index.ts
packages/okta-adapter/test/change_validators/assigned_policies.test.ts

Okta doesn't allow deactivation of `AccessPolicy` if the policy is used by `Application`
---
None
---
None

SALTO-3883: Verify user is not trying to deactivate assigned AccessPolicy instances

---

.github/workflows/notices.yml

Retry "yarn" command
---
---
_None_
---
_None_

SALTO-4040: Fix attribution NOTICES file workflow

---

packages/netsuite-adapter/config_doc.md
packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/client/client.ts
packages/netsuite-adapter/src/client/manifest_utils.ts
packages/netsuite-adapter/src/client/types.ts
packages/netsuite-adapter/src/config.ts
packages/netsuite-adapter/test/adapter.test.ts
packages/netsuite-adapter/test/adapter_creator.test.ts
packages/netsuite-adapter/test/change_validator.test.ts
packages/netsuite-adapter/test/client/client.test.ts
packages/netsuite-adapter/test/client/manifest_utils.test.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts

_files referenced in sdf and aren't deployed at the exact deployment will added as dependencies in the manifest_
---
_None_
---
* All files referenced in SDF will be added as dependencies in the manifest
---
_None_

SALTO-3371: files referenced in SDF are not written as dependencies in the manifest

---

packages/core/src/core/plan/filter.ts
packages/core/test/core/plan/filter.test.ts

Omit dependency errors for anything nested inside something that already has errors.
---
This should help solve the unreadability of errors when new objects/instances are added and all their fields have dependency errors because the parent has a dependency error
---
Core:
- Omit dependency errors for elements whose parent already failed due to dependency error
---

SALTO-3780 omit dependency nested errors

---

packages/okta-adapter/src/config.ts

Hide non multi-env fields in AuthorizationServer
---
None
---
None

SALTO-3983: Hide non multi-env fields in AuthorizationServer

---

packages/okta-adapter/src/adapter.ts
packages/okta-adapter/src/config.ts
packages/okta-adapter/src/filters/expression_language.ts
packages/okta-adapter/src/filters/profile_enrollment_attributes.ts
packages/okta-adapter/src/reference_mapping.ts
packages/okta-adapter/test/filters/expression_language.test.ts
packages/okta-adapter/test/filters/profile_enrollment_attributes.test.ts

Add references from `ProfileEnrollmentPolicyRule` to `UserSchema`
---
`ProfileEnrollmentPolicyRule` have a list of attributes required from the user in order to login. those attributes are taken from the default user `UserSchema`. Also, user can provide attributes that doesn't exist in the schema, Okta will allow it but Okta's UI will show an error, so in this case we add a missing reference.
This PR also fixes a bug in references to custom attributes in expression_language.ts filter 
---
None
---
None

SALTO-3805: Profile attribute references

---

packages/netsuite-adapter/src/change_validator.ts
packages/netsuite-adapter/src/change_validators/inactive_parent.ts
packages/netsuite-adapter/test/change_validators/inactive_parent.test.ts

Add change validator to throw an error when assigning an inactive parent to data element.
---
Currently deployment fails on NetSuite when modifying a parent field to reference an inactive parent.
The new validator
---
NetSuite adapter:
- Change validator will throw an error when trying to deploy assignment of inactive parent to a data element.
---
None

SALTO-3795: Add change validator to validate inactive parent assignment.

---

packages/okta-adapter/src/filters/expression_language.ts
packages/okta-adapter/test/filters/expression_language.test.ts

Add missing references for Okta Expression Language templated
---
For now the best way to detect a missing reference to group (without changing the entire filter) is to check if the `id` starts with `00g` which is the prefix of group ids in Okta in general (from what I saw)
---
None
---
None

SALTO-4063: Add missing references for Okta Expression Language templates

---

packages/workspace/src/parser/internal/native/consumers/values.ts
packages/workspace/src/parser/internal/native/parse.ts
packages/workspace/test/parser/parse.test.ts

When there is an invalid character in a NaCl (e.g., `'`), the NaCl is ignored and no error is returned 
---
_Core_:
- Fixed a bug where no error would be returned when there is an invalid character in the NaCl (e.g., `'`)
---
None

SALTO-3855: NaCls with invalid characters are ignored

---

packages/netsuite-adapter/src/service_url/constant_urls.ts

_support open in app for reportdefinitions and financiallayout_
---
_None_
---
* Open in app is supported for `reportdefinition` and `financiallayout` types
---
_None_

SALTO - 3380: support open in app for reportdefinition and financial layout

---

packages/okta-adapter/src/adapter.ts
packages/okta-adapter/src/filters/template_urls.ts
packages/okta-adapter/test/filters/template_urls.test.ts

Converts BrandTheme favicon url to TemplateExpression
Added fetch only cause `BrandTheme` deploy is not supported yet
---
None
---
None

SALTO-3987: Converts BrandTheme favicon url to TemplateExpression

---

packages/okta-adapter/src/change_validators/enabled_authenticators.ts
packages/okta-adapter/src/change_validators/index.ts
packages/okta-adapter/src/config.ts
packages/okta-adapter/src/reference_mapping.ts
packages/okta-adapter/test/change_validators/enabled_authenticators.test.ts

Support deployment of authenticators
---
- There is not endpoint for `remove`, deactivating `Authenticator` removes it from the admin console
- I added a CV that verifies `Authenticator` is not being used in MFA policy before its deactivation
- added ref
---
None
---
None

SALTO-4057: Add deploy for Authenticator type

---

packages/netsuite-adapter/src/type_parsers/report_definition_parsing/parsed_report_definition.ts

_FIELD_VALUE field in reportdefinition.criteria changed from string to unkown type_
---
_None_
---
_Netsuite Adapter:_
* FIELD_VALUE field in reportdefinition type is changed to from string to unknown type
---
* FIELD_VALUE field in reportdefinition type is changed to from string to unknown type

SALTO-4047: fix FIELD_VALUE warning in reportdefinition criteria

---

packages/okta-adapter/src/config.ts

Until we'll fetch `UISchema` type, we should hide `uiSchemaId` field from `ProfileEnrollmentRule` type to avoid diffs when comparing envs
---
None
---
None

SALTO-4071: Hide UISchemaId Field

---

packages/salesforce-adapter/src/filters/custom_object_instances_references.ts
packages/salesforce-adapter/test/filters/custom_object_instances_references.test.ts

When a single instance of a certain type had empty Salto ID, we didn't omit the instance but treated it as it was a **Settings Instance**.
---
I've added additional handling in [customObjectInstancesReferences](https://github.com/salto-io/salto/blob/main/packages/salesforce-adapter/src/filters/custom_object_instances_references.ts) for this edge case. I've tried to make the fetch warning as similar as possible to the collision warning.
---
Omitted 13 instances of Account due to Salto ID collisions.
Current Salto ID configuration for Account is defined as [UniqueField__c].
Breakdown per colliding Salto ID:
- Instances with empty name (Due to no values in any of the provided ID fields):
* https://salto68-dev-ed.develop.my.salesforce.com/0018d00000Q8k44AAB
* …

SALTO-3990: Omit Custom Object instances with empty Salto ID

---

packages/cli/src/commands/fetch_diff.ts
packages/core/src/api.ts
packages/core/src/core/fetch.ts

calcFetchChanges returns an array instead of iterator
---
There is no change of the logic, it was always an array that was returned as an iterator
---
None
---
None

SALTO-4080 - Change the return type of calcFetchChanges to array instead of iterator

---

packages/zendesk-adapter/src/filters/utils.ts

schema validation for subject conditions should allow reference expression
---
---
none
---
none

SALTO-3705: schema validation for subject conditions should allow reference expression

---

packages/netsuite-adapter/src/client/client.ts
packages/netsuite-adapter/src/client/deploy_xml_utils.ts
packages/netsuite-adapter/src/client/graph_utils.ts
packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/test/adapter.test.ts
packages/netsuite-adapter/test/client/client.test.ts
packages/netsuite-adapter/test/client/deploy_xml_utils.test.ts
packages/netsuite-adapter/test/client/graph_utils.test.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts

_do not list explicitly in the deploy.xml elements that have a circular dependeny_
---
_None_
---
* Elements that have circular dependency will not be listed explicitly in deploy.xml to avoid circular dependency error
---
_None_

Salto-3868: reorder deploy xml only for elements not in cycle

---

packages/adapter-api/src/author_information.ts
packages/adapter-api/test/author_information.test.ts
packages/cli/test/mocks.ts
packages/core/src/core/fetch.ts
packages/workspace/src/workspace/alias_index.ts
packages/workspace/src/workspace/author_information_index.ts
packages/workspace/src/workspace/changed_at_index.ts
packages/workspace/src/workspace/changed_by_index.ts
packages/workspace/src/workspace/index_utils.ts
packages/workspace/src/workspace/static_files_index.ts
packages/workspace/src/workspace/workspace.ts
packages/workspace/test/workspace/author_information_index.test.ts
packages/workspace/test/workspace/index_utils.test.ts
packages/workspace/test/workspace/workspace.test.ts

Added author information index that maps element ids to author information (changedBy & changedAt).
Added `getElementAuthorInformation` function to workspace API.
---
---
Workspace:
- Added author information index that maps element ids to author information (changedBy & changedAt)
- Added `getElementAuthorInformation` function to workspace API
---
None

SALTO-3918 author information index

---

packages/salesforce-adapter/src/filters/field_references.ts
packages/salesforce-adapter/src/transformers/reference_mapping.ts

Ain't no party like a reference party cuz a reference party don't
---
Note that the reference is to a RecordType object. I'm not 100% sure I did this the right way so please verify.
[WS Diff](https://github.com/salto-io/tomsellek-sf/pull/6)
---
Salesforce: AnimationRule.recordTypeName references now work as expected
---
N/A

SALTO-3384 - Salesforce: Missing reference from AnimationRule.recordTypeName

---

packages/adapter-components/src/elements/instance_elements.ts
packages/adapter-components/test/elements/swagger/instance_elements.test.ts

fixed bug causing us to look at the standalone field type transformation and not the parent when writing the standalone instance.
causing us to ignore the parent's  "nestStandaloneInstances: false" and nesting the instance anyway.
---
I added a test to simulate a case with true default nestStandaloneInstances and false on specific type.
---
---

SALTO-4083/standlone field bug

---

packages/netsuite-adapter/config_doc.md
packages/netsuite-adapter/src/adapter_creator.ts
packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
packages/netsuite-adapter/src/config.ts
packages/netsuite-adapter/test/adapter_creator.test.ts

* Increase axios timeout (on SuiteApp) from 12 minutes to 20.
* Allow the user to control it through the config file.
* Add validation to the suitAppClient config.
---
---
---

SALTO-3971: Increase axios timeout and make it configurable

---

packages/okta-adapter/src/config.ts

Omit appLinks field from Application
---
the field causes unwanted diffs between envs, its not visible in the UI and it doesn't change with API requests
---
None
---
None

SALTO-4089: Omit appLinks field from Application

---

packages/adapter-api/src/adapter.ts
packages/cli/src/commands/apply_patch.ts
packages/cli/src/commands/index.ts
packages/cli/test/commands/apply_patch.test.ts
packages/core/index.ts
packages/core/src/api.ts
packages/core/test/api.test.ts
packages/salesforce-adapter/src/adapter_creator.ts
packages/salesforce-adapter/src/sfdx_parser/sfdx_parser.ts
packages/salesforce-adapter/test/sfdx_parser/sfdx_parser.test.ts

What's here? 
CLI - 
* Renamed `fetch-diff` to `apply-patch`
* Moved the Changes calculation logic to be a core api to extracted a lot of the logic outside of the CLI
Core - 
* Added `loadElementsFromFolder` to the adapter api (not under operations cause it doesn't require the context)
* Created a new `calculatePatch` api that gets a workspace and 2 folders with SFDX content (this is currently restricted only to salesforce) and returns a "FetchResult" to apply to the workspace
---
TODO:
---
*Core*:
* Add calculatePatch to the core api. It gets a workspace and two path directories with external service format (ie. SFDX) content, calculates the diff between them, translates them to Changes and returns "FetchResult" to be applied to the Workspace.
*CLI*:
* Rename the …

SALTO- 4008 - Move FetchDiffToWorkspace to core + add loadElementsFromFolder to the adapter api

---

packages/okta-adapter/src/filters/expression_language.ts

Fix bug causing removals of instances with templates containing missing refs to fail
---
What happened is that when trying to resolve references for templates with missing refs during pre deploy, we got an error because the reference wasn't resolved
To fix this I filtered  the changes for the `TemplateExpression` filter to be addition of modification changes only, cause there's no point to resolve templates for removals changes (Okta ignores data on `delete` method)
---
None
---
None

SALTO-4092: Fix bug causing removals of instances with templates containing missing refs to fail

---

packages/netsuite-adapter/src/change_validators/client_validation.ts
packages/netsuite-adapter/src/client/client.ts
packages/netsuite-adapter/src/client/deploy_xml_utils.ts
packages/netsuite-adapter/src/client/errors.ts
packages/netsuite-adapter/src/client/graph_utils.ts
packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/src/client/types.ts
packages/netsuite-adapter/test/adapter.test.ts
packages/netsuite-adapter/test/client/client.test.ts
packages/netsuite-adapter/test/client/deploy_xml_utils.test.ts
packages/netsuite-adapter/test/client/graph_utils.test.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts

- Remove the `graph.key` attribute and use `node.id` instead.
- Use the graph as the only SOT in SDF deploy iterations (instead of using also `changesToDeploy`)
---
---
None
---
None

Refactor SDF dependencies graph

---

packages/okta-adapter/src/change_validators/app_group.ts
packages/okta-adapter/src/change_validators/index.ts
packages/okta-adapter/test/change_validators/app_group.test.ts

Block additions or modifications of APP_GROUP in Okta
---
it is not supported through the API
---
None
---
None

SALTO-2692: Block additions or modifications of APP_GROUP in Okta

---

packages/adapter-utils/src/filter.ts
packages/salesforce-adapter/src/filter.ts
packages/salesforce-adapter/src/sfdx_parser/sfdx_parser.ts

Moved `LocalFilterCreatorDefinition`, `RemoteFilterCreatorDefinition`, `isLocalFilterCreator` from SF adapter to adapter-utils in order to share it in NS adapter.
---
---
None
---
None

SALTO-4104 Move Local & Remote Filter Creator Definitions to adapter-utils

---

packages/jira-adapter/src/filters/account_id/account_id_filter.ts
packages/jira-adapter/test/filters/account_id/account_id_filter.test.ts

Came from an incident, hard to verify this is the cause but it makes sense and recreates
---
None
---
Jira Adapter:
* Fixed a bug that caused null values to fail the fetch 
---
None

SALTO-4107: add check for null on account id

---

packages/okta-adapter/src/config.ts
packages/okta-adapter/src/filters/delete_fields.ts
packages/okta-adapter/test/filters/delete_fields.test.ts

Remove policyRules field from policies
---
The field is added during `recurseInto` so it must be removed with filter
---
None
---
None

SALTO-4087: Remove policyRules field from policies

---

packages/workspace/src/workspace/static_files/functions.ts
packages/workspace/test/workspace/static_files/functions.test.ts

_Fix the dump of a Missing Static File which currently leads to a parse error_
---
---
_Core_
* Fix the dump of a Missing Static File which currently leads to a parse error
---

SALTO-4046 Add support for invalid static files for copying between accounts

---

packages/okta-adapter/src/adapter.ts
packages/okta-adapter/src/change_validators/index.ts
packages/okta-adapter/src/change_validators/user.ts
packages/okta-adapter/src/filters/user.ts
packages/okta-adapter/test/change_validators/users.test.ts
packages/okta-adapter/test/filters/user.test.ts

Add missing users validator for Okta
---
Similar to what we have in Zendesk & Jira
---
None
---
None

SALTO-3953: Validate users exists in target env validator for Okta

---

packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
packages/netsuite-adapter/src/client/utils.ts

The thrown value can be different from an `Error` object so `e.message.includes` can fail on `Cannot read property 'includes' of undefined`.
---
---
- Fix error catching in SOAP client
---
None

SALTO-4112 fix error catching in SOAP client

---

packages/adapter-components/src/deployment/change_validators/check_deployment_based_on_config.ts
packages/adapter-components/test/deployment/change_validators/check_deployment.test.ts
packages/okta-adapter/src/change_validators/index.ts
packages/zendesk-adapter/src/change_validator.ts

Add CheckDeploymentBasedOnConfigValidator to Okta
---
I merged the swagger types config with the ducktype types config so the validator would work on both
---
None
---
None

SALTO-4095: Add CheckDeploymentBasedOnConfigValidator to Okta

---

packages/zendesk-adapter/src/change_validator.ts
packages/zendesk-adapter/src/change_validators/guide_disabled.ts
packages/zendesk-adapter/test/change_validators/guide_disabled.test.ts

__In this PR__ 
1. I modified the guide_disabled validator that validates that the user Cannot add instance when its associated brand has help center disabled or its associated brand is not include in the config. I found a great function that checks both in `utils` so I changed a lot in this CV. 
2. I added test for this CV.
---
In Order to test the code manually - do as follows:
1. Create two environments in Zendesk.
2. Check\create two brands with the same name. 
3. Make sure that one brand has help center enabled and one brand has help center disabled. 
Or make sure the one brand is part of the config and the other one isn't. 
5. clone a sub guide element from the brand in the env with help center enabled to the env with help center disabled. 
Example …

SALTO-4073 Modified guide_disabled_validator

---

packages/okta-adapter/src/change_validators/user.ts
packages/okta-adapter/test/change_validators/users.test.ts

Fix bug in missing users validator causing users to get errors for changes in instances that don't have users path
---
None
---
None

SALTO-4127: Fix bug in missing users validator

---

packages/salesforce-adapter/src/filters/custom_type_split.ts

I am not proud of this. But after https://github.com/salto-io/salto/pull/4348 this will actually matter a bit and fit our use-case better.
---
None
---
None

SALTO-4120 - Change the order of the paths in CustomObject split

---

packages/workspace/src/workspace/path_index.ts
packages/workspace/test/workspace/path_index.test.ts

We have an issue when using `splitElementByPath` and using a pathIndex that does not have information for all the elemIDs that are being split. For example splitting an Object type and one if the fields does not exist in the pathIndex.
This is caused by the fact that `getFromPathIndex` returns the hints of the "closest" parent, even if that parent has multiple hints.
This changes the logic so that for elemIDs that exist in the pathIndex, we will still return all the relevant hints, but for those who do not, we will still use the closest parent's hints, but only one of them and not all the hints cause returning multiple will eventually cause merge errors for this element since the part that does not exist in the pathIndex will appear in multiple fragments.
---
*Core*:
* …

SALTO-4120 - Change getFromPathIndex to not return multiple hints for elemIDs that do not exist in the pathIndex

---

packages/zendesk-adapter/src/filters/webhook.ts
packages/zendesk-adapter/test/filters/webhook.test.ts

deploy webhook with api_key as authentication
---
---
zendesk:
* Fix deploy of webhook when authentication is  api_key
---
none

SALTO-4124: deploy webhook with api_key as authentication

---

packages/adapter-components/src/elements/request_parameters.ts
packages/adapter-components/test/elements/request_parameters.test.ts

Fix error for fetch with no categories
---
---
zendesk: 
* Fix error for fetch of guide with no categories
---
None

SALTO-4129: Fix error for fetch with no categories

---

packages/jira-adapter/src/filters/fields/context_options.ts
packages/jira-adapter/test/filters/fields/context_options.test.ts

set context options batch sizes to 1000 at the time,
added tests to mock the behavior of jira's servers but i wasnt able to system test it myself.
---
---
jira_adapter:
* fixed bug with context options failing to update because there were over 1000 updating at the same request.
---

SALTO-4090/batch context options

---

packages/okta-adapter/src/filters/app_deployment.ts
packages/okta-adapter/test/filters/app_deployment.test.ts

Add deployment annotations to notify users `features` field will not be deployed.
---
When enabling provisioning for app, `features` field is added to app instance. Okta doesn't support managing those settings and provisioning settings must be managed through the admin console. 
This doesn't fail the request so we don't need to remove it before deployment.
---
- Add support in Okta
- When trying to deploy provisioning features for apps, user will be notified the action is not supported
---
None

SALTO-4110: Provisioning features for apps cannot be managed

---

packages/jira-adapter/src/filters/script_runner/script_template_expressions.ts
packages/jira-adapter/src/filters/script_runner/workflow/walk_on_scripts.ts
packages/jira-adapter/test/filters/script_runner/script_template_expressions.test.ts

If a script field of scriptrunner is null the fetch fails. Added to the undefined checks also null checks
---
Jira Adatper:
* Fixed a bug that caused null scripts in scriptrunner to fail the fetch
---
None

SALTO-4133: Failed on null values in scripts

---

packages/okta-adapter/src/config.ts

Add deploy for TrustedOrigin type in Okta
---
None
---
None

SALTO-4123: Add deploy for TrustedOrigin type in Okta

---

packages/okta-adapter/src/config.ts
packages/okta-adapter/src/reference_mapping.ts

Support Device Assurance policies in Okta
---
Added fetch, deploy, and reference from `AccessPolicyRule` to the new type 
---
None
---
None

SALTO-3576: Support Device Assurance policies in Okta

---

packages/jira-adapter/e2e_test/instances/cloud/workflow.ts
packages/jira-adapter/e2e_test/instances/datacenter/workflow.ts
packages/jira-adapter/jest.config.js
packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/change_validators/workflows/workflow_properties.ts
packages/jira-adapter/src/filters/workflow/triggers_deployment.ts
packages/jira-adapter/src/filters/workflow/types.ts
packages/jira-adapter/src/filters/workflow/workflow_deploy_filter.ts
packages/jira-adapter/src/filters/workflow/workflow_diagrams.ts
packages/jira-adapter/src/reference_mapping.ts
packages/jira-adapter/test/filters/workflow/workflow_deploy_filter.test.ts
packages/jira-adapter/test/filters/workflow/workflow_diagrams.test.ts

_Add support in fetching and deploying workflow diagrams_
---
Noise suppression can be found [here](https://github.com/salto-io/salto_private/pull/5587)
The statuses will have a new 'direction' field with its diagram coordinates: 
The transition 'from' field will contain the source and the target angles of the related statuses in the diagram, in addition to the 'from status' id:
---
* add support in fetching and deploying workflow diagrams
---
* workflow statuses will have 'direction' field that represents its diagram coordinates
* workflow transitions 'from' field will include the angles of the source and the target of the related statuses in the diagram.

SALTO-2678: Support fetching and deploying workflow diagrams - Jira

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/deployment.ts
packages/zendesk-adapter/src/filters/routing_attribute_value.ts
packages/zendesk-adapter/test/deployment.test.ts
packages/zendesk-adapter/test/filters/routing_attribute_value.test.ts

prevent deploy of routing attribute value to happen in parallel
---
---
zendesk:
* Fix issue that prevented deploying multiple values under the same routing attribute
---
None

SALTO-4085: prevent deploy of routing attribute value to happen in parallel

---

packages/salesforce-adapter/src/metadata_deploy.ts

Salesforce test failures will not show the character `\n` and instead go down a line as required
---
before:
after:
---
- Sanitize test failures to create newline instead of showing escaped character
---

SALTO-4150: Sanitize test failure output

---

packages/dummy-adapter/src/adapter.ts
packages/dummy-adapter/src/adapter_creator.ts
packages/dummy-adapter/src/generator.ts
packages/dummy-adapter/test/adapter.test.ts
packages/dummy-adapter/test/adapter_creator.test.ts
packages/dummy-adapter/test/test_params.ts

Added `fieldsToOmit` to dummy so it will be easier to test deploy that omit fields from instances
---
None
---
None

SALTO-4067: Added fieldsToOmit to dummy adapter

---

packages/vscode/README.md
packages/vscode/package.json

Update extension's details before publishing to VS Code marketplace
---
---
_VS Code_:
- Update texts for VS Code extension
---
None

SALTO-4137: Update extension details before publishing to VS Code marketplace

---

packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts

_In case there are no folders to query, Dont query files at all instead of querying the entire file cabinet._
---
_This is a first pr for - https://salto-io.atlassian.net/browse/SALTO-4140?focusedCommentId=81758&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-81758, The main target of it is to add logs for us to have better visibility to allow us find the underline cause_
---
_Netsuite Adapter:_
* When there are no folders to query we don't query files at all.
---
_None_

Salto-4140: Avoid querying entire file cabinet

---

packages/adapter-utils/src/walk_element.ts

Add try-catch so in case we get another typescript error we will know in which element it happened 
---
---
None
---
None

SALTO-4147: Add logs for ScriptRunner failures

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/config/config.ts
packages/jira-adapter/src/filters/remove_specific_duplicate_roles.ts
packages/jira-adapter/test/filters/remove_specific_duplicate_roles.test.ts

Omitting duplicate a specific built-in project role that can be caused by deleting team-managed project
---
See details in the Jira ticket
This is a bandage fix for a Jira bug.
When you create a team-managed project several project-scoped roles are created by default, including atlassian-addons-project-access
When you delete a team-managed project all its project-scope roles are not really deleted.
They keep appearing in the roles API answer, but without the project scope. They are not visible in the UI
This fix will only address atlassian-addons-project-access as it is a built-in role, will always be there
and the global role will (hopefully) always have the lower id
The entire feature is under a config flag: fetch->removeDuplicateProjectRoles 
---
Jira Adapter:
* …

SALTO-4065: Remove specific duplicate project roles

---

packages/netsuite-adapter/src/client/deploy_xml_utils.ts
packages/netsuite-adapter/test/client/deploy_xml_utils.test.ts

_FileCabinet elements will not be ordered in deploy.xml_
---
_None_
---
_None_
---
_None_

SALTO-3907: fix error when deploying nested files and folders

---

packages/core/src/core/diff.ts
packages/workspace/src/workspace/element_selector.ts

Add log.time to selectElementIdsByTraversal & getEnvsDeletionsDiff
No logic was changed even tho git has trouble identifying it :\ 
---
---
None
---
None

SALTO-4171 - Add log.time to selectElementIdsByTraversal & getEnvsDeletionsDiff

---

packages/workspace/src/parser/internal/native/consumers/values.ts
packages/workspace/src/parser/internal/native/lexer.ts
packages/workspace/test/parser/parse.test.ts

_Update parser (lexer) to support very long string contents_
---
* The previous version of the single line string content was using a complex regex, which cause errors for extremely long strings.
This fix optimizes it by splitting the way the lexer tokenizes string parts.
---
_Parser_
* Update parser to support very long string contents
---

SALTO-4125 Update parser to support very long string contents

---

packages/jira-adapter/e2e_test/instances/cloud/fieldConfiguration.ts
packages/jira-adapter/e2e_test/instances/cloud/index.ts
packages/jira-adapter/e2e_test/instances/datacenter/fieldConfiguration.ts
packages/jira-adapter/e2e_test/instances/datacenter/index.ts
packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/change_validators/unresolved_field_configuration_items.ts
packages/jira-adapter/src/config/config.ts
packages/jira-adapter/src/dependency_changers/field_configuration.ts
packages/jira-adapter/src/dependency_changers/index.ts
packages/jira-adapter/src/filters/field_configuration/field_configuration_deployment.ts
packages/jira-adapter/src/filters/field_configuration/field_configuration_items.ts
packages/jira-adapter/src/filters/field_configuration/field_configuration_split.ts
packages/jira-adapter/src/filters/field_configuration/replace_field_configuration_references.ts
packages/jira-adapter/test/change_validators/unresolved_field_configuration_items.test.ts
packages/jira-adapter/test/dependency_changers/field_configuration.test.ts
packages/jira-adapter/test/filters/field_configuration/field_configuration_deployment.test.ts
packages/jira-adapter/test/filters/field_configuration/field_configuration_items.test.ts
packages/jira-adapter/test/filters/field_configuration/field_configuration_split.test.ts
packages/jira-adapter/test/filters/field_configuration/replace_field_configuration_references.test.ts

Combined all field configuration items to be part if the field configuration.
This is how the field configuration will look after this change:
```
jira.FieldConfiguration emptyConfig4 {
name = "emptyConfig4"
description = ""
fields = {
Approvers__multiuserpicker__c = {
description = "Contains users needed for approval. This custom field was created by Jira Service Desk."
isHidden = false
isRequired = false
}
Impact__select__c = {
description = ""
isHidden = false
isRequired = false
}
...
}
```
---
In this PR there are:
- The filter that removes the references from the field configurations
- The dependency changer that adds dependency between the field configuration to its fields (since there aren't references and the dependency is not created automatically)
- A change validator that do a …

SALTO-4067: Consolidate FieldConfigurationItem into FieldConfiguration

---

packages/salesforce-adapter/src/filters/custom_metadata_to_object_type.ts
packages/salesforce-adapter/src/filters/custom_objects_to_object_type.ts
packages/salesforce-adapter/test/filters/custom_metadata_to_object_type.test.ts
packages/salesforce-adapter/test/filters/custom_objects_to_object_type.test.ts

Add Aliases to Salesforce CustomObjects.
---
Covers **CustomSettings**, **CustomMetadata types** and **CustomObjects**
Workspace diff: https://github.com/salto-io/tamir-sf/commit/dc123103190ddc96fc6ae019ef65a373cb2a722d
---
- Added aliases to Salesforce Custom Objects. 
---
_None_

SALTO-4141: Salesforce CustomObjects Aliases

---

packages/adapter-components/src/elements/ducktype/transformer.ts
packages/adapter-components/src/elements/request_parameters.ts
packages/adapter-components/src/elements/swagger/instance_elements.ts
packages/adapter-components/test/elements/ducktype/transformer.test.ts
packages/okta-adapter/src/config.ts

Fix bug in adapter-components that caused `EmailTemplate` type not to return during fetch
---
The bug happened when when using `recurseInto` in type A and `dependsOn` in type B (that depends on A)
This caused `contextElements` for type A to include all instances returned in `recurseInto` as well
and then, when fetching type B, we used instances returned from `recurseInto` and not just instances from type A
The solution was to create a reverse mapping for supported types (because dependsOn is using the page types but the context elements are from "items" types), and filter in `dependsOn` func to only for instances from the relevant types
---
None
---
None

SALTO-4163: Fix bug in adapter-components when using both dependsOn and recurseInto

---

packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/dependency_changer.ts
packages/netsuite-adapter/test/dependency_changer.test.ts

Suitescript files generated dependencies can cause a circular dependencies error between SDF deploy group and SuiteApp FileCabinet deploy group, although there is no real dependency between them (there is a real dependency between the script instance and the file instance, so the file instance should be deployed before).
In order to solve it, we remove the dependencies that file instances have. This should have no harm (as the file instance itself don’t really depend on anything but its parent folder).
---
---
- Fix circular dependencies in suitescript files deploy
---
None

SALTO-4064 Fix circular dependencies in suitescript files deploy

---

packages/jira-adapter/src/dependency_changers/global_field_contexts.ts
packages/jira-adapter/src/filters/fields/context_deployment_filter.ts
packages/jira-adapter/src/utils.ts
packages/jira-adapter/test/dependency_changers/global_field_contexts.test.ts
packages/jira-adapter/test/filters/fields/field_context_deployment.test.ts

fixed bug causing us to try and remove an already removed context (which happens when a user removes a field but keeps the nacls of the contexts and then removes them before the next fetch.
---
---
jira adapter:
* fixed bug with removing field contexts after the field was already removed.
---

SALTO-4081/orphan contexts

---

packages/okta-adapter/src/config.ts

Add missing `serviceUrl` annotations to Okta config.
---
Okta adapter:
- Add support for go-to-service to Okta settings types

SALTO-4078: Add missing serviceUrl annotations to Okta config

---

packages/salesforce-adapter/src/change_validators/unknown_users.ts
packages/salesforce-adapter/test/change_validators/unknown_users.test.ts
packages/salesforce-adapter/test/mock_elements.ts

Another field with a user ID we can validate
---
The logic here is similar to `FolderShare.sharedTo`, so I merged the logic of the two fields into a single function
---
Salesforce: The user referenced in WorkflowTask.assignedTo is now verified
---
N/A

SALTO-4027 - Salesforce: verify another user reference

---

packages/jira-adapter/src/client/client.ts

Increased the default concurrent connections from 20 to 60, which should improve the fetch performance
---
Jira Adapter:
* Increased the default concurrent connections limit, which significantly improves the fetch performance
---
None

SALTO-4149: Increase default concurrent connections

---

packages/core/src/core/deploy/deploy_actions.ts

We want to log the deploy plan of users so we can better understand on what types we should focus and to have better monitoring of deployment errors.
The new logs look likes this:
```
2023-05-21T08:03:08.958Z info core/core/deploy/deploy_actions Deploy item zendesk.ticket_field.instance.Ticket_status_custom_status@suu
2023-05-21T08:03:08.958Z info core/core/deploy/deploy_actions Deploy change zendesk.ticket_field.instance.Ticket_status_custom_status@suu.raw_title (action=modify)
2023-05-21T08:03:08.959Z info core/core/deploy/deploy_actions Deploy change zendesk.ticket_field.instance.Ticket_status_custom_status@suu.raw_description (action=modify)
```
---
---
None
---
None

SALTO-1857: Add logs to the deploy plan

---

packages/jira-adapter/src/filters/statuses/status_deployment.ts
packages/jira-adapter/test/filters/statuses/status_deployment.test.ts

add retry for status deployment when we receive a specific error from the service with "Failed to acquire lock"
---
since i was not able to reproduce the error myself i found the specific log that had the request error in it and made a unit test that mocks that error.
---
jira adapter:
* add retry to specific deployment bug for statuses.
---

SALTO-4044/retry on status deployment error

---

packages/jira-adapter/src/filters/field_configuration/replace_field_configuration_references.ts
packages/jira-adapter/test/filters/field_configuration/replace_field_configuration_references.test.ts

made sure we dont put back field items that were not found in the element source (and deployed) after deploying field configurations.
---
there was a test literarily named according to what i need but the test did the opposite. i changed the test to actually work.
i didnt add any other tests.
---
jira_adapter:
* when deploying field configurations, if a field did not exist salto will remove it from the nacl on deploy.
---

SALTO-4160/remove unknown fields on deploy
