packages/okta-adapter/jest.config.js

SALTO-2747: Update coverage settings

---

README.md
packages/netsuite-adapter/src/change_validators/immutable_changes.ts
packages/netsuite-adapter/test/change_validators/immutable_changes.test.ts

_Add validation for script id when adding new elements_
---
---
Netsuite adapter: 
* Add validation for script id when adding new elements
---
None

SALTO-3121 Add validation for script id when adding new elements

---

packages/zendesk-adapter/src/filters/unordered_lists.ts

_zendesk fix sort logs_
---
---
None
---
None

SALTO-4017: zendesk fix sort logs

---

packages/jira-adapter/src/constants.ts
packages/jira-adapter/src/filters/automation/automation_fetch.ts
packages/jira-adapter/src/filters/automation/automation_label/label_fetch.ts
packages/jira-adapter/src/filters/data_center/priority_scheme/priority_scheme_fetch.ts
packages/jira-adapter/test/filters/automation/automation_fetch.test.ts
packages/jira-adapter/test/filters/automation/automation_label/label_fetch.test.ts
packages/jira-adapter/test/filters/data_center/priority_scheme/priority_scheme_fetch.test.ts

Fixed for automation, automationLabel, and Priority Scheme
---
Fixed a bug that failed fetches of non-admin users
---
None

SALTO-4010: Resolve fetch failures for non admin users

---

packages/okta-adapter/src/config.ts

fix dataField
---
None
---
None

SALTO-4015: EmailNotifications dataField

---

packages/okta-adapter/src/filters/field_references.ts
packages/okta-adapter/src/reference_mapping.ts
packages/okta-adapter/test/filters/field_references.test.ts

Missing references for ProfileMapping
---
References might be for `Application` type or for `UserType` type, so i also added context functions for references in Okta
---
None
---
None

SALTO-4005: Missing references for ProfileMapping

---

packages/netsuite-adapter/src/change_validators/client_validation.ts
packages/netsuite-adapter/test/change_validators/client_validation.test.ts

_handle account settings validation fail in ObjectsDeployError error message_
---
_bugfix for - https://salto-io.atlassian.net/browse/INCIDENT-4508_
---
_None_
---
_None_

INCIDENT-4508 - fix error message handling for account settings validation fail

---

packages/okta-adapter/src/reference_mapping.ts

Enable missing reference for Application references
---
None
---
None

SALTO-4020: Enable missing reference for Application references

---

packages/adapter-components/src/config/ducktype.ts
packages/adapter-components/src/config/request.ts
packages/adapter-components/src/config/shared.ts
packages/adapter-components/src/config/swagger.ts
packages/adapter-components/src/config/transformation.ts
packages/adapter-components/test/config/request.test.ts
packages/adapter-components/test/config/transformation.test.ts
packages/okta-adapter/src/config.ts

Add optional prefix for config type name
---
None
---
None

SALTO-4016: Add optional prefix for config type name

---

packages/sap-adapter/src/config.ts

small leftover from https://github.com/salto-io/salto/pull/4206#discussion_r1181237111
---
None
---
None

fix SAP config

---

packages/jira-adapter/src/filters/automation/smart_values/smart_value_reference_filter.ts

Internal code bug that seems without influence but is risky
---
None
---
None

SALTO 4086: Fix async code bug in smart values

---

packages/zendesk-adapter/src/filters/unordered_lists.ts

fix sort of ticket form conditions
---
---
zendesk:
* fix sort of ticket form conditions
---
None

SALTO-4053: fix sort of ticket form conditions

---

packages/netsuite-adapter/src/change_validators/immutable_changes.ts
packages/netsuite-adapter/test/change_validators/immutable_changes.test.ts

_Update field scriptid validation to apply only on custom fields_
---
---
_NetSuite Adapter_
* Update field scriptid validation to apply only on custom fields
---

Update field validation only for custom fields

---

packages/workspace/src/workspace/alias_index.ts
packages/workspace/test/workspace/alias_index.test.ts
packages/workspace/test/workspace/workspace.test.ts

alias index to include only elements with alias defined
---
---
None
---
None

SALTO-4012: alias index to include only elements with alias defined

---

packages/core/src/local-workspace/remote_map.ts

While chasing down an issue that was discovered thanks to the existing logs, we realized some more information would make debugging easier.
---
---
N/A
---
N/A

SALTO-4118 - Improve logging in createRemoteMapCreator

---

packages/okta-adapter/src/config.ts
packages/okta-adapter/src/filters/expression_language.ts
packages/okta-adapter/src/filters/field_references.ts
packages/okta-adapter/test/filters/expression_language.test.ts
packages/okta-adapter/test/filters/field_references.test.ts

add enableMissingReferences flag in Okta
---
None
---
None

SALTO-4076: enableMissingReferences flag in Okta

---

packages/netsuite-adapter/src/config.ts
packages/netsuite-adapter/test/config.test.ts

Delete deprecated config suggestions:
Some config suggestions on Netsuite modified old config format to the new one. 
This format was replaced *22 months ago* which makes it irrelevant now.
---
---
---

SALTO-4122: Delete deprecated config suggestions

---

packages/core/src/local-workspace/remote_map.ts

SALTO-4118 - fix logging from previous PR

---

packages/netsuite-adapter/src/filters/author_information/system_note.ts
packages/netsuite-adapter/test/filters/author_information/system_note.test.ts

_Simplified systemNotes field query to help avoid timeouts_
---
_None_
---
_None_
---
_None_

Salto-3875: Improve fields system notes query that is used for chaged by/at

---

packages/salesforce-adapter/src/change_validators/fullname_changed.ts

See PR title
---
---
N/A
---
N/A

SALTO-4156 - Salesforce: Switch the message and detailed message of the fullname_changed CV

---

packages/vscode/README.md

Update more texts in VS Code README
---
None
---
None

SALTO-4162: Update more texts in VS Code README

---

packages/netsuite-adapter/src/client/deploy_xml_utils.ts
packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/src/client/sdf_parser.ts
packages/netsuite-adapter/src/client/types.ts
packages/netsuite-adapter/src/filters/config_features.ts
packages/netsuite-adapter/test/adapter.test.ts
packages/netsuite-adapter/test/client/mocks.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts
packages/netsuite-adapter/test/client/sdf_parser.test.ts
packages/netsuite-adapter/test/transformer.test.ts

In order to be able to load elements from existing SDF projects.
---
---
None
---
None

SALTO-2428 separate SDF parser code from SDF client

---

packages/jira-adapter/src/change_validators/unresolved_field_configuration_items.ts
packages/jira-adapter/src/dependency_changers/field_configuration.ts
packages/jira-adapter/src/filters/field_configuration/field_configuration_deployment.ts
packages/jira-adapter/src/filters/field_configuration/replace_field_configuration_references.ts
packages/jira-adapter/test/change_validators/unresolved_field_configuration_items.test.ts
packages/jira-adapter/test/filters/field_configuration/replace_field_configuration_references.test.ts

Limited the number of fields to show in the messages and added some logs
---
None
---
None

SALTO-4067: Changes to field configuration

---

packages/netsuite-adapter/src/changes_detector/changes_detector.ts

Bug fix: support file cabinet partial fetch
---
None
---
Bug fix - can now support partial fetch for file cabinet
---
None

SALTO-4189 Fix file-cabinet partial-fetch bug

---

packages/netsuite-adapter/config_doc.md
packages/netsuite-adapter/src/client/file_cabinet_utils.ts
packages/netsuite-adapter/test/client/file_cabinet_utils.test.ts

_Enable limiting the amount of FileCabinet data we fetch_
---
---
---

Update log message for file cabinet large folders

---

packages/netsuite-adapter/test/changes_detector/changes_detector.test.ts
packages/netsuite-adapter/test/client/suiteapp_client/suiteapp_file_cabinet.test.ts

File cabinet partial fetch unit tests
---
None
---
None
---
None

SALTO-4189 File cabinet partial fetch unit tests

---

packages/salesforce-adapter/package.json
yarn.lock

SALTO-4198: use proper built package for salesforce formula parser

---

packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts

Change Json encoding
---
None
---
Now we support Json files in file cabinet. fetch, deploy and preview
---
None

Support JSON files in file-cabinet

---

packages/zendesk-adapter/test/adapter.test.ts

add test to adapter that checks that unresolved references are omitted from array in deploy
---
---
None
---
None

SALTO-4232: add test to adapter that checks that unresolved references are omitted from array in deploy

---

packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts

revert PR 4419
---
https://github.com/salto-io/salto/pull/4419
---
None
---
None

Revert support of JSON files in file-cabinet

---

packages/netsuite-adapter/src/filters/data_instances_internal_id.ts
packages/netsuite-adapter/test/filters/data_instances_internal_id.test.ts

_fix bug preventing deployments of statistical accounts_
---
_None_
---
---
_id field will be added in the unitsType, mainAddress and state fields_

Salto-4054: unable to deploy statistical accounts in netsuite

---

packages/workspace/src/workspace/element_selector.ts

Improved performance of selectElementIdsByTraversal by using withLimitedConcurrency instead of awu.forEach
---
None
---
None

SALTO-4171 - selectElementIdsByTraversal concurrent subElements calculations

---

packages/jira-adapter/src/filters/dashboard/gadget_properties.ts
packages/jira-adapter/test/filters/dashboard/gadget_properties.test.ts

Fixed null values in gadget properties
---
None
---
None

SALTO-4259: fix null values in gadget properties

---

packages/jira-adapter/src/filters/dashboard/gadget_properties.ts
packages/jira-adapter/test/filters/dashboard/gadget_properties.test.ts

Fixed empty gadget properties
---
None
---
None

SALTO-4259: Fixed empty gadget properties

---

packages/salesforce-adapter/src/fetch.ts

SALTO-4274 - Salesforce: Improve logging of failed calls to retrieve

---

packages/jira-adapter/src/filters/dashboard/gadget_properties.ts
packages/jira-adapter/test/filters/dashboard/gadget_properties.test.ts

Convert properties in any depths from map to list in gadgets
---
- Properties in any depths in gadgets will be converted from map to list
---
- Properties in any depths in gadgets will be converted from map to list

SALTO-4259: Convert properties in any depths from map to list in gadgets

---

packages/jira-adapter/jest.config.js

Lowered Jira coverage threshold so the build will pass
---
None
---
None

Lowered Jira coverage threshold

---

packages/netsuite-adapter/src/client/language_utils.ts
packages/netsuite-adapter/test/client/sdf_client.test.ts

Add regex for missing features in SDF deploy

---

packages/zendesk-adapter/src/filters/article/article.ts
packages/zendesk-adapter/src/filters/article/article_body.ts

Will need to continue looking into this (and reducing the code duplication), but starting with fixing the uninformative logs
---
None
---
None

SALTO-4312 add details to logs

---

packages/salesforce-adapter/src/filters/centralize_tracking_info.ts

Log cases where the object-level toggle is missing yet there are other indications that the object supports history tracking.
---
See the comments in https://salto-io.atlassian.net/browse/PROD-93 for background on why this situation happens. We want to get a better understanding of which types exhibit this behaviour so we can decide on a workaround.
---
N/A
---
N/A

SALTO-4309 - Salesforce: add logs to history tracking filter

---

packages/jira-adapter/src/deployment/standard_deployment.ts
packages/jira-adapter/test/adapter.test.ts
packages/jira-adapter/test/deployment/standard_deployment.test.ts
packages/jira-adapter/test/filters/issue_type_schemas/issue_type_scheme.test.ts
packages/jira-adapter/test/filters/workflow/workflow_modification_filter.test.ts

Change Jira adapter to return SaltoElementErrors
---
None
---
None

SALTO-4217: Change Jira adapter to return SaltoElementErrors

---

packages/salesforce-adapter/src/additional_references.ts
packages/salesforce-adapter/test/additional_references.test.ts

Changed the dependency from field to profile to be from profile to field
---
None
---
None

SAAS-8004: Reversed the dependency between a profile and a field

---

packages/adapter-api/src/values.ts
packages/adapter-api/test/values.test.ts
packages/core/src/api.ts
packages/core/src/core/plan/dependency/reference_dependency.ts
packages/core/src/core/plan/plan.ts
packages/core/test/core/plan/plan.test.ts
packages/okta-adapter/src/change_validators/group_schema_modify_base_fields.ts
packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
packages/zendesk-adapter/e2e_test/adapter.test.ts
packages/zendesk-adapter/src/filters/article/utils.ts
packages/zendesk-adapter/src/filters/guide_arrange_paths.ts
packages/zendesk-adapter/test/filters/guide_arrange_paths.test.ts

SALTO-4301, SALTO-4248 revert
---
---
---

SALTO-4301, SALTO-4248 revert

---

packages/salesforce-adapter/src/metadata_deploy.ts

Add mapping so that during failures we will be able to know the element ID of the instance.
---
---
_None_
---

SALTO-4288 add mapping between type and full name and ElemID

---

packages/zendesk-adapter/src/filters/article/article.ts
packages/zendesk-adapter/test/filters/article/article.test.ts

fix title for article in deploy
---
---
---

SALTO-4319: fix title for article in deploy

---

packages/adapter-utils/src/change.ts
packages/adapter-utils/test/change.test.ts

Added a util function to reverse a change to be used later
---
None
---
None

SAAS-8004: Added a util function to reverse a change

---

packages/jira-adapter/src/filters/workflow/workflow_modification_filter.ts

_Fixed a bug that prevented the deployment of active workflows in jira_
---
_see in the jira ticket_
---
Jira Adapter:
* Fixed a bug that prevented the deployment of active workflows
---
None

SALTO-4405: deploy active workflows

---

packages/jira-adapter/src/filters/automation/smart_values/smart_value_reference_filter.ts

_Fixed a small bug of type mismatch in automations_
---
Jira Adapter:
* Fixed a type mismatch in automations
---
None

SALTO-4400: wrong type in automations

---

packages/jira-adapter/src/filters/automation/smart_values/smart_value_reference_filter.ts
packages/jira-adapter/test/filters/automation/smart_values/smart_value_reference_filter.test.ts

Forgot to add a test to a previous [commit](https://github.com/salto-io/salto/pull/4533) 
---
None
---
None

SALTO-4400: Boolean type in automation- added a test

---

packages/netsuite-adapter/src/config.ts

_increase SDF timeout to 10 min_
---
_None_
---
* SDF default timeout increased to 10 min
---
_None_

SALTO-4296: increase default SDF timeout to 10 min

---

packages/salesforce-adapter/cpq-sbaa-config-doc.md
packages/salesforce-adapter/src/config_creator.ts

Fix typo in CPQ default config
---
---
Fix typo in CPQ default config
---
None

SALTO-4421 - Fix typo in CPQ default config

---

packages/core/src/core/deploy/deploy_actions.ts

Add log on exception in deploy so that full stack trace appears
---
---
_None_
---
_None_

INCIDENT-6487 Add log message on exception in deploy

---

packages/salesforce-adapter/src/adapter.ts

Fetch some more types via retrieve.
WS diff is nil.
---
---
Salesforce: improved stability when fetching certain types
---
N/A

SALTO-4461 - Salesforce: fetch additional types via retrieve API

---

packages/netsuite-adapter/src/change_validators/file_cabinet_internal_ids.ts

To https://help.salto.io/en/articles/7876750-deploying-file-cabinet
---
---
None
---
None

add help link in file-cabinet change validator

---

packages/jira-adapter/src/config/config.ts

_The default was missing, added it_
---
None
---
None
---
None

SALTO-4065: Remove duplicate roles, added default true

---

packages/salesforce-adapter/src/config_change.ts
packages/salesforce-adapter/src/filters/custom_objects_from_soap_describe.ts

added some logs to SF soap api filter.
This will give some visibility into it's affects.
---
None.
---
None
---
None

SALTO-4487 - added some logs to SF soap api filter

---

packages/salesforce-adapter/src/fetch.ts
packages/salesforce-adapter/test/adapter.discover.test.ts

SALTO-4465: Revert (Due to regression in some Layout instances)

---

packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts

Fix the spelling of "recieved" to "received" - it was killing me.  Besides, this is a simple change that does not need the time/effort of a developer so I grabbed it

correct spelling

---

packages/adapter-components/src/deployment/change_validators/create_change_validator.ts

Log run time for each validator
---
None
---
None

SALTO-4513 Log change validator run times

---

packages/jira-adapter/test/filters/fields/context_options.test.ts

_Fixed the long time it takes tests to run_
---
None
---
None
---
None

SALTO-4262: fix tests times

---

packages/salesforce-adapter/src/change_validators/account_settings.ts
packages/salesforce-adapter/src/change_validators/case_assignmentRules.ts
packages/salesforce-adapter/src/change_validators/currency_iso_codes.ts
packages/salesforce-adapter/src/change_validators/data_category_group.ts
packages/salesforce-adapter/src/change_validators/duplicate_rules_sort_order.ts
packages/salesforce-adapter/src/change_validators/flows.ts
packages/salesforce-adapter/src/change_validators/installed_packages.ts
packages/salesforce-adapter/src/change_validators/omit_data.ts
packages/salesforce-adapter/src/change_validators/package.ts
packages/salesforce-adapter/src/change_validators/record_type_deletion.ts
packages/salesforce-adapter/src/change_validators/standard_field_or_object_additions_or_deletions.ts
packages/salesforce-adapter/src/change_validators/unknown_picklist_values.ts

SALTO-4429 add intercom url toSF CVs
---
none
---
none

SALTO-4429 add intercom url toSF CVs

---

packages/netsuite-adapter/e2e_test/adapter.test.ts
packages/netsuite-adapter/src/filters/add_alias.ts
packages/netsuite-adapter/test/filters/add_alias.test.ts

---
---
- Add alias to settings instances & bundles
---
- Add alias to settings instances & bundles

SALTO-4536 add alias to settings instances & bundles (NS)

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/filters/project_field_contexts_order.ts
packages/jira-adapter/test/filters/project_field_contexts_order.test.ts

_add a filter for sorting project field contexts - Jira_
---
_None_
---
_None_

SALTO-4494: add a filter for sorting project field contexts - Jira

---

packages/netsuite-adapter/src/client/errors.ts
packages/netsuite-adapter/src/client/language_utils.ts
packages/netsuite-adapter/src/client/sdf_client.ts

Added to regexes list
---
---
None
---
None

SALTO-4413 Extract SDF locked object error

---

packages/dummy-adapter/src/generator.ts

fix alias in dummy adapter
---
---
None
---
None

SALTO-4525: fix alias in dummy adapter

---

packages/netsuite-adapter/src/config.ts

Make netsuite deploy config type-safe

---

packages/netsuite-adapter/e2e_test/adapter.test.ts
packages/netsuite-adapter/src/filters/add_alias.ts

---
---
- Add alias to definition types
---
None

SALTO-4537 Add alias to NS definition types

---

packages/zendesk-adapter/src/client/connection.ts
packages/zendesk-adapter/test/adapter.test.ts
packages/zendesk-adapter/test/adapter_creator.test.ts
packages/zendesk-adapter/test/change_validators/organization_existence.test.ts
packages/zendesk-adapter/test/client/client.test.ts
packages/zendesk-adapter/test/client/connection.test.ts

update validateCredentials to identify production accounts
---
---
None
---
None

SALTO-4374: update validateCredentials to identify production accounts

---

packages/netsuite-adapter/src/client/suiteapp_client/types.ts
packages/netsuite-adapter/test/client/suiteapp_client/suiteapp_client.test.ts

_update sysInfo enum and schema_
---
_None_
---
_None_
---
_None_

update sysInfo enum and schema

---

packages/netsuite-adapter/package.json
yarn.lock

Upgrade SDF to rely on a new JAR download URL based on 2023.2.0

---

packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/filters/account_id/account_id_filter.ts
packages/jira-adapter/src/filters/jql/jql_references.ts
packages/jira-adapter/src/filters/script_runner/script_runner_instances_deploy.ts

Added support for ScriptRunner's Scheduled Jobs and Escalation Services
---
Jira Adapter:
* added support for ScriptRunner's Scheduled Jobs and Escalation Services
---
Jira Adapter:
* Customers with ScriptRunner will have Scheduled Jobs and Escalation Services NaCls

SALTO-3956: Scheduled Jobs and Escalation Service

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/filters/broken_reference_filter.ts
packages/jira-adapter/src/filters/script_runner/behaviors_field_uuid.ts
packages/jira-adapter/src/filters/script_runner/behaviors_mappings.ts
packages/jira-adapter/src/filters/script_runner/walk_on_scripts.ts
packages/jira-adapter/src/reference_mapping.ts
packages/jira-adapter/test/change_validators/script_runner_unresolved_reference.test.ts
packages/jira-adapter/test/filters/script_runner/behavior_field_uuid.test.ts
packages/jira-adapter/test/filters/script_runner/behavior_mappings.test.ts
packages/jira-adapter/test/filters/script_runner/script_runner_broken_reference.test.ts

Added support for Script Runner's behaviors
---
Jira Adapter:
* Added support for ScirptRunner's behaviors
---
Jira Adapter:
* Customers with ScriptRunner will be added Added ScriptRunner's Behaviors NaCls

SALTO-3961: Behaviors

---

packages/jira-adapter/src/filters/sort_lists.ts

Fixed issue layout owner order which seems to change on each fetch
---
- Fixed issue layout owners order to not change on each fetch
---
None

SALTO-4177: Fix issue layout owner order

---

packages/jira-adapter/src/deployment/jsp_deployment.ts
packages/jira-adapter/src/deployment/standard_deployment.ts
packages/jira-adapter/src/filters/script_runner/script_runner_listeners_deploy.ts
packages/jira-adapter/test/adapter.test.ts
packages/jira-adapter/test/deployment/standard_deployment.test.ts
packages/jira-adapter/test/filters/issue_layout/issue_layout.test.ts
packages/jira-adapter/test/filters/issue_type_schemas/issue_type_scheme.test.ts
packages/jira-adapter/test/filters/script_runner/script_runner_listeners_deploy.test.ts
packages/jira-adapter/test/filters/security_scheme.test.ts
packages/jira-adapter/test/filters/workflow/workflow_deploy_filter.test.ts
packages/jira-adapter/test/filters/workflow/workflow_modification_filter.test.ts
packages/okta-adapter/src/deployment.ts
packages/okta-adapter/test/deployment.test.ts
packages/okta-adapter/test/filters/policy_rule_removal.test.ts
packages/okta-adapter/test/logo.test.ts
packages/zendesk-adapter/src/errors.ts
packages/zendesk-adapter/src/filters/app_installations.ts
packages/zendesk-adapter/src/filters/article/utils.ts
packages/zendesk-adapter/src/filters/macro_attachments.ts
packages/zendesk-adapter/src/filters/reorder/creator.ts
packages/zendesk-adapter/src/filters/webhook.ts
packages/zendesk-adapter/test/errors.test.ts

Remove element IDs and improve deploy error messages
---
- Improve deployment error messages
- Improve deployment error messages
_Zendesk_adapter_:
- Improve deployment error messages
---
None

SALTO-4640: Change deploy error messages

---

packages/zendesk-adapter/src/constants.ts
packages/zendesk-adapter/src/filters/audit_logs.ts

improve audit log call
add filter[source_type] as was suggested by zendesk
---
---
None
---
None

SALTO-4542: improve audit log call

---

packages/jira-adapter/test/filters/script_runner/scripted_fragments_deploy.test.ts

Unit tests got broken from a merge
---
None
---
None
---
None

SALTO-3959: Fix the UTs

---

packages/jira-adapter/src/config/api_config.ts

_Removed the issue layout from support types until we resolve the performance issue_
---
Will add noise reduction
---
Jira Adapter:
* Issue layouts will  not be fetched due to a performance issue for some cusomters
---
Jira Adapter:
* NaCls will no longer contain issue layouts

SALTO-4177: removed issue layouts to prevent performance issues

---

packages/zendesk-adapter/src/change_validators/duplicate_id_field_values.ts
packages/zendesk-adapter/test/change_validators/duplicate_id_field_values.test.ts

Update the message to reference a doc
---
None
---
* Duplicate id values CV will point to a doc with an explanation
---
None

SALTO-4679 - Zendesk Adapter - Update duplicate id values message

---

packages/jira-adapter/src/filters/script_runner/script_runner_filter.ts
packages/jira-adapter/src/filters/script_runner/script_runner_instances_deploy.ts
packages/jira-adapter/test/filters/script_runner/script_runner_filter.test.ts

Handle deployment of first instance of ScriptRunner- if there are no items we have an empty type and references will not be resolved
---
None
---
Jira Adapter:
* Fixed a bug that prevented deployment of first instance of a ScriptRunner type
---
None

SALTO-4704: First Instance of ScriptRunner

---

packages/jira-adapter/src/filters/script_runner/script_runner_filter.ts
packages/jira-adapter/test/filters/script_runner/script_runner_filter.test.ts

There was a bug with the type of auditData times in some of the types
---
None
---
None
---
None

SALTO-3958: Fixed type issue for audit

---

packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/config/config.ts
packages/jira-adapter/src/filters/issue_layout/issue_layout.ts
packages/jira-adapter/test/filters/issue_layout/issue_layout.test.ts

The previous try was not enough
---
None
---
Jira Adapter:
* Removing Issue Layouts
---
None

SALTO-4177: Remove layouts

---

packages/jira-adapter/src/filters/script_runner/script_runner_listeners_deploy.ts
packages/jira-adapter/src/filters/script_runner/scripted_fragments_deploy.ts

Added support for script listeners and script fragments
---
None
---
None
---
None

SALTO-4704: Allow deployment of first instance in ScriptRunner

---

packages/netsuite-adapter/src/client/language_utils.ts

SALTO-3203 add SDF error regex

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/filters/issue_layout/create_references_issue_layout.ts
packages/jira-adapter/src/filters/issue_layout/issue_layout.ts
packages/jira-adapter/src/filters/issue_layout/issue_layout_query.ts
packages/jira-adapter/src/filters/issue_layout/issue_layout_types.ts
packages/jira-adapter/src/filters/remove_simplified_field_project.ts
packages/jira-adapter/test/filters/issue_layout/create_references_issue_layout.test.ts
packages/jira-adapter/test/filters/issue_layout/issue_layout.test.ts
packages/jira-adapter/test/filters/remove_simplified_field_project.test.ts

In this PR I fixed the issue layout bugs.
1. I Filtered out all the project that aren't company managed, and not of type "software".
2. I removed the owners from the issue layout. 
3. I splitted the filter to three filters - issueLayout, remove porject simplified field, create references for issueLayout. 
---
In a future PR I will resolve the performance problem. 
---
None
---
None

SALTO-4177 Fixed issue layout bugs

---

packages/zendesk-adapter/src/filters/field_references.ts

add missing references to ticket_form
---
has noise reduction
---
* ticket_form will have now missing references for ticket_fields
---
None

SALTO-4718 - missing references in ticket_form

---

packages/dummy-adapter/src/adapter_creator.ts
packages/dummy-adapter/src/generator.ts
packages/dummy-adapter/test/adapter_creator.test.ts

Add elementsToExclude option to dummy in order to test SALTO-4656
---
None
---
None

SALTO-4656: Add elementsToExclude option to dummy

---

packages/salesforce-adapter/src/filters/author_information/custom_objects.ts

Only try to add author information for objects that receive it
---
---
---

SALTO-4749 fix author information bug

---

packages/jira-adapter/src/filters/fields/field_structure_filter.ts

Did not see the [PR comment](https://github.com/salto-io/salto/pull/4855) before
---
None
---
None
---
None

SALTO-4755: performance fix

---

packages/jira-adapter/src/filters/automation/automation_deployment.ts
packages/jira-adapter/test/filters/automation/automation_deployment.test.ts

Fixed a bug in automations where the answer for automations did not return the lately created one
---
---
Jira Adapter:
* Fixed a bug that could cause automation deployment issues
---
None

SALTO-4760: Fix automation E2E

---

packages/jira-adapter/src/weak_references/automation_projects.ts
packages/jira-adapter/test/weak_references/automation_projects.test.ts

Changed element fixer messages
---
None (the element fixer was not deployed yet)
---
None

SALTO-4751: changed element fixer messages

---

packages/zendesk-adapter/src/change_validators/dynamic_content_deletion.ts
packages/zendesk-adapter/test/change_validators/dynamic_content_deletion.test.ts

Don't know how, but a code with a wrong import was merged (the build did not fail for some reason)
---
None
---
None
---
None

Fix import from a wrong file path

---

packages/zendesk-adapter/config_doc.md
packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/filters/article/article.ts
packages/zendesk-adapter/src/filters/handle_identical_attachment_conflicts.ts
packages/zendesk-adapter/test/filters/handle_identical_attahments_conflicts.test.ts

handle identical attachments conflicts fixes
fixes of https://github.com/salto-io/salto/pull/4886
---
---
None
---
None

SALTO-4747: handle identical attachments conflicts fixes

---

packages/adapter-components/src/elements/ducktype/type_elements.ts
packages/adapter-components/src/elements/swagger/type_elements/type_config_override.ts
packages/adapter-components/src/elements/type_elements.ts
packages/adapter-components/test/elements/type_elements.test.ts
packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/test/adapter.test.ts

Add hidden fields to types in case they do not exist
---
See the description in Jira
---
None
---
None

SALTO-4717: Add hidden fields to types

---

packages/salesforce-adapter/src/filters/organization_wide_sharing_defaults.ts
packages/salesforce-adapter/src/types.ts

Wrap organizationWideSharingDefaultsFilter with ensureSafeFilterFetch
---
---
_None_
---
_None_

SALTO-4792

---

packages/salesforce-adapter/e2e_test/custom_object_instances.test.ts

Reverts salto-io/salto#4640 due to flakiness

Revert "SALTO-4435 - Salesforce: Add an E2E test that tests a type with OwnerId"

---

packages/salesforce-adapter/src/filters/changed_at_singleton.ts
packages/salesforce-adapter/test/filters/changed_at_singleton.test.ts

Saving ChangedAt values for CustomObjects as a required step for quick fetch on CustomObjects,
---
_None_
---
_None_

SALTO-4727: Save CustomObject in ChangedAtSingleton

---

packages/okta-adapter/e2e_test/adapter.test.ts

Should solve flakiness
---
---
None
---
None

SALTO-4793: increase timeout for Okta E2E (Okta)

---

packages/jira-adapter/src/filters/layouts/issue_layout.ts
packages/jira-adapter/test/filters/layouts/issue_layout.test.ts

In this PR I fixed the bug mentioned in [Incident-8928](https://salto-io.atlassian.net/browse/INCIDENT-8928?focusedCommentId=104351&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-104351)
---
---
None
---
None

SALTO-4848: Fixed Issue Layout bug

---

packages/dummy-adapter/package.json
packages/dummy-adapter/src/generator.ts
packages/dummy-adapter/tsconfig.json

add logs in dummy adapter
---
---
None
---
None

SALTO-4859: add logs in dummy adapter

---

packages/jira-adapter/src/filters/workflow/workflow_deploy_filter.ts
packages/jira-adapter/test/filters/workflow/workflow_deploy_filter.test.ts

Added a workaround for a bug in Jira that when creating a workflow we get an error that it already exist although it wasn't.
Since although we get this error the workflow is created, the workaround is to get the id from the service in this case and continue the deployment
---
- Added a workaround for a Jira bug that when creating a workflow we somtimes receive an error that the workflow name is already used although it wasn't
---
None

SALTO-4886: Creating workflow fails with the workflow already exist error

---

packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
packages/netsuite-adapter/src/client/suiteapp_client/soap_client/types.ts

---
---
- Better message in NS SOAP search error
---
None

better message in NS SOAP search error

---

packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/filters/jsm_types_deploy_filter.ts

In this Deploy I support fetch and deploy of calendars. 
---
None
---
Now we support deploying of JSM calendars. 
---
None

SALTO-4884: Fetch and Deploy Calendar

---

packages/zendesk-adapter/src/user_utils.ts

There was a race condition that caused us to query the users multiple times
---
_Zendesk Adapter_:
- Fixed a race condition that caused us to query the users multiple times on deploy
---
None

INCIDENT-9172: Fixed race condition when getting users in Zendesk

---

packages/jira-adapter/src/filters/screen/screen.ts
packages/jira-adapter/test/filters/screen/screen.test.ts

_add onDeploy to screen filter_
---
* fix a bug in https://github.com/salto-io/salto/pull/4988
---
_None_
---
_None_

SALTO-4905: add onDeploy to screen filter - Jira

---

packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/constants.ts
packages/jira-adapter/src/filters/jql/jql_references.ts
packages/jira-adapter/src/filters/jsm_paths.ts
packages/jira-adapter/src/filters/jsm_types_fetch_filter.ts
packages/jira-adapter/src/reference_mapping.ts
packages/jira-adapter/test/filters/jql/jql_references.test.ts

In this PR I added support to fetch SLA
---
None
---
Now support fetch of SLA. 
---
For those who enable JSM, SLA nacls will be visible upon your next fetch

SALTO-4899: Fetch Sla

---

packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/filters/jsm_types_deploy_filter.ts

In this PR I support deploy of Sla. 
---
Please review only from [support deploy of SLA](https://github.com/salto-io/salto/commit/bae22f7d95b29dd5c8a69ff361c2b50a3d21cc07) and any subcommit. 
---
Now supporting deploy of SLA.
---
None

SALTO-4899: Deploy Sla

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/filters/portal_settings.ts
packages/jira-adapter/test/filters/portal_settings.test.ts

In this PR I support deploy of portal settings. 
---
None
---
Now support deploy of portal settings. 
---
_Replace me with a short sentence that describes changes that will appear in NaCls and are not caused by user actions (e.g. None

SALTO-4907: Deploy portal settings

---

packages/netsuite-adapter/src/config.ts

SALTO-4798 rephrase "bin" type config suggestion

---

packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/client/client.ts
packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts

Based on @dorsev's PR (https://github.com/salto-io/salto/pull/5009) with making more promises go in parallel (using `Promise.all`), and removing any variable of a promise (so we don't have unhandled promises).
---
---
None
---
None

SAAS-9299: NetSuite credentials not propagated as credentials issue

---

packages/zendesk-adapter/src/deployment.ts

On call to deployChanges with different types of changes, deploy the removal changes first (to prevent duplication errors in case of renames)
---
This might make half of https://github.com/salto-io/salto/pull/4701 useless (as this makes handling of most elemID changes work)
---
* Deployments will no longer fail on simultaneously addition and removal of elements with equal idFields values
---
None

SALTO-4955 - Zendesk Adapter - deploy removal changes first

---

packages/zendesk-adapter/test/filters/handle_template_expressions.test.ts

Add a UT to check the fix of 4807-fix
---
None
---
None
---
None

SALTO-4807 - Zendesk adapter - update UT

---

packages/adapter-utils/src/important_values.ts
packages/adapter-utils/test/important_values.test.ts

change return value for getImportantValues func
---
---
None
---
None

SALTO-4957: change return value for getImportantValues func

---

packages/salesforce-adapter/src/custom_object_instances_deploy.ts

- Add log on thrown unknown error in Salesforce Data Deploy group.
- Do not expose unknown runtime errors.
---
_None_
---
_None_

SALTO-4965: Better Data Instances Unknown exception handling

---

packages/jira-adapter/e2e_test/adapter.test.ts
packages/jira-adapter/e2e_test/adapter.ts
packages/jira-adapter/e2e_test/instances/cloud/index.ts
packages/jira-adapter/e2e_test/instances/cloud/jsm/SLA.ts
packages/jira-adapter/e2e_test/instances/cloud/jsm/calendar.ts
packages/jira-adapter/e2e_test/instances/cloud/jsm/portal_groups.ts
packages/jira-adapter/e2e_test/instances/cloud/jsm/portal_settings.ts
packages/jira-adapter/e2e_test/instances/cloud/jsm/queue.ts
packages/jira-adapter/src/config/api_config.ts

In this PR I added E2E to jira Jsm. 
---
None
---
None
---
None

SALTO-4941: E2E to Jira Jsm

---

packages/netsuite-adapter/src/adapter.ts

Was raised in https://salto-io.atlassian.net/browse/INCIDENT-8902?focusedCommentId=109008
---
---
---

Add logDuration decorator to NS

---

packages/netsuite-adapter/src/change_validators/data_account_specific_values.ts
packages/netsuite-adapter/test/change_validators/data_account_specific_values.test.ts

To be more accurate.
---
---
None
---
None

Rephrase data elements ACCOUNT_SPECIFIC_VALUE CV

---

packages/salesforce-adapter/src/change_validators/unknown_users.ts
packages/salesforce-adapter/src/custom_object_instances_deploy.ts
packages/salesforce-adapter/src/filters/author_information/data_instances.ts
packages/salesforce-adapter/src/filters/custom_objects_instances.ts
packages/salesforce-adapter/src/filters/utils.ts
packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts

Revert "SALTO-4881 - Salesforce: Support more complex SOQL queries"

---

packages/okta-adapter/src/config.ts
packages/okta-adapter/src/filters/replace_object_with_id.ts
packages/okta-adapter/src/reference_mapping.ts
packages/okta-adapter/system_config_doc.md

Remove feature dependencies type as fetching this causing many 429
---
---
None
---
None

SALTO-5036: Remove feature dependencies type

---

packages/zendesk-adapter/src/adapter.ts

Added a log with some relevant information in zendesk deploy flow Removed a redundant uniq call on InstaceElements
---
---
_None_
---
_None_

SALTO-4933: add log in zendesk deploy

---

packages/jira-adapter/src/client/client.ts
packages/jira-adapter/src/filters/automation/automation_deployment.ts
packages/jira-adapter/test/filters/automation/automation_deployment.test.ts

_fix jira e2e flakiness_
---
* add a header to delete automation request in order to solve the 415 issue
---
_None_
---
_None_

SALTO-5050: fix jira e2e flakiness

---

packages/zendesk-adapter/src/adapter.ts

When there are no guide related changes in the deploy change group we don't need to know which brands exist This can save time when there are many small deploy groups that are not related to guide
---
---
- Improve performance of large deployments with no guide related changes
---
_None_

SALTO-4933: Zendesk deploy - avoid reading brands when there are no guide changes

---

packages/core/src/core/adapters/adapters.ts

Avoid reading the content of all elements when only asked to read the element IDs
---
---
Core:
- Improve performance of several fetch and deploy scenarios
---
_None_

SALTO-4933: Improve filter element source performance in list

---

packages/core/src/local-workspace/remote_map/remote_map.ts

Add debug logs to closing rocksDB connections
---
None.
---
None.
---
None.

SAAS-9492 - Add debug logs to closing rocksDB connections

---

packages/zendesk-adapter/src/filters/guide_order/guide_order_utils.ts
packages/zendesk-adapter/src/filters/reorder/creator.ts
packages/zendesk-adapter/src/filters/reorder/trigger.ts
packages/zendesk-adapter/test/filters/guide_orders.test.ts
packages/zendesk-adapter/test/filters/reorder/automation.test.ts
packages/zendesk-adapter/test/filters/reorder/trigger.test.ts
packages/zendesk-adapter/test/filters/reorder/view.test.ts

Revert "SALTO-4654 - Zendesk Adapter - Add gaps to order positions"

---

packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/filters/forms/forms.ts
packages/jira-adapter/src/filters/forms/forms_types.ts
packages/jira-adapter/test/filters/forms/forms.test.ts

In this PR I added a fix to forms instance in JSM. 
---
Currently, We cannot deploy forms with empty values in JSM. 
This PR fixes this issue.
---
Fix that allows deployment of forms with empty values. 
---
None

SALTO-5054: Fix forms bug

---

packages/jira-adapter/e2e_test/instances/cloud/index.ts
packages/jira-adapter/e2e_test/instances/cloud/jsm/form.ts
packages/jira-adapter/package.json
packages/jira-adapter/test/filters/forms/forms.test.ts

In this PR I added Forms to E2E
Currently we compare the time in the ms level so the test if flaky. Change it to the minute time. 
---
None
---
None
---
None

SALTO-5052: Added Forms to E2E

---

packages/jira-adapter/src/config/config.ts

_add enableNewWorkflowAPI flag_
---
---
_None_
---
_None_

SALTO-5093: add enableNewWorkflowAPI flag - Jira

---

packages/jira-adapter/src/config/config.ts

_fix enableNewWorkflowAPI flag_
---
---
_None_
---
_None_

SALTO-5093: fix enableNewWorkflowAPI flag - Jira

---

packages/dummy-adapter/src/generator.ts
packages/dummy-adapter/test/generator.test.ts

SAAS-9634 dummy adapter conflicts support fix

---

packages/dummy-adapter/src/generator.ts

SAAS-9634 dummy adapter conflicts support fix2

---

README.md

SALTO-4567 Update README.md

---

packages/dummy-adapter/src/generator.ts

add more logs to dummy adapter
---
---
---

SALTO-5100: add more logs to dummy adapter

---

packages/dummy-adapter/src/generator.ts

---
https://github.com/omrifarkash/forReview
---
None
---
None

SAAS-9634 dummy adapter fix complicated inst

---

packages/zendesk-adapter/src/filters/add_important_values.ts

add temp list important value in zendesk
---
---
---

SALTO-5113: add temp list important value

---

packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/filters/forms/forms.ts
packages/jira-adapter/src/filters/forms/forms_types.ts

In this PR I added the option to exclude forms in fetch. 
---
None
---
None
---
None

SALTO-5114: Allow to exclude forms

---

packages/jira-adapter/src/filters/layouts/layout_queries.ts
packages/jira-adapter/src/filters/layouts/layout_service_operations.ts

In this PR I fixed the error mentioned in this [incident.](https://salto-io.atlassian.net/browse/INCIDENT-10457?focusedCommentId=113768)
---
---
None
---
None

INCIDENT-10457: Fixing missing type in issue layout deploy

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/product_settings/cloud.ts

Fixing missing serviceDeskId
---
None
---
None
---
None

Fix missing serviceDeskId

---

packages/okta-adapter/src/adapter.ts
packages/okta-adapter/src/filters/add_important_values.ts
packages/okta-adapter/test/filters/add_important_values.test.ts

Add important values 
Still TODO - verify how it works wit nested types 
---
None
---
None

SALTO-5112: Okta important values 

---

packages/netsuite-adapter/src/config.ts
packages/netsuite-adapter/test/filters/exclude_by_criteria.test.ts

add the following default exclusions to NS config:
1. exclude inactive elements
2. exclude private saved searches
3. exclude data files
---
---
- Change default excluding in the adapter config
---
None

SALTO-4765 Change default excluding in NS adapter config

---

packages/jira-adapter/src/filters/forms/forms.ts
packages/jira-adapter/test/filters/forms/forms.test.ts

This PR is following this incident - [Parsing error when applying addition detailed change to a list in a map](https://salto-io.atlassian.net/browse/SALTO-5115?focusedCommentId=114806)
1. Fetch - change each numeric key to nackCase. 
2. deploy - cahgne each naclCase key to numeric. 
---
The bug as reproduce with Jira account and got fixed
---
There will be noise since the names of the keys are going to change. 
---
None

SALTO-5126: Fix parsing error In form maps

---

packages/okta-adapter/src/config.ts

Support deployment of SmsTemplate type
---
---
- Add support in SmsTemplate type
---
None

SALTO-5153: Support deployment of SmsTemplate type

---

packages/jira-adapter/src/filters/forms/forms.ts
packages/jira-adapter/test/filters/forms/forms.test.ts

In this PR I added  a fetch warning when form is untitled. 
---
None
---
Added a fetch warning when form is untitled. 
---
None

SALTO-5151: Return SaltoError when form is untitled

---

packages/zendesk-adapter/src/fix_elements/fallback_user.ts
packages/zendesk-adapter/test/fix_elements/fallback_user.test.ts

Fix replace fallback user.
---
---
---

SALTO-5156 Fix fallback user

---

packages/adapter-utils/src/important_values.ts
packages/dummy-adapter/src/generator.ts
packages/dummy-adapter/test/generator.test.ts

fix important values in dummy
---
---
---

SALTO-5171: fix important values in dummy

---

packages/salesforce-adapter/src/custom_object_instances_deploy.ts

Currently the logs look like 
```
in custom object deploy retry-flow. retries left: 1,
remaining retryable failures are: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
```
Let's fix the log line, and add some more logging while we're at it.
---
---
N/A
---
N/A

SALTO-5190 - Salesforce: Improve logging of failed instance deploys

---

packages/jira-adapter/e2e_test/instances/cloud/board.ts

Fixed E2E
---
---
None
---
None

SALTO-5202-FixE2E

---

packages/jira-adapter/e2e_test/adapter.test.ts
packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/constants.ts
packages/jira-adapter/src/filters/assets/assets_instances_addition.ts
packages/jira-adapter/src/filters/assets/assets_object_type_change_fields.ts
packages/jira-adapter/src/filters/assets/assets_object_type_path.ts
packages/jira-adapter/src/filters/assets/attribute_deploy_filter.ts
packages/jira-adapter/src/filters/assets/change_attributes_path.ts
packages/jira-adapter/src/filters/change_jsm_fields.ts
packages/jira-adapter/src/filters/jsm_types_deploy_filter.ts
packages/jira-adapter/src/filters/jsm_types_fetch_filter.ts
packages/jira-adapter/src/jsm_utils.ts
packages/jira-adapter/src/reference_mapping.ts
packages/jira-adapter/test/adapter.test.ts
packages/jira-adapter/test/filters/assets/assets_instances_addition.test.ts
packages/jira-adapter/test/filters/assets/assets_object_type_change_fields.test.ts
packages/jira-adapter/test/filters/assets/assets_object_type_path.test.ts
packages/jira-adapter/test/filters/assets/attribute_deploy_filter.test.ts
packages/jira-adapter/test/filters/assets/change_attributes_path.test.ts
packages/jira-adapter/test/filters/change_jsm_fields.test.ts
packages/jira-adapter/test/filters/jsm_types_deploy_filter.test.ts

After conversation with Lior where we decided on the assets name, I changed them in our code. 
---
None
---
None
---
None

SALTO-5198: Fix assets typeNames

---

packages/persistent-pool/package.json
yarn.lock

SALTO-2558: remove unused dependency on aws-sdk v2

---

packages/jira-adapter/e2e_test/adapter.test.ts
packages/jira-adapter/e2e_test/adapter.ts
packages/jira-adapter/e2e_test/instances/cloud/index.ts
packages/jira-adapter/e2e_test/instances/cloud/jsm/objectSchema.ts
packages/jira-adapter/e2e_test/instances/cloud/jsm/objectSchemaStatus.ts
packages/jira-adapter/e2e_test/instances/cloud/jsm/objectType.ts
packages/jira-adapter/e2e_test/instances/cloud/jsm/objectTypeAttribute.ts
packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/filters/assets/assets_instances_addition.ts
packages/jira-adapter/src/filters/assets/assets_instances_deployment.ts
packages/jira-adapter/test/filters/assets/assets_instances_addition.test.ts
packages/jira-adapter/test/filters/assets/assets_instances_deployment.test.ts

In this PR I added E2E for all assets types
---
---
None
---
None

SALTO-5197: Added E2E for Assets

---

packages/zendesk-adapter/config_doc.md
packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/src/filters/article/article.ts

handle socket hang up errors in zendesk
---
---
zendesk:
* handle socket hang up errors
---

SALTO-5150: handle socket hang up errors

---

packages/zendesk-adapter/config_doc.md

PR updates the description of the ZD enable audit flag

fixed zd enableAudit flag desc

---

packages/zendesk-adapter/src/fix_elements/fallback_user.ts
packages/zendesk-adapter/test/fix_elements/fallback_user.test.ts

Small fix for missing fallback user flow.
---
---
---

INCIDENT-11440 Add filter to irrelevant instances

---

packages/jira-adapter/test/filters/workflowV2/transition_parameters_filter.test.ts

_add transition parameters filter unit tests_
---
* add some UTs to raise the coverage
---
_None_
---
_None_

SALTO-4978:  add transition parameters filter unit tests - Jira

---

packages/jira-adapter/src/config/config.ts

_fix Jira DC scriptRunner supportedTypes bug_
---
---
_None_
---
_None_

SALTO-5240: fix Jira DC scriptRunner supportedTypes bug

---

packages/netsuite-adapter/package.json
yarn.lock

Revert: SALTO-5234: Upgrade SDF version to 1.8.0-salto-2

---

packages/jira-adapter/src/filters/screen/screen.ts

_fix screen filter log level - Jira_
---
---
_None_
---
_None_

SALTO-5259: fix screen filter log level - Jira

---

packages/jira-adapter/src/weak_references/automation_projects.ts
packages/jira-adapter/src/weak_references/field_configuration_items.ts

nit in fix elements
---
None
---
None
---
None

SALTO-4894 nit in fix elements

---

packages/jira-adapter/src/filters/project.ts
packages/jira-adapter/test/filters/project.test.ts

In this PR I added try-catch to prevent the deployment failure for project when no serviceDeskId was found.
Also I added another endpoint to try and find the service desk Id of a project.  
---
1. Will add UT after first review. 
---
None
---
None

SALTO 5267: Fixed deployment failure for missing serviceDeskId

---

packages/jira-adapter/src/filters/add_alias.ts

Fixed Aliases
---
---
None
---
None

SALTO-5152: Fix Alias in jsm assets

---

packages/netsuite-adapter/package.json
yarn.lock

This reverts commit 644c8f9a1e7d4636d2e63b35a48c95f2c7a2c806.
---
---
---

SALTO-5234: Revert Upgrade SDF version to 1.8.0-salto-2 (#5297)"

---

packages/netsuite-adapter/src/client/suiteapp_client/soap_client/schemas.ts
packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
packages/netsuite-adapter/src/client/suiteapp_client/soap_client/types.ts
packages/netsuite-adapter/test/client/suiteapp_client/soap_client/soap_client.test.ts

Catch error response on NS SOAP and throw a more readable message.
I also refactored the `soap_client/schemas.ts`, to have much more DRY definitions.
---
---
None
---
None

Catch error response on NS SOAP

---

packages/salesforce-adapter/e2e_test/utils.ts
packages/salesforce-adapter/src/custom_object_instances_deploy.ts
packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
packages/salesforce-adapter/test/custom_object_instances_deploy.test.ts

Revert PR
---
_None_
---
_None_

SALTO-5206: Revert

---

packages/zendesk-adapter/src/filters/guide_theme.ts
packages/zendesk-adapter/test/adapter.test.ts
packages/zendesk-adapter/test/filters/guide_theme.test.ts

theme files to be nacl cased
---
---
none
---
none

SALTO-5288: theme files to be nacl cased

---

packages/jira-adapter/src/filters/layouts/request_types_layouts_to_values.ts
packages/jira-adapter/test/filters/layouts/request_types_layouts_to_values.test.ts

Added annotation to requestForm and issueView
---
---
None
---
None

SALTO-5291: Add Deploy annotations to requestForm and issueView

---

packages/jira-adapter/e2e_test/instances/cloud/fieldConfiguration.ts
packages/jira-adapter/e2e_test/instances/cloud/index.ts
packages/jira-adapter/e2e_test/instances/datacenter/fieldConfiguration.ts
packages/jira-adapter/e2e_test/instances/datacenter/index.ts
packages/jira-adapter/src/filters/field_configuration/replace_field_configuration_references.ts
packages/jira-adapter/src/weak_references/field_configuration_items.ts
packages/jira-adapter/test/filters/field_configuration/replace_field_configuration_references.test.ts
packages/jira-adapter/test/weak_references/field_configuration_items.test.ts

SALTO-5289 remove field reference from nacl
---
[remove missing field configuration items in fix element](https://github.com/salto-io/salto/pull/5274)
---
* Fix oom issue on big fieldConfiguration by removing field references from nacl
---
None

SALTO-5289 Jira adapter -  remove field reference from nacl

---

packages/workspace/src/workspace/reference_indexes.ts

SAAS-5289 increase reference index version
---
https://github.com/salto-io/salto/pull/5323
---
None
---
None

SAAS-5289 increase reference index version

---

packages/okta-adapter/src/client/client.ts

We see this log recently so I added some more info to it so it would be easier to debug
---
---
None
---
None

SALTO-5306: Add info to invalid rate limit headers (Okta)

---

packages/jira-adapter/src/filters/assets/assets_object_type_change_fields.ts

Remove recursedInto fields in objectSchema. 
---
---
None
---
None

SALTO-5306: Removed recursed into fields

---

packages/salesforce-adapter/src/config_change.ts
packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts

Improved createManyInstancesExcludeConfigChange reason string
---
_None_
---
_None_

SALTO-5305: (Salesforce) Improved createManyInstancesExcludeConfigChange reason string

---

packages/jira-adapter/src/reference_mapping.ts

_add reference from workflowScheme to jiraWorkflow_
---
---
_None_
---
_None_

SALTO-5297: add reference from workflowScheme to jiraWorkflow

---

packages/adapter-components/src/elements/index.ts
packages/adapter-components/src/elements/instance_elements.ts
packages/jira-adapter/src/filters/automation/automation_structure.ts

Small refactor on automation_structor filter in Jira so we walk on each instance only once
---
---
None
---
None

SALTO-5310 refactor automation structure to walk on instance once

---

packages/adapter-utils/src/utils.ts
packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/change_validators/workflow_scheme_migration.ts
packages/jira-adapter/src/change_validators/workflowsV2/status_mappings.ts
packages/jira-adapter/src/config/config.ts
packages/jira-adapter/test/change_validators/workflowsV2/status_mappings.test.ts

_add workflow statusMapping CV_
---
more info in the [ticket](https://salto-io.atlassian.net/browse/SALTO-5312)
---
_None_
---
_None_

SALTO-5312: add workflow statusMapping CV - Jira

---

packages/jira-adapter/src/filters/workflowV2/types.ts
packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts
packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts

_add conditionGroups to transition condition_
---
The nacl looks like this: 
checkout the API [documentation](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-workflows/#api-rest-api-3-workflows-update-post) for more info
* more info in the [ticket](https://salto-io.atlassian.net/browse/SALTO-5335)
---
_None_
---
_None_

SALTO-5335: add conditionGroups to transition condition

---

packages/jira-adapter/src/filters/sort_lists.ts

_sort workflow transition list_
---
* in order to reduce the noise
---
_None_
---
_None_

SALTO-5345: sort workflow transition list

---

packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts
packages/netsuite-adapter/test/data_elements/suiteql_table_elements.test.ts

- add quick return when results length is lower than the query limit
- replace error log with warn log when results is undefined
- add test for allocation types queries
---
---
None
---
None

SALTO-2392 small fix in allocation type internal ids search

---

packages/okta-adapter/src/client/connection.ts

as title
---
---
None
---
None

SALTO-5368: Log all errors when validating credentials in Okta

---

packages/jira-adapter/src/filters/script_runner/workflow/workflow_cloud.ts
packages/jira-adapter/src/filters/script_runner/workflow/workflow_filter.ts
packages/jira-adapter/src/filters/workflow/workflow_deploy_filter.ts
packages/jira-adapter/test/filters/script_runner/workflow/workflow_cloud.test.ts
packages/jira-adapter/test/filters/workflow/workflow_deploy_filter.test.ts

_refactor encode and decode scriptRunner values_
---
* should not affect any user
---
_None_
---
_None_

SALTO-5362: refactor encode and decode scriptRunner values

---

packages/jira-adapter/src/config/api_config.ts

_fix jira clean e2e changes_
---
* remove omitRequestBody from portalGroups delete endpoint
---
_None_
---
_None_

SALTO-5364: fix jira clean e2e changes 

---

packages/salesforce-adapter/src/metadata_deploy.ts
packages/salesforce-adapter/test/adapter.crud.test.ts

Deploy errors where the `componentType` is `CustomObject` or `CustomField` were not mapped to the correct ElemID (e.g. they were mapped to `salesforce.CustomObject.instance.Account`.
---
At the point where we collect the names/elemIDs, custom objects are already converted back to instances. So our mapping is technically correct (which is the best kind of correct, of course), but not helpful.
---
Salesforce: Improved mapping of deploy errors to elements
---
N/A

SALTO-5375 - Salesforce: Fix mapping of deploy errors of custom object and custom field

---

packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/filters/sort_lists.ts
packages/jira-adapter/src/filters/workflow/transition_structure.ts
packages/jira-adapter/src/filters/workflowV2/types.ts
packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts
packages/jira-adapter/test/filters/script_runner/workflow/workflow_cloud.test.ts
packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts

_transform transitions to map_
---
---
_None_
---
_None_

SALTO-5362: transform transitions to map

---

packages/salesforce-adapter/src/transformers/xml_transformer.ts

Wrapped the problematic flow with try/catch for better visibility of issues.
---
_None_
---
_None_

SALTO-5391: Add log on Salesforce Metadata Deploy runtime error

---

packages/adapter-components/src/definitions/system/utils.ts
packages/adapter-components/test/definitions/system/utils.test.ts

should get both customizations and default, not merge
---
None
---
None

fix getNestedWithDefault

---

packages/jira-adapter/src/filters/assets/attribute_deploy_filter.ts
packages/jira-adapter/src/filters/request_type.ts

In this PR, I corrected the error that occurs when a type is missing during the initial deployment of a type that has not been present in the target environment before.
---
Their was an issue stemmed from deploying a requestType in an environment where no RequestTypes existed previously. 
As a result, the filter responsible for substituting references with actual values failed to recognize this type. 
The solution is similar to the one we took for other JSM types: defining its type using the instance being deployed.
---
None
---
None

SALTO-5417: Fix Jsm Deployment For First Time

---

packages/jira-adapter/src/filters/add_jsm_types_as_fields.ts
packages/jira-adapter/test/filters/add_jsm_types_as_fields.test.ts

In this PR:
1. Fixed a bug when there is an undefined project.
2. Improved performance.
---
None
---
Fixed bug when project instance is undefined. 
---
None

SALTO-5433-Fix Undefined Project

---

packages/jira-adapter/src/filters/layouts/issue_layout.ts

Wrongly used the import
---
None
---
None
---
None

SALTO-5437: fixed import that broke the build

---

packages/zendesk-adapter/src/change_validators/guide_theme_readonly.ts
packages/zendesk-adapter/test/change_validators/guide_theme_readonly.test.ts

SALTO-5451 Disable guide themes deploy

---

packages/netsuite-adapter/src/change_validator.ts
packages/netsuite-adapter/src/config/types.ts

_Add bundle changes CV to list_
---
_None_
---
_None_
---
_None_

SALTO: 5351 - add bundles cv to list

---

packages/netsuite-adapter/src/filters/data_account_specific_values.ts
packages/netsuite-adapter/src/filters/workflow_account_specific_values.ts
packages/netsuite-adapter/test/change_validators/workflow_account_specific_values.test.ts

---
---
- Add ASV help article link to CVs
---
None

Add ASV help article link to CVs

---

.git-blame-ignore-revs

SALTO-5404 Exclude the prettier commit from git blame

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/filters/account_info.ts
packages/jira-adapter/test/adapter.test.ts

In this PR I fix the bug when user tries to fetch JSM while he doesn't have JSM in service. 
---
---
Fixed bug when JSMEnable = true but no JSM instance in the service.
---
None

SALTO-5453: Fix Jsm Fetch Failing

---

packages/netsuite-adapter/src/change_validators/bundle_changes.ts
packages/netsuite-adapter/test/change_validators/bundle_changes.test.ts

---
---
- add Bundles help article to CV
---
None

add Bundles help article to CV

---

packages/netsuite-adapter/src/transformer.ts

Quick return `bundle_<id>` for the bundle instance name
---
---
None
---
None

Refactor Bundle instances name logic

---

packages/zendesk-adapter/src/filters/references/missing_references.ts

remove broken references for tags
---
---
zendesk:
* missing references will not be created for tags
---

SALTO-5457: remove broken references for tags

---

packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts

we should use `lastFetchTimeForQuery` for both the count query and the records query.
---
---
- Fix SuiteQL count query
---
None

Fix SuiteQL count query

---

.git-blame-ignore-revs

SALTO-5404 Exclude the real prettier commit from git blame

---

packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/config/bundle_query.ts
packages/netsuite-adapter/src/config/types.ts
packages/netsuite-adapter/src/filters/bundle_ids.ts
packages/netsuite-adapter/test/adapter.test.ts
packages/netsuite-adapter/test/bundle_query.test.ts

_Allow users to exclude elements according the their bundle_
---
_None_
---
* excludeBundles added to config, All elements from listed bundles Ids will be excluded.
---
_None_

SALTO-4022: Exclude by bundleId

---

.git-blame-ignore-revs

SALTO-5404 Change the commit to the rebased PR commit

---

package.json
packages/adapter-api/package.json
packages/adapter-components/package.json
packages/adapter-utils/package.json
packages/aws-utils/package.json
packages/cli/package.json
packages/core/package.json
packages/dag/package.json
packages/dummy-adapter/package.json
packages/e2e-credentials-store/package.json
packages/jira-adapter/package.json
packages/logging/package.json
packages/lowerdash/package.json
packages/netsuite-adapter/package.json
packages/okta-adapter/package.json
packages/persistent-pool/package.json
packages/salesforce-adapter/package.json
packages/stripe-adapter/package.json
packages/test-utils/package.json
packages/vscode/package.json
packages/workato-adapter/package.json
packages/workspace/package.json
packages/zendesk-adapter/package.json
packages/zuora-billing-adapter/package.json

Added format to the build in yarn
---
---
None
---
None

SALTO-5404: add format to the build

---

packages/jira-adapter/src/change_validators/workflowsV2/status_mappings.ts
packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts
packages/jira-adapter/test/change_validators/workflowsV2/status_mappings.test.ts
packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts

_remove deletion of statusMappings in onDeploy_
---
---
_None_
---
_None_

SALTO-5475: remove deletion of statusMappings in onDeploy

---

packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts

_fix format_
---
---
_None_
---
_None_

SALTO-5362: fix format

---

packages/zendesk-adapter/src/client/client.ts
packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/test/client/client.test.ts

fix idFields mechanism for newly created fields
---
---
zendesk:
*  fix idFields mechanism for newly created fields
---

SALTO-5474: fix idFields mechanism for newly created fields

---

packages/zendesk-adapter/test/client/client.test.ts

fix uncommited changes
---
---
---

SALTO-5474: fix uncommited changes

---

.vscode/settings.json
package.json
packages/adapter-api/package.json
packages/adapter-components/package.json
packages/adapter-utils/package.json
packages/aws-utils/package.json
packages/cli/package.json
packages/core/package.json
packages/dag/package.json
packages/dummy-adapter/package.json
packages/e2e-credentials-store/package.json
packages/jira-adapter/package.json
packages/jira-adapter/test/dependency_changers/root_object_type_to_schema.test.ts
packages/logging/package.json
packages/lowerdash/package.json
packages/netsuite-adapter/package.json
packages/okta-adapter/package.json
packages/persistent-pool/package.json
packages/salesforce-adapter/package.json
packages/stripe-adapter/package.json
packages/test-utils/package.json
packages/vscode/package.json
packages/workato-adapter/package.json
packages/workspace/package.json
packages/zendesk-adapter/package.json
packages/zuora-billing-adapter/package.json

Header is self explanatory
---
---
None
---
None

SALTO-5404: Add format on save for VS Code

---

packages/jira-adapter/src/filters/sort_lists.ts

_sort workflow statuses_
---
---
_None_
---
_None_

SALTO-5518: sort workflow statuses

---

packages/jira-adapter/src/filters/workflow/transition_structure.ts
packages/jira-adapter/src/filters/workflowV2/types.ts

_fix workflow transition schema_
---
---
_None_
---
_None_

SALTO-5521: fix workflow transition schema

---

packages/core/src/core/plan/dependency/reference_dependency.ts
packages/core/test/core/plan/dependency.test.ts

This reverts commit 0fed916f98ede340639a666dd1e608232cf755f1.
---
---
---

Revert "new Dependency Flow - changing removal depencdency  (#5427)"

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/filters/workflowV2/workflowV1_removal.ts
packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts
packages/jira-adapter/test/filters/workflowV2/workflowV1_removal.test.ts

_workflowV1 removal filter_
---
* removes workflowV1 instances when enableNewWorkflowAPI is enabled
---
_None_
---
_None_

SALTO-5524: workflowV1 removal filter

---

packages/adapter-components/src/definitions/system/requests/types.ts
packages/adapter-components/src/fetch/request/pagination/pagination.ts
packages/adapter-components/src/fetch/request/requester.ts
packages/adapter-components/test/fetch/request/pagination/pagination.test.ts
packages/jira-adapter/src/client/client.ts
packages/okta-adapter/src/client/client.ts
packages/zendesk-adapter/src/client/client.ts

SALTO-5415 Support customizing the http response codes in fetch
---
---
none
---
none

SALTO-5415 Support customizing the http response codes in fetch

---

packages/jira-adapter/src/reference_mapping.ts

_add references from workflow status properties_
---
---
_None_
---
_None_

SALTO-5517: add references from workflow status properties

---

packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts

SALTO-5524: workflowV1 removal filter - remove debug leftover 

---

packages/zendesk-adapter/e2e_test/adapter.test.ts
packages/zendesk-adapter/src/filters/article/article_body.ts
packages/zendesk-adapter/src/filters/article/utils.ts
packages/zendesk-adapter/src/filters/guide_theme.ts
packages/zendesk-adapter/src/filters/template_engines/handlebar_parser.ts
packages/zendesk-adapter/src/filters/template_engines/html_parser.ts
packages/zendesk-adapter/src/filters/utils.ts
packages/zendesk-adapter/test/filters/template_engines/handlebar_parser.test.ts
packages/zendesk-adapter/test/filters/template_engines/html_parser.test.ts

SALTO-3080 Fix some template parsing errors

---

packages/workato-adapter/src/filters/cross_service/jira/project_issuetypes.ts
packages/workato-adapter/test/filters/project_issuetypes.test.ts

add preDeploy for project_issuetype
---
pre PR for https://github.com/salto-io/salto/pull/5536
---
---

Workato - add support for on deploy of cross service jira project issuetype

---

packages/dummy-adapter/src/adapter_creator.ts
packages/dummy-adapter/src/generator.ts
packages/dummy-adapter/test/adapter.test.ts
packages/dummy-adapter/test/generator.test.ts

1. add template staticFile to dummy
2. add template expression to dummy
---
---
---

SALTO-5523: add template staticFile to dummy

---

packages/adapter-components/src/filters/service_url.ts

Fix main build.
There was a build 'conflict' after [this](https://github.com/salto-io/salto/commit/dcaca312b627860d0b9960cc114859038d37a44e) and [this](https://github.com/salto-io/salto/commit/08f8135e519fd399acaf5db4ba6410618ae51195) PRs were merged. The reason it happened is probably because the first PR was merged **after** the CI passed on the second PR.
---
---
None
---
None

SALTO-5429: Fix build

---

packages/adapter-components/src/fetch/resource/subresources.ts

fix - add context from parent
---
None
---
None

SALTO-5388 fix recurseinto context

---

packages/PLACEHOLDER-adapter/src/definitions/deploy/business_hours_schedule.ts
packages/adapter-components/src/config/ducktype.ts
packages/adapter-components/src/definitions/system/shared/types.ts
packages/adapter-components/src/definitions/system/utils.ts
packages/adapter-components/test/definitions/system/utils.test.ts
packages/adapter-components/test/deployment/deploy/graph.test.ts
packages/adapter-components/test/deployment/deploy/requester.test.ts
packages/zendesk-adapter/src/config.ts

SALTO-5613 make the customizations optional in defaultWithCustomizations type
---
---
none
---
none

SALTO-5613 make the customizations optional in defaultWithCustomizations type

---

docs/user_guide.md

Some readability improvements.
---
Playing around with the git, posting this again.
---
None.
---
None.

SALTO-5622 - Update user_guide.md

---

README.md

It doesn't need a token because it's a public project. Also aligning the prettier badge to the same style.
---
---
None.
---
None.

SALTO-5633 - Fixing CircleCI badge

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/config/config.ts
packages/jira-adapter/src/constants.ts
packages/jira-adapter/src/filters/add_important_values.ts
packages/jira-adapter/test/filters/add_important_values.test.ts

Added important values to Jira. Currently under a flag to allow Lior to test in production
---
Once Lior approves I will remove the flag and add release notes
---
None
---
None

SALTO-5111: important values

---

packages/jira-adapter/e2e_test/instances/cloud/index.ts
packages/jira-adapter/e2e_test/instances/cloud/jsm/SLA.ts

In this PR I fixed the E2E in Jira. 
---
---
* Fixed the e2e in jira. 
---
None

SALTO-5238: Fix E2E In Jira

---

packages/adapter-components/src/client/http_client.ts
packages/zendesk-adapter/test/change_validators/organization_existence.test.ts
packages/zendesk-adapter/test/client/client.test.ts

the extraction script looks for `:`
---
None
---
None

SALTO-5641 avoid breaking the extraction script

---

packages/jira-adapter/src/filters/forms/forms.ts
packages/jira-adapter/src/reference_mapping.ts
packages/jira-adapter/test/filters/forms/forms.test.ts

In this PR I added resolved value to form instances. 
---
We added requestType reference in this PR https://github.com/salto-io/salto/pull/5597 to form instances. 
In deploy, the reference stays reference. 
---
None
---
None

SALTO-5606: Fix Reference Request Type In Form

---

packages/jira-adapter/src/change_validators/workflow_scheme_migration.ts
packages/jira-adapter/test/change_validators/workflow_scheme_migration.test.ts

_support workflow v2 in workflow scheme migration cv_
---
---
_None_
---
_None_

SALTO-5652: support workflow v2 in workflow scheme migration cv

---

packages/jira-adapter/src/filters/workflowV2/types.ts
packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts
packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts

_turn triggers into a list in the new Workflow_
---
---
_None_
---
_None_

SALTO-5616: turn triggers into a list in the new Workflow

---

docs/syntax.md

At least they helped me read it.
---
---
None.
---
None.

SALTO-5655: Readability imporvements for syntax.md

---

packages/adapter-components/src/fetch/resource/subresources.ts
packages/adapter-components/src/fetch/resource/type_fetcher.ts
packages/adapter-components/test/fetch/fetch.test.ts

the `single: true` case wasn't working properly
---
None
---
None

fix recurseInto with single result

---

packages/jira-adapter/src/constants.ts
packages/jira-adapter/src/filters/account_id/account_id_filter.ts
packages/jira-adapter/src/filters/workflowV2/types.ts
packages/jira-adapter/test/filters/account_id/account_id_filter.test.ts

_support workflowV2 in accountIdFilter_
---
---
_None_
---
_None_

SALTO-5657: support workflowV2 in accountIdFilter

---

packages/jira-adapter/src/filters/workflowV2/types.ts
packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts
packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts

_remove empty strings from transition parameters_
---
---
_None_
---
_None_

SALTO-5658: remove empty strings from transition parameters

---

packages/okta-adapter/e2e_test/adapter.test.ts
packages/okta-adapter/src/change_validators/brand_removal.ts
packages/okta-adapter/src/change_validators/index.ts
packages/okta-adapter/src/config.ts
packages/okta-adapter/test/change_validators/brand_removal.test.ts

Okta adapter:
- Added support for addition and removal of `Brand` elements
---
None

SALTO-5090: Okta: Add basic addition and removal support for `Brand`

---

packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts
packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts

_fix a bug in fetching transition with the same key_
---
---
_None_
---
_None_

SALTO-5618: fix a bug in fetching transition with the same key

---

packages/jira-adapter/src/client/client.ts
packages/jira-adapter/src/deployment/standard_deployment.ts
packages/jira-adapter/src/filters/workflow/steps_deployment.ts
packages/jira-adapter/src/filters/workflowV2/types.ts
packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts
packages/jira-adapter/test/client/client.test.ts
packages/jira-adapter/test/deployment/standard_deployment.test.ts
packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts

_support workflow steps in the new Workflow_
---
---
_None_
---
_None_

SALTO-5645: support workflow steps in the new Workflow

---

packages/jira-adapter/src/reference_mapping.ts

_add missing references between workflowScheme to workflow_
---
---
_None_
---
_None_

SALTO-5617: add missing references between workflowScheme to workflow

---

packages/jira-adapter/src/filters/automation/automation_deployment.ts
packages/jira-adapter/test/filters/automation/automation_deployment.test.ts

In this PR I fix assets component in Automation. 
---
---
* assets component in Automation. 
---
None

SALTO-5732: Fix Assets Component In Automation

---

packages/adapter-components/src/adapter-wrapper/adapter_creator.ts

SALTO-5614 make createAdapter in adapter wrapper to get connection per client
---
---
none
---
none

SALTO-5614 make createAdapter in adapter wrapper to get connection per client

---

packages/google-workspace-adapter/src/definitions/deploy/deploy.ts
packages/google-workspace-adapter/src/definitions/fetch/fetch.ts

SALTO-5614 google-workspace service-url
---
---
none
---
none

SALTO-5614 google-workspace service-url

---

packages/adapter-components/src/fetch/element/element.ts
packages/adapter-components/src/fetch/resource/resource_manager.ts

SALTO-5772: Fix some logs in new infra

---

packages/jira-adapter/src/filters/script_runner/walk_on_scripts.ts
packages/jira-adapter/test/filters/script_runner/script_template_expressions.test.ts

_add references to script runner template expression with the new workflow_
---
---
_None_
---
_None_

SALTO-5774: add references to script runner template expression with the new workflow

---

packages/google-workspace-adapter/src/definitions/deploy/deploy.ts
packages/google-workspace-adapter/src/definitions/fetch/fetch.ts
packages/google-workspace-adapter/src/definitions/references.ts
packages/google-workspace-adapter/src/definitions/types.ts

SALTO-5614 google-workspace support groupMembers
---
---
none
---
none

SALTO-5614 google-workspace support groupMembers

---

packages/zendesk-adapter/src/filters/references/list_values_missing_references.ts
packages/zendesk-adapter/test/filters/references/list_values_missing_references.test.ts

fix missing references logic
---
---
---

SALTO-5785: fix missing references logic

---

packages/google-workspace-adapter/src/definitions/deploy/deploy.ts
packages/google-workspace-adapter/src/definitions/fetch/fetch.ts
packages/google-workspace-adapter/test/adapter.test.ts

SALTO-5787 google ws fix elemId for orgUnit
---
---
none
---
none

SALTO-5787 google ws fix elemId for orgUnit

---

packages/google-workspace-adapter/README.md

SALTO-5668 google ws fix Readme
---
---
none
---
none

SALTO-5668 google ws fix Readme

---

packages/adapter-components/src/deployment/deploy/requester.ts

SALTO-5801 invert Nacl case in the new infra deploy
---
---
none
---
none

SALTO-5801 invert Nacl case in the new infra deploy

---

packages/adapter-components/src/deployment/deploy/graph.ts
packages/adapter-components/test/deployment/deploy/graph.test.ts

fix constraint order for dependencies
---
None (not in use yet)
---
None

SALTO-5388 reverse edge order

---

packages/salesforce-adapter/jest.config.js
packages/salesforce-adapter/test/change_validators/element_api_version.test.ts
packages/salesforce-adapter/test/filters/organization_settings.test.ts

Fixing a regression from recent PR https://github.com/salto-io/salto/pull/5719
---
_None_
---
_None_

SALTO-5279: Add missing UTs (coverage increase)

---

packages/jira-adapter/src/filters/account_id/account_id_filter.ts
packages/jira-adapter/test/filters/account_id/account_id_filter.test.ts

Good thing Alon is not here to see that, he warned about this but I waved him off
---
I do not think there will be noise as we would have crashed like we already saw in the bug
---
Jira Adapter:
* Fixed a bug in automation that could cause fetch to fail
---
None

SALTO-5815: fix a bug in account ids for automations

---

packages/jira-adapter/src/config/config.ts
packages/jira-adapter/src/filters/add_important_values.ts
packages/jira-adapter/test/filters/add_important_values.test.ts

Added important values for Jira
---
The config was added previously for testing purposes. 
---
JIra Adapter:
* Added important values to Jira
---
None

SALTO-5111: add jira important values

---

.circleci/config.yml
packages/cli/e2e_test/multi_env.test.ts
packages/cli/e2e_test/salto.test.ts
packages/jira-adapter/e2e_test/adapter.test.ts
packages/logging/src/internal/logger.ts
packages/logging/src/internal/pino.ts
packages/logging/test/internal/pino_logger.test.ts
packages/netsuite-adapter/e2e_test/adapter.test.ts
packages/okta-adapter/e2e_test/adapter.test.ts
packages/salesforce-adapter/e2e_test/adapter.test.ts
packages/salesforce-adapter/e2e_test/custom_object_instances.test.ts
packages/salesforce-adapter/e2e_test/quick_deploy.test.ts
packages/salesforce-adapter/e2e_test/workflow.test.ts
packages/stripe-adapter/e2e_test/adapter.test.ts
packages/zendesk-adapter/e2e_test/adapter.test.ts
packages/zuora-billing-adapter/e2e_test/adapter.test.ts

print log count for all e2e
---
---
---

SALTO-5065: print log count for all e2e

---

packages/okta-adapter/src/filters/policy_rule_priority.ts

In this PR I fixed the bug where you cannot deploy signOn priority rule. 
---
---
_Okta Adapter"_
* Fixed bug in signOn policy rule. 
---
None

SALTO-5829: Fix Bug Okta

---

packages/jira-adapter/e2e_test/instances/cloud/automation.ts

Fixed E2E in Jira
---
---
None
---
None

SALTO-5688: fix E2E

---

packages/google-workspace-adapter/jest.config.js
packages/google-workspace-adapter/package.json
packages/google-workspace-adapter/src/adapter_creator.ts
packages/google-workspace-adapter/src/change_validator.ts
packages/google-workspace-adapter/src/change_validators/domain_read_only.ts
packages/google-workspace-adapter/src/change_validators/group_member_role.ts
packages/google-workspace-adapter/src/change_validators/index.ts
packages/google-workspace-adapter/src/change_validators/role_assignment_addition.ts
packages/google-workspace-adapter/src/change_validators/role_read_only.ts
packages/google-workspace-adapter/src/change_validators/schema_fields.ts
packages/google-workspace-adapter/src/change_validators/system_role.ts
packages/google-workspace-adapter/src/definitions/deploy/deploy.ts
packages/google-workspace-adapter/src/definitions/fetch/fetch.ts
packages/google-workspace-adapter/test/change_validators/domain_read_only.test.ts
packages/google-workspace-adapter/test/change_validators/group_member_role.test.ts
packages/google-workspace-adapter/test/change_validators/role_assignment_addition.test.ts
packages/google-workspace-adapter/test/change_validators/role_read_only.test.ts
packages/google-workspace-adapter/test/change_validators/schema_fields.test.ts
packages/google-workspace-adapter/test/change_validators/system_role.test.ts
packages/google-workspace-adapter/tsconfig.json
packages/serviceplaceholder-adapter/src/adapter_creator.ts
packages/serviceplaceholder-adapter/src/change_validator.ts

SALTO-5819 Google WS - CV
---
---
none
---
none

SALTO-5819 Google WS - CV

---

packages/jira-adapter/src/filters/layouts/issue_layout.ts
packages/jira-adapter/src/filters/layouts/layout_service_operations.ts
packages/jira-adapter/test/filters/layouts/issue_layout.test.ts

Not sure what the problem is. Added some guards to prevent, and logs to understand the root cause
---
None
---
Jira adapter:
* fixed an issue that caused some users to fail fetch in the issue layouts filter
---
None

SALTO-5845: fix a bug of projectIds in issue layouts

---

packages/zendesk-adapter/src/filters/unordered_lists.ts
packages/zendesk-adapter/test/filters/unordered_lists.test.ts

order values in routing attribute
---
---
zendesk: 
* reorder values in routing attribute
---
zendesk: 
* reorder values in routing attribute

SALTO-5663: order values in routing attribute

---

packages/google-workspace-adapter/src/definitions/fetch/fetch.ts

SALTO-5668 Google ws - fix ServiceUrl
---
---
none
---
none

SALTO-5668 Google ws - fix ServiceUrl

---

packages/google-workspace-adapter/src/client/connection.ts
packages/google-workspace-adapter/test/adapter.test.ts

SALTO-5668 Google ws - fix accountId
---
---
none
---
none

SALTO-5668 Google ws - fix accountId

---

packages/confluence-adapter/src/definitions/fetch/fetch.ts

sort permissions on spaces
---
---
- Sort permissions on spaces
---
- Sort permissions on spaces

SALTO-5830 sort permissions on spaces

---

packages/confluence-adapter/src/definitions/fetch/fetch.ts

Add aliases for confluence
---
---
- Add aliases
---
- Add aliases

SALTO-5765 aliases for confluence

---

packages/jira-adapter/src/filters/layouts/issue_layout.ts

Removed logs that were added to understand the problem, not needed anymore
---
None
---
None
---
None

SALTO-5845: Removed the logs

---

packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts

_restrict getActiveWorkflowNamePromise and add logs_
---
---
_None_
---
_None_

SALTO-5875: restrict getActiveWorkflowNamePromise and add logs

---

packages/okta-adapter/src/filters/rename_default_access_policy.ts
packages/okta-adapter/test/filters/rename_default_access_policy.test.ts

This resolves the changes seen in state file after a second fetch in Okta.
---
The issue was with `renameDefaultAccessPolicy` filter which changes the default policy elem and but not the path. On the second fetch, as elemID already exist, the path was recreated based on the `getElemID` func and changed to include the instance name calculated in the first fetch.
The fix is to change the path as well from the first place.
---
- Fix a bug caused to the file path of the default access policy to change on the second fetch
---
None

SALTO-5837: Resolve fetch changes in default policy rules path hints in state file

---

packages/parser/src/parser/internal/native/consumers/blocks.ts
packages/parser/src/parser/internal/native/consumers/top_level.ts
packages/parser/src/parser/internal/native/errors.ts
packages/parser/src/parser/internal/native/parse.ts
packages/parser/test/parser/errors.test.ts
packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
packages/workspace/test/common/nacl_file_store.ts
packages/workspace/test/path_index_fallbacks.test.ts
packages/workspace/test/workspace/workspace.test.ts
salto.code-workspace

Fixing typos and improving consistency.
---
---
None.
---
None.

SALTO-5643: Cleaning up workspace before changes

---

packages/jira-adapter/src/filters/workflowV2/types.ts
packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts
packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts

_add conditionGroups support in workflowV2_
---
---
_None_
---
_None_

SALTO-5895: add conditionGroups support in workflowV2

---

packages/jira-adapter/e2e_test/adapter.test.ts
packages/jira-adapter/e2e_test/instances/cloud/index.ts

Removed automations from E2E until we fix them
---
None
---
None
---
None

SALTO-5920: Fix E2E and remove automation

---

packages/salesforce-adapter/e2e_test/adapter.test.ts
packages/salesforce-adapter/src/custom_references/handlers.ts
packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts
packages/salesforce-adapter/test/filters/installed_package_generated_dependencies.test.ts
packages/workspace/src/workspace/reference_indexes.ts

Revert "PROD-279: Salesforce Workspace Changes"

---

packages/workspace/src/workspace/nacl_files/nacl_file_update.ts

Should have just done this in the first place.
---
---
None.
---
None.

SALTO-1707: Simplifying element removal trim

---

packages/confluence-adapter/src/adapter_creator.ts

Fix broken build, caused by merging [this](https://github.com/salto-io/salto/pull/5876) PR
---
---
None
---
None

SALTO-5545 fix confluence build

---

packages/jira-adapter/src/constants.ts
packages/jira-adapter/src/filters/automation/automation_fetch.ts
packages/jira-adapter/test/filters/automation/automation_fetch.test.ts

Added a retry to prevent failing on 504
---
None
---
Jira Adapter:
* Added a retry when automation rules fetch fail with 504
---
None

SALTO-5914: retry on Automation's 504

---

packages/jira-adapter/e2e_test/adapter.test.ts
packages/jira-adapter/e2e_test/instances/cloud/index.ts

This reverts commit 07a6ad9465b20b7bae114d6ab626e2b2a827e6bc.
Returning the E2E for automations
---
None
---
None
---
None

Revert "SALTO-5920: Fix E2E (#5885)"

---

packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts

add requested type to soap error message

---

packages/salesforce-adapter/src/change_validators/new_fields_and_objects_fls.ts
packages/salesforce-adapter/test/change_validators/new_fields_and_objects_fls.test.ts

Update the message as per the ticket
---
---
N/A
---
N/A

SALTO-5818 - Salesforce: Update the text for addition of FLS upon CustomField addition

---

packages/jira-adapter/src/filters/statuses/status_deployment.ts
packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts
packages/jira-adapter/src/utils.ts
packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts

_add retry mechanism to new Workflow API_
---
---
_None_
---
_None_

SALTO-5990: add retry mechanism to new Workflow API

---

packages/google-workspace-adapter/e2e_test/adapter.test.ts
packages/google-workspace-adapter/e2e_test/mock_elements.ts

SALTO-5987 gGoogle ws e2e fix
---
---
---

SALTO-5987 gGoogle ws e2e fix

---

packages/adapter-components/src/definitions/system/fetch/element.ts
packages/adapter-components/src/definitions/system/fetch/index.ts
packages/adapter-components/test/fetch/element/instance_utils.test.ts

SALTO-5998: Fix parent arg in elemID customizer

---

packages/adapter-components/src/definitions/system/fetch/index.ts
packages/okta-adapter/src/definitions/fetch.ts

Add the fetch warning support using custom handler
---
No release notes as this continues the behavior from old infra
---
None
---
None

SALTO-5691: Add fetch warning for 403

---

packages/okta-adapter/src/definitions/fetch.ts

Fix rate limit issue 
---
---
- Fix a bug causing fetch to hit the account's rate limit
---
None

SALTO-6018: Fix rate limit issue in Okta

---

packages/zendesk-adapter/src/config_creator.ts
packages/zendesk-adapter/test/config_creator.test.ts

SALTO-6023 Create a default behavior for enabling Guide Themes

---

.circleci/config.yml

SALTO-5987-googlews-e2e-disable

---

packages/pagerduty-adapter/src/definitions/fetch/fetch.ts
packages/pagerduty-adapter/test/adapter.test.ts

SALTO-5964 pagerDuty fix-subdomain
---
---
---

SALTO-5964 pagerDuty fix-subdomain

---

packages/zendesk-adapter/e2e_test/adapter.test.ts

Disable guide themes test due to consistent failures

---

packages/zendesk-adapter/src/config_creator.ts

SAAS-6023 Config bug

---

.circleci/config.yml
packages/netsuite-adapter/e2e_test/adapter.test.ts
packages/zendesk-adapter/src/config_creator.ts

Zendesk: fix theme import that breaks build in main

---

salto.code-workspace

SALTO-5964 add pagerduty to code-workspace
---
---
---

SALTO-5964 add pagerduty to code-workspace

---

packages/okta-adapter/src/adapter.ts

I deleted it in the previous upgrade PR 👀 
---
---
None
---
None

SALTO-6044: Return progress reporter in Okta

---

packages/okta-adapter/e2e_test/adapter.test.ts

TIL `concat` doesn't modify arrays in place, whaddya know...
---
None
---
None
---
None

SALTO-6034: Okta: e2e: Actually perform the cleanup :/

---

packages/e2e-credentials-store/src/jest-environment/index.ts

Remove warning log when everything is actually fine
---
---
_None_
---
_None_

SALTO-6057: Remove constant warning

---

packages/jira-adapter/src/filters/add_alias.ts

_add alias to Priority_
---
_jira ticket: https://salto-io.atlassian.net/browse/SALTO-5954_
---
Jira Adapter:
* Add alias to Priority
---
_None_

SALTO-5954: (Jira) add alias to Priority

---

packages/google-workspace-adapter/README.md

SALTO-5843 Google ws fix oauth readme

---

.circleci/config.yml
packages/google-workspace-adapter/e2e_test/mock_elements.ts

SALTO-5987 Google ws - e2e another-fix
---
---
---

SALTO-5987 Google ws - e2e another-fix

---

packages/netsuite-adapter/src/filters/element_references.ts

---
---
- Fix MAX_STRING_LENGTH error in NS
---
None

Fix MAX_STRING_LENGTH error in NS

---

packages/jira-adapter/src/change_validators/issue_layouts_validator.ts
packages/jira-adapter/test/change_validators/issue_layout_validator.test.ts

Added a more detailed error message for the change validator of issue layouts
---
None
---
Jira Adapter:
* improved the change validator message for invalid issue layouts
---
None

SALTO-5442: issue layout validator update intercom message

---

packages/serviceplaceholder-adapter/config_doc.md

---
Will adjust the elemID config part based on review here (https://github.com/salto-io/salto/pull/6005)
---
None
---
None

SALTO-6040: Add service placeholder config doc

---

packages/adapter-utils/src/utils.ts

---
fix log message
---
None
---
None

SALTO-6015: Fix log message from earlier PR

---

packages/adapter-components/src/deployment/filtering.ts
packages/adapter-components/src/elements_deprecated/swagger/deployment/additional_properties.ts
packages/adapter-components/src/resolve_utils.ts
packages/adapter-components/src/restore_utils.ts
packages/jira-adapter/src/filters/automation/automation_structure.ts
packages/jira-adapter/src/filters/workflow/workflow_modification_filter.ts
packages/salesforce-adapter/src/transformers/transformer.ts
packages/workspace/src/workspace/adapters_config_source.ts
packages/workspace/src/workspace/hidden_values.ts

---
remove all current usages in OSS
---
None
---
None

SALTO-6105: remove allowEmpty usages in `transformElement`

---

packages/jira-adapter/src/filters/workflowV2/types.ts

_fix workflow condition type guard_
---
---
_None_
---
_None_

SALTO-6123: fix workflow condition type guard

---

packages/adapter-components/src/fetch/element/element.ts
packages/adapter-components/src/fetch/element/instance_element.ts
packages/adapter-components/src/fetch/element/instance_utils.ts
packages/adapter-components/src/fetch/element/type_utils.ts
packages/adapter-components/src/fetch/resource/resource_manager.ts

---
Adding log time to fetch resources flow and generate elements
---
None
---
None

SALTO-6111 Add logs in fetch resources for debugging

---

packages/okta-adapter/src/filters/policy_priority.ts
packages/okta-adapter/test/filters/policy_priority.test.ts

SALTO-6002- Add error log when duplicate priorities

---

packages/okta-adapter/src/definitions/fetch/types/application.ts

SALTO-6124: Remove noisy error logs on undefined link property

---

packages/pagerduty-adapter/src/definitions/fetch/fetch.ts

SALTO-6130 PagerDuty fix schedule modification side affects
---
---
---

SALTO-6130 PagerDuty fix schedule modification side affects

---

packages/okta-adapter/src/adapter.ts
packages/okta-adapter/src/utils.ts
packages/okta-adapter/test/utils.test.ts

Add api call to get the number of users
---
---
None
---
None

SALTO-6137: Log users count in Okta

---

packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/change_validator.ts
packages/netsuite-adapter/src/change_validators/analytics_post_deploy_notification.ts
packages/netsuite-adapter/src/change_validators/check_referenced_datasets.ts
packages/netsuite-adapter/src/change_validators/data_account_specific_values.ts
packages/netsuite-adapter/src/change_validators/extra_reference_dependencies.ts
packages/netsuite-adapter/src/change_validators/omit_fields.ts
packages/netsuite-adapter/src/change_validators/remove_sdf_elements.ts
packages/netsuite-adapter/src/change_validators/types.ts
packages/netsuite-adapter/src/change_validators/unique_fields.ts
packages/netsuite-adapter/src/change_validators/workflow_account_specific_values.ts
packages/netsuite-adapter/test/change_validator.test.ts
packages/netsuite-adapter/test/change_validators/analytics_post_deploy_notification.test.ts
packages/netsuite-adapter/test/change_validators/check_referenced_datasets.test.ts
packages/netsuite-adapter/test/change_validators/data_account_specific_values.test.ts
packages/netsuite-adapter/test/change_validators/extra_reference_dependencies.test.ts
packages/netsuite-adapter/test/change_validators/omit_fields.test.ts
packages/netsuite-adapter/test/change_validators/unique_fields.test.ts
packages/netsuite-adapter/test/change_validators/workflow_account_specific_values.test.ts

change NS changeValidators params to be an object instead of params list.
---
---
None
---
None

Change NS changeValidators params

---

.vscode/settings.json
packages/pagerduty-adapter/jest.config.js
packages/pagerduty-adapter/src/adapter_creator.ts
packages/pagerduty-adapter/src/config.ts
packages/pagerduty-adapter/src/definitions/fetch/fetch.ts
packages/pagerduty-adapter/src/filters/users.ts
packages/pagerduty-adapter/src/users_utils.ts
packages/pagerduty-adapter/test/filters/users.test.ts

SALTO-6074 PagerDuty - resolve userId to email
---
---
none
---
none

SALTO-6074 PagerDuty - resolve userId to email

---

packages/zendesk-adapter/src/filters/guide_theme.ts

A mitigation for large theme environments that can receive `EMFILE: too many open files`
---
---
---

INCIDENT-18290 - Limit theme file read concurrency

---

packages/salesforce-adapter/src/filters/custom_objects_instances.ts
packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts

In changed-based fetch, if we fetch a record that contains a reference, and the referred record was not fetched (because it was not modified), we need to look for the referred record in the workspace. 
---
Test:
- Run the test described in the ticket. Observe no issues with missing references.
---
Salesforce: will no longer show an error when using changed-based fetch to fetch records that refer to unchanged records.
---
N/A

SALTO-6100 - Salesforce: Fallback to element source if referred element was not fetched in QuickFetch

---

packages/jira-adapter/e2e_test/adapter.test.ts
packages/jira-adapter/e2e_test/instances/datacenter/index.ts

Adding a deletion for past E2E instances that were not deleted
---
None
---
None
---
None

SALTO-6143: Clear E2E instances

---

packages/pagerduty-adapter/jest.config.js
packages/pagerduty-adapter/src/config.ts
packages/pagerduty-adapter/src/definitions/deploy/deploy.ts
packages/pagerduty-adapter/src/definitions/utils/schedule_layers.ts
packages/pagerduty-adapter/src/filters/users.ts
packages/pagerduty-adapter/src/users_utils.ts
packages/pagerduty-adapter/test/definitions/utils/schedule_layers.test.ts
packages/pagerduty-adapter/test/filters/users.test.ts

SALTO-6130 Pagerduty fix layers with users

---

packages/adapter-api/src/elements.ts
packages/adapter-api/test/elements.test.ts
packages/adapter-utils/src/compare.ts
packages/adapter-utils/src/utils.ts
packages/adapter-utils/test/compare.test.ts
packages/adapter-utils/test/utils.test.ts
packages/core/src/core/fetch.ts
packages/core/src/core/plan/filter.ts
packages/core/src/core/plan/plan.ts
packages/core/src/local-workspace/workspace_config_types.ts
packages/dummy-adapter/src/generator.ts
packages/dummy-adapter/test/generator.test.ts
packages/parser/src/parser/dump.ts
packages/parser/src/parser/internal/native/consumers/top_level.ts
packages/parser/src/parser/internal/native/errors.ts
packages/parser/test/parser/dump.test.ts
packages/parser/test/parser/parse.test.ts
packages/workspace/src/expressions.ts
packages/workspace/src/merger/internal/object_types.ts
packages/workspace/src/merger/internal/primitives.ts
packages/workspace/src/serializer/elements.ts
packages/workspace/src/validator.ts
packages/workspace/src/workspace/hidden_values.ts
packages/workspace/src/workspace/nacl_files/addition_wrapper.ts
packages/workspace/src/workspace/nacl_files/multi_env/projections.ts
packages/workspace/test/core/expressions.test.ts
packages/workspace/test/merger.test.ts
packages/workspace/test/serializer/serializer.test.ts
packages/workspace/test/validator.test.ts
salto.code-workspace

This PR should add everything needed for meta types including validations, parsing and dumping.
---
Hope I didn't miss anything...
---
None.
---
None.

SALTO-3621: Adding meta type to Object type

---

.circleci/scripts/find_changed_packages.js

When adding dependencies during the map creation, only the package itself was added - without its dependencies.
---
---
---

SALTO-6180 Update dependency map recursion to add already recursed dependencies.

---

packages/zendesk-adapter/e2e_test/adapter.test.ts
packages/zendesk-adapter/src/filters/article/utils.ts
packages/zendesk-adapter/test/filters/article/article.test.ts

fix fetch content of article attachments
---
---
zendesk:
* fix fetch content of article attachments content
---
None

SALTO-6193: fix fetch content of article attachments

---

.circleci/scripts/find_changed_packages.js

When a package changes, it affects all packages that depend on it recursively. The old code did not recurse correctly
---
Ran a quick test on the current code, it yielded:
```
generateDependencyMapping(getWorkspacesInfo())
{
...
'@salto-io/confluence-adapter': [ '@salto-io/confluence-adapter', '@salto-io/core', '@salto-io/cli' ],
'@salto-io/core': [ '@salto-io/core', '@salto-io/cli', 'salto-vscode' ],
...
}
```
which shows that `confluence-adapter` affects `core` but did not get all of its affected packages (specifically, `salto-vscode` which is a direct affected package of `core`).
changed the code to recursively add the affected packages
---
_None_
---
_None_

SALTO-6180: Make e2e run for all affected packages

---

packages/adapter-components/src/fetch/element/type_utils.ts
packages/adapter-components/src/filters/custom_paths.ts

Clean noisy logs
---
in ticket
---
None
---
None

SALTO-6198: Clean noisy logs from adapters infra

---

packages/salesforce-adapter/src/custom_references/profiles.ts
packages/salesforce-adapter/test/custom_references/profiles.test.ts

Improving profiles element fixer message
---
---
None.
---
None.

SALTO-6129: Improving profiles element fixer message

---

packages/salesforce-adapter/src/custom_references/profiles.ts
packages/salesforce-adapter/test/custom_references/profiles.test.ts

SALTO-6136: Adding Intercom link to profiles element fixer message

---

packages/jamf-adapter/src/client/connection.ts
packages/jamf-adapter/src/definitions/deploy/deploy.ts
packages/jamf-adapter/test/adapter.test.ts

---
---
- Change validate credential url to one that we support
- Add support in site deployment
- Fix api-role deployment
---
- Change validate credential url to one that we support
- Add support in site deployment
- Fix api-role deployment

SALTO_6215  Jamf adapter improvments

---

packages/zendesk-adapter/src/change_validators/child_parent/missing_from_parent.ts
packages/zendesk-adapter/src/change_validators/duplicate_option_values.ts
packages/zendesk-adapter/test/change_validators/duplicate_option_values.test.ts
packages/zendesk-adapter/test/change_validators/missing_from_parent.test.ts

Clarify CV descriptions
---
---
---

SALTO-6210: change text for zd cv

---

packages/salesforce-adapter/src/client/client.ts

---
---
Salesforce: retry on some more kinds of errors
---
N/A

SALTO-5709,SALTO-6185 - Salesforce: add some more errors to retry on

---

packages/confluence-adapter/src/filters/deploy_space_and_permissions.ts
packages/confluence-adapter/tsconfig.json
packages/jamf-adapter/src/definitions/deploy/classic_api_utils.ts
packages/jamf-adapter/tsconfig.json
packages/jira-adapter/src/filters/queue_deployment.ts
packages/jira-adapter/test/filters/assets/change_attributes_path.test.ts
packages/jira-adapter/test/filters/assets/object_type_icon.test.ts
packages/jira-adapter/test/filters/automation/automation_fetch.test.ts
packages/jira-adapter/test/filters/automation/automation_label/label_fetch.test.ts
packages/jira-adapter/test/filters/data_center/priority_scheme/priority_scheme_fetch.test.ts
packages/okta-adapter/test/logo.test.ts
packages/zendesk-adapter/src/filters/dynamic_content.ts
packages/zendesk-adapter/src/inactive.ts
packages/zendesk-adapter/test/inactive.test.ts

will later check why these are no longer blocked
---
None
---
None

fix bad imports

---

packages/confluence-adapter/src/definitions/fetch/fetch.ts
packages/google-workspace-adapter/src/definitions/fetch/fetch.ts
packages/intercom-adapter/src/definitions/fetch/fetch.ts
packages/jamf-adapter/src/definitions/fetch/fetch.ts
packages/microsoft-entra-adapter/src/definitions/fetch/constants.ts
packages/okta-adapter/src/definitions/fetch/fetch.ts
packages/pagerduty-adapter/src/definitions/fetch/fetch.ts
packages/serviceplaceholder-adapter/src/definitions/fetch/fetch.ts
packages/zendesk-adapter/src/definitions/fetch/fetch.ts

no need for the two separate structures
---
None
---
None

SALTO-5392 simplify default field csutomizations

---

packages/zendesk-adapter/src/definitions/fetch/fetch.ts
packages/zendesk-adapter/src/filters/custom_field_options/custom_object_field_options.ts

fix fetch definitions
---
---
---

SALTO-6273: fix fetch definitions

---

packages/jira-adapter/jest.config.js
packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/config/config.ts
packages/jira-adapter/src/constants.ts
packages/jira-adapter/src/filters/assets/assets_object_field_configuration.ts
packages/jira-adapter/src/filters/fields/contexts.ts
packages/jira-adapter/src/filters/jql/jql_references.ts
packages/jira-adapter/src/reference_mapping.ts
packages/jira-adapter/test/filters/assets/assets_instances_deployment.test.ts
packages/jira-adapter/test/filters/fields/contexts.test.ts

SALTO-6159: support assetsObjectFieldConfiguration

---

packages/jira-adapter/jest.config.js

SALTO-6159 temp jira ut coverage
---
---
---
None

SALTO-6159 temp jira ut coverage

---

packages/salesforce-adapter/src/client/client.ts
packages/salesforce-adapter/test/client.test.ts

Avoid sending multiple listMetadataObjects requests on the same type in Salesforce fetch
---
In Salesforce Changed Based Fetch, we have three promises that run concurrently and perform list on the same types:
1. Fetch metadata instances of all the types
2. Fetch of changed profiles with all the related types
3. Fetch of partial changed parts in all Profiles 
Since this code runs concurrently, the Metadata types that are related to Profiles (e.g. ApexClass, Layout) will be listed multiple times in Change Based Fetch for Environments with profiles.
---
- Improved caching of listMetadataObjects: Same type won't be listed twice even when the requests are created concurrently.
---
_None_

SALTO-6300: Avoid sending multiple listMetadataObjects requests on the same type in Salesforce fetch

---

packages/zendesk-adapter/specific-cli-options.md

Add missing optional param for apiToken to docs for zendesk-adaptor

specific-cli-options.md - Update cli options for zendesk-adaptor

---

packages/jira-adapter/src/filters/layouts/issue_layout.ts

None
---
None
---
None
---
None

SALTO-6298: fix main build

---

packages/zendesk-adapter/src/definitions/fetch/fetch.ts

small zendesk type fix
---
---
---

SALTO-5761: small zendesk type fix

---

packages/adapter-api/src/elements.ts
packages/adapter-api/test/elements.test.ts
packages/adapter-utils/src/compare.ts
packages/adapter-utils/test/compare.test.ts

SALTO-6277: Support base elements in applyDetailedChanges

---

packages/workspace/src/workspace/state/in_mem.ts
packages/workspace/test/workspace/state.test.ts

SALTO-6320: Fixing bug in modifying base elements in in mem source

---

.circleci/adapters_with_java.txt
.circleci/config_template.yml
.circleci/scripts/find_changed_packages.js
.circleci/scripts/update_config_template.js
build_utils/hash_dependencies.js
build_utils/turbo_run.sh
package.json

SALTO-6252 turbocache e2e tests

---

.circleci/config_template.yml
build_utils/hash_dependencies.js
build_utils/turbo_run.sh

SALTO-6241 bug fixes

---

packages/adapter-components/src/definitions/system/overrides.ts

format logs and use safe stringify
---
None
---
None

SALTO-5432 adjust logs

---

packages/adapter-components/src/definitions/system/requests/endpoint.ts

small follow up to https://github.com/salto-io/salto/pull/5988 that could help in cases like https://github.com/salto-io/salto/pull/6263 
---
None
---
None

SALTO-6024  SALTO-6313 ensure client request customizations use valid endpoint paths

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/client/script_runner_connection.ts
packages/jira-adapter/src/filters/assets/assets_object_field_configuration.ts
packages/jira-adapter/src/filters/fields/contexts.ts
packages/jira-adapter/src/utils.ts
packages/jira-adapter/test/filters/fields/assets_object_field_configuration.test.ts

_get assets field config id using html_
---
---
---

SALTO-6159: get assets field config id using html

---

packages/netsuite-adapter/src/change_validators/client_validation.ts
packages/netsuite-adapter/src/client/language_utils.ts
packages/netsuite-adapter/src/client/sdf_client.ts
packages/netsuite-adapter/test/change_validators/client_validation.test.ts

**Once this PR is merged we should update the linked doc to point on the new Change Validation message**
---
---
SALTO-6325: Link NetSuite CV about enabling a feature to help doc
---

SALTO-6325: Link NetSuite CV about enabling a feature to help doc

---

.vscode/settings.json
.vscode/tasks.json
packages/adapter-api/src/adapter.ts
packages/cli/webpack.config.js
packages/salesforce-adapter/package.json
packages/salesforce-adapter/src/adapter.ts
packages/salesforce-adapter/src/adapter_creator.ts
packages/salesforce-adapter/src/metadata_deploy.ts
packages/salesforce-adapter/src/sfdx_parser/salesforce_imports.ts
packages/salesforce-adapter/src/sfdx_parser/salesforce_imports_fix.ts
packages/salesforce-adapter/src/sfdx_parser/sfdx_dump.ts
packages/salesforce-adapter/src/sfdx_parser/tree_container.ts
packages/salesforce-adapter/src/transformers/xml_transformer.ts
packages/salesforce-adapter/test/sfdx_parser/sfdx_dump.test.ts
yarn.lock

Reverts salto-io/salto#6296
(the issue the caused the original revert was not an issue in the code eventually)

Revert "Revert "SALTO-6276: add dumpElementsToFolder to adapter api and imple…"

---

packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/test/adapter.test.ts
packages/zendesk-adapter/test/filters/add_recurse_into_field.test.ts
packages/zendesk-adapter/test/filters/custom_objects/custom_object_fields_order.test.ts

SALTO-6360 Move default config to be with new infra fetch

---

packages/core/test/common/workspace.ts
packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
packages/workspace/src/workspace/workspace.ts
packages/workspace/test/common/nacl_file_store.ts
packages/workspace/test/workspace/config_source.test.ts
packages/workspace/test/workspace/workspace.test.ts

Revert "SALTO-6342: fix updateNaclFiles to count static file changes"

---

packages/jira-adapter/src/change_validators/index.ts

In this PR I added the SLA name attribute to the `uniqueFieldsChangeValidatorCreator`
---
---
* Added the SLA name attribute to the `uniqueFieldsChangeValidatorCreator`
---
None

SALTO-6374:  Added the SLA name attribute to the `uniqueFieldsChangeValidatorCreator`

---

packages/okta-adapter/src/adapter.ts

as title 
---
---
None
---
None

SALTO-6401: Fix duplicate log message on Okta fetch

---

packages/zendesk-adapter/src/config_creator.ts
packages/zendesk-adapter/test/config_creator.test.ts

SALTO-6407 Update config type to match the current Guide and Themes implementation.

---

packages/core/src/local-workspace/dir_store.ts
packages/core/test/common/workspace.ts
packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
packages/workspace/src/workspace/workspace.ts
packages/workspace/test/common/nacl_file_store.ts
packages/workspace/test/workspace/config_source.test.ts
packages/workspace/test/workspace/multi_env/multi_env_source.test.ts
packages/workspace/test/workspace/workspace.test.ts

Revert "SALTO-6342: fix update nacl files to include static file changes continue"

---

packages/jira-adapter/src/change_validators/field_contexts/assets_object_field_configuration_aql.ts
packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/config/config.ts
packages/jira-adapter/test/change_validators/field_contexts/assets_object_field_configuration_aql.test.ts

_add AQL placeholder change validator_
---
---
---

SALTO-6422: add AQL placeholder change validator

---

packages/okta-adapter/src/definitions/requests/clients.ts

The recent commit was somehow merged without running prettier step 🤷‍♀️ 
---
---
None
---
None

Format Okta

---

packages/okta-adapter/src/definitions/requests/clients.ts

fix format again

---

packages/jira-adapter/src/filters/project_component.ts
packages/jira-adapter/test/filters/project_component.test.ts

None
---
None
---
Jira Adapter:
* Fixed a bug in jira DC causing components with no lead to fail deployment
---
None

SALTO-6478: component crash when no lead id

---

packages/jira-adapter/src/config/api_config.ts

Fixed a bug that caused creation of project scoped automations to fail
---
See jira [ticket](https://salto-io.atlassian.net/browse/SALTO-6484) for details on the solution
A noise reduction PR will be added
---
Jira Adapter:
* Fixed a bug that caused some automation deployments to fail
---
Jira Adapter:
automations will no longer contain their uuid

SALTO-8484: Automation deployment failure

---

packages/netsuite-adapter/src/filters/workflow_account_specific_values.ts

SALTO-2392 better "formula params mismatch" log in workflows ASVs resolving

---

packages/jira-adapter/src/filters/data_center/plugin_version.ts

---
---
Jira Adapter:
* fix a bug in fieldConfiguration deployment in Jira DC - to enable it you should upgrade Salto's plugin via the marketplace
_None_
---
_None_

SALTO-6469: update jira DC version

---

packages/okta-adapter/src/definitions/fetch/types/email_domain.ts
packages/okta-adapter/test/definitions/fetch/types/email_domain.test.ts

SALTO-5983: Fix headers in `email_domain{,.test}.ts`

---

packages/okta-adapter/src/definitions/fetch/fetch.ts

SALTO-6404: Don't recurse into group push rules when app disabled

---

packages/netsuite-adapter/src/change_validators/client_validation.ts
packages/netsuite-adapter/test/change_validators/client_validation.test.ts

as described in SALTO-3016 we should include file cabinet changes as part of the SDF validation, but can we just ignore the validation errors that we have on them after the validation has ran.
---
---
- Ignore FileCabinet errors on SDF validation
---
None

SALTO-6491 Ignore FileCabinet errors on SDF validation

---

packages/adapter-components/src/config_deprecated/request.ts
packages/adapter-components/src/fetch/resource/subresources.ts

Just adding some comments to document the usage.
---
Inspired by #6426 
---
None
---
None

Add docs to `RecurseIntoCondition`

---

packages/core/src/api.ts

Fix core utilities that throw run-time errors
---
_None_
---
_None_

SAAS-11879: Fix core utilities that throw run-time errors

---

packages/adapter-components/src/fetch/request/pagination/queue.ts
packages/adapter-components/src/fetch/resource/type_fetcher.ts

SALTO-6501: Remove errors from logs

---

packages/salesforce-adapter/src/change_validators/unknown_picklist_values.ts
packages/salesforce-adapter/test/change_validators/unknown_picklist_values.test.ts

Salesforce Unknown Picklist Values CV does not handle CustomField references correctly
---
This was the behavior prior to my fix:
---
- Bug-fix: Salesforce Unknown Picklist Values CV does not handle CustomField references correctly
---
_None_

SALTO-6502: Salesforce Unknown Picklist Values CV does not handle CustomField references correctly

---

packages/adapter-components/test/fetch/utils.test.ts

UT fix for https://github.com/salto-io/salto/pull/6441
---
None
---
None

SALTO-6509 fix test

---

packages/jira-adapter/src/change_validators/field_contexts/custom_field_with_10K_options.ts
packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/common/fields.ts
packages/jira-adapter/test/change_validators/field_contexts/custom_field_with_10K_options.test.ts

_match 10k VC to splitFieldContextOptions flag_
---
---
* match 10k VC to splitFieldContextOptions flag
---
_None_

SALTO-5932: (Jira) match 10k VC to splitFieldContextOptions flag

---

packages/zendesk-adapter/e2e_test/adapter.ts
packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/adapter_creator.ts

add definitions override to zendesk
---
---
---

SALTO-6532: add definitions override to zendesk

---

packages/jira-adapter/src/filters/layouts/layout_service_operations.ts
packages/jira-adapter/src/filters/layouts/layout_types.ts
packages/jira-adapter/test/filters/layouts/request_type_request_form.test.ts

In this PR I supported new issueView format, only for stage 1.
---
Much much more context can be found in [SALTO-6477 ](https://salto-io.atlassian.net/browse/SALTO-6477?focusedCommentId=174771)
---
* [SALTO-6477 ](https://salto-io.atlassian.net/browse/SALTO-6477?focusedCommentId=174771): Supporting new issue view format stage 1. 
---
None

SALTO-6477: Support new IssueView format

---

packages/adapter-components/scripts/client/mock_replies.py
packages/adapter-components/scripts/client/mock_replies_nock.py
packages/adapter-components/src/client/http_client.ts
packages/adapter-components/src/client/logging_utils.ts
packages/adapter-components/test/client/logging_utils.test.ts

Small fixes - use smaller params when reaching truncate + typo fix + adjust extraction scripts
---
None
---
None

SALTO-6481 truncate more

---

packages/adapter-components/src/client/http_client.ts
packages/jira-adapter/test/client/client.test.ts
packages/jira-adapter/test/client/script_runner_client.test.ts
packages/jira-adapter/test/filters/issue_type_schemas/issue_type_scheme.test.ts
packages/jira-adapter/test/filters/portal_settings.test.ts
packages/jira-adapter/test/filters/security_scheme.test.ts
packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts
packages/okta-adapter/test/filters/app_user_schema_deployment.test.ts

continuing from https://github.com/salto-io/salto/pull/6388
---
None
---
None

SALTO-6419 change error text to avoid AxiosError prefix for additional errors

---

packages/adapter-components/src/client/pagination/common.ts
packages/adapter-components/src/client/pagination/pagination_async.ts
packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/config/config.ts
packages/jira-adapter/src/filters/store_users.ts
packages/jira-adapter/src/users.ts
packages/jira-adapter/test/filters/store_users.test.ts
packages/jira-adapter/test/utils.ts

_add allow user call failure config flag_
---
---
_None_
---
_None_

SALTO-6538: add allow user call failure config flag

---

packages/google-workspace-adapter/e2e_test/adapter.test.ts

SALTO-6535-flakiness-in-google-workspace-e2e
---
---
---

SALTO-6535-flakiness-in-google-workspace-e2e

---

packages/workspace/src/workspace/index_utils.ts
packages/workspace/test/workspace/index_utils.test.ts

SALTO-6508: Fix update index to avoid running on the same element twice

---

packages/jira-adapter/src/change_validators/field_contexts/field_context_default_value.ts
packages/jira-adapter/src/change_validators/field_contexts/field_context_options.ts
packages/jira-adapter/src/change_validators/field_contexts/order_removal.ts
packages/jira-adapter/src/change_validators/index.ts
packages/jira-adapter/src/config/config.ts
packages/jira-adapter/test/change_validators/field_contexts/field_context_default_value.test.ts
packages/jira-adapter/test/change_validators/field_contexts/field_context_options.test.ts
packages/jira-adapter/test/change_validators/field_contexts/order_removal.test.ts

_Validate that the order instance reference all of it's options and validate the default values_
---
---
* Validate that the context order instance reference all of it's options and validate the default values of the context
---
_None_

SALTO-5932: (Jira) Validate that the order instance reference all of it's options and validate the default values

---

packages/jira-adapter/src/filters/fields/context_deployment_filter.ts
packages/jira-adapter/src/filters/fields/context_options.ts
packages/jira-adapter/src/filters/fields/default_values.ts
packages/jira-adapter/src/group_change.ts
packages/jira-adapter/test/filters/fields/contexts.test.ts
packages/jira-adapter/test/filters/fields/default_values.test.ts
packages/jira-adapter/test/filters/fields/field_context_deployment.test.ts
packages/jira-adapter/test/group_change.test.ts

_Update some filters related to splitting options from contexts_
---
---
* Update filters related to splitting options from contexts
---
_None_

SALTO-5932: Update some filters related to splitting options from contexts

---

packages/zendesk-adapter/src/fix_elements/fallback_user.ts

_Adds a log to fallback_user fixer to increase visibility_
---
_None_
---
_None_
---
_None_

SAAS-10995: add logs to fallback_user fixer

---

packages/adapter-components/src/client/pagination/pagination_async.ts
packages/jira-adapter/src/filters/automation/automation_deployment.ts

Remove some unneeded trace logs
---
None
---
None
---
None

Salto-6572:  trace logs

---

packages/adapter-utils/src/element_source.ts
packages/adapter-utils/src/utils.ts
packages/adapter-utils/test/element_source.test.ts

_fix elementsSource bug that cause failure when getting a non top level element_
---
---
_None_
---
_None_

SALTO-6592:  fix elementsSource bug that cause failure when getting a non top level element

---

.circleci/config.yml

SALTO-6593: fix prepare pipeline name

---

packages/core/src/local-workspace/remote_map/remote_map.ts

We suspect that in certain scenarios `closeRemoteMapsOfLocation` is getting stuck
added log.timeDebug so we can track cases when the function doesn't finish
---
---
None
---
None

SALTO-6571: Add time log.timeDebug for closeRemoteMapsOfLocation

---

packages/netsuite-adapter/src/constants.ts
packages/netsuite-adapter/src/filters/workflow_account_specific_values.ts
packages/netsuite-adapter/test/filters/workflow_account_specific_values.test.ts

SALTO-2392 Improve workflow formula parsing for ASVs

---

packages/adapter-utils/src/important_values.ts
packages/adapter-utils/test/important_values.test.ts

fix getImportantValues
---
---
---

SAAS-11985: fix getImportantValues

---

packages/netsuite-adapter/package.json
yarn.lock

SALTO-6546: Update the dependency version of salto-io/logging in SDF

---

packages/jira-adapter/src/filters/script_runner/workflow/workflow_filter.ts

Fixed the deployment annotations
---
---
Jira Adapter:
* Fixed deployment annotations in ScriptRunner for DC
---
None

SALTO-6612: fix scriptRunner DC deployment annotations

---

packages/core/index.ts

Export updateElementFolder from core
---
See the previous PR - https://github.com/salto-io/salto/pull/6534
---
None
---
None

SAAS-12017: Export updateElementFolder from core

---

packages/netsuite-adapter/src/filters/data_account_specific_values.ts

this can help us identify `typeId`s that aren't mapped to suiteql table instances.
---
---
None
---
None

Add logs when missing SuiteQL table instance for ASVs in data instances

---

packages/zendesk-adapter/src/adapter_creator.ts

fix updateElemIDDefinitions
---
---
---

SALTO-6665: fix updateElemIDDefinitions

---

packages/salesforce-adapter/src/custom_object_instances_deploy.ts
packages/salesforce-adapter/src/metadata_deploy.ts
packages/zendesk-adapter/src/filters/account_settings.ts

_add detailedMessage to salesforce custom object deploy error_
---
* remove other casting I found as well
---
_None_
---
_None_

SALTO-6675: add detailedMessage to salesforce custom object deploy error

---

packages/dummy-adapter/src/adapter.ts
packages/dummy-adapter/src/adapter_creator.ts
packages/dummy-adapter/src/generator.ts
packages/dummy-adapter/test/adapter_creator.test.ts

---
---
_Dummy Adapter_:
- Support returning fetch errors in Dummy adapter
---
None

SALTO-6678 Support returning fetch errors in Dummy adapter

---

packages/jira-adapter/src/filters/automation/types.ts

Some additional types of automation
---
---
None
---
None

SALTO-6658: better support raw value references

---

packages/jira-adapter/src/filters/automation/smart_values/smart_value_reference_filter.ts
packages/jira-adapter/test/filters/automation/smart_values/smart_value_reference_filter.test.ts

Fixed a small bug in the original ticket that prevented the deployment, and added tests
---
None
---
Jira Adapter:
* Fixed a bug in deployment of automation with complex smart values
---
None

SALTO-6625: fix automation smart values

---

packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts

Get some knowledge about folders with large amount of files in them.
---
---
None
---
None

SALTO-6690 log FileCabinet folders with large amount of files

---

packages/netsuite-adapter/src/filters/element_references.ts

Add logs for new SuiteScript references logic, and avoid running the calculation (regex) for files with invalid extension.
---
---
None
---
None

SALTO-6056 Add logs for new SuiteScript references logic

---

packages/netsuite-adapter/src/filters/data_account_specific_values.ts

Add missing typeId logs

---

packages/core/src/local-workspace/remote_map/remote_map.ts

Currently there is a mismatch between opening a new DB with "open" and creating a new DB with "replicate" the "open" code uses a much smaller write buffer size than "replicate". We want the bigger buffer size since we tend to write a lot of information
---
Documentation about the write buffer size option:
https://github.com/facebook/rocksdb/wiki/Setup-Options-and-Basic-Tuning#write-buffer-size
The place in the binding code that sets the different default value:
https://github.com/salto-io/rocksdb/blob/9863eafd245cefa2fa2a70f6b82734b194259457/binding.cc/#L831
---
Core:
- Increase write buffer size in rocksdb to improve performance
---
_None_

SALTO-6696: Increase rocksdb write buffer size when opening a new DB

---

packages/okta-adapter/e2e_test/adapter.test.ts
packages/okta-adapter/e2e_test/mock_elements.ts

Add policy priority E2E for policy and policy rules
---
added coverage for password policy and access policy for now, will extend later
---
None
---
None

SALTO-6672: Add policy priority E2E

---

packages/dummy-adapter/src/adapter.ts
packages/dummy-adapter/src/generator.ts
packages/dummy-adapter/test/generator.test.ts

---
---
_Dummy Adapter_:
- support elemID input for fetch errors
---
None

SALTO-6723 support elemID in fetch errors dummy adapter

---

packages/jira-adapter/src/config/config.ts

reduce logs for jira gql calls that are made many times during fetch. more details are in the ticket
---
None
---
None

SALTO-6481 reduce logs for heavy jira gql calls

---

packages/core/index.ts
packages/core/src/core/plan/index.ts

context in ticket
---
---
None
---
None

SALTO-6725: Export ChangeWithDetails type

---

packages/jira-adapter/src/client/connection.ts

Added a log for the header + a cred error for captcha. We still need to connect it to the UI, but we will be able to understand from the logs what happened
---
---
Jira Adapter: added log visibility for DC captcha failures
---
None

SALTO-6662: log cred errors such as captcha

---

packages/jira-adapter/src/filters/automation/types.ts
packages/jira-adapter/src/reference_mapping.ts

Add projectId reference for JSM automation within components...children
---
None
---
None
---
None

SALTO-6734 Jira JSM Automation->projectId reference

---

packages/workspace/src/workspace/hidden_values.ts
packages/workspace/test/workspace/hidden_values.test.ts

Fix a bug which broke fetches which caused type elements to be hidden in a top-level modification, such as when hiding a type and adding a meta type in the same fetch.
---
Example env: https://github.com/salto-io/ariel-sf/commit/3a761290a2d4427610a319551c923d411bbc56f6
Not testing for unhiding types because that doesn't work due to an unrelated bug (SALTO-6741).
---
None.
---
None.

SALTO-6739: Fixing hiding elements in top level modifications

---

packages/adapter-utils/src/compare.ts
packages/adapter-utils/src/list_comparison.ts

Remove redundant list-comparison logs

---

packages/netsuite-adapter/e2e_test/adapter.test.ts
packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts
packages/netsuite-adapter/src/filters/element_references.ts
packages/netsuite-adapter/test/adapter.test.ts
packages/netsuite-adapter/test/data_elements/suiteql_table_elements.test.ts

- `fetch.forceFileCabinetExclude` - change to `true` by default
- `fetch.addLockedCustomRecordTypes` - change to `true` by default
- `fetch.resolveAccountSpecificValues` - change to `true` by default
- `fetch.useNewReferencesInSuiteScripts` - change to `true` by default
- `suiteAppClient.wsdlVersion` - change to `"2024_1"` by default
---
---
- Change features config defaults
---

Change NS features config defaults

---

packages/adapter-components/src/definitions/system/fetch/element.ts
packages/zendesk-adapter/src/definitions/fetch/fetch.ts

fix for https://github.com/salto-io/salto/pull/6115
+ remove a zendesk case that I think wasn't working
---
None
---
None

SALTO-6141 fix type

---

packages/adapter-api/src/adapter.ts
packages/cli/src/commands/adapter_format.ts
packages/cli/test/commands/adapter_format.test.ts
packages/core/index.ts
packages/core/src/core/adapter_format.ts
packages/core/test/common/helpers.ts
packages/core/test/core/adapter_format.test.ts
packages/dummy-adapter/src/adapter_creator.ts
packages/dummy-adapter/test/adapter_creator.test.ts
packages/netsuite-adapter/e2e_test/adapter.test.ts
packages/netsuite-adapter/src/adapter_creator.ts
packages/salesforce-adapter/package.json
packages/salesforce-adapter/src/adapter_creator.ts
packages/salesforce-adapter/src/sfdx_parser/project.ts
packages/salesforce-adapter/src/sfdx_parser/salesforce_imports.ts
packages/salesforce-adapter/src/sfdx_parser/sfdx_dump.ts
packages/salesforce-adapter/src/sfdx_parser/sfdx_parser.ts
packages/salesforce-adapter/test/sfdx_parser/project.test.ts
packages/salesforce-adapter/test/sfdx_parser/sfdx_dump.test.ts
packages/salesforce-adapter/test/sfdx_parser/utils.ts
yarn.lock

For now not allowing any customisation of the created project, don't think we'll ever need it.
---
None.
---
_Salesforce adatprer_:
* Added new methods to check for the existence of an SFDX project in a directory and for creating one.
---
None.

SALTO-6747: Support checking for and creating SFDX projects

---

packages/jamf-adapter/src/adapter_creator.ts
packages/jamf-adapter/src/definitions/fetch/fetch.ts
packages/jamf-adapter/test/adapter.test.ts

support service url on Jamf
---
---
- support service url
---
- support service url

SALTO-6758 support service url on Jamf

---

packages/adapter-components/src/deployment/change_validators/skip_parents_of_skipped_instances.ts
packages/jira-adapter/src/change_validators/automation/automation_projects.ts
packages/jira-adapter/src/change_validators/screen.ts
packages/jira-adapter/test/change_validators/automations/automation_projects.test.ts
packages/jira-adapter/test/change_validators/screen.test.ts
packages/netsuite-adapter/src/change_validators/standard_types_invalid_values.ts

SALTO-6771, SALTO-6772, SALTO-6773, SALTO-6774: Better CV messages

---

packages/netsuite-adapter/src/change_validators/client_validation.ts
packages/netsuite-adapter/test/change_validators/client_validation.test.ts

---
---
SALTO-6523: Update the message and detailedMessage for 'SDF validation error'
---

SALTO-6523: Update the message and detailedMessage for 'SDF validation error'

---

packages/jamf-adapter/src/definitions/fetch/transforms/configuration_profile.ts
packages/jamf-adapter/src/definitions/fetch/transforms/utils.ts
packages/jamf-adapter/test/definitions/fetch/transform/configuration_profile.test.ts

---
---
- omit password from configurationProfile instances
---
- omit password from configurationProfile instances

SALTO-6759 omit password from configurationProfile instances

---

packages/jira-adapter/src/filters/script_runner/workflow/workflow_dc.ts

SALTO-6782: Reduce the large payload Jira DC prints

---

packages/jira-adapter/src/filters/fields/context_options.ts
packages/jira-adapter/src/filters/layouts/issue_layout.ts

SALTO-6833 Jira small improvements
---
---
None
---
None

SALTO-6833 Jira small improvements

---

packages/adapter-utils/src/change.ts
packages/adapter-utils/test/change.test.ts

Make `reverseChange` reverse also the `baseChange`.
---
---
None
---
None

SALTO-6278 reverse base change

---

packages/salesforce-adapter/src/filters/convert_maps.ts
packages/salesforce-adapter/test/filters/convert_maps.test.ts

Being more defensive about values we use in this filter since we've seen it fail in the wild.
---
Not sure this is the best approach, open to other ideas.
---
None.
---
None.

SALTO-6843: Filtering out invalid keys in convert maps

---

packages/salesforce-adapter/src/filters/convert_maps.ts

---
_Salesforce_:
* Fixed a regression in deploying Lightning Web Components.
---
None.

SALTO-6853: Fixing LWC regression in convert maps

---

packages/salesforce-adapter/test/filters/convert_maps.test.ts

The fix didn't include UT so we could get it in faster.
---
None.
---
None.

SALTO-6853: Adding UT for LWC regression

---

packages/okta-adapter/test/mock_replies/README.md

See title.
---
None
---
None
---
None

SALTO-6291: Okta: Add README to HTTP-recording test directory

---

packages/jira-adapter/src/filters/data_center/plugin_version.ts

_update jira DC version_
---
---
_None_
---
_None._

SALTO-6854: update jira DC version

---

packages/jira-adapter/e2e_test/instances/cloud/workflow.ts
packages/jira-adapter/e2e_test/instances/datacenter/workflow.ts

_add global looped transition to jira E2E_
---
---
_None_
---
_None_

SALTO-6861: add global looped transition to jira E2E

---

packages/salesforce-adapter/src/transformers/xml_transformer.ts

Log transformed XMLs in Salesforce Deployments.
---
This should help us understand invalid XMLs the adapter sends to Salesforce.
---
_None_
---
_None_

SALTO-6858: Log transformed XMLs in Salesforce Deployments

---

packages/microsoft-security-adapter/jest.config.js
packages/microsoft-security-adapter/src/client/connection.ts

Header is self explanatory
---
---
---

SALTO-6841: Log an error when getAccessToken fails for Microsoft Security

---

packages/jira-adapter/src/group_change.ts
packages/jira-adapter/test/group_change.test.ts

_add issueLinkType change group_
---
---
_None_
---
_None_

SALTO-6870: add issueLinkType change group

---

packages/workspace/src/workspace/workspace.ts

SALTO-6887: Add log time debug to buildWorkspaceState

---

packages/jira-adapter/src/reference_mapping.ts

_remove missingRefStrategy from FIELD_SELECTED_FIELDS_
---
---
_None_
---
_None_

SALTO-6894: remove missingRefStrategy from FIELD_SELECTED_FIELDS

---

packages/adapter-components/src/references/field_references.ts

SALTO-2432: Log the time it takes to process references for type

---

packages/salesforce-adapter/config_doc.md
packages/salesforce-adapter/src/additional_references.ts
packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts
packages/salesforce-adapter/src/types.ts

Revert "SALTO-6901: Removing the `generateRefsInProfiles` optional feature"

---

packages/okta-adapter/e2e_test/adapter.test.ts
packages/okta-adapter/e2e_test/mock_elements.ts

Return Okta E2E

---

eslint.config.mjs
packages/adapter-utils/test/utils.test.ts
packages/core/src/local-workspace/remote_map/remote_map.ts
packages/core/src/telemetry.ts
packages/core/test/workspace/local/s3_dir_store.test.ts
packages/e2e-credentials-store/test/cli/index.test.ts
packages/jira-adapter/src/filters/account_id/account_id_filter.ts
packages/jira-adapter/src/filters/jql/jql_references.ts
packages/jira-adapter/src/filters/remove_self.ts
packages/jira-adapter/src/filters/workflow/workflow_diagrams.ts
packages/netsuite-adapter/src/filters/currency_omit_fields.ts
packages/netsuite-adapter/test/change_validators/immutable_changes.test.ts
packages/okta-adapter/src/filters/access_policy_rule_constraints.ts
packages/okta-adapter/src/filters/expression_language.ts
packages/okta-adapter/src/filters/user_schema.ts
packages/persistent-pool/src/lib/renewed_lease.ts
packages/salesforce-adapter/src/client/client.ts
packages/salesforce-adapter/src/filters/convert_maps.ts
packages/salesforce-adapter/src/filters/cpq/lookup_fields.ts
packages/salesforce-adapter/src/filters/field_permissions_enum.ts
packages/salesforce-adapter/src/metadata_deploy.ts
packages/salesforce-adapter/test/filters/field_permissions_enum.test.ts
packages/workato-adapter/src/rlm.ts
packages/zendesk-adapter/src/filters/deploy_trigger_skills.ts
packages/zendesk-adapter/src/filters/handle_template_expressions.ts

Hopefully, this will be useful.
---
---
None
---
None

SALTO-6916: enable `no-misused-promises` lint for all oss projects

---

packages/salesforce-adapter/src/metadata_deploy.ts

Saw them while working on this issue.
---
None.
---
None.
---
None.

SALTO-6898: Fixing lint warnings in deploy

---

packages/jira-adapter/src/adapter.ts
packages/jira-adapter/src/config/config.ts
packages/jira-adapter/src/filters/field_configuration/field_configuration_default_values.ts
packages/jira-adapter/test/filters/field_configuration/field_configuration_default_values.test.ts

_reduce fieldConfiguration nacl size_
---
---
---

SALTO-5289: reduce fieldConfiguration nacl size

---

packages/okta-adapter/src/filters/access_policy_rule_constraints.ts
packages/okta-adapter/src/filters/expression_language.ts
packages/okta-adapter/src/filters/user_schema.ts
packages/workato-adapter/src/rlm.ts

SALTO-6918: Fix misused promises in Okta & Workato

---

packages/netsuite-adapter/src/filters/currency_omit_fields.ts
packages/netsuite-adapter/test/change_validators/immutable_changes.test.ts

SALTO-6918 fix netsuite no-misused-promises lint error

---

packages/jira-adapter/src/filters/data_center/plugin_version.ts

_update jira DC plugin version_
---
---
---

SALTO-6902: update jira DC plugin version

---

packages/salesforce-adapter/cpq-sbaa-config-doc.md

Update the CPQ doc to include an example with Internal Id as Salto Id
---
None
---
None
---
None

DOC-191 - Update the CPQ doc to include an example with Internal Id as Salto Id

---

packages/core/src/core/fetch.ts

The current code searches for elements on every modification change. This is a waste because only top level IDs are available and modification changes on nested IDs don't require a path anyway
---
---
_None_
---
_None_

SALTO-6928 - improve fetch performance - avoid searching for nested IDs

---

packages/workspace/src/workspace/reference_indexes.ts

Add logs to reference index update
---
---
None
---
None

SALTO-6931: Add logs to reference index update

---

packages/salesforce-adapter/src/filters/formula_deps.ts

removed log from formula_deps
---
removed noisy log from formula_deps 
---
salseforce-adapter:
removed noisy log
---
none

removedLog

---

packages/salesforce-adapter/src/fetch.ts

SALTO-3398: Better visibility on Salesforce retrieve requests
---
_None_
---
_None_

SALTO-3398: Better visibility on Salesforce retrieve requests

---

packages/cli/src/commands/deploy.ts
packages/cli/src/formatter.ts
packages/cli/src/prompts.ts
packages/cli/test/commands/deploy.test.ts
packages/core/index.ts
packages/core/src/core/deploy/deploy_summary.ts
packages/core/test/core/deploy/deploy_summary.test.ts

This reverts commit a89412540facad94762ea74b57644cd1f3ff6878.
---
---
---

Revert "SALTO-1830 Post deploy message (#6783)"

---

packages/e2e-credentials-store/index.ts
packages/e2e-credentials-store/src/jest-environment/index.ts
packages/jira-adapter/src/filters/automation/automation_label/label_fetch.ts
packages/jira-adapter/src/filters/broken_reference_filter.ts
packages/salesforce-adapter/src/constants.ts

Found by knip.
---
None.
---
None.

SALTO-6213: Removing duplicate exports

---

packages/salesforce-adapter/src/adapter_creator.ts
packages/salesforce-adapter/src/transformers/transformer.ts
packages/salesforce-adapter/src/types.ts

Found by knip.
---
---
None.
---
None.

SALTO-6213: Fixing unused enum members

---

packages/jira-adapter/src/filters/sort_lists.ts
packages/jira-adapter/test/filters/sort_lists.test.ts

Salto 6917 sort lists by relevant types
---
None
---
None
---
None

Salto 6917 sort lists by relevant types

---

packages/cli/src/commands/deploy.ts

erased useless export
---
erased useless export
---
none
---
none

fixed lint

---

packages/salesforce-adapter/src/config_creator.ts
packages/salesforce-adapter/src/types.ts
packages/salesforce-adapter/test/config_creator.test.ts

SAAS-11665: Revert

---

.circleci/config_template.yml
.knip.json
knip.json
package.json
yarn.lock

Disabled the two most important issue types (exports and types) since we will onboard them gradually.
---
---
None.
---
None.

SALTO-6213: Adding knip to CI

---

packages/jira-adapter/src/filters/account_id/account_id_filter.ts
packages/jira-adapter/src/filters/jql/jql_references.ts
packages/jira-adapter/src/filters/remove_self.ts
packages/jira-adapter/src/filters/workflow/workflow_diagrams.ts

Fixed some async issues thanks to a new lint rule added by Dor
---
None
---
None
---
None

SALTO-6918: async issues for jira discoverd with new lint

---

packages/cli/src/main.ts
packages/core/src/app_config.ts
packages/dummy-adapter/src/adapter_creator.ts
packages/dummy-adapter/src/generator.ts
packages/dummy-adapter/test/adapter.test.ts
packages/lowerdash/src/collections/tree_map.ts
packages/workspace/src/workspace/config_source.ts
packages/workspace/src/workspace/nacl_files/nacl_files_source.ts

Also, refactor dummy adapter a bit to allow it to handle scale better
---
Based on #6832 
---
Core:
- Small performance improvements by reducing source map calculations
---
_None_

SALTO-6964: avoid generating source maps where they are not needed 

---

packages/salesforce-adapter/src/filters/formula_deps.ts
packages/salesforce-adapter/src/filters/formula_utils.ts
packages/salesforce-adapter/src/filters/utils.ts

Some logs are a bit spammy and there is much more async than there needs to be.
---
---
None.
---
None.

SALTO-6962: Improve formula deps filter

---

packages/salesforce-adapter/src/change_validators/account_settings.ts
packages/salesforce-adapter/src/change_validators/flows.ts
packages/salesforce-adapter/src/change_validators/map_keys.ts
packages/salesforce-adapter/src/change_validators/multiple_defaults.ts
packages/salesforce-adapter/src/change_validators/ordered_maps.ts
packages/salesforce-adapter/src/filters/convert_maps.ts

Won't solve all the problems but hopefully will lead to some performance gains.
---
---
None.
---
None.

SALTO-6954: Removing some async calls from validators

---

packages/salesforce-adapter/src/change_validators/account_settings.ts
packages/salesforce-adapter/src/change_validators/flows.ts
packages/salesforce-adapter/src/change_validators/map_keys.ts
packages/salesforce-adapter/src/change_validators/multiple_defaults.ts
packages/salesforce-adapter/src/change_validators/ordered_maps.ts
packages/salesforce-adapter/src/filters/convert_maps.ts

This reverts commit e971100cbb32b6780017a0c9d8071ab6407027a5.
---
---
---

Revert "SALTO-6954: Removing some async calls from validators (#6827)"

---

packages/core/test/workspace/local/remote_map/remote_map.test.ts

In future PRs, I plan to move this "test" into a new package, which I'd like not to be dependent on dummy-adapter.
This is a step in that direction
---
---
None
---
None

SALTO-6956: Remove remote_map tests usage of dummy-adapter

---

packages/jira-adapter/src/change_validators/sd_portals_permission_scheme.ts
packages/jira-adapter/src/filters/permission_scheme/forbidden_permission_schemes.ts
packages/jira-adapter/src/filters/permission_scheme/sd_portals_permission_scheme.ts
packages/jira-adapter/test/change_validators/sd_portals_permission_scheme.test.ts
packages/jira-adapter/test/filters/permission_scheme/forbidden_permission_schemes.test.ts
packages/jira-adapter/test/filters/permission_scheme/sd_portals_permission_scheme.test.ts

Remove unsupported permissions from PermissionSchemes
---
None
---
- Fix PermissionScheme bug
---
None

SALTO-6984 Jira: remove unsupported permissions

---

packages/salesforce-adapter/src/change_validators/account_settings.ts
packages/salesforce-adapter/src/change_validators/flows.ts
packages/salesforce-adapter/src/change_validators/map_keys.ts
packages/salesforce-adapter/src/change_validators/multiple_defaults.ts
packages/salesforce-adapter/src/change_validators/ordered_maps.ts

Hopefully this should lead to some performance gains.
---
I tested all of the CVs using the CLI in a real world example and they all worked.
---
None.
---
None.

SALTO-6954: Removing some async calls from CVs

---

packages/salesforce-adapter/src/change_validator.ts
packages/salesforce-adapter/src/change_validators/custom_applications.ts
packages/salesforce-adapter/src/transformers/reference_mapping.ts
packages/salesforce-adapter/src/types.ts
packages/salesforce-adapter/test/change_validators/custom_applications.test.ts

SALTO-6326: Add a CV for custom application
---
---
_None_
---
_None_

SALTO-6326: Add a CV for custom application

---

packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/src/definitions/fetch/fetch.ts

Add a service url for the queue type.
---
---
---

SALTO-6968 Add queue service URL

---

packages/salesforce-adapter/src/sfdx_parser/sfdx_dump.ts

This is a pretty naive approach but might well be good enough.
---
None.
---
None.
---
None.

SALTO-6818: Validating SFDX project after dump

---

packages/salesforce-adapter/src/change_validators/invalid_list_view_filter_scope.ts
packages/salesforce-adapter/src/config_change.ts
packages/salesforce-adapter/src/constants.ts
packages/salesforce-adapter/src/filters/centralize_tracking_info.ts
packages/salesforce-adapter/src/filters/global_value_sets.ts
packages/salesforce-adapter/src/filters/territory.ts
packages/salesforce-adapter/test/change_validators/invalid_list_view_filter_scope.test.ts
packages/salesforce-adapter/test/filters/workflow.test.ts
packages/salesforce-adapter/test/mock_elements.ts

Surfaced by upgrading eslint.
---
Looks like the invalid list view filter scope CV didn't actually work...
---
None.
---
None.

SALTO-7009: Fixing misused promises

---

packages/core/src/core/adapter_format.ts
packages/core/test/core/adapter_format.test.ts

SALTO-7015: Return unapplied changes from update element folder

---

packages/adapter-api/src/comparison.ts
packages/adapter-api/src/element_id.ts

Revert "SALTO-6991: create element ID full name only if needed"

---

packages/cli/src/commands/deploy.ts
packages/cli/test/commands/deploy.test.ts

fixed case of cancelled deployment for deployment summary
---
fixed case of cancelled deployment
---
none
---
none

SALTO-1830-cancel-deployment-fix

---

packages/parser/src/parser/index.ts

SALTO-6990: Export ParseValue
---
---
---

SALTO-6990: Export ParseValue

---

packages/local-workspace/test/common/nacl_file_source.ts
packages/workspace/src/workspace/dependents.ts
packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
packages/workspace/src/workspace/nacl_files/nacl_file_update.ts
packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
packages/workspace/src/workspace/nacl_files/parsed_nacl_file.ts
packages/workspace/src/workspace/nacl_files/parsed_nacl_files_cache.ts
packages/workspace/src/workspace/workspace.ts
packages/workspace/test/common/nacl_file_source.ts
packages/workspace/test/workspace/dependents.test.ts
packages/workspace/test/workspace/nacl_files/nacl_file_update.test.ts
packages/workspace/test/workspace/nacl_files/nacl_files_source.state.test.ts
packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
packages/workspace/test/workspace/nacl_files/parsed_nacl_files_cache.test.ts
packages/workspace/test/workspace/workspace.test.ts

This index isn't needed anymore.
---
---
Workspace:
- Remove nacl files referenced index
---
None

SALTO-6697 remove nacl files referenced index

---

packages/zendesk-adapter/src/change_validator.ts
packages/zendesk-adapter/src/change_validators/business_hours_schedule_holiday.ts
packages/zendesk-adapter/src/change_validators/index.ts
packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/test/change_validators/business_hours_schedule__holiday.test.ts

SALTO-6788: Add CV for business holiday creation dates
---
---
_None_
---
_None_

SALTO-6788: Add CV for business holiday creation dates

---

packages/local-workspace/src/s3_dir_store.ts

Safer log print

---

packages/salesforce-adapter/config_doc.md

SALTO-6326: Added the CV to config_doc
---
None
---
None

SALTO-6326: Added the CV to config_doc

---

packages/zendesk-adapter/src/change_validators/business_hours_schedule_holiday.ts
packages/zendesk-adapter/test/change_validators/business_hours_schedule_holiday.test.ts

SALTO-6788-FIX: Add CV for business holiday creation dates
---
---
None
---
None

SALTO-6788-FIX: Add CV for business holiday creation dates

---

packages/zendesk-adapter/src/dependency_changers/modified_and_deleted.ts
packages/zendesk-adapter/test/dependency_changers/modified_and_deleted.test.ts

add ticket field and trigger to the modifiedAndDeletedDependencyChanger
---
---
---

SALTO-7064: add ticket field and trigger to the modifiedAndDeletedDependencyChanger

---

packages/zendesk-adapter/src/filters/deploy_trigger_skills.ts
packages/zendesk-adapter/src/filters/handle_template_expressions.ts

SALTO-6961 Fix misused promises

---

packages/jira-adapter/e2e_test/instances/cloud/filter.ts
packages/jira-adapter/src/constants.ts
packages/jira-adapter/src/filters/filter.ts
packages/jira-adapter/src/filters/share_permission.ts
packages/jira-adapter/test/filters/filter.test.ts

The deployments failed, which is very weird
---
None
---
Jira Adapter:
* Fixed a bug in deployment of Filters with user share permissions
---
None

SALTO-7062: Deployment of filters with user share permissions

---

packages/okta-adapter/src/adapter.ts

SALTO-6874: Make share context shared across change groups

---

packages/zendesk-adapter/src/filters/handle_template_expressions.ts
packages/zendesk-adapter/test/filters/handle_template_expressions.test.ts

add more references to json body
---
---
zendesk: 
* add more references to json body when `convertJsonIdsToReferences` = true
---

SALTO-7097: add more references to json body

---

packages/workspace/src/workspace/workspace.ts
packages/workspace/test/workspace/workspace.test.ts

Suggestion: View this PR using
---
None
---
None

SALTO-7092: call workspace close method in case loadWorkspace fails

---

packages/workspace/src/workspace/nacl_files/elements_cache.ts

Includes a small readability refactor in `elements_cache.ts`.
In the code we have `Promise.all` that gets elements from each of the sources and returns `Element[]`, but it should return `AsyncIterable<Element>`, so we don’t need to have all elements in the memory in the same time.
---
---
Workspace:
- Reduce memory consumption in mergeManager cache update
---
None

SALTO-7119 use async iterable in mergeManager cache update

---

packages/local-workspace/src/workspace.ts
packages/local-workspace/test/workspace.test.ts

Take 2
---
The last attempt did not handle all the cases where we failed to run `loadLocalWorkapce` or `initLocalWorkspace`. This PR attempts to do just that.
---
---

SALTO-7092: cleanup resources in workspace init\load

---

packages/zendesk-adapter/src/config.ts
packages/zendesk-adapter/src/filters/article/utils.ts

Update Zendesk max duration to avoid timeouts
---
---
---

SALTO-7131 Update Zendesk max duration to avoid timeouts.

---

packages/workspace/src/workspace/workspace.ts

Add a workspace log for config validation warnings next to where we currently log element warnings
---
---
_None_
---
_None_

SALTO-7143: Log adapter config validation warnings

---

packages/core/test/api.test.ts

SALTO-7006: fix test

---

packages/jira-adapter/e2e_test/instances/datacenter/automation.ts
packages/jira-adapter/src/config/api_config.ts
packages/jira-adapter/src/config/config.ts
packages/jira-adapter/test/filters/automation/automation_fetch.test.ts

1. Remove tags from Automations
2. Mask 'Authorization' and 'x-api-key' Automation headers by default
---
None
---
- Remove tags from Automations
- Mask 'Authorization' and 'x-api-key' Automation headers by default
---
- Remove tags from Automations
- Mask 'Authorization' and 'x-api-key' Automation headers by default

SAAS-7133 Jira Improvements

---

packages/salesforce-adapter/src/filters/picklist_references.ts

Change noisy SF log to trace
---
_None_
---
_None_

SALTO-7154: Change noisy SF log to trace

---

packages/salesforce-adapter/src/fetch_profile/optional_features.ts
packages/salesforce-adapter/src/transformers/reference_mapping.ts
packages/salesforce-adapter/src/types.ts

Add reference from PackageVersion to InstalledPackage instances
---
Requires the optional feature `packageVersionReference `
---
_None_
---
_None_

SALTO-7163 - Add reference from PackageVersion to InstalledPackage instances

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/constants.ts
packages/zendesk-adapter/src/definitions/fetch/fetch.ts
packages/zendesk-adapter/src/definitions/fetch/graphql_schemas.ts
packages/zendesk-adapter/src/definitions/fetch/transforms/graphql_adjuster.ts
packages/zendesk-adapter/src/filters/bot_builder_arrange_paths.ts
packages/zendesk-adapter/src/filters/field_references.ts
packages/zendesk-adapter/test/definitions/fetch/transforms/graphql_adjuster.test.ts
packages/zendesk-adapter/test/filters/bot_builder_arrange_paths.test.ts

Clean up schema (equivalent to omitting fields)
Add path arrange filter
Add references
Add inner error handling from the graphql response
---
---
---

SALTO-6867 Bot builder fetch additions

---

packages/salesforce-adapter/src/adapter.ts
packages/salesforce-adapter/src/last_change_date_of_types_with_nested_instances.ts
packages/salesforce-adapter/test/last_change_data_of_types_with_nested_instances.test.ts

SALTO-6950: Avoid listing unsupported types
---
None
---
None

SALTO-6950: Avoid listing unsupported types

---

packages/jira-adapter/src/adapter.ts

_reorder alias and serviceUrl filters in Jira_
---
There is a conflict between some of the filters, to overcome it we run aliasFilter twice.
We will solve it on
---
_None_
---
_None_

SALTO-7157: reorder alias and serviceUrl filters in Jira

---

packages/salesforce-adapter/src/fetch_profile/optional_features.ts
packages/salesforce-adapter/src/filters/organization_settings.ts
packages/salesforce-adapter/src/types.ts

Omit noisy OrganizationSettings field.
---
_None_
---
_None_

SALTO-7177: Omit noisy Salesforce OrganizationSettings field

---

packages/adapter-components/src/add_alias.ts

SALTO-7161 Reduce no-alias logs
---
---
None
---
None

SALTO-7161 Reduce no-alias logs

---

packages/netsuite-adapter/src/change_validators/types.ts
packages/netsuite-adapter/src/constants.ts
packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts
packages/netsuite-adapter/src/data_elements/types.ts
packages/netsuite-adapter/src/elements_source_index/elements_source_index.ts
packages/netsuite-adapter/src/filter.ts
packages/netsuite-adapter/src/filters/author_information/system_note.ts
packages/netsuite-adapter/test/data_elements/suiteql_table_elements.test.ts

Add more SuiteQL tables for ASV resolving.
This is not going to affect any existing workspace. In order to resolve the ASVs to those types the following needs to be specified in the adapter config:
```
netsuite {
...
suiteAppClient = {
additionalSuiteQLTables = [
{
name = "customtransactiontype"
typeId = "-100"
queryParams = {
internalIdField = "id"
nameField = "name"
}
},
{
name = "emailtemplate"
typeId = "-120"
queryParams = {
internalIdField = "id"
nameField = "name"
}
},
{
name = "customrecordtype"
typeId = "-125"
queryParams = {
internalIdField = "id"
nameField = "name"
}
},
{
name = "customrecordtype"
typeId = "-123"
queryParams = {
internalIdField = "id"
nameField = "name"
}
},
{
name = "customfield"
typeId = "-124"
queryParams = {
internalIdField = "id"
nameField = "name"
}
},
{ …
```

SALTO-7050 add SuiteQL tables

---

packages/workspace/src/workspace/hidden_values.ts
packages/workspace/test/workspace/hidden_values.test.ts

When a field changes both its `_hidden_value` annotation _and_ its refType, the created detailed change is a modification on the field level, not on the `_hidden_value` attribute directly. This PR adds the appropriate side effect for these kind of changes (hide/unhide values appropriately).
---
This addresses the second scenario mentioned in SALTO-7048
---
Core:
- Bugfix: Modified field changes that include hidden value changes now have correct side effects for hiding or unhiding instance field values.
---
None

7048: Core: Hidden Values: Add side effects for existing field values due to field-level modification changes

---

packages/zendesk-adapter/src/definitions/fetch/fetch.ts

fix brand logo type
---
---
---

SALTO-7219: fix brand logo type

---

packages/core/src/core/adapter_format.ts
packages/core/test/core/adapter_format.test.ts

updateElementFolder now gets an optional workspace which will function as storage for any changes which are not supported by dumpToFolder.
This current implementation does not deal with the case of elements which "move" between the folder & workspace.
---
---
---

SALTO-7233: Support mixed mode in updateElementFolder

---

packages/local-workspace/src/remote_map/remote_map.ts

SAAS-12620: Log error when a DB is not found and needs to be created

---

packages/cli/src/commands/adapter_format.ts
packages/cli/test/commands/adapter_format.test.ts
packages/core/src/core/adapter_format.ts
packages/core/test/core/adapter_format.test.ts

implement mixed mode in calculatePatch.
---
---
---

SALTO-7234: Support mixed mode in calculatePatch

---

packages/netsuite-adapter/index.ts

SAAS-13313: Export toUrlAccountId

---

packages/salesforce-adapter/config_doc.md
packages/salesforce-adapter/src/change_validator.ts
packages/salesforce-adapter/src/change_validators/flexi_page_unused_or_missing_facets.ts
packages/salesforce-adapter/src/constants.ts
packages/salesforce-adapter/src/types.ts
packages/salesforce-adapter/test/change_validators/flexi_page_unused_or_missing_facets.test.ts

SALTO-6840: Add a CV for unused facets in FlexiPage
---
---
None
---
None

SALTO-6840: Add a CV for unused facets in FlexiPage

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/filters/field_references.ts
packages/zendesk-adapter/src/filters/support_address.ts

Revert "SALTO-5481: add reference to support address"

---

packages/zendesk-adapter/src/filters/support_address.ts

SALTO-5481: fix build

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/filters/field_references.ts
packages/zendesk-adapter/src/filters/support_address.ts

add reference to support address v2
---
---
---

SALTO-5481: add reference to support address v2

---

packages/microsoft-security-adapter/config_doc.md

Self explanatory.
---
None
---
None

SALTO-7137: nit - fix MS config_doc

---

packages/zendesk-adapter/src/filters/webhook.ts
packages/zendesk-adapter/test/filters/webhook.test.ts

add references to endpoint webhook
---
---
zendesk:
* add reference to brand subdomain from webhook endpoint field
---
zendesk:
* add reference to brand subdomain from webhook endpoint field

SALTO-7331: add references to endpoint webhook

---

packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/filters/field_references.ts

This reverts commit bb728a4c5a2a2f13f56ca733be0b1ea34a09dcf6.
---
---
---

Revert "SALTO-5481: add reference to support address v2 (#7130)"

---

packages/local-workspace/src/workspace.ts
packages/local-workspace/test/workspace.test.ts

Allow callers of loadLocalWorkspace to supply a custom workspaceConfig - this will allow the caller to specify the localStorage path.
Also don't allow looking up the baseDir, and use only the supplied path.
There are still two distinct options, as we still rely on salto.config to exist in the top level. 
---
---
---

SALTO-7344: Support custom workspaceConfig & prevent dir traversal in loadLocalWorkspace

---

packages/workspace/src/flags.ts
packages/workspace/src/workspace/static_files/source.ts

Not needed anymore
---
---
None
---
None

SALTO-7323 revert added logs to static files source

---

packages/okta-adapter/e2e_test/adapter.test.ts

SALTO-7359: Unskip okta e2e

---

packages/zendesk-adapter/jest.config.js
packages/zendesk-adapter/src/adapter.ts
packages/zendesk-adapter/src/config.ts

change default for useGuideNewInfra
---
---
---

SALTO-7371: change default for useGuideNewInfra

---

packages/zendesk-adapter-e2e/e2e_test/e2e_instance_generator.ts

add trigger to zendesk e2e
---
---
---

SALTO-7370: add trigger to zendesk e2e

---

salto.code-workspace

SALTO-7125: Add new packages to vs code workspace 

---

packages/salesforce-adapter/config_doc.md
packages/salesforce-adapter/src/change_validator.ts
packages/salesforce-adapter/src/change_validators/unique_flow_element_name.ts
packages/salesforce-adapter/src/types.ts
packages/salesforce-adapter/test/change_validators/unique_flow_element_name.test.ts

SALTO-7199: Unique FlowElement Name CV
---
---
None
---
None

SALTO-7199: Unique FlowElement Name CV

---

packages/salesforce-adapter/src/filters/custom_objects_to_object_type.ts
packages/salesforce-adapter/src/filters/utils.ts
packages/salesforce-adapter/test/filters/custom_metadata_to_object_type.test.ts
packages/salesforce-adapter/test/filters/custom_objects_to_object_type.test.ts

added description to annotations of custom metadata
---
added description to annotations of custom metadata
env diff: https://github.com/rotem531/salto-tests/commit/f08fd6d3ae1ebb2d394e16fb5445b83f9f42bd2b
---
_Salesforce_:
- added description to annotations of custom metadata
---
none

SALTO-3859 - salesforce - added description to annotations of custom metadata

---

packages/zendesk-adapter/jest.config.js
packages/zendesk-adapter/src/filters/webhook.ts
packages/zendesk-adapter/test/filters/webhook.test.ts

webhook url to look only at subdomain
---
---
---

SALTO-7390: webhook url to look only at subdomain

---

packages/jira-adapter/src/dependency_changers/forms.ts

SALTO-7389 Jira small fixes
---
---
None
---
None

SALTO-7389 Jira small fixes

---

packages/jira-adapter/e2e_test/adapter.test.ts

Disable Jira E2E

---

packages/adapter-utils/src/collisions.ts

_add back id collision logs_
---
---
_None_
---
_None_

SALTO-7422: add back id collision logs

---

packages/zuora-billing-adapter/e2e_test/adapter.ts
packages/zuora-billing-adapter/src/adapter.ts
packages/zuora-billing-adapter/src/auth.ts
packages/zuora-billing-adapter/src/client/connection.ts
packages/zuora-billing-adapter/src/config.ts
packages/zuora-billing-adapter/src/filter.ts
packages/zuora-billing-adapter/src/filters/object_def_split.ts

SALTO-7363: Removing unused Zuora Billing adapter exports

---

.circleci/config_template.yml

SALTO-7441: Do not fail the unit test job if coveralls upload fails

---

tsconfig.base.json

SALTO-7467: Use updated build target in tsconfig

---

packages/salesforce-adapter/src/change_validators/flow_referenced_elements.ts
packages/salesforce-adapter/src/constants.ts
packages/salesforce-adapter/test/change_validators/flow_referenced_elements.test.ts

SALTO-7439: (Bugfix) False positive missing flow elements
---
None
---
None

SALTO-7439: (Bugfix) False positive missing flow elements

---

packages/salesforce-adapter/src/transformers/xml_transformer.ts

Adding some logs to help debug an issue with building deploy packages.
---
---
None.
---
None.

SALTO-7475: Adding logs

---

packages/jira-adapter/src/filters/field_configuration/field_configuration.ts
packages/jira-adapter/test/filters/field_configuration/field_configuration.test.ts

In [here](https://github.com/salto-io/salto/blob/6c212414719b70fa737c702fa352b9a7d3646c49/packages/jira-adapter/src/filters/field_configuration/field_configuration.ts#L50) we set the fields field type to be `Map<List<jira.FieldConfigurationItem>>`, but it should actually be `Map<jira.FieldConfigurationItem>`, like the field’s value ([here](https://github.com/salto-io/salto/blob/6c212414719b70fa737c702fa352b9a7d3646c49/packages/jira-adapter/src/filters/field_configuration/replace_field_configuration_references.ts#L36)).
---
---
Jira Adapter:
- fix field type in `jira.FieldConfiguration`
---
None

SALTO-7492 fix field type in jira.FieldConfiguration

---

packages/netsuite-adapter/e2e_test/adapter.test.ts
packages/netsuite-adapter/src/adapter.ts
packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts

NS change features defaults in config

---

packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts
packages/netsuite-adapter/src/data_elements/types.ts
packages/netsuite-adapter/src/filters/workflow_account_specific_values.ts
packages/netsuite-adapter/test/elements_source_index.test.ts
packages/netsuite-adapter/test/filters/author_information/system_note.test.ts

SALTO-7207 add suiteQL tables for AVS resolving

---

packages/salesforce-adapter/test/adapter.creator.test.ts

We lose some coverage on the implementation of SALTO-7457 so picking up some coverage elsewhere to avoid reducing the threshold.
---
---
None.
---
None.

SALTO-7457: Adding coverage

---

packages/salesforce-adapter/src/change_validators/custom_applications.ts
packages/salesforce-adapter/test/change_validators/custom_applications.test.ts

SALTO-7479: (Bugfix) Fix false positives for customApplications CV
---
None
---
None

SALTO-7479: (Bugfix) Fix false positives for customApplications CV

---

packages/okta-adapter/src/change_validators/app_provisioning_addition.ts
packages/okta-adapter/src/change_validators/index.ts
packages/okta-adapter/src/filters/app_fetch.ts
packages/okta-adapter/src/user_config.ts
packages/okta-adapter/test/change_validators/app_provisioning_addition.test.ts

In this PR I added CV to prevent provisioning addition
---
---
* Users will not be able to deploy additions of provisioning field in application  
_
---
None

SALTO-7493: Add CV to prevent provisioning addition

---

packages/jira-adapter/src/filters/dashboard/gadget.ts
packages/jira-adapter/test/filters/dashboard/gadget.test.ts

---
---
- Remove null values from dashboard gadgets
---
- null values will be removed from dashboard gadgets on the next fetch

SALTO-7192: Remove null values from dashboard gadgets

---

packages/jira-adapter/src/filters/dashboard/gadget.ts

The previous commit broke the build.
---
---
None.
---
None.

SALTO-7192: Fixing build

---

knip.json
packages/jira-adapter/e2e_test/instances/field.ts

It's time.
---
---
None.
---
None.

SALTO-7363: Enabling knip unused exports rules

---

packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts

The `retryOnRetryableError` function should wrap a single query, but instead it wrapped all of the files queries together, so in case of an retryable error all of the queries ran again, even the successful queries.
---
---
None
---
None

Move files query retry wrapper
