- packages/netsuite-adapter/e2e_test/adapter.test.ts
- packages/netsuite-adapter/e2e_test/sdf_executor.ts
- packages/netsuite-adapter/package.json
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/adapter_creator.ts
- packages/netsuite-adapter/src/client/sdf_client.ts
- packages/netsuite-adapter/src/client/sdf_parser.ts
- packages/netsuite-adapter/src/filter.ts
- packages/netsuite-adapter/src/filters/add_instances_fetch_time.ts
- packages/netsuite-adapter/src/sdf_folder_loader.ts
- packages/netsuite-adapter/src/server_time.ts
- packages/netsuite-adapter/src/transformer.ts
- packages/netsuite-adapter/src/type_parsers/report_definition_parsing/parsed_report_definition.ts
- packages/netsuite-adapter/src/types.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/netsuite-adapter/test/client/sdf_client.test.ts
- packages/netsuite-adapter/test/client/sdf_parser.test.ts
- packages/netsuite-adapter/test/filters/add_instances_fetch_time.test.ts
- packages/netsuite-adapter/test/filters/author_information/system_note.test.ts
- packages/netsuite-adapter/test/sdf_folder_loader.test.ts
- packages/netsuite-adapter/test/types.test.ts
Support the `loadElementsFromFolder` API.
---
This PR contains several commits that can be reviewed separately:
commit a13f6426304749efa102a862448b3cbf353f3eef
SALTO-2428 add e2e test to NS loadElementsFromFolder
commit 85b083d873483751f73ae9c58588deefdf0446e6
SALTO-2428 add loadElementsFromFolder to netsuite adapter api
commit 6901a6cbc7cfb026b2fa9e47e4eebce3f93264eb
SALTO-2428 create add-instances-fetch-time filter
commit a2939db5a196c2298ee4e7533788137da72aeb6c
SALTO-2428 move SDF transformation code from adapter.ts to transformer.ts
commit 90ac26790d9cf814f2ae240faa4adcf052bf919d
SALTO-2428 added parseSdfProjectDir function
---
- Support the `loadElementsFromFolder` API
---
None
> SALTO-2428 SDF Folder Loader

- packages/jira-adapter/src/change_validators/account_id.ts
- packages/jira-adapter/test/change_validators/account_id.test.ts
add display names of missing users to the error message.
---
tested with cloud and dc
cloud has both values in this format id: "display name", ....
dc is not changed with just id.
---
jira adapter:
* add display name to user errors with visible id.
---
> SALTO-4011/add display name to error

- packages/okta-adapter/src/client/client.ts
- packages/okta-adapter/test/client/client.test.ts
Fix bug causing built in apps to disappear from fetch as they don't have AppUserSchema which caused 404 when trying to fetch those
---
- Fix a bug in built-in applications fetch
---
- Built-in Application will be added on the next fetch
> SALTO-4193: Suppress 404 on AppUserSchema

- packages/zendesk-adapter/src/change_validators/custom_statuses_enabled.ts
- packages/zendesk-adapter/src/filters/ticket_form.ts
- packages/zendesk-adapter/test/change_validators/custom_statuses_enabled.test.ts
…dator
The customStatusesEnabledValidator now shows a warning message when trying to change zendesk.ticket_form instances with `custom_statuses` specified in either `agent_conditions` or `end_user_conditions`.
---
---
ZenDesk adapter:
- Check that custom statuses are enabled when updating zendesk.ticket_form instances that include custom_statuses under agent_conditions or end_user_conditions.
---
None
> SALTO-3490: Add ticket form check to the custom statuses enabled validator

- packages/zendesk-adapter/src/filters/ticket_form.ts
- packages/zendesk-adapter/test/filters/ticket_form.test.ts
fix deployment in ticket_form when custom statuses are disabled
---
---
zendesk:
* fix bug where the deploy of a `ticket_form` with `custom_statuses` when  `custom_statuses` is disabled would delete all statuses in the form
---
None
> SALTO-4219: fix deployment in ticket_form when custom statuses are disabled

- packages/netsuite-adapter/package.json
---
Following #4412 
Turns out files in netsuite e2e import utils from the tests folder, so we need to include that in the files we publish to npm as well
---
_None_
---
_None_
> SALTO-4201: publish netsuite adapter test utils

- packages/okta-adapter/src/config.ts
Fix AppUserSchema idFields
---
Because we have one AppSchema to each app, elemID for `AppUserSchema` should depend on the parent app elemID.
Otherwise `AppUserSchema` instances of the same app would look as an addition and removal changes when comparing environments.
---
- Fix a bug causing non existing differences in `AppUserSchema` instances when comparing environments
---
- Element Ids for `AppUserSchema` instances will change
> SALTO-4241- Fix AppUserSchema idFields

- packages/workspace/src/parser/internal/native/lexer.ts
- packages/workspace/test/parser/parse.test.ts
In case that there is an escaped Unicode letter in a string content (e.g `\u0065`) the parsing fails with `Invalid string character`.
---
---
Workspace:
- Fix escaped Unicode letters parsing
---
None
> SALTO-4253 fix escaped unicode letters parsing

- packages/salesforce-adapter/src/client/client.ts
We've seen this error in both fetch and deploy. Per [Salesforce docs](https://help.salesforce.com/s/articleView?id=000387767&type=1) it can happen due to user interaction with Salesforce at the time of the fetch/deploy.
---
`requestWithRetry` seems to be used by both the fetch and the deploy flows. LMK if there's anywhere else I should check for this error to ensure fetch is covered.
---
Salesforce: Fetch and deploy operations will be retried if they receive an UNABLE_TO_LOCK_ROW error
---
N/A
> SALTO-3999 - Salesforce: add retry to fetch in case of UNABLE_TO_LOCK_ROW

- packages/adapter-api/src/adapter.ts
- packages/adapter-utils/src/filter.ts
- packages/adapter-utils/test/filter.test.ts
- packages/cli/src/commands/deploy.ts
- packages/cli/src/formatter.ts
- packages/cli/test/formatter.test.ts
- packages/core/src/core/deploy/deploy_actions.ts
- packages/core/test/api.test.ts
- packages/netsuite-adapter/src/client/client.ts
- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/custom_object_instances_deploy.ts
- packages/salesforce-adapter/src/metadata_deploy.ts
- packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
- packages/salesforce-adapter/test/custom_object_instances_deploy.test.ts
Alter the way we return errors from deployments, so that instead of returning one bulk error, we return multiple errors with their errors and ElemIDs (if relevant)
---
This is the beginnings of a PR to separate errors out in deployment. The way to look at this is as so:
commit 1: changes to core, adapter-api, and adapter-utils to allow this change
commit 2: Salesforce specific changes to make the adapter work
---
Core:
- Receive ElemIDs in deploy errors related to specific elements
- Change deploy errors from `Error` type to `SaltoError` or `SaltoElementError`
---
> Saas 6976 - Only allow deployment errors of type SaltoError or SaltoElementError

- packages/jira-adapter/e2e_test/instances/cloud/dashboard.ts
- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/filters/dashboard/gadget_properties.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/test/filters/dashboard/gadget_properties.test.ts
Change dashboard gadget properties to a list, since the keys there might cause syntax errors in the nacl
---
- Change dashboard gadget properties to a list, since the keys there might cause syntax errors in the nacl
---
- Properties in dashboard gadgets will be converted from maps to lists
> SALTO-4259: Change dashboard gadget properties to a list

- packages/core/src/core/deploy/deploy_actions.ts
---
Because of code beautification change in `deployOrValidate`, when calling dummy adapter `this` might be undefined.
---
---
> SAAS-6976 fix dummy adapter deploy due to code change in deployOrValidate

- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
Change Json encoding
---
None
---
Now we support Json files in file cabinet. fetch, deploy and preview
---
None
> SALTO-4132 Support JSON files in file-cabinet

- packages/adapter-api/src/adapter.ts
- packages/cli/src/commands/deploy.ts
- packages/cli/test/commands/deploy.test.ts
- packages/cli/test/formatter.test.ts
- packages/cli/test/mocks.ts
- packages/jira-adapter/src/change_validators/masking.ts
- packages/jira-adapter/src/change_validators/workflow_scheme_migration.ts
- packages/jira-adapter/test/change_validators/masking.test.ts
- packages/netsuite-adapter/src/change_validators/currency_undeployable_fields.ts
- packages/okta-adapter/src/change_validators/app_integration_setup.ts
- packages/okta-adapter/test/change_validators/app_integration_setup.test.ts
- packages/salesforce-adapter/src/change_validators/cpq_trigger.ts
- packages/salesforce-adapter/src/change_validators/flows.ts
- packages/zendesk-adapter/src/change_validators/target.ts
- packages/zendesk-adapter/src/change_validators/webhook.ts
The post-deploy action messages for the salesforce adapter should be shown if the change failed but the other ones it should not.
To deal with this I've added a flag named `showOnFailure` to the `DeployAction` type (by creating a subtype called `PostDeployAction`).
When showing the post deploy messages I filter out ChangeError instances of failed changes where the `showOnFailure` flag is true.
Once this is merged the next step is to handle this flag in the SASS part.
---
---
CLI:
- Post-deploy actions of failed changes will no longer be shown to the user (except for Salesforce CPQ failures).
---
None
> SALTO-3817: Add postAction.showOnFailure flag

- packages/jira-adapter/e2e_test/instances/cloud/workflow.ts
- packages/jira-adapter/e2e_test/instances/datacenter/workflow.ts
- packages/jira-adapter/src/filters/workflow/types.ts
- packages/jira-adapter/src/filters/workflow/workflow_diagrams.ts
- packages/jira-adapter/test/filters/workflow/workflow_deploy_filter.test.ts
- packages/jira-adapter/test/filters/workflow/workflow_diagrams.test.ts
_add workflow diagram transition initial source_
---
I added a new field to workflows that is called `diagramInitialEntry`
---
Jira Adapter:
* fix a bug with workflow diagram initial transition source 
---
Jira Adapter:
* workflows have a new field called `diagramInitialEntry` that contains the location coordinates of the initial transition source in the workflow diagram
> SALTO-4252: add workflow diagram transition initial source

- packages/jira-adapter/src/dependency_changers/workflow.ts
- packages/jira-adapter/test/dependency_changers/workflow.test.ts
Fixed 'getFullName' of undefined when a string value in a workflow scheme was not converted to a reference
---
- Fixed 'getFullName' of undefined when a string value in a workflow scheme was not converted to a reference
---
None
> INCIDENT-5618: fixed 'getFullName' of undefined when missing a reference

- packages/workspace/src/validator.ts
- packages/workspace/test/validator.test.ts
Limit length of value text in validation error messages to 20 chars
Replace the value field in the error object with this truncated value
---
None
---
Avoid long error messages of validation errors.
Change the message to include only the first 20 chars of the value
---
None
> SALTO-4265 Limit length of value text in validation errors

- packages/netsuite-adapter/src/filters/consistent_values.ts
- packages/netsuite-adapter/test/filters/consistent_values.test.ts
_Add TransferOrder to the in-consist values in the transaction form_
---
_There are some fields with in-consist values, we choose one of the values to be our default between the in-consistent ones to hide the changes from the user._
---
_None_
---
_None_
> SALTO-4109 Add TransferOrder to the in-consist values in the transaction form

- packages/core/src/core/plan/change_validators/incoming_unresolved_references.ts
_Clarify unresolved reference validator message_
---
---
_Clarify unresolved reference validator message_
---
> SALTO-3534 Clarify unresolved reference validator message

- packages/workspace/src/validator.ts
SALTO-4265 Limit length of value text in validation errors - cosmetic changes
---
None
---
None
---
None
> SALTO-4265 Limit length of value text in validation errors - cosmetic changes

- Dockerfile
- README.md
No dependencies but docker ofc.
Updates https://salto-io.atlassian.net/browse/SALTO-4286
---
---
There's now a possibility to run the CLI using a docker image
---
None
> SALTO-4286: Add dockerfile for running cli without any dependencies

- packages/salesforce-adapter/src/config_creator.ts
Changed the default config file of CPQ to rely on SF IDs instead of value-based IDs.
---
Although I've changed the default config for CPQ, I did not update any documentations. The documentations should be updated as part of [SALTO-4130](https://salto-io.atlassian.net/browse/SALTO-4130) after we officially support self-serve CPQ.
---
- Changed the default config file of CPQ to rely on SF IDs instead of value-based IDs.
---
_None_
[SALTO-4130]: https://salto-io.atlassian.net/browse/SALTO-4130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SAAS-7196: CPQ config based on Salesforce Ids

- packages/salesforce-adapter/src/filters/custom_objects_instances.ts
- packages/salesforce-adapter/src/filters/custom_settings_filter.ts
- packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
Aliases to Data Records in Salesforce are available by default.
---
_None_
---
_None_
---
Salesforce:
- Existing Data Records `nacls` will have a new `_alias` annotation.
> SALTO-4285: Open Aliases to Salesforce Data Records

- packages/netsuite-adapter/src/group_changes.ts
- packages/netsuite-adapter/test/group_changes.test.ts
There was a bug in `getChangesChunks` that didn't create changes chunks based on the dependencies correctly.
In addition, we didn't create changes chunks for data instances deletions.
---
---
- Fix group changes chunks for data instances additions/deletions
---
None
> Fix group changes chunks for data instances additions/deletions

- packages/salesforce-adapter/src/metadata_deploy.ts
Only return `SaltoError`s on metadata deploy component failures
---
---
---
> SALTO-4288 do not crash on inability to get full name for element ID and log all failures

- packages/adapter-components/src/client/http_client.ts
- packages/adapter-components/test/client/http_client.test.ts
fix http_connection to extract retry-after header correctly
---
---
None
---
None
> SALTO-4300: fix http connection to extract retry-after header correctly

- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/constants.ts
- packages/salesforce-adapter/src/filters/centralize_tracking_info.ts
- packages/salesforce-adapter/test/filters/centralize_tracking_info.test.ts
Undo the revert and add logging to catch the case where we don't get the 'enableHistory' annotation even though history tracking is enabled.
---
Following discussion with @amitgoldarb , we believe the issue is not worth reverting the change over.
Original PR is at https://github.com/salto-io/salto/pull/4400
---
Improved modelling of History and Feed History Tracking on Standard and Custom Objects.
---
The annotation historyTrackedFields will be added to existing custom objects with history tracking enabled.
The annotation feedHistoryTrackedFields will be added to existing custom objects with feed history tracking enabled.
The annotation trackHistory will be removed from all custom fields
The annotation …
> SALTO-3751 - Salesforce: re-enable history tracking

- packages/zendesk-adapter/src/filters/field_references.ts
invalid resolve prevents deletion
---
---
zendesk:
* fix error when deleting a `dynamic_content_item_variant` with missing locale 
---
None
> SALTO-4314: invalid resolve prevents deletion

- packages/workspace/src/parser/internal/native/errors.ts
- packages/workspace/src/parser/internal/native/lexer.ts
- packages/workspace/src/parser/internal/native/parse.ts
- packages/workspace/test/parser/errors.test.ts
- packages/workspace/test/parser/parse.test.ts
- packages/workspace/test/utils.ts
_Currently when the parser crashes with an unexpected error, that error is logged, but the parse result doesn’t contain any error so the rest of the code doesn’t know that something failed._
---
---
_Workspace_
* Update the parse result with caught errors
---
> SALTO-4254 Return a lexer error token and add a better catch

- packages/workspace/src/parser/internal/native/lexer.ts
- packages/workspace/test/parser/parse.test.ts
_Add support for unicode line terminator parsing_
---
* Javascript has 2 unicode line terminators (\u2028 and \u2029)
---
_Core_
* Unicode line terminators will no longer throw parse errors.
---
> SALTO-4278 Add parser support for unicode newline

- packages/adapter-components/src/client/http_client.ts
Only include needed details in `HTTPError`s.
---
None
---
None
> SALTO-4325 reduce details in HTTPError

- packages/workspace/src/workspace/reference_indexes.ts
- packages/workspace/src/workspace/workspace.ts
Returned the namespace of referenceTargets to the orignal
---
Changing the name was a mistake and a bug that should be fixed
---
None
---
None
> SAAS-7820 - fixed naming of namespace

- packages/jira-adapter/e2e_test/instances/index.ts
Deploying groups now returns 500, looks like a jira bug.
For now to unblock the CI I removed it from the e2e
---
None
---
None
> Removed group from e2e due to Jira bug

- packages/adapter-components/src/elements/ducktype/transformer.ts
- packages/adapter-components/src/elements/swagger/instance_elements.ts
- packages/adapter-components/test/elements/swagger/instance_elements.test.ts
- packages/okta-adapter/e2e_test/adapter.test.ts
Get fetch warning for 401
---
Fix some inconsistency in handling 401 on simple adapters, the user will now get a fetch warning
---
- On 401 error, the user will get fetch warning instead of fetch failure
- On 401 error, the user will get fetch warning
- On 401 error, the user will get fetch warning instead of fetch failure
_Workato adapter_:
- On 401 error, the user will get fetch warning instead of fetch failure
_Zuora adapter_:
- On 401 error, the user will get fetch warning
_Stripe adapter_:
- On 401 error, the user will get fetch warning
---
None
> SALTO-5821: Get fetch warning for 401

- packages/adapter-components/src/client/http_client.ts
- packages/adapter-components/test/client/http_client.test.ts
- packages/okta-adapter/test/client/client.test.ts
- packages/zendesk-adapter/test/change_validators/organization_existence.test.ts
- packages/zendesk-adapter/test/client/client.test.ts
Trace the HTTP responses even when there are HTTP errors
---
None
---
None
> SALTO-4192 log HTTP response on errors as well

- packages/jira-adapter/src/constants.ts
- packages/jira-adapter/src/filters/share_permission.ts
- packages/jira-adapter/test/filters/share_permission.test.ts
Improved the performance of Share Permission Filter
---
The existing filter was one of the most time-consuming.
There was no need for a transformValue, the share permissions exist on two types and into static locations
---
Jira Adatper:
* Improved fetch performance
---
None
> SALTO-4202: Improve SharePermissions filter's performance

- packages/jira-adapter/e2e_test/instances/index.ts
This reverts commit 5e5826df45a4924cd47edbfce60c0c956838c112.
We removed the group from the e2e due to a Jira bug, now it seems to work
---
None
---
None
> SALTO-4333: Added group back to e2e

- packages/adapter-api/src/values.ts
- packages/adapter-api/test/values.test.ts
- packages/core/src/api.ts
- packages/core/src/core/plan/dependency/reference_dependency.ts
- packages/core/src/core/plan/plan.ts
- packages/core/test/core/plan/plan.test.ts
- packages/okta-adapter/src/change_validators/group_schema_modify_base_fields.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
update static file path.
until now, static files whose path changed but content didn't would remain in their old location, after this PR,  static files whose path changed will be created in their new location and the old files will be deleted.
---
---
core:
* static file path changes will be referred to as a change in fetch
---
* some static files might move location
> SALTO-4301: update static file path

- packages/jira-adapter/e2e_test/instances/index.ts
Removing group from e2e until the Jira related incident will be over
---
---
---
> SALTO-4333: Removed group from e2e due to Jira bug

- packages/adapter-api/test/values.test.ts
> Revert "SALTO-4301: add test for normalize path in static file"

- packages/core/src/core/deploy/deploy_actions.ts
- packages/core/test/api.test.ts
Only add element IDs of elements that failed to deploy to `Error`s.
---
When a deploy returns errors of type `Error`, extract errors into `SaltoElementError` only for elements that were not successfully deployed (are not in `appliedChanges`)
---
Core:
- On partial deploy failures, only add element IDs of elements that failed to deploy to errors.
---
> SAAS-6976 only add errors to elements that failed to apply

- packages/adapter-components/src/add_alias.ts
- packages/adapter-components/test/add_alias.test.ts
- packages/jira-adapter/src/filters/add_alias.ts
- packages/zendesk-adapter/src/filters/add_alias.ts
Today the add-alias utility in adapter-components supports only instances. It should support adding aliases to types too, because of the custom record types in netsuite.
---
---
Adapter Components:
- Support adding alias to ObjectTypes
---
None
> SALTO-4338 Support adding alias to ObjectTypes

- packages/jira-adapter/src/filters/automation/automation_deployment.ts
- packages/jira-adapter/src/filters/automation/automation_structure.ts
- packages/jira-adapter/test/filters/automation/automation_structure.test.ts
Atlassian recently changed the structure of automation scopes, removing the `projects` object. It caused all new automation to be deployed as Global
---
Jira Adapter:
* Fixed a bug causing all automation to be deployed with global scope
---
Jira Adapter:
* Recently created automations with a non-global scope will be added scope in the projects field
> SALTO-4275: Fix Automation Scopes

- packages/okta-adapter/src/change_validators/enabled_authenticators.ts
Don't log errors when there are no authenticator changes
---
---
None
---
None
> SALTO-4352: Don't log errors when there are no authenticator changes

- packages/adapter-api/src/adapter.ts
- packages/core/src/api.ts
- packages/core/src/core/fetch.ts
- packages/netsuite-adapter/e2e_test/adapter.test.ts
- packages/netsuite-adapter/src/adapter_creator.ts
- packages/netsuite-adapter/src/config.ts
- packages/netsuite-adapter/src/sdf_folder_loader.ts
- packages/netsuite-adapter/test/sdf_folder_loader.test.ts
- packages/salesforce-adapter/src/sfdx_parser/sfdx_parser.ts
- packages/salesforce-adapter/test/sfdx_parser/sfdx_parser.test.ts
The `loadElementsFromFolder` should get the adapter config in order to know the user’s configuration that effects the nacls (like `fieldsToOmit`). Also we should pass the `ElemIdGetter` function.
---
---
Core:
- Pass adapter operations context to loadElementsFromFolder
---
None
> SALTO-4167 pass adapter operations context to loadElementsFromFolder

- packages/adapter-components/src/client/http_client.ts
Added logs when getting a response from client
---
This is to investigate an incident when it looks like we would get stuck before printing `Full HTTP response`
---
None
---
None
> INCIDENT-5846: added logs when getting response from client

- packages/jira-adapter/src/change_validators/dashboard_gadgets.ts
- packages/jira-adapter/test/change_validators/dashboard_gadgets.test.ts
Changed dashboard gadget back to ReferenceExpression
---
---
None
---
None
> SALTO-4038 Changed dashboard gadget back to ReferenceExpression

- packages/jira-adapter/src/filters/workflow/workflow_modification_filter.ts
- packages/jira-adapter/test/filters/workflow/workflow_modification_filter.test.ts
Improved Deployment Performace
---
The deployment performance of any instance was impacted by the workflow modification filter, as it called elementSource.list() for each change, regardless of the relevance. Also, those calls lead to many calls on RocksDB which is single-threaded.
We now call the list only for relevant changes, and cache the result
---
Jira Adapter:
* improve deployment performance when deploying many instances
---
None
> SALTO-4236: Jira Deployment performance

- packages/salesforce-adapter/src/filters/custom_object_instances_references.ts
- packages/salesforce-adapter/src/transformers/transformer.ts
- packages/salesforce-adapter/test/filters/custom_object_instances_references.test.ts
For all the **System Fields** we overridden their `createable | updatable` annotation values to false with the values returned from the API.
---
Workspace Diff: https://github.com/salto-io/tamir-sf/commit/af0b2b6743d8ada7491f7c4378ab8ac99ca4d045
---
- Correct createable and updateable annotation values for Salesforce System Fields.
---
Salesforce:
- Changes to the values of the annotations **createable** and **updateable** of System Fields in existing nacls.
> SALTO-4263: Do not override properties for system fields

- packages/salesforce-adapter/config_doc.md
- packages/salesforce-adapter/src/filters/formula_deps.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/filters/formula_deps.test.ts
The feature is currently behind a default-disabled config flag. Eliminate the flag and enable the feature by default.
---
[WS Diff](https://github.com/salto-io/tomsellek-sf/pull/3)
[WS Diff without self-references](https://github.com/salto-io/tomsellek-sf/pull/7) (cf. https://github.com/salto-io/salto/pull/4196)
---
Salesforce: more dependencies are now extracted from formula fields
---
N/A
> SALTO-1730 - Salesforce: Enable formula parsing by default

- packages/salesforce-adapter/config_doc.md
- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/types.ts
Add PermissionSet and CustomObject to the list of types we fetch using the retrieve API.
---
We want to eventually use the retrieve API for all types because it provides better data, behaves better in regards to rate limits and is more similar to SFDX. As part of our work to improve our support for Salesforce Profiles, we need to use retrieve to fetch these two types.
[WS Diff](https://github.com/salto-io/tomsellek-sf/pull/9)
---
Salesforce: Use a different API to fetch custom objects.
---
Salesforce: Changing the API used for fetching custom objects will result in several changes across all custom object types, including additional data as well as changes to existing fields.
> SALTO-4318 - Salesforce: use retrieve API for PermissionSet and CustomObject

- packages/okta-adapter/src/client/client.ts
- packages/okta-adapter/test/client/client.test.ts
Suppress 410 https errors
---
Okta returns 410 for deprecated endpoints, this shouldn't fail fetch
Didn't excluded the type that caused it because in our accounts it works.
---
None
---
None
> SALTO-4370: Don't fail fetch for 410 errors

- packages/zendesk-adapter/e2e_test/adapter.test.ts
- packages/zendesk-adapter/src/filters/article/article.ts
- packages/zendesk-adapter/src/filters/article/utils.ts
- packages/zendesk-adapter/src/filters/guide_translation.ts
- packages/zendesk-adapter/test/filters/article/article.test.ts
- packages/zendesk-adapter/test/filters/guide_translation.test.ts
fix bug that prevented the deploy of two articles that reference each other
---
---
zendesk:
* fix bug that prevented the deploy of two articles that reference each other
---
None
> SALTO-4319: cannot create two articles that reference each other

- packages/adapter-api/src/values.ts
- packages/adapter-api/test/values.test.ts
- packages/core/src/api.ts
- packages/core/src/core/plan/dependency/reference_dependency.ts
- packages/core/src/core/plan/plan.ts
- packages/core/test/core/plan/plan.test.ts
- packages/okta-adapter/src/change_validators/group_schema_modify_base_fields.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
update static file path.
until now, static files whose path changed but content didn't would remain in their old location, after this PR, static files whose path changed will be created in their new location and the old files will be deleted.
---
---
core:
* static file path changes will be referred to as a change in fetch
---
* some static files might move location
> SALTO-4301 update static file path

- packages/zendesk-adapter/src/filters/guide_locale.ts
fix logs for missing guide_language_settings
---
---
---
> SALTO-4392: fix logs for missing guide_language_settings

- packages/salesforce-adapter/src/filters/formula_deps.ts
Invalid references currently generate error-level logs, but we expect many invalid references because we don’t handle custom relations yet.
---
N/A
---
N/A
---
N/A
> SALTO-4390 - Salesforce: reduce severity of logging in formula_deps

- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/filters/organization_wide_sharing_defaults.ts
We only really care about account sharing settings, and some fields of OrganizationSettings are noisy on fetches (change on every fetch) or across envs.
---
N/A
---
Salesforce: remove some fields of OrganizationSettings
---
N/A
> SALTO-4105 - Salesforce: Discard multienv-unfriendly fields of OrganizationSettings

- packages/jira-adapter/src/filters/script_runner/workflow/workflow_lists_parsing.ts
- packages/jira-adapter/test/filters/script_runner/workflow_link_type.test.ts
- packages/jira-adapter/test/filters/script_runner/workflow_mail_lists.test.ts
_Fixed a bug with scriptrunner. FIELD_LINK_TYPE was assumed to always be of format 'type direction' but direction can be omitted
---
_According to adaptavist the direction can be omitted, in which case it is considered outwards.
I added robustness- if the string contains only one part after parsing use that part as the id.
I also added a test to reveal branch coverage and make sure I kept it_
---
Jira Adapter:
* Fixed a bug in scriptRunner, sometimes FIELD_LINK_TYPE was not parsed corretly
---
None
> SALTO-4260: Fix link type string error

- packages/salesforce-adapter/src/transformers/transformer.ts
- packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
Fixed data deployment bug due to regression in changes to Salesforce System Fields annotations.
---
- Fixed a bug when attempting to deploy new Data Record instances.
---
_None_
> SALTO-4397: Salesforce Additions Data Deployment Bugfix

- packages/lowerdash/src/chunks.ts
- packages/lowerdash/test/chunks.test.ts
This function is like weightedChunks but attempts to split the chunks into roughly equal sizes.
---
This can be useful as part of SAAS-8289
---
_None_
---
_None_
> SALTO-4407: Add chunkByEvenly function to lowerdash

- packages/okta-adapter/src/config.ts
- packages/okta-adapter/src/filters/app_logo.ts
- packages/okta-adapter/src/filters/brand_theme_files.ts
- packages/okta-adapter/src/filters/delete_fields.ts
- packages/okta-adapter/src/logo.ts
- packages/okta-adapter/src/reference_mapping.ts
- packages/okta-adapter/test/filters/brand_theme_files.test.ts
- packages/okta-adapter/test/logo.test.ts
Okta made a change and they now support more than one brand per org
---
Okta now supports defining more than one brand per org.
This means that on dependent types are no longer singletons.
Also, they added some references to the API response of `Domain` and `Brand`
(Still missing one more ref that I need to resolve)
---
- Support multibrand customizations
- Support fetch of 'EmailDomain' instances
---
- Changes to `Brand`, `BrandTheme`, `BrandLogo` and `Domain` instances due to recent changes in Okta
- 'EmailDomain' instances will be added
> SALTO-4396: Support multi brands in Okta

- packages/jira-adapter/src/reference_mapping.ts
_Fixed a bug that prevented the deployment of a workflow if there is a workflow scheme with a reference to it and a missing reference_
---
Other solutions that I could think of were too complicated.
The best solution IMO remains to change the way we deploy workflow modifications
---
Jira Adapter: 
* Fixed a bug that prevented workflow modification deployment in some cases
---
None
> SALTO-4417: Fix Workflow Deployment bug

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/filters/script_runner/workflow/empty_account_ids.ts
- packages/jira-adapter/src/filters/script_runner/workflow/workflow_cloud.ts
- packages/jira-adapter/src/filters/workflow/types.ts
- packages/jira-adapter/test/filters/script_runner/empty_account_ids.test.ts
_Removed empty accountIds to avoid errors during deployment_
---
_Not adding noise reduction as we do not have customers with enabled scriptrunner, except maybe Convex_
---
Jira Adapter:
* Fixed a bug in scriptRunner that prevented deployment of notification post functions without users
---
None
> SALTO-4266: delete empty accountIds in scriptRunner

- packages/salesforce-adapter/src/change_validators/unknown_users.ts
@pgonzaleznetwork noticed a few more fields we can validate. So let's validate them.
---
---
Salesforce: Additional fields are now validated for unknown users
---
N/A
> SALTO-4408 - Salesforce: Add more types to unknown_users change validator

- packages/jira-adapter/src/filters/workflow/types.ts
- packages/jira-adapter/src/filters/workflow/workflow_diagrams.ts
- packages/jira-adapter/test/filters/workflow/workflow_deploy_filter.test.ts
- packages/jira-adapter/test/filters/workflow/workflow_diagrams.test.ts
_add global looped transition location to workflow diagrams_
---
the addition will add diagramGlobalLoopedTransition to workflows
---
Jira Adapter:
* add support in global looped transition  in Workflow's diagram 
---
Jira Adapter:
* workflows will have a new field called  `diagramGlobalLoopedTransition` that represents a global transition location from any status to itself.
> SALTO-4420: add global looped transition to workflow diagrams - Jira

- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts
- packages/netsuite-adapter/test/client/suiteapp_client/suiteapp_file_cabinet.test.ts
_skip querying bundleable if SuiteBundles feature is disabled_
---
_None_
---
* If the SuiteBundles feature is disabled skip querying the bundleable field
---
_None_
> SALTO-4340: skip querying bundleable if SuiteBundles feature is disabled

- packages/core/src/local-workspace/workspace.ts
- packages/workspace/src/workspace/workspace.ts
This issue has to do with way too many remote maps being opened. We don't know why, yet. Hopefully, adding some logs will point us in the right direction.
---
---
N/A
---
N/A
> SAAS-7513 - Add some logs to workspace state initialization

- packages/zendesk-adapter/src/filters/audit_logs.ts
- packages/zendesk-adapter/test/filters/audit_logs.test.ts
add debug logs for audit log filter
---
---
---
> SALTO-4422: add debug logs for audit log filter

- packages/zendesk-adapter/src/change_validators/feature_activation.ts
- packages/zendesk-adapter/test/change_validators/feature_activation.test.ts
Some changes according to [CR](https://github.com/salto-io/salto/pull/4536#discussion_r1242136160) 
---
None
---
None
---
None
> SALTO-4403 - Warn the user on activation of a feature - small changes

- packages/salesforce-adapter/src/fetch.ts
Changed retrieve visible error message to include the **errorMessage** property that wasn't previously defined.
---
_None_
---
_None_
> SALTO-4431: Changed retrieve visible error message

- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/article/article.ts
- packages/zendesk-adapter/test/filters/article/article.test.ts
write workaround to a zendesk API limitation that inline article attachments are not deleted properly
---
---
zendesk:
* add workaround to a zendesk API limitation that inline article attachments are not deleted properly
---
zendesk:
* Certain attachments may be deleted. Previously, these deleted attachments continued to appear in Salto, despite being removed from the Zendesk UI due to zendesk API limitation. This issue is now fixed by adding a workaround.
> SALTO-4294: write workaround to a zendesk API limitation that inline article attachments are not deleted properly

- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
Propagate the `calcSourceMap` parameter to the callers of parseNaclFile and set the appropriate value
---
---
N/A
---
N/A
> SALTO-4297 - Only create source map when required

- packages/salesforce-adapter/src/filters/field_references.ts
- packages/salesforce-adapter/src/transformers/reference_mapping.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/filters/field_references.test.ts
Fetching profiles takes a very long time. One part of that time is resolving references on the many, many fields that each profile has (basically the number of fields in a single profile = O(number of fields in all custom objects)). 
So let's not resolve references in profiles by default, unless the user explicitly asks us to.
---
N/A
---
Salesforce: references will no longer be generated from profile fields
---
Salesforce: References in fields of profiles will be replaced with the field's original content.
> SALTO-4402 - Salesforce: Adapter config to control profile references

- packages/logging/README.md
- packages/logging/jest.config.js
- packages/logging/src/internal/config.ts
- packages/logging/src/internal/env.ts
- packages/logging/src/internal/log-tags.ts
- packages/logging/src/internal/pino.ts
- packages/logging/test/internal/env.test.ts
- packages/logging/test/internal/log-tags.test.ts
- packages/logging/test/internal/pino_logger.test.ts
Added maxLogTags config to logger
---
There have been a few documented cases of crashes due to a large amount of logTags being logged.
---
Stability fix to our logger.
---
None.
> SALTO-3702 - Added maxLogTags config option to logger

- packages/zendesk-adapter/src/filters/article/article.ts
- packages/zendesk-adapter/test/filters/article/article.test.ts
deploy article attachments in chunks of 20
---
---
zendesk:
* fix bug where deployment of an article with more than 20 attachments did not work
---
None
> SALTO-4415: deploy article attachments in chunks of 20

- packages/netsuite-adapter/src/filters/service_urls.ts
- packages/netsuite-adapter/src/service_url/constant_urls.ts
- packages/netsuite-adapter/test/service_url/constant_urls.test.ts
_constant urls will be added to InstanceElements and not only ObjectTypes_
---
_None_
---
* constant urls will be added to instances and not only ObjectTypes
---
_None_
> SALTO-3380 - fix open in app

- packages/adapter-components/src/client/index.ts
- packages/adapter-components/src/client/pagination/pagination.ts
- packages/adapter-components/test/client/pagination.test.ts
- packages/jira-adapter/src/client/pagination.ts
_Due to an internal jira bug temporary fix to allow fetching all statuses_
---
_The pagination function and its tests were restored completely from a previous version of the file, they are not new_
---
Jira Adapter: Fixed a bug that prevented fetching more than 200 statuses
---
None
> SALTO-4451: Statuses pagination bug

- packages/salesforce-adapter/src/filters/field_references.ts
- packages/salesforce-adapter/src/transformers/reference_mapping.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/filters/field_references.test.ts
Re-introduce the change from SALTO-4402 (https://github.com/salto-io/salto/pull/4537), but make them disabled by default.
From original PR: Fetching profiles takes a very long time. One part of that time is resolving references on the many, many fields that each profile has (basically the number of fields in a single profile = O(number of fields in all custom objects)).
So let's not resolve references in profiles by default, unless the user explicitly asks us to.
---
---
Salesforce: add an adapter fetch configuration that controls reference generation for profiles
---
N/A
> SALTO-4402 - undo revert and disable by default

- packages/netsuite-adapter/e2e_test/adapter.test.ts
- packages/netsuite-adapter/e2e_test/sdf_executor.ts
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/client/sdf_parser.ts
- packages/netsuite-adapter/src/client/types.ts
- packages/netsuite-adapter/src/constants.ts
- packages/netsuite-adapter/src/sdf_folder_loader.ts
- packages/netsuite-adapter/src/transformer.ts
- packages/netsuite-adapter/src/types/file_cabinet_types.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/netsuite-adapter/test/client/mocks.ts
- packages/netsuite-adapter/test/client/sdf_client.test.ts
- packages/netsuite-adapter/test/client/sdf_parser.test.ts
- packages/netsuite-adapter/test/transformer.test.ts
Today we need all files&folders in the SDF Project’s “FileCabinet” directory to have their metadata xmls in the .attributes folder. For SDF, it is supported to deploy a file without it’s metadata xml - if the file already exists in the account only its content is updated, and if it is a new file then it gets the default metadata (non checkbox is marked, no description, etc).
---
---
- Support loading files without their attributes in SDF integration
---
None
> SALTO-4227 Support loading files without their attributes in SDF integration

- packages/adapter-components/src/add_alias.ts
- packages/netsuite-adapter/e2e_test/adapter.test.ts
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/change_validators/immutable_changes.ts
- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
- packages/netsuite-adapter/src/config.ts
- packages/netsuite-adapter/src/data_elements/multi_fields_identifiers.ts
- packages/netsuite-adapter/src/data_elements/types.ts
- packages/netsuite-adapter/src/filters/add_alias.ts
- packages/netsuite-adapter/src/query.ts
- packages/netsuite-adapter/src/types.ts
- packages/netsuite-adapter/src/types/configuration_types.ts
- packages/netsuite-adapter/test/filters/add_alias.test.ts
Can be enabled with `netsuite { fetch = { addAlias = true } }` 
---
---
- Add alias annotation to all elements.
---
None
> SALTO-3740 Add alias annotation to netsuite elements

- packages/jira-adapter/src/change_validators/field_contexts/field_contexts.ts
- packages/jira-adapter/src/change_validators/field_contexts/second_global_context.ts
- packages/jira-adapter/src/change_validators/index.ts
- packages/jira-adapter/test/change_validators/field_contexts/second_global_context.test.ts
_add second global context change validator_
---
Jira Adapter:
* add validation that prevents the user from adding more than one global context to custom fields
---
_None_
> SALTO-3233: add second global context change validator - Jira

- packages/zendesk-adapter/src/change_validator.ts
- packages/zendesk-adapter/src/change_validators/index.ts
- packages/zendesk-adapter/src/change_validators/standard_fields.ts
- packages/zendesk-adapter/test/change_validators/standard_fields.test.ts
- packages/zendesk-adapter/test/change_validators/standrad_fields.test.ts
Validates that standard ticket fields are not added or removed or that their non-editable fields are not modified
---
It seems that some fields of standard ticket fields are uneditable under some conditions
I did not get into it because i did not see a failed deployment of the other fields so it might be better to wait and handle it if it pops
---
None
---
None
> SALTO-3648 - Added a validator to prevent illegal changes to standard ticket fields

- packages/jira-adapter/src/client/pagination.ts
_Reverting [this](https://github.com/salto-io/salto/pull/4571) Jira Fixed the problem they had_
---
_Kept the original pagination even though no one is using in case another bug will be introduced (and against evil eye)_
---
None
---
None
> SALTO-4451: Revert Status workaround

- packages/salesforce-adapter/src/additional_references.ts
- packages/salesforce-adapter/src/constants.ts
- packages/salesforce-adapter/test/additional_references.test.ts
Building on top of https://github.com/salto-io/salto/pull/4573, re-add the removed profile references in the adapter's `getAdditionalReferences`. 
`getAdditionalReferences` already dealt with field-level permissions, so we add all the other profile sections.
Note: This PR is missing the references from `layoutAssignments`...`recordType`. due to the urgency of this PR, I will add them in a follow-up PR.
---
I basically factored out the implementation for fieldPermissions ~and added support for a couple of edge cases (e.g. in layoutAssignments every entry is an array with a single element for some reason)~
---
N/A
---
N/A
> SALTO-4402 - Salesforce: Recreate profile refs as additional refs

- packages/salesforce-adapter/src/additional_references.ts
- packages/salesforce-adapter/test/additional_references.test.ts
These refs require some special handling that we didn't have time to implement in the previous PR, so add them now.
---
---
N/A
---
N/A
> SALTO-4402 - Salesforce: Recreate references from profiles' layoutAssignments' recordTypes

- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/test/adapter_creator.test.ts
- packages/netsuite-adapter/test/client/suiteapp_client/suiteapp_client.test.ts
Use `systemInformation` as returned from SuiteApp in order to define the `accountType` and `isProduction` values.
---
A new SuiteApp version returns envType info - which is one of the 4 values - `production`, `sandbox`, `beta` or `internal`.
We use these values to define the account type and whether it's a production account or not.
Notice that `accountType` and `isProduction` values are optional and are not returned in cases the account does not have SuiteApp credentials.
---
---
> SALTO-4376: Netsuite - Update validateCredentials to return accountType and isProduction info

- packages/core/src/local-workspace/dir_store.ts
- packages/core/test/workspace/local/directory_store.test.ts
- packages/workspace/src/workspace/dir_store.ts
- packages/workspace/src/workspace/static_files/source.ts
- packages/workspace/test/workspace/static_files/source.test.ts
Fixed local dir store when a file is deleted
---
The local dir store `get` and `mtimestamp` function did not check if a file is in the `deleted` list which made it returns a file that was deleted from the dirstore if a flush wasn't called in between.
This fix is necessary for the "restore elements path" flag, since we remove the files and recreate them.
Fixing the dirstore created another issue that we access the content of lazy static files for the first time after they were deleted so they can't be loaded. It happened in the router when we delete a static file from common and create it in a specific env. I change the LazyStaticFile to ignore deletions that were not flushed to solve this case
---
None (I am not aware of this having an effect on the user so far)
--- …
> SALTO-4456: Fixed local dir store when a file is deleted

- packages/adapter-api/src/error.ts
- packages/adapter-api/test/error.test.ts
- packages/zendesk-adapter/src/adapter.ts
- packages/zendesk-adapter/src/deployment.ts
- packages/zendesk-adapter/src/errors.ts
- packages/zendesk-adapter/src/filters/account_settings.ts
- packages/zendesk-adapter/src/filters/app.ts
- packages/zendesk-adapter/src/filters/article/article_body.ts
- packages/zendesk-adapter/src/filters/article/utils.ts
- packages/zendesk-adapter/src/filters/brand_logo.ts
- packages/zendesk-adapter/src/filters/business_hours_schedule.ts
- packages/zendesk-adapter/src/filters/custom_statuses.ts
- packages/zendesk-adapter/src/filters/guide_order/guide_order_utils.ts
- packages/zendesk-adapter/src/filters/macro_attachments.ts
- packages/zendesk-adapter/src/filters/organization_field.ts
- packages/zendesk-adapter/src/filters/organizations.ts
- packages/zendesk-adapter/src/filters/reorder/creator.ts
- packages/zendesk-adapter/src/filters/reorder/trigger.ts
- packages/zendesk-adapter/src/filters/webhook.ts
- packages/zendesk-adapter/test/adapter.test.ts
- packages/zendesk-adapter/test/errors.test.ts
- packages/zendesk-adapter/test/filters/app.test.ts
- packages/zendesk-adapter/test/filters/brand_logo.test.ts
change zendesk errors to return saltoErrors instead of throwing them
---
---
None
---
None
> SALTO-4214: change zendesk errors to return saltoErrors instead of throwing them

- packages/okta-adapter/e2e_test/mock_elements.ts
Fix Okta E2E
---
2 fields were added to app instances and needed to be added to apps mock as well
---
None
---
None
> SALTO-4475: Fix Okta E2E

- packages/adapter-utils/src/utils.ts
- packages/adapter-utils/test/utils.test.ts
- packages/core/src/core/restore.ts
- packages/workspace/index.ts
- packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
- packages/workspace/src/workspace/path_index.ts
- packages/workspace/test/workspace/path_index.test.ts
SALTO-4356 improve splitElementByPath complexity 
---
Improve splitElementByPath and filterByID complexity 
---
Reduced operation time of Fetch (from workspace) and Restore
> SALTO-4356 improve splitElementByPath complexity 

- packages/salesforce-adapter/src/additional_references.ts
- packages/salesforce-adapter/test/additional_references.test.ts
Added additional references for modification changes.
---
When there is a modification change, we will create a reference between the profile to each one of the detailed changes of the modified change
---
- Added additional references for modification changes
---
None
> SALTO-4482: added additional_references also for modifications

- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/test/client/suiteapp_client/soap_client/soap_client.test.ts
_Timeout added for soap client_
---
_The ticket - https://salto-io.atlassian.net/browse/SALTO-4424_
---
_NetSuite Adapter_:
* Timeout added to soap requests
---
_None_
> SALTO-4424: Add timeout for soap client

- packages/netsuite-adapter/src/elements_source_index/elements_source_index.ts
- packages/netsuite-adapter/src/elements_source_index/types.ts
- packages/netsuite-adapter/src/filters/element_references.ts
- packages/netsuite-adapter/test/elements_source_index.test.ts
- packages/netsuite-adapter/test/filters/element_references.test.ts
- packages/netsuite-adapter/test/utils.ts
_Create references to custom record fields in suitescripts_
---
_The ticket: https://salto-io.atlassian.net/browse/SALTO-4305_
_Currentrly this pr contains a "softer" version which only logs the new found references and doesn't add them_
---
* custom record field references in suitescripts will be logged.
---
_None_
> SALTO-4305: Create references to custom record fields in suitescripts

- packages/adapter-utils/src/utils.ts
- packages/adapter-utils/test/utils.test.ts
- packages/core/src/core/restore.ts
- packages/workspace/index.ts
- packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
- packages/workspace/src/workspace/path_index.ts
- packages/workspace/test/workspace/path_index.test.ts
This reverts commit a846cc7170baa8ba2033256a756870203e5b2446.
We discovered a behavior change in the function that breaks the SaaS
---
None
---
None
> SALTO-4482: Revert filterById change

- packages/salesforce-adapter/src/filters/centralize_tracking_info.ts
- packages/salesforce-adapter/test/filters/centralize_tracking_info.test.ts
Per https://help.salesforce.com/s/articleView?id=sf.tracking_field_history.htm&type=5, there is a closed list of standard objects that support history tracking. Per https://help.salesforce.com/s/articleView?id=sf.tracking_field_history_for_standard_objects.htm&type=5 only four of them have an actual object-level enable annotation. The rest just implicitly support the feature.
---
---
Salesforce: can now manage history tracking of all standard objects 
---
Salesforce: The 'historyTrackedFields' annotation may be added to some standard object types
> SALTO-4309 - Salesforce: Hard-coded list of standard objects that support history tracking

- packages/workato-adapter/package.json
- packages/workato-adapter/src/filters/cross_service/recipe_block_types.ts
- packages/workato-adapter/test/filters/recipe_block_type.test.ts
In this PR, I have added createBlockChecker which create recipe block checker from Joi Schema. 
In addition, I have been added 'provider' arg for the blockBase such that createBlockChecker can depend on it.
(All CrossService Blocks contanis provider anyway)
---
This PR is base branch for future SALTO-1619 PR. (we want to use Joi while validating Jira block)
---
None
---
None
> workato add Joi support for recipeBlockTypes (cross-service)

- packages/adapter-api/src/adapter.ts
- packages/core/src/api.ts
- packages/core/src/core/fetch.ts
- packages/core/test/core/fetch.test.ts
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/salesforce-adapter/src/adapter.ts
Support deletion in partial fetch - core side (NetSuite side was done already)
---
None
---
Support deletion in partial fetch (**NetSuite** only currently)
Support deletion of standard instances, custom types and custom records. **No** support for file cabinet
---
None
> SALTO-3791 Support deletion in partial fetch - core side

- packages/adapter-utils/src/compare.ts
- packages/salesforce-adapter/src/additional_references.ts
- packages/salesforce-adapter/test/additional_references.test.ts
Fixed additional_references to work for modifications changes in profiles
---
The fix is to instead of making the relevant section in the profile the source of the reference, I create a reference for each detailed change in the relevant section in the profile, so the source and target of the references match a detailed changes in the comparison
---
None
---
None
> SALTO-4482: Fixed additional_references on modifications in profiles

- packages/adapter-api/src/element_id.ts
- packages/adapter-utils/src/utils.ts
- packages/adapter-utils/test/utils.test.ts
- packages/core/src/core/restore.ts
- packages/workspace/index.ts
- packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
- packages/workspace/src/workspace/path_index.ts
- packages/workspace/test/workspace/path_index.test.ts
SALTO-4356 improve splitElementByPath complexity 
---
Improve splitElementByPath and filterByID complexity 
---
Reduced operation time of Fetch (from workspace) and Restore
> SALTO-4356 improve splitElementByPath complexity

- packages/workato-adapter/src/constants.ts
- packages/workato-adapter/src/filters/cross_service/jira/project_issuetypes.ts
- packages/workato-adapter/test/filters/project_issuetypes.test.ts
In this pull request, I have divided 'project_issuetype' and 'sample_project_issuetype' into two separate entities: 'project_key' and 'issuetype'.
---
This PR is based on https://github.com/salto-io/salto/pull/4600  branch  and is base branch for future SALTO-1619 https://github.com/salto-io/salto/pull/4487   PR. (we want to use Joi while validating Jira block) 
---
Release Notes:
Workato Adapter -
- change jira-connected input arguments. splitting project_issuetype and sample_project_issuetype.
---
User Notifications:
With each fetch using the Workato adapter, any Jira-Connected recipe code will now retrieve 'projectKey' and 'issueType' as separate entities rather than the combined 'project_issue_type'. This change will be reflected similarly in 'sample_project_issuetype'
> Workato jira cross service split project issuetype

- packages/adapter-utils/src/template.ts
- packages/zendesk-adapter/src/filters/handle_template_expressions.ts
- packages/zendesk-adapter/test/filters/handle_template_expressions.test.ts
Support missing references for dynamic content
Also support array in array structure in 'actions' field of instances
---
trigger type action's are array inside array, and we covered only 1 nesting level with our code, so i made it recursive to cover all possible nesting levels (which is currently 2)
---
* References inside array inside array in 'actions' field of instances will be converted to reference expressions
* Dynamic content references will now be converted to reference expressions
---
None
> SALTO-4295 - Zendesk Adapter - Support missing reference for dynamic_content

- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/omit_inactive.ts
- packages/zendesk-adapter/test/filters/omit_inactive.test.ts
Allow to put omitInactive in typeDefault to omit inactive instances from all types, being able to override that default in the type specific config
---
None
---
* Added the option to default omit all inactive instances using typeDefaults config
---
None
> SALTO-4280 - Zendesk Adapter - allow omitInactive in typeDefaults

- packages/adapter-api/src/element_id.ts
- packages/adapter-utils/src/utils.ts
- packages/adapter-utils/test/utils.test.ts
- packages/core/src/core/restore.ts
- packages/workspace/index.ts
- packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
- packages/workspace/src/workspace/path_index.ts
- packages/workspace/test/workspace/path_index.test.ts
This reverts commit 9ab5a1b0dc2b9834757dfa1f608a7d594af87352.
---
---
---
> Revert "SALTO-4356 improve splitElementByPath complexity (#4618)"

- packages/jira-adapter/e2e_test/instances/cloud/index.ts
- packages/workato-adapter/src/filters/cross_service/jira/project_issuetypes.ts
- packages/workato-adapter/test/filters/project_issuetypes.test.ts
In  Workato Adapter - Jira recipe. allow split project_issuetype even if dynamicPickListSelction not contained.
---
This is fix for the PR here - https://github.com/salto-io/salto/pull/4602
needed because Workato change interface
---
Workato adapter
- jira-connected input arguments. now splitting project_issuetype and sample_project_issuetype even if dynamicPickLiseSelection isn't exist.
---
- From now, you will see the projectKey and IssueType instead of project_issuetype even if dynamicPickListSelction is not exist
> SALTO-1619: Fit new workato ids model

- packages/salesforce-adapter/src/change_validators/unknown_users.ts
- packages/salesforce-adapter/test/change_validators/unknown_users.test.ts
The previous PR for this CV was... painfully naive. It assumed we will get changes to instances as changes to the specific type of the inner field of the instance that was actually changed. This not being the case, we need to support validation of nested fields and arrays.
---
This is a rework of https://github.com/salto-io/salto/pull/4554 . Instead of manually implementing access to nested fields, arrays, etc. we use `transformElement` to recursively walk through every instance. When we find a field of a type that we care about we extract users from it. 
It also allows us to simplify the code a bit and remove the duplicate iteration in `getUnknownUsers`.
Thanks @tamtamirr !
Tests:
- Deployed AssignmentRules, EscalationRules with correct and incorrect users
--- …
> SALTO-4430 - Salesforce: Add support for arrays and nested fields to unknown_users CV (v2)

- packages/adapter-api/src/adapter.ts
- packages/adapter-utils/src/filter.ts
- packages/core/src/core/deploy/deploy_actions.ts
- packages/core/test/api.test.ts
- packages/jira-adapter/src/deployment/jsp_deployment.ts
- packages/jira-adapter/test/filters/notification_scheme/notification_scheme_deployment.test.ts
- packages/jira-adapter/test/filters/security_scheme.test.ts
- packages/zendesk-adapter/src/filters/guide_order/guide_order_utils.ts
From this point on, only SaltoError or SaltoElementError can be returned as errors from adapters. Errors can and should be thrown for exceptions and unexpected scenarios.
---
Also touched specific adapters that did not conform 100%
---
---
> SALTO-4324 do not allow returning Error in DeployResult

- packages/workspace/src/workspace/adapters_config_source.ts
- packages/workspace/test/workspace/adapters_config.test.ts
There was a bug that causes us to add a flush call when setting the adapter config. The bug was solved so we can remove it
---
None
---
None
> SALTO-1641: Removed flush from adapter config source

- packages/jira-adapter/src/change_validators/account_id.ts
- packages/jira-adapter/src/change_validators/masking.ts
- packages/jira-adapter/src/change_validators/permission_scheme.ts
- packages/jira-adapter/src/filters/account_id/user_fallback_filter.ts
- packages/jira-adapter/src/filters/account_info.ts
- packages/zendesk-adapter/src/change_validators/one_translation_per_locale.ts
We have generic logs for filters and change validators, removing redundant ones that were added manually
---
None
---
None
> SALTO-4513 remove redundant logs

- packages/workspace/src/workspace/path_index.ts
- packages/workspace/test/workspace/path_index.test.ts
SALTO-4458 improve path index hints generation consistency
we added for keys to the pathIndex such as .annotation .field and .attr elemId (e.g: salto.obj.field).
now when the field of an object are divided between two files `salto.obj.field`   will point to both of them.
And if the few annotation under the same file, we wont have a key of each annotation in the pathIndex. instead `salto.obj.annotation` will point at the relevant file.
---
none
---
none
> SALTO-4458 improve path index hints generation consistency

- packages/netsuite-adapter/e2e_test/adapter.test.ts
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/transformer.ts
- packages/netsuite-adapter/src/types.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/netsuite-adapter/test/sdf_folder_loader.test.ts
We should create the bundle type and its inner types once, so the field types of the bundle type will point to the same inner type objects that we return.
---
---
None
---
None
> Keep bundle inner-types relations

- packages/zendesk-adapter/src/dependency_changers/article_attachment_change.ts
- packages/zendesk-adapter/src/dependency_changers/index.ts
- packages/zendesk-adapter/test/dependency_changers/article_attachment_change.test.ts
add dependency between attachment to article
---
---
* deploy of addition of attachments to an article with change validator errors will fail.
---
None
> SALTO-4467: add dependency between attachment to article

- packages/netsuite-adapter/src/change_validators/client_validation.ts
- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/src/client/errors.ts
- packages/netsuite-adapter/src/client/language_utils.ts
- packages/netsuite-adapter/src/client/sdf_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts
- packages/netsuite-adapter/src/client/utils.ts
- packages/netsuite-adapter/src/filters/config_features.ts
- packages/netsuite-adapter/src/types.ts
- packages/netsuite-adapter/test/change_validators/client_validation.test.ts
- packages/netsuite-adapter/test/client/client.test.ts
- packages/netsuite-adapter/test/client/sdf_client.test.ts
- packages/netsuite-adapter/test/filters/config_features.test.ts
> SALTO-3203 return more readable error messages on NS SDF deploy and reuse in SDF validation

- packages/netsuite-adapter/src/change_validator.ts
- packages/netsuite-adapter/src/change_validators/translation_collection_references.ts
- packages/netsuite-adapter/src/config.ts
- packages/netsuite-adapter/test/change_validators/translation_collection_references.test.ts
_Add change validator for translation collection NS references_
---
_The ticket: https://salto-io.atlassian.net/browse/SALTO-3067_
---
* NetSuite references to translation collections not in the project will raise a change error
---
_None_
> SALTO-3067: add change validator for translation collection NS references

- packages/adapter-api/src/elements.ts
- packages/adapter-api/src/values.ts
- packages/adapter-utils/src/utils.ts
- packages/adapter-utils/test/utils.test.ts
- packages/lowerdash/src/types.ts
- packages/lowerdash/test/types.test.ts
- packages/salesforce-adapter/src/filters/convert_types.ts
- packages/salesforce-adapter/src/transformers/transformer.ts
- packages/salesforce-adapter/test/transformers/transformer.test.ts
Shorten runtime of covertTypes filter by making it run synchronously
---
Made covertTypes filter synchronous by creating sync versions of `transformValues` and `transformPrimitive`
---
_Release Notes_:  _None_
---
> SALTO-4306 make convertTypes filter synchronous

- packages/salesforce-adapter/config_doc.md
SALTO-4282 add SF change validators documentation
---
1. I deleted one table entry that did not showed up inhttps://github.com/salto-io/salto/blob/main/packages/salesforce-adapter/config_doc.md
2. one rename based on the same file.
3. I did not include omitData and dataChange CVs as they are used internally. 
---
none
---
none
> SALTO-4282 add SF change validators documentation

- packages/dummy-adapter/src/adapter.ts
- packages/dummy-adapter/src/generator.ts
- packages/dummy-adapter/test/adapter.test.ts
add alias to dummy adapter
---
added only for instances and custom objects
---
None
---
None
> SALTO-4525: add alias to dummy adapter

- packages/jira-adapter/src/change_validators/field_contexts/field_contexts.ts
- packages/jira-adapter/test/change_validators/field_contexts/field_contexts.test.ts
_Fixed a bug in the change validator that should prevent deployment of non-global context that no project references_
---
---
Jira Adapter:
* Fixed a bug in change validator for non-global contexts
---
None
> SALTO-4535: bug with non global context change validator

- packages/salesforce-adapter/src/additional_references.ts
- packages/salesforce-adapter/test/additional_references.test.ts
Use fullName to map from the contents of the fields in the various Profile sections to the potential ref targets.
---
Before this change the code assumed it can create the field names from the apiName of the potential reference targets. This is not the case, and only happened to work most times for most types.
---
N/A
---
N/A
> Salesforce: getAdditionalReferences doesn't return references for Profile.layoutAssignments

- packages/cli/src/commands/restore.ts
- packages/cli/src/prompts.ts
- packages/cli/test/commands/restore.test.ts
- packages/core/src/api.ts
- packages/core/src/core/restore.ts
- packages/core/test/api.test.ts
- packages/core/test/core/restore.test.ts
Added flag to CLI restore to also restore paths
---
The way to restore paths currently is to delete and re-add all the elements in the workspace.
I added another API in core to do that.
---
CLI:
- Added `-r` flag to restore to also restore elements to their original paths
---
None
> SALTO-4456: Add flag to CLI restore to also restore paths

- packages/salesforce-adapter/src/fetch.ts
- packages/salesforce-adapter/test/adapter.discover.test.ts
Changes to retrieve API caused internal ID to have empty string. 
---
---
Salesforce:
- Fix broken go-to-service URLs
---
> SALTO-4486 deal with case where internal ID is an empty string, and don't return it in getTypeIdenitifier

- packages/adapter-api/src/error.ts
- packages/adapter-api/test/utils.test.ts
isSaltoElementError should return false, in case value is undefined
---
---
---
> SAAS-8650: Fix isSaltoElementError method

- packages/salesforce-adapter/src/additional_references.ts
- packages/salesforce-adapter/test/additional_references.test.ts
Only create references that are meaningful to the user
---
See the ticket for the definition of "meaningful to the user". Basically we only want to create refs where not creating them would make a difference to what we deploy.
~This PR builds on top of https://github.com/salto-io/salto/pull/4617~
---
N/A
---
N/A
> SALTO-4457 - Salesforce: Fine-tune profile refs in getAdditionalReferences

- packages/adapter-components/src/client/pagination/pagination_async.ts
- packages/adapter-components/test/client/pagination.test.ts
_make parallel pagination keep its order_
---
* solving race condition that we found in this [ticket](https://salto-io.atlassian.net/browse/SALTO-4504) 
performance tests:
I fetched a large env couple of times with and without the new implementation:
old implementation time (in seconds): 
* 2:02.21
* 3:04.13
* 2:19.06
* 2:35.83
* 1:32.10
new implementation time (in seconds): 
* 2:34.74
* 3:16.73
* 1:51.87
* 1:34.27
* 1:46.61
---
Jira Adapter:
* fix a bug of inconsistent order in elements that contain a list with many objects
---
_None_
> SALTO-4504: make parallel pagination keep its order

- packages/zendesk-adapter/src/filters/article/article_body.ts
- packages/zendesk-adapter/test/filters/article/article_body.test.ts
Use the type name instead of the type field
---
None
---
* Missing instances in article body will have the correct type
---
Zendesk Adapters:
* article_translations with reference expressions in their body will change, the typename will change from plural to singular (eg articles -> article)
> SALTO-4311 - Zendesk Adapter - Fix type of missing instances in article body

- packages/core/src/local-workspace/s3_dir_store.ts
- packages/core/test/workspace/local/s3_dir_store.test.ts
Fixed files in s3_dir_store being flushed twice on each flush of the workspace
---
- Fixed files in s3_dir_store being flushed twice on each flush of the workspace
---
None
> SALTO-4533: State static files are flushed twice for each workspace flush

- packages/zendesk-adapter/src/config.ts
omit usage_7d from selected_macros in workspace
---
---
zendesk:
* omit usage_7d from selected_macros in workspace
---
zendesk:
* remove field usage_7d from selected_macros in workspace
> SALTO-4558: omit usage_7d from selected_macros in workspace

- packages/jira-adapter/src/filters/account_id/account_id_filter.ts
- packages/jira-adapter/test/filters/account_id/account_id_common.ts
_Fixed a bug where automations could not be deployed due to a certain usage of a built-in user type_
[Noise reduction](https://github.com/salto-io/salto_private/pull/6332)
---
To recreate add a create issue action for an automation. 
In 'Choose fields to set' select assignee or reporter.
At the bottom of the page find the field, on the right side press the ... and change to `copy` 
Fetch, make a copy and try to deploy.
Note- the custom fields with users does not use the 'ID' type, they use 'name' so they are no a concern here
---
Jira Adapter: 
* Fixed a bug that prevented the deployment of automations in specific conditions
---
Jira Adapter:
* On very specific cases there will be a change in autmations of the structure of assignee or reporter …
> SALTO-4554: exclude built-in names from automations' account id filter

- packages/jira-adapter/src/change_validators/field_contexts/field_contexts.ts
_There is currently a bug that prevents deployments of non-global contexts_
---
The previous fix for 4535 was not complete
---
JIra Adapter:
* Fixed a bug that prevented deployment of non-global field contexts
---
None
> SALTO-4535: Fix a bug with field contexts

- packages/netsuite-adapter/src/client/suiteapp_client/constants.ts
- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
---
---
- Add SOAP retryable error - request aborted error
---
None
> Add SOAP retryable error - request aborted error

- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/sdf_folder_loader.ts
- packages/netsuite-adapter/src/types.ts
- packages/netsuite-adapter/test/sdf_folder_loader.test.ts
Trying to parse integration objects causes an error to be thrown because integration object xmls has no values in them. We should skip them.
---
---
- Skip integration objects on SDF folder parsing
---
None
> SALTO-4565 Skip integration objects on SDF folder parsing

- packages/netsuite-adapter/src/client/language_utils.ts
- packages/netsuite-adapter/src/client/sdf_client.ts
- packages/netsuite-adapter/test/client/sdf_client.test.ts
In order to return shorter and more relevant deploy/validation errors.
---
Also removed unused property `validationFailed`
---
- Detect known general SDF errors
---
None
> SALTO-3203 detect known general SDF errors

- packages/jira-adapter/src/change_validators/default_field_configuration.ts
- packages/jira-adapter/test/change_validators/default_field_configuration.test.ts
_fix defaultFieldConfiguration validator to not fail items changes_
---
* lately we inserted the `fieldConfigurationItems` into `fieldConfiguration` and we did not change the validator accordingly.  
---
Jira Adapter:
* fix a bug with deploying changes on the default Field Configuration Items
---
None
> SALTO-4526: fix defaultFieldConfiguration validator to not fail items changes

- packages/okta-adapter/src/client/connection.ts
- packages/okta-adapter/test/adapter_creator.test.ts
- packages/okta-adapter/test/client/connection.test.ts
Return account type for Okta
---
identify if the account is sandbox or production based on base url
---
None
---
None
> SALTO-4377: Return account type for Okta

- packages/netsuite-adapter/src/change_validators/role_permission_ids.ts
We should not log permissions that are in the pattern of `[scriptid=...]`.
---
---
None
---
None
> SALTO-3417 ignore scriptid permissions

- packages/netsuite-adapter/src/change_validators/unique_fields.ts
- packages/netsuite-adapter/test/change_validators/unique_fields.test.ts
_Added workflows and scripts to the unique fields change validator_
---
_ticket: https://salto-io.atlassian.net/browse/SALTO-4138 first ticket about this change validator https://salto-io.atlassian.net/browse/SALTO-2915
Changed some logics in the existing code for it to match the new type of fields (inner fields)_
---
_In case users give the same scriptid for the custom fields, the change validator will cache this and cancel the deployment instead of getting exception_
---
_None_
> SALTO-4138: enforce uniqueness of workflow and scripts custom fields

- packages/zendesk-adapter/src/change_validators/attachment_without_content.ts
- packages/zendesk-adapter/src/filters/article/article.ts
- packages/zendesk-adapter/src/filters/article/utils.ts
- packages/zendesk-adapter/test/filters/article/article.test.ts
When failing to get content of attachment, don't fail the fetch, don't put any content and alert the user about the failure
---
None
---
* Failure of requesting article attachment content will no longer fail the fetch
---
None
> SALTO-4499 - Handle errors on article attachment content requests

- packages/netsuite-adapter/src/change_validator.ts
- packages/netsuite-adapter/src/change_validators/omit_fields.ts
- packages/netsuite-adapter/src/change_validators/types.ts
- packages/netsuite-adapter/src/config.ts
- packages/netsuite-adapter/src/filters/data_instances_diff.ts
- packages/netsuite-adapter/src/filters/omit_fields.ts
- packages/netsuite-adapter/test/change_validator.test.ts
- packages/netsuite-adapter/test/change_validators/omit_fields.test.ts
- packages/netsuite-adapter/test/filters/omit_fields.test.ts
_omit_fields filter now removes fields on preDeploy according to hard coded fields and fields from config_
---
_This pr covers two tickets_:
* https://salto-io.atlassian.net/browse/SALTO-2781
* https://salto-io.atlassian.net/browse/SALTO-4481
---
* 'classTranslationList' field in data elements and 'currency' field in inventory items will be omitted in preDeploy
* fieldToOmit added to config.deploy similar to the existing logic in config.fetch
---
_None_
> SALTO-4481: omit fields in preDeploy

- packages/adapter-components/src/references/field_references.ts
- packages/jira-adapter/src/filters/dashboard/gadget.ts
- packages/jira-adapter/src/filters/dashboard/gadget_properties.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/src/references/dashboard_gadget_properties.ts
- packages/jira-adapter/test/filters/dashboard/gadget.test.ts
- packages/jira-adapter/test/filters/dashboard/gadget_properties.test.ts
- packages/jira-adapter/test/references/dashboard_gadget_properties.test.ts
Add references to `Filter`, `Project` and extend `Field` references to support custom fields as well
---
This PR also fixes a bug in resolving of `Field` references in `DashboardGadget` causing deployment of changes with those references to fail
Will add noise reduction
---
- Fix bug in deployment of DashboradGadget
- Add references to Filter, Project, and Field from DashboardGadget
---
- References to Filter, Project, and Field will be added in DashboardGadget elements
> SALTO-4577: DashboardGadget references

- packages/core/src/core/restore.ts
- packages/core/test/core/restore.test.ts
SALTO-4594 fix the restore flow for modify instance change
before this fix modify changes in instances return without data as it was excluded in the new `filterByPathHint` func.
the tests did not caught this bug as it did not checked the data of the changes.
---
None
---
None
---
> SALTO-4594 fix the restore flow for modify instance change

- .circleci/config.yml
Fix a version problem in circle CI
---
None
---
None
---
None
> SALTO-4601: bump Xcode version

- packages/netsuite-adapter/src/filters/element_references.ts
- packages/netsuite-adapter/test/filters/element_references.test.ts
_match files referenced in suiteScripts that don't start with path prefix_
---
_The ticket - https://salto-io.atlassian.net/browse/SALTO-4025
This PR might cause audit noise, need communication before a noisy deployment._
---
* file references in suiteScripts that dont start with a path prefix will be added to generated dependencies
---
*_file references in suiteScripts that dont start with a path prefix will be added to generated dependencies_
> SALTO-4025: match files referenced in suiteScripts that don't start with path prefix

- packages/netsuite-adapter/src/change_validator.ts
- packages/netsuite-adapter/src/change_validators/unreferenced_addition.ts
- packages/netsuite-adapter/src/change_validators/unreferenced_file_addition.ts
- packages/netsuite-adapter/src/config.ts
- packages/netsuite-adapter/test/change_validators/unreferenced_file_addition.test.ts
_Added a change validator that checks for every file added in the deployment whether there is an element referencing it_
---
_None_
---
_Especially when deploying between 2 environments, users who added a file to the deployment but forgot to add the element referencing the file will get a warning.
This may cause warnings for a legitimate, although not typical, action_
---
_None_
> SALTO-4045: Warning about adding a file without referencing it

- packages/workspace/src/workspace/workspace.ts
Double-check whether workspace state exists before creating it.
---
There is a call to an async function between the time we check whether the workspace state exists and the time we initialize it if it doesn't. 
This `await` can cause Node.js to switch to another context that also called this function, which would also see that the workspace has no state and try to create it.
Best case scenario we crash because we open too many files when we parse the NaCl files in the workspace multiple times concurrently. Worst case scenario we overwrite the state with another state, which may or may not be benign but we'll never know we did it.
---
Improve stability when loading a workspace
---
N/A
> SALTO-4553 - Fix TOCTOU issue when creating workspace state

- packages/netsuite-adapter/src/filters/element_references.ts
- packages/netsuite-adapter/test/filters/element_references.test.ts
_log paths without path prefix instead of adding them until communicated_
---
_we should log the references instead of adding them until PROD-125 is communicated_
---
_None_
---
_None_
> SALTO-4025: log paths without path prefix instead of adding them

- packages/core/src/local-workspace/remote_map/counters.ts
- packages/core/src/local-workspace/remote_map/remote_map.ts
Prefer using the cache over deserializing as it tends to be faster
---
---
_None_
---
_None_
> SALTO-4604: Improve remote map performance when iterating over entries

- packages/jira-adapter/src/client/connection.ts
- packages/jira-adapter/test/adapter_creator.test.ts
- packages/jira-adapter/test/client/connection.test.ts
As of today, Jira does not have an API that checks if an account is production or sandbox.
After consultations with @omrilit  and @liorn, the solution implemented is:
1. Check if the URL contains `-sandbox-`.
2. Check if the account has paid apps.
If the URL contains the word sandbox or all the apps in the account are in a free plan, then the account will not be defined as Production.
---
None
---
None
---
None
> SALTO-4293 Update validateCredentials to identify whether the account is production or not

- packages/netsuite-adapter/package.json
- yarn.lock
---
---
Upgrade SDF to rely on a new JAR download URL based on 2023.1.0
---
> Upgrade SDF to rely on a new JAR download URL based on 2023.1.0

- packages/salesforce-adapter/config_doc.md
- packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts
Allow a custom default value for adapter configs. This PR also changes the default value of `fetchProfilesUsingReadApi` - both to show how it's done and because we've been wanting to do it anyway.
---
If we want to use adapter configs as feature flags we need to be able to change their default values without renaming them. This means the "default is always true" logic no longer holds. So let's change it slightly to "default is true, unless explicitly overridden".
---
N/A
---
N/A
> SALTO-4520 - Salesforce: Allow different default values for adapter configs

- packages/salesforce-adapter/src/custom_object_instances_deploy.ts
Remove CPU intensive log from SF adapter
---
This would get stuck in some cases where we needed to serialize profiles.
---
Resolve some rare cases where deploy would get stuck.
---
Resolve some rare cases where deploy would get stuck.
> SALTO-4612 - Remove CPU intensive log from SF adapter

- packages/jira-adapter/src/references/dashboard_gadget_properties.ts
We accidentally logged error when iterating gadget values to create references, I removed this cause it's not an error
---
None
---
None
> SALTO-4613: Remove redundant log when creating gadget references in Jira

- eslint/adapter-api.rules.js
- packages/adapter-api/src/values.ts
- packages/adapter-components/src/deployment/deployment.ts
- packages/adapter-utils/src/collisions.ts
- packages/adapter-utils/src/utils.ts
- packages/jira-adapter/src/filters/duplicate_ids.ts
- packages/jira-adapter/src/filters/workflow/workflow_deploy_filter.ts
- packages/lowerdash/src/types.ts
- packages/salesforce-adapter/src/custom_object_instances_deploy.ts
- packages/workspace/src/merger/internal/common.ts
- packages/workspace/src/merger/internal/instances.ts
- packages/workspace/src/serializer/elements.ts
- packages/zendesk-adapter/src/filters/app_installations.ts
- packages/zendesk-adapter/src/filters/app_owned_convert_list_to_map.ts
- packages/zendesk-adapter/src/filters/article/utils.ts
- packages/zendesk-adapter/src/filters/brand_logo.ts
- packages/zendesk-adapter/src/filters/collision_errors.ts
- packages/zendesk-adapter/src/filters/hardcoded_channel.ts
- packages/zendesk-adapter/src/filters/macro_attachments.ts
- packages/zendesk-adapter/src/filters/reorder/creator.ts
Switch to `inspect` for performance reasons.
---
None
---
None
> SALTO-3059 use inspect instead of safeJsonStringify with replacer

- packages/okta-adapter/src/config.ts
- packages/okta-adapter/src/filters/delete_fields.ts
Remove EmailTemplate type from the default config
---
---
> SALTO-4628: Remove EmailTemplate type

- packages/netsuite-adapter/src/change_validators/unique_fields.ts
- packages/netsuite-adapter/test/change_validators/unique_fields.test.ts
_Added states of workflows to the unique fields change validator_
---
_Incident: https://salto-io.atlassian.net/browse/INCIDENT-7262?focusedCommentId=95306&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-95306_
---
_Users will get an error when trying to deploy a workflow which contains a state with a custom field that has a non-unique scriptid_
---
_None_
> SALTO-4138: Added a check for unique scriptid of custom fields in states within workflows

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/constants.ts
- packages/jira-adapter/src/deployment/standard_deployment.ts
- packages/jira-adapter/src/filter.ts
- packages/jira-adapter/src/filters/broken_reference_filter.ts
- packages/jira-adapter/src/filters/script_runner/script_runner_filter.ts
- packages/jira-adapter/src/filters/script_runner/script_runner_instances_deploy.ts
- packages/jira-adapter/src/filters/script_runner/script_template_expressions.ts
- packages/jira-adapter/src/filters/script_runner/scripted_fields_issue_types.ts
- packages/jira-adapter/src/filters/script_runner/walk_on_scripts.ts
- packages/jira-adapter/src/filters/script_runner/workflow/walk_on_scripts.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/test/adapter.test.ts
- packages/jira-adapter/test/change_validators/script_runner_unresolved_reference.test.ts
- packages/jira-adapter/test/filters/script_runner/script_runner_broken_reference.test.ts
- packages/jira-adapter/test/filters/script_runner/script_runner_filter.test.ts
- packages/jira-adapter/test/filters/script_runner/script_runner_instance_deploy.test.ts
- packages/jira-adapter/test/filters/script_runner/scripted_fields_issue_types.test.ts
- packages/jira-adapter/test/filters/script_runner/workflow/empty_account_ids.test.ts
- packages/jira-adapter/test/filters/script_runner/workflow/workflow_cloud.test.ts
- packages/jira-adapter/test/filters/script_runner/workflow/workflow_dc.test.ts
- packages/jira-adapter/test/filters/script_runner/workflow/workflow_link_type.test.ts
- packages/jira-adapter/test/filters/script_runner/workflow/workflow_mail_lists.test.ts
- packages/jira-adapter/test/filters/script_runner/workflow/workflow_ors.test.ts
- packages/jira-adapter/test/filters/script_runner/workflow/workflow_references.test.ts
- packages/jira-adapter/test/utils.ts
Added support for fetch and deployment for scripted fields
---
Added some filters and repaired deployment for all script runner items.
Also Added initial fetch for api_config, commented out.
I have split  the PR to two commits, as one was a folder restructure
---
Jira Adapter:
* Added support for scripted fields in ScriptRunner
---
Jira Adapter:
* Added support for scripted fields in ScriptRunner
> SALTO-3958: scripted fields

- packages/salesforce-adapter/src/change_validator.ts
- packages/salesforce-adapter/test/change_validator.test.ts
Added core change validators to Salesforce Adapter.
---
This caused flows where users where not blocked when the deploy scope did not contain required dependencies.
---
- Deploys that miss required missing dependencies will be blocked.
---
_None_
> SALTO-4609: Added core change validators to Salesforce Adapter.

- packages/salesforce-adapter/src/filters/minify_deploy.ts
- packages/salesforce-adapter/src/filters/profile_permissions.ts
Keep all the sections of profiles, even if `minify_deployment` determines there's nothing interesting to deploy in them.
---
The `profile_permissions` filter assumes the `fieldPermissions` and `objectPermissions` sections exist. If a new object is added, it will try to add permissions for it to the Admin profile's `objectPermissions` section. But because that section was removed by `minify_deployment` (since it contained no changes), `profile_permissions` crashes.
---
Salesforce: Fix crash when deploying profiles along with new custom object types.
---
N/A
> SALTO-4617 - Salesforce: keep empty profile sections in minify_deployment

- packages/dag/src/nodemap.ts
- packages/dag/test/nodemap.test.ts
move `getComponent` so it can be used for graph traversal that doesn't require node values, e.g. https://github.com/salto-io/salto/pull/4141
---
None
---
None
> SALTO-2957 move getComponent to AbstractNodeMap

- packages/jira-adapter/e2e_test/instances/cloud/notificationScheme.ts
It looks like Jira removed the EmailAddress notification scheme so I removed it from the e2e
---
None
---
None
> SALTO-4643: Deploying notification scheme fails in E2E

- packages/zendesk-adapter/config_doc.md
- packages/zendesk-adapter/src/change_validator.ts
- packages/zendesk-adapter/src/change_validators/organization_existence.ts
- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/organizations.ts
- packages/zendesk-adapter/test/change_validators/organization_existence.test.ts
- packages/zendesk-adapter/test/filters/organizations.test.ts
add ability to create missing orgs in deployment
---
---
zendesk:
* when the deploy flag `defaultMissingOrgFallback` is true, missing referenced organizations will be created on deploy
---
None
> SALTO-4637: add ability to create missing orgs in deployment

- packages/adapter-api/src/error.ts
- packages/core/src/core/deploy/deploy_actions.ts
- packages/core/src/core/plan/filter.ts
- packages/lang-server/src/workspace.ts
- packages/workspace/src/workspace/adapters_config_source.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/adapters_config.test.ts
- packages/workspace/test/workspace/workspace.test.ts
Add 'dependency' to new `SaltoErrorType` to determine whether an error is a dependency error
---
---
---
> SAAS-8197 define dependency type for errors

- packages/adapter-components/src/elements/query/fetch_criteria.ts
- packages/adapter-components/src/elements/query/index.ts
- packages/adapter-components/test/elements/query/fetch_criteria.test.ts
- packages/zendesk-adapter/config_doc.md
- packages/zendesk-adapter/src/fetch_criteria.ts
- packages/zendesk-adapter/test/adapter.test.ts
Note: also contains the changes from https://github.com/salto-io/salto/pull/4141, please only review the last commit here.
Allow filtering by additional field values in zendesk - only a hard-coded list for now.
---
* Allow including/excluding items by additional properties besides name, including title, raw title, key, and type.
---
None
> SALTO-4638 Allow filtering in zendesk by title, raw title, type, key

- packages/netsuite-adapter/src/change_validators/client_validation.ts
- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/src/client/language_utils.ts
- packages/netsuite-adapter/src/client/utils.ts
1. Make some lists unique.
2. Do not return dependency errors on validation (core does it already).
3. Add known error messages.
---
---
- Improve NS change errors.
---
None
> Improve NS change errors

- packages/jira-adapter/src/config/config.ts
- packages/jira-adapter/test/filters/add_alias.test.ts
- packages/zendesk-adapter/src/config.ts
turn default alias config flag to true for all adapters
PR https://github.com/salto-io/salto/pull/4611 is for netsuite
PR https://github.com/salto-io/salto/pull/4734 is for salesforce
---
---
zendesk:
* annotation _alias will be added by default
jira:
* annotation _alias will be added by default
---
zendesk:
* annotation _alias will be added to the relevant nacls by default
jira:
* annotation _alias will be added to the relevant nacls by default
> SALTO-4608: turn default alias config flag to true for all adapters

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/change_validators/broken_references.ts
- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/filters/broken_reference_filter.ts
- packages/jira-adapter/src/filters/script_runner/script_runner_filter.ts
- packages/jira-adapter/src/filters/script_runner/script_runner_listeners_deploy.ts
- packages/jira-adapter/src/group_change.ts
- packages/jira-adapter/test/change_validators/script_runner_unresolved_reference.test.ts
- packages/jira-adapter/test/filters/script_runner/script_runner_broken_reference.test.ts
- packages/jira-adapter/test/filters/script_runner/script_runner_filter.test.ts
- packages/jira-adapter/test/filters/script_runner/script_runner_listeners_deploy.test.ts
Added support for script runner listeners
---
The deployment is done for all listeners together. Implementation tries to hide it from the users
The same deployment method is required for scripted fragments, there will be some reuse and some copy-paste
---
Jira Adapter:
* Added support for ScriptRunner Listeners
---
Jira Adapter:
* Customers with ScriptRunner enabled will see new ScriptRunner Listeners NaCls
> SALTO-3955: Script Runner Listeners

- packages/salesforce-adapter/src/filters/custom_metadata_to_object_type.ts
- packages/salesforce-adapter/src/filters/custom_objects_to_object_type.ts
- packages/salesforce-adapter/src/filters/metadata_instances_aliases.ts
- packages/salesforce-adapter/src/filters/utils.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/filters/metadata_instances_aliases.test.ts
Changed the aliases as for the plan described on the ticket.
---
Here are examples per different use-cases:
1. Instance with label: https://github.com/salto-io/tamir-sf/blob/alias/envs/env1/salesforce/Records/CMT2__mdt/CMT2_Record1.nacl
2. Instance with label from a namespace: https://github.com/salto-io/tamir-sf/blob/alias/envs/env1/salesforce/InstalledPackages/sbaa/Records/PermissionSet/sbaa__AdvancedApprovalsUser.nacl 
3. Custom Settings: https://github.com/salto-io/tamir-sf/blob/alias/envs/env1/salesforce/Objects/MyCustomSettings__c/MyCustomSettings__cAnnotations.nacl 
4. Custom Object from a namespace: https://github.com/salto-io/tamir-sf/blob/alias/envs/env1/salesforce/InstalledPackages/SBQQ/Objects/SBQQ__AttributeSet__c/SBQQ__AttributeSet__cAnnotations.nacl
5. Layout from a …
> SALTO-4627: Improved Metadata aliases

- packages/jira-adapter/src/filters/automation/automation_fetch.ts
- packages/jira-adapter/src/filters/automation/automation_structure.ts
- packages/jira-adapter/test/filters/automation/automation_fetch.test.ts
- packages/jira-adapter/test/filters/automation/automation_structure.test.ts
Jira changed Their API so project names are supported through `ruleScope`. This PR supports this change.
---
None
---
None
---
None
> SALTO-4515: Projects are not added to automation names

- packages/salesforce-adapter/src/client/user_facing_errors.ts
Append original error to user facing Errors & Map Metadata deploy limit error
---
To improve the experience with **user facing errors**, it's better to include the original error returned from **Salesforce** to give more context on the error.
---
- Custom Salto errors will include the original error from Salesforce. 
- Improved Salesforce Metadata Deploy size limit error.
---
_None_
> SALTO-4636 SALTO-4624: Append original error to user facing Errors & Map Metadata deploy limit error

- packages/cli/src/formatter.ts
- packages/cli/test/formatter.test.ts
Display ElemId in deploy error messages & some readability improvements 
---
before:
after:
---
_CLI_
- Improve readability of deploy errors in the CLI
---
None
> SALTO-4642: Display ElemId in deploy error messages

- packages/adapter-api/src/error.ts
- packages/adapter-api/test/error.test.ts
- packages/core/src/api.ts
- packages/core/test/api.test.ts
There is an implicit assumption that whenever the adapter fails due to invalid credentials in fetch or validateCredentials flows, an CredentialError will be thrown from the adapter.
We found that there are cases that this doesn't really happen and we wouldn't like to count on it and behave differently in such cases.
---
Core:
SALTO-4626: identify credentials error in fetch, deploy and validateCredentials flows
---
> SALTO-4626: do not treat CredentialError differently in validateCredentials and fetch

- packages/jira-adapter/e2e_test/instances/datacenter/index.ts
- packages/jira-adapter/src/adapter_creator.ts
- packages/jira-adapter/src/client/connection.ts
- packages/jira-adapter/test/client/connection.test.ts
We added a check for the license in validate creds, this check works only in Cloud and fails validate creds on DC so I changed to run it only in cloud
---
- Fixed bug with authentication to Jira
---
None
> SALTO-4657: Jira DC authentication fails

- packages/workato-adapter/src/constants.ts
- packages/workato-adapter/src/filters/cross_service/recipe_references.ts
- packages/workato-adapter/src/filters/cross_service/reference_finders.ts
- packages/workato-adapter/src/filters/cross_service/zendesk/element_index.ts
- packages/workato-adapter/src/filters/cross_service/zendesk/recipe_block_types.ts
- packages/workato-adapter/src/filters/cross_service/zendesk/reference_finder.ts
- packages/workato-adapter/test/filters/cross_service/element_index.test.ts
- packages/workato-adapter/test/filters/recipe_references.test.ts
In this PR I have added support for cross service references from Zendesk when fetching Workato account.
---
None
---
Workato adapter
- The users will be able to add Zendesk connection to serviceConnectionNames (in workato.nacl) and get all Zendesk references in workaot recipes 
---
When using Workato. Zendesk connected recipe will include references to zendesk
> Salto 1618/support cross service from workato to zendesk

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/filters/issue_layout/issue_layout.ts
- packages/jira-adapter/test/filters/issue_layout/issue_layout.test.ts
This PR supports issueLayout deploy via a private API and small fetch fixes. 
---
It follows this PR for fetching issueLayouts -  https://github.com/salto-io/salto/pull/4709
---
Now support deploy of issue Layout. 
---
Jira:
Upon your next fetch, you may encounter new instances of type **IssueLayout**.
> SALTO-4177 Support deploy of issue layout

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/change_validators/index.ts
- packages/jira-adapter/src/change_validators/issue_type_hierarchy.ts
- packages/jira-adapter/src/config/config.ts
- packages/jira-adapter/src/filters/issue_type_hierarchy_filter.ts
- packages/jira-adapter/src/utils.ts
- packages/jira-adapter/test/change_validators/issue_type_hierarchy.test.ts
- packages/jira-adapter/test/filters/issue_type_hierarchy_filter.test.ts
1. This PR support CV for handle deployment of issue type with hierarchy level > 0. 
The CV has different behaviors for free or paid accounts.
2. This PR includes filter that support deploy of issue type with hierarchy level > 0. 
3. This PR includes change for "isFreeLicencse" function. 
---
None
---
1. Paid users will be able to deploy issue types with hierarchy level larger than 1, but will need to change the hierarchy level through the service.
2. Free users will be able to modify issue types and change their hierarchy level from 0 to -1 or backwards. 
---
None
> SALTO-4386 Handle deployment of issue type with hierarchy level > 0

- packages/jira-adapter/e2e_test/instances/datacenter/index.ts
Add field configuration back to Jira DC E2E
---
It doesn't reproduce anymore so for now I will add the test back
---
None
---
None
> SALTO-4659: Creating new field configuration does not work in the Jira DC e2e account

- packages/netsuite-adapter/src/client/sdf_parser.ts
- packages/netsuite-adapter/test/client/mocks.ts
- packages/netsuite-adapter/test/client/sdf_client.test.ts
- packages/netsuite-adapter/test/client/sdf_parser.test.ts
Also supports a case where the "Objects" folder isn't exists (treated as empty folder)
---
---
- Support subdirs of Objects folder in SDF integration
---
None
> SALTO-4226 Support subdirs of Objects folder in SDF integration

- packages/jira-adapter/src/config/api_config.ts
Revert Behaviors as users without the Behaviors App get a 500 error on the behavior get call.
We revert for now and will deploy a long term solution later on 
---
None
---
Jira Adapter:
* Fixed a bug in ScriptRunner that failed fetches for customers without the Behaviours app
---
None
> SALTO-3961: disable behaviors until a proper fix to the 500 bug

- packages/zendesk-adapter/src/change_validators/users.ts
- packages/zendesk-adapter/src/user_utils.ts
- packages/zendesk-adapter/test/user_utils.test.ts
some automated users can have null custom role id. we should not assume this is failing the schema, because that has side-effects (we treat the entire user list as empty).
there are some other improvements we can make, but starting with a quick fix
---
* fix bug where users might get an incorrect deploy validation warning about a missing user due to an unexpected response structure
---
None
> SALTO-4680 allow null custom_role_id in user schema

- packages/netsuite-adapter/src/type_parsers/report_definition_parsing/parsed_report_definition.ts
_change FIELD_PARENT_GROUP, FIELD_GROUP type to unknown_
---
_The [incident](https://salto-io.atlassian.net/jira/software/c/projects/SALTO/issues/INCIDENT-7359?filter=myopenissues&jql=project%20in%20%28Salto%2C%20%22Salto%20SaaS%22%2C%20Incidents%29%0Aand%20assignee%20IN%20%28currentUser%28%29%29%0Aand%20statusCategory%20in%20%28%22To%20Do%22%2C%20%22In%20Progress%22%29%0AORDER%20BY%20created%20DESC)_
---
* reportdefinitions FIELD_PARENT_GROUP and FIELD_GROUP type changed to unkown
---
_None_
> INCIDENT-7359: change FIELD_PARENT_GROUP type to unknown

- packages/salesforce-adapter/src/change_validator.ts
- packages/salesforce-adapter/src/types.ts
Enable CV on additions/removals of Standard Fields and Objects
---
This is a previously implemented CV that wasn't enabled by mistake.
---
- Add a Change Validator that forbids Additions and Deletions of Standard Fields and Objects.
---
_None_
> SALTO-4410: Enable CV on additions/removals of Standard Fields and Objects

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/filters/broken_reference_filter.ts
- packages/jira-adapter/src/filters/script_runner/script_runner_filter.ts
- packages/jira-adapter/src/filters/script_runner/scripted_fragments_deploy.ts
- packages/jira-adapter/src/group_change.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/test/change_validators/script_runner_unresolved_reference.test.ts
- packages/jira-adapter/test/filters/script_runner/script_runner_broken_reference.test.ts
- packages/jira-adapter/test/filters/script_runner/script_runner_filter.test.ts
- packages/jira-adapter/test/filters/script_runner/scripted_fragments_deploy.test.ts
Support scripted fragments in script runner
---
To use you can enter one of the following in the single URL
https://status.circleci.com
https://status.atlassian.com
To view it press the script fragment button in the right panel (if you choose issue sidebar) or the script fragment button in the upper panel (below the name of the issue, near link issue) if you choose issue header
After putting the fragments in the adaptavist server we need to also activate them, that is the reason for the project/properties calls.
This feature is really buggy, you get wrong warnings for certain cases (more than 2 fragments), and if you add more than 1 in the same project and location you will only see the first
---
Jira Adapter:
* Added support for ScriptRunner's scripted fragments
--- …
> SALTO-3959: Scripted-Fragments

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/change_validators/index.ts
- packages/jira-adapter/src/change_validators/issue_type_hierarchy.ts
- packages/jira-adapter/src/config/config.ts
- packages/jira-adapter/src/filters/issue_type_hierarchy_filter.ts
- packages/jira-adapter/src/utils.ts
- packages/jira-adapter/test/change_validators/issue_type_hierarchy.test.ts
- packages/jira-adapter/test/filters/issue_type_hierarchy_filter.test.ts
Returned the changes of the [Hierarchy fixes](https://github.com/salto-io/salto/pull/4696) and reverted the change for `isFreeLicense`
---
Split into two: one commit for the revert of the revert, the second for the change
---
Jira Adapter:
* Fixed a bug that prevented deployment of permission schemes for some customers
---
None
> SALTO-4386: fix is free license

- packages/netsuite-adapter/src/filters/data_instances_attributes.ts
---
---
SALTO-4641: Fix crash in data_instances_attributes trying to access "attributes" on null
---
> SALTO-4641: Fix NS crash in data_instances_attributes trying to access "attributes" on null

- packages/salesforce-adapter/src/change_validator.ts
- packages/salesforce-adapter/src/types.ts
This reverts commit 688d2addfce9742bb09a76bf7634f562719cfa8d.
---
---
---
> Revert "Enable previously implemented CV on additions/removals of Standard Fields and Objects (#4791)"

- packages/lang-server/src/diagnostics.ts
- packages/lang-server/test/diagnostics.test.ts
- packages/vscode/e2e_test/extension.test.ts
- packages/vscode/src/adapters.ts
This reverts commit aeebfa5fc6eb091057cc8eb40fd04522e61548ef.
---
---
---
> Revert "SAAS-7539 display the total number of workSpace errors from diagnostics (#4796)"

- packages/lang-server/src/diagnostics.ts
- packages/lang-server/test/diagnostics.test.ts
- packages/vscode/e2e_test/extension.test.ts
- packages/vscode/src/adapters.ts
Revert "Revert "SAAS-7539 display the total number of workSpace errors
This reverts commit 357933a562fa5261823517049da83c31b202d401, that reverted aeebfa5fc6eb091057cc8eb40fd04522e61548ef.
---
display the total number of workSpace errors from diagnostics
---
None
> Revert "Revert "SAAS-7539 display the total number of workSpace errors

- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/src/workspace/state/in_mem.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
fix deletion of static file when fetch is run with regenerate salto ids
---
---
core:
* fix bug where regenerate salto ids would cause deletion of static file
---
None
> SALTO-4693: fix deletion of static file when fetch is run with regenerate salto ids

- packages/adapter-api/src/adapter.ts
- packages/core/index.ts
- packages/core/src/api.ts
- packages/core/src/local-workspace/workspace.ts
- packages/core/test/workspace/local/workspace.test.ts
- packages/dummy-adapter/src/adapter_creator.ts
- packages/lang-server/test/workspace.ts
- packages/workspace/src/workspace/reference_indexes.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/reference_indexes.test.ts
- packages/workspace/test/workspace/workspace.test.ts
Add getCustomReferences function to the adapter interface to allow him return references that are not in the NaCl and mark references as weak.
Changed the refernceTargetIndex structure to have a reference type for each reference
---
None
---
None
> SALTO-4656: Add getCustomReferences adapter API

- packages/zendesk-adapter/src/adapter.ts
Attempt to log account subscription data on fetch
---
None
---
* On begining of fetch, we will attempt to get the account subscription data and log it, only works on Zendesk production environment
---
None
> SALTO-4696 - Zendesk Adapter - Attempt to log account subscription data on fetch

- packages/workspace/src/serializer/elements.ts
- packages/workspace/test/serializer/serializer.test.ts
Support serializing and deserializing non element values - as primitives, reference expressions, static files etc.
This PR also fixes SALTO-4706 (static files are not well serialized on their own).
---
---
Workspace:
None
---
None
> SALTO-4705 Support serializing and deserializing values

- packages/lang-server/src/diagnostics.ts
- packages/lang-server/test/diagnostics.test.ts
SAAS-7539 fix total number of ws errors sent from getDiagnostics 
---
---
none
---
none
> SAAS-7539 fix total number of ws errors sent from getDiagnostics 

- packages/okta-adapter/src/adapter.ts
- packages/okta-adapter/src/filters/unordered_lists.ts
- packages/okta-adapter/test/filters/unordered_lists.test.ts
We noticed differences in `GroupRule` target groups between envs. The order has no meaning so we should sort the list to avoid this 
---
---
- Fix a bug casing unwanted differences in GroupRule lists
---
- In GroupRule instances, target group list order might change
> SALTO-4712: Add order filter in Okta

- packages/jira-adapter/src/filters/data_center/plugin_version.ts
- packages/jira-adapter/test/filters/data_center/plugin_version.test.ts
Do not raise fetch errors if dc plugin version is newer to allow updates
---
We need to update the supported versions of Jira DC. For that we need to issue a new plugin version.
Currently, we have a problem- we issue warnings on plugin versions which are higher or lower than expected. It means we need to issue both a new SAAS version and a plugin version at the same time, and we cannot do it.
The solution is to remove the info warning if the plugin version is higher than expected, as the warning is for CLI users and I think the amount of possible users for CLI against DC is small, and the loss is minimal.
---
None
---
None
> SALTO-4722: Allow silent DC plugin upgrades

- packages/zendesk-adapter/src/filters/ticket_form.ts
- packages/zendesk-adapter/test/filters/ticket_form.test.ts
fix removal of a field and conditions from a form at the same time
---
---
zendesk:
* Fix deployment error where removal of a field and relevant conditions from a form at the same time would return an error
---
None
> SALTO-4633: fix removal of a field and conditions from a form at the same time

- docs/syntax.md
- packages/adapter-api/src/builtins.ts
- packages/adapter-api/src/constants.ts
add important attribute core annotation
the annotations are: `_important_values` and `_self_important_values`
---
---
core:
* add important attribute core annotation `_important_values` and `_self_important_values`
---
None
> SALTO-4649: add important attribute core annotation

- packages/lang-server/src/diagnostics.ts
SAAS-7539 raise total number of ws errors that returns from getDiagnostics
---
---
raise total number of ws errors that returns from getDiagnostics
---
none
> SAAS-7539 raise total number of ws errors that returns from getDiagnostics

- packages/zendesk-adapter/src/filters/ticket_form.ts
- packages/zendesk-adapter/test/filters/ticket_form.test.ts
add onDeploy filter for ticket form.
when there is a ticket status field in the env and it does not have an id, the onDeploy for `ticket_forms` will add the `ticket_field_ids` to the form from the `elmentSource` 
---
---
zendesk:
* prevent the failure of deployment of `ticket_form` when ticket status `ticket_field` is added to the env
---
None
> SALTO-4714: add onDeploy filter for ticket form

- packages/adapter-components/src/client/http_connection.ts
default limitation is 10MB, there is no reason to limit us at the client level
---
None
---
* Deploying now supports objects larger than 10MB
---
None
> SALTO-4731 - Remove content size limitation on client post requests

- packages/jira-adapter/src/change_validators/issue_type_hierarchy.ts
- packages/jira-adapter/src/change_validators/permission_scheme.ts
- packages/jira-adapter/src/filters/issue_type_hierarchy_filter.ts
- packages/jira-adapter/src/filters/permission_scheme/deploy_permission_scheme_filter.ts
- packages/jira-adapter/src/filters/project.ts
- packages/jira-adapter/src/utils.ts
- packages/jira-adapter/test/change_validators/issue_type_hierarchy.test.ts
- packages/jira-adapter/test/filters/issue_type_hierarchy_filter.test.ts
- packages/jira-adapter/test/filters/permission_scheme/deploy_permission_scheme.test.ts
- packages/jira-adapter/test/utils.test.ts
In this PR, I've split isFreeLicense into two functions:
1. `isAllFreeLicense`, which checks if there are any non-free apps for the account.
2. `isJiraSoftwareFreeLicense`, which checks if the account has a non-free Jira Software app.
---
None
---
None
---
None
> SALTO-4386 Changed isFreeLicense in Jira

- packages/salesforce-adapter/src/filters/custom_object_instances_references.ts
Change the format of the error message as described by our Product folks.
---
Looks like when we went from grouping by ref target to grouping by ref source the code ends up much simpler. Or maybe there's something I missed.
New message looks like this:
```
Your Salto environment is configured to manage records of the Case object. 24 Case records were not fetched because they have a lookup relationship to one of the following objects:
Account
Contact
and these objects are not part of your Salto configuration. 
Here are the records:
https://salto-b7-dev-ed.my.salesforce.com/500Dn000002U0oWIAS relates to https://salto-b7-dev-ed.my.salesforce.com/001Dn0000063rYwIAI
https://salto-b7-dev-ed.my.salesforce.com/500Dn000002U0oWIAS relates to …
```
> SALTO-4500 - Salesforce: update error message when dropping data instances

- packages/workspace/src/serializer/elements.ts
- packages/workspace/test/serializer/serializer.test.ts
Use the static-files-reviver when deserializing a single static file value (not in an element).
---
---
None
---
None
> SALTO-4705 fix static files deserialization

- packages/okta-adapter/src/change_validators/group_rule_administrator.ts
- packages/okta-adapter/src/change_validators/role_assignment.ts
- packages/okta-adapter/src/config.ts
Changed config so we won't recurse into group role for every group
It slows down fetch a lot and doesn't seem to be important 
---
_Okta_adapter_
- Improve fetch times
- RoleAssignment instances will be excluded by default, this can be changed by editing the adapter config file.
---
_Okta_adapter_
- RoleAssignment instances will be removed
> SALTO-4734: Exclude RoleAssignment by default

- packages/jira-adapter/src/filters/jql/jql_references.ts
Fixed a bug in jql references
---
Verfifed on the service. recreation: Edit a reference in the jql part of an automation and deploy. The NaCl after the deployment will contain the value before the change.
---
Jira Adapter:
* Fixed a bug with deployments of jqls
---
None
> SALTO-4720: fix bug in jql references

- packages/jira-adapter/src/client/script_runner_connection.ts
- packages/jira-adapter/test/client/script_runner_client.test.ts
We make in the ScriptRunner Authentication a call using axios which is not documented. It is OK as it contains sensitive information, but in case we cannot parse it correctly we need to print the content of the answer
---
None
---
None
---
None
> SALTO-2525: Add logs to Script Runner Authentication

- packages/zendesk-adapter/src/filters/field_references.ts
Add missing references for 'field' fields that supposed to have ticket_field inside of them
---
Has noise reduction
---
* 'field' fields that are supposed to have ticket_field can now have missing references
---
None
> SALTO-4718 - Zendesk Adapter - 'field' ticket fields missing reference

- packages/lowerdash/src/chunks.ts
- packages/lowerdash/test/chunks.test.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts
`readFiles` request with a large amount of files (very small files) might be the reason for the `Script Execution Time Exceeded` error from NS restlet API. Limiting the maximum amount of files per request may be useful here.
---
---
None
---
None
> limit suiteapp readFiles to 10K files per request

- packages/workspace/src/workspace/element_selector.ts
- packages/workspace/test/element_selector.test.ts
Return quickly in `selectElementIdsByTraversal` when all given selectors are actually elemIds - without wildcards or referencedBy.
---
---
None
---
None
> SALTO-4733 treat selectors as elemIds when there are no wildcards

- packages/adapter-api/src/adapter.ts
- packages/cli/src/commands/element.ts
- packages/cli/src/formatter.ts
- packages/cli/src/prompts.ts
- packages/cli/test/commands/element.test.ts
- packages/core/src/api.ts
- packages/core/test/api.test.ts
- packages/dummy-adapter/src/adapter.ts
- packages/dummy-adapter/src/adapter_creator.ts
- packages/workspace/index.ts
- packages/workspace/src/workspace/element_selector.ts
Added fixElements adapter API
---
- Added fixElements API to adapter and core
- Added CLI command to run it
- Added fixElements function to dummy
---
__CLI__:
- Added `salto element fix` command
---
None
> SALTO-4697: Add fixElements adapter API

- packages/core/test/core/restore.test.ts
- packages/workspace/src/workspace/path_index.ts
- packages/workspace/test/workspace/path_index.test.ts
SALTO-4746 fix splitElementByPath (fetch from) for fields that are not in the path index
---
---
Core:
- fix issue where "fetch from" would omit fields that were not in the path index (fields that were recently deployed)
---
None
> SALTO-4746 fix splitElementByPath (fetch from) for fields that are not in the path index

- packages/jira-adapter/src/filters/fields/field_structure_filter.ts
- packages/jira-adapter/test/filters/fields/field_structure.test.ts
Seen on a customer's env.
The test recreates a similar case
---
None
---
Jira Adapter:
* Fixed a bug that caused fetch to fail for custom fields with parentless cascading options
---
None
> SALTO-4755: Fetch fails on invalid cascading options

- packages/jira-adapter/src/filters/issue_type_schemas/issue_type_scheme.ts
- packages/jira-adapter/test/filters/issue_type_schemas/issue_type_scheme.test.ts
Fixed deleting an issue type and removing it from the issue type scheme
---
---
- Fixed deleting an issue type and removing it from the issue type scheme
---
None
> INCIDENT-8074: Deleting issue types from the default issue type scheme fails

- packages/zendesk-adapter/src/change_validators/custom_statuses_enabled.ts
- packages/zendesk-adapter/test/change_validators/custom_statuses_enabled.test.ts
* isTicketForm now allow unknown in order to not fail on every ticket form
* also added 'end_user_conditions' to the possible conditions
* no longer error log in case the schema doesn't pass (as it is not necessarily an error)
---
None
---
* Fix warning on ticket_form deployments if the ticket form has custom ticket status, and the feature it not enabled
---
None
> Salto-4756 - Zendesk Adapter - Fix ticket_form schema guard and remove error login if it doesn't pass

- packages/salesforce-adapter/config_doc.md
- packages/salesforce-adapter/src/fetch_profile/data_management.ts
- packages/salesforce-adapter/src/filters/custom_objects_instances.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/fetch_profile/data_management.test.ts
- packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
Introduce the `saltoManagementFieldSettings.defaultFieldName` config. Fetching instances would now work in the following way:
1. If the instance's type is in `allowReferenceTo` and there's a reference to the instance, fetch it
2. If the instance's type is in `allowReferenceTo` and the instance has the `saltoManagementField` and the field's value is `true`, fetch it
3. If the instance's type is in `excludeObjects`, don't fetch it
4. If the instance's type is in `includeObjects`, and the instance has the `saltoManagementField` and the field's value is `true`, fetch it.
5. If the instance's type is in `includeObjects`, and does not have the `saltoManagementField`, fetch it.
6. Otherwise, don't fetch it.
---
~Note that this PR builds on top of https://github.com/salto-io/salto/pull/4762 - the …
> SALTO-4579 - Salesforce: Fetch instances based on a configurable field

- packages/salesforce-adapter/src/filters/extra_dependencies.ts
- packages/salesforce-adapter/test/filters/extra_dependencies.test.ts
The wrong field was queried which caused the queries to fail when running with the optional feature `toolingDepsOfCurrentNamespace`
---
_None_
---
_None_
> SALTO-4631: Extra Dependencies for current namespace only bugfix

- packages/netsuite-adapter/scripts/bundle_components_generation/bundle_components_generator.py
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/types.ts
- packages/netsuite-adapter/src/types/bundle_type.ts
- packages/netsuite-adapter/test/client/suiteapp_client/suiteapp_client.test.ts
_Bundle generation script updated, bundleType changed_
---
_The ticket - https://salto-io.atlassian.net/browse/SALTO-2602
**background** - Because relying on the NetSuite bundle search doesn't necessarily give the correct result, The script is changed to directly access bundles using its url. The log for installed bundles is updated to return the bundle_id, fetched_from and publisher_id which are required to access bundle's url directly. Also, this saves us some overhead when running the script.
The bundle type and schema are updated for better cover and now differentiate between the type returned from our suiteapp and the full type we late create._
---
_None_
---
_None_
> SALTO 2602: update bundle generation script and type

- packages/salesforce-adapter/src/additional_references.ts
- packages/salesforce-adapter/test/additional_references.test.ts
Add back @alonstern 's  https://github.com/salto-io/salto/pull/4837 that was reverted in https://github.com/salto-io/salto/pull/4862
---
None (same release as original)
---
None
> added references from new objects to profile field permissions (#4837)

- packages/zendesk-adapter/src/filters/guide_translation.ts
make guideTranslationFilter deploy run only when necessary
---
---
None
---
None
> SALTO-4770: make guideTranslationFilter deploy run only when necessary

- packages/jira-adapter/src/config/config.ts
In this PR I set enableIssueLayout to true.
---
None
---
We now able to fetch issue layouts in jira. 
---
_Jira_:
Upon your next fetch, you may encounter new instances of type **IssueLayout**.
> SALTO-4177: Enable Issue Layouts

- packages/workspace/src/parser/internal/dump.ts
- packages/workspace/src/parser/internal/native/consumers/values.ts
- packages/workspace/test/parser/dump.test.ts
Escape the string ''' inside multi line when dumping a nacl, and unescape it when parsing the nacl
---
None
---
Core:
* Fixed issue where multi line quotes inside a multi line value were not properly escaped in NaCl
---
_None_
> SALTO-4703 - Escape multi line quotes inside multi line

- packages/adapter-components/src/deployment/deployment.ts
Inspect data with bigger depth than the default, to log complicated instances correctly
---
None
---
Core
* trace log of instance deployment have bigger depth for the data
---
None
> SALTO-4773 - Increase data depth in deploy instance trace log

- packages/zendesk-adapter/src/change_validators/duplicate_id_field_values.ts
- packages/zendesk-adapter/test/change_validators/duplicate_id_field_values.test.ts
Also check for duplications with removals, because a change in the elemId can be translated into an addition and a removal change
---
None
---
Zendesk Adapter
* mismatches between environments of the elemIds of groups will be prevented
---
None
> SALTO-4534 - Zendesk Adapter - Detect duplicate ids from removal changes

- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/handle_identical_attachment_conflicts.ts
- packages/zendesk-adapter/test/filters/handle_identical_attahments_conflicts.test.ts
add handleIdenticalAttachmentConflicts flag
---
---
zendesk:
* add `handleIdenticalAttachmentConflicts` flag. when it is true it will look at all attachments with the same elemId and hash and will keep only one.
---
None
> SALTO-4747: add handleIdenticalAttachmentConflicts flag

- packages/jira-adapter/src/change_validators/workflows/empty_validator_workflow.ts
The Empty workflow validators change validators contained some validators that should be empty
---
Jira Adapter:
* Fixed a bug that prevented the deployment of some workflow validators
---
None
> SALTO-4794:Empty Validators

- packages/salesforce-adapter/e2e_test/adapter.test.ts
- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/fetch.ts
- packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts
- packages/salesforce-adapter/src/transformers/xml_transformer.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/adapter.discover.test.ts
- packages/salesforce-adapter/test/transformers/xml_transformer.test.ts
Support fetch of Workflow (it's sub-instances) on Custom Objects
---
Workspace diff with the optional feature enabled: https://github.com/salto-io/tamir-sf/commit/9a8d247550eef24f62a1be9f762247438e2b8ad1
The fileName that returned for a Workflow on a Custom Object are incorrect. See this as an example:
---
_None_
---
_None_
> SALTO-4761: Support fetch of Workflow on Custom Objects

- packages/salesforce-adapter/src/transformers/transformer.ts
- packages/salesforce-adapter/test/transformers/transformer.test.ts
handle undefined apiNames in transformer.isCustom in Salesforce Adapter.
---
Upon modification of picklist standard fields, when the **apiName** is undefined the preview flow yielded runtime error.
See the Jira ticket for more context.
---
_None_
---
_None_
> SALTO-4784: handle undefined apiNames in transformer.isCustom in SF

- packages/salesforce-adapter/src/config_creator.ts
Add problematic metadata types to default exclude list
---
---
- Add EclairGeoData, OmniUiCard, OmniDataTransform, OmniIntegrationProcedure, OmniInteractionAccessConfig, OmniInteractionConfig, and OmniScript to default exclude list
---
_User Notifications_:  _None_
> SALTO-4669 SALTO-4523 add metadata types to default exclude list

- packages/salesforce-adapter/src/change_validators/multiple_defaults.ts
Extract string so that error message does not show `[Object object]` anymore
---
---
_None_
---
_None_
> SALTO-4476 extract string from FieldDef for detailedMessage

- packages/zendesk-adapter/e2e_test/adapter.test.ts
- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/article/utils.ts
- packages/zendesk-adapter/src/filters/guide_arrange_paths.ts
- packages/zendesk-adapter/test/filters/guide_arrange_paths.test.ts
change path for attachment static file
add the possibility to use `&hash` in `idFields` of `article_attachment`
---
---
zendesk:
* change the path of article attachment static file, the new path will end with `/article_attachment/fileName/<hash>_fileName.png` instead of `/article_attachment/fileName.png`
* add the possibility to use `&hash` in `idFields` of `article_attachment`
---
zendesk:
* change the path of article attachment static file, the new path will end with `/article_attachment/fileName/<hash>_fileName.png` instead of `/article_attachment/fileName.png`
> SALTO-4747: change path for attachment static file

- packages/adapter-components/src/elements/ducktype/transformer.ts
- packages/adapter-components/test/elements/ducktype/transformer.test.ts
Following this [PR](https://github.com/salto-io/salto/pull/4857) I splited adapter components from jsm initial fetch.
---
None
---
None
---
None
> SALTO-2349: Added additional request context

- packages/salesforce-adapter/src/fetch_profile/data_management.ts
- packages/salesforce-adapter/src/types.ts
Follow-up to https://github.com/salto-io/salto/pull/4853 where we move the validation of the nested fields to a function, since using restrictions doesn't work as expected.
---
---
N/A
---
N/A
> SALTO-4581 - Salesforce: Fix validation of broken ref config

- packages/adapter-components/src/elements/ducktype/transformer.ts
Fixing a mistake in adapter components - should be additionalRequestContext.
---
None
---
None
---
None
> SALTO-2349: Fixing mistake in additionalRequestContext

- packages/workspace/src/workspace/path_index.ts
- packages/workspace/test/workspace/path_index.test.ts
SAAS-4710 Remove duplicate path from getFromPathIndex response
---
Core:
- fixed bug where restore/fetchFrom on element that has multiple fragments in the same file would create merge errors in nacl
---
None
> SAAS-4710 Remove duplicate path from getFromPathIndex response

- packages/jira-adapter/src/filters/project_category.ts
- packages/jira-adapter/test/filters/project_category.test.ts
We used to return them based on id, but we do not have an id on addition.
Changed to key, added tests and some coverage
---
---
Jira Adapter:
* Fixed a bug that caused project category not to be translated into a reference after project addition
---
None
> SALTO-4817: Return reference to project category

- docs/syntax.md
- packages/adapter-api/src/builtins.ts
- packages/adapter-api/src/constants.ts
- packages/adapter-utils/src/important_values.ts
- packages/adapter-utils/test/important_values.test.ts
add highlighted in annotation of important values
fix `getImportantValues` to return an array and to test values that are returned
add only last value of path when indexed
---
---
core:
* add highlighted field in annotation of important values
---
None
> SALTO-4767: add highlighted in annotation of important values

- packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts
- packages/salesforce-adapter/test/adapter.discover.test.ts
Opened the optional feature  fixRetrieveFilePaths.
---
- Bugfix: Retrieve Workflow instances on **Custom Objects**.
---
Saleforce:
- Upon your next fetch, you may encounter new sub-instances of **Workflow** on **Custom Objects**.
> SALTO-4761: open fixRetrieveFilePaths (Retrieve Workflow instances on CustomObjects)

- packages/adapter-utils/src/utils.ts
- packages/adapter-utils/test/utils.test.ts
Combine logic between transformValues and transformValuesSync so that they share more code.
---
The difficulty in combining the logic is the fact that we have to by synchronicity-agnostic, which is something Typescript is not very good at. With @ori-moisis's help, the logic that does not depend on synchronicity was refactored out into `recurseIntoValue`, and any part that still required synchronicity logic was kept inside the separate base functions `transformValues` and `transformValuesSync`
---
---
> SALTO-4527 combine transform values and transform values sync logic

- packages/jira-adapter/src/filters/automation/automation_fetch.ts
- packages/jira-adapter/test/filters/automation/automation_fetch.test.ts
_Sort projects in the automations elem ID_
---
Jira Adapter: 
* Automations with several projects will now have a consistent elemID (projects names in the ID are now sorted)
---
Jira Adapter: 
* For new envs the projects part of the automations elem ID will now be sorted. It can create a mismatch (add & removal instead of modification) when comparing to an older env
> SALTO-4811: sort projects in automations elem id

- packages/workspace/src/validator.ts
- packages/workspace/test/validator.test.ts
SALTO-4816 fix wrong elemId in unresolved reference error in tamplate expressions
---
---
language server:
- fix issue where unresolved references inside template expressions did not show as workspace warnings
---
None
> SALTO-4816 fix wrong elemId in unresolved reference error in template expressions

- packages/salesforce-adapter/src/change_validator.ts
- packages/salesforce-adapter/src/change_validators/deleted_non_queryable_fields.ts
- packages/salesforce-adapter/src/filters/custom_object_instances_references.ts
- packages/salesforce-adapter/src/filters/custom_objects_instances.ts
- packages/salesforce-adapter/src/filters/utils.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/change_validators/deleted_non_queryable_fields.test.ts
When we fetch a type that has some fields that are not queryable by the fetching user, any instances of this type will be fetched without values for said fields. If we later try to deploy these instances, these missing values are interpreted as if we want to delete the values of these fields. This is probably not what the user wants.
---
---
Salesforce: will now warn when deploying instances of types for which the fetching user did not have permission to read certain fields
---
N/A
> SALTO-4653 - Salesforce: Add change validator on deletions of non-queryable customFields

- packages/salesforce-adapter/src/filters/custom_object_instances_references.ts
The warning message about dropped instances due to broken refs is aggregated by type - we display a separate warning for each type that contains broken refs. But when we list the actual instances that were dropped we list all of them, not just the instances of the specific type we're warning about.
---
---
N/A
---
N/A
> SALTO-4813 - Salesforce: only show relevant instances when warning about broken refs

- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/test/adapter.discover.test.ts
When getting existing metadata types from the **ElementsSource** in quick fetch, filtering out Settings types. 
---
Added missing UT and improved the documentation of the method.
---
_None_
---
_None_
> SALTO-4825:  Filter out settings types when getting MetadataTypes from elementsSource in Quick Fetch

- packages/adapter-utils/src/important_values.ts
- packages/adapter-utils/test/important_values.test.ts
make getImportantValues return and array
---
---
---
> SALTO-4830: make getImportantValues return and array

- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/config.ts
- packages/netsuite-adapter/src/constants.ts
- packages/netsuite-adapter/src/data_elements/types.ts
- packages/netsuite-adapter/src/filters/add_alias.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/netsuite-adapter/test/config.test.ts
Add support in `bin` instances and exclude it by default.
---
---
- Support fetching `bin` instances. To start fetching `bin` instances in your environment, go to your environment configuration, remove `{ name = "bin" }` from the `fetch.exclude.types` section, then add it to the `fetch.include.types` section.
---
- `bin` will be added to `fetch.exclude.types` configuration.
> SALTO-4798 fetch NS bin instances

- packages/jira-adapter/src/deployment/standard_deployment.ts
- packages/jira-adapter/src/filters/jsm_types_deploy_filter.ts
This PR is the infrastructure for all other PRs. 
The following PRs [deploy portal group](https://github.com/salto-io/salto/pull/4932) and [deploy queue](https://github.com/salto-io/salto/pull/4902) are rebase on it. 
---
The Type CUSTOMER_PERMISSION will change in the next PR. 
---
None
---
None
> SALTO-2349: Improve JSM defualt deployment

- packages/jira-adapter/src/filters/issue_type_schemas/issue_type_scheme.ts
Current order created a problem when the default issue type did not exist in the before changes 
---
---
Jira Adapter:
* Fixed a bug that caused deployment of Issue Type Schemes to fail in certain conditions
---
None
> SALTO-4849: Change order of actions in Issue Type Scheme

- packages/core/src/app_config.ts
- packages/core/src/core/fetch.ts
- packages/core/test/core/fetch.test.ts
Change the default behavior of auto-merge - disable only when `SALTO_AUTO_MERGE_DISABLE=1`.
---
---
None
---
None
> SALTO-4757 enable auto-merge by default

- packages/salesforce-adapter/src/metadata_deploy.ts
- packages/salesforce-adapter/test/adapter.crud.test.ts
- packages/salesforce-adapter/test/mock_elements.ts
Fix issue where element IDs were not saved on failed deployments
Also, make deploy message more concise, since all the information is now saved elsewhere
---
---
---
> SALTO-4588 fix SF errors not always saving element IDs

- packages/okta-adapter/config_doc.md
- packages/okta-adapter/src/adapter.ts
- packages/okta-adapter/src/config.ts
- packages/okta-adapter/src/filters/profile_mapping_addition.ts
- packages/okta-adapter/src/filters/profile_mapping_properties.ts
- packages/okta-adapter/test/filters/add_alias.test.ts
- packages/okta-adapter/test/filters/profile_mapping_addition.test.ts
- packages/okta-adapter/test/filters/profile_mapping_properties.test.ts
Add push status info for ProfileMapping instances
---
changes:
1. Add deployment for ProfileMapping instances (only modifications)
2. Fetch properties for profile mapping which also contains info re push status of each property
---
- Fetch properties push status in ProfileMapping instances
- Support deployments of ProfileMapping
---
- properties push status will be added to ProfileMapping instances
> SALTO-4769: Add properties & push status to ProfileMapping instances (Okta)

- packages/salesforce-adapter/src/filters/reference_annotations.ts
- packages/salesforce-adapter/test/filters/reference_annotations.test.ts
There does not seem to be a reason to use unresolved references, and it will help us avoid making the utility in https://github.com/salto-io/salto/pull/4914 async
---
This was not an issue until now because the `reference_annotation` filter runs very late and so we never tried to access the references it creates. But if we want to create generic utilities to access the contents of the REFERENCE_TO annotation, we need them to be resolved.
---
N/A
---
N/A
> SALTO-4846 - Salesforce: make all references in REFERENCE_TO resolved

- packages/adapter-api/src/change.ts
- packages/adapter-api/src/elements.ts
- packages/adapter-components/src/add_alias.ts
- packages/core/src/api.ts
- packages/core/test/api.test.ts
- packages/netsuite-adapter/src/client/types.ts
- packages/netsuite-adapter/src/reference_dependencies.ts
- packages/netsuite-adapter/src/suiteapp_config_elements.ts
- packages/netsuite-adapter/src/transformer.ts
This API is similar to `calculatePatch`, except it gets a list of changes, a workspace and a path index (to split the changes into fragments) - and calculates the fetch changes of the patch, including conflicts (where the value in the workspace is different from the value in the changes' `before`).
---
---
Core:
- Add calculatePatchFromChanges API
---
None
> SALTO-4804 Add calculatePatchFromChanges API

- packages/core/src/core/fetch.ts
- packages/workspace/index.ts
- packages/workspace/src/path_index_fallbacks.ts
- packages/workspace/test/common/workspace.ts
- packages/workspace/test/path_index_fallbacks.test.ts
- packages/workspace/test/workspace/workspace.test.ts
extract into a workspace API the code that we use in fetch-from-workspace for creating a path index for elements that aren’t in the state.
NOTE: this API can be removed when we do the fragment refactor.
---
---
Workspace:
- create path index for element API
---
None
> SALTO-4863 create path index for element

- packages/core/src/local-workspace/adapters_config.ts
- packages/core/src/local-workspace/workspace.ts
- packages/core/test/workspace/local/adapters_config.test.ts
- packages/core/test/workspace/local/workspace.test.ts
- packages/workspace/index.ts
- packages/workspace/src/workspace/static_files/index.ts
- packages/workspace/src/workspace/static_files/static_files_cache.ts
- packages/workspace/test/workspace/static_files/static_files_cache.test.ts
First step of SAAS-6359: Move static_file_cache to `workspace` package,  remove migration code, and remove `local` prefix from it
---
---
None
---
none
> SAAS-6359: Move static files cache from core to workspace package

- packages/core/src/api.ts
- packages/core/test/api.test.ts
- packages/core/test/common/workspace.ts
In the `calculatePatch` & `calculatePatchFromChanges` APIs we currently return removal changes on hidden values-
If the patch includes an addition of an element (without hidden values in it, since it’s coming from PR/SAAS change) and it is already exists in the workspace, we’ll have removal changes on the hidden fields/annotations of the element- like `internalId`, `_service_url` etc.
The reason is that we’re calling `calcFetchChanges` with `workspace.elements()` for the `workspaceElements` param- which includes the hidden values from the state in it. The problem is that for `stateElements`&`accountElements` we’re passing the PR’s elements, that doesn’t have hidden values in them- and the result is having removal changes on the hidden values.
IMO we should call `calcFetchChanges` with …
> SALTO-4869 ignore hidden values on calculatePatch

- packages/zendesk-adapter/src/client/connection.ts
- packages/zendesk-adapter/test/adapter_creator.test.ts
always default the subdomain to zendesk.com when not provided
---
* Fix bug when using the OAuth credentials flow that required providing a domain argument
---
None
> SALTO-4870 always default domain to zendesk.com

- packages/jira-adapter/src/filters/workflow/conditions_types.ts
- packages/jira-adapter/src/filters/workflow/workflow_structure_filter.ts
- packages/jira-adapter/test/filters/workflow/workflow_structure_filter.test.ts
Added missing annotation to workflow
---
- Fixed a bug where workflow transition configuration would not be deployed
---
None
> SALTO-4872: workflow transition changes are not deployed 

- packages/okta-adapter/src/client/client.ts
Added a buffer for the rate limit reset, in case okta rounds down the reset time in the headers
also added an endpoint that is rate limited but not documented
---
None
---
None
---
None
> SALTO-4350 - Added buffer and an rate limited endpoint

- packages/salesforce-adapter/src/change_validators/multiple_defaults.ts
- packages/salesforce-adapter/test/change_validators/multiple_defaults.test.ts
The CV code assumes that if a field exists in an instance it also exists in the type of the instance. This is not necessarily the case.
---
I chose to just not run the validator on fields that do not exist in the type, under the assumption that the deploy will fail anyway.
---
Salesforce: fixed a crash if fields with certain names were created in instances whose types did not include said fields.
---
N/A
> SALTO-4882 - Salesforce: multiple_defaults CV crashes if instance has a field that's missing from its type

- packages/jira-adapter/src/filters/layouts/issue_layout.ts
Fixing incident that can be viewed in [dataDog](https://app.datadoghq.com/logs?query=%40operationId%3Aeb920232-a15a-40f4-ba98-85d88f889aa6%20all%20merge%20errors%20&cols=host%2Cservice&event=AgAAAYs3J2RqNrXPkQAAAAAAAAAYAAAAAEFZczNKMjl0QUFBajFoUEdIZWZGc0FCMwAAACQAAAAAMDE4YjM3NjEtNGVlMy00MTYzLTg1NTEtODJhYjA3YTdiZTE5&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1697437247087&to_ts=1697437435348&live=false).
---
None
---
Fixing bug in issue layouts that causes to duplicate elemIDs.
---
None
> SALTO-4891: Fixing issue layouts duplicates

- packages/jira-adapter/src/filters/layouts/issue_layout.ts
- packages/jira-adapter/test/filters/layouts/issue_layout.test.ts
In this PR I added service urls to the issue layouts through the filter. 
---
None.
---
Added service Url to issue layouts. 
---
You will see service url in your issue layouts nacls upon your next fetch.
> SALTO-4892: Add service url to issue Layouts

- packages/adapter-components/src/filters/referenced_instance_names.ts
- packages/zendesk-adapter/src/filters/article/utils.ts
add initialization to article attachment hash
---
---
zendesk:
* when using `&hash` in the `article_attachment` idFields, if the hash field does not exist it will add to the `elemId` the string `INVALID_HASH`
---
None
> SALTO-4897: add initialization to article attachment hash

- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/reference_mapping.ts
In this PR I support fetching of workflow statuses
---
None
---
Now supports Workflow statuses in JSM. 
---
JSM RequestType will now have new field - workfowStatuses.
> SALTO-4854: Fetch WorkflowStatuses

- packages/okta-adapter/src/config.ts
Default page size was 20 for apps and 50 for rules, changed both to 200 (which is the maximum value supported)
---
None
---
None
> SALTO-4887: Increase page size for group rules and apps in Okta

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/filters/change_portal_group_fields.ts
- packages/jira-adapter/src/filters/jsm_types_deploy_filter.ts
- packages/jira-adapter/src/filters/portal_groups.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/test/filters/change_portal_group_fields.test.ts
- packages/jira-adapter/test/filters/jsm_types_deploy_filter.test.ts
- packages/jira-adapter/test/filters/portal_groups.test.ts
In this PR I added:
1. Changed portal group fetch to include current request types.
2. Omited groups from request types. 
3. Support for deployment of portal group. 
4. Support for addition of id in addition change. 
---
None
---
Now supports deployment of portal groups. 
---
None
> SALTO-4833: Initial deploy portal group

- packages/zendesk-adapter/e2e_test/adapter.test.ts
Removing the warning from the e2e test
---
This comes with enabling the missing custom_statuses feature in the service
---
None
---
None
> SALTO-4898 - Remove fetch warning from e2e

- packages/zendesk-adapter/src/change_validators/automation_all_conditions.ts
fix automation all condition validator to include custom_status_id
---
---
None
---
None
> SALTO-4906: fix automation all condition validator to include custom_status_id

- packages/jira-adapter/src/filters/screen/screen.ts
- packages/jira-adapter/test/filters/screen/screen.test.ts
_fix a bug in screenTab fields with missingReference_
---
* currently we have a change validator that prevents missing references in the `after` instance
* if the change is a modification, the screen filter uses the `before` instance fields, so we got an error because it is a missing reference.
* I added a hidden value that stores the original fields ids and a `preDeploy` operation to the screen filter that uses the original fields ids in order to prevent this error.
---
_None_
---
_None_
> SALTO-4905: fix a bug in screenTab fields with missingReference - Jira

- packages/okta-adapter/src/config.ts
Default page size is 20, but the maximum is 200. This should help in big environments to avoid reaching rate limits and make less requests 
---
None
---
None
> SALTO-4887: Increase page size for app-group assignments

- packages/jira-adapter/e2e_test/instances/cloud/index.ts
Deployment of instances from this type is causing flakiness
removing for now until we figure out why it's happening
---
---
None
---
None
> SALTO-4915: Remove scriptedFields type from Jira E2E

- packages/jira-adapter/src/weak_references/automation_projects.ts
- packages/jira-adapter/test/weak_references/automation_projects.test.ts
Fixed automation weak references function
---
I missed a case where the automation does not have a project field
---
None (no effect on the user)
---
None
> SALTO-4818: Failed to get custom references for jira: TypeError: Cannot read properties of undefined

- packages/salesforce-adapter/src/adapter.ts
in `fetch` code inside the SF adapter, we have created 2 promises, and await only the first(metadatatypes)
In the specific use-case described in SAAS-9321, the first promise rejects(and rightfully so, due to invalid credentials)
And the whole fetch handler is returned, however, a few millis after, the second promise(as far as I believe, rejects as well)
And since it's un-handled, crashes the APP with a non zero exit code.
My Suspicion ( did not 100% prove this, as the docs say otherwise, but Im probably missing something here ? ):
In older versions of node, the following error was thrown
`(node:31727) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit …
> SAAS-9321: Await types promise before creating the metadataInstancesPromise

- packages/zendesk-adapter/src/change_validators/guide_disabled.ts
- packages/zendesk-adapter/src/change_validators/guide_order/order_children_parent_validator.ts
- packages/zendesk-adapter/src/change_validators/utils.ts
- packages/zendesk-adapter/test/change_validators/guide_disabled.test.ts
* Prevent crashing in case an instance's brand doesn't exists
* remove error log if guide order instance is empty
---
None
---
* Fix crash on deployment of a guide instance without a brand
---
None
> INCIDENT-9318 - Don't crash on missing brand

- packages/jira-adapter/e2e_test/instances/cloud/index.ts
- packages/jira-adapter/e2e_test/instances/cloud/scriptrunner/scripted_fields.ts
fix `Full error from the logs: Search term is already being used by another scripted field` by randomizing the search term as well
---
None
---
None
> SALTO-4915 fix jira scriptedFields e2e flakiness

- packages/okta-adapter/src/client/connection.ts
- packages/okta-adapter/test/adapter_creator.test.ts
Added another account type - dev account
all preview accounts (regular and dev) will be marked as preview, dev accounts that are not preview will be marked as dev, and the others as production.
---
None
---
None
> SALTO-4922: Mark dev accounts as non production in Okta

- packages/adapter-api/src/adapter.ts
- packages/salesforce-adapter/src/client/client.ts
- packages/salesforce-adapter/test/client.test.ts
SAAS-2351 add instanceUrl as accountId to validateCredentials response for SF sandbox
---
Salesforce:
validateCredentials on Sandboxes will now return the organization url as a stable accountId and will include extraProperties with the Organization Id
---
None
> SAAS-2351 add instanceUrl as accountId to validateCredentials response for SF sandbox

- packages/zendesk-adapter/src/filters/utils.ts
- packages/zendesk-adapter/test/filters/utils.test.ts
Revert the missing instance id to the original, before SALTO-4807 change
---
None
---
None
---
None
> SALTO-4807 - fix mischange

- packages/zendesk-adapter/config_doc.md
- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/handle_template_expressions.ts
- packages/zendesk-adapter/test/filters/handle_template_expressions.test.ts
In free text fields, if the value is a JSON, and there is a key named 'id' with a number value - attempt to convert it to reference expression
---
No noise reduction needed because this is behind a config
---
* Added `convertJsonIdsToReferences` config, that allows convert of JSON pairs of 'id' to reference expression
---
None
> SALTO-4808 - Convert JSON pairs of 'id' to reference expression

- packages/adapter-components/src/elements/type_elements.ts
- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/test/adapter.test.ts
Reduce the noise in the logs - 
1. reduce level to `debug` if field is not defined
2. relax restrictions in zendesk to not expect a specific type for the default-hidden fields, since there is sometimes inconsistency between string/number that causes the field type to be unknown and we should still hide it in this case
3. assign a few more field types with `fieldTypeOverrides` since they don't always exist
---
None
---
None
> SALTO-4717 reduce log level to debug in some cases, relax zendesk restrictions

- packages/jira-adapter/src/config/config.ts
Added enableJsmExperimental flag
---
We are planning to release JSM to customers. 
For not expose them to JSM elements that are being developed, I added another flag called `enableJsmExperimental`.
The customers will be able to use jsm when `enableJSM = true`. And after each type will be approve it will change from `enableJsmExperimental=true` to `enableJSM=true`
---
None
---
None
> SALTO-4923: Added flag for enableJsmExperimental

- packages/zendesk-adapter/src/change_validators/ticket_form_default.ts
- packages/zendesk-adapter/test/change_validators/ticket_form_default.test.ts
Change the handling of changing the default ticket form
* Prevent changing two ticket forms to be the default
* Warn that the current default will be set as not default
---
None
---
* No longer prevents deployment of a a new default ticket form if the current default is not changing
---
None
> SALTO-4753 - Change handling of changing the default ticket form

- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/test/adapter.test.ts
We were passing the timeZone&format to filtersRunner only in case of `useChangesDetection=true`, but we should always pass it. It caused the author_information/saved_searches filter to skip the query.
---
---
- Fix bug - saved searches author information query is skipped in full fetch
---
None
> Saved searches author information query is skipped in full fetch

- packages/zendesk-adapter/src/filters/guide_order/guide_order_utils.ts
- packages/zendesk-adapter/src/filters/reorder/creator.ts
- packages/zendesk-adapter/src/filters/reorder/trigger.ts
- packages/zendesk-adapter/test/filters/guide_orders.test.ts
- packages/zendesk-adapter/test/filters/reorder/automation.test.ts
- packages/zendesk-adapter/test/filters/reorder/trigger.test.ts
- packages/zendesk-adapter/test/filters/reorder/view.test.ts
Add gaps to order positions, to start from 100 and go up by 100 (100, 200, 300)
---
Changed only the types where the position updates by element
Types that are updated as a whole (reorder API) are not changed
---
* Added gaps to elements positions of triggers, automations and views
---
None
> SALTO-4654 - Zendesk Adapter - Add gaps to order positions

- packages/jira-adapter/e2e_test/adapter.test.ts
I added another project to jira test account of type JSM. 
Due to this addition, I needed to modify the jira E2E tests. 
---
None
---
None
---
None
> SALTO-4946: Fixed jira E2E test 

- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/src/client/types.ts
- packages/netsuite-adapter/src/client/utils.ts
- packages/netsuite-adapter/src/filters/additional_changes.ts
- packages/netsuite-adapter/src/filters/element_references.ts
- packages/netsuite-adapter/src/service_id_info.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/netsuite-adapter/test/client/client.test.ts
- packages/netsuite-adapter/test/filters/additional_changes.test.ts
We are currently considering a referenced SDF object as a dependency only in case that the referenced object was added. We should also consider it a dependency when the reference is to an inner object/field (`customworkflow123.customstate123` / `customrecord123.custfield123`), that was added (although the whole object was modified).
In order to do that:
- in `additional_changes` filter - set the `before` of an added fields parent to be without the added fields.
- move logic of extracting inner objects from `element_references` filter to `service_id_info`.
- use the above logic to find the added objects in a modified SDF object.
---
---
- Fix SDF deploy dependencies when referencing an added inner object/field
---
_User …
> SALTO-4919 Fix SDF deploy dependencies when referencing an added inner object/field

- packages/jira-adapter/src/filters/workflow/workflow_deploy_filter.ts
- packages/jira-adapter/test/filters/workflow/workflow_deploy_filter.test.ts
_add workflow deletion before second attempt of workflow deployment_
---
---
_None_
---
_None_
> SALTO-4944: add workflow deletion before second attempt of workflow deployment 

- packages/zendesk-adapter/src/filters/field_references.ts
Add zendeskMissingRefStrategy to orgField
---
None
---
* added missing reference to missing organizations in trigger, automation, sla_policy and ticket_field
---
None
> SALTO-4774 - Zendesk Adapter - Add missing reference strategy for orgField

- packages/zendesk-adapter/src/filters/handle_template_expressions.ts
A link can now start with a '/' and still be converted
---
None
---
None
---
None
> SALTO-4807 - Zendesk Adapter - catch urls with both and without initial '/'

- packages/cli/e2e_test/helpers/salesforce.ts
- packages/salesforce-adapter/e2e_test/adapter.ts
- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/adapter_creator.ts
- packages/salesforce-adapter/test/adapter.creator.test.ts
- packages/salesforce-adapter/test/adapter.discover.test.ts
- packages/salesforce-adapter/test/adapter.ts
Moved the creation of the fetchProfile from the SalesforceAdapter constructor  to the operations themselves.
---
This is a necessary refactor, since in https://github.com/salto-io/salto/pull/5030 the **fetchProfile** receives the promise of **relatedPropsByMetadataType** that should only start executing in fetch, and not in the creation of the adapter. (As we invoke client calls there).
We should never leave hanging promises that won't be necessarily awaited in our code.
---
_None_
---
_None_
> SALTO-4727: Remove creation of the fetchProfile from the SalesforceAdapter constructor  

- packages/zendesk-adapter/src/filters/handle_template_expressions.ts
- packages/zendesk-adapter/test/filters/handle_template_expressions.test.ts
Make prepRef default to be the instance's id, to prevent returning [Object, object] by mistake
---
This is the default exists in the other 2 prepRefs
---
None
---
None
> SALTO-4947 - Zendesk - handle_template_expression - default prepRef result to instance's id

- packages/okta-adapter/src/config.ts
Make okta config options visible in the adapter's nacl
---
We recently added many config options to Okta. Making those visible will make it easier to CE to follow.
Only changed config options that I believe can be useful in first fetch
The new adapter config default - 
```
okta {
fetch = {
include = [
{
type = ".*"
},
]
exclude = [
]
convertUsersIds = true
includeGroupMemberships = false
includeProfileMappingProperties = true
}
}
```
---
---
_Replace me with a short sentence that describes changes that will appear in NaCls and are not caused by user actions (e.g. a new annotation, field values that are converted to references, etc). Hidden changes should not …
> SALTO-4925: Make okta config options visible in the adapter's nacl

- packages/salesforce-adapter/src/filters/custom_object_instances_references.ts
- packages/salesforce-adapter/src/filters/custom_objects_instances.ts
- packages/salesforce-adapter/src/filters/utils.ts
- packages/salesforce-adapter/test/filters/custom_object_instances_references.test.ts
- packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
- packages/salesforce-adapter/test/filters/utils.test.ts
Looks like there's another type of lookup field called `Hierarchy` that is used for self references
~**NOTE:** This PR builds on top of https://github.com/salto-io/salto/pull/4938~
---
Tests:
- Fetched and verified Hierarchy fields show as references instead of the raw internal ID.
---
Salesforce: Hierarchy fields in data records are now treated as references
---
N/A
> SALTO-4815 - Salesforce: Handle hierarchy fields as references in data records

- packages/jira-adapter/e2e_test/instances/datacenter/automation.ts
- packages/jira-adapter/src/filters/automation/automation_structure.ts
- packages/jira-adapter/test/filters/automation/automation_structure.test.ts
_Fail to deploy global automation in Jira DC_
---
* it was caused by this [change](https://github.com/salto-io/salto/pull/4885) that affected only cloud users.
* I added a simple change that removes the project list when it's empty to align with the cloud behavior.
---
Jira Adapter: 
* fix a bug in deploying global Automation using Jira DC
---
_None_
> SALTO-4964: Fail to deploy global automation in Jira DC

- packages/zendesk-adapter/src/filters/reorder/creator.ts
use the custom filter name for reorder filters so that we can distinguish between them in the logs
---
None
---
None
> SALTO-4962 use correct filter name

- packages/salesforce-adapter/config_doc.md
- packages/salesforce-adapter/src/fetch_profile/data_management.ts
- packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts
- packages/salesforce-adapter/src/filters/custom_objects_instances.ts
- packages/salesforce-adapter/src/filters/utils.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
When the user fetches data records that have some non-queryable fields, the result may be fear, uncertainty and confusion during deploy - the fields will be deployed as deleted.
Let's warn the user about fetching data records with inaccessible fields. But not if they're hidden, since the user can't see them anyway.
---
---
Salesforce: Warn when fetching data records with non-queryable fields.
---
N/A
> SALTO-4652 - Salesforce: add a fetch warning for custom fields that are not queryable

- packages/zendesk-adapter/src/filters/article/article.ts
- packages/zendesk-adapter/src/filters/article/article_body.ts
- packages/zendesk-adapter/src/filters/custom_field_options/creator.ts
- packages/zendesk-adapter/src/filters/custom_objects/custom_object_fields.ts
- packages/zendesk-adapter/src/filters/custom_statuses.ts
- packages/zendesk-adapter/src/filters/macro_attachments.ts
- packages/zendesk-adapter/src/filters/ticket_form.ts
Adding early returns in a few filters to avoid doing unneeded work.
The motivation for this was an OOM we saw for macro deployments, that seems to at least be partially caused by attempting to initialize the element source many times in parallel, likely for the `ticketFormDeploy`'s `isCustomStatusesEnabled` call - but using this to remove some other cases as well (focusing for now on the ones that do not require a bigger refactor).
(besides this, we should also investigate the issue directly in the element source, but starting with a mitigation)
---
* Fix potential crash on large deployments due to memory consumption
---
None
> SALTO-4961 Zendesk - return early in irrelevant filters, avoid too many concurrent calls to element source

- packages/workspace/src/element_adapter_rename.ts
- packages/workspace/src/workspace/elements_source.ts
- packages/workspace/test/workspace/element_adapter_rename.test.ts
The code did not handle the case where there was an unresolved type referece to a container type, it only worked for resolved type references.
---
This can cause an infinite loop when trying to resolve an element because when resolving types we would try to get the element using its original name and the element source would replace it, so we'd never get the type we need in order to resolve (see INCIDENT-8902 for more details)
---
Core:
- Fixed issue where fetching with a non-default account name could get stuck
---
_None_
> SALTO-4991: Fix account/adapter name replace for container types

- packages/okta-adapter/src/filters/group_push.ts
- packages/okta-adapter/test/filters/group_push.test.ts
Okta doesn't support fetching `GroupPushRule` for apps in status inactive. currently fetch fails for environments that contains this (we get 400). This fix is to avoid fetching this for inactive apps. 
---
---
_Okta_adapter_: 
- Fix issue with fetch when environment contains inactive apps with Group Push enabled
---
None
> SALTO-4992: Fetching Group Push Rules for inactive apps fails fetch

- packages/workspace/src/expressions.ts
- packages/workspace/test/core/expressions.test.ts
In the previous fix of this issue we hopefully took care of the bug in the element source. But even so, and just in case there is another such issue somewhere else or in the future adding another layer of protection against cases that should never happen
---
no release notes here since this should not solve any issue, the issue was supposed to be fixed by the previous commit
---
_None_
---
_None_
> SALTO-4991: Avoid infinite loop in resolve elem source has a bug

- packages/salesforce-adapter/config_doc.md
I made an oopsie
---
---
N/A
---
N/A
> SALTO-4983 - Salesforce: remove conflict markers from config doc

- packages/salesforce-adapter/src/change_validators/unknown_users.ts
- packages/salesforce-adapter/src/custom_object_instances_deploy.ts
- packages/salesforce-adapter/src/filters/author_information/data_instances.ts
- packages/salesforce-adapter/src/filters/custom_objects_instances.ts
- packages/salesforce-adapter/src/filters/utils.ts
- packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
Make it possible to run range-based queries in addition to exact-match queries. If the query is too long and has to be broken into multiple queries, make sure the range-based queries are appended to every query that is created, to maintain the expected behavior.
---
**PR Chain**:
- https://github.com/salto-io/salto/pull/4961 👈 YOU ARE HERE 👈 
- https://github.com/salto-io/salto/pull/4964
- https://github.com/salto-io/salto/pull/4965
---
N/A
---
N/A
> SALTO-4881 - Salesforce: Support more complex SOQL queries

- packages/okta-adapter/src/change_validators/app_with_group_push.ts
- packages/okta-adapter/src/change_validators/index.ts
- packages/okta-adapter/src/config.ts
- packages/okta-adapter/src/filters/group_push.ts
- packages/okta-adapter/test/change_validators/app_with_group_push.test.ts
Before addition of `GroupPush` or `GroupPushRule`, we should verify the associated app enabled Group Push feature
---
None
---
None
> SALTO-4901: Verify parent app supports group push

- packages/core/src/app_config.ts
- packages/core/src/core/adapters/adapters.ts
- packages/core/src/core/fetch.ts
- packages/core/src/core/flags.ts
- packages/core/test/core/flags.test.ts
- packages/test-utils/src/index.ts
- packages/test-utils/src/setup_envvar.ts
- packages/test-utils/test/setup_envvar.test.ts
added env var `SALTO_DISABLE_RESOLVE_TYPES_IN_ELEMENT_SOURCE` that allows skipping resolving types to be used in case of an emergency if we find this resolve is a problem
---
---
- Added environment flag `SALTO_DISABLE_RESOLVE_TYPES_IN_ELEMENT_SOURCE` that allows turning off type resolving in fetch / deploy
---
_None_
> SALTO-4981: add env var that controls if we resolve types

- packages/jira-adapter/src/change_validators/field_contexts/second_global_context.ts
- packages/jira-adapter/test/change_validators/field_contexts/second_global_context.test.ts
_expand secondGlobalContext CV for handling invalid removals of contextFields from a project_
---
* we already have a change validator for second global context (which is forbidden in Jira)
* the scenario: when we remove a fieldContext from a project it implicitly becomes a global context, if there is another global context the service fails this change.
---
_None_
---
_None_
> SALTO-4896: expand secondGlobalContext CV for handling invalid removals of contextFields from a project - Jira

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/filters/layouts/layout_service_operations.ts
- packages/jira-adapter/src/filters/layouts/layout_types.ts
- packages/jira-adapter/src/filters/layouts/request_types_layouts_to_values.ts
- packages/jira-adapter/src/filters/request_type.ts
- packages/jira-adapter/test/filters/request_type.test.ts
In this PR I support deploy of request type. 
---
Request types have several endpoints:
1. For request forms, which also include request type name, description, and help text.
2. For the issue view.
3. For workflow statuses.
4. For groups.
Please review only from commit number 3 - 28b73c4efd87e8cbfe0d2371dc0df208a9c37892. 
---
We are now providing support for the deployment of request types.
---
None
> SALTO-4850: Support deploy of request Type 

- packages/salesforce-adapter/src/filters/utils.ts
Lower log level of duplicate file props in SF
---
This happens on every fetch for installed packages and is confusing readers of the log when it is a warn. Lowered to debug.
---
None.
---
None.
> SALTO-5000 - Lower log level of duplicate file props in SF

- packages/okta-adapter/e2e_test/mock_elements.ts
Okta now returns `signOnMode` field 2 places
---
---
None
---
None
> SALTO-5012: Okta e2e fails due to structure change in Application values

- packages/zendesk-adapter/src/change_validators/default_dynamic_content_item_variant.ts
- packages/zendesk-adapter/test/change_validators/default_dynamic_content_item_variant.test.ts
Add validation of dynamic content without default
---
---
__Zendesk__
* Add validation to prevent addition of a dynamic content with no default variant.
---
> SALTO-4759 Add validation of dynamic content without default

- packages/adapter-components/src/filters/index.ts
- packages/adapter-components/src/filters/query.ts
- packages/adapter-utils/src/collisions.ts
- packages/zendesk-adapter/src/filters/collision_errors.ts
- packages/zendesk-adapter/test/adapter.test.ts
- packages/zendesk-adapter/test/filters/collision_errors.test.ts
remove child elements if their parent is omitted due to id collision
---
---
zendesk:
- child elements will be omitted when their parent is omitted due to elemId collision
---
> SALTO-4980:  remove child elements if their parent is omitted due to id collision

- packages/jira-adapter/e2e_test/adapter.test.ts
- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/constants.ts
- packages/jira-adapter/src/filters/forms/forms.ts
- packages/jira-adapter/src/filters/forms/forms_types.ts
- packages/jira-adapter/src/filters/jsm_paths.ts
- packages/jira-adapter/src/filters/jsm_types_deploy_filter.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/test/adapter.test.ts
- packages/jira-adapter/test/filters/forms/forms.test.ts
In this PR I started to support fetch of forms. 
I also added support for deploy to check that the fetch and deploy is multienv friendly. 
---
Please Review from [initial forms fetch support](https://github.com/salto-io/salto/commit/81a7768780bb2beaea8ead9f3a99ff950c17b558) and any sub commit. 
---
Now supporting fetch  and deploy operations for Form.
---
_JIra Adapter_:
You can now fetch and deploy Forms in JSM.
> SALTO-2349: Fetch and deploy Forms 

- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts
the beginning of the error message is different per account language, so it prevents us from detecting that error. removing the language-specific text should be safe. 
---
---
None
---
None
> Fix missing feature error detector in suiteapp file cabinet fetch

- packages/netsuite-adapter/src/filters/data_instances_references.ts
in case that `value` was `null` as exception was thrown: `TypeError: Cannot read properties of null (reading 'internalId')`
---
---
None
---
None
> Fix null error in NS

- packages/zendesk-adapter/src/config.ts
update fetch warning about unknown author id
---
---
zendesk:
* When the 'author_id' in articles is a numerical value, we will no longer generate a fetch warning.
---
None
> SALTO-4283: update fetch warning about unknown author id

- packages/core/src/api.ts
- packages/core/test/api.test.ts
Add a flag to preview core API that allows skipping the change validators in `getPlan`.
---
---
Core:
- Add skipValidations flag to preview API
---
None
> SALTO-5009 Add skipValidations flag to preview API

- packages/adapter-components/src/elements/ducktype/standalone_field_extractor.ts
- packages/adapter-components/src/elements/ducktype/transformer.ts
- packages/adapter-components/test/elements/ducktype/standalone_field_extractor.test.ts
Added support for nestedPath in duckType when we recurse tInto.
---
None
---
None
---
None
> SALTO-5019: Support nestedPath in ducktypes

- packages/core/src/core/adapters/adapters.ts
- packages/core/src/core/fetch.ts
The original implementation was meant to only [affect fetch operations](https://salto-io.atlassian.net/browse/SALTO-4517?focusedCommentId=93101) Since it uses a cache, it must not be used in deploy where the underlying element source changes
---
We haven't seen a bug directly from the original reason why this shouldn't be used in deploy, but we did see a possibly related bug in zendesk deployments.
we should still get to the bottom of the the possibly related bug probably, but changing the implementation here because regardless of the other bug, caching elements in deploy could lead to incorrect behavior when deploying ObjectType elements
---
_None_
---
_None_
> SALTO-4517: only resolve types in fetch, not in deploy

- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/support_address.ts
- packages/zendesk-adapter/test/filters/support_address.test.ts
allow idFields fro support address to be username of email
---
---
zendesk:
* It is possible to add the email username as idField for support_address using `&username`.
---
None
> SALTO-5024: allow idFields fro support address to be username of email

- packages/jira-adapter/e2e_test/adapter.test.ts
- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/workspace_id.ts
In this PR I support fetching assets schema using the infrastructure. 
---
In order to fetch assets schema I need to have `workspaceId`. 
Only users who purchased Assets will have workspaceId. 
---
_JIra Adapter:_
Now support fetching of assets schemas. 
---
_JIra Adapter:_
Now support fetching of assets schemas.
> SALTO-4986: Support getting workspaceId and fetching assests schema

- packages/jira-adapter/e2e_test/adapter.test.ts
- packages/jira-adapter/src/config/api_config.ts
In this PR I added support for fetching assets statuses. 
---
Please review only the last commit "assets statuses". Only added a type in api_config.ts
---
Now supporting fetch of assets statuses. 
---
Now supporting fetch of assets statuses.
> SALTO-4986: Add assets statuses

- packages/zendesk-adapter/src/filters/article/article_body.ts
- packages/zendesk-adapter/src/filters/custom_objects/utils.ts
- packages/zendesk-adapter/src/filters/handle_template_expressions.ts
- packages/zendesk-adapter/src/filters/side_conversation.ts
- packages/zendesk-adapter/test/filters/side_conversation.test.ts
fix side conversation group template expression
---
---
zendesk:
* remove empty strings from side conversation group template expressions
---
None
> SALTO-5030: fix template expressions in zendesk

- packages/workspace/src/workspace/state/static_files_sources/history_static_files_source.ts
Log lines in history static files source get written per-file and are not that interesting especially given the logs are about the code not doing anything
---
---
_None_
---
_None_
> SALTO-5045: move spamming debug log to trace

- packages/netsuite-adapter/config_doc.md
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/config.ts
- packages/netsuite-adapter/src/filters/exclude_by_criteria.ts
- packages/netsuite-adapter/src/filters/exclude_by_criteria/exclude_custom_record_types.ts
- packages/netsuite-adapter/src/filters/exclude_by_criteria/exclude_instances.ts
- packages/netsuite-adapter/src/query.ts
- packages/netsuite-adapter/test/config.test.ts
- packages/netsuite-adapter/test/filters/exclude_by_criteria.test.ts
- packages/netsuite-adapter/test/query.test.ts
- packages/netsuite-adapter/test/utils.ts
Add the ability to exclude elements using the `criteria` config.
---
TODO:
---
- Support excluding elements by criteria (e.g `isinactive = true`)
```
netsuite {
...
exclude = {
...
types = [
...
{
name = ".*"
criteria = {
isinactive = true
}
},
]
}
}
```
---
None
> SALTO-1590 support exclude by criteria in netsuite

- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/filters/custom_object_instances_references.ts
- packages/salesforce-adapter/src/filters/utils.ts
- packages/salesforce-adapter/src/transformers/reference_mapping.ts
- packages/salesforce-adapter/test/filters/custom_object_instances_references.test.ts
- packages/salesforce-adapter/test/transformers/reference_mapping.test.ts
In the package `Field Service Lightning` we have custom objects instances that reference instances of metadata types. Our current code complains of invalid references, because we only look up reference targets among instances of custom objects.
So let's make a distinction between potential reference sources (only custom object instances) and potential reference targets (all instances).
---
~This relies on instances of metadata types having an `Id` field. I haven't tested this yet.~
Please note the code that gets the internal ID for both custom objects and metadata instances.
Tests:
- Fetch and observe a reference created in the `SkillId` field of an instance of `ServiceResourceSkill`
- Deploy an instance that contains a reference to a metadata instance
---
Salesforce: …
> SALTO-4814 - Salesforce: Consider metadata instances as potential lookup targets

- packages/salesforce-adapter/src/fetch_profile/metadata_query.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/fetch_profile/metadata_query.test.ts
Required step for fetch with changes detection on **Profiles** and **Nested Instances**
---
You can already see usage of this code in this PR: https://github.com/salto-io/salto/pull/5109
---
_None_
---
_None_
> SALTO-5068: Salesforce FileProperties Metadata Query

- packages/core/src/core/diff.ts
It can only be used when elementSelectors are provided, and since elementSelectors is optional, this should be as well.
---
---
None
---
None
> SAAS-9617: Make referenceSourcesIndex optional

- packages/zendesk-adapter/src/filters/article/article_body.ts
- packages/zendesk-adapter/test/filters/article/article_body.test.ts
Handle unresolved references when resolving template expressions
---
---
zendesk:
* Avoid crushing when resolving an article_body template expression with an unresolved reference
---
None
> SALTO-5074: Handle unresolved references when resolving template expressions

- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/fetch.ts
- packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/adapter.discover.test.ts
Required step for fetch with changes detection on Profiles. 
---
_None_
---
_None_
> SALTO-5070: Move Salesforce retrieve settings into the Fetch Profile

- packages/jira-adapter/src/filters/layouts/layout_queries.ts
- packages/jira-adapter/src/filters/layouts/layout_service_operations.ts
- packages/jira-adapter/src/filters/layouts/layout_types.ts
- packages/jira-adapter/src/filters/request_type.ts
- packages/jira-adapter/test/filters/layouts/issue_layout.test.ts
- packages/jira-adapter/test/filters/layouts/request_type_request_form.test.ts
- packages/jira-adapter/test/filters/request_type.test.ts
In this PR I added the filter that retrieves the issueLayout, issueView and requestForm. 
---
1. Convex feedback told me that they need the metadata of each field. 
2. I added the metadata request part to the graphQL body. 
3. Most of the changes are in the query and in the tests and only little bit of change are core code changes. 
---
_JIra adapter:_
Now supporting metadata of fields in  issueLayout, issueView and requestForm. 
---
Under  issueLayout, issueView and requestForm, there will be more fields upon your next fetch.
> SALTO-5081 Added more fields in requestForm, issueView and issueLayout

- packages/zendesk-adapter/src/adapter.ts
Avoid iterating all workspace IDs multiple times when deploying guide changes
---
---
---
> SALTO-5058: Avoid iterating all workspace IDs multiple times when deploying guide changes

- packages/salesforce-adapter/src/client/client.ts
- packages/salesforce-adapter/test/adapter.discover.test.ts
- packages/salesforce-adapter/test/client.test.ts
This PR adds caching on the results of **listMetadataObjects**.
---
Main reason for this caching is the fact we have some MetadataTypes we list more than once, especially in **fetch with changes detection mode**. Listing types can be time consuming, depending on the amount of **Instances** per type. It's widely noticeable around **CustomFields** and **CustomObjects**.
---
_None_
---
_None_
> SALTO-4968: Cache Salesforce Client listMetadataObjects results

- packages/cli/test/command_builder.test.ts
- packages/cli/test/commands/deploy.test.ts
- packages/core/src/local-workspace/state.ts
- packages/core/test/workspace/local/state.test.ts
- packages/file/package.json
- packages/file/src/gzip.ts
- packages/file/test/gzip.test.ts
- packages/workspace/package.json
- packages/workspace/src/workspace/state/in_mem.ts
- packages/workspace/src/workspace/state/state.ts
- packages/workspace/test/workspace/workspace.test.ts
Cleaning up the code before working on new features in the area
This also contains a couple of unit test fixes in other packages
---
---
Core:
- Removed code that would migrate very old state files to the "new" format - this would only affect workspaces that were not used for over 10 months
---
_None_
> SALTO-5086: remove old state migration code

- packages/salesforce-adapter/src/custom_object_instances_deploy.ts
- packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
- packages/salesforce-adapter/test/mock_elements.ts
Fixed an edge-case where the deploy of group `add_Custom_ApprovalRule_and_ApprovalCondition_instances` fails when the **salto Id fields** of **Approval Conditions** contain **Approval Rule**
---
- Add deploy support in **CPQ Custom Approval Rule and Conditions** for accounts that use the old **Salto ID Settings** (non Id based).
---
_None_
> SALTO-4963: Custom Approval Rule And Conditions using Salto ID Setting bugfix

- packages/adapter-components/src/filters/referenced_instance_names.ts
- packages/adapter-components/test/filters/referenced_instance_name.test.ts
After instance is being renamed in `referencedInstanceNames`, we look for all its references and update them to include the new elemID. Until now we only updated the reference `elemID` and left the old res value instead of updating as well.
---
---
None
---
None
> SALTO-5092: Fix bug in reference update for renamed instances in referencedInstanceNames filter

- packages/jira-adapter/test/filters/forms/forms.test.ts
In this  PR I fixed the forms.test.ts since it was flaky. 
---
None
---
None
---
None
> SALTO-5095: Fix forms.test.ts

- packages/jira-adapter/e2e_test/adapter.test.ts
- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/constants.ts
- packages/jira-adapter/src/filters/assets/change_attributes_path.ts
- packages/jira-adapter/src/jsm_utils.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/test/adapter.test.ts
- packages/jira-adapter/test/filters/assets/change_attributes_path.test.ts
In this PR I added support for AssetsObjedctType attributes.
---
please review only from commit 3 [support assets attributes](https://github.com/salto-io/salto/pull/5113/commits/12260d0a3a87781f5464d7ad556dd828f5e2bab9) and any sub commit
---
Now supporting fetch of assets attributes.
---
_JIra Adapter:_
Now supporting fetch of assets attributes.
> SALTO-5035:  Add AssetsObjedctType attributes

- packages/adapter-components/src/auth/index.ts
- packages/adapter-components/src/auth/oauth.ts
- packages/adapter-components/test/auth/oauth.test.ts
- packages/okta-adapter/src/adapter_creator.ts
- packages/okta-adapter/src/auth.ts
- packages/okta-adapter/src/client/connection.ts
- packages/okta-adapter/test/client/connection.test.ts
Change adapter code so it will be able to get `clientId`, `clientSecret`, `accessToken` and `refreshToken`, as credentials, and refresh access token a create connection with it.
This code is enough to start implementing OAUTH in saas, but we will need to make adjustment to support oauth flow for OSS.
---
---
None
---
None
> SALTO-4878: OAuth for Okta - part 1

- packages/jira-adapter/src/config_creator.ts
- packages/jira-adapter/test/config_creator.test.ts
In this PR I added the flag enableJSM to user Fetch config. 
---
None
---
None
---
None
> SALTO-2349: Add enableJSM to user fetch config

- packages/dummy-adapter/src/generator.ts
- packages/dummy-adapter/test/generator.test.ts
Improve the conflict generator on dummy to create conflict on objectType fields defenition
---
The previous version did not create any conflicts. we should check the definition of each field to create a conflict and not just its existence 
B -> A (autoMergedStaticFile):
B -> C (autoMergedStaticFile):
---
None
---
None
> SAAS-9634 conflicted elements in dummy adapter to conflict on object fields

- packages/zendesk-adapter/src/adapter.ts
- packages/zendesk-adapter/src/filters/omit_collision.ts
- packages/zendesk-adapter/test/adapter.test.ts
- packages/zendesk-adapter/test/filters/omit_collision.test.ts
avoid merge errors on collision in zendesk
---
---
zendesk:
* remove merge errors on collision of elemIds
---
> SALTO-4036: avoid merge errors on collision in zendesk

- packages/jira-adapter/e2e_test/instances/cloud/index.ts
- packages/okta-adapter/e2e_test/adapter.test.ts
Unclear what the issue is but it seems it was not caused by a code change. removing the check for now to unblock development of other features
Same with Jira where deploying a notification scheme seems to fail
---
---
_None_
---
_None_
> SALTO-5116, SALTO-5117: Disable okta e2e test and jira e2e test

- packages/aws-utils/jest.config.js
- packages/aws-utils/package.json
- packages/aws-utils/src/utils.ts
- packages/aws-utils/test/utils.test.ts
- packages/aws-utils/tsconfig.json
- packages/cli/src/commands/workspace.ts
- packages/cli/test/commands/workspace.test.ts
- packages/cli/test/mocks.ts
- packages/core/src/local-workspace/state/state.ts
- packages/core/test/workspace/local/state/content_providers/file_content_provider.test.ts
- packages/core/test/workspace/local/state/content_providers/s3_content_provider.test.ts
- packages/core/test/workspace/local/state/state.test.ts
- packages/test-utils/src/index.ts
- packages/test-utils/src/setup_tmpdir.ts
- packages/test-utils/test/setup_tmpdir.test.ts
- packages/workspace/src/workspace/state/in_mem.ts
- packages/workspace/src/workspace/state/state.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/common/workspace.ts
- packages/workspace/test/workspace/state.test.ts
- packages/workspace/test/workspace/workspace.test.ts
Added `salto workspace set-state-provider` command
The new command allows configuring the state content provider
It also migrates the current state data from the current provider to the new one
---
Based on #5160 
Ignore the first commit here (review it in the other PR)
---
CLI:
- Added the option to store state file content in S3 instead of storing it locally, see command `salto workspace set-state-provider`
---
_None_
> SALTO-5099: Add cli command to set state content provider

- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/system_config_doc.md
exclude ServerInformation in Jira
---
When switching to the updated adapter swaggers, this type is suddenly added because it's in Jira's supported type list, but it was not fetched before for some reason. We should exclude it to avoid noise when switching to the updated swaggers
---
None
---
None
> SALTO-6125: exclude ServerInformation in Jira

- packages/workspace/src/workspace/static_files/source.ts
- packages/workspace/test/workspace/static_files/source.test.ts
This fixes an issue where we would not take the content hash into account when loading static files this caused a case where if the modification time of the static file changed we would invalidate the cache even if the file content did not change
---
---
Core:
- Fixed issue where loadWorkspace would have degraded performance when static file modification times changed
---
_None_
> SALTO-5127: Avoid invalidating cache when static file content is unchanged

- packages/jira-adapter/e2e_test/instances/cloud/index.ts
- packages/jira-adapter/src/filters/forms/forms.ts
In this PR I fixed forms elemID and modified the e2e 
---
None
---
Change forms elemID
---
To change the current elemID, customers must perform a fetch --regenerate command. This will change the forms elemID, which may cause some disruptions
> SALTO-5123-Fix forms elemID

- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/test/adapter.test.ts
- packages/zendesk-adapter/test/change_validators/trigger_category_removal.test.ts
- packages/zendesk-adapter/test/inactive.test.ts
omit inactive instances by default in zendesk
---
---
zendesk: 
* inactive instances will be omitted by default
---
zendesk: 
* inactive instances will be omitted by default
> SALTO-5051: omit inactive instances by default in zendesk

- packages/jira-adapter/src/change_validators/automation/automation_projects.ts
- packages/jira-adapter/src/change_validators/automation/automation_to_assets.ts
- packages/jira-adapter/src/change_validators/automation/automations.ts
- packages/jira-adapter/src/change_validators/index.ts
- packages/jira-adapter/src/config/config.ts
- packages/jira-adapter/test/change_validators/automations/automation_projects.test.ts
- packages/jira-adapter/test/change_validators/automations/automation_to_assets.test.ts
- packages/jira-adapter/test/change_validators/automations/automations.test.ts
In this PR, I have included a CV that verifies whether an automation contains components with assets when the user does not have JSM support.
---
None
---
None
---
None
> SALTO-5102: Add CV to automation with assets

- packages/jira-adapter/src/filters/layouts/layout_service_operations.ts
- packages/jira-adapter/src/filters/layouts/layout_types.ts
- packages/jira-adapter/test/filters/layouts/request_type_request_form.test.ts
In this PR I added the option to fetch and deploy when metadata is null. 
---
None
---
None
---
None
> SALTO-5141: Allow metadata in requestForm to be null

- packages/jira-adapter/src/change_validators/board_culomn_config.ts
- packages/jira-adapter/src/change_validators/index.ts
- packages/jira-adapter/src/config/config.ts
- packages/jira-adapter/src/filters/board/board_columns.ts
- packages/jira-adapter/test/change_validators/board_column_config.test.ts
- packages/jira-adapter/test/filters/board/board_columns.test.ts
_add CV for Board without at least one column with at least one status_
---
Board column config has some restrictions: 
* A board must have columnConfig with at least one column
* at least one column must have statuses inside it
---
_None_
---
_None_
> SALTO-5130: add CV for Board without at least one column with at least one status

- yarn.lock
---
Not bumping the required version, just the version that is actually being used so we'll be on a newer version
---
_None_
---
_None_
> bump local version of Joi package in yarn.lock

- packages/jira-adapter/e2e_test/instances/cloud/index.ts
- packages/jira-adapter/jest.config.js
- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/filters/account_id/account_id_filter.ts
- packages/jira-adapter/src/filters/notification_scheme/notification_events.ts
- packages/jira-adapter/src/filters/notification_scheme/notification_scheme_deployment.ts
- packages/jira-adapter/src/filters/notification_scheme/notification_scheme_structure.ts
- packages/jira-adapter/src/product_settings/data_center/api_config.ts
- packages/jira-adapter/test/filters/account_id/account_id_filter.test.ts
- packages/jira-adapter/test/filters/notification_scheme/notification_scheme_deployment.test.ts
Our current deployment of NotificationScheme no longer works due to changes in the private API
---
This PR replaces the API used for deployment of `NotificationScheme` from private API deployment (using JSP endpoint) to official `NotificationScheme` API.
unit test are still missing, will add soon
---
- Fix bug in deployment of NotificationScheme type
---
None
> SALTO-5124: Deploy Jira NotificationScheme type

- packages/jira-adapter/src/filters/forms/forms_types.ts
In this PR I fixed the form schemaGuard to allow a form to be untitled when I get the list of forms in a project. 
Their is additional  schemaGuard that blocks the untitled form to be fetched. 
---
None
---
None
---
None
> SALTO-5146: Fixing Form Fetch

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/filters/assets/attribute_deploy_filter.ts
- packages/jira-adapter/src/filters/change_jsm_fields.ts
- packages/jira-adapter/src/filters/jsm_types_fetch_filter.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/test/filters/assets/attribute_deploy_filter.test.ts
- packages/jira-adapter/test/filters/change_jsm_fields.test.ts
In this PR I support deployment of attributes. 
---
Still need to add 2 CV:
1. CV that checks that I don't delete default attribute.
2. CV that checks that I don't modify typeValue while it has objects. 
---
Now supports deployment of attributes. 
---
None
> SALTO-5035: Deploy Assets attributes

- packages/adapter-utils/src/important_values.ts
- packages/adapter-utils/test/important_values.test.ts
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/change_validators/inactive_parent.ts
- packages/netsuite-adapter/src/config.ts
- packages/netsuite-adapter/src/constants.ts
- packages/netsuite-adapter/src/filters/add_important_values.ts
- packages/netsuite-adapter/src/query.ts
- packages/netsuite-adapter/test/filters/add_important_values.test.ts
Adding general important values to all types - only those that exist in the type (in that order):
1. name
2. label
3. description
4. scriptid
5. isinactive / inactive / isInactive
This filter will run with the adapter config value `addImportantValues=true`
---
TODO:
---
- Add important values (with adapter config `addImportantValues=true`)
---
- The `_important_values` annotation will be added to all types (custom record types will also have `_self_important_values`)
> SALTO-5110 NS important values filter

- packages/core/src/core/plan/group.ts
- packages/core/test/core/plan/group.test.ts
This reverts commit f38fd47e9f5c7ee7dc55868d6d5126db2056d968.
---
---
_None_
---
_None_
> Revert "SALTO-5137: Fix collisions of group ids in multi app deploy"

- packages/salesforce-adapter/src/custom_object_instances_deploy.ts
Fixed false masking of data deploy group errors
---
- Fixed a bug where data deploy group errors were falsely masked.
---
_None_
> SALTO-5133: False masking of data deploy group errors.

- packages/jira-adapter/src/filters/change_jsm_fields.ts
- packages/jira-adapter/src/filters/project.ts
- packages/jira-adapter/test/filters/project.test.ts
In this PR I added support for adding serviceDeskId in JSM project addition 
---
None
---
None
---
None
> SALTO-5157: Add serviceDeskId in JSM project addition 

- packages/cli/src/commands/env.ts
- packages/cli/src/commands/workspace.ts
- packages/cli/test/commands/workspace.test.ts
- packages/core/src/local-workspace/s3_dir_store.ts
- packages/core/src/local-workspace/state/content_providers/common.ts
- packages/core/src/local-workspace/state/content_providers/file_content_provider.ts
- packages/core/src/local-workspace/state/content_providers/s3_content_provider.ts
- packages/core/src/local-workspace/state/state.ts
- packages/core/src/local-workspace/workspace.ts
- packages/core/test/workspace/local/state/content_providers/file_content_provider.test.ts
- packages/core/test/workspace/local/state/content_providers/s3_content_provider.test.ts
- packages/core/test/workspace/local/state/state.test.ts
- packages/core/test/workspace/local/workspace.test.ts
- packages/workspace/index.ts
- packages/workspace/src/workspace/config/workspace_config_types.ts
This allows the workspace configuration to determine the location of the static file source for the state
Currently using the same storage provider as the state content
---
---
Core:
- Added support for storing state static files in S3
---
_None_
> SALTO-5140: Allow state static files to be stored in S3

- packages/dummy-adapter/src/adapter_creator.ts
- packages/dummy-adapter/src/generator.ts
- packages/dummy-adapter/test/generator.test.ts
add important values to all object types in dummy
---
---
---
> SALTO-4744: add important values to all object types in dummy

- packages/jira-adapter/src/filters/project.ts
- packages/jira-adapter/test/filters/project.test.ts
Fixed error that when we add software project it calls to jsm endpoint. 
---
None
---
None
---
None
> SALTO-5168: Changed customerPermissions deployment

- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/filters/jsm_types_deploy_filter.ts
- packages/jira-adapter/test/filters/jsm_types_deploy_filter.test.ts
In this PR I fixed the issue when you don't have type in first deployment of ducktype. 
---
None
---
None
---
None
> SALTO-5167: Fixing missing type in first type deployment and serviceId

- packages/adapter-api/src/adapter.ts
- packages/cli/e2e_test/helpers/salesforce.ts
- packages/core/src/core/deploy/deploy_actions.ts
- packages/dummy-adapter/test/adapter.test.ts
- packages/jira-adapter/e2e_test/adapter.test.ts
- packages/jira-adapter/test/adapter.test.ts
- packages/netsuite-adapter/e2e_test/adapter.test.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/okta-adapter/e2e_test/adapter.test.ts
- packages/salesforce-adapter/e2e_test/adapter.test.ts
- packages/salesforce-adapter/e2e_test/custom_object_instances.test.ts
- packages/salesforce-adapter/e2e_test/quick_deploy.test.ts
- packages/salesforce-adapter/e2e_test/utils.ts
- packages/salesforce-adapter/e2e_test/workflow.test.ts
- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/client/client.ts
- packages/salesforce-adapter/src/client/jsforce.ts
- packages/salesforce-adapter/src/metadata_deploy.ts
- packages/salesforce-adapter/test/adapter.crud.test.ts
- packages/salesforce-adapter/test/connection.ts
- packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
- packages/salesforce-adapter/test/filters/filters.test.ts
- packages/salesforce-adapter/test/utils.ts
- packages/sap-adapter/test/adapter.test.ts
- packages/stripe-adapter/test/adapter.test.ts
- packages/workato-adapter/test/adapter.test.ts
- packages/zendesk-adapter/e2e_test/adapter.test.ts
- packages/zendesk-adapter/test/adapter.test.ts
- packages/zuora-billing-adapter/test/adapter.test.ts
Allow adapters to report progress during deploy
---
1. Allow adapters to accept a `ProgressReporter` during deploy
2. In the Salesforce adapter, Instead of waiting for the deploy to complete, check its status once in a while and report the progress
Tests:
- Deploy and check the logs to see the expected data is printed out
- Change the `client.polling.interval` and `client.polling.deployTimeout` configs to 1 second and confirm the deploy times out with the correct error message.
---
N/A
---
N/A
> SALTO-5013 - Salesforce: Report progress during deploy

- packages/adapter-components/src/client/config.ts
- packages/adapter-components/src/client/constants.ts
- packages/adapter-components/src/client/http_connection.ts
- packages/adapter-components/test/client/http_client.test.ts
- packages/adapter-components/test/client/http_connection.test.ts
- packages/jira-adapter/config_doc.md
- packages/okta-adapter/config_doc.md
- packages/stripe-adapter/config_doc.md
- packages/workato-adapter/config_doc.md
- packages/zendesk-adapter/config_doc.md
- packages/zendesk-adapter/src/client/client.ts
- packages/zendesk-adapter/src/client/connection.ts
- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/test/change_validators/organization_existence.test.ts
- packages/zuora-billing-adapter/config_doc.md
Add request timeout documentation for the adapters, add default of 5 seconds for Zendesk with retries.
---
---
__Zendesk adapter:__
* Add default timeout for requests
---
> SALTO-5071 Zendesk request timeout

- packages/jira-adapter/src/filters/account_info.ts
- packages/jira-adapter/test/filters/account_info.test.ts
Added log to count users in jsm accounts
---
None
---
None
---
None
> SALTO-5170: Add jsm user count

- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/change_validator.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/netsuite-adapter/test/change_validator.test.ts
Make sure to pass the adapter config to NS change validators.
---
---
None
---
None
> Fix NS deploy config usage in change validators

- packages/jira-adapter/src/change_validators/automation/automation_to_assets.ts
- packages/jira-adapter/test/change_validators/automations/automation_to_assets.test.ts
In this PR I fixed a bug when you are reading workspaceId from undefined value. 
---
None
---
None
---
None
> SALTO-5200: Fixed reading workspaceId from undefined 

- packages/adapter-components/src/deployment/change_validators/outgoing_unresolved_references.ts
- packages/adapter-components/test/deployment/change_validators/unresolved_references.test.ts
change the missing dependency error to include a link to a learn more page
---
---
adapter-component:
* change the missing dependency error to include a link to a "learn more" page
---
> SALTO-5162: change the missing dependency error to include a link to a learn more page

- packages/okta-adapter/src/reference_mapping.ts
We had some places where we didn't create missing references but allowed it in Okta
---
---
None
---
None
> SALTO-5208: Add missing reference strategy in Okta

- packages/okta-adapter/src/change_validators/group_push_to_application_uniqueness.ts
- packages/okta-adapter/src/change_validators/index.ts
- packages/okta-adapter/src/config.ts
- packages/okta-adapter/test/change_validators/group_push_to_application_uniqueness.test.ts
New change validator that detects if user tries to add groupPush instance with userGroupId and a parent (application)
that already exists in the target env, and return change error with severity `Error`
---
---
Validation error when user tries to add group push with groupId and application relation that already exists in the target environment
---
None
> SALTO-4902 Validate group is not already mapped before adding a GroupPush instance

- packages/jira-adapter/src/deployment/standard_deployment.ts
- packages/jira-adapter/src/filters/jsm_types_deploy_filter.ts
- packages/jira-adapter/test/filters/jsm_types_deploy_filter.test.ts
- packages/jira-adapter/test/filters/layouts/request_types_layouts_to_values.test.ts
In this PR I solved serviceId validator for queue type
---
There is an odd bug in standard_deployment relates to queues that brings back workspace warning Error validating `[jira.Queue.instance.Unassigned_issues10_MYJ8@su.id](mailto:jira.Queue.instance.Unassigned_issues10_MYJ8@su.id)": Invalid value type for serviceid` because in the fetch (Get) the id of the queue is a string and in the addition (POST) the id is a number.
---
None
---
None
> SALTO-5183: Solved serviceid validator for queue

- packages/netsuite-adapter/src/change_validators/workflow_account_specific_values.ts
- packages/netsuite-adapter/test/change_validators/workflow_account_specific_values.test.ts
When trying to modify a condition within a workflow instance, and the parameters contain ACCOUNT_SPECIFIC_VALUE, SDF will silently ignore the condition and won't apply it.
We should add a warning on the condition in this case, to let the user know that it's not going to be applied. It shouldn't be an error because it will block other changes in the workflow from being deployed (which SDF allows).
---
TODO:
---
- Add workflow condition warning when there are parameters with ACCOUNT_SPECIFIC_VALUES
---
None
> SALTO-5122 add workflow condition warning

- packages/jira-adapter/src/filters/portal_settings.ts
- packages/jira-adapter/test/filters/portal_settings.test.ts
support deletion of portal settings.
---
If we remove portal setting while we deleting its project. then it will be deleted automatically by the project and we don't need to do anything. 
---
None
---
None
> SALTO-5214: Remove portal setting

- packages/jira-adapter/src/filters/queue_deployment.ts
- packages/jira-adapter/test/filters/portal_settings.test.ts
- packages/jira-adapter/test/filters/queue_deployment.test.ts
In this PR I fixed queue filter to check parent just for queue changes and not all changes.
---
---
None
---
None
> SALTO-5216: Fixing queue filter

- packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts
- packages/salesforce-adapter/test/filters/extra_dependencies.test.ts
The improved implementation of the `Tooling Extra Dependencies` filter is enabled by default.
---
- The improved implementation of the `Tooling Extra Dependencies` is enabled by default. This will improve IA of Metadata Components.
---
Salesforce:
- You may encounter changes in Metadata Elements `_extra_dependencies`.
> SALTO-5131: Salesforce - Rollout the improved tooling extra dependencies implementation

- packages/adapter-utils/src/utils.ts
- packages/jira-adapter/src/change_validators/workflow_scheme_migration.ts
- packages/jira-adapter/test/change_validators/workflow_scheme_migration.test.ts
_fix workflow_scheme_migration CV bug_
---
* in this CV the relevant elements are coming via the elementsSource, therefore the function `isResolvedReference` always returns false.
---
_None_
---
_None_
> SALTO-5222: fix workflow_scheme_migration CV bug

- packages/zendesk-adapter/src/filters/ticket_form.ts
- packages/zendesk-adapter/test/filters/ticket_form.test.ts
fix removal of missing ticket in ticket_field_ids in ticket_form
---
---
zendesk:
* fix bug where the removal of a missing `ticket_field` by editing from `ticket_field_ids` list in `ticket_form` would fail the deploy
---
> SALTO-5219: fix removal of missing ticket in ticket_field_ids in ticket_form

- packages/adapter-components/src/filters/service_url.ts
- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/filters/service_url/service_url_jsm.ts
- packages/jira-adapter/test/filters/service_url/service_url_jsm.test.ts
In this PR I support serviceUrl in JSM. 
---
---
Jsm types will now have serviceUrl. 
---
Jsm types will now have serviceUrl.
> SALTO-4904: Initial support for service url JSM

- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/filters/workflow_scheme.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/test/filters/workflow_scheme.test.ts
_replace workflowScheme statusMigration type_
---
While working on [upgrading Workflow API](https://salto-io.atlassian.net/browse/SALTO-4978) Im using the type statusMigration from the Swagger.
This typeName collides with another type that we create manually [here](https://github.com/salto-io/salto/blob/main/packages/jira-adapter/src/filters/workflow_scheme.ts#L302). 
In this PR I am replacing the type that we created with an identical type from the Swagger for solving the collision.
---
_None_
---
_None_
> SALTO-5223: replace workflowScheme statusMigration type - Jira

- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/schemas.ts
- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/types.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/test/client/suiteapp_client/soap_client/soap_client.test.ts
The [GetSelectValue](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_N3504236.html#getSelectValue) API can be used to get the correct `internalId` of missing references (ASV) in data instances, as it return a list of the possible options for a specific field of a specific type.
The `filterBy` field should be used for fields that are dependent on the value of another field - for example:
```typescript
getSelectValue('account', 'unitstype')
getSelectValue('account', 'unit', [{ field: 'unitstype', internalId: '2' }])
```
This API should be used in deploy, in order to get missing internalIds in data instances.
---
TODO:
---
None
---
None
> SALTO-3432 add GetSelectValue NetSuite SOAP API

- packages/okta-adapter/src/filters/profile_mapping_properties.ts
We used awu instead of `Promise.all`, which caused requests for mappings to happen one by one
---
---
None
---
None
> SALTO-4943: Improve profileMappingPropertiesFilter

- packages/okta-adapter/src/client/client.ts
- packages/okta-adapter/src/config.ts
- packages/okta-adapter/test/client/client.test.ts
We fetch users data in order to convert userIds to emails. To avoid logging users data, we should omit it before writing to log.
---
`profile` object might include properties that may vary between account. we only use `login`, so the rest is omitted
---
None
---
None
> SALTO-5230: Omit values from users response before logging

- packages/okta-adapter/src/adapter.ts
- packages/okta-adapter/src/change_validators/user.ts
- packages/okta-adapter/src/filter.ts
- packages/okta-adapter/src/filters/group_members.ts
- packages/okta-adapter/src/filters/user.ts
- packages/okta-adapter/src/user_utils.ts
- packages/okta-adapter/test/adapter.test.ts
- packages/okta-adapter/test/filters/user.test.ts
- packages/okta-adapter/test/user_utils.test.ts
This is part of an effort to improve fetch times in Okta
---
Until now, we fetched users data in filter. as responses are paginated (max page size 200), in envs with many users we need to make many requests to fetch this data, which we did one-by-one
when initiating getUsers call earlier in fetch flow, we can make API call while we fetch this.
measured with 2000 users and total fetch time improve in 30~ seconds
I only made this change in fetch, LMK if you think we should do the same for deploy
None
---
None
> SALTO-4943: initiate getUsers early in fetch

- packages/netsuite-adapter/package.json
- yarn.lock
There is an issue when upgrading from the previous SDF version due to formatting changes in the SDF credentials file, that should be resolved by deleting it:
> Error: The following file may be corrupted: /Users/omrilitvak/.suitecloud-sdk/credentials. Delete it and set up your account again. The authentication IDs you had set up previously will be lost.
---
---
Netsuite Adapter: SALTO-5234: Upgrade SDF version to 1.8.0-salto-1 so it'll be based on 2023.2 API version
---
Netsuite Adapter: For existing Salto Workspaces, you should reinstall the NetSuite account by creating a temporary Salto Workspace and calling salto service add netsuite --no-login.
This will download the new SDF version that will be used globally …
> SALTO-5234: Upgrade SDF version to 1.8.0-salto-1 so it'll be based on 2023.2 API version

- packages/jira-adapter/src/filters/add_alias.ts
In this PR I added aliases to JSM Types 
---
---
JSM instances now have _alias fields. 
---
JSM instances now have _alias fields.
> SALTO-5152: Add Aliases to JSM

- packages/cli/src/commands/env.ts
- packages/cli/test/commands/diff.test.ts
- packages/core/src/api.ts
- packages/core/src/core/plan/plan.ts
When calculating a plan that is filiterd by top level ID, perform the filtering before reading and deserializing the element
---
---
Core:
- Improved performance for calculating plan / env diff when the diff is filtered
---
_None_
> SALTO-5232: Improve performance of filtered plan

- packages/zendesk-adapter/src/filters/custom_field_options/custom_object_field_options.ts
- packages/zendesk-adapter/test/filters/custom_objects/custom_object_field_options.test.ts
make creation of custom_object_field_option to use nacl case
---
---
zendesk:
* make creation of custom_object_field_option to use nacl case
---
> SALTO-5239: make creation of custom_object_field_option to use nacl case

- packages/jira-adapter/src/change_validators/assets/default_attribute.ts
- packages/jira-adapter/src/change_validators/index.ts
- packages/jira-adapter/src/config/config.ts
- packages/jira-adapter/src/filters/assets/attribute_deploy_filter.ts
- packages/jira-adapter/src/group_change.ts
- packages/jira-adapter/test/change_validators/assets/default_attribute.test.ts
- packages/jira-adapter/test/filters/assets/attribute_deploy_filter.test.ts
In this PR:
1. I added the option to change default attributes addition as modification. 
2. I added a CV that prevent deployment of non editable attributes. (except an addition of them which doesn't really calls to the endpoint, but adding automatically). 
---
1. 'Name' is the only system attribute that can be modified. (but not added or deleted)
---
None
---
None
> SALTO-5210: Support deploy of default attributes

- packages/netsuite-adapter/package.json
- yarn.lock
> SALTO-5234: Upgrade SDF version to 1.8.0-salto-2 to overcome node version inconsistency due to commander 11.0.0 dependency

- packages/salesforce-adapter/config_doc.md
- packages/salesforce-adapter/src/client/client.ts
- packages/salesforce-adapter/src/constants.ts
- packages/salesforce-adapter/src/custom_object_instances_deploy.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/client.ts
- packages/salesforce-adapter/test/custom_object_instances_deploy.test.ts
Instead of always delaying by the same amount of time, let's have a pluggable strategy. If the user provides an explicit config, use the old constant-interval strategy with the provided value; if there is no explicit config, use an exponential-backoff strategy.
---
See the comment about how the `lowerdash` retry strategies are instantiated.
---
Salesforce: If no explicit configuration is provided, Salto will now use exponential backoff when retrying deployment of custom object instances.
---
N/A
> SALTO-5190 - Salesforce: Exponential backoff for data instances deploy

- packages/okta-adapter/src/change_validators/app_group_assignments.ts
- packages/okta-adapter/src/change_validators/index.ts
- packages/okta-adapter/src/config.ts
- packages/okta-adapter/test/change_validators/app_group_assignment.test.ts
When changing groups assignments for application in status inactive, Okta returns 404 (and also this option blocked on UI)
---
---
- Add validator to verify app groups assignments are not modified in inactive apps
---
None
> SALTO-4205: block changes in group assignments for inactive apps (Okta)

- packages/core/src/api.ts
- packages/core/test/api.test.ts
Add TopLevelFilters to Preview API. this allows consumers to improve the performance of Plan calculation to consider only the elements we expect to have changes on and not the whole workspace.
---
---
None
---
None
> SAAS-9985: Add TopLevelFilter to preview API

- packages/okta-adapter/src/adapter.ts
- packages/okta-adapter/src/change_validators/user.ts
- packages/okta-adapter/src/config.ts
- packages/okta-adapter/src/filters/user.ts
- packages/okta-adapter/src/user_utils.ts
- packages/okta-adapter/test/user_utils.test.ts
default `getUsers` in Okta will now fetch specific users instead of getting all users
---
1. Add config option to to determine how we fetch users - `allUsers` or `searchQuery`. in the future we might want to support `oneByOne` strategy (which will use a different endpoint without query params)
2. `searchQuery` will be the default strategy, and will only fetch user ids that appear in nacls (in both fetch and deploy)
3. left the option to use `allUsers` strategy, cause it might be more efficient in certain envs
for my env with (2000 users total, and 300 that appears in nacls), using the both strategies gave almost the same results for fetch times (with a little advantage to  `allUsers`)
---
- Add config option to enable fetching only users referenced by …
> SALTO-5233: Fetch referenced users only (Okta)

- packages/jira-adapter/src/filters/assets/assets_object_type_order.ts
- packages/jira-adapter/test/filters/assets/assets_object_type_order.test.ts
In this PR I changed the objectTypeOrder name
---
There can be more than one ObjectType, as long as they are in different branches of the tree. The name of their Order is derived from its name and the name of the path should also be added
---
Changed objectTypeOrder instance name. 
---
> SALTO-5241: Change object type order name

- packages/jira-adapter/src/filters/automation/automation_deployment.ts
- packages/jira-adapter/src/filters/automation/automation_fetch.ts
- packages/jira-adapter/src/filters/automation/types.ts
- packages/jira-adapter/src/filters/jsm_types_deploy_filter.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/test/filters/automation/automation_deployment.test.ts
- packages/jira-adapter/test/filters/automation/automation_fetch.test.ts
In this PR I support fetch and deploy for automation with assets components.
---
---
Can now support assets components in automations. 
---
Can now support assets components in automations.
> SALTO-5212: Initial support for assets in automations

- packages/salesforce-adapter/e2e_test/utils.ts
- packages/salesforce-adapter/src/custom_object_instances_deploy.ts
- packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
- packages/salesforce-adapter/test/custom_object_instances_deploy.test.ts
If the user doesn't have access to a field (i.e. it's not creatable for add or updateable for modify), remove it from the instance during deploy.
~UTs still pending.~
---
1. Since we are now making the deploy code remove inaccessible fields, we could go all the way and remove the handling of inaccessible fields from `toRecord`. Would that make sense?
2. I had to use `forEach` instead of `map` when removing the fields because the same instance object is referenced from other instances - thus we can't clone+modify, we have to make the change in-place.
---
Salesforce: When deploying data instances with fields that are not creatable (for addition) or updateable (for modification) by the fetching user, the fields will now be deleted from the workspace.
---
_User …
> SALTO-5206 - Salesforce: Remove fields the user doesn't have permissions to deploy from applied changes

- packages/salesforce-adapter/src/metadata_deploy.ts
- packages/salesforce-adapter/test/adapter.crud.test.ts
We deploy with the `rollbackOnError` option, which means if any part of the deploy group fails, the entire group doesn't deploy. Let's make this more obvious to the user.
---
The current code creates warnings for every successful component in a group where at least one component failed. It also does not return any successful components. We can do either one instead of both if that makes more sense. The current code implements both.
I will add UTs once we decide on what we want to do.
---
Salesforce: will now be more explicit about metadata types that did not deploy because they were in a deploy group along with types that failed to deploy because of an error.
---
N/A
> SALTO-5213 - Salesforce: Improve UX of deploy failure reason in case of metadata deploy and rollback on error

- packages/jira-adapter/src/filters/screen/screen.ts
- packages/jira-adapter/test/filters/screen/screen.test.ts
_fix a bug in screen filter that assumes originalFieldsIds is defined - Jira_
---
---
_None_
---
_None_
> SALTO-5259: fix a bug in screen filter that assumes originalFieldsIds is defined - Jira

- packages/netsuite-adapter/src/filters/custom_record_types.ts
- packages/netsuite-adapter/test/filters/custom_record_types.test.ts
In NS `loadElementsFromFolder` (apply-patch) we don't fetch the data types, so we need to use the elements source to get them, so we'll be able to set the field types in custom record type, instead of setting them to `unknown`.
---
---
- Fix custom record type fields type in NS loadElementsFromFolder (apply-patch)
---
None
> Fix custom record type fields type in NS loadElementsFromFolder

- packages/salesforce-adapter/src/client/types.ts
- packages/salesforce-adapter/src/constants.ts
- packages/salesforce-adapter/src/transformers/transformer.ts
- packages/salesforce-adapter/test/transformers/transformer.test.ts
Fixed a bug where MetadataRelationship CustomFields with controlling field couldn't be deployed.
---
We simply didn't populate this value in `toCustomField` in the transformer.
---
- Fixed a bug where MetadataRelationship CustomFields with controlling field couldn't be deployed.
---
_None_
> SALTO-4069: Salesforce MetadataRelationship with controlling field bugfix

- packages/jira-adapter/src/filters/queue_fetch.ts
In this PR I changed the jql query in queue such that the wotd `type` will be replaced with `issuetype`. 
---
In the jql section in queue, you can write `type =` or `issuetype = ` and it references to the same thing. 
The desired field name is `issuetype` so in order for our template expression generator to identify the field, I changed the jql query. 
More context can be found in [this ticket](https://salto-io.atlassian.net/browse/INCIDENT-11717). 
---
Modify jql in queue. 
---
None
> SALTO 5266: Modify jql in queue

- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/workspace.test.ts
There is a merge error that happens when there are state-only changes in a type, and a field type changed too.
---
TODO:
---
Workspace:
- Fix merge error on field type change in apply patch/changes
---
None
> SALTO-5261 Fix merge error on field type change in apply patch/changes

- packages/salesforce-adapter/src/custom_object_instances_deploy.ts
- packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
Do not create warnings on Standard Fields that lack permissions
---
_None_
---
_None_
> SALTO-5206: Do not create warnings on Standard Fields that lack permissions (bugfix)

- packages/jira-adapter/src/change_validators/adding_jsm_project.ts
- packages/jira-adapter/src/change_validators/index.ts
- packages/jira-adapter/src/config/config.ts
- packages/jira-adapter/src/utils.ts
- packages/jira-adapter/test/change_validators/adding_jsm_project.test.ts
In this PR I added a cv that prevent the deployment of JSM project when JSM is not enabled in the service. 
---
None
---
Added a CV that prevents addition of JSM project when JSM is disabled in the service. 
---
None
> SALTO-5155: Added CV for Jsm project addition

- packages/salesforce-adapter/src/adapter_creator.ts
- packages/salesforce-adapter/src/custom_references.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/custom_references.test.ts
Create references from profiles and permission sets in `getCustomReferences`
---
1. Note how I create the ElemID name for the references. Given the fullName, the correct thing to do would be to look up the element with this full name and use its ElemID. However, in `getCustomReferences` we are supposed to deal with elements one at a time with no context, so that's not an option. I basically replicated how we create ElemID from fullName where we create instances.
2. ~Ideally, this would be an optional feature, but I'm not sure how to get access to the fetch profile from this callback~
** PR Chain **
- https://github.com/salto-io/salto/pull/5150 
- https://github.com/salto-io/salto/pull/5045 👈 YOU ARE HERE 👈
---
N/A
---
N/A
> SALTO-4780 - Salesforce: convert profile and permission sets to custom references

- packages/salesforce-adapter/src/constants.ts
- packages/salesforce-adapter/src/group_changes.ts
- packages/salesforce-adapter/test/group_changes.test.ts
Change group names appear in user-visible error messages, so let's make them easier to understand by the end user.
---
TODO:
---
Salesforce: Errors and warnings that contain the names of change groups are now clearer.
---
N/A
> SALTO-5215 - Salesforce: Improve dependency error text by updating the group names

- packages/netsuite-adapter/package.json
- yarn.lock
There is an issue when upgrading from the previous SDF version due to formatting changes in the SDF credentials file, that should be resolved by deleting it:
> Error: The following file may be corrupted: /Users/omrilitvak/.suitecloud-sdk/credentials. Delete it and set up your account again. The authentication IDs you had set up previously will be lost.
---
---
Netsuite Adapter: SALTO-5234: Upgrade SDF version to 1.8.0-salto-1 so it'll be based on 2023.2 API version
---
Netsuite Adapter: For existing Salto Workspaces, you should reinstall the NetSuite account by creating a temporary Salto Workspace and calling salto service add netsuite --no-login.
This will download the new SDF version that will be used globally …
> SALTO-5234: Upgrade SDF version to 1.8.0-salto-2

- packages/adapter-components/src/config/config_change.ts
- packages/adapter-components/test/config/config_change.test.ts
- packages/okta-adapter/src/adapter.ts
- packages/okta-adapter/src/config.ts
- packages/okta-adapter/src/utils.ts
- packages/okta-adapter/test/adapter.test.ts
- packages/okta-adapter/test/utils.test.ts
Some types are not supported with the Classic Engine, we would like to avoid fetching them (currently we return fetch warnings)
---
---
- Accounts with Okta Classic Engine will no longer get warnings when fetching Okta Identity Engine types fails.
---
None
> SALTO-5257: Adjust supported types for classic engine orgs (Okta)

- packages/salesforce-adapter/src/constants.ts
- packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts
- packages/salesforce-adapter/src/filters/custom_objects_from_soap_describe.ts
- packages/salesforce-adapter/src/filters/organization_wide_sharing_defaults.ts
- packages/salesforce-adapter/src/transformers/transformer.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/transformers/transformer.test.ts
Implemented a feature that adds extra information on the fetched `CustomFields`.
---
Disabled by default. The current extraInformation I've added is for `defaultedOnCreate`
You can see diff on the opportunity object here as an example: https://github.com/salto-io/tamir-sf/commit/64e6bbeb40f41201ff2f4f75d6cccd1b9d52c491
---
- Added the optional feature `extraCustomFieldInformation` that extends the annotations of the `CustomFields` when enabled.
---
Salesforce:
- When enabling the feature `extraCustomFieldInformation`, expect to see new values on each `CustomField`.
> SALTO-5274: Salesforce CustomField extra information feature

- packages/okta-adapter/config_doc.md
- packages/okta-adapter/src/adapter.ts
- packages/okta-adapter/src/adapter_creator.ts
- packages/okta-adapter/src/change_validators/user.ts
- packages/okta-adapter/src/config.ts
- packages/okta-adapter/src/fix_elements/fallback_user.ts
- packages/okta-adapter/src/fix_elements/index.ts
- packages/okta-adapter/src/fix_elements/missing_users.ts
- packages/okta-adapter/src/fix_elements/types.ts
- packages/okta-adapter/src/user_utils.ts
- packages/okta-adapter/test/change_validators/user.test.ts
- packages/okta-adapter/test/fix_elements/missing_users.test.ts
---
---
- Add `FixElement`
- Add `omitMissingUsers` flag to deploy configuration
- When the flag is true, every list of users that contains users that do not exist in the target environment, will be modified such that the missing users will be removed from it (if the list gets empty then the whole path will be removed from the instance). A change error with severity `Warning` will be attached to that instance 
---
None
> SALTO-5163_omit_missing_users_okta_adapter

- packages/salesforce-adapter/src/constants.ts
- packages/salesforce-adapter/src/fetch_profile/metadata_query.ts
- packages/salesforce-adapter/src/filters/changed_at_singleton.ts
- packages/salesforce-adapter/src/filters/utils.ts
- packages/salesforce-adapter/src/transformers/transformer.ts
- packages/salesforce-adapter/test/filters/changed_at_singleton.test.ts
Add a new "section" to the changed-at Singleton where we store the most recent "changed-at" among all instances of a given type
---
- I chose to create a new "section" as the least-disruptive way of storing the data. Feedback welcome!
- I added the `isInstanceOfCustomObjectSync` utility. Let me know if it's better added in a separate PR.
- I added a couple of utility functions for use with the changed-at Singleton: `getTypeChangedAt` and `getTypeInstancesChangedAt`.
**PR Chain**:
- https://github.com/salto-io/salto/pull/5071
- https://github.com/salto-io/salto/pull/4964 👈 YOU ARE HERE 👈 
- https://github.com/salto-io/salto/pull/4965
---
N/A
---
N/A
> SALTO-4839 - Salesforce: Aggregate changed-at for instances

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/filters/assets/assets_object_type_order.ts
- packages/jira-adapter/src/filters/assets/attribute_deploy_filter.ts
- packages/jira-adapter/src/filters/jsm_types_deploy_filter.ts
- packages/jira-adapter/src/workspace_id.ts
Currently, when customers have JSM Free but not JSM premium, they might get an errors for trying to access a source they don't have permission to. I wanted to add security that prevents the fetch or deployment from failing for not good reason. 
---
---
None.
---
None.
> SALTO 5270: Add Secuiry to workspaceId

- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/types.ts
- packages/netsuite-adapter/test/client/suiteapp_client/soap_client/soap_client.test.ts
when `item` types reach the limit of max allowed instances, we should return the correct types names for the exclusion.
---
---
- Fix NS item types limiter exclusion
---
None
> Fix NS item types limiter exclusion

- packages/jira-adapter/e2e_test/instances/cloud/jsm/objectTypeAttribute.ts
- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/change_validators/assets/default_attribute.ts
- packages/jira-adapter/src/change_validators/assets/label_attribute_removal.ts
- packages/jira-adapter/src/change_validators/index.ts
- packages/jira-adapter/src/config/config.ts
- packages/jira-adapter/src/constants.ts
- packages/jira-adapter/src/filters/assets/attribute_deploy_filter.ts
- packages/jira-adapter/src/filters/assets/label_object_type_attribute.ts
- packages/jira-adapter/test/change_validators/assets/default_attribute.test.ts
- packages/jira-adapter/test/change_validators/assets/label_attribute_removal.test.ts
- packages/jira-adapter/test/filters/assets/attribute_deploy_filter.test.ts
- packages/jira-adapter/test/filters/assets/label_object_type_attribute.test.ts
In this PR:
1. Added CV that prevents the deletion of label attribute.
2. Added a filter that fetches and deploys the label attribute.
3. Modified the attribute deploy filter. 
---
None
---
1. New instance element that holds for each objectType who its label attribute. 
2. New CV that prevents deletion of assets label attribute. 
---
1. New instance element that holds for each objectType who its label attribute. 
2. New CV that prevents deletion of assets label attribute.
> SALTO-5271: Support label attribute

- packages/netsuite-adapter/src/config/suggestions.ts
- packages/netsuite-adapter/test/config/suggestions.test.ts
---
---
SALTO-5287: Netsuite too many instances type exclusion description is not containing the type name
---
> SALTO-5287: Netsuite too many instances type exclusion description is not containing the type name

- packages/jira-adapter/src/filters/assets/label_object_type_attribute.ts
Fixed missing parma in getWorkspaceId
---
---
None
---
None
> SALTO-5296: Added param to getWorkspaceId

- packages/jira-adapter/src/filters/layouts/issue_layout.ts
- packages/jira-adapter/src/filters/layouts/layout_service_operations.ts
- packages/jira-adapter/src/filters/layouts/layout_types.ts
- packages/jira-adapter/src/filters/layouts/request_types_layouts_to_values.ts
- packages/jira-adapter/src/filters/request_type.ts
- packages/jira-adapter/test/filters/layouts/request_types_layouts_to_values.test.ts
_convert requestForm properties to list_
---
requestForm properties can have an invalid field name as you can see in the attached image, the solution is to convert the field to a list in which each entry contains key and value (same as we do in [other places](https://github.com/salto-io/salto/blob/main/packages/jira-adapter/src/filters/workflow/workflow_properties_filter.ts#L92) in Jira).
before: 
after: 
---
None
---
Jira Adapter:
the properties of requestForm instances will be a list in which each entry will contain key and value
> SALTO-5283: convert requestForm properties to list - Jira

- packages/salesforce-adapter/e2e_test/utils.ts
- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/change_validators/custom_field_type.ts
- packages/salesforce-adapter/src/constants.ts
- packages/salesforce-adapter/src/custom_object_instances_deploy.ts
- packages/salesforce-adapter/src/sfdx_parser/sfdx_parser.ts
- packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
- packages/salesforce-adapter/test/custom_object_instances_deploy.test.ts
- packages/salesforce-adapter/test/utils.ts
This is a de-fanged version of https://github.com/salto-io/salto/pull/5317 where we only log the fields we would have removed.
---
---
N/A
---
N/A
> SALTO-5206 - Salesforce: Log when inaccessible fields are dropped from deploy

- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
- packages/netsuite-adapter/src/config/types.ts
- packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts
- packages/netsuite-adapter/src/data_elements/types.ts
- packages/netsuite-adapter/test/data_elements/suiteql_table_elements.test.ts
Fetch the internal ids & names of lots of data objects from SuiteQL tables and save them in hidden instances.
This will be used in the future for finding the real value behind an ACCOUNT_SPECIFIC_VALUE, in workflows & data elements.
In case of partial/quick fetch no new data will be fetched.
This feature is behind an adapter config value - `fetch.addSuiteQLTables`
---
TODO:
---
None
---
None
> SALTO-2392 fetch internal ids from SuiteQL tables

- packages/jira-adapter/jest.config.js
- packages/jira-adapter/src/deployment/standard_deployment.ts
- packages/jira-adapter/src/filters/request_type.ts
When system is not defined we should use the name in lower case as the type
---
---
Fix reading system from undefined when deploying RequestTypeLayout
---
None
> SALTO-5295 reading properity of undefined fix (when deploying RequestTypeLayout)

- packages/netsuite-adapter/src/config/query.ts
- packages/netsuite-adapter/test/config/query.test.ts
When running partial fetch for custom record types, the custom record types with custom segments were deleted.
It is because those custom record types are fetched by their custom segments, and since the custom segments weren't fetched we thought that the custom record types were deleted in the service and we marked them as "deleted elements".
The solution is to fetch the matching custom segments of those custom record types.
---
TODO:
---
- Fix custom record types with segments partial fetch
---
None
> Fix custom record types with segments partial fetch

- packages/okta-adapter/src/filters/unordered_lists.ts
- packages/okta-adapter/test/filters/unordered_lists.test.ts
Sort unordered list password policy rule to avoid noise in subsequent fetches
---
there are no notifications enabled for this type, so no need of noise reduction
---
---
- In password policy rules with more then one method used for password reset, the list of methods will be sorted.
> SALTO-5304: sort password policy rule methods (Okta)

- packages/jira-adapter/e2e_test/adapter.ts
- packages/jira-adapter/src/adapter_creator.ts
- packages/jira-adapter/src/client/connection.ts
- packages/jira-adapter/test/adapter.test.ts
- packages/jira-adapter/test/client/client.test.ts
- packages/jira-adapter/test/client/connection.test.ts
- packages/jira-adapter/test/client/pagination.test.ts
- packages/jira-adapter/test/client/script_runner_client.test.ts
add validate creds func as we have in other adapters
---
we will call validateCredentials for each function with `@requiresLogin()` decorator.
This way user will get unauthorized error when credentials are invalid
---
- When trying to deploy with invalid credentials, user will get unauthorized error.
---
None
> SALTO-5187: Add validate creds func (Jira)

- packages/okta-adapter/src/change_validators/app_urls.ts
- packages/okta-adapter/src/change_validators/index.ts
- packages/okta-adapter/src/config.ts
- packages/okta-adapter/test/change_validators/app_urls.test.ts
Add a validator to remind users to change tenant specific values
---
For more context see ticket details.
The validator is disabled by default and can be enabled from the adapter's config file
---
- Add the ability to setup a reminder to change tenant specific values (such as URLs or subdomains) when deploying applications. To enable it, add the following config to the deploy section in adapter config: 
```
okta = {
deploy = {
changeValidators = {
appUrls = true
}
}
}
```
---
None
> SALTO-5303: Add validator to remind users to change tenant specific values when deploying application (Okta)

- packages/jira-adapter/src/adapter.ts
In this PR, I changed the filters order so the types I create in 
```
defaultAttributesFilter,
assetsObjectTypeOrderFilter,
```
Can be hide as well   
---
None
---
None
---
None
> SALTO-5309: Jsm Types should be hidden

- packages/jira-adapter/src/filters/automation/automation_structure.ts
- packages/jira-adapter/src/filters/automation/types.ts
- packages/jira-adapter/test/filters/automation/automation_structure.test.ts
For hasAttachment type of component in Jira, the api returns a boolean value.
In Salto matched objectType, value is an object.
To solve this, we're mapping the boolean value from the api to a new field "hasAttachmentsValue"
---
---
For automation with component from type "hasAttachment", its boolean value will be store in "hasAttachmentsValue" field
---
Automation with component from type "hasAttachment", will have a new field named "hasAttachmentsValue" that will contain the boolean value
> SALTO-5129 convert boolean value in component type to hasAttachmentsValue

- packages/netsuite-adapter/src/filters/add_important_values.ts
- packages/netsuite-adapter/test/filters/add_important_values.test.ts
Change the default behavior of the `fetch.addImportantValues` config - so by default we'll add important values.
---
---
- Add important-values by default
---
- The `_important_values` will be added to all types, and the `_self_important_values` will be added to all custom record types.
> SALTO-5110 add important-values by default (netsuite)

- packages/adapter-api/src/constants.ts
- packages/netsuite-adapter/src/config/config_creator.ts
- packages/netsuite-adapter/src/config/constants.ts
- packages/netsuite-adapter/src/config/types.ts
- packages/netsuite-adapter/src/config/validations.ts
- packages/netsuite-adapter/src/types.ts
- packages/netsuite-adapter/src/types/file_cabinet_types.ts
- packages/netsuite-adapter/test/config/config_creator.test.ts
- packages/netsuite-adapter/test/config/validations.test.ts
Add simple fields to NS adapter config - fields that should be used to easily set customized configuration.
- All simple fields are in the config type's `_important_values` annotation, ordered by their presentation order.
- The field's title is in the `_alias` annotation
- The field's description is in the `_description` annotation
- Links are in a markdown format (`[Learn more](https://url...)`)
- The field's type should be inferred by the field's `refType`
- The field's suggested values are in the `_restriction.values` annotation
- When `_restriction.enforce_value = false`, it means that the suggested values list is partial, and the adapter will receive also other values
- There are some special values that the adapter defines: "All" means *include all* and translates to `.*`, …
> SALTO-5217 NS simple config

- packages/salesforce-adapter/src/custom_references.ts
- packages/salesforce-adapter/test/custom_references.test.ts
Permission sets are already handled by the normal reference mapping code. No need to create custom refs for them.
Additionally, if `generateRefsInProfiles` config is enabled then the normal reference mapping code will also generate refs for profiles, and we shouldn't try to create custom references from these generated `ReferenceExpression`s.
---
---
N/A
---
N/A
> SALTO-5302 - Salesforce: Don't create custom refs from PermissionSets.

- packages/jira-adapter/src/filters/layouts/issue_layout.ts
- packages/jira-adapter/src/filters/layouts/layout_service_operations.ts
- packages/jira-adapter/test/filters/layouts/issue_layout.test.ts
In some cases, IssueLayout ids are being changed over and over, causing fetches to be very big.
We need to replace the id of IssueLayouts with a combination of screenId and projectId
---
None
---
None
---
None
> SALTO-5316 fix IssueLayout id

- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/constants.ts
- packages/salesforce-adapter/src/filters/custom_objects_instances.ts
- packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
Use the changed-at data we aggregate into the changed-at Singleton in the SOQL query we use to fetch instances
---
**PR Chain**:
- https://github.com/salto-io/salto/pull/5071
- https://github.com/salto-io/salto/pull/4964
- https://github.com/salto-io/salto/pull/4965 👈 YOU ARE HERE 👈 
---
Salesforce: Quickfetch is now supported for data records
---
N/A
> SALTO-4839 - Salesforce: support quick fetch for data instances

- packages/okta-adapter/e2e_test/mock_elements.ts
- packages/okta-adapter/src/config.ts
I omitted `priority` field from policies that has no order and can't be deployed (it returned by default the API as other types of policies supports this)
---
---
None
---
- In AccessPolicy, ProfileEnrollment Policy and IDP policy instances, 'priority' field will be omitted
> SALTO-5325: Omit priority field from policies when not relevant

- packages/jira-adapter/e2e_test/instances/cloud/jsm/queue.ts
- packages/jira-adapter/src/filters/queue_fetch.ts
- packages/jira-adapter/test/filters/queue_fetch.test.ts
When fetching a queue, the API adds 'project = <ProjectKey>' at the beginning of the JQL. This doesn't appear to have any functional impact, but it is causing a lot of unnecessary noise
---
None
---
The JQL for queues will no longer include an unnecessary 'project = <projectKey>' at the beginning.
---
The JQL for queues will no longer include an unnecessary 'project = <projectKey>' at the beginning.
> SALTO-5331: Fixed jql in queue

- packages/jira-adapter/src/config/api_config.ts
_Omit condition's and trigger's ids in jiraWorkflow_
---
* it does not affect any user - the jiraWorkflow is behind a config flag
---
_None_
---
_None_
> SALTO-5328: Omit condition's and trigger's ids in jiraWorkflow

- packages/salesforce-adapter/src/metadata_deploy.ts
- packages/salesforce-adapter/test/adapter.crud.test.ts
- packages/salesforce-adapter/test/mock_elements.ts
We need to add the types and names of nested instances for when we get deploy errors that reference them
Note that there are still error conditions in which the error mapping will be wrong. See ticket for further details.
---
~Unit tests pending.~
Before the change:
After the change:
---
Salesforce: Improved mapping of deploy errors to elements
---
N/A
> SALTO-4861 - Salesforce: fix mapping of nested objects in deploy errors

- packages/jira-adapter/src/filters/layouts/request_types_layouts_to_values.ts
- packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts
- packages/jira-adapter/src/utils.ts
- packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts
_convert statuses and transitions properties to a list_
---
* We use the same logic in other places in the adapter so I took it out as a more generic function
---
_None_
---
_None_
> SALTO-5343: convert statuses and transitions properties to a list

- packages/salesforce-adapter/jest.config.js
- packages/salesforce-adapter/src/fetch_profile/metadata_query.ts
- packages/salesforce-adapter/src/filters/custom_objects_instances.ts
- packages/salesforce-adapter/src/filters/topics_for_objects.ts
- packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
- packages/salesforce-adapter/test/filters/topics_for_objects.test.ts
Fixed a couple regressions I've noticed in main.
---
Regressions fixed:
- CustomObject sub-instances are being deleted.
- Fetch fails due to issue with unresolved reference in referenceTo fields.
- TopicsForObjects instances are included in the workspace.
---
_None_
---
_None_
> SALTO-5342: Salesforce Fetch With Changes Detection regression fixes

- packages/zendesk-adapter/src/change_validator.ts
- packages/zendesk-adapter/src/change_validators/default_group_change.ts
- packages/zendesk-adapter/test/change_validators/default_group_change.test.ts
Do not allow deletion of groups where one of the group's members has it set as default.
---
---
---
> SALTO-4956 Validate group has no default members before deletion.

- packages/jira-adapter/src/change_validators/automation/automation_to_assets.ts
- packages/jira-adapter/test/change_validators/automations/automation_to_assets.test.ts
In this PR I fix the CV that warn when customer has automation to assets without assets support
---
None
---
* Fixed automationToAssetsValidator validator in jira to warn when customer doesn't have assets support.
---
None
> SALTO-5353: Fix CV for Automation to assets

- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/change_validators/account_specific_values.ts
- packages/netsuite-adapter/src/change_validators/workflow_account_specific_values.ts
- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/types.ts
- packages/netsuite-adapter/src/constants.ts
- packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts
- packages/netsuite-adapter/src/elements_source_index/elements_source_index.ts
- packages/netsuite-adapter/src/elements_source_index/types.ts
- packages/netsuite-adapter/src/filters/element_references.ts
- packages/netsuite-adapter/src/filters/workflow_account_specific_values.ts
- packages/netsuite-adapter/test/change_validators/account_specific_values.test.ts
- packages/netsuite-adapter/test/change_validators/workflow_account_specific_values.test.ts
- packages/netsuite-adapter/test/client/suiteapp_client/suiteapp_client.test.ts
- packages/netsuite-adapter/test/data_elements/suiteql_table_elements.test.ts
- packages/netsuite-adapter/test/elements_source_index.test.ts
- packages/netsuite-adapter/test/filters/workflow_account_specific_values.test.ts
- packages/netsuite-adapter/test/utils.ts
Use queried internal ids maps from SuiteQL and the "record" SuiteApp operation to get the value behind ASV in workflows.
---
TODO:
---
- resolve account specific values in workflows (behind config value `fetch.resolveAccountSpecificValues`)
---
None
> SALTO-2392 resolve account specific values in workflows

- packages/zendesk-adapter/src/filters/field_references.ts
- packages/zendesk-adapter/src/filters/references/missing_references.ts
- packages/zendesk-adapter/test/filters/field_references.test.ts
Support referencing a custom status, add missing reference if is a valid number and does not exist.
---
---
* Support referencing a custom status, add missing reference if is a valid number and does not exist.
---
Field values that are of the type `custom_status_####` will be converted to references to the relevant custom status.
> SALTO-5340 Support referencing custom status

- packages/salesforce-adapter/e2e_test/quick_deploy.test.ts
- packages/salesforce-adapter/package.json
- yarn.lock
Salesforce Quick Deploy Regression Fix
---
The previous salto-io/jsforce version didn't contain the `deployRecentValidation` method so we always failed back to regular deploy.
---
- Fix Quick Metadata Deploy.
---
_None_
> SALTO-5352: Salesforce Quick Deploy Regression Fix

- packages/salesforce-adapter/src/custom_object_instances_deploy.ts
- packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
Take 2 of https://github.com/salto-io/salto/pull/5239.
If the user doesn't have access to a field (i.e. it's not creatable for add or updateable for modify), remove it from the instance during deploy.
Only apply the logic for fields whose values changed, and that are neither hidden nor system fields.
---
Note that this logic is not identical to the code that removes fields in `toRecord`, because it is more selective in the fields it removes.
---
Salesforce: When deploying data instances with fields that are not creatable (for addition) or updateable (for modification) by the fetching user, the fields will now be deleted from the workspace and a warning will be issued.
---
N/A
> SALTO-5206 - Salesforce: Warn when inaccessible fields are dropped from deploy

- packages/salesforce-adapter/src/client/client.ts
- packages/salesforce-adapter/src/types.ts
~Introduce a new undocumented config `client.additionalDebugging`. When this config is set we~ log (at `trace` level) the parameters passed to `SalesforceClient.bulkLoadOperation`.
---
Test:
- Deploy data records with the config set to `true`, observe trace-level logs
- Deploy data records without the config, confirm no logs of data records
---
N/A
---
N/A
> SALTO-5357 - Salesforce: Log deployed data records

- packages/netsuite-adapter/src/adapter_creator.ts
The global concurrency limit should be the maximum allowed limit from SDF+SuitApp APIs plus one, because every integration is allowed to have the maximum concurrency of the account minus one.
---
---
- Increase global concurrency limit in NS APIs
---
None
> Increase global concurrency limit in NS APIs

- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/src/constants.ts
- packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts
- packages/netsuite-adapter/src/data_elements/types.ts
- packages/netsuite-adapter/src/filters/workflow_account_specific_values.ts
- packages/netsuite-adapter/test/changes_detector/role.test.ts
- packages/netsuite-adapter/test/changes_detector/savedsearch.test.ts
- packages/netsuite-adapter/test/changes_detector/workflow.test.ts
- packages/netsuite-adapter/test/data_elements/suiteql_table_elements.test.ts
- packages/netsuite-adapter/test/filters/author_information/saved_searches.test.ts
- packages/netsuite-adapter/test/filters/internal_ids/sdf_internal_ids.test.ts
- map more fields with ASV to the data types they are referring
- fetch more SuiteQL tables
- fetch internal id maps from saved search too
- add option to limit saveSearch query results
---
---
- More account specific values resolving in workflows
---
- When `fetch.resolveAccountSpecificValues` is `true`, more `ACCOUNT_SPECIFIC_VALUE` values in workflows will be resolved.
> SALTO-2392 more account specific values resolving in workflows

- packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts
- packages/netsuite-adapter/src/filters/workflow_account_specific_values.ts
- packages/netsuite-adapter/test/filters/workflow_account_specific_values.test.ts
`instance.value[INTERNAL_IDS_MAP]` can be undefined because transformElement transform empty objects to undefined
---
---
- Fix `undefined` internalIdsMap bug in workflow ASV resolving
---
None
> SALTO-5367 fix undefined internalIdsMap bug in workflow ASV resolving

- packages/salesforce-adapter/e2e_test/utils.ts
- packages/salesforce-adapter/src/custom_object_instances_deploy.ts
- packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
Create Deploy Warning when attempting to deploy data instance with missing fields.
---
~Based on https://github.com/salto-io/salto/pull/5317~
Take 2 of https://github.com/salto-io/salto/pull/5277
When users attempt to deploy data instances with values to fields that do not exist in the CustomObject, we warn the users that the instance was most likely partially deployed in Salesforce.
The implementation does not intercept the applied changes, as we don't really know what was actually deployed to the service.
---
Add Deploy Warning when attempting to deploy Data Instance with fields that do not exist on the CustomObject type.
---
_Replace me with a short sentence that describes changes that will appear in NaCls and are not caused …
> SALTO-5243 - Salesforce: Create deploy warning when data instance may have been partially deployed due to non existing fields

- packages/jira-adapter/src/change_validators/workflowsV2/status_mappings.ts
- packages/jira-adapter/test/change_validators/workflowsV2/status_mappings.test.ts
---
* statusMappings CV should suggest migrating only issueTypes that exist in the Project and not all the issueTypes that the workflowScheme contains.
---
_None_
---
_None_
> SALTO-5374: fix statusMappings CV bug

- packages/jira-adapter/src/client/client.ts
- packages/jira-adapter/test/client/client.test.ts
> SALTO-5326: log errored GQL responses

- packages/salesforce-adapter/src/metadata_deploy.ts
- packages/salesforce-adapter/test/adapter.crud.test.ts
- packages/salesforce-adapter/test/mock_elements.ts
Revert the revert of this code, because the issue we thought was caused by it is still there after the revert.
---
---
N/A
---
N/A
> SALTO-4861 - Salesforce: Revert the revert of mapping deploy errors to sub-instances

- packages/salesforce-adapter/src/filters/cpq/referencable_field_references.ts
- packages/salesforce-adapter/test/filters/cpq/referencable_field_references.test.ts
Fixed a bug where the cpqReferencableFieldReferencesFilter returned incorrect appliedChanges
---
This filter would push all the related changes that were manipulated on `preDeploy` and pushed them to the `appliedChanges` regardless if they were successful or not.
---
_None_
---
_None_
> SALTO-5381: Salesforce Data Deploy with wrong applied changes bugfix

- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/change_validators/bundle_changes.ts
- packages/netsuite-adapter/src/filters/bundle_ids.ts
- packages/netsuite-adapter/src/transformer.ts
- packages/netsuite-adapter/test/change_validators/bundle_changes.test.ts
- packages/netsuite-adapter/test/filters/bundle_ids.test.ts
- packages/netsuite-adapter/test/transformer.test.ts
_A few bundles related updates_:
* bundles change validator updated to prevent all modifications on bundle elements and not only additions
* bundle elements renamed to have "bundle_" prefix and not only id
---
_None_
---
* bundle elements will be renamed from `<bundleId>` to `bundle_<bundleId>`
---
_bundle elements will be renamed from `<bundleId>` to `bundle_<bundleId>`_
> SALTO-5351: minor bundle updates

- packages/adapter-components/src/definitions/index.ts
- packages/adapter-components/src/definitions/system/index.ts
- packages/adapter-components/src/definitions/system/shared/index.ts
- packages/adapter-components/src/definitions/system/shared/types.ts
- packages/adapter-components/src/definitions/system/utils.ts
- packages/adapter-components/test/definitions/system/utils.test.ts
- packages/lowerdash/src/types.ts
Add a few utility types and helper functions that will be used in the new infra.
See https://github.com/salto-io/salto/pull/5409/files for more context.
Merging this now because we want to start using `DefaultWithCustomization` and its utilities soon.
---
None
---
None
> SALTO-5389 utils and DefaultWithCustomization, ArgsWithCustomizer, OptionsWithDefault

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/filters/group_name.ts
- packages/jira-adapter/test/filters/group_name.test.ts
Fix bug in recreation of elemIds for trusted users group
---
The bug was that in every fetch after the first fetch ran with `--regenerate-salto-ids`, we didn't rename the `trusted-users` group in Jira (because `elemIdGetter` wasn't provided so we returned original name).
This pr fixes this issue. In addition, instead of recreating all group instances, we'll only recreate the group we'd want to rename
---
- Fix issue with the elemId of trusted-users group in Jira. If the elemId for the trusted-users group contains uuid, fetch with `regenerate salto ids` to resolve the issue.
---
None
> SALTO-5376: Fix bug in recreation of elemIds for trusted users group

- packages/adapter-components/src/definitions/user/fetch_config.ts
- packages/adapter-components/src/definitions/user/user_config.ts
- packages/adapter-components/test/definitions/user/fetch_config.test.ts
- packages/adapter-components/test/definitions/user/user_config.test.ts
- packages/jira-adapter/src/config/config.ts
- packages/okta-adapter/src/config.ts
- packages/sap-adapter/src/config.ts
- packages/stripe-adapter/src/config.ts
- packages/workato-adapter/src/config.ts
- packages/zendesk-adapter/src/config.ts
- packages/zuora-billing-adapter/src/config.ts
the new elem id field was added in https://github.com/salto-io/salto/pull/5411 as optional - I think it's safer to allow the adapter to not support it until we allow users to control the flow via that (forgot to add this in the previous PR).
also using this opportunity to switch the function to named parameters.
---
None
---
None
> SALTO-5388 allow omitting the user fetch config elem id field

- packages/adapter-components/src/elements/instance_elements.ts
- packages/adapter-components/src/filters/referenced_instance_names.ts
- packages/adapter-components/test/elements/instance_elements.test.ts
- packages/adapter-components/test/filters/referenced_instance_name.test.ts
- packages/workato-adapter/test/filters/referenced_id_fields.test.ts
We now allow configuring idFields that might be null in some elements. 
---
This continues - https://github.com/salto-io/salto/pull/4056
---
None 
---
None
> SALTO-4056: Allow configuring idFields that only exist in some elements

- packages/netsuite-adapter/src/config/types.ts
- packages/netsuite-adapter/src/data_elements/custom_fields.ts
- packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts
- packages/netsuite-adapter/src/filters/author_information/system_note.ts
- packages/netsuite-adapter/src/filters/replace_record_ref.ts
- packages/netsuite-adapter/src/filters/workflow_account_specific_values.ts
- packages/netsuite-adapter/test/data_elements/suiteql_table_elements.test.ts
- packages/netsuite-adapter/test/filters/author_information/system_note.test.ts
Use the existing "employee" suiteQLTable instance to populate the `_changed_by` annotation.
---
---
None
---
None
> SALTO-2392 reduce employees queries

- packages/jira-adapter/src/change_validators/jsm/jsm_permissions.ts
- packages/jira-adapter/test/change_validators/jsm/jsm_permissions.test.ts
In this PR I fixed the jsmPermissionsValidator
---
This PR fixes two bugs that can be found in [this thread](https://salto-io.slack.com/archives/C02A0C56GGL/p1707304806010629?thread_ts=1707227425.893209&cid=C02A0C56GGL) and [this thread](https://salto-io.slack.com/archives/C05R7BP89RA/p1707320341823179) about JSM Permissions validator.
Bug 1 - Admins are encountering "Lacking permissions" errors despite they have permissions. 
The problem was that we are checking for the permission of the associated project even if the project itself is an addition change, and therefore doesn't locate in the system yet.
I filtered out all the changes that are connected to a project that being added as well. 
Bug 2 - unnecessary types are being validate. 
I removed the …
> SALTO-5409: Fix Jsm Permissons Validator

- packages/jira-adapter/src/config/config.ts
- packages/jira-adapter/src/filters/workflow_scheme.ts
Increase number of retries in checking workflowScheme draft change, and instead of sending a failure error, state that we run out of retries but don't know wether this was successful
---
None
---
None
---
None
> SALTO-5401 Improve handling publish workflowScheme draft

- packages/zendesk-adapter/e2e_test/adapter.test.ts
- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/view.ts
- packages/zendesk-adapter/test/filters/view.test.ts
When deploying a view, if raw_title was a `dynamic content` token if used to get swapped into a raw string (specifically, the resolved dynamic token)
Now, it no longer happens, and we've hidden the title field so that users don't edit it and create conflicts with changes to the raw_title field
---
_Test plan_:
Before:
1. apply a dynamic content name to a view - {{dc.dynamic_content}}, who's value is "blip bloop"
2. `salto fetch`
3. Observe that in the instance, the following fields show up:
```
title = "blip bloop"
raw_title = "{{${ zendesk.dynamic_content_item.instance.dynamic_content }}}"
```
4. Change anything in the view (changed the description text, for example)
5. `salto deploy`
6. `salto fetch`
7. Observe that in the instance, the title fields are now as follows:
```
title = "blip …
```
> SALTO-5186: [Zendesk] Hide title field in view and fix the raw_title deployment bug

- packages/zendesk-adapter/src/filters/article/article.ts
- packages/zendesk-adapter/test/filters/article/article.test.ts
TSIA
---
Since the "Everyone" instance is a Salto concept and Zendesk doesn't know it, changing the User Segment to "Everyone" would fail on deploy.
---
Zendesk:
Changing `User Segment` in `Article` to `Everyone` now deploys correctly
---
None
> SALTO-5255: [Zendesk] Fix bug when deploying an article with a change to User Segment to "Everyone"

- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/article/utils.ts
- packages/zendesk-adapter/test/filters/article/article.test.ts
make get content of article_attachment use relative_path field
---
---
zendesk:
* fix fetch of attachments with non english characters
---
None
> SALTO-5411: make get content of article_attachment use relative_path field

- packages/zendesk-adapter/src/filters/organizations.ts
Change from `organizations/autocomplete` to `organizations/search` for more accurate searching (first one does not find organizations like "⭐⭐ INCIDENT-12941 ⭐⭐"
---
---
__Zendesk Adapter__
* Fix references to organizations starting with non alphanumeric characters, e.g. ⭐⭐ My Org ⭐⭐
---
> INCIDENT-12941 Change to more accurate API call

- packages/core/src/core/plan/dependency/reference_dependency.ts
- packages/core/test/core/plan/dependency.test.ts
bugfix - add new dependency flow.
From now on - if A has reference to B and A modified and B removed, A would be dependency of B. so A would change before B removed.
---
see https://salto-io.atlassian.net/browse/SALTO-5402
---
Zendesk adapter - fix bug of getting Service error while removing trigger_category and changing trigger to be depend on other category simultaneously 
---
None
> new Dependency Flow - changing removal depencdency 

- packages/salesforce-adapter/src/constants.ts
- packages/salesforce-adapter/src/custom_object_instances_deploy.ts
- packages/salesforce-adapter/src/group_changes.ts
- packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
- packages/salesforce-adapter/test/group_changes.test.ts
- packages/salesforce-adapter/test/mock_elements.ts
Similar to the special handling we have for SBAA `ApprovalRule`/`ApprovalCondition`, we need to do the same thing for CPQ `PriceRule`/`PriceCondition`.
---
I made the existing code more generic and implemented two special cases for SBAA and CPQ
---
Salesforce: Can now deploy new CPQ PriceRule records with 'Custom' ConditionMet value that reference new PriceCondition records.
---
N/A
> SALTO-5369 - Salesforce: Handle circular dependency of CPQ PriceRule/PriceCondition

- packages/adapter-components/src/config/index.ts
- packages/jira-adapter/src/client/script_runner_client.ts
- packages/jira-adapter/src/client/script_runner_connection.ts
- packages/jira-adapter/test/client/script_runner_client.test.ts
Change the login failures in ScriptRunner to cause fetch errors.
Also add a special message when the cause of failure is the survey screen
(And changed an error I made in the previous PR that exported the AdapterFetchError under the wrong name)
---
It was tested against a real-life scenario
---
Jira Adapter:
* In case a fetch that includes ScriptRunner fails the fetch will end with a fetch error. Also, in case the reason is the ScriptRunner's Survey, the user will be provided with the relevant instructions
---
None
> SALTO-4752: script runner survey

- packages/netsuite-adapter/e2e_test/adapter.test.ts
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/config/config_creator.ts
- packages/netsuite-adapter/src/config/suggestions.ts
- packages/netsuite-adapter/src/config/types.ts
- packages/netsuite-adapter/src/filters/align_field_names.ts
- packages/netsuite-adapter/src/filters/exclude_by_criteria/exclude_custom_record_types.ts
- packages/netsuite-adapter/test/config/config_creator.test.ts
- packages/netsuite-adapter/test/config/suggestions.test.ts
- packages/netsuite-adapter/test/filters/align_field_names.test.ts
- packages/netsuite-adapter/test/filters/exclude_by_criteria.test.ts
Align isinactive/inactive/isInactive fields to be all "isInactive", in top level & nested values.
In addition, changed the order of some filters and added removal of refTypes to excluded custom record types.
---
TODO:
---
- align inactive fields
---
- all isinactive/inactive fields will be replaced with "isInactive" field - in types, instances, and important values
> SALTO-5360 align inactive fields

- packages/netsuite-adapter/e2e_test/adapter.test.ts
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/change_validators/data_account_specific_values.ts
- packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts
- packages/netsuite-adapter/src/filters/bundle_ids.ts
- packages/netsuite-adapter/src/filters/data_account_specific_values.ts
- packages/netsuite-adapter/src/filters/data_instances_internal_id.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/netsuite-adapter/test/data_elements/suiteql_table_elements.test.ts
- packages/netsuite-adapter/test/filters/data_instances_internal_id.test.ts
Enable the "fetch bundles" and "resolve account specific values" features by default.
---
---
- Enable the "fetch bundles" and "resolve account specific values" features by default
---
- `bundle` instances will be fetched
- `bundle` field will be added to instances that are part of a bundle
- `ACCOUNT_SPECIFIC_VALUE` will be resolved in workflows & data elements, on fetch & deploy
> PROD-232 enable features

- packages/jira-adapter/src/change_validators/assets/default_attribute.ts
- packages/jira-adapter/test/change_validators/assets/default_attribute.test.ts
I fixed the default attribute CV to refer only to removal changes and not refers to all changes.
---
None
---
Fixed bug in default attribute CV. 
---
None
> SALTO-5434: Fix default attribute CV

- packages/adapter-api/src/change.ts
- packages/adapter-utils/src/compare.ts
- packages/adapter-utils/test/compare.test.ts
- packages/cli/test/commands/apply_patch.test.ts
- packages/cli/test/commands/fetch.test.ts
- packages/cli/test/commands/restore.test.ts
- packages/cli/test/mocks.ts
- packages/core/src/core/diff.ts
- packages/core/src/core/fetch.ts
- packages/core/src/core/plan/plan_item.ts
- packages/core/src/core/restore.ts
- packages/core/src/types.ts
- packages/core/test/api.test.ts
- packages/workspace/test/workspace/multi_env/routers.test.ts
Create `DetailedChangeWithBaseChange` that is a `DetailedChange` with `baseChange: Change<Element>` in it, and return it in `PlanItem` & `FetchChange`
---
---
Core:
- Create `DetailedChangeWithBaseChange` and return it in `PlanItem` & `FetchChange`
---
None
> SALTO-3483 return detailed change with base change

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/change_validators/workflows/empty_validator_workflow.ts
- packages/jira-adapter/src/filters/workflow/empty_validator_workflow.ts
- packages/jira-adapter/src/filters/workflow/transition_structure.ts
- packages/jira-adapter/src/filters/workflowV2/types.ts
- packages/jira-adapter/test/change_validators/workflows/empty_validator_workflow.test.ts
- packages/jira-adapter/test/filters/workflow/empty_validator_workflow.test.ts
_adjust empty validator cv and filter to the new Workflow structure_
---
---
_None_
---
_None_
> SALTO-5440: adjust empty validator cv and filter to the new Workflow structure

- packages/netsuite-adapter/src/filters/add_important_values.ts
Settings types in NS should not have important values (at least not the scriptid/label/name/isInactive/bundle fields). The problem is that `companyInformation` has isinactive field, so we create `_important_values` annotation for `companyInformation`, although that it doesn't make sense to filter it by the `isInactive` field (because there's only one `companyInformation` instance).
---
---
- Remove important values from Settings types
---
- The `_important_values` annotation will be removed from the `companyInformation` type
> Remove important values from Settings types

- packages/adapter-components/src/config/ducktype.ts
- packages/adapter-components/src/config/index.ts
- packages/adapter-components/src/config/shared.ts
- packages/zendesk-adapter/config_doc.md
- packages/zendesk-adapter/src/adapter.ts
- packages/zendesk-adapter/src/adapter_creator.ts
- packages/zendesk-adapter/src/change_validator.ts
- packages/zendesk-adapter/src/change_validators/ticket_field_deactivation.ts
- packages/zendesk-adapter/src/change_validators/trigger_category_removal.ts
- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/inactive.ts
- packages/zendesk-adapter/test/adapter.test.ts
- packages/zendesk-adapter/test/change_validators/ticket_field_deactivation.test.ts
- packages/zendesk-adapter/test/change_validators/trigger_category_removal.test.ts
- packages/zendesk-adapter/test/config.test.ts
- packages/zendesk-adapter/test/inactive.test.ts
SALTO-2343 zendesk: move the omit inactive logic to the user facing part of the config #5404
---
---
---
> SALTO-2343 zendesk: move the omit inactive logic to the user facing part of the config #5404

- packages/netsuite-adapter/src/change_validators/account_specific_values.ts
- packages/netsuite-adapter/src/change_validators/workflow_account_specific_values.ts
- packages/netsuite-adapter/test/change_validators/workflow_account_specific_values.test.ts
Workflow instances are ignored in the generic ASV change validator, but in case of `ACCOUNT_SPECIFIC_VALUE` in a workflow instance, that is not sender/recipient/parameters, we still should return the generic CV warning about ASV.
---
---
- Add generic ASV warning to workflows
---
None
> Add generic ASV warning to workflows

- packages/adapter-components/src/config/shared.ts
- packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts
- packages/netsuite-adapter/test/data_elements/suiteql_table_elements.test.ts
- packages/zendesk-adapter/config_doc.md
Avoid querying SuiteQL tables that have more that 100K records in them, and exclude those tables' instances.
---
---
- Limit SuiteQL tables query to 100K records
---
None
> Limit SuiteQL tables query to 100K records

- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/src/config/types.ts
- packages/netsuite-adapter/src/config/validations.ts
- packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts
- packages/netsuite-adapter/test/data_elements/suiteql_table_elements.test.ts
Add the `suiteAppClient.maxRecordsPerSuiteQLTable` config to allow defining the max allowed records of a suiteql table query
---
---
- Add config option to SuiteQL queries limitation: `suiteAppClient.maxRecordsPerSuiteQLTable`
---
None
> Add config option to SuiteQL queries limitation

- packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts
- packages/salesforce-adapter/test/adapter.discover.test.ts
Add important values for Salesforce Metadata Types.
---
Turned on the feature `importantValues` by default.
---
- Add important values to Salesforce Metadata Types.
---
Salesforce:
- Upon your next fetch, expect changes to existing Metadata Types nacls.
> SALTO-5458: Salesforce Metadata Important Values

- packages/adapter-components/src/fetch/request/utils.ts
- packages/adapter-components/src/filters/service_url.ts
- packages/adapter-components/test/filters/service_url.test.ts
- packages/jira-adapter/src/change_validators/workflow_scheme_migration.ts
- packages/okta-adapter/src/config.ts
- packages/okta-adapter/src/filters/service_url.ts
- packages/okta-adapter/test/filters/service_url.test.ts
Allow using parent values with service url through the config.
The format is similar to the one being used with `urlParamsToFields`, for example `api/v1/apps/{_parent.0.id}/schema/{id}`
---
I also change serviceId Filter to use the definitions according to type to avoid creating filter for each config
---
None
---
None
> SALTO-4927: Allow using parent in serviceUrl

- packages/core/src/core/deploy/deploy_actions.ts
- packages/core/test/core/deploy/deploy_actions.test.ts
No reason to skip the dependencies of a change group with e.g. 'Info' level warnings.
---
---
Dependencies of change groups that have low-severity errors will now be deployed.
---
N/A
> SALTO-5382 - Don't skip deploy groups if a dependency had a recoverable error

- packages/netsuite-adapter/src/filters/fix_order_problems_in_workbooks.ts
- packages/netsuite-adapter/src/type_parsers/analytics_parsers/analytics_constants.ts
Instead of checking for unrelevant changes in XMLs only in specific paths, it would be better to check for XMLs all over the instance, and then compare the XML content with the XML content in the existing instance.
---
---
None
---
None
> Make fix-order-problems-in-workbooks run generically on XMLs

- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/types.ts
- packages/netsuite-adapter/test/client/suiteapp_client/suiteapp_client.test.ts
Use the first SuiteQL result's "last page" link to determine how many pages are there for the SuiteQL query, and then query all pages using `Promise.all`.
NOTE - there's still the bottleneck limiter that run max of 4/5 requests at the same time.
---
---
- Run SuiteQL queries concurrently
---
None
> Run SuiteQL queries concurrently

- packages/salesforce-adapter/src/change_validator.ts
- packages/salesforce-adapter/src/change_validators/instance_with_unknown_type.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/change_validators/instance_with_unknown_type.test.ts
In some "Compare and Deploy" cases there may be cases where instances are deployed to the new environment but their types are not.
Let's create an explicit warning in such cases.
---
Tests:
- Delete the `Account` folder in a workspace, add an `Account` instance and deploy. Observe the CV warning.
---
Salesforce: Warn when attempting to add instances without their types
---
N/A
> SALTO-4741 - Salesforce: don't allow deploying instances without their types

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/filters/script_runner/workflow/workflow_references.ts
- packages/jira-adapter/src/filters/workflowV2/transition_ids.ts
- packages/jira-adapter/src/filters/workflowV2/types.ts
- packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts
- packages/jira-adapter/test/filters/workflowV2/transition_ids.test.ts
- packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts
_hide workflow transitionId and add it in the deployment_
---
in this pr: 
* add transition_ids filter
* fix workflow schema bug
* fix workflow_filter test
---
_None_
---
_None_
> SALTO-5456: hide workflow transitionId and add it in the deployment

- packages/core/src/core/plan/change_validators/incoming_unresolved_references.ts
- packages/core/test/core/plan/change_validators/incoming_unresolved_references.test.ts
This is necessary in order to distinguish between change errors (incoming references errors and outcoming references errors)
---
---
None
---
None
> SALTO-5356: Don't return unresolvedReferences change error for incoming references validator

- packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts
This changes the default behavior of fetching the SuiteQL tables for ASV resolving - we will fetch the tables only when `fetch.resolveAccountSpecificValues` is `true`.
We still transform data elements to be in the new format in `data_account_sepcific_values` filter.
---
---
- change the default behavior of fetching the SuiteQL tables for ASV resolving
---
None
> SALTO-2392: change the default behavior of resolveAccountSpecificValues so if undefined do not fetch SuiteQL tables

- packages/jira-adapter/src/filters/assets/assets_object_type_order.ts
- packages/jira-adapter/test/filters/assets/assets_object_type_order.test.ts
In this PR I fixed The assets folders structure to be more intuitive. 
---
---
* New Folder structure:
objectType1
....|__ attributes (folder)
....|__ childObjectType1 (folder)
....|__ childObjectType2 (folder)
....|__ objectType1.nacl
....|__objectType1_childOrder.nacl
* New name for the child order nacl. 
* The change is on type ObjectTypeOrder (Name change and path change)
---
* New Folder structure:
objectType1
....|__ attributes (folder)
....|__ childObjectType1 (folder)
....|__ childObjectType2 (folder)
....|__ objectType1.nacl
....|__objectType1_childOrder.nacl
* New name for the child order nacl. 
* The change is on type ObjectTypeOrder (Name change and path change)
> SALTO-5471: Fix Assets Folder Structure

- packages/okta-adapter/src/config.ts
- packages/okta-adapter/src/filters/app_logo.ts
- packages/okta-adapter/src/filters/delete_fields.ts
- packages/okta-adapter/src/logo.ts
- packages/okta-adapter/test/filters/delete_fields.test.ts
- packages/okta-adapter/test/logo.test.ts
This pr nests app-related instances under app
---
The new file tree structure will be - 
```md
── Application
└── appName
└── AppUserSchema
└── appUserSchemaName.nacl
└──AppLogo
└── appLogoName.nacl
└──appName.nacl
```
We should have group push instances nested as well, but there's currently a bug with `referencedInstanceNames` blocking it
---
- On the next fetch, AppLogo and AppUserSchema types will now be nested under Application type in the element tree
---
None
> SALTO-4536: Nest app schema and app logo under application type

- packages/okta-adapter/src/adapter.ts
- packages/okta-adapter/src/filters/group_push_path.ts
- packages/okta-adapter/test/filters/group_push_path.test.ts
Nest group push types under the parent app
---
This is in a dedicated filter and not using "nestStandaloneFields" as group push types are not standalone fields of apps cause the types are in different configs.
This is a temp filter that will be removed once we migrate Okta to the new infra
This change is done without any migration to existing files.
---
- On the next fetch, GroupPush and GroupPushRule types will now be nested under the parent Application type in the element tree
---
None
> SALTO-5436: [Okta] Nest GroupPush and GroupPushRule under the parent app path

- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/change_validator.ts
- packages/netsuite-adapter/src/change_validators/remove_list_item.ts
- packages/netsuite-adapter/src/change_validators/remove_list_item_without_id.ts
- packages/netsuite-adapter/src/change_validators/remove_list_item_without_scriptid.ts
- packages/netsuite-adapter/src/config/types.ts
- packages/netsuite-adapter/src/filters/restore_deleted_list_items.ts
- packages/netsuite-adapter/src/filters/restore_deleted_list_items_without_scriptid.ts
- packages/netsuite-adapter/test/change_validators/remove_list_item.test.ts
- packages/netsuite-adapter/test/change_validators/remove_list_item_without_scriptid.test.ts
- packages/netsuite-adapter/test/filters/restore_deleted_list_items.test.ts
- packages/netsuite-adapter/test/filters/restore_deleted_list_items_without_scriptid.test.ts
_Added a CV to warn the user of deleting permissions from role (can be done only in the UI).
Changed the CV that check the inner item list to warning instead of error.
Added filters to add the deleted items onDeploy to make the user's enviroment updated._
---
Jira ticket: https://salto-io.atlassian.net/browse/SALTO-4564
---
_None_
---
_None_
> SALTO-4564: Netsuite - warning about deleting permissions from role

- packages/salesforce-adapter/src/change_validator.ts
- packages/salesforce-adapter/src/change_validators/artifical_types.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/change_validators/artificial_types.test.ts
`CurrencyIsoCodes` is a synthetic type we create. The type (and its instances) can't be deployed because they don't exist on the service.
---
---
Salesforce: Warn when attempting to modify the list of supported currencies.
---
N/A
> SALTO-4690 - Salesforce: CV for modification/deletion of CurrencyIsoCode instance

- packages/jira-adapter/src/dependency_changers/index.ts
- packages/jira-adapter/src/dependency_changers/root_object_type_to_schema.ts
- packages/jira-adapter/test/dependency_changers/root_object_type_to_schema.test.ts
In this PR I removed the connection between the root object type and the its objectSchema upon removals.
---
Much more context in https://salto-io.atlassian.net/browse/SALTO-5479.
---
* Resolved a bug that occurred when attempting to delete a root objectType and its corresponding objectSchema.
---
None
> SALTO-5479: RemoveDependencyFromObjectTypeToObjectSchema

- packages/zendesk-adapter/src/filters/webhook.ts
- packages/zendesk-adapter/test/filters/webhook.test.ts
👋  Salto team, as I dive into the Salto code base for the first time, I'm making an effort to thoroughly understand the existing logic and context. If I have overlooked any details or misinterpreted any part of the code, I would greatly appreciate your input. Please don't hesitate to offer feedback. Thank you for your assistance.
There is an alternative PR https://github.com/salto-io/salto/pull/5520 which just updating the HTTP method from `PATCH` to `PUT` for modification behaviour of Zendesk webhook in order to address this issue. The reason I've created two PRs is that I am not sure the reason of using `PATCH` of webhook mortification behaviour in deployment.
We've identified a minor issue during the deployment of webhooks with custom headers from the source environment to the target …
> Fix removed custom headers still exist issue in zendesk webhook after deploment

- packages/okta-adapter/index.ts
- packages/okta-adapter/src/adapter_creator.ts
- packages/okta-adapter/src/utils.ts
- packages/okta-adapter/test/adapter.test.ts
- packages/okta-adapter/test/adapter_creator.test.ts
- packages/okta-adapter/test/utils.test.ts
This is temporary addition, will remove once all tests are done
More details in linked ticket 
---
---
None
---
None
> SALTO-5482: Allow trexcloud domain in okta login

- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/reference_mapping.ts
In this PR I added the subType `SLA__config__goals__subGoals` to the SLA and modified the 'calendar' field to be a reference expression.
---
---
* In SLA nacls, whenever there are subgoals fields - The calendar field will change from id to referenceExpression. 
---
* In SLA nacls, whenever there are subgoals fields - The calendar field will change from id to referenceExpression.
> SALTO-5497: Add SubType subgoals to api_config in jira

- packages/jira-adapter/src/filters/workflow/transition_structure.ts
- packages/jira-adapter/src/filters/workflowV2/types.ts
- packages/jira-adapter/test/change_validators/workflows/empty_validator_workflow.test.ts
- packages/jira-adapter/test/change_validators/workflows/workflow_properties.test.ts
- packages/jira-adapter/test/change_validators/workflows/workflow_transition_duplicate_name.test.ts
- packages/jira-adapter/test/filters/script_runner/workflow/workflow_references.test.ts
- packages/jira-adapter/test/filters/workflow/empty_validator_workflow.test.ts
- packages/jira-adapter/test/filters/workflowV2/transition_ids.test.ts
- packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts
_fix statusReference bug in getTransitionKey_
---
_Bug description:_ 
The function `getTransitionKey` is used to create a unique key for the transitions map. The unique key is structured from `transitionName`, `transitionType` and `from` statuses.
The `from` part is different in WorkflowV2 comparing to the old workflow which caused this bug:
key before the fix: 
```
Resolve_Issue__From____Directed@sfffsszdzdff 
```
key after the fix: 
```
Resolve_Issue__From__Open__Directed@sfffsszdzdff 
```
---
_None_
---
_None_
> SALTO-5362: fix statusReference bug in getTransitionKey

- packages/jira-adapter/src/config/api_config.ts
In this PR I omitted the ids in SLA golas and sub goals since they are not needed. 
---
---
* Omitted Id fields in SLA subTypes. 
---
None
> SALTO-5497: Omit id field in SLA sub types

- packages/cli/test/mocks.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/workspace.test.ts
Add a method to Workspace that returns all the Elements author informations for a given env. 
---
_None_
---
_None_
---
_None_
> SALTO-5507: add getElementsAuthorsById to Workspace

- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts
- packages/netsuite-adapter/test/client/suiteapp_client/suiteapp_file_cabinet.test.ts
_fix fetching fileCabinet elements with fetchTarget_
---
_The Issue_:
Description: Fetching fileCabinet items using quick fetch did not fetch changes. In `suiteapp_file_cabinet.ts` we filter out folders before querying all files to avoid querying redundant folders. When fetching with fetchTarget and passing only the file path or any string that doesn't match the parent folders name we filter out the folder and do not query it.
The [ticket](https://salto-io.atlassian.net/jira/software/c/projects/SALTO/issues/SALTO-5314?filter=myopenissues&jql=project%20%3D%20Salto%20and%20assignee%20IN%20%28currentUser%28%29%29%20and%20statusCategory%20in%20%28%22To%20Do%22%2C%20%22In%20Progress%22%29%0AORDER%20BY%20created%20DESC)
_Fix_:
* Dont filter folders in case they are a parent folder of one of the …
> SALTO-5314 - Fix fetchTarget file cabinet bug

- packages/cli/e2e_test/helpers/salesforce.ts
- packages/salesforce-adapter/src/metadata_deploy.ts
- packages/salesforce-adapter/test/adapter.crud.test.ts
See ticket for an example of such a message on a successful deploy of a component
---
I made a couple of fixes to the E2E utils while I was at it.
---
Salesforce: info/warning messages from successfully deployed components will now be shown
---
N/A
> SALTO-5461 - Salesforce: Propagate warnings from successful deploy results

- packages/netsuite-adapter/src/client/sdf_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
After seeing that increasing the total concurrency doesn’t affect the fetch duration I saw in the logs that when having a load of SuiteApp calls that are triggered ~together, no SDF request is executed.
The reason for that is that we first use the global limiter and only then the specific SDF/SuiteApp limiter.
We should flip the order of the funnel: first SDF/SuiteApp limiter and only then the global one, since this way we will respect also the fairness between them.
---
---
Netsuite Adapter: SALTO-5515: Utilize NS concurrency limit by having fairness between the inner concurrency limiters
---
_Replace me with a short sentence that describes changes that will appear in NaCls and are not caused by user actions (e.g. …
> SALTO-5515: Utilize NS concurrency limit by having fairness between the inner concurrency limiters

- packages/salesforce-adapter/jest.config.js
- packages/salesforce-adapter/src/config_change.ts
- packages/salesforce-adapter/src/fetch.ts
- packages/salesforce-adapter/test/adapter.discover.test.ts
- packages/salesforce-adapter/test/config_change.test.ts
When creating a config change suggestion, make sure it isn't already excluded
---
For now we'll only log the cases where this change would take effect. If we see things are OK we can fully enable it.
---
N/A
---
N/A
> SALTO-4077 - Salesforce: Ignore duplicate retrieve config changes

- packages/jira-adapter/src/config_creator.ts
- packages/jira-adapter/test/config_creator.test.ts
In this PR I added the OSS support for enableJSMPremium to work
---
---
None
---
None
> SALTO-5503: EnableJSM button to activate JSMPremium

- packages/jira-adapter/e2e_test/instances/cloud/index.ts
- packages/jira-adapter/e2e_test/instances/cloud/jsm/SLA.ts
changed SLA name in the e2e. 
---
For some reason the e2e doesn't work with the random string for the SLA any more (Failed all the time). If I just change the name to a normal random name it works. 
---
* Fix e2e due to cannot deploy SLA.
---
None
> SALTO-5527: Fix E2E

- packages/adapter-components/src/definitions/system/references.ts
- packages/adapter-components/src/filter_utils.ts
- packages/adapter-components/src/filters/hide_types.ts
- packages/adapter-components/src/filters/query.ts
- packages/adapter-components/test/filters/hide_types.test.ts
- packages/adapter-components/test/filters/query.test.ts
some of the other filters will need a "migration" from the relevant args of the old config to the new format, but these only rely on the user part so adjusting the types to have a reduced scope in order to avoid needing to support both formats. 
note this also contains some helper types + utils for filters using the new definitions.
---
this is technically ready, but I want to adjust some of the type names (used for now names that are very similar to the old format). if this is needed feel free to merge, or I'll adjust these before merging
---
None
---
None
> SALTO-5421 adjust adapter-components filters that only need user config so they will work with both versions of the system config

- packages/zendesk-adapter/src/filters/workspace.ts
- packages/zendesk-adapter/test/filters/workspace.test.ts
Same thing as https://github.com/salto-io/salto/pull/5438 - we saw that an error can also be a string, so add a case to catch that
---
---
Zendesk:
Fail deployment when Zendesk returns errors when changing workspaces
---
None
>  SALTO-5249: [Zendesk] Throw during Workspace deployment when the Zendesk client returns 200 with an error

- packages/salesforce-adapter/src/change_validators/metadata_types.ts
- packages/salesforce-adapter/test/change_validators/metadata_types.test.ts
Fixed a bug where the Change Validator created incorrect errors on CustomMetadataTypes.
---
Here's an example output with changes to the `CustomMetadata` metadata type and a `CustomMetadata` custom type.
```
Salto will perform the following actions:
| salesforce.CMT2__mdt
| EntityDef__c
M label
Please review the following messages; changes with errors will not be deployed.
Deploying a non-deployable type
envs/env1/salesforce/Types/CustomMetadata.nacl(line: 1)
Error: The type CustomMetadata is not a custom type and can't be deployed
Resources and actions are indicated with the following symbols:
+ create
M change
- remove
Impacts: 1 type and 0 instances.
```
---
_None_
---
_None_
> SALTO-5548: Salesforce metadataTypes Change Validator Bugfix

- packages/zendesk-adapter/src/filters/guide_theme.ts
- packages/zendesk-adapter/src/filters/template_engines/javascript_extractor.ts
- packages/zendesk-adapter/test/filters/template_engines/javascript_extractor.test.ts
This is the trivial strategy of extracting all over 6 digit long matches and trying to find a reference. 
In next PRs (based on discussions with clients), we will add some config to allow digit amount changes, and to choose different strategies.
---
---
---
> SALTO-3080 Add greedy id extraction from JS files

- packages/zendesk-adapter/config_doc.md
- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/ticket_form.ts
- packages/zendesk-adapter/test/filters/ticket_form.test.ts
Added a config flag, which, if turned on, will make it so that we omit the `Ticket_status_custom_status` ticket field from Ticket Forms on fetch.
---
Added a test
---
[Zendesk]: 
Added a config flag which allows omitting the `Ticket_status_custom_status` ticket field from Ticket Forms on fetch
---
[Zendesk]: 
Added a config flag which allows omitting the `Ticket_status_custom_status` ticket field from Ticket Forms on fetch
> SALTO-5275: [Zendesk] Add ability to omit ticket status custom status ticket field from Ticket Forms on fetch

- packages/adapter-utils/src/template.ts
- packages/zendesk-adapter/src/filters/handle_template_expressions.ts
- packages/zendesk-adapter/test/filters/handle_template_expressions.test.ts
The current regex for catching dynamic content placeholders allows for some pretty whacky stuff;
For example, having `{{ blip bloop blep dc.content_item }}` will catch `dc.content_item` as a dynamic content placeholder, even though Zendesk wouldn't allow it. 
Another example is that this issue was caught when a customer tried to note his email, which had the string `dc.stuttgart` in it, and it got replaced by a dynamic content ref - without any brackets at all!
In this PR, i've changed the regex so that it forces the content to be inside brackets, and furthermore forces the brackets to be "close" to the placeholder (so if you have content between the brackets and the placeholder it won't catch it anymroe).
---
Ironically, we already had a test for this in place, but it was testing the …
> SALTO-5460: [Zendesk] Fix dynamic_content placeholder regex catching non-DC strings

- packages/adapter-components/src/client/http_client.ts
- packages/adapter-components/src/deployment/old_deployment.ts
Data logs were missing in POST requests that were part of the deploy
---
I removed the existing data from the deploy log to avoid duplicate write
---
None
---
None
> SALTO-5522: Add data to trace logs of http calls

- packages/jira-adapter/src/change_validators/index.ts
- packages/jira-adapter/src/change_validators/workflowsV2/inbound_transition.ts
- packages/jira-adapter/src/config/config.ts
- packages/jira-adapter/test/change_validators/workflowsV2/inbound_transition.test.ts
_add inbound transition change validator_
---
* statuses without inbound transition are not allowed in the new Workflow API
---
__None_
---
_None._
> SALTO-5513: add inbound transition change validator

- packages/workato-adapter/src/adapter_creator.ts
- packages/workato-adapter/src/config.ts
- packages/workato-adapter/test/adapter.test.ts
- packages/workato-adapter/test/config.test.ts
- packages/workato-adapter/test/filters/add_root_folder.test.ts
- packages/workato-adapter/test/filters/field_references.test.ts
- packages/workato-adapter/test/filters/project_issuetypes.test.ts
- packages/workato-adapter/test/filters/recipe_references.test.ts
- packages/workato-adapter/test/filters/referenced_id_fields.test.ts
- packages/workato-adapter/test/filters/service_url.test.ts
not omit extended_input/output_schema when using new flag - FETCH_V2_FIELDS_TO_OMIT
From now on, users should use the FETCH_V2_FIELDS_TO_OMIT on theirs config and start getting the extended_schemas
---
preperation for deploy support - https://github.com/salto-io/salto/pull/4096 
When deploying Workato we will use the Recipe Lifecycle Managment feature. When using it without extended_schema recipe could stop, recipe parameters could change without announcing and hazards could pop up. So, we change the fetch structure, such that extended_schema enter to the Nacl
---
---
None
> fetch support for basic workato deploy

- packages/salesforce-adapter/config_doc.md
- packages/salesforce-adapter/cpq-sbaa-config-doc.md
- packages/salesforce-adapter/src/config_creator.ts
- packages/salesforce-adapter/src/types.ts
Exclude this metadata type, because apparently we should?
---
Added a couple of exclusions that were mistakenly added only to the CPQ default config.
---
Salesforce: DiscoveryAIModel metadata type is excluded in new workspaces
---
Salesforce: DiscoveryAIModel metadata type is now excluded by default from new environments
> SALTO-5263 - Salesforce: Exclude DiscoveryAIModel from Salesforce fetch

- packages/workspace/index.ts
- packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/src/workspace/state/static_files_sources/history_static_files_source.ts
- packages/workspace/src/workspace/state/static_files_sources/override_static_files_source.ts
- packages/workspace/src/workspace/static_files/common.ts
- packages/workspace/src/workspace/static_files/source.ts
- packages/workspace/test/common/nacl_file_source.ts
- packages/workspace/test/utils.ts
1. remove parser form workspace index
2. remove backwards compatibility in getStaticFile 
---
---
---
> SALTO-5485: remove backward compatibility

- packages/salesforce-adapter/src/client/client.ts
We're already doing this for metadata, let's do it for data as well
---
```
2024-03-13T13:39:49.877Z trace salesforce-adapter/client/client client.bulkLoadOperation result: [
{ id: '001Dn0000063rYsIAI', success: true, errors: [ [length]: 0 ] },
[length]: 1
]
```
---
N/A
---
N/A
> SALTO-5585 - Salesforce: Log bulk load results

- packages/salesforce-adapter/src/change_validators/duplicate_rules_sort_order.ts
- packages/salesforce-adapter/src/change_validators/invalid_listview_filterscope.ts
- packages/salesforce-adapter/src/change_validators/map_keys.ts
- packages/salesforce-adapter/src/change_validators/unknown_picklist_values.ts
- packages/salesforce-adapter/src/change_validators/unknown_users.ts
Some CV messages are too detailed and won't be grouped as expected
---
---
Salesforce: Minor changes to change validator messages
---
N/A
> SALTO-5380 - Salesforce: Remove element names from CV messages

- packages/okta-adapter/src/config.ts
Until now we used the maximum page size for specific endpoint, I switched it to be used by default
---
- Not all endpoints support page size but it has no affect for unsupported endpoints
- I prefer to put this as default as every now and then we find out we can increase page size for another type (usually default is 20 or 50)
- groups maximum page size is different from all other endpoints and it defined to be 10000 (which is the default one, but now that we override the default it needs to be mentioned explicitly)
---
None
---
None
> SALTO-5576: Modify default page size in Okta

- packages/adapter-components/src/deployment/old_deployment.ts
- packages/adapter-components/src/fetch/resource/request_parameters.ts
- packages/adapter-components/src/filters/index.ts
- packages/adapter-components/src/filters/service_url.ts
- packages/adapter-components/test/filters/service_url.test.ts
- packages/jira-adapter/src/change_validators/workflow_scheme_migration.ts
- packages/jira-adapter/src/filters/service_url/service_url.ts
- packages/jira-adapter/src/filters/service_url/service_url_jsm.ts
- packages/jira-adapter/src/utils.ts
- packages/okta-adapter/src/deployment.ts
- packages/okta-adapter/src/filters/service_url.ts
- packages/zendesk-adapter/src/filters/guide_order/guide_order_utils.ts
- packages/zendesk-adapter/src/filters/service_url.ts
- packages/zendesk-adapter/test/filters/guide_orders.test.ts
Make service url filter support the new definition type
---
---
- Service url filter support the new definition type, should have no effect on users
---
None
> SALTO-5421 support definitions in serviceUrl generic filter

- packages/adapter-components/src/fetch/element/id_utils.ts
- packages/adapter-components/src/fetch/element/instance_utils.ts
- packages/adapter-components/src/fetch/element/standalone.ts
- packages/adapter-components/test/fetch/element/id_utils.test.ts
- packages/adapter-components/test/fetch/element/instance_utils.test.ts
nestUnderParent didn't affect the nacls path
---
In order to keep the behavior we have today for `nestStandaloneInstances`, both parent and children paths should be adjusted - 
1. the parent file should be nested under its own folder
2. the children filed should be nested under the parent folder -> field name
will add tests once finalized 
---
None
---
None
> SALTO-5604: nestUnderParent standalone flag doesn't affect paths

- packages/adapter-components/src/add_alias.ts
- packages/adapter-components/src/definitions/system/fetch/element.ts
- packages/adapter-components/src/fetch/element/type_element.ts
- packages/adapter-components/src/filters/add_alias.ts
- packages/adapter-components/src/filters/index.ts
- packages/adapter-components/test/add_alias.test.ts
- packages/adapter-components/test/filters/add_alias.test.ts
- packages/jira-adapter/src/filters/add_alias.ts
- packages/okta-adapter/src/filters/add_alias.ts
- packages/zendesk-adapter/src/filters/add_alias.ts
- support defining aliases and importantValues in definitions
- build dependencies graph for addAlias function to calculate the order we should create aliases
---
---
- addAlias function is no longer supports `secondInterationsTypes` parameter, instead it builds a dependencies graph
---
None
> SALTO-5424 support defining aliases and importantValues in definitions

- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/test/adapter_creator.test.ts
---
---
SALTO-5596: do not classify testing accounts as production
---
> SALTO-5596: Classify NS testing accounts as non-production

- packages/adapter-components/package.json
- packages/adapter-components/src/fetch/request/pagination/index.ts
- packages/adapter-components/src/fetch/request/pagination/pagination_functions.ts
- packages/adapter-components/src/fetch/request/pagination/queue.ts
- packages/adapter-components/src/fetch/request/requester.ts
- packages/adapter-components/test/fetch/request/pagination/pagination_functions.test.ts
- packages/okta-adapter/src/client/pagination.ts
part of the preparations to upgrade okta to the new infra
---
The new infra gets pagination function in a slightly different formant, so in this PR I: 
- added okta's pagination to adapter-component (+ needed adjustments)
- modify logs to fallback `get` when undefined method is undefined
---
None
---
None
> SALTO-5608: Move Okta pagination function to adapter components

- packages/jira-adapter/src/client/client.ts
- packages/jira-adapter/test/client/client.test.ts
In this PR I fixed the error throwing in gqlPost
---
More context can be found in: https://salto-io.atlassian.net/browse/SALTO-5631
---
* Fixed error throwing in gqlPost for requestForm. 
---
> SALTO-5631: Fix Error Throwing In gqlPost

- packages/adapter-components/src/client/index.ts
- packages/adapter-components/src/client/polling.ts
- packages/adapter-components/src/definitions/system/requests/index.ts
- packages/adapter-components/src/definitions/system/requests/types.ts
- packages/adapter-components/src/deployment/deploy/requester.ts
- packages/adapter-components/src/fetch/request/pagination/pagination.ts
- packages/adapter-components/src/fetch/request/requester.ts
- packages/adapter-components/test/client/polling.test.ts
- packages/adapter-components/test/deployment/deploy/requester.test.ts
- packages/adapter-components/test/fetch/request/pagination/pagination.test.ts
SALTO-5414 support polling as a capability in the new infra
---
added the polling option for both deploy + fetch
completed the support in additional status codes for deploy
---
none
---
none
> SALTO-5414 support polling as a capability in the new infra

- packages/dummy-adapter/src/change_validator.ts
- packages/dummy-adapter/test/adapter.test.ts
This is needed to test missing dependencies flows, more info in ticket
---
---
None
---
None
> SALTO-5634: add outgoingUnresolvedReferencesValidator to dummy

- packages/adapter-components/src/deployment/placeholder_types.ts
- packages/adapter-components/src/fetch/element/element.ts
- packages/adapter-components/src/fetch/element/index.ts
- packages/adapter-components/src/fetch/element/instance_element.ts
- packages/adapter-components/src/fetch/element/instance_utils.ts
- packages/adapter-components/src/fetch/element/type_utils.ts
- packages/adapter-components/test/fetch/element/instance_element.test.ts
- packages/adapter-components/test/fetch/element/instance_utils.test.ts
* make sure predefined types are used for field type overrides
* first override fields types and then remove omitted field values, to fix a bug where we didn't omit nested values of overwritten fields
(this is in the new infra, not impacting existing adapters)
---
None
---
None
> SALTO-5388 fix omitting values of overridden types

- packages/adapter-components/src/fetch/element/instance_element.ts
- packages/adapter-components/src/fetch/element/standalone.ts
we should set standalone instance types based on the defined type, even if it's different from the current field type
---
None
---
None
> allow setting a standalone instance's type using predefined types

- packages/zendesk-adapter/e2e_test/adapter.test.ts
we need this to be able to run the test on an additional instance of zd
---
---
Zendesk:
Modifications to the Zendesk e2e test
---
None
> Remove a couple of fields from zendesk e2etest

- packages/adapter-components/src/elements/swagger/deployment/additional_properties.ts
- packages/adapter-components/src/elements/swagger/instance_elements.ts
- packages/adapter-components/src/elements/swagger/type_elements/element_generator.ts
- packages/adapter-components/test/elements/swagger/instance_elements.test.ts
- packages/adapter-components/test/elements/swagger/type_elements.test.ts
- packages/adapter-utils/src/utils.ts
- packages/jira-adapter/src/filters/notification_scheme/notification_events.ts
- packages/jira-adapter/src/filters/workflow/workflow_structure_filter.ts
- packages/jira-adapter/src/filters/workflow_scheme.ts
- packages/jira-adapter/test/filters/notification_scheme/notification_scheme_structure.test.ts
- packages/jira-adapter/test/filters/workflow/workflow_structure_filter.test.ts
- packages/jira-adapter/test/filters/workflow_scheme.test.ts
- packages/okta-adapter/src/filters/unordered_lists.ts
- packages/okta-adapter/src/filters/user_schema.ts
- packages/okta-adapter/test/filters/unordered_lists.test.ts
- packages/okta-adapter/test/filters/user_schema.test.ts
Keep additional properties annotation from swagger and stop creating a field `additionalProperties` 
---
---
_Jira_Adapter_:
Instances with `additionalProperties` map field will be flatten upon fetch (types to be affected: Notification Events, Workflows and maybe more)
Instances with `additionalProperties` map field will be flatten upon fetch (types to be affected: Users, GroupRule, PasswordPolicyRule and maybe more)
---
_Jira_Adapter_:
Instances with `additionalProperties` map field will be flatten upon fetch (types to be affected: Notification Events, Workflows and maybe more)
Instances with `additionalProperties` map field will be flatten upon fetch (types to be affected: Users, GroupRule, PasswordPolicyRule and …
> SALTO-5332 keep additional properties from swagger as annotation and not field

- packages/adapter-components/src/client/http_client.ts
- packages/zendesk-adapter/test/change_validators/organization_existence.test.ts
- packages/zendesk-adapter/test/client/client.test.ts
add data and headers to log when http request fails
---
---
---
> SALTO-5641: add data and headers to log when http request fails

- packages/adapter-components/src/fetch/request/pagination/pagination_functions.ts
- packages/adapter-components/test/fetch/request/pagination/pagination_functions.test.ts
In the previous PR I passed query params wrong
---
---
None
---
None
> SALTO-5608: Fix link header pagination func

- packages/salesforce-adapter/src/client/user_facing_errors.ts
- packages/salesforce-adapter/src/constants.ts
- packages/salesforce-adapter/test/client.test.ts
Sometimes Salesforce returns a whole HTML page when it encounters an internal connection error. Let's handle this.
---
---
Salesforce: better handling of internal Salesforce errors.
---
N/A
> SALTO-4832 - Salesforce: handle the case where SF returns an HTML page as an error

- packages/adapter-components/src/elements/swagger/deployment/additional_properties.ts
- packages/adapter-components/src/elements/swagger/instance_elements.ts
- packages/adapter-components/src/elements/swagger/type_elements/element_generator.ts
- packages/adapter-components/test/elements/swagger/instance_elements.test.ts
- packages/adapter-components/test/elements/swagger/type_elements.test.ts
- packages/adapter-utils/src/utils.ts
- packages/jira-adapter/src/filters/notification_scheme/notification_events.ts
- packages/jira-adapter/src/filters/workflow/workflow_structure_filter.ts
- packages/jira-adapter/src/filters/workflow_scheme.ts
- packages/jira-adapter/test/filters/notification_scheme/notification_scheme_structure.test.ts
- packages/jira-adapter/test/filters/workflow/workflow_structure_filter.test.ts
- packages/jira-adapter/test/filters/workflow_scheme.test.ts
- packages/okta-adapter/src/filters/unordered_lists.ts
- packages/okta-adapter/src/filters/user_schema.ts
- packages/okta-adapter/test/filters/unordered_lists.test.ts
- packages/okta-adapter/test/filters/user_schema.test.ts
---
---
Jira_Adapter:
Revert: Instances with additionalProperties map field will be flatten upon fetch (types to be affected: Notification Events, Workflows and maybe more)
Okta_Adapter:
Revert: Instances with additionalProperties map field will be flatten upon fetch (types to be affected: Users, GroupRule, PasswordPolicyRule and maybe more)
---
Jira_Adapter:
Revert: Instances with additionalProperties map field will be flatten upon fetch (types to be affected: Notification Events, Workflows and maybe more)
Okta_Adapter:
Revert: Instances with additionalProperties map field will be flatten upon fetch (types to be affected: Users, GroupRule, PasswordPolicyRule and maybe more)
> Revert "SALTO-5332 keep additional properties from swagger as annotation and not field (#5443)"

- packages/adapter-components/jest.config.js
- packages/adapter-components/src/definitions/system/fetch/types.ts
- packages/adapter-components/src/deployment/placeholder_types.ts
- packages/adapter-components/src/fetch/element/element.ts
- packages/adapter-components/src/fetch/element/instance_element.ts
- packages/adapter-components/src/fetch/element/standalone.ts
- packages/adapter-components/test/fetch/element/instance_element.test.ts
This continues the fix from https://github.com/salto-io/salto/pull/5623
---
This fixes the issue when the top level type is defined in swagger types, but certain standalone field are not
we need to create the missing types and then return them (by updating definedTypes)
---
None 
---
None
> Fix standalone field types

- packages/okta-adapter/src/config.ts
- packages/okta-adapter/src/filters/profile_mapping_properties.ts
- packages/okta-adapter/test/filters/profile_mapping_properties.test.ts
modify the default value of `includeProfileMappingProperties` flag to false
---
The change will only apply for new envs
---
- In new environments, ProfileMapping properties object will not be fetch by default, and can be included by turning `includeProfileMappingProperties` flag to true. Existing envs will not be affected.
---
None
> SALTO-5637: Don't fetch ProfileMapping properties for new envs

- packages/salesforce-adapter/src/client/client.ts
Retrying SFDC requests on no healthy upstream
---
---
None.
---
None.
> SALTO-5480 - Retrying SFDC requests on no healthy upstream

- .vscode/settings.json
- packages/core/test/workspace/local/state/state.test.ts
updateConfig creates a real content provider instead of the mock, so every time the test was run it saved the state file to the local directory. Instead, saving it to the tmp dir.
Also handled some spelling warnings in the file.
---
---
None.
---
None.
> SALTO-5647 - Saving test state in tmp dir

- packages/core/src/core/fetch.ts
- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/fetch_profile/metadata_query.ts
- packages/salesforce-adapter/src/filters/changed_at_singleton.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/adapter.discover.test.ts
- packages/salesforce-adapter/test/fetch_profile/metadata_query.test.ts
Add logs for Salesforce Quick Fetch
---
As part of this PR, also added a log in core that indicates we are running a quick-fetch for a specific account.
---
_None_
---
_None_
> SALTO-5660: Salesforce Quick Fetch logs

- packages/adapter-components/src/fetch/element/id_utils.ts
- packages/adapter-components/test/fetch/element/id_utils.test.ts
Fixed a bug in the new create elemId function.  Where for an elemId with extendsParent = true but without any parts. We added a redundant delimiter at the end of the elemId
---
---
None
---
None
> SALTO-5659 avoid adding additional delimiter when element only extendsParent

- packages/salesforce-adapter/src/change_validators/flows.ts
- packages/salesforce-adapter/src/elements_url_retreiver/elements_url_retreiver.ts
- packages/salesforce-adapter/src/elements_url_retreiver/lightning_url_resolvers.ts
- packages/salesforce-adapter/test/elements_url_retreiver.test.ts
Also doing some cleanup in `lightning_url_resolvers.ts`.
---
In SF there are exactly 2 instances of `AutoResponseRules`: Lead and Case. Adding a `_service_url` for them will allow us to support **Go To Service** for them.
---
- Support for Go To Service for Auto Response Rules elements.
---
None.
> SALTO-5022: Adding service URLs for SF auto response rules

- packages/salesforce-adapter/src/filters/custom_objects_instances.ts
- packages/salesforce-adapter/src/filters/custom_settings_filter.ts
- packages/salesforce-adapter/src/transformers/transformer.ts
- packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
When fetch-with-changes-detection is enabled, we only attempt to fetch instances that are referred to from instances that changed.
Instead, we should fetch instances that are referenced by instances in the workspace too, in case any of the referred-to instances changed.
---
~We cheat a little by treating `InstanceElement.value` as a `SalesforceRecord` for the purpose of finding references. This is because the data in the workspace/`elementsSource` is stored as `InstanceElement`s, but the fetched records are `SalesforceRecord`s.~
There is an issue where if the user deleted the last reference to a data record, the referred record will not be removed from the workspace. This is because we don't identify the deletion of the referring record (because we don't support deletions in quickfetch) …
> SALTO-5533 - Salesforce: Fix Quickfetch for allowReferenceTo records

- packages/adapter-components/src/definitions/system/api.ts
- packages/adapter-components/src/definitions/system/index.ts
- packages/adapter-components/src/definitions/system/references.ts
- packages/adapter-components/src/filters/field_references.ts
- packages/serviceplaceholder-adapter/src/definitions/fetch/fetch.ts
- packages/serviceplaceholder-adapter/src/definitions/references.ts
- packages/serviceplaceholder-adapter/src/definitions/types.ts
- packages/serviceplaceholder-adapter/test/adapter.test.ts
- packages/serviceplaceholder-adapter/test/fetch_mock_replies.json
---
Enable defining contextStrategyLookup within the new reference definitions - to be used in the `field_references` filter.
---
None
---
None
> SALTO-5677: Add contextStrategyLookup field to ReferenceDefinitions

- packages/okta-adapter/src/adapter.ts
- packages/okta-adapter/src/filters/access_policy_rule_constraints.ts
- packages/okta-adapter/test/filters/access_policy_rule_constraints.test.ts
Fix issue with deployment of AccessPolicyRule
---
the `required` field is optional and should be set to true when no authentication method is excluded.
The filter omits this field when it optional in order to handle misalignments in envs (when source env supports this but target env doesn't)
---
- Fix bug in deployment of Access Policy Rules with `required` field set
---
None
> SALTO-5667: Omit required field from AccessPolicyRule constraints when it's optional

- packages/zendesk-adapter/src/change_validator.ts
- packages/zendesk-adapter/src/change_validators/empty_automation_order.ts
- packages/zendesk-adapter/src/change_validators/index.ts
- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/test/change_validators/empty_automation_order.test.ts
Validating Zendesk automation order isn't empty.
---
---
_Zendesk_:
- Validating Zendesk automation order isn't empty.
---
None.
> SALTO-5184: Validating Zendesk automation order isn't empty

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/client/pagination.ts
- packages/jira-adapter/test/client/pagination.test.ts
In this PR I fixed the JSM Calendar duplication. 
---
much more context can be found in https://salto-io.atlassian.net/issues/SALTO-5683?jql=assignee%20in%20%28currentUser%28%29%29%20AND%20statusCategory%20in%20%282%2C%204%29%20ORDER%20BY%20statusCategory%20ASC%2C%20updated%20DESC
---
* Fixed duplication error that arose from a bad response for Calendar instances. 
---
None
> SALTO-5683: Fix JSM Calendar duplication 

- packages/cli/src/commands/deploy.ts
- packages/cli/src/formatter.ts
- packages/cli/src/outputer.ts
- packages/cli/src/prompts.ts
- Removing many extra newlines.
- Improving adapter names.
---
Just stuff I ran into using the CLI.
Example before changes:
After:
---
None.
---
None.
> SALTO-5679: Improve CLI ouput

- packages/salesforce-adapter/src/change_validator.ts
- packages/salesforce-adapter/src/change_validators/new_fields_and_objects_fls.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/change_validators/new_fields_and_objects_fls.test.ts
Salesforce new Custom Object And Fields Change Validator 
---
This is another iteration of https://github.com/salto-io/salto/pull/5552 that enables the CV and does not create Change Infos on added CustomFields if there's addition on their parent CustomObject.
Example:
```
CustomObject visibility in Profiles.
envs/env1/salesforce/Objects/TestObject__c/TestObject__cStandardFields.nacl(line: 1)
envs/env1/salesforce/Objects/TestObject__c/TestObject__cAnnotations.nacl(line: 1)
envs/env1/salesforce/Objects/TestObject__c/TestObject__cCustomFields.nacl(line: 1)
Info: Deploying this new CustomObject will make it and it's CustomFields accessible by the following Profiles: [Admin].
CustomField visibility in Profiles.
envs/env1/salesforce/Objects/Account/AccountCustomFields.nacl(line: 379)
Info: …
```
> SALTO-5448 SALTO-5612: Salesforce new Custom Object And Fields Change Validator 

- packages/okta-adapter/src/adapter.ts
- packages/okta-adapter/src/filters/rename_default_access_policy.ts
- packages/okta-adapter/test/filters/rename_default_access_policy.test.ts
This fixes an issue with deployment of default access policies when it was renamed in one env but not the other
---
every Okta tenant has one default access policy, the default policy has a certain rule in the configuration and therefore cannot be added (only modified in certain properties). The issue occurred during env compare when the default policies have different names across envs. As the elemIDs are different, salto identifies the changes as addition and removal instead of modification. To resolve the issue, we create a constant elemID for the default policy, alias and path remains the same for better UX.
I also had to rename all children rules as the point to the parent policy.
---
- Fix an issue with deployment of default authentication policies …
> SALTO-5684: Rename the default access policy

- packages/salesforce-adapter/src/client/client.ts
- packages/salesforce-adapter/test/client.test.ts
SFDC client retry on 406.
---
None.
---
_Salesforce_:
- Automatically retrying requests which fail with a 406 status. We are seeing these errors in the wild and they are always resolved by retrying.
---
None.
> SALTO-5514: SFDC client retry on 406

- packages/adapter-components/src/definitions/system/deploy/deploy.ts
- packages/adapter-components/src/deployment/definition_helpers.ts
- packages/adapter-components/src/deployment/deploy/requester.ts
- packages/adapter-components/src/deployment/placeholder_types.ts
- packages/adapter-components/test/adapter-wrapper/adapter.test.ts
- packages/adapter-components/test/deployment/deploy/requester.test.ts
- packages/adapter-components/test/deployment/placeholder_types.test.ts
1. Fix a bug in the new `overrideInstanceTypeForDeploy` that caused service id fields to not be marked correctly on additions if they did not exist on the instance
2. improve the `copyFromResponse` logic - separate the service id copy from custom transformations in order to avoid confusing / misaligned cases, and change the default behavior when copying service ids to use the request's `nestUnderField` as its `root`
---
None (not used yet)
---
None
> SATLO-5705 fix copyFromResponse on additions

- packages/zendesk-adapter/src/user_utils.ts
enable deployment with null user
---
---
zendesk:
* enable deployment of `__NULL__` as user
---
> SALTO-5384: enable deployment with null user

- packages/salesforce-adapter/src/filters/custom_objects_instances.ts
- packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
Do not suggest to exclude types with many instances in allowReferenceTo.
---
- Do not suggest to exclude types with many instances that are under `allowReferenceTo`.
---
_None_
> SALTO-4730: Do not suggest to exclude types with many instances in allowReferenceTo

- salto.code-workspace
When the "parser" package was created, it wasn't added to the vscode workspace file.
took the chance to also remove some folders that were already removed
---
---
_None_
---
_None_
> SALTO-5319: add missing package folders to vscode workspace

- packages/salesforce-adapter/src/client/client.ts
Retrying SFDC requests on disconnect/reset before headers.
---
None.
---
_Salesforce_:
- Retrying SFDC requests on disconnect/reset before headers.
---
None.
> SALTO-5672: Retrying SFDC requests on disconnect/reset before headers

- packages/salesforce-adapter/src/client/client.ts
Retrying SFDC requests on security policies timeout.
---
None.
---
Salesforce:
- Retrying SFDC requests on "security policies took too long to evaluate".
---
None.
> SALTO-3041: Retrying SFDC requests on security policies timeout

- packages/okta-adapter/src/adapter.ts
- packages/okta-adapter/src/filters/group_members.ts
- packages/okta-adapter/src/filters/unordered_lists.ts
- packages/okta-adapter/test/filters/unordered_lists.test.ts
To avoid comparison noise, we should sort group members
this must be done after user filter to avoid sorting based on internal ids 
---
No noise reduction is needed as this is behind an FF 
---
None
---
- members list in GroupMembership instances will be sorted
> SALTO-5711: Sort group membership members

- packages/jira-adapter/src/reference_mapping.ts
_remove workflow missing reference to security level_
---
---
_None_
---
_None_
> SALTO-5654: remove workflow missing reference to security level

- packages/jira-adapter/src/reference_mapping.ts
_revert missing reference between workflow scheme to old workflow_
---
* When turning on the new workflow flag it caused missing references to the old workflow in every workflowScheme object. It is because both types have a reference rule from workflowScheme to themself.
---
_None_
---
_None_
> SALTO-5617: revert missing reference between workflow scheme to old workflow

- packages/adapter-components/src/elements/swagger/deployment/additional_properties.ts
- packages/adapter-components/src/elements/swagger/instance_elements.ts
- packages/adapter-components/src/elements/swagger/type_elements/element_generator.ts
- packages/adapter-components/test/elements/swagger/instance_elements.test.ts
- packages/adapter-components/test/elements/swagger/type_elements.test.ts
- packages/adapter-components/test/fetch/element/openAPI/types.test.ts
- packages/adapter-utils/src/additional_properties.ts
- packages/adapter-utils/src/utils.ts
- packages/adapter-utils/test/additional_properties.test.ts
- packages/jira-adapter/src/filters/notification_scheme/notification_events.ts
- packages/jira-adapter/src/filters/workflow/workflow_structure_filter.ts
- packages/jira-adapter/src/filters/workflow_scheme.ts
- packages/jira-adapter/test/filters/notification_scheme/notification_scheme_structure.test.ts
- packages/jira-adapter/test/filters/workflow/workflow_structure_filter.test.ts
- packages/jira-adapter/test/filters/workflow_scheme.test.ts
- packages/okta-adapter/src/filters/unordered_lists.ts
- packages/okta-adapter/src/filters/user_schema.ts
- packages/okta-adapter/test/filters/unordered_lists.test.ts
- packages/okta-adapter/test/filters/user_schema.test.ts
- packages/zuora-billing-adapter/src/config.ts
- packages/zuora-billing-adapter/src/filters/object_defs.ts
- packages/zuora-billing-adapter/src/filters/workflow_and_task_references.ts
- packages/zuora-billing-adapter/test/adapter.test.ts
- packages/zuora-billing-adapter/test/filters/object_defs.test.ts
- packages/zuora-billing-adapter/test/filters/workflow_and_task_references.test.ts
- Stop creating additionalProperties field upon fetch
- Save reference to a type in _additional_properties annotation
---
---
_Jira_Adapter_:
Instances with additionalProperties map field will be flatten upon fetch (types to be affected: Notification Events, Workflows and maybe more)
Instances with additionalProperties map field will be flatten upon fetch (types to be affected: Users, GroupRule, PasswordPolicyRule and maybe more)
_Zuora_billing_Adapter_:
Instances with additionalProperties map field will be flatten upon fetch
_Stripe_Adapter_:
Instances with additionalProperties map field will be flatten upon fetch
---
_Jira_Adapter_:
Instances with additionalProperties map field will be flatten upon fetch (types to be affected: …
> SALTO-5332 stop creating additionalProperties map field and use the annotation instead

- packages/okta-adapter/e2e_test/adapter.test.ts
- packages/okta-adapter/e2e_test/mock_elements.ts
Looks like Okta changed back SAML app structure after changing it back in november (https://github.com/salto-io/salto/pull/5075)
also added some logs for easier debugging next time
---
---
None
---
None
> SALTO-5275: Fix Okta E2E

- packages/adapter-components/src/definitions/system/fetch/dependencies.ts
- packages/adapter-components/src/fetch/resource/subresources.ts
- packages/adapter-components/test/adapter-wrapper/adapter.test.ts
- packages/adapter-components/test/fetch/fetch.test.ts
- packages/adapter-components/test/fetch/resource/subresources.test.ts
- packages/serviceplaceholder-adapter/src/definitions/fetch/fetch.ts
Allow passing transformation for recurseInto in order to adjust values before using in recurse into
---
---
None 
---
None
> SALTO-5704: Allow using transformation in recurseInto

- packages/okta-adapter/config_doc.md
- packages/okta-adapter/src/fetch_criteria.ts
- packages/okta-adapter/test/fetch_criteria.test.ts
Allow filtering by type, status, group
---
Added originally to support the option to exclude the "Everyone" group
---
- Allow filtering instances using fetch criteria by type, status, and group names. For example, to exclude all inactive apps, use:
```
okta = {
fetch = {
...
exclude = [
{
type = "Application"
criteria = {
status = "INACTIVE"
}
}
]
}
}
```
---
None
> SALTO-5722: allow filtering instances by type, status and group names in Okta

- packages/adapter-components/src/references/reference_mapping.ts
- packages/adapter-components/test/references/field_references.test.ts
- packages/jira-adapter/src/filters/field_references.ts
- packages/jira-adapter/src/filters/layouts/create_references_layouts.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/okta-adapter/src/filters/field_references.ts
- packages/okta-adapter/src/reference_mapping.ts
Consolidate missing ref strategies between okta and jira and allow reusing missing ref strategies for other adapters
---
---
None
---
None
> SALTO-5721: Consolidate missing ref strategies between okta and jira

- packages/zendesk-adapter/src/change_validator.ts
- packages/zendesk-adapter/src/change_validators/active_action_features.ts
- packages/zendesk-adapter/src/change_validators/index.ts
- packages/zendesk-adapter/src/change_validators/utils.ts
- packages/zendesk-adapter/src/change_validators/view_custom_status_conditions.ts
- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/test/change_validators/active_action_features.test.ts
- packages/zendesk-adapter/test/change_validators/view_custom_status_conditions.test.ts
Adding a new validator that emits errors when custom statuses are disabled for the account but used in view conditions.
---
---
_Zendesk_:
- Added a new validator that emit errors when custom statuses are disabled for the account but used in view conditions.
---
None.
> SALTO-5413: Validating views with custom status conditions

- packages/zendesk-adapter/src/filters/unordered_lists.ts
Article labels are unordered, so add them to the unordered_list to make sure they don't show up in changesets while deploying
---
_Test Plan_: 
Before:
After:
---
Zendesk:
Stop showing Article Label ordering in deployment changesets
---
Zendesk:
Stop showing Article Label ordering in deployment changesets
> SALTO-5067: [Zendesk] Remove Article label ordering from the deployment changeset

- packages/jira-adapter/src/change_validators/account_id.ts
- packages/jira-adapter/test/change_validators/account_id.test.ts
SALTO-5347 change accountId CV message to be generic
---
None
---
None
---
None
> SALTO-5347 change accountId CV message to be generic

- .prettierignore
We want to be able to define mock replies JSONs (like [this one](https://github.com/salto-io/salto/blob/main/packages/serviceplaceholder-adapter/test/fetch_mock_replies.json)) in a more concise format. Therefore, we should disable Prettier for JSON files located directly within test directories.
---
---
None
---
None
> SALTO-5404: Set prettier to ignore json files under test folder

- packages/parser/src/parser/internal/native/lexer.ts
- packages/parser/test/parser/parse.test.ts
Fix multiline regex to support $ before a reference
For example: "Cost:  ${{issue.Cost}} for year" - we should be able to escape the given $, and match the reference to cost
---
None
---
None
---
None
> SALTO-5599 Fix multiline regex to support $ before a reference

- packages/netsuite-adapter/package.json
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/adapter_creator.ts
- packages/netsuite-adapter/src/change_validator.ts
- packages/netsuite-adapter/src/change_validators/custom_record_empty_permission_list.ts
- packages/netsuite-adapter/src/change_validators/remove_list_item_without_scriptid.ts
- packages/netsuite-adapter/src/config/types.ts
- packages/netsuite-adapter/src/custom_references/index.ts
- packages/netsuite-adapter/src/custom_references/weak_references/permissions_references.ts
- packages/netsuite-adapter/test/change_validators/custom_record_empty_permission_list.test.ts
- packages/netsuite-adapter/test/custom_references/weak_references/permissions_references.test.ts
- packages/workspace/src/workspace/reference_indexes.ts
_Added weak references to Netsuite
Currently applied to references in permissions between roles and custom record types_
---
_SALTO-4142: https://salto-io.atlassian.net/browse/SALTO-4142_
---
_Fix elements will now remove permissions with unresolved references_
---
_None_
> SALTO-4142 - Netsuite weak references addition

- packages/okta-adapter/src/change_validators/dynamic_os_version_feature.ts
- packages/okta-adapter/src/change_validators/index.ts
- packages/okta-adapter/src/config.ts
- packages/okta-adapter/test/change_validators/dynamic_os_version_feature.test.ts
Add a validator to notify user when trying to deploy device assurance with dynamic os constraints and the feature is not enabled in the account.
---
---
- When deploying Device Assurance Policies with dynamic OS constraints, verify the dynamic OS feature is enabled in the target account
---
None
> SALTO-5686: Validate dynamic OS constraints on DeviceAssurancePolicy (Okta)

- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/filters/organization_settings.ts
- packages/salesforce-adapter/src/filters/utils.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/filters/organization_settings.test.ts
In preparation for fetching supported API versions.
---
None.
---
None.
---
None.
> SALTO-5279: Cleaning up organization settings filter

- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/filters/automation/automation_deployment.ts
- packages/jira-adapter/src/filters/automation/types.ts
- packages/jira-adapter/src/filters/request_type.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/test/filters/automation/automation_deployment.test.ts
- packages/jira-adapter/test/filters/request_type.test.ts
In this PR I modified the requestType field in automation to be a reference and added required `serviceDesk` field with the correct value.  
---
---
None
---
* for automation nacls: serviceDesk field will be removed and requestType field will be converted from string to reference expression.
> SALTO-5735: Add requestType field in automaiton

- packages/okta-adapter/src/reference_mapping.ts
- packages/okta-adapter/test/filters/field_references.test.ts
The issue we didn't modify okta to use `serializationStrategy` instead of `oktaSerializationStrategy` that is no longer supported
---
This continues the changes in 
https://github.com/salto-io/salto/commit/7727b40fffa5756989818959cccf01bde4de73a4
---
None
---
None
> SALTO-5752: Fix custom serialization strategy in Okta

- packages/adapter-components/src/fetch/element/instance_utils.ts
- packages/adapter-components/test/fetch/element/instance_utils.test.ts
recursiveNaclCase was only changing top level keys
---
The issue was that `cloneDeepWith` was not iterating through the value once it received the result from the customizer
---
None
---
None
> SALTO-5747: recursiveNaclCase is not iterating inner value

- packages/zendesk-adapter/src/filters/field_references.ts
Add missing reference to skills in trigger actions
---
---
Zendesk:
- Add reference to skills in trigger actions
---
_User Notifications_:  _None_
> SALTO-5611 add references to add_skills, set_skills, and remove_skills in trigger actions

- packages/salesforce-adapter/src/change_validators/deleted_non_queryable_fields.ts
- packages/salesforce-adapter/test/change_validators/deleted_non_queryable_fields.test.ts
Improving SFDC non queryable fields warning.
---
None.
---
None.
---
None.
> SALTO-5726: Improve SFDC non queryable fields warning

- packages/adapter-components/src/deployment/change_validators/outgoing_unresolved_references.ts
- packages/adapter-components/test/deployment/change_validators/outgoing_unresolved_references.test.ts
- packages/adapter-utils/src/compare.ts
- packages/adapter-utils/src/utils.ts
- packages/adapter-utils/test/utils.test.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/workspace.test.ts
This PR fix the redundancy in showing a missing dependency for a field when its parent type is also a missing dependency
---
2 main changes here - 
- Modify `getOutgoingUnresolvedReferences` to avoid including missing references to nested elements if their parent is already a missing reference. 
- Modify `listElementsDependenciesInWorkspace` to do the same when recursively listing dependencies to a specific elemID. This is done per element's dependency and not on the entire result to avoid omiting nested elements that are explicitly required without their parent.
note that changing `listElementsDependenciesInWorkspace` also changes `--listUnresolved`, so LMK if you think I should add a flag to avoid it.
---
None
---
None
> SALTO-5744: Don't list nested elemIDs as missing dependencies if their parent is already a missing dependency 

- packages/netsuite-adapter/src/change_validators/data_account_specific_values.ts
- packages/netsuite-adapter/src/change_validators/remove_sdf_elements.ts
- packages/netsuite-adapter/src/change_validators/report_types_move_environment.ts
- packages/netsuite-adapter/test/change_validators/data_account_specific_values.test.ts
- packages/netsuite-adapter/test/change_validators/remove_sdf_elements.test.ts
---
---
SALTO-5750: NetSuite change validator messages wrongly contain element names
---
> SALTO-5750: NetSuite change validator messages wrongly contain element names

- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/filters/custom_objects_instances.ts
- packages/salesforce-adapter/src/filters/utils.ts
- packages/salesforce-adapter/test/adapter.discover.test.ts
- packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
In the quickfetch case we need to determine which records were deleted on the Salesforce side so we can delete them on our end. The simple way to do this would be to use a SOQL query with all the IDs of the records that exist in the workspace and see which of them are not returned. 
---
There's a small optimization of not querying for IDs of records that we just fetched, because we know those records were not deleted.
Tests:
- Do a full fetch, delete an account, do a quickfetch, observe the account being deleted.
---
Salesforce: quickfetch will now correctly identify deleted records
---
N/A
> SALTO-5534 - Salesforce: support data records deletions in quickfetch

- packages/adapter-components/src/fetch/request/requester.ts
pass the relevant request's context to the transformation
will add unittests together with the rest of the missing coverage for this logic
---
None
---
None
> SALTO-5707 pass context correctly

- packages/okta-adapter/e2e_test/adapter.test.ts
- packages/okta-adapter/e2e_test/mock_elements.ts
Changing mock element so the E2E can pass until a I'll add a full fix
---
---
None 
---
None
> SALTO-5779: Modify network zone to inactive to make E2E pass

- packages/adapter-components/src/filters/referenced_instance_names.ts
- packages/adapter-components/test/filters/referenced_instance_names.test.ts
NestUnderParent should take the fieldName and not the fieldTypeName
---
---
Fix nestUnderParent incorrect folder name
---
None
> SALTO-5775 fix nestUnderParent

- packages/jira-adapter/e2e_test/instances/cloud/jsm/objectType.ts
- packages/jira-adapter/src/config/api_config.ts
In this PR I removed object count field from objectType instances (requested by @liorn )
---
---
* objectTypes will have no field called objectCount. 
---
* objectTypes will have no field called objectCount.
> Salto 5781 remove object count from object types

- packages/okta-adapter/e2e_test/mock_elements.ts
- packages/okta-adapter/src/deployment.ts
- packages/okta-adapter/test/deployment.test.ts
Okta recently made a change and they no longer allow removing an active network zone
The solution is to deactivate the network zone before trying to delete it 
---
---
- Okta no longer allow to delete an active NetworkZone, Salto will no deactivate NetworkZone when trying to delete it
---
None
> SALTO-5779: Deactivate NetworkZone before removal

- packages/adapter-components/src/definitions/user/user_config.ts
- packages/adapter-components/test/adapter-wrapper/adapter.test.ts
- packages/adapter-components/test/filters/common_filters.test.ts
- packages/confluence-adapter/src/config.ts
- packages/google-workspace-adapter/src/config.ts
- packages/intercom-adapter/src/config.ts
- packages/serviceplaceholder-adapter/src/config.ts
minor improvements to the user defaults to clean up the resulting env and config
---
None
---
None
> SALTO-5293 hide types by default, avoid requiring client config

- packages/zendesk-adapter/src/filters/unordered_lists.ts
- packages/zendesk-adapter/test/filters/unordered_lists.test.ts
Apps in workspace need to be ordered by position.
---
This should not merge implementing noise reduction or prod ticket
---
Zendesk:
- Active apps inside workspace will now be ordered by position
---
> SALTO-5516 Make sure that apps in workspace are ordered by position

- packages/zendesk-adapter/src/custom_references/weak_references/order_elements.ts
- packages/zendesk-adapter/src/fix_elements/fallback_user.ts
- packages/zendesk-adapter/src/fix_elements/remove_dup_users.ts
- packages/zendesk-adapter/test/fix_elements/fallback_user.test.ts
- packages/zendesk-adapter/test/fix_elements/remove_dup_users.test.ts
- packages/zendesk-adapter/test/weak_references/order_elements.test.ts
Remove numbers and names from change validator messages so that they will be groupable
---
The information still exists in the detailed message field of the change validator.
---
_Release Notes_: _None_ 
---
> SALTO-5751 Remove elements and numbers from change validator messages

- packages/adapter-utils/src/additional_properties.ts
- packages/adapter-utils/test/additional_properties.test.ts
- packages/jira-adapter/e2e_test/adapter.test.ts
Fix unintentional fallback to `additionalProperties = false` on loadWorkspace
---
will also check if there are other similar assumptions before merging, and try to add a UT
---
* Fix issue that would cause false pending changes to remain after deploy
---
None
> SALTO-5788 do not rely on types being loaded

- packages/jira-adapter/e2e_test/instances/cloud/index.ts
- packages/jira-adapter/e2e_test/instances/cloud/scriptrunner/scripted_fields.ts
Changed the ScriptedFields to meet the new structure
---
None
---
None
---
None
> SALTO-5797: fix jira E2E for scriptRunner

- packages/google-workspace-adapter/src/definitions/deploy/deploy.ts
SALTO-5728 Google WS omit domainAliases deploy when creating domain
---
---
none
---
none
> SALTO-5728 Google WS omit domainAliases deploy when creating domain

- packages/jira-adapter/src/filters/duplicate_ids.ts
- packages/jira-adapter/test/filters/duplicate_ids.test.ts
Change duplicate id message for better visualization
---
None
---
duplicate id message in Jira was changed for better visualization
---
None
> SALTO-5786 Change duplicate id message

- packages/adapter-components/src/definitions/system/deploy/deploy.ts
- packages/adapter-components/src/deployment/deploy/requester.ts
- packages/google-workspace-adapter/src/adapter_creator.ts
- packages/google-workspace-adapter/src/client/connection.ts
- packages/google-workspace-adapter/src/client/oauth.ts
- packages/google-workspace-adapter/src/definitions/deploy/deploy.ts
- packages/google-workspace-adapter/src/definitions/fetch/fetch.ts
- packages/google-workspace-adapter/src/definitions/requests/clients.ts
- packages/google-workspace-adapter/src/definitions/types.ts
SALTO-5796 Google workspace support cloud identity api for group labels
---
---
none
---
none
> SALTO-5796 Google workspace support cloud identity api for group labels

- packages/adapter-components/src/deployment/change_validators/skip_parents_of_skipped_instances.ts
change createSkipParentsOfSkippedInstancesValidator error message
---
---
---
> SALTO-5220: change createSkipParentsOfSkippedInstancesValidator error message

- packages/zendesk-adapter/src/change_validators/not_enabled_missing_references.ts
fix notEnabledMissingReferencesValidator
---
---
---
> SALTO-5808: fix notEnabledMissingReferencesValidator

- packages/okta-adapter/e2e_test/mock_elements.ts
- packages/okta-adapter/src/adapter.ts
- packages/okta-adapter/src/adapter_creator.ts
- packages/okta-adapter/src/config.ts
- packages/okta-adapter/src/constants.ts
- packages/okta-adapter/src/filters/default_rule_deployment.ts
- packages/okta-adapter/src/filters/policy_rule_priority.ts
- packages/okta-adapter/src/fix_elements/index.ts
- packages/okta-adapter/src/fix_elements/types.ts
- packages/okta-adapter/src/weak_references/index.ts
- packages/okta-adapter/src/weak_references/policy_rule_priorities.ts
- packages/okta-adapter/src/weak_references/weak_references_handler.ts
- packages/okta-adapter/test/filters/policy_rule_priority.test.ts
- packages/okta-adapter/test/fix_elements/missing_users.test.ts
- packages/okta-adapter/test/weak_references/policy_rule_priorities.test.ts
In this PR:
1. I added a filter that fetches and deploys policy rules priories into an instance.
2. Added a weak reference mechanism to allow deploying order without all the instances in it.  
---
1. **I will add tests after first review when the tech design will be approve.** 
3. View of the nacl:
4. View of the element tree
@shir-reifenberg I don't think that the priority should actually be inside its own folder. WDYT?
---
_Okta Adapter:_
* New instances responsible for policy rules priorities were added. 
---
_Okta Adapter:_
* New instances responsible for policy rules priorities were added.
> SALTO-4094: Deploy priority instance for policy

- packages/jira-adapter/e2e_test/instances/cloud/jsm/objectTypeAttribute.ts
- packages/jira-adapter/src/filters/assets/attribute_deploy_filter.ts
- packages/jira-adapter/src/reference_mapping.ts
Added support for reference expression in TypeValueMulti field 
---
| Status | ObjectSchemaStatus | Group |
|--------|--------------------|-------|
| <img width="1728" alt="Screenshot 2024-04-14 at 12 27 08" src="https://github.com/salto-io/salto/assets/63644199/73558e74-f5ce-4c7e-8ddb-7e0142f1dd9f"> | <img width="1728" alt="Screenshot 2024-04-14 at 12 27 59" src="https://github.com/salto-io/salto/assets/63644199/cda0c718-7233-4378-84f2-5e93e2ee64e5"> | <img width="1728" alt="Screenshot 2024-04-14 at 12 28 26" src="https://github.com/salto-io/salto/assets/63644199/5c3a9877-fef6-45fe-9f68-239e8dc7c52f"> |
---
* Fixed bug SALTO-5793 by added references from objectTypeAttribute to statuses, objectSchemaStatuses and groups. …
> SALTO-5793: Add TypeValueMulti References in ObjectTypeAttribute

- package.json
- packages/zendesk-adapter/config_doc.md
- packages/zendesk-adapter/e2e_test/adapter.test.ts
- packages/zendesk-adapter/package.json
- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/guide_theme.ts
- packages/zendesk-adapter/src/filters/template_engines/creator.ts
- packages/zendesk-adapter/src/filters/template_engines/handlebar_parser.ts
- packages/zendesk-adapter/src/filters/template_engines/html_parser.ts
- packages/zendesk-adapter/src/filters/template_engines/javascript_extractor.ts
- packages/zendesk-adapter/src/filters/template_engines/javascript_parser.ts
- packages/zendesk-adapter/src/filters/template_engines/types.ts
- packages/zendesk-adapter/src/filters/template_engines/utils.ts
- packages/zendesk-adapter/src/filters/utils.ts
- packages/zendesk-adapter/test/adapter.test.ts
- packages/zendesk-adapter/test/filters/guide_theme.test.ts
- packages/zendesk-adapter/test/filters/guide_theme_settings.test.ts
- packages/zendesk-adapter/test/filters/template_engines/creator.test.ts
- packages/zendesk-adapter/test/filters/template_engines/handlebar_parser.test.ts
- packages/zendesk-adapter/test/filters/template_engines/html_parser.test.ts
- packages/zendesk-adapter/test/filters/template_engines/javascript_extractor.test.ts
- packages/zendesk-adapter/test/filters/template_engines/javascript_parser.test.ts
- packages/zendesk-adapter/test/filters/template_engines/utils.test.ts
- yarn.lock
Add support to fetch template static files in Zendesk guide themes
---
---
---
> SALTO-3080 Fetch guide theme with references

- packages/salesforce-adapter/src/change_validator.ts
- packages/salesforce-adapter/src/change_validators/element_api_version.ts
- packages/salesforce-adapter/src/client/client.ts
- packages/salesforce-adapter/src/client/jsforce.ts
- packages/salesforce-adapter/src/filters/organization_settings.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/change_validators/element_api_version.test.ts
- packages/salesforce-adapter/test/connection.ts
- packages/salesforce-adapter/test/filters/organization_settings.test.ts
- packages/salesforce-adapter/test/utils.ts
Adds the latest supported API versions to the organization settings as a hidden field and then validates flows do not use a later version.
We can easily add additional elements to this validation as needed.
---
Note the new field is hidden, so no need for release notes or notifications.
---
_Salesforce_:
* Added a new change validator which checks for flows with an unsupported API version.
---
None.
> SALTO-5279: Validating SFDC flows do not use an unsupported API version

- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/view.ts
- packages/zendesk-adapter/test/filters/view.test.ts
When removing the restriction field in views, it must be set to null for the service to understand that it was on purpose.
---
When changing restrictions on views to "all agents", Zendesk sets the field to null. We should exhibit the same behavior as the service.
---
---
> SALTO-5639 allow removing restriction field in views

- packages/adapter-components/src/definitions/system/deploy/request.ts
- packages/adapter-components/src/definitions/system/fetch/request.ts
- packages/adapter-components/src/definitions/system/shared/transformation.ts
- packages/adapter-components/src/deployment/deploy/requester.ts
- packages/adapter-components/src/fetch/request/requester.ts
- packages/adapter-components/test/deployment/deploy/requester.test.ts
- packages/adapter-components/test/fetch/request/requester.test.ts
- packages/google-workspace-adapter/jest.config.js
- packages/google-workspace-adapter/src/definitions/deploy/deploy.ts
Allow using a custom function for defining context args for request url/body, both in fetch and in deploy.
---
The immediate use case is for google workspace, where we need the "before" name in a request url.
---
None
---
None
> SALTO-5749 custom request context

- packages/adapter-components/src/deployment/placeholder_types.ts
- packages/adapter-components/test/deployment/placeholder_types.test.ts
we create synthetic types during deploy in order to support creating the first instance of its type / other cases in ducktype adapters that might not have all fields defined accurately during fetch.
added a fallback in case a service id field does not exist at all (which happens when the first instance of its type is created)
---
None
---
None
> SALTO-5814 default service id field type if missing when replacing types during deploy

- packages/core/src/local-workspace/s3_dir_store.ts
- packages/core/test/workspace/local/s3_dir_store.test.ts
- packages/workspace/src/workspace/static_files/common.ts
In this Pr I added support for deletion with S3 dir store.
---
---
_Core Adapter:_
* Added support for deletion in S3 dir store.
---
> SALTO-5807: Added S3 dir store Deletion

- packages/salesforce-adapter/src/filters/utils.ts
- packages/salesforce-adapter/test/adapter.discover.test.ts
This keeps the state file consistent across fetches.
---
---
N/A
---
N/A
> SALTO-5745 - Salesforce: When duplicate file props are retrieved, keep the most up-to-date one

- packages/adapter-api/src/builtins.ts
- packages/adapter-api/test/adapter.test.ts
- packages/adapter-api/test/builtins.test.ts
- packages/adapter-api/test/comparison.test.ts
- packages/adapter-api/test/values.test.ts
Coverage dropped a bit lately in the SFDC adapter so making up for it a bit here.
---
Note that the implementation of `isServiceId` in `packages/adapter-api/src/builtins.ts` changed because the UT picked up on it not actually returning a boolean...
---
None.
---
None.
> Improving coverage in adapter-api

- packages/adapter-components/src/adapter-wrapper/adapter/adapter.ts
- packages/adapter-components/src/adapter-wrapper/adapter_creator.ts
- packages/adapter-components/src/deployment/change_validators/check_deployment_based_on_definitions.ts
- packages/adapter-components/src/deployment/change_validators/index.ts
- packages/adapter-components/test/deployment/change_validators/check_deployment_based_on_definitions.test.ts
- packages/google-workspace-adapter/src/adapter_creator.ts
SALTO-5703 convert create-check-deployment-based-on-config-validator to work with definitions
---
Also added the option to pass additional CV to the new createAdapter func and pass the new definitions CV to google WS adapter
---
none
---
none
> SALTO-5703 convert create-check-deployment-based-on-config-validator to work with definitions

- docs/syntax.md
- packages/adapter-api/src/builtins.ts
- packages/adapter-api/test/builtins.test.ts
The docs were a bit misleading so it wasn't clear that the `_service_id` annotation is a bool (and not `_is_service_id`), leading to the change in salto-io#5794.
Reverted the implementation and updated the test.
Also corrected the docs and fixed some lint warnings.
---
---
None.
---
None.
> Reverting isServiceId change

- packages/jira-adapter/src/filters/layouts/issue_layout.ts
- packages/jira-adapter/test/filters/layouts/issue_layout.test.ts
I change the code so that it will bring all the issue layouts of the projects and also prevent fetching issue layouts that do not exist
I added a function that will do it and I also deleted part of the code that maps for the second time projects to the issue layout and used the first map
---
---
Jira adapter: 
* Fixed a bug that prevented fetching some of the issue layouts
---
None
> SALTO-5520: fix issue Layout for view screen

- packages/salesforce-adapter/src/filters/settings_type.ts
Always Retrieve Settings Instances in Fetch With Changes Detection
---
_None_
---
_None_
> SALTO-4820: Always Retrieve Settings Instances in Fetch With Changes Detection (Salesforce)

- packages/workspace/src/workspace/static_files/functions.ts
- packages/workspace/src/workspace/static_files/source.ts
- packages/workspace/test/workspace/static_files/functions.test.ts
- packages/workspace/test/workspace/static_files/source.test.ts
It now will never call `staticFilesDirStore.get` when `ignoreChanges` is true.
Also allow undefined buffer for persistStaticFile.
---
---
---
> SALTO-5699 Update ignoreChanges flow

- packages/confluence-adapter/jest.config.js
- packages/confluence-adapter/src/definitions/deploy/deploy.ts
- packages/confluence-adapter/src/definitions/fetch/fetch.ts
- packages/confluence-adapter/src/definitions/transformation_utils/index.ts
- packages/confluence-adapter/src/definitions/transformation_utils/restriction.ts
- packages/confluence-adapter/test/deploy_mock_replies.json
- packages/confluence-adapter/test/transformation_utils/restriction.test.ts
Clean up redundant details on restrictions on fetch + support deploy.
---
Tested on addition + modification
---
* Add support for deploying page restrictions
---
None
> SALTO-5738 support deploy for page restrictions

- packages/adapter-utils/src/important_values.ts
- packages/adapter-utils/test/important_values.test.ts
For better understanding of the context of an important value, e.g. we now return `accountId.author` instead of just `author`.
---
---
---
> SAAS-10839 Return nested important value keys

- packages/adapter-components/src/filters/common_filters.ts
looks like this was accidentally removed in https://github.com/salto-io/salto/pull/5735/files#diff-3e1148f4e7287ce92424fbadcb6a495f5ca06d76e77daaac91ff6fab41c78272L73
we should add a test for it, adding a fix first
---
None
---
None
> fix custom reference resolution during deploy

- packages/google-workspace-adapter/src/definitions/fetch/fetch.ts
SALTO-5843 Google ws - remove domain annotation from groups
---
---
none
---
none
> SALTO-5843 Google ws - remove domain annotation from groups

- packages/jira-adapter/src/filters/layouts/issue_layout.ts
- packages/jira-adapter/test/filters/layouts/issue_layout.test.ts
Fixed a bug that causes users with empty issueTypeSchemes fetches to fail
---
None
---
Jira Adapter:
* Fixed a bug that caused failed fetches for some customers due to changes in issue layouts filter
---
None
> SALTO-5520: Fix issue layout crashes

- packages/confluence-adapter/src/definitions/deploy/deploy.ts
- packages/confluence-adapter/src/definitions/fetch/fetch.ts
- packages/confluence-adapter/src/definitions/transformation_utils/template.ts
- packages/confluence-adapter/test/transformation_utils/template.test.ts
* First label fetch + fake deploy support, to unblock template deployments. labels do not need to be created directly, if they are created without an id they are available implicitly
* Fix non-global template addition + modification to correctly pass in the space key
---
* Support linking templates to existing labels
* Fix deployment of templates inside spaces
---
None
> SALTO-5816 support label deploy in templates

- packages/adapter-components/src/deployment/change_validators/check_deployment_based_on_definitions.ts
- packages/adapter-components/test/deployment/change_validators/check_deployment_based_on_definitions.test.ts
Treat `earlySuccess: true` as a valid request and do not block it
---
None
---
None
> SALTO-5703 allow earlySuccess

- packages/jira-adapter/src/filters/layouts/issue_layout.ts
Fixed a bug in the log that caused Jira fetches to crash.
---
I tried stringifying an object that was too big before. I did not need the value (an instance element), only the key (a string/number).
I know the usage of 'Value' there sucks, but I did not want to change it now and introduce more complexity
---
None
---
None
> SALTO-5845: fixed a log bug

- .circleci/config.yml
Separate each package's e2e test into its own job in CircleCI so that they run in parallel
---
This still runs all e2e tests regardless of which package changed, but will make it easier to see which package's e2e tests failed, and rerun only that package instead of all e2es
---
---
> SALTO-2242 separate e2es into their own workflow

- packages/confluence-adapter/src/definitions/deploy/deploy.ts
- packages/confluence-adapter/src/definitions/transformation_utils/restriction.ts
- packages/confluence-adapter/test/transformation_utils/restriction.test.ts
- When deploying a page addition with default restriction we should not modify restriction after addition as default restrictions are created anyway
- When deploying a page modification with default restriction we should not modify restriction but delete the existing restriction. Deletion, resets the restriction to the default
---
---
- Fully support restrictions on page deployment
---
- Fully support restrictions on page deployment
> SALTO-5738 handle default restriction on page deployment

- packages/zendesk-adapter/src/filters/dynamic_content.ts
- packages/zendesk-adapter/src/filters/utils.ts
- packages/zendesk-adapter/test/filters/dynamic_content.test.ts
When creating dynamic content, Zendesk automatically takes the title and creates the placeholder from it, regardless of what was sent as a placeholder. To overcome this, we create two changes, one that creates the dynamic content item with a title that will translate to the placeholder we expect, and a second to modify the title to the final expected title.
---
---
Zendesk:
* Allow adding dynamic content items whose placeholders and titles are different
---
_User Notifications_:  _None_
> SALTO-5671 allow creation of dynamic content whose placeholder and title are different

- packages/lowerdash/src/collections/asynciterable.ts
- packages/lowerdash/test/collections/asynciterable.test.ts
- packages/netsuite-adapter/src/custom_references/index.ts
- packages/netsuite-adapter/src/custom_references/weak_references/fields_references.ts
- packages/netsuite-adapter/src/custom_references/weak_references/permissions_references.ts
- packages/netsuite-adapter/test/custom_references/weak_references/fields_references.test.ts
_Define the references in forms to be weak references.
Making it possible to deploy a form to a target environment that doesn't have all the referenced fields without adding all those fields to the deployment._
---
_Jira ticket: https://salto-io.atlassian.net/browse/SALTO-5537_
---
_None_
---
_None_
> SALTO-5537: exclude fields with unresolved references in forms

- packages/jira-adapter/src/change_validators/jsm/jsm_permissions.ts
- packages/jira-adapter/test/change_validators/jsm/jsm_permissions.test.ts
In this PR I fixed JSM permission change validator
---
When a user has enableJSM set to true, but no JSM enabled in the service. he is failing in jsm_permissions CV since he is trying to access an endpoint that is JSM related. We should check if JSM is enabled in the CV before we check separately for each project. 
---
* The bug where deploy fails when a user has `enableJSM = true` but no JSM in the service is solved. 
---
None
> SALTO-5865: Fix jsm permissions change validator 

- packages/netsuite-adapter/e2e_test/adapter.test.ts
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/client/sdf_parser.ts
- packages/netsuite-adapter/src/client/types.ts
- packages/netsuite-adapter/src/sdf_folder_loader.ts
- packages/netsuite-adapter/src/transformer.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/netsuite-adapter/test/client/sdf_client.test.ts
- packages/netsuite-adapter/test/client/sdf_parser.test.ts
- packages/netsuite-adapter/test/transformer.test.ts
---
---
SALTO-4227: NS: SDF Loader shouldn't set attributes from the existing instance
---
> SALTO-4227: NS: SDF Loader shouldn't set attributes from the existing instance

- packages/adapter-components/src/resolve_utils.ts
- packages/adapter-utils/src/utils.ts
- packages/zendesk-adapter/src/adapter.ts
add new useElementSourceForTypes flag for resolveValues func
---
---
* Fix issues on deploy of some values containing reference expressions
---
> SALTO-5872: add new useElementSourceForTypes flag for resolveValues func

- packages/jira-adapter/src/filters/workflow/transition_structure.ts
- packages/jira-adapter/test/filters/script_runner/workflow/workflow_references.test.ts
_remove missing reference when transitionId is empty_
---
* the users can use the transition name as a reference. Currently when they do that the id field is empty and they get a missingReference  that creates a fetch warning and blocks their deployment
---
_None_
---
_None_
> SALTO-4976: remove missing reference when transitionId is empty

- packages/jira-adapter/src/filters/automation/automation_deployment.ts
- packages/jira-adapter/src/filters/automation/automation_fetch.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/test/filters/automation/automation_deployment.test.ts
- packages/jira-adapter/test/filters/automation/automation_fetch.test.ts
In this PR I added recursive methods to support the children and conditions of automation components. 
---
Much more context can be found [here](https://salto-io.atlassian.net/browse/SALTO-5856).
---
*  The fields 'workspaceId', 'schemaLabel', 'objectTypeLabel', 'serviceDesk' are going to be removed from all sub-components. 
---
* The fields 'workspaceId', 'schemaLabel', 'objectTypeLabel', 'serviceDesk' are going to be removed from all sub-components.
> SALTO-5856: Fix Bug In Automation Components

- packages/jira-adapter/src/filters/layouts/layout_service_operations.ts
- packages/jira-adapter/src/filters/layouts/layout_types.ts
- packages/jira-adapter/src/filters/layouts/request_types_layouts_to_values.ts
- packages/jira-adapter/test/filters/layouts/request_type_request_form.test.ts
In this PR I excluded requestTypes that being partial fetched. 
---
There is a known issue where lacking the "Browse Projects" and "Service Project Agent" permissions for a specific project prevents access to the RequestType. In the UI, this discrepancy is evident, whereas the API returns a partial RequestType, contradicting the user's experience and causing issues during deployment attempts. The error message received in such cases is: "Entity associated with issue layout does not exist or user does not have required permissions." Consequently, when this message appears, we should avoid fetching the RequestType altogether.
---
* Stop fetching requestsType that has no requestForm or issueView.
--- …
> SALTO-5603: Do not fetch Partial requestType

- packages/netsuite-adapter/src/filters/add_permissions_to_cutomRecord_and_roles.ts
- packages/netsuite-adapter/test/filters/add_permissions_to_customRecord_and_role.test.ts
_add missing permissions to roles and custom record types, not only change modified permissions_
---
_jira ticket: https://salto-io.atlassian.net/browse/SALTO-4142
previous PRs:
adding weak references: https://github.com/salto-io/salto/pull/5515
adding modified permissions to roles/custom record types: https://github.com/salto-io/salto/pull/5713_
---
_Allow the user to deploy custom record type and role that one have permission to the other_
---
_None_
> SALTO-4142: add missing permissions to roles and custom record types
