salto-io/salto

packages/jira-adapter/src/change_validators/index.ts, packages/jira-adapter/src/change_validators/workflowsV2/referenced_workflow_deletion.ts, packages/jira-adapter/src/config/config.ts, packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts, packages/jira-adapter/test/change_validators/workflowsV2/referenced_workflow_deletion.test.ts, packages/jira-adapter/test/utils.ts
Jira Adapter:
- Added a Change Validator that emits an error when attempting to delete a workflow referenced by some scheme (active or inactive, it doesn't matter). This is consistent with Jira behaviour. Note, this only works when using the new Workflow API.
---
At first the ticket was about deleting an active workflow, however the current constraint (referenced by a workflow scheme) is stronger.
---
Jira Adapter:
- When attempting to delete a workflow referenced by workflow scheme (whether active or inactive) and error will be emitted. Note, this works only when using the new Workflow API.
=> SALTO-5452 cv prevent deleting associated workflow

packages/jira-adapter/src/filters/icon_utils.ts, packages/jira-adapter/src/filters/issue_type.ts, packages/jira-adapter/test/filters/issue_type.test.ts
In this PR:
1. Fixed fetch error due to missing icon and added proper fetch warning.
2. Decreased the severity from Error to Warning since we can deploy issueType and all related types without the issueType icon. 
---
---
* Fixed fetch error for missing issueTypeIcon. 
---
* Fixed fetch error for missing issueTypeIcon.
=> SALTO-5852: Skip fetching issueType icon if response is 404

packages/okta-adapter/src/filters/add_important_values.ts
The important value was unintentionally to the entire `source` group instead of `source.id`
---
---
None
---
None
=> SALTO-5899: fix important value for group in Okta

packages/jira-adapter/src/filters/layouts/issue_layout.ts
updating the error message the client gets when he tries to deploy change (add, remove, or modify) regarding issue layout and he gets a failed response from jira service.
it can happen because the issue layout was in the environment and there were changes in the environment and now the issue layout no longer exists in this environment and the problem was that is environment was not sync 
I changed the error message so it will explain this possibility
---
---
jira adapter:
- improved the error message for some failed issue layouts deployments
---
N/A
=> SALTO-5441: update error message for failing to get issueLayouts

packages/adapter-components/src/client/http_connection.ts, packages/jira-adapter/src/client/client.ts, packages/jira-adapter/test/client/client.test.ts
Logs were added to Jira's rate limit headers.
I also added general logs to trace in case we retry due rate limit
---
The responses of the calls do not log in case of a retry as it is an internal axios mechanism to which we provide a call-back
---
Jira Adapter: added logs to better understand rate limits
---
None
=> SALTO-5890: log jira rate limit headers

packages/salesforce-adapter/src/filters/custom_object_instances_references.ts, packages/salesforce-adapter/test/filters/custom_object_instances_references.test.ts
When we fetch instances in fetch-with-changes-detection, we may fetch referring instances without the instances they refer to. In order to resolve these references we need to look for the reference targets in the workspace.
---
Tests:
* Run the test case described in the ticket. Confirm it fails before this change and passes after it.
---
Salesforce: References from custom object instances will now be resolved correctly in quickfetch.
---
N/A
=> SALTO-5674 - Salesforce:Quick Fetch omits data instances due to missing refs

packages/okta-adapter/src/adapter.ts, packages/okta-adapter/src/change_validators/brand_theme_removal.ts, packages/okta-adapter/src/change_validators/index.ts, packages/okta-adapter/src/config.ts, packages/okta-adapter/src/filters/brand_theme_addition.ts, packages/okta-adapter/src/filters/brand_theme_removal.ts, packages/okta-adapter/src/logo.ts, packages/okta-adapter/test/change_validators/brand_theme_removal.test.ts, packages/okta-adapter/test/filters/brand_theme_addition.test.ts, packages/okta-adapter/test/filters/brand_theme_removal.test.ts, packages/okta-adapter/test/logo.test.ts
Add support for addition and removal of `BrandTheme`.
Addition: `BrandTheme`s are created automatically with default values. This PR allows to "add" a custom theme (alongside its Brand) by modifying the automatically created theme instead.
Removal: `BrandTheme`s are automatically removed when their `Brand`s are removed. This PR implements removal by just verifying that they are removed (and disallowing removal if the `Brand` wasn't removed as well).
---
Removal handling is similar to #5594
---
- Added support for addition and removal of `BrandTheme`.
---
None
=> SALTO-5879: Okta: Add support for addition and removal of `BrandTheme`

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/custom_references/handlers.ts, packages/salesforce-adapter/src/custom_references/managed_elements.ts, packages/salesforce-adapter/src/custom_references/profiles.ts, packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts, packages/salesforce-adapter/src/filters/installed_package_generated_dependencies.ts, packages/salesforce-adapter/src/filters/utils.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/custom_references/managed_elements.test.ts, packages/salesforce-adapter/test/filters/installed_package_generated_dependencies.test.ts, packages/salesforce-adapter/test/filters/utils.test.ts, packages/salesforce-adapter/test/utils.ts
Implementing a new custom references handler for installed packages.
The old filter will only generate references if the handler is disabled, but there are some logs we will always want it to print.
---
Workspace diff: https://github.com/salto-io/ariel-sf/commit/fe51f1759dd5dc946b4e0c6a3d151db7536ead01
Explicit references to the `InstalledPackage` are removed from all managed elements.
---
_Salesforce_:
* Use custom (weak) references for installed packages. Disabled by default.
---
_Salesforce_
* Enabling the custom references handler `managedElements` will remove the explicit references to the `InstalledPackage` from all managed elements.
=> SALTO-5062: Calculating weak references from managed elements to installed packages

packages/okta-adapter/e2e_test/adapter.test.ts
This PR adds cleanup to Okta e2e environment before running the tests.
---
None
---
None
---
None
=> SALTO-4958: Okta: Add cleanup to e2e test

packages/zendesk-adapter/src/filters/unordered_lists.ts, packages/zendesk-adapter/test/filters/unordered_lists.test.ts
Fix issue where two apps with the same position can flip places by adding the ID to the sorting
---
---
* Two app installation with the same position in workspace will keep their set position
---
=> SALTO-5516 order apps field in workspace by ID as well as position

packages/zendesk-adapter/src/filters/add_important_values.ts
remove content from being index important value in dynamic content item variant
---
---
zendesk:
* content in dynamic content item variant is no longer an indexed important value
---
=> SALTO-5913: remove content from being index important value in dynamic content item variant

packages/salesforce-adapter/src/custom_references/handlers.ts, packages/salesforce-adapter/src/custom_references/permission_sets.ts, packages/salesforce-adapter/src/custom_references/profiles.ts, packages/salesforce-adapter/src/filters/field_references.ts, packages/salesforce-adapter/src/transformers/reference_mapping.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/custom_references/permission_sets.test.ts, packages/salesforce-adapter/test/filters/field_references.test.ts
This implementation is based on old PR by @tomsellek  https://github.com/salto-io/salto/pull/5547
Move the extraction of references from the reference mapper to custom references. This will speed fetches in cases where `PermissionSet`s are included and some of them are very large.
---
- Add PermissionSet custom references handler.
---
_None_
=> SALTO-5334, SALTO-5346 - Salesforce: move PermissionSet refs to custom references code

packages/salesforce-adapter/e2e_test/adapter.test.ts, packages/salesforce-adapter/src/custom_references/handlers.ts, packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts, packages/salesforce-adapter/test/filters/installed_package_generated_dependencies.test.ts, packages/workspace/src/workspace/reference_indexes.ts
Salesforce Workspace Changes
---
Rollout for [PROD-279](https://salto-io.atlassian.net/browse/PROD-279)
---
- Converted PermissionSet references to custom references.
- Converted managed Elements references to custom references.
- The `Types` folder will be hidden by default.
- Standard Picklist Fields non deployable values will be omitted by default.
---
Salesforce:
- Types folder will be removed.
- `_generated_dependencies` from managed elements will be removed.
- Strong references from PermissionSet instances will be removed.
- The annotations `valueSet` and `referenceTo` will be removed from Standard Picklist Fields.
[PROD-279]: https://salto-io.atlassian.net/browse/PROD-279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …
=> PROD-279: Salesforce Workspace Changes

packages/jira-adapter/src/filters/forms/forms.ts, packages/jira-adapter/src/filters/forms/forms_types.ts, packages/jira-adapter/test/filters/forms/forms.test.ts
In this PR I fixed the multiple errors in JSM Forms. 
---
Currently, we are logging many errors related to failures in fetching JSM forms.
|Was|Now|
|----|-----| 
|Previously, when we failed to fetch forms for an entire project, we logged an error for each project in the account.| Now, we log a single error for all projects.|
|When forms had missing titles, we logged an error for each form. |Now, we log one error covering all forms and projects.|
Example in oriSaltoTest:
In addition, I decreased the logs from Error to debug and added fetch warnings.  
**I will add tests after the initial review to ensure that my solution is acceptable.**
---
* Optimized error logging for JSM form fetching to reduce noise: Now logging a …
=> SALTO-5555: errors in fetch JSM forms

packages/zendesk-adapter/src/filters/unordered_lists.ts, packages/zendesk-adapter/test/filters/unordered_lists.test.ts
Ticket field conditions are sorted by "value". if there are dup values (like `true` or `false`), the sorting is not robust enough. In this PR we add an additional field, parent_field_id, so that sorting stays consistent
---
---
Zendesk: 
Make sorting of conditions in Ticket Forms more consistent
---
Zendesk: 
Make sorting of conditions in Ticket Forms more consistent
=> SALTO-5916: [Zendesk] Add a second sorting field for conditions in ticket forms

packages/adapter-components/src/client/polling.ts, packages/adapter-components/src/definitions/system/requests/types.ts, packages/adapter-components/src/deployment/deploy/requester.ts, packages/adapter-components/test/client/polling.test.ts, packages/google-workspace-adapter/src/definitions/requests/clients.ts
SALTO-5915 Google ws - fix - roleAssignment deployment
---
---
none 
---
none
=> SALTO-5915 Google ws - fix - roleAssignment deployment

packages/google-workspace-adapter/README.md
We recently found out that the default reauthentication policy defined on GW accounts requires requthentication after 16 hours, which causes us to receive an error when trying to get an access token using only our stored refresh token.
This can be configured in the admin console in 2 ways. We added guidance for both in the GW README.
---
---
None
---
None
=> SALTO-5980: Update Google Workspace README with reauthentication policy instructions

packages/confluence-adapter/src/adapter_creator.ts, packages/confluence-adapter/src/change_validator.ts, packages/confluence-adapter/src/change_validators/index.ts, packages/confluence-adapter/src/change_validators/space_key_uniqueness.ts, packages/confluence-adapter/src/change_validators/unique_page_title_under_space.ts, packages/confluence-adapter/test/change_validator.test.ts, packages/confluence-adapter/test/change_validators/space_key_uniqueness.test.ts, packages/confluence-adapter/test/change_validators/unique_page_title_under_space.test.ts
Added two change validator to Confluence:
1. Uniqueness of page title under space
2. Uniqueness of space key
---
---
- CV for uniqueness of page title under space
- CV for uniqueness of space key
---
- CV for uniqueness of page title under space
- CV for uniqueness of space key
=> SALTO-5758 page and space CVs for Confluence

packages/workato-adapter/src/rlm.ts
Currently workato deployment fails for all recipes due to checking the `account_id` field for all recipes though it's not mandatory.
---
The `account_id` field only appears when there's a connected connection, but it's a valid scenario to try and deploy a recipe without it, so we should allow it.
---
None
---
None
=> SALTO-5930: Workato deployment fails for invalid recipe schema

packages/adapter-api/src/values.ts, packages/adapter-api/test/values.test.ts, packages/adapter-utils/test/important_values.test.ts, packages/core/src/core/fetch.ts, packages/core/test/core/fetch.test.ts, packages/jira-adapter/src/filters/fields/field_structure_filter.ts, packages/workspace/test/workspace/hidden_values.test.ts, packages/zendesk-adapter/src/filters/custom_field_options/custom_object_field_options.ts, packages/zendesk-adapter/test/filters/custom_objects/custom_object_field_options.test.ts
this can fix a regression introduced in zendesk by https://github.com/salto-io/salto/pull/5733/files#diff-89893d1af4da92a0633bf2148169be4c5bfbc87b840ef9a7eb4e82ebdc75682cR825 , that caused the ducktype call to [replaceInstanceTypeForDeploy](https://github.com/salto-io/salto/blob/main/packages/zendesk-adapter/src/adapter.ts#L808) to have no effect during the [resolveChangeElement](https://github.com/salto-io/salto/blob/main/packages/zendesk-adapter/src/adapter.ts#L820) call.
~I'm not 100% about the reasons for giving the old precedence, so this is still WIP. we can also solve this by adding a variant of `resolveValues` that will use the element source for the values but not for the types, but we prefer not to use it if we can avoid it since it should be ok to pass an element source in …
=> SALTO-5878 when resolving values, give precedence for the already-resolved value if available

packages/parser/src/parser/internal/native/consumers/values.ts, packages/parser/test/parser/parse.test.ts
fix parser to not use trim in createStringValue
---
---
core:
* fix issue where pending changes appear in multi-line string when the unicode U+200D is the last character
---
=> SALTO-5927: fix parser to not use trim in createStringValue

packages/adapter-components/src/deployment/deploy/requester.ts, packages/adapter-components/test/deployment/deploy/requester.test.ts, packages/confluence-adapter/src/definitions/deploy/deploy.ts
- Resolve args on request.queryArgs (adapter-component)
- Initial support in deployment of space settings. There still some things todo but I think this adds some value and can be merge until we will support more complex cases.
- Convert action to modification from addition when deploying new space with its settings. 
TODO:
On this PR we support modification of custom settings. Global is not configurable.
- Allow to set which settings definition to use on a space ('custom', 'global', 'theme'). using [this](https://developer.atlassian.com/cloud/confluence/rest/v1/api-group-settings/#api-wiki-rest-api-settings-lookandfeel-put) API
- Block somehow modification on global field on settings instance, as this is not editable in the sevice
- Explore more about 'theme' option. As I understand this …
=> SALTO-5817 support deployment of settings instances

packages/zendesk-adapter/src/filters/article/utils.ts, packages/zendesk-adapter/test/filters/article/article.test.ts
When fetching article attachment, we use a url that has the filename in it - which breaks when the file name is weird. In this PR i switched it so that we use the same url but remove the filename (which was suggested by zendesk support)
---
---
Zendesk:
Fix fetching of article attachments with weird names
---
None
=> SALTO-5861: [Zendesk] Fix fetching of article attachments

packages/jira-adapter/src/filters/forms/forms.ts, packages/jira-adapter/test/filters/forms/forms.test.ts
Currently, users who have no forms are receiving a Salto fetch warning indicating that they lack permissions. Jira has changed their API so that when attempting to access forms without the necessary permissions, a 403 error is returned instead of an empty list.
---
---
* Fixed JSM Forms bug where users without forms received a permission error.
---
=> SALTO-5925: Fix Forms bug

packages/zendesk-adapter/src/config.ts
fix type for section
---
adding direct_parent_type to filedTypeOverrides so that it will appear in the type as this field is added in a filter
---
---
=> SALTO-5933: fix type for section

packages/core/src/api.ts, packages/core/test/api.test.ts
Fixed a bug which caused `fixElements` to throw when element list was empty
---
---
None
---
None
=> SALTO-5935: Return empty results for fix elements when provided element list is empty

packages/netsuite-adapter/src/adapter.ts
Remove duplicate filters, that were there probably because of a rebase mistake
---
---
None
---
None
=> remove duplicate filter calls

packages/jira-adapter/src/reference_mapping.ts
_add references between workflowV2 action to Resolution and Priority_
---
before:
after:
---
Jira Adapter:
* add a reference from WorkflowConfiguration (new Workflow API) action to Resolution and Priority
---
_None_
=> SALTO-5945: add references between workflowV2 action to Resolution and Priority

packages/okta-adapter/src/adapter.ts, packages/okta-adapter/src/change_validators/app_user_schema_and_application.ts, packages/okta-adapter/src/change_validators/app_user_schema_removal.ts, packages/okta-adapter/src/change_validators/index.ts, packages/okta-adapter/src/config.ts, packages/okta-adapter/src/filters/app_user_schema_removal.ts, packages/okta-adapter/test/change_validators/app_user_schema_removal.test.ts, packages/okta-adapter/test/filters/app_user_schema_removal.test.ts
_When removing an application, the client also automatically removes the related `appUserSchema`. This PR introduces an option to remove the appUserSchema concurrently with the application. In the background, we ensure that the application is removed successfully, and no additional actions are needed regarding the `appUserSchema`._
---
Jira ticket: https://salto-io.atlassian.net/browse/SALTO-4242
---
_Users can now remove `appUserSchema` along with removing it's parent application._
---
_None_
=> SALTO-4242 (Okta): Adding removal for app user schema

packages/okta-adapter/src/client/client.ts, packages/zendesk-adapter/src/client/client.ts
only log buffer length instead of response data
also removed the debug log as I think it kind of a dup I but can return it
---
None
---
None
---
None
=> SALTO-5944: Avoid logging buffers in getResource

packages/adapter-components/src/resolve_utils.ts, packages/adapter-utils/src/utils.ts, packages/zendesk-adapter/src/adapter.ts
This reverts commit 680f619358385c31cbce2a778a1f90d698eaae39.
after we merge https://github.com/salto-io/salto/pull/5849, we can revert the workaround from https://github.com/salto-io/salto/pull/5850
---
None
---
None
=> Revert "SALTO-5872: add new useElementSourceForTypes flag for resolveValues func (#5850)"

packages/adapter-components/src/fetch/request/requester.ts
we need to spread context otherwise real context will be nested twice under context
---
---
None
---
None
=> SALTO-5965: Pass spread request context to extractor context

packages/salesforce-adapter/jest.config.js, packages/salesforce-adapter/src/change_validators/unknown_users.ts, packages/salesforce-adapter/test/change_validators/unknown_users.test.ts
There's an annotation on custom fields that refers to a user. Let's validate that user too
---
This is different from the current validations because it runs on annotations of all custom fields as opposed to the values of specific fields. Thus a separate function.
---
Salesforce: Will now validate custom fields' Data Owner property
---
N/A
=> SALTO-5408 - Salesforce: Validate Salesforce CustomField businessOwnerUser user existence

packages/jira-adapter/src/client/client.ts
Currently it is impossible to filter out which fetches receive the near limit header due to datadog limitation.
I added a temp log to make it more visible
---
The header is returned as "X-RateLimit-NearLimit":"false" or "X-RateLimit-NearLimit":"true"
As datadog [does not allow you to search for special chars in the message](https://docs.datadoghq.com/logs/explorer/search_syntax/#:~:text=You%20cannot%20search%20for%20special%20characters%20in%20a%20log%20message) and as "true" is a common word in API responses I added a temp log to understand where we stand with the near limit for different customers
---
None
---
None
=> SALTO-5890: Add logs for near limit visibility

packages/adapter-api/src/element_id.ts, packages/adapter-api/test/elements.test.ts, packages/workspace/src/workspace/nacl_files/nacl_file_update.ts, packages/workspace/test/workspace/nacl_files/nacl_file_update.test.ts
Instead of adding new fields, annotations or values at the end of their parent in NaCl files, add them in the order they are defined in their parent object. This will ensure that members always show up in the same place in the NaCl if they are removed and added again.
---
Still need to add higher level tests, IMO it's cleaner to split into a separate PR.
---
_Core_
* Element members (field, annotations or values) are added in the same location consistently instead of being appended.
---
None.
=> SALTO-5643: Adding members in the order they are defined

packages/salesforce-adapter/src/custom_references/managed_elements.ts, packages/salesforce-adapter/test/custom_references/managed_elements.test.ts, packages/workspace/src/workspace/reference_indexes.ts
They should never have been weak.
---
---
_Salesforce_:
* Using strong custom references for managed elements.
---
None.
=> SALTO-5928: Using strong references for managed elements

packages/google-workspace-adapter/e2e_test/adapter.test.ts
SALTO-5867 Google ws add e2e logs
---
---
---
=> SALTO-5867 Google ws add e2e logs

packages/salesforce-adapter/src/adapter.ts
The comment says changed at singelton should be last.
---
---
---
=> SALTO-5958: Moving generated dependencies filter to not be last

packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts, packages/salesforce-adapter/src/filters/organization_settings.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/organization_settings.test.ts
It was tied to the feature hiding the types folder but we don't want to wait for it.
---
Workspace diff: https://github.com/salto-io/ariel-sf/commit/3a41d13f4fd0a003f566a4472d634f8f85971a19
The `latestSupportedApiVersion` field is added to the Organization settings.
---
None.
---
None.
=> SALTO-5279: Adding a new SFDC optional feature for latest supported API version

packages/google-workspace-adapter/README.md, packages/google-workspace-adapter/src/client/oauth.ts
We want to be able to choose the desired google workspace account even if we're already logged in to this account/another one.
---
None
---
None
=> SALTO-5668: Google Workspace OAuth - enforce consent + login screen

packages/dag/src/nodemap.ts, packages/dag/test/nodemap.test.ts
Currently, if we throw an error during the DAG walk, the error isn’t thrown immediately but is instead caught and only thrown as a combined error (containing all the errors that occurred) once the graph walk is complete. 
We want to optimize this behavior and allow certain errors to be thrown before the graph walk is complete. 
To achieve this, we have exposed a `FatalError` error class. If the handler throws such an error, then we throw and exit during the walk. It's important to note that for `walkAsync`, jobs that have already started will not be interrupted; however, the function will return with an error.
---
---
None
---
None
=> SALTO-5948: Allow throwing an error during the DAG walk

packages/okta-adapter/src/filters/default_rule_deployment.ts, packages/okta-adapter/test/filters/default_rule_deployment.test.ts
This PR fixes a bug where the deployment of a default access policy rule would fail.
---
When deploying a system rule of type AccessPolicyRule, you need to set its priority to 99, similar to how we handle PROFILE_ENROLLMENT_RULE_TYPE_NAME.
---
_Okta Adapter:_
* Fixed the deployment issue for default access policy rules by ensuring the priority is set correctly to 99.
---
None
=> SALTO-5979: FixErrorDeployingDefaultAccessPolicyRule

packages/salesforce-adapter/src/change_validators/element_api_version.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/organization_settings.ts, packages/salesforce-adapter/test/change_validators/element_api_version.test.ts, packages/salesforce-adapter/test/filters/organization_settings.test.ts
We will have the duplication for a bit until we enbale the optional feature.
---
---
_Salesforce_:
* Adding a hidden Organization API Version settings type and instance which stores the latest supported API version. This is only temporary and will be removed soon.
---
None.
=> SALTO-5978: Adding separate Organization API Version settings in SFDC

packages/google-workspace-adapter/e2e_test/adapter.test.ts
This keeps failing and currently blocks merges to main
---
---
None 
---
None
=> SALTO-5987: Temporarily disable google workspace E2E 

packages/adapter-components/src/definitions/system/fetch/index.ts, packages/adapter-components/src/definitions/system/fetch/resource.ts, packages/adapter-components/src/fetch/element/element.ts, packages/adapter-components/test/fetch/element/element.test.ts
To include the typeName in the fetch warning message / suggestion, we should be able to access it from handler 
---
---
None 
---
None
=> SALTO-6000: Add typeName to error handler

packages/adapter-components/src/client/pagination/pagination.ts, packages/adapter-components/test/client/pagination.test.ts, packages/jira-adapter/src/client/pagination.ts, packages/jira-adapter/src/config/api_config.ts
Added pagination to JSM
---
There are two different pagination types. Object Schema uses the regular [Jira API pagination](https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/#pagination) and the [JSM API pagination](https://developer.atlassian.com/cloud/jira/service-desk/rest/intro/#pagination)
I went over all of the JSM APIs, both in api_config and all the get calls in the filters.
I did not add noise reduction, as the noise would be too big
---
Jira Adapter:
* Fixed a bug where Object Schemas, Queues, and Request Types would bring partial results for big environments
---
None
=> SALTO-5967: JSM pagination

packages/jira-adapter/src/filters/automation/automation_deployment.ts, packages/jira-adapter/src/filters/automation/automation_fetch.ts, packages/jira-adapter/test/filters/automation/automation_deployment.test.ts, packages/jira-adapter/test/filters/automation/automation_fetch.test.ts
This PR addresses issues related to special component handling in automation: requestType default field and trigger components. 
The changes ensure that different formats of requestType are supported and that trigger components are handled the same as the component fields is handled. 
---
more context in https://salto-io.atlassian.net/browse/SALTO-5999
---
_Jira Adapter:
* Fix handling of requestType field and trigger components in automations to support various formats and proper processing.
---
_Replace me with a short sentence that describes changes that will appear in NaCls and are not caused by user actions (e.g. a new annotation, field values that are converted to references, etc). Hidden changes should not …
=> SALTO-5999: Fix Components handling in automation 

packages/adapter-components/src/fetch/request/requester.ts, packages/adapter-components/src/fetch/resource/type_fetcher.ts, packages/adapter-components/test/fetch/fetch.test.ts
see [SALTO-6017](https://salto-io.atlassian.net/browse/SALTO-6017) for details
---
I'll only merge this code as part of the PR for the guide elements in Zendesk - i just want to make sure that this doesn't break anything and on main i don't have a convenient way to check the code :)
reiterating: I PR'd this so that it's easier to talk about, THIS PR IS NOT GOINT TO BE MERGED
[SALTO-6017]: https://salto-io.atlassian.net/browse/SALTO-6017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SALTO-6017: fix dependsOn context

packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/filters/data_instances_reference_names.ts, packages/netsuite-adapter/src/filters/replace_record_ref.ts, packages/netsuite-adapter/test/filters/data_instances_reference_names.test.ts, packages/netsuite-adapter/test/filters/replace_record_ref.test.ts
Some references in data instances return with only `internalId` field, and without the `name` field. In those cases we currently set the value to "[ACCOUNT_SPEICIFIC_VALUE] (object) (unknown object)", but this way those instances aren't deployable (we don't know what is the internalId behind "unknown object").
This behavior happens only in specific fields. At this point there is only one field like that we saw with "unknown object" - `restrictToAccountingBookList` field in `account` instances, and we identify that this field is a list of "accounting book" records. Using SuiteQL we query the referenced "accounting book" records (only the referenced records) and we set the `name` field with the matching name of the "accounting book" (by its `internalId`). The filter is extendable to other …
=> SALTO-5850 add missing data instances reference names

packages/netsuite-adapter/src/filters/data_account_specific_values.ts, packages/netsuite-adapter/test/filters/data_account_specific_values.test.ts
Recognize that the ASV references of the `taxSchedule` field belongs to the taxSchedule SuiteQL table, that we're already fetching (when `resolveAccountSpecificValues=true`).
---
---
- Resolve ASV references of the `taxSchedule` field
---
- ASV references of the `taxSchedule` field will change the type in them: from `object` to `taxSchedule`:
```
taxSchedule = {
id = "[ACCOUNT_SPECIFIC_VALUE] (taxSchedule) (Tax Schedule 123)"
}
```
=> SALTO-5847 resolve ASV references of the taxSchedule field

packages/salesforce-adapter/src/filters/custom_metadata_to_object_type.ts, packages/salesforce-adapter/test/filters/custom_metadata_to_object_type.test.ts
CustomMetadata types are being corrupt on targeted fetch of CustomObjects.
---
This caused having invalid types in the Workspace until the next full fetch, which yields warnings on all of the CustomMetadata Records and cause partial fetch to fail constantly afterwards until the next full fetch.
---
- Bugfix: CustomMetadata types are being corrupt on targeted fetch of CustomObjects.
---
_None_
=> SALTO-6015: (Bugfix) CustomMetadata types are being corrupt on targeted fetch of CustomObjects

packages/adapter-components/src/definitions/system/requests/index.ts, packages/adapter-components/src/definitions/system/requests/types.ts, packages/microsoft-entra-adapter/src/definitions/fetch/fetch.ts, packages/okta-adapter/src/definitions/fetch.ts
Enforce forward slash on endpoints in request definitions for both fetch and deploy
---
see https://github.com/salto-io/salto/pull/5984
---
None
---
None
=> SALTO-6024: Enforce forward slash on endpoint path

packages/confluence-adapter/src/definitions/fetch/fetch.ts
As title
---
---
None
---
None
=> SALTO-5545 remove serviceUrl def from page type in Confluence

.circleci/config.yml
SALTO-5987 Google ws - e2e-enable
---
---
---
=> SALTO-5987 Google ws - e2e-enable

packages/dag/src/nodemap.ts, packages/dag/test/nodemap.test.ts
Before this fix, getCycle would return edges that lead up to the cycle along with the actual cycle This causes issues in depending code which assumed the return of "getCycle" is just the cycle
---
---
Core:
- Fix issue where plan would go into infinite loop on specific cases of circular dependencies
---
_None_
=> SALTO-5782: return only cycle from getCycle

.circleci/config.yml
removing a patch that replaced the Ubuntu sources with an alternative mirror, due to some network issue in the past, and is no longer required.
---
---
---
=> SALTO-6042 remove source.list override patch from ci pipeline

packages/netsuite-adapter/e2e_test/adapter.test.ts
It was disabled at the last NS outage.
---
---
None
---
None
=> enable ns e2e

packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/test/client/sdf_client.test.ts
On quick fetch, we delete objects that aren't returned in the `object:list` command from SDF, because in general it means that they're deleted from the service. There is one exception and it is custom record types with matching custom segments - the `object:list` command returns only the custom segments, and on `object:import` the custom record types are fetched. This causes us to delete all the custom record types with matching custom segments on quick fetch. The solution is to add the matching custom record types to the returned `instancesIds` list, as it will prevent us from deleting them on quick fetch, and also we'll add them to the `netsuite.script_ids` hidden nacl (see [this comment](https://github.com/salto-io/salto/pull/5893#discussion_r1626922075))
---
_Additional context for …
=> Fix custom record type quick fetch

packages/google-workspace-adapter/e2e_test/adapter.test.ts
SALTO-5987 Google ws e2e longer sleep between deploy and fetch
---
---
---
=> SALTO-5987 Google ws e2e longer sleep between deploy and fetch

packages/e2e-credentials-store/src/jest-environment/index.ts, packages/e2e-credentials-store/src/jest-environment/interval_scheduler.ts
Catch final event in jest circus to make sure the printer doesn't hang.
---
---
---
=> SALTO-6057 Fix hanging e2e tests

packages/jira-adapter/src/reference_mapping.ts
In this PR I fixed missing Reference bug in ObjectTypeAttribute
---
In the ObjectTypeAttribute, there is a field named additionalValue.
This field can hold two types: ObjectSchemaDefaultReferenceType or ObjectSchemaReferenceType.
Initially, I assumed they could have the same IDs and attempted a hack to determine the reference type.
I have now updated the logic to match the approach used for the typeValueMulti field in ObjectTypeAttribute.
---
* Fixed missing reference bug in ObjectTypeAttribute in the `additionalValue` field.
---
* Users might encounter changes in the additionalValue field within the ObjectTypeAttribute instances, changing from a missing reference to an actual …
=> SALTO-6049: Fix missing Reference bug in ObjectTypeAttribute

packages/jira-adapter/e2e_test/instances/field.ts, packages/jira-adapter/src/filters/fields/field_structure_filter.ts, packages/jira-adapter/test/filters/fields/field_structure.test.ts
Change the counting of the options in field-context so that it will start from 1 instead of 0 to make it compatible with the jira UI
---
---
- update the counting of the options in field-context 
N/A
=> SALTO-5553 update field context counting

packages/adapter-api/src/elements.ts, packages/adapter-api/src/values.ts, packages/core/src/core/adapters/adapters.ts, packages/core/test/core/adapters/adapters.test.ts, packages/workspace/src/merger/internal/instances.ts, packages/workspace/src/serializer/elements.ts
This allows us to enforce that instance types are object types using the type system and will allow us to do the same for meta types in the next PR.
---
---
None.
---
None.
=> SALTO-3621: Specifying type references using generics

packages/jira-adapter/src/filters/automation/types.ts
There were warnings on `requestType` field in `Automation` with an “edit request type” action after fetch.
The error happened because we defined this field as string.
Fixed this by changing the type to unknown.
* As we know this field can be either reference expression or `{ type: string; value: string }`
---
jira ticket: https://salto-io.atlassian.net/browse/SALTO-5950
---
Jira Adapter:
* Fixed warnings on `requestType` field in `Automation`
---
_None_
=> SALTO_5950: (Jira) fix warnings on requestType field in Automations

packages/jira-adapter/src/filters/automation/automation_fetch.ts, packages/jira-adapter/test/filters/automation/automation_fetch.test.ts
Retry automations also on 502
---
None
---
Jira Adapter:
* Added retry on 502 errors on automations
---
None
=> SALTO-5914: retry automations on 502 errors

packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts, packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts
_fail gracefully when workflowV2 version does not match the service_
---
---
_None_
---
_None_
=> SALTO_6050: fail gracefully when workflowV2 version does not match the service

packages/adapter-components/src/openapi/type_elements/type_config_override.ts, packages/okta-adapter/src/definitions/fetch/fetch.ts, packages/okta-adapter/src/filters/add_important_values.ts
When cloned types, we didn't create an independent new object type, which caused each cloned object type to be affected by the original types customizations.
---
I tested with both Jira and Zuora which uses `additionalTypes` in the old infra and the change doesn't effect types
The change did changed some types in Okta so I included the adjustments in this PR.
---
None 
---
None
=> SALTO-6045: Cloned types should not share types customizations

packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/config/types.ts, packages/netsuite-adapter/src/custom_records/custom_record_type.ts, packages/netsuite-adapter/src/filters/custom_record_types.ts, packages/netsuite-adapter/src/filters/element_references.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/filters/custom_record_types.test.ts, packages/netsuite-adapter/test/filters/element_references.test.ts
Create hidden "dummy" instances of locked custom record types, and fetch their instances. The deploy of those custom record instances works out of the box (the locked custom record type must be in the target account).
---
TODO:
---
- Fetch and Deploy Custom Record instances of locked Custom Record Types (use adapter config `fetch.addLockedCustomRecordTypes=true`)
---
- When enabled in adapter config (`fetch.addLockedCustomRecordTypes=true`), custom records of locked custom record types will be fetched and added `/CustomRecords/<lock_custom_record_type_scriptid>`
=> SALTO-6043 Fetch and Deploy Custom Record instances of locked Custom Record Types

packages/adapter-components/src/fetch/element/element.ts, packages/dag/src/nodemap.ts
We originally used `...` to push all validEntries, when there are a lot of entries, this will cause `Maximum call stack size exceeded` Error
---
- I also added a log of the original error stack. It was very hard to debug since we lose the original error stack while walking on a DAG.
---
- fix fetch for large amount of pages
---
- fix fetch for large amount of pages
=> SALTO-6080 pushing entities one by one upon fetch to prevent RangeError

packages/salesforce-adapter/src/filters/remove_fields_and_values.ts, packages/salesforce-adapter/test/filters/remove_fields_and_values.test.ts
This field can't be deployed, so no reason to have it around.
While we're at it, change a bunch of async stuff to sync.
---
The path of least resistance seems to be to delete the field. Is there a reason to hide it instead?
Tests:
- fetch an env with the CPQ Billing package installed with/without this PR. Observe the field `blng__UniqueId__c` removed from `blng__RevenueRecognitionTreatment__c`, and that the fields `blng__Family__c`, `blng__NextOpenPeriod__c` and `blng__UniqueId__c` are removed from `blng__FinancePeriod__c`.
---
Salesforce: CPQ Billing - automatically-generated fields in the 'RevenueRecognitionTreatment' and 'FinancePeriod' will no longer be fetched.
---
Salesforce: CPQ Billing - The `blng__UniqueId__c` field is removed from the …
=> SALTO-6048 - Salesforce: Remove Salesforce CPQ Billing unique ID field

.circleci/config.yml
SALTO-5987 Google ws  e2e disable
---
---
---
=> SALTO-5987 Google ws  e2e disable

packages/netsuite-adapter/src/scriptid_list.ts, packages/netsuite-adapter/test/adapter.test.ts
The inner `objectId` type and the `objectIdList` type had the same element id on fetch, causing them to be dropped because of merge error.
---
---
None
---
None
=> Fix NS merge error

packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/config/config.ts, packages/jira-adapter/src/fix_elements/index.ts, packages/jira-adapter/src/fix_elements/remove_missing_extension_transition_rules.ts, packages/jira-adapter/src/fix_elements/types.ts, packages/jira-adapter/test/change_validators/workflowsV2/missing_extensions_transition_rules.test.ts, packages/jira-adapter/test/fix_elements/remove_missing_extension_transition_rules.test.ts, packages/jira-adapter/test/utils.ts, packages/lowerdash/src/types.ts
Jira:
- Added a 'fix element' that will **_remove_** workflow transition rules of missing (not installed in target environment) Jira apps. This 'fix element' is under the feature flag of config.deploy.ignoreMissingExtensions in Jira NaCl.
---
Part of a series of PRs. This one depends on #5943, so review that one first.
---
Jira:
- Added a feature flag under config.deploy called ignoreMissingExtensions (defaults to false). When enabled, workflow transition rules of Jira apps that aren't installed in the target environment will be removed.
=> Salto 5973 create a fix element that will remove transition rules dependent on missing jira apps

packages/netsuite-adapter/src/changes_detector/changes_detectors/custom_record_type.ts, packages/netsuite-adapter/src/changes_detector/changes_detectors/custom_records.ts, packages/netsuite-adapter/src/changes_detector/changes_detectors/custom_type.ts, packages/netsuite-adapter/src/changes_detector/changes_detectors/file_cabinet.ts, packages/netsuite-adapter/src/changes_detector/changes_detectors/role.ts, packages/netsuite-adapter/src/changes_detector/changes_detectors/script.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts, packages/netsuite-adapter/src/client/suiteapp_client/types.ts, packages/netsuite-adapter/src/custom_records/custom_records.ts, packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts, packages/netsuite-adapter/src/filters/author_information/constants.ts, packages/netsuite-adapter/src/filters/author_information/system_note.ts, packages/netsuite-adapter/src/filters/data_instances_reference_names.ts, packages/netsuite-adapter/src/filters/internal_ids/sdf_internal_ids.ts, packages/netsuite-adapter/test/changes_detector/changes_detector.test.ts, packages/netsuite-adapter/test/changes_detector/custom_field.test.ts, packages/netsuite-adapter/test/changes_detector/custom_list.test.ts, packages/netsuite-adapter/test/changes_detector/custom_record_type.test.ts, packages/netsuite-adapter/test/changes_detector/custom_records.test.ts, packages/netsuite-adapter/test/changes_detector/file_cabinet.test.ts, packages/netsuite-adapter/test/changes_detector/role.test.ts, packages/netsuite-adapter/test/changes_detector/script.test.ts, packages/netsuite-adapter/test/client/suiteapp_client/suiteapp_client.test.ts, packages/netsuite-adapter/test/client/suiteapp_client/suiteapp_file_cabinet.test.ts, packages/netsuite-adapter/test/data_elements/suiteql_table_elements.test.ts, packages/netsuite-adapter/test/filters/author_information/system_note.test.ts, packages/netsuite-adapter/test/filters/internal_ids/sdf_internal_ids.test.ts
SuiteQL returns only the first 100K items. In this PR we fix it and retrieve whole items when there are more than 100K items, by making more queries with filtering by the last queried item id - `WHERE ... AND id > {lastQueriedItemId}`
---
---
- Fix SuiteQL query of over 100K items
---
- Missing files/folders will be fetched & added to the FileCabinet folder
=> SALTO-6090 Fix SuiteQL query of over 100K items

packages/jira-adapter/src/config/config.ts, packages/jira-adapter/src/filters/automation/automation_fetch.ts
Added a configuration to set the automation page size, which might solve the 502/504 errors for automations. It will be removed afterwards
---
The purpose is to test if the automation page size change can make a difference without reducing the general performance.
---
Jira Adapter:
* Added a configuration for automation page size
---
None
=> SALTO-6904: add automation specific page size configuration

packages/jira-adapter/src/constants.ts, packages/jira-adapter/src/filters/statuses/status_deployment.ts, packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts, packages/jira-adapter/src/utils.ts, packages/jira-adapter/test/filters/statuses/status_deployment.test.ts, packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts
_add delay to workflowV2 retries_
---
* add delay
* update `MAX_RETRIES` from 3 to 5
---
_None_
---
_None_
=> SALTO-6079: add delay to workflowV2 retries

packages/okta-adapter/test/adapter.test.ts, packages/okta-adapter/test/deploy_mock_replies.json
Added a unit test for Okta deploy.
---
This is based on a similar test in `serviceplaceholder-adapter`
---
None
---
None
=> Okta: Add a deploy unit test (with mock HTTP requests)

packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/custom_object_instances_deploy.ts, packages/salesforce-adapter/src/group_changes.ts, packages/salesforce-adapter/test/group_changes.test.ts, packages/salesforce-adapter/test/mock_elements.ts
Similar to other types that refer to each other implicitly (rather than via explicit references), we need to create a special deploy group and handle it explicitly.
---
Test:
- Change the NaCl files of a `ProductRule` instance and the related `ErrorCondition` instance. Observe the correct group ID.
---
Salesforce: Circular dependency between CPQ ProductRule instances with 'Custom' ConditionsMet value and ErrorCondition instances are handled correctly.
---
N/A
=> SALTO-6096 - Salesforce: Handle circular dependency between ProductRule and ErrorCondition

packages/salesforce-adapter/src/filters/remove_fields_and_values.ts
These fields can't be deployed, and contain no useful information. We can just discard them.
---
---
Salesforce: All 'Unique ID' fields of CPQ Billing objects are now discarded.
---
Salesforce: All 'Unique ID' fields of CPQ Billing objects will be removed from the workspace.
=> SALTO-6093 - Salesforce: Remove some more UniqueID fields from CPQ Billing types

packages/adapter-components/src/fetch/element/type_utils.ts, packages/adapter-components/src/filters/sort_lists.ts, packages/adapter-components/src/references/field_references.ts, packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/utils.test.ts, packages/jira-adapter/src/filters/hidden_value_in_lists.ts, packages/jira-adapter/src/filters/masking.ts, packages/jira-adapter/src/filters/references_by_self_link.ts, packages/jira-adapter/src/filters/remove_empty_values.ts, packages/jira-adapter/src/filters/remove_self.ts, packages/jira-adapter/src/filters/sort_lists.ts, packages/salesforce-adapter/src/change_validators/map_keys.ts, packages/salesforce-adapter/src/filters/convert_types.ts, packages/salesforce-adapter/src/filters/custom_object_instances_references.ts, packages/salesforce-adapter/src/filters/custom_objects_to_object_type.ts, packages/salesforce-adapter/src/filters/foreign_key_references.ts, packages/salesforce-adapter/src/filters/remove_fields_and_values.ts, packages/salesforce-adapter/src/filters/replace_instance_field_values.ts, packages/salesforce-adapter/src/filters/value_to_static_file.ts, packages/salesforce-adapter/src/filters/xml_attributes.ts, packages/salesforce-adapter/src/transformers/xml_transformer.ts, packages/workspace/src/workspace/hidden_values.ts, packages/zendesk-adapter/src/filters/dynamic_content_references.ts
Split `allowEmpty` param `transformValues` and `transformValuesSync` to distinguish between arrays and objects
---
though `transformValues` and `transformValuesSync` are exported but currently not in use, I removed it entirely.
added `allowEmptyArrays` and `allowEmptyObjects` to `transformElement, left `allowEmpty` in `transformElement` for backward compatibility and will remove it in a separate PR
---
_Core_:
- Change `transformValues` and `transformValuesSync` params by splitting `allowEmpty` param to `allowEmptyArray` and `allowEmptyObjects`
- Add `allowEmptyArrays` and `allowEmptyObjects` to `transformElement`, `allowEmpty` is deprecated and will be deleted soon
---
None
=> SALTO-6105: split allow empty in transformValues and transformValuesSync

packages/salesforce-adapter/src/custom_references/handlers.ts, packages/workspace/src/workspace/reference_indexes.ts
Opening Salesforce Custom References By Default.
---
- Salesforce Profiles custom references will be available by default.
---
_None_
=> SALTO-6112: Open Salesforce Profiles Custom References

packages/adapter-components/src/references/field_references.ts, packages/salesforce-adapter/src/filters/field_references.ts, packages/salesforce-adapter/src/transformers/reference_mapping.ts, packages/salesforce-adapter/test/filters/field_references.test.ts
1. Made the instance filter sync.
2. Dropping profiles when not needed.
Also removed the comment to move to using the element source, we decided against that in #5907.
---
This filter is very slow.
---
None.
---
None.
=> SALTO-5918: Performance improvements in field references filter

packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts, packages/netsuite-adapter/src/config/config_creator.ts, packages/netsuite-adapter/src/config/constants.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/client/suiteapp_client/suiteapp_file_cabinet.test.ts
It happens quite often that we're fetching a large amount of files, then we're excluding most of them because of their extensions. The query can be improved by adding it a regex of the excluded file extensions from the user's adapter config.
---
---
- Improve FileCabinet files query by excluding excluded file extensions
---
None
=> Improve FileCabinet files query by excluding excluded file extensions

packages/adapter-components/src/definitions/user/client_config.ts, packages/adapter-components/src/definitions/user/user_config.ts, packages/adapter-components/test/definitions/user/client_config.test.ts, packages/jira-adapter/src/config/config.ts, packages/okta-adapter/src/user_config.ts, packages/sap-adapter/src/config.ts, packages/stripe-adapter/src/config.ts, packages/workato-adapter/src/config.ts, packages/zendesk-adapter/src/config.ts, packages/zuora-billing-adapter/src/config.ts
We accidentally passed `usePrivateAPI` to the wrong place in the config object type 
---
will add test soon 
---
- Fix a bug in fetch causing all fetch to include invalid config event
---
=> SALTO-6133: Fix issue with client config type in Okta

packages/adapter-components/src/definitions/user/user_config.ts, packages/okta-adapter/src/user_config.ts
Fix the current behavior that adapter config nacl contains all default config properties and align with old infra
---
we used to exclude by default the `client` config and the `hideTypes` property
This will omit those in all adapters created using the new infra
---
None
---
None
=> SALTO-6121: Fix default config nacl upon creation

packages/netsuite-adapter/package.json, yarn.lock
=> SALTO-6114: Upgrade SDF version to 1.9.0-salto-1 that is based on 2024.1 API version

packages/adapter-components/src/fetch/element/element.ts, packages/adapter-components/src/fetch/element/instance_utils.ts, packages/adapter-components/test/fetch/element/element.test.ts
- In case directFetch is true we want to allow topLevelDef to be undefined without throwing an error. In this case Instances will not be created but the fetched data can be used for recurseInto or dependsOn types
---
---
None
---
None
=> SALTO-6022 allow isTopLevel to be false

packages/core/src/core/merge_content.ts, packages/core/test/core/merge_content.test.ts
We should be able to auto merge strings when there are different line separators between the base/current/incoming versions. The easiest solution would be to take the line separator of the `current` version (if there are mixed line separators in current - take the most common one*) and use it in the merged version**.
*we’ll lose the other used separators in current, but I guess that it’s fine.
**only in conflicts auto-merge - other fetched files will be kept as fetched even they have mixed line separators.
---
TODO:
---
Core:
- Ignore conflicts caused by different line separators
---
None
=> SALTO-6116 Ignore conflicts caused by different line separators

packages/confluence-adapter/src/definitions/deploy/deploy.ts, packages/confluence-adapter/src/definitions/fetch/fetch.ts, packages/confluence-adapter/src/definitions/utils/page.ts, packages/confluence-adapter/src/definitions/utils/space.ts, packages/confluence-adapter/test/definitions/utils/page.test.ts, packages/confluence-adapter/test/definitions/utils/space.test.ts
In context to resolveAllArgs, we didn't passed the data (after transformation), but only the value from the original change
---
---
- Fix homepage deployment
---
- Fix homepage deployment
=> SALTO-5800 fix homepage deployment

packages/salesforce-adapter/src/change_validator.ts, packages/salesforce-adapter/src/change_validators/cpq_billing_start_date.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/change_validators/cpq_billing_start_date.test.ts
See ticket for details
---
---
Salesforce: Will now show an error when attempting to deploy CPQ Billing records with StartDateTime in the past
---
N/A
=> SALTO-6095 - Salesforce: Handle Salesforce CPQ Billing Start Date fields

packages/netsuite-adapter/package.json, yarn.lock
Reverts salto-io/salto#6076 due to issues with node versions compatibility
=> Revert "SALTO-6114: Upgrade SDF version to 1.9.0-salto-1 that is based on 2024.1 API version"

packages/adapter-components/src/definitions/system/fetch/element.ts, packages/adapter-components/src/elements_deprecated/instance_elements.ts, packages/adapter-components/src/fetch/element/instance_element.ts, packages/adapter-components/src/fetch/element/instance_utils.ts, packages/adapter-components/src/fetch/element/standalone.ts, packages/adapter-components/src/fetch/element/type_utils.ts, packages/adapter-components/test/fetch/element/instance_utils.test.ts, packages/okta-adapter/e2e_test/mock_elements.ts, packages/okta-adapter/src/definitions/fetch/fetch.ts, packages/okta-adapter/src/filters/app_deployment.ts, packages/okta-adapter/test/filters/app_deployment.test.ts
---
** **please only review last commit** **
Still TODO - 
---
- Fix a bug in deployment of OIDC application causing applications with empty scopes to fail
---
- Empty arrays in Okta `Application` will be visible in `Application` elements
-
=> SALTO-6106: Add optional allowEmptyArrays option to top level element and enable it in Okta Application

packages/netsuite-adapter/package.json, yarn.lock
After the CI failure in https://github.com/salto-io/salto/pull/6076/files due to:
```
error commander@11.1.0: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.18.0"
```
we are using a lower `commander` version in SDF (https://github.com/salto-io/netsuite-suitecloud-sdk/commit/d175d5c4fdd91ae3c23f7ff00efcdc3de53889f1)
---
---
Netsuite Adapter: SALTO-5234: Upgrade SDF version to 1.9.0-salto-2 so it'll be based on 2024.1 API version
---
Netsuite Adapter: For existing Salto Workspaces, you should reinstall the NetSuite account by creating a temporary Salto Workspace and calling salto service add netsuite --no-login.
This will download the new SDF version that will be used globally …
=> SALTO-6114: Upgrade SDF version to 1.9.0-salto-2 that is based on 2024.1 API version

packages/confluence-adapter/e2e_test/adapter.test.ts, packages/confluence-adapter/e2e_test/mock_elements.ts, packages/confluence-adapter/src/definitions/fetch/fetch.ts, packages/confluence-adapter/src/definitions/utils/restriction.ts
None
---
None
---
None
---
None
=> SALTO-6132 explicitly define serviceIds and elemId parts to empty array when not needed

packages/netsuite-adapter/src/custom_records/custom_record_type.ts, packages/netsuite-adapter/src/filters/internal_ids/sdf_internal_ids.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/custom_records/custom_record_type.test.ts, packages/netsuite-adapter/test/filters/internal_ids/sdf_internal_ids.test.ts
In the apply-patch flow we’re not creating the `internalId` annotation ref on added custom record types, that is a hidden string, and the result is that after the deploy we populate the `internalId` annotation of the custom record type and it is visible and not hidden. Then in the next fetch we fetch the created custom record type, this time with the `internalId` annotation ref, and it makes a merge error because `internalId` is already visible in the nacl.
---
---
- Fix merge error on custom record type addition in the apply-patch flow
---
None
=> SALTO-6150 Fix merge error on custom record type addition in the apply-patch flow

packages/adapter-components/src/definitions/system/fetch/element.ts, packages/adapter-components/test/fetch/element/id_utils.test.ts, packages/adapter-components/test/filters/referenced_instance_names.test.ts
support extendParent for pathParts
---
---
---
=> SALTO-6141: support extendParent for pathParts

packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/test/client.test.ts
It's good to have even for non sandbox orgs.
---
---
None.
---
None.
=> SAAS-9608: Returning SF instance URL in client extra info

packages/jira-adapter/src/filters/layouts/issue_layout.ts
fix the code so it will not crash when the fetch included a project with no issueTypeMappings or when the fetch did not include the issueTypeScreenSchemes of a project and add a log to report this type of cases
---
---
* Fixed a bug that caused fetches to fail when an `Issue Type Screen Scheme` has no `Issue Type Mappings` or when the fetch did not include an `Issue Type Screen Scheme` of a `project`
---
N/A
=> SALTO-5982 issueTypeMappings missing crash

packages/salesforce-adapter/src/custom_references/profiles.ts, packages/salesforce-adapter/test/custom_references/profiles.test.ts
In the profiles element fixer we listed the element source which did not give us fields, which led to us evaluating all field permissions as broken references and removing them.
---
---
_Salesforce_:
* Fixed bug in Salesforce profiles element fixer which caused all field permissions to be dropped.
---
None.
=> SALTO-6153: Including fields when searching in profiles element fixer

packages/netsuite-adapter/e2e_test/adapter.test.ts, packages/netsuite-adapter/src/account_specific_values_resolver.ts, packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/change_validator.ts, packages/netsuite-adapter/src/change_validators/data_account_specific_values.ts, packages/netsuite-adapter/src/change_validators/types.ts, packages/netsuite-adapter/src/change_validators/workflow_account_specific_values.ts, packages/netsuite-adapter/src/config/query.ts, packages/netsuite-adapter/src/config/suggestions.ts, packages/netsuite-adapter/src/config/types.ts, packages/netsuite-adapter/src/config/validations.ts, packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts, packages/netsuite-adapter/src/filter.ts, packages/netsuite-adapter/src/filters/author_information/system_note.ts, packages/netsuite-adapter/src/filters/data_account_specific_values.ts, packages/netsuite-adapter/src/filters/workflow_account_specific_values.ts, packages/netsuite-adapter/src/sdf_folder_loader.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/change_validator.test.ts, packages/netsuite-adapter/test/change_validators/data_account_specific_values.test.ts, packages/netsuite-adapter/test/change_validators/workflow_account_specific_values.test.ts, packages/netsuite-adapter/test/config/suggestions.test.ts, packages/netsuite-adapter/test/config/validations.test.ts, packages/netsuite-adapter/test/data_elements/suiteql_table_elements.test.ts, packages/netsuite-adapter/test/filters/author_information/system_note.test.ts, packages/netsuite-adapter/test/filters/data_account_specific_values.test.ts, packages/netsuite-adapter/test/filters/workflow_account_specific_values.test.ts
Instead of fetching all SuiteQL tables data, we want to fetch only the referenced internalIds in workflows and data instances.
---
~~This PR is based on #6102 . Please review it first.~~
TODO:
---
- Query referenced ASV only
---
None
=> SALTO-5472 query referenced ASV only

packages/confluence-adapter/src/filters/transform_template_body_to_template_expression.ts
Create indices using `reduce` and `...` spreading was not efficient
---
Adding data from running the filter on 42k instances (99% of them are from type `page`)
before:
"(templateBodyToTemplateExpressionFilter):onFetch took 404669 ms"}
after:
"(templateBodyToTemplateExpressionFilter):onFetch took 177 ms" 🤯 
---
None
---
None
=> SAAS-6162 Improve performance on template body filter

packages/zendesk-adapter/src/filters/field_references.ts
add references to user segment ids in article
---
---
zendesk:
* add references to user segment ids in article
---
zendesk:
* add references to user segment ids in article
=> SALTO-6167: add references to user segment ids in article

packages/zendesk-adapter/src/filters/unordered_lists.ts, packages/zendesk-adapter/test/filters/unordered_lists.test.ts
order workspace macro_ids and selected_macros
---
---
zendesk:
* order workspace macro_ids and selected_macros
---
zendesk:
* order workspace macro_ids and selected_macros, to eliminate order diffs between envs
=> SALTO-5897: order workspace macro_ids and selected_macros

packages/jira-adapter/src/config/api_config.ts
salto-6161 JSM omit canCreateRequest field in RequestType
---
---
None
---
None
=> salto-6161 JSM omit canCreateRequest field in RequestType

packages/okta-adapter/e2e_test/adapter.test.ts, packages/zendesk-adapter/src/filters/article/article.ts, packages/zendesk-adapter/test/filters/article/article.test.ts
omit user segment id field from deployment of article
---
---
zendesk:
* fix deployment of articles
---
=> SALTO-6173: omit user segment id field from deployment of article

packages/okta-adapter/e2e_test/adapter.test.ts, packages/okta-adapter/e2e_test/mock_elements.ts
See title.
---
None
---
None
---
None
=> SALTO-6177: Okta: Fix e2e test by temporarily removing Brand-related types

packages/adapter-components/src/filters/referenced_instance_names.ts
Improving running time for referenced instance name filter
---
findIndex is O(n) and we are doing it in the worst case n times. this make the filter running time O(n^2)
adding actual data from fetch on 42K instances (most of them are from type `page` in confluence, which has a reference in its element name)
before:
"(referencedInstanceNames):onFetch took 32647 ms"
after:
"(referencedInstanceNames):onFetch took 7697 ms"
---
None
---
None
=> SALTO-6165_Improve_referenced_instance_name_filter_efficiency

packages/adapter-api/src/adapter.ts, packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/test/client.test.ts
This field can be relevant for all adapters and has semantic meaning (it should be a URL leading to the account in the service).
---
None.
---
None.
---
None.
=> SAAS-9608: Move account URL in to AccountInfo type

packages/jira-adapter/src/config/api_config.ts
salto-6161 JSM omit restrictionStatus field in RequestType
---
---
None
---
None
=> salto-6161 JSM omit restrictionStatus field in RequestType

packages/jira-adapter/src/filters/layouts/issue_layout.ts, packages/jira-adapter/test/filters/layouts/issue_layout.test.ts
this bug was revealed during #6108 and applied here independently.
---
---
---
=> SALTO-6186 fix-broken-jira-ut-layout-issue

packages/netsuite-adapter/src/client/deploy_xml_utils.ts, packages/netsuite-adapter/src/client/graph_utils.ts, packages/netsuite-adapter/test/client/deploy_xml_utils.test.ts, packages/netsuite-adapter/test/client/graph_utils.test.ts
We should remove from deploy.xml not only objects that are in a dependency cycle, but also objects that are dependent on them.
---
---
- Fix "unresolved reference" error in SDF deploy
---
None
=> Remove cycle dependents from deploy.xml

packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts, packages/netsuite-adapter/src/config/config_creator.ts, packages/netsuite-adapter/test/config/config_creator.test.ts
Make two things possible (that before didn't happen together):
- Fix FileCabinet fetchTarget - so user can request for a file only without its parent folder
- Remove folders correctly before querying files - and in fetchTarget we'll keep the folder of a queried file
---
---
- Fix FileCabinet fetchTarget and remove folders correctly before querying files
---
None
=> SALTO-6145 Fix FileCabinet fetchTarget and remove folders correctly before querying files

packages/netsuite-adapter/e2e_test/adapter.test.ts, packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts, packages/netsuite-adapter/src/config/types.ts, packages/netsuite-adapter/test/adapter.test.ts
instead of just writing log, force excluding file cabinet folders before the files query.
---
---
None
---
None
=> SALTO-6145 add config value to force FileCabinet exclusion

packages/netsuite-adapter/src/config/config_creator.ts, packages/netsuite-adapter/test/config/config_creator.test.ts
We should ignore invalid regexes when we add the parent folder to `fetchTarget.filePaths`.
---
---
None
---
None
=> SALTO-6145 ignore invalid regexes

packages/netsuite-adapter/e2e_test/adapter.test.ts
=> Fix NS E2E - skip checking custom records without alias

packages/adapter-components/src/definitions/system/overrides.ts, packages/adapter-components/test/definitions/system/overrides.test.ts
SALTO-5432 override definitions removeNull fix
---
---
---
=> SALTO-5432 override definitions removeNull fix

packages/okta-adapter/e2e_test/adapter.test.ts, packages/okta-adapter/e2e_test/mock_elements.ts, packages/okta-adapter/src/definitions/deploy.ts
See SALTO-6199 for more details. 
TL;DR: To add a new `Brand`, we are now required to call `POST` with only the `name` field and then `PUT` with the other fields (add and then modify).
---
I also included a change for better Jest error messages in the Okta e2e test  🎉 
---
None
---
None
=> SALTO-6199: Fix `Brand` addition API calls following a service change

packages/salesforce-adapter/src/metadata_deploy.ts, packages/salesforce-adapter/test/adapter.crud.test.ts
We currently have a bug where we add errors to successful elements even if they only have info or warning messages and the deployment succeeded.
---
---
_Salesforce_:
* Fixed a bug where elements in a successful deployment got an error with the message: `Element was not deployed because other elements had errors and the 'rollbackOnError' option is enabled (or not set).`
---
None.
=> SALTO-6184: Only adding errors to successful elements if the deploy failed

packages/workspace/src/workspace/nacl_files/nacl_file_update.ts, packages/workspace/test/workspace/nacl_files/nacl_file_update.test.ts
Caught this when adding meta types to existing elements. It's pretty rare to see this in other cases.
---
---
None.
---
None.
=> SALTO-3621: Fixing extra newline when modifying whole elements

packages/cli/src/callbacks.ts
Hide `accessToken` values on account add/login in CLI
---
None
---
None
=> SALTO-6219 hide accessToken in CLI

packages/adapter-components/src/adapter-wrapper/adapter/adapter.ts, packages/pagerduty-adapter/src/filters/users.ts
SALTO-6146 PagerDuty cache users between deploy change groups
---
---
none
---
none
=> SALTO-6146 PagerDuty cache users between deploy change groups

packages/jamf-adapter/src/definitions/fetch/transforms/policy.ts, packages/jamf-adapter/test/adapter.test.ts, packages/jamf-adapter/test/definitions/fetch/transform/policy.test.ts
---
We'd like to add a support on icon but not as part of the MVP (SALTO-6225)
---
- Omit selfServiceIcon on policy instance upon fetch
---
- Omit selfServiceIcon on policy instance upon fetch
=> SALTO-6224 Omit selfServiceIcon on policy instance upon fetch

packages/salesforce-adapter/src/change_validators/new_fields_and_objects_fls.ts, packages/salesforce-adapter/src/change_validators/standard_field_or_object_additions_or_deletions.ts, packages/salesforce-adapter/test/change_validators/standard_field_or_object_additions_or_deletions.test.ts, packages/salesforce-adapter/test/mock_elements.ts
Also improved a warning message that came up during testing.
---
Tested on my env with a custom event.
---
_Salesforce_:
* Fixed a bug where Custom Events were misidentified as Standard Objects and could not be deployed.
---
None.
=> SALTO-6235: Supporting all non-standard types in standard object CV

packages/cli/src/commands/deploy.ts, packages/cli/test/command_builder.test.ts, packages/cli/test/commands/account.test.ts, packages/cli/test/commands/element.test.ts, packages/cli/test/commands/fetch.test.ts, packages/cli/test/commands/init.test.ts, packages/cli/test/commands/restore.test.ts, packages/cli/test/mocks.ts, packages/cli/test/telemetry.test.ts
---
Noticed as part of trying to update jest version.
There are two fixes here:
1. the "mock" telemetry sender was actually using a real telemetry sender that uses timers to send events, most tests never bothered to stop that telemetry sender. since there is really no point in using the real telemetry sender in the mock, the fix was creating a real mock that does nothing
2. in the code of the "deploy" action, there are timers that update about the status of each action, when the deploy is done, in theory, all actions should have received either a "success" or "failure" event, but if that does not happen for any reason, we should still stop all the timers at the end of the function 
---
_None_
---
_None_
=> SALTO-6237: Fix leftover timers in cli tests

packages/salesforce-adapter/src/filters/custom_metadata.ts, packages/salesforce-adapter/test/filters/custom_metadata.test.ts
Bugfix: Salesforce CustomMetadata Records deploy fail when attempting to delete field values
---
It seems like Salesforce started to enforce providing value to the xsi:nil attribute which indicates no value (null). This caused deletions in CustomMetadata Records to fail as we used to send them as <xsi:nil/> instead of <xsi:nil=”true”/>. 
---
- Bugfix: Salesforce CustomMetadata Records deploy fail when attempting to delete field values
---
_None_
=> SALTO-6236: Salesforce CustomMetadata Records deploy fail when attempting to delete field values

packages/jira-adapter/src/filters/fields/context_options_splitted.ts
Fixed a bug in addition of cascading options
---
None
---
Jira Adapter:
* fixed a bug in cascading options when working with the new beta
---
=> SALTO-5932: cascading options bug

packages/confluence-adapter/src/definitions/requests/pagination.ts
Using different pagination function to bring users for confluence. The old function wasn't effective and was fetching the same user more than once
---
---
None
---
None
=> SALTO-6245 change pagination function for users

packages/salesforce-adapter/src/custom_references/handlers.ts
Due to some edge-cases we plan to solve in the future, we will disable the fixer for the time being.
---
Had to separate the defaults for the `customRefFuncs` and the `fixers`.
---
_None_
---
_None_
=> SALTO-6240: Disable Salesforce Profiles Elements Fixer by default

packages/zendesk-adapter/src/change_validators/users.ts, packages/zendesk-adapter/src/fix_elements/fallback_user.ts, packages/zendesk-adapter/src/user_utils.ts, packages/zendesk-adapter/test/change_validators/users.test.ts, packages/zendesk-adapter/test/fix_elements/fallback_user.test.ts, packages/zendesk-adapter/test/user_utils.test.ts
fix missing user fallback logic when resolveUserIds is false
---
---
zendesk:
* fix missing user fallback logic when resolveUserIds is false. setting `defaultMissingUserFallback =  "##DEPLOYER##"` will work.
---
none
=> SALTO-6250: fix missing user fallback logic when resolveUserIds is false

packages/jira-adapter/src/filters/sort_lists.ts
Cancled the sorting of post functions
---
See Jira ticket for details. We are skipping noise reduction is it is complicated and will only influence one customer which will be communicated personally
---
Jira adapter:
* keep post functions order in DC
---
Jira adapter:
* for DC users the order of post functions in workflow will change
=> SALTO-3845: cancel workflow post functions sort in DC

packages/zendesk-adapter/src/adapter_creator.ts, packages/zendesk-adapter/src/auth.ts, packages/zendesk-adapter/src/client/connection.ts, packages/zendesk-adapter/test/adapter.test.ts, packages/zendesk-adapter/test/adapter_creator.test.ts, packages/zendesk-adapter/test/client/connection.test.ts
Zendesk is deprecating username/password and adding API token support
---
---
__Zendesk Adapter:__ 
* Users can now authenticate to Zendesk with username and API Token
---
=> SALTO-6188 Add support for API Token for Zendesk

packages/adapter-components/src/fetch/request/pagination/queue.ts, packages/adapter-components/src/fetch/resource/type_fetcher.ts
---
1. fix args parsing
2. fix response parsing (in both cases we got `response: [Object]`
---
None
---
None
=> SALTO-6257: Fix object parsing in log messages in adapters infra

packages/core/src/api.ts, packages/core/test/api.test.ts, packages/zendesk-adapter/src/adapter.ts, packages/zendesk-adapter/src/adapter_creator.ts, packages/zendesk-adapter/src/config.ts, packages/zendesk-adapter/src/fix_elements/index.ts, packages/zendesk-adapter/src/fix_elements/merge_lists.ts, packages/zendesk-adapter/src/user_config.ts, packages/zendesk-adapter/test/fix_elements/merge_lists.test.ts
add fixer for merge of  options lists in ticket_field
---
In this fixer we merge custom_field_options, by updating the father list to include all options from the elementsSource.
Therefor if there is a custom option that was deleted from the list however its instance was not deleted we will add it back to the list
---
---
=> SALTO-6211: add fixer for merge of options lists in ticket_field

packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/utils.test.ts
---
will be merged after next release
---
_Core_:
- `allowEmpty` param is removed from `transformElement`. Alternatively, you may use `allowEmptyArrays` and `allowEmptyObjects`.
---
None
=> SALTO-6105: Remove allow empty from `transformElement`

packages/vscode/syntaxes/salto.json
---
---
_VS Code Extension_:
* Support for meta types syntax.
---
None.
=> SALTO-6259: Supporting meta types syntax in VSC extension

packages/adapter-utils/src/change.ts, packages/adapter-utils/test/change.test.ts
in `reverseChange`, reverse the `change.elemIDs` too (in case of `detailedChange` input).
---
---
None
---
None
=> SALTO-5323 reverse change elemIDs

packages/adapter-components/src/adapter-wrapper/adapter/adapter.ts
small leftover from the previous fix - in the new infra we only generate types and no config, so the types are different 
(was fixed in okta at the time but not in the adapter wrapper)
---
None
---
None
=> SALTO-5642 fix extracted types from swagger

salto.code-workspace
Ignoring packages directory explicitly to avoid duplications.
---
---
None.
---
None.
=> SALTO-2670: Adding root to VS Code workspace

packages/jira-adapter/src/dependency_changers/issue_layout_dependency.ts, packages/jira-adapter/test/dependency_changers/issue_layout_dependency.test.ts
Can happen with a missing reference in the parent
---
None
---
Jira Adapter:
* Fixed a bug that caused errors in deployment when an issue layout had a missing parent reference 
---
None
=> SALTO-6275: issue layout dependency bug

packages/salesforce-adapter/src/transformers/xml_transformer.ts, packages/salesforce-adapter/test/adapter.crud.test.ts, packages/salesforce-adapter/test/transformers/xml_transformer.test.ts
This is a step towards supporting SFDX format.
Formatting the XMLs generated by the adapter to match the formatting options that SFDX uses
---
---
_None_
---
_None_
=> SALTO-6276: Format salesforce deployed XMLs

packages/okta-adapter/src/filters/policy_priority.ts, packages/okta-adapter/test/filters/policy_priority.test.ts
bug fix
---
After creating policy with its rules, we create api calls to update the rules order according to the user's request.
To update the priority field we must update the policy rule, and the bug was due to the fact we didn't send the `actions` field for this policy (which is mandatory in the request) 
---
- Bug fix for deployment of priority of `MultifactorEnrollmentPolicyRule` 
---
None
=> SALTO-6288: Fix bug in deployment of MultifactorEnrollment Policy order instance

packages/adapter-components/src/fetch/request/requester.ts
fix to allow defining custom `params` in client calls
(still missing UTs)
---
None
---
None
=> SALTO-6296 fix passing custom params to client

packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/test/client.test.ts
Simplify Salesforce Client listMetadataObjects caching
---
Required step to tackle throttling issues in Change Based Fetch where we execute the same listMetadataObjects request three times on Profiles related metadata types. 
---
_None_
---
_None_
=> SLATO-6295: Simplify Salesforce Client listMetadataObjects caching

README.md
Add missing input path specifier to docker build command instruction
=> README.md: Update docker build command instruction

packages/microsoft-entra-adapter/src/adapter_creator.ts, packages/microsoft-entra-adapter/src/error_utils.ts, packages/microsoft-entra-adapter/src/filters/array_fields_deployment.ts, packages/microsoft-entra-adapter/test/error_utils.test.ts, packages/microsoft-entra-adapter/test/filters/array_fields_deployment.test.ts
The error message returned in the response from Microsoft Graph when a request fails are informative (AFAICT ATM) and helpful in understanding the cause of the problem. We want the users to be able to read them as well and workaround small issues if such exist.
---
Microsoft Entra:
* Expand user-facing errors to include more informative messages when requests fail.
---
=> SALTO-6293: [MS Entra] Convert http error messages to include the message from the response

packages/salesforce-adapter/src/filters/custom_metadata.ts, packages/salesforce-adapter/src/transformers/xml_transformer.ts, packages/salesforce-adapter/test/mock_elements.ts, packages/salesforce-adapter/test/transformers/xml_transformer.test.ts
Salesforce LWC deploy XML parsing bug-fix
---
There's a bug when a property has the attribute `default` with the value true. This is demonstrated in the UTs and pretty straightforward.
---
Salesfore Adapter:
- Fixed a bug where deploy of LightningWebComponent failed on `Attribute name "default" associated with an element type "property" must be followed by the ' = ' character.`
---
_None_
=> SALTO-6284: Salesforce LWC deploy XML parsing bug-fix

packages/adapter-components/src/definitions/system/index.ts, packages/adapter-components/src/definitions/system/shared/transformation.ts, packages/adapter-components/src/fetch/utils.ts, packages/adapter-components/test/fetch/utils.test.ts, packages/confluence-adapter/src/definitions/utils/label.ts, packages/confluence-adapter/src/definitions/utils/page.ts, packages/confluence-adapter/src/definitions/utils/restriction.ts, packages/confluence-adapter/src/definitions/utils/space.ts, packages/confluence-adapter/src/definitions/utils/template.ts, packages/confluence-adapter/src/definitions/utils/users.ts, packages/intercom-adapter/src/definitions/fetch/transforms/map_array_field_to_nested_values.ts, packages/intercom-adapter/src/definitions/fetch/transforms/replace_field_with_nested_value.ts, packages/jamf-adapter/src/definitions/fetch/transforms/class.ts, packages/jamf-adapter/src/definitions/fetch/transforms/configuration_profile.ts, packages/jamf-adapter/src/definitions/fetch/transforms/policy.ts, packages/okta-adapter/src/definitions/fetch/types/user_type.ts, packages/pagerduty-adapter/src/definitions/utils/schedule_layers.ts, packages/serviceplaceholder-adapter/src/definitions/fetch/transforms/business_hours_schedule.ts
Allow the `adjust` function to return multiple items or values - needed for some more complex manipulations of returned responses
---
the "extended" `AdjustFunction` function can still be used, but since sometimes it helps to be able to rely on the returned type for further manipulation, converted most of the existing functions to `Single` (which was the only supported variant until this PR)
---
None
---
None
=> SALTO-6305 allow adjust to return multiple items

packages/cli/src/commands/account.ts, packages/cli/test/commands/account.test.ts, packages/cli/test/mocks.ts
Noticed this while working with the `zendesk-adaptor` after the recent changes to add `token` to the cli options (for zendesk api token usage).
Attempting to add the `zendesk` service to an environment worked okay when using the interactive mode
`node ~/salto/packages/cli/dist/src/main.js account add zendesk`
However, trying to do this as a one-shot via the `--login-parameters` failed
`node ~/salto/packages/cli/dist/src/main.js account add zendesk --login-parameters username=chris token=abc123 subdomain=testdomain`
```
Error: Could not login to zendesk: Missing the following login parameters: password
```
The comparison operator utilized in `createConfigFromLoginParameters()` (in `packages/cli/src/commands/account.ts`) scans the param field annotations looking for the **required** params …
=> BUGFIX: cli parameters being misidentified as 'required'

packages/adapter-components/src/definitions/system/utils.ts, packages/adapter-components/src/fetch/element/instance_element.ts
The def query is used in many places, and runs some computations in order to return `.query(typeName)` results. specifically, it makes many such requests as part of the `extractStandaloneInstances` logic which runs recursively on instances - and has caused some slowdown in zendesk fetches post upgrade.
---
adding a cache as a first step for optimizing that flow - which seems to reduce it significantly on large environments.
also adding some additional logs - if needed, we can optimize this flow further, e.g. by "pruning" paths that cannot reach standalone instances.
---
None
---
None
=> SALTO-6304 Cache queryWithDefault queries

packages/jira-adapter/jest.config.js, packages/jira-adapter/src/change_validators/issue_layouts_validator.ts, packages/jira-adapter/src/filters/layouts/issue_layout.ts, packages/jira-adapter/test/change_validators/issue_layout_validator.test.ts, packages/jira-adapter/test/filters/layouts/issue_layout.test.ts
The issue type scheme can have no issue type ids
---
None
---
Jira Adapter:
* Fixed a bug that caused a change validator to fail a deploy operation
---
N/A
=> SALTO-6298: fixed a crash for issue layout validator

packages/parser/src/parser/internal/native/consumers/values.ts, packages/parser/src/parser/internal/native/lexer.ts, packages/parser/src/utils/template_static_file.ts, packages/parser/test/parser/dump.test.ts, packages/parser/test/template_static_file.test.ts
This PR wants to have a single string parser both for the regular flow and for template static files. 
Regarding the `values.ts` changes - I had to change the way the string value was created, as the parser now works for both single line and multi line strings. This means that multi line strings have escapes as tokens. So unescaping multiline strings doesn't work for escaped tokens, as they split the `\'''` into `\'` and `''`.
---
---
__Core:__
* Fixed a bug parsing template static files with string interpolations.
---
_Replace me with a short sentence that describes changes that will appear in NaCls and are not caused by user actions (e.g. a new annotation, field values that are converted to references, etc). …
=> SALTO-6037 Extract string lexer, consolidate usage with template static file

.circleci/config_template.yml, build_utils/hash_dependencies.js, build_utils/turbo_run.sh, package.json, turbo.json
add turbocache to unit tests
---
this part was split off of SALTO-3518
---
with this PR, we now support turbocache for both local tests and CircleCI.
if you need to test a specific package, do (for example):
```
yarn test --filter @salto-io/zendesk-adapter
```
before the turbocache run, we will check if any source files have been modified in any of the dependencies of the package you are testing (or the entire project, if you run all tests).
---
=> SALTO-6241 turbocache unit tests

.git-blame-ignore-revs
---
Ignore the commit from #6255
---
_None_
---
_None_
=> SALTO-5404: Add salesforce-adapter prettier commit to blame ignore

packages/salesforce-adapter/e2e_test/jest_environment.ts, packages/salesforce-adapter/src/change_validators/metadata_types.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/custom_metadata_to_object_type.ts, packages/salesforce-adapter/src/filters/custom_objects_to_object_type.ts, packages/salesforce-adapter/src/filters/reference_annotations.ts, packages/salesforce-adapter/src/metadata_deploy.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/change_validators/metadata_types.test.ts, packages/salesforce-adapter/test/filters/custom_metadata.test.ts, packages/salesforce-adapter/test/filters/custom_metadata_to_object_type.test.ts, packages/salesforce-adapter/test/filters/custom_type_split.test.ts, packages/salesforce-adapter/test/mock_elements.ts
Added an underscore before so we can free these element IDs up for meta types. Also syncified some logic during debugging which is nice to have generally.
---
I tested fetching and deploying and also deploying without fetching.
The latter works fine is because all of the places we rely on the new names are either during fetch (in which case we always already have them) or during deploy where we create them artificially and don't rely on what we got in fetch.
---
_Salesforce_:
- Renamed the internal and hidden `CustomObject` and `CustomMetadata` types to `_CustomObject` and `_CustomMetadata`.
---
None.
=> SALTO-6264: Renaming CustomObject and CustomMetadata types

packages/okta-adapter/src/definitions/fetch/fetch.ts, packages/okta-adapter/src/definitions/requests/clients.ts
Fix pagination bug
---
The issue caused by the `search` query param that was part of the `endpoint` instead of being passes as `query` arg
This somehow caused calculating a wrong url for the next page which caused the entire type to fail
The fix is removing it from the `endpoint` and pass it as a query arg 
---
- Fix bug in pagination for `User` type
---
None
=> SALTO-6314: Fix issue with User type pagination

packages/jira-adapter/config_doc.md, packages/jira-adapter/src/client/client.ts
SALTO-5959 Jira should use bottleneck by default
---
https://github.com/salto-io/salto/pull/6146/
---
none
---
none
=> SALTO-5959 Jira should use bottleneck by default

packages/okta-adapter/src/definitions/requests/clients.ts
We were adding the page size query param to the wrong thing
---
---
None
---
None
=> SALTO-6313: Fix page size params for Okta endpoints 

packages/parser/src/parser/internal/native/consumers/top_level.ts, packages/parser/src/parser/internal/native/errors.ts, packages/parser/test/parser/parse.test.ts
No reason to not allow and we have a use for this in SFDC.
---
---
None.
---
None.
=> SALTO-3621: Allow meta types for settings

packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts, packages/salesforce-adapter/src/types.ts
Adding in a separate PR so I can rely on this for both adding the meta types and the existing types rename.
---
---
None.
---
None.
=> SALTO-6147: Adding meta types optional feature to SFDC

packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/src/config/types.ts, packages/netsuite-adapter/src/custom_references/weak_references/fields_references.ts, packages/netsuite-adapter/src/scriptid_list.ts, packages/netsuite-adapter/test/custom_references/weak_references/fields_references.test.ts
in case that a form field reference an object with `appid`, we should check if that app id is even being fetched, otherwise the object won't be in the `objectid_list` instance, and we'll remove it.
---
---
- fix fixElements of form fields that reference objects with appid
---
None
=> SALTO-6299 fix fixElements of form fields that reference objects with appid

packages/adapter-api/src/utils.ts, packages/adapter-utils/src/compare.ts, packages/adapter-utils/src/list_comparison.ts, packages/adapter-utils/test/compare.test.ts
Add a `filterFunc` to `applyDetailedChanges`, that tells the function which changes should be applied. The reason for this `filterFunc`, instead of passing in advance only the list of changes that you want to apply, is that in list item changes, the indexes should be fixed when you apply only part of the changes - if you want to ignore an addition/removal, the indexes of the following changes should be fixed, so the right order is kept.
Because of the complexity in applying only part of the reorder changes in a list, reorder changes will be applied only when all of the changes in that list should be applied.
---
---
Core:
- add `filterFunc` to `applyDetailedChanges`
---
None
=> SALT0-5323 add filterFunc to applyDetailedChanges

packages/adapter-components/src/definitions/system/fetch/resource.ts, packages/adapter-components/src/fetch/element/element.ts, packages/adapter-components/test/fetch/element/element.test.ts, packages/okta-adapter/src/definitions/fetch/fetch.ts
Added the option to ignore known errors during fetch and suppress them 
---
changes - 
- By default, all errors will not ignored and will trigger `log.error` (even when not providing error handler) with "failed to fetch type".
- When customizing `onError`, returning `ignoreError` will make the error to be suppressed (to debug level).
---
None
---
None
=> SALTO-6319: Add the ability to ignore errors during fetch

packages/adapter-api/src/values.ts, packages/adapter-utils/src/compare.ts, packages/core/src/api.ts, packages/core/src/core/diff.ts, packages/core/src/core/restore.ts, packages/core/test/api.test.ts, packages/core/test/core/diff.test.ts
change the API of `createDiffChanges` to receive an object param, and add it `compareOptions`, that are used in the elements comparison.
---
---
Core:
- Change the API of `createDiffChanges` to receive an object param, and add it `compareOptions`, that are used in the elements comparison.
---
None
=> SALTO-5323 add compareOptions to createDiffChanges params

packages/adapter-components/src/client/http_client.ts, packages/adapter-components/src/definitions/system/requests/types.ts, packages/adapter-components/src/fetch/request/requester.ts, packages/adapter-components/test/client/http_client.test.ts
Allow serializing combinations of the same query arg in different ways using axios - 
`arg=val1&arg=val2`
`arg[]=val1&arg[]=val2`
`arg[0]=val1&arg[1]=val2`
for use in https://github.com/salto-io/salto/pull/6217
---
None
---
None
=> SALTO-6330 allow adjusting serializations for query arg combinations

packages/salesforce-adapter/src/config_creator.ts, packages/salesforce-adapter/src/types.ts
They come together with permission sets, doesn't make much sense to exclude only permission sets and not these.
---
---
_Salesforce_:
* Excluding MutingPermissionSets and PermissionSetGroups by default for new accounts.
---
None.
=> SALTO-6335: Excluding MutingPermissionSets and PermissionSetGroups by default

packages/salesforce-adapter/src/transformers/reference_mapping.ts
Add reference from Salesforce QuickAction `fieldOverrides` to their respective fields.
---
Before value:
```
fieldOverrides = [
{
field = "SLA__c"
literalValue = "Gold"
},
]
```
After value:
```
fieldOverrides = [
{
field = salesforce.Account.field.SLA__c
literalValue = "Gold"
},
]
```
---
- Add references for QuickAction fieldOverrides.
---
Salesforce:
- Existing QuickAction instances may have changes from strings to References.
=> SALTO-6341: Salesforce QuickAction Field Overrides References

build_utils/create_version_pr.sh
In this PR I modified ./create_version_pr.sh  script
---
@Eshed Gal-Or [PR](https://github.com/salto-io/salto/pull/6108) added dependency to our Salto release version in the yarn.lock
For example: 
"@salto-io/adapter-api": 0.3.60
Meaning that we should add yarn to modify this yarn.lock as part of the script of OSS release.
---
---
=> SALTO-6350: Modify ./create_version_pr.sh script

packages/netsuite-adapter/src/config/config_creator.ts, packages/netsuite-adapter/test/config/config_creator.test.ts
Leaving empty values in fetch target makes us run `listObjects` on the types that we're not interested in.
---
---
None
---
None
=> Remove empty values from NS fetch target

packages/okta-adapter/src/definitions/fetch/types/application.ts, packages/okta-adapter/test/adapter.test.ts, packages/okta-adapter/test/mock_replies/application_add_custom_active.json, packages/okta-adapter/test/mock_replies/application_add_custom_inactive.json, packages/okta-adapter/test/mock_replies/application_add_regular_inactive.json, packages/okta-adapter/test/mock_replies/application_modify_custom_active_unchanged_policies.json, packages/okta-adapter/test/mock_replies/application_modify_custom_inactive_with_changed_policies.json
There is a bug in the current `isCustomApp` detection method when subdomains are changed. We suspect that checking for a suffix of underscore + counter (`_1`, `_2` etc.) would be sufficient and work around this bug. This PR adds some logs so we can gather some data on this.
---
I've also modified some tests to match what we know about custom app names.
---
None
---
None
=> SALTO-6351: Okta: Add logs for `isCustomApp` matching methods.

packages/salesforce-adapter/src/filters/reference_annotations.ts
Salesforce adapter referenceTo references from Lookup fields bug-fix
---
Fixed a recent regression where referenceTo references were not created successfully in Lookup fields.
---
_None_
---
_None_
=> SALTO-6353: Salesforce adapter referenceTo references from Lookup fields bug-fix

packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/config/suggestions.ts, packages/netsuite-adapter/src/config/types.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/config/suggestions.test.ts
_We fully support `withChangesDetection` in the SAAS, there is no need for a config flag_
---
None
---
* _useChangesDetection in the NS is not longer supported. Use changed-based fetch._
---
=> SALTO-3676: remove useChangesDetection from NS config

packages/google-workspace-adapter/src/definitions/fetch/fetch.ts
SALTO-5939 Google ws: ignore common errors 
---
---
---
=> SALTO-5939 Google ws: ignore common errors 

packages/adapter-api/src/adapter.ts, packages/adapter-components/src/adapter-wrapper/adapter_creator.ts, packages/adapter-components/src/definitions/system/overrides.ts, packages/adapter-components/test/definitions/system/overrides.test.ts, packages/core/src/core/adapters/adapters.ts
SALTO-6354 defention overrides env var work by account name
---
---
none
---
none
=> SALTO-6354 definition overrides env var work by account name

packages/jira-adapter/src/client/client.ts, packages/jira-adapter/src/filters/forms/forms.ts, packages/jira-adapter/src/filters/forms/forms_types.ts, packages/jira-adapter/test/filters/forms/forms.test.ts
In this PR I moved the Form type in Jira to the new API 
---
The values ​​remained the same except for 3 new fields which I will add Noise Reduction.
From what I see through the CLI - fetch, create, modify and remove all worked great! 
It is important to note some point:
1. The id changed from a number to a string which is actually a uuid and I'm not sure if it has certain meanings or not
since the uuid was deleted, so the ServiceID changed to the id field. Whats going to happen in the next Fetch? 
---
* Moved JSM forms to the new API. 
---
* Changes will be applied in Form instances:
The fields `issueRequestTypeIds`, `newIssueIssueTypeIds`, `newIssueRequestTypeIds` will be replaced …
=> SALTO-6317: Move Jsm forms to official api

packages/core/test/common/workspace.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/common/nacl_file_store.ts, packages/workspace/test/workspace/config_source.test.ts, packages/workspace/test/workspace/workspace.test.ts
fix updateNaclFiles to count static file changes
---
---
---
=> SALTO-6342: fix updateNaclFiles to count static file changes

packages/adapter-utils/src/collisions.ts, packages/adapter-utils/test/collisions.test.ts, packages/zendesk-adapter/src/filters/guide_service_url.ts, packages/zendesk-adapter/test/filters/omit_collision.test.ts
A link to the service will now appear if it exists to the ID collision errors.
The error looked (partially) like this before:
```
Breakdown per colliding Salto ID:
- Test_12672121723027:
* Instance with Id - Test_12672121723027
* Instance with Id - Test_12672121723027
```
and after: 
```
Breakdown per colliding Salto ID:
- Test_12672121723027:
* Instance with Id - Test_12672121723027. View in the service - https://d3v-salto2.zendesk.com/knowledge/articles/31771664875155/en-us?brand_id=11442239212179
* Instance with Id - Test_12672121723027. View in the service - https://d3v-salto2.zendesk.com/knowledge/articles/13536523381523/da?brand_id=11442239212179
```
---
---
* In ID collision errors - a link to the service will …
=> SALTO-6109 Add service url (if present) to collision error

packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts, packages/netsuite-adapter/src/client/suiteapp_client/soap_client/types.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts, packages/netsuite-adapter/src/client/utils.ts, packages/netsuite-adapter/test/client/client.test.ts, packages/netsuite-adapter/test/client/suiteapp_client/soap_client/soap_client.test.ts, packages/netsuite-adapter/test/client/suiteapp_client/suiteapp_file_cabinet.test.ts
Since each deploy error is attached to the failed change id, the error message we're returning for data instances deploy can be more friendly to the user:
instead of `SOAP api call <...> for instance <...> failed. error code: <...>, error message: <...>` we can just return the error message from SOAP. it will be much more readable for users.
In addition, make SOAP deploy return a nicer return type - `SoapDeployResult` instead of `number | Error`.
---
---
- Return nicer SOAP deploy error messages
---
None
=> Return nicer SOAP deploy error messages

packages/okta-adapter/src/change_validators/index.ts, packages/okta-adapter/src/config.ts, packages/okta-adapter/src/filters/brand_theme_files.ts, packages/okta-adapter/test/adapter.test.ts, packages/okta-adapter/test/mock_replies/brand_theme_files_remove.json
`BrandTheme`-related static files (`BrandLogo` and `FavIcon`) don't really use the infra to deploy - all the work is done in the `brand_theme_files.ts` filter. In this PR I removed the dummy content from the old config and added these to an ignore list for the CV that verifies deploy definitions exist.
---
None
---
None
---
None
=> SALTO-5692: Okta: Add HTTP recording tests for `BrandTheme` files (logo and favicon) deploy and remove old-infra config

packages/adapter-utils/src/config_options.ts, packages/jira-adapter/src/config_creator.ts, packages/salesforce-adapter/src/config_creator.ts, packages/workato-adapter/src/adapter_creator.ts, packages/workato-adapter/src/config_creator.ts, packages/workato-adapter/test/config_creator.test.ts, packages/zendesk-adapter/src/config_creator.ts
Add config creator to workato to allow controlling deploy settings
---
Also added some code to adapter utils 
---
None
---
None
=> SALTO-6376: Add config creator with enable deploy option to Workato

packages/okta-adapter/src/definitions/requests/clients.ts
Okta endpoints return 404 for `delete` endpoints where the instance was already deleted. Many Okta instances are deleted automatically with their parent, so we allow 404 as response by default for cases where we delete both parent and child together.
---
---
None
---
None
=> SALTO-5692: Okta: Allow HTTP 404 as valid response for `delete` endpoints by default

packages/jira-adapter/src/filters/field_configuration/field_configuration_deployment.ts, packages/jira-adapter/src/filters/field_configuration/field_configuration_items.ts
Following a bug for a customer we limit deployment of field configurations to one at a time in Jira DC
---
None
---
Jira Adapter:
* Fixed a bug with FieldConfiguration deployment in jira DC
---
None
=> SALTO-6395: fieldConfiguration in DC

packages/okta-adapter/src/config.ts, packages/okta-adapter/src/definitions/deploy/deploy.ts, packages/okta-adapter/test/adapter.test.ts, packages/okta-adapter/test/filters/app_logo.test.ts
See title.
---
This PR includes both the tests and the actual upgrade, because filters still do all the work (config change is just a hack to keep the "operation not supported" CV from reporting this type).
---
None
---
None
=> SALTO-5692: Okta: Upgrade `AppLogo` deploy definitions to new infra

packages/jira-adapter/e2e_test/adapter.ts, packages/jira-adapter/e2e_test/instances/cloud/index.ts, packages/jira-adapter/e2e_test/instances/cloud/workflow.ts, packages/jira-adapter/e2e_test/instances/cloud/workflowScheme.ts, packages/jira-adapter/e2e_test/instances/datacenter/index.ts, packages/jira-adapter/e2e_test/instances/datacenter/workflowScheme.ts, packages/jira-adapter/e2e_test/instances/index.ts, packages/jira-adapter/src/config/config.ts, packages/jira-adapter/src/filters/workflowV2/workflowV1_removal.ts, packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts, packages/jira-adapter/test/filters/script_runner/workflow/workflow_cloud.test.ts, packages/jira-adapter/test/filters/workflowV2/workflowV1_removal.test.ts, packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts
_enable enableNewWorkflowAPI config flag by default_
---
* The enable required to add WorkflowV2 to Jira E2E
---
---
=> SALTO-6359: enable enableNewWorkflowAPI config flag by default

packages/pagerduty-adapter/src/definitions/fetch/fetch.ts
SALTO-6403 Pagerduty remove direct fetch from recurseInto serviceOrchestration type
---
---
none
---
none
=> SALTO-6403 Pagerduty remove direct fetch from recurseInto serviceOrchestration type

packages/zendesk-adapter/src/change_validators/default_dynamic_content_item_variant.ts, packages/zendesk-adapter/test/change_validators/default_dynamic_content_item_variant.test.ts
defaultDynamicContentItemVariantValidator - Cannot read properties of undefined (reading 'default')
---
There was edge-case where the adapter threw this run-time error due to invalid resolved reference of a `Variant`.
---
_None_
---
_None_
=> SALTO-6279: (bug-fix) defaultDynamicContentItemVariantValidator - Cannot read properties of undefined (reading 'default')

packages/adapter-api/src/adapter.ts, packages/core/index.ts, packages/core/src/api.ts, packages/core/src/core/adapter_format.ts, packages/core/src/types.ts, packages/core/test/api.test.ts, packages/core/test/common/helpers.ts, packages/core/test/core/adapter_format.test.ts
Add a new core API that syncs the elements from a workspace to a folder in an adapter format (SFDX) This also refactors the existing "calculatePatch" function which also deals with adapter formatted folders
---
No release notes yet since this is not an exposed command.
will add to the release notes once the CLI command is added
---
_None_
---
_None_
=> SALTO-6398: Add syncWorkspaceToFolder API

packages/jira-adapter/src/filters/fields/field_structure_filter.ts, packages/jira-adapter/test/filters/fields/field_structure.test.ts
In this PR, I modified the empty key in the context option to be saved as @ instead of an empty string.
---
---
* Fixed a bug that caused duplicate attributes due to an empty string in the context option's key.
---
* The empty string inside the options field in `CustomFieldContext` will now be replaced by '@'.
=> SALTO-6415: Fix empty key for context options

packages/jira-adapter/src/filters/forms/forms_types.ts
We recently changed the API to fetch forms and the question field changes from ListType to mapType which resulted in not adding references. In this PR I fixed it. 
---
---
* Inside `Form` type, the `jiraField` will change from string to reference. 
---
* Inside `Form` type, the `jiraField` will change from string to reference.
=> SALTO-6417: Change question type in forms

packages/core/src/local-workspace/dir_store.ts, packages/core/test/common/workspace.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/common/nacl_file_store.ts, packages/workspace/test/workspace/config_source.test.ts, packages/workspace/test/workspace/multi_env/multi_env_source.test.ts, packages/workspace/test/workspace/workspace.test.ts
fix update nacl files to include static file changes
---
---
core:
* fix bug that when the only changes in fetch are modifications to static resources, the fetch returns empty
---
=> SALTO-6342: fix update nacl files to include static file changes continue

packages/salesforce-adapter/src/filters/cpq/rules_and_conditions_refs.ts, packages/salesforce-adapter/test/filters/cpq/rules_and_conditions_refs.test.ts
CPQ Rules and Conditions Filter creates invalid TemplateExpressions when no conditions are fetched for Rule
---
When a `TemplateExpression` contains a single part that is string, the env will have non-semantic pending changes. (As we compare `TemplateExpression` with a string)
This is an edge-case that the filter can reach when no conditions were fetched for the `Custom Rule`.
---
- Bugfix: CPQ Rules and Conditions Filter creates invalid TemplateExpressions when no conditions are fetched for Rule.
---
_None_
=> SAAS-11750: CPQ Rules and Conditions Filter creates invalid TemplateExpressions when no conditions are fetched for Rule

packages/core/src/local-workspace/dir_store.ts, packages/core/test/common/workspace.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/common/nacl_file_store.ts, packages/workspace/test/workspace/config_source.test.ts, packages/workspace/test/workspace/multi_env/multi_env_source.test.ts, packages/workspace/test/workspace/workspace.test.ts
fix update nacl files to include static file changes
---
---
core:
* fix bug that when the only changes in fetch are modifications to static resources, the fetch returns empty
---
=> SALTO-6342: fix update nacl files to include static file changes

packages/okta-adapter/test/adapter.test.ts, packages/okta-adapter/test/mock_replies/network_zone_activate.json, packages/okta-adapter/test/mock_replies/network_zone_add_active.json, packages/okta-adapter/test/mock_replies/network_zone_add_inactive.json, packages/okta-adapter/test/mock_replies/network_zone_deactivate.json, packages/okta-adapter/test/mock_replies/network_zone_modify.json, packages/okta-adapter/test/mock_replies/network_zone_modify_and_activate.json, packages/okta-adapter/test/mock_replies/network_zone_modify_and_deactivate.json, packages/okta-adapter/test/mock_replies/network_zone_remove.json
See title.
---
This PR is just the tests, not the upgrade yet.
---
None
---
None
=> SALTO-5692: Okta: Add HTTP recording tests for `NetworkZone`

packages/okta-adapter/test/adapter.test.ts, packages/okta-adapter/test/mock_replies/org_setting_modify.json
See title
---
These are just the tests, not the actual upgrade. `OrgSetting` only supports `modify`.
---
None
---
None
=> SALTO-5692: Okta: Add HTTP recording tests for `OrgSetting`

packages/confluence-adapter/src/definitions/deploy/deploy.ts, packages/confluence-adapter/src/definitions/fetch/fetch.ts, packages/confluence-adapter/src/definitions/references.ts, packages/confluence-adapter/src/definitions/utils/space.ts, packages/confluence-adapter/test/definitions/utils/space.test.ts, packages/confluence-adapter/test/filters/deploy_space_and_permissions.test.ts
- add support on fetch and deploy groups
- reference on groups permissions on space instance
- change logic of create key for permission (this key is used to store permission serviceId in an hidden map), new logic doesn't use the serviceId as part of the key (as groups internalIds are not multi env friendly, this was the root cause of failure in deploying space with its permissions between environment)
---
---
- Support fetch and deploy of groups
- Fix space deployment
---
- Support fetch and deploy of groups
- Fix space deployment
=> SALTO-6345_fix_space_deployment

packages/adapter-components/src/deployment/change_validators/unique_fields.ts, packages/adapter-components/test/deployment/change_validators/unique_fields.test.ts, packages/jira-adapter/src/change_validators/index.ts
Validate the uniqueness of the fields `name` and `key` within project type elements
Changed the unique values CV to handle multiple fields within a type
---
None
---
* validate uniqueness in Project's name and key
---
_None_
=> SALTO-6416: (Jira) validate uniqueness in Project's name and key

packages/okta-adapter/src/reference_mapping.ts
Add 2 rules in order to parse references to `Group` type from inner types in `IdentityProviderType`
---
This is a noisy change, will follow up with noise reduction / prod ticket
---
- References to groups will be added to Identity Provider instances with assigned groups
---
- References to groups will be added to Identity Provider instances with assigned groups
=> SALTO-6411: Add reference from IdP type to Group type (Okta)

packages/jira-adapter/src/filters/assets/assets_object_type_order.ts, packages/jira-adapter/test/filters/assets/assets_object_type_order.test.ts
In this PR I removed unused field `assetSchema` from ObjectTypeOrder
---
* Will add noise reduction. 
---
* ObjectTypeOrder instances will no longer have `assetSchema` field.
---
* ObjectTypeOrder instances will no longer have `assetSchema` field.
=> SALTO-6420: Remove unused field `assetSchema` from ObjectTypeOrder

packages/jira-adapter/src/change_validators/workflowsV2/status_mappings.ts, packages/jira-adapter/test/change_validators/workflowsV2/status_mappings.test.ts
_statusMapping change validator should relies on elemID instead of name_
---
---
Jira Adapter: 
* fix a bug in statusMapping change validator
---
=> SALTO-6423: statusMapping change validator should relies on elemID instead of name

packages/jira-adapter/src/filters/assets/assets_object_type_path.ts, packages/jira-adapter/test/filters/assets/assets_object_type_path.test.ts
_add try catch to assetsObjectTypePath filter_
---
* add try catch to not fail the whole fetch as happened in [INCIDENT-20592](https://salto-io.atlassian.net/browse/INCIDENT-20592)
---
_None_
---
_None_
[INCIDENT-20592]: https://salto-io.atlassian.net/browse/INCIDENT-20592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SALTO-6368: add try catch to assetsObjectTypePath filter

packages/okta-adapter/src/reference_mapping.ts
Add reference from `UserSchema` to `Application`
---
I used context strategy cause the reference should only be created with `type = 'APP'`
This is a noisy change, will followup with noise reduction / prod ticket
---
- Add reference from UserSchema type to `Application` type
---
- `UserSchema` instances with properties sourced by external app will have `Application` reference added
=> SALTO-6400: Add reference from UserSchema properties sourced by apps to Application type (Okta)

packages/workato-adapter/src/config_creator.ts, packages/workato-adapter/test/config_creator.test.ts
Adjust Workato config object type 
---
We allow working with Workato in 2 modes - deploy support or impact analysis. each have implications on the adapter config, nacls structure, and more.
The object type should reflect this selection.
---
None
---
None
=> SALTO-6376: Adjust Workato config options type

packages/microsoft-entra-adapter/src/definitions/fetch/fetch.ts, packages/microsoft-entra-adapter/src/definitions/references.ts
Fix definitions for servicePrincipal - appRoleAssignments:
1. Define as standalone
2. Add reference definition
---
The `appRoleAssignments` defined on the Service Principal is supposed to be a standalone element (`isTopLevel: true` in the type definition) but this definition is missing on the paren't `fieldCustomization` field.
When reproducing this issue I also noticed that we're missing its reference definition as well.
---
_Microsoft Entra:_
* Fix issue with appRoleAssignments definition - set them as `standalone`
---
_Microsoft Entra:_
* Service Principal's `appRoleAssignments` instances will be added with references to the `appRole` + `resource`.
=> SALTO-6453: Add missing standalone definition for appRoleAssignments

packages/okta-adapter/src/change_validators/enabled_authenticators.ts, packages/okta-adapter/src/dependency_changers/authenticator_to_mfa_policy.ts, packages/okta-adapter/src/dependency_changers/index.ts, packages/okta-adapter/test/dependency_changers/authenticator_to_mfa_policy.test.ts
Add dependency changes to make sure MFA policies are deployed after their authenticators are activated
---
Each MFA policy has a list used authenticators. Authenticator must be activated before it can be assigned to MFA policy. 
The dependency changer is fixing a bug caused when trying to activate authenticator together with adding it to the MFA policy - in this case we must activate the authenticator before deploying the MFA policy changes.
In the next PR I'll add a validator to verify no inactive authenticator is added to mfa policy.
---
- Fix a bug in MultifactorEnrollmentPolicy when deployed with Authenticator
---
None
=> SALTO-6442: add dependency changer to allow deployment of MFA policy with authenticator

packages/jira-adapter/src/config/config.ts, packages/jira-adapter/src/fetch_criteria.ts, packages/jira-adapter/test/fetch_criteria.test.ts
_Enable the option to filter objects by `state` field in the fetch_
---
_None_
---
* Enable the option to filter objects by `state` field in the fetch
---
_None_
=> salto-6450: (JIRA) Enable state criteria in fetch

packages/adapter-components/src/client/http_client.ts, packages/adapter-components/src/client/http_connection.ts, packages/jira-adapter/src/filters/fields/field_deployment_filter.ts, packages/jira-adapter/test/filters/fields/field_deployment.test.ts
The upgrade of Axios created a problem with deploying a deletion of a custom field.
The problem is happening because of a change in the way it handle redirection (it is no longer automatically pass the auth headers).
---
_None_
---
Jira adapter:
* Fix custom fields deletion
---
_None_
=> SALTO-6447: (Jira) Fix custom fields deletion

packages/adapter-api/src/builtins.ts, packages/adapter-components/src/fetch/element/type_utils.ts, packages/adapter-components/test/fetch/element/element.test.ts
- when creating type from entries and definitions. If there are no entries contains fields that defined to be hidden in the definitions: 
- Create field with type `unknown` and `_hidden_value` annotation
- If field is defined as `serviceIdField` in `resource` definitions, mark it as `serviceId` field instead of `unknown`
---
---
- Fix hidden fields are written to the nacl after deploy of first instance from a type
---
None
=> SALTO-6357 fix serviceId is visible on target environment after deployment

packages/microsoft-entra-adapter/src/definitions/deploy/types.ts, packages/microsoft-entra-adapter/src/definitions/fetch/types.ts, packages/microsoft-entra-adapter/src/definitions/fetch/utils/adjust_expanded_members.ts, packages/microsoft-entra-adapter/src/definitions/fetch/utils/application.ts, packages/microsoft-entra-adapter/test/deploy/utils/app_role_assignment.test.ts, packages/microsoft-entra-adapter/test/deploy/utils/group_deployment_life_cycle_policy.test.ts, packages/microsoft-entra-adapter/test/fetch/utils/adjust_expanded_members.test.ts, packages/microsoft-entra-adapter/test/fetch/utils/application.test.ts, packages/microsoft-entra-adapter/test/filters/array_fields_deployment.test.ts
There's currently a regression where TS build is not failing on test files.
Until it's resolved I manually fixed build errors under `entra-adapter` package.
---
None
---
None
=> SALTO-6129: Manually fix Entra TS build errors

packages/jira-adapter/src/filters/script_runner/workflow/workflow_dc.ts, packages/jira-adapter/test/filters/script_runner/workflow/workflow_dc.test.ts
DC can have both script and path nulls. When it happens, we keep the null, and bad things happen
---
None
---
Jira Adapter:
* Fixed a scriptrunner bug that caused unwanted values in deployment
---
None
=> SALTO-6452: DC null scripts

packages/jira-adapter/src/filters/workflow/workflow_properties_filter.ts
See description
---
None
---
Jira Adapter:
* Removed a cv that warned about deployment of workflow transition's properties
---
None
=> SALTO-6441: remove cv for workflow transition properties

packages/salesforce-adapter/src/filters/centralize_tracking_info.ts, packages/salesforce-adapter/test/filters/centralize_tracking_info.test.ts, packages/salesforce-adapter/test/sfdx_parser/sfdx_dump.test.ts
Avoid setting history tracking on fields if the feature is disabled on the object This was already the behavior when adding objects, but the behavior when adding / modifying fields was different
---
---
_None_
---
_None_
=> SALTO-6457: Inconsistent beahvior on field tracking history in deploy filter

packages/salesforce-adapter/src/client/client.ts
Log all records as part of bulkLoadOperation
---
The previous log only outputted the first 100 Records.
---
- Improved trace log of bulkLoadOperation to output all the records.
---
_None_
=> SALTO-6455: (Salesforce) Log all records as part of bulkLoadOperation

.circleci/scripts/find_changed_packages.js
This fixes a bug in the find_changed_packages script that caused it to not run e2e for dependant packages It would only run it for the current package.
---
Seems like a regression from the node18 commit.
The code in `generateDependencyMapping` is built with the assumption that the keys of `workspaceInfo` is the same thing that is in the array of `workspaceDependencies` (see line 48 in particular).
the info in `workspaceDependencies` is the package location, whereas the previous code had the package name is the key in `workspaceInfo`, so we didn't get any dependency calculation...
---
_None_
---
_None_
=> SALTO-6463: run e2e for dependant packages

packages/vscode/scripts/package.sh
Fix the package.sh script to put all the required dependencies in the right paths
---
There was a missing trailing `/` in the `rsync` command which made it create the node modules folder under `extension/node_modules/node_modules`
Also, since we are dealing with a monorepo and the salto-io packages are there with a symbolic link, they would get excluded from the zip, so added a separate step to copy all the salto-io pacakges.
---
_None_
---
_None_
=> SALTO-6261: include all required node_modules in vscode package

packages/adapter-utils/src/element.ts, packages/okta-adapter/src/change_validators/disabled_authenticators_in_mfa.ts, packages/okta-adapter/src/change_validators/index.ts, packages/okta-adapter/src/user_config.ts, packages/okta-adapter/test/change_validators/disabled_authenticators_in_mfa.test.ts
Add change validator to block deployments of `MultifactorEnrollmentPolicy` with disabled Authenticators 
---
This rebased on top of https://github.com/salto-io/salto/pull/6370
**Please only review the second commits**  
---
- Add validation to prevent deployment of MultifactorEnrollmentPolicy with disabled Authenticator
---
None
=> SALTO-6442: Validate all authenticators in MFA are enabled

packages/adapter-components/src/client/http_connection.ts, packages/adapter-components/test/client/http_connection.test.ts
In this PR I removed the HTTP errors that are thrown with the string `AxiosError` and are user visible.
---
---
---
=> SALTO-6419: Fix Axios error message

packages/jira-adapter/e2e_test/instances/cloud/jsm/request_type.ts, packages/jira-adapter/src/filters/layouts/issue_layout.ts, packages/jira-adapter/src/filters/layouts/layout_service_operations.ts, packages/jira-adapter/src/filters/layouts/layout_types.ts, packages/jira-adapter/src/filters/request_type.ts, packages/jira-adapter/src/reference_mapping.ts, packages/jira-adapter/test/filters/layouts/create_references_issue_layout.test.ts, packages/jira-adapter/test/filters/layouts/issue_layout.test.ts, packages/jira-adapter/test/filters/request_type.test.ts
In this PR I support fetching and deploying development field in issue Layout
---
1. As we can see in the gira response we get from jira - there are two types of fields: `FIELD` and `PANEL`. 
Currently we supported only fields of type `FIELD` and I expended it to support also `PANEL` fields.  
---
* [SALTO-6421](https://salto-io.atlassian.net/browse/SALTO-6421): Now support fetching and deploying development field in issueLayout. 
---
* One or more fields of type `PANEL` will be added to the issueLayout type. 
[SALTO-6421]: https://salto-io.atlassian.net/browse/SALTO-6421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SALTO-6421: Support Development Field In Issue Layout

packages/microsoft-entra-adapter/src/definitions/deploy/deploy.ts, packages/microsoft-entra-adapter/src/definitions/deploy/utils/app_role.ts, packages/microsoft-entra-adapter/src/filters/app_role.ts, packages/microsoft-entra-adapter/test/deploy/utils/app_role.test.ts, packages/microsoft-entra-adapter/test/filters/app_role.test.ts, packages/microsoft-entra-adapter/test/mocks.ts
1. On `application` addition - copy the `appId` from the response.
2. On `appRole` addition - generate internal id directly on the changes.
---
1. The `Service Principal` addition requires its corresponding `appId`, which is hidden on the `Application` instance.
We don't copy it automatically from the response, since it's not a serviceId, so when attempting to add the `Service Principal` right after adding the `Application` we can't resolve the `appId` ref.
When fixing it I found out that the `copyFromResponse` flow works on the original change, which means I had to adjust the `app_role` filter to not create a new `Application` change with the `appRole` field, but rather modify it in-place. 
2. In a similar way - when adding an instance that depends on an `appRole` - we have to get its …
=> SALTO-6378: Fix - combined addition of Application and its Service Principal fails

packages/microsoft-entra-adapter/src/definitions/fetch/fetch.ts
We discovered potential collisions with the elemIDs of `OAuth2PermissionGrant` instances when the `consentType` is `Principal` and the same permission is granted to different users. To address this, we've chosen to filter out these permissions in the request, as we currently don't manage users at all.
---
_Microsoft Entra:_
* Filter out `OAuth2PermissionGrant` instances that grant permissions to specific users.
---
_Microsoft Entra:_
* Filter out `OAuth2PermissionGrant` instances that grant permissions to specific users.
* Modify the elemID of `OAuth2PermissionGrant` by removing `consentType` from it.
=> SALTO-6462: Fetch only OAuth2 Permission Grants for all users

packages/core/src/core/fetch.ts
For some reason the following error occurred - `TypeError: actualStaticFile.isEqual is not a function` . This is a quick fix that should make sure that we're dealing with a `StaticFile`, and not other empty or non empty object.
---
---
Core:
- Fix `actualStaticFile.isEqual` error
---
None
=> Fix actualStaticFile.isEqual error

packages/jira-adapter/src/change_validators/field_contexts/assets_object_field_configuration_aql.ts, packages/jira-adapter/test/change_validators/field_contexts/assets_object_field_configuration_aql.test.ts
In this PR I fixed `assetsObjectFieldConfigurationAqlValidator`
---
There's an issue with the assetsObjectFieldConfigurationAqlValidator.
When we add both the context and its field parent, the field parent doesn't have an id attribute at this stage. However, we're trying to access this attribute, which leads to the undefined error.
For field and context additions we will add a general action item instead of specific URL.
I also validated that there is valid parent. 
---
* Fixed Bug in `assetsObjectFieldConfigurationAqlValidator` when we are reading startsWith of an undefined object. 
---
None
=> SALTO-6468: Fix assetsObjectFieldConfigurationAqlValidator

packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/change_validators/workflowsV2/missing_extensions_transition_rules.ts, packages/jira-adapter/src/common/workflow/transitions.ts, packages/jira-adapter/src/filters/script_runner/workflow/workflow_references.ts, packages/jira-adapter/src/filters/workflowV2/status_properties_references.ts, packages/jira-adapter/src/fix_elements/remove_missing_extension_transition_rules.ts, packages/jira-adapter/src/references/workflow_properties.ts, packages/jira-adapter/test/filters/workflowV2/workflow_properties.test.ts
Added support for JSM workflow approvals
---
Changed a common file name and added a function to it.
It can be tested on a JSM instance.
Noise reduction will be added
---
Jira Adapter:
* Added support for JSM workflow approvals
---
None
=> SALTO-6451: Support JSM workflow approvals

packages/microsoft-entra-adapter/src/definitions/fetch/fetch.ts
When the domain is federated, we receive the following error from the service:
```
[microsoft_entra] Error caught while fetching domain__domainNameReferences: {"response":{"status":400,"data":{"error":{"code":"Request_UnsupportedQuery","message":"This API is not supported for federated domains."}}}
```
Therefore, we should avoid receiving this error by requesting the domain name references only if the domain is not federated.
---
None
---
None
=> SALTO-6460: Don't fetch domainNameReferences in case the domain is Federated

packages/jira-adapter/src/change_validators/index.ts, packages/jira-adapter/src/change_validators/projects/project_assignee_type.ts, packages/jira-adapter/src/config/config.ts, packages/jira-adapter/src/constants.ts, packages/jira-adapter/src/filters/project.ts, packages/jira-adapter/test/change_validators/projects/project_assignee_type.test.ts, packages/jira-adapter/test/filters/project.test.ts
Added assignee type to projects with an additional API call
---
With the old infra of swagger, adding it with the API config will require too much 
It was done on top of Seggev's PR with its comments https://github.com/salto-io/salto/pull/6386
---
Jira Adapter:
* added support for assignee type in projects
---
Jira Adapter:
* projects will be added with assignee type
=> SALTO-5912: Support Assignee Type

packages/salesforce-adapter/src/filters/topics_for_objects.ts, packages/salesforce-adapter/test/filters/topics_for_objects.test.ts
Change behavior of topics for objects filter to be more consistent - avoid creating topics instances if they are not enabled or changed
---
Not sure if the correct way to make this consistent is to actually always create the instance, but making this change felt less risky since it will not affect most scenarios
Tested manually with:
- Adding a new object with topics (unspecified, disabled, enabled)
- Updating topics on existing object
- From true to false
- From true to undefined
- From undefined to false
- From false to true
---
_None_
---
_None_
=> SALTO-6456: avoid creating disabled topics instance when not needed

packages/zendesk-adapter/src/filters/unordered_lists.ts, packages/zendesk-adapter/test/filters/unordered_lists.test.ts
Add ticket form restricted_brand_ids sorting
---
---
* Ticket form `restricted_brand_ids` are now sorted, as these cannot be updated by users.
---
* Ticket form `restricted_brand_ids` are now sorted, as these cannot be updated by users.
=> SALTO-6265 Add ticket form restricted_brand_ids sorting

packages/zendesk-adapter/src/filters/unordered_lists.ts, packages/zendesk-adapter/test/filters/unordered_lists.test.ts
Add selected macros restriction ids sorting
---
---
* Workspace selected macros restriction ids are now sorted, as these cannot be updated by users.
---
* Workspace selected macros restriction ids are now sorted, as these cannot be updated by users.
=> SALTO-6269 Add selected macros restriction ids sorting

packages/salesforce-adapter/src/filters/flows_filter.ts
In order to deactivate a `Flow` instance, we create a `FlowDefinition` instance with `activeVersionNumber` of 0. We do it by getting the `FlowDefinition` type from the `elementsSource` and create the instance with that type. The problem was that the type's fields weren't resolved, so while running `transformElement` on the `FlowDefinition` instance we got the following error- `Can not resolve value of reference with ElemID serviceid without elementsSource because value does not exist`.
The solution is to resolve the `FieldDefinition` type's fields & annotations when we get it from the `elementsSource`.
---
---
Salesforce:
- Fix the "Can not resolve ..." error on `Flow` deactivation changes.
---
None
=> SALTO-5891 Resolve the FlowDefinition type in preDeploy

packages/microsoft-entra-adapter/src/definitions/fetch/constants.ts, packages/microsoft-entra-adapter/src/definitions/fetch/fetch.ts
We defined the group lifecycle policy as dependent on the lifecycle policy to perform a conditional request. However, setting a sub-resource as dependent on another resource, which is not its parent, is not supported. Instead, we should define the parent as dependent on whatever we need and use the conditions under the recurseInto definition.
---
_Microsoft Entra:_
* Fix dependsOn definition for groupLifeCyclePolicy
---
_Microsoft Entra:_
* groupLifeCyclePolicy will now be referenced from the group to which it applies.
=> SALTO-6470: Fix dependsOn definition for groupLifeCyclePolicy

packages/okta-adapter/e2e_test/adapter.test.ts, packages/okta-adapter/e2e_test/mock_elements.ts, packages/okta-adapter/src/adapter.ts, packages/okta-adapter/src/change_validators/index.ts, packages/okta-adapter/src/change_validators/oidc_idp.ts, packages/okta-adapter/src/client/client.ts, packages/okta-adapter/src/constants.ts, packages/okta-adapter/src/definitions/deploy/deploy.ts, packages/okta-adapter/src/definitions/deploy/utils/simple_status.ts, packages/okta-adapter/src/definitions/fetch/fetch.ts, packages/okta-adapter/src/definitions/requests/clients.ts, packages/okta-adapter/src/filters/field_references.ts, packages/okta-adapter/src/reference_mapping.ts, packages/okta-adapter/src/user_config.ts, packages/okta-adapter/test/change_validators/oidc_idp.test.ts, packages/okta-adapter/test/client/client.test.ts, packages/okta-adapter/test/definitions/deploy/utils/simple_status.test.ts
Added support for Identity Provider type.
---
In order to support deployment of Identity Provider type, I made the following changes - 
- Add non secret fields that are required for deployment to Identity Provider type
- Added support in `JsonWebKey` type, that can be referenced from Identity Provider and must be added when adding a SAML IdentityProvider (only additions and removals are supported)
- Added a migration to the okta.nacl file to exclude `JsonWebKey` in order to reduce noise for existing environments
- Used @Nurdok's generalization utilities to handle additions / modifications with status changes (originally added here - https://github.com/salto-io/salto/pull/6348)
- Change validator to avoid deploying OIDC Identity Providers in scenarios that …
=> SALTO-6048: Add Identity Provider deploy support (Okta)

packages/adapter-components/src/fetch/element/element.ts, packages/adapter-components/test/fetch/element/element.test.ts
adding log tags 
---
---
None
---
None
=> SALTO-6319: add log tags to failed types error

packages/jira-adapter/src/filters/account_id/user_id_filter.ts, packages/jira-adapter/test/filters/account_id/user_id_filter.test.ts
The deployment of project components with lead ID did not work- we send the id but we need to send the user name
---
None
---
Jira Adapter:
* Fixed a bug that prevented deployment of components with lead ID in dc
---
None
=> SALTO-6478: deploy dc component with lead id

packages/adapter-api/src/values.ts, packages/adapter-utils/src/list_comparison.ts, packages/adapter-utils/test/compare.test.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts, packages/zendesk-adapter/src/filters/guide_service_url.ts, packages/zendesk-adapter/test/filters/guide_service_url.test.ts
`isPrimitiveValue` returns true for `null`, `undefined`, but those weren't part of the the `PrimitiveValue` type.
---
---
Core:
- List items comparison will not throw when there's `null` / `undefined` in an item.
---
None
=> SALTO-6479 Fix PrimitiveValue type to include null & undefined

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts, packages/salesforce-adapter/src/filters/flow_coordinates.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/flow_coordinates.test.ts
When flows are in auto-layout mode, the coordinates of their components are meaningless, yet when they change they cause many diffs in deployments.
This PR removes these coordinate values and re-adds them as 0 for deployment (since they are required)
---
Testing: 
- Fetch a flow in auto-layout mode. Observe the fields not being present in the NaCl files.
- Deploy a flow with no coordinate fields. Observe a successful deployment. Observe no coordinate fields in the NaCl file post-deploy.
---
Salesforce: coordinate fields of flow components that belong to a flow with AUTO_LAYOUT_CANVAS mode are now removed.
---
Salesforce: coordinate fields of flow components that belong to a flow with AUTO_LAYOUT_CANVAS mode are now removed.
=> SALTO-5917 - Salesforce: remove coordinate fields from auto-layout flows

packages/jira-adapter/src/reference_mapping.ts
Following a change in the service, the group references are now IDs instead of names. Keeping both in case they revert
---
[Noise reduction](https://github.com/salto-io/salto_private/pull/9118)
None
---
Jira Adapter:
* Support Atlassian change in automation's email recipients from group name to group id
---
Jira Adapter:
* Automations with email group recipients will return to be references
=> SALTO-6490: support group references change in automations

packages/okta-adapter/src/definitions/fetch/fetch.ts, packages/okta-adapter/src/definitions/fetch/types/email_domain.ts, packages/okta-adapter/test/definitions/fetch/types/email_domain.test.ts
This PR fixes a bug when fetching EmailDomain instances:
When deleting an email domain through the UI, the API still returns it, but with `validationStatus = "DELETED"`.
When recreating the same email domain through the UI (same email address and sender name), the API will now return two entries with the same details (one `DELETED` and one not)
When Salto performs a fetch, we get
```
Error merging okta.EmailDomain.instance.Team_Rachum@s: duplicate key <somekey>
[..]
dropped elements: okta.EmailDomain.instance.Team_Rachum@s
```
We solve this by omitting entries with DELETED status on fetch.
---
---
Fixed a bug where email domains are dropped after being deleted and recreated, by omitting all currently-deleted email domains …
=> SALTO-5984: Okta: Omit `EmailDomain` instances marked as `DELETED`

packages/okta-adapter/src/definitions/fetch/fetch.ts
Okta returns 401 on `/api/v1/mappings` when the feature is not enabled in the account.
This PR create config suggestion to exclude this type when getting 401.
---
---
- Exclude `ProfileMapping` type from Salto when the type is not enabled in the Okta account.
---
None
=> SALTO-6404: Exclude ProfileMapping when the feature is not enabled

packages/jira-adapter/src/change_validators/field_configuration/field_configuration_description_length.ts, packages/jira-adapter/test/change_validators/field_configuration/field_configuration_description_length.test.ts
_fix fieldConfigurationDescriptionLengthValidator bug_
---
* the bug is that the validator fails when there is no description
---
_None_
---
_None_
=> SALTO-6492: fix fieldConfigurationDescriptionLengthValidator bug

packages/adapter-utils/index.ts, packages/adapter-utils/src/list_comparison.ts, packages/core/src/core/fetch.ts, packages/core/src/core/flags.ts, packages/core/src/core/merge_content.ts, packages/core/test/core/fetch.test.ts, packages/core/test/core/merge_content.test.ts
Try auto merging lists, by replacing each list item with its hash and running the `diff3` algorithm on the hashed list, then mapping the items back in the merged list.
This can be disabled using the `SALTO_AUTO_MERGE_LISTS_DISABLE` env var.
---
---
Core:
- Support auto-merge for lists
---
None
=> SALTO-5323 Support auto-merge for lists

packages/adapter-components/src/definitions/system/index.ts, packages/okta-adapter/e2e_test/adapter.ts, packages/okta-adapter/src/adapter.ts, packages/okta-adapter/src/adapter_creator.ts
Allow to override definitions in Okta using SALTO_DEFINITIONS_OVERRIDES env var
---
---
None
---
None
=> SALTO-6496: Add definitions override in Okta

packages/netsuite-adapter/src/constants.ts, packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts, packages/netsuite-adapter/src/data_elements/types.ts, packages/netsuite-adapter/src/filters/workflow_account_specific_values.ts, packages/netsuite-adapter/test/data_elements/suiteql_table_elements.test.ts
Add mapping between missing type internal ids (from the `selectrecordtype` field) and their SuiteQL tables.
This PR is rebased on https://github.com/salto-io/salto/pull/6311 .
---
---
- Recognize more types for ASVs 
---
- unresolved `[ACCOUNT_SPECIFIC_VALUE]` values may be resolved
=>  SALTO-2392 recognize more types for ASVs 

packages/netsuite-adapter/src/filters/workflow_account_specific_values.ts, packages/netsuite-adapter/test/filters/workflow_account_specific_values.test.ts
Improve the condition formula parsing for resolving ASVs in workflows:
1. extract only non-zero integers as internal ids.
2. deal with formulas that have the same param/s more than once.
---
---
- Improve condition formula parsing for ASVs
---
- unresolved `[ACCOUNT_SPECIFIC_VALUE]` values may be resolved
=> SALTO-2392 Improve condition formula parsing for ASVs

packages/salesforce-adapter/src/filters/standard_value_sets.ts, packages/salesforce-adapter/test/filters/standard_value_sets.test.ts
Currently we only omit the value set name annotation on field modification This extends this behavior to field addition and to all fields inside an object addition
---
These new scenarios can't really happen in a real deployment (we cannot deploy a standard object / new standard field) but they can happen in a "dumpElementsToFolder" flow 
Manual tests:
- Tested setting / removing description on a standard picklist field (Account.Type), checked the change is deployed, the nacl does not change and there are no pending changes after the deploy 
---
_None_
---
_None_
=> SALTO-6472: Omit value set name annotation on object / field addition

packages/salesforce-adapter/config_doc.md, packages/salesforce-adapter/src/change_validator.ts, packages/salesforce-adapter/src/change_validators/custom_field_type.ts, packages/salesforce-adapter/src/client/types.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/custom_objects_to_object_type.ts, packages/salesforce-adapter/src/filters/utils.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/change_validators/custom_field_type.test.ts, packages/salesforce-adapter/test/filters/custom_objects_to_object_type.test.ts, packages/salesforce-adapter/test/filters/utils.test.ts
The metadata API technically supports deploying fields with unknown type if the type was already unknown This change:
- Removes the change validator that would prevent modifying existing fields with unknown type
- Moves the logic of putting an error on unknown field types to the custom_field_type validator to avoid having double warnings
- Fixes the deployment code / filters to not explicitly specify the field type when it is unknown
---
Manually tested with:
- Deploying a new object with a field that has an unknown type (the field with the unknown type is not deployed, deployment succeeds)
- Adding a field with an unknown type (gets change validation error)
- Modifying a field with an unknown type (adding a "description") - works
--- …
=> SALTO-6473: Support changing fields with unknown type

packages/netsuite-adapter/src/filters/workflow_account_specific_values.ts
An error was thrown because we ran `string.find()` instead of `string[].find()`.
---
---
- Fix bug in workflow ASV resolving
---
None
=> SALTO-2392 Fix bug in workflow ASV resolving

packages/jira-adapter/src/change_validators/account_id.ts, packages/jira-adapter/src/change_validators/adding_jsm_project.ts, packages/jira-adapter/src/change_validators/assets/label_attribute_removal.ts, packages/jira-adapter/src/change_validators/automation/automations.ts, packages/jira-adapter/src/change_validators/dashboard_gadgets.ts, packages/jira-adapter/src/change_validators/default_addition_queue.ts, packages/jira-adapter/src/change_validators/field_contexts/second_global_context.ts, packages/jira-adapter/src/change_validators/issue_type_hierarchy.ts, packages/jira-adapter/src/change_validators/last_queue.ts, packages/jira-adapter/src/change_validators/permission_type.ts, packages/jira-adapter/src/change_validators/projects/project_deletion.ts, packages/jira-adapter/src/change_validators/workflows/workflow_scheme_dups.ts, packages/jira-adapter/src/change_validators/workflowsV2/referenced_workflow_deletion.ts, packages/jira-adapter/src/change_validators/wrong_user_permission_scheme.ts, packages/jira-adapter/src/config/config.ts, packages/jira-adapter/test/change_validators/automations/automations.test.ts, packages/jira-adapter/test/change_validators/dashboard_gadgets.test.ts, packages/jira-adapter/test/change_validators/default_addition_queue.test.ts, packages/jira-adapter/test/change_validators/permission_type.test.ts, packages/jira-adapter/test/change_validators/workflows/workflow_scheme_dups.test.ts, packages/jira-adapter/test/change_validators/workflowsV2/referenced_workflow_deletion.test.ts, packages/jira-adapter/test/change_validators/wrong_user_permission_scheme.test.ts
To optimize the time we spend on CVs, we need to first check if there is a relevant change before using the elementsSource to get instances.
Added some checks to many CVs.
---
None
---
Jira Adapter:
- check relevant changes before using elementsSource in CVs
---
_None_
=> SALTO-5949: (Jira) check relevant changes before using elementsSource in CVs

packages/adapter-components/src/client/http_client.ts
we should only log the extracted headers
seems this was added in https://github.com/salto-io/salto/pull/5614/files#diff-6208129eee6ab17f3e8123438554138652e9750654f5af9a6903d8e07b8adf16R303 (and I missed it in the review)
---
None
---
None
=> SALTO-6501 use extractHeaders in error log

packages/salesforce-adapter/src/config_creator.ts, packages/salesforce-adapter/src/types.ts
See title
---
---
_Salesforce adapter_:
- `ManagedEventSubscription` is now excluded by default for new accounts.
---
None
=> SALTO-5893: Salesforce: Exclude `ManagedEventSubscription` by default

packages/adapter-components/src/deployment/change_validators/index.ts, packages/adapter-components/src/deployment/change_validators/unique_fields.ts, packages/adapter-components/test/deployment/change_validators/unique_fields.test.ts, packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/utils.test.ts, packages/jira-adapter/src/change_validators/index.ts
Change the unique fields CV to support uniqueness in different scopes.
We will support global and parent scopes.
Added types that need the parent scope check in Jira.
---
_None_
---
_Adapter Components:_
* Added a scope option in the unique fields CV
* Check unique names in SLAs and field contexts
---
_None_
=> SALTO-6424: (Jira) Support unique field checks within parent scope

packages/adapter-components/src/definitions/system/shared/transformation.ts, packages/adapter-components/src/fetch/utils.ts, packages/adapter-components/test/fetch/utils.test.ts
Add `rename` capability to the transformation definitions.
Adding it before setting the `root`, so that it will be possible to nest neighboring fields under the field that is going to be used as the root.
---
None
---
None
=> SALTO-6509 Add rename capability to transformation definitions

packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/utils.test.ts, packages/jira-adapter/e2e_test/adapter.test.ts
_Added getParentAsync to adapter utils and fixed Jira e2e_
---
---
* added getParentAsync to adapter utils and fixed Jira e2e
---
_None_
=> SALTO-5932: added getParentAsync to adapter utils and fixed Jira e2e

packages/okta-adapter/src/constants.ts, packages/okta-adapter/src/definitions/fetch/fetch.ts
The type shouldn't be fetched if the account is a classic engine
---
---
None
---
None
=> SALTO-6519: Add embeddedSignInSupport to classic engine exclude list

packages/confluence-adapter/src/definitions/fetch/fetch.ts
---
---
- stop fetching templates for archived spaces
---
None
=> SALTO-6505 stop fetching templates for archived spaces

packages/salesforce-adapter/src/change_validator.ts, packages/salesforce-adapter/src/change_validators/managed_apex_component.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/change_validators/managed_apex_components.test.ts
Salesforce Managed Apex Components Change Validator
---
Here's how the Error looks like:
---
- Implemented a Change Validator that forbids deploying Apex Components with `hidden` content (managed).
---
_None_
=> SALTO-6507: Salesforce Managed Apex Components Change Validator

packages/workspace/src/workspace/workspace.ts
Added some logs for visibility to understand why we get out of memory error
---
Also replaced `...` with concat as a first attempt to resolve the issue
---
None
---
None
=> SALTO-6503: Add logs for visibility to `validateElementsAndDependents`

packages/salesforce-adapter/src/filters/custom_object_instances_references.ts
Add logs on omitted instances warnings in Salesforce Data Fetch
---
This should help us troubleshoot issues.
---
_None_
---
_None_
=> SALTO-6531: Add logs on omitted instances warnings in Salesforce Data Fetch

packages/adapter-components/src/client/http_client.ts, packages/adapter-components/src/client/logging_utils.ts, packages/adapter-components/src/definitions/user/client_config.ts, packages/adapter-components/test/client/logging_utils.test.ts, packages/adapter-components/test/definitions/user/client_config.test.ts, packages/adapter-utils/src/utils.ts, packages/okta-adapter/src/client/client.ts, packages/zendesk-adapter/src/client/client.ts
Add some controls for truncating/omitting the full response logs (can extend later as needed, e.g. more granular control on truncating / better buckets by pattern).
This was added as part of the user-facing config for simplicity, but does not have a user-facing default.
Default behavior: responses over ~10kb will be truncated.
---
Also consolidated some code duplication (that missed past cleanups) from the zendesk and okta adapters.
---
None
---
None
=> SALTO-6481 Allow controlling how full responses are logged

packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts, packages/netsuite-adapter/src/client/suiteapp_client/types.ts, packages/netsuite-adapter/test/client/suiteapp_client/suiteapp_client.test.ts
regenerate the auth header on each axios request in a way that we’ll regenerate it also when the axios-retry mechanism makes the next request (and we’re not getting to call `axiosClient.post` again).
this should prevent us from getting `401 unauthorized` on a second request after the first request failed with `429 concurrency limit reached`.
---
---
- Prevent getting  "Invalid login attempt" after a delayed request (e.g. due to concurrency limit)
---
None
=> SALTO-6539 regenerate auth header inside the axios request

packages/adapter-components/src/fetch/errors.ts, packages/adapter-components/test/fetch/errors.test.ts, packages/jamf-adapter/src/definitions/fetch/fetch.ts, packages/okta-adapter/src/definitions/fetch/fetch.ts, packages/zendesk-adapter/src/definitions/fetch/fetch.ts
- Change `getInsufficientPermissionsError` to `createGetInsufficientPermissionsErrorFunction` with the same logic but able to get a list of statuses.
- Use `createGetInsufficientPermissionsErrorFunction` in Jamf for statuses [401, 403]
---
---
- Convert error to Unauthorized error for statuses 401 and 403 
---
- Convert error to Unauthorized error for statuses 401 and 403
=> SALTO-6513 Convert error to Unauthorized error for statuses 401 and 403 (WIP)

packages/jira-adapter/src/dependency_changers/index.ts, packages/jira-adapter/src/dependency_changers/object_type_order_to_schema.ts, packages/jira-adapter/test/dependency_changers/object_type_order_to_schema.test.ts
In this PR I removed the dependencies between objectTypeOrder and objectSchema in removal
---
Context can be found in [SALTO-6543](https://salto-io.atlassian.net/browse/SALTO-6543).
---
* Fixed a bug caused by circular dependency between root `ObjectType`, `ObjectTypeOrder` and `ObjectSchema`.
---
None
[SALTO-6543]: https://salto-io.atlassian.net/browse/SALTO-6543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SALTO-6543: Remove dependencies between objectTypeOrder and objectSchema in removal

build_utils/create_version_pr.sh
fix for https://github.com/salto-io/salto/pull/6302 since the yarn lockfile is mutated as part of version bumps
---
None
---
None
=> SALTO-6350 remove --immutable flag from yarn in version script

packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts, packages/salesforce-adapter/src/filters/custom_object_instances_references.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/custom_object_instances_references.test.ts
Improve Data Instances References behavior.
---
Implemented as optional feature for a gradual rollout. (`improvedDataBrokenReferences`)
Workspace Diff when feature is enabled: https://github.com/salto-io/tamir-sf/commit/806650b66b5c587cc64cf84cb09aa0f418b55bf7
When the `ReferenceBehavior` is not `ExcludeInstance`, instances that were referencing an invalid instance, would be omitted altogether, regardless to the defined reference behavior.
---
_None_
---
_None_
=> SALTO-6544: Improve Data Instances References behavior

packages/adapter-components/src/deployment/filtering.ts, packages/adapter-components/test/deployment/filtering.test.ts, packages/okta-adapter/src/definitions/deploy/deploy.ts
The current implementation of transformRemovedValuesToNull recurses into subfields when a deleted field is an object, and it only transforms the lowest-level fields to null. In some cases, we want to allow the top-level deleted field to be set to null without including its subfields.
---
---
=> SALTO-6550: Allow transforming removed object fields to null

packages/adapter-components/src/deployment/filtering.ts, packages/adapter-components/test/deployment/filtering.test.ts
The existing utility `transformRemovedValuesToNull` sets the removed fields to null in-place. This means that once the deployment succeeds, these null changes will appear in the workspace, which is not supposed to happen.
---
To fix this, we simply modify a clone of the change, rather than the original one.
---
---
=> SALTO-6551: Fix - transforming removed values to null creates side effects in the workspace

packages/salesforce-adapter/src/filters/custom_object_instances_references.ts, packages/salesforce-adapter/test/filters/custom_object_instances_references.test.ts
Salesforce customObjectInstanceReferencesFilter fails on Cannot read properties of null (reading 'slice')
---
This is an edge-case where the Lookup field has either no `referenceTo` annotation or multiple `referenceTo` annotations, but the value of the Lookup is not a string. (null is possible for optional Lookup Field).
I simply validate the value of the reference field is a string as part of the transform function.
---
_None_
---
_None_
=> SALTO-6556: Salesforce customObjectInstanceReferencesFilter fails on Cannot read properties of null (reading 'slice')

packages/jira-adapter/src/config/config.ts
See context in the ticket - truncate/omit full logs for heavy hitter endpoints
---
None
---
None
=> SALTO-6481 adjust default rules for jira

packages/salesforce-adapter/src/filters/author_information/custom_objects.ts, packages/salesforce-adapter/src/filters/author_information/sharing_rules.ts
Improve Salesforce warning logs that print [object Object]
---
_None_
---
_None_
=> SALTO-6559: Improve Salesforce warning logs that print [object Object]

packages/cli/e2e_test/helpers/jest_matchers.ts, packages/cli/e2e_test/multi_env.test.ts
Before this change, when the test failed due to a plan that was not as expected we would only know the size was wrong and we would not get the actual changes
Added toBeEmptyPlan custom matcher to allow tests to verify if a plan is empty in a way that will print the plan if it is not as expected
---
example output from a failed run on this PR can be found [here](https://app.circleci.com/pipelines/github/salto-io/salto/28870/workflows/3bd88849-dd32-43fe-9194-3a8626e89c06/jobs/293152/parallel-runs/0/steps/0-106) (search for "empty plan" in the output)
---
_None_
---
_None_
=> SALTO-6549: Output plan from test when it does not match expected plan

packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts
If there are no items to query using "anyof" filter in saved search- return empty result.
---
---
None
---
None
=> Fix saved search query filters

packages/jira-adapter/src/filters/automation/automation_fetch.ts, packages/jira-adapter/src/filters/automation/automation_structure.ts, packages/jira-adapter/test/filters/automation/automation_fetch.test.ts
_fix Jira DC ruleScope bug_
---
* `convertRuleScopeValueToProjects` function was meant to be used in Cloud only but we were using it DC as well
---
---
=> SALTO-6512: fix Jira DC ruleScope bug

packages/okta-adapter/src/definitions/deploy/deploy.ts, packages/okta-adapter/src/reference_mapping.ts
Adde deploy support for `OAuth2Scope` type, and a missing ref from ` AuthorizationServerPolicyRule` to `OAuth2Scope`
---
will add tests & noise reduction later
---
- Support deployment of Authorization Server scopes 
- Fix a bug in deployment of Authorization Server Policy Rules that references scopes
---
- Reference will be added in Authorization Server Policy Rule that references Auth Scopes
=> SALTO-6577: support OAuth server scopes

packages/okta-adapter/e2e_test/adapter.test.ts, packages/okta-adapter/src/definitions/deploy/deploy.ts, packages/okta-adapter/src/definitions/fetch/types/application.ts, packages/okta-adapter/src/filters/app_fetch.ts, packages/okta-adapter/test/definitions/fetch/types/application.test.ts
Our current custom app logic didn't take into account domain changes, this PR fixes this
---
When the subdomain of the tenant changes, apps created before the changes will keep the name of the original domain and will not get updated. This leads to cases when we false detect certain apps as non custom, though they actually are.
This PR introduces a new logic to determine if an app is custom - 
1. If the OrgSetting type exist, we will use the domain
2. If there's no match, we will use the tenant_appName_number pattern to detect it
---
- Fix a bug in the deployment of custom apps when subdomain has changed.
---
- Name field will be removed for custom SAML and AUTO_LOGIN applications.
=> SALTO-6531: Change custom name logic in Okta to be less strict

packages/workspace/src/expressions.ts
On `getClonedElements` in `workspace` package, we are cloning the parent of each Field. This might cause an OOM error, we should first filter out duplications before cloning
---
---
_Core_:
- fix OOM error when cloning large amount of Fields
---
None
=> SALTO-6480 make sure there are no dups before cloning fields parent

packages/jira-adapter/src/filters/field_configuration/replace_field_configuration_references.ts, packages/jira-adapter/src/weak_references/field_configuration_items.ts, packages/jira-adapter/test/filters/field_configuration/replace_field_configuration_references.test.ts
In `getFieldConfigurationItemsReferences`:
1. I removed the usage of `joi` schema for `fields` in `FieldConfiguration` instances, because I suspected that it has memory/runtime implications, and we actually only care about the key of each field in `fields`
2. I reused the `elemIDs` of the `Field` instances, because there's no reason to create a new `ElemID` object in memory for each field in each fieldConfiguration instance, as all fieldConfiguration instances reference the same field instances (`ElemID` objects are immutable, so there's no problem sharing them).
Those improvements made it possible to run `salto workspace cache update` on a really large Jira environment - with more that 1M references of `Field` instances in `FieldConfiguration` instances.
---
_Additional context for …
=> Improve memory usage of custom references calculation in Jira

packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/test/workspace/multi_env/routers.test.ts
The change routing code would omit annotation values from fields when the field type changed. This is a hacky fix that does not really cover all cases, but should solve the most obvious ones at least
---
This issue was caught by the cli e2e, see ticket for more details on the scenario
---
Core:
- Fixed issue where fetch in "isolated" mode could potentially drop field attributes in some cases
---
_None_
=> SALTO-6549: Fix fetch isolated mode omitting field annotations

packages/netsuite-adapter/src/filters/workflow_account_specific_values.ts, packages/netsuite-adapter/test/filters/workflow_account_specific_values.test.ts
1. map `STDBODYDECISIONMAKER` & `STDBODYEMPLOYEE` to suiteql tables
2. fix `getTypesFromInternalId` to work when `typeInternalId` is in both `INTERNAL_ID_TO_TYPES` and `ADDITIONAL_INTERNAL_ID_TO_TYPES` 
3. fix `getParametersAccountSpecificValueToTransform` to consider param values that are referenes
---
---
- identify more ASVs
---
- unresolved `[ACCOUNT_SPECIFIC_VALUE]` values may be resolved
=> SALTO-2392 identify more ASVs

packages/adapter-utils/src/element_source.ts
_fix elementsSource has implementation_
---
* it is a fix for the change from this [pr](https://github.com/salto-io/salto/pull/6505). I changed `elementsSource.has` implementation to use `elementsSource.get` inside, which may cause performance issues.
---
_None_
---
_None_
=> SALTO-6592: fix elementsSource has implementation

packages/lowerdash/src/types.ts, packages/microsoft-security-adapter/src/constants/entra.ts, packages/microsoft-security-adapter/src/constants/intune.ts, packages/microsoft-security-adapter/test/adapter.test.ts
Change all Microsoft Security type names to PascalCase, following the discussion here
---
This was done following the discussion [here](https://github.com/salto-io/salto/pull/6456#discussion_r1727124764).
---
---
=> SALTO-6428: Change Microsoft Security type names to PascalCase

packages/google-workspace-adapter/e2e_test/adapter.test.ts
SALTO-6535 google workspace e2e - remove groups from deploy e2e temporarily 
---
---
---
=> SALTO-6535 google workspace e2e - remove groups from deploy e2e temporarily 

packages/cli/src/commands/adapter_format.ts, packages/cli/src/commands/index.ts, packages/cli/src/formatter.ts, packages/cli/src/prompts.ts, packages/cli/test/commands/adapter_format.test.ts, packages/core/src/core/adapter_format.ts, packages/core/test/core/adapter_format.test.ts
Add cli command to sync a salto workspace to an adapter format folder
---
---
Cli:
- Added cli command to sync a salto workspace to an adapter format folder
---
_None_
=> SALTO-6398: add sync-to-folder command

packages/adapter-api/src/comparison.ts, packages/core/src/core/plan/plan.ts, packages/workspace/src/workspace/elements_source.ts, packages/workspace/src/workspace/nacl_files/elements_cache.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/elements_source.test.ts
This avoids loading another copy of the elements from the state
It also avoids re-calculating the hidden parts for each such element
---
The main point of the change here is this:
There is code that needs to decide which elements to merge (dropStateOnlyElementsRecovery)
before this change, that code gets two iterators of elements, it needs to filter the second iterator such that it only contains elements that exist in the first iterator (by element ID) or elements that are fully hidden.
to implement the first condition, it has to fully consume the first iterator just to get the element IDs, so essentially it loads all the elements into memory.
In this PR we change the interface such that it works with iterators of element IDs and not full elements, this …
=> SALTO-6573: Avoid redundant read of elements when rebuilding cache

packages/jira-adapter/src/change_validators/field_contexts/field_context_options.ts, packages/jira-adapter/test/change_validators/field_contexts/field_context_options.test.ts
Check if there is a relevant order instance in the elementsSource when there is not a relevant order change.
---
None
---
* Check the existence of field context order when adding an option
---
_None_
=> SALTO-6588: (Jira) Check the existence of field context order when adding an option

packages/netsuite-adapter/config_doc.md, packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts, packages/netsuite-adapter/src/client/suiteapp_client/soap_client/types.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts, packages/netsuite-adapter/src/config/types.ts, packages/netsuite-adapter/src/config/validations.ts, packages/netsuite-adapter/test/client/suiteapp_client/soap_client/soap_client.test.ts, packages/netsuite-adapter/test/config/validations.test.ts
Allow users to config the SOAP WSDL version used by `SoapClient` - using the `suiteAppClient.wsdlVersion` adapter config.
---
---
- Allow users to config the SOAP WSDL version used by `SoapClient` - using the `suiteAppClient.wsdlVersion` adapter config
---
None
=> SALTO-6605 SOAP WSDL version config

packages/adapter-components/src/fetch/errors.ts, packages/zendesk-adapter/src/filters/brand_logo.ts, packages/zendesk-adapter/test/filters/brand_logo.test.ts
Until now, when we got 403 while trying to get brand logos, the entire fetch failed, we now convert it into a fetch warning, like we do to other types fetched with the infra.
---
---
_Zendesk_adapter_:
- Create fetch warning when failing to get brand logos due to insufficient permissions, instead of failing the entire fetch
---
None
=> SALTO-6614: Create fetch warning on Brand Logo 403

packages/jira-adapter/src/filters/assets/assets_object_field_configuration.ts, packages/jira-adapter/src/filters/fields/contexts.ts, packages/jira-adapter/src/filters/jql/jql_references.ts, packages/jira-adapter/test/filters/fields/assets_object_field_configuration.test.ts, packages/jira-adapter/test/filters/jql/jql_references.test.ts
_add elementsSource to assetObjectFieldConfiguration deployment_
---
* while working I found a bug in the jql filter - unresolved references were not resolved.
* fix a bug in the elementsSource that would not resolve references of not top-level instances.
---
_None_
---
_None_
=> SALTO-6552: add elementsSource to assetObjectFieldConfiguration deployment

packages/jira-adapter/src/config/config.ts, packages/jira-adapter/src/filters/automation/smart_values/smart_value_reference_filter.ts, packages/jira-adapter/test/filters/automation/smart_values/smart_value_reference_filter.test.ts
Added additional smart values parsing, under a flag so we can open it gradually.
---
- Added support for smart values under `operations` field
- Added support for nested smart values in `BRANCH` components
---
- Parse additional smart values in automations. To enable this feature add `parseAdditionalAutomationExpressions` config flag under the `fetch` section.
---
None
=> SALTO-6625: Parse additional smart values in automations

packages/okta-adapter/src/change_validators/everyone_group_assignments.ts, packages/okta-adapter/src/change_validators/index.ts, packages/okta-adapter/src/filters/group_members.ts, packages/okta-adapter/src/user_config.ts, packages/okta-adapter/test/change_validators/everyone_group_assignments.test.ts
Added a validator to block assignments to the "Everyone" Group in Okta as it is auto managed by Okta
---
- Added a validator
- Also fixed some logs as we were logging an error also when all assignments succeeded 
---
- Add a validator to block assignments to "Everyone" group in Okta
---
None
=> SALTO-6633: Everyone group assignment validator

packages/jamf-adapter/src/adapter_creator.ts, packages/jamf-adapter/src/config.ts, packages/jamf-adapter/src/constants.ts, packages/jamf-adapter/src/definitions/deploy/classic_api_utils.ts, packages/jamf-adapter/src/definitions/deploy/deploy.ts
We need to add some busy waiting after POST or DELETE api calls on Jamf classicAPI
Please see https://community.jamf.com/t5/jamf-pro/delay-time-after-post-or-delete-api-calls/m-p/323383/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufE0wM1dLNk4xNU4yMlBFfDMyMzM4M3xTVUJTQ1JJUFRJT05TfGhL#M278490
---
---
- Fix deployment fails when there are dependencies on creation or deletion
---
- Fix deployment fails when there are dependencies on creation or deletion
=> SALTO-6344 delay after creation or deletion on Jamf

packages/google-workspace-adapter/e2e_test/adapter.test.ts
SALTO-6535 change log level in google-workspace E2E
---
---
---
=> SALTO-6535 change log level in google-workspace E2E

packages/zendesk-adapter/src/filters/guide_themes/types.ts, packages/zendesk-adapter/test/filters/guide_themes/api/pollJobStatus.test.ts
Remove restriction on API response, as we've seen a `null` value instead of an object.
---
---
---
=> SALTO-6632 Remove API response restriction

packages/adapter-components/src/client/http_client.ts, packages/adapter-components/src/definitions/system/requests/types.ts, packages/adapter-components/src/fetch/resource/resource_manager.ts, packages/adapter-components/test/client/http_client.test.ts
* Add an option to omit empty query args - which will allow unsetting values more easily when placeholders are defined (this still won't cover everything - we can later add conditions on fetch requests as well)
* Reverse order of precedence between initial context and overrides received from recurseInto args, to allow self-recursion
---
None
---
None
=> Allow ignoring empty query args, fix precedence during recursion

packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/state/in_mem.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
Add a heuristic to recognize (and stop) deletion of static files with multiple pointers.
---
---
---
=> SALTO-5558 SALTO-954 Multiple pointers to static file

packages/cli/src/command_builder.ts, packages/cli/src/commands/account.ts, packages/cli/src/commands/adapter_format.ts, packages/cli/src/commands/element.ts, packages/cli/src/commands/env.ts
---
This was mildly annoying that I couldn't run `salto element print` when I tried to debug something...
---
Cli:
- Enable running commands that do not change the workspace while other commands are running
---
_None_
=> SALTO-6618: Avoid using persistent workspace for read only commands

packages/core/src/core/adapter_format.ts, packages/core/test/core/adapter_format.test.ts
Add a new function `dumpElementsToFolder` which updates a “hybrid” folder - a folder containing a Salto workspace and an SFDX project.
It will get the changes to apply, it will call `dumpElementsToFolder` to update the SFDX part. And in the future, it should use the leftover changes to the Salto workspace
Additional context for the reviewer
No release notes
Release Notes:
None
User Notifications:
None
=> SAAS-12017: Add updateElementFolder

packages/adapter-components/src/definitions/user/index.ts, packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/change_validators/board_culomn_config.ts, packages/jira-adapter/src/change_validators/index.ts, packages/jira-adapter/src/change_validators/script_runner/enhanced_search_deployment.ts, packages/jira-adapter/src/common/script_runner.ts, packages/jira-adapter/src/config/config.ts, packages/jira-adapter/src/filters/script_runner/enhanced_search/enhanced_search_noise_filter.ts, packages/jira-adapter/test/change_validators/script_runner/enhanced_search_deployment.test.ts, packages/jira-adapter/test/filters/script_runner/enhanced_search/enhanced_search_noise_filter.test.ts
Removed the variable part of Enhanced Search jql to reduce noise
---
Look at the jira thread [here](https://salto-io.atlassian.net/browse/SALTO-3464).
Enhanced Search is causing a lot of noise, as they change the jql almost every fetch. I have replaced the variable part with a constant string, and blocked the deployment.
Also, a minor clean-up, and a refactor of the CV config creation 
[Noise Reduction](https://github.com/salto-io/salto_private/pull/9272)
---
Jira Adapter:
* Enhanced Search will not create noise
---
Jira Adapter:
* The variable part of the jql in Enhanced Search will be replaced with a constant string
=> SALTO-3464: Enhanced Search Noise reduction

packages/netsuite-adapter/src/filters/element_references.ts
_The existing version of the regex was greedy and caused parsing to misbehave, The regex now matches the key in key: value and verifies there something after the colon._
---
_None_
---
* Failing to parse suitescripts for references logs error instead of failing fetch..
---
_None_
=> SALTO-6026: Update mappedReferenceRegex to not be greedy

packages/workspace/src/serializer/elements.ts, packages/workspace/test/serializer/serializer.test.ts
We should serialize the `ConflictingMetaTypeError` merge error, to be able loading it back as a merge error (currently we fail with `Deserialization failed. At least one element did not deserialize to a MergeError`)
---
---
None
---
None
=> SALTO-6642 serialize ConflictingMetaTypeError

packages/okta-adapter/e2e_test/mock_elements.ts
Added the new field added by Okta
---
---
None
---
None
=> SALTO-6645: Fix IdP check in Okta's E2E

packages/salesforce-adapter/src/fetch.ts, packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts, packages/salesforce-adapter/src/transformers/xml_transformer.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/adapter.discover.test.ts
Remove fixRetrieveFilePaths FF in Salesforce Adapter
---
- Removed the `fixRetrieveFilePaths` optional feature.
---
_None_
=> SALTO-6656: Remove fixRetrieveFilePaths FF in Salesforce Adapter

packages/cli/src/commands/adapter_format.ts, packages/cli/src/commands/deploy.ts, packages/cli/src/commands/fetch.ts, packages/cli/src/formatter.ts, packages/cli/test/commands/adapter_format.test.ts, packages/cli/test/commands/fetch.test.ts, packages/cli/test/formatter.test.ts, packages/core/src/core/deploy/deploy_actions.ts, packages/jira-adapter/src/deployment/standard_deployment.ts, packages/jira-adapter/test/deployment/standard_deployment.test.ts, packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/change_validators/client_validation.ts, packages/netsuite-adapter/test/change_validators/client_validation.test.ts, packages/parser/src/utils/template_static_file.ts, packages/workspace/src/workspace/errors.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/workspace.test.ts
_use detailedMessage instead of message in saltoError_
---
---
_None_
---
_None_
=> SALTO-6646: use detailedMessage instead of message in saltoError

packages/jira-adapter/src/filters/layouts/layout_types.ts
In this PR I fixed the fetching of reqesutType with empty content in the new requestType format
---
---
* Fixed the fetching of `reqesutType` with empty content in the new requestType format
---
=> SALTO-6657-Fix fetch requestType with empty content in the new format

packages/google-workspace-adapter/e2e_test/adapter.test.ts
SALTO-6535 google e2e logsh
---
---
---
=> SALTO-6535 google e2e logs

packages/jira-adapter/src/filters/automation/types.ts
Fixed automation type to support the deployment of new automation references
---
None
---
Jira Adapter:
* Fix a bug that prevented deployment of automation references with circular references error
---
None
=> SALTO-6658: Fix Automation Type

packages/adapter-components/src/fetch/element/type_element.ts, packages/adapter-components/test/fetch/fetch.test.ts, packages/confluence-adapter/test/adapter.test.ts
When adding a field with `resource.recurseInto`, the user provides the name of the type they are creating, and various downstream places rely on it. this was ignored when generating the ducktype type name, causing non-standalone types to not be defined correctly (and e.g. miss field customizations and not support defining nested references)
---
None
---
None
=> SALTO-5922 use provided type name for recurseInto types instead of generating default ducktype nested type name

packages/zendesk-adapter/e2e_test/adapter.test.ts, packages/zendesk-adapter/src/filters/guide_arrange_paths.ts, packages/zendesk-adapter/src/filters/guide_theme.ts, packages/zendesk-adapter/src/filters/macro_attachments.ts, packages/zendesk-adapter/src/filters/utils.ts, packages/zendesk-adapter/test/adapter.test.ts, packages/zendesk-adapter/test/filters/guide_arrange_paths.test.ts, packages/zendesk-adapter/test/filters/guide_theme.test.ts, packages/zendesk-adapter/test/filters/macro_attachments.test.ts
Currently in the relevant places in the Zendesk adapter
---
---
_Zendesk Adapter:_
* Some static file paths will change in order to ensure uniqueness. Also the pointers to these static files will be updated to the correct path.
---
_Zendesk Adapter:_
* Some static file paths will change in order to ensure uniqueness. Also the pointers to these static files will be updated to the correct path.
=> SALTO-6350 Add elemId hash to create uniqueness of static file paths

packages/confluence-adapter/src/definitions/references.ts
after the fix in https://github.com/salto-io/salto/pull/6558, the reference rule should use the correct type name from the definitions
---
None
---
None
=> SALTO-5922 fix confluence reference rule

packages/microsoft-entra-adapter/src/definitions/deploy/deploy.ts, packages/microsoft-security-adapter/src/definitions/deploy/entra/deploy.ts
The members of the `Directory Role` are deployed using a dedicated filter, so we omit the members field from the modification request. We also have a condition property that should check for changes other than in the members field, but we accidentally used `pick` instead of `omit`.
Thanks @netama for this catch :)
---
---
=> SALTO-5884: Fix Entra Directory Role modification definition

packages/salesforce-adapter/src/filters/flows_filter.ts, packages/salesforce-adapter/test/filters/flows_filter.test.ts
Targeted CBF fetches modified Flow instances even though the Flow MetadataType is not in the fetch targets
---
The filter implementation relied on the existence of the Flow MetadataType to understand if the Flow type should be retrieved or not. This caused a weird behavior in Change-Based Fetches where we get the types from the Elements Source and not filter them. This will be fixed in the major changes from the way we handle types in CBF here: https://github.com/salto-io/salto/pull/6389.
---
- Bug-fix: Targeted Change-based fetch fetches modified Flow instances even though the Flow MetadataType is not in the fetch targets.
---
_None_
=> SALTO-6611: Targeted CBF fetches modified Flow instances even though the Flow MetadataType is not in the fetch targets

packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts, packages/salesforce-adapter/src/filters/custom_objects_to_object_type.ts, packages/salesforce-adapter/src/sfdx_parser/sfdx_dump.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/custom_objects_to_object_type.test.ts
This is needed for SFDX dump code to actually delete side effects from the project
---
---
- Added optional feature `performSideEffectDeletes` that allows explicitly deleting child instances of custom object when the custom object is removed (default: false)
---
_None_
=> SALTO-6623: add perform side effect removals config option

packages/salesforce-adapter/src/filters/organization_settings.ts
(Salesforce) Fetch OrganizationSettings in Change-Based Fetch 
---
- The OrganizationSettings instance will now be fetched in Change-Based fetch.
---
_None_
=> SALTO-4821: (Salesforce) Fetch OrganizationSettings in Change-Based Fetch 

packages/jira-adapter/src/filters/layouts/issue_layout.ts
SALTO-6668 fix a bug in IssueLayout of undefined.length
---
None
---
None
---
None
=> SALTO-6668 fix a bug in IssueLayout of undefined.length

packages/lowerdash/src/serialize.ts, packages/lowerdash/test/serialize.test.ts
Allow creating serialized stream with the following options:
- `maxLineLength`: writes the result in multiple lines, each line with length <= `maxLineLength`. for example:
```
createStreamSerializer({ maxLineLength: 5 })([1,2,3,4,5]) will result:
[1,2]
[3,4]
[5]
```
- `wrapWithKey`: wraps the output list with `{wrapWithKey:[]}`. for example:
```
createStreamSerializer({ wrapWithKey: 'elements' })([1,2,3,4,5]) will result:
{"elements":[1,2,3,4,5]}
```
---
---
Lowerdash:
- Extend stream serializer
---
None
=> SALTO-6522 Extend stream serializer

packages/salesforce-adapter/src/fetch_profile/metadata_query.ts, packages/salesforce-adapter/src/fetch_profile/metadata_types.ts, packages/salesforce-adapter/test/fetch_profile/metadata_types.test.ts
(Salesforce) Simplify metadataQuery for targeted fetch.
---
Moved metadata targets dependencies from the metadataQuery implementation to the dependencies definitions.
Tested targeted fetch on both Flow and CustomObject.
---
_None_
---
_None_
=> SALTO-6677: (Salesforce) Simplify metadataQuery for targeted fetch

packages/core/src/core/fetch.ts, packages/core/src/core/flags.ts, packages/core/test/core/fetch.test.ts
after seeing that the merge-content code is stable, the `autoMergeDisable` core flag (the SALTO_AUTO_MERGE_DISABLE env var) can be removed.
---
---
Core:
- Remove the ability to disable auto merge
---
None
=> SALTO-4757 remove the autoMergeDisable core flag

packages/core/src/core/flags.ts, packages/core/src/local-workspace/state/state.ts, packages/core/test/workspace/local/state/state.test.ts, packages/workspace/src/serializer/elements.ts, packages/workspace/src/workspace/path_index.ts
a new state file format, that would be backward compatible and deals with too-long JSON lines:
```
[] // deprecated
{} // deprecated
[] // deprecated
"" // deprecated
{"versions":["0.1.2"]}
{"updateDates": [{"dummy":"2023-01-09T15:57:59.322Z"}]}
{"elements":[serializedElement1, serializedElement2, ..., serializedElementN]} // each line is shorter than MAX_STRING_LENGTH
{"elements":[serializedElementN+1, serializedElementN+2, ...]}
... // more {"elements":[...]} rows, until we cover all the elements
{"pathIndices":[...]}
{"pathIndices":[...]}
{"pathIndices":[...]}
```
this way the data in the state file won’t be positional, so we’ll be able to chunk long JSON lines, and after parsing each line we’ll merge them back to one `elements` / `pathIndices` lists.
The new state dumping code can be …
=>  SALTO-6522 new state file format to avoid line length limit

packages/okta-adapter/src/definitions/fetch/fetch.ts
Okta added ORN (=Okta resource name) to all apps
---
deploy works without this field so it should be safe to remove
---
None
---
- `orn` field will be deleted from all applications
=> SALTO-6687: Omit ORN field from Okta applications

packages/jira-adapter/src/filters/script_runner/workflow/workflow_dc.ts, packages/jira-adapter/test/filters/script_runner/workflow/workflow_dc.test.ts
Fixed a bug in ScriptRunner wokrflow for DC
---
The original implementation considered the following structure for some of the fields for scripts:
{
script: "...."
}
The entire object is encoded.
We saw cases where there was not such structure, and others where the script was not encoded.
From now on all scripts will have the same structure (like the new format).
noise reduction: https://github.com/salto-io/salto_private/pull/9348
---
Jira Adapter: 
* Fixed a bug that prevented deployment of DC workflows with old format scriptRunner scripts
---
Jira Adapter:
* ScriptRunner scripts in old formats for DC will look like new format scripts inte NaCls
=> SALTO-6674: fix scriptRunner workflow for old formats

packages/lowerdash/src/serialize.ts, packages/lowerdash/test/serialize.test.ts
`JSON.stringify(undefined)` returns `undefined` and not `string`, which cause us to throw when accessing `serializedItem.length`
---
---
Lowerdash:
- Fix serializer for undefined
---
None
=> SALTO-6522 Fix serializer for undefined

packages/adapter-components/src/references/field_references.ts, packages/okta-adapter/src/filters/field_references.ts, packages/okta-adapter/src/reference_mapping.ts, packages/okta-adapter/test/filters/field_references.test.ts
I created a reference to the `client_id` field of the application
---
had to make a tiny change in the reference filter to work with `_.get` to allow fields that are not top level.
---
_Okta adapter_
- Fix a bug causing Authorization Server Policies that apply to specific clients to fail, due to missing reference
---
- Authorization server policies that applies to specific clients, will have reference added to this client.
=> SALTO-6680: Add reference from authorization servers to client ids

packages/adapter-components/src/client/http_connection.ts, packages/adapter-components/test/client/http_connection.test.ts
add timeout only for safe requests
---
---
---
=> SALTO-6679: add timeout only for safe requests

packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/client/file_cabinet_utils.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts, packages/netsuite-adapter/src/group_changes.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/client/suiteapp_client/suiteapp_file_cabinet.test.ts
delete `SuiteAppFileCabinetOperations` and export `importFileCabinet` & `deployFileCabinetInstances` directly.
---
---
None
---
None
=> Refactor SuiteApp FileCabinet

packages/salesforce-adapter/src/fetch_profile/metadata_query.ts, packages/salesforce-adapter/test/fetch_profile/metadata_query.test.ts
(Bugfix) Change-Based fetch deletes sub-instances that their type is not included explicitly in the adapter config
---
Made the implementation of `metadataQuery.isTypeMatch` more correct and take into consideration the relationship between the nested instances and their parent.
---
_None_
---
_None_
=> SALTO-6688: (Bugfix) Change-Based fetch deletes sub-instances that their type is not included explicitly in the adapter config

packages/okta-adapter/src/filters/policy_priority.ts, packages/okta-adapter/test/filters/policy_priority.test.ts
When updating policy / rules priorities, by sending partial data using `PUT`, the policy settings were overridden with Okta's default.
---
There is no `PATCH` request to update policy priority, therefore, in order to update it's priority we send an additional request in `policyPrioritiesFilter` to update this field. The issue was, we sent partial data, and in some cases it cause Okta to fail the request (in MFA enrollment policies), and in others to "reset" the policy settings into the default settings.
To avoid this, I adjusted how we make the policy update - instead of sending specific fields, we'll make a `GET` request to get the current policy data, and the merge of the current data + the required priority (and omit any non deployable fields).
due to …
=> SALTO-6671: Avoid overriding policy settings when updating policy priority

packages/netsuite-adapter/src/filters/element_references.ts
add word boundaries to regex to improve its performance by to preventing partial matches that could lead to more backtracking.
---
---
None
---
None
=> SALTO-6056 add word boundaries to regex

packages/okta-adapter/src/definitions/deploy/deploy.ts, packages/okta-adapter/src/reference_mapping.ts, packages/okta-adapter/test/adapter.test.ts, packages/okta-adapter/test/mock_replies/authorization_server_claim_add.json, packages/okta-adapter/test/mock_replies/authorization_server_claim_modify.json, packages/okta-adapter/test/mock_replies/authorization_server_claim_remove.json
Added support for authorization server claims + reference from auth server claims to scopes.
---
status field can be changed with the regular `PUT`, `POST` requests
---
- Support deployment of Authorization Server Claims
---
- Authorization Server Claims will now have reference to Authorization Server Scopes
=> SALTO-6685: Deploy Authorization Server Claims

packages/core/src/api.ts, packages/core/src/core/adapter_format.ts, packages/core/src/core/fetch.ts, packages/core/test/api.test.ts, packages/core/test/core/fetch.test.ts
We can have conflicts even when there are no before elements. We currently don’t calculate the pending changes in this case (because we treat it as "empty state"), which makes us accept all the service changes even if there are already nacls with elements that conflict that.
In fetch we shouldn't do that, because we can fetch an environment for the first time (so there's no state) and already have elements in common - we don't want pending changes in that case.
In `calculatePatch` it can happen, if there are no elements in the `fromDir`, which we use as the state when calculating the pending changes.
In `calculatePatchFromChanges` it can happen, when we have only addition changes, because then there won’t be any `before` elements to use as the state when calculating the pending changes - …
=> SALTO-6643 add calculatePendingChanges param to calcFetchChanges

packages/netsuite-adapter/src/filters/element_references.ts
We don't need to extract object keys in the form of `{ "key": value }` / `{ 'key': value }`, because they are extracted from the general strings regex (`semanticReferenceRegex`)
---
---
None
---
None
=> SALTO-6056 Improve SuiteScripts object keys regex

packages/core/src/local-workspace/remote_map/counters.ts, packages/core/src/local-workspace/remote_map/remote_map.ts, packages/core/test/workspace/local/remote_map/remote_map.test.ts
Checking if a remote map is empty requires creating a DB iterator with a prefix. If we know that a namespace is empty, we can avoid doing that and hopefully reduce the amount of DB iterators we create. This in turn will hopefully reduce the chances that we trigger the crazy memory consumption issue in rocksdb
---
---
Core:
- Improve performance when reading many elements with static files for a workspace
---
_None_
=> SALTO-6699: Cache whether a remote map is empty

packages/adapter-api/src/adapter.ts, packages/core/src/core/flags.ts, packages/core/src/core/plan/filter.ts, packages/core/src/core/plan/group.ts, packages/core/src/core/plan/plan.ts, packages/core/test/common/plan_generator.ts, packages/core/test/core/plan/plan.test.ts, packages/dag/src/group.ts, packages/dag/test/group.test.ts
When encounter circular dependencies in the grouped graph plan, remove the cycle from graph and create a valid plan without it.
---
Today, when the plan contains a circular dependency, we throw error and fail the entire plan, even for elements that could have been deployed. This PR changes this behavior, by removing the cycles from plan and creating change errors for the removed elements.
When first building the grouped graph, every cycle detected is removed from graph until no more cycles can be found.
After the first iteration of the grouped graph, we need to rerun the filter in order to adjust types and create additional (non circular, regular) dependency errors based on the dropped elements.
Then we try to build the group graph again, this time …
=> SALTO-5724: Avoid failing the entire plan for circular dependency error

packages/okta-adapter/src/definitions/fetch/fetch.ts, packages/okta-adapter/src/filters/policy_priority.ts
This should fix a bug causing the policy / policy rule to be "pushed" as the latest policy upon modifications.
---
Until now, for policies / rules with a dedicated order instance, we completely removed the `priority` field from the element. This caused modification changes to send the payload without the `priority`, and have Okta to fallback to the lowest priority available (so the policies were "push" down the queue)
To solve this, I made the field hidden (when relevant), this should give us the following - 
1. Addition changes - the priority field will not exist, and the policy priority will be inclusively determined by the order instance
2. Removal changes - this doesn't matter
3. Modification changes -
- If policy changed its position, we first modify …
=> SALTO-6691: Hide priority field from policies to be used in modification changes

packages/netsuite-adapter/src/config/types.ts, packages/netsuite-adapter/src/filters/element_references.ts, packages/netsuite-adapter/test/filters/element_references.test.ts
Add the `useNewReferencesInSuiteScripts` adapter config in order to calculate & set the `_generated_dependencies` of SuiteScripts.
- Ignores invalid file extensions
- Ignores commented code
- Extracts references from object keys
---
---
- Add the `useNewReferencesInSuiteScripts` adapter config in order to calculate & set the `_generated_dependencies` of SuiteScripts
---
- When the `useNewReferencesInSuiteScripts` adapter config is `true`, the `_generated_dependencies` annotation of file instances will be modified
=> SALTO-6026 Add adapter config for using new references in SuiteScripts

packages/microsoft-security-adapter/src/definitions/fetch/entra/fetch.ts
AuthenticationMethodConfiguration can have multiple custom instances created by the user. It currently resides under the Settings directory since its parent is located there, and we've set it to nest under the parent directory. However, there's no real reason to keep it there. Therefore, it’s best to extract it outside of the Settings directory.
---
---
=> SALTO-6710: Extract Entra AuthenticationMethodConfiguration from the Settings directory

packages/salesforce-adapter/src/fetch.ts
(Salesforce) add trace log on Layout File Properties
---
Should help investigate the issue where Layouts are sporadically included / excluded from Workspaces.
---
_None_
---
_None_
=> SALTO-6719: (Salesforce) add trace log on Layout File Properties

packages/salesforce-adapter/src/fetch_profile/metadata_types.ts, packages/salesforce-adapter/test/fetch_profile/metadata_types.test.ts
(Salesforce) Add Targeted Fetch support for Profiles
---
Profiles must be retrieved alongside all of their related types. This PR simply adds a dependency to the fetch targets for Profiles. 
---
- Add Targeted Fetch support for Profiles.
---
_None_
=> SALTO-6712: (Salesforce) Add Targeted Fetch support for Profiles 

packages/workato-adapter/src/definitions/fetch/fetch.ts
Recipe code elements will now be nested under the parent recipe in the element tree
---
---
_Workato adapter_:
- Improve elements structure in Workato be nesting recipe code elements under their parent recipe.
---
None
=> SALTO-2061: Nest Recipe Code under Recipe instances in Workato

packages/salesforce-adapter/src/fetch.ts
(Bug-fix) Salesforce Fetch fails on TypeError: Cannot read properties of undefined (reading 'annotations')
---
Type safety issues when dealing with Records, again 🤦 
Not SOS as this is the first time we encounter issue like this and it's not a regression. Added logs to understand these cases in future.
---
_None_
---
_None_
=> SALTO-6724: (Bug-fix) Salesforce Fetch fails on TypeError: Cannot read properties of undefined (reading 'annotations')

packages/jira-adapter/src/filters/automation/types.ts, packages/jira-adapter/src/reference_mapping.ts
Revert adding projectId reference for JSM automation within components...children
---
https://github.com/salto-io/salto/pull/6634
---
None
---
None
=> SALTO-6734 Revert Jira JSM Automation->projectId reference #6634

packages/jira-adapter/src/filters/automation/types.ts, packages/jira-adapter/src/reference_mapping.ts
Add projectId reference for JSM automation within components...children
---
https://github.com/salto-io/salto/pull/6634
---
None
---
None
=> SALTO-6734 Jira JSM Automation->projectId reference

packages/salesforce-adapter/src/adapter.ts
---
Unclear why this didn't prevent the deployment from working until now, I did check that deploying auto response rule changes works before and after this change.
---
_None_
---
_None_
=> SALTO-6742: Fix auto response rule field name

packages/zendesk-adapter/src/filters/field_references.ts
Add explicit reference to custom_status_id in views
---
---
__Zendesk:__
* Fix a bug with missing references to a `custom_status` from a `view`.
---
__Zendesk:__
* Instead of unresolved ids, `view` nacls will have a missing reference for `custom_status`es.
=> SALTO-6666 Add explicit reference to custom_status_id in views

packages/microsoft-security-adapter/src/definitions/fetch/entra/fetch.ts, packages/microsoft-security-adapter/src/definitions/fetch/intune/fetch.ts, packages/microsoft-security-adapter/src/definitions/fetch/intune/utils/device_configuration_settings.ts, packages/microsoft-security-adapter/src/definitions/fetch/intune/utils/group_assignments.ts, packages/microsoft-security-adapter/src/definitions/fetch/intune/utils/platform_script.ts, packages/microsoft-security-adapter/test/definitions/fetch/intune/utils/platform_script.test.ts
MS Graph doesn’t return the following fields in a specific order (between different tenants), so we sort them to maintain consistency:
* Assignments: Found in various Intune types.
* Application Tags: Found in Entra Service Principals.
---
---
=> SALTO-6730: (Microsoft Security) Fix inconsistent order of array fields

packages/microsoft-security-adapter/jest.config.js, packages/microsoft-security-adapter/src/definitions/references/entra_reference_rules.ts, packages/microsoft-security-adapter/src/definitions/references/references.ts, packages/microsoft-security-adapter/src/definitions/requests/clients.ts, packages/microsoft-security-adapter/src/definitions/types.ts
1. Add polling for creation/update of a Conditional Access Policy.
2. Fix reference rule for Conditional Access policies
---
1. When we deploy a conditional access policy and the service principal it references within the same request, the service might throw an error stating that the service principal does not exist. This issue resolved (i.e. the service principal is updated) after 5-15 seconds.
2. A Conditional access policy may contain the following structure for application references:
```
conditions = {
...otherFields,
applications = {
includeApplications = [
microsoft_security.EntraServicePrincipal.instance.someSPInstanceA,
...
]
excludeApplications = [
microsoft_security.EntraServicePrincipal.instance.someSPInstanceB,
...,
]
}
}
```
The current reference rule simply serialize the …
=> SALTO-6735: (MS Security) Fix reference rule for Conditional Access Policy

packages/core/src/local-workspace/remote_map/counters.ts, packages/core/src/local-workspace/remote_map/location_cache.ts, packages/core/src/local-workspace/remote_map/location_pool.ts, packages/core/src/local-workspace/remote_map/remote_map.ts, packages/core/test/workspace/local/adapters_config.test.ts, packages/core/test/workspace/local/remote_map/location_cache.test.ts, packages/core/test/workspace/local/remote_map/remote_map.test.ts, packages/lang-server/test/workspace.ts, packages/workspace/src/workspace/remote_map.ts, packages/workspace/test/utils.ts, packages/workspace/test/workspace/adapters_config.test.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts, packages/workspace/test/workspace/remote_map.test.ts
Remove reference counting logic from remote map cache. Unfortunately, we can't really count references because the interface for closing remote maps is not symmetric with the interface for creating them. Currently when we close remote maps, we just close them, no matter how many references they had, so the cache has to have the same behavior.
Also, removed the unused "revert" function from the remote map interface (will need another PR to fully remove it)
---
---
Core:
- Fix potential memory leak in long running processes using workspaces
---
_None_
=> SALTO-6504: Fix memory leak in remote map cache

packages/okta-adapter/src/definitions/fetch/fetch.ts, packages/okta-adapter/src/filters/common.ts
Sort a field causing noise between fetches
---
---
None
---
None
=> SALTO-6750: Sort verification methods fields in Okta verify authenticator

packages/salesforce-adapter/src/fetch.ts, packages/salesforce-adapter/src/transformers/xml_transformer.ts
Salesforce Adapter Log fixes
---
- Changed the trace log to be explicit about the array length of the Layout FileProperties, to avoid the values being truncated.
- Fixed a printed value in the xml parsing numbers diff log. Added explicit log on affected types.
---
_None_
---
_None_
=> SALTO-6755: Salesforce Adapter Log fixes

packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts, packages/netsuite-adapter/src/data_elements/types.ts
`customrecordtype = "-120"` means that the field reference an email template instance, and we can use a reference (e.g. `netsuite.emailtemplate.instance.custtemailtmpl123`) instead of ASV (e.g `[ACCOUNT_SPECIFIC_VALUE] (object) (email template name)`).
---
---
- Identify email template references in data instances
---
- Fields in custom record types that reference email template will replace their field type:
```diff
-  unknown custom_custrecord_email_template {
+  netsuite.emailtemplateReference custom_custrecord_email_template {
scriptid = "custrecord_email_template"
```
- References to email templates in data instances will replace ASVs:
```diff
- …
```
=> Identify email template references in data instances

packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
When we receive an invalid creds error inside the `listBundles` query we throw this error:
`listBundles operation failed. Received the following error: Invalid SuiteApp credentials`
We should instead throw the `InvalidSuiteAppCredentialsError` itself.
---
---
- Throw a right error on InvalidSuiteAppCredentialsError
---
None
=> Throw the right error on InvalidSuiteAppCredentialsError

packages/jira-adapter/src/config/config.ts, packages/jira-adapter/src/filters/fields/field_name_filter.ts, packages/jira-adapter/test/filters/fields/field_name_filter.test.ts
Temp solution till we handle id-alignment generally
---
---
- SALTO-5887: Fix a bug where RequestType field name in JSM is different for some old envs
---
None
=> SALTO-5887 JSM - support Field RequestType name change

packages/dummy-adapter/src/adapter_creator.ts, packages/dummy-adapter/src/generator.ts, packages/dummy-adapter/test/adapter_creator.test.ts
Support loadElementsFromFolder in dummy adapter as a first step towards running "Deploy from PR" tests using the dummy adapter instead of using Netsuite.
---
Per the requirements specified in the ticket, the adapter will look for a dummy.nacl file in the provided directory and use it as a configuration file to generate elements.
---
- Dummy adapter supports loadElementsFromFolder function
---
=> SAAS-5602: Dummy: Support loadElementsFromFolder

packages/salesforce-adapter/src/fetch.ts, packages/salesforce-adapter/test/adapter.discover.test.ts
(Bug-fix) Salesforce Standard Layouts are being removed and added randomly
---
The bug occurred since we've uniqued the **fileProperties** before fixing properties of managed Elements that don't have the namespace prefix as part of their fullName. See added UT for a clear example. It happened sporadically since the order of the `list` result is inconsistent.
---
- (Bug-fix) Standard Layouts are being removed and added randomly
---
_Salesforce_:
- You may notice new Elements that were omitted previously due to the bug.
=> SALTO-6716: (Bug-fix) Salesforce Standard Layouts are being removed and added randomly

packages/microsoft-security-adapter/src/auth.ts
The OAuth scope `DeviceManagementRBAC.ReadWrite.All` is missing in order to support `scope* tags` 
(*funny, isn't it? :)
---
---
---
=> SALTO-6770: Add missing Intune oauth scope

packages/adapter-components/src/definitions/system/fetch/element.ts, packages/adapter-components/src/fetch/element/id_utils.ts, packages/adapter-components/test/fetch/element/id_utils.test.ts
Allow customizing prefix for element path
---
hardcoded path added to the `topLevel`.`path` definition, allowing to consolidate few types under the same path.
example (not a real usecase):
will add tests later
---
None
---
None
=> SALTO-6707: Allow customizing prefix for element path

packages/salesforce-adapter/src/filters/profile_instance_split.ts, packages/salesforce-adapter/src/sfdx_parser/sfdx_parser.ts, packages/salesforce-adapter/test/filters/profile_instance_split.test.ts
Reordering profiles pre deploy to maintain order in SFDX.
This is the last issue for profiles so enabling them.
---
For elements split between files, the NaCl source loads only the files that have been changed and then merges them with the element in the state. This means that the order of the value depends on which files have been changed.
In order to avoid fundementally changing the way the NaCl source works I instead opted for just fixing the issue for Profiles which as far as I can tell is the only type affected in this way which is merged back into a single file in SFDX.
---
* None.
---
* None.
=> SALTO-6621: Sort profiles

packages/salesforce-adapter/src/filters/profile_instance_split.ts, packages/salesforce-adapter/src/filters/profile_permissions.ts, packages/salesforce-adapter/src/sfdx_parser/sfdx_parser.ts, packages/salesforce-adapter/test/filters/profile_permissions.test.ts
We add some extra permissions to profiles when deploying to make sure users have access, but we don't want to do this in the SFDX dump flow.
---
None.
---
None.
---
None.
=> SALTO-6621: Skipping additional profile permissions in SFDX flow

packages/salesforce-adapter/src/filters/workflow.ts, packages/salesforce-adapter/test/mock_elements.ts, packages/salesforce-adapter/test/sfdx_parser/sfdx_dump.test.ts
Since the SFDX code overrides entire workflows on any workflow change, we need to collect all workflow sub-instances on any workflow change.
---
None.
---
None.
---
None.
=> SALTO-6753: Supporting workflows in SFDX

packages/zendesk-adapter/src/adapter.ts, packages/zendesk-adapter/src/definitions/fetch/fetch.ts, packages/zendesk-adapter/src/definitions/fetch/transforms/index.ts, packages/zendesk-adapter/src/definitions/fetch/transforms/trigger_adjuster.ts, packages/zendesk-adapter/src/filters/deploy_trigger_skills.ts, packages/zendesk-adapter/test/definitions/fetch/transforms/trigger_adjuster.test.ts, packages/zendesk-adapter/test/filters/deploy_trigger_skills.test.ts
Support a new API format of skills within Zendesk triggers.
---
---
_Zendesk Adapter:_
* set_skills or add_skills under Trigger actions will now have a priority of required or optional as per https://developer.zendesk.com/documentation/ticketing/using-the-zendesk-api/setting-skill-priority-with-skills-in-trigger-action/
---
_Zendesk Adapter:_
* Trigger nacls with set_skills or add_skills will now include a priority key if this is received from Zendesk.
=> SALTO-6667 Zendesk trigger skill priority

packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
this is an improvement for fetches with mainly additions (like first fetch), or when no static file was removed - we can then avoid going over all of the changes' after and return an empty result.
---
---
Workspace:
- Improve dangling static files removal
---
None
=> Improve dangling static files removal

packages/netsuite-adapter/package.json, yarn.lock
Remove Spinner prints in the SaaS so the logs will be indexed
---
---
---
=> SAAS-2781: Bump SDF to 1.9.0-salto-4

packages/cli/src/commands/adapter_format.ts, packages/core/src/core/adapter_format.ts, packages/core/test/core/adapter_format.test.ts
---
Core: Change the parameters of `isInitializedFolder` and `initFolder` not to include `workspace`
---
=> SALTO-6747: Change InitFolder params

packages/core/src/local-workspace/remote_map/remote_map.ts, packages/core/test/workspace/local/remote_map/remote_map_connection.test.ts
If closeRemoteMapsOfLocation is directly called but no remote map was opened we should not try to close the cache of that location.
This is mostly to avoid the redundant warning log
---
---
_None_
---
_None_
=> SALTO-6783: Do not return remote map cache if it was not closed

packages/adapter-components/src/client/http_client.ts, packages/jira-adapter/e2e_test/instances/cloud/workflow.ts, packages/jira-adapter/src/change_validators/workflowsV2/inbound_transition.ts, packages/jira-adapter/src/filters/workflow/transition_structure.ts, packages/jira-adapter/src/filters/workflow/types.ts, packages/jira-adapter/src/filters/workflow/workflow_deploy_filter.ts, packages/jira-adapter/src/filters/workflow/workflow_structure_filter.ts, packages/jira-adapter/src/filters/workflowV2/types.ts, packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts, packages/jira-adapter/src/reference_mapping.ts, packages/jira-adapter/test/change_validators/workflowsV2/inbound_transition.test.ts, packages/jira-adapter/test/filters/workflow/transition_structure.test.ts, packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts
_add workflow transition links_
---
---
* Workflow transitions will no longer have the `to` and `from` fields, instead we will use `links` and `toStatusReference` due to an Atlassian API change (Jira Cloud only).
---
* Workflow transitions will no longer have the `to` and `from` fields, instead we will use `links` and `toStatusReference` due to an Atlassian API change (Jira Cloud only).
=> SALTO-6779: add workflow transition links

packages/salesforce-adapter/src/sfdx_parser/sfdx_dump.ts, packages/salesforce-adapter/src/sfdx_parser/sfdx_parser.ts, packages/salesforce-adapter/test/sfdx_parser/sfdx_dump.test.ts
Fix an issue where changes to unsupported metadata types would not be applied but also were not returned as unapplied
---
Also added a test for deleting nested non-decomposed instances
---
_None_
---
_None_
=> SALTO-6762: SFDX dump return unsupported type changes as unapplied

packages/adapter-components/src/client/http_client.ts, packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts, packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts
_remove boolean query param from adapter component client interface_
---
---
_None_
---
_None_
=> SALTO-6779: remove boolean query param from adapter component client interface

packages/salesforce-adapter/jest.config.js, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/change_validator.ts, packages/salesforce-adapter/src/change_validators/map_keys.ts, packages/salesforce-adapter/src/change_validators/multiple_defaults.ts, packages/salesforce-adapter/src/change_validators/ordered_maps.ts, packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts, packages/salesforce-adapter/src/filters/convert_lists.ts, packages/salesforce-adapter/src/filters/convert_maps.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/change_validators/map_keys.test.ts, packages/salesforce-adapter/test/change_validators/ordered_maps.test.ts, packages/salesforce-adapter/test/filters/convert_maps.test.ts
This is a redo of #6604 which was reverted in #6680.
There were a few issues, the main one was that I protected the filter behavior with a FF only on `onFetch` and not on `preDeploy` and `onDeploy`, but I also found more bugs and added some tests. Hopefully this looks better now.
Workspace diff: https://github.com/salto-io/amir-sf1/commit/1ff0e4d32556d0c661067317541b1e3769228c60
Original PR description below:
---
This PR remodels picklists (of various kinds) to "OrderedMap" which is a new type that has a Map and a separate list of references to all values in that map to maintain its order.
This behavior is protected by a `picklistsAsMaps` feature flag.
See SALTO-4990 for more details.
Workspace diff: https://github.com/salto-io/amir-sf1/commit/46f8c50dd0087d3baf3db3c00e9dbc9b3cc411d7
``` …
```
=> SALTO-4990: Salesforce: Remodel picklist value lists to maps, to allow references to specific values (un-rollback)

packages/salesforce-adapter/src/sfdx_parser/project.ts
The standard template is a bit more spammy than we would like.
---
_Salesforce adapter_: 
* Moved to using the empty template for creating SFDX projects instead of the standard template which has some extra files.
---
None.
=> SALTO-6812: Using empty SFDX project template

packages/salesforce-adapter/package.json, packages/salesforce-adapter/src/adapter_creator.ts, packages/salesforce-adapter/test/adapter.crud.test.ts, yarn.lock
SALTO-6736: Add Elapsed Time to Salesforce Metadata Deploy Progress Reporter
---
Example for queued deployment: 
Metadata: Waiting on another deploy or automated process to finish in Salesforce. Elapsed Time: 3.344 seconds. View deployments [in Salesforce](https://salto-1a-dev-ed.develop.my.salesforce.com/lightning/setup/DeployStatus/home)
---
- Improved the Metadata Deploy progress to include the elapsed time since the deployment was created.
---
_None_
=> SALTO-6736: Add Elapsed Time to Salesforce Metadata Deploy Progress Reporter

packages/jira-adapter/src/change_validators/adding_jsm_project.ts, packages/jira-adapter/src/change_validators/index.ts, packages/jira-adapter/test/change_validators/adding_jsm_project.test.ts
In this PR I fixed AddJsmProjectValidator to address only jira cloud 
---
During deployment of a JSM project to our Jira DC instance, the operation failed due to the addJsmProjectValidator being incorrectly applied to both DC and Cloud environments. After disabling the validator, the deployment succeeded.
The validator logic needs to be updated to address only Cloud environments.
---
* [SALTO-6817](https://salto-io.atlassian.net/browse/SALTO-6817) - Users will be able to deploy JSM projects (Only the projects, without subTypes) to their DC instances. 
---
None
[SALTO-6817]: https://salto-io.atlassian.net/browse/SALTO-6817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SALTO-6817: Fix AddJsmProjectValidator to address only jira cloud 

packages/zendesk-adapter/src/filters/template_engines/handlebar_parser.ts, packages/zendesk-adapter/test/filters/template_engines/handlebar_parser.test.ts
Header is self explanatory
---
---
---
=> SALTO-6461 Add a try/catch for the handlebar parser

packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts, packages/salesforce-adapter/src/filters/field_references.ts, packages/salesforce-adapter/src/transformers/reference_mapping.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/field_references.test.ts, packages/salesforce-adapter/test/mock_elements.ts
(Salesforce) LightningPage FieldItem references
---
- Workspace Diff: https://github.com/salto-io/tamir-sf/commit/1083e2b2d5058a5d3cfc4d68a0d736f6ba60bf0a
- Added a new serialization strategy with UTs.
---
- Added references from LightningPage instances to CustomFields (requires the `lightningPageFieldItemReference` optional feature)
---
Salesforce:
- When enabling the feature `lightningPageFieldItemReference`, expect changes to existing LightningPage nacls.
=> SALTO-5929: (Salesforce) LightningPage FieldItem references

packages/adapter-components/src/definitions/system/fetch/resource.ts, packages/adapter-components/src/fetch/errors.ts, packages/adapter-components/src/fetch/request/pagination/index.ts, packages/adapter-components/src/fetch/request/pagination/pagination_functions.ts, packages/adapter-components/test/fetch/element/element.test.ts, packages/adapter-components/test/fetch/request/pagination/pagination_functions.test.ts, packages/okta-adapter/src/adapter.ts, packages/okta-adapter/src/definitions/fetch/fetch.ts, packages/okta-adapter/src/definitions/requests/clients.ts, packages/okta-adapter/src/definitions/requests/pagination.ts, packages/okta-adapter/src/definitions/types.ts, packages/okta-adapter/src/user_config.ts, packages/okta-adapter/test/utils.ts
We want to limit the number of users fetched to 200,000
---
Set the default max users number to 200,000, when exceeding this, the pagination func will throw and this error will be caught by the custom error handler that will convert the error into fetch warning.
The max number is configurable through the adapter config, and can also be set to `-1` to cancel this limitation.
---
- Add safety to avoid fetching users in account with more than 200,000 users
---
None
=> SALTO-6737: Limit the number of users fetched in Okta

packages/adapter-api/src/adapter.ts, packages/salesforce-adapter/src/sfdx_parser/errors.ts, packages/salesforce-adapter/src/sfdx_parser/project.ts, packages/salesforce-adapter/src/sfdx_parser/salesforce_imports.ts, packages/salesforce-adapter/src/sfdx_parser/sfdx_dump.ts, packages/salesforce-adapter/src/sfdx_parser/sfdx_parser.ts, packages/salesforce-adapter/test/sfdx_parser/errors.test.ts
We've seen `converter.convert` throwing errors in dump, so better safe than sorry on all library calls.
Also adding a fallback for all error messages just in case.
---
Covering the error flows seems pretty tricky - will require some uncomfortable mocking. Open to suggestion or pushback on this if we think it's worth the effort.
---
_Salesforce adapter_:
* Return errors from parsing and dumping SFDX instead of throwing.
---
None
=> SALTO-6811: Adding try/catch on calls to SF library

packages/zendesk-adapter/src/config.ts, packages/zendesk-adapter/src/filters/template_engines/creator.ts, packages/zendesk-adapter/src/user_config.ts
The nacl doesn't support an OR type.
---
---
---
=> SALTO-6606 Fix faulty OR clause in Zendesk config

packages/core/src/core/adapter_format.ts, packages/core/test/core/adapter_format.test.ts
The way things currently stand (and likely forever), the adapter logic for dumping to folder never depends on these chages, so we can omit them.
This is becuase dumping to folder is (in many ways) like deploying, and we will never try to deploy changes on hidden elements because they cannot be selected in the plan.
We took a naive approach for filtering hidden changes which is good enough for now but we might choose to expand in the future.
---
Salesforce:
* Exclude hidden elements in SFDX.
---
None.
=> SALTO-6819: Excluding changes on hidden elements from dump to folder

packages/salesforce-adapter/src/filters/task_and_event_custom_fields.ts, packages/salesforce-adapter/test/filters/task_and_event_custom_fields.test.ts
This problem came up in the SFDX flow.
---
None.
---
None.
---
None.
=> SALTO-6863: Fixing task and events custom fields filter when missing types

packages/okta-adapter/src/change_validators/index.ts, packages/okta-adapter/src/change_validators/provisioned_user_addition.ts, packages/okta-adapter/src/user_config.ts, packages/okta-adapter/test/change_validators/provisioned_user_addition.test.ts
Indicate admins that added users will receive an email when adding those using Salto.
---
---
- Add a change validator to indicate that users added in status provisioned will receive an email to complete activation.  
---
None
=> SALTO-6171: Create "Info" message when adding a user in status PROVISIONED (Okta)

packages/adapter-components/src/deployment/deploy/requester.ts, packages/okta-adapter/src/definitions/deploy/deploy.ts, packages/okta-adapter/src/definitions/deploy/types/authorization_servers.ts, packages/okta-adapter/src/definitions/fetch/fetch.ts, packages/okta-adapter/src/definitions/requests/clients.ts, packages/okta-adapter/test/adapter.test.ts, packages/okta-adapter/test/mock_replies/authorization_server_add.json, packages/okta-adapter/test/mock_replies/authorization_server_add_custom_scope.json, packages/okta-adapter/test/mock_replies/authorization_server_add_system_scope.json, packages/okta-adapter/test/mock_replies/authorization_server_modify_and_activate.json, packages/okta-adapter/test/mock_replies/authorization_server_modify_and_deactivate.json, packages/okta-adapter/test/mock_replies/authorization_server_remove.json
Added deploy support for authorization servers.
---
I added deploy support for auth servers. Okta accounts come with a default servers, and additional servers can be configured. Each server comes with scopes, claims the policies.
On auth server addition, some scopes and claims might be created (there's no consistent list of the scopes and claims that will be created, but they will have `system = true` property. 
Included in this PR -
- Support for auth servers action (add, activate..)
- Handle auto creation for scopes additions - In case of addition of system scopes, we'll fetch the added scope and then modify it to ensure the scope is updated with the requested values
- remove the reference from auth servers to their scopes, claims and policies. It was …
=> SALTO-5282: Add deploy support for authorization servers

packages/jira-adapter/src/filters/workflowV2/workflow_filter.ts, packages/jira-adapter/test/filters/workflowV2/workflow_filter.test.ts
_add empty links to workflow transitions_
---
* we should add the link list when `links = undefined`
---
_None_
---
_None_
=> SALTO-6865: add empty links to workflow transitions

packages/adapter-components/src/auth/oauth.ts, packages/adapter-components/src/client/http_connection.ts, packages/adapter-components/src/fetch/element/element.ts, packages/adapter-components/test/auth/oauth.test.ts, packages/adapter-components/test/fetch/element/element.test.ts, packages/jira-adapter/test/client/script_runner_client.test.ts, packages/microsoft-security-adapter/src/client/connection.ts, packages/okta-adapter/test/adapter.test.ts, packages/zuora-billing-adapter/test/adapter_creator.test.ts
Also added throw `Unauthorized Error` when generating the token in OAuth flow (cause it's called before validate credentials)
---
additionally, I wrapped `login` func in try-catch as well, as `authParamsFunc` might make network calls
---
- Fix a bug causing fetch not to fail on credentials error
- Fix a bug causing fetch not to fail on credentials error
_Microsoft adapter_:
- Fix a bug causing fetch not to fail on credentials error
---
None
=> SALTO-6765: Fail fetch if credentials are invalid

packages/cli/src/commands/env.ts, packages/cli/src/commands/init.ts, packages/cli/test/commands/init.test.ts, packages/cli/test/mocks.ts, packages/core/src/local-workspace/workspace.ts, packages/core/src/local-workspace/workspace_config.ts, packages/core/src/local-workspace/workspace_config_types.ts, packages/core/test/workspace/local/workspace.test.ts, packages/core/test/workspace/local/workspace_config.test.ts, packages/workspace/src/workspace/config/workspace_config_types.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/workspace.test.ts
The workspace name is never used and can be removed.
---
---
Workspace:
- Delete workspace name property from `Workspace` and `WorkspaceConfig`
- Delete workspace name param from `initWorkspace` and `initLocalWorkspace`
---
- Adding/deleting/renaming an env/account will delete the `name` property from `salto.config/workspace.nacl`
- New workspaces will be created without the `name` property in `salto.config/workspace.nacl`
=> SALTO-6848 Delete workspace name

packages/core/package.json, yarn.lock
https://github.com/salto-io/node-diff3 is now rebased on the latest https://github.com/bhousel/node-diff3 code.
This rebase is possible because we're now using node 18, and before that there were dependencies in bhousel/node-diff3 that required that.
There are no changes in the algorithm code between the versions - https://github.com/bhousel/node-diff3/compare/a94dbaa1307b6c6ff578479a7a51f1b587e8ed7d...4d91ac7d5e2ca1a96b15ec21fac0fa19908ae2fd
---
---
None
---
None
=> Upgrade @salto-io/node-diff3

packages/jira-adapter/src/filters/hidden_value_in_lists.ts, packages/jira-adapter/src/filters/masking.ts, packages/jira-adapter/src/filters/references_by_self_link.ts, packages/jira-adapter/src/filters/remove_empty_values.ts, packages/jira-adapter/src/filters/remove_self.ts, packages/jira-adapter/src/filters/sort_lists.ts
`hiddenValuesInLists` and `sortLists` filters were taking very long time for large environments, hopefully making those sync will reduce the time they take.
---
---
- Fetch optimization for large Jira envs
---
None
=> SALTO-6882: Replace `transformValues` usages in Jira with `TransformValuesSync`

packages/adapter-components/src/references/field_references.ts, packages/adapter-components/src/references/reference_mapping.ts, packages/salesforce-adapter/src/transformers/reference_mapping.ts
Probably won't make a big difference, but we know async is adding overhead and there's no need for loading the type when we only care about the typename that's already available on the instance's elem id.
(this is not the case in salesforce, but it is currently in all other adapters - and salesforce has its own variant of this implementation for this reason, so it's not impacted - but the reuse of shared functions meant not all async calls could be fully removed. we can do that if we make sure the types are always available on the salesforce side before entering this filter, but I didn't want to add that as a prereq for this smaller change).
---
None
---
None
=> SALTO-2432 remove unneeded async logic from reference strategy finder

packages/salesforce-adapter/config_doc.md, packages/salesforce-adapter/src/additional_references.ts, packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts, packages/salesforce-adapter/src/types.ts
It isn't used anywhere.
---
None.
---
None.
---
None.
=> SALTO-6901: Removing the `generateRefsInProfiles` optional feature

packages/salesforce-adapter/src/filters/add_missing_ids.ts, packages/salesforce-adapter/src/filters/author_information/custom_objects.ts, packages/salesforce-adapter/src/filters/author_information/data_instances.ts, packages/salesforce-adapter/src/filters/author_information/nested_instances.ts, packages/salesforce-adapter/src/filters/author_information/sharing_rules.ts, packages/salesforce-adapter/src/filters/create_missing_installed_packages_instances.ts, packages/salesforce-adapter/src/filters/custom_object_instances_references.ts, packages/salesforce-adapter/src/filters/custom_objects_from_soap_describe.ts, packages/salesforce-adapter/src/filters/custom_objects_instances.ts, packages/salesforce-adapter/src/filters/custom_settings_filter.ts, packages/salesforce-adapter/src/filters/elements_url.ts, packages/salesforce-adapter/src/filters/extend_triggers_metadata.ts, packages/salesforce-adapter/src/filters/extra_dependencies.ts, packages/salesforce-adapter/src/filters/flows_filter.ts, packages/salesforce-adapter/src/filters/organization_settings.ts, packages/salesforce-adapter/src/filters/profile_paths.ts, packages/salesforce-adapter/src/filters/settings_type.ts, packages/salesforce-adapter/src/filters/standard_value_sets.ts
It's no longer supported.
---
None.
---
None.
---
None.
=> SALTO-6900: Removing `remote` from all SF filters

packages/jira-adapter/src/filters/field_references.ts
SALTO-6889 Jira: do not scan ProjectComponents when indexing references
---
---
None
---
None
=> SALTO-6889 Jira: do not scan ProjectComponents when indexing references

packages/zendesk-adapter/src/definitions/fetch/transforms/trigger_adjuster.ts, packages/zendesk-adapter/src/filters/deploy_trigger_skills.ts, packages/zendesk-adapter/test/definitions/fetch/transforms/trigger_adjuster.test.ts, packages/zendesk-adapter/test/filters/deploy_trigger_skills.test.ts
Update support for trigger priorities according to https://developer.zendesk.com/documentation/ticketing/using-the-zendesk-api/setting-skill-priority-with-skills-in-trigger-action/
---
---
---
_Zendesk Adapter:_
* Trigger skill priorities will change from `optional` to `optional high` as per  https://developer.zendesk.com/documentation/ticketing/using-the-zendesk-api/setting-skill-priority-with-skills-in-trigger-action/
=> SALTO-6905 Update trigger skill priorities

packages/adapter-components/src/definitions/system/requests/types.ts, packages/adapter-components/src/fetch/request/requester.ts, packages/adapter-components/test/fetch/request/pagination/pagination.test.ts
The current `body` field does not pass well in POST methods on fetch definitions (`sendRequest` expects a `data` field).
---
---
---
=> SALTO-6867 Update infra to have a data field instead of body field

packages/cli/src/prompts.ts, packages/cli/test/commands/init.test.ts
SALTO-1132: Removed extra '\n' from init command response
---
_None_
---
_None_
=> SALTO-1132: Removed extra '\n' from init command response

packages/salesforce-adapter/src/filters/custom_objects_to_object_type.ts, packages/salesforce-adapter/test/filters/custom_objects_to_object_type.test.ts
This came us as a bug in a test flow for parsing SFDX. Better to not make assumptions if we don't have to.
---
None.
---
None.
---
None.
=> SALTO-6818: Making less assumptions in custom objects to object type

packages/adapter-utils/src/nacl_case_utils.ts, packages/adapter-utils/test/nacl_case_utils.test.ts, packages/jira-adapter/src/filters/icon_utils.ts, packages/jira-adapter/test/filters/assets/object_type_icon.test.ts, packages/jira-adapter/test/filters/issue_type.test.ts, packages/okta-adapter/src/logo.ts
Fixed the static file path collision in Jira
---
* It makes more sense that all adapters will do it similarly, so I added a function to adapter-utils and moved the okta solution to use it.
* The solution is based on the[ solution agreed upon in Okta](https://github.com/salto-io/salto/pull/6477) following a conversation with @netama 
* A change was done in jira to use the elemID name instead of the name in the value of the instance. It seems safer, as in some cases in Jira to API allows for two elements with the same name, and we can have different elemIDs for them (for instance if one of them was changed after starting to use Salto)
Added [noise reduction](https://github.com/salto-io/salto_private/pull/9244)
---
Jira Adapter:
* Fixed a potential bug with static file path …
=> SALTO-6517: fix static file path collision

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/custom_references/profiles_and_permission_sets.ts, packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts, packages/salesforce-adapter/src/fetch_profile/metadata_query.ts, packages/salesforce-adapter/src/fetch_profile/metadata_types.ts, packages/salesforce-adapter/src/fetch_profile/optional_features.ts, packages/salesforce-adapter/src/filters/settings_type.ts, packages/salesforce-adapter/src/filters/settings_types.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/src/transformers/xml_transformer.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/fetch_profile/metadata_query.test.ts, packages/salesforce-adapter/test/fetch_profile/metadata_types.test.ts, packages/salesforce-adapter/test/filters/settings_type.test.ts, packages/salesforce-adapter/test/filters/settings_types.test.ts, packages/salesforce-adapter/test/mock_elements.ts
Using retrieve API for fetching settings and moving it to the main fetch code (instead of in a filter).
Gated by the `retrieveSettings` optional feature.
---
WS diff: https://github.com/salto-io/ariel-small/commit/a719c02cddd0de90510c0fbae7d252aaf70b7731
Leaving improving the deploy code for a later PR, this one is getting pretty big.
---
_Salesforce_:
* Using the retrieve API for settings which returns slightly different results.
---
_Salesforce_:
* When enabling the `retrieveSettings` optional feature settings instances will have some slight changes.
=> SALTO-6898: Using retrieve API for settings

packages/zendesk-adapter/src/filters/handle_template_expressions.ts, packages/zendesk-adapter/test/filters/handle_template_expressions.test.ts
fix convertJsonIdsToReferences to work when json looks like this:
"id":"\<number\>"
---
---
---
=> SALTO-6919: fix convertJsonIdsToReferences

packages/jira-adapter/src/filters/sort_lists.ts, packages/jira-adapter/test/filters/sort_lists.test.ts
SALTO-6917 Jira: run sort-lists filter on relevant types only
---
None
---
None
---
None
=> SALTO-6917 Jira: run sort-lists filter on relevant types only

packages/salesforce-adapter/jest.config.js, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/filters/convert_maps.ts, packages/salesforce-adapter/src/filters/cpq/lookup_fields.ts, packages/salesforce-adapter/test/filters/convert_maps.test.ts, packages/salesforce-adapter/test/filters/cpq/lookup_fields.test.ts, packages/salesforce-adapter/test/resolve_changes.test.ts
(Bugfix) Salesforce picklistAsMaps feature does not work for environments with CPQ 
---
For environments that manage CPQ metadata, turning on the `picklistAsMaps` feature makes fetch fail violently. This PR exposes two issues in the adapter:
1. `convert_maps` filter should be able to key-by `ReferenceExpression` value.
2. If `OrderedMap` order value references value with unresolved references, the Element won't be fully resolved.
---
_None_
---
_None_
=> SALTO-6845: (Bugfix) Salesforce `picklistAsMaps` feature does not work for environments with CPQ

packages/salesforce-adapter/config_doc.md, packages/salesforce-adapter/src/filters/elements_url.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/elements_url.test.ts
It's no longer used.
---
None.
---
_Salesforce_:
* Deprecating the `elementsUrls` optional feature.
---
None.
=> SALTO-6901: Deprecating elements URLs optional feature

packages/salesforce-adapter/src/config_creator.ts
Fix default config creator for Salesforce Adapter in the CLI
---
Since the `configCreatorInput` instance is undefined, we created the instance with Profiles and PermissionSets included.
Opened a followup ticket: https://salto-io.atlassian.net/browse/SALTO-6925
---
_None_
---
_None_
=> SAAS-11665: Fix default config creator for Salesforce Adapter in the CLI

packages/salesforce-adapter/src/fetch_profile/optional_features.ts, packages/salesforce-adapter/src/transformers/reference_mapping.ts, packages/salesforce-adapter/src/types.ts
SALTO-6800 SALTO-6799 salesforce adapter - GenAi references
---
commit with the WS changes: https://github.com/Uri-Bar/salesforce1/commit/7b1d3ba747c3d79f47cd26700a9b4a01f9b9280e
---
none
---
SF: added references in GenAiPlugin and GenAiPlanner under the genAiReferences optionalFeatures
=> SALTO-6800 SALTO-6799 salesforce adapter - GenAi references

packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.state.test.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
In `nacl_files_source.ts` we need the current element IDs in each modified file. Instead of getting them by calling `elements()` that reads and deserialize all of the elements in the nacl file, we can use the `elementsIndex` that holds a mapping between `ElemID` and the files it's in.
This is currently disabled by default and can be enabled with an env var - `SALTO_CREATE_FILENAMES_TO_ELEMENT_IDS_MAPPING`
---
The change in the tests is the addition of `describe.each([false, true])` with the env var's value on all of the tests in each file.
---
Workspace:
- Reduce memory consumption when updating nacl files (enabled with an env var - `SALTO_CREATE_FILENAMES_TO_ELEMENT_IDS_MAPPING`)
---
None
=> Reduce memory consumption when updating nacl files

packages/cli/src/command_builder.ts, packages/cli/src/commands/workspace.ts, packages/cli/src/workspace/workspace.ts, packages/cli/test/commands/workspace.test.ts
Added workspace validate command to the CLI
---
The CLI output should appear as follows:
Valid workspace:
Workspace with errors:
Workspace with warnings:
---
CLI: 
Users can use the validate command as part of the workspace sub-commands. This command will indicate whether the workspace is valid or, if not, specify the errors or warnings and provide links to their locations.
---
_None_
=> SALTO 6824: Add workspace validate command to the CLI

packages/okta-adapter/src/adapter.ts, packages/okta-adapter/src/user_config.ts
As part of SALTO-6048, We added migration to migrate all existing envs to have `JWK` type in their exclude list
It has been long enough since, and all active envs are migrated, so it's safe to remove this now
---
---
None
---
None
=> SALTO-6048: Remove adding JWK to exclude list migration

packages/jira-adapter/src/adapter_creator.ts, packages/jira-adapter/src/config/config.ts, packages/jira-adapter/src/fix_elements/index.ts, packages/jira-adapter/src/weak_references/index.ts
Add the ability to disable / enable specific custom references funcs from Jira config
---
Added this ability as in certain large Jira envs we might create too many references
By default all custom reference func are enabled
Usage example - 
```
jira {
fetch = { ... }
customReferences = {
fieldConfigurationsHandler = false
}
}
```
---
None
---
None
=> SALTO-6939: Add the ability to disable custom references from config (Jira)

packages/e2e-credentials-store/index.ts, packages/e2e-credentials-store/package.json
This is the convention for other packages and will save the need for bespoke knip configuration.
---
Still need to address persistent-pool but it's giving me trouble.
---
None.
---
None.
=> SALTO-6213: Moving E2E creds store index to root

packages/cli/src/commands/deploy.ts, packages/cli/src/formatter.ts, packages/cli/src/prompts.ts, packages/cli/test/commands/deploy.test.ts, packages/core/index.ts, packages/core/src/core/deploy/deploy_summary.ts, packages/core/test/core/deploy/deploy_summary.test.ts
added post deployment summary to the cli
---
when deployment isn't fully successful, post deployment summary will be printed listing which elements where deployed successfully, which were partially successful and which have failed
---
CLI:
added post deployment summary
---
none
=> SALTO-1830 Post deploy message

packages/salesforce-adapter/src/change_validators/unknown_users.ts
SALTO-6620: Link SFDC CV user does not exist to help doc
---
_None_
---
_None_
=> SALTO-6620: Link SFDC CV user does not exist to help doc

packages/workspace/src/flags.ts, packages/workspace/src/workspace/dependents.ts, packages/workspace/src/workspace/nacl_files/nacl_file_update.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.state.test.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
When finding locations for changes, try to avoid creating a single source map. We suspect this single source map consumes a lot of memory.
Instead, try to group changes by which files that could be located in, and for each group create a source map just from the relevant file(s).
This is all behind a flag: SALTO_USE_SPLIT_SOURCE_MAP_IN_UPDATE
---
Some results from a reproduction with the dummy adapter - having 70 large files (~50k lines each).
Fetch with a single change per file:
  | Peak memory in relevant part | Time in code | Total fetch time
-- | -- | -- | --
Old code | before: 1014, peak: 2441.8, after: 965.7 | 16.25 | 122505 ms |  
New code | before: 948.5, peak: 1905.1 (mid run GC to 926.1), after: 1027.7 | 15.04 | 121357 ms |  
Fetch with many …
=> SALTO-6903: Avoid creating a unified source map for many files

packages/jira-adapter/src/constants.ts, packages/jira-adapter/src/filters/jsm_types_fetch_filter.ts, packages/jira-adapter/src/reference_mapping.ts, packages/jira-adapter/src/utils.ts, packages/jira-adapter/test/filters/jsm_types_fetch_filter.test.ts
Added references the the SLA's conditionId
---
See ticket.
JSM SLA has some conditions that can be defined. Some of them are for specific statuses, and they require reference in the conditioned field.
Also, I changed the deployment annotation for the name field, as changes to it will not change anything in the service
Noise reduction will follow
---
Jira Adapter:
* Added reference support to SLA's status conditions
---
Jira Adapter:
* SLA's conditioned can turn from a number to a reference
=> SALTO-6939: Add reference to SLA's conditionId

packages/salesforce-adapter/src/client/client.ts
Looks like we can get `undefined` here in some flows.
---
None.
---
None.
---
None.
=> SALTO-6946: Protecting unsafe call to toMD5

packages/microsoft-security-adapter/src/definitions/fetch/shared/fetch.ts
Convert 403 errors to fetch warnings
---
I saw we get 403 when we lack of permissions, we can iterate once we see more relevant status codes.
---
_Microsoft Security Adapter_:
- Create fetch warning for while detecting there are missing permissions during fetch
---
None
=> SALTO-6828: Convert MS security permission errors into warning

packages/zendesk-adapter/src/definitions/fetch/fetch.ts
It appears the tag id field was incorrectly defined when switching to the new infra.
---
* Fix warnings of the form "Error validating "zendesk.tag.instance.<>.id": Invalid value type for serviceid_number"
---
None
=> SALTO-6949 fix tag id field definition

packages/salesforce-adapter/src/change_validators/flows.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/test/change_validators/flows.test.ts
SALTO-5023: Do not allow Activating Flow of type InvalidDraft
---
---
_None_ 
---
_None_
=> SALTO-5023: Do not allow Activating Flow of type InvalidDraft

packages/jira-adapter/src/adapter_creator.ts, packages/jira-adapter/test/adapter_creator.test.ts
SALTO-5888 Jira DC: Fail on API-config with JSM on
---
None
---
None
---
None
=> SALTO-5888 Jira DC: Fail on API-config with JSM on

packages/dummy-adapter/src/generator.ts, packages/dummy-adapter/test/generator.test.ts
Added the option to simulate user elements in Dummy
---
With users configured in Dummy, the adapter will create
- User elements
- Group elements
- Group member elements containing references to users (controlled by `distributionFactor`)
---
None
---
None
=> SALTO-6852: Add the option to fetch user similar elements in Dummy

packages/microsoft-security-adapter/src/definitions/deploy/entra/deploy.ts
The current deploy definition, which uses the MS Graph v1.0 API, no longer works.
---
---
* Fix Administrative Unit deployment.
---
=> SALTO-6866: Switch MS Entra Administrative Unit deployment definition to use the beta API

packages/workspace/src/expressions.ts, packages/workspace/test/core/expressions.test.ts
When multiple fragments of the same element were passed, only one of them was resolved This fixes the code so we will resolve all the fragments
---
This still leaves a bit of "unstable" behavior in that if there are references point to the element which is split, we will resolve them to point to one of the fragments, we do not guarantee which one
---
_None_
---
_None_
=> SALTO-6963: fix resolve types when passing multiple fragments

packages/adapter-components/src/deployment/change_validators/check_deployment_based_on_definitions.ts, packages/adapter-components/test/deployment/change_validators/check_deployment_based_on_definitions.test.ts, packages/google-workspace-adapter/e2e_test/adapter.test.ts, packages/google-workspace-adapter/test/adapter.test.ts
This PR fixes a bug where types deployed by the old config were reported as not supporting deploy. The issue was that we checked if they were supported by the new definition config first, and instead of returning `undefined`, the query returned the default definitions which aren't enough to support deploy.
---
---
- Fixed a bug where some types were reported as not supporting deploy actions.
---
None
=> SALTO-6976: Fix wrong "unsupported deploy" errors caused by default definitions

packages/salesforce-adapter/test/filters/field_permissions_enum.test.ts
This is the last occurrence in the SF adapter.
---
---
None.
---
None.
=> SALTO-6916: Removing no-misused-promises from field permissions enum test

packages/salesforce-adapter/config_doc.md, packages/salesforce-adapter/src/fetch_profile/optional_features.ts, packages/salesforce-adapter/src/filters/custom_metadata_to_object_type.ts, packages/salesforce-adapter/src/filters/custom_objects_to_object_type.ts, packages/salesforce-adapter/src/filters/metadata_instances_aliases.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/custom_metadata_to_object_type.test.ts, packages/salesforce-adapter/test/filters/metadata_instances_aliases.test.ts
It's no longer in use.
---
---
_Salesforce_:
* Deprecating `skipAliases` optional feature.
---
None.
=> SALTO-6901: Deprecating `skipAliases` optional feature

packages/jira-adapter/src/filters/jsm_types_fetch_filter.ts
Crashed as ducktypes might not contain the conditioned field
---
None
---
Jira Adapter:
* fixed a bug in SLA references
---
None
=> SALTO-6978: Fix an SLA bug

packages/lowerdash/src/collections/tree_map.ts
See title
---
None
---
None
---
None
=> SALTO-6964: Re-export TreeMapEntry as it is used externally

packages/jira-adapter/src/filters/jsm_types_fetch_filter.ts, packages/jira-adapter/test/filters/jsm_types_fetch_filter.test.ts
Fixed CR comments from[ previous PR](https://github.com/salto-io/salto/pull/6841) + improved the logic as we are using ducktype we want to handle even a single type
---
I have decided to keep findObjects even though it is no longer in use, in case someone will want it in the future
---
None
---
None
=> SALTO-6978: PR for sla bug

packages/dummy-adapter/src/generator.ts, packages/dummy-adapter/test/generator.test.ts
Exclude config did not affect extra elements
---
Bug was introduced in https://github.com/salto-io/salto/pull/6833
---
_None_
---
_None_
=> SALTO-6964: fix dummy adapter exclude config

packages/jira-adapter/src/config/config.ts
Jira JSM: support assetsObjectFieldConfiguration by default
---
None
---
- JSM: support assetsObjectFieldConfiguration by default
---
None
=> SALTO-6159 Jira assets fields

packages/core/src/local-workspace/workspace.ts, packages/core/test/workspace/local/workspace.test.ts
None
---
Remove deprecated API of loadWorkspace - that was added here - https://github.com/salto-io/salto/pull/2895 ( over 2 years ago)
---
None
=> SALTO-6956: Remove deprecated loadWorkspace api

packages/salesforce-adapter/src/fetch_profile/optional_features.ts, packages/salesforce-adapter/src/filters/important_values_filter.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/important_values_filter.test.ts
It's no longer used.
---
---
None.
---
None.
=> SALTO-6901: Deprecating important values optional feature

packages/parser/src/parser/types.ts, packages/workspace/src/workspace/nacl_files/index.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/nacl_files/parsed_nacl_file.ts, packages/workspace/src/workspace/nacl_files/parsed_nacl_files_cache.ts, packages/workspace/test/common/nacl_file_source.ts, packages/workspace/test/common/nacl_file_store.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts, packages/workspace/test/workspace/nacl_files/parsed_nacl_files_cache.test.ts
Split `ParsedNaclFile` into two types:
- `ParsedNaclFile` returns getters that are non-async
- `CachedParsedNaclFile` returns getters that are async (same as current implementation of `ParsedNaclFile`)
Whenever possible use `ParsedNaclFile`, in order to remove redundant `await`s in the code.
---
---
Workspace:
- Reduce asynchronousity in nacl files update
---
None
=> Reduce asynchronousity in nacl files update

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/convert_maps.ts, packages/salesforce-adapter/test/filters/convert_maps.test.ts
Rename Salesforce OrderedMap type to not use container type syntax
---
_None_
---
_None_
=> SALTO-6904: Rename Salesforce OrderedMap type to not use container type syntax

packages/cli/src/commands/fetch.ts, packages/core/src/core/fetch.ts
---
in the past the changes here were an iterator
they are an array now, so there is no point in creating this copy
---
_None_
---
_None_
=> SALTO-6994: Avoid redundant copy of fetch changes

packages/salesforce-adapter/src/custom_references/profiles_and_permission_sets.ts, packages/salesforce-adapter/test/custom_references/profiles_and_permission_sets.test.ts
(Salesforce) Profiles & PS Elements fixer should omit default values from Instance
---
Prior to this PR the fixer didn't omit values where we don't create references for.
---
_None_
---
_None_
=> SALT-6999: (Salesforce) Profiles & PS Elements fixer should omit default values from Instance

packages/salesforce-adapter/src/change_validators/ordered_maps.ts, packages/salesforce-adapter/src/filters/convert_maps.ts
It should slightly improve performance.
---
This was originally implemented in https://github.com/salto-io/salto/pull/6827 but was reverted due to a bug in fetching profiles.
The bug was the extra `async` keyword in https://github.com/salto-io/salto/pull/6827/files#diff-616666620c2c1d68e89a7ac6aa5f3734f3a73fd036150009bca8124f97faa0bfR610. This is now removed.
---
None.
---
None.
=> SALTO-6954:  Removing some async calls from maps filter and CV

packages/jamf-adapter/src/definitions/fetch/fetch.ts
Omit `payloads` field in `os_x_configuration_profile` and in `mobile_device_configuration_profile`, as it contains a password and the whole field might be redundant
---
None
---
_Jamf_adapter_:
- Solve the issue of having users' passwords in configuration profile instances, within the `payload` field
---
Payloads field was omitted from `os_x_configuration_profile` and in `mobile_device_configuration_profile`
=> SALTO-6759 Jamf: omit payloads in configuration profiles

packages/zendesk-adapter/src/inactive.ts, packages/zendesk-adapter/test/inactive.test.ts
Omit explicitly inactive workspaces as they have a different indicator field
---
---
---
* Bug fix: inactive workspaces will be removed if omitInactive is set.
=> SALTO-7007 Omit inactive (not activated) workspaces

packages/salesforce-adapter/src/sfdx_parser/sfdx_dump.ts, packages/salesforce-adapter/src/sfdx_parser/sfdx_parser.ts, packages/salesforce-adapter/test/sfdx_parser/sfdx_dump.test.ts
The new settings filter no longer relies on the client so it works for SFDX.
---
Interestingly, we don't need to do anything pre-deploy because they way settings are deployed is super weird in SF.
---
_Salesforce_:
* Add support for settings types in SFDX.
---
None.
=> SALTO-2905: Supporting settings in SFDX

packages/salesforce-adapter/src/fetch_profile/optional_features.ts, packages/salesforce-adapter/src/transformers/reference_mapping.ts, packages/salesforce-adapter/src/types.ts
SALTO-7004: Add references from Network instances to EmailTemplates
---
Workspace Diff: https://github.com/salto-io/almog-sf/commit/902045fdd193a05d8c770e27bb619f1218bfe7f2?diff=unified
---
None
---
_Salesforce_:
Added references from Network to EmailTemplate instance under the feature **networkReferences** in **optionalFeatures**
=> SALTO-7004: Add references from Network instances to EmailTemplates

packages/jamf-adapter/src/definitions/fetch/fetch.ts
SALTO-6759 Jamf: revert omitting payloads in configuration profiles - will mask the relevant password instead
---
https://github.com/salto-io/salto/pull/6875
---
None
---
None
=> SALTO-6759 Jamf: revert omitting payloads in configuration profiles

packages/adapter-api/src/comparison.ts, packages/adapter-api/src/element_id.ts
Before this change, the string with the full name of the element ID was always created even if it was never used Changed this to create the string the first time it is needed.
---
Tested this with a dummy adapter fetch that created a very large number of detailed changes.
This change reduced peak memory consumption from ~7.9GB to 6.9GB 
Based on #6866 and #6880
---
Core:
- Improvements to memory consumption when working with large numbers of changes
---
_None_
=> SALTO-6991: create element ID full name only if needed

packages/microsoft-security-adapter/src/constants/entra.ts, packages/microsoft-security-adapter/src/definitions/fetch/entra/fetch.ts
Add service url to specific Entra instances.
Some types requires service url customization (for example we need the negation of some value in the url), which is not supported yet.
---
* Add service url to specific Entra instances.
---
=> SALTO-6969: Add service URL support for Microsoft Entra elements

packages/workspace/src/validator.ts, packages/workspace/test/validator.test.ts
When there's a missing required field, we currently return the error on the missing field's elemID itself, which means that we can't get the location of the error in a nacl file (since it doesn't exist). In that case we should return the `MissingRequiredFieldValidationError` error on the parent elemID.
In case of an empty list, we return the same error if the field is required. In that case we still return the elemID of the list, because it exists.
---
---
None
---
None
=> SALTO-7021 return missing required field validation error on the parent elemID

knip.json, packages/element-test-utils/package.json
The exports section in the package pointed to files that were not exported
---
---
_None_
---
_None_
=> SALTO-6995: fix element-test-utils export

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/sfdx_parser/sfdx_dump.ts
This is required for OrderedMaps.
---
---
None.
---
None.
=> SALTO-7024: Using custom resolver in SFDX dump

packages/netsuite-adapter/e2e_test/adapter.ts, packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/adapter_creator.ts, packages/netsuite-adapter/src/config/config_creator.ts, packages/netsuite-adapter/src/config/validations.ts, packages/netsuite-adapter/src/sdf_folder_loader.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/adapter_creator.test.ts, packages/netsuite-adapter/test/config/config_creator.test.ts
The config suggestions should be on the config instance that the adapter receives from core, without the modifications that are done in `config_creator`, otherwise we might return a modification to a field that was override using a config override, which isn't allowed.
---
---
- Fix NS config suggestions when there are config overrides
---
None
=> Fix NS config suggestions when there are config overrides

packages/element-test-utils/package.json, packages/element-test-utils/src/all.ts, packages/element-test-utils/src/custom_equality.ts
Also export "allEqualityTesters" as an array so if more are added in the future, depending packages won't have to change
---
---
_None_
---
_None_
=> SALTO-6995: fix element test utils types path

packages/salesforce-adapter/src/fetch_profile/optional_features.ts, packages/salesforce-adapter/test/adapter.discover.test.ts
Disable Salesforce features that should be part of the next PROD release due to regression.
---
_None_
---
_None_
=> SALTO-7036: Disable Salesforce features 

packages/zendesk-adapter/src/filters/ticket_form.ts, packages/zendesk-adapter/test/filters/ticket_form.test.ts
add end_user_conditions and agent_conditions fields if they are missing from the form during deploy
---
---
---
=> SALTO-7037: add end_user_conditions and agent_conditions fields if they are missing from the form during deploy

packages/microsoft-security-adapter/src/client/oauth.ts
Currently, the OAuth flow for connecting to MS Security fails if the user is logged into Microsoft with a different account than the one they wish to use for authentication.
This PR enforces the OAuth flow to prompt the user to select the account they want to authenticate with.
---
---
* Enforce MS Security OAuth flow to select an account
---
None
=> SALTO-7039: Enforce MS Security OAuth flow to select an account

packages/local-workspace/jest.config.js, packages/local-workspace/src/s3_dir_store.ts
Related to an issue where S3 returned an empty content.
---
---
---
=> Add s3 logs for error visibility

packages/salesforce-adapter/src/filters/fetch_targets.ts, packages/salesforce-adapter/test/filters/fetch_targets.test.ts
SALTO-7040: Salesforce fetchTargets filter should not run in partial fetch
---
_None_
---
_None_
=> SALTO-7040: Salesforce fetchTargets filter should not run in partial fetch

packages/jamf-adapter/src/definitions/fetch/transforms/configuration_profile.ts, packages/jamf-adapter/src/definitions/fetch/transforms/policy.ts, packages/jamf-adapter/src/definitions/fetch/transforms/utils.ts, packages/jamf-adapter/test/definitions/fetch/transform/configuration_profile.test.ts, packages/jamf-adapter/test/definitions/fetch/transform/policy.test.ts, packages/jira-adapter/src/filters/masking.ts
Mask passwords within policy scripts and configuration_profiles payloads
---
---
_Jamf_adapter_:
- Mask passwords within policy scripts and configuration_profiles payloads
---
Passwords within policy scripts and configuration_profiles payloads will be masked
=> SALTO-6759 Jamf: mask passwords

packages/workspace/src/serializer/elements.ts, packages/workspace/test/serializer/serializer.test.ts
When serializing element IDs and Fields, only write the attributes that are needed to deserialize
---
On an example workspace (relatively small salesforce environment) - this reduced the overall size of the cache (rocksdb)  from 21MB to 14MB
most likely, this would mostly scale with the number of references in the workspace...
---
Core:
- Reduced size of state file and cache
---
_None_
=> SALTO-6166: Avoid serializing redundant values

packages/core/src/core/fetch.ts, packages/core/src/core/flags.ts, packages/core/src/core/plan/group.ts, packages/core/test/core/plan/plan.test.ts, packages/dag/src/group.ts, packages/dag/test/group.test.ts, packages/workspace/src/flags.ts
Delete the following flags:
`SALTO_SKIP_RESOLVE_TYPES_IN_ELEMENT_SOURCE`
`SALTO_AUTO_MERGE_LISTS_DISABLE`
`SALTO_FAIL_PLAN_ON_CIRCULAR_DEPENDENCY`
`SALTO_USE_OLD_DEPENDENTS_CALCULATION`
---
---
Core:
- Delete old Salto flags
---
None
=> SALTO-7051 Delete old Salto flags

packages/netsuite-adapter/scripts/types_generation/types_generator.py, packages/netsuite-adapter/src/autogen/types/standard_types/reportdefinition.ts, packages/netsuite-adapter/src/autogen/types/standard_types/role.ts, packages/netsuite-adapter/src/autogen/types/standard_types/savedsearch.ts, packages/netsuite-adapter/src/type_parsers/report_definition_parsing/parsed_report_definition.ts, packages/netsuite-adapter/src/type_parsers/saved_search_parsing/parsed_saved_search.ts
The code that was added to `types_generator.py` wasn't really tested, but only added so it won't get overridden next time we will generate types.
I used https://app.datadoghq.com/logs?query=status%3Awarn%20RegexMismatchValidationError%20-%2Areportdefinition%2A%20-%2Acustomsearch%2A%20-%2Acustomrole%2A&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1733300418316&to_ts=1733905218316&live=true in order to find which elements suffer from the issue.
---
---
---
_Replace me with a short sentence that describes …
=> SALTO-7054: NS: Avoid having RegexMismatchValidationError warning for apparently valid scriptIds

packages/cli/test/commands/adapter_format.test.ts, packages/cli/test/commands/fetch.test.ts, packages/core/src/api.ts, packages/core/src/core/adapter_format.ts, packages/core/src/types.ts, packages/core/test/core/adapter_format.test.ts, packages/core/test/core/fetch.test.ts
_add pariallyFetchedAccounts to FetchResult_
---
The motivation is to differ between fetch operation types in the backend (full, custom or changed based).
partiallyFetchAccounts is filled with accounts that do any kind of a partial fetch, and we want to expose it to the SAAS.
---
_Core_:
* `FetchResult` will contain `partiallyFetchedAccounts` to differentiate between partial and full fetches.
---
_None_
=> SALTO-7049: add pariallyFetchedAccounts to FetchResult

packages/adapter-utils/src/compare.ts, packages/adapter-utils/test/compare.test.ts, packages/cli/test/commands/element.test.ts, packages/core/src/api.ts, packages/core/src/core/rename.ts, packages/core/test/api.test.ts, packages/core/test/core/rename.test.ts, packages/workspace/src/workspace/adapters_config_source.ts, packages/workspace/src/workspace/hidden_values.ts, packages/workspace/src/workspace/nacl_files/addition_wrapper.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/nacl_files/multi_env/projections.ts, packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/src/workspace/nacl_files/nacl_file_update.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/common/nacl_file_source.ts, packages/workspace/test/workspace/hidden_values.test.ts, packages/workspace/test/workspace/multi_env/multi_env_source.test.ts, packages/workspace/test/workspace/multi_env/projections.test.ts, packages/workspace/test/workspace/multi_env/routers.test.ts, packages/workspace/test/workspace/nacl_files/nacl_file_update.test.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts, packages/workspace/test/workspace/workspace.test.ts
we expect the input changes in `updateNaclFiles` to have `baseChange` in them (`DetailedChangeWithBaseChange`). this is trivial in most places because the core returns `DetailedChangeWithBaseChange[]` in most of its flows, but in some places we were building new `DetailedChange[]` and there we should make sure that they have `baseChange` too.
---
---
None
---
None
=> SALTO-6278 ensure that updateNaclFiles get detailedChanges with baseChange in them

packages/adapter-api/src/adapter.ts
This will be used in https://github.com/salto-io/salto/pull/6921
---
---
Adapter API:
- add `additionallyInstalledVersions` to `AdapterSuccessInstallResult`
---
None
=> SALTO-7045 add `additionallyInstalledVersions` to `AdapterSuccessInstallResult`

packages/salesforce-adapter/src/adapter.ts
SALTO-4230: Extract DiscoveryAIModel content to a static file
---
Retrieve already includes functionality for extracting content of instance into a static file [here](https://github.com/salto-io/salto/blob/fad42b019fdd1370af9c3c689d37862da1cf6d7b/packages/salesforce-adapter/src/transformers/xml_transformer.ts#L447C9-L447C36).
This PR adds the discoveryAIModel to Retrieve.
---
Workspace Diff: https://github.com/salto-io/almog-sf/commit/3dc65d070328a0e8c63384226fbab9fa675a2a49
---
- Extract DiscoveryAIModel content to a static file.
---
- Content field in DiscoveryAIModel instances will be converted to static files.
- New static files will be created.
=> SALTO-4230: Extract DiscoveryAIModel content to a static file

packages/workspace/src/workspace/elements_source.ts, packages/workspace/src/workspace/nacl_files/elements_cache.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/elements_source.test.ts, packages/workspace/test/workspace/workspace.test.ts
The override mechanism is replaced by fixing the original element source to return the correct result The issue that the override mechanism was there to solve was that if a field was removed from NaCl, we should remove the hidden part of the field as well.
This didn't work in the original code because the state element source would try to merge it with the element from the workspace cache but the element in the workspace cache was not updated yet, so it still had that field.
Changing the element source to use the element from the nacl cache instead (which is updated before) should solve the issue
---
It seems like the original issue that the overrides code solves was never actually covered in unit tests, I did verify it manually and added the missing unit …
=> SALTO-7047: Improve performance of workspace update

packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/utils.test.ts, packages/cli/src/commands/deploy.ts
The deploy summary in the CLI was incorrect when changes were not fully applied
---
---
CLI:
- Fixed issue where deploy summary would not show failed or partially successful changes correctly
---
_None_
=> SALTO-7058: Fix CLI deploy summary

packages/microsoft-security-adapter/jest.config.js, packages/microsoft-security-adapter/src/client/connection.ts
Logging the error message doesn't provide the information needed, so we log the response data instead. We don't expect MS to return secrets in this response.
For example, when failing to retrieve the access token due to MFA enabled. 
When logging only the message we get:
`Failed to get access token, error: {"message":"Request failed with status code 400","status":400}, stack: AxiosError: Request failed with status code 400`
However, when we log the error response data we get:
`Failed to get access token, error: {"data":{"error":"invalid_grant","error_description":"AADSTS50158: External security challenge not satisfied. User will be redirected to another page or authentication provider to satisfy additional authentication challenges. Trace ID: <ID> Correlation ID: <ID> Timestamp: …
=> SALTO-6841: Log error data when getAccessToken fails for Microsoft Security

packages/core/src/core/fetch.ts, packages/core/test/core/fetch.test.ts
(Bug-fix) Fetch-From with `fromState` with addition of static file causes pending change
---
See comments.
---
_Core_:
- (Bug-fix) Fetch-From with `fromState` with addition of static file causes pending change.
---
_None_
=> SALTO-7065: (Bug-fix) Fetch-From with `fromState` with addition of static file causes pending change

packages/salesforce-adapter/src/change_validators/instance_with_unknown_type.ts
update error message when type is unknown
---
update error message when type is unknown to suggest the customer look at account/org settings
---
none
---
none
=> SALTO-6542 - salesforce - update error message when type is unknown

packages/okta-adapter/src/definitions/fetch/fetch.ts, packages/okta-adapter/src/definitions/fetch/types/application.ts, packages/okta-adapter/src/filters/app_logo.ts
The Okta Dashboard app is a singleton - only one of its type is allowed. However, it has an autogenerated `id` from the service, and we use its label as the element ID, which users can change. We want the element ID to be fixed, so that deploying Okta Dashboard app changes between environments where that app's label was changed, to modify the correct app and not apply an add+remove change (which is disallowed by the service).
This PR also fixes a bug in computing `AppLogo` element IDs (which are based on their parent app ID) - before this fix, element IDs for `AppLogo`s were always recomputed regardless of whether `--regenerate-salto-ids` was supplied or not.
---
I manually tested that running `fetch` without `--regenerate-salto-ids` results in zero …
=> SALTO-7068: Set a hardcoded element ID for the Okta Dashboard app

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/fetch_profile/optional_features.ts, packages/salesforce-adapter/src/filters/add_parent_to_instances_within_folder.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/add_parent_to_instances_within_folder.test.ts, packages/salesforce-adapter/test/mock_elements.ts
SALTO-7020: Add parent relationship to metadata instances within folders
---
Workspace Diff: https://github.com/salto-io/almog-sf/commit/87210277c3ecd008ba1df96b7b8762a94be85c76
---
- Add parent relationship to instances within folders.
---
- **_parent** annotation will be added to some of the instances that are within Folders, instances of types:
- EmailTemplate
- Report
- Document
- Dashboard
=> SALTO-7020: Add parent relationship to metadata instances within folders

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/test/fetch_with_changes_detection.test.ts
(Bug-fix) Salesforce CBF with `retrieveSettings` leads to merge Errors
---
The merge errors were due to the fact the subtypes of the settings were fetched in CBF and were also included in the Elements source.
---
_None_
---
_None_
=> SALTO-7031: (Bug-fix) Salesforce CBF with `retrieveSettings` leads to merge Errors

packages/salesforce-adapter/src/filters/convert_maps.ts, packages/salesforce-adapter/test/filters/convert_maps.test.ts
This will give us consistent ordering in SFDX and shouldn't affect deployments (the current order we send is basically random).
---
---
_Salesforce_:
* Consistent ordering for values in SFDX which are represented in NaCl using maps (e.g. profiles).
---
None.
=> SALTO-6830: Sorting converted map values in pre deploy

packages/cli/src/commands/adapter_format.ts, packages/dummy-adapter/jest.config.js, packages/dummy-adapter/package.json, packages/dummy-adapter/src/adapter_creator.ts, packages/dummy-adapter/test/adapter_creator.test.ts, packages/dummy-adapter/test/generator.test.ts, packages/dummy-adapter/tsconfig.json, yarn.lock
This is rebased on [https://github.com/salto-io/salto/pull/6853 &](https://github.com/salto-io/salto/pull/6944)
Keeping this in draft until the above is merged.
So please only review the last commit
---
None
---
None
---
None
=> SALTO-6955: Support all adapter format methods in dummy adapter

eslint.config.mjs
Add rules to prevent importing from files that are not distributed to NPM
---
---
_None_
---
_None_
=> SALTO-7076: Add lint rules to prevent invalid imports

packages/adapter-components/src/references/field_references.ts
For easier debugging when `serialize` returns undefined
---
---
None
---
None
=> SALTO-7080: Log when resolving ref to undefined

packages/jira-adapter/src/change_validators/field.ts, packages/jira-adapter/src/change_validators/index.ts, packages/jira-adapter/src/config/config.ts, packages/jira-adapter/test/change_validators/field.test.ts
Added a field validator to prevent deployment of a searcherKey value for the field type 'textfield':
searcherKey = 'com.atlassian.jira.plugin.system.customfieldtypes:exacttextsearcher'
type = 'com.atlassian.jira.plugin.system.customfieldtypes:textfield'
---
---
- Added new CV to prevent deployment of JIM field
---
=> SALTO-6594: Add a CV to prevent deployment of JIM field

packages/jira-adapter/src/filters/filter.ts, packages/jira-adapter/test/filters/filter.test.ts
Added support to deploy filter's owners (addition or modification)
---
---
- Support deployment of Filter's owners in Jira
---
=> SALTO-5462: Support deployment of Filter's owners

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/static_resource_zip_timestamps.ts, packages/salesforce-adapter/test/filters/static_resource_zip_timestamps.test.ts, salto.code-workspace
Currently we get a diff when comparing two identical SFDX projects because the zip is built dynamically and the timestamps within zip files are different.
---
---
None.
---
None.
=> SALTO-7078: Override zip timestamps in static resources in SFDX flow

packages/salesforce-adapter/src/filters/picklist_references.ts
Change noisy SF warn log severity to trace
---
_None_
---
_None_
=> SALTO-7091: Change noisy SF warn log severity to trace

packages/okta-adapter/e2e_test/adapter.test.ts, packages/okta-adapter/e2e_test/mock_elements.ts, packages/okta-adapter/src/change_validators/standard_role_deployments.ts, packages/okta-adapter/src/definitions/deploy/deploy.ts, packages/okta-adapter/src/definitions/deploy/types/roles.ts, packages/okta-adapter/src/definitions/fetch/fetch.ts, packages/okta-adapter/src/filters/standard_roles.ts, packages/okta-adapter/test/adapter.test.ts, packages/okta-adapter/test/change_validators/standard_role_deployments.test.ts, packages/okta-adapter/test/mock_replies/role_add.json, packages/okta-adapter/test/mock_replies/role_modify.json, packages/okta-adapter/test/mock_replies/role_remove.json
Add a proper support in Okta's custom roles
---
Until now, we only fetched the name and description of the role, with no deploy support.
This PR adds the permission field for roles + support deploying those
Standard roles are not deployable and blocked using a validator.
This PR rebased on top of https://github.com/salto-io/salto/pull/6933, only the last commit is relevant
---
- Add deploy support for Custom Roles
---
- Custom roles elements will now include their permissions
=> SALTO-4062: Support Custom Roles in Okta

packages/workspace/src/workspace/workspace.ts
When a workspace function needs to rebuild the inner state, it should not return before the state is updated
---
---
_None_
---
_None_
=> SAAS-11932: Fix workspace functions return too early when updating inner state

packages/jira-adapter/src/filters/workflow_scheme.ts, packages/jira-adapter/test/filters/workflow_scheme.test.ts
Current situation creates partial success for deployments and triggers an incident
---
I decided to do the long way, and properly clone the change before deployment. That is the correct behavior and the one used in the deployment function, and I think it reduces future potential issues
[Noise reduction](https://github.com/salto-io/salto_private/pull/10078)
---
Jira Adapter:
* Deployments of Workflow Schemes with migration will not end in partial success
---
None
=> SALTO-7087: keep statusMigrations when deploying workflowScheme

packages/zendesk-adapter/src/config.ts, packages/zendesk-adapter/src/filters/ticket_form.ts, packages/zendesk-adapter/src/fix_elements/fix_ticket_forms.ts, packages/zendesk-adapter/src/fix_elements/index.ts, packages/zendesk-adapter/src/user_config.ts, packages/zendesk-adapter/test/filters/ticket_form.test.ts, packages/zendesk-adapter/test/fix_elements/fix_ticket_forms.test.ts
move fixedTicketFormChanges from filter to a fixer
---
---
---
=> SALTO-7079: move fixedTicketFormChanges from filter to a fixer

packages/salesforce-adapter/src/custom_references/handlers.ts
Enable Salesforce Profiles & PS elements fixer by default
---
_None_
---
_None_
=> SALTO-7099: Enable Salesforce Profiles & PS elements fixer by default 

packages/netsuite-adapter/scripts/types_generation/types_generator.py, packages/netsuite-adapter/src/autogen/types/standard_types/reportdefinition.ts, packages/netsuite-adapter/src/type_parsers/report_definition_parsing/parsed_report_definition.ts
---
---
SALTO-7108:  Modify ReportDefinition scriptId regex is to be less restrictive
---
=> SALTO-7108: NS - ReportDefinition scriptId regex is too restrictive

packages/salesforce-adapter/src/adapter_creator.ts, packages/salesforce-adapter/src/types.ts
This also reduces the severity of listing a CV that doesn't exist from an error to a warning.
---
---
_Salesforce_:
* Added support for listing deprecated CVs in deploy config.
* Reduced the severity of listing a CV that doesn't exist in the delpoy config from an error to a warning.
---
None.
=> SALTO-7105: Supporting deprecated CVs in config

packages/salesforce-adapter/src/change_validators/default_rules.ts, packages/salesforce-adapter/test/change_validators/default_rules.test.ts
fixed bug of defaultRules CV catches permission Sets
---
validating metadata types that have no defaults in their recordTypeVisibilities raised errors by defaultRules CV, now fixed to check only recordTypeVisibilities of Profiles
---
none
---
none
=> SALTO-7101-salesforce - fixed bug of defaultRules CV catches permission Sets

packages/jira-adapter/e2e_test/instances/cloud/board.ts, packages/jira-adapter/e2e_test/instances/datacenter/board.ts, packages/jira-adapter/src/change_validators/boards/board_column_config.ts, packages/jira-adapter/src/change_validators/boards/kanban_board_backlog.ts, packages/jira-adapter/src/change_validators/index.ts, packages/jira-adapter/src/config/config.ts, packages/jira-adapter/src/constants.ts, packages/jira-adapter/src/filters/board/board_columns.ts, packages/jira-adapter/test/change_validators/boards/board_column_config.test.ts, packages/jira-adapter/test/change_validators/boards/kanban_board_backlog.test.ts, packages/jira-adapter/test/filters/board/board_columns.test.ts, packages/jira-adapter/test/filters/board/board_deployment.test.ts
Fixed a bug in which we used to delete the backlog column of boards
---
This PR is split to 2 commits, the first one is relocation for some functions.
In kanban boards there are columns. They have a special built-in column called `Backlog` that is always the first column. Unfortunately, you can also add another column called the same way. 
The bug here resulted from a wrong bug fix in the past.
Fetch for Boards is the official API, but modify is private API.  As part of the private API there is a field called `isKanPlanColumn`, which is true for the built-in Backlog, and false for the rest (from what I saw).
If you deploy without `isKanPlanColumn` you will deploy that Backlog column as a user added `Backlog` column.
In the past we did that and created unwanted columns for users. The fix …
=> SALTO-7104 Kanban board backlog

packages/adapter-utils/src/collisions.ts, packages/adapter-utils/test/collisions.test.ts
---
an example of the new detailedMessage: 
```
2 salto elements and their child elements were not fetched, as they were mapped to a single ID salto.obj.instance.test:
[aliasName](someUrl), [aliasName](someUrl)
Usually, this happens because of duplicate configuration names in the service. Make sure these element names are unique, and try fetching again.
[Learn about additional ways to resolve this issue](https://help.salto.io/en/articles/6927157-salto-id-collisions)
```
---
---
_Replace me with a short sentence that describes changes that will appear in NaCls and are …
=> SALTO-7095: add getAndLogCollisionWarningsV2

packages/adapter-components/jest.config.js, packages/adapter-components/src/resolve_utils.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts, packages/zendesk-adapter/src/filters/article/article_body.ts, packages/zendesk-adapter/src/filters/macro_attachments.ts
As part of an issue with content received undefined without knowing the source, adding some logs for this case.
---
---
---
=> INCIDENT-27037 Add logs for undefined static file content

packages/salesforce-adapter/src/adapter.ts
Calculate Salesforce Data Instances service URL before creating collision warnings
---
Simply reordered the filters.
---
_None_
---
_None_
=> SALTO-7134: Calculate Salesforce Data Instances service URL before creating collision warnings

packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/test/client/sdf_client.test.ts
Return a cleaner SDF error message - without warnings that aren't part of the error.
---
---
- Remove warnings from SDF error message
---
None
=> Remove warnings from SDF error message

packages/core/src/api.ts, packages/core/test/api.test.ts
Elements Fixer should receive Elements with resolved types.
---
Simply invoking `resolveTypeShallow` on the Workspace Elements.
---
_Core_:
- Element fixers will now receive Elements with resolved types.
---
_None_
=> SALTO-7139 SALTO-6602: Elements Fixer should receive Elements with resolved types

packages/adapter-components/src/deployment/deploy/subresources.ts, packages/adapter-components/test/deployment/deploy/subresources.test.ts
Fix a bug in `recurseIntoPath` that can happen when referenceResolution strategy is "on_demand"
---
(This has no affect on any current definitions)
This can happen when the references are resolved "late" in flow.
---
None
---
None
=> SALTO-7149: Fix deployment of array fields in adapters infra when there are references

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/fetch_profile/optional_features.ts, packages/salesforce-adapter/src/filters/add_parent_to_record_triggered_flows.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/add_parent_to_record_triggered_flows.test.ts
SALTO-7117: Add parent relationship to Record-Triggered Flows
---
Workspace Diff: https://github.com/salto-io/almog-sf/commit/7587794e26f5e0b5c3aa65e0a72b689297c81edc
---
- Add parent relationship to Record-Triggered Flows.
---
- **_parent** annotation will be added to Record-Triggered Flows.
=> SALTO-7117: Add parent relationship to Record-Triggered Flows

packages/salesforce-adapter/config_doc.md
SALTO-6988: Salesforce adapter config documentation saltoIdSettings overrides example is misleading
---
None
---
None
=> SALTO-6988: Salesforce adapter config documentation saltoIdSettings overrides example is misleading

packages/adapter-components/src/definitions/system/index.ts, packages/okta-adapter/src/adapter.ts, packages/okta-adapter/src/constants.ts, packages/okta-adapter/src/definitions/deploy/deploy.ts, packages/okta-adapter/src/definitions/deploy/types/user_roles.ts, packages/okta-adapter/src/definitions/fetch/fetch.ts, packages/okta-adapter/src/filters/removed_user_roles_assignments.ts, packages/okta-adapter/src/reference_mapping.ts, packages/okta-adapter/src/user_config.ts, packages/okta-adapter/src/user_utils.ts, packages/okta-adapter/test/adapter.test.ts, packages/okta-adapter/test/filters/removed_user_roles_assignments.test.ts, packages/okta-adapter/test/mock_replies/user_role_add.json, packages/okta-adapter/test/mock_replies/user_role_modify.json, packages/okta-adapter/test/mock_replies/user_role_remove.json
Add support in user-role assignments in Okta
---
- `UserRoles` is an instance listing all roles of a single user
- As users are excluded by default, `UserRoles` will be excluded by default as well. I created a migration to add the type into the exclude list, the migration should be deleted once all exiting environments were fetched.
- On fetch:
- Instead of iterating all users and getting their roles, we call an endpoint that returns only users with assigned roles
- Then for each returned user, we make a request to get its roles
- Each assignment has an assignment id which is omitted, cause hidden values are not supported in lists.
- On deploy:
- in order to remove user-role assignment, we must specify the assignment id. As we don't keep the ids on the …
=> SALTO-2737: Support User Roles in Okta

packages/zendesk-adapter/src/definitions/fetch/fetch.ts, packages/zendesk-adapter/src/filters/add_alias.ts
As a result of cases where the raw_name is a dynamic content, the `raw_name` field is not a good fit for alias.
---
---
---
=> SALTO-7160 Change to more robust alias field

packages/microsoft-security-adapter/src/filters/entra/app_role.ts, packages/microsoft-security-adapter/test/filters/entra/app_role.test.ts
We should clone the instances received from the `elementSource` before we apply any changes on them.
---
* Fix pending changes on the app role id post addition
---
None
=> SALTO-7169: Fix Entra app roles addition results in pending changes on the app role id

packages/zendesk-adapter/src/dependency_changers/modified_and_deleted.ts, packages/zendesk-adapter/test/dependency_changers/modified_and_deleted.test.ts
I created a new faulty theme, changed `live_theme` to point there and deleted the current live theme.
Before I got the errors:
```
Errors:
○ zendesk.theme.instance.SeroussiTest_Copenhagen: InvalidTemplates - Template(s) with syntax error(s)
○ zendesk.theme.instance.SeroussiTest_Copenhagen2: Error: Failed to delete /api/v2/guide/theming/themes/50b3cc11-5c0a-4142-86e8-927288956c84 with error: Request failed with status code 400
{
"errors": [
{
"title": "Cannot delete live theme",
"code": "LiveThemeDeleted",
"status": "400",
"meta": {}
}
]
}
○ zendesk.theme_settings.instance.SeroussiTest_settings: Element was not deployed, as it depends on theme which failed to deploy
```
After I got the errors:
```
Errors:
○ zendesk.theme.instance.SeroussiTest_Copenhagen: InvalidTemplates - Template(s) with …
```
=> SALTO-7145 Add theme settings and guide theme dependency

packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/change_validator.ts, packages/netsuite-adapter/src/change_validators/bundle_changes.ts, packages/netsuite-adapter/src/change_validators/locked_custom_record_types.ts, packages/netsuite-adapter/src/change_validators/remove_sdf_elements.ts, packages/netsuite-adapter/src/config/types.ts, packages/netsuite-adapter/src/constants.ts, packages/netsuite-adapter/src/filters/add_important_values.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/change_validators/bundle_changes.test.ts, packages/netsuite-adapter/test/change_validators/locked_custom_record_types.test.ts, packages/netsuite-adapter/test/change_validators/remove_sdf_elements.test.ts, packages/netsuite-adapter/test/filters/add_important_values.test.ts
Make locked custom record types visible (with adapter config `visibleLockedCustomRecordTypes`). the locked custom record types will have the `isLocked` annotation, and there's a CV that prevents deploying any changes to them.
---
---
- make locked custom record types visible (with adapter config `visibleLockedCustomRecordTypes`).
---
- with the adapter config `visibleLockedCustomRecordTypes`, locked custom record types will be visible in the workspace, with the `isLocked = true` annotation.
=> SALTO-6781 make locked custom record types visible

packages/netsuite-adapter/src/config/validations.ts, packages/netsuite-adapter/test/config/validations.test.ts
Validate that the `singletonCustomRecords` is a list of valid regexes.
---
---
None
---
None
=> SALTO-7084 validate singletonCustomRecords config

packages/salesforce-adapter/src/client/user_facing_errors.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/test/adapter.crud.test.ts, packages/salesforce-adapter/test/client.test.ts
SALTO-6922: Map "Invalid dashboard Unique Name" deploy error to a link explaining that dashboards might be excluded
---
New error message:
---
None
---
None
=> SALTO-6922: Map "Invalid dashboard Unique Name" deploy error to a link explaining that dashboards might be excluded

packages/okta-adapter/src/definitions/deploy/deploy.ts, packages/okta-adapter/src/definitions/deploy/types/authorization_servers.ts, packages/okta-adapter/src/definitions/fetch/fetch.ts, packages/okta-adapter/test/adapter.test.ts, packages/okta-adapter/test/mock_replies/authorization_server_default_claim_add.json
In order to complete the support in Authorization servers in Okta, we need to handle deploy of new claims
---
This PR fixes leftovers remained from https://github.com/salto-io/salto/pull/6712
We need to allow creation of claims together with newly added auth server, for this, we need to handle "additions" of default claims, that are auto created when the auth server is created.
There are 2 types of default claims -
- The "sub" claim, which is auto created, visible in the UI, and can be modified after creation
- "SYSTEM" claims, that are auto created, are not visible in Okta UI, and can't be modified
This PR supports "additions" of the "sub" claim, and removes the "SYSTEM" claims entirely (from fetch as well), as there is no need to show objects that are …
=> SALTO-5282: Complete support in Authorization Servers in Okta

packages/netsuite-adapter/src/constants.ts, packages/netsuite-adapter/src/data_elements/suiteql_table_elements.ts, packages/netsuite-adapter/src/filters/analytics_definition_handle.ts, packages/netsuite-adapter/src/type_parsers/analytics_parsers/analytics_constants.ts, packages/netsuite-adapter/test/filters/analytics_tests_constants.ts
Builtin fields can be referenced in data instances & custom record instances. They are referenced by their internalID, but I couldn’t find the SuiteQL table to query them from. Instead, it looks like their internalIDs are static and the same across accounts, so we can add a static mapping for them.
In order to resolve them, the user need to add the following to their adapter config:
```
netsuite {
...
suiteAppClient = {
additionalSuiteQLTables = [
...
{
name = "fieldType"
typeId = "-213"
},
]
}
}
```
Resolving it automatically will be done in a future PR, in order to make it less noisy.
---
---
- Resolve ASVs for referenced builtin field types
---
- Resolve ASVs for referenced …
=> SALTO-7063 Resolve ASVs for referenced builtin field types

packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/test/client.test.ts
SALTO-5055: Salesforce cleanup outdated TopicForObjects read error suppression
---
None
---
None
=> SALTO-5055: Salesforce cleanup outdated TopicForObjects read error suppression

packages/salesforce-adapter/src/fetch_profile/optional_features.ts, packages/salesforce-adapter/src/filters/add_parent_to_record_triggered_flows.ts, packages/salesforce-adapter/src/transformers/reference_mapping.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/add_parent_to_record_triggered_flows.test.ts, packages/salesforce-adapter/test/filters/field_references.test.ts
SALTO-6375: Removed from optional features, reference from FlowAssignmentItem (Flows) to CustomField
---
Workspace Diff: https://github.com/salto-io/almog-sf/commit/d454106f2ae78cd0c9169bbbdfee6a886b4d0d68
---
- Improved IA between Flows and CustomFields.
---
- References will be added from FlowAssignmentItem (Flows) to CustomField.
- **_parent** annotation will be added to Record-Triggered Flows.
- **_generated_dependencies** will be removed from Record-Triggered Flows.
=> SALTO-6375: Removed from optional features, reference from FlowAssignmentItem (Flows) to CustomField

packages/microsoft-security-adapter/src/change_validator.ts, packages/microsoft-security-adapter/src/change_validators/entra/application_setup_validator.ts, packages/microsoft-security-adapter/src/change_validators/entra/index.ts, packages/microsoft-security-adapter/src/change_validators/shared/index.ts, packages/microsoft-security-adapter/src/definitions/deploy/shared/utils/read_only_fields.ts, packages/microsoft-security-adapter/src/definitions/fetch/entra/fetch.ts, packages/microsoft-security-adapter/test/change_validators/entra/application_setup_validator.test.ts, packages/microsoft-security-adapter/test/change_validators/shared/built_in_instances_validator.test.ts, packages/microsoft-security-adapter/test/change_validators/shared/read_only_fields_validator.test.ts, packages/microsoft-security-adapter/test/change_validators/shared/required_fields_validator.test.ts, packages/microsoft-security-adapter/test/definitions/deploy/shared/utils/read_only_fields.test.ts
1. Omit the following fields from Entra Application & Service Principal: `keyCredentials`, `passwordCredentials`, `tokenEncryptionKeyId`.
2. Return a change error with deploy actions reminding the user to manually set credentials if needed.
---
The above credential fields are not easily deployable using MS Graph. For now, we omit them and instruct users to manually configure these fields for newly created applications.
Omitting these fields will not cause them to be removed during modification changes, as we use the PATCH request method.
---
* Omit credential fields (`keyCredentials`, `passwordCredentials`, `tokenEncryptionKeyId`) from Entra Application & Service Principal.
--- …
=> SALTO-7176: Omit Entra application's credentials fields

packages/microsoft-security-adapter/src/change_validators/entra/index.ts, packages/microsoft-security-adapter/src/change_validators/entra/on_prem_group_addition_validator.ts, packages/microsoft-security-adapter/src/change_validators/shared/read_only_fields_validator.ts, packages/microsoft-security-adapter/test/change_validators/entra/on_prem_group_addition_validator.test.ts, packages/microsoft-security-adapter/test/change_validators/shared/built_in_instances_validator.test.ts
It's not possible to create on-premises groups using MS Graph. 
This PR:
*  introduces a change validator to block additions of on-prem groups
* Set on-prem related fields as read-only, to prevent their modification on modification changes (which are not blocked).
---
* Block the creation of on-prem groups.
---
None
=> SALTO-7106: [MS Security] Block the creation of on-prem groups

packages/salesforce-adapter/src/change_validators/duplicate_rules_sort_order.ts, packages/salesforce-adapter/test/change_validators/duplicate_rules_sort_order.test.ts
SALTO-5096: Bug in duplicateRulesSortOrder Change Validator in Salesforce
---
None
---
None
=> SALTO-5096: Bug in duplicateRulesSortOrder Change Validator in Salesforce

packages/workspace/src/workspace/hidden_values.ts, packages/workspace/test/workspace/hidden_values.test.ts
Current side effect changes were added if a field annotations' `_hidden_value` was _modified_. This PR handles cases where the entire field annotation is added (as hidden) or removed (and was hidden before removal).
---
Manually tested with the reproduction steps detailed in SALTO-7048. Note that this PR only addresses the first issue in that ticket.
---
- Bugfix: added or removed field annotations now have correct side effects for hiding or unhiding instance field values. 
---
None
=> SALTO-7048: Core: Hidden Values: Add side effects for existing field values where field annotation is added or removed completely

packages/salesforce-adapter/src/fetch_profile/data_management.ts
Now uses SBQQ__OptionalSKU__c and SBQQ__ConfiguredSKU__c.
---
WS diff: https://github.com/salto-io/ariel-sf/commit/1c148edc8c6e6e58adc22ba6c3e21109272a4371
---
_Salesforce_:
* Improve SBQQ__ProductOption__c alias.
---
_Salesforce_:
* Tha alias for SBQQ__ProductOption__c instances will change.
=> SALTO-7110: Improving SBQQ__ProductOption__c alias

packages/core/src/core/adapters/adapters.ts, packages/core/src/local-workspace/workspace.ts, packages/core/test/core/adapters/adapters.test.ts, packages/local-workspace/index.ts, packages/local-workspace/src/adapters_config.ts, packages/local-workspace/src/workspace.ts, packages/workspace/index.ts, packages/workspace/src/workspace/adapters_config_source.ts, packages/workspace/src/workspace/index_utils.ts, packages/workspace/src/workspace/workspace.ts
move functions between packages 
`getAdaptersConfigTypesMap` and `getAdapterConfigsPerAccount` are moved to workspace package instead of being in core
---
---
---
=> SALTO-7006: move functions between packages

packages/core/src/core/adapter_format.ts, packages/core/test/core/adapter_format.test.ts
We can currently error on these flows when we get changes with types that aren't resolved.
---
---
None.
---
None.
=> SALTO-7170: Resolve changes before dumping in SFDX flows

packages/salesforce-adapter/src/filters/flow_coordinates.ts, packages/salesforce-adapter/test/filters/flow_coordinates.test.ts
This will also drop preexisting coordinates if they were 0 before but that should basically never happen.
---
---
_Salesforce_:
* Preserve coordinates in Flows with auto-canvas layout when deploying.
---
None.
=> SALTO-7144: Stop removing flow coordinates on deploy which were not added pre deploy

packages/confluence-adapter/e2e_test/adapter.test.ts
Looks like they added unexpected field `currentActiveAlias` to their API response when fetching Spaces.
The API should be stable AFAICT, so this may be a bug on their side. For the meantime, in order to unblock us, we will simply omit this field when comparing the fetched value vs the deployed value.
```
2025-01-08T22:51:15.226Z error confluence-adapter/e2e_test/adapter.test Received unexpected result when deploying instance: confluence.space.instance.Testspace4359b24f. Deployed value: {
key: 'Testspace4359b24f',
name: 'Testspace4359b24f',
type: 'global',
status: 'current',
description: { plain: { value: 'some description', representation: 'plain' } }
} , Received value after fetch: {
description: { plain: { representation: 'plain', value: 'some description' } },
status: 'current',
name: …
```
=> SALTO-7217: Fix Confluence e2e

packages/zendesk-adapter/src/config.ts
fix zendesk config type to include criteria
---
---
---
=> SALTO-7206: fix zendesk config type to include criteria

packages/cli/src/formatter.ts, packages/cli/src/workspace/workspace.ts, packages/cli/test/formatter.test.ts
_CLI shows WS error message instead of detailedMessage_
---
* WS errors should be shown with their detailedMessage. The CLI used the same function for WS and change errors, so I split `formatWorkspaceError` into two for both usages
---
_CLI_
* bug fix: show WS errors detailedMessage instead of message
---
=> SALTO-7223: CLI shows WS error message instead of detailedMessage

packages/jira-adapter/src/filters/duplicate_ids.ts, packages/jira-adapter/test/filters/duplicate_ids.test.ts
SAAS-12444 Jira: add service Url in collision msg
---
Put back https://github.com/salto-io/salto/pull/6928
---
Add in-app links to duplicated instances in collision error
---
None
=> SAAS-12444 Jira: add service Url in collision msg

packages/adapter-components/src/definitions/system/deploy/deploy.ts, packages/adapter-components/src/deployment/deploy/deploy.ts, packages/adapter-components/src/deployment/deploy/graph.ts, packages/adapter-components/test/deployment/deploy/deploy.test.ts, packages/adapter-components/test/deployment/deploy/graph.test.ts, packages/confluence-adapter/src/definitions/deploy/deploy.ts, packages/confluence-adapter/src/definitions/utils/page.ts, packages/confluence-adapter/test/definitions/utils/page.test.ts, packages/okta-adapter/src/definitions/deploy/deploy.ts, packages/okta-adapter/src/definitions/deploy/utils/simple_status.ts, packages/okta-adapter/test/definitions/deploy/utils/simple_status.test.ts
The function was sync which made element source useless
---
---
None
---
None
=> SALTO-7148: Change toActionNames to be async, so it can work with element source

packages/cli/src/commands/adapter_format.ts, packages/cli/test/commands/adapter_format.test.ts, packages/core/src/core/adapter_format.ts, packages/core/test/core/adapter_format.test.ts
syncWorkspaceToFolder now gets an optional workspace which will function as storage for any changes which are not supported by dumpToFolder.
This current implementation does not deal with the case of elements which "move" between the folder & workspace.
---
---
---
=> SALTO-7220: Support mixed mode in syncWorkspaceToFolder

packages/salesforce-adapter/src/change_validator.ts, packages/salesforce-adapter/src/change_validators/live_chat_button_routing_type.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/transformers/missing_fields.json, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/change_validators/live_chat_button_routing_type.test.ts, packages/salesforce-adapter/test/mock_elements.ts
SALTO-6868: CV for LiveChatButton with routingType "Omni-Channel"
---
Error message in Markdown preview:
---
None
---
None
=> SALTO-6868: CV for LiveChatButton with routingType "Omni-Channel"

packages/jira-adapter/src/config/api_config.ts
SALTO-6998 Jira: omit webhookToken from Automation by default
---
None
---
- Remove webhookToken from Automations
---
- Remove webhookToken from Automations
=> SALTO-6998 Jira: omit webhookToken from Automation by default

packages/local-workspace/src/remote_map/remote_map.ts
Deprecating `closeRemoteMapsOfLocation` in favor of `workspace.close()`.
---
---
Workspace:
- Deprecating `closeRemoteMapsOfLocation` in favor of `workspace.close()`. The deprecated function will be removed from the package's exports on the next release (0.5.1).
---
None
=> SALTO-2490 deprecate closeRemoteMapsOfLocation

packages/salesforce-adapter/src/transformers/xml_transformer.ts, packages/salesforce-adapter/test/transformers/xml_transformer.test.ts
This is mainly meaningful for SFDX though it might also allow deploying some elements we couldn't before.
---
At least for LWC (though it's likely the case for other "complex types") the files are packaged such that in the file props there is a namespace prefix but in the zip it is not present.
---
None.
---
None.
=> SALTO-6616: Support namespaced complex types in deploy

packages/jira-adapter/src/config/api_config.ts, packages/jira-adapter/src/filters/automation/automation_deployment.ts, packages/jira-adapter/test/filters/automation/automation_deployment.test.ts
See jira ticket
---
[Noise reduction](https://github.com/salto-io/salto_private/pull/10304)
---
Jira Adapter: 
* Fixed a bug in automation deployments that prevented them from being triggered
---
Jira Adapter:
* Removed the eventFilter field in automations' triggers
=> SALTO-7248: Support Automation Deployment with trigger eventFilters

packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/filters/forms/forms.ts, packages/jira-adapter/src/filters/forms/forms_types.ts, packages/jira-adapter/src/reference_mapping.ts, packages/jira-adapter/test/filters/forms/forms.test.ts
In this PR I fixed the deployment of forms.
---
We encountered an issue where the absence of a reference to contextOption in forms prevented proper deployment. 2. Additionally, the reference infrastructure didn't support adding references to lists within maps. To resolve this, I made the following changes:
1. Fetch: Adjusted the structure of forms during the fetch process to allow adding references.
2. PreDeploy: Reverted the forms back to their original structure before deployment.
3. OnDeploy: Restored the modified structure.
Adding noise reduction now. 
---
_jira Adapter_:
* Users can now deploy forms that include contextOption.
---
* The conditions field in the forms NACL has been updated. It …
=> SALTO-7268: Fix deployment for contextOption in forms

packages/jira-adapter/src/utils.ts, packages/jira-adapter/test/filters/automation/automation_structure.test.ts, packages/lowerdash/src/hash.ts, packages/lowerdash/test/hash.test.ts
Fixed a limitation on the file size name
---
The proper fix should be done IMO in the static file code, but doing this for speed, might remove it later on
---
Jira Adapter: 
* Fixed a bug that caused fetch failures for envs with automations that are connected to many projects
---
Jira Adapter:
* for some users the path of static files for HTML automation content might change
=> SALTO-7275: limit static file name in automations

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/src/last_change_date_of_types_with_nested_instances.ts, packages/salesforce-adapter/test/last_change_data_of_types_with_nested_instances.test.ts
Salesforce CBF won't detect modifications of sub-instances and CustomFields
---
This is a regression from https://github.com/salto-io/salto/pull/7024.
1. We didn't take into consideration the `childXmlNames`.
2. The `metadataTypeInfos` input shouldn't be filtered by the MetadataQuery.
---
- (Bug-fix) Change Based Fetch won't detect modifications of sub-instances and CustomFields
---
_None_
=> SALTO-7278:  (Bug-fix) Salesforce CBF won't detect modifications of sub-instances and CustomFields

packages/jira-adapter/src/filters/fields/README.md, packages/jira-adapter/src/filters/fields/context_deployment_filter.ts, packages/jira-adapter/src/filters/fields/context_options_deployment_filter.ts, packages/jira-adapter/src/filters/fields/context_options_splitted.ts, packages/jira-adapter/src/group_change.ts, packages/jira-adapter/test/filters/fields/context_options_deployment.test.ts, packages/jira-adapter/test/filters/fields/field_context_deployment.test.ts, packages/jira-adapter/test/group_change.test.ts
Solved two deletion bugs, and reduced code complexity by removing the options order from the context group
---
This PR has 2 commits
* The first one is to simplify the code. The context options order used to be part of a change group that contained the context and the options. Because of that we had to manually add ids of options in addition flow. I removed it from the group and deleted the id update code. It is still part of the group in removal- it does not matter for anything as orders are not really deleted, and without it the group would have been broken by dependency problems (in removal we change the directions of dependencies but not for parents. It causes a circle (the options point to the order after reversal, and the order points to the context which is in the group with the …
=> SALTO-7155: solve context deletion options bugs

packages/zendesk-adapter/src/adapter.ts, packages/zendesk-adapter/src/filters/field_references.ts, packages/zendesk-adapter/src/filters/support_address.ts
add reference to support address
---
---
zendesk: 
* add references to `support_address` in triggers.
---
zendesk: 
* add references to `support_address` in triggers.
=> SALTO-5481: add reference to support address

packages/jira-adapter/src/filters/assets/assets_object_field_configuration_references.ts
_remove noisy logs from AssetsObjectFieldConfigurationReferencesFilter_
---
---
_None_
---
_None_
=> SALTO-7240: remove noisy log from AssetsObjectFieldConfigurationReferencesFilter

packages/okta-adapter/jest.config.js, packages/okta-adapter/package.json, packages/okta-adapter/src/adapter.ts, packages/okta-adapter/src/definitions/deploy/types/brand.ts, packages/okta-adapter/src/filters/brand_customizations.ts, packages/okta-adapter/test/filters/brand_customizations.test.ts, packages/okta-adapter/tsconfig.json, yarn.lock
Replace brand customization content with static file (behind FF)
---
Depending of the previous step of creating template expression from content, we create a regular static file if we could not detect refs in previous step, or create template static file otherwise.
(tests will follow)
---
None
---
None
=> SALTO-7198: Convert Okta Brand customization content into static file

packages/jira-adapter/src/adapter.ts, packages/jira-adapter/test/adapter.test.ts
Fix a bug causing applied changes to return to core with incorrect types.
---
When deploying ducktype types, we override types for deployment, to make sure fields that are service ids defined this way, so we'll correctly assign the created internal id to the newly created element.
The types created for deployment should be ultimately restored, before returning the applied change to core, as this might cause pending changes, merge errors, and more.
The types creation is done in various of different filters, but I added the type restore in the end of flow of the adapter.
---
- Fix a bug causing merge errors after deployments of new Request Types
---
None
=> SALTO-7241: Restore Jira types to original ones after deployment 

packages/jira-adapter/src/reference_mapping.ts
_add objectTypeAttribute references rule_
---
* I added the rules that I removed in this [pr](https://github.com/salto-io/salto/pull/7099/files#diff-ef0b7e0d708b8a1d16e805a734d3527fac5248a64958ad1c20cdf9783bacd7fbL1363).
* I omit the `target` section because these rules should be applied only for resolving, because we create the references in a filter. 
---
---
=> SALTO-7286: add objectTypeAttribute references rule

packages/cli/e2e_test/helpers/salesforce.ts, packages/core/src/core/fetch.ts, packages/lang-server/src/diagnostics.ts, packages/lang-server/test/workspace.ts, packages/parser/src/parser/functions.ts, packages/parser/test/parser/functions.test.ts, packages/workspace/src/merger/index.ts, packages/workspace/src/merger/internal/common.ts, packages/workspace/src/validator.ts, packages/workspace/test/merger.test.ts
_clean leftover usages of error messages_
---
---
_None_
---
_None_
=> SALTO-7223: clean leftover usages of error messages

packages/jira-adapter/src/filters/layouts/issue_layout.ts
SALTO-7294 bug in IssueLayout filter with length on undefined
---
---
None
---
None
=> SALTO-7294 bug in IssueLayout filter with length on undefined

packages/salesforce-adapter/src/filters/picklist_references.ts, packages/salesforce-adapter/test/filters/picklist_references.test.ts
(Bug-fix) Salesforce picklistReferences crashes when fullName is a non resolved Element
---
Reproduces on CPQ account and CBF that modifies RecordTypes.
---
_None_
---
_None_
=> SALTO-7925: (Bug-fix) Salesforce picklistReferences crashes when fullName is a non resolved Element

packages/jira-adapter/src/change_validators/boards/kanban_board_backlog.ts, packages/jira-adapter/test/change_validators/boards/kanban_board_backlog.test.ts
The original message was for users who deployed without fetching, not likely anymore
---
---
None
---
None
=> SALTO-7104: Remove kanban CV temp message

packages/zendesk-adapter/src/filters/webhook.ts, packages/zendesk-adapter/test/filters/webhook.test.ts
The endpoint is turned into a template expression if this happens.
---
---
_Zendesk Adapter:_
* Webhook endpoints can now contain a reference to a brand url.
---
_Zendesk Adapter:_
* Webhook endpoints can now contain a reference to a brand url.
=> SALTO-7288 Webhook endpoint can contain a reference to a brand url

packages/salesforce-adapter/src/fetch_profile/optional_features.ts, packages/salesforce-adapter/test/adapter.discover.test.ts, packages/salesforce-adapter/test/filters/field_permissions_enum.test.ts
PROD-390: Salesforce noisy features
---
Workspace Diff: TBD
---
- Remodeled Picklist values as Maps instead of arrays (GlobalValueSet, StandardValueSet, and Picklist fields)
- Retrieve Settings Instances instead of using Read API for correct Metadata values.
- Fixed an issue where we've previously omitted values from PermissionSet and Profile instances.
---
_Salesforce_:
- Expect changes to nacls of the following types:
- Settings instances.
- GlobalValueSet.
- StandardValueSet.
- Picklist fields
=> PROD-390: Salesforce noisy features

packages/microsoft-security-adapter/jest.config.js, packages/microsoft-security-adapter/src/config/assignment_fields.ts, packages/microsoft-security-adapter/src/config/index.ts, packages/microsoft-security-adapter/src/fix_elements/assignment_fields_handler.ts, packages/microsoft-security-adapter/test/fix_elements/assignment_fields_handler.test.ts
There's a bug in the assignment fields handler for Intune types **on modification**:
The fixer simply deletes the `assignments` fields, which is considered as a modification to that field (when we match it against our [deploy condition for Intune assignments](https://github.com/salto-io/salto/blob/2a6890d7ddae3b682b165a95727f320be58fd776/packages/microsoft-security-adapter/src/definitions/deploy/intune/utils/assignments.ts#L40) field). Therefore, we try to deploy the `assignments` field with an undefined value - which results in an error.
This PR specifically set an `emptyValue` of [] for intune assignments.
---
None
---
None
=> SALTO-7137: Fix assignment fields handler - array fields

packages/zendesk-adapter/src/change_validators/users.ts
Unneeded resolver in a CV creates failing to serialize references errors.
---
---
---
=> SALTO-7308 Remove resolver from CV

packages/salesforce-adapter/src/fetch_profile/optional_features.ts, packages/salesforce-adapter/src/filters/omit_standard_fields_non_deployable_values.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/omit_standard_fields_non_deployable_values.test.ts
Allow users to disable Salesforce   `omitStandardFieldsNonDeployableValues` optional feature
---
Un-deprecated the optional feature.
---
- Add the ability to disable  `omitStandardFieldsNonDeployableValues` optional feature.
---
_None_
=> SALTO-7309: Allow users to disable Salesforce   `omitStandardFieldsNonDeployableValues` optional feature

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/add_parent_to_approval_process.ts, packages/salesforce-adapter/test/filters/add_parent_to_approval_process.test.ts, packages/salesforce-adapter/test/filters/add_parent_to_record_triggered_flows.test.ts, packages/salesforce-adapter/test/mock_elements.ts
SALTO-6396: Add missing reference from ApprovalProcess to workflowAction
---
Workspace Diff: https://github.com/salto-io/almog-sf/commit/438db584c6f41112b82dd06e7b0f37f22b1aef7d
---
- Improved IA between ApprovalProcess and WorkflowAction.
---
- References will be added from ApprovalProcess WorkflowAction.
- **_parent** annotation will be added to ApprovalProcess.
=> SALTO-6396: Add missing reference from ApprovalProcess to WorkflowAction

packages/okta-adapter/src/adapter.ts
until SALTO-7314 is implemented, we need to first rename domain elements (with `referencedInstanceNames`), and only then create the references
---
---
None
---
None
=> SALTO-7198: Fix Brand template static files filter when Domain element is renamed

packages/local-workspace/src/remote_map/remote_map.ts, packages/workspace/src/workspace/nacl_files/elements_cache.ts
* Flush `mergeManager` remote maps sequentially.
* Add logs: timeDebug, a conditional log (triggered if more than 10 minutes have passed), and debug logs during each flushable flush operation
---
None
---
None
=> SALTO-7279: Change elements_cache mergeManager to flush remote maps sequentially

packages/adapter-utils/src/collisions.ts, packages/adapter-utils/test/collisions.test.ts
_replace markdown links in id collision message_
---
---
_None_
---
_None_
=> SALTO-7095: replace markdown links in id collision message

packages/jira-adapter/src/filters/layouts/request_type_request_form.ts, packages/jira-adapter/test/filters/layouts/request_type_request_form.test.ts
Added a new filter to remove empty properties in request forms
---
---
- Added a filter to remove empty properties in request forms in Jira
---
- Upon user next fetch, all empty properties will be removed from the requestType instances
=> SALTO-5299: New properties added to JSM request form 

packages/adapter-components/src/fetch/element/standalone.ts, packages/adapter-components/src/filters/referenced_instance_names.ts, packages/adapter-components/test/fetch/element/instance_element.test.ts, packages/adapter-components/test/filters/referenced_instance_names.test.ts
This PR fixes two issues, the first that when having a custom configuration where both the parent and the standalone child have `allowEmptyArrays: true` still removes empty arrays from the children. 
The second is for instances with references in their id that have `allowEmptyArrays: true` - these also still have their empty arrays removed..
---
---
---
=> SALTO-7316 Allow empty arrays also for standalone instances

packages/workspace/src/workspace/static_files/source.ts
add logs whenever we don't return a static file with content, including the reason for it.
---
---
None
---
None
=> SALTO-7323 add warn logs to static files source

packages/workato-adapter/specific-cli-options.md, packages/workato-adapter/src/adapter_creator.ts, packages/workato-adapter/src/auth.ts, packages/workato-adapter/src/client/connection.ts, packages/workato-adapter/test/adapter_creator.test.ts, packages/workato-adapter/test/client/connection.test.ts
Allow providing optional base URL for workato, with a fallback value to the default Workato based URL we used until now.
---
---
_Workato Adapter_:
- Support authenticating Workato adapter with non US based Workato account (see https://docs.workato.com/workato-api.html#base-url)
---
None
=> SALTO-7332: Add optional base url for Workato

packages/microsoft-security-adapter/src/auth.ts
This scope is sometimes required to assign App Roles to a Service Principal
---
* Add missing Entra scope, to allow assigning App Roles to Service Principals.
---
None
=> SALTO-7333: Add missing Entra scope

packages/zendesk-adapter/src/filters/guide_arrange_paths.ts
fix guide_arrange_path filter
---
---
---
=> SALTO-7337: fix guide_arrange_path filter

packages/microsoft-security-adapter/src/definitions/fetch/intune/fetch.ts
This is a newly added field in their beta API response.
ATM there’s no documentation available for it, and it doesn’t seem to appear in the Intune admin center (based on my attempts).
Currently, it causes deployment failures. Until we gain more clarity, we will omit this field.
---
_Microsoft Security:_
* Omit Intune scopeTag.permissions field on fetch
---
_Microsoft Security:_
* The field `permissions` will be omitted from Intune Scope Tags elements starting from the next fetch.
=> SALTO-7338: Omit Intune scopeTag.permissions field on fetch

packages/workspace/src/flags.ts, packages/workspace/src/workspace/static_files/source.ts
There's a possibility to have a mismatch in the StaticFile's hash and the hash of the StaticFile's content that was received from the staticFIlesDirStore.
---
---
None
---
None
=> SALTO-7323 log when there is a different hash to the buffer in LazyStaticFile

packages/cli/generate.sh, packages/core/src/generated/version.json, packages/local-workspace/src/generated/version.json
The version files should not have been pushed to git.
Also, fixed the script that created them to make sure it creates the generated folder in the right location no matter where it is run from
---
---
_None_
---
_None_
=> SALTO-7340: remove generated version files

packages/adapter-components/src/fetch/element/standalone.ts, packages/adapter-components/src/filters/referenced_instance_names.ts, packages/adapter-components/test/fetch/element/instance_element.test.ts, packages/adapter-components/test/filters/referenced_instance_names.test.ts, packages/workato-adapter/src/filters/cross_service/jira/project_issuetypes.ts, packages/workato-adapter/test/filters/project_issuetypes.test.ts, packages/zendesk-adapter/src/filters/article/article.ts, packages/zendesk-adapter/src/filters/guide_order/article_order.ts, packages/zendesk-adapter/src/filters/guide_order/guide_order_utils.ts, packages/zendesk-adapter/test/filters/guide_order/guide_order_utils.test.ts
Reverting the revert and updating the filters that created empty arrays.
---
---
---
=> SALTO-7316 Allow empty arrays fix

packages/okta-adapter/src/definitions/fetch/fetch.ts
Order application `features` field (list of strings)
---
---
- Fix a bug causing items in application features list to be re ordered between fetches.
---
- For application with `features` configured, feature items might be re-ordered
=> SALTO-7315: Order Okta application features list to avoid noise

packages/okta-adapter/src/adapter.ts, packages/okta-adapter/src/user_config.ts
Remove temporary config suggestion to migrate `UserRoles` into the exclude list introduced in https://github.com/salto-io/salto/pull/7007
---
---
None
---
None
=> SALTO-2737: Remove config suggestion to exclude user roles

packages/jira-adapter/e2e_test/adapter.test.ts, packages/jira-adapter/src/deployment/standard_deployment.ts, packages/jira-adapter/src/filters/notification_scheme/notification_scheme_deployment.ts, packages/jira-adapter/src/filters/screen/screen.ts, packages/jira-adapter/src/filters/script_runner/script_runner_filter.ts, packages/jira-adapter/src/filters/script_runner/script_runner_instances_deploy.ts, packages/jira-adapter/src/filters/script_runner/script_runner_listeners_deploy.ts, packages/jira-adapter/test/filters/notification_scheme/notification_scheme_deployment.test.ts, packages/jira-adapter/test/filters/screen/screen.test.ts, packages/jira-adapter/test/filters/script_runner/script_runner_filter.test.ts, packages/jira-adapter/test/filters/script_runner/script_runner_listeners_deploy.test.ts
Fixed a problem in the E2E- it did not apply changes to the instances
---
In the core we apply changes after a deployment of a change group on the instances, so references will have the valid values (for instance IDs). In the E2E we only copied the value of the ids for parents.
Following the change, which is in the first commit, a few bug were revealed. Each is fixed in a separate commit.
In the last commit I added another fix for the E2E, to perform the delete in the same groups of the additions as sometimes the order is important
---
Jira Adapter:
* Improvements to the E2E and related bug fixes (mostly in hidden fields)
---
None
=> SALTO-7313: E2E fixes

packages/jira-adapter/e2e_test/adapter.test.ts, packages/jira-adapter/e2e_test/instances/field.ts, packages/jira-adapter/e2e_test/instances/index.ts, packages/jira-adapter/src/config/config.ts, packages/jira-adapter/src/filters/fields/context_options_deployment_filter.ts, packages/jira-adapter/src/filters/script_runner/script_runner_filter.ts, packages/jira-adapter/test/change_validators/field_contexts/custom_field_with_10K_options.test.ts, packages/jira-adapter/test/filters/fields/context_options_deployment.test.ts, packages/jira-adapter/test/filters/fields/default_values.test.ts
None
---
[Noise reduction](https://github.com/salto-io/salto_private/pull/10145)
---
Jira Adapter:
* Options in Fields will now be a separate element. It allows modifying options without changing their IDs
---
Jira Adapter:
* Field contexts will now have a list of references to their options, options will now be in standalone elements
=> SALTO-5932: change split options in Fields to default true

packages/okta-adapter/e2e_test/adapter.test.ts
Per the request of @shir-reifenberg as the E2E is blocking deployment
---
None
---
None
---
None
=> SALTO-7359: temporary disable Okta E2e

packages/jira-adapter/src/filters/sort_lists.ts, packages/jira-adapter/test/filters/sort_lists.test.ts
Sort the links as their order is not important, and they cause noise for the customers
---
Noise reduction will follow
---
Jira Adapter:
* Workflow transition links' list will now be sorted to avoid order noise
---
Jira Adapter:
* Workflow transition links might change order
=> SALTO-7341: sort workflow transition links

packages/adapter-components/src/filters/omit_collisions.ts, packages/adapter-components/test/filters/omit_collisions.test.ts, packages/adapter-utils/src/collisions.ts, packages/adapter-utils/test/collisions.test.ts, packages/jira-adapter/src/filters/duplicate_ids.ts, packages/jira-adapter/test/filters/duplicate_ids.test.ts, packages/okta-adapter/src/filters/common.ts, packages/salesforce-adapter/src/filters/custom_object_instances_references.ts, packages/zendesk-adapter/src/filters/omit_collision.ts, packages/zendesk-adapter/test/adapter.test.ts, packages/zendesk-adapter/test/filters/omit_collision.test.ts
_use the new id collision message in the adapters_
---
* in this pr I changed the usage of `getAndLogCollisionWarnings` to use `getCollisionWarnings`, and delete the old function
---
_None_
---
_None_
=> SALTO-7095: use the new id collision message in the adapters

packages/cli/src/commands/init.ts, packages/local-workspace/src/workspace.ts, packages/local-workspace/test/workspace.test.ts
This is a follow up of https://github.com/salto-io/salto/pull/7164 
---
---
---
=> SALTO-7358: Change locateWorkspaceRoot to named params

packages/cli/src/commands/element.ts, packages/cli/test/commands/element.test.ts
---
---
CLI:
- Added different formatting options to `element print` command
---
_None_
=> SALTO-7352: Add inspect / serialize format options to element print

packages/parser/src/parser/internal/dump.ts, packages/parser/src/parser/internal/native/consumers/values.ts, packages/parser/src/parser/internal/native/helpers.ts, packages/parser/src/parser/internal/utils.ts, packages/parser/src/utils/template_static_file.ts, packages/parser/test/parser/dump.test.ts, packages/parser/test/parser/parse.test.ts, packages/parser/test/template_static_file.test.ts
This fixes an issue where it was impossible to tell the difference between an escaped reference marker \${ and a real reference that had a \ before it. The effect of this change is that all `\` leading up to a template marker will now be escaped (turned into `\\`)
---
A few examples of the old behavior vs the new behavior, marking reference expressions in the actual value as "(ref)" so it will be possible to see where a real reference is supposed to be (the table below shows multi line NaCl, the behavior in single line strings is slightly different)
Value  |  Nacl (old) |  Nacl (new)
------ | ---------- | -----------
`bla \(ref)` | `"bla \${ ref }"` | `"bla \\${ ref }"`
`bla ${ not.ref }` | `"bla \${ not.ref }"` | `"bla \${ not.ref }"`
`bla \\(ref)` | …
=> SALTO-6286, SALTO-7280: Fix escaping of template expressions

packages/jira-adapter/src/filters/layouts/request_type_request_form.ts
Removed the scheme guard log error message as it made a lot of unnecessary noise, as there are also valid objects without 'properties' field.
---
---
---
=> SALTO-5299: New properties added to JSM request form fix - remove log error message

packages/netsuite-adapter/config_doc.md, packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/client/file_cabinet_utils.ts, packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/src/client/sdf_parser.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts, packages/netsuite-adapter/src/client/types.ts, packages/netsuite-adapter/src/config/constants.ts, packages/netsuite-adapter/src/config/suggestions.ts, packages/netsuite-adapter/src/config/types.ts, packages/netsuite-adapter/src/config/validations.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/change_validator.test.ts, packages/netsuite-adapter/test/change_validators/safe_deploy.test.ts, packages/netsuite-adapter/test/client/file_cabinet_utils.test.ts, packages/netsuite-adapter/test/client/sdf_client.test.ts, packages/netsuite-adapter/test/client/suiteapp_client/suiteapp_file_cabinet.test.ts, packages/netsuite-adapter/test/config/suggestions.test.ts, packages/netsuite-adapter/test/config/validations.test.ts
Exclude FileCabinet folders (and all in them) that have more then the allowed amount of files for a single folder.
The limit is configurable using the `maxFilesPerFileCabinetFolder` config (see config_doc.md).
In case that a folder has reached 90% of the allowed amount, a fetch warning will be returned.
---
TODO:
---
- Limit the allowed amount of files in a FileCabinet folder (using the `client.maxFilesPerFileCabinetFolder` config)
---
- When `client.maxFilesPerFileCabinetFolder` is given, FileCabinet folder that have more than the allowed amount of files will be excluded.
=> SALTO-6690 limit the allowed amount of files in a FileCabinet folder

packages/core/src/core/fetch.ts, packages/workspace/src/flags.ts
This feature is already rolled out, so the killswitch flag can be removed.
---
None
---
None
---
None
=> SALTO-7376: Cleanup `SALTO_COMPUTE_PLAN_ON_FETCH` flag.

packages/salesforce-adapter/src/filters/utils.ts, packages/salesforce-adapter/src/transformers/reference_mapping.ts, packages/salesforce-adapter/test/filters/utils.test.ts
(Bugfix) Salesforce fetch name-spaced instances within Folders and add CustomApplication logo reference
---
Workspace Diff: https://github.com/salto-io/tamir-sf/commit/9f2a92bf63a806a5a98b5279d8ac81bbff7f71b7
The adapter returned incorrect fullName for the fileProperties of instances within folder that has a namespace
---
- (Bugfix) fetch name-spaced instances within Folders.
- Add reference to CustomApplication logos.
---
_None_
=> SALTO-7392: (Bugfix) Salesforce fetch name-spaced instances within Folders and add CustomApplication logo reference

packages/jira-adapter/src/change_validators/index.ts, packages/jira-adapter/src/filters/automation/smart_values/smart_value_reference_filter.ts, packages/jira-adapter/src/filters/automation/types.ts, packages/jira-adapter/src/reference_mapping.ts, packages/jira-adapter/test/filters/automation/smart_values/smart_value_reference_filter.test.ts
Added support for additional references in automation rules
---
I added cover for the following:
1. Smart queries (places where the user can add smart tags)
2. Smart queries in IQL
3. Triggers of type jira.sla.threshold.trigger
4. Outgoing mails- the `to` is populated by a field (of a user or a group)
5. Conditions of type affected.service.condition
I also added a minor fix- the portals CV was too strict, it did not allow the deploy valid portal groups.
There are 4 commits- the first  for the minor fix,  the second for fix number 3, the third for fixes 4 & 5, and the last for fixes 1 & 2
Noise reduction will follow
---
Jira Adapter:
* Added support for additional references in Automations
---
Jira Adapter:
* References will replace values in …
=> SALTO-7253: automation references

packages/salesforce-adapter/src/change_validators/unique_flow_element_name.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/test/change_validators/unique_flow_element_name.test.ts
SALTO-7395: (Bugfix) Fix false positives for FlowElements with non-unique names in the Unique FlowElement Name CV
---
None
---
None
=> SALTO-7395: (Bugfix) Fix false positives for FlowElements with non-unique names in the Unique FlowElement Name CV

packages/salesforce-adapter/src/filters/flows_filter.ts, packages/salesforce-adapter/test/filters/flows_filter.test.ts
Currently the author info is derived from the flow object which is not necessarily what users expect. Creation info is for when the entire flow was created and change info is for the last time a version was created or activated.
Now, the author information for the selected version (latest or active, depending on user preference) is used. Creation info is from when the version was created and change info is from one second later or when the version was activated (this is SF behavior).
Also, no longer hiding the FlowDefinition type because that's covered by the hide types folder filter.
---
See the Flow tooling api documentation: https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_flow.htm
--- …
=> SALTO-7188: Setting flow author info from selected version

packages/jira-adapter/src/reference_mapping.ts, packages/jira-adapter/test/reference_mapping.test.ts
Another small one
---
[Noise reduction](https://github.com/salto-io/salto_private/pull/10499)
---
Jira Adapter: 
* Added support for request-type references in automation conditions
---
Jira Adapter:
* Request type names in automation's conditions will turn into references
=> SALTO-7378: references for request type in automation conditions

packages/salesforce-adapter/src/change_validators/unique_flow_element_name.ts, packages/salesforce-adapter/test/change_validators/unique_flow_element_name.test.ts
SALTO-7403: (Bugfix)  Fix FlowNodes support for Unique FlowElement Name in CV
---
None
---
None
=> SALTO-7403: (Bugfix)  Fix FlowNodes support for Unique FlowElement Name in CV

packages/salesforce-adapter/src/change_validators/flow_referenced_elements.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/test/change_validators/flow_referenced_elements.test.ts
SALTO-7282: Extend CV for missing referenced FlowElements in Flow to support more FlowElements
---
---
None
---
None
=> SALTO-7282: Extend CV for missing referenced FlowElements in Flow to support more FlowElements

packages/jira-adapter/src/dependency_changers/forms.ts, packages/jira-adapter/src/dependency_changers/index.ts, packages/jira-adapter/test/dependency_changers/forms.test.ts
SALTO-7389 Workaround for a Jira bug: when trying to deploy (addition/modification) several forms of the same project, only one is deployed. deploying the changes one-by-one (per project) solves this
---
None
---
- SALTO-7389 solve bug of failing to deploy forms
---
None
=> SALTO-7389 deploy forms one by one

packages/jira-adapter/src/change_validators/automation/automation_to_assets.ts, packages/jira-adapter/src/change_validators/automation/automations_issue_types.ts, packages/jira-adapter/src/change_validators/index.ts, packages/jira-adapter/src/config/config.ts, packages/jira-adapter/test/change_validators/automations/automations_issue_types.test.ts
CV that blocks Automation with issueTypes that are out of scope.
I blocked the following cases (for `jira.issue.create` automation actions):
1. When the issue type value is not one of the project’s issue type scheme referenced (in the field directly above it).
2. When it is a single project scope automation, the project value is current, and the issue type value is not from that project’s issue type scheme.
---
- Added a new CV to block Automations with issueTypes out of scope
---
=> SALTO-7179: CV that blocks Automation with issueTypes that are out of scope

packages/logging/src/logger.ts, packages/logging/test/pino_logger.test.ts
Add the ability to log the running time of an iterator, including:
1. total run time
2. time to start iterating the iterator (`tts`)
3. total time to retrieve iterated items (`net`)
---
---
Logger:
- add `timeIterator` methods to logger
---
None
=> SALTO-7345 add timeIterator methods to logger

packages/netsuite-adapter/e2e_test/adapter.test.ts, packages/netsuite-adapter/src/adapter_creator.ts, packages/netsuite-adapter/test/adapter_creator.test.ts
Cannot be installed anymore
---
---
- Remove installation of old suitecloud version. TBA won't be supported in new installations- OAuth authenrication will be required.
---
None
=> Remove installation of old suitecloud version

packages/salesforce-adapter/src/fetch_profile/metadata_query.ts, packages/salesforce-adapter/test/fetch_profile/metadata_query.test.ts
We can get this flow if a user defines a non-array metadata query.
---
---
None.
---
None.
=> SALTO-7421: Fixing bug in metadata query validation

packages/local-workspace/index.ts, packages/local-workspace/src/remote_map/index.ts, packages/local-workspace/src/remote_map/remote_map.ts, packages/local-workspace/test/remote_map/remote_map.test.ts, packages/local-workspace/test/remote_map/remote_map_connection.test.ts
use `workspace.close()` / `remoteMapCreator.close()` instead.
---
---
Workspace:
- Removed export of `closeRemoteMapsOfLocation`. use `workspace.close()` / `remoteMapCreator.close()` instead.
---
None
=> SALTO-2490 Remove export of closeRemoteMapsOfLocation

packages/core/src/core/adapter_format.ts, packages/core/src/core/fetch.ts, packages/core/test/core/adapter_format.test.ts, packages/core/test/core/fetch.test.ts
Re-use the logic from fetch from to get the path from the index path or by getting the element nacl files.
---
---
_Core_:
* Store elements with the correct nacl file path for adapter format commands.
---
N/A
=> SALTO-7243: Fix element paths for adapter format functions

packages/jira-adapter/e2e_test/adapter.test.ts
There was a problem with the specific server. I created a new one (as there was no way to debug the old one)
---
None
---
None
---
None
=> SALTO-7423: re-enable jira E2E

packages/google-workspace-adapter/e2e_test/adapter.ts, packages/google-workspace-adapter/src/auth.ts, packages/google-workspace-adapter/src/client/connection.ts, packages/google-workspace-adapter/src/client/oauth.ts, packages/google-workspace-adapter/src/config.ts, packages/google-workspace-adapter/src/definitions/index.ts, packages/google-workspace-adapter/src/definitions/requests/index.ts, packages/google-workspace-adapter/src/definitions/types.ts
=> SALTO-7363: Removing unused exports from Google Workspace adapter

packages/jamf-adapter/src/client/connection.ts, packages/jamf-adapter/src/config.ts, packages/jamf-adapter/src/definitions/requests/index.ts, packages/jamf-adapter/src/definitions/types.ts
=> SALTO-7363: Removing unused exports from Jamf adapter

packages/zendesk-adapter/src/filters/handle_template_expressions.ts, packages/zendesk-adapter/test/filters/handle_template_expressions.test.ts
We saw cases where the `expression` was very large and threw a `Regular expression too large` error. 
Changed the way we search - we now look for a help center url, and then split that into potential references
---
---
---
=> SALTO-7319 Remove large regex pattern

packages/jira-adapter/src/filters/sort_lists.ts, packages/jira-adapter/test/filters/sort_lists.test.ts
Re-ordered the collaborators in automations to preserve order
---
Noise reduction [here](https://github.com/salto-io/salto_private/pull/10557) 
The collaborators should be changed to show the names and not only the ids. I opened a [ticket](https://salto-io.atlassian.net/browse/SALTO-7417) 
---
Jira Adapter:
* Automation collaborators will now be sorted 
---
Jira Adapter:
* Automation collaborators will now be sorted
=> SALTO-7413: sort collaborators order

packages/jira-adapter/src/change_validators/index.ts
Jira don't allow creating screens with the same name. We have our elemId based on the name, but such duplication could occur in case a screen name was changed and we have the elemId points to the original name.
We need to use the general CV and make sure we enforce Screen name uniqueness in deployment
---
---
None
---
None
=> SALTO-7365 Jira Screen: enforce uniqueness in deployment

packages/microsoft-entra-adapter/src/client/connection.ts, packages/microsoft-entra-adapter/src/client/oauth.ts, packages/microsoft-entra-adapter/src/constants.ts, packages/microsoft-entra-adapter/src/definitions/deploy/types.ts, packages/microsoft-entra-adapter/src/definitions/index.ts, packages/microsoft-entra-adapter/src/definitions/requests/index.ts, packages/microsoft-entra-adapter/src/definitions/types.ts, packages/microsoft-entra-adapter/src/filters/array_fields_deployment.ts, packages/microsoft-entra-adapter/test/mocks.ts, packages/microsoft-security-adapter/src/auth.ts, packages/microsoft-security-adapter/src/client/connection.ts, packages/microsoft-security-adapter/src/config/config.ts, packages/microsoft-security-adapter/src/constants/entra.ts, packages/microsoft-security-adapter/src/constants/intune.ts, packages/microsoft-security-adapter/src/definitions/fetch/shared/types.ts, packages/microsoft-security-adapter/src/definitions/index.ts, packages/microsoft-security-adapter/src/definitions/references/index.ts, packages/microsoft-security-adapter/src/definitions/requests/index.ts, packages/microsoft-security-adapter/src/definitions/types.ts, packages/microsoft-security-adapter/src/filters/shared/array_fields_deployment.ts, packages/microsoft-security-adapter/src/filters/shared/index.ts, packages/microsoft-security-adapter/test/mocks.ts
=> SALTO-7363: Removing unused exports from Microsoft adapters

packages/pagerduty-adapter/src/client/connection.ts, packages/pagerduty-adapter/src/config.ts, packages/pagerduty-adapter/src/definitions/index.ts, packages/pagerduty-adapter/src/definitions/requests/index.ts
=> SALTO-7363: Removing unused exports from PagerDuty adapter

packages/stripe-adapter/src/client/connection.ts, packages/stripe-adapter/src/config.ts, packages/stripe-adapter/src/definitions/types.ts
=> SALTO-7363: Removing unused exports from Stripe adapter

packages/workato-adapter/src/adapter.ts, packages/workato-adapter/src/auth.ts, packages/workato-adapter/src/definitions/types.ts, packages/workato-adapter/src/filter.ts, packages/workato-adapter/src/filters/add_root_folder.ts, packages/workato-adapter/src/filters/cross_service/salesforce/element_index.ts, packages/workato-adapter/src/reference_mapping.ts, packages/workato-adapter/src/rlm.ts, packages/workato-adapter/src/user_config.ts, packages/workato-adapter/test/utils.ts
=> SALTO-7363: Removing unused exports from Workato adapter

packages/zendesk-adapter-e2e/e2e_test/adapter.ts, packages/zendesk-adapter/src/adapter.ts, packages/zendesk-adapter/src/change_validators/child_parent/utils.ts, packages/zendesk-adapter/src/change_validators/guide_creation_or_removal.ts, packages/zendesk-adapter/src/change_validators/index.ts, packages/zendesk-adapter/src/client/client.ts, packages/zendesk-adapter/src/definitions/index.ts, packages/zendesk-adapter/src/definitions/requests/index.ts, packages/zendesk-adapter/src/definitions/requests/pagination.ts, packages/zendesk-adapter/src/filters/add_alias.ts, packages/zendesk-adapter/src/filters/article/article.ts, packages/zendesk-adapter/src/filters/article/utils.ts, packages/zendesk-adapter/src/filters/bot_builder_arrange_paths.ts, packages/zendesk-adapter/src/filters/custom_objects/utils.ts, packages/zendesk-adapter/src/filters/field_references.ts, packages/zendesk-adapter/src/filters/guide_section_and_category.ts, packages/zendesk-adapter/src/filters/guide_themes/types.ts, packages/zendesk-adapter/src/filters/handle_template_expressions.ts, packages/zendesk-adapter/src/filters/reorder/queue.ts, packages/zendesk-adapter/src/filters/reorder/user_field.ts, packages/zendesk-adapter/src/user_config.ts, packages/zendesk-adapter/test/utils.ts
Also Zendesk E2E tests.
---
---
None.
---
None.
=> SALTO-7363: Removing unused exports from Zendesk adapter

packages/salesforce-adapter/src/transformers/reference_mapping.ts, packages/salesforce-adapter/test/filters/field_references.test.ts
SALTO-3221-4531: Added references in Flow for the leftValueReference and elementReference fields starting with $Record.
---
Workspace Diff: https://github.com/salto-io/almog-sf/commit/3f14c7fbbe3638420f5dba25113acc652eac22b7
---
- Improved IA between Flow and CustomFields.
---
- References will be added from Flow to CustomFields.
=> SALTO-3221 SALTO-4531: Added references in Flow for the leftValueReference and elementReference fields starting with $Record.

packages/salesforce-adapter/src/change_validators/flexi_page_unused_or_missing_facets.ts, packages/salesforce-adapter/test/change_validators/flexi_page_unused_or_missing_facets.test.ts
SALTO-7411: (Bugfix) False positive for unused FlexiPage facets. Added detection for unused FlexiPage facets without the ‘Facet-’ prefix.
---
None
---
None
=> SALTO-7411: (Bugfix) False positive for unused FlexiPage facets. Added detection for unused FlexiPage facets without the ‘Facet-’ prefix.

packages/microsoft-security-adapter/jest.config.js, packages/microsoft-security-adapter/src/definitions/requests/clients.ts
We have a polling mechanism for assigning a lifecycle policy to a group. This polling exists for cases where we create a group in the same deployment, as it may take some time for the group to become available for assignment.
However, sometimes the request that resulted in a 404 error actually succeeded. In this case, the service then returns the following error:
`Request failed with status code 400: Error in validating lifecycle manangement policy. Error: GroupId 675a7363-c692-415c-acf5-39cdd6d8d0bd is already present in the policy.`
We should consider this response as a success.
---
* Fix flakiness in assigning a group to a lifecycle policy
---
None
=> SALTO-7443: Fix assigning lifecycle policy to Entra group is flaky

packages/jira-adapter/e2e_test/instances/field.ts, packages/jira-adapter/e2e_test/instances/index.ts, packages/jira-adapter/src/filters/fields/constants.ts, packages/jira-adapter/src/filters/fields/context_options_deployment_filter.ts, packages/jira-adapter/src/filters/fields/default_values.ts, packages/jira-adapter/src/filters/fields/field_name_filter.ts, packages/jira-adapter/test/filters/fields/context_options_deployment.test.ts, packages/jira-adapter/test/filters/fields/default_values.test.ts
Fixed default values- the value of the references for options in the default value was not updated in add
---
Tests will follow
---
Jira Adapter:
* Fixed a bug with deployment of default values for field contexts 
---
None
=> SALTO-7433: fixing default value for contexts

packages/jira-adapter/src/constants.ts, packages/jira-adapter/src/filters/automation/smart_values/smart_value_reference_filter.ts, packages/jira-adapter/src/filters/automation/types.ts, packages/jira-adapter/src/filters/script_runner/workflow/workflow_filter.ts, packages/jira-adapter/test/filters/automation/smart_values/smart_value_reference_filter.test.ts
Fixed type and smart value deploy issues
---
I did some order on the types on the way
---
Jira Adapter:
* Solved a bug with deployment of automation when parseAdditionalAutomationExpressions is on
---
None
=> SALTO-7445: Automation References types

packages/salesforce-adapter/src/change_validators/flexi_page_unused_or_missing_facets.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/transformers/reference_mapping.ts, packages/salesforce-adapter/test/change_validators/flexi_page_unused_or_missing_facets.test.ts, packages/salesforce-adapter/test/filters/field_references.test.ts
SALTO-4207: Missing reference in FlexiPage criterias
---
Workspace Diff: https://github.com/salto-io/almog-sf/commit/75f4631f409655ca88977ec0214246b87b109356#diff-bf6841af5dcdd8f35c9cacd4cbee8c00d31a550c52f2d40ab84298d222163cc8
---
- Improved IA between LightningPages and CustomFields.
---
- References will be added from UiFormulaCriterion (LightningPage) to CustomField.
=> SALTO-4207: Missing reference in FlexiPage criterias

packages/microsoft-security-adapter/src/definitions/deploy/intune/deploy.ts, packages/microsoft-security-adapter/src/definitions/deploy/intune/utils/assignments.ts, packages/microsoft-security-adapter/test/definitions/deploy/intune/utils/group_assignments.test.ts
Deploy scope tags one by one 
---
Tested when adding and removing multiple scope tags in the same deployments
Requests are enqueued one after the other
---
_Microsoft Security Adapter_:
- Fix a bug in deployment of Intune ScopeTags when deploying concurrently multiple tags.
---
None
=> SALTO-7440: Deploy Intune ScopeTags one by one

packages/jira-adapter/src/filters/fields/context_deployment_filter.ts, packages/jira-adapter/src/reference_mapping.ts, packages/jira-adapter/test/filters/fields/field_context_deployment.test.ts
_fail fieldContextOption when the relevant feildContext fails_
---
---
---
=> SALTO-7414: fail fieldContextOption when the relevant feildContext fails

packages/jira-adapter/src/filters/fields/context_options_splitted.ts, packages/jira-adapter/test/filters/fields/context_options_deployment.test.ts
In case two cascade options had the same value we would not populate some of them with ids
---
For non-cascading option the optionId will be undefined, and it will be a part of the map name
---
Jira Adapter:
* Fixed a bug with deployment of same-name cascading options
---
None
=> SALTO-7438: duplicate values in cascading options

packages/microsoft-security-adapter-e2e/e2e_test/e2e_instance_generator.ts
The [previous fix](https://github.com/salto-io/salto/pull/7263) didn’t solve the issue since we don’t use checkStatus when an error is thrown. See the relevant code: https://github.com/salto-io/salto/blob/3592a0cde603d8039173bc53702dd58b62e8a055/packages/adapter-components/src/client/polling.ts#L24-L32.
We should think of a better way to fix this. For the meantime I will remove the life cycle policy assignment from the e2e in order to deflake them.
---
None
---
None
=> SALTO-7443: Fix Microsoft Security e2e flakiness

packages/serviceplaceholder-adapter/src/adapter_creator.ts, packages/serviceplaceholder-adapter/src/client/connection.ts, packages/serviceplaceholder-adapter/src/definitions/deploy/business_hours_schedule.ts, packages/serviceplaceholder-adapter/src/definitions/deploy/deploy.ts, packages/serviceplaceholder-adapter/src/definitions/types.ts
---
Where possible I used the unused exports instead of removing them. If we want to keep the others we will need to find some solution (if we want to ignore we would have to ignore entire files which I think is best avoided).
---
None.
---
None.
=> SALTO-7363: Removing unused exports from Service Placeholder Adapter

packages/microsoft-security-adapter/jest.config.js, packages/microsoft-security-adapter/src/definitions/requests/clients.ts
The fix didn’t solve the issue since we don’t use checkStatus when an error is thrown. See the relevant code: https://github.com/salto-io/salto/blob/3592a0cde603d8039173bc53702dd58b62e8a055/packages/adapter-components/src/client/polling.ts#L24-L32.
---
None
---
None
=> Revert "SALTO-7443: Fix assigning lifecycle policy to Entra group is flaky (#7263)

packages/salesforce-adapter/test/sfdx_parser/sfdx_dump.test.ts
No clear why it started failing after 7 months of stability. For now just aligning the expected output with what we're getting. If this happens again we should make the test more resilient to changes like this.
---
---
None.
---
None.
=> SALTO-7474: Fixing failing SFDX dump UT

packages/jira-adapter/src/filters/automation/automation_deployment.ts, packages/jira-adapter/test/filters/automation/automation_deployment.test.ts
When deploying an Automation creation we have another call to update its state to 'enabled'. This call could fail, and we need to inform the user the automation was created, but the state isn't 'enabled' as requested.
---
---
None
---
None
=> SALTO-7437 Jira Automation partial success on deploy

packages/salesforce-adapter/src/transformers/reference_mapping.ts
SALTO-7478: (Bugfix) Remove references that cause field integrity exception
---
None
---
None
=> SALTO-7478: (Bugfix) Remove references that cause field integrity exception

packages/adapter-components/src/deployment/deployment_deprecated.ts, packages/adapter-components/test/deployment/old_deployment.test.ts, packages/pagerduty-adapter/test/definitions/utils/schedule_layers.test.ts, packages/serviceplaceholder-adapter/jest.config.js
As the new infra does nacl casing on all keys, we need to invert it also in the old deploy infra to allow compatibility between the versions.
---
---
---
=> SALTO-6540 Invert nacl case for old deploy

packages/jira-adapter/src/filters/forms/forms.ts, packages/jira-adapter/src/filters/forms/forms_types.ts, packages/jira-adapter/src/reference_mapping.ts, packages/jira-adapter/test/filters/forms/forms.test.ts
---
---
- Users can now safely deploy forms that include default form fields.
---
- The default answer field in the forms NACL has been updated. It previously stored 'choices' as a list of string IDs. It has now been updated to use a list of key-value objects, where the IDs have been converted to references.
=> SALTO-7456: Add reference from Form to CustomFieldContextOption

packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/src/fetch.ts, packages/salesforce-adapter/src/fetch_profile/optional_features.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/adapter.discover.test.ts
SALTO-7409: Handle "INSUFFICIENT_ACCESS: insufficient access rights on entity" errors in retrieve
---
None
---
None
=> SALTO-7409: Handle "INSUFFICIENT_ACCESS: insufficient access rights on entity" errors in retrieve

packages/adapter-components/src/filters/service_url.ts, packages/adapter-components/test/filters/service_url.test.ts
When defining a service URL, we can use “template args” like so: `/account/{_parent.0.id}/home`. However, it fails to process args that use deep attribute under a parent, e.g., `_parent.0.account.id`. 
This is due to the fact that _parent has special handling, and we actually insert `_parent.0.account` into the context args. We then call lodash `_.get`, but it can’t handle string paths if one of the keys has dots in its name.
This PR changes the parent attributes insertion into args, to insert nested objects instead.
---
None
---
None
---
None
=> SALTO-7496: Fix service URL computation for deep-path into parent instances

packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/src/fetch.ts, packages/salesforce-adapter/test/adapter.discover.test.ts
SALTO-7409: (Bugfix) Handle "INSUFFICIENT_ACCESS: insufficient access rights on entity" errors in retrieve
---
- The error was not detected because it is received through a RetrieveResult errorMessage rather than a thrown error.
- Removed the error from the suppressed errors in readMetadata.
---
None
---
None
=> SALTO-7409: (Bugfix) Handle "INSUFFICIENT_ACCESS: insufficient access rights on entity" errors in retrieve

packages/adapter-components/src/deployment/change_validators/outgoing_unresolved_references.ts, packages/adapter-components/test/deployment/change_validators/outgoing_unresolved_references.test.ts, packages/workspace/src/validator.ts, packages/workspace/test/validator.test.ts, packages/workspace/test/workspace/workspace.test.ts
Validators' config messages look bad when the elemId is very long. Given the fact we already have the elemId as another field, should we omit it? Like we do in CV messages. We have these messages in the CLI as well, need to take into consideration.
Options:
1. Write a general term instead ('element' for example)
2. Provide the alias and use it instead.
3. Move the elemId to the end of the message
Attached approach (1) for a single validator. We'll need to do the same for all the rest once having a decision.
Current state:
---
None
---
None
---
None
=> SALTO-7434 Refine validators config message

packages/salesforce-adapter/cpq-sbaa-config-doc.md
Update examples in md to expsoe salto manage field for salesforce data fetch config
=> DOC-123: add salto management field to the examples

packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/src/fetch.ts, packages/salesforce-adapter/test/adapter.discover.test.ts
SALTO-7409: (Bugfix-2) Handle "INSUFFICIENT_ACCESS: insufficient access rights on entity" errors in retrieve
---
- No read request was made because the problematic type is referenced but does not directly exist in the retrieve request.
- The log of the original and updated retrieve request is too long and not helpful. 
---
None
---
None
=> SALTO-7409: (Bugfix-2) Handle "INSUFFICIENT_ACCESS: insufficient access rights on entity" errors in retrieve

packages/okta-adapter/src/config.ts
Remove a field in deployment
---
The field should be omitted as it's created by Okta post deploy
---
- Fix a bug in additions of GroupPush
---
None
=> SALTO-7510: Fix deployment of GroupPush type

packages/okta-adapter/src/change_validators/group_push_to_application_uniqueness.ts, packages/okta-adapter/test/change_validators/group_push_to_application_uniqueness.test.ts
The validator was using _groupBy by element id instead of element id full name 
---
---
- Fix a bug in deployment of Group Push, blocking deployment of group push if the group is mapped to a different app.
---
None
=> SALTO-7509: Fix GroupPush uniqueness validator

packages/jira-adapter/e2e_test/adapter.test.ts, packages/jira-adapter/e2e_test/instances/cloud/automation.ts, packages/jira-adapter/e2e_test/instances/datacenter/automation.ts, packages/jira-adapter/e2e_test/instances/datacenter/index.ts, packages/jira-adapter/src/config/config.ts, packages/jira-adapter/src/filters/automation/smart_values/smart_value_reference_filter.ts, packages/jira-adapter/src/filters/automation/walk_on_automation.ts, packages/jira-adapter/src/filters/field_references.ts, packages/jira-adapter/src/filters/fields/reference_to_fields.ts, packages/jira-adapter/src/filters/script_runner/script_template_expressions.ts, packages/jira-adapter/test/filters/automation/walk_on_automation.test.ts, packages/jira-adapter/test/filters/fields/field_references.test.ts, packages/jira-adapter/test/filters/fields/reference_to_fields.test.ts
Added support for advanced fields reference
---
Required some refactoring, made that in a different commit.
I also fixed a problem (missing functionality) in ScriptRunner where there were no missing references
(also a small bug in the E2E)
[Noise reduction](https://github.com/salto-io/salto_private/pull/10558) (also for scriptRunner) 
---
Jira Adapter:
* Added support to references in advanced fields in automations
* Added support for missing references in ScriptRunner scripts
---
Jira Adapter:
* customfields IDs in advacedFields (in automation type) will become references. 
* ScriptRunner scripts that uses missing custom fields will be replaced with missing references
=> SALTO-7399: advanced fields references

packages/core/index.ts
Expose getPlan from core package, so we can easily create plan objects and provide them "change-errors". This is needed for SAAS-13046.
---
None
---
None
---
None
=> SALTO-7521: Expose getPlan from Core package

packages/salesforce-adapter/src/sfdx_parser/sfdx_dump.ts
It's too slow.
---
---
None.
---
None.
=> SALTO-7532: Stop loading SFDX project after dump

packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/src/transformers/xml_transformer.ts
* We get a log for every element with a parent because we drop the annotation in the transform even though we don't need the annotations during deploy.
* Logging the content of files added to the zip is extremely spammy and unintelligible anyway.
---
---
None.
---
None.
=> SALTO-7504: Reducing logs spam during deploy

packages/salesforce-adapter/src/fetch_profile/optional_features.ts
SALTO-7409: Make handleInsufficientAccessRightsOnEntity optional feature enabled by default 
---
None
---
None
=> SALTO-7409: Make handleInsufficientAccessRightsOnEntity optional feature enabled by default 

packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_file_cabinet.ts, packages/netsuite-adapter/src/config/types.ts, packages/netsuite-adapter/test/client/suiteapp_client/suiteapp_file_cabinet.test.ts
1. add the `netsuite.suiteAppClient.numOfFolderIdsPerFilesQuery` config to set a custom chunk size
2. don't throw in case of a failure in a files count query
---
---
- fix SuiteApp files counts query fails
---
None
=> SALTO-7537 fix SuiteApp files counts query fails

packages/salesforce-adapter/src/fetch.ts
It's easier to compare chunks when they are sorted.
---
---
None.
---
None.
=> SALTO-7457: Improving retrieve chunk log

packages/workspace/src/workspace/nacl_files/elements_cache.ts, packages/workspace/test/workspace/nacl_files/elements_cache.test.ts
Before this fix, if an element that had merge errors was removed, its errors would persist until the cache was cleared
---
---
Core:
- Fixed issue where merge errors would persist even if the offending element was removed
---
_None_
=> SALTO-7559: Remove merge errors when element is deleted

packages/salesforce-adapter/src/filters/remove_fields_and_values.ts
When running a partial fetch / changes detection, the we use the profile type from the workspace which does not match the profile values at the point when the remove_files_and_values filter runs.
changing the call to be non-strict to avoid excessive logs
---
Reproduced locally - before this change got ~4k logs in a fetch of a fairly small env, after this change no such logs
---
_None_
---
_None_
=> SALTO-7529: Reduce type mis-match logs from salesforce

packages/parser/src/parser/internal/native/consumers/values.ts, packages/parser/src/parser/internal/native/lexer.ts, packages/parser/test/parser/dump.test.ts, packages/parser/test/parser/parse.test.ts
In multiline template expressions the parser would not properly handle escaped multiline string endings. so if there was an escaped ''' in the template expression, it would not be unescaped
---
---
Parser:
- Fixed issue with parsing multiline template expressions that would lead to unintended pending changes
---
_None_
=> SALTO-7531: Fix parser wrong escape handling in multiline template expressions

packages/okta-adapter/src/definitions/deploy/deploy.ts, packages/okta-adapter/src/definitions/fetch/fetch.ts, packages/okta-adapter/src/reference_mapping.ts
1. Support deploy for `Feature` type
2. Add new type called Threat Insights (singleton)
---
---
- Support managing tenant features via Salto
- Support managing Threat Insights configurations 
---
- Threat Insights configuration will be added to workspace
=> SALTO-7561-SALTO-7562-Add Features deploy support, add Threat Insights type

packages/okta-adapter/src/definitions/deploy/deploy.ts, packages/okta-adapter/src/definitions/fetch/fetch.ts
---
---
- Add support for Okta Admin console session settings
---
- Okta Admin console session settings will be added
=> SALTO-7570: Add Okta admin console session time settings
