salto-io/salto

packages/salesforce-adapter/src/types.ts
MarketoEmailTemplates should be skipped by default.
[ticket](https://salto-io.atlassian.net/browse/SALTO-732)
=> SALTO-732-Marketo email templates should be skipped by default

packages/core/src/parser/internal/lexer.ts, packages/core/test/parser/internal/hcl.test.ts
The . operator in JS regexes catches everything expect line breaks. It turns out that JS consider the \u2028 and \u2029 chars to be line breaks as well for that purpose. This change remove the . operator from the lexer and replaces it with a group that catches anything but \r or \n to overcome this issue.
=> replaced . usage in lexer ts regexes to [^\r\n] in order to catch u2028

docs/user_guide.md
the curl line in the guide was wrong as we need to follow redirects when trying to download `latest`
=> change curl line to follow redirects

packages/adapter-api/src/builtins.ts
before this, in every `deploy` / `preview` we would get a ton of warnings in the log like:
```
warn adapter-utils/utils Array value and isListType mis-match for field - _parent. Only ListTypes should have array values.
```
this fixes these warnings
=> fix instance annotation expected types to match the actual expected types

packages/hubspot-adapter/package.json, packages/hubspot-adapter/src/client/client.ts, packages/hubspot-adapter/test/client.test.ts
What's here?
Handle fetch (getAll) permissions case as expected (if there's no permissions - return empty)
I had to change our whole error handling in the client cause the best way to discover it's a permissions error was not available. That's why it might look much "bigger" than the product impact.
=> SALTO-567: HubSpot permissions

packages/salesforce-adapter/e2e_test/adapter.test.ts, packages/salesforce-adapter/src/transformers/xml_transformer.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/adapter.discover.test.ts, packages/salesforce-adapter/test/transformers/xml_transformer.test.ts
Basically changing all Apex* components to be StaticFiles
Instead of being saved as strings in the `content` parameter, the content will be saved in the `static-resources` dir, under the following convention `salesforce/{componentType}/filename.ext'.
E.g.
`static-resources/salesforce/classes/ApexClassForProfile.cls`
~Please note that the first commit (not SF related) might be dropped due to @ori-moisis 's fix at https://github.com/salto-io/salto/pull/986~
=> Add StaticFiles to SalesForce Apex files

packages/cli/e2e_test/helpers/workspace.ts, packages/cli/e2e_test/multi_env.test.ts, packages/core/src/workspace/nacl_files/mutil_env/routers.ts, packages/core/test/workspace/multi_env/routers.test.ts
Changed normal fetch behaviour to route add changes to the env and not common if the top level element is env specific.
=> fetch add changes go to env if there is no top level element in common

docs/user_guide.md, packages/cli/e2e_test/NACL/add.nacl, packages/cli/e2e_test/helpers/workspace.ts, packages/cli/e2e_test/salto.test.ts, packages/core/src/api.ts, packages/core/src/core/expressions.ts, packages/core/src/core/fetch.ts, packages/core/src/core/plan/plan.ts, packages/core/src/serializer/elements.ts, packages/core/src/serializer/parse_result.ts, packages/core/src/workspace/local/state.ts, packages/core/test/api.test.ts, packages/core/test/core/expressions.test.ts, packages/core/test/core/fetch.test.ts, packages/core/test/core/plan/plan.test.ts, packages/core/test/serializer/serializer.test.ts, packages/core/test/workspace/local/cache.test.ts
* Added different serialization for state vs cache.
* Now fetch, deploy, etc. all work.
* Added tests.
* Added documentation.
=> SALTO-696: Variables fetch, preview and deploy

lerna.json, packages/adapter-api/package.json, packages/adapter-utils/package.json, packages/cli/package.json, packages/core/package.json, packages/dag/package.json, packages/e2e-credential-store/package.json, packages/file/package.json, packages/hubspot-adapter/package.json, packages/logging/package.json, packages/lowerdash/package.json, packages/netsuite-adapter/package.json, packages/persistent-pool/package.json, packages/salesforce-adapter/package.json, packages/vscode/package.json
Note: This version will modify the in which certain elements are written to the NaCL. As a result - some of the changes won't take effect until the fetching the services. For more details in which changes will require a fetch - see below.
**What's New**
* Added a new CLI command `rename` to rename an existing environment (https://github.com/salto-io/salto/blob/master/docs/user_guide.md#salto-env-command-name-new-name)
* Added variable support to NaCL (https://github.com/salto-io/salto/blob/master/docs/user_guide.md#variables)
* Added static files support to NaCL
_Hubspot adapter_
* Auto generated attributes are no longer written to the NaCL files.
* Emails are used in the NaCL files instead of internal user ids in order to improve readability. `Note that this may result in validation …
=> Bump to version 0.1.15

packages/core/src/parser/expressions.ts, packages/core/src/workspace/nacl_files/nacl_files_source.ts
~Delete static files upon delete changes~
~Use only first source map positions when deleting static files~
Calculate source map for functions expression without creating an extra id for the parameters.
=> Make multienv work for static files

.github/workflows/notices.yml
Instead of every merge to `master`.
It runs on the latest commit in `master` in that point in time (see [docs](https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule))
=> NOTICES github action: run once a week

packages/core/src/api.ts
Currently, if you would create a new env and add a service, the service config would be changed to the default one. This PR fixes it.
=> fix default adapter config bug

packages/salesforce-adapter/src/filters/record_type.ts
The bug was that the code assumes that each record type got a business process field, but its not true. 
as you can see here (taken from the documentation of RecordType):
This means that for records type for other types than lead, opportunity, solution, and case this log message will be written.
So I just added an `if` that checks if this field exists before it writes that log.
=> SALTO-748-fix business process undefined in logs bug

packages/adapter-api/src/elements.ts, packages/core/src/core/merger/index.ts, packages/core/src/core/merger/internal/object_types.ts, packages/core/src/parser/language.ts, packages/core/test/merger.test.ts
---
This was annoying in #1018, was easier to remove support for `update` than make it work with #1018
=> SALTO-286: remove field update syntax

packages/adapter-api/src/elements.ts, packages/adapter-api/src/values.ts, packages/adapter-api/test/values.test.ts, packages/cli/src/commands/fetch.ts, packages/cli/test/commands/fetch.test.ts, packages/core/src/api.ts, packages/core/src/serializer/elements.ts, packages/core/test/serializer/serializer.test.ts, packages/lowerdash/src/types.ts, packages/lowerdash/test/types.test.ts
* Removed `serializedTypeName`
* We no longer rely on the value of `constructor.name`
=> SALTO-769: Serialization without relying on constructor name

lerna.json, packages/adapter-api/package.json, packages/adapter-utils/package.json, packages/cli/package.json, packages/core/package.json, packages/dag/package.json, packages/e2e-credential-store/package.json, packages/file/package.json, packages/hubspot-adapter/package.json, packages/logging/package.json, packages/lowerdash/package.json, packages/netsuite-adapter/package.json, packages/persistent-pool/package.json, packages/salesforce-adapter/package.json, packages/vscode/package.json
Note: This version will hide the types folder in the Hubspot directory after the first fetch. The elements data will remain in the state file.
**What's New**
* Improved NaCL files parsing speed. 
* Removed the `update` syntax from the NaCL language.
* Added a new workspace size telemetry. (See: https://salto.io/telemetry_c.html)
* The NaCL static file function will no longer allow access for files that are not located within the static files folders.
_Hubspot adapter_
* Large JSON values are now saved in static files.
* Elements from the Hubspot types folder are fetched to the state file, but are not written to the NaCL files.
* Will no longer attempt to deploy changes to readonly fields.
* Fixed default values are assigned for fields with no default values if the field type is an object …
=> Bump to version 0.1.16

packages/netsuite-adapter/scripts/types_generator.py, packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/constants.ts, packages/netsuite-adapter/src/transformer.ts, packages/netsuite-adapter/src/types/custom_types/advancedpdftemplate.ts, packages/netsuite-adapter/src/types/custom_types/emailtemplate.ts, packages/netsuite-adapter/src/types/field_types.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/client/client.test.ts, packages/netsuite-adapter/test/transformer.test.ts, packages/netsuite-adapter/test/types.test.ts
Some context:
In SDF, emailtemplate & advancedpdftemplate types may have another file in the project containing the template's content. In the xml there is no mention for that content and the way to understand the connection between the content file and the xml is by the files names (e.g. `email_template_script_id.xml` & `email_template_script_id.template.html`).
In this PR:
- detect the additional files suffix
- add a 'content' field to types with additional file
- fetch the content from the additional file to the `content` field and set it as a `StaticFile`
- deploy the `content` value to a separate file in the project upon add & update
- support resolve & restore of static files in the adapter
=> Netsuite: Support additional files

packages/cli/.vscode/tasks.json, packages/persistent-pool/test/lib/dynamodb/dynamodb_repo.e2e.test.ts
allows running the build in vscode the background
=> vscode - add tsc watch task for cli

packages/core/src/workspace/local/state.ts, packages/core/src/workspace/state.ts, packages/core/test/workspace/local/state.test.ts
No code (except tests) used the "feature" of `State` that allowed passing in multiple elements to `set` and `remove`.
since this was a confusing interface (get/set/remove become asymmetric) and nothing actually needed it, I changed it to always work on a single element (as it is used in all cases in the core)
=> remove unused interface complexity

lerna.json, packages/adapter-api/package.json, packages/adapter-utils/package.json, packages/cli/package.json, packages/core/package.json, packages/dag/package.json, packages/e2e-credentials-store/package.json, packages/file/package.json, packages/hubspot-adapter/package.json, packages/logging/package.json, packages/lowerdash/package.json, packages/netsuite-adapter/package.json, packages/persistent-pool/package.json, packages/salesforce-adapter/package.json, packages/vscode/package.json
Note: This version will fix a bug related to settings instance names. This might lead to changes on the first fetch for every environment. It is recommended to fetch each environment in isolated mode after upgrading to this version.
**What's New**
* Improved NaCL files parsing speed. 
_VScode extension_
* Improved extension responsiveness.
* Added auto complete for type level annotations
* Improved goto references and goto definitions functionality
* When auto completing attribute values, references will only be suggested if the element ID prefix was already entered (declutter the suggestions.)
* Auto complete will no longer be re-invoked when accepting an auto complete suggestion.
* Auto complete will no longer suggest field updates.
_Salesforce adapter_
* Will no longer fetch …
=> Bump to version 0.1.17

lerna.json, packages/adapter-api/package.json, packages/adapter-utils/package.json, packages/cli/package.json, packages/core/package.json, packages/dag/package.json, packages/e2e-credentials-store/package.json, packages/file/package.json, packages/hubspot-adapter/package.json, packages/logging/package.json, packages/lowerdash/package.json, packages/netsuite-adapter/package.json, packages/persistent-pool/package.json, packages/salesforce-adapter/package.json, packages/vscode/package.json
**What's New**
* Added a new fetch command flag `--state-only` to fetch service changes to the state file without applying them the the NaCL file.
* Added a new flag `-d` to the preview command to display a more detailed deploy plan.
* Added the abilty to define regex based restriction and validations.
_VScode extension_
* Added goto defintion and goto references support for type level annotations
* Added support for VScode version 1.36
_Salesforce adapter_
* Added a configuration flag `hideTypesInNacls` to toggle the ability to store certain types in the state file and not in the NaCL files.
* Added territory types to the default skip list.
* Fixed new elements are create in the NaCL files with an extra indentation level
* Fixed references inside an array are not indented when dumped in …
=> Bump to version 0.1.18

yarn.lock
there was a change to a `package.json` that was committed with without committing the resulting change to `yarn.lock`
=> update yarn lock file

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/adapter_creator.ts, packages/salesforce-adapter/src/config_change.ts, packages/salesforce-adapter/src/filters/custom_objects_instances.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
Change from namespaceList to a more advanced configuration with includeNamespace, excludeObject and includeObject to support the "right" CPQ configuration and allow fluidity
=> Change the Records Management configuration

packages/adapter-api/tsconfig.json, packages/core/tsconfig.json, packages/salesforce-adapter/tsconfig.json
Now that the target is es2019, I think we do not need the extra "lib" for async iterable
=> remove unneeded lib from tsconfig

packages/salesforce-adapter/e2e_test/adapter.test.ts, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/filters/custom_objects.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/custom_objects.test.ts
Move system fields (besides nameField) to be saved only in the state and make them not required or editable. 
This is needed to make instances deploy work on create.
=> Make system fields (^nameField) hidden, not required and editable

packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/client/client.test.ts
since the Java CLI triggers API call per scriptId which makes it much less efficient
This reverts commit 956a2acf
=> Revert "Netsuite: skip the fetch of custom types that are in the typesToSkip also in SDF"

packages/adapter-api/src/builtins.ts, packages/adapter-utils/test/common.ts, packages/adapter-utils/test/deploy.test.ts, packages/salesforce-adapter/e2e_test/adapter.test.ts, packages/salesforce-adapter/e2e_test/utils.ts, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/src/client/jsforce.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/fetch.ts, packages/salesforce-adapter/src/filters/missing_fields.ts, packages/salesforce-adapter/src/filters/settings_type.ts, packages/salesforce-adapter/src/filters/workflow.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/src/transformers/xml_transformer.ts, packages/salesforce-adapter/test/adapter.crud.test.ts, packages/salesforce-adapter/test/adapter.discover.test.ts, packages/salesforce-adapter/test/adapter.ts, packages/salesforce-adapter/test/client.ts, packages/salesforce-adapter/test/connection.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts, packages/salesforce-adapter/test/transformers/xml_transformer.test.ts, packages/salesforce-adapter/test/utils.ts
Change the way fetch works for types that use the `retrieve` endpoint:
- rely on information from the metadata API instead of hard coded constants
- remove a heuristic that extracted an instance fullName from its fileName and use the fullName from the API instead
=> SALTO-800: refactor fetch to support additional types

packages/adapter-api/src/adapter.ts, packages/adapter-utils/test/change_validator.test.ts, packages/core/src/api.ts, packages/core/src/core/fetch.ts, packages/core/src/core/plan/filter.ts, packages/core/src/core/plan/plan.ts, packages/core/test/api.test.ts, packages/core/test/core/fetch.test.ts, packages/core/test/core/plan/filter.test.ts, packages/core/test/core/plan/plan.test.ts, packages/hubspot-adapter/src/change_validators/form_field.ts, packages/hubspot-adapter/src/change_validators/json_type.ts, packages/hubspot-adapter/src/change_validators/readonly.ts, packages/hubspot-adapter/test/change_validators/form_field.test.ts, packages/hubspot-adapter/test/change_validators/json_type.test.ts, packages/hubspot-adapter/test/change_validators/readonly.test.ts, packages/hubspot-adapter/test/common/mock_changes.ts, packages/lowerdash/src/collections/iterable.ts, packages/netsuite-adapter/src/change_validators/remove_customization.ts, packages/netsuite-adapter/test/change_validators/remove_customization.test.ts, packages/salesforce-adapter/src/change_validators/package.ts, packages/salesforce-adapter/src/change_validators/picklist_standard_field.ts, packages/salesforce-adapter/test/change_validators/package.test.ts, packages/salesforce-adapter/test/change_validators/picklist_standard_field.test.ts, packages/salesforce-adapter/test/utils.ts
As preparation for grouping changes with custom logic, this PR removes the unnecessary use of change grouping before running change validators.
=> SALTO-791: remove grouping from plan filter

packages/workspace/src/serializer/elements.ts
Since we changed `content` to `internalContent`, we kept writing HUGE data to our state that isn't needed.
This change updates the serialize accordingly
=> Ensure that static file content are NOT in state

packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/adapter_creator.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/constants.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/adapter_creator.test.ts, packages/netsuite-adapter/test/client/client.test.ts, packages/salesforce-adapter/src/adapter_creator.ts, packages/salesforce-adapter/test/adapter.creator.test.ts
This PR  reduces the amount of path args to importFiles in case of failure. It might happen in the following scenarios:
- If having too many arguments, the command might fail due to OS memory issues.
- when having a single file that fails (e.g. due to locked file), the whole command fails. thus, splitting to smaller chunks will eventually return only the valid files.
In addition, filePathRegexSkipList mechanism to accelerate the fetch / reduce noise for users.
=> Netsuite: overcome errors in importFiles & support filePathRegexSkipList

docs/user_guide.md, packages/cli/src/commands/restore.ts, packages/cli/src/prompts.ts, packages/cli/test/commands/restore.test.ts, packages/core/index.ts, packages/core/src/api.ts, packages/core/src/core/restore.ts, packages/core/test/core/restore.test.ts
* Refactored `restore` to work more like `deploy` than `fetch`, including:
* ~Not making changes without user approval (default `interactive` to true - there's an "approve all" option on the first prompt)~ - reverted based on input from Tomer
* Not relying on event emitters
* Added a `--dry-run` option that prints the change summary and exits
* Optionally print a summary of all the planned changes using `--list-planned-changes` (always included in dry-run mode)
* Optionally include value changes in the summary with `--detailed-plan`
=> SALTO-811: Make restore behave more like deploy, add dry-run and plan printing options

packages/core/src/core/fetch.ts, packages/core/src/core/plan/dependency/dependency.ts, packages/core/src/core/plan/filter.ts
- Add shortcuts to dependency and plan filter to avoid the setup calculation
when there are no dependencies / filters
- Skip dependencies on fetch plans where the dependencies do not matter
=> SALTO-843: Improve fetch plan calculation performance

.circleci/config.yml, yarn.lock
The current check does not work because of an [open issue in yarn](https://github.com/yarnpkg/yarn/issues/4098)
=> Add CI check that yarn.lock is up to date

packages/cli/test/mocks.ts, packages/core/src/core/plan/dependency/dependency.ts, packages/core/src/core/plan/filter.ts, packages/core/src/core/plan/plan.ts, packages/core/test/common/plan.ts, packages/dag/src/diff.ts, packages/dag/src/group.ts, packages/dag/src/nodemap.ts, packages/dag/test/diff.test.ts, packages/dag/test/nodemap.test.ts
General changes:
- Avoid cloning graphs for each node
- Remove multiple nodes to slightly improve deleteNode efficiency (still O(n))
mergeNodesToModify:
- check for cycles before creating the merged node
Group graph:
- Add index for node id -> group id to avoid O(n) searches for each node
- add items to existing node instead of creating a new one and merging
- removed log that wasn't very useful and took a non-trivial percentage of time
---
Based on top of #1225 - please review separately (only review second commit here)
profiling:
scenario - vanilla SFDC workspace, for each element add an annotation / value to create a modification diff, for each type create a copy new type to create an addition diff and rename all fields from the existing type to create remove and add changes that would …
=> SALTO-843: Improve graph operations performance

packages/salesforce-adapter/e2e_test/custom_object_instances.test.ts, packages/salesforce-adapter/src/filters/custom_objects_instances.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/custom_object_instances_references.test.ts, packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
**Name-based ElemID logic:**
* If has no masterDetail fields ElemID is based on  record "Name" value
* If has masterDetail feilds ElemID is based on master's "Name" joined with record's "Name"
* Special support for PricebookEntry & CustomAction because masterDetail logic is not enough for their cases. This needs to be in the same PR cause currently they get "Name" as ElemID and duplicates can occur
=> Add name-based ElemID logic to CustomObject instances

packages/adapter-api/.vscode/launch.json, packages/adapter-utils/.vscode/launch.json, packages/cli/.vscode/launch.json, packages/core/.vscode/launch.json, packages/dag/.vscode/launch.json, packages/hubspot-adapter/.vscode/launch.json, packages/lang-server/.vscode/launch.json, packages/logging/.vscode/launch.json, packages/netsuite-adapter/.vscode/launch.json, packages/salesforce-adapter/.vscode/launch.json, packages/vscode/.vscode/launch.json, packages/workspace/.vscode/launch.json
seems like newer versions of vscode don't handle this extra `--inspect-brk` well
old versions should handle the command without it (seems to work for other commands)
=> remove redundant --inspect-brk from jest launch command

packages/salesforce-adapter/e2e_test/adapter.test.ts
During setup the test suite attempts to remove a custom object but it does not
remove a field that references that custom object first, so if that fields exists
the setup will fail and the whole suite will fail with it
=> Fix SFDC e2e setup failures

packages/salesforce-adapter/src/filters/missing_fields.json
1. Add interval to Report
2. Add componentType to Dashboard
3. Fix values restriction annotation in existing missing fields
---
Turns out that when we refactored the `_restriction` annotation, we did not fix the missing fields that we define manually, so they had their restriction values in the wrong annotation
=> Fix salesforce missing fields

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/foreign_key_references.ts, packages/salesforce-adapter/src/filters/hide_types.ts, packages/salesforce-adapter/src/filters/instance_references.ts, packages/salesforce-adapter/src/filters/workflow_rule.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/connection.ts, packages/salesforce-adapter/test/filters/foreign_key_references.test.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts
Use the `isForeignKey` and `foreignKeyDomain` fields of the `DescribeValueType` API to identify references.
This is done by introducing a new annotation type for Salesforce - `FOREIGN_KEY_DOMAIN` (starting with a SF-specific one until we see a need to generalize), and using it to look for instances of relevant types for each of the annotated fields.
=> SALTO-804 Resolve more references using Salesforce DescribeValueType API

packages/core/src/core/plan/plan.ts, packages/dag/src/diff.ts, packages/dag/src/group.ts, packages/dag/src/nodemap.ts, packages/dag/test/diff.test.ts, packages/dag/test/nodemap.test.ts
- Add reverse neighbors mapping to data structure to allow for faster deleteNode
- Add "clearEdges" to avoid the need to clone the graph in order to remove all edges
=> SALTO-843: Improve DAG deleteNode performance

packages/salesforce-adapter/src/transformers/salesforce_types.ts
@omrilit - no refactor goes unpunished :wink:
since `caseSubjectOptionType` was not returned under `allMissingSubTypes` we got validation errors (because the type was unknown to the core), I deleted it instead of adding it to the list for consistency with the rest of the adapter - it does not create types for enums, enums are strings with restrictions
=> SALTO-868: fix manual definition of social settings type

packages/cli/e2e_test/NACL/salto.config/salesforce.nacl, packages/salesforce-adapter/e2e_test/adapter.test.ts, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/filters/foreign_key_references.ts, packages/salesforce-adapter/src/filters/reference_annotations.ts, packages/salesforce-adapter/test/filters/foreign_key_references.test.ts, packages/salesforce-adapter/test/filters/reference_annotations.test.ts
Note: This needs to be run on a clean environment in order for existing annotations to be converted to references.
=> SALTO-858 - Convert referenceTo to reference expressions

packages/cli/e2e_test/helpers/workspace.ts, packages/cli/e2e_test/multi_env.test.ts, packages/cli/e2e_test/salto.test.ts, packages/cli/src/callbacks.ts, packages/cli/src/commands/env.ts, packages/cli/src/formatter.ts, packages/cli/src/prompts.ts, packages/cli/test/commands/env.test.ts, packages/cli/test/mocks.ts, packages/core/index.ts, packages/core/src/local-workspace/dir_store.ts, packages/core/src/local-workspace/static_files_cache.ts, packages/core/src/local-workspace/workspace.ts, packages/core/test/workspace/local/directory_store.test.ts, packages/file/src/file.ts, packages/workspace/src/workspace/nacl_files/mutil_env/multi_env_source.ts, packages/workspace/src/workspace/workspace.ts
* Add a prompt when adding the 2nd env if some configuration exists and no configuration is isolated (if something is in the env folder we assume the user made a conscious decision about what should remain in the common folder)
* Add a `force` flag to the env command to avoid this interactive prompt
=> SALTO-873 Multienv - suggest to isolate the existing env when adding a 2nd env

packages/salesforce-adapter/e2e_test/adapter.test.ts, packages/salesforce-adapter/e2e_test/utils.ts, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/fetch.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/src/transformers/xml_transformer.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts, packages/salesforce-adapter/test/transformers/xml_transformer.test.ts
- Additional annotations on metadata types (dirName, suffix) to store information that will later be useful for deploy
- Change isFolder annotation to folderContentType annotation for simpler lookup and for deploy where we won’t have context
- Add typescript types for metadata instances and object types instead of relying on constants
- Removed unused type MetadataInfoWithStaticFile
- Remove duplicate constants for metadata content field name
---
As preparation for supporting the `deploy` api on all types, we need to store information that we get in `fetch` so we can use it later in `deploy` (otherwise we'd have to manually add all this information under the `ZipProps` map which is not a scalable solution.
This PR doesn't actually use this information yet, the next PR will contain the …
=> SALTO-793: store relevant information in type annotations on fetch

packages/cli/src/commands/copy.ts, packages/cli/src/commands/index.ts, packages/cli/src/formatter.ts, packages/cli/src/prompts.ts, packages/cli/test/commands/copy.test.ts, packages/cli/test/mocks.ts, packages/workspace/src/workspace/nacl_files/mutil_env/multi_env_source.ts, packages/workspace/src/workspace/nacl_files/mutil_env/routers.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/multi_env/multi_env_source.test.ts, packages/workspace/test/workspace/multi_env/routers.test.ts
Add a cli command to copy elements between environments, without going through common - with temporary name `copy`.
The requirement is that if the element already exists in the target environment, it will be overwritten (rather than merged).
For completeness I think we'll want to add some more granular control (such as deciding between merge and override) - starting with the basic requirements and will discuss the rest separately (see the ticket for more details).
=> SALTO-875 - add copy command for duplicating elements across environments

packages/cli/e2e_test/NACL/salto.config/salesforce.nacl, packages/cli/src/convertors.ts, packages/lowerdash/src/index.ts, packages/lowerdash/src/regex.ts, packages/lowerdash/test/regex.test.ts, packages/netsuite-adapter/src/adapter_creator.ts, packages/salesforce-adapter/src/adapter_creator.ts, packages/salesforce-adapter/src/filters/custom_objects_instances.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/adapter.creator.test.ts, packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
Use regex for `includeObjects`, `excludeObjects` and `allowReferencesTo` in `dataManagement` config.
What's here?
* Extract `isValidRegex` to lowerdash and use it all around the code
* Use regex'es instead of complete matches in custom_object_instances filter
* Validate the regex'es in the configuration
=> dataManagement config by regex and not full string match

packages/cli/src/commands/env.ts, packages/cli/src/prompts.ts, packages/cli/test/commands/env.test.ts
Add a flag for accepting all salto suggestions - currently only used for a `create env` recommendation.
=> SALTO-873 Add accept-suggestions / y cmdline argument

packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts
Some "top level" types are also embedded in other types, we need to avoid the race
condition of creating them as embedded types if we happen to get to the embedded
definition before we get to the top level definition
---
While this doesn't resolve the issue that causes e2e to fail, it should take away the base scenario that caused it to happen so often
=> SALTO-908: Do not create base types as embedded types

docs/user_guide.md, packages/cli/src/commands/service.ts, packages/cli/src/filters/service.ts, packages/cli/src/prompts.ts, packages/cli/test/commands/service.test.ts, packages/cli/test/filters/service.test.ts, packages/cli/test/mocks.ts
changed 'service add' command so that it now requests credentials, and only if they are valid - adds an adapter.
also added a 'nologin' flag (to be used like: 'service add salesforce --nologin') that leads to adding the adapter without asking for credentials at the moment.
please note that it was impossible to name the flag 'no-login' because '--no-' is a Yargs prefix and causes Yargs to not recognise 'no-login' as one string.
=> Service add login bundle

packages/core/src/api.ts, packages/core/test/api.test.ts, packages/core/test/common/helpers.ts, packages/core/test/common/plan.ts
In the second commit there are the tests for this feature which required changed to existing tests to remove redundant mocks
=> Fix bug where deploy tried to add removed elements back to workspace

packages/core/src/api.ts
seems like the bug where `getDetailedChanges` changed its input was resolved and there is no need to clone the input anymore
Release notes: small performance improvement in deploy
=> remove redundant element clone

packages/salesforce-adapter/e2e_test/adapter.test.ts, packages/salesforce-adapter/src/transformers/xml_transformer.ts
According to [the documentation](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_package.htm#meta_package) that field is required
=> Add version field to deploy/retrieve packages

packages/adapter-api/src/utils.ts, packages/adapter-api/test/utils.test.ts, packages/lang-server/src/completions/suggestions.ts, packages/lang-server/src/definitions.ts, packages/workspace/src/workspace/hidden_values.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/hidden_values.test.ts
This is an existing bug that's preventing the addition of a hidden `internalId` in SALTO-900, and also related to SALTO-907.
(@ori-moisis 's solution)
Scenario: Adding a hidden field to an existing instance element.
Additional e2e tests are added [here](https://github.com/salto-io/salto/pull/1316/files#diff-c90bec8f7ee92483f615e645ca8da141R287).
=> Correctly hide fields added to existing elements

packages/core/src/core/fetch.ts, packages/core/test/core/fetch.test.ts
Fixes case where fetch would fail completely if there are conflicting IDs instead of filtering out only the elements that had the conflict
=> SALTO-865: drop elements that cause merge errors on fetch

packages/adapter-utils/test/utils.test.ts, packages/cli/e2e_test/multi_env.test.ts, packages/core/src/core/plan/plan.ts, packages/salesforce-adapter/e2e_test/utils.ts, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/fetch.ts, packages/salesforce-adapter/src/filters/add_missing_ids.ts, packages/salesforce-adapter/src/filters/custom_objects.ts, packages/salesforce-adapter/src/filters/remove_memory_only_annotations.ts, packages/salesforce-adapter/src/filters/settings_type.ts, packages/salesforce-adapter/src/filters/utils.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/src/transformers/xml_transformer.ts, packages/salesforce-adapter/test/filters/add_missing_ids.test.ts, packages/salesforce-adapter/test/filters/remove_memory_only_annotations.test.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts
Step 1 for SALTO-900 - retrieving salesforce ids for use to translate results from the tooling API (SALTO-899).
For instance elements, we're using the existing state-only mechanism. 
For fields, we use a new memory-only annotation (`id`). Once SALTO-910 is implemented, it will be converted to state-only and the removal filter will be deleted.
=> SALTO-900 Add state-only and memory-only salesforce internal ids

docs/user_guide.md, packages/adapter-api/src/builtins.ts, packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/utils.test.ts, packages/core/src/core/plan/dependency/reference_dependency.ts, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/src/client/jsforce.ts, packages/salesforce-adapter/src/filters/extra_dependencies.ts, packages/salesforce-adapter/src/filters/utils.ts, packages/salesforce-adapter/test/client.test.ts, packages/salesforce-adapter/test/connection.ts, packages/salesforce-adapter/test/filters/extra_dependencies.test.ts
Note: This also contains the changes from https://github.com/salto-io/salto/pull/1316 - please review only the 2nd commit (`extra_dependencies.ts` has almost all the new logic), and review the `internalId` changes on the other PR.
First step for populating references from the tooling API, continuing @ori-moisis 's initial work.
Using a new annotation for that, so that `_depends_on` can be kept for manually-configured dependencies.
Using salesforce ids retrieved from earlier calls to `listMetadataObjects` to avoid making additional API calls for this (so far, all references were resolved successfully).
We only include in in the new list references that are not already found on the element or (for instance elements) the object type. 
Next step: Reduce the number of references further by …
=> SALTO-899 Add references from the tooling API

packages/workspace/src/validator.ts
We currently omit validation warnings when annotation values are a list by the
type isn't and vice-versa.
This change also omits this type of warning for complex annotation values where
this mis-match occurs in a nested part of the annotation value
=> SALTO-934: Remove list type mismatch validation warnings on annotations

packages/cli/src/workspace/workspace.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- Write workspace errors to the log (currently only printed to the console)
- Add more context for parsing errors that are caused by nacl update
=> SALTO-930: debug log improvements

packages/core/package.json, packages/core/src/telemetry.ts, packages/core/test/telemetry.test.ts, yarn.lock
In case of unrecoverable error in sending telemetry, we'll give up on retrying, by this logic:
1. If it's a user error (`4xx`), we will stop immediately without any further retries
2. If it's another type of error (either `5xx` or any other network error) we will retry a few times and in case where we fail sending events consecutively we will give up
Also tested locally, once without any server running (so network error);
```
$ rg telemetry /tmp/fetch.log
1:2020-08-27T13:00:05.995Z info cli/cli CLI started. Version: version 0.1.23, branch salto-931/fix/telemetry_stop_retries, hash b536fe92
71:2020-08-27T13:00:07.079Z debug core/telemetry failed sending telemetry events: Error: connect ECONNREFUSED 127.0.0.1:8080
184:2020-08-27T13:00:08.084Z debug core/telemetry failed sending telemetry …
```
=> Stop trying sending telemetry if error is unrecoverable

packages/adapter-api/src/change.ts, packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/utils.test.ts, packages/core/src/core/diff.ts, packages/core/src/core/plan/filter.ts, packages/core/src/core/restore.ts, packages/workspace/src/workspace/nacl_files/multi_env/projections.ts, packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/src/workspace/nacl_files/nacl_file_update.ts
- Replace a number of different places that duplicated the logic of applying a function on a change
- Change filterBy to be sync (needed in order to use the new function in some places)
- Improve type inference for is*Change functions (before this calling the type guard with a DetailedChange would have lost the data type information)
---
None (refactor)
=> Add function to apply transform on change data

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/custom_object_instances_deploy.ts, packages/salesforce-adapter/src/filters/custom_objects_instances.ts, packages/salesforce-adapter/test/adapter.crud.test.ts, packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
Implemented `upsert` logic for Custom Object Instances on Add based on idFields from the configuration.
The general flow on Add is -
1. Query where WHERE based on idFields (to see if it already exists in the service)
2. If it exists, use update. If it didn't exist, use add.
3. Gather the results together
(A lot of the code is because I moved all the crud tests of Custom Object Instances out of the "adapter" file (well, the flow is separate so why not the tests as well!) and then added a lot of cases there. But a big chunk of is copy-paste.)
---
Added `upsert` logic for Custom Object Instances on Add based on `saltoIDSettings` in the `dataManagement` configuration.
Deploying Instances between environments is now "safer". It will not create logically duplicate Instances when …
=> Custom object instances upsert

packages/core/src/local-workspace/state.ts, packages/core/test/api.test.ts, packages/core/test/common/state.ts, packages/workspace/src/workspace/state/in_mem.ts, packages/workspace/test/workspace/state.test.ts, packages/workspace/test/workspace/workspace.test.ts
Use in memory state instead of partial mocked state in unit tests
---
None (refactor)
=> Extend in memory state implementation to support the full State interface

packages/salesforce-adapter/src/adapter_creator.ts, packages/salesforce-adapter/test/adapter.creator.test.ts
`dataManagmenet` => `dataManagement`
=> Fix typo of an error string in salesforce adapter creator

packages/core/src/local-workspace/dir_store.ts, packages/core/test/workspace/local/directory_store.test.ts, packages/workspace/src/workspace/dir_store.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/common/nacl_file_source.ts, packages/workspace/test/common/nacl_file_store.ts, packages/workspace/test/workspace/multi_env/multi_env_source.test.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts, packages/workspace/test/workspace/static_files/source.test.ts
We shouldn't parse all the nacls in order to determine if a workspace is empty.
=> SALTO-945: Use dir-based workspace.isEmpty check

packages/adapter-api/src/elements.ts, packages/adapter-api/test/elements.test.ts, packages/workspace/src/merger/index.ts
during merge, so that they will match their inner type annotations
=> SALTO-806 Added a method to ListType to be used for setting ListTypes annotations

packages/core/src/core/adapters/adapters.ts
After @hadasb request to print the SDF concurrency that is used in Netsuite to the log I think that it worths to log all of the adapters config values for debugging purposes.
=> Log adapter config values upon fetch & deploy

packages/adapter-api/src/change.ts, packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/utils.test.ts
since list types are a part of element lists throughout the code base and we can have changes on list types (like for example when an adapter returns a new list type), the type definition of `ChangeDataType` needed to be fixed.
Also, `transformElement` with a list type would crash, so that had to be fixed as well
=> fix ChangeDataType definition to include ListType and add support to transformElement

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/filters/hardcoded_lists.json, packages/salesforce-adapter/src/filters/missing_fields.json
- Extract content to static files in more metadata with content types
- Add missing fields and missing lists in a few tested metadata types
Metadata types added:
Certificate
ContentAsset
EclairGeoData
NetworkBranding
SiteDotCom
---
_Release notes_:
Improved support for salesforce types with content (Certificate, ContentAsset, EclairGeoData, NetworkBranding, SiteDotCom)
=> SALTO-749: Improve support for metadata with content in salesforce

packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/adapter.discover.test.ts
The documentation does not seems to suggest the limits defined in the code exists
Removing after seeing numbers that exceed the supposed restrictions in a real account
=> Remove restrictions from percision and scale annotations in salesforce

packages/cli/src/commands/service.ts, packages/cli/test/commands/service.test.ts, packages/core/src/api.ts, packages/core/test/api.test.ts
Before that change, there was a bug which called `installAdapter` only after `validateCredentials` or upon service addition when the `--nologin` flag was supplied. It causes a failure when adding netsuite adapter because it requires the jar to be installed prior to validating the credentials
=> Install adapter before calling validateCredentials

packages/adapter-utils/src/compare.ts, packages/workspace/src/workspace/nacl_files/multi_env/projections.ts, packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/test/workspace/multi_env/projections.test.ts, packages/workspace/test/workspace/multi_env/routers.test.ts
Change projections and router code to not omit changes to annotation types
---
- Fix issue where annotation type change was not written to Nacl
=> SALTO-958: Support type change for fields and annotations

packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/config.ts, packages/netsuite-adapter/test/adapter.test.ts
Until now we disabled the support for `savedsearch` type. We have a customer that said that although the value of the `savedsearch` is encrypted and regenerated every fetch, he has value in using it since this way he can back it up and move between envs. We still set it in skip list by default because it might be too noisy upon fetch but enable the user to control it using the config value.
@hadasb @netama @EllaSharakanski FYI
=> Netsuite: skip savedsearch type by default but allow the user to enable it

packages/adapter-api/src/change.ts
the previous casting (e.g `change is change<Field>`) did not actually work
=> changed generics definition for functions checking change type

packages/salesforce-adapter/src/change_validator.ts, packages/salesforce-adapter/src/change_validators/custom_field_type.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/change_validators/custom_field_type.test.ts, packages/salesforce-adapter/test/change_validators/picklist_standard_field.test.ts, packages/salesforce-adapter/test/change_validators/unknown_field.test.ts, packages/salesforce-adapter/test/utils.ts
the change validator checks for creation of new custom fields with invalid type, or change of existing custom fields to an invalid type.
=> SALTO-961 Added a change validator for custom field types

packages/lowerdash/src/values.ts, packages/salesforce-adapter/e2e_test/adapter.test.ts, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/custom_object_instances_deploy.ts, packages/salesforce-adapter/src/filter.ts, packages/salesforce-adapter/src/filters/lookup_filters.ts, packages/salesforce-adapter/src/filters/profile_permissions.ts, packages/salesforce-adapter/src/filters/topics_for_objects.ts, packages/salesforce-adapter/src/filters/value_set.ts, packages/salesforce-adapter/test/custom_object_instances.crud.test.ts, packages/salesforce-adapter/test/filters/filters.test.ts, packages/salesforce-adapter/test/filters/lookup_filters.test.ts, packages/salesforce-adapter/test/filters/profile_permissions.test.ts, packages/salesforce-adapter/test/filters/topics_for_objects.test.ts, packages/salesforce-adapter/test/filters/value_set.test.ts, packages/salesforce-adapter/test/filters/workflow.test.ts, packages/salesforce-adapter/test/utils.ts
The new callback replaces onAdd/onUpdate/onRemove and can be called in a more general way
from the adapter.
This is part of changing the adapter interface to apply multiple changes in one transaction
---
- None (refactor)
=> Refactor salesforce adapter filters to have onDeploy callback

packages/core/src/local-workspace/state.ts, packages/core/test/workspace/local/state.test.ts
After a recent change, if an env's name is the prefix of another (e.g. `env` + `env2`), its state elements would be included in the other env's state. This fixes it.
Also includes the changes from https://github.com/salto-io/salto/pull/1459
=> SALTO-965, SALTO-969 - Check state path prefix correctly and properly upgrade from old state file

packages/netsuite-adapter/src/config.ts, packages/netsuite-adapter/test/adapter.test.ts
Most of our tests on real NetSuite accounts has failed to import all objects in a single call. Instead of waisting 10 minutes until failing and then use the automatic fallback to type by type, it feels like it would be better to fetch type by type at first place.
=> Netsuite: fetch objects type by type by default instead of as a bulk due to failures in real accounts

packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
`_.trimEnd` truncates a list of characters, not a substring - so filenames ending with n/a/c/l would get their last characters truncated (`salesforce/Types/Skill.nacl` becomes `salesforce/Types/Ski.nacl`).
=> SALTO-977 Fix filename suffix truncate

packages/salesforce-adapter/src/change_validators/custom_field_type.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/custom_objects.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/change_validators/custom_field_type.test.ts
- fixed bug where field type change validator did not allow formula fields
- reduced validation severity to warning until we better understand the side effects of
removing field changes from a plan
=> SALTO-984: Fix field type validator false positive on formula fields

packages/adapter-utils/src/utils.ts, packages/core/src/core/plan/dependency/reference_dependency.ts, packages/core/test/core/plan/dependency.test.ts, packages/salesforce-adapter/test/filters/profile_permissions.test.ts
In the diff graph object types are separate from their fields and therefore
the dependencies of the object type node should not include the references from the fields
they should only include references from the type annotations
also, self references should not be added, no matter where they come from
=> SALTO-983: Fix reference dependency of types to not include all references from fields

packages/workspace/src/validator.ts, packages/workspace/test/validator.test.ts
In multienv we can get validation errors if an element in one of the environments has an array value, and the type is not from the known list types (the full scenario is described in the ticket).
This is one solution with some limitations - other alternatives are listed on the ticket.
=> SALTO-975 - Avoid validation error for array in non-list type and vice versa

packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/cpq/custom_script.ts, packages/salesforce-adapter/test/filters/cpq/custom_script.test.ts
**What's here?**
Extract the value of `SBQQ__Code__c` to a `.js` file. Handle sending it to SF as string using the `preDeploy`/`onDeploy` filter until SALTO-881 is done and the general case of string valued files and encoding in static files is handled
=> SALTO-938 - [continued but still not complete] Extract SBQQ__Code__c in CustomScript to static file

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/filters/cpq/custom_script.ts, packages/salesforce-adapter/test/filters/cpq/custom_script.test.ts
**Structure**
- `Resolve` before `preDeploy`
- `onDeploy` before `Restore`
- Run `restore` and `preDeploy` only on `mainElement` because `transformElement` on `Field` detaches it from parent
**Features**
- CustomScript `preDeploy` on `ObjectType` instead of `Field` changes
- Static file `preDeploy` on Buffer instead of StaticFile because it runs after `resolve` & remove `onDeploy` handling cause it's handled in restore
=> Reverse preDeploy & resolve and onDeploy & restore order + Change current filters accordingly

packages/salesforce-adapter/src/filters/field_references.ts, packages/salesforce-adapter/src/transformers/reference_mapping.ts, packages/salesforce-adapter/test/filters/field_references.test.ts
Populate more external-facing references (not pointing within the same flow).
Does not include some references that depend on a field of a parent object rather than a direct neighbor (such as `FlowRecordFilter.field`) - will add support for these in a separate PR.
Includes a small extension to the existing `neighborStrategy` so it will be able to pick the neighbor of an array correctly (ignore the nested array index).
=> SALTO-988 more flow references

packages/adapter-api/src/builtins.ts, packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/utils.test.ts
The _parent, _depends_on and _generated_dependencies annotations were not affecting deploy plans
because their types were not set when handling annotations of objects and fields and they were
lists which meant that transformElement with strict=false only called the transform func once with
the list and not for each reference (and it called with with an undefined field)
This fixes the issue for the other core annotations as well and provides the types properly
even though that had a smaller effect because they are not lists, so the transform function
was called with their values
---
- Fixed issue where manually added / generated dependencies where not considered in deploy plans
=> Fix deploy plan ignoring generated dependencies on fields and objects

packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/adapter.discover.test.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts
sometimes these empty strings have real meaning, one example is in sharing rules
where the empty string is used as a marker for "sharedTo" type that requires no parameter
---
- Fix issue where salesforce adapter would not fetch empty string values which prevented deploying SharingRules in some scenarios
---
The effect of this change on my dev account:
=> SALTO-992: Stop omitting empty strings from salesforce values

packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/test/client.test.ts
See the ticket for full details - the simplest example is layouts failing due to `insufficient access rights on cross-reference id`, for some features that prod admins don't have access to by default (or at all).
=> SALTO-991 - Suppress errors for entries with insufficient access on readMetadata

packages/adapter-api/src/values.ts, packages/adapter-utils/src/utils.ts, packages/salesforce-adapter/src/filters/cpq/custom_script.ts, packages/salesforce-adapter/test/filters/cpq/custom_script.test.ts, packages/workspace/src/serializer/elements.ts, packages/workspace/src/workspace/cache.ts, packages/workspace/src/workspace/static_files/common.ts, packages/workspace/src/workspace/static_files/functions.ts, packages/workspace/src/workspace/static_files/source.ts, packages/workspace/test/serializer/serializer.test.ts, packages/workspace/test/workspace/static_files/functions.test.ts, packages/workspace/test/workspace/static_files/source.test.ts
**What's here?**
- Add encoding to StaticFile (with a default 'binary')
- Use the encoding in restore/restoreValues
- Use the new encoding feature for StaticFiles in CustomScript
*** I will do the HubSpot changes in a different PR
=> SALTO-881 - files encoding + resolve/restore using the encoding

packages/salesforce-adapter/src/filters/field_references.ts, packages/salesforce-adapter/src/transformers/reference_mapping.ts, packages/salesforce-adapter/test/filters/field_references.test.ts
Small extension - we had an old rule that only supported one type - switching it to the new format.
(doesn't cover all the choices - some don't use the `actionName` field, and some need some more work to set up for testing)
=> SALTO-988 - Support more action types for FlowActionCall

packages/salesforce-adapter/src/filters/missing_fields.json
salesforce lately added another option ("SalesTeam") for that enum (supported by the API since version 49.0 and above).
=> SALTO-998 Fix validation error on filterScope

packages/salesforce-adapter/package.json, packages/salesforce-adapter/src/transformers/xml_transformer.ts, packages/salesforce-adapter/test/transformers/xml_transformer.test.ts
Some field values may contain xml encoded values like < and > which should be translated
from `&gt;` on fetch and to `&gt;` on deploy (otherwise we fail deploying due to malformed XML)
---
_Release Notes_ (salesforce):
- Fix XML encoded values like `&gt;` or `&qout;` appearing in some instances (EmailTemplates, Reports, etc.)
=> SALTO-1005: Handle XML encoding in salesforce values

packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/utils.test.ts
---
Before this fix if we try to return a reference on an `ObjectType` field it would have changed it to be an object (the class would be removed)
---
- None (this bug had no reproduction in current code flows as far as we know)
=> allow transform function to return reference in object field

packages/salesforce-adapter/src/filters/field_references.ts, packages/salesforce-adapter/src/transformers/reference_mapping.ts, packages/salesforce-adapter/test/filters/field_references.test.ts
Support finding references based on fields higher in the instance. For example, this populates the `field` nested field in the following scenario based on the relevant `object` field (which may be a reference or a string, as before)
```
recordLookups = [
{
...
filters = [
{
field = "NumberofLocations__c"    ->    salesforce.Lead.field.NumberofLocations__c
...
},
{
field = "Primary__c"    ->    salesforce.Lead.field.Primary__c
...
},
]
object = salesforce.Lead
...
},
{
...
filters = [
{
field = "CreatedById"    ->    salesforce.AccountContactRole.field.CreatedById
...
},
]
object = "AccountContactRole"
},
]
```
plus some leftover references using the added strategies.
=> SALTO-988 - Support referencing neighbors of parents / earlier predecessors

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/client/types.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/custom_objects.ts, packages/salesforce-adapter/src/filters/topics_for_objects.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/filters/custom_objects.test.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts
First part of fixing [Salto-758]. Custom settings objects will be uploaded with correct fields, preventing them from causing migration errors.
@omrilit  - maybe you will be interested in reviewing this, as you wrote code in this area?
=> When uploading an object of type "Custom settings" - treat it appropriately, not as normal custom object

packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
Same as https://github.com/salto-io/salto/pull/1463 (linked to the same ticket because it's similar enough) - ran into this randomly in the code, but there are no remaining `trimEnd`s so hopefully we won't see any more of these.
=> SALTO-977 Fix remaining filename suffix truncate

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/filters/missing_fields.json
Changed type of articlePublicSharingCommunities to unknown since it causes validation errors and it's missing in SFDC documentation. The other types were corrected in accordance with the documentation.
=> SALTO-1011 corrected types of fields of KnowledgeCaseSettings

packages/workspace/src/parser/dump.ts, packages/workspace/src/workspace/nacl_files/nacl_file_update.ts, packages/workspace/test/parser/dump.test.ts, packages/workspace/test/workspace/workspace.test.ts
This changes the update nacl logic to work when writing a new object value into a list
This fixes a bug in the scenario where a value in a list was primitive and changed to be complex
With the old code that would not dump the brackets for the new value and it would create a parse
error
---
_Release notes_:
- Fixed bug in nacl serialization that caused some fetch scenarios to create invalid nacl files
=> SALTO-1008: Fix nacl update code to support dumping objects into lists

packages/lowerdash/src/promises/timeout.ts, packages/lowerdash/test/promises/timeout.test.ts
withTimeout wraps a promise with a timeout.
first concrete use case is currently in the SaaS.
=> lowerdash: added promise.timeout

packages/salesforce-adapter/e2e_test/adapter.test.ts, packages/salesforce-adapter/e2e_test/setup.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/custom_objects.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/adapter.crud.test.ts, packages/salesforce-adapter/test/filters/custom_objects.test.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts
Needed in order to avoid conflicts with the location standard object.
Need to finalize the upgrade plan before merging.
=> SALTO-1028 Rename location compound field to geolocation

packages/netsuite-adapter/e2e_test/adapter.test.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/test/transformer.test.ts
I encountered an issue when deploying to Riskified a record that contains the `’` char. It was encoded to `&rsquo;` and the deployment failed. With the new code it's encoded to `&#x2019;` and the deploy passes.
---
Bug fixes:
Netsuite:
- Fix encoding issue which caused the deployment of records with special characters to fail
=> Netsuite: fix xml encoding for special chars

packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/test/workspace/multi_env/multi_env_source.test.ts, packages/workspace/test/workspace/multi_env/routers.test.ts
This changes the behavior of the `default` and `override` fetch modes such that if they fetch a delete of a top level element that is at least partially common, it will be deleted from all environments instead of leaving a partial (and usually invalid) element fragment in other environments.
---
- Fix issue in multi-env workspaces where removing an element that was partially common could break other environments
=> SALTO-1016: Remove elements from all environments when fetch removes elements

packages/salesforce-adapter/e2e_test/adapter.test.ts, packages/salesforce-adapter/e2e_test/setup.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/custom_objects.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/adapter.crud.test.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts
Reduce the special handling of `Geolocation` (see https://github.com/salto-io/salto/pull/1548 and https://github.com/salto-io/salto/pull/1552).
It's easiest to review by checking out the branch and diffing including the last master commit, as this reverts some of the changes from #1548.
=> SALTO-1028 Improve geolocation handling

packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
We removed the use of `parse` in order to keep it compatible with webpack.
Webpack uses a builtin path module that does not includes the `parse` function.
=> parse file path differently

packages/adapter-api/src/elements.ts, packages/workspace/src/merger/index.ts, packages/workspace/test/merger.test.ts
When after fetching element with map fields, when loading the workspace type validation errors are created.
The root cause:
1. Map inner types are saved in the state/cache or parse from the nacl as object types (the placeholder used for any type ref)
2. The function in merger that replaces the placeholder with a reference to the real type ignored map types.
3. As a result, the validator always attempted to validate the map values as objects. Anything else resulted in validation errors.
=> Fixed maptype validation

packages/netsuite-adapter/package.json, yarn.lock
After failing in the saas to install NS and the logs were non indicative:
`Failed to add the netsuite adapter.
[object Object]`
I fixed the unwrapExceptionMessage in SDF
=> Netsuite: bump SDF to fix exceptions toString logic

packages/netsuite-adapter/e2e_test/jest_environment.ts
When validating netsuite credentials it requires the test runner to have java and access to the SDF jar.
In SaaS, we can't use the tested env's SDF jar when running against staging and prod from the test runner, opposed to regular backend e2e tests.
Thus we skip the credentials validation in e2e tests.
Since we don't validate the creds anymore, there will be no reason to have java in the SaaS deploy's job docker (that runs e2e against staging & production) anymore.
=> Netsuite: dont validate credentials when grabbing creds from credsPool

packages/vscode/language-configuration.json
Before this change, trying to comment out a line of nacl in vscode would create invalid syntax
---
- VSCode extension - Fixed comment character definition so commenting out won't create invalid nacls
=> fix comment spec in vscode language definition

packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/cpq/lookup_object.ts, packages/salesforce-adapter/src/filters/field_references.ts, packages/salesforce-adapter/src/transformers/reference_mapping.ts, packages/salesforce-adapter/test/filters/cpq/lookup_object.test.ts, packages/salesforce-adapter/test/filters/field_references.test.ts
Added 2 new "Lookup Objects" references that also include special CPQ mapping between "Label" and ApiName.
**This includes -** 
* Handling the references in the Field's annotations (value set)
* Handling the references in the CustomObject's instances
This does not include all Objects but is supposed to be easy enough to add more (Checking that Product wise that it's right to add them all first).
* I am going to extend this to Fields references (not only Objects) in future PR but this stands alone so putting it our first
=> SALTO-925 (Partial) - CPQ mapping references

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/filters/add_missing_ids.ts, packages/salesforce-adapter/src/filters/replace_instance_field_values.ts, packages/salesforce-adapter/test/filters/replace_instance_field_values.test.ts
This PR will result in mixed-styled nacls: 
* the field names that did not need change will stay the same, e.g: `OPPORTUNITY.LAST_UPDATE`
* the field names the required replacing by this filter will look like their API names: `Opportunity.DeliveryInstallationStatus__c`
Because changing the first kind to their API names is rather complicated (in order to make them actual references) I left it this way, and it could be done in another PR if needed.
=> SALTO-381 replace ForecastingSettings id fields with their names

packages/salesforce-adapter/src/filters/profile_maps.ts
Need two levels in the map because of the api name structure.
(not adding tests because we already have a similar case covered)
=> SALTO-1018 - Convert recordTypeVisibilities to nested map

packages/core/src/core/plan/filter.ts, packages/core/test/common/elements.ts, packages/core/test/core/plan/filter.test.ts, packages/salesforce-adapter/src/change_validator.ts, packages/salesforce-adapter/src/change_validators/profile_map_keys.ts, packages/salesforce-adapter/test/change_validators/profile_map_keys.test.ts, packages/salesforce-adapter/test/filters/profile_maps.test.ts
Verify the keys for all map fields in profiles to make sure they were not modified manually by the user. The error includes the correct path.
=> SALTO-1018 - validate profile map keys

packages/salesforce-adapter/src/transformers/xml_transformer.ts, packages/salesforce-adapter/test/transformers/xml_transformer.test.ts
In the past we used to omit all of the instance's values that are not part of the type.
Since we don't do that anymore we should manually remove the `xmlns` & `xmlns:xsi` xml attributes that are not deployable.
=> Remove xmlns xml attributes since they are not part of the type

packages/salesforce-adapter/README.md, packages/salesforce-adapter/config_doc.md, packages/salesforce-adapter/src/adapter_creator.ts, packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/src/client/jsforce.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/client.test.ts, packages/salesforce-adapter/test/connection.ts
- Moved the salesforce `config_doc.md` to fix a broken link from the main Salto documentation
- Also fixed the example data management configuration that was not in nacl format
---
- Allow configuration of more salesforce client options
=> make salesforce client configurable

packages/dummy-adapter/src/generator.ts, packages/dummy-adapter/test/generator.test.ts, packages/lowerdash/src/strings.ts, packages/lowerdash/test/strings.test.ts, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/custom_object_instances_deploy.ts, packages/salesforce-adapter/src/filters/profile_instance_split.ts, packages/salesforce-adapter/src/filters/profile_maps.ts, packages/salesforce-adapter/test/filters/profile_instance_split.test.ts, packages/workspace/test/workspace/path_index.test.ts
Split profiles into multiple files - each map field in its own nacl, and everything else under `Attributes.nacl`.
---
_Release Notes_ (should be combined with https://github.com/salto-io/salto/pull/1546 if in the same release)
Split salesforce profiles into multiple files for easier navigation.
_Upgrade Instructions_
No action required. In order to get the new file structure, clear the workspace using `salto clean` and fetch again (note that `salto clean` is irreversible).
=> SALTO-1033 - Split profile instances into multiple files

packages/adapter-utils/src/utils.ts
This line is no longer correct (since SALTO-975), and it's polluting the log when there are array values on fields that are not explicitly defined as lists.
Keeping the warning in the other direction for now (non-array value in list field), because I think it's a less likely scenario and may be worth noticing - I can remove it too if that's preferred.
=> Remove outdated list mismatch log

packages/salesforce-adapter/src/filters/cpq/lookup_fields.ts, packages/salesforce-adapter/test/filters/cpq/lookup_fields.test.ts
Ori's deploy flow change caused CPQ Lookup Field's onDeploy & preDeploy to not work because it expected ObjectType both for Addition & Modification Changes but now that's not true.
Changes the filter to handle ObjectType on Addition and Field on Modification & Addition.
=> Fix the lookup fields filter to work to work with the right pre/onDeploy inputs

packages/salesforce-adapter/src/adapter_creator.ts
fix for #1582 , the configuration was omitted by a translation step in the adapter.
changed the type so that the typescript compiler will catch such errors in the future
=> read client config from adapter config

packages/salesforce-adapter/config_doc.md, packages/salesforce-adapter/src/client/jsforce.ts, packages/salesforce-adapter/src/metadata_deploy.ts, packages/salesforce-adapter/test/adapter.crud.test.ts, packages/salesforce-adapter/test/connection.ts
- Improve handling for failing tests in deploy result - include test failures in deploy result
- Unrelated fix to the adapter config example in the documentation
---
- Fixed issue where deployments that failed due to failing apex tests would be considered successful
=> handle errors from apex tests in deploy

packages/lang-server/src/symbols.ts, packages/lang-server/test/symbols.test.ts, packages/vscode/src/adapters.ts, packages/vscode/src/providers.ts
vscode does not display search result for which the query string is not a substring.
Since the new MO for search usage assumes query strings which are full or partial elemIDs we need to display the fullname in the search results.
=> changed symbol search to use fullnames

packages/workspace/src/workspace/nacl_files/nacl_file_update.ts, packages/workspace/test/common/nacl_file_store.ts, packages/workspace/test/workspace/nacl_files/nacl_file_update.test.ts, packages/workspace/test/workspace/workspace.test.ts
- Fix the logic that assigns locations to changes so that new top level elements are added to the end of the file instead of the beginning
---
_Release notes_:
- Fix issue where invalid nacls would be created in fetch when elements are renamed
=> SALTO-1043: add new elements at the end of the file

packages/salesforce-adapter/config_doc.md, packages/salesforce-adapter/src/metadata_deploy.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/adapter.crud.test.ts, packages/salesforce-adapter/test/connection.ts
- Added checkOnly flag to salesforce adapter config
- When running a checkOnly deploy, do not update state file with any changes
---
- Add initial support for salesforce validation deploy using the `checkOnly` flag
=> Support validation deploy

packages/adapter-api/.vscode/launch.json, packages/adapter-utils/.vscode/launch.json, packages/cli/.vscode/launch.json, packages/core/.vscode/extensions.json, packages/core/.vscode/launch.json, packages/dag/.vscode/launch.json, packages/dummy-adapter/.vscode/launch.json, packages/hubspot-adapter/.vscode/launch.json, packages/lang-server/.vscode/launch.json, packages/logging/.vscode/launch.json, packages/netsuite-adapter/.vscode/launch.json, packages/salesforce-adapter/.vscode/extensions.json, packages/salesforce-adapter/.vscode/launch.json, packages/workspace/.vscode/launch.json
It seems like the default configuration for outFiles finds the output .js files in our project
Not really clear why, but the new vscode debugger sets additional breakpoints in these .js files
and that causes it to move the correct breakpoints to other places (again, not clear why)
While I have no idea why making outFiles an empty list instead of the default fixes this,
It seems to work with the new debugger and it seems like the old vscode debugger is not broken
Also in this commit:
- added the package name to the debug jest task name so it will be easier to pick the tests of the
relevant package
- Removed the separate "windows" section from all the configs since it was not used
=> Fix vscode debug config for new versions of vscode

packages/salesforce-adapter/src/filters/custom_objects.ts
`Types.getElemId` calls `naclCase` internally
---
Salesforce bug fix:
- Fixed issue where some elements got an element ID that was more complicated than necessary
=> remove double nacl case for nested instances

packages/cli/src/callbacks.ts
---
Now returns an error message when trying to name the first environment as an empty string.
=> SALTO-839: added validation for env name

packages/cli/src/commands/element.ts, packages/cli/src/formatter.ts, packages/cli/src/prompts.ts, packages/cli/src/workspace/errors.ts, packages/cli/src/workspace/workspace.ts, packages/cli/test/commands/element.test.ts, packages/core/src/api.ts, packages/core/src/core/list.ts, packages/core/test/core/list.test.ts, packages/workspace/index.ts, packages/workspace/src/validator.ts
Adding `salto element list-unresolved` with an optional `--complete-from <env>` argument, for helping users identify and fix unresolved references after a partial `move-to-common` / `clone`. This is checked recursively - if moving a referenced element would result in new unresolved references, those references are listed too.
The output is divided into two parts:
1. `found` - references that were found in the `complete-from` env
2. `missing` - references that could not be found in the `complete-from` env
Sample output: If `env1` has references to `salesforce.Custom__c` and `salesforce.Layout.instance.Custom__c_Custom_Layout@uubs` which exist in `env2`, and also a reference to `salesforce.INVALID` that does not exist anywhere:
```
$ salto element list-unresolved --complete-from env2
✔ …
```
=> SALTO-1022 - Add element list-unresolved command

packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/test/workspace/workspace.test.ts
This change makes elements that have the same name in a different case -
e.g. "salesforce.A" and "salesforce.a" - go to the same file even if they come in the same fetch
Before this change this was broken when working over case insensitive filesystems because
our code would think these are different files and we would override one element with the other
---
- Fix issue where instances with similar names would override each other when working in Windows / Mac
=> SALTO-1053: Make elements with the same name in a different case go to the same file

packages/salesforce-adapter/e2e_test/adapter.test.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts
---
_Release Notes:_
Added support for relationshipName annotation in lookup and master-detail fields.
=> SALTO-1030: added support for relationshipName annotation

packages/salesforce-adapter/src/adapter.ts
Scontrol is a deprecated metadata type in salesforce that has a base64 encoded content field.
It slipped under the radar because it is not possible to create it in new organizations, but in a recent demo we did encounter an instance of it.
moving it to be fetched with `retrieve` like the rest of the metadata with content seemed to work well.
---
- Extract content of SControl metadata to static files
=> fetch SControl content to static file

packages/salesforce-adapter/e2e_test/adapter.test.ts
Fixed a bug where an e2e test failed because the value of relationshipName was already existed (even though we delete the element at the beginning of the test, it is not deleted immediately but moved to the recycle bin and deleted 15 days later)
The solution was to include a random string (based on the current date time) in the relationshipName.
---
_Release Notes:_ None
=> fixed e2e test

packages/core/test/workspace/local/cache.test.ts, packages/workspace/src/serializer/parse_result.ts, packages/workspace/src/workspace/cache.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/test/workspace/cache.test.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
Added check for files' hash in the cache mechanism in addition to the modification time check for cases where a NaCl file is modified, but its content was not changed (common scenario when working with git).
Also moved ParseResults and ParseError to a different file (types.ts) since they were declared multiple times.
---
Added check in the cache for md5 change. For that, I had to add the file's content to the ParseResultsKey so the cache will have access to it and be able to calculate its md5. Also, in order to save the last known md5 in the filesystem, I added it to the ParseResults and modified the serializer to serialize it as well.
Some types were declared multiple times, so I moved them to a common file.
_Release Notes:_
Fixed NaCls cache to use the cache in cases where a NaCl file …
=> SALTO-971: Added check for file's hash in the cache mechanism

packages/adapter-api/src/builtins.ts, packages/cli/e2e_test/salto.test.ts, packages/core/test/core/fetch.test.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/workspace/src/workspace/hidden_values.ts, packages/workspace/test/common/nacl_file_store.ts, packages/workspace/test/workspace/workspace.test.ts
1. Add `hidden_string` builtin type to support hidden annotations.
2. Add a supporting `_hidden_value` annotation (that is used by `hidden_string`), in order to allow separating between marking elements as hidden (with the old `_hidden` annotation), and using type elements to mark their _values_ as hidden without hiding the types (like in this case). This was needed in order to avoid conflicts with hidden types (like when `enableHideTypesInNacls` is set to true)
Ideally we would allow adding annotations directly on the annotation type definitions, but this would introduce some conflicts with the annotations on the underlying types and require bigger changes that we decided not to do at this point.
---
No release notes (internal changes)
=> SALTO-910 - Add hidden annotation support with hidden_string type

packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/filters/custom_objects.test.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts, packages/workspace/src/workspace/hidden_values.ts, packages/workspace/test/common/nacl_file_store.ts, packages/workspace/test/workspace/workspace.test.ts
This also includes the changes from https://github.com/salto-io/salto/pull/1641 and https://github.com/salto-io/salto/pull/1642 , please only review the last commit here.
We now have two separate annotations for hiding elements and values - `_hidden` for hiding elements directly (for exmaple, for completely hiding a type so that it does not appear in the nacls), and `_hidden_value` for hiding values referencing the type that has the annotation (for example, for storing internalId values - we still want the _definition_ of the relevant field / annotation to be visible, but the value itself should only appear in the state).
This PR relies on https://github.com/salto-io/salto/pull/1641 and converts all salesforce fields that used the `_hidden` annotation to use the new `_hidden_value`.
Not …
=> SALTO-910 - Switch internal salesforce fields from _hidden to _hidden_value

packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/utils.test.ts, packages/workspace/src/workspace/hidden_values.ts, packages/workspace/src/workspace/path_index.ts
Based on a discussion on another PR, avoiding the synthetic traversal over `element.elemID.createNestedID('attr')`, which is not a valid elem id (for example, calling `isParentOf` comparing to this id will never be true, as can be seen in the workaround in `hidden_values`). The options discussed were either making this a valid id, or removing the usages - and there was a preference to do the latter.
It turns out that when fields do not have annotations, `transformElement` does not enter them at all - and one place in the code relied on accessing something in each field (and in general this seems like useful functionality given how we use `transform` in the code), so there is now an optional `runOnFields` argument that allows running the transform func directly on the field. We can decide …
=> Avoid traversing invalid ids in transformElement

packages/workspace/src/workspace/hidden_values.ts, packages/workspace/test/workspace/hidden_values.test.ts
Generally mergeWithHidden is supposed to add hidden values to workspace elements but it should not do so if the parent of the hidden value was deleted in the workspace.
However this did not work with hidden annotation values in fields because we only filtered out top level elements that were deleted
---
- Fixed issue that caused restoring deleted fields from state to fail
=> SALTO-1085: omit hidden annotation values in deleted fields

packages/salesforce-adapter/e2e_test/workflow.test.ts, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/test/adapter.discover.test.ts, packages/salesforce-adapter/test/client.test.ts
Updating to a new API version, we get more fields in readMetadata / retrieve and this fixes some issues we had with missing fields in deploy like SALTO-1075
---
- Update salesforce client to api version 50.0
=> SALTO-1032: Bump salesforce client API version to 50.0

packages/dummy-adapter/src/generator.ts
`hidden_string` was added to `BuiltinTypes` as a way to hide annotations, but it is only in use by a specific annotation type in salesforce. It should not be used as a field type (at least not randomly when it can conflict with other hidden annotation values).
=> Avoid using hidden_string as a field type in dummy adapter

packages/adapter-api/src/element_id.ts, packages/cli/src/commands/element.ts, packages/cli/test/commands/element.test.ts, packages/cli/test/mocks.ts, packages/workspace/index.ts, packages/workspace/src/workspace/element_selector.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/element_selector.test.ts, packages/workspace/test/workspace/multi_env/multi_env_source.test.ts
Extract usage of selectors from outside workspace (mostly), so that its methods can be used with element ids.
=> Workspace selector interface

packages/salesforce-adapter/config_doc.md, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/src/metadata_deploy.ts, packages/salesforce-adapter/src/transformers/xml_transformer.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/adapter.crud.test.ts, packages/salesforce-adapter/test/transformers/xml_transformer.test.ts
Fixed bug where deletion of a referenced field (with the necessary changes where it was referenced) would fail because the deployment would attempt to make the deletion first.
This is solved by adding a deleteBeforeUpdate configuration option to the salesforce adapter to configure whether deletion changes will be deployed before or after any other changes (false by default).
---
_Relase Notes:_ 
Added "deleteBeforeUpdate" configuration option to salesforce adapter to configure whether deletions changes will be deployed before or after any other changes (false by default).
=> SALTO-1061: added deleteBeforeUpdate option to configuration

packages/dummy-adapter/src/generator.ts
Instead of #1662. 
After digging a bit more - the random generator was attempting to add random annotations (surprise) on fields with the `hidden_string` type based on its annotation types, which caused some errors and warnings when the randomly-generated values were inconsistent (unlike all other builtins, `hidden_string` "supports" [all core annotation types](https://github.com/salto-io/salto/blob/master/packages/adapter-api/src/builtins.ts#L95) - but they should still be defined consistently). 
Note that additional annotations _can_ be defined on the field, it just needs to be done a little more carefully and this specific part of the generator was not intended for that (for example, a `regex` restriction can be added on string fields, but if it's added here it can generate a warning …
=> Support hidden_string in dummy adapter

packages/hubspot-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/filters/custom_objects.test.ts
Field values are now hidden when `_hidden_value` is set instead of `_hidden`, switching the remaining field defs in hard-coded types.
=> switch remaining hubspot fields to _hidden_value

packages/salesforce-adapter/src/filters/topics_for_objects.ts, packages/salesforce-adapter/test/adapter.crud.test.ts, packages/salesforce-adapter/test/filters/topics_for_objects.test.ts
This fixes a bug in the way the topics for objects filter would compare whether
topics for objects changed for an object type that would cause it to add topics
for existing objects that should not have them
---
- Fixed issue with deploying standard objects that do not support topics
=> SALTO-1092: Avoid adding topics for standard objects that do not support them

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/src/client/jsforce.ts, packages/salesforce-adapter/test/adapter.discover.test.ts, packages/salesforce-adapter/test/connection.ts
Saved the instance URL of salesforce as a hidden element, which will be retrieved at each fetch.
This is done for task SALTO-1042, so I won't need to login to salesforce to retrieve the URL each time I convert an element into a URL.
---
_Release Notes:_ None
=> SALTO-1042: Saved salesforce url in state each fetch

packages/lang-server/src/definitions.ts, packages/lang-server/test/definitions.test.ts
Fixed go to definition for annotation types.
The fix is that if the token is a valid element id, we will always try to go to the element of the token first. Otherwise, we continue to run the usual procedure.
---
Fixed go to definition for annotation types.
=> SAAS-905: fixed go to definition for annotation types

packages/adapter-api/src/adapter.ts, packages/core/src/core/adapters/progress.ts, packages/core/src/core/fetch.ts, packages/core/test/core/fetch.test.ts, packages/dummy-adapter/src/adapter.ts, packages/dummy-adapter/src/generator.ts, packages/dummy-adapter/test/adapter.test.ts
This change adds a callback that will allow reporting progress events from each adapter operation (currently added for `fetch` operation)
Progress is then emitted to the operation progress emitter along with the operation name and adapter name.
Example reporting in dummy adapter was added.
JIRA: SAAS-931, SAAS-997
=> Support adapter progress reporting in fetch

packages/salesforce-adapter/e2e_test/adapter.test.ts, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/client/types.ts, packages/salesforce-adapter/src/filters/utils.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/adapter.crud.test.ts, packages/salesforce-adapter/test/filters/utils.test.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts
- Remove custom code that would set a sharing model and plural label on standard
objects that should not have them set
- Add default sharing model, plural label, deployment status and name field defaults
only when creating a new custom object (instead of setting them by default on all
objects)
---
- Improvements to custom object deploy flow to avoid overriding default configuration like sharingModel
=> SALTO-1092: Avoid overriding custom object default sharing model

packages/salesforce-adapter/src/client/types.ts, packages/salesforce-adapter/src/filters/custom_objects.ts, packages/salesforce-adapter/test/adapter.crud.test.ts, packages/salesforce-adapter/test/filters/custom_objects.test.ts
When deploying a custom object we currently include all fields to handle the case
where sharingModel is controlled by parent (and that requires master-detail fields
to be in the deploy request)
Since this can increase the scope of the deploy significantly, this changes that
behavior such that we will only include master-detail fields and only if the sharing
model is controlled by parent
---
Based on #1685 
_Release Notes_ (same as #1685):
- Improvements to custom object deploy flow to avoid overriding default configuration like sharingModel
=> SALTO-1093: Only include fields in custom object deploy when necessary

packages/lang-server/src/workspace.ts, packages/lang-server/test/workspace.test.ts, packages/vscode/package.json, packages/vscode/src/commands.ts, packages/vscode/src/events.ts, packages/vscode/src/extension.ts
Implemented go to service right-click button in VSCode.
---
VSCode Extension:
Added go to service right-click menu option to go to the service page in the browser of a certain element (Currently only supported for salesforce elements).
=> SALTO-1042: added go to service button in the extension

packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
Currently, in the function updatedNaclFiles, we save the content of the NaCl file in state even though we don't use it. This PR is to remove unnecessary fields from state.
---
=> Changed to not save nacl content on state

packages/lang-server/index.ts, packages/lang-server/src/definitions.ts, packages/lang-server/src/location.ts, packages/lang-server/src/token.ts, packages/lang-server/src/usage.ts, packages/lang-server/test/definitions.test.ts, packages/lang-server/test/token.test.ts, packages/lang-server/test/usage.test.ts, packages/vscode/e2e_test/extension.test.ts, packages/vscode/src/providers.ts, packages/workspace/src/parser/index.ts
Changed to use PeekableLexer to get the token
Moved the token mechanism to the language server
Fixed go to definition for container tokens (e.g., "List<salesforce.Accout>")
---
Language Server (impact on VSCode extension and SAAS editor): Fixed right-click actions for tokens with '@'.
=> Changed to use PeekableLexer for getting token

packages/workspace/package.json
In https://github.com/salto-io/salto/pull/1687, I exported a class from Workspace packages, which contains a type from the moo package. Therefore, the dependency @types/moo needs to move from dev dependencies to dependencies.
---
=> fixed workspace dependencies

packages/salesforce-adapter/src/transformers/xml_transformer.ts, packages/salesforce-adapter/test/transformers/xml_transformer.test.ts
Seems like salesforce does not know how to parse all names like &gt; and &eq;
Specifically &rsquot; was failing in an example deploy
---
_Salesforce Adapter_
- Fix deployment of values that contain special characters (non standard quotes in strings)
=> Remove named escape sequences from salesforce XML transformer

packages/salesforce-adapter/src/types.ts
Seems like the data we fetch for SiteDotCom instances is different on each fetch and it looks like just a binary blob that we can't do too much with.
pending further investigation into properly supporting it, adding it to the default skip list seems like the way to go for now
---
_Salesforce Adapter_
- Added `SiteDotCom` to default skip list
=> Add SiteDotCom to default salesforce skip list

packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/test/workspace/multi_env/routers.test.ts
When a field is defined only in the common env, and a change in its annotation was fetched in isolated mode, the resulting nacl file in the current env was invalid.
=> fixed isolated fetch creates invalid nacls (SALTO-1096)

packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/test/workspace/multi_env/routers.test.ts
This fix fixes a bug that took place when and item was fetch isolated mode and:
1. The diff between the existing item and the fetched item was a list value
2. The list value was defined in common
3. The new list value contained more items then the existing list vaue
This was caused by the the filterByFile function that checked for the each nested id in which file it is defined. For elements in the new value who's index was greater than the existing value - no value was returned.
This only happens in lists since it in not mergeable. The solution is to search for the parent mergeable id (which will always be defined)
=> fixed filterByFile for unmergeable values (SALTO-1104)

packages/lang-server/src/usage.ts
Split provideWorkspaceReferences in order to export its `getWorkspaceReferences` logic (for saas usage)
---
No release notes
=> split provideWorkspaceReferences in order to export its get references logic

packages/lang-server/src/token.ts, packages/lang-server/test/token.test.ts
Fixed a bug in getToken that it would not return a token if the position is the first or second characters of the token.
---
__Release Notes:__ 
VSCode Extension:
Fixed editor operation (Go To Definition, Go To References, etc...) when the position is the first or second character of the selected token.
=> SALTO-1105: fixed getToken for first characters of a token

packages/workspace/src/workspace/hidden_values.ts, packages/workspace/test/workspace/hidden_values.test.ts
Before this change when a field type was changed in the nacl we would get a merge error
This is because the same field would exist in the state file with a different type and
when we tried to merge the definitions (to merge the hidden annotations into the field)
we would get a type conflict
---
(general bug fixes section)
- Fix incorrect merge error when changing a field's type in nacl
=> SALTO-1100: Support changing field type

package.json, packages/cli/package.json, packages/marketo-adapter/package.json, yarn.lock
- Update webpack version because the old version depended on a vulnerable version of `serialize-javascript`
- Update lerna version because the old version depended on a vulnerable version of `dot-prop`
---
None
=> SALTO-1106: Update vulnerable dependencies for webpack and lerna

packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/test/client/client.test.ts
Fixed a bug caused by SDF where during deployment, SDF would raise an error about features that are not enabled in the account although they are not necessary for the deployment. 
---
Fixed a bug where during deployment, an error about features that must be enabled in the account would occur, although those features are not necessary for the deployment (ADVANCEDEXPENSEMANAGEMENT, SUBSCRIPTIONBILLING...).
=> SALTO-1107: fixed SDF dependencies bug

packages/workspace/src/serializer/elements.ts
We currently sort the state file, the logic behind this in the past was so that the state file wouldn't change on identical workspaces. This is irrelevant since we added the fetchTime to the service in state.
Sorting the state causes restore to reorder values in the Nacl file. This causes unnecessary diffs.
---
Core bug fixes:
- Fixed issue where restore would reorder values even when they were not reordered by the user.
=> SALTO-1103 - removed sort of state file

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/settings_type.ts, packages/salesforce-adapter/src/metadata_deploy.ts, packages/salesforce-adapter/src/transformers/xml_transformer.ts, packages/salesforce-adapter/test/filters/convert_types.test.ts, packages/salesforce-adapter/test/mock_elements.ts, packages/salesforce-adapter/test/transformers/xml_transformer.test.ts
1. added annotations to Settings types on fetch: 
dirName = 'settings'
suffix = 'settings'
2. changed the manifest type name to 'Settings' for all settings types
---
bug fixed - changes in Settings instances can now be deployed properly (attempting to deploy raised an error).
=> SALTO-1081 Deploy Settings

packages/netsuite-adapter/scripts/types_generator.py, packages/netsuite-adapter/src/types/enums.ts
Fix validation error upon deploy for portlet_kpireport_reportid although it hasn't changed
=> Netsuite - overcome documentation of enum without values that causes invalid change every deploy

packages/salesforce-adapter/src/adapter.ts
---
fetch NetworkBranding metadata type.
=> SALTO-548: remove NetworkBranding from skip list

packages/cli/src/commands/common/config_override.ts, packages/cli/src/commands/common/env.ts, packages/cli/src/commands/deploy.ts, packages/cli/src/commands/element.ts, packages/cli/src/commands/fetch.ts, packages/cli/src/commands/restore.ts, packages/cli/src/commands/service.ts, packages/cli/src/workspace/workspace.ts, packages/cli/test/commands/commons.test.ts, packages/core/src/local-workspace/workspace.ts, packages/core/src/local-workspace/workspace_config.ts, packages/workspace/src/workspace/config_source.ts, packages/workspace/test/workspace/config_source.test.ts
---
CLI new feature:
- Allow overriding configuration values with `--config` and/or `SALTO_CONFIG_` environment variables in `fetch` and `deploy` commands
=> SALTO-1108: Add config override option to CLI commands

packages/workspace/src/workspace/hidden_values.ts, packages/workspace/test/workspace/hidden_values.test.ts
In a previous PR, I created a built-in instance annotation `_service_url` with a type of `hidden_string`.
In instances, we treat annotations as values, and It seems we don't support `hidden_string` in this case because, for values of instances, we expect the `hidden_value` annotation to be on the field itself and not the type of the field. In this PR, I also check the type of the field.
---
__Release Notes:__ None (Bug was not released)
=> fixed hidden_string type on instance annotations

packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/utils.test.ts, packages/workspace/src/workspace/hidden_values.ts, packages/workspace/test/workspace/hidden_values.test.ts
revert https://github.com/salto-io/salto/pull/1734 to not support hidden string as a field type and handles hidden_string instance annotations by copying the annotation from the type to the field when creating the instance annotations.
---
=> fixed hidden instances annotations

packages/salesforce-adapter/e2e_test/adapter.test.ts
Deploy of any instance of settings failed before [https://github.com/salto-io/salto/pull/1727](url) was merged, but E2E did not catch this bug.
__
Release Notes: None
=> SALTO-1081: add deploy of settings to E2E tests

packages/adapter-api/src/builtins.ts
Changing the annotationTypes of HIDDEN_STRING causes the dummy adapter the return different results.
I guess this is because the dummy adapter uses the HIDDEN_STRING, and changing the annotationTypes in HIDDEN_STRING causes the random in the dummy adapter to return completely different results.
---
=> made dummy adapter to return the expected elements

packages/workspace/src/workspace/element_selector.ts, packages/workspace/test/element_selector.test.ts
and not just char/num/underscore
=> SALTO-1121 : Element Selector wildcard now catches special chars (besides .)

packages/salesforce-adapter/src/elements_url_retreiver/elements_url_retreiver.ts, packages/salesforce-adapter/test/elements_url_retreiver.test.ts
Fixed the elements URL generation to work for Salesforce URLs with 'my' subdomain in them.
---
__Release Note:__
VSCode Extension:
Fixed "Go to service" not working for some users.
=> fixed lightining url for domains without 'my' in them

packages/cli/src/commands/init.ts, packages/cli/src/prompts.ts, packages/cli/test/commands/init.test.ts, packages/core/index.ts, packages/core/src/local-workspace/workspace.ts, packages/core/test/workspace/local/workspace.test.ts
Whenever performing `salto init` command on an already instantiated workspace, the user is prompted to enter an env name before receiving the message 'workspace already exists'.
This PR removes the redundant question and presents the error immediately.
___
__Release Note:__
CLI:
Initiating a workspace twice will prompt an error to the user without asking for env name first.
```
> salto init
? Enter a name for the first environment in the workspace env2
Could not initiate workspace: existing salto workspace
``` 
```
> salto init
Could not initiate workspace: existing salto workspace in /work/git/workspace
```
=> SALTO-745 - Salto init error flow

packages/workspace/src/serializer/elements.ts, packages/workspace/test/serializer/serializer.test.ts, packages/workspace/test/workspace/hidden_values.test.ts
This fixes an issue where container types would not get their inner type's annotations
and annotation types when deserialized.
---
(salesforce bug fix)
- Fix deploy plan incorrectly showing removals of internalId in CPQ CustomScript fields.
=> SALTO-1125: Fix deserialization of container type annotations

packages/cli/src/commands/env.ts, packages/cli/test/commands/env.test.ts, packages/cli/test/mocks.ts, packages/core/index.ts, packages/core/src/local-workspace/workspace.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/workspace.test.ts
Needed for a separate refactor so that commands don't need to be exposed to the workspace path, only the workspace.
basically this logic can be implemented semantically on the workspace rather than rely on folder structure
---
_Release Notes_: None
=> Move empty env logic from core into workspace

packages/workspace/src/parser/internal/native/lexer.ts, packages/workspace/test/parser/parse.test.ts
Invalid tokens in comments should not continue to the next line - that can cause it to treat valid tokens in that line as invalid.
(the breakage was in https://github.com/salto-io/salto/blob/master/packages/workspace/src/parser/internal/native/lexer.ts#L117)
---
Fix handling of comments ending in unexpected characters
=> SALTO-1138 - end invalid parser tokens on newline

packages/core/src/core/fetch.ts
Changed stateElementIDs to be a set to improve the complexity of `processMergeErrors` from O(number of merge errors * number of elements in state) to O(number of merge errors)
---
=> changed stateElementIDs to a set

packages/adapter-api/src/adapter.ts, packages/core/src/api.ts, packages/core/src/core/fetch.ts, packages/core/src/core/plan/index.ts, packages/core/src/core/plan/plan.ts, packages/core/test/core/fetch.test.ts
In order to support partial fetch in adapters, now when an adapter will return that its results are partial by setting `isPartial` to true, the core will ignore deletion changes.
---
__Release Notes__: None
=> SALTO-1131: added support for partial results from adapters

packages/workspace/src/parser/internal/native/consumers/blocks.ts, packages/workspace/src/parser/internal/native/consumers/values.ts, packages/workspace/src/parser/internal/native/lexer.ts, packages/workspace/test/parser/parse.test.ts
Some (invalid) nacls could result in an out-of-memory exception instead of being caught earlier as invalid.
The original scenario being fixed is for [this](https://github.com/salto-io/salto/blob/master/packages/workspace/src/parser/internal/native/consumers/values.ts#L363) error, where if the lexer was already at EOL, `recover` did nothing because the peeked character was one of the stop tokens - resulting in an endless loop. Based on a suggestion from @roironn , instead of fixing just this scenario, the `recover` logic was changed to advance past EOLs (with an option to opt-out).
---
(can be combined with https://github.com/salto-io/salto/pull/1767)
Fix parser out-of-memory on some invalid nacl formats.
=> SALTO-1139 - advance past newlines on lexer recover

packages/cli/src/commands/element.ts, packages/cli/src/prompts.ts, packages/cli/test/commands/element.test.ts, packages/vscode/src/commands.ts
Today's in our vs-code extension and saas, users can right-click on an element and apply `go to service` command on it.
This PR adds similar basic functionality to the CLI under the `element` command.
Usage example:
```bash
salto element open salesforce.Account
```
Add `element open` command to the CLI - which allows opening the service page of an element
=> SALTO-786: add open element command

packages/adapter-utils/test/elements.test.ts, packages/netsuite-adapter/config_doc.md, packages/netsuite-adapter/e2e_test/adapter.ts, packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/adapter_creator.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/config.ts, packages/netsuite-adapter/src/constants.ts, packages/netsuite-adapter/src/filter.ts, packages/netsuite-adapter/src/filters/convert_lists.ts, packages/netsuite-adapter/src/filters/instance_references.ts, packages/netsuite-adapter/src/query.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/adapter_creator.test.ts, packages/netsuite-adapter/test/client/client.test.ts, packages/netsuite-adapter/test/filters/convert_lists.test.ts, packages/netsuite-adapter/test/filters/instance_references.test.ts, packages/netsuite-adapter/test/query.test.ts
Implemented partial fetch from Netsuite according to the query here: https://www.notion.so/saltoio/Netsuite-Partial-Fetch-Query-a451486fd54c46ae9770ea295fd86a5b
This PR does not include the API change of typesToSkip and filePathRegexSkipList. This will be done in a different PR.
This PR currently includes some unrelated changes, such as the implementation of build `buildElementsSourceFromElements` I will remove those changes once https://github.com/salto-io/salto/pull/1755 and https://github.com/salto-io/salto/pull/1763 are merged (Also, the CI won't pass until they are merged).
---
__Release Notes__:
Added "fetchTarget" to choose what elements to fetch from the service.
=> SALTO-1133: added fetchTarget to netsuite

packages/cli/src/index.ts, packages/cli/test/mocks.ts
Small fix for a recent change (moving the cli teardown from [here](https://github.com/salto-io/salto/pull/1765/files#r557455894) to [here](https://github.com/salto-io/salto/pull/1765/files#diff-2fb448d11702324cc59d657d5945d59cd325540eb87b71f2e66a5bc01ada834cR65)) that caused a crash due to the telemetry and logger closing right after starting.
---
None (not released yet)
=> fix early close of telemetry and logger

packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/transformers/reference_mapping.ts
Today when we `fetch` email templates from salesforce, the `letterhead` field was resolved as `string` type, which caused the link between Email Template and Letterhead records to break in multi-env scenarios.
This PR changes the letterhead type from string to a reference.
---
_Additional information_ : 
Before this change: sharing an  EmailTemplate with a letterhead between envs, and deploying it, showed no validation errors, and we got exceptions from saleforce when trying to deploy it. 
After this change: deploying to a new service will yield a reference error
```
➜  salto-workspace salto deploy
Error validating "salesforce.EmailTemplate.instance.unfiled_public_asd@zcd.letterhead": unresolved reference salesforce.Letterhead.instance.WelcomeMail
on …
```
=> SALTO-1059: Resolve EmailTemplate -> Letterhead reference

packages/core/src/api.ts, packages/core/test/api.test.ts
Changed the elementsSource that is passed to each adapter to contain the state elements and not the workspace elements.
---
In https://github.com/salto-io/salto/pull/1763, I passed the adapter an elementsSource with the workspace elements of the adapter. The adapters should not be able to access changes that were not deployed to the service, so the adapter should only get the state elements and not the whole workspace. 
---
_Release Notes_: None
=> fixed to use state elements in the adapters elementsSource

packages/salesforce-adapter/e2e_test/custom_object_instances.test.ts, packages/salesforce-adapter/src/filters/custom_objects.ts, packages/salesforce-adapter/test/filters/custom_objects.test.ts
Fixed instancesRegexSkippedList to work with custom objects.
---
Additional context can be found in https://salto-io.atlassian.net/browse/SALTO-1097.
---
Added support for excluding custom objects using the "instancesRegexSkippedList" configuration option.
=> SALTO-1097: fixed instancesRegexSkippedList to work with custom objects

eslint/adapter-api.rules.js, packages/hubspot-adapter/src/transformers/transformer.ts, packages/netsuite-adapter/.eslintrc.js, packages/salesforce-adapter/.eslintrc.js, packages/salesforce-adapter/src/custom_object_instances_deploy.ts, packages/salesforce-adapter/src/metadata_deploy.ts, packages/workspace/.eslintrc.js, packages/workspace/src/serializer/parse_result.ts
Ran into this when moving some code to adapter-utils.
It looks like the function was called `safeJsonStringify` since the rule was added, must have been a last-minute change on the original PR.
Seems `no-restricted-syntax` doesn't support fix suggestions and I didn't want to create a custom rule for it, so hopefully the correct function name won't change too much.
Also applying to adapters / shared libraries where this wasn't enforced.
---
None
=> Fix JSON.stringify outdated eslint message, apply in all relevant modules

packages/salesforce-adapter/test/adapter.discover.test.ts, packages/salesforce-adapter/test/client.test.ts, packages/salesforce-adapter/test/connection.ts
- Fix mock functions in client test to return appropriate value types
- Remove type casts that made it possible to return incorrect value types from mocks
- Change mock implementation to work around jest bug which caused the functions to return
their default value (immediately resolved promise) instead of the return value specified in the tests
---
Jest has a bug (solved in newer versions) where a mock function that has `mockReturnValue` would return that value even if we later set a `mockResolvedValueOnce` on it.
Working around that issue by fixing the test to use `mockReturnValueOnce` (and returning the correct type of answer)
---
_None_
=> Fix salesforce client throttling tests

packages/netsuite-adapter/scripts/types_generator.py, packages/netsuite-adapter/src/filters/convert_lists.ts, packages/netsuite-adapter/src/types/custom_types/bundleinstallationscript.ts, packages/netsuite-adapter/src/types/custom_types/clientscript.ts, packages/netsuite-adapter/src/types/custom_types/customrecordactionscript.ts, packages/netsuite-adapter/src/types/custom_types/mapreducescript.ts, packages/netsuite-adapter/src/types/custom_types/massupdatescript.ts, packages/netsuite-adapter/src/types/custom_types/portlet.ts, packages/netsuite-adapter/src/types/custom_types/restlet.ts, packages/netsuite-adapter/src/types/custom_types/scheduledscript.ts, packages/netsuite-adapter/src/types/custom_types/sdfinstallationscript.ts, packages/netsuite-adapter/src/types/custom_types/suitelet.ts, packages/netsuite-adapter/src/types/custom_types/usereventscript.ts, packages/netsuite-adapter/src/types/custom_types/workflowactionscript.ts
Netsuite Adapter: fetch script deployments in a consistent order
=> Netsuite: return script deployments in a consistent order

packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/config.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/client/client.test.ts, packages/netsuite-adapter/test/config.test.ts
Until now we used to split the type's objects into chunks and in case a certain chunk has failed we would not return any instance if that type and add it to the skipList using the config suggestions mechanism.
This PR contains a retry mechanism on top of the chunks while dividing the chunk's size by 2 in case of failure in until the chunk has size of 1. In case we fail also when having chunk of size 1, we will fail the fetch operation.
Since we now have a safe fallback, I also increased the default chunk size from 30 to 50 assuming it'll accelerate the fetch.
---
Netsuite:
1. Do not add types that failed to fetch to typesToSkip automatically, but retry fetching them and fail the fetch operation in case it fails also then.
2. Increase default …
=> SALTO-1124 SALTO-1127 - Netsuite: Add import objects retries, don't add types to skiplist, increase default objects chunk size

packages/dummy-adapter/src/generator.ts, packages/dummy-adapter/test/generator.test.ts, packages/workspace/src/workspace/nacl_files/nacl_file_update.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/test/workspace/nacl_files/nacl_file_update.test.ts
(updated after discussing with @roironn and @ori-moisis )
We used to have a default filename for elements that do not specify a path (we cannot expect all elements to specify one). It seems this was changed a while ago (in https://github.com/salto-io/salto/pull/486). In some multienv scenarios, this can result in invalid write attempts that can fail the fetch operation completely (details are in the ticket) - but even in single-env, it seems the current behavior of not persisting these elements anywhere is not the intended one. 
The agreed solution is to bring back the default filename (one per env).
---
None (not happening in existing adapters)
=> SALTO-1154 - Use default per-env filename for elements with no path

packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/types.test.ts
Added regex to skip packages' records and types to the default salesforce configuration.
Custom fields to existing objects will still be fetched.
The regex that will be added to the configuration is `^.+\\.(?!standard_)[^_]+__(?!(c|r|ka|kav|Feed|ViewStat|VoteStat|DataCategorySelection|x|xo|mdt|Share|Tag|History|pc|pr|hd|hqr|hst|b|latitude__s|longitude__s|e|p|ChangeEvent|chn)([^a-zA-Z\\d_]+|$)).+$`
---
Added regex to skip external packages' records and types to the default salesforce configuration.
=> SALTO-1136: added regex to skip packages' records and types to the default salesforce configuration

packages/salesforce-adapter/config_doc.md, packages/salesforce-adapter/src/types.ts
Add CustomObjectTranslation to the default skip list
---
---
Salesforce Adapter: _Add CustomObjectTranslation to the default skip list_
_
=> SALTO-1159-add CustomObjectTranslation to the skipped list

packages/workspace/src/workspace/hidden_values.ts, packages/workspace/test/common/state.ts, packages/workspace/test/workspace/hidden_values.test.ts
Before this, a change made directly on an instance annotation value would not be removed from nacl
---
Note this scenario is currently impossible because of a bug that prevents us from creating changes on instance annotation values, see the ticket and PR #1805 for more details
---
_None_ (because the bug this solves is currently impossible)
=> SALTO-1158: Fix support for hidden annotation value changes on instances

packages/adapter-api/src/elements.ts, packages/adapter-api/test/elements.test.ts, packages/adapter-utils/src/compare.ts, packages/adapter-utils/test/compare.test.ts
- Consider instance annotation values when comparing instances
- Remove unused `getValuesThatNotInPrevOrDifferent` function from `InstanceElement`
---
This is currently only relevant in cases where the instance annotation is written to the nacl.
Only reasonable use case were this would be problematic is with _generated_dependecies that would not be updated
Based on #1807  - review the other PR first
---
Salesforce adapter
- Fixed issue where _generated_dependencies would not be updated to reflect the correct dependencies of ApexClasses and Flows when they change
=> SALTO-1158: Compare instance annotation values

packages/netsuite-adapter/config_doc.md, packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/adapter_creator.ts, packages/netsuite-adapter/src/config.ts, packages/netsuite-adapter/src/constants.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/adapter_creator.test.ts, packages/netsuite-adapter/test/config.test.ts
This PR converts the format of the old skip list (i.e., `typesToSkip` and `filePathRegexSkipList`) to the same format as the `fetchTarget` in Netsuite. The new format is described in https://www.notion.so/saltoio/Netsuite-Partial-Fetch-Query-a451486fd54c46ae9770ea295fd86a5b
---
The configuration options `typesToSkip` and `filePathRegexSkipList` were replaced with a new option `skipList` that also allows skipping specific items of a type. On the next fetch, Salto will automatically upgrade the old options to the new option (with the user approval).
=> SALTO-1133: converted the old format of the skip list to the new format in Netsuite

packages/netsuite-adapter/src/config.ts
After seeing some timeout failures due to too big chunk (50) after 20 minutes I reduced the the chunk size to 40 to reduce the probability of failure. The longest chunk that I saw which ended successfully took around 5 minutes, thus I reduced the timeout to 8 minutes to avoid waiting up to 20 minutes in case of failure. This way if a failure will occur we'll retry with a smaller chunk faster.
---
Netsuite:
1. Reduce default fetchTypeTimeoutInMinutes to 8.
2. Increase default maxItemsInImportObjectsRequest to 40.
=> Netsuite: modify default import types timeout & chunk size

docs/user_guide.md
---
Preview:
The following flags are available for all commands:	The following flags are available for all commands:
* `--version -V` :  Show version number	* `--version -V` :  Show version number
* `--help, -h` :    Show help	* `--help, -h` :    Show help
* `--verbose, -v` : Output extra logs 	* `--verbose, -v` : Output extra logs 
* `--config, -C` :  Override adapter configuration value. format: `<service>.<path>=<value>`
Can also be done by setting an environment variable named `SALTO_<service>_<path>=<value>`
---
None
=> Update CLI documentation to include config override option

packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/client/client.test.ts, packages/netsuite-adapter/test/config.test.ts
After seeing that fetch might take forever due to the 'add to skipList' approach when encountering a locked file (when having a large file cabinet with a lot of locked files), I decided to throw an indicative error when encountering a locked file.
Having said that, I left the config suggestion when encountering a top level folder that doesn't exist. We saw that case several months ago in a customer's account and there is no reason to throw error in that case.
Netsuite Adapter: Do not suggest to add locked files to the files skipList but throw an error, in order to prevent potential performance issue.
=> Throw error when failing to import a certain file from file cabinet

packages/adapter-api/src/elements.ts, packages/adapter-api/test/elements.test.ts
`InstanceElement.isEqual` did not compare the instance elem ids. This fixes it.
---
None
=> Fix instance comparison

packages/cli/src/formatter.ts, packages/cli/test/formatter.test.ts, packages/cli/test/mocks.ts
Fixed a bug where a change of a field was not counted as an impact on a type when printing the number of impacted types in instances on deploy.
---
CLI:
Fixed a bug where a change of a field would not be counted in the impacts report printed to the user on deploy.
=> SALTO-1176: fixed bug in number of printed impacts

packages/cli/src/workspace/workspace.ts, packages/core/src/core/restore.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/path_index.ts, packages/workspace/src/workspace/state/in_mem.ts, packages/workspace/src/workspace/state/state.ts, packages/workspace/test/workspace/path_index.test.ts, packages/workspace/test/workspace/state.test.ts
_Optimized path index creation_
---
In the previous implementation, path index was created by performing a DFS on all of the elements and keeping all of the path hints. This caused a few problems:
1. DFS took too long on large data sets.
2. The resulting data structure was to large, resulting in an OOM error.
3. The number of key-value pair in the resulting data structure was too large (usually, about two order of magnitudes from the number of elements) which caused the flush of the path index to be very long.
In order to improve we:
1. Keep only uniq prefixes in the path index, when getting a key - get the closes id prefix defined.
2. Calculate the index by performing a parallel DFS on all of the element fragments, and terminating the DFS if there is only one path defined. (remove the …
=> changed path index creation to avoid dfs when possible

packages/salesforce-adapter/src/change_validators/custom_field_type.ts
The validator implicitly assumed all fields have api names which is not correct
in the change validator phase (before addDefaults).
---
`toCustomField` assumes the field is convertible to a salesforce custom field (which must include a fullName).
this is not the case in the change validator since it runs before we `addDefaults` to fields, so we can have fields without an api name here.
since `toCustomField` was only used to get the type name, using the same logic to get the field type name should be sufficient
---
(salesforce adapter)
- Fix error deploying new fields without specifying apiName and label explicitly
=> SALTO-1175: Fix custom field type validator failure on new fields

packages/netsuite-adapter/package.json, yarn.lock
In case an exception was thrown when creating the Jar's folder, e.g. due to permissions issue, the exception was thrown as an object and not unwrapped as expected.
See https://github.com/salto-io/netsuite-suitecloud-sdk/pull/24 for more info.
None
=> SAAS-1310: Bump SDF to 1.1.2-salto-4 to unwrap exception correctly when installing NS adapter

packages/cli/src/callbacks.ts, packages/cli/test/workspace/workspace.test.ts
Changed any y/n question in Salto CLI to accept only 'y' or 'n'.
`inquirer` confirm type does not support this, so I changed it to input type and added validation.
---
CLI:
y/n questions in the CLI will only accept 'y' or 'n' answers.
=> SALTO-1128: changed to accept only y or n answers

packages/adapter-api/src/elements.ts, packages/adapter-api/test/elements.test.ts, packages/adapter-utils/src/compare.ts, packages/adapter-utils/test/compare.test.ts
Reverting the fix that makes instance compare take into account annotations because it makes the issue in SALTO-1185 more likely and we don't agree on a solution for it
Reverts #1823 and #1805
---
- Remove the note about fixing _generated_dependecies not being updated since this reverts the fix for that issue
=> SALTO-1185, SALTO-1158: Revert/instance compare

packages/adapter-api/src/elements.ts, packages/adapter-api/test/elements.test.ts, packages/adapter-utils/src/compare.ts, packages/adapter-utils/test/compare.test.ts
This reverts commit 6bd84123dc7eca52ce4a4b86a326d659a7e0f808
Re-applying changes from #1823 and #1805
---
* Fixed issue where _generated_dependencies would not be updated to reflect the correct dependencies of ApexClasses and Flows when they change
=> SALTO-1158: make instance compare check annotations and ID

packages/salesforce-adapter/src/filters/extra_dependencies.ts, packages/salesforce-adapter/test/filters/extra_dependencies.test.ts
To avoid differences between environments in multienv, we sort the generated dependencies alphabetically by the elem id. This is a system-generated annotation that is not supposed to be edited by users.
Note that this may appear in diffs in existing workspaces.
---
Salesforce adapter: Sort generated dependencies alphabetically to reduce differences in multienv.
=> SALTO-1185 - Sort Salesforce generated dependencies by elem id

packages/core/src/core/plan/filter.ts, packages/core/src/core/plan/group.ts, packages/core/src/core/restore.ts, packages/core/src/local-workspace/state.ts, packages/workspace/src/parser/dump.ts, packages/workspace/src/serializer/elements.ts, packages/workspace/src/workspace/hidden_values.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/src/workspace/nacl_files/nacl_file_update.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/workspace.ts
_Changed promise all calls to `awu` to reduce memory foot print_
---
_Promise all calls can create memory usage bottlenecks without effecting speed (if no significant IO is performed in the promise). One such `Promise.all` invocation created a bottle neck in handleHiddenChanges which causes a crush in a 110K elements fetch._
---
NA
=> changed promise all calls to awu to redcue mem foot print

packages/salesforce-adapter/src/deprecated_config.ts, packages/salesforce-adapter/test/deprecated_config.test.ts
Fixed a bug in the conversion between the old salesforce configuration to the new where an undefined was written inside `data` in an attribute that was not filled in the old configuration
---
None
=> fixed salesforce deprecated config convertion

packages/adapter-api/src/values.ts, packages/core/src/core/plan/plan.ts, packages/lowerdash/src/collections/asynciterable.ts, packages/lowerdash/test/collections/asynciterable.test.ts, packages/workspace/src/expressions.ts
_Change get plan to resolve only nodes that were added to the graph_
---
_Currently, getPlan resolves all of the elements before comparing them in order to decide which element should be added to the diff graph. This is very wasteful in both run time, and memory usage. The only "resolve" action that needed to be taken in order to compare two elements is resolving references to non element objects. The isEqual method was modified in order to reflect that._
_The deploy command still needs resolved elements though (Since we had yet to modify the deploy command to accept) so a step that resolves nodes that were added to the graph was created. This step will be removed once the deploy API will be modified._
---
_NA_
=> changed get plan to resolve only added nodes

packages/workspace/src/workspace/workspace.ts, packages/workspace/test/common/nacl_file_store.ts, packages/workspace/test/workspace/workspace.test.ts
Added log with elements ids that a validation error was thrown for.
The new logs in a workspace with a lot of errors:
The last one is `UnresolvedReferenceValidationError`
---
None
=> SALTO-1189: added log for invalid elements ids

packages/cli/src/callbacks.ts, packages/cli/src/commands/element.ts, packages/cli/src/prompts.ts, packages/cli/test/commands/element.test.ts
Provided the elements to be moved/cloned in the message to the user in the operations: move-to-envs move-to-common and clone.
Images of the new messages can be found in https://salto-io.atlassian.net/browse/SALTO-1129.
---
CLI:
move-to-env/common and clone will now print the moved/clone elements and ask for confirmation from the user.
=> SALTO-1129: improved move-to-envs/move-to-common/clone messages

packages/core/src/core/diff.ts, packages/core/test/core/diff.test.ts
https://salto-io.atlassian.net/browse/SALTO-1186
Core: Include field's annotations matches in restore & fetch commands when using field element ID as the element selector.
=> SALTO-1186: createDiffChanges correctly for field annotations

packages/adapter-utils/package.json, packages/adapter-utils/scripts/client/mock_replies.py, packages/adapter-utils/src/client/http_connection.ts, packages/adapter-utils/src/client/pagination.ts, packages/adapter-utils/src/elements/ducktype/index.ts, packages/adapter-utils/src/elements/ducktype/instance_elements.ts, packages/adapter-utils/src/elements/ducktype/transformer.ts, packages/adapter-utils/test/client/http_client.test.ts, packages/adapter-utils/test/client/http_connection.test.ts, packages/adapter-utils/test/elements/ducktype/transformer.test.ts, packages/adapter-utils/test/elements/ducktype/type_elements.test.ts, yarn.lock
Leftovers from https://github.com/salto-io/salto/pull/1811 and helper utils for Workato.
Extracted from https://github.com/salto-io/salto/pull/1812.
* Avoid shortening elem ids
* Switched to a better mocking library for Axios
* Adjusted the debug logs and added a script to convert them into initial mocks (which can then be modified manually). See the Workato PR for a sample usage ([here](https://github.com/salto-io/salto/pull/1812/files#diff-fec06cb19d512b6003757e93f2477a8cc53b5e509c299bdf6b50ba76c6f510ccR47)).
---
None
=> SALTO-1147, SALTO-1148 - Switch axios mock library, avoid shortening elem id, add helper script for mocking http responses

packages/logging/jest.config.js, packages/logging/src/internal/log-tags.ts, packages/logging/src/internal/pino.ts, packages/logging/test/internal/log-tags.test.ts, packages/logging/test/internal/pino_logger.test.ts
This PR adds the functionality of logging error stack-trace and message for errors given as logTagValues.
---
This should not affect the CLI users.
=> SAAS-1477: Support logging errors specific information in log tags

packages/cli/src/index.ts
stopping telemetry and the logger in a Promise.all creates a race condition
because telemetry tries to emit a log when it stops
---
CLI:
- Fixed possible crash at the end of CLI commands when telemetry is enabled
=> Fix race condition in CLI teardown

packages/salesforce-adapter/src/filters/custom_object_split.ts, packages/salesforce-adapter/src/filters/custom_objects.ts, packages/salesforce-adapter/src/filters/layouts.ts
As preparation for partial fetch (where we can get elements that do not have a path)
Changing the implementation of places that set element paths to not rely on custom object
paths but instead apply the same logic to determine the path of the custom object as if
it was new
---
Tested (manually) by cleaning a workspace, fetching again, and checking that none of the files moved.
---
None
=> Remove reliance on custom object path to determine other element paths

packages/adapter-api/src/elements.ts, packages/adapter-api/test/elements.test.ts
Without this, cloned objects default to `unsorted.nacl`
---
None
=> Clone path when cloning object types

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/hardcoded_lists.json, packages/salesforce-adapter/src/filters/territory.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/filters/territory.test.ts
Territory2 and Territory2Model support custom fields by exposing a custom object
with the same name as the metadata type.
This changes the salto ID of the metadata types so it does not conflict with
the custom objects so that we are able to fetch the custom objects as well and
we remove the custom fields definitions on the metadata instances to avoid duplication
---
- Added support for custom fields on Territory2 and Territory2Model types
=> SALTO-1191: Add support for Territory2 custom fields

packages/salesforce-adapter/src/transformers/salesforce_types.ts
Removing a subtype of OrgPreferenceSettings that was removed in a previous commit
---
Related to the removal of OrgPreferenceSettings in #1854 ([here](https://github.com/salto-io/salto/pull/1854/files#diff-f9e535c160d8b2ec686efb2ac45ae7129677f9fd56275c0b477e8af7dfa412b7L2008))
---
None
=> Remove unused manual type - OrganizationSettingsDetail

packages/salesforce-adapter/src/filters/convert_maps.ts, packages/salesforce-adapter/src/filters/profile_paths.ts, packages/salesforce-adapter/test/filters/profile_paths.test.ts
---
- Removed redundant call to SF API when not fetching profiles
=> Avoid query on profile info when not fetching profiles

packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
increase PARSE_CONCURRENCY and DUMP_CONCURRENCY from 20 to 100
---
a similar change to what @noamhammer done in PR: https://github.com/salto-io/salto/pull/1845
---
improve bulk element clone and move performance
=> increase files read and dump concurrency

packages/salesforce-adapter/config_doc.md, packages/salesforce-adapter/src/config_change.ts, packages/salesforce-adapter/src/deprecated_config.ts, packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts, packages/salesforce-adapter/src/filters/custom_settings_filter.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/config_change.test.ts, packages/salesforce-adapter/test/deprecated_config.test.ts, packages/salesforce-adapter/test/filters/custom_settings_filter.test.ts
This PR is for not fetching all the custom settings instances by default in new workspaces.
I added a `fetchAllCustomSettings` option that, when undefined, is treated as true, and when creating a new workspace, it is created with a false value.
---
Added `fetchAllCustomSettings` option to pick whether to bring all the custom settings instances. In new workspaces, it will be created with a default of `false`.
=> SALTO-1202: added 'fetchAllCustomSettings' option

packages/adapter-api/src/change.ts, packages/adapter-utils/src/utils.ts, packages/cli/src/command_builder.ts, packages/core/src/local-workspace/workspace.ts, packages/core/test/workspace/local/workspace.test.ts, packages/dummy-adapter/src/generator.ts, packages/lang-server/src/workspace.ts, packages/lang-server/test/workspace.ts, packages/workspace/package.json, packages/workspace/src/merger/index.ts, packages/workspace/src/merger/internal/primitives.ts, packages/workspace/src/serializer/elements.ts, packages/workspace/src/workspace/elements_source.ts, packages/workspace/src/workspace/hidden_values.ts, packages/workspace/src/workspace/nacl_files/elements_cache.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/remote_map.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/common/nacl_file_source.ts, packages/workspace/test/merger.test.ts, packages/workspace/test/serializer/serializer.test.ts, packages/workspace/test/workspace/elements_source.test.ts, packages/workspace/test/workspace/hidden_values.test.ts, packages/workspace/test/workspace/multi_env/multi_env_source.test.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.state.test.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts, packages/workspace/test/workspace/remote_map.test.ts, packages/workspace/test/workspace/workspace.test.ts, yarn.lock
_Chaned workspace and multi env sources to avoid reading the entire sub sources and use the changes returned by the sub sources for init instead_
---
---
_NA_
=> Iterative merged update

packages/netsuite-adapter/src/query.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/query.test.ts
Before this PR, adding a type to the skip list would cause the entire type to be skipped regardless of the patterns of the type.
---
Fixed bug in the skipList where in some cases, it would incorrectly skip instances.
=> SALTO-1207: fixed netsuite skipList

packages/workspace/src/workspace/element_selector.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/element_selector.test.ts
selectElementsByIdsTraversal will now have an optional parameter that makes sure that specified element ids exist.
---
Solving:
https://salto-io.atlassian.net/browse/SALTO-1203
---
None
=> Add option of validating existence of element id [SALTO-1203]

packages/netsuite-adapter/src/changes_detector/changes_detector.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/query.ts, packages/netsuite-adapter/test/client/client.test.ts, packages/netsuite-adapter/test/query.test.ts
Avoid listing files and instances if there is not going to be anything that matches them.
---
Optimization to `fetchTarget` when no files/instances are matched to the value passed in `fetchTarget`.
=> Avoids listing files and instances if not necessary

packages/adapter-components/src/change_validators.ts, packages/adapter-components/test/change_validators.test.ts, packages/workato-adapter/src/change_validator.ts
Make the simple-adapter deploy change validator reusable for all simple adapters.
---
None
=> move deploy change validator to adapter-components

packages/adapter-utils/src/element_source.ts, packages/adapter-utils/test/element_source.test.ts
---
This will be needed for the salesforce partial fetch feature where we want some of the elements to come from the current fetch but we also want the rest of the workspace elements to "exist" through the read only elements source that core provides
---
None
=> SALTO-1209: Add fallback element source for readonly element source util

packages/lowerdash/src/index.ts, packages/lowerdash/src/multi_index.ts, packages/lowerdash/src/types.ts, packages/lowerdash/test/multi_index.test.ts
- Added multi index implementation for building multiple indices from a single
iteration over an async iterable
- Added short type definitions for TypeGuard and Predicate
- Sorted package index file
---
None
=> Lowerdash - multi index builder

packages/netsuite-adapter/config_doc.md, packages/netsuite-adapter/src/config.ts
After noticing that when we reach the timeout we waste a precious time and the retry on smaller chunks makes it work faster, I decided to reduce the `fetchTypeTimeoutInMinutes` default to 4 minutes as the longest chunk fetch that I saw that eventually succeeded to fetch, took around 3 minutes.
---
NetSuite Adapter: reduce the default fetchTypeTimeoutInMinutes config value to 4 to avoid waiting too long for a response from SDF
=> Netsuite: reduce the default fetch timeout per type's chunk

packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/src/client/types.ts, packages/netsuite-adapter/src/client/utils.ts, packages/netsuite-adapter/src/config.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/client/sdf_client.test.ts, packages/netsuite-adapter/test/config.test.ts, packages/netsuite-adapter/test/utils.ts
When we run SDF importObjects command we have few types of failures we encountered.
1. An error is thrown
2. In the response it's written that a certain object has failed to be imported due to "_You cannot download the XML file for this object because it is locked_."
3. In the response it's written that a certain object has failed to be imported due to "_An unexpected error has occurred_"
When #.1 happens we fail the fetch.
When #.2 happens we ignore it and it appears in the logs
This PR handles #.3 by adding the failing instances to the types skipList.
We decided to go with this approach as these failures are almost consistent. We saw in few customers' accounts that the same 10-70 instances fail to be imported due to that error message.
We also saw once in a while that a certain instance …
=> Netsuite: Add instances that failed to import due to an unexpected SDF error to skipList

packages/workato-adapter/src/config.ts, packages/workato-adapter/test/adapter.test.ts
The extended schemas can be very long, and at least for now we get the data we need from other fields.
Note that the fields are only omitted in the default configuration - they can be added back if needed without requiring a new release.
=> Omit extended schemas from workato elements (applies to recipe code)

packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/utils.test.ts, packages/salesforce-adapter/src/filters/extra_dependencies.ts
The `_generated_depenedencies` annotation's values should be sorted and unique - adding a util function for that so it doesn't need be be re-implemented every time (split from https://github.com/salto-io/salto/pull/1900).
---
None
=> Add util function for extending generated dependencies

packages/adapter-api/src/adapter.ts, packages/adapter-components/src/config/shared.ts, packages/adapter-components/src/filter_utils.ts, packages/adapter-components/test/filter_utils.test.ts, packages/core/src/api.ts, packages/core/src/core/fetch.ts, packages/core/test/core/fetch.test.ts
Allow adapters to make adjustments based on fetch results from other adapters.
This currently needs to run within `fetch` before we calculate the changes, because otherwise we may get unwanted changes because core cannot compare reference expressions and plain values.
Also added support for the `postFetch` filter operation in `adapter-components` (the first usage will be in workato which is using it).
---
Add post-fetch step to allow adapters to define references to elements from other adapters
=> SALTO-1205 - Add postFetch step

packages/netsuite-adapter/test/client/sdf_client.test.ts
Doesn't seem like we need the mock to be virtual anymore since suitecloud is a normal dependency
Changing because the virtual mock didn't always work and it would causes unit tests to fail
---
@omrilit - I am not sure why this was virtual or what the virtual thing really does, but the netsuite unit tests would fail from time to time and it seemed like it was because the mock didn't work correctly, I assume this was the reason because it is the only place where we use a different type of mock....
---
None
=> Change suitetcloud mock to be non-virtual

packages/core/src/core/fetch.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/workato-adapter/config_doc.md, packages/workato-adapter/src/adapter.ts, packages/workato-adapter/src/adapter_creator.ts, packages/workato-adapter/src/config.ts, packages/workato-adapter/src/constants.ts, packages/workato-adapter/src/filters/cross_service/element_indexes.ts, packages/workato-adapter/src/filters/cross_service/recipe_block_types.ts, packages/workato-adapter/src/filters/cross_service/recipe_references.ts, packages/workato-adapter/test/adapter.test.ts, packages/workato-adapter/test/adapter_creator.test.ts, packages/workato-adapter/test/filters/recipe_references.test.ts
Find references to salesforce/netsuite that are contained inside workato recipes.
Each recipe is linked to at most one salesforce and one netsuite account (through the standard connectors), and we only look at recipes with the configured connections (the config is not multienv-friendly yet - see SALTO-1213).
For now, we add _all_ references we find under the `_generated_dependencies` annotation, and also replace in-place where possible. This will be improved later.
This includes some but not all references - will extend in subsequent PRs.
---
Add cross-service references from Workato recipes to Salesforce and Nestuite.
=> SALTO-1205 - Workato cross-service references

packages/workspace/src/workspace/workspace.ts
_Fix merge error on fetch with only hidden changes_
---
_The element source used to complete changes which only present in the state only changes was wrong (used the merge source instead of the nacl file source) which created the duplications._
=> fixed merge errors when update contain only hidden changes

packages/adapter-api/src/builtins.ts
With `_generated_dependencies` defined as a string, we sometimes get validation warnings (`Error validating "workato.recipe__code.instance.<some_id>._generated_dependencies.1": Invalid value type for string`). Generated dependencies can point to any element / element path, so I think there's no reason to define them specifically as strings.
---
None (the new references that get these warnings were not released yet)
=> Turn generated dependencies from string to unknown to avoid validation warnings on cross-service references

packages/cli/test/mocks.ts, packages/core/src/api.ts, packages/core/src/core/adapters/adapters.ts, packages/core/src/local-workspace/workspace_config.ts, packages/core/test/common/workspace.ts, packages/core/test/core/adapters/adapters.test.ts, packages/workspace/src/workspace/config_source.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/src/workspace/workspace_config_source.ts, packages/workspace/test/workspace/config_source.test.ts
Before this change config overrides would not be applied to adapter configuration
if the configuration file did not exist.
---
CLI:
- Fix bug where config overrides (-C) for adapter configuration would not work when adapter config file did not exist
=> Fix config overrides for default adapter config

packages/netsuite-adapter/src/adapter.ts
I changed the log of "Failed to get sysInfo" from a warning to debug because it always happens if the SuiteApp is not configured, and I think it might be confusing. If there was a real error with getting the sysInfo, another log will be written.
---
None
=> SALTO-1198: changed log level

packages/cli/src/commands/deploy.ts, packages/cli/src/commands/fetch.ts, packages/cli/src/commands/restore.ts, packages/cli/src/formatter.ts, packages/cli/src/outputer.ts, packages/cli/src/prompts.ts, packages/cli/src/workspace/workspace.ts, packages/cli/test/commands/deploy.test.ts, packages/cli/test/commands/fetch.test.ts, packages/cli/test/commands/restore.test.ts, packages/cli/test/workspace/workspace.test.ts, packages/core/src/core/deploy.ts, packages/core/src/core/fetch.ts, packages/workspace/src/workspace/workspace.ts
Changed the CLI message in fetch and restore the show the number of syntactic changes in the NaCl files instead of the number of semantic changes.
---
CLI:
Improvement to the CLI messages in fetch and restore.
=> SALTO-1090: changes to notify about the number syntactic instead of the semantic changes

packages/netsuite-adapter/src/changes_detector/changes_detector.ts, packages/netsuite-adapter/src/changes_detector/changes_detectors/custom_record_type.ts, packages/netsuite-adapter/src/changes_detector/changes_detectors/custom_type.ts, packages/netsuite-adapter/src/changes_detector/changes_detectors/role.ts, packages/netsuite-adapter/src/changes_detector/changes_detectors/savedsearch.ts, packages/netsuite-adapter/src/changes_detector/changes_detectors/script.ts, packages/netsuite-adapter/src/changes_detector/changes_detectors/workflow.ts, packages/netsuite-adapter/test/changes_detector/changes_detector.test.ts, packages/netsuite-adapter/test/changes_detector/custom_record_type.test.ts, packages/netsuite-adapter/test/changes_detector/role.test.ts, packages/netsuite-adapter/test/changes_detector/savedsearch.test.ts, packages/netsuite-adapter/test/changes_detector/script.test.ts, packages/netsuite-adapter/test/changes_detector/workflow.test.ts
Fixed the following bugs:
- isTypeMatch should also check if there are types changes
- customsegments (which are returned from the customrecordtype query) are returned without the `customrecord_` prefix
- role and savedsearch has missing fields
- the script deployment query returns the id of the script instead of the id of the deployment.
---
None
=> SALTO-1198: fixed bugs in changes detection

packages/logging/test/internal/pino_logger.test.ts
---
Test would fail on newer versions of node.js because the string representation of anonymous functions can be different
---
None
=> Removed test that relied on internal node implementation

packages/netsuite-adapter/specific-cli-options.md, packages/netsuite-adapter/src/adapter_creator.ts
Exposed the credentials for the SuiteApp to the user and documented the changes detection related option.
---
Netsuite:
Salto can now integrate with a dedicated Salto SuiteApp (contact Salto to install the SuiteApp). Given the required credentials to the SuiteApp integration, Salto will use the SuiteApp to detect changes in elements in the service and fetch only the changed element when using `fetchTarget` (not supported for all element types).
=> SALTO-1198: exposed changes detection to the user

packages/salesforce-adapter/src/filters/utils.ts, packages/salesforce-adapter/test/filters/utils.test.ts
Custom object instances get their ID generated by the service
We should not add a default fullName in our code
---
Salesforce adapter
- Fixed bug where data instances deployed from salto would get an extra "fullName" value in the nacl
=> Skip adding fullName to custom object instances

packages/lowerdash/.vscode/launch.json, packages/lowerdash/src/collections/tree_map.ts, packages/lowerdash/test/collections/tree_map.test.ts
In some cases we check for the existence of nested values by just reading them from the object - for object methods this will never return `undefined`, so the logic is incorrect and we may erroneously return the builtin functions / modify these shared properties in unintended ways.
Ran into this while trying out a swagger that has a nested field named `toString` - when this happens it crashes the fetch operation on  
```
error cli/cli Caught exception: TypeError: Cannot read property 'push' of undefined
TypeError: Cannot read property 'push' of undefined
at TreeMap.push (/Users/neta/code/salto/packages/lowerdash/src/collections/tree_map.ts:104:24)
...
```
Fixed the two relevant places in the flow that broke - there may be additional places that are impacted by this, these are the ones I …
=> Fix lowerdsah TreeMap get/set for inherited properties

packages/netsuite-adapter/src/config.ts
_fixed netsuite config created with deprecated keys_
---
_The empty keys were created due to a rebase issue - remove._
=> fixed netsuite config created with deprecated keys (SALTO-1226)

packages/workspace/src/workspace/element_selector.ts, packages/workspace/test/element_selector.test.ts
Add optional parameter to make selectors case insensitive
---
see
SALTO-1230
---
This will add an option to be used in SaaS for case insensitive selectors
=> SALTO-1230: Add option for case insensitive selectors

packages/salesforce-adapter/src/adapter.ts
=> changed fetchMetadataInstances to use Promise.all instead of awu

packages/workato-adapter/src/config.ts, packages/workato-adapter/src/filters/extract_fields.ts, packages/workato-adapter/test/adapter.test.ts
* Remove running indexes for recipe code instances - they were causing unnecessary id changes when recipes were added/removed (this surfaced SALTO-1240)
* Include unique ids in recipe instances and in folders - unfortunately this means these ids are _not multienv-friendly_, but for recipes there's no guarantee that any of the other fields will result in a unique and stable id. 
For folders, we can consider replacing these with the full path (may be easier to do after similar work @ori-moisis is planning for some Jira instances) - see SALTO-1241
---
Workato adapter - change ids for recipe and folder instances
=> Workato - remove unneeded indexes from code instance ids, add ids to non-unique names

packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/utils.test.ts, packages/netsuite-adapter/test/transformer.test.ts, packages/workspace/test/workspace/hidden_values.test.ts
---
Alternative to #1956 that handles cases for other non-plain objects as well (static file, variables and such)
---
- Fix potential corruption in nacl files when changing only reference expressions
=> SALTO-1240: Avoid replacing classes with plain objects in transform

packages/adapter-api/src/adapter.ts, packages/core/src/api.ts, packages/core/src/core/adapters/change_validators.ts, packages/core/src/core/adapters/custom_group_key.ts, packages/core/src/core/adapters/dependency_changers.ts, packages/core/test/core/adapters/dependency_changers.test.ts, packages/hubspot-adapter/src/adapter.ts, packages/hubspot-adapter/src/adapter_creator.ts, packages/marketo-adapter/src/adapter.ts, packages/marketo-adapter/src/adapter_creator.ts, packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/adapter_creator.ts, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/adapter_creator.ts, packages/workato-adapter/src/adapter.ts, packages/workato-adapter/src/adapter_creator.ts
Moved the deploy modifiers methods to be part of the `AdapterOperations` so we will have access to the `adapterContext` inside of these methods.
This is needed for the feature of deploying the file cabinet elements using the SuiteApp. In `getChangeGroupIds`, if the SuiteApp credentials were passed, I want to split the changed elements to a group of elements to deploy via SDF and a group of elements to deploy via the SuiteApp. If the SuiteApp credentials were not passed, I want to group all the changes under SDF. This change is needed to do so.
---
None
=> SALTO-1234: moved deploy modifiers to adapter operations

packages/workspace/src/parser/internal/native/consumers/values.ts, packages/workspace/test/parser/parse.test.ts
Trimming trailing whitespace can result in incorrect items in the deploy plan - for example for this nacl:
```
dummy.x y {
a = '''
Something
Something else  
'''
}
```
We would get this from `deploy -dp`:
```
| dummy.x.instance.y:
M a: "\n      Something\n   \n  Something else  \n    " => "\n      Something\n   \n  Something else  \n"
```
(because the whitespace is omitted when parsing but still exists in the state).
---
Fix bug that could add unneeded deploy items for multi-line strings ending in whitespace.
=> SALTO-1244 - Keep trailing whitespace in multiline strings

packages/cli/src/commands/clean.ts, packages/cli/src/formatter.ts, packages/cli/test/commands/clean.test.ts
Add option to recompute the nacl file cache separately from deploy/fetch, based on @roironn 's suggestion. 
This can be useful for speeding up the VSCode extension on slow machines, allowing it to run quicker reference lookups without requiring heavy blocking computations.
This is added initially as an additional flag under the `clean` command - we may want to revisit this later. 
This can be combined with any other `clean` flag except for cleaning the cache.
---
Add option to re-generate the file cache as part of the `salto clean` command
=> SALTO-1242 - Add dedicated command for re-generating the cache

docs/salto_configuration.md, packages/adapter-components/src/client/pagination.ts, packages/logging/README.md, packages/logging/src/internal/level.ts, packages/logging/test/internal/pino_logger.test.ts, packages/netsuite-adapter/package.json, yarn.lock
Add a more-verbose-than-debug log level so we can use it for dumping response objects without making the log unreasonably large. Ideally this would be in debug, but we need to clean up many of our current logs so adding `trace` (which is a standard `pino` log level) for the more verbose lines for now.
Note: In order to actually use this log level we need to support it in the `suitecloud-cli` as well - looks like it was pinned to a specific `@salto-io/logging` version ([here](https://github.com/salto-io/netsuite-suitecloud-sdk/commit/694ae308ae2376cf70cece6826ebc9437eee68bf#diff-65e8afbed413960add9206b039256e13a34b47b215c928b8d57cfd98f618fb28R26)) so we should probably cut a new release (and then bump it here). I'll verify with @omrilit that this is ok before merging this.
---
_Release …
=> Add trace log level

packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/change_validator.ts, packages/netsuite-adapter/src/change_validators/immutable_changes.ts, packages/netsuite-adapter/src/filters/add_parent_folder.ts, packages/netsuite-adapter/src/filters/instance_references.ts, packages/netsuite-adapter/src/transformer.ts, packages/netsuite-adapter/test/change_validators/immutable_changes.test.ts, packages/netsuite-adapter/test/filters/add_parent_folder.test.ts, packages/netsuite-adapter/test/filters/instance_references.test.ts
Added 'parent' field to the file cabinet instances
---
Instances of the file cabinet will now have a 'parent' field that will reference the parent folder of the instance.
=> SALTO-1234: added parent to file cabinet instances

packages/netsuite-adapter/scripts/types_generator.py, packages/netsuite-adapter/src/constants.ts, packages/netsuite-adapter/src/filters/consistent_values.ts, packages/netsuite-adapter/src/types/custom_types/customrecordtype.ts, packages/netsuite-adapter/test/filters/consistent_values.test.ts
Return consistent recordType value for entryForms and permittedRole for customRecordTypes
=> SALTO-1152 - Netsuite: return consistent values when SDF is inconsistent #2

packages/core/src/core/plan/dependency/reference_dependency.ts, packages/core/test/core/plan/dependency.test.ts
Changed `addReferencesDependency` to add dependencies also for references to none-elements targets (values, annotations, etc..)
This is needed for Netsuite, where all the references are to the ids of specific values of instance elements and not the ids of the instance elements.
---
None
=> SALTO-1234: dependencies will now be created for references to inner attributes

packages/netsuite-adapter/src/change_validators/immutable_changes.ts, packages/netsuite-adapter/src/filters/add_parent_folder.ts, packages/netsuite-adapter/src/filters/instance_references.ts, packages/netsuite-adapter/test/change_validators/immutable_changes.test.ts, packages/netsuite-adapter/test/filters/add_parent_folder.test.ts, packages/netsuite-adapter/test/filters/instance_references.test.ts
Following a conversion with @ori-moisis, it would be better if the `_parent` annotations in NetSuite file cabinet instances would reference the parent element itself and not its path.
---
None
=> changed parent to reference the element itself

packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/change_validators/file_changes.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/client/suiteapp_client/soap_client/schemas.ts, packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts, packages/netsuite-adapter/src/client/suiteapp_client/soap_client/types.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts, packages/netsuite-adapter/src/client/suiteapp_client/types.ts, packages/netsuite-adapter/src/group_changes.ts, packages/netsuite-adapter/src/suiteapp_file_cabinet.ts, packages/netsuite-adapter/src/types.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/change_validators/file_changes.test.ts, packages/netsuite-adapter/test/client/soap_client.test.ts, packages/netsuite-adapter/test/client/soap_responses.ts, packages/netsuite-adapter/test/group_changes.test.ts, packages/netsuite-adapter/test/suiteapp_file_cabinet.test.ts
Added support for deploying the entire file cabinet using the SuiteApp.
This PR includes:
- Adding the functionality of updating and creating files and folders through SOAP API.
- Using the new functionality to deploy the changes in the `suiteapp_file_cabinet`.
In case of additions, we need to deploy new folders before new files inside of those folders. To do so, we split the new changes into groups by the depth for the path of each file and deploy the groups in the order of their depths so a folder will always be deployed before the files inside it.
- Splitting the changes into the following groups:
- "Records" - Changes of anything that is not the file cabinet using SDF
- "Salto SuiteApp - File Cabinet - Creating Files" - Additions of new files and folders to the file cabinet to be …
=> SALTO-1234: support deploying the entire Netsuite file cabinet

packages/adapter-components/src/elements/swagger/type_elements/element_generator.ts, packages/adapter-components/src/elements/swagger/type_elements/swagger_parser.ts, packages/adapter-components/test/elements/swagger/petstore_openapi.v3.json, packages/adapter-components/test/elements/swagger/petstore_openapi.v3.yaml, packages/adapter-components/test/elements/swagger/type_elements.test.ts, packages/lowerdash/src/types.ts, packages/lowerdash/test/types.test.ts
Add support for `anyOf` and `oneOf` in the swagger type generator - leftover from https://github.com/salto-io/salto/pull/1941 .
Note: This does not cover all functionality (in terms of validations) because of some limitations of our type system, see SALTO-1259 for a suggested extension.
---
None
=> SALTO-1147 Support anyOf and oneOf in swagger adapter components

packages/netsuite-adapter/e2e_test/adapter.test.ts, packages/netsuite-adapter/e2e_test/adapter.ts, packages/netsuite-adapter/e2e_test/jest_environment.ts, packages/netsuite-adapter/package.json
e2e tests now run with Salto SuiteApp
Used `jest-each` to run every e2e-test with and without Salto SuiteApp
---
None
=> SALTO-1234: Netsuite e2e tests also SuiteApp

packages/adapter-components/src/client/base.ts, packages/adapter-components/src/client/http_client.ts, packages/adapter-components/src/client/http_connection.ts, packages/adapter-components/src/client/index.ts, packages/adapter-components/src/client/pagination.ts, packages/adapter-components/src/elements/ducktype/transformer.ts, packages/adapter-components/src/elements/request_parameters.ts, packages/adapter-components/src/elements/swagger/instance_elements.ts, packages/adapter-components/src/filter_utils.ts, packages/adapter-components/test/client/http_client.test.ts, packages/adapter-components/test/client/pagination.test.ts, packages/adapter-components/test/elements/ducktype/transformer.test.ts, packages/adapter-components/test/elements/swagger/instance_elements.test.ts, packages/adapter-components/test/filter_utils.test.ts, packages/workato-adapter/src/adapter.ts, packages/workato-adapter/src/client/client.ts, packages/workato-adapter/src/client/pagination.ts, packages/workato-adapter/test/client/pagination.test.ts, packages/workato-adapter/test/filters/extract_fields.test.ts, packages/workato-adapter/test/filters/field_references.test.ts, packages/workato-adapter/test/filters/recipe_references.test.ts
Interface change in the lightweight adapter shared infra:
* The client will only have a simple `get` that covers one page
* The pagination function will be provided separately (but still use the client and its config)
---
Also adjusted workato (in this PR) and zuora (in its [branch](https://github.com/netama/salto/commit/228652b9a0f6ee3c022a257488fe76fb292f96da)) - similar changes will be required in the other in-progress adapters.
---
None
=> SALTO-1147 Separate pagination layer from client

packages/adapter-components/package.json, packages/adapter-components/src/auth/index.ts, packages/adapter-components/src/auth/oauth.ts, packages/adapter-components/src/client/http_client.ts, packages/adapter-components/src/client/http_connection.ts, packages/adapter-components/test/auth/oauth.test.ts, packages/adapter-components/test/client/common.ts, packages/adapter-components/test/client/pagination.test.ts, packages/cli/src/callbacks.ts, packages/workato-adapter/src/client/connection.ts, packages/workato-adapter/test/client/connection.test.ts, packages/workato-adapter/test/client/pagination.test.ts, yarn.lock
Add OAuth `client_credentials` token auth method (only the functionality needed so far) in adapter-components.
This is initially intended for the Zuora adapter - see (temporary) usage [here](https://github.com/netama/salto/blob/feature/SALTO-1150-zuora-initial-with-infra/packages/zuora-billing-adapter/src/client/connection.ts#L42).
---
This has minor conflicts with https://github.com/salto-io/salto/pull/1990 in some tests - will be resolved once the first of them is merged.
---
None
=> SALTO-1150 Add OAuth access token reusable auth method

packages/salesforce-adapter/src/change_validator.ts, packages/salesforce-adapter/src/change_validators/multiple_deafults.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/test/change_validators/multiple_defaults.test.ts
Added a change validator to check for places where several `default` fields are set to `true` (only one is allowed) in specific lists/maps, and in picklists / multi-picklists.
Attempt to deploy instances with a field of one of those metadata types: `'ProfileApplicationVisibility', 'ProfileRecordTypeVisibility', 'StandardValue', 'CustomValue'`, or in a valueSet of a picklist/MultiselectPicklist, where `default = true` in more than one entry, will raise a warning since it is not allowed by SF.
=> SALTO-1163: Change validator for multiple default values

packages/cli/src/commands/env.ts, packages/cli/src/formatter.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/test/workspace/multi_env/multi_env_source.test.ts
Fix an issue where MultiEnvSource would return the wrong thing when asked for a secondary env source.
Also fixed an issue where diff would print a promise instead of the desired string.
---
---
Diff should start working
=> Fix issue with multi_env_source

packages/adapter-components/src/config/index.ts, packages/adapter-components/src/config/shared.ts, packages/adapter-components/src/config/transformation.ts, packages/adapter-components/src/elements/ducktype/transformer.ts, packages/adapter-components/src/elements/ducktype/type_elements.ts, packages/adapter-components/src/elements/instance_elements.ts, packages/adapter-components/src/elements/swagger/instance_elements.ts, packages/adapter-components/src/elements/swagger/type_elements/element_generator.ts, packages/adapter-components/src/elements/swagger/type_elements/type_config_override.ts, packages/adapter-components/src/elements/type_elements.ts, packages/adapter-components/test/config/shared.test.ts, packages/adapter-components/test/config/transformation.test.ts, packages/adapter-components/test/elements/ducktype/transformer.test.ts, packages/adapter-components/test/elements/ducktype/type_elements.test.ts, packages/adapter-components/test/elements/swagger/type_elements.test.ts, packages/adapter-components/test/elements/type_elements.test.ts, packages/workato-adapter/src/filters/extract_fields.ts
Add simple-adapter config option for hiding values for env-specific fields (`fieldsToHide`).
This is done by setting the `_hidden_value` annotation on the field to true.
Note that this needs to be used carefully, because it has the usual caveats of hidden values - mainly, hiding values nested inside lists can cause merge conflicts. This can be avoided by either completely omitting the field values (using `fieldsToOmit`), or making the array items standalone fields, so that the array becomes an array of references and but the elements that are merged are single elements.
---
None
=> SALTO-1147 Support hiding fields in simple-adapter configs

packages/salesforce-adapter/src/adapter_creator.ts, packages/salesforce-adapter/test/adapter.creator.test.ts
Fixed a bug where in Salesforce the config suggestions would be ignored if the configuration would not have deprecated fields
---
Salesforce Adapater:
Fixed a bug where in some cases the config suggestion would be ignored
=> fixed config suggestion ignored in salesforce

packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/test/workspace/multi_env/routers.test.ts
Fix issue where addition changes could be routed to a nacl source that did not contain
their parent, which caused invalid nacls to be written
---
When we update nacls with changes, addition changes assume they are either a top level element, or their parent exists (because if the parent did not exist, the change would have been adding the parent).
because of this bug in routing, it was possible to get to the nacl update code with an addition change that did not have a parent.
aligning the condition to match the condition in the nacl update code should make it work
---
Core
- Fixed bug that would cause invalid nacl files to be written on fetch in case new annotations or values were added to common elements in a multi-env workspace
=> SAAS-1833: Fix addition routing for nested values

packages/dummy-adapter/jest.config.js, packages/dummy-adapter/src/data/fixtures/instWithStatic.nacl.mock, packages/dummy-adapter/src/generator.ts, packages/dummy-adapter/test/generator.test.ts
Add an instance which points to a static file to the adapter's fixtures. New instance ID is:
`dummy.Full.instance.InstWithStatic`
=> add an instance which points to a static file to dummy adapters fixtures

packages/netsuite-adapter/e2e_test/adapter.test.ts, packages/netsuite-adapter/e2e_test/adapter.ts, packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/adapter_creator.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/client/credentials.ts, packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts, packages/netsuite-adapter/src/filters/service_urls.ts, packages/netsuite-adapter/src/service_url/file_cabinet.ts, packages/netsuite-adapter/src/service_url/types.ts, packages/netsuite-adapter/src/suiteapp_file_cabinet.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/adapter_creator.test.ts, packages/netsuite-adapter/test/client/client.test.ts, packages/netsuite-adapter/test/filters/add_parent_folder.test.ts, packages/netsuite-adapter/test/filters/consistent_values.test.ts, packages/netsuite-adapter/test/filters/convert_lists.test.ts, packages/netsuite-adapter/test/filters/instance_references.test.ts, packages/netsuite-adapter/test/filters/service_urls.test.ts, packages/netsuite-adapter/test/service_url/file_cabinet.test.ts, packages/netsuite-adapter/test/suiteapp_file_cabinet.test.ts
Added support for "Go To Service" for file cabinet instances.
This PR includes: 
- Creating `service_urls` filter to add URLs to elements
- Changing the `suiteapp_file_cabinet` to a class (Salto style), so it can cache the queries results to avoid running the queries more than once
- Adding the URL to file and folder instances
---
Added support for "Go To Service" for file cabinet instances
=> SALTO-1208: added support for go-to-service for file cabinet instnaces

packages/lowerdash/src/chunks.ts, packages/lowerdash/test/chunks.test.ts
Fix for an edge-case bug found when reviewing https://github.com/salto-io/salto/pull/2016 - when the first item is larger than the max size, the first chunk is empty.
---
None
=> Fix weightedChunks when first item is larger than size limit

packages/core/src/core/deploy.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/custom_object_instances_deploy.ts, packages/salesforce-adapter/src/filters/custom_objects_instances.ts, packages/salesforce-adapter/test/custom_object_instances.crud.test.ts, packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
Limit custom object instances query length in fetch and deploy to not exceed
the recommended salesforce URI length of 2000
---
- Fix issue where fetching or deploying a large number of data records could fail with a "URI too long" error
=> SALTO-1274: Limit salesforce query length

packages/adapter-components/src/elements/swagger/type_elements/type_config_override.ts, packages/adapter-components/test/elements/swagger/type_elements.test.ts
Allow specifying field types even if the field did not exist in the original definition (instead of only overriding existing ones).
---
Will be useful in Zuora to extract a field that is nested under `additionalProperties` - but it can be useful in general for that purpose.
---
None
=> Swagger adapter-components - support creating fields that did not exist based on config

packages/netsuite-adapter/src/change_validator.ts, packages/netsuite-adapter/src/change_validators/account_specific_values.ts, packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/test/change_validators/account_specific_values.test.ts
Netsuite Adapter: Allow deploying instances with ACCOUNT_SPECIFIC_VALUE, while not deploying the real value behind it. Add a deployment warning in case it happens.
=> SALTO-1269: Partially support deploying instances with ACCOUNT_SPECIFIC_VALUES

packages/netsuite-adapter/config_doc.md, packages/netsuite-adapter/package.json, packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/src/config.ts, packages/netsuite-adapter/test/client/sdf_client.test.ts, packages/netsuite-adapter/types/suitecloud-cli.d.ts, yarn.lock
**This PR won't pass build until https://github.com/salto-io/netsuite-suitecloud-sdk/pull/26 is merged and published to npm.**
I chose not to rename `fetchTypeTimeoutInMinutes` to `commandTimeout` since I wanted to avoid another disrupting change to customers existing WSs, and especially SaaS customers until [Feature Suggestion: notify customers about upcoming changes in their configuration](https://salto-io.atlassian.net/browse/SAAS-1749) is implemented. If you think otherwise please LMK. FYI @tomermevorach 
Netsuite Adapter: Modify fetchTypeTimeoutInMinutes client property to enforce timeout for all SDF commands.
=> SALTO-1277: Set command timeout for all commands from SDF and bump SDF to 1.1.2-salto-6

packages/dummy-adapter/src/generator.ts
Unite dummy adapter fixture env paths to single path.
---
Allows for easier maintenance of dummy adapter fixtures.
---
Unite dummy adapter fixture env paths to single path.
=> SALTO-1284 - Unite dummy adapter fixture env paths

packages/adapter-components/src/elements/swagger/index.ts, packages/adapter-components/src/elements/swagger/type_elements/element_generator.ts, packages/adapter-components/src/elements/swagger/type_elements/swagger_parser.ts, packages/adapter-components/test/elements/swagger/type_elements.test.ts
Allow generating type elements based on pre-parsed swagger definitions.
Also exported the return type do avoid re-defining it in the adapters.
---
This will be used in the Zuora billing adapter to generate types for the settings endpoint, whose definitions are returned dynamically and not defined in the main swagger.
---
None
=> Swagger adapter-components - allow passing in pre-parsed swagger defs

packages/cli/src/commands/fetch.ts, packages/cli/test/commands/fetch.test.ts, packages/core/src/api.ts
Add regenerateSaltoIds flag to fetch (ignore state id mapping)
*** Need to add tests ***
---
**CLI:** 
* Add a regenerateSaltoIds flag to fetch that ignores current ElemID mapping from the state if active
=> Add regenerateSaltoIds flag to fetch (ignore state id mapping)

packages/netsuite-adapter/src/config.ts
Workbook & Dataset have a `definition` field which is a multiline string in XML format and it has a 'translationScriptId' field that is changed every fetch.
---
Netsuite Adapter: New workspaces will now not fetch Workbooks & Datasets by default since their definition is changing in every fetch. This behavior can be changed by removing them from the netsuite.nacl skip list.
=> Netsuite: Add Workbooks & Datasets to the default skip list since they generate changes every fetch

packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/test/client/sdf_client.test.ts
I chose to implement it with a very naive solution and not create a util function for that
None
=> SALTO-1282: Add retry to Netsuite SDF authentication command

packages/adapter-api/src/adapter.ts, packages/adapter-components/src/filter_utils.ts, packages/adapter-components/test/filter_utils.test.ts, packages/core/test/core/fetch.test.ts, packages/lowerdash/src/strings.ts, packages/lowerdash/test/strings.test.ts, packages/workato-adapter/config_doc.md, packages/workato-adapter/src/adapter.ts, packages/workato-adapter/src/config.ts, packages/workato-adapter/src/constants.ts, packages/workato-adapter/src/filters/cross_service/recipe_references.ts, packages/workato-adapter/src/filters/cross_service/reference_finders/netsuite.ts, packages/workato-adapter/src/filters/cross_service/reference_finders/recipe_block_types.ts, packages/workato-adapter/src/filters/cross_service/reference_finders/salesforce.ts, packages/workato-adapter/src/filters/cross_service/reference_finders/shared.ts, packages/workato-adapter/test/adapter.test.ts, packages/workato-adapter/test/adapter_creator.test.ts, packages/workato-adapter/test/filters/recipe_references.test.ts
Extend the workato reference filter to find more references:
* Changing the configuration to support listing multiple connections per adapter (also preparing for supporting multiple accounts under the same adapter in SALTO-1264, which will require some additional changes but can keep this config format)
* The user doesn't need to specify if this is the primary or secondary connector - we conclude that from the connection and look only at the relevant blocks for each connection
* Extending workato->salesforce reference coverage:
* Parsing salesforce object+field details from formulas - there are a few different patterns, I assume we may discover a couple more later on and can add them as well
* Adding references to objects other than the primary sobject from `field_list`
---
* Also …
=> SALTO-1280 Support secondary connectors, formulas and related objects in workato cross-service references

packages/adapter-components/src/client/http_connection.ts, packages/adapter-components/test/client/common.ts, packages/workato-adapter/src/client/connection.ts, packages/workato-adapter/test/client/connection.test.ts, packages/zuora-billing-adapter/src/client/connection.ts
We often don't use the credentials, so switching to named parameters to avoid having unused args following @ori-moisis 's suggestion
---
None
=> adapter-components - use named parameters in function validating credentials

packages/logging/src/internal/logger.ts, packages/logging/src/internal/pino.ts, packages/logging/test/internal/pino_logger.test.ts
Provide capabilities for getting the global tags from the logger.
---
This will be useful for adding tracing capabilities and utilizing the existing tags in our logger infra.
---
None
=> SAAS-1981: Provide getGlobalTags capabilities to BaseLogger

packages/lang-server/src/workspace.ts, packages/workspace/src/validator.ts, packages/workspace/src/workspace/workspace.ts
Change some implementations in validation flow to support concurrency
---
Required to allow batching in SaaS
---
Should improve performance of some flows
=> Allow more concurency in validation

packages/core/src/local-workspace/remote_map.ts, packages/core/test/workspace/local/remote_map.test.ts
Change the validation regex in remote map to allow spaces in env name
---
---
environments with spaces in their name should be supported
=> Allow spaces in env names

packages/salesforce-adapter/src/types.ts
---
Already encountered two real accounts where fetching this type caused an internal server error on salesforce, deemed not valuable enough to fetch by default
---
- Added ContentAsset to default skip list
=> SALTO-1301: Add ContentAsset to default skip list

packages/salesforce-adapter/config_doc.md, packages/salesforce-adapter/src/fetch_profile/fetch_profile.ts, packages/salesforce-adapter/src/filters/extra_dependencies.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/extra_dependencies.test.ts
The extra dependencies filter seems to fail on some accounts, unclear why, but since this filter only gets information that does not affect the correctness of the rest of the configuration (and cannot be deployed back) we would like to allow users to skip it
---
- Allow disabling the extra dependencies filter
=> SALTO-1296: Add ability to disable extra dependencies filter in salesforce adapter

packages/salesforce-adapter/src/types.ts
---
---
* Added CustomObjectTranslation to default exclude metadataType
=> SALTO-1303 - Add CustomObjectTranslation to default exclude metadataType

packages/lowerdash/src/collections/asynciterable.ts, packages/lowerdash/test/collections/asynciterable.test.ts
handleErrorsAsync can be used to place an error handler on an async iterable
---
there is currently no other way to handle exceptions in async iterables when using the asynciterable.*Async functions.
this is because the callbacks we provide those functions are only called if the iterable resolved its `next` function successfully.
The only places that can handle errors are the functions that fully consume the iterable (toArrayAsync, findAsync, forEachAsync)
---
_None_
=> Added handleErrorsAsync function to lowerdash

packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/custom_object_instances_references.ts, packages/salesforce-adapter/test/filters/custom_object_instances_references.test.ts
Change the CustomObject Instances Reference logic to include not only the referencing itself but also logic about invalid Instances. 
There are 3 "invalid" reasons - 
1. Colliding ElemID
2. Missing references (reference to a missing instance)
3. References to an Instance we chose to omit (due to 1/2/3)
This PR has 2 parts - 
1. The implementation of the above logic
2. Warnings about the omitted instances based on https://www.notion.so/saltoio/Salesforce-Data-Management-0b397279069b4f368f692d617f721487
---
Salesforce Adapter - 
* CustomObject Instances with collisions in ElemID or references to non-Fetched Instances are now omitted from the fetch. Information about these Instances is available through Fetch Errors (Warnings).
=> SALTO-1256 Custom Object instances omitting & warning

packages/adapter-components/src/config/index.ts, packages/adapter-components/src/config/request.ts, packages/adapter-components/src/elements/request_parameters.ts, packages/adapter-components/src/elements/swagger/instance_elements.ts, packages/adapter-components/test/elements/request_parameters.test.ts, packages/adapter-components/test/elements/swagger/instance_elements.test.ts
Allow "recursing into" an entry to fetch additional fields that do not return from the main endpoint of that type
---
Developed as part of JIRA adapter preparations, used to handle REST resources that have multiple layers like
/mainResource/{resourceID}/subResources
/mainResource/{resourceID}/subResources/{subResourceID}/details
etc...
---
_None_
=> Add ability to fetch an instance from multiple endpoints in adapter components

packages/adapter-api/src/builtins.ts, packages/workspace/src/validator.ts, packages/workspace/test/validator.test.ts
- Before this change the validator would not check built in annotations because it would not get their types correctly
- Also changed the type of the `_default` core annotation to Unknown because it should support any type
---
- Fixed issue where broken references would not be detected when they were in built in annotations such as _generated_dependencies
=> SALTO-1305: fix validation of broken references in built in annotations

packages/dummy-adapter/generate.sh
Running `yarn build && yarn test` locally after a previous build without running `yarn clean` fails, because more fixtures are created under `dist/src/data/fixtures/fixtures`. 
I think it may be safer to completely re-generate these as part of the `test` command, but since it looks like this was added for a SaaS test, starting with the smaller fix.
---
None (internal)
=> Fix dummy adapter failure on 2nd unittest run

packages/adapter-api/src/adapter.ts, packages/adapter-components/test/filter_utils.test.ts, packages/core/src/core/fetch.ts, packages/core/test/core/fetch.test.ts, packages/workato-adapter/src/adapter.ts, packages/workato-adapter/test/adapter.test.ts, packages/workato-adapter/test/filters/recipe_references.test.ts
Support reporting progress post-fetch as well, and use it in workato.
---
For now reusing the adapter's fetch progress report - we may want to revisit it later (see discussion on the ticket).
---
None
=> SALTO-1304 Report progress post-fetch

packages/salesforce-adapter/test/adapter.discover.test.ts
In the past few weeks one of the discovery tests fails occasionally on timeouts (mostly locally). It looks like it just got a little slower due to a recent change, and since it was already close to the time limit the extra slowness is causing the flakiness.
---
It looks like this started happening when the query throttling was added in https://github.com/salto-io/salto/commit/fda83465a99f58b9730bd634cc5743410132a035#diff-c8aa71d139bb13eaefbf09c63a685d3b7b071585b9751074a0dc53afeadd52d3R501 - and it's just some extra slowness that was added (using unlimited concurrent queries is still just a little too slow, but removing the decorator from the new functions is enough to get the tests to pass). We could increase the timeout by 1-2s, but it doesn't look like the current number of concurrent …
=> Fix salesforce flaky test timeout

packages/workspace/src/parser/internal/native/consumers/blocks.ts, packages/workspace/test/parser/errors.test.ts
Ran into this when looking into a sample workspace with a `toString` field. There might be other places that will need to change (or we can decide to rename fields with problematic names?)
---
Also see https://github.com/salto-io/salto/pull/1937 for a previous related fix.
---
None (not known to exist in any of the current adapter fields)
=> SALTO-1315 ignore builtins when checking field existence in parser

packages/workato-adapter/src/filters/cross_service/reference_finders/salesforce.ts, packages/workato-adapter/test/filters/recipe_references.test.ts
Extract references from related objects using `get_custom_object` in workato recipes.
---
_(only if not already mentioned in another PR's notes in the same release)_
Workato adapter - extract additional salesforce references
=> SALTO-1280 Extract references from get_custom_object

packages/workspace/src/workspace/workspace.ts
Need to load the workspace regardless of clear params so it will be ready to be flushed.
=> Fix clear only service config fails (SALTO-1272)

eslintrc.js, packages/adapter-components/src/client/decorators.ts, packages/e2e-credentials-store/.eslintrc.js, packages/lang-server/src/usage.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/client/sdf_client.ts, packages/salesforce-adapter/src/filters/settings_type.ts
Added a lint rule to prevent bugs like this:
```
const async x() => {
...
}
const async y() => {
try {
return x()
} catch (e) {
...
}
}
```
The rule found two missed awaits
---
None
=> added return-await lint rule

packages/adapter-components/test/config/transformation.test.ts, packages/salesforce-adapter/e2e_test/adapter.test.ts, packages/salesforce-adapter/src/filters/custom_objects.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/adapter.discover.test.ts, packages/salesforce-adapter/test/filters/custom_objects.test.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts
Because the default is false and it's redundant
---
* Removed the _required annotation for false values in Fields
=> SALTO-1321 - Remove _required = false

docs/syntax.md, docs/user_guide.md
Updated user guide and the NaCl documentation to match the current implementation
---
This basically replaces the outdated https://github.com/salto-io/lang-spec
---
- Updated user guide and the NaCl documentation to match the current implementation
=> SALTO-1313: Update NaCl documentation

packages/netsuite-adapter/src/changes_detector/changes_detector.ts, packages/netsuite-adapter/test/changes_detector/changes_detector.test.ts
Fixed a bug that if the changes detection would return there are no changes at all, we would not attempt to fetch types that are not supported by the changes detector.
---
None
=> Fixed bug for partial fetch of type that are not supproted by the changes detector

packages/cli/src/commands/service.ts, packages/cli/src/formatter.ts, packages/cli/src/prompts.ts, packages/cli/test/commands/service.test.ts, packages/core/src/api.ts
add more information for the users about what configurable services are open for him to use.
services already listed under configured services will not be seen in the new text.
services which are private (like dummyadapter) will not be seen by the user.
in case there are no more services to be configured there is a different message for it without listing anything.
---
add tests for what i can test easily.
there might be more to check but i dont think this feature deserves any more tests...
---
CLI:
add additional configurable services to the "salto service list command" in cli.
=> SALTO-1323: service list command

packages/salesforce-adapter/src/elements_url_retreiver/lightining_url_resolvers.ts, packages/salesforce-adapter/test/elements_url_retreiver.test.ts
---
* Added go to service functionality for instances of custom objects
=> SALTO-1317 - custom object instances go to service

packages/lowerdash/src/values.ts, packages/lowerdash/test/values.test.ts, packages/workspace/package.json, packages/workspace/src/workspace/hidden_values.ts, packages/workspace/test/workspace/hidden_values.test.ts, yarn.lock
Switch new diff implementation to something that can handle arrays + objects with `{ key: undefined }` without generating an incorrect diff.
blocker for https://github.com/salto-io/salto/pull/2078
---
None (not released yet)
=> switch hidden_values diff to handle nested arrays and undefined values

packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/test/workspace/multi_env/routers.test.ts
Instead of unpacking a large record we need to merge, we merge it with reduce, avoiding a stack maximum size issue.
Solves jira [SALTO-1325]:
---
---
should enable support for larger fetches
[SALTO-1325]: https://salto-io.atlassian.net/browse/SALTO-1325
=> fix issue with over-large parameters to route changes

packages/adapter-components/src/elements/instance_elements.ts, packages/adapter-utils/src/nacl_case_utils.ts, packages/adapter-utils/test/nacl_case_utils.test.ts
Limit pathNaclCase to a 200 chars to avoid issues with certain OS that limit the length of file names
---
---
Core:
* New elements will create files with a length limited to 200 chars. This will not effect current file names for existing worksapces.
=> Limit pathNaclCase to a 200 char

packages/adapter-api/src/builtins.ts, packages/adapter-utils/index.ts, packages/adapter-utils/src/dependencies.ts, packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/dependencies.test.ts, packages/adapter-utils/test/utils.test.ts, packages/salesforce-adapter/src/filters/extra_dependencies.ts, packages/salesforce-adapter/test/filters/extra_dependencies.test.ts, packages/workato-adapter/src/filters/cross_service/reference_finders/netsuite.ts, packages/workato-adapter/src/filters/cross_service/reference_finders/salesforce.ts, packages/workato-adapter/src/filters/cross_service/reference_finders/shared.ts, packages/workato-adapter/test/adapter.test.ts, packages/workato-adapter/test/filters/recipe_references.test.ts, packages/zuora-billing-adapter/src/filters/object_defs.ts, packages/zuora-billing-adapter/src/filters/workflow_and_task_references.ts, packages/zuora-billing-adapter/test/filters/object_defs.test.ts, packages/zuora-billing-adapter/test/filters/workflow_and_task_references.test.ts
Extend the `_generated_dependencies` + `_depends_on` annotations to support optional details about the location and direction. See the ticket for more details.
---
* We still need to decide if we want a flat format or an aggregate - I started with an aggregate, but the flat one is a little simpler so we can switch to it if it's preferred.
* Starting by supporting only `input` / `output` (/ undefined = unknown) for directions - we can consider also adding a `both` option, but since it seems to not be common right now and requires more careful maintenance, we can start without it and add it later as needed.
---
Updated the structure of some core annotations (`_generated_dependencies` and `_depends_on`) to allow specifying more granular information about the references used …
=> SALTO-1314 Update generated dependencies format

packages/adapter-api/src/utils.ts, packages/adapter-api/test/utils.test.ts, packages/adapter-components/src/elements/soap/type_elements/types_generator.ts, packages/adapter-components/src/elements/type_elements.ts, packages/adapter-components/test/elements/soap/types_generator.test.ts, packages/adapter-components/test/elements/type_elements.test.ts, packages/netsuite-adapter/package.json, packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts, packages/netsuite-adapter/src/data_elements/data_elements.ts, packages/netsuite-adapter/src/filters/hidden_fields.ts, packages/netsuite-adapter/src/filters/remove_redundant_fields.ts, packages/netsuite-adapter/src/filters/remove_unsupported_types.ts, packages/netsuite-adapter/src/filters/replace_record_ref.ts, packages/netsuite-adapter/src/types.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/data_elements/data_elements.test.ts, packages/netsuite-adapter/test/filters/hidden_fields.test.ts, packages/netsuite-adapter/test/filters/remove_redundant_fields.test.ts, packages/netsuite-adapter/test/filters/remove_unsupported_types.test.ts, packages/netsuite-adapter/test/filters/replace_record_ref.test.ts, packages/netsuite-adapter/tsconfig.json
Added support for fetching the SOAP types in Netsuite.
Currently, all the lines that use the new functionality in adapter.ts are commented out, so this PR does not affect the user.
---
None
=> SALTO-825: added fetch for dataTypes

packages/netsuite-adapter/e2e_test/cred_store, packages/netsuite-adapter/e2e_test/credentials_store/adapter.ts, packages/netsuite-adapter/e2e_test/jest_environment.ts, packages/netsuite-adapter/src/client/suiteapp_client/constants.ts
In order for the SuiteApp bundle to include the integration, I had to create new integration in the same account I created the bundle. Therefore I had to change the consumer keys.
The `netsuite` to `netsuite_tmp` is to not break the e2e tests in master since the old credentials won't work with the new integration.
---
None
=> changed suiteapp integration keys

packages/workato-adapter/src/filters/cross_service/reference_finders/netsuite.ts, packages/workato-adapter/src/filters/cross_service/reference_finders/recipe_block_types.ts, packages/workato-adapter/src/filters/cross_service/reference_finders/salesforce.ts, packages/workato-adapter/src/filters/cross_service/reference_finders/shared.ts, packages/workato-adapter/test/filters/recipe_references.test.ts
Note: also includes the changes from https://github.com/salto-io/salto/pull/2076, please only review the workato part here.
Include details about the reference location and direction in workato references.
---
WIP - This is an initial suggestion for discussion, we still need to finalize the `location` details for consistency (right now, formula references point to the specific formula field, but some others point at the whole block).
---
Workato adapter - Add more specific details in cross-service references in recipes.
=> SALTO-1314 Add location and direction in workato cross-service references

packages/workato-adapter/src/filters/cross_service/element_indexes.ts, packages/workato-adapter/src/filters/cross_service/reference_finders/netsuite.ts, packages/workato-adapter/test/filters/recipe_references.test.ts
Support referenencing Netsuite standard types and fields - this will allow generating more Netsuite references once SALTO-825 is merged (first part is in https://github.com/salto-io/salto/pull/2081 but will need to be enabled - verified that when enabled the references are generated).
---
Workato adapter:
* Support generating references from recipes to Netsuite standard types and fields
=> SALTO-1314 Add workato references to Netsuite standard objects and fields

packages/netsuite-adapter/e2e_test/adapter.test.ts, packages/netsuite-adapter/scripts/types_generator.py, packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/client/suiteapp_client/soap_client/schemas.ts, packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts, packages/netsuite-adapter/src/client/suiteapp_client/soap_client/types.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts, packages/netsuite-adapter/src/data_elements/data_elements.ts, packages/netsuite-adapter/src/data_elements/types.ts, packages/netsuite-adapter/src/filters/data_instances_internal_id.ts, packages/netsuite-adapter/src/filters/data_instances_references.ts, packages/netsuite-adapter/src/filters/remove_unsupported_types.ts, packages/netsuite-adapter/src/filters/replace_record_ref.ts, packages/netsuite-adapter/src/suiteapp_file_cabinet.ts, packages/netsuite-adapter/src/types.ts, packages/netsuite-adapter/src/types/file_cabinet_types.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/client/soap_client.test.ts, packages/netsuite-adapter/test/data_elements/data_elements.test.ts, packages/netsuite-adapter/test/filters/data_instances_internal_id.test.ts, packages/netsuite-adapter/test/filters/data_instances_references.test.ts, packages/netsuite-adapter/test/suiteapp_file_cabinet.test.ts
This PR is to fetch instances of data types.
The line that fetches the instances is commented out to not affect the user until SALTO-825 is done.
---
There are two methods of fetching using SOAP: `search` and `getAll`.
`search` supports paging, so if possible, we use search. If a certain type does not support search, we use `getAll`.
In addition, in this PR, two filters were added:
- data_instances_internal_id - extract to a new instance every object in a list that contains an internal id (since the internal id is hidden, and we don't support hidden values in lists, the objects in the list need to be extracted to new instances).
- data_instances_references - creates references between the instances based on the types of the field and the internal id in the value.
--- …
=> SALTO-825: fetching instances from SOAP

packages/netsuite-adapter/e2e_test/cred_store, packages/netsuite-adapter/e2e_test/credentials_store/adapter.ts, packages/netsuite-adapter/e2e_test/jest_environment.ts
Restored the e2e pool type name in PR https://github.com/salto-io/salto/pull/2126/files
---
None
=> SALTO-1359: restored the e2e pool type name

packages/core/src/core/fetch.ts
(same as https://github.com/salto-io/salto/pull/2132)
Internal log to track cases where multiple incoming service changes conflict with a workspace change, which can result (if accepted by the user) in invalid nacls.
Note that this is not a fix yet.
---
None
=> SALTO-1364 Add log when merging fetch change with local parent

packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts, packages/netsuite-adapter/src/client/types.ts, packages/netsuite-adapter/test/client/soap_client.test.ts, packages/netsuite-adapter/test/client/suiteapp_client.test.ts
Suiteapp invalid creds don't throw an indicative error on fetch/deploy - fixed.
---
Due to SaaS requirements, may support revoked tokens as well.
---
=> SALTO-1360 - Added indicative error message for invalid suiteApp credentials

packages/cli/src/commands/init.ts, packages/cli/src/prompts.ts, packages/cli/test/commands/init.test.ts
added a keyed option flag to the init command that allows an optional input for the first environment name to spare the interactive input.
also changed the output massage of the init command for Tomer's request to a shorter message that doesn't include the environment name and the path
---
---
added a flag to init command that allows to create the first environment as an init command input
=> Salto 1355: Allow init command without interactive input

packages/cli/src/commands/service.ts, packages/cli/src/formatter.ts, packages/cli/src/prompts.ts, packages/cli/test/commands/service.test.ts
changed the error that return when running salto service add with an in valid adapter name.
also change the exit code to the user input error code
---
---
Improve service add command error in case of invalid service name
=> Salto 1324: Improve service add command error in case of invalid service name

packages/adapter-components/src/config/shared.ts, packages/adapter-utils/src/element.ts, packages/jira-adapter/src/config.ts
Added usage of createMatchingObjectType in the shared config for simple adapters. This raised the need to add validation of MapType in `SaltoTypeForType`, which revealed a bug in Jira's config (`types` should be a `MapType` instead of an `ObjectType`).
---
None
=> Simple adapters config type fix

packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/nacl_files/parsed_nacl_files_cache.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
_Use keep ref in workspace remote maps serializers_
---
_IThe keepRef attribute should be passed to workspace serializer in order to make sure that if a reference to value is passed, it will be saved as a reference and not a value_
---
_NA_
=> use keep ref in workspace remote maps

packages/core/src/local-workspace/remote_map.ts, packages/core/src/local-workspace/state.ts, packages/core/src/local-workspace/workspace.ts, packages/core/test/workspace/local/remote_map.test.ts, packages/lang-server/test/workspace.ts, packages/vscode/src/extension.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/nacl_files/parsed_nacl_files_cache.ts, packages/workspace/src/workspace/remote_map.ts, packages/workspace/src/workspace/state/in_mem.ts, packages/workspace/src/workspace/state/state.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/multi_env/multi_env_source.test.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.state.test.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts, packages/workspace/test/workspace/nacl_files/parsed_nacl_files_cache.test.ts, packages/workspace/test/workspace/state.test.ts, packages/workspace/test/workspace/workspace.test.ts
_Add a new location that holds the tmp storage db in remote app_
---
_rocksDB prevents us when we attempt to open two write connections to the same location at the same time. This creates a situation that prevent the editor to be open along side a shell operation. In order to solve this, we added a way to specify a ws as a non-persistent ws. In such a case, the ws won't be flushable, and the connection to the main location will be read only_
---
_NA_
=> Modified remote map to have different db for tmp

packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/changes_detector/changes_detector.ts, packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/src/data_elements/data_elements.ts, packages/netsuite-adapter/src/elements_source_index/elements_source_index.ts, packages/netsuite-adapter/src/elements_source_index/types.ts, packages/netsuite-adapter/src/filter.ts, packages/netsuite-adapter/src/filters/data_instances_references.ts, packages/netsuite-adapter/src/filters/instance_references.ts, packages/netsuite-adapter/src/query.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/changes_detector/changes_detector.test.ts, packages/netsuite-adapter/test/data_elements/data_elements.test.ts, packages/netsuite-adapter/test/elements_source_index.test.ts, packages/netsuite-adapter/test/filters/add_parent_folder.test.ts, packages/netsuite-adapter/test/filters/consistent_values.test.ts, packages/netsuite-adapter/test/filters/convert_lists.test.ts, packages/netsuite-adapter/test/filters/data_instances_internal_id.test.ts, packages/netsuite-adapter/test/filters/data_instances_references.test.ts, packages/netsuite-adapter/test/filters/hidden_fields.test.ts, packages/netsuite-adapter/test/filters/instance_references.test.ts, packages/netsuite-adapter/test/filters/remove_redundant_fields.test.ts, packages/netsuite-adapter/test/filters/remove_unsupported_types.test.ts, packages/netsuite-adapter/test/filters/replace_record_ref.test.ts, packages/netsuite-adapter/test/filters/service_urls.test.ts, packages/netsuite-adapter/test/query.test.ts
This PR is to make the new Netsuite instances to support the skip list and partial fetch. 
The changes in the element index are to make the references work when using partial fetch
---
None
=> SALTO-825: added support for skip list for data instances

packages/cli/src/commands/clean.ts, packages/cli/src/formatter.ts, packages/cli/test/commands/clean.test.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/workspace.ts
_Fix cache is not being create when the regenerate flag is passed to clean_
---
_The cache was not regenerated since the regenerate command cleans the cache after the load. In order to fix that, full ws load is now invoked after the clean._ 
Note regarding tests - I'm still trying to find a way to unit-test this, I'm not sure it makes real sense. Either way - gonna add an e2e test for it in the dummy adapter e2e PR.
---
=> fixed cache regeneration

packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/test/client/sdf_client.test.ts
Dear reviewer, should I create the same PR also on top of the lazy_ws branch?
NetSuite adapter: reduce the probability of inconsistent fetch results due to SDF unexpected error.
=> SAAS-2204: Add retry on top of SDF unexpected errors to reduce the inconsistent skipList noise

packages/adapter-api/src/elements.ts, packages/adapter-utils/src/element.ts, packages/adapter-utils/test/element.test.ts, packages/adapter-utils/test/utils.test.ts, packages/hubspot-adapter/src/transformers/transformer.ts, packages/jira-adapter/src/config.ts, packages/workspace/src/parser/internal/nearly/converter/elements.ts
- Added back the validation on list and map inner types
- We now allow references in createMatchingObjectType because it is
better than the alternative solution of creating empty object types
- Fixed jira config type which was wrong
---
None (only real fix is the jira config type and that is not really released yet)
=> Enforce list and map types in createMatchingObjectType

packages/core/src/local-workspace/remote_map.ts, packages/core/test/workspace/local/remote_map.test.ts, packages/core/test/workspace/local/remote_map_connection.test.ts, packages/vscode/src/extension.ts
_Added connection close in vscode and improved db creation_
---
_The code that creates the persistent db connection was not atomic, causing a failure when two remote maps when the same location were created in the same time_
---
_NA_
=> Fixed persistent DB creation is not atomic (fixes SALTO-1377)

packages/netsuite-adapter/src/client/sdf_client.ts
NetSuite adapter:
Fix fetch failures for accounts with thousands of files in the FileCabinet
=> SALTO-1399: Netsuite: Limit sdf_client read from FS concurrency

packages/adapter-components/src/config/index.ts, packages/adapter-components/src/config/swagger.ts, packages/adapter-components/src/elements/subtypes.ts, packages/adapter-components/src/elements/swagger/type_elements/element_generator.ts, packages/adapter-components/src/elements/type_elements.ts, packages/adapter-components/test/config/swagger.test.ts, packages/adapter-components/test/elements/swagger/type_elements.test.ts, packages/jira-adapter/src/adapter_creator.ts, packages/jira-adapter/src/config.ts, packages/stripe-adapter/src/adapter_creator.ts, packages/stripe-adapter/src/config.ts, packages/stripe-adapter/test/adapter_creator.test.ts, packages/zuora-billing-adapter/src/adapter_creator.ts, packages/zuora-billing-adapter/src/config.ts, packages/zuora-billing-adapter/test/adapter_creator.test.ts
Added supportedType field to the config of swagger adapters as an optional field.
---
This is important for Stripe adapter since we only support a small subset of Stripe's types, and may be useful for future adapters.
Added validation of the field to enforce it's not empty if defined.
Added usage in Stripe adapter.
---
Added a supportedTypes field in swagger-based adapters' config.
Stripe Adapter: The only types that will be visible now in the workspace are the ones Salto supports.
=> Swagger Simple Adapters infra: added supportedTypes field to config

packages/salesforce-adapter/config_doc.md, packages/salesforce-adapter/src/filter.ts, packages/salesforce-adapter/src/filters/add_missing_ids.ts, packages/salesforce-adapter/src/filters/elements_url.ts, packages/salesforce-adapter/src/filters/profile_paths.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/filters/add_missing_ids.test.ts, packages/salesforce-adapter/test/filters/elements_url.test.ts, packages/salesforce-adapter/test/filters/profile_paths.test.ts
Added a configuration option to disable the filters - add_missing_ids , profile_paths and elements_url on fetch.
---
---
- Configurable enabling/disabling of specific filters - add_missing_ids , profile_paths and elements_url on fetch.
=> Salto 1296 - optionalFeatures configuration  to filters on fetch

packages/workspace/src/expressions.ts, packages/workspace/test/core/expressions.test.ts
_fixed top level parent in reference expressions are not resolved_
---
_Elements should be fully resolved after the resolve function is called. The bug took place since the top level parent of reference expressions values were not resolved, causing the `type` field to remain unresolved. The netsuite adapter attempted to access the type of said element - causing an error to be thrown._
---
_NA_
=> fixed top level parent in reference expressions are not resolved (fix SALTO-1400)

packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/test/workspace/multi_env/routers.test.ts
_Move commands crushed when invoked with an missing element id_
---
_the existence check was to late in the flow_
---
_NA_
=> fixed move commands end when invoked with a missing element id

packages/core/src/core/diff.ts, packages/core/test/core/diff.test.ts
_Added missing element source in diff command_
---
_When invoking a diff command, the elements are taken directly from the element sources so they are unresolved, and the element sources need to be provided to the transform element function._
---
_NA_
=> added missing element source in diff command (fix SALTO-1404)

packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/test/workspace/multi_env/routers.test.ts
_fixed nested field values are not wraped when moved between envs_
---
_The add to source function did not wrap changes that were do not exists in the target source. nacl file sources fail to handle some types of nested changes (in this example, nested field change). This change makes sure that all changes that are created with this function are properly nested. _ (Also, unskipped a few tests that were skipped for no reason) 
---
=> fixed nested field values are not wraped when moved between envs (SALTO-1407)

packages/salesforce-adapter/config_doc.md, packages/salesforce-adapter/src/filters/add_missing_ids.ts, packages/salesforce-adapter/src/filters/elements_url.ts, packages/salesforce-adapter/src/filters/extra_dependencies.ts, packages/salesforce-adapter/src/filters/profile_paths.ts, packages/salesforce-adapter/src/filters/utils.ts, packages/salesforce-adapter/test/filters/add_missing_ids.test.ts, packages/salesforce-adapter/test/filters/elements_url.test.ts, packages/salesforce-adapter/test/filters/extra_dependencies.test.ts, packages/salesforce-adapter/test/filters/profile_paths.test.ts
Adding a try catch for each one of the filter that return a Salto error with severity of warning in case an error was catched.
---
---
In case of an error during fetch in one of the filters below they will return warning and won't crash the fetch process:
extra_dependencies, add_missing_ids, profile_paths and elements_url
=> Salto 1296 - warnings mechanism for extra_dependencies, add_missing_ids , profile_paths and elements_url

packages/salesforce-adapter/src/change_validators/package.ts, packages/salesforce-adapter/src/deprecated_config.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/change_validators/package.test.ts
Fixed package change validator to work for elements with API name with suffixes different than `__c`
---
Fixed a bug where for some elements, while deploying them, Salto would misclassify them as elements that belong to a namespace and throw an error about it.
=> SALTO-1414: changed package change validator to warning

packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/test/workspace/multi_env/routers.test.ts
_fixed get mergeable id for number attr and element names_
---
_get mergeable parent checked if a part of the elemID is a number to decide if it represents a list value. This does not work for element or attribute names which are numbers._
---
_NA_
=> fixed get mergeable id for number attr and element names

packages/salesforce-adapter/src/change_validators/package.ts, packages/salesforce-adapter/test/change_validators/package.test.ts
Changed package validator to validate only custom objects and fields.
---
Salto will no longer disable deployments of elements that belong to a namespace unless it is a field or a custom object.
=> SALTO-1414: changed package validator to validate only custom objects and fields

packages/workspace/src/workspace/nacl_files/elements_cache.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/workspace.ts
_workaround form SALTO-1428_
---
_When a merged element cache is invalidated, the default behaviour is to clear and rebuild it by 'getting' all of the elements in the lower sources and merging them. This is not the desired behaviour in the SaaS UI - where we only want to clear the maps. This is a quick temporary workaround to prevent blocking the testing until the issue is fixed in a nicer manner._
---
_NA_
=> workaround form SALTO-1428

packages/adapter-api/src/element_id.ts, packages/adapter-api/test/elements.test.ts, packages/adapter-utils/src/utils.ts, packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/src/workspace/nacl_files/nacl_file_update.ts, packages/workspace/test/workspace/multi_env/routers.test.ts
After the [fix](https://github.com/salto-io/salto/pull/1595/files) for SALTO-1003, we omit from the move to common elements that are empty. This has an undesired effect in some scenarios - if we have detailed changes that contain _only_ non-standard primitive annotation types, they may be omitted because they are considered to be empty. 
---
Can happen in cases where a full object is moved to common after some of it is already in common.
Added some more details on the ticket.
---
_Core_: Fixed bug where non-standard annotation types were dropped on move-to-common of the element, if part of it was already in common.
=> SALTO-1431 Avoid omitting annotation types from move-to-common

packages/salesforce-adapter/src/change_validators/package.ts, packages/salesforce-adapter/test/change_validators/package.test.ts
Same as #2176 for lazy
---
None
=> SALTO-1414: change package validator to only custom objects and fields lazy

packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/test/client/sdf_client.test.ts
In case of an error in fetching instances in Netsuite, for some types (`savedcsvimport` and `pluginimplementation`) SDF would return different type names. This would cause Salto to add invalid type names to the skip list
---
Fixed a bug where in some cases an invalid type name would be added to the configuration skip list
=> SALTO-1446: Fixed type names in SDF error response

packages/netsuite-adapter/src/changes_detector/changes_detectors/custom_record_type.ts, packages/netsuite-adapter/src/changes_detector/changes_detectors/custom_type.ts, packages/netsuite-adapter/src/changes_detector/changes_detectors/file_cabinet.ts, packages/netsuite-adapter/src/changes_detector/changes_detectors/role.ts, packages/netsuite-adapter/src/changes_detector/changes_detectors/script.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts, packages/netsuite-adapter/src/service_url/custom_field.ts, packages/netsuite-adapter/src/service_url/custom_record_type.ts, packages/netsuite-adapter/src/service_url/custom_transaction_type.ts, packages/netsuite-adapter/src/service_url/emailtemplate.ts, packages/netsuite-adapter/src/service_url/role.ts, packages/netsuite-adapter/src/service_url/script.ts, packages/netsuite-adapter/src/service_url/sublist.ts, packages/netsuite-adapter/src/suiteapp_file_cabinet.ts, packages/netsuite-adapter/test/changes_detector/custom_field.test.ts, packages/netsuite-adapter/test/changes_detector/custom_list.test.ts, packages/netsuite-adapter/test/changes_detector/custom_record_type.test.ts, packages/netsuite-adapter/test/changes_detector/file_cabinet.test.ts, packages/netsuite-adapter/test/changes_detector/role.test.ts, packages/netsuite-adapter/test/changes_detector/script.test.ts, packages/netsuite-adapter/test/client/suiteapp_client.test.ts
Netsuite support gave a better workaround to the problem described in https://salto-io.atlassian.net/browse/SALTO-1416: To add the the queries `ORDER BY <unique identifier> ASC` (SuiteQL does not support ORDER BY without ASC)
---
None
=> SALTO-1416: fix suiteql queries

packages/workspace/src/workspace/nacl_files/elements_cache.ts, packages/workspace/test/workspace/workspace.test.ts
_Fixed merge errors are not removed when fixed_
---
_This fixes a bug in which merge errors that were fixed by the user were not updated in the cache due to a faulty condition in the cache update logic. This PR fixes this logic._
---
_NA_
=> fixed merge errors are not removed when fixed

packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/workspace.test.ts
Fix issue where lazy element workspace would return wrong number of changes on updateNaclFiles in workspace
---
---
The number of changes printed in fetch will be correct
=> fix [SALTO-1410] - updateNaclFiles returning wrong number of changes

packages/adapter-api/src/builtins.ts, packages/adapter-api/src/core_annotations.ts, packages/core/src/core/fetch.ts, packages/netsuite-adapter/src/change_validators/immutable_changes.ts, packages/netsuite-adapter/src/reference_dependencies.ts, packages/netsuite-adapter/test/types.test.ts, packages/salesforce-adapter/test/adapter.crud.test.ts, packages/salesforce-adapter/test/adapter.discover.test.ts, packages/salesforce-adapter/test/filters/custom_objects.test.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts
added boolean CORE_ANNOTATION "_service_id" which indicates wether field's type is service_id type
=> SALTO-1382 Identify ServiceId By Core Annotation

packages/salesforce-adapter/src/transformers/missing_fields.json, packages/workspace/.vscode/launch.json
Add KnowledgeSettings languages missing field
---
added a few salesforce field’s type related to KnowledgeSettings.
=> Salto 1394 - Add KnowledgeSettings languages missing field

packages/core/src/local-workspace/remote_map.ts
_reuse readonly main db connection_
---
_When two write connections are created in the same time for rocks db - an error will be thrown. The remote map implementation did not acquire main read connection in an atomic way. Since creating read connections involved creating a write connection to see if the db exists - a race condition could have resulted in the error_
---
_NA_
=> reuse readonly main db connection (fixes SALTO-1453)

packages/core/src/core/plan/plan.ts, packages/workspace/src/expressions.ts, packages/workspace/test/core/expressions.test.ts
_resolve top level parent only when needed_
---
_When passed to the adapter, resolved reference expression needs to have the optional top level parent attribute set with a resolved element id. (which used in the netsuite adapter). An old bug in the lazy element branch was caused by the fact that the top level parent was not resolved. The fix for that bug (which was to always resolve the top level parent) solved the issue, but introduced a very large performance penalty in the `getPlan` method. (specifically, in the `isEqualNode` method. This fix solves the issue by adding a resolve root boolean which is only used in the one place in which is needed. As a result, the performance of the `getPlan` method were greatly improved. _
---
_NA_
=> resolve top level parent only when needed (fix SALTO-1458)

packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/workspace.test.ts
_Fix error on rename env_
---
_The nacl files source throws an error if its member are accessed before its load method was invoked. This call was missing from the rename env method causing an error to be thrown. This fix adds the call._
---
_NA_
=> Fix error on rename env (fix SALTO-1452)

packages/core/src/local-workspace/remote_map.ts
Fix issue where too many temp dbs would be created for each process
---
---
Some internal folders no user would look at will be cleaner
=> [SALTO-1375] create only one tmp DB per process

packages/core/src/core/clean.ts, packages/core/src/local-workspace/remote_map.ts
When clean is called - delete dbs
---
---
when users use salto clean, it will also clean rocksdb databases
=> [SALTO-1456] Delete dbs on clean

packages/core/src/core/diff.ts, packages/core/src/core/plan/plan_item.ts, packages/core/test/core/plan/plan_item.test.ts
_ changed restore to apply the selectors to the plan instead of the entire workspace_
---
_The restore method applied its element selectors to the entire workspace. That resulted with invoking transform elements on the entire workspace and state, which was painfully slow (~70second for the workspace in the ticket). In order to solve it, we modified the method to apply the selectors to the result of the `getPlan` function by:
- Adding a new method to filter plan item changes
- Using this method to filter out the plan
- Verifying that all of the specific element selectors were present by checking that the get function on the element sources returns a value (this method can handle exact selectors so there was no need for the previous complex sieve usage)
Since …
=>  changed restore to apply the selectors to the plan (fix SALTO-1441)

packages/workspace/src/workspace/nacl_files/elements_cache.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/common/nacl_file_store.ts, packages/workspace/test/workspace/workspace.test.ts
_fixed removing fields with hidden annotation from the nacls does not remove the hidden annotations_
---
_When a change is made in the nacls, we complete the hidden parts from the state. When a field is removed - we need to make sure what we don't re-add the hidden field annotation. This fix fixes a bug in which the workspace element which is used as a reference was taken from the nacl version *before the change* with the fields. Causing the fields to be re added. The solution was to use the version of the field *after the change* in which the fields are already deleted._
---
_NA_
=> Fix remove change to field with hidden annotations (fix SALTO-1451)

packages/netsuite-adapter/src/filters/remove_unsupported_types.ts, packages/netsuite-adapter/test/filters/remove_unsupported_types.test.ts
Fixed upgrading from NetSuite without SuiteApp to NetSuite with SuiteApp
Due to a collision between SDF types to SOAP types, the fetch after the upgrade would throw an error. 
---
None
=> SALTO-1465: fixed upgrade from NetSuite without SuiteApp to with SuiteApp

packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/test/workspace/multi_env/routers.test.ts
_changed fetch align to drop add changes if mergeable id is in common_
---
_Until this fix, the route align method would have passed all add changes to the primary source. This was based on an assumption that all of the changes that are produced by the plan are "mergeable". This assumption did not take into account add changes inside an array object in which the array did not change length. When this type of change was applied that an array which was in the common source - the result was an array with a lot of undefined items in the primary source. The fix is to route an add change to the primary source only if its mergeable id is not in common._
---
_Fixed add changes in common array can result in invalid nacls in the env folder when using fetch align_
=> changed fetch align to drop add changes if mergeable id is in common (Fixes SALTO-1430)

packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
---
Bug Fix:
Salesforce: 
* Fix issue with modify of CustomObject instances that values that were present and after modify are not were not deleted in the past
=> SALTO-1448 - Deploy with null instead of no values on CustomObject instances deploy

packages/workspace/src/serializer/elements.ts, packages/workspace/src/validator.ts, packages/workspace/test/validator.test.ts
Fixed a bug where a value of a field with max_length annotation would have some value that is not a string, an invalid error message would be thrown
---
None
=> SALTO-1438: fixed max-length validation when value is not a string

packages/cli/src/prompts.ts, packages/core/src/core/diff.ts, packages/workspace/src/workspace/element_selector.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/element_selector.test.ts
Until now, when explicit elem ids (without any wildcards) were passed to operations like `move-to-common` / `clone` / `move-to-envs` (and `diff`), we would fail if not all of them were found in the (env-specific part of the) selected env. 
We're changing this behavior to be the same as selectors with wildcards - the preview will show the full list of ids that were _found_, and any missing ids will be omitted silently.
---
Core: 
- Commands that accept selectors no longer throw an error when element ids that were specified exactly are not found. This impacts `move-to-common`, `clone`, `move-to-envs`, and `diff`.
=> SALTO-1450 avoid failing move operations on missing ids

packages/cli/src/workspace/workspace.ts, packages/cli/test/commands/fetch.test.ts, packages/netsuite-adapter/src/types/file_cabinet_types.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/workspace.test.ts
_update workspace cache after merge state only_
---
_The resolve command compares the workspace merged cache (which is a merge of the nacls and the hidden values from the state) with the state. When the state-only command was invoked, the workspace was not updated with the changes, resulting in the merged cache no accounting for the changed hidden value, So if an hidden value has changed during a state only fetch, it would have be shown as a diff that needs to be restored. (In SALTO-1442, the fields that showed up are last fetch time which are hidden, and change on every fetch). The solution is to update the workspace with the hidden parts of the fetch changes in state only mode._
---
_Replace me with a short sentence that describes the effect of this change on Salto …
=> update workspace cache after merge state only (fix SALTO-1442)

packages/adapter-api/src/values.ts, packages/cli/src/commands/element.ts, packages/cli/src/prompts.ts, packages/core/src/core/diff.ts, packages/core/test/core/diff.test.ts, packages/workspace/src/workspace/element_selector.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/element_selector.test.ts, packages/workspace/test/workspace/multi_env/multi_env_source.test.ts
Similar change to https://github.com/salto-io/salto/pull/2224 (adjusted to the new implementation) + additional unrelated fixes due to the changes in the branch (see SALTO-1471).
---
* I think there's still some remaining issue in how we load the referenced type's fields in `transformElements` - @roironn can you please check if it's something you're familiar with? (see the relevant comment)
* We should have better coverage of functions like `getElementIdsBySelectors` and not just as part of another test. I'll try to add a few tomorrow
---
None (assuming it will already be listed in the master release)
=> SALTO-1450 SALTO-1471 avoid failing move operations on missing ids

packages/workspace/src/workspace/workspace.ts
_added state hash validity check on first ws build_
---
_When building the workspace state, the salto state validity was always assumed. As a result, when the state file was changed out of band (for example, using a git checkout) changes in the state were ignored. The fix is to add a check for the state hash validity. (In the future we are planning on making the state non atomic - that is - allow iterative changes. When we'll do that we can also check for the changes midway) _
---
_NA_
=> added state hash validity check on first ws build (SALTO-1480)

packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/common/nacl_file_source.ts, packages/workspace/test/workspace/multi_env/multi_env_source.test.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts, packages/workspace/test/workspace/workspace.test.ts
_added a static file reviver for workspace and multi env source_
---
_The workspace and multi env source did not have static file reviver, since they do not have a static file store (or information as to which source a specific static file belongs to).  This resulted in static files being loaded as simple static files, which prevented their content from being loaded, this in turn lead to deploy fails when attempting to deploy static files, since their data was missing.
In order to resolve this, we added a method that allows to get a static file from the file source by hash. Since the hash is a good identifier for content, and since it is present in the simple static file, this allows us to properly revive the static files without de-encapsulation
---
_NA_
=> added a static file reviver (fix SALTO-1454)

.circleci/config.yml
Before change: CI failed.
After change: CI no longer fails.
=> Fix AWS CLI in circleci config

packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
_added an explicit check to ensure that a file was deleted_
---
The path attribute that is created in the adapter is case sensitive. However, some filesystems are case insensitive. This can lead to some file overrides, so file changes are grouped based on their lower case value. The actual file name is not in lower case, and one of the possible filenames is used. This can result in the files being written to a different location than their filename attribute in the following way:
- Two changes are create with the following pathes: [a, b, c.nacl] and [a, B, d.nacl].
- The files will not be grouped together since the full filename is not the same in lower case.
- When the first file is flushed, mkdir -p is invoked. 
- When the second file is flushed - mkdir has no effect (it is case …
=> added an explicit check to ensure that a file was deleted (SALTO-1433)

packages/adapter-api/src/values.ts, packages/workspace/src/expressions.ts, packages/workspace/test/core/expressions.test.ts
Fix validation errors in workato
---
The issue was in `resolve`. When a value in an element would reference another value in the same element it would not be fully resolved due to the fact that transformValues creates deep copy of the values
---
None
=> SALTO-1461: fixed workato validation error

packages/workspace/src/workspace/nacl_files/index.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/nacl_files/parsed_nacl_file.ts, packages/workspace/src/workspace/nacl_files/parsed_nacl_files_cache.ts, packages/workspace/test/common/nacl_file_source.ts, packages/workspace/test/common/nacl_file_store.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts, packages/workspace/test/workspace/nacl_files/parsed_nacl_files_cache.test.ts
Using the modification timestamp is suspected to be incorrect in certain scenarios
Because the effect of using the wrong cache can be critical (corrupts the workspace)
and the performance difference should not be too significant, changing the logic for
additional safety
---
This is the same logical change as #2137 
---
None (the same change was made on master, so the release notes were there)
=> SALTO-1366: Change cache logic to always use file hash

packages/netsuite-adapter/src/config.ts
The current default file cabinet regexes in Netsuite wouldn't include the top folders, e.g. The folder `/SuiteScript` does not match the regex `^/SuiteScripts/.*`. This would cause the top folders instances to not be fetched.
---
None
=> Fix default netsuite folders regexes

packages/core/src/core/diff.ts, packages/core/test/core/diff.test.ts
_fixed diff command ignores field annotation changes when selectors are used_
---
_When a field selector was used, the diff command ignored changes in that field. This is due to an error which assumed that the change element is a top level element. Field is a legal change element, so the assumption did not hold. Fixed this by checking for the change top level element id._
---
_NA_
=> fixed diff command ignores field annotation changes (SALTO-1484)

packages/dummy-adapter/src/generator.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/common/nacl_file_source.ts, packages/workspace/test/workspace/multi_env/multi_env_source.test.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
_Fix static file changes ignored in deploy_
---
_The `getStaticFilesByHash` method used in the workspace element source deserialize function, used the cached static file hash in order to differentiate static files with the same path which exists in both the common and the primary source. This caused it to fail when a static file was changed (since the hash didn't match) causing the diff function to ignore the change. In order to resolve that, we removed the hash check, added a log warning if the file exists in both envs with different hashes, and created https://salto-io.atlassian.net/browse/SALTO-1062 for future handling._
---
_NA_
=> Fix static file changes ignored in deploy (SALTO-1485)

packages/core/src/local-workspace/remote_map.ts
__
added an informative error for db locks when destroyed is called
---
_Destroy can throw an error if another process is holding a write connection to the db. We wrapped this error with an informative wrapper_
---
=> added an informative error for db locks when destroyed is called (SALTO-1483)

packages/workspace/src/validator.ts, packages/workspace/test/validator.test.ts
bug fix, when a value has a reference the validation won't continue validating that value
when a value has a reference the validation won't continue validating that value
=> Salto 1327 - Incorrect validation error on references with a required field

packages/netsuite-adapter/src/filters/parse_saved_searchs.ts, packages/netsuite-adapter/src/saved_search_parsing/parsed_saved_search.ts, packages/netsuite-adapter/test/filters/parse_saved_searches.test.ts
fixed bug with double dependencies as object types.
---
the other option to fix this was not to create a new dependency in the new parsed saved search and use the old one but it is not exported and the code there is generated.
=> fixed bug with double dependecies fields

packages/netsuite-adapter/src/change_validator.ts, packages/netsuite-adapter/src/change_validators/subinstances.ts, packages/netsuite-adapter/src/filters/data_instances_internal_id.ts, packages/netsuite-adapter/test/change_validators/subinstances.test.ts, packages/netsuite-adapter/test/filters/data_instances_internal_id.test.ts
When there is an object with an internal id inside a list, we extract it to a different instance and add a reference to it (because we don't support hidden values inside lists). This instances are not deployable so I added a change validate to verify the user does not edit them
---
None
---
None
=> SALTO-825: added change validator to prevent deployment of sub-instances

packages/adapter-api/src/builtins.ts, packages/cli/e2e_test/salto.test.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/transformers/transformer.ts
This reverts commit SALTO-1308 which caused a bug when fetching on existing non empty workspace.
has been tested on a workspace after fetch with master version. second fetch worked fine.
=> Revert "SALTO-1308 Make Read-Only Field Annotations Hidden (#2194)"

packages/netsuite-adapter/src/filters/data_instances_internal_id.ts, packages/netsuite-adapter/test/filters/data_instances_internal_id.test.ts
Sub-instances of SDF types might not have the required fields of the type. To avoid validation errors we use `RecordRef` types for sub-instances of SDF types
---
None
---
None
=> SALTO-825: fixed required validation error in subinstances

packages/workspace/src/parser/internal/native/consumers/blocks.ts, packages/workspace/src/parser/internal/native/errors.ts, packages/workspace/test/parser/errors.test.ts
added a parse error for  annotation values inside annotation type definitions
added a parse error for  annotation values inside annotation type definitions
=> Salto 1363 - Parser should create parse error when annotation values are added to an annotation type definition

packages/netsuite-adapter/src/filters/data_instances_internal_id.ts, packages/netsuite-adapter/test/filters/data_instances_internal_id.test.ts
Data instances can have references to SDF instances that have required fields. If the instance is skipped, we can create a reference to the instance so we leave the value as is. The problem is that the value might not have the required fields. To solve this, we extract the value to sub-instance of type `RecordRef` 
---
None
---
None
=> SALTO-825: fixed validation errors for skipped instances

packages/netsuite-adapter/src/elements_source_index/elements_source_index.ts, packages/netsuite-adapter/src/filters/roles_internal_id.ts, packages/netsuite-adapter/test/elements_source_index.test.ts, packages/netsuite-adapter/test/filters/roles_internal_ids.test.ts
Fixed two issues with partial fetch for data instances:
- If the partial fetch would not include `role`s the role internal id field would be deleted
- internalIdsIndex includes sub-instances that caused wrong references in the `data_instances_references` filter
---
None
---
None
=> SALTO-825: fixed partial fetch for data instances

packages/salesforce-adapter/src/change_validators/package.ts, packages/salesforce-adapter/test/change_validators/package.test.ts
removed the filter of modification change from package change validator to resolved this bug. 
---
Salto will now return an error when when modifying a managed object.
---
none
=> SALTO - 1500 package change validator is not working on modification change

packages/netsuite-adapter/src/change_validators/immutable_changes.ts, packages/netsuite-adapter/src/data_elements/data_elements.ts, packages/netsuite-adapter/src/data_elements/multi_fields_identifiers.ts, packages/netsuite-adapter/src/data_elements/types.ts, packages/netsuite-adapter/test/data_elements/data_elements.test.ts
Apparently, types with `parent` can have the same identifier if their parent is different. 
Fixed the identifiers to use the parent in the identifier. 
---
None
---
None
=> SALTO-825: fixed identifiers with parent

packages/zuora-billing-adapter/src/adapter.ts, packages/zuora-billing-adapter/src/filters/unordered_lists.ts, packages/zuora-billing-adapter/test/filters/unordered_lists.test.ts
The field is an unsorted list, and its order changes on every fetch. Sorting it to avoid unnecessary noise in the nacls.
---
Zuora Billing:
* Sort the Settings_Role.attributes field to avoid noise due to order changes returned from the API.
=> SALTO-1502 Sort the attributes field in Settings_Role to make it stable across fetches

packages/workspace/src/parser/internal/native/consumers/values.ts, packages/workspace/src/parser/internal/native/lexer.ts, packages/workspace/test/parser/parse.test.ts
Fixed a bug where the parser throws an error for instance names starting with a boolean value (e.g., `false_name`)
---
Fixed incorrect syntax errors for instance names starting with boolean values
---
None
=> fixed parser to support names starting with booleans

packages/netsuite-adapter/scripts/types_generator.py, packages/netsuite-adapter/src/types/custom_types/emailtemplate.ts
Fix bug: Modify EmailTemplate type to allow the existence of standard email templates without having a workspace validation on them.
---
Netsuite emailtemplate type will be modified in existing workspaces upon the next fetch. No action item is needed from the customer's side.
=> Netsuite Adapter: allow standard email templates scriptid to avoid validation warnings

packages/cli/src/workspace/workspace.ts, packages/cli/test/commands/deploy.test.ts, packages/cli/test/commands/fetch.test.ts, packages/cli/test/commands/restore.test.ts, packages/cli/test/mocks.ts, packages/cli/test/workspace/workspace.test.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/workspace.test.ts
Change result of workspace `updateNaclFiles` to a type including:
- Number of NaCl updates
- Number of state only updates
Instead of a number represents the sum of all changes
---
This is required in order to determine if changes were applied in SAAS.
Specifically, it is required in scenarios like Fetch Align,
in order to determine if a user approval is required.
---
_Release Notes_: N/A
---
_User Notifications_: N/A
=> SALTO-1509 - Change result type of workspace update NaCls

packages/dummy-adapter/src/generator.ts
Added service URL for dummy adapter element.
This is done for writing an e2e in the SaaS to test the "show in service" functionality
---
None
---
None
=> Added service url to dummy adapter element

packages/salesforce-adapter/src/change_validators/package.ts
error message that has been created by packageChangeError ChangeValidator will now print the correct nameSpace
=> SALTO-1498 packageChangeError ChangeValidator Printing Issue fixed

packages/adapter-components/src/elements/ducktype/index.ts, packages/adapter-components/src/elements/ducktype/standalone_field_extractor.ts, packages/adapter-components/src/elements/ducktype/transformer.ts, packages/adapter-components/src/elements/index.ts, packages/adapter-components/test/elements/ducktype/standalone_field_extractor.test.ts, packages/workato-adapter/src/adapter.ts
In preparation for the Zendesk adapter which will also use standalone fields, moving the logic from a workato-specific filter to the shared `ducktype` code (the `swagger` variant is already in `adapter-components`).
Note that there are some other improvements we can make in that logic - focused on just making it reusable for now to avoid code duplications.
---
None
=> SALTO-1149 move logic for extracting standalone fields to shared ducktype code

packages/workspace/src/workspace/hidden_values.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/common/nacl_file_store.ts, packages/workspace/test/workspace/hidden_values.test.ts, packages/workspace/test/workspace/workspace.test.ts
- Add support for changing an annotation type from a hidden to a visible type (and vice versa)
- Fix handling of annotation types becoming hidden / visible
---
_None_ (this fixes an issue that could not happen in any released version of the code)
---
_None_
=> SALTO-1495: Add support for annotation type changes in hidden values

packages/adapter-components/src/config/ducktype.ts, packages/adapter-components/src/config/index.ts, packages/adapter-components/src/elements/ducktype/type_elements.ts, packages/adapter-components/test/elements/ducktype/type_elements.test.ts
Add a `typeNameOverrideFrom` config option to allow giving better names to nested types in ducktype adapters (will initially be used for Zendesk).
---
None
---
None
=> SALTO-1149 adapter-components - support renaming types in ducktype adapters

packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/workspace.test.ts
_Changed workspace element call to return state only elements only if they are explicitly marked as hidden_
---
When an element which contains a hidden value is fetched in state only mode, its hidden part will be returned from workspace.elements. As a result, restore create nested changes for an element which is not in the nacls. When this type of changes is applied to the workspace, parsing errors are created. The solution was to restore the old behaviour, in which top level elements which are in the state and not in the nacls will only be returned if they are explicitly marked as hidden. 
---
_Fixed restoring an element with hidden values creates invalid nacl files._
---
_NA_
=> modify ws.element to avoid returning state-only elements unless hidden (fixes SAAS-2639)

packages/netsuite-adapter/e2e_test/adapter.test.ts, packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/filters/data_instances_identifiers.ts, packages/netsuite-adapter/src/filters/remove_redundant_fields.ts, packages/netsuite-adapter/test/filters/data_instances_identifiers.test.ts
Open Netsuite data instances for users
---
This PR:
- uncomment the commented line that fetches data instances
- adds e2e for fetching and deploying data instances
- Fixed bug that when creating data instances we are sending the "identifier" value too
- removed redundant fields from fetch 
---
Additional types were added for accounts with Salto SuiteApp configured (Subsidiary, Account, Location, Items, and more). The additional types support all deployment types (creation, modification, and deletions)
---
New instances of the new types will be fetched in the next fetch for users with Salto SuiteApp configured
=> SALTO-825: open data instances

packages/salesforce-adapter/src/change_validators/multiple_deafults.ts, packages/salesforce-adapter/test/change_validators/multiple_defaults.test.ts
---
multi defaults change validator will now yield instance element ids instead of the field.
---
None
=> SALTO-1515: return instance ElemID instead of Field in MultiDefaultsChangeValidator

packages/adapter-components/test/elements/ducktype/instance_elements.test.ts, packages/adapter-components/test/elements/swagger/instance_elements.test.ts, packages/adapter-utils/src/nacl_case_utils.ts, packages/adapter-utils/test/nacl_case_utils.test.ts
Escape digit-only identifiers to distinguish them from array indices. See discussion on SALTO-1424 (we may eventually want to add a dedicated notation, but this should hopefully be enough for now).
---
Doesn't look like we enforce anywhere the use of naclCase (the dummy adapter isn't really using it either) - I think maybe we should, at least in some tests, but didn't want to tie that to this change.
---
Add escaping for element id parts that only contain digits.
=> SALTO-1424 escape digit-only identifiers in naclCase

packages/workspace/src/workspace/hidden_values.ts
Moved the "?." to the correct place in the line
---
should solve the failure from [this e2e run](https://app.circleci.com/pipelines/github/salto-io/salto/9847/workflows/de44c64f-e94a-4c6a-9128-8a17f8570117/jobs/67649)
---
_None_ (fixes an unreleased bug)
---
_Replace me with a short sentence that describes the changes in the PR that the user should be notified about (changes to elements in existing workspaces, migrations, etc...)_
=> Fix handling undefined values in hidden values filter

packages/salesforce-adapter/src/filters/hardcoded_lists.json
Salesforce's `QuickAction.field.fieldOverrides` should be a list, so added to the `hardcoded_lists.json` file
=> SALTO-1513 add salesforce.QuickAction.field.fieldOverrides to hardcoded_lists

packages/workspace/src/workspace/nacl_files/addition_wrapper.ts, packages/workspace/test/workspace/multi_env/routers.test.ts, packages/workspace/test/workspace/nacl_files/elements_cache.test.ts
When instance annotations were added and the router had to wrap them with a new instance
it would move the annotations to the instance values instead
---
This case was triggered by running fetch align and getting a new annotation.
This would create a change where the instance would have this annotation in its `.value` instead of in `.annotations`.
When this was stored in the nacl cache, the issue would persist and would cause trouble when trying to deploy that instance since the rest of the code is not built to handle the case where an annotation is placed in a value (and so, it treated that annotation as if it was part of the value, tried to deploy it, and crashed).
Note that a workaround for existing workspaces is to clear their nacl cache (that would force the parser to read the nacl …
=> SALTO-1449: Fix router moving annotations to values when wrapping instance additions

docs/syntax.md
documentation and uses example for the new core annotation `_is_service_id`
=> added documentations for new core annotations

packages/salesforce-adapter/src/change_validator.ts, packages/salesforce-adapter/src/change_validators/picklist_promote.ts, packages/salesforce-adapter/src/filters/value_set.ts, packages/salesforce-adapter/test/change_validators/picklist_promote.test.ts
Adds a change validator to salesforce, prohibiting a picklist field to have a change of regular value-set to a global one (promotion). will add another change-error for the global value-set creation itself.
---
* Salto will now return an error when when attempting to promote a picklist value-set to a global one.
---
_NA_
=> SALTO-1466 picklist promote

packages/adapter-components/src/client/index.ts, packages/adapter-components/src/client/pagination.ts, packages/adapter-components/src/elements/ducktype/standalone_field_extractor.ts, packages/adapter-components/test/client/pagination.test.ts, packages/adapter-components/test/elements/ducktype/standalone_field_extractor.test.ts, packages/stripe-adapter/src/adapter.ts, packages/stripe-adapter/test/adapter.test.ts, packages/stripe-adapter/test/filters/field_references.test.ts, packages/workato-adapter/test/adapter.test.ts, packages/zuora-billing-adapter/src/client/pagination.ts, packages/zuora-billing-adapter/test/filters/field_references.test.ts, packages/zuora-billing-adapter/test/filters/object_defs.test.ts, packages/zuora-billing-adapter/test/filters/unordered_lists.test.ts, packages/zuora-billing-adapter/test/filters/workflow_and_task_references.test.ts
A couple of additional infra improvements before the zendesk PR:
* Allow custom path validation on cursor pagination
* Support arrays of standalone fields in ducktype adapters
---
None
---
None
=> adapter-components improvements - cursor pagination, standalone fields

packages/netsuite-adapter/e2e_test/adapter.test.ts, packages/netsuite-adapter/package.json, packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/test/client/sdf_client.test.ts, yarn.lock
I rebased all of our changes on top of the newest available SDF node.js version.
This PR includes:
1. using the new version
2. align the "save token" command parameter as done in the new version
3. unskip NS e2e tests that failed since the new version was released
---
None
---
None
=> SAAS-2792: use newer SDF after rebasing our fork on top of 2021.1.1 since previous version is deprecated

packages/adapter-components/src/references/context.ts, packages/adapter-components/src/references/field_references.ts, packages/adapter-components/src/references/index.ts, packages/adapter-components/src/references/reference_mapping.ts, packages/adapter-components/test/references/field_references.test.ts, packages/lowerdash/src/types.ts, packages/salesforce-adapter/e2e_test/adapter.test.ts, packages/salesforce-adapter/src/filters/field_references.ts, packages/salesforce-adapter/src/transformers/reference_mapping.ts, packages/salesforce-adapter/test/filters/cpq/fields_with_context_references.test.ts, packages/stripe-adapter/src/filters/field_references.ts, packages/workato-adapter/src/filters/field_references.ts, packages/zuora-billing-adapter/src/filters/field_references.ts
We had a few advanced features in the Salesforce reference resolution engine that we will need in Zendesk as well, so moving them (with some small adjustments) to the new reusable reference engine in adapter-components.
---
None
---
None
=> SALTO-1149 make reference resolution context reusable in adapter-components

packages/workspace/src/validator.ts, packages/workspace/test/validator.test.ts
This fixes the validator code to emit a validation warning when a required value
is missing inside a map. before this it only worked in lists and objects.
---
- Fixed issue where we would not get validator errors when a required value was missing in a map
---
_None_
=> SALTO-1540: Support validating required values inside maps

packages/salesforce-adapter/src/change_validators/profile_map_keys.ts, packages/salesforce-adapter/test/change_validators/profile_map_keys.test.ts
Avoid crashing in the change validator when the structure is not as expected.
---
* Omit profiles with invalid structure instead of failing deploy.
---
None
=> SAAS-2785 Avoid failing deploy on invalid profile map structure

packages/core/src/core/restore.ts, packages/core/test/core/restore.test.ts
_fixed restore create multiple remove changes for object with multiple path hints_
---
When an element exists in the state but not in the workspace, a remove change is created by restore for the element. If the element has multiple entries in the path index, the split change by path hint method would have generated multiple remove changes. When identical remove changes are applied to the update nacl files bad things can happen. (In this bug case, the field was removed multiple time which caused the buffer manipulation to create a broken nack)
---
_Fixed restore can create bad nacls_
---
_NA_
=> fixed restore create multiple remove changes for object with multiple path hints (SALTO-1532)

packages/workspace/src/workspace/elements_source.ts, packages/workspace/src/workspace/nacl_files/elements_cache.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/workspace.test.ts
_fixed salto creates wrong plan for removal changes_
---
_When a element is completely removed from the nacls, it should be completely removed from the workspace cache even if it has hidden parts which were not removed (since we consider such a removal as a signal that the entire element needs to be removed. There was a bug in the code, which ignored that condition when the state cache was invalid. This PR fixes this._
---
Fixed removing an object which was modified via a deploy result in wrong deployment plan.
---
_NA_
=> fixed salto creates wrong plan for removal changes (SALTO-1511)

packages/salesforce-adapter/src/filters/convert_maps.ts, packages/salesforce-adapter/test/filters/convert_maps.test.ts, packages/salesforce-adapter/test/utils.ts
Mark fields used as map keys in profile subtypes as `_required = true` - if they do not exist, deploying the profile will fail when the maps are converted back before deploy.
---
* Marking a few fields in types related to profiles and business hours as `_required=true`.
---
A `_required=true` annotation was added under the following salesforce fields:
* `BusinessHoursEntry.name`
* `ProfileApexClassAccess.apexClass`
* `ProfileApexPageAccess.apexPage`
* `ProfileApplicationVisibility.application`
* `ProfileCategoryGroupVisibility.dataCategoryGroup`
* `ProfileCustomMetadataTypeAccess.name`
* `ProfileCustomPermissions.name`
* `ProfileCustomSettingAccess.name`
* `ProfileExternalDataSourceAccess.externalDataSource` …
=> SAAS-2785 Mark map key fields as required

packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/filters/custom_objects.ts, packages/salesforce-adapter/test/filters/custom_objects.test.ts
added a parent relation to LightningPage that has a source object type and changed their path
---
LightningPage will now have parent relation to the CustomObject
=> Salto 1460 - LightningPage should have parent relation to the CustomObject

packages/netsuite-adapter/src/change_validators/safe_deploy.ts, packages/netsuite-adapter/test/change_validators/safe_deploy.test.ts
Include data instances in safe deploy change validator, in order to warn the user if an instance was changed in the service since the last fetch.
---
originally we only supported custom types and fileCabinet types.
---
Netsuite Adapter: When attempting to deploy a data instance which has changed in the service since the last fetch, a warning will be shown (previously supported only custom types and file cabinet types).
---
None
=> SALTO-1531: add data instance support in safe deploy change validator in Netsuite

packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/filters/translation_converter.ts, packages/netsuite-adapter/src/transformer.ts, packages/netsuite-adapter/test/filters/translation_converter.test.ts
Fixed validation error on the name value in translationcollection, workbook, and dataset types
---
Bugfixes:
Fixed validation error of values that contain '#text' in them
---
new "translate fields" will be added to some of the types
Values of the form 
```
name = {
'#text' = 'value'
translate = 'T'
}
```
will be changed to
```
name = 'value'
nameTranslate = true
```
(This change will be omitted from the tracker)
=> SALTO-1192: Fixed validation errors in workbook and translationcollection

packages/persistent-pool/package.json, packages/persistent-pool/src/lib/renewed_lease.ts, packages/persistent-pool/test/lib/renewed_lease.test.ts, packages/persistent-pool/tsconfig.json
_Ignore InstanceNotLeasedError on renew added to persistent-pool_
---
_Meant mainly for SaaS UI e2e_
---
=> SALTO-1562 - Ignore InstanceNotLeasedError on renew added to persistent-pool

packages/salesforce-adapter/src/transformers/reference_mapping.ts
added a reference to flowName in subflows field of Flow
added a reference to field in outputAssignments field of FlowRecordLookup
---
subflows flowName and  outputAssignments field  will now contain reference
=> Salto 1535 - Add explicit references in Flow

eslintrc.js, packages/netsuite-adapter/src/config.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/salesforce-adapter/test/deprecated_config.test.ts
Replaced eslint rule with its matched typescript-eslint version
---
None
---
None
=> Replaced no-unused-expressions with typescript-eslint version

packages/netsuite-adapter/src/constants.ts, packages/netsuite-adapter/src/filters/instance_references.ts, packages/netsuite-adapter/test/filters/instance_references.test.ts
Please see info in the ticket (https://salto-io.atlassian.net/browse/SALTO-1558)
---
Netsuite Adapter: Identify NetSuite references that state the explicit referenced type, e.g. CustomSegment references.
=> SALTO-1558: Netsuite: References to CustomSegment are not identified by Salto

packages/netsuite-adapter/config_doc.md, packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/adapter_creator.ts, packages/netsuite-adapter/src/change_validators/immutable_changes.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/src/config.ts, packages/netsuite-adapter/src/constants.ts, packages/netsuite-adapter/src/filters/account_specific_values.ts, packages/netsuite-adapter/src/group_changes.ts, packages/netsuite-adapter/src/transformer.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/adapter_creator.test.ts, packages/netsuite-adapter/test/change_validators/immutable_changes.test.ts, packages/netsuite-adapter/test/client/sdf_client.test.ts, packages/netsuite-adapter/test/filters/account_specific_value.test.ts, packages/netsuite-adapter/test/group_changes.test.ts
Add support for fetching and deploying instances from SuiteApps installed on the account
---
For fetching the instances, I pass `appid` to the `object:import` command
For deploying, I create a SuiteApp type sdf project and run `project:deploy`
---
Netsuite adapter now supports fetching and deploying instances (not locked) from SuiteApps installed in the account using the `client.installedSuiteApps` configuration option
Some types in NetSuite will have an additional `application_id` field after the next fetch
---
None
=> SALTO-1552: SDF client now support fetching instances of SuiteApps

packages/core/test/core/plan/plan_item.test.ts, packages/workspace/src/workspace/nacl_files/addition_wrapper.ts, packages/workspace/test/workspace/nacl_files/addition_wrapper.test.ts
This was a side-effect of another bug, but we should have details about the specific field that failed if we're already getting to this scenario.
---
None
---
None
=> SALTO-1550 throw more indicative error when field is missing

packages/adapter-api/src/change.ts, packages/core/src/core/fetch.ts, packages/core/test/core/fetch.test.ts
add audit information to FetchChange type in order to read them in saas.
---
the type AuditDetailedChange will be used in saas so its not redundent
---
---
=> SALTO-1224/nacl detailed change

packages/cli/src/workspace/workspace.ts, packages/cli/test/commands/fetch.test.ts, packages/cli/test/workspace/workspace.test.ts
_update workspace on fetch even if no changes were made_
---
This fix solves an issue in which the workspace update method was not invoked by the cli if no changes were fetched during the fetch. This has caused state corruption since the state is set in the `core` method, and failing to update the workspace cases the hashes to go out of sync. 
---
_NA_
---
_NA_
=> update workspace on fetch even if no changes were made (fix SALTO-1543)

packages/salesforce-adapter/src/change_validators/picklist_promote.ts, packages/salesforce-adapter/src/change_validators/picklist_standard_field.ts, packages/salesforce-adapter/src/filters/value_set.ts, packages/salesforce-adapter/test/change_validators/picklist_standard_field.test.ts
Fix  standard picklist change-validator that reports false-positive on errors.
Change includes referring to the correct value-set annotation (valueSetName instead of valueSet) and checking that the referred value set is indeed standard (standardValueSet).
---
_NA_
---
_NA_
=> SALTO-1508 standard picklist fix

packages/netsuite-adapter/e2e_test/adapter.test.ts
add e2e tests for safe deploy change validator.
---
Test description:
adding a new instance to the service, then run change validator on changes that should cause the safe deploy validator to throw warning (the validator does a three-way comparison)
---
None
---
None
=> SALTO-1389: Add E2E tests for safe deploy feature

packages/jira-adapter/src/adapter.ts, packages/netsuite-adapter/src/adapter.ts, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/client/jsforce.ts, packages/salesforce-adapter/test/adapter.crud.test.ts, packages/salesforce-adapter/test/connection.ts, packages/salesforce-adapter/test/mock_elements.ts, packages/workato-adapter/src/adapter.ts, packages/zuora-billing-adapter/src/adapter.ts
This changes the usage pattern of the filters runner such that it will not allow
filters to accidentally share context between preDeploy and onDeploy of different
deploy calls
---
The problematic scenario was where two (or more) concurrent `adapter.deploy` calls were made, this could lead to the same filter instance getting called with `preDeploy` for deploy A, then `preDeploy` for deploy B before returning to `onDeploy` of deploy A.
for stateful filters this caused an issue since they rely on their state in `onDeploy` to match what they saw in `preDeploy`.
Changing the usage pattern such that every `adapter.deploy` call creates a new set of filter instances resolves this issue
---
- Fixed an issue where the workspace state was not properly updated …
=> SALTO-1533: Avoid sharing filter context between deploy calls

packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/workspace.test.ts
When getting elements without hidden types, the workspace attempted to complete this from a multienv source that into which the load source were not applied, resulting in missing file changes.
This resulted in `ws.elements(false)` calls to ignore changes in static files (SALTO-2745)
---
---
_Fixed diff command ignores static files changes_
=> fixed elements without hidden elements to not return elements and tic files that were changed during the load (fix SAAS-2745)

docs/user_guide.md, packages/cli/src/commands/fetch.ts, packages/cli/src/commands/restore.ts
These modes remain in code but are not recommended, so we're removing them from the docs.
---
None
---
None
=> SALTO-1565 remove "override" and "isolated" modes from documentation

package.json
_Added no-hoist rule for rocks db deps_
---
_The lib was missing in the executable since it was hoisted instead of being placed inside the rocks db lib. Still need to investigate what triggered the hoisting in main._
---
_NA_
---
_NA_
=> added no-hoist rule for rocks db deps (fix SALTO-1574)

packages/cli/test/callbacks.test.ts, packages/cli/test/commands/fetch.test.ts, packages/cli/test/commands/restore.test.ts, packages/cli/test/formatter.test.ts, packages/cli/test/mocks.ts, packages/cli/test/workspace/workspace.test.ts, packages/core/src/api.ts, packages/core/src/core/fetch.ts, packages/core/test/api.test.ts
This reverts commit 9f6de667ccf26f8ebf6e90a340bd668c0618c864.
revert changes in last last pr about making audit information mandatory
---
---
---
=> Revert "SALTO:1224/nacl detailed change (#2372)"

packages/core/src/local-workspace/remote_map.ts, packages/dag/src/nodemap.ts
_add log when creating rocksdb if not exist_
---
In addition, remove unneeded `get` method on the graph
=> add log when creating rocksdb if not exist

packages/adapter-api/src/change.ts, packages/core/src/core/fetch.ts, packages/core/test/core/fetch.test.ts, packages/salesforce-adapter/config_doc.md, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/fetch.ts, packages/salesforce-adapter/src/filters/author_information.ts, packages/salesforce-adapter/src/transformers/transformer.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/adapter.discover.test.ts, packages/salesforce-adapter/test/filters/author_information.test.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts
renaming all of audit information changes to author information after a discussion about naming
Implementing author information behind FetchChangeMetadata to support future metadata information on fetch changes
---
---
The optional flag auditInformation has been renamed to authorInformation
Reminder - This his feature is true by default but can be turned off by adding
```
optionalFeatures = {
authorInformation = true
// formerly auditInformation = true 
}
```
to each adapter configuration Nacl file inside the fetch scope.
---
=> SALTO:1224/rename audit information

packages/salesforce-adapter/src/transformers/reference_mapping.ts
added Reference to cpq fields : 
errorDisplayField under ValidationRule
picklist under RecordTypePicklistValue
page under WebLink
---
on Salesforce adapter the following fields will be converted to a Reference expressions:
ValidationRule.errorDisplayField, RecordTypePicklistValue.picklist, WebLink.page.
=> SALTO-925 - CPQ mapping references 

packages/cli/src/commands/init.ts, packages/workspace/src/workspace/nacl_files/addition_wrapper.ts
- The code in addition wrapper would handle a case where a full field was added but the exception was thrown before the code that handled that case
- Also added a full error log when init fails (unrelated)
---
- Fixed issue where fetch in isolated mode would fail in specific scenarios
---
_None_
=> SALTO-1580: Avoid throwing exception in a valid case when routing changes

packages/cli/src/callbacks.ts, packages/cli/src/formatter.ts, packages/cli/test/callbacks.test.ts, packages/cli/test/commands/fetch.test.ts, packages/cli/test/commands/restore.test.ts, packages/cli/test/formatter.test.ts, packages/cli/test/mocks.ts, packages/cli/test/workspace/workspace.test.ts, packages/core/src/api.ts, packages/core/src/core/fetch.ts, packages/core/test/api.test.ts, packages/core/test/core/fetch.test.ts, packages/lowerdash/src/collections/tree_map.ts, packages/lowerdash/test/collections/tree_map.test.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts
This change allows the fetch conflict code to detect a conflict between one service change
and multiple pending changes (or vice-versa), grouping them into a single fetch change.
---
This can happen for example when a field is removed in the nacl and has several annotations change in the service - the conflict in this case is between the single removal change of the entire field, and multiple annotation changes.
The same can happen in the other direction, when there are multiple annotation changes in the nacl but the field is deleted in the service.
---
Core
- Fixed fetch conflict detection code issue that would cause invalid nacls to appear after fetch in case of conflicting changes
---
_None_
=> SALTO-1364: Allow fetch conflict logic to group related conflicts

packages/salesforce-adapter/config_doc.md, packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/adapter_creator.ts, packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/custom_object_instances_deploy.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/client.ts, packages/salesforce-adapter/test/custom_object_instances_deploy.test.ts
Add retry mechanism to custom objects deploy flow. supports custom retry options via config to customise max-retries, delay between each retry and which salesforce error messages are retryable.
---
_NA_
---
_NA_
=> WIP - Salto-1455 cpq deploy retries

packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts, packages/netsuite-adapter/src/client/suiteapp_client/types.ts, packages/netsuite-adapter/src/suiteapp_file_cabinet.ts, packages/netsuite-adapter/src/transformer.ts, packages/netsuite-adapter/src/types/file_cabinet_types.ts, packages/netsuite-adapter/test/suiteapp_file_cabinet.test.ts
Some files in the file cabinet are not files that were uploaded to the account but links to URLs outside of Netsuite.
This PR changed those file instances to not contain `content` value and contain a `link` value instead
I will remove this changed from the tracker in a SaaS PR
---
Files in the file cabinet that are links will no longer have a "content" value but will have a "link" value to the linked URL
---
None
=> SALTO-1237: added link value to files in the file cabinet

packages/adapter-components/src/client/index.ts, packages/adapter-components/src/client/pagination.ts, packages/adapter-components/src/elements/ducktype/transformer.ts, packages/adapter-components/src/elements/swagger/instance_elements.ts, packages/adapter-components/test/client/pagination.test.ts, packages/adapter-components/test/elements/ducktype/transformer.test.ts, packages/adapter-components/test/elements/swagger/instance_elements.test.ts, packages/jira-adapter/test/client/pagination.test.ts, packages/workato-adapter/src/client/pagination.ts, packages/workato-adapter/test/client/pagination.test.ts, packages/zuora-billing-adapter/src/client/pagination.ts
Stop attempting to go to the next page if the current page has empty results. 
---
This required moving the entry-extraction logic into the pagination logic (which I think is a good thing).
---
None
---
None
=> SALTO-1584 stop pagination on empty page

packages/core/src/core/fetch.ts, packages/core/test/core/fetch.test.ts
_new instances do not add up on non first fetch if their type is also being added_
---
- the issue introduced in https://github.com/salto-io/salto/pull/2374
- please add the release note only if it existed in the previous version
---
fixed a bug that caused new instances to not be fetched after a type is removed from the skip list
=> SALTO-1583: new instances are not added on second first fetch if their type is also added

packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/multi_env/multi_env_source.test.ts
_changed workspace to deserialize deleted static files as MissingStaticFile_
---
_The fallback for a missing static file in the workspace deserializer was to return the original static file object instead of the lazystaticfile. This cause deletion of static files to be ignored. This change accounts for such cases._
---
_Fixed static files deletions are ignored in a deploy_
---
_NA_
=> changed workspace to deserialize deleted static files as MissingStaticFile (Fix Salto-1572)

packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/filters/references_by_self_link.ts, packages/jira-adapter/test/filters/references_by_self_link.test.ts, packages/jira-adapter/test/mock_elements.ts, packages/jira-adapter/test/utils.ts, packages/lowerdash/src/multi_index.ts
Add filter that creates references for all instances in JIRA that reference each other using a "self" link
---
See the tests for an example of what these self links look like in the service
Some examples can also be found in the example JIRA workspace [here](https://github.com/salto-io/adapter-sample-jira-workspace/blob/main/jira/Records/Board/Engineering.nacl#L38-L45)
---
_None_ (JIRA adapter is not officially released yet)
---
Technically this would change any JIRA workspace by creating a bunch of references, but since the JIRA adapter is not officially released this should not matter as there should be no maintained JIRA workspaces
=> SALTO-1319: jira adapter - add references for values with self links

packages/core/package.json, yarn.lock
_upgrade rocksdb version_
---
Added validation check that throws exceptions if the connection is closed and we are trying to use it (the current situation is seg fault)
---
_None_
---
=> upgrade rocksdb version

packages/cli/src/commands/restore.ts, packages/cli/src/formatter.ts, packages/cli/src/prompts.ts, packages/cli/test/commands/restore.test.ts, packages/cli/test/mocks.ts
Salto restore does not restore static resources, hence a suitable message has been added to the cli help and when running restore. The last one also prints the changed static files.
=> SALTO-1434 - Add a warning message for unrestored static files

packages/adapter-api/src/authentication_types.ts, packages/cli/e2e_test/helpers/salesforce.ts, packages/cli/src/callbacks.ts, packages/cli/src/cli_oauth_authenticator.ts, packages/cli/src/commands/service.ts, packages/cli/test/cli_oauth_authenticator.test.ts, packages/cli/test/commands/service.test.ts, packages/cli/test/mocks.ts, packages/salesforce-adapter/src/adapter_creator.ts, packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/adapter.creator.test.ts, packages/salesforce-adapter/test/client.test.ts
This is needed because access tokens only last for ~2 days
---
OSS oauth will now require consumer secret as well as consumer id (from salesforce connected app). Apps already configured through oauth will need to be reconfigured.
---
No changes
=> Do salesforce oauth with refresh tokens

packages/netsuite-adapter/e2e_test/adapter.test.ts
Add the static-resources use-case to the NS E2E tests (put the previous tests under the `on custom type instances` describe).
---
None
---
None
=> SALTO-1389: Add e2e tests for static resources for safe deploy change validator

packages/workato-adapter/src/config.ts, packages/workato-adapter/test/adapter.test.ts
API endpoint names are not unique - but the path they define is.
Keeping the name as part of the id as well to make the element easier to find (we can change that when we add aliases).
---
Workato adapter:
* Fix id definiton for API endpoints, to avoid omitting elements when multiple endpoints use the same name.
---
None (won't impact existing workspaces)
=> SALTO-1601 fix workato id uniqueness for api endpoints

docs/user_guide.md, packages/cli/src/commands/element.ts
Improved the documentation and CLI help for element move-to-common and move-to-envs to clearly indicate source and destination configurations.
---
Better documentation for element move-to-common and move-to-envs commands.
=> Clarify move-to-common and move-to-envs docs

packages/workspace/src/merger/index.ts
Changed merge errors log level from debug to warning to make it easier to spot on datadog
---
None
---
None
=> Change merge errors log level

packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts, packages/netsuite-adapter/test/client/soap_client.test.ts
Added retries to the SuiteApp Soap operation
---
We saw when fetching from Varonis account the following error https://salto-io.atlassian.net/browse/SAAS-3034 . I think it comes from the SuiteApp Soap operation so I added a retry
---
Bugfix: 
Added retry for soap requests operations for connection errors
---
None
=> SAAS-3034: added retries to suiteapp soap requests

docs/user_guide.md
Updated user-guide to remove hubspot and add jira and stripe
Also updated links to point to main instead of master
---
None
---
None
=> SALTO-1608 update supported bizapps in user-guide

packages/cli/src/commands/fetch.ts, packages/cli/test/commands/fetch.test.ts, packages/core/src/api.ts, packages/core/src/core/fetch.ts, packages/core/test/api.test.ts, packages/core/test/common/workspace.ts, packages/core/test/core/fetch.test.ts, packages/workspace/src/workspace/path_index.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/path_index.test.ts
_Added ability to fetch from another workspace to the cli_
This PR includes:
1. Adding a core functionality to fetch from another workspace
2. Adding an argument to the fetch command that enables it to use the new function using a workspace
Future SaaS implementation will work in a similar way with a workspace that uses remote maps utilizing the existing wslc API
---
Still need to add all of the tests, but figured I'll create this PR for early review. Tested manually for the following scenarios:
1. Simple fetch from another workspace (with all types of changes)
2. Iterative fetches after fetching the source workspace to detect changes
3. Both of the above but from the source workspace non active env
4. Both of the above but the source workspace has errors
5. Missing services in the source …
=> Added ability to fetch from another workspace to the cli

packages/core/package.json, yarn.lock
_add arm64 rocksdb prebuilds_
---
_Added prebuilds for arm64 - needed inorder to run salto in dev mode (when you don't use the binary)_
---
=> add arm64 rocksdb prebuilds

packages/zuora-billing-adapter/src/adapter.ts, packages/zuora-billing-adapter/src/config.ts, packages/zuora-billing-adapter/test/adapter.test.ts, packages/zuora-billing-adapter/test/config.test.ts
Fix id for `Settings_Gateway` to use the gateway name + add a change suggestion to fix the system config.
---
Zuora-Billing adapter:
* Use indicative id for Payment Gateways
---
Zuora-Billing:
* A few changes related to `Settings_Gateway` type and instances
=> SALTO-1658 Fix Zuora settings gateway id fields

packages/adapter-components/src/elements/swagger/type_elements/element_generator.ts, packages/adapter-components/test/elements/swagger/petstore_openapi.v3.json, packages/adapter-components/test/elements/swagger/petstore_openapi.v3.yaml, packages/adapter-components/test/elements/swagger/petstore_swagger.v2.json, packages/adapter-components/test/elements/swagger/petstore_swagger.v2.yaml, packages/adapter-components/test/elements/swagger/type_elements.test.ts
Fix issue where if the swagger had a reference to a list instead of a list of references, we would create an intermediate object with an `items` field even in cases where we shouldn't. This impacted a few Zuora-Settings fields that had an unnecessary reference to a list of strings
---
Zuora-Billing adapter:
* Fix incorrect type for `cards` fields for Payment Gateways
---
Zuora-Billing:
* A few changes related to `Settings_Gateway` type and instances
=> SALTO-1658 Fix Zuora settings payment gateway cards fields

packages/salesforce-adapter/src/types.ts
Excluding Layout (CollaborationGroup-Group Layout) that causes additions & removals noises in SalesForce adapter.
---
- Added CollaborationGroup-Group Layout to default exclude list for new workspaces
---
_None_
=> SALTO-1635 - Added layout to exclude list.

packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/utils.test.ts
Handle the case where a field's type is an object or array, while the instance value is a string (or string array).
---
Adding this as it was recently the cause of some invalid instance values (due to an incorrect type), there may be some other edge cases that can occur when types are inconsistent.
---
Core:
* Fix issue where if an instance had a nested string value while the field type expected an object, the string would be deconstructed in the nacl.
---
None (already covered in https://github.com/salto-io/salto/pull/2451)
=> SALTO-1658 Handle type inconsistencies in transformValues

packages/core/package.json, yarn.lock
_Upgrade RocksDB version to support backup_
---
_Upgrade RocksDB version to support backup for the SaaS_
Relates to https://salto-io.atlassian.net/browse/SALTO-1606
---
None
=> upgrade rocksdb version to support backup

packages/salesforce-adapter/src/filters/utils.ts
Reduce severity when silently handling errors from Salesforce filters marked as "optional".
---
None
---
None
=> SALTO-1664 reduce log severity

packages/adapter-api/package.json, packages/adapter-api/src/elements.ts, packages/adapter-api/test/elements.test.ts, packages/adapter-api/tsconfig.json
This PR fixes the load workspace crashing for some cases of syntax errors in the workspace
---
The issue is happening when for example I have the type
```
type adapter.someType {
annotations {
}
string internalId {
}
}
```
and I create a syntax error with the type, for example removing the first {
```
type adapter.someType
annotations {
}
string internalId {
}
}
```
This will cause us to parse the 
```
string internalId {
}
```
as a top level type, which will therefore have the id `string._config.instance.internalId`
When we try to get the type of that instance we will get an error since the id `string._config` returns the primitve value of string and we expect an `ObjectType`
---
Core:
- Fixed an issue with the workspace failing to load for some cases of syntax errors …
=> SAAS-3250: fixed load workspace failure in some cases of syntax errors

packages/salesforce-adapter/src/transformers/reference_mapping.ts, packages/salesforce-adapter/test/transformers/transformer.test.ts
When attempting to serialize a reference that we expected to be an element, fallback to serializing the current value (even if there is a rule that expects it to be an element).
---
Note that this means that unresolved references will be silently replaced with the "unresolved reference" placeholder (which is expected to fail downstream).
~Still missing a test - will add before merging.~
---
* Fix an error when attempting to deploy custom object instances with unresolved references
---
None
=> SALTO-1665 Change fallback behavior for resolving non-element references

packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/test/client/sdf_client.test.ts
Increased the number of retries for signle object in SDF client
---
None
---
None
=> SAAS-3128: added more retries for single object in sdf client

packages/netsuite-adapter/src/filters/instance_references.ts, packages/netsuite-adapter/test/filters/instance_references.test.ts
We encountered a situation where a value is composed of both string value and a reference.
1. A filter was added that split it to 2 fields and compose it back upon deploy.
2. Added generated dependency containing the references element while keeping the value as is.
---
* netsuite-adapter
---
A one time notification will appear due to the addition of _generaeted_dependencies annotation.
=> SALTO-1563 Netsuite: Identify references that are only part of the field

packages/cli/src/formatter.ts, packages/cli/test/formatter.test.ts, packages/cli/test/mocks.ts
following the ticket [SALTO-979](https://salto-io.atlassian.net/browse/SALTO-979), I added a separation between different objects in the detailed plan for deploy.
---
CLI: improve the display for a list of objects in the deploy's detailed plan
---
=> SALTO-979 Fix detailed plan for nested objects in CLI

packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
When a cache invalidation takes place, the multi env source will attempt to recover the files while using the wrong static file source. If the files are not there - missing file error will be created.
The following PR is a hotfix for this issue which does not address the real root cause (wrong multi env source is used during cache invalidation in the workspace). The root cause will be fixed in another PR later on today.  (And this PR will be reverted) 
---
Release Notes:
- Fixed issue where static files would be loaded incorrectly in workspaces with multiple environments, causing missing static files and / or incorrect deploy plans
=> SALTO-1676: hotfix for missing static file error

packages/zendesk-support-adapter/src/adapter.ts, packages/zendesk-support-adapter/src/filters/unordered_lists.ts, packages/zendesk-support-adapter/test/filters/unordered_lists.test.ts
The variants' order may change when creating a sandbox.
---
This should eventually be supported as part of the simple-adapter config, but we need to see more cases first (this is the 2nd one after a couple of fields in Zuora that needed different sorting).
---
* Sort the dynamic content item variants to avoid unneeded differences between sandboxes.
---
* Changes in `dynamic_content_item` instances (under the `variants` field)
=> SALTO-1681 Sort Zendesk dynamic content item variants

packages/workspace/src/workspace/nacl_files/parsed_nacl_files_cache.ts, packages/workspace/test/workspace/nacl_files/parsed_nacl_files_cache.test.ts
_Added hash in mem cache invalidation in parsed nacl files cache_
---
_The `ParsedNaclFileCache` module expose a `getHash` function that returns a hash value based on the hashes of all of the cached files, and is used by the `naclFileSource` module to create its own hash. In order to prevent unneeded calculations, that hash value is cached in memory. However, the `deleteAll` and `putAll` methods do not invalidate that cash when invoked, leading for the `getHash` method to return outdated value.r_
---
_Core_:
- fixed issue that would cause unneeded cache invalidation and lead to slow loading times
---
_NA_
=> SALTO-1694: added hash invalidation on putAll and deleteAll of parsed nacl files cache

packages/jira-adapter/src/config.ts
- The FieldConfiguration type was renamed to FieldConfigurationDetails in swagger
- Added components as a field on project
- Fixed columns field type in FilterDetails
---
The internal name of the type changed in swagger and the config has to be updated accordingly
---
Jira Adapter:
Bug fixes:
- Fixed issue with FieldConfiguration failing to fetch
New features:
- Now fetching components under projects  
---
Jira adapter:
- Default adapter configuration has changed, please run `salto workspace clean -ncrsg` to reset the configuration in your workspace
=> SALTO-1629: Fixed field configuration request type

packages/cli/src/commands/element.ts, packages/workspace/index.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/common/nacl_file_source.ts, packages/workspace/test/utils.ts, packages/workspace/test/workspace/multi_env/multi_env_source.test.ts, packages/workspace/test/workspace/multi_env/routers.test.ts, packages/workspace/test/workspace/workspace.test.ts
_Modify the workspace structure to hold a single multienv source instead of a multi env source for each environment_
---
Until this PR, the workspace contained a multienv source for each existing environment, and a hidden assumption was made that operations that only involves one env will be done on a multienv source in which that env is the primary source. To make things even more confusing, some of the multienv source function did expose the ability to access data (or modify) the non primary nacl files sources while other did not. This has caused SALTO-1676 since the `getStaticFiles` method was invoked on the wrong element source.
To fix this, and to prevent similar mistakes from happening, the workspace now holds only a single multi env source. To do that, the following steps were …
=> SALTO-1676: Single multienv source

packages/adapter-components/src/elements/ducktype/standalone_field_extractor.ts, packages/adapter-components/test/elements/ducktype/standalone_field_extractor.test.ts, packages/zendesk-support-adapter/test/adapter.test.ts
We have an option in simple adapters to mark fields as "standalone", which means they should be converted to separate instances and referenced from the instance that originally contained them. We do this for swagger adapters and for ducktype adapters - for the ducktype variant there were a couple of issues in cases when the field being extracted was a list:
1. The generated type was the inner type instead of the list (this on its own does not cause issues besides the inconsistency, since we had to handle this gracefully due to needs in the Salesforce adapter).
2. We would sometimes re-generate the nested types when we didn't need to. This could cause us in some cases to have the same type definition twice, which can cause it to be omitted from the nacls.
Both should be fixed here.
--- …
=> SALTO-1689 fix simple adapter extraction of standalone fields inside lists

packages/workspace/src/workspace/element_selector.ts, packages/workspace/test/element_selector.test.ts
Until now if a user would set a selector with pipes, e.g. `salesforce.Lead|Task` it would match also `LeadConvertSettings`.
---
Core: Support element selectors with multiple values separated with pipes ('|')
---
None
=> SAAS-2861: Support element selectors with multiple values separated with pipes ('|')

packages/core/src/local-workspace/remote_map.ts, packages/core/test/workspace/local/remote_map.test.ts
Changed `clear` in remote map to change the persistent db only when flush is called
Before this PR, since clear did not happen on flush, flush after clear would return false (no changes were flushed) which cause an `elementsUpdate` in the SaaS to not be sent.
This caused errors in the UI in some cases to not disappear after fixed
---
None (I'm not await of an effect this has in the OSS)
---
None
=> SALTO-1703: changed remote map clear to change the persistent db only when flush is called

packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/filters/service_urls.ts, packages/netsuite-adapter/src/service_url/suiteapp_elements_url.ts, packages/netsuite-adapter/test/service_url/suiteapp_elements.test.ts
Add support in go-to-service for SuiteApp elements.
---
I replaced the serviceUrl filter order in adapter.ts as we need the internalId of elements in order to apply the go-to-service option.
---
Add go-to-service option for new types of instance elements in Netsuite
=> SALTO-1628: add support in go-to-service for SuiteApp instance elements

packages/jira-adapter/src/config.ts
---
see [this commit](https://github.com/salto-io/adapter-sample-jira-workspace/commit/6c1b546f908ecf6cf91eba02fea2cf3a596a5aa2) for the affect on an example workspace
---
Jira adapter
- Added issue type to default fetch configuration
---
_None_
=> SALTO-1712: add issue type details to default fetch config

packages/adapter-api/src/element_id.ts, packages/adapter-api/test/elements.test.ts, packages/cli/test/mocks.ts, packages/workspace/src/workspace/reference_indexes.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/reference_indexes.test.ts, packages/workspace/test/workspace/workspace.test.ts
Added `references` index to get the elements a certain element references and a `referencedBy` index to get all the elements that reference a certain element
---
Performance:
On NetSuite big account:
With the indexes first fetch took:
771.637 seconds
without the indexes:
764.718 seconds
without the indexes
---
None
---
None
=> SALTO-1702: added references and referencedBy indexes

packages/core/src/core/rename.ts, packages/core/test/api.test.ts, packages/core/test/common/elements.ts, packages/core/test/core/plan/plan.test.ts, packages/core/test/core/rename.test.ts
solving bug on SALTO-1476 - references to the source element weren't changed if they were inside the source element itself.
---
* core
bug fix - rename inner references on element rename
=> SALTO-1710 rename inner references on element rename

packages/salesforce-adapter/src/transformers/transformer.ts
The annotation on the picklist contains a list of values, the type should be a list as well
---
---
- Fixed annotation type under picklist field type
---
- The Salesforce picklist type definition will change the next time a fetch is done on a salesforce workspace
=> SALTO-1717: Change picklist value set annotation type to a list

packages/netsuite-adapter/e2e_test/adapter.test.ts, packages/netsuite-adapter/src/suiteapp_file_cabinet.ts, packages/netsuite-adapter/test/suiteapp_file_cabinet.test.ts
before this PR the e2e assumed that a folder with a path /images/innerFolder exists on the account. Fixed it to not have this assumption
In addition, fixed some minor bugs that made the error message less clear:
- There was a situation when we called deploy without any files
- When there was an error in the deployment, we would not return the errors of the invalid instances to deploy
---
Improved the error message when trying to create a file in a folder that does not exist
---
None
=> Fixed Netsuite e2e for NetSuite empty account

packages/adapter-api/src/element_id.ts, packages/adapter-api/test/elements.test.ts, packages/cli/test/mocks.ts, packages/workspace/src/workspace/reference_indexes.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/reference_indexes.test.ts, packages/workspace/test/workspace/workspace.test.ts
Improved references indexes performance
on Nitzan Env with profiles, it takes now 2 minutes (out of 30 minutes of the applying changes part and 40 minutes for the whole fetch)
No need to review the revert commit
---
None
---
None
=> SALTO-1702: improved references indexes performance

packages/jira-adapter/src/config.ts
It looks like fetching default values is supported for all custom types fields. Changed the config accordingly
---
None (Jira adapter is not officially deployed)
---
None
=> SALTO-1725: fixed default values config

packages/netsuite-adapter/src/change_validators/account_specific_values.ts, packages/netsuite-adapter/test/change_validators/account_specific_values.test.ts
Set a Warning change validation when creating an instance that is enabled but contain ACCOUNT_SPECIFIC_VALUE instead of ignoring this change.
=> SALTO-1270: Modify ChangeValidation severity to WARN when deploying instance with ACCOUNT_SPECIFIC_VALUE

packages/workspace/src/workspace/element_selector.ts, packages/workspace/test/element_selector.test.ts
Changed element selector `includeNested` to also include fields and attributes for type selectors
---
None (CLI does not use includeNested)
---
None
=> SALTO-1702: changed include nested to include fields and attributes for types

packages/salesforce-adapter/src/transformers/reference_mapping.ts
Extract part of the referenced fields and columns in reports and dashboards.
Note that not all are covered, because there are different formatting options, and in order to know we can safely serialize the reference back to its original form, our current mechanism requires there to be at most one valid serialization.
---
In the future, we can extend this by either adding the other variants under `_generated_dependencies`, or having a smarter serialization mechanism that follows the Salesforce rules for these specific types. But for now, I believe these should be safe and cover some common scenarios.
---
Salesforce adapter: Extend reference coverage for reports and dashboards
---
Additional references in Salesforce reports and dashboards.
=> SALTO-1758 extract standard-format references for fields and columns

packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/workspace.test.ts
Due to regression in `getElementIdsBySelectors` that caused him to ignore the env that was passed to it and always use the current env, clone and move to common would ignore deletion changes.
The bug was the `isFromSourceWithEnv` looked for the var `fromEnv` instead of `envName`
---
core:
- Fixed regression of clone and move-to-common ignoring deletion changes
---
None
=> SAAS-3586: fixed regression in clone/move-to-common for deletions

packages/zuora-billing-adapter/src/config.ts
Fix another field that is listed as string but its value is actually a number.
---
Zuora Billing:
* Fix field types that are inconsistent between the Zuora definition and actual value
---
None (currently not applied to existing workspaces - see SAAS-2783)
=> SALTO-1765 Fix type for additional field that is inconsistent with its swagger definition

packages/lang-server/src/token.ts, packages/lang-server/test/token.test.ts
bug fix , right click menu operations were not executed when the cursor was on the last char or when element was marked
---
https://salto-io.atlassian.net/browse/SAAS-1519
=> SAAS-1519 - When an element is marked, right click menu operations are not executed

packages/jira-adapter/src/config.ts
Convert Jira setting instances to singleton:
AttachmentSettings
Configuration
Permissions_permissions 
---
This change follows the new option to define instances as singleton types in swagger adapters.=
---
=> SALTO-1697 convert Jira setting instances to singleton

packages/jira-adapter/src/config.ts
Added Children information to Jira Schemes
---
Some Jira schemes lacked information about their children records. This information was in a different Mapping records, that linked them both. The mapping records were removed, and instead we include the relevant children infos under their parents.
---
Jira Adapter:
The following Schemes include the ids of their children:
* FieldConfigurationScheme
* IssueTypeScheme
* IssueTypeScreenScheme
---
_None_
=> SALTO-1698: Refactor item instances into their parents instances

packages/salesforce-adapter/jest.config.js, packages/salesforce-adapter/package.json, packages/salesforce-adapter/src/filters/custom_object_split.ts, packages/salesforce-adapter/test/filters/custom_object_split.test.ts
Custom fields for Salesforce custom objects will all be under the same file in the Objects directory.
---
Custom fields that came from installed packages for Salesforce custom objects were separated to a different file under the InstalledPackages directory. This created an unnecessary noise in the workspace, hence they're not separated anymore and instead will be under the same file.
---
- Custom fields will all persist under the same file (depending on the namespace).
- Will no longer create `nacls` for empty Annotations, StandardFields or CustomFields objects. 
---
_None_
=> SALTO 1642: Don't split custom fields from installed packages for SalesForce custom objects

packages/zuora-billing-adapter/src/config.ts
Convert Zuora singleton instances into settings in order to improve its presentation in workspace.
---
This ticket is done using the new singleton transformation flag.
I re-fetched Zuora workspace to check the instances has changed.
---
Improved presentation for instance elements with only one instance in Zuora.
=> SALTO-1683 Convert Zuora singleton instances into settings

packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/test/client.test.ts
We see this type of error is non transient and therefore if it happens
we assume it will always happen and we should skip whatever element caused it
---
---
- Avoid failure on fetch due to sf:INVALID_TYPE errors
---
_None_
=> SALTO-1759: Create config suggestion when salesforce returns sf:INVALID_TYPE

packages/cli/e2e_test/helpers/salesforce.ts, packages/cli/e2e_test/multi_env.test.ts, packages/cli/e2e_test/salto.test.ts, packages/salesforce-adapter/e2e_test/adapter.ts, packages/salesforce-adapter/e2e_test/setup.ts, packages/salesforce-adapter/test/mock_elements.ts
Change default in salesforce related e2e tests to purgeOnDelete=true
to avoid leaving junk in the recycle bin
---
Without purge on delete, when we delete a custom object or custom field they go to the recycle bin (and they still count towards the org's total custom objects / fields limit), we have reached a point where some accounts in our e2e credentials pool were hitting that limit
---
_None_
---
_None_
=> SALTO-1764: Enable purgeOnDelete for salesforce e2e tests

packages/workspace/src/workspace/element_selector.ts, packages/workspace/test/element_selector.test.ts
In the flow of element selectors we use ElemID.fromFullName. We don't validate that the element selector is a correct elemId and this causes us to crash in a non indicative way.
---
Core:
- More indicative errors when creating element selectors.
---
None.
=> SALTO-1772 - added element selector validation is correct elemID

packages/zendesk-support-adapter/src/adapter_creator.ts, packages/zendesk-support-adapter/src/auth.ts, packages/zendesk-support-adapter/test/adapter_creator.test.ts
clientSecret param isn't used in the implicit  OAuth grant flow that we use on Zendesk, so there's no reason to ask for it from the user.
---
Zendesk Support Adapter:
- remove clientSecret param on OAuth authentication mode
=> remove unused OAuth param in Zendesk - clientSecret

packages/adapter-components/src/references/field_references.ts, packages/adapter-components/src/references/index.ts, packages/adapter-components/src/references/reference_mapping.ts, packages/zendesk-support-adapter/src/filters/field_references.ts, packages/zuora-billing-adapter/src/adapter.ts, packages/zuora-billing-adapter/src/constants.ts, packages/zuora-billing-adapter/src/element_utils.ts, packages/zuora-billing-adapter/src/filters/field_references.ts, packages/zuora-billing-adapter/src/filters/finance_information_references.ts, packages/zuora-billing-adapter/src/filters/object_defs.ts, packages/zuora-billing-adapter/src/filters/object_references.ts, packages/zuora-billing-adapter/src/filters/workflow_and_task_references.ts, packages/zuora-billing-adapter/test/filters/field_references.test.ts, packages/zuora-billing-adapter/test/filters/finance_information_references.test.ts, packages/zuora-billing-adapter/test/filters/object_references.test.ts, packages/zuora-billing-adapter/test/filters/workflow_and_task_references.test.ts
Found and added more references in Zuara. 
Some references were replaced with the value itself, some were added to `_generated_dependencies` (if they were inside strings)
---
this is the second PR for this ticket, followed by [https://github.com/salto-io/salto/pull/2500](url)
---
* zuara-billing-adapter
Added references to objects and instances
---
* changed to references:
`zuora_billing.Settings_Notification.emailTemplateName`
`zuora_billing.ProductRatePlanType.productRatePlanCharges[...].uom`
`zuora_billing.ProductRatePlanType.productRatePlanCharges[...].taxCode`
`zuora_billing.ProductRatePlanType.productRatePlanCharges[...].discountClass`
`zuora_billing.ProductRatePlanType.productRatePlanCharges[...].productDisco …
=> SALTO-1660 Extend reference coverage in Zuora

packages/salesforce-adapter/config_doc.md
---
Text was not formatted as a proper markdown link like the other sections
---
_None_
---
_None_
=> Fix link in salesforce config documentation

packages/core/src/core/fetch.ts
…
_Added a log line when creating an empty fetch from due to mismatch error_
_NA_
---
_NA_
=> added a log line when creating an empty fetch from result due to error (SALTO-1802)

packages/adapter-utils/src/filter.ts, packages/adapter-utils/test/filter.test.ts, packages/lowerdash/src/collections/asynciterable.ts, packages/lowerdash/src/objects.ts, packages/lowerdash/test/collections/asynciterable.test.ts, packages/salesforce-adapter/test/filters/filters.test.ts
Added a deploy function to filter to allow deploying changes through filters for the simple adapters deployment 
---
None
---
None
=> SALTO-1715: added deploy function to filter

packages/adapter-components/src/references/field_references.ts, packages/adapter-components/src/references/index.ts, packages/adapter-components/src/references/reference_mapping.ts, packages/adapter-components/test/references/field_references.test.ts
Added `generateLookupFunc` for simple adapters to use to resolve references on deploy
---
None
---
None
=> SALTO-1715: added generateLookupFunc to simple adapter infra

packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/filters/authenticated_permission.ts, packages/jira-adapter/test/filters/authenticated_permission.test.ts
Replace `loggedin` value with `authenticated` in `SharePermission` value
When fetching we get the value `loggedin` as a type of permission but when deploying we need to deploy with the type `authenticated` for the same kind of permission so I changed on fetch the value of `loggedin` with `authenticated`
---
None
---
None
=> SATLO-1715: replaced loggedin with authenticated

packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
…
_Use cached hash value in nacl file source when the ignore file changes flag is set_
---
_The ignore file changes flow is designed to minimize rocks db interactions in order to expedite the workspace loading time. It should be used in cases in which using the already cached values is good enough.
In the previous flow, the pre change hash that is used by the nacl file source was calculated by concating and hashing the hash values of all of the workspace files. However - since we *ignore* these changes - using the cached hash value is enough._
---
_Improved workspace loading time when the ignore nacl file changes flag is set_
---
_NA_
=> use cached hash value in nacl file source when the ignore file changes flag is set (SALTO-1807)

packages/netsuite-adapter/src/filters/instance_references.ts, packages/netsuite-adapter/test/filters/instance_references.test.ts
Identify references with `appid` and `bundleid` fields, and add their salto reference to `_generated_dependencies`.
---
See attached JIRA bug for context.
---
NetSuite references in the form of `[appid=foo.bar, scriptid=someid]` or `[bundleid=123, scriptid=someid]` will now add a `_generated_dependencies` section when fetching. This helps find references and dependencies better.
---
NetSuite references in the form of `[appid=foo.bar, scriptid=someid]` or `[bundleid=123, scriptid=someid]` will now add a `_generated_dependencies` section when fetching.
=> SALTO-1559: NetSuite: Identify references from bundles and SuiteApps

packages/cli/test/mocks.ts, packages/core/src/local-workspace/adapters_config.ts, packages/core/src/local-workspace/dir_store.ts, packages/core/src/local-workspace/workspace.ts, packages/core/test/common/nacl_file_source.ts, packages/core/test/workspace/local/adapters_config.test.ts, packages/core/test/workspace/local/directory_store.test.ts, packages/lang-server/test/workspace.ts, packages/workspace/src/workspace/dir_store.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/static_files/common.ts, packages/workspace/src/workspace/static_files/source.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/common/nacl_file_source.ts, packages/workspace/test/common/nacl_file_store.ts, packages/workspace/test/utils.ts, packages/workspace/test/workspace/multi_env/multi_env_source.test.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.state.test.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts, packages/workspace/test/workspace/static_files/source.test.ts
_Exposes a function that will tell which env a specific path belongs to_
---
---
_Exposed a method that, provided with a path, returns which environments contains the file, and if it is a static file_
---
_NA._
=> expose get nacl file envs (SALTO-1768)

packages/adapter-components/package.json, packages/adapter-components/src/deployment/dependency/index.ts, packages/adapter-components/src/deployment/dependency/remove_standalone_field_dependency.ts, packages/adapter-components/test/deployment/dependency/remove_standalone_field_dependency.test.ts, packages/zendesk-support-adapter/src/adapter.ts
_Add dependency changer that removes the edge in the plan graph from the parent to the child in order to support deploy on standalone fields_
---
---
_None_
---
=> SALTO-1770: add dependency change for standalone fields

packages/adapter-components/src/elements/swagger/deployment/annotations.ts, packages/adapter-components/test/elements/swagger/deployment/annotations.test.ts
Added support for inner types in `addDeploymentAnnotations`
---
None
---
None
=> SALTO-1715: addDeploymentAnnotations now supports inner types

packages/jira-adapter/jest.config.js, packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/config.ts, packages/jira-adapter/src/filters/hidden_value_in_lists.ts, packages/jira-adapter/system_config_doc.md, packages/jira-adapter/test/filters/hidden_value_in_lists.test.ts
Removed most ids from Jira NaCls
The change in the workspace after this PR can be found [here](https://github.com/salto-io/alon-jira-workspace/commit/363c3482a235f124cdc1e708a5e9e9824597c3af)
In this PR I:
- Made the ids hidden whenever possible
- Removed the ids if I couldn't make them hidden but their instance was anyway not deployable
- Extract the tabs field in `Screen` to new instances so I can make its id hidden
- Added a filter to remove hidden values inside the array in case I missed an id that I made hidden and can be inside the array so it won't fail the whole fetch
This still won't cover:
- Workflow - which will require some custom logic to deal with there ids
- Field - Still needs to decide what the way to remove its ids
- Some more places that should become referecens
--- …
=> SALTO-1779: removed most ids from jira nacls

packages/dummy-adapter/src/generator.ts
…
_change dummy adapter to avoid creating the restriction annotation_
---
_The dummy adapters creates the restriction annotation, and proceeds to create the values without semantic understanding of the restriction leading to validation errors._
---
_NA_
---
_NA_
=> (SALTO-1823) change dummy adapter to avoid creating the restriction annotation

packages/adapter-components/src/config/request.ts, packages/adapter-components/src/elements/swagger/instance_elements.ts, packages/adapter-components/test/config/request.test.ts, packages/adapter-components/test/elements/swagger/instance_elements.test.ts
1. When a field is not a list type but the value is an array (and vice versa), keep the value under the field with a type warning instead of the current behavior of moving it to `additionalProperties`
2. Add a `isSingle` flag for `recurseInto` to allow having a non-list `recurseInto` value
3. Add missing type definitions for `recurseInto`
---
These two together should help avoid some custom logic needed for jira references.
---
None (infra changes)
---
None
=> SALTO-1822 SALTO-1789 Correctly support arrays without converting them to additional properties unneccessarily, allow isSingle for recurseInto

packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/filters/field_references.ts, packages/jira-adapter/src/references.ts, packages/jira-adapter/test/adapter.test.ts
Added `getLookupName` to resolve references using the rules we defined in Jira.
---
None
---
None
=> SALTO-1715: added getLookupName func for the Jira adapter

packages/stripe-adapter/src/config.ts, packages/stripe-adapter/system_config_doc.md
Omit/hide timestamp fields that get changed a lot
---
Stripe adapter:
* Omit some timestamps from types such as report types
---
* Values in `stripe.*.instance.*.updated`, and in `stripe.reporting_report_type.instance.*.data_available_start` and `stripe.reporting_report_type.instance.*.data_available_end` will be removed from the nacls
* Adding the annotations `stripe.reporting_report_type.field.data_available_start._hidden_value` and `stripe.reporting_report_type.field.data_available_end._hidden_value`
=> SALTO-1824 avoid noise from timestamp changes

packages/core/src/api.ts, packages/core/src/core/deploy.ts, packages/core/test/api.test.ts
This PR adds the "AppliedChange" data in the `deployResult` API.
This gives consumers of deploy API the ability to generate an accurate list of Changes that were successfully deployed \ failed.
Todo
---
Add 'appliedChanges' to 'DeployResult' API to allow consumers to assess requested changes \ deployed changes
---
None
=> SALTO-1815: Add applied changes result to deploy

packages/zuora-billing-adapter/src/config.ts, packages/zuora-billing-adapter/src/filters/unordered_lists.ts, packages/zuora-billing-adapter/test/filters/unordered_lists.test.ts
These lists of allowed/accepted cards change order between fetches, without any user-initiated change. Sorting them to avoid the noise.
Also avoid fetching a gateway response that only contains duplicate data from other types.
---
Zuora Billing adapter:
* Reduce noise between fetches of gateway instances that is caused by the allowed/accepted cards lists not having a consistent order
---
None (these fields' value changes on every fetch currently)
=> SALTO-1827 Zuora - sort card-related gateway fields to avoid noise between fetches

packages/workspace/src/serializer/elements.ts, packages/workspace/test/serializer/serializer.test.ts
Fixed a bug of circular dependency error on serializing (an example can be found [here](https://salto-io.atlassian.net/browse/SALTO-1828))
---
The issue was that in https://github.com/salto-io/salto/blob/main/packages/workspace/src/serializer/elements.ts#L188 we expect the replacer to run on every node of the element before passing to the `JSON.stringify`. However, when we return the value of the reference in https://github.com/salto-io/salto/blob/main/packages/workspace/src/serializer/elements.ts#L148 the replacer function won't run on `e.value` values which can create circular dependencies
---
Core:
- Fixed a bug of circular dependency error for some cases of NaCls with inner references
---
None
=> SALTO-1828: fixed circular dependency issue on serialize

packages/workspace/src/workspace/hidden_values.ts, packages/workspace/test/workspace/hidden_values.test.ts
Changed `mergeWithHidden` to not create parent object if it was deleted from the workspace element
---
None (I don't think it currently has an effect on users)
---
None
=> SALTO-1831: fixed hidden values inside objects

packages/adapter-utils/src/filter.ts, packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/filters/default_deploy.ts, packages/jira-adapter/src/filters/issue_type_schemas/issue_type_scheme.ts, packages/jira-adapter/test/adapter.test.ts
Added support for deploying `IssueTypeSchema`
---
- Changed `issueTypes` to `issueTypesIds` in `IssueTypeSchema` because this is the name that is expected on create
- Called the modification endpoints of  issueTypesIds on modification
---
None
---
None
=> SALTO-1715: issue type schema deploy

packages/adapter-components/src/config/shared.ts, packages/adapter-components/src/config/swagger.ts, packages/adapter-components/src/config/transformation.ts, packages/adapter-components/test/config/transformation.test.ts, packages/jira-adapter/src/config.ts, packages/stripe-adapter/src/config.ts, packages/workato-adapter/src/config.ts, packages/zendesk-support-adapter/src/config.ts, packages/zuora-billing-adapter/src/config.ts
Removed required annotation from  types in simple adapters so when overriding it partially we won't get warnings that that values are missing
---
None
---
None
=> Removed required annotations from adapter-component

packages/zendesk-support-adapter/src/config.ts, packages/zendesk-support-adapter/system_config_doc.md
Avoid hiding the id field by default, because that can cause merge conflicts for nested types that appear inside lists.
---
* Fix zendesk config that could cause invalid elements
---
Fix some zendesk types that had merge conflicts after the first fetch
=> SALTO-1866 do not hide ids by default

packages/workspace/src/parser/internal/native/lexer.ts, packages/workspace/test/parser/errors.test.ts, packages/workspace/test/parser/parse.test.ts
The regex used by lexer identified the end of a content token by looking a head until a closing char (`\r` `\n` `${` or a `"`) that is not proceeded by a `\` char. As a result, if any of them was preceded by an escaped `\\` was not identified as a closing char resulting an a parse error.
The fix is a better regex which consumes every char after a '\' 
---
_NA_
---
_Fixed parsing error when a forward slash is escaped before a quotation mark_
---
=> (SALTO-1862) fixed escape from forward slash before a closing quote creates a parser error

packages/adapter-api/src/change.ts, packages/netsuite-adapter/src/change_validators/custom_types_invalid_values.ts
Removed the deprecated `getChangeElement` and `getAllChangeElements`
---
---
API: Removed the deprecated `getChangeElement` and `getAllChangeElements`
---
=> SALTO-1854: Remove getChangeElement

packages/workspace/src/workspace/nacl_files/elements_cache.ts, packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/nacl_files/elements_cache.test.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
_ improved ws load concurrency_
---
_In order to reduce rocks db access in the ws load:
1. Avoid getting the hash value when ignore file changes is used (return undefined instead)
2. Avoid performing merge calculation if no changes were detected.
3. init the merger in a lazy fashion,
---
---
=> (SALTO-1853) improved ws load concurrency

packages/workspace/src/expressions.ts
in `resolveReferenceExpression`, when `resolveRoot = true`, `resolveElement` is called but `resolveRoot` wasn't passed into it. It should be passed.
---
None
---
None
=> SALTO-1832 pass 'resolveRoot' parameter to resolveElement 

packages/logging/jest.config.js, packages/logging/src/internal/namespace.ts, packages/logging/test/internal/namespace.test.ts
=> Revert "SALTO-1833: Retrieve normalized namespace for ts modules"

packages/jira-adapter/src/config.ts, packages/jira-adapter/src/references.ts
Made small config changes to the types IssueTypeScreenScheme, IssueTypeDetailsk PermissionScheme and ProjectCategory will be deployable
---
IssueTypeScreenScheme:
- Changed the field `items` to `issueTypeMappings`
IssueTypeDetails:
- Added field for `untranslatedName`
- Removed subtask field (not deployable and we already have `hierarchyLevel` that says the same thing)
PermissionScheme:
- Removed additional parameters from expand that includes data that already included in the `parameter` field
- Added field for user
ProjectCategory:
- added deploymentRequests config
---
---
None
=> SALTO-1778: Fixed deployment config for several types

packages/cli/src/commands/workspace.ts, packages/cli/test/commands/workspace.test.ts
Added a command for updating the workspace cache.
This only loads the workspace and flushes it
the actual updating is a side effect of the load and flush
---
The workspace clean command that used to expose this option does not anymore, adding as a separate command
---
CLI
- Added `salto workspace cache update` administrative command to allow updating the workspace cache
---
_None_
=> SALTO-1542: Added workspace cache update command

packages/cli/e2e_test/multi_env.test.ts, packages/cli/e2e_test/salto.test.ts
The cli e2e expects there to be static resources in one of the tests
but it does not create anything with a static resource, so in new accounts it fails
Added a test that adds an instance with a static resource and does not delete it until teardown
Also fixed issue where jest.each was not provided with parameters in the correct structure
---
~Did not test locally yet, what are the odds this works?~ edit: it didn't
---
_None_
---
_None_
=> Fix cli e2e failing on newly created accounts

packages/adapter-components/src/elements/swagger/deployment/annotations.ts
Because in Jira we look for the types in two different swaggers, we always get "not found in swagger" warning for the swagger the type is not in, which makes the log to be written for all the types.
---
None
---
None
=> SALTO-1715: removed 'not found in swagger' that appears for every type in Jira

packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/config.ts, packages/jira-adapter/src/filters/remove_self.ts, packages/jira-adapter/test/filters/remove_self.test.ts
Removed:
- self (after we use it to create references)
- viewUrl (URL to the relevant page in the UI)
- favouritedCount (number of people who starred the object in the UI)
- isFavourite (whether the current user starred the object in the UI)
- key (same value as id)
- searchUrl (link to the search page of a filter)
---
None
---
None
=> SALTO-1780: removed redundant values from the Jira instances

packages/salesforce-adapter/src/constants.ts, packages/salesforce-adapter/src/transformers/transformer.ts
The track history annotation exists on all fields of custom objects that have enableHistory = true.
Its type should be boolean.
When this type was not defined, deploying changes to the trackHistory value would not do anything
---
Note that when the annotation type did not exist, we would not include the annotation value in our request to salesforce, so the deploy would seem successful, but in fact nothing would be deployed.
Having the annotation type defined is sufficient to make the code deploy the annotation value, so this fixes the issue in deployment and not just the type issue.
---
- Fix issue with the `trackHistory` annotation not working when deployed
---
Salesforce Adapter workspaces:
- On the next fetch, all …
=> SALTO-1796: Add type for trackHistory annotation

.circleci/config.yml
The version we have been using has been deprecated and [is being removed tomorrow](https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions)
---
---
_None_
---
_None_
=> SALTO-1888: Update macos version on CI

packages/dummy-adapter/src/adapter_creator.ts, packages/dummy-adapter/src/generator.ts, packages/dummy-adapter/test/adapter_creator.test.ts
_added env flag to dummy adapter config_
---
_Exposed the SALTO_ENV flag which is used to modify the adapter output via the adapter config as well_
---
_NA_
---
_NA_
=> added env flag to dummy adapter config

packages/adapter-utils/src/change_validator.ts, packages/adapter-utils/test/change_validator.test.ts, packages/salesforce-adapter/config_doc.md, packages/salesforce-adapter/src/adapter_creator.ts, packages/salesforce-adapter/src/change_validator.ts, packages/salesforce-adapter/src/types.ts, packages/salesforce-adapter/test/change_validator.test.ts
Ideally this should be a core ability, but this is a first step towards that.
This adds a section to the salesforce adapter configuration that allows disabling a validator by name
---
Still need to add tests and documentation
---
- Added `validators` section in the configuration to allow disabling specific change validators
---
_None_
=> SALTO-1890: Add ability to disable specific change validators in salesforce

packages/jira-adapter/test/adapter.test.ts
Looks like we started making network calls due to a recent change to load swaggers before `generateTypes` ([here](https://github.com/salto-io/salto/pull/2527/files#diff-c0e6fe5ff7328c339f0fcaaad6e26e11196075822b41173debf3667cd0a83de3R92))
---
None
---
None
=> SALTO-1882 Mock missed swagger calls in jira unittests

packages/adapter-components/package.json, packages/adapter-components/src/client/http_client.ts, packages/adapter-components/src/elements/swagger/instance_elements.ts, packages/adapter-components/test/client/http_client.test.ts, packages/core/package.json, packages/jira-adapter/package.json, packages/netsuite-adapter/package.json, packages/stripe-adapter/package.json, packages/workato-adapter/package.json, packages/zendesk-support-adapter/package.json, packages/zuora-billing-adapter/package.json, yarn.lock
Fixed a bug where we would sometimes get ETIMEDOUT error when fetching from Jira which would cause some elements to not be returned from fetch
---
- It looks `axios-retry` covers `ETIMEDOUT` but there was a bug in our current axios package which would cause the axios-retry to not work at all. The bug was fixed in axios 0.21.3 (https://github.com/axios/axios/releases?q=21.3&expanded=true the interceptor thing) so I upgraded the package and it seems to work 
- Changed to throw an exception and fail the whole fetch if we still got ETIMEDOUT after the retries
---
None
---
None
=> SALTO-1864: fixed ETIMEDOUT error

packages/adapter-components/src/deployment/deployment.ts, packages/adapter-components/test/deployment/deployment.test.ts, packages/adapter-utils/src/utils.ts, packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/config.ts, packages/jira-adapter/src/filters/screen/fields.ts, packages/jira-adapter/src/filters/screen/screen.ts, packages/jira-adapter/src/filters/screen/screenable_tab.ts, packages/jira-adapter/src/reference_mapping.ts, packages/jira-adapter/test/adapter.test.ts, packages/jira-adapter/test/filters/screen/screen.test.ts, packages/jira-adapter/test/filters/screen/screenable_tab.test.ts
Added support for deploy screen and its tabs
Only the last commit is relevant
This PR is build on https://github.com/salto-io/salto/pull/2598
---
- Added support for deploying tabs order in screen
- Added support for deploying fields in screen tab
- Added support in urlParamsToFields to point to inner values
---
None
---
None
=> SALTO-1778-Support-screen-deployment

packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/filters/issue_type_screen_scheme.ts, packages/jira-adapter/test/filters/issue_type_screen_scheme.test.ts
Added support for deploying issue type screen scheme
Only last commit is relevant
This PR is build on https://github.com/salto-io/salto/pull/2598
---
None
---
None
=> SALTO-1778-Added-support-for-deploying-issue-type-screen-scheme

packages/stripe-adapter/test/adapter.test.ts
Stripe UTs parsed the actual swagger as part of the UTs which was slow and required internet.
---
_None_
---
_None_
=> SALTO-1882: Stripe UTs will no longer require internet access

packages/core/src/core/plan/filter.ts, packages/core/test/core/plan/filter.test.ts
Omit type/field/instance change from the deploy plan when its inner value has ChangeError
---
None
=> SALTO-1895: Omit base element changes from deploy plan when their inner value has ChangeError

packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/change_validators/field_configuration.ts, packages/jira-adapter/src/change_validators/index.ts, packages/jira-adapter/src/config.ts, packages/jira-adapter/src/filters/field_configuration.ts, packages/jira-adapter/src/filters/fields/constants.ts, packages/jira-adapter/src/filters/fields/context_options.ts, packages/jira-adapter/src/filters/fields/contexts.ts, packages/jira-adapter/src/filters/fields/default_values.ts, packages/jira-adapter/src/filters/fields/field_deployment_filter.ts, packages/jira-adapter/src/filters/fields/field_structure_filter.ts, packages/jira-adapter/src/filters/fields/field_type_references_filter.ts, packages/jira-adapter/src/filters/screen/screen.ts, packages/jira-adapter/src/filters/workflow/workflow.ts, packages/jira-adapter/src/reference_mapping.ts, packages/jira-adapter/src/utils.ts, packages/jira-adapter/system_config_doc.md, packages/jira-adapter/test/adapter.test.ts, packages/jira-adapter/test/adapter_creator.test.ts, packages/jira-adapter/test/change_validators/change_validator.test.ts, packages/jira-adapter/test/change_validators/field_configuration.test.ts, packages/jira-adapter/test/filters/field_configuration.test.ts
Added support for deploying field configuration
Only the last commit is relevant
This PR is build on https://github.com/salto-io/salto/pull/2598
---
- Added support for deploying field configuration items
- Added change validator when trying to deploy a change validator that is read-only or team-managed
---
None
---
None
=> SALTO-1778-field-configuration-deploy

packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/config.ts, packages/jira-adapter/src/diff.ts, packages/jira-adapter/src/filters/field_configurations_scheme.ts, packages/jira-adapter/test/filters/field_configurations_scheme.test.ts
Added support for deploying field configuration schemes
Only the last commit is relevant
This PR is build on https://github.com/salto-io/salto/pull/2598
---
None
---
None
=> SALTO-1778-field-configuration-scheme-deploy

packages/adapter-components/src/deployment/change_validators/deploy_types_not_supported.ts, packages/adapter-components/test/deployment/change_validators/deploy_types_not_supported.test.ts, packages/core/src/core/plan/change_validators/check_deployment_annotations.ts, packages/core/test/core/plan/change_validators/check_deployment_annotations.test.ts, packages/jira-adapter/src/change_validators/index.ts, packages/jira-adapter/src/change_validators/workflow.ts, packages/jira-adapter/src/filters/workflow/types.ts, packages/jira-adapter/src/filters/workflow/workflow.ts, packages/jira-adapter/test/change_validators/change_validator.test.ts, packages/jira-adapter/test/change_validators/workflow.test.ts, packages/jira-adapter/test/filters/workflow.test.ts, packages/jira-adapter/test/filters/workflow_values.ts, packages/zendesk-support-adapter/test/change_validator.test.ts
Fixed two issues in workflow deployment
- When creating a workflow it automatically adds an additional `PermissionValidator` with `permissionKey` of `CREATE_ISSUES`  to the initial transition so if it's already in the NaCl I remove it to not create duplicate validators
- Jira does not support deploying script runners config so I removed it from the nacl on deploy and added a changed validator
---
None
---
None
=> SALTO-1778-workflow-bug

packages/vscode/package.json, packages/vscode/src/commands.ts, yarn.lock
Due to [CVE-2017-16024](https://github.com/advisories/GHSA-38h8-x697-gh8q). This was found in `sync-exec` which is a dependency of the very unmaintained [copy-paste](https://github.com/xavi-/node-copy-paste).
This PR is changing `vscode` to use [clipboardy](https://github.com/sindresorhus/clipboardy)
---
None
---
None
---
None
=> vscode: replace copy-paste with clipboardy

package.json, packages/cli/package.json, packages/cli/package_native.js, yarn.lock
Update nexe version to avoid vulnerable version for normalize-url
---
Based on #2664 
---
_None_
---
_None_
=> SALTO-1670: Update normalize-url version

packages/jira-adapter/e2e_test/instances/index.ts, packages/jira-adapter/e2e_test/instances/workflowScheme.ts, packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/filters/field_references.ts, packages/jira-adapter/src/filters/workflow_scheme.ts, packages/jira-adapter/src/reference_mapping.ts, packages/jira-adapter/test/filters/workflow_scheme.test.ts
Added references to workflow scheme
---
The structure workflow scheme is changed from 
from
```
jira.WorkflowScheme "1801BugWorkflowScheme" {
name = "1801BugWorkflowScheme"
description = "this is a description!1@"
defaultWorkflow = "Software Simplified Workflow for Project LIORCOMP"
issueTypeMappings = {
additionalProperties = {
"10000" = "Software Simplified Workflow for Project TP3"
"10005" = "Lior's Test Workflow"
"10006" = "Software Simplified Workflow for Project TP3"
"10007" = "Software Simplified Workflow for Project LIORCOMP"
"10008" = "jira"
}
}
}
```
to
```
jira.WorkflowScheme "1801BugWorkflowScheme" {
name = "1801BugWorkflowScheme"
description = "this is a description!1@"
defaultWorkflow = jira.Workflow.instance.Software_Simplified_Workflow_for_Project_LIORCOMP@s
items = [
{ …
```
=> SALTO-1778: Added references to workflow scheme

packages/adapter-components/package.json, packages/hubspot-adapter/package.json, packages/salesforce-adapter/package.json, yarn.lock
- Update version of the request package to avoid vulnerable version of json-schema
- Update version of hosted-git-info
- update @apidevtools/swagger-parser version to avoid vulnerable version of validator
---
---
_None_
---
_None_
=> Update package versions to avoid moderate vulnerabilities

packages/adapter-components/src/references/field_references.ts, packages/adapter-components/test/references/field_references.test.ts, packages/zendesk-support-adapter/src/adapter.ts, packages/zendesk-support-adapter/src/filters/field_references.ts, packages/zendesk-support-adapter/test/filters/field_references.test.ts
_Add custom fields references in zendesk_
---
None
---
_Zendesk-Support Adapter_
* Add references to custom ticket fields in views and macros
---
_Add references to custom ticket fields in views and macros_
=> SALTO-1904: add custom fields references in zendesk

packages/adapter-components/src/client/http_connection.ts, packages/adapter-components/test/client/http_connection.test.ts
Added support for waiting the time that was returned in the "retry-after" header in the response before retrying a request in the simple adapter HTTP client
---
None
---
None
=> SALTO-1739: Add support for "retry-after" header

packages/jira-adapter/src/change_validators/index.ts, packages/jira-adapter/src/change_validators/screen.ts, packages/jira-adapter/test/change_validators/screen.test.ts
Added change validator to validate that the same tab is not used more than once in screen tabs (since Jira does not support that)
---
None
---
None
=> SALTO-1778: added change validator for screen tabs

packages/jira-adapter/src/deployment.ts, packages/jira-adapter/src/filters/default_instances_deploy.ts, packages/jira-adapter/src/filters/workflow_scheme.ts, packages/jira-adapter/src/reference_mapping.ts, packages/jira-adapter/test/filters/issue_type_schemas/issue_type_scheme.test.ts, packages/jira-adapter/test/filters/workflow_scheme.test.ts
Added support for deploying an active workflow scheme.
---
When updating an active workflow scheme it creates the changes in a draft and then we need to publish the drat.
The publish draft API is async, meaning we need to send one request to start the publishing and then check it's status repeatedly with another request.
Also, when publishing workflow scheme draft. The changes might not be backward compatible with the previous workflow scheme (if in the new workflow scheme we removed some issue statuses). So Jira allows us to pass how we want to migrate the used issue statuses so I also added `statusMigrations` field.
---
None
---
None
=> SALTO-1908: added support for deploying active workflow schemes

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/filters/remove_restriction_annotations.ts, packages/salesforce-adapter/test/filters/remove_restriction_annotations.test.ts
Remove `_restriction` values in salesforce types that may be impacted by addition/removal of custom objects and fields, to avoid unintentional changes in that annotation that may result in unexpected deploy plans (and sometimes failures).
Ideally these would be hidden rather than removed, but we don't have a good way to apply hidden changes related to builtin annotation types on existing workspaces - once we do, this will be replaced by the improved approach.
---
Will wait with merging until the corresponding noise-reduction PR is merged
---
* Remove `_restriction` annotation values for specific fields under `AccessControlPolicy`, `AnimationRule`, `PlatformEventChannelMember`, `RestrictionRule`, `AppProfileActionOverride`, `QueueSobject`, …
=> SALTO-1791 Remove restrictions impacted by custom objects and fields

packages/adapter-utils/src/collisions.ts, packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/collisions.test.ts, packages/adapter-utils/test/utils.test.ts
This can be combined with some chunking mechanism like the one started in https://github.com/salto-io/salto/pull/2681, but I think regardless we should avoid logging values inside reference expressions as these can be very large.
For now only omitting these in a log we know is problematic, but I think we should consider using this replacer everywhere.
---
(same as https://github.com/salto-io/salto/pull/2681)
_Zendesk_support adapter_:
* Fix bug in logging when there are collided element ids
---
None
=> SALTO-1921 avoid logging serialized values inside reference expressions

packages/core/src/core/plan/plan.ts, packages/core/test/core/plan/plan.test.ts
Plan calc throws "Cannot read property 'getFullName' of undefined" if a type have a field with a name of a built in function (such as `toString`)
The bug was that we expected `beforeFields[fieldName]` to be either `undefined` or `Field` but when `fieldName` is `toString`, `beforeFields[fieldName]` is a function
---
Core:
- Fixed bug of fields with built-in function names (e.g., `toString`)
---
None
=> SALTO-1915: Fixed plan of fields with built in function names

packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/change_validators/field_configuration.ts, packages/jira-adapter/src/filters/field_configuration_trashed_fields.ts, packages/jira-adapter/test/change_validators/field_configuration.test.ts, packages/jira-adapter/test/filters/field_configuration_trashed_fields.test.ts
Removed fields in trash from the fields configuration instances since we don't fetch them, they are not deployable, and they are not visible in the UI
---
None
---
None
=> SALTO-1927: removed fields in trash from field configuration

packages/adapter-components/src/client/http_client.ts, packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/client/client.ts, packages/jira-adapter/src/filters/avatars.ts, packages/jira-adapter/test/filters/avatars.test.ts
Remove the domain prefix of the current env from the URLs of avatars
---
If the URL contains the id of the avatar we replace the URL with the ID. Otherwise, we remove the domain name prefix from the URL if exists
---
None
---
None
=> SALTO-1925: remove domain from url prefixes

packages/jira-adapter/src/config.ts
Removed from `ProjectType` a base64 value of a SVG icon
---
None
---
None
=> Removed base64 icon from projectType

packages/lowerdash/src/values.ts, packages/lowerdash/test/values.test.ts, packages/netsuite-adapter/src/client/manifest_utils.ts, packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/src/reference_dependencies.ts, packages/netsuite-adapter/test/client/manifest_utils.test.ts, packages/netsuite-adapter/test/client/sdf_client.test.ts, packages/netsuite-adapter/test/reference_dependencies.test.ts
Some feature dependencies are not added automatically to the manifest and fail the deploy 
---
- add missing features & objects dependencies to `manifest.xml` on SDF deploy
=> SALTO-1287 netsuite - add required dependencies

packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/config.ts, packages/jira-adapter/src/filters/project.ts, packages/jira-adapter/src/filters/project_component.ts, packages/jira-adapter/test/filters/project.test.ts, packages/jira-adapter/test/filters/project_component.test.ts
Moved project component to a standalone field, removed redundant values in it, and made it deployable
---
None
---
None
=> SALTO-1933: added support deploying project components

packages/adapter-components/src/elements/index.ts, packages/adapter-components/src/elements/instance_elements.ts, packages/jira-adapter/e2e_test/adapter.test.ts, packages/jira-adapter/e2e_test/instances/field.ts, packages/jira-adapter/e2e_test/instances/index.ts, packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/config.ts, packages/jira-adapter/src/deployment.ts, packages/jira-adapter/src/filters/fields/constants.ts, packages/jira-adapter/src/filters/fields/context_deployment_filter.ts, packages/jira-adapter/src/filters/fields/context_options.ts, packages/jira-adapter/src/filters/fields/contexts.ts, packages/jira-adapter/src/filters/fields/default_values.ts, packages/jira-adapter/src/filters/fields/field_deployment_filter.ts, packages/jira-adapter/src/filters/fields/field_structure_filter.ts, packages/jira-adapter/src/filters/fields/field_type_references_filter.ts, packages/jira-adapter/src/filters/fields/issues_and_projects.ts, packages/jira-adapter/system_config_doc.md, packages/jira-adapter/test/filters/fields/context_options.test.ts, packages/jira-adapter/test/filters/fields/contexts.test.ts, packages/jira-adapter/test/filters/fields/default_values.test.ts, packages/jira-adapter/test/filters/fields/field_context_deployment.test.ts, packages/jira-adapter/test/filters/fields/field_deployment.test.ts, packages/jira-adapter/test/filters/fields/field_structure.test.ts, packages/jira-adapter/test/filters/fields/field_type_references.test.ts, packages/jira-adapter/test/filters/fields/issues_and_projects.test.ts
Separated contexts in fields to different instances to break the circle in https://salto-io.atlassian.net/browse/SALTO-1913
Also changed the id of a field to be its name and not id to be env friendly
---
None
---
None
=> SALTO-1913: separated field and contexts to different instances

packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/workspace.test.ts
listUnresolvedReference would get into an infinite recursion if there were a circular references in the completeFrom env (which is a valid case if the adapter defined a dependency changer to resolve the cycle)
---
Core:
- Fixed bug in `listUnresolvedReference` with `completeFrom` when there is a circular references in the `completeFrom` env
---
None
=> SALTO-1940: fixed listUnresolvedReference with circular dependencies

packages/zendesk-support-adapter/src/config.ts, packages/zendesk-support-adapter/system_config_doc.md
Fix type for field with dynamic keys.
Note: I think we are still generating the subtype even though we are not using it - ~maybe for now we should remove it manually?~ I will try to add a PR in a few days that removes "orphan" subtypes.
---
* Change type for organization fields
---
* Change type for organization fields (I believe this is not currently tracked)
=> SALTO-1941 define field as map

packages/jira-adapter/src/filters/fields/field_structure_filter.ts, packages/jira-adapter/test/filters/fields/field_structure.test.ts
Removed isLocked from fields when it is false to remove the redundant change validator warning about this value not being deployable
---
None
---
None
=> SALTO-1946: removed isLocked when not locked

packages/jira-adapter/src/filters/fields/context_deployment_filter.ts, packages/jira-adapter/src/filters/fields/contexts.ts, packages/jira-adapter/src/filters/fields/field_structure_filter.ts, packages/jira-adapter/test/filters/fields/field_context_deployment.test.ts, packages/jira-adapter/test/filters/fields/field_deployment.test.ts
Added deployment annotation to field contexts so we won't get a warning when attempting to deploy it and fixed it's type (it was map when it was supposed to be list)
---
None
---
None
=> SALTO-1961: fixed contexts field

packages/jira-adapter/README.md, packages/jira-adapter/src/config.ts, packages/jira-adapter/system_config_doc.md, packages/jira-adapter/test/adapter.test.ts
Replaced URL of Jira swagger with the URL of our repo
---
None
---
None
=> SALTO-1962: Replaced swaggers URL without our repo

packages/adapter-api/src/builtins.ts, packages/adapter-components/src/elements/ducktype/standalone_field_extractor.ts, packages/adapter-components/src/elements/ducktype/transformer.ts, packages/adapter-components/src/elements/ducktype/type_elements.ts, packages/adapter-components/src/elements/instance_elements.ts, packages/adapter-components/src/elements/swagger/instance_elements.ts, packages/adapter-components/src/elements/type_elements.ts, packages/adapter-components/test/elements/ducktype/instance_elements.test.ts, packages/adapter-components/test/elements/type_elements.test.ts, packages/zendesk-support-adapter/src/adapter.ts, packages/zendesk-support-adapter/src/adapter_creator.ts, packages/zendesk-support-adapter/src/config.ts, packages/zendesk-support-adapter/test/adapter.test.ts, packages/zendesk-support-adapter/test/resolve_changes.test.ts
_add ElemIdGetter to zendesk_
---
---
* renaming element name in the service would modify the element
---
_None_
=> SALTO-1894: add ElemIdGetter to zendesk

packages/jira-adapter/e2e_test/instances/field.ts, packages/jira-adapter/e2e_test/instances/fieldConfigurationScheme.ts, packages/jira-adapter/e2e_test/instances/index.ts, packages/jira-adapter/e2e_test/instances/issueTypeScheme.ts, packages/jira-adapter/e2e_test/instances/issueTypeScreenScheme.ts, packages/jira-adapter/e2e_test/instances/workflowScheme.ts, packages/jira-adapter/src/change_validators/index.ts, packages/jira-adapter/src/change_validators/issue_type_scheme.ts, packages/jira-adapter/src/config.ts, packages/jira-adapter/src/constants.ts, packages/jira-adapter/src/diff.ts, packages/jira-adapter/src/filters/issue_type_schemas/issue_type_scheme.ts, packages/jira-adapter/src/filters/issue_type_schemas/issue_type_scheme_references.ts, packages/jira-adapter/src/reference_mapping.ts, packages/jira-adapter/test/adapter.test.ts, packages/jira-adapter/test/change_validators/issue_type_scheme.test.ts, packages/jira-adapter/test/filters/issue_type_schemas/issue_type_scheme.test.ts, packages/jira-adapter/test/mock_elements.ts
Fixed adding and removing issue types from the default issue type scheme
---
The default issueTypeScheme always contains all of the issueTypes. That creates two problems:
- When creating a new issueType and adding it to the list, we get an error on deploy because when we create the issueType it is automatically added to the default issue type scheme so when we call the endpoint to add it to the list we fail because it's already there. For that, we can just ignore the new ids if the scheme is the default scheme
- Removing an issue type from the default scheme is not supported, so if an issue type was removed from the list, we need to check if it was really deleted
---
None
---
None
=> SALTO-1957: fixed issues with adding and removing values from the default issueTypeScheme

packages/adapter-api/src/adapter.ts, packages/adapter-components/src/deployment/change_validators/skip_parents_of_skipped_instances.ts, packages/adapter-utils/src/change_validator.ts, packages/adapter-utils/test/change_validator.test.ts, packages/core/src/api.ts, packages/core/src/core/adapters/adapters.ts, packages/core/src/core/plan/change_validators/index.ts, packages/core/src/core/plan/filter.ts, packages/core/src/core/plan/plan.ts, packages/core/test/core/plan/change_validators/index.test.ts, packages/salesforce-adapter/index.ts, packages/salesforce-adapter/src/adapter_creator.ts, packages/salesforce-adapter/src/change_validator.ts, packages/salesforce-adapter/src/change_validators/validate_only_flag.ts, packages/salesforce-adapter/test/change_validator.test.ts, packages/salesforce-adapter/test/change_validators/validate_only_flag.test.ts
PR #2439 added an interface to adapter-api change validators that was inconsistent and should not be used. it was relying on a config instance that was passed through a different code path than the one the adapter actually uses and as such was not validated or parsed by the adapter.
There is already an interface to get the adapter config in a change validator, so in this PR we remove the interface that should not exist and change the implementation of the one validator that used the old interface to use the correct interface instead
---
---
_None_
---
_None_
=> SALTO-1292: remove inconsistent interface from adapter-api change validator

packages/jira-adapter/src/deployment.ts, packages/jira-adapter/test/adapter.test.ts
Fixed Jira deployment error message to contain also `errors` in the response if exists and not only `errorMessages`
---
None
---
None
=> SALTO-1976: fixed deployment error message in Jira

packages/adapter-api/src/values.ts, packages/core/src/core/plan/plan.ts, packages/core/test/core/plan/plan.test.ts
Fixing bug - In `core/src/core/plan/plan.ts` line 79 - the reference expressions are compared after resolving them, but in some cases the value doesn't change and the reference does change. For example - from `netsuite.a.instance.a.list.0.scriptid` to `netsuite.a.instance.a.list.somekey.scriptid`
It means that this change will be ignored and if it is the only change in an instance it won’t be written to the NaCl.
This PR is a fix to https://github.com/salto-io/salto/pull/2589 and its keeping the original behavior of references comparison, with a recursive comparison of nested references.
---
None
---
None
=> SALTO-1963 resolve references on plan

packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/change_validators/field_configuration_unsupported_fields.ts, packages/jira-adapter/src/filters/field_configuration.ts, packages/jira-adapter/src/filters/map_lists.ts, packages/jira-adapter/test/change_validators/default_field_configuration.test.ts, packages/jira-adapter/test/change_validators/field_configuration_unsupported_fields.test.ts, packages/jira-adapter/test/filters/map_lists.test.ts
Changed fields in `FieldConfiguraiton` to be a map where the key is the field name to reduce noise when comparing between envs
---
None
---
None
=> SALTO-1971: changed field configuration fields from list to a map

packages/netsuite-adapter/src/saved_search_parsing/parsed_saved_search.ts
Fixed saved search type
---
Netsuite:
- Fixed `sort_columns` field type in `savedsearch` type
---
- The type of `sort_column` field in `savedsearch` type in Netsuite is going to change (the notifications won't alert this change, but it will affect the workspace on git).
=> SALTO-1990: Fixed saved search type

packages/jira-adapter/e2e_test/instances/fieldConfiguration.ts, packages/jira-adapter/e2e_test/instances/index.ts, packages/jira-adapter/src/filters/field_configuration.ts, packages/jira-adapter/test/filters/field_configuration.test.ts
Fixed regression in FieldConfgiuration deployment
---
The condition [here](https://github.com/salto-io/salto/compare/main...alonstern:SALTO-1991?expand=1#diff-36059ffe65bf56a701ac1401981c8b25503bf1adcdb70fdf16254b71ecef532eL93) was wrong
---
None
---
None
=> SALTO-1991: fixed fieldConfiguration deployment

packages/cli/src/commands/common/config_override.ts, packages/cli/src/commands/service.ts, packages/cli/test/commands/service.test.ts
Added support for non-interactive service login for `add` and `login` commands 
---
CLI:
- Service `add` and `login` commands now supports non-interactive login.
---
_None_
=> SALTO-1401: non-interactive service login

packages/netsuite-adapter/src/filters/instance_references.ts, packages/netsuite-adapter/test/filters/instance_references.test.ts
- generate reference dependency when there is a reference of the form `[type=crmcustomfield, scriptid=cseg1]` and `cseg1` is not of type `crmcustomfield`
- use `extendGeneratedDependencies`
---
None
---
Netsuite-Adapter:
- generate reference dependency for references of the form `[type=crmcustomfield, scriptid=cseg1]` when `cseg1` is not of type `crmcustomfield` 
---
- NetSuite Adapter: more references in `_generated_dependencies`
=> SALTO-1559 more generated dependencies

packages/zendesk-support-adapter/src/deployment.ts, packages/zendesk-support-adapter/src/filters/custom_field_options/creator.ts, packages/zendesk-support-adapter/src/filters/dynamic_content.ts
_Removal changes on custom field options and variants should be done last_
---
Handles the case where we first try to remove the only variant(s) and then add them (we can't leave an item with no variants). Same thing applies to custom fields options
---
_None_
---
_None_
=> SALTO-1860: removal changes on custom field options and variants should be done last

packages/jira-adapter/src/change_validators/field_configuration_unsupported_fields.ts, packages/jira-adapter/test/change_validators/field_configuration_unsupported_fields.test.ts
Fixed `unsupportedFieldConfigurationsValidator` detailedMessage.
- Changed it to contain all information in the message (because in the SaaS we show only the detailedMessage)
- Replaced the ids in the message with the field instances names
---
None
---
None
=> SALTO-1974, SALTO-1967: fixed changed validator message

packages/jira-adapter/src/config.ts, packages/jira-adapter/system_config_doc.md, packages/jira-adapter/test/adapter.test.ts
Changed swagger back to use `main` branch in the jira-swaggers repo after it's been updated with the latest swagger
---
None
---
None
=> SALTO-1958: changed swagger back to use main branch

packages/adapter-components/src/config/ducktype.ts, packages/adapter-components/src/config/index.ts, packages/adapter-components/src/config/swagger.ts, packages/adapter-components/src/config/transformation.ts, packages/adapter-components/src/elements/ducktype/add_remaining_types.ts, packages/adapter-components/src/elements/ducktype/transformer.ts, packages/adapter-components/src/elements/ducktype/type_elements.ts, packages/adapter-components/src/elements/swagger/instance_elements.ts, packages/adapter-components/test/elements/ducktype/add_remaining_types.test.ts, packages/adapter-components/test/elements/ducktype/transformer.test.ts, packages/workato-adapter/test/adapter.test.ts, packages/zendesk-support-adapter/src/filters/reorder/creator.ts, packages/zendesk-support-adapter/test/adapter.test.ts
_always have at least an empty type for any deployable instance_
---
None
---
* always have at least an empty type for any deployable instance
_Workato adapter_
* always have at least an empty type for any deployable instance
---
_Zendesk - new empty instances will be added_
=> SALTO-1966: always have at least an empty type for any deployable instance

packages/adapter-components/src/elements/type_elements.ts
_remove spamming log_
---
Some types don't have the default fields to hide and therefore our logs is spammed by this log message
---
_None_
---
_None_
=> remove spamming log

packages/zendesk-support-adapter/src/adapter.ts, packages/zendesk-support-adapter/src/filters/hide_definition_instances.ts, packages/zendesk-support-adapter/test/filters/hide_definition_instances.test.ts
_hide definition instances in zendesk_
---
---
* Hide definition instances
---
_Hide definition instances in zendesk_
=> SALTO-2012: hide definition instances in zendesk

packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/test/client.test.ts
On some rare cases salesforce client fails with 400, and a retry would fix the failure, so we will retry on 400
---
---
---
=> [SALTO-1876] retry 400 errors on salesforce client

packages/adapter-components/src/client/http_client.ts, packages/adapter-components/src/client/http_connection.ts, packages/jira-adapter/config_doc.md, packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/config.ts, packages/jira-adapter/src/constants.ts, packages/jira-adapter/src/filters/statuses/missing_statuses.ts, packages/jira-adapter/test/filters/statuses/missing_statuses.test.ts
Jira public API for getting all the statuses returns only the statuses that are used in active workflows so we fetch the missing statuses using private API.
I also added a configuration option to turn off the usage of private API
---
None
---
None
=> SALTO-1973: Added fetch for missing statuses

packages/workspace/src/workspace/hidden_values.ts, packages/workspace/test/workspace/hidden_values.test.ts
Fixed a bug with hidden values in maps values
---
There were two issues:
- We would not check inner values if the change was a change of map and not an object type
- `await (await getField(changeType, changePath, state))?.getType(state)` return the Map type and not the inner type also for values inside maps so we should use `getFieldType`
---
None
---
None
=> SALTO-1997: fixed bug of hidden values with maps

packages/adapter-components/src/elements/swagger/type_elements/element_generator.ts, packages/adapter-components/src/elements/type_elements.ts, packages/adapter-components/src/filter_utils.ts, packages/adapter-components/test/elements/swagger/type_elements.test.ts, packages/adapter-components/test/elements/type_elements.test.ts, packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/adapter_creator.ts, packages/jira-adapter/src/config.ts, packages/jira-adapter/src/filters/fields/field_structure_filter.ts, packages/jira-adapter/test/adapter.test.ts, packages/jira-adapter/test/filters/fields/field_structure.test.ts
Using elemIdGetter in Jira to persist the element name after the first fetch
---
None
---
None
=> SALTO-1999: added elemIdGetter to Jira

packages/core/src/core/fetch.ts, packages/core/test/core/fetch.test.ts
Before this change, if both sides (nacl and account) added an element, we would not consider it a conflict
even if the values inside were completely different.
this changes the behavior such that each difference between the added values would be considered a conflict
with the exceptions of values that we added by the account - those will be applied anyway.
This is not ideal, but it could help us avoid false conflicts due to hidden values that come from the account
---
---
Core:
- Fixed issue where elements added both in NaCl and in the service would not be merged or detected as conflicts on fetch
---
_None_
=> SALTO-1972: Handle conflicts when both sides add an element

packages/jira-adapter/src/filters/user.ts, packages/jira-adapter/test/filters/user.test.ts
Replaced the User object with only the display name of the user in Dashboard and Board
---
None
---
None
=> SALTO-1979: replaced user with display names in more types

packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/dependency_changers/index.ts, packages/jira-adapter/src/dependency_changers/project.ts, packages/jira-adapter/test/dependency_changers/index.test.ts, packages/jira-adapter/test/dependency_changers/project.test.ts
Added dependency from additions to removals of projects with the same key
---
This is to prevent a scenario where for example with delete a project and create a project with the same key in the same deploy, but because we don't first remove the project and then add the new one, we get an error the the key is already in use
---
None
---
None
=> SALTO-1985: changed to deploy removals first for projects

packages/zendesk-support-adapter/src/change_validator.ts, packages/zendesk-support-adapter/src/change_validators/empty_custom_field_options.ts, packages/zendesk-support-adapter/src/change_validators/empty_variants.ts, packages/zendesk-support-adapter/src/change_validators/index.ts, packages/zendesk-support-adapter/src/change_validators/utils.ts, packages/zendesk-support-adapter/test/change_validators/empty_custom_field_options.test.ts, packages/zendesk-support-adapter/test/change_validators/empty_variants.test.ts
_Prevent omitting all options from fields and dynamic content items_
---
We can't leave a dropdown field with no options, or a dynamic content item with no variants
---
_None_
---
_None_
=> SALTO-1986: prevent omitting all options from fields and dynamic content items

packages/workspace/src/workspace/hidden_values.ts, packages/workspace/test/common/state.ts, packages/workspace/test/workspace/hidden_values.test.ts
…
_show or hide instances when their type _hidden_value value is changed_
---
_when an instance type _hidden_value value changes, the instance should be removed/shown in the nacls_
---
_Fixed merge errors after a _hidden_value value is change in a type that is used by instances._
---
_NA_
=> (SALTO-2025) show or hide instances when their type _hidden_value value is changed

packages/jira-adapter/e2e_test/instances/workflow.ts, packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/filters/workflow/types.ts, packages/jira-adapter/src/filters/workflow/workflow.ts, packages/jira-adapter/src/filters/workflow/workflow_properties.ts, packages/jira-adapter/test/filters/workflow_properties.test.ts
Changed workflow statuses properties from a map to a list of objects with `key` and `value` because the key might contain `.` which isn't supported well by the parser
---
None
---
None
=> SALTO-1998: changed workflow properties to a list of objects

packages/jira-adapter/specific-cli-options.md, packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/adapter_creator.ts, packages/jira-adapter/src/change_validators/index.ts, packages/jira-adapter/src/change_validators/project_deletion.ts, packages/jira-adapter/src/config.ts, packages/jira-adapter/test/change_validators/change_validator.test.ts, packages/jira-adapter/test/change_validators/project_deletion.test.ts
Added `forceDelete` deploy option that when is off, deploying projects with issues will be blocked because the issues can't be restored
---
None
---
None
=> SALTO-2016: added "forceDelete" deploy option

packages/jira-adapter/jest.config.js
Currently, the coverage in main is 93.99 🥲
---
None
---
None
=> Lowered the branch threshold in Jira adapter

packages/adapter-components/src/elements/index.ts, packages/adapter-components/src/elements/instance_elements.ts, packages/adapter-components/test/elements/instance_elements.test.ts, packages/jira-adapter/config_doc.md, packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/config.ts, packages/jira-adapter/src/filter.ts, packages/jira-adapter/src/filters/duplicate_ids.ts, packages/jira-adapter/src/filters/fields/field_structure_filter.ts, packages/jira-adapter/src/utils.ts, packages/jira-adapter/test/filters/duplicate_ids.test.ts, packages/jira-adapter/test/filters/fields/field_structure.test.ts, packages/jira-adapter/test/filters/sort_lists.test.ts
JSM creates some duplicate records in the account, to deal with it we will add the id of the instance only to name of the duplicate instances in the account 
---
None
---
None
=> SALTO-2001: Added id to the name of duplicate instances

packages/netsuite-adapter/e2e_test/adapter.test.ts, packages/netsuite-adapter/package.json, packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/change_validator.ts, packages/netsuite-adapter/src/change_validators/safe_deploy.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/elements_source_index/elements_source_index.ts, packages/netsuite-adapter/src/elements_source_index/types.ts, packages/netsuite-adapter/src/filters/instance_references.ts, packages/netsuite-adapter/src/reference_dependencies.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/change_validators/safe_deploy.test.ts, packages/netsuite-adapter/test/filters/author_information/saved_searches.test.ts, packages/netsuite-adapter/test/filters/author_information/system_note.test.ts, packages/netsuite-adapter/test/filters/data_instances_references.test.ts, packages/netsuite-adapter/test/filters/data_types_custom_fields.test.ts, packages/netsuite-adapter/test/filters/instance_references.test.ts, packages/netsuite-adapter/test/filters/internal_ids/sdf_internal_ids.test.ts, packages/netsuite-adapter/test/filters/parse_saved_searches.test.ts, packages/netsuite-adapter/test/filters/remove_unsupported_types.test.ts, packages/netsuite-adapter/test/filters/service_urls.test.ts, packages/netsuite-adapter/test/reference_dependencies.test.ts, packages/netsuite-adapter/tsconfig.json
For certain types, once we deploy them, SDF fails since it expects the referenced instances to be in the same deployed SDF project.
The hack in netsuite-adapter is to deploy the referenced instances in these specific cases although they are not in the plan.
The downside is that we deploy things to the customer that they are not aware of, and might override an element that has changed in the service and has an outdated version in the Workspace.
We should add these elements to the safe-deploy calculation.
---
- add required/referenced elements to safe-deploy validation
---
None
=> SALTO-1886 safe deploy SDF referenced deployed elements

packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/config.ts, packages/jira-adapter/src/filters/duplicate_ids.ts, packages/jira-adapter/src/filters/fields/context_references_filter.ts, packages/jira-adapter/src/filters/fields/field_structure_filter.ts, packages/jira-adapter/test/filters/fields/context_references_filter.test.ts, packages/jira-adapter/test/filters/fields/field_structure.test.ts
Fixed duplicateIdsFilter to run also on duplicates field contexts since the UI in Jira permits to contexts with the same name on the same field
---
None
---
None
=> SALTO-2001: fix context dups

packages/zendesk-support-adapter/src/adapter.ts, packages/zendesk-support-adapter/src/filters/business_hours_schedule.ts, packages/zendesk-support-adapter/src/filters/routing_attribute.ts, packages/zendesk-support-adapter/test/filters/business_hours_schedule.test.ts, packages/zendesk-support-adapter/test/filters/routing_attribute.test.ts
_Fix routing attribute deploy in zendesk_
---
Also removed the deploy of holidays in schedule (it's currently working but we don't want to deploy it)
---
_None_
---
_None_
=> SALTO-2055: fix routing attribute deploy

packages/zendesk-support-adapter/src/config.ts, packages/zendesk-support-adapter/system_config_doc.md
_Fix zendesk config issues around webhooks and brands_
---
---
* Remove ticket_form_ids from brand instances
* Remove the meta field from webhooks
---
_Remove ticket_form_ids from zendesk' brand instances_
_Remove unneeded meta field from webhooks in zendesk_
=> SALTO-1964: fix zendesk config issues around webhooks and brands

packages/workato-adapter/src/config.ts, packages/workato-adapter/test/adapter.test.ts
Hide non-multienv-friendly fields in Workato resources.
Note that some ids still exist in the element ids themselves - this will be handled as part of SALTO-1241.
---
Will add a noise-reduction PR before merging (as needed)
---
Workato adapter:
* Hide fields containing internal ids that are different between environments
* Change the id of the `property` instance to mark it as a singleton
---
Workato adapter:
* Hide fields containing internal ids that are different between environments
* Change the id of the `property` instance to mark it as a singleton
=> SALTO-2059 Hide Workato internal ids and non-multienv fields

packages/workato-adapter/src/adapter.ts, packages/workato-adapter/src/filters/add_root_folder.ts, packages/workato-adapter/src/filters/field_references.ts, packages/workato-adapter/test/adapter.test.ts, packages/workato-adapter/test/filters/add_root_folder.test.ts
Add a placeholder root folder (since none is returned by the API but it is referenced by a lot of instances).
---
I will add a noise-reduction PR before this is merged (if needed - need to check - (update: not needed))
---
Workato adapter:
* Add a new `ROOT` folder instance
* Add more references to folders
---
Workato adapter:
* A new `ROOT` folder instance will be added
* Some references to folder instances will be added
=> SALTO-2060 Add base folder in Workato

packages/workato-adapter/src/adapter.ts, packages/workato-adapter/src/config.ts, packages/workato-adapter/src/filters/add_root_folder.ts, packages/workato-adapter/src/filters/fix_multienv_ids.ts, packages/workato-adapter/test/adapter.test.ts, packages/workato-adapter/test/filters/fix_multienv_ids.test.ts
* Add support for multienv-friendly ids with "expected" repetitions (repeating names but not under the same paths), specifically for recipes and folders.
This is temporary until SALTO-1241 and SALTO-1687 are fully implemented, and then the default config will use these options.
For now, adding a filter that does nothing with the default config, but supports customizing for multienv-friendly ids when needed - by using the following id field overrides:
```
apiDefinitions = {
types = {
recipe = {
transformation = {
idFields = [
"name",
"&folder_id",
]
}
}
folder = {
transformation = {
idFields = [
"name",
"&parent_id",
]
}
}
}
}
```
* Also removing a couple of recipe fields that are not needed, and cleaning up the ids of recipe_code instances for future workspaces (since we have …
=> SALTO-1241 Add special handling for recipe and folder multienv ids

docs/user_guide.md
Bash is so 2019
---
---
Nope
---
=> Update user guide to use zsh instead of bash

packages/netsuite-adapter/src/client/manifest_utils.ts, packages/netsuite-adapter/src/elements_source_index/elements_source_index.ts, packages/netsuite-adapter/src/filters/instance_references.ts, packages/netsuite-adapter/src/mapped_lists/utils.ts, packages/netsuite-adapter/src/service_id_info.ts, packages/netsuite-adapter/src/transformer.ts, packages/netsuite-adapter/test/client/manifest_utils.test.ts
references to `[appid=com.someapp, scriptid=...]` should not be included in the manifest, as they causing an error - `The manifest contains a dependency on <scriptid> object, but it is not in the account.`
I also changed the keys in `ServiceIdInfo` type to literal strings instead of `[CONST_VALUE]` because its unnecessary.
---
- fix bug in manifest.xml dependencies logic
---
None
=> SALTO-2049 netsuite - fix manifest appid error

packages/salesforce-adapter/e2e_test/setup.ts
The current setup attempts to remove an object before creating it but the object
cannot be removed while there is still a reference to it.
Added a removal of the referring field from Case before attempting to remove the object
---
---
_None_
---
_None_
=> SALTO-2057: Fix e2e setup for salesforce adapter

packages/workspace/src/workspace/hidden_values.ts, packages/workspace/test/workspace/hidden_values.test.ts
_Do not treat empty values as hidden_
---
@ori-moisis FYI
---
_Core_
* empty values will stop being treated as hidden
---
_Fetches of envs that have elements with empty values will stop to be hidden_
=> SALTO-2024: do not treat empty values as hidden

packages/workspace/src/workspace/hidden_values.ts, packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/workspace.test.ts
_fixed changing type to hidden creates warnings_
The issue was caused since the hidden element was removed from the state cache as well as the workspace cache.
This was a result of the filter hidden changes function returning remove changes to both the state and the workspace, the function and flow was modified to direct remove changes just like regular changes. In addition to that, the `compateStateChanges` code was modify to account for cases in which remove changes to the workspace are a result of such change (which means they shouldn't be removed from the state)
_Fixed validation errors after a type `_hidden` annotation is changed to true._
---
_NA_
=> (SALTO-1968) fixed changing type to hidden creates warnings

packages/workato-adapter/src/adapter.ts, packages/workato-adapter/src/adapter_creator.ts, packages/workato-adapter/src/config.ts, packages/zendesk-support-adapter/src/adapter.ts, packages/zendesk-support-adapter/src/adapter_creator.ts, packages/zendesk-support-adapter/src/config.ts
_change hide type default to true in duck type adapters_
---
---
_Zendesk_support adapter_:
* hiding the types by default
_Workato adapter_:
* hiding the types by default
---
_All the types in Zendesk and Workato will become hidden_
=> SALTO-1965: change hide type default to true in ducktype adapters

packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/workspace.test.ts
Prevent creating new environments with the '/' char or renaming to it.
---
Core: Prevent creating new environments with the '/' char or renaming to it.
---
None
=> SALTO-2082: Prevent creating new environments with the '/' char or renaming to it

packages/netsuite-adapter/src/adapter.ts
change the order of `consistentValues` and `convertListsToMaps` filters to prevent inconsistent key names.
---
Netsuite Adapter
- fix bug in inconsistent key names
---
None
=> SALTO-2086 change order of filters

packages/cli/src/callbacks.ts, packages/netsuite-adapter/e2e_test/credentials_store/adapter.ts, packages/netsuite-adapter/e2e_test/jest_environment.ts, packages/netsuite-adapter/package.json, packages/netsuite-adapter/src/adapter_creator.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/client/credentials.ts, packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts, packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts, packages/netsuite-adapter/test/adapter_creator.test.ts, packages/netsuite-adapter/test/client/suiteapp_client.test.ts, packages/netsuite-adapter/test/data_elements/data_elements.test.ts, yarn.lock
Passing `activationKey` param in suiteapp restlet requests. It is the `accountId` signature and it is given by the user on `salto service add/login`. If the installed SuiteApp is not updated to the version that verifies `activationKey` - falling back to restlet requests without the `activationKey` param.
---
- Added `suiteAppActivationKey` parameter to the adapter's SuiteApp credentials - please run `salto service login` and enter all required parameters to use SuiteApp
- Using SuiteApp with activation key verification
---
None
=> SALTO-1975 add suiteapp activation key

packages/jira-adapter/src/filters/workflow_scheme.ts, packages/jira-adapter/test/filters/workflow_scheme.test.ts
I saw a case where after publishing a workflow scheme draft, the id of the workflow scheme is changed, so before deploying, I added a check that we have the right id
---
None
---
None
=> SALTO-2089: Updating workflow scheme id when changed

packages/core/test/workspace/local/remote_map.test.ts, packages/dummy-adapter/src/generator.ts, packages/dummy-adapter/test/generator.test.ts
_make dummy adapter process safe_
---
The random mechanism used in the dummy adapter is currently global for the process and is reset when the dummy adapter fetch begins. As a result, if two fetches takes place concurrently, the random generator is shared between them - causing them to generate different outputs.
While this is not an issue when invoked via the cli, it can create issues when the adapter is fetched in an other execution environments  (for example, a nodejs express server)
When used globally, `seedrandom` override Math.random functionality. Since we are now using a local generator, changes to the uniqueNameGenerator were also needed. Namely:
1. Explicitly provide a seed value for the name generation
2. Explicitly ensuring names are unique (since seed random does not provide …
=> SALTO-2078: make dummy adapter process safe

packages/jira-adapter/e2e_test/instances/workflow.ts, packages/jira-adapter/src/adapter.ts, packages/jira-adapter/src/config.ts, packages/jira-adapter/src/filters/workflow/step_ids_filter.ts, packages/jira-adapter/src/filters/workflow/steps_deployment.ts, packages/jira-adapter/src/filters/workflow/types.ts, packages/jira-adapter/src/filters/workflow/workflow_deploy_filter.ts, packages/jira-adapter/src/filters/workflow/workflow_structure_filter.ts, packages/jira-adapter/test/filters/workflow/step_ids_filter.test.ts, packages/jira-adapter/test/filters/workflow/steps_deployment.test.ts, packages/jira-adapter/test/filters/workflow/workflow_structure_filter.test.ts
Added support for deploying step names in workflow
---
Added the ids of the steps in the workflow to the workflow using the private API and used the ids to create a post request to a JSP page to edit the name of the steps after creating the workflow
---
_Jira Adapter_
- Workflow status names are now fetched from the service and are deployable when creating a workflow
---
_Jira Adapter_
- After the next fetch, a name value will be added to each status in each workflow
=> SALTO-2042: added support for step names in workflow

packages/workspace/src/parser/dump.ts, packages/workspace/src/parser/internal/native/consumers/blocks.ts, packages/workspace/src/parser/internal/native/consumers/values.ts, packages/workspace/src/parser/internal/native/helpers.ts, packages/workspace/src/parser/internal/native/parse.ts
_Make dump internally sync by adding promise value watchers_
---
The dump method is currently async since the functions dump method is async.
Tests showed that removing this can improve the dump performance in about 50%.
This is can be done by creating value promise watchers and awaiting them all at once like we do in the parser. 
---
_Improved the NaCL dump methods performance_
---
_NA_
=> SALTO-2066: make dump internally sync

packages/adapter-components/src/elements/swagger/instance_elements.ts, packages/adapter-components/test/elements/swagger/instance_elements.test.ts
Currently, if we would fail to fetch the recurseInto data of one instance, we would omit from the workspace all the instances of that type. This causes the issue in Jira where a team-managed project in the trash would cause all the screen instances to be omitted from the workspace
---
- Fixed a bug where putting a team-managed project in the trash would cause the screen instances to be omitted from the workspace
---
None
=> SALTO-2094: Fixed to not omit all the instances when recurseInto of one instance is failing

packages/zendesk-support-adapter/src/adapter.ts, packages/zendesk-support-adapter/src/filters/field_references.ts
_Some user's internal ids are not changed into emails_
---
Two tiny changes here:
- There was a bug that prevented the users filter from running in some cases
- Added references for restricted_brand_ids (brands)
---
* Fixed a bug that prevented users internal ids to change into emails
* Added one more reference
---
* Zendesk - Some users internal ids can be changed into emails
* Zendesk - added references for brands for restricted_brand_ids field
=> SALTO-2100: some users internal ids are not changed into emails

packages/salesforce-adapter/src/adapter.ts, packages/salesforce-adapter/src/filters/author_information/validation_rules.ts, packages/salesforce-adapter/test/filters/author_information/validation_rules.test.ts
add author information to validation rule instances.
---
there is an option to merge sharing rules author information filter and this new one into a single generic filter that will handle even more types but it will be done in a different pr.
---
---
=> SAAS-4317/validation rules authour information

packages/core/src/core/fetch.ts, packages/core/test/common/workspace.ts, packages/core/test/core/fetch.test.ts, packages/workspace/src/workspace/nacl_files/multi_env/routers.ts, packages/workspace/src/workspace/nacl_files/nacl_files_source.ts, packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
_added file location as path fallback in fetch from_
---
If an element was added to the nacls and then deployed, it will be in the state - but not in the path index.
In the long term - this should be handled by the fragments refactor epic. As a short term solution until  - we should use the nacl files location as a fallback.
---
_Added file location as a fallback for changes path in fetch from workspace_
---
_NA_
=> (SALTO-2102) added file location as path fallback in fetch from

packages/salesforce-adapter/src/adapter_creator.ts
Force login on salesforce oauth flow - using the `prompt=login%20consent` url parameter.
---
- Force login on Salesforce OAuth flow
---
None
=> SAAS-4452 force login on salesforce oauth flow

packages/adapter-utils/src/utils.ts, packages/adapter-utils/test/utils.test.ts
Fixed a bug in transform values where we would run `_.isEmpty` on values that might be numbers or booleans which `_.isEmpty` returns true for but we would not want treat as empty
---
None
---
None
=> SALTO-1934: fixed bug in transform values

packages/salesforce-adapter/src/client/client.ts, packages/salesforce-adapter/test/client.test.ts
Salesforce Adapter: retry upon "unknown_error: retry your request" error when listing metadata types.
=> SALTO-2110: SF fetch fails sporadically due to "unknown_error: retry your request"

packages/workspace/src/workspace/workspace.ts, packages/workspace/test/workspace/workspace.test.ts
Added a new optional target env to the workspace, so actions will use that as instead of the active env for most operations.
---
None
---
CLI - Fix issue where setting the -e flag would change the active env 
---
None
=> SALTO-1406: Fix issue where temporary env switches the active env

docs/user_guide.md
Removing the empty glossary from the getting started guide
=> SALTO-2117 remove glossary from getting started guide

packages/adapter-components/src/client/http_connection.ts
---
Seems like since [this change](https://github.com/salto-io/salto/commit/90e0df36f2540690fcac458d8e8f4b3356be32e7#diff-2880859bfcf8851294b1f831ff389e877c7b498966a488198fb2f80c42bd58bbR18) external projects would fail when importing salto packages.
The typescript issue that causes this: https://github.com/microsoft/TypeScript/issues/38540
Not clear how the CLI kept working, still investigating that part
---
_None_ (no behavior change)
---
_None_
=> SALTO-2128: Fix build issue with axios import and old TS

packages/core/src/core/plan/filter.ts, packages/core/src/core/plan/plan.ts, packages/workspace/src/expressions.ts
Before this change, the plan algorithm would resolve elements twice.
The second resolve was there in order to make sure everything is resolved after filtering.
When no changes were filtered out, there is no need to resolve again.
Skipping that second resolve seems to have a significant effect on performance
Also added more granular timing logs for different parts of the plan algorithm
---
---
Core:
- Improve performance of comparisons (fetch, diff)
---
_None_
=> Skip resolving elements in plan when not needed

packages/stripe-adapter/e2e_test/adapter.test.ts, packages/stripe-adapter/src/config.ts
Quick fix for missing type that is listed in `recurseInto` - will replace by a generic fix soon.
The `products` type includes an additional query that adds `prices` instances. Adding `prices` explicitly for now
---
Stripe adapter:
* Fix issue that caused products to not be fetched
---
Stripe adapter:
* Add back product instances that were erroneously removed
=> SALTO-2130 temporarily list recurseInto type explicitly

packages/adapter-components/src/elements/swagger/type_elements/element_generator.ts, packages/adapter-components/test/elements/swagger/type_elements.test.ts, packages/stripe-adapter/src/config.ts
Generic solution that replaces https://github.com/salto-io/salto/pull/2856:
When using simple adapters to only generate types for `supportedTypes`, we did not consider the types listed in `recurseInto` to be subtypes. 
Note that we now list all `recurseInto` types as subtypes, regardless of whether they are used by `supportedTypes` or not.
---
Adapter-components:
* Fixed bug where if `supportedTypes` was enabled, `recurseInto` might break because its types were not considered as subtypes
Stripe adapter:
* Fix a recent regression that caused `product` instances to be omitted
---
None (not deployed yet)
=> SALTO-2130 Treat recurseInto types as subtypes when restricting types to only include supported types

packages/netsuite-adapter/e2e_test/adapter.test.ts, packages/netsuite-adapter/package.json, packages/netsuite-adapter/src/adapter.ts, packages/netsuite-adapter/src/change_validator.ts, packages/netsuite-adapter/src/change_validators/account_features.ts, packages/netsuite-adapter/src/client/client.ts, packages/netsuite-adapter/src/client/sdf_client.ts, packages/netsuite-adapter/src/constants.ts, packages/netsuite-adapter/src/errors.ts, packages/netsuite-adapter/src/filters/account_features.ts, packages/netsuite-adapter/src/group_changes.ts, packages/netsuite-adapter/src/query.ts, packages/netsuite-adapter/src/transformer.ts, packages/netsuite-adapter/src/types.ts, packages/netsuite-adapter/src/types/configuration_types.ts, packages/netsuite-adapter/test/adapter.test.ts, packages/netsuite-adapter/test/change_validators/account_features.test.ts, packages/netsuite-adapter/test/client/client.test.ts, packages/netsuite-adapter/test/client/sdf_client.test.ts, packages/netsuite-adapter/test/filters/account_features.test.ts, packages/netsuite-adapter/test/transformer.test.ts, packages/netsuite-adapter/test/types.test.ts, yarn.lock
Support new type using SDF - `accountFeatures`. This type represent the features in the NetSuite account.
Both fetch and deploy are supported, also partial success deploy (when some features fails and some succeed)
---
Netsuite-Adapter:
- Supporting fetch and deploy on new settings type using SDF - `accountFeatures`
---
Netsuite - new settings type and instance will be added to the workspace - `accountFeatures`.
Instance example: `netsuite/Settings/accountFeatures.nacl`
```
netsuite.accountFeatures {
features = {
DEPARTMENTS = {
label = "Departments"
id = "DEPARTMENTS"
status = "ENABLED"
}
LOCATIONS = {
label = "Locations"
id = "LOCATIONS"
status = "ENABLED"
}
}
}
```
=> SALTO-1387 support account features: fetch and deploy

docs/faq.md
Fixed documentation links in the FAQ to reflect all supported services, and correctly link to pages instead of hard-coded link to "master" branch.
---
N/A
---
Fixed FAQ documentation links to correctly point at service documentation pages
---
N/A
=> Fixing documentation FAQ service links

packages/workspace/src/workspace/workspace.ts
_Perform update workspace on all the envs_
---
Background on the issue:
There was a bug in the code that caused changes that were done only on the state and not on the workspace, to not update the whole cache (only update the state level cache but not the workspace level cache). The reason for that is that we skipped running the update cache mechanism on envs that didn't have nacl changes. We changed the behavior to always update the cache of all the envs. We did a test to check if it causes a performance issue, and it didn't
---
_None_
---
_None_
=> SALTO-2125: perform update workspace on all the envs

packages/workspace/src/parser/internal/native/errors.ts, packages/workspace/src/parser/internal/native/lexer.ts, packages/workspace/src/parser/internal/native/parse.ts, packages/workspace/test/parser/errors.test.ts
Instead of showing a long list of parse errors, we should show clear indications that there are conflicts that should be resolved in the error panel. We have now those git markers as part of the files after an operation that caused conflicts are done but the error panel today shows multiple errors per such conflict and the error message is not clear
---
* The way to verify git conflict is verifying token with '<' (x7) and then recovering for '=' (x7) and recovering again for '>' (x7)
* All the errors of a merge conflict file are dropped
* In case salto detects only the beginning string of a conflict and can't find the rest of the conflict strings - an invalid error will be raised and the file won't be scanned again
---
* Users now will …
=> SAAS-3619-identify-and-alert-for-merge-conflicts

packages/core/src/local-workspace/remote_map.ts, packages/workspace/src/workspace/nacl_files/elements_cache.ts, packages/workspace/src/workspace/workspace.ts
Also fixed empty log in workspace
---
Hopefully this will help debugging future issues with caches by at least providing some information about when connections are flushed and closed and what hash we had each time
---
_None_
---
_None_
=> Add logs for remote maps

packages/salesforce-adapter/src/transformers/transformer.ts
Seems like the restrictions from the documentation are sometimes inaccurate
Making them non-enforcing to avoid false positive warnings
---
---
- Avoid false warnings on "visibleLines" values
---
- On the next fetch, `enforce_value = false` will be added to several elements in the `annotationTypes.nacl` file
=> SALTO-1334: Make numeric restrictions non enforcing in salesforce

packages/zendesk-support-adapter/src/adapter.ts, packages/zendesk-support-adapter/src/config.ts, packages/zendesk-support-adapter/src/filters/field_references.ts, packages/zendesk-support-adapter/src/filters/reorder/automation.ts, packages/zendesk-support-adapter/src/filters/reorder/creator.ts, packages/zendesk-support-adapter/src/filters/reorder/sla_policy.ts, packages/zendesk-support-adapter/test/adapter.test.ts, packages/zendesk-support-adapter/test/filters/reorder/automation.test.ts
_support ordering of automations_
---
None
---
* Add automation order element
---
_A new automation order element will appear_
=> SALTO-2149: support reorder of automations
