salto-io/salto

- packages/hubspot-adapter/src/client/client.ts
- packages/hubspot-adapter/src/transformers/transformer.ts
- packages/hubspot-adapter/test/filters/useridentifier.test.ts
Fix an issue with transformPrimitives not handling JSON cause it's not a primitive value & use this PR to take advantage of the new multi-line feature for JSON's
> Hubspot - fix JSON

- packages/adapter-utils/src/utils.ts
- packages/adapter-utils/test/utils.test.ts
- packages/hubspot-adapter/src/adapter.ts
- packages/salesforce-adapter/e2e_test/adapter.test.ts
- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/transformers/xml_transformer.ts
- packages/salesforce-adapter/test/transformers/transformer.test.ts
- packages/salesforce-adapter/test/transformers/xml_transformer.test.ts
Enhance the adapter-utils functions that were used for ReferenceRestore/Resolve to also support StaticFiles
> StaticFiles resolve & restore

- packages/netsuite-adapter/package.json
- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/test/client/client.test.ts
- yarn.lock
related to https://github.com/salto-io/netsuite-suitecloud-sdk/pull/7
> Netsuite: control SDF log and spinner verbosity based on Salto's log level

- packages/core/src/core/validator.ts
- packages/core/src/serializer/elements.ts
- packages/core/src/workspace/local/dir_store.ts
- packages/core/src/workspace/local/workspace.ts
- packages/core/src/workspace/static_files/common.ts
- packages/core/src/workspace/static_files/functions.ts
- packages/core/src/workspace/static_files/source.ts
- packages/core/test/validator.test.ts
- packages/core/test/workspace/local/directory_store.test.ts
- packages/core/test/workspace/static_files/common.test.ts
- packages/core/test/workspace/static_files/source.test.ts
Prevent access to files outside of the base dir of a local dir store.
> SALTO-752 No access outside of local dir store

- packages/cli/e2e_test/helpers/workspace.ts
- packages/cli/src/commands/fetch.ts
- packages/cli/src/index.ts
- packages/cli/src/telemetry.ts
- packages/cli/src/types.ts
- packages/cli/test/commands/fetch.test.ts
- packages/cli/test/mocks.ts
- packages/core/index.ts
- packages/core/src/app_config.ts
- packages/core/src/workspace/dir_store.ts
- packages/core/src/workspace/local/dir_store.ts
- packages/core/src/workspace/nacl_files/mutil_env/multi_env_source.ts
- packages/core/src/workspace/nacl_files/nacl_files_source.ts
- packages/core/src/workspace/static_files/common.ts
- packages/core/src/workspace/static_files/source.ts
- packages/core/src/workspace/workspace.ts
- packages/core/test/common/nacl_file_source.ts
- packages/core/test/common/nacl_file_store.ts
- packages/core/test/workspace/local/directory_store.test.ts
- packages/core/test/workspace/multi_env/multi_env_source.test.ts
- packages/core/test/workspace/nacl_files/nacl_files_source.test.ts
- packages/core/test/workspace/static_files/common.test.ts
- packages/core/test/workspace/static_files/source.test.ts
Currently, there are not tests. They will be added after the first cr
> SALTO-709-add log and telemetry for workspace size - without tests

- docs/salto_configuration.md
- docs/telemetry.md
@gilhoffer , I wasn't sure what exactly I should add. If I missed something, please lmk
> add docs for size of workspace collection

- packages/adapter-utils/src/utils.ts
- packages/adapter-utils/test/utils.test.ts
- packages/core/src/workspace/hidden_values.ts
- packages/core/test/workspace/hidden_values.test.ts
- Changed transformElement to call the callback on every field
- Added support for hiding fields with complex types and not only primitive
> Support hiding complex fields

- packages/adapter-api/src/values.ts
- packages/adapter-api/test/values.test.ts
- packages/adapter-utils/src/utils.ts
- packages/adapter-utils/test/utils.test.ts
- packages/core/src/serializer/elements.ts
- packages/core/src/workspace/static_files/source.ts
- packages/core/test/core/expressions.test.ts
- packages/core/test/serializer/serializer.test.ts
- packages/core/test/validator.test.ts
- packages/core/test/workspace/static_files/common.test.ts
- packages/core/test/workspace/static_files/functions.test.ts
- packages/hubspot-adapter/src/transformers/transformer.ts
- packages/hubspot-adapter/test/change_validators/json_type.test.ts
- packages/hubspot-adapter/test/change_validators/readonly.test.ts
- packages/salesforce-adapter/e2e_test/adapter.test.ts
- packages/salesforce-adapter/src/transformers/xml_transformer.ts
Make parameters more explicit to help adapter integrators
> SALTO-777 Alter StaticFile constructor

- packages/salesforce-adapter/src/constants.ts
- packages/salesforce-adapter/src/filters/custom_objects.ts
- packages/salesforce-adapter/src/transformers/transformer.ts
- packages/salesforce-adapter/test/transformers/transformer.test.ts
so the special Name cases are handled properly
> Improve the compoundFields heuristic 

- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/test/client/client.test.ts
Please review this one along with https://github.com/salto-io/netsuite-suitecloud-sdk/pull/8
> Netsuite: set SDF log level using Salto's log level

- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/test/client/client.test.ts
- packages/netsuite-adapter/test/client/client.ts
fixes https://github.com/oracle/netsuite-suitecloud-sdk/issues/140
> Netsuite uppercase account ID and use extended authID

- packages/salesforce-adapter/src/filters/instance_references.ts
Just a couple more references needed for a demo
> add more hard coded references

- packages/salesforce-adapter/src/filters/missing_fields.json
Definition from: https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_report.htm
> add missing operator in report filter item

- packages/cli/package.json
- packages/cli/package_native.js
- yarn.lock
update location for nexe binaries after old location stopped working
> fix: nexe binaries location

- packages/logging/src/internal/pino.ts
- packages/logging/test/console.ts
- packages/logging/test/internal/pino_logger.test.ts
- no line separator between logs in text mode
- browser issues
> fix: logging with pino bugs

- packages/core/test/workspace/local/cache.test.ts
- packages/vscode/test/salto/workspace.ts
- packages/workspace/src/parser/parse.ts
- packages/workspace/src/serializer/parse_result.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/test/workspace/cache.test.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
Still needs tests, and probably some refactoring - but I'd be happy if ya'll can have a look at the general idea until I'll add them :)
> WIP - parse files only when sourcemap is needed

- packages/cli/src/commands/restore.ts
The current code works, but it seems like generally [using `this` in object functions is a bit delicate](https://www.codementor.io/@dariogarciamoya/understanding-this-in-javascript-with-arrow-functions-gcpjwfyuc).
for example, if we changed it to arrow functions like we use in most of our code it would suddenly stop working.
Suggesting this small refactor to use closure instead so this code better fits the style of the rest of our code
(the code inside `applyRestoreChangesToWorkspace` is unchanged)
> avoid using this in object functions

- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/change_validators/custom_object_instances.ts
- packages/salesforce-adapter/src/filters/custom_object_instances_references.ts
- packages/salesforce-adapter/test/filters/custom_object_instances_references.test.ts
Replace `Lookup` / `MasterDetail` values (Id's) with references to the instance if it exists
> Add Custom Object instance to instance references filter

- packages/adapter-api/package.json
- packages/adapter-utils/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/dag/package.json
- packages/e2e-credentials-store/package.json
- packages/hubspot-adapter/package.json
- packages/lang-server/package.json
- packages/logging/package.json
- packages/lowerdash/package.json
- packages/monitoring/package.json
- packages/netsuite-adapter/package.json
- packages/salesforce-adapter/package.json
- packages/vscode/package.json
- packages/workspace/package.json
- yarn.lock
https://github.com/advisories/GHSA-p6mc-m468-83gw
> Update lodash version

- packages/cli/e2e_test/helpers/workspace.ts
- packages/cli/e2e_test/multi_env.test.ts
- packages/cli/e2e_test/salto.test.ts
telemetry was not stopped, causing jest to hang on end of tests when running locally.
> fix: e2e tests hang

- docs/salto_configuration.md
- docs/user_guide.md
- Fixed all salto to Salto for consistency
- Added link for SFDC dev account creation
> Fixes to few minor documentation issues

- packages/workspace/src/validator.ts
- packages/workspace/test/validator.test.ts
Related to https://salto-io.atlassian.net/browse/SALTO-889
> Do not print complex values upon validations

- packages/dag/src/group.ts
- packages/dag/src/nodemap.ts
- packages/dag/test/nodemap.test.ts
- packages/lowerdash/src/collections/map.ts
- packages/lowerdash/test/collections/map.test.ts
leftovers from #1272 which was closed
> minor refactor to dag

- packages/cli/src/commands/demote.ts
- packages/cli/src/commands/index.ts
- packages/cli/src/commands/promote.ts
Also moved the text help for diff to be last
> fixed minor language issues in the text help for promote/demote

- packages/core/src/api.ts
- packages/core/src/local-workspace/state.ts
- packages/core/test/api.test.ts
- packages/core/test/common/state.ts
- packages/core/test/workspace/local/state.test.ts
- packages/workspace/src/workspace/path_index.ts
- packages/workspace/src/workspace/state/in_mem.ts
- packages/workspace/src/workspace/state/state.ts
- packages/workspace/test/workspace/path_index.test.ts
- packages/workspace/test/workspace/state.test.ts
@noamhammer Please CR :)
Resolve: [SALTO-833]
[SALTO-833]: https://salto-io.atlassian.net/browse/SALTO-833
> Don't delete existing service state when fetching from other services

- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/workspace.test.ts
We shouldn't modify the original `change` object when removing hidden fields.
> Avoid modifying changes in-place when hiding fields

- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/workspace.test.ts
> fixed workspace methods that use the nacl file source (SALTO-927)

- packages/lang-server/src/location.ts
- packages/lang-server/test/location.test.ts
Release Notes: Symbol search now works on fields as well
> support symbol search on fields

- packages/salesforce-adapter/src/filters/custom_objects.ts
- packages/salesforce-adapter/src/transformers/transformer.ts
Release notes - 
* Bug fix: Single valued valueSets are now fetched as a list.
> Handle the single element case in valueSet

- packages/salesforce-adapter/example-cpq-config.md
Based on meeting with Snyc + making sure it makes sense as a general case
> Update CPQ default configuration according to new learnings

- packages/workspace/src/expressions.ts
- packages/workspace/test/core/expressions.test.ts
this fix prevents the resolve function from creating additional "deepClone" duplicates
of every field, instance and annotation type.
also fixed resolve to preserve type links so instance type will point to the
resolved type rather than the original type
---
_Release notes_:
- Improvements to Salto core memory consumption
> Fix resolve expression creating copies of instance and field types

- packages/core/src/local-workspace/dir_store.ts
Context: [getParsedNaclFiles](https://github.com/salto-io/salto/blob/5922a7e36aa14f04a34ed49d9d67d43918a142a7/packages/workspace/src/workspace/nacl_files/nacl_files_source.ts#L136-L139) and [parseNaclFiles](https://github.com/salto-io/salto/blob/5922a7e36aa14f04a34ed49d9d67d43918a142a7/packages/workspace/src/workspace/nacl_files/nacl_files_source.ts#L120-L125) seem to be optimized for parsing in-memory, and in the current logs there isn't an easy way to tell how much of `getParsedNaclFiles` was spent in `await naclFilesStore.getFiles()` and how much was in `parseNaclFiles()`. 
Hopefully this added log line will help us figure out if it's worth optimizing the file reads further (such as - first `stat` files without reading their data until we check if we can [get them from the …
> Track the time it takes to read file batches from disk

- packages/monitoring/src/index.ts
use regex for state file path after spliting it to state file per service
> use regex for state file path 

- packages/salesforce-adapter/src/filters/custom_objects.ts
- packages/salesforce-adapter/src/filters/field_references.ts
- packages/salesforce-adapter/src/filters/utils.ts
- packages/salesforce-adapter/src/transformers/reference_mapping.ts
- packages/salesforce-adapter/test/filters/field_references.test.ts
Leftover from https://github.com/salto-io/salto/pull/1434#discussion_r487493920 + additional cleanups
> SALTO-942 - Use parent apiName instead of recomputing, improve tests

- packages/e2e-credentials-store/src/cli/commands/register.ts
- packages/e2e-credentials-store/src/types.ts
- packages/e2e-credentials-store/test/cli/index.test.ts
- packages/netsuite-adapter/e2e_test/credentials_store/adapter.ts
- packages/salesforce-adapter/e2e_test/credentials_store/adapter.ts
- packages/salesforce-adapter/src/client/client.ts
Adding salesforce oauth credentials to all credentials under the lease. So that future e2e tests can use these
> Add connected app to salesforce creds

- packages/netsuite-adapter/package.json
- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/test/client/client.test.ts
- yarn.lock
Please review only the last commit. Others are included in another PR.
> Netsuite: don't reuse auth Id to avoid skipping the token validation upon SDF project creation

- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/test/client/client.test.ts
Please review only the last commit, the others are included in other PRs
> Netsuite: Accelerate the fetch time when fetchAllTypesAtOnce is set to false by fetching long types first

- packages/salesforce-adapter/e2e_test/credentials_store/adapter.ts
Small fix dropped from earlier commit by mistake
@royra
> A couple of fixes to Roy CR that should've been in ealrier commit

- packages/salesforce-adapter/src/filters/field_references.ts
- packages/salesforce-adapter/src/transformers/reference_mapping.ts
> SALTO-988 - Add more workflow references

- packages/core/src/core/plan/filter.ts
- packages/core/test/core/plan/plan.test.ts
Before this change, deploy would just silently omit the changes involved in the circle
with this, it will fail and emit a somewhat useful warning to the user
---
- Fix bug where invalid deploy plans would show up as empty instead of showing an error
> SALTO-983: Fail deploy if plan has circular dependency

- packages/cli/e2e_test/helpers/workspace.ts
- packages/cli/e2e_test/salto.test.ts
- packages/cli/src/commands/clean.ts
- packages/cli/src/commands/index.ts
- packages/cli/src/formatter.ts
- packages/cli/src/prompts.ts
- packages/cli/test/commands/clean.test.ts
- packages/cli/test/mocks.ts
- packages/core/src/api.ts
- packages/core/src/core/clean.ts
- packages/core/src/local-workspace/dir_store.ts
- packages/core/src/local-workspace/static_files_cache.ts
- packages/core/src/local-workspace/workspace.ts
- packages/core/test/api.test.ts
- packages/core/test/core/clean.test.ts
- packages/core/test/workspace/local/directory_store.test.ts
- packages/core/test/workspace/local/static_files_cache.test.ts
- packages/core/test/workspace/local/workspace.test.ts
- packages/file/src/file.ts
- packages/file/test/file.test.ts
- packages/workspace/index.ts
- packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/src/workspace/state/in_mem.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
- packages/workspace/test/workspace/workspace.test.ts
Support clearing out different parts of the workspace (see ticket for full details).
> SALTO-986 - Add clean command

- packages/salesforce-adapter/README.md
@gilhoffer as per your request, please approve this :)
> add documentation for oauth credentials

- packages/core/src/core/deploy.ts
- packages/core/test/api.test.ts
This fixes an issue where if an adapter returns partial success from deploy, the applied changes are not updated in the state / nacls
This can currently happen only in custom object instance deployment in salesforce (the only scenario we have where an adapter can return partial success)
---
Salesforce:
- Fix issue where changes that were partially deployed were not updated in the state file, causing the state file to become out of sync with the service
> Update state with partial success in deploy

- docs/salto_configuration.md
- packages/netsuite-adapter/config_doc.md
- packages/salesforce-adapter/src/config_doc.md
Please LMK if you think that we should have an empty page for HubSpot or we should leave it as is.
> SALTO-989: add documentation for adapters configuration

- packages/netsuite-adapter/package.json
- yarn.lock
The SDF version contains a fix for https://github.com/node-fetch/node-fetch/issues/450
> Netsuite: bump SDF to fix node-fetch issue

- packages/salesforce-adapter/e2e_test/custom_object_instances.test.ts
- packages/salesforce-adapter/e2e_test/utils.ts
- packages/salesforce-adapter/index.ts
- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/constants.ts
- packages/salesforce-adapter/src/custom_object_instances_deploy.ts
- packages/salesforce-adapter/src/filters/custom_objects_instances.ts
- packages/salesforce-adapter/src/filters/custom_settings_filter.ts
- packages/salesforce-adapter/src/transformers/transformer.ts
- packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
- packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
- packages/salesforce-adapter/test/filters/custom_settings_filter.test.ts
- yarn.lock
@adamro This is my commit for uploading settings. I would appreciate a cr.
Note that currently I only upload settings of the "list" type, because Hierarchical settings raise different issues.
> Copy list settings instances

- packages/salesforce-adapter/src/client/client.ts
@ori-moisis  @netama one of you could take a look at this :)
> Solve [SALTO-1013] - suppress error in split retry mechanism

- packages/adapter-api/src/values.ts
- packages/adapter-api/test/values.test.ts
> [SALTO-1009] ignore newline differences in diff

- packages/cli/src/cli.ts
- packages/cli/src/index.ts
- packages/cli/test/mocks.ts
- packages/workspace/src/workspace/workspace.ts
> SALTO-857: added logs for workspace id, installation id, and os properties

- packages/workspace/src/workspace/element_selector.ts
- packages/workspace/test/element_selector.test.ts
small fix, no ticket that fits it
> fix regex usage in element selectors

- packages/lang-server/src/workspace.ts
Release notes: add caching of the workspace errors in the extension
> cache workspace errors

- packages/workspace/src/parser/internal/native/errors.ts
- packages/workspace/src/parser/internal/native/parse.ts
- packages/workspace/src/parser/internal/native/types.ts
- packages/workspace/src/parser/internal/nearly/parse.ts
- packages/workspace/src/parser/parse.ts
- packages/workspace/src/parser/types.ts
> moved multiple parserResult definitions to one file

- packages/adapter-api/src/builtins.ts
- packages/adapter-api/src/core_annotations.ts
- packages/adapter-api/src/element_id.ts
- packages/adapter-api/test/elements.test.ts
- packages/adapter-utils/src/utils.ts
- packages/adapter-utils/test/utils.test.ts
- packages/core/test/core/plan/dependency.test.ts
- packages/dummy-adapter/src/generator.ts
- packages/lang-server/test/completions.test.ts
- packages/salesforce-adapter/src/filters/custom_objects.ts
- packages/salesforce-adapter/src/filters/extra_dependencies.ts
- packages/salesforce-adapter/src/filters/utils.ts
- packages/salesforce-adapter/test/filters/custom_objects.test.ts
- packages/salesforce-adapter/test/filters/extra_dependencies.test.ts
- packages/salesforce-adapter/test/filters/field_references.test.ts
- packages/salesforce-adapter/test/filters/layouts.test.ts
- packages/workspace/src/workspace/hidden_values.ts
- packages/workspace/test/parser/dump.test.ts
- packages/workspace/test/validator.test.ts
- packages/workspace/test/workspace/workspace.test.ts
Added support for hidden annotation in element instances.
---
_Relese Notes:_ None
> SALTO-1042: support hidden instances

- packages/workspace/src/workspace/hidden_values.ts
In order to get full elements that include the hidden parts from the state, the `mergeWithHidden` logic relies on generating elements containing only the hidden parts. This relies on traversing each relevant element twice - first to find all the hidden paths, and then to create an element with just these parts. 
This PR speeds up generating the hidden elements by adjusting how we index the hidden paths in the first traversal.
---
Improve workspace load speed
> improve performance of merging with hidden elements

- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/filters/custom_objects.ts
- packages/salesforce-adapter/src/filters/hardcoded_lists.json
- packages/salesforce-adapter/src/filters/missing_fields.json
- packages/salesforce-adapter/src/filters/workflow.ts
- packages/salesforce-adapter/src/transformers/reference_mapping.ts
- packages/salesforce-adapter/test/filters/custom_objects.test.ts
* Added missing references: entryStartDateField , SObjectType
* Added some missing fields
* Changed the path of workflow actions
> SALTO-763: EntitlementProccess missing fields & references

- packages/adapter-api/src/change.ts
- packages/adapter-utils/test/common.ts
- packages/core/test/core/plan/dependency.test.ts
- packages/netsuite-adapter/test/group_changes.test.ts
- packages/salesforce-adapter/test/group_changes.test.ts
> make toChange function more strictly typed

- docs/user_guide.md
- packages/cli/src/commands/deploy.ts
- packages/cli/src/commands/element.ts
- packages/cli/src/commands/env.ts
- packages/cli/src/commands/fetch.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/commands/restore.ts
- packages/cli/src/commands/service.ts
This is basically a https://github.com/salto-io/salto/pull/1674 with a fix
> Finalize new CLI copy and docs

- packages/cli/src/commands/deploy.ts
Before this change we could exceed the allowed number of open files if we had a lot of errors on deploy because `transformToWorkspaceError` internally opens a file to get the source map)
After this change it may still take a long time to format all the errors but hopefully we won't crash because of it.
---
We should probably limit the number of errors we show like this because if we really do have a lot of errors this transform will take a very long time (and printing >1000 errors to the terminal isn't really useful).
For now this PR only fixes the issue with crashing due to the number of open files
None
> Limit concurrency of error transform on deploy

- packages/lang-server/package.json
- packages/lang-server/src/token.ts
- packages/lang-server/tsconfig.json
- packages/workspace/package.json
- packages/workspace/src/parser/index.ts
- packages/workspace/src/parser/parse.ts
- packages/workspace/test/parser/parse.test.ts
Made necessary changes, so we won't need @types/moo to be a dependency and moved it to dev dependencies
---
> moved @types/moo from dependencies to dev dependencies

- packages/core/src/core/diff.ts
- packages/core/test/core/diff.test.ts
- packages/workspace/index.ts
Use selectors to produce the old behavior of diff command.
> Fix SALTO-1079 - selector functioning in diff command

- packages/adapter-api/src/builtins.ts
- packages/adapter-utils/src/utils.ts
- packages/salesforce-adapter/src/filters/elements_url.ts
- packages/workspace/src/workspace/hidden_values.ts
- packages/workspace/test/workspace/hidden_values.test.ts
Fixed the bug causing duplicates errors in https://salto-io.atlassian.net/browse/SAAS-1156
---
> fixed hidden annotations in fields

- packages/core/package.json
- packages/marketo-adapter/package.json
- yarn.lock
Also did some cleanup on marketo adapter package.json to remove unused packages
---
None
> SALTO-1119: Update axios version to fix security vulnerability

- packages/adapter-api/src/adapter.ts
- packages/cli/e2e_test/helpers/salesforce.ts
- packages/core/src/core/deploy.ts
- packages/core/src/core/fetch.ts
- packages/core/test/api.test.ts
- packages/core/test/core/fetch.test.ts
- packages/dummy-adapter/src/adapter.ts
- packages/dummy-adapter/src/generator.ts
- packages/dummy-adapter/test/adapter.test.ts
- packages/dummy-adapter/test/generator.test.ts
- packages/hubspot-adapter/src/adapter.ts
- packages/hubspot-adapter/test/adapter.test.ts
- packages/marketo-adapter/src/adapter.ts
- packages/netsuite-adapter/e2e_test/adapter.test.ts
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/salesforce-adapter/e2e_test/adapter.test.ts
- packages/salesforce-adapter/e2e_test/custom_object_instances.test.ts
- packages/salesforce-adapter/e2e_test/utils.ts
- packages/salesforce-adapter/e2e_test/workflow.test.ts
- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/test/adapter.crud.test.ts
- packages/salesforce-adapter/test/adapter.discover.test.ts
- packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
- packages/salesforce-adapter/test/filters/filters.test.ts
The build of SAAS does not work with the new progress changes and I need to update to OSS version in SAAS. To create a version that can be built with the SAAS I want to revert these changes and return the changes after I update the OSS in the SAAS.
> revert progress changes

- packages/cli/src/command_builder.ts
- packages/cli/test/command_builder.test.ts
Ensure a command doesn't define two flags with the same name or alias
---
None
> Add conflict validation for CLI flags

- packages/adapter-api/src/adapter.ts
- packages/cli/e2e_test/helpers/salesforce.ts
- packages/core/src/core/deploy.ts
- packages/core/src/core/fetch.ts
- packages/core/test/api.test.ts
- packages/core/test/core/fetch.test.ts
- packages/dummy-adapter/src/adapter.ts
- packages/dummy-adapter/src/generator.ts
- packages/dummy-adapter/test/adapter.test.ts
- packages/dummy-adapter/test/generator.test.ts
- packages/hubspot-adapter/src/adapter.ts
- packages/hubspot-adapter/test/adapter.test.ts
- packages/marketo-adapter/src/adapter.ts
- packages/netsuite-adapter/e2e_test/adapter.test.ts
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/salesforce-adapter/e2e_test/adapter.test.ts
- packages/salesforce-adapter/e2e_test/custom_object_instances.test.ts
- packages/salesforce-adapter/e2e_test/utils.ts
- packages/salesforce-adapter/e2e_test/workflow.test.ts
- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/test/adapter.crud.test.ts
- packages/salesforce-adapter/test/adapter.discover.test.ts
- packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
- packages/salesforce-adapter/test/filters/filters.test.ts
Restore the changes made in https://github.com/salto-io/salto/pull/1738
---
> Restore progress changes

- packages/netsuite-adapter/scripts/types_generator.py
- packages/netsuite-adapter/src/filters/convert_lists.ts
- packages/netsuite-adapter/src/types/custom_types/customsegment.ts
Release Notes:
Return consistent order for customsegment inner lists.
> Netsuite - order customsegment inner lists

- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/netsuite-adapter/test/client/client.test.ts
Changed Netsuite adapter to fetch objects by chunks of objects ids instead of by types:
---
Performance improvement for fetch
> changed to fetch from Netsuite by ids instead of types

- packages/adapter-api/src/values.ts
- packages/adapter-utils/src/utils.ts
- packages/core/src/core/fetch.ts
- packages/core/src/core/plan/plan.ts
- packages/core/test/core/list.test.ts
- packages/dummy-adapter/src/generator.ts
- packages/dummy-adapter/test/generator.test.ts
- packages/salesforce-adapter/e2e_test/adapter.test.ts
- packages/salesforce-adapter/e2e_test/custom_object_instances.test.ts
- packages/salesforce-adapter/e2e_test/utils.ts
- packages/salesforce-adapter/e2e_test/workflow.test.ts
- packages/salesforce-adapter/src/filters/custom_object_split.ts
- packages/workspace/src/expressions.ts
- packages/workspace/src/validator.ts
- packages/workspace/src/workspace/cache.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/workspace.test.ts
adapter e2e passes
manual fetch + deploy a custom object works on sf adapter
still have an issue with fetching updates
> fixed salesforce adapter e2e

- packages/dummy-adapter/src/generator.ts
_fixed dummy adapter trys to create array with negative length_
---
_The normal random function could return negative numbers, which makes no sense in the context of the dummy adapter_
---
_NA_
> fixed dummy adapter trys to create array with negative length

- packages/cli/e2e_test/helpers/workspace.ts
- packages/cli/e2e_test/salto.test.ts
- packages/core/src/api.ts
- packages/core/src/core/fetch.ts
- packages/core/test/api.test.ts
- packages/core/test/core/fetch.test.ts
- packages/workspace/src/workspace/nacl_files/addition_wrapper.ts
- packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
- packages/workspace/src/workspace/nacl_files/nacl_file_update.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
> Fix cli e2e sanity

- packages/workspace/src/expressions.ts
Add resolveElement handling for containerTypes
---
None
> Add containerTypes to resolveElement

- packages/core/index.ts
for future use in the SaaS Tracker in order to filter out hidden changes
---
None
> Export createDiffChanges

- packages/cli/src/commands/element.ts
- packages/cli/test/commands/element.test.ts
- packages/core/.eslintignore
- packages/core/src/core/diff.ts
- packages/core/test/core/diff.test.ts
- packages/lowerdash/src/collections/asynciterable.ts
- packages/lowerdash/test/collections/asynciterable.test.ts
- packages/workspace/src/workspace/element_selector.ts
- packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/element_selector.test.ts
- packages/workspace/test/workspace/multi_env/multi_env_source.test.ts
Make diff work with element ids for top level elements.
> Async element selector

- packages/core/src/core/fetch.ts
_fixed nested additions are not recognised as nested additions during fetch_
---
_During a fetch we use a map to with a single value to map an elemID to all of the fetched fragments resulting in data lost. Fixed it to hold a map to an array of elements,_
---
_NA_
> fixed information lost when creating fetch elemID getter

- packages/salesforce-adapter/test/client.test.ts
Avoid leaving unresolved promises after tests
---
_None_
> Cleanup salesforce client tests

- packages/hubspot-adapter/src/client/client.ts
- packages/hubspot-adapter/test/client.test.ts
- Add missing await in fetch code
- Fix test to mock more connection methods that are required for the tested flow
---
Found unhandled promise rejection while trying to update jest version
---
_None_ (no real user impact)
> Add missing await in hubspot fetch code

- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/constants.ts
- packages/netsuite-adapter/src/filters/consistent_values.ts
- packages/netsuite-adapter/test/filters/consistent_values.test.ts
---
Return consistent recordType value for Journal TransactionForm & Discount/Markup EntryForms
> SALTO-1152 - Netsuite: return consistent values when SDF is inconsistent

- packages/lowerdash/src/collections/tree_map.ts
- packages/lowerdash/test/collections/tree_map.test.ts
Expose the root of the TreeMap via it's public API
> expose treemap root

- packages/workspace/src/merger/internal/common.ts
- packages/workspace/src/serializer/elements.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/serializer/serializer.test.ts
Split deserialization function into two: One that deserializes elements and one that deserializes Merge errors
---
---
None
> split deserialization function

- packages/cli/e2e_test/multi_env.test.ts
- packages/dummy-adapter/src/generator.ts
- packages/dummy-adapter/test/generator.test.ts
- packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
- packages/workspace/test/workspace/multi_env/routers.test.ts
> Rocksdb multi env fix

- packages/netsuite-adapter/package.json
- yarn.lock
> SAAS-1310: Bump SDF to 1.1.2-salto-2 to unwrap exception correctly

- packages/netsuite-adapter/package.json
- yarn.lock
> SAAS-1310: Bump SDF to 1.1.2-salto-3 to unwrap exception correctly # 2

- packages/adapter-utils/src/utils.ts
- packages/adapter-utils/test/utils.test.ts
- packages/core/src/core/restore.ts
- packages/core/src/local-workspace/remote_map.ts
- packages/core/src/local-workspace/state.ts
- packages/core/src/local-workspace/workspace.ts
- packages/core/test/api.test.ts
- packages/core/test/common/state.ts
- packages/core/test/common/workspace.ts
- packages/core/test/core/restore.test.ts
- packages/core/test/workspace/local/remote_map.test.ts
- packages/core/test/workspace/local/state.test.ts
- packages/core/test/workspace/local/workspace.test.ts
- packages/workspace/src/serializer/elements.ts
- packages/workspace/src/workspace/elements_source.ts
- packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
- packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/src/workspace/path_index.ts
- packages/workspace/src/workspace/remote_map.ts
- packages/workspace/src/workspace/state/in_mem.ts
- packages/workspace/src/workspace/state/state.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/utils.ts
- packages/workspace/test/workspace/elements_source.test.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
- packages/workspace/test/workspace/path_index.test.ts
- packages/workspace/test/workspace/remote_map.test.ts
- packages/workspace/test/workspace/state.test.ts
- packages/workspace/test/workspace/workspace.test.ts
state to use remote map
---
---
None
> state to use remote map

- packages/salesforce-adapter/src/filters/extra_dependencies.ts
- packages/salesforce-adapter/test/filters/extra_dependencies.test.ts
Edit: Adding a temporary workaround until we switch to using bulk API v2 for this - making individual requests for some of the more popular referencing types.
Background:
The tooling API response for generated dependencies does not return all the data for large accounts - it's limited at 2000, and sometimes returns even fewer entries than that, which is not always enough to cover accounts with many references. This is a limitation of the tooling API SOAP/REST endpoints, and can be solved by switching to bulk API v2 - but that API has some limitations, so we're starting with a small improvement to help us cover more types in a small number of queries, until we fully switch to the bulk API.
This only impacted the generated dependencies annotation, since it's the only one using the tooling …
> SALTO-1162 - Split extra_dependencies queries for specific types

- packages/core/src/core/diff.ts
Accelerate restore & diff commands when it has wildcard in the selector.
The following command took several minutes and now takes 2 seconds for a regular dev env:
```salto restore -d salesforce.*```
Improve the performance of diff & restore commands when using wildcards in the element selector definition.
> SALTO-1160: fix performance issue in createDiffChanges when using selectors with wildcards

- packages/salesforce-adapter/src/custom_object_instances_deploy.ts
- packages/salesforce-adapter/test/custom_object_instances.crud.test.ts
Improve the Error msg and logging in the CustomObject Instances deploy flow
---
Salesforce Adapter: Improve the Error messages presented when deploying CustomObject Instances with failures
> Improve CustomObjectInstances deploy error info presented

- packages/workspace/src/serializer/elements.ts
Small changes in serialization implementaiton to improve performance
---
This is part of the move to rocksdb, which requires improving serialization performance
---
Release Notes: 
hopefully somewhat improved performance of all commands?
> optimization to serializer

- packages/salesforce-adapter/src/client/client.ts
- packages/salesforce-adapter/src/constants.ts
Use the new functions from https://github.com/salto-io/salto/pull/1811 for Salesforce to reduce code duplication.
---
None
> Use shared client utils for Salesforce

- packages/workspace/src/workspace/hidden_values.ts
export removeHiddenFromElement from workspace.hiddenValues module
> SAAS-1384: export remove hidden values from element

- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
Increase read concurrency
---
---
No release notes
> Increase read concurrency

- packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
- packages/workspace/test/common/nacl_file_source.ts
_Remove unneeded getSourceRange call_
---
---
No release notes
> remove unneeded getSourceRange call

- packages/netsuite-adapter/e2e_test/adapter.test.ts
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/netsuite-adapter/test/utils.ts
> SALTO-1199: Report progress for NetSuite adapter so it will be presented in the SaaS

- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/types.ts
- packages/netsuite-adapter/test/client/suiteapp_client.test.ts
Updated the SuiteApp client according to changes made in https://github.com/salto-io/salto_suiteapp/pull/3 and added support for the "sysInfo" operation in the SuiteApp.
---
None
> SALTO-1198: added getSystemInformation functionality

- packages/core/src/core/plan/plan.ts
- packages/core/src/local-workspace/remote_map.ts
- packages/core/test/core/diff.test.ts
- packages/core/test/core/restore.test.ts
- packages/core/test/workspace/local/remote_map.test.ts
- packages/core/test/workspace/local/state.test.ts
- packages/lang-server/test/workspace.ts
- packages/lowerdash/src/collections/asynciterable.ts
- packages/lowerdash/test/collections/asynciterable.test.ts
- packages/workspace/src/workspace/elements_source.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/src/workspace/remote_map.ts
- packages/workspace/test/utils.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.state.test.ts
- packages/workspace/test/workspace/remote_map.test.ts
- packages/workspace/test/workspace/state.test.ts
Changes to remote map operations for performance purposes
> Fix performance merge

- packages/cli/e2e_test/NACL/salto.config/salesforce.nacl
- packages/core/test/workspace/local/workspace_config.test.ts
- packages/salesforce-adapter/config_doc.md
- packages/salesforce-adapter/cpq-config-doc.md
- packages/salesforce-adapter/src/types.ts
_Add EmailTemplate to the deafault skip list_
---
---
_EmailTemplate will be added to the skip list_
> SALTO-1201-add email templates to default skip list

- packages/workspace/src/parser/index.ts
To be used in the SaaS
_Release Notes_: None
> Export Functions type from workspace

- packages/workato-adapter/src/adapter_creator.ts
- packages/workato-adapter/src/auth.ts
> switch workato credentials to type

- packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
_Create a flow that loads the workspace without checking for changed files_
> create a flow that loads the workspace without checking for changed files

- packages/lang-server/src/location.ts
- packages/lang-server/test/location.test.ts
_Add a more strict threshold to the fuzzy search_
---
---
_Elements search will return more relevant results_
> add a more strict threshold to the fuzzy search

- packages/lowerdash/src/collections/asynciterable.ts
- packages/lowerdash/test/collections/asynciterable.test.ts
- Added flatMapAsync, forEachAsync, filterAsync and toAsyncIterable
- Added short type definitions for TypeGuard and Predicate
- Moved findAsync's tests to be under the correct `describe` block
---
Implementations for new functions taken (mostly) from the `lazy_element_intg` branch
---
None
> Lowerdash - Added a few async iterable functions

- packages/core/src/local-workspace/remote_map.ts
- packages/core/test/workspace/local/remote_map.test.ts
- packages/lang-server/src/location.ts
- packages/lang-server/test/location.test.ts
- packages/lang-server/test/workspace.ts
- packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
- packages/workspace/src/workspace/remote_map.ts
- packages/workspace/test/utils.ts
- packages/workspace/test/workspace/remote_map.test.ts
Add remote map get multiple
In addition, changed getFuzzyQueryLocation to return only results for top level elements. We should undo it once @adamro PR is in
> Add remote map get multiple

- packages/salesforce-adapter/src/client/client.ts
Lowering log level of errors in salesforce client
---
Lowering log levels in salesforce client for handled errors.
> SALTO-1214 - lowered log level for salesforce client

- packages/adapter-api/src/element_id.ts
- packages/adapter-api/test/elements.test.ts
- packages/lang-server/src/usage.ts
- packages/lang-server/test/usage.test.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
TODO:
* Add tests to annoType case in the usage 
* Check this actually helps :)
> Change getElemIDUsages to not use ElementsSource + Add annotationType usage

- packages/lang-server/src/workspace.ts
- packages/workspace/jest.config.js
- packages/workspace/src/serializer/elements.ts
- packages/workspace/src/validator.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/serializer/serializer.test.ts
- packages/workspace/test/workspace/workspace.test.ts
_Added iterative validation calculation_
---
_Validation errors are calculated after every nacl files update and cached. The errors are calculated for the changed elements and every element the depends on them or their dependents._
---
> added iterative validation calculation

- packages/workato-adapter/src/filters/cross_service/element_indexes.ts
- packages/workato-adapter/src/filters/cross_service/recipe_references.ts
- packages/workato-adapter/test/filters/recipe_references.test.ts
Extract nested netsuite fields from formulas in workato recipes.
---
None (this is extending a new feature that wasn't released yet)
> SALTO-1205 - extracting netsuite custom fields from formulas

- packages/workato-adapter/src/filters/cross_service/recipe_references.ts
- packages/workato-adapter/test/filters/recipe_references.test.ts
Small extension to https://github.com/salto-io/salto/pull/1907
---
None
> SALTO-1205 - extract netsuite references in workato recipes from additional records

- packages/netsuite-adapter/src/changes_detector/changes_detector.ts
- packages/netsuite-adapter/test/changes_detector/changes_detector.test.ts
Since SDF import files command does not work with folder paths, we only bring data about a folder when fetching a file inside it. Thus when the changes detector returns a path to a folder, it won't be fetched.
The solution here is if there was a folder change and there wasn't a file change inside it, the changes detector will also match any file under the folder.
In the future, we will fetch files and folders using the SuiteApp, which will support fetching folders, and we won't need this solution.
---
None
> SALTO-1198: fix detection of folders

- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/adapter_creator.ts
- packages/netsuite-adapter/src/config.ts
- packages/netsuite-adapter/src/constants.ts
- packages/netsuite-adapter/test/adapter.test.ts
Added flag to disable changes detection (by default, it won't be disabled).
---
None
> SALTO-1198: added useChangesDetection configuration option

- packages/lang-server/src/workspace.ts
- packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/src/workspace/nacl_files/parsed_nacl_file.ts
- packages/workspace/src/workspace/nacl_files/parsed_nacl_files_cache.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/common/nacl_file_source.ts
- packages/workspace/test/common/nacl_file_store.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
- packages/workspace/test/workspace/nacl_files/parsed_nacl_files_cache.test.ts
> support lazy parsed nacl file

- packages/core/src/local-workspace/state.ts
- packages/workspace/src/workspace/state/in_mem.ts
- packages/workspace/src/workspace/workspace.ts
> Fix a state version updating issue + small fixes

- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/workspace.test.ts
>  Added missing flushes (fixes SALTO-1232 and SALTO-1229)

- packages/workspace/src/serializer/elements.ts
- packages/workspace/test/serializer/serializer.test.ts
> Fix state backward comp

- packages/netsuite-adapter/src/query.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/netsuite-adapter/test/query.test.ts
---
Fixed bug in the skipList where in some cases, it would incorrectly skip instances.
> SALTO-1238: fixed netsuite skipList

- packages/netsuite-adapter/src/filters/instance_references.ts
- packages/netsuite-adapter/src/types.ts
> Fix netsuite crush on partial fetch (fix SALTO-1227)

- packages/workspace/src/workspace/element_selector.ts
- packages/workspace/test/element_selector.test.ts
See info at https://salto-io.atlassian.net/browse/SAAS-1724
---
None
> SAAS-1724: Support element selector matches for nested element IDs

- packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/src/workspace/workspace.ts
> changed getErrors to use promise all instead of awu

- packages/cli/src/cli.ts
- packages/cli/src/commands/deploy.ts
- packages/cli/src/commands/fetch.ts
- packages/core/index.ts
- packages/core/src/local-workspace/remote_map.ts
- packages/core/test/workspace/local/remote_map.test.ts
> close all rocksdb connections

- packages/core/src/local-workspace/remote_map.ts
> fix remote map readonly rebase issue

- packages/workspace/src/workspace/nacl_files/elements_cache.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
> Improve update index performance

- packages/cli/e2e_test/multi_env.test.ts
- packages/salesforce-adapter/src/constants.ts
- packages/salesforce-adapter/src/transformers/transformer.ts
- packages/salesforce-adapter/test/adapter.discover.test.ts
> fixed missing rollup summary type

- packages/workspace/src/workspace/hidden_values.ts
> SAAS-1259: Export filterOutHiddenChanges so saas tracker will not notify on hidden values

- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/src/workspace/nacl_files/parsed_nacl_files_cache.ts
- packages/workspace/test/workspace/nacl_files/parsed_nacl_files_cache.test.ts
see description
---
---
internal usage
> Fix a problem where parsed_nacl_files_cache would create error entries for files that have no errors

- packages/vscode/package.json
> changed back salto package name to a valid vscode extension name

- packages/core/src/core/restore.ts
- packages/core/test/core/restore.test.ts
- packages/vscode/package.json
> Fixed filterByPathIndex filter out change data types  (SALTO-1258)

- packages/adapter-utils/src/utils.ts
- packages/core/src/core/list.ts
- packages/core/src/core/plan/plan.ts
- packages/vscode/package.json
- packages/workspace/src/expressions.ts
- packages/workspace/src/validator.ts
- packages/workspace/test/core/expressions.test.ts
- packages/workspace/test/serializer/serializer.test.ts
- packages/workspace/test/workspace/workspace.test.ts
> added nested resolve

- packages/core/package.json
- packages/core/src/local-workspace/remote_map.ts
- packages/workspace/src/workspace/workspace.ts
> add lock on db create

- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
Already reviewed, should have been merged earlier.
---
---
should make element_selector stuff work again
> Fixing a programming bug in the list function of NaclFileSource

- packages/dummy-adapter/generate.sh
- packages/dummy-adapter/jest.config.js
- packages/dummy-adapter/package.json
- packages/dummy-adapter/src/adapter.ts
- packages/dummy-adapter/src/adapter_creator.ts
- packages/dummy-adapter/src/data/fixtures/fullInst.nacl.mock
- packages/dummy-adapter/src/data/fixtures/fullInst2.nacl.mock
- packages/dummy-adapter/src/data/fixtures/fullObj.nacl.mock
- packages/dummy-adapter/src/data/fixtures/partialInst.nacl.mock
- packages/dummy-adapter/src/data/fixtures/partialInst2.nacl.mock
- packages/dummy-adapter/src/data/fixtures/partialObj.nacl.mock
- packages/dummy-adapter/src/data/fixtures/partialObj2.nacl.mock
- packages/dummy-adapter/src/generator.ts
- packages/dummy-adapter/test/adapter.test.ts
- packages/dummy-adapter/test/adapter_creator.test.ts
- packages/dummy-adapter/test/generator.test.ts
- packages/dummy-adapter/test/mocks/multi1.nacl.mock
- packages/dummy-adapter/test/mocks/multi2.nacl.mock
- packages/dummy-adapter/test/mocks/single.nacl.mock
- packages/dummy-adapter/tsconfig.json
- yarn.lock
_Added default elements to dummy adapters_
---
_Added the ability to instruct the dummy adapter to return elements which are provided with input nacl files, and modified it to return specific fixed elements for unit tests usage. Also ported some of the changes and fixes from the lazy element branch._
> added default elements to dummy adapters

- packages/dummy-adapter/src/generator.ts
Fixing a bug where the dummy adapter would return parse results as elements.
Parse results are fragments with incomplete types and cannot be treated as elements.
This quick "fix" is to resolve the types on the fragments but this is not a proper
fix because the adapter should not be using the parser in the first place. if it needs
to load elements it should be using an element source...
---
_None_ (dummy adapter is internal use only)
> Fix dummy adapter returning fragments instead of elements

- packages/netsuite-adapter/src/filters/consistent_values.ts
Return more consistent recordType value for entryForms and permittedRole for customRecordTypes
> SALTO-1152 - Netsuite: return consistent values when SDF is inconsistent #3

- packages/core/index.ts
- packages/core/src/local-workspace/remote_map.ts
> close remote map of a specific workspace

- packages/salesforce-adapter/src/fetch.ts
Unclear why but it seems like the zipFile field in retrieve results
can be an object and not a string in some cases.
In order to get more information if/when it happens again, added more
logs and more information about the request in the error
---
- Improved error message and debug log information for specific fetch error scenarios
> SALTO-1288: Add logs and explicit error on retrieve failure

- packages/netsuite-adapter/package.json
- yarn.lock
BugFix:
NetSuite Adapter: Fix a bug that caused fetch to potentially get stuck infinitely
> SALTO-1289: Netsuite: Bump SDF to support: Kill child process and its child processes in case of timeout

- packages/adapter-components/src/client/index.ts
- packages/adapter-components/src/client/pagination.ts
- packages/adapter-components/test/client/pagination.test.ts
---
Needed for the JIRA API [pagination](https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/#pagination)
Most likely we will need additional parameters (currently "isLast" and "values" are hard coded) but I was not sure how the configuration was supposed to be extended to support that
---
_None_
> Added offset / limit based pagination to adapter-components

- packages/salesforce-adapter/src/constants.ts
- packages/salesforce-adapter/src/filters/custom_objects.ts
- packages/salesforce-adapter/src/filters/utils.ts
- packages/salesforce-adapter/src/transformers/transformer.ts
> SALTO-1297: Add keyPrefix annotation to Custom Objects

- packages/adapter-api/src/adapter.ts
- packages/cli/src/commands/fetch.ts
- packages/cli/src/formatter.ts
- packages/cli/src/prompts.ts
- packages/cli/test/commands/fetch.test.ts
- packages/core/src/api.ts
- packages/core/src/core/fetch.ts
- packages/core/test/api.test.ts
- packages/lowerdash/src/index.ts
- packages/lowerdash/src/objects.ts
- packages/lowerdash/test/objects.test.ts
- packages/salesforce-adapter/e2e_test/utils.ts
- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/change_validators/custom_object_instances.ts
- packages/salesforce-adapter/src/filter.ts
- packages/salesforce-adapter/src/filters/custom_feed_filter.ts
- packages/salesforce-adapter/src/filters/custom_objects_instances.ts
- packages/salesforce-adapter/src/filters/custom_settings_filter.ts
- packages/salesforce-adapter/src/filters/settings_type.ts
- packages/salesforce-adapter/src/filters/standard_value_sets.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/filters/custom_objects_instances.test.ts
Add errors to FetchResult and add it to Salesforce's filters
---
None (No user effect atm)
> SALTO-1256 - Add errors to FetchResult and add it to Salesforce's filters

- packages/lang-server/src/usage.ts
- packages/salesforce-adapter/src/filters/settings_type.ts
Added the missing awaits that were found in the PR https://github.com/salto-io/salto/pull/2060
---
None
> added missing awaits

- packages/workato-adapter/src/adapter.ts
- packages/zuora-billing-adapter/e2e_test/adapter.test.ts
- packages/zuora-billing-adapter/src/adapter.ts
- packages/zuora-billing-adapter/test/utils.ts
Add progress report events for fetch (similar to the salesforce and netsuite format).
---
None
> SALTO-1304 Add progress report for workato+zuora

- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
> fix listNaclFiles bug

- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/src/workspace/nacl_files/parsed_nacl_files_cache.ts
- packages/workspace/test/common/nacl_file_store.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.state.test.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
Make cache parsed nacl file batch its calls 
---
---
Shouldn't affect users, maybe through performance
> Batch delete

- packages/cli/package.json
- packages/core/package.json
- yarn.lock
> upgraded rocksdb version

- packages/lang-server/src/location.ts
- packages/lang-server/test/location.test.ts
- packages/vscode/src/providers.ts
Add a new symbol search algorithm
---
This symbol search will be used as the elements search in the SAAS.
https://salto-io.atlassian.net/browse/SAAS-2020
see algorithm detail in https://salto-io.atlassian.net/browse/SAAS-2020?focusedCommentId=17872
---
_No release notes_
> SAAS-2020-Add new symbol search algorithm

- packages/core/src/local-workspace/remote_map.ts
- packages/core/test/workspace/local/remote_map.test.ts
> fixed remote map pages not working after flush

- packages/core/src/core/fetch.ts
Added a missing service filter to have the plan ignore elements which are whos adapter was not fetched.
>  added service IDFilter to fetch plan invocation (SALTO-1273)

- packages/lang-server/src/location.ts
_export new location types_
---
_Part of SAAS-2020_
---
None
> export new location types

- packages/workspace/src/validator.ts
> fix missing element source in element annotation types invocation

- packages/cli/src/commands/restore.ts
> Fix restore calc diff formatting issue

- packages/salesforce-adapter/src/transformers/transformer.ts
---
None (bug was introduced in this branch)
> revert accidental change to salesforce field types

- packages/workspace/src/workspace/nacl_files/elements_cache.ts
Should not ignore Errors if the merge result is the same as the original value
> Fix merge Error issue

- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.state.test.ts
> Fix elements index bug

- packages/workspace/src/workspace/nacl_files/index.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
> remove getParsedNaclFiles

- packages/core/src/local-workspace/remote_map.ts
> Fix remote map cache usage

- packages/lang-server/src/workspace.ts
- packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/common/nacl_file_source.ts
- packages/workspace/test/workspace/multi_env/multi_env_source.test.ts
- packages/workspace/test/workspace/workspace.test.ts
Still needs to fix the tests and write new ones. In addition, I want to do a little more testing manually.
> SALTO-1336: update cache after load

- packages/lang-server/src/definitions.ts
- packages/lang-server/src/location.ts
- packages/lang-server/src/workspace.ts
- packages/lang-server/test/definitions.test.ts
> fixed static file goto def

- packages/core/src/local-workspace/remote_map.ts
- packages/core/test/workspace/local/remote_map.test.ts
> Fix remote map delete

- packages/cli/package.json
- packages/netsuite-adapter/package.json
- packages/salesforce-adapter/package.json
- packages/zuora-billing-adapter/package.json
> SALTO-1344 make e2e-credentials-store a dev dependency

- packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
- packages/workspace/test/workspace/multi_env/routers.test.ts
Fix an issue with empty change arrays
---
---
Fix an issue with empty change arrays
> Fix update nacl

- packages/netsuite-adapter/e2e_test/cred_store
- packages/netsuite-adapter/e2e_test/credentials_store/adapter.ts
- packages/netsuite-adapter/e2e_test/jest_environment.ts
- packages/netsuite-adapter/src/client/suiteapp_client/constants.ts
Sames as https://github.com/salto-io/salto/pull/2125 for lazy element branch
---
None
> SALTO-1359: changed suiteapp integration keys

- packages/netsuite-adapter/e2e_test/cred_store
- packages/netsuite-adapter/e2e_test/credentials_store/adapter.ts
- packages/netsuite-adapter/e2e_test/jest_environment.ts
Same as https://github.com/salto-io/salto/pull/2129/files from lazy_element_integ
---
None
> SALTO-1359: update the e2e pool type lazy

- packages/cli/src/commands/fetch.ts
- packages/cli/src/formatter.ts
- packages/cli/src/prompts.ts
- packages/cli/test/commands/fetch.test.ts
Added fetching progress output in the CLI
> Salto 1285 expose progress information in the cli

- packages/jira-adapter/src/adapter.ts
- packages/salesforce-adapter/src/adapter.ts
- packages/workato-adapter/src/adapter.ts
- packages/zuora-billing-adapter/src/adapter.ts
Changed adapters progressing messages on fetch command
> Change adapters progressing messages on fetch command

- packages/workato-adapter/src/reference_mapping.ts
> Workato - add reference from recipe to folder_id

- packages/cli/src/commands/service.ts
- packages/cli/src/formatter.ts
- packages/cli/src/prompts.ts
- packages/cli/test/commands/service.test.ts
change prompt message when login failed
> SALTO-1290 Prompt When Login Failed

- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/src/client/types.ts
- packages/netsuite-adapter/test/client/soap_client.test.ts
- packages/netsuite-adapter/test/client/suiteapp_client.test.ts
SuiteApp invalid credentials indicative error message on fetch & deploy 
---
CherryPicked from master
> Salto-1360cherry - SuiteApp indicative error message on fetch

- packages/core/src/core/plan/plan.ts
- packages/workspace/src/expressions.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/test/core/expressions.test.ts
- packages/workspace/test/validator.test.ts
_Fixed resolve mutates input values_
---
_The resolve method should not modify its input values. The previous implementation mutated the input in two place - fields, annotation types, and refType). This PR fixes that._
---
_NA_
> fixed resolve mutates input values

- packages/core/src/local-workspace/workspace.ts
> make nacl files source use the same remote map creator as workspace

- packages/netsuite-adapter/src/client/sdf_client.ts
- packages/netsuite-adapter/test/client/sdf_client.test.ts
(cherry picked from commit e3ff59574edba78dc34c999ae6985db2e6ddd1bc)
This was already merged to master as part of: https://github.com/salto-io/salto/pull/2143
> SAAS-2204: Add retry on top of SDF unexpected errors to reduce the inconsistent skipList noise

- .github/pull_request_template.md
Added 'Users Notifications' to the PR template so we will have a place to document all the changes the user should be notified about when releasing a new version.
---
None
> Added 'Users Notifications' to PR template

- packages/netsuite-adapter/src/client/suiteapp_client/errors.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/src/suiteapp_file_cabinet.ts
- packages/netsuite-adapter/test/client/suiteapp_client.test.ts
- packages/netsuite-adapter/test/suiteapp_file_cabinet.test.ts
Changed locked files to not be written to the skip list
---
None
> SALTO-1379: changed locked files to not be written to the skip list

- packages/netsuite-adapter/src/adapter.ts
- packages/stripe-adapter/src/adapter.ts
missed two adapters fetch progressing messages modification, in ticket SALTO-1357.
modify them on this brench
> netsuite adpater and stripe adapter fetch progressing messages

- packages/netsuite-adapter/src/client/sdf_client.ts
(cherry picked from commit f9ea3346d993151952f53b4c1f9940d1f31ab415)
> SALTO-1399: Netsuite: Limit sdf_client read from FS concurrency

- packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
- packages/workspace/test/workspace/multi_env/routers.test.ts
Fix an issue where a large amount of updated files would crash updateNaclFiles
---
---
Should enable updating more files at the same time
> [SALTO-1325] - Fix issue with large amount of nacl files to update

- packages/cli/e2e_test/helpers/workspace.ts
- packages/cli/e2e_test/salto.test.ts
- packages/core/src/core/plan/filter.ts
- packages/core/src/core/plan/group.ts
- packages/core/src/core/plan/plan.ts
- packages/core/src/local-workspace/remote_map.ts
- packages/core/src/local-workspace/state.ts
- packages/core/test/workspace/local/remote_map.test.ts
- packages/core/test/workspace/local/state.test.ts
- packages/dag/src/nodemap.ts
- packages/lang-server/src/workspace.ts
- packages/lang-server/test/workspace.test.ts
- packages/workspace/src/workspace/elements_source.ts
- packages/workspace/src/workspace/nacl_files/elements_cache.ts
- packages/workspace/src/workspace/nacl_files/index.ts
- packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/src/workspace/nacl_files/parsed_nacl_files_cache.ts
- packages/workspace/src/workspace/state/in_mem.ts
- packages/workspace/src/workspace/state/state.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/common/nacl_file_source.ts
- packages/workspace/test/common/nacl_file_store.ts
- packages/workspace/test/workspace/multi_env/multi_env_source.test.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.state.test.ts
- packages/workspace/test/workspace/workspace.test.ts
- yarn.lock
when rocksdb cache is inconsistent with nacl files - delete cache
---
Reminder to follow up:
1. Telemetry, logging for elements cache reset
2. Move the pre/post hash calculation to the new interface in the atomic flush
---
should fix scenarios in which cache is inconsistent with nacl files
> Validation cherrypick - WIP

- packages/salesforce-adapter/test/filters/add_missing_ids.test.ts
- packages/salesforce-adapter/test/filters/elements_url.test.ts
- packages/salesforce-adapter/test/filters/extra_dependencies.test.ts
- packages/salesforce-adapter/test/filters/profile_paths.test.ts
Build fails due to (probably) silent conflict between PRs
---
None
> fixed imports in salesforce

- packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
- packages/workspace/test/workspace/multi_env/routers.test.ts
* fixed get mergeable id for number attr and element names
_Port #2172 to master_
---
_NA_
> fixed get mergeable id for number attr and element names (#2172)

- packages/salesforce-adapter/src/change_validators/package.ts
- packages/salesforce-adapter/src/deprecated_config.ts
- packages/salesforce-adapter/src/types.ts
- packages/salesforce-adapter/test/change_validators/package.test.ts
Same as https://github.com/salto-io/salto/pull/2171 for lazy
---
None
> SALTO-1414: fixed package change validator (#2171)

- packages/core/index.ts
- packages/core/package.json
- packages/core/src/local-workspace/remote_map.ts
- yarn.lock
Add replicate db support
---
None
> Add replicate db support

- packages/netsuite-adapter/src/data_elements/types.ts
Added missing subitems of inventory and assembly items
---
None
> SALTO-825: added missing sub inventory and assembly types

- packages/netsuite-adapter/src/data_elements/data_elements.ts
- packages/netsuite-adapter/test/data_elements/data_elements.test.ts
Added support for service id in data instances
---
None
> SALTO-825: added support for changing instances element ids

- packages/adapter-components/src/elements/soap/type_elements/complex_types_converter.ts
Added naclCase to object name
---
None
> SALTO-825: added nacl case to object name

- packages/netsuite-adapter/src/config.ts
Added dataset and workbook types back to the exclude list
---
None
> SALTO-1439: Add dataset and workbook to the exclude list

- packages/netsuite-adapter/src/client/sdf_client.ts
- packages/netsuite-adapter/test/client/sdf_client.test.ts
Same as https://github.com/salto-io/salto/pull/2205 for lazy
---
None
> SALTO-1446: fixed type names in SDF error response

- packages/netsuite-adapter/src/data_elements/multi_fields_identifiers.ts
- packages/netsuite-adapter/src/data_elements/types.ts
Fixed account identifier
---
None
> SALTO-825: fix account identifier

- packages/core/src/local-workspace/workspace.ts
- packages/workspace/src/workspace/nacl_files/elements_cache.ts
- packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/nacl_files/elements_cache.test.ts
> added missing persistent modifer to the hash remote map (SALTO-1462)

- packages/netsuite-adapter/src/client/sdf_client.ts
- packages/netsuite-adapter/src/config.ts
- packages/netsuite-adapter/test/client/sdf_client.test.ts
(Not adding release notes as the relevant release note of modifying the default include list will be merged to master when this code will)
> SALTO-1459: Netsuite exclude list modifications

- packages/core/src/local-workspace/remote_map.ts
---
---
Better error will be printed if cache DB is already taken
> [SALTO-1330] Crash informatively when cache DB is taken

- packages/core/src/core/diff.ts
Fixed circular-dependencies-error on diff
---
None
> fixed circular-dependencies-error on diff

- packages/core/src/core/plan/plan.ts
- packages/lowerdash/src/collections/asynciterable.ts
- packages/lowerdash/test/collections/asynciterable.test.ts
Some log messages will have values
---
---
> [SALTO-1333] Fix empty debug logs in plan.ts 

- packages/workspace/src/workspace/nacl_files/elements_cache.ts
- packages/workspace/src/workspace/workspace.ts
Add some logs for cache invalidation situations
---
---
should mainly help debugging
> [SALTO-1380] add logs to cache invalidation scenarios

- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/types.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/src/data_elements/custom_fields.ts
- packages/netsuite-adapter/src/data_elements/data_elements.ts
- packages/netsuite-adapter/src/filters/data_instances_attributes.ts
- packages/netsuite-adapter/src/filters/data_instances_custom_fields.ts
- packages/netsuite-adapter/src/filters/data_instances_diff.ts
- packages/netsuite-adapter/src/filters/data_instances_internal_id.ts
- packages/netsuite-adapter/src/filters/data_instances_null_fields.ts
- packages/netsuite-adapter/src/filters/data_instances_references.ts
- packages/netsuite-adapter/src/filters/data_types_custom_fields.ts
- packages/netsuite-adapter/src/filters/remove_redundant_fields.ts
- packages/netsuite-adapter/src/filters/replace_record_ref.ts
- packages/netsuite-adapter/src/group_changes.ts
- packages/netsuite-adapter/test/client/client.test.ts
- packages/netsuite-adapter/test/client/soap_client.test.ts
- packages/netsuite-adapter/test/data_elements/data_elements.test.ts
- packages/netsuite-adapter/test/filters/data_instances_attributes.test.ts
- packages/netsuite-adapter/test/filters/data_instances_custom_fields.test.ts
- packages/netsuite-adapter/test/filters/data_instances_diff.test.ts
- packages/netsuite-adapter/test/filters/data_instances_internal_id.test.ts
- packages/netsuite-adapter/test/filters/data_instances_null_fields.test.ts
- packages/netsuite-adapter/test/filters/data_instances_references.test.ts
- packages/netsuite-adapter/test/filters/data_types_custom_fields.test.ts
- packages/netsuite-adapter/test/filters/remove_redundant_fields.test.ts
- packages/netsuite-adapter/test/group_changes.test.ts
Now supporting deploying modification changes to data instances
Most of this PR is about converting the instance value back to its XML form
---
None
> SALTO-825: added support for modification deployments to data instances

- .circleci/config.yml
> Fix AWS CLI in circleci config (#2243)

- .circleci/config.yml
- build_utils/create_version_pr.sh
> changed branch name to main

- packages/adapter-utils/src/filter.ts
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/src/filter.ts
- packages/netsuite-adapter/src/filters/add_internal_ids.ts
- packages/netsuite-adapter/src/group_changes.ts
- packages/netsuite-adapter/src/types.ts
- packages/netsuite-adapter/test/client/client.test.ts
- packages/netsuite-adapter/test/client/soap_client.test.ts
- packages/netsuite-adapter/test/filters/add_internal_ids.test.ts
- packages/netsuite-adapter/test/filters/roles_internal_ids.test.ts
- packages/netsuite-adapter/test/group_changes.test.ts
- packages/salesforce-adapter/test/filters/filters.test.ts
Added support for creating and deleting data instances
---
None
> SALTO-825: create and delete data instances

- packages/core/index.ts
- packages/core/src/local-workspace/remote_map.ts
- packages/core/test/workspace/local/remote_map.test.ts
- packages/workspace/src/workspace/remote_map.ts
_Add read only remote map creator_
---
_Used in the SaaS_
---
_None_
> read only remote map creator

- packages/netsuite-adapter/src/change_validator.ts
- packages/netsuite-adapter/src/change_validators/data_account_specific_values.ts
- packages/netsuite-adapter/src/filters/data_instances_diff.ts
- packages/netsuite-adapter/test/change_validators/data_account_specific_values.test.ts
Added change validator for data account specific values
---
None
---
None
> SALTO-825: added data_account_specific_values

- packages/lang-server/src/workspace.ts
Added flag for the SaaS UI to skip validation in workspace editor
---
None
---
None
> Added flag to skip validation in workspace editor

- packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
- packages/workspace/test/workspace/multi_env/routers.test.ts
> Port salto 1487 from master

- packages/core/src/local-workspace/remote_map.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
_Delete DB to not throw error if the DB does not exist_
---
Also, I added another if that remove one unneeded set to the rocksDB 
---
_No release notes_
> delete db should not throw error if the db does not exist

- packages/workspace/src/workspace/nacl_files/elements_cache.ts
Some changes to logs to help debugging of cache code
---
---
---
> Add logs according to Ori CR

- packages/core/src/local-workspace/remote_map.ts
- packages/core/src/local-workspace/workspace.ts
- packages/workspace/index.ts
- packages/workspace/src/errors.ts
- packages/workspace/src/workspace/errors.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/workspace.test.ts
_Add environment name validation_
---
---
_Add validation for the environment name_
---
Env name can now contain only alphanumeric chars or one of _-!.
> Add env name validation

- packages/salesforce-adapter/src/filters/field_references.ts
- packages/salesforce-adapter/test/filters/field_references.test.ts
looks like this was missed when the async reference resolution was added
---
None
> SALTO-1520 fix async function call in salesforce references

- packages/logging/README.md
replaced the readme test part to a working code with better names
---
i haven’t read the other parts of the read me or checked if they are up to date.
i just needed this part and i found it to be not working
---
---
> fixed readme with working code and better names

- packages/core/src/local-workspace/remote_map.ts
---
---
When salto clean is called (unless cache is not deleted), database will be deleted from file system
> [SALTO-1456] Delete DB on clean

- packages/adapter-api/src/elements.ts
Remove the redundant PlaceholderTypeElement
> Remove the redundant PlaceholderTypeElement

- packages/adapter-api/src/elements.ts
- packages/adapter-api/src/values.ts
- packages/workspace/src/serializer/elements.ts
- packages/workspace/src/validator.ts
- packages/workspace/test/serializer/serializer.test.ts
- packages/workspace/test/validator.test.ts
Added validation warning when an instance's type that does not exist
---
Core:
Added validation warning when an instance's type does not exist
---
None
> SALTO-1329: added validation warning when an instance's type that does not exist

- packages/workato-adapter/README.md
- packages/zuora-billing-adapter/README.md
> Add details to workato+zuora READMEs

- packages/adapter-components/src/client/decorators.ts
- packages/adapter-components/src/client/http_client.ts
This will eventually be replaced with a change suggestion mechanism, but for now reducing the log level.
---
None
---
None
> SAAS-2799 lower log level for errors due to missing permissions

- packages/cli/src/commands/env.ts
- packages/cli/test/commands/env.test.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/workspace.test.ts
_Add option to keep nacl and state files in delete environment_
---
---
_add option to delete env but keep it's nacls and states files_
---
> add option to keep nacls in delete env

- packages/cli/src/commands/env.ts
- packages/cli/test/commands/env.test.ts
- packages/core/index.ts
- packages/core/src/local-workspace/workspace.ts
- packages/workspace/index.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/workspace.test.ts
_addEnvironment to change internal workspace state_
---
---
_None_
---
> addEnvironment to change internal workspace state

- packages/core/src/local-workspace/remote_map.ts
- packages/core/test/workspace/local/remote_map.test.ts
_fix remote map namespace regex_
---
---
None
---
> fix remote map namespace regex

- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/workspace.test.ts
_fixed workspace create multiple instances of the same multienvSource_
---
_A bug in the creation of the mergeManager caused the workspace to create two instances of the main env (one which is used for merger, one outside of it). This has caused the merger to drop hidden changes when their top level element was added to the nacl in the same load._
---
_Fixed deploying an instance from the nacl with service generated hidden values can create invalid plan changes in the next deploy_
---
_NA)_
> fixed workspace create multiple instances of the same multienvSource (SALTO-1537)

- packages/salesforce-adapter/src/transformers/reference_mapping.ts
Add explicit references in FieldSet
---
availableFields and displayedFields values will be converted to references based on their field set's parent
> SALTO - 1534 - added FieldSetItem ref

- packages/core/src/local-workspace/remote_map.ts
_close read only connections as well_
---
---
> close read only connections as well

- .github/pull_request_template.md
Update the PR template with more specific details.
---
None
---
None
> Update the User Notifications section of the PR template

- packages/core/src/local-workspace/state.ts
_cache state content and hash in order to improve performance_
---
---
> cache state content and hash in order to improve performance

- packages/stripe-adapter/README.md
> add to stripe's README

- packages/adapter-components/test/elements/ducktype/standalone_field_extractor.test.ts
Removed console.log lines from test
---
None
---
None
> Removed console.log from test

- .circleci/config.yml
- packages/cli/package_native.js
- packages/core/package.json
- packages/core/src/local-workspace/rocksdb.ts
- yarn.lock
_Upgraded rocks db binding version_
---
_Will hopefully solve build issue
> Fix package native

- packages/adapter-components/src/client/http_connection.ts
Reducing log level for recoverable errors.
---
None
---
None
> SAAS-2799 reduce log level

- packages/core/index.ts
export metadata type
---
---
---
> SALTO:1224/export metadata type

- packages/core/src/core/plan/plan.ts
_add missing await that fix the getPlan bug_
---
https://salto-io.atlassian.net/browse/SALTO-1527
---
Release notes: None
> SALTO-1527: add missing await that fix the getPlan bug

- packages/salesforce-adapter/src/client/client.ts
- packages/salesforce-adapter/test/client.test.ts
It appears in rare cases the `records` field is missing in `query` and `queryMore` responses. This can fail the `extra_dependencies` filter and cause us to not get any dependencies from the tooling API.
Adding handling for that on the client + logs so that next time we can understand if it's a different response structure.
---
None
---
None
> SALTO-1582 handle missing records in salesforce query response

- packages/salesforce-adapter/src/client/client.ts
- packages/salesforce-adapter/test/client.test.ts
While it is still unclear why this happens, it seems that in certain accounts the Salesforce API
sometimes returns a null response on an arbitrary request. this causes jsforce to crash due to the
unexpected response format.
We hope adding a retry in that case would help
---
- Added handling for rare cases where the Salesforce API returns a null response that caused the fetch operation to fail
---
_None_
> SALTO-1581: Add handling for salesforce returning a null response

- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
_cache referenced on parsed nacl file - as part of the performance improvements_
---
---
> SALTO-1597: cache referenced on parsed nacl file

- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/workspace/workspace.test.ts
When having an unresolved reference in NetSuite, the "Fix Unresolved References" operation in the SaaS guides the user to clone only the scriptid of the missing element while we should clone the whole element.
---
Release Notes:
workspace:
* Changing list-unresolved references results by returning the base wrapping element instead of the field (makes problems on Netsuite cases).
> SALTO-1569 Fixed listUnresolvedReferences return base wrapping element

- docs/syntax.md
> fix typo in docs

- packages/workato-adapter/src/constants.ts
- packages/workato-adapter/src/filters/cross_service/element_indexes.ts
- packages/workato-adapter/src/filters/cross_service/recipe_references.ts
- packages/workato-adapter/src/filters/cross_service/reference_finders/recipe_block_types.ts
- packages/workato-adapter/src/filters/cross_service/reference_finders/shared.ts
- packages/workato-adapter/src/filters/cross_service/reference_finders/zuora.ts
- packages/workato-adapter/test/adapter_creator.test.ts
- packages/workato-adapter/test/filters/recipe_references.test.ts
Added references from Workato to Zuora
---
Example:
Before:
```
workato.recipe__code Alon_s_reciepe_1806547_tsu__new_updated_record@uuumuuuu {
number = 0
provider = "zuora"
name = "new_updated_record"
as = "eadbb773"
description = "New or updated <span class=\"provider\">accountingperiods</span> in <span class=\"provider\">Zuora</span>"
keyword = "trigger"
dynamicPickListSelection = {
object = "AccountingPeriod"
}
input = {
object = "AccountingPeriod"
since = "#{_('data.workato.job_context.user_id')}"
}
block = [
{
number = 1
keyword = "if"
input = {
type = "compound"
operand = "and"
conditions = [
{
operand = "greater_than"
lhs = "#{_('data.zuora.eadbb773.Name')}"
rhs = "111111111"
uuid = "condition-f98160b0-bff3-4257-8e06-8ffedcfb7b8d"
},
]
}
block = [
{
number = 2
provider = "zuora" …
```
> SALTO-1617: added zuora references from workato

- packages/core/package.json
- yarn.lock
_upgrade rocksDB version_
---
_Fix the SaaS bug_
> upgrade rocksDB version

- packages/zendesk-support-adapter/README.md
- packages/zuora-billing-adapter/README.md
Add Zendesk readme and update Zuora details.
---
None
---
None
> Add Zendesk readme

- packages/netsuite-adapter/config_doc.md
added documentations for fetch and deploy config on Netsuite
> SALTO-1539 Netsuite Config Doc References Are Broken

- README.md
- packages/jira-adapter/README.md
- packages/jira-adapter/config_doc.md
Added more detailed instructions on how to connect a Jira environment, fixed documentation around rate limit defaults, and added the required Jira version 
---
---
_None_
---
_None_
> Readme fixes and additions

- packages/salesforce-adapter/src/transformers/reference_mapping.ts
Removing duplicate (had no actual impact)
---
None
---
None
> Remove duplicate ref parent type

- packages/workspace/src/validator.ts
Changed the elements validation code to:
1. Process all of the elements that needs validation in order instead of in parallel
2. Recurse into the elements in order instead of in parallel 
---
This task was created after analysis that showed that the concurrent processing of the elements, and the concurrent recursion can lead to excessive memory usage in large workspaces (which might lead to an OOM exception)
---
_Reduced memory usage on large workspaces_
---
_NA_
> Changed validator to process elements in seq order (SALTO-1755)

- packages/adapter-components/src/elements/swagger/type_elements/type_config_override.ts
_fix rebase issue_
---
---
None
---
> fix rebase issue

- packages/zuora-billing-adapter/src/config.ts
The merge in https://github.com/salto-io/salto/pull/2522 introduced a duplicate with an earlier commit
---
None
---
None
> SALTO-1660 fix bad merge

- packages/netsuite-adapter/README.md
Add M1 NetSuite installation instructions
---
Installing JDK v11 on M1 Macs need special instructions
> Add M1 NetSuite installation instructions

- packages/jira-adapter/src/adapter_creator.ts
- packages/jira-adapter/src/config.ts
- packages/jira-adapter/system_config_doc.md
- packages/jira-adapter/test/adapter_creator.test.ts
Changed the configuration NaCl in Jira to be empty when the workspace is created
Once this will be approved I will do the same for the rest of the adapters
---
None
---
None
> SAAS-2783: removed the configuration from Jira config NaCl

- packages/salesforce-adapter/src/change_validators/package.ts
While testing the PackageChangeError implementation, I saw that some of the detailed messages returned by this change-validator are nonunique.
As far as I understand, "message" should be "groupable" and constant, and "detailed message" should contain unique and specific information about the element that caused the issue.
This PR adds that information.
---
None.
---
None.
---
None.
> SALTO-1706: PackageChangeError returns non unique detailed message strings

- packages/adapter-components/src/config/index.ts
- packages/adapter-components/src/config/merge.ts
- packages/adapter-components/test/config/merge.test.ts
- packages/jira-adapter/src/adapter_creator.ts
- packages/jira-adapter/src/config.ts
- packages/jira-adapter/system_config_doc.md
- packages/jira-adapter/test/adapter_creator.test.ts
- packages/stripe-adapter/src/adapter_creator.ts
- packages/stripe-adapter/src/config.ts
- packages/stripe-adapter/system_config_doc.md
- packages/workato-adapter/src/adapter_creator.ts
- packages/workato-adapter/src/config.ts
- packages/workato-adapter/system_config_doc.md
- packages/zendesk-support-adapter/src/adapter_creator.ts
- packages/zendesk-support-adapter/src/config.ts
- packages/zendesk-support-adapter/system_config_doc.md
- packages/zendesk-support-adapter/test/adapter.test.ts
- packages/zuora-billing-adapter/src/adapter.ts
- packages/zuora-billing-adapter/src/adapter_creator.ts
- packages/zuora-billing-adapter/src/config.ts
- packages/zuora-billing-adapter/system_config_doc.md
- packages/zuora-billing-adapter/test/adapter.test.ts
Removed the API definitions from the default config NaCl in the workspace so we will be able to update it without modifying the users' nacl
---
Stripe, Workato, Zuora Billing, Zendesk Support:
- Removed the API definitions from the default config NaCl in the workspace
---
None
> SAAS-2783: removed api definition from all simple adapters

- packages/core/src/core/fetch.ts
_changed fetch from split by path to use limited concurrency_
---
_Currently awu is used, which causes performance issues. Changing this to use with limited concurrency will allow us to bulk requests and improve performance. _
---
_NA_
---
_NA_
> (SALTO-1814) changed fetch from split by path to use limited concurrency

- packages/jira-adapter/src/change_validator.ts
Fixed build break
---
None
---
None
> Fixed build

- packages/jira-adapter/src/adapter.ts
Build broke again  on main due to a silent conflict
---
None
---
None
> added await to addDeploymentAnnotations

- packages/zendesk-support-adapter/src/adapter.ts
- packages/zendesk-support-adapter/src/filters/default_deploy.ts
_extract Zendesk deploy logic to filter_
---
---
_None_
---
> SALTO-1818: extract Zendesk deploy logic to filter

- packages/zendesk-support-adapter/src/adapter.ts
- packages/zendesk-support-adapter/src/adapter_creator.ts
- packages/zendesk-support-adapter/src/config.ts
- packages/zendesk-support-adapter/src/filters/field_references.ts
- packages/zendesk-support-adapter/src/filters/views.ts
- packages/zendesk-support-adapter/test/filters/unordered_lists.test.ts
- packages/zendesk-support-adapter/test/filters/views.test.ts
_support view deploy_
---
---
_None_
---
> SALTO-1818: support view deploy

- packages/core/src/core/plan/plan.ts
- packages/core/test/core/plan/plan.test.ts
Fixed resolve when comparing elements between the state and the workspace to look for inner references.
---
If we have an instance like
```
dummy.someType myInstance {
a = dummy.someType.instance.myInstance.b
b = {
b = dummy.someType.instance.myInstance.c
}
c = 2
}
```
when comparing whether the value `a` was changed we resolve its reference but we don't resolve the reference `b.b` inside of it which makes us return there is a difference although there isn't
IIUC this shouldn't impact performance because we call the new `transformElement` only for references that the points to a not base-level value which is not very common (but I will verify with some big workspaces)
---
Core:
- Fixed bug of false-positive changes on deploy in rare cases
---
None
> SALTO-1838: fixed resolve of inner references in plan

- packages/adapter-components/src/deployment/change_validators/check_deployment_based_on_config.ts
- packages/adapter-components/src/deployment/change_validators/index.ts
- packages/adapter-components/test/deployment/change_validators/check_deployment.test.ts
- packages/zendesk-support-adapter/src/adapter.ts
- packages/zendesk-support-adapter/src/change_validator.ts
- packages/zendesk-support-adapter/test/change_validator.test.ts
_Fix check deployment based on config function_
---
---
_None_
> SALTO-1826: fix check deployment based on config function

- packages/zendesk-support-adapter/src/errors.ts
- packages/zendesk-support-adapter/src/filters/default_deploy.ts
- packages/zendesk-support-adapter/src/filters/views.ts
- packages/zendesk-support-adapter/test/errors.test.ts
_format Zendesk message errors_
---
Looks like that:
---
None
---
> SALTO-1834: format Zendesk message errors

- packages/adapter-utils/src/walk_element.ts
- packages/adapter-utils/test/walk_element.test.ts
* `walkOnElement` will now accept only `Element`s and not any `Value`.
* Exported a `walkOnValue` that receives any value but also an element ID.
---
_None_
---
_None_
> SALTO-1852: Walk On Value

- packages/salesforce-adapter/src/client/client.ts
as part of solving https://salto-io.atlassian.net/browse/SAAS-3660 
---
None
---
None
> SALTO-1856 add logs to salesforce oauth connection

- packages/jira-adapter/src/config.ts
- packages/jira-adapter/src/references.ts
- packages/jira-adapter/test/adapter.test.ts
Change Jira type names,
The change in the workspace can be seen [here](https://github.com/salto-io/alon-jira-workspace/commit/242be0e59ace1693166a13e00df896317112dffe)
---
None
---
None
> SALTO-1821: Changed JIRA type names

- packages/adapter-components/src/elements/swagger/instance_elements.ts
Fix log to only appear when relevant
---
None
---
None
> SALTO-1865 SALTO-1789 fix warning

- packages/zendesk-support-adapter/src/adapter.ts
- packages/zendesk-support-adapter/src/deployment.ts
- packages/zendesk-support-adapter/src/filters/business_hours_schedule.ts
- packages/zendesk-support-adapter/src/filters/default_deploy.ts
- packages/zendesk-support-adapter/test/filters/business_hours_schedule.test.ts
_Support deploy of schedules in zendesk_
---
---
_None_
---
_None_
> SALTO-1841: support deploy of schedules in zendesk

- packages/core/src/local-workspace/remote_map.ts
- packages/core/test/workspace/local/remote_map_connection.test.ts
_read only remote map creates db only if files not exist_
---
---
_None_
---
> read only remote map creates db only if files not exist

- packages/zendesk-support-adapter/src/adapter.ts
- packages/zendesk-support-adapter/src/filters/reorder/workspace.ts
- packages/zendesk-support-adapter/test/adapter.test.ts
_Add workspace reorder filter_
---
---
_None_
---
_A new workspace order element (and it's type) will be added_
> SALTO-1848: add workspace reorder filter

- packages/zendesk-support-adapter/src/config.ts
- packages/zendesk-support-adapter/src/filters/field_references.ts
- packages/zendesk-support-adapter/system_config_doc.md
_Fix workspace reorder filter_
---
None
---
_None_
---
_None_
> SALTO-1848: fix workspace reorder filter

- packages/salesforce-adapter/e2e_test/credentials_store/adapter.ts
Removed support for registering oauth credentials to fix an issue with registering password credentials
---
Honestly, not really sure if or how registering oauth actually worked with the previous code, but it definitely broke the ability to register password credentials.
so removing the oatuh related code for now to resolve that issue, we can bring it back later if needed
---
_None_
---
_None_
> Fix salesforce cred store register command

- packages/zendesk-support-adapter/src/config.ts
- packages/zendesk-support-adapter/system_config_doc.md
_add deploy config for some recurseInto types_
---
None
---
_None_
---
_None_
> SALTO-1762: add deploy config for some recurseInto types

- packages/adapter-utils/test/nacl_case_utils.test.ts
saw this actually fail :) looks like `naclCase` was missing. (not trying to change anything else in the test)
---
None
---
None
> fix naclCase incorrect test

- packages/zendesk-support-adapter/src/deployment.ts
- packages/zendesk-support-adapter/src/filters/utils.ts
- packages/zendesk-support-adapter/src/filters/view.ts
- packages/zendesk-support-adapter/src/filters/workspace.ts
- packages/zendesk-support-adapter/test/filters/business_hours_schedule.test.ts
- packages/zendesk-support-adapter/test/filters/reorder/ticket_form.test.ts
- packages/zendesk-support-adapter/test/filters/view.test.ts
- packages/zendesk-support-adapter/test/filters/workspace.test.ts
_fix workspace and view filters_
---
None
---
_None_
---
_None_
> SALTO-1905: fix workspace and view filters

- packages/jira-adapter/.vscode/launch.json
- packages/jira-adapter/e2e_test/adapter.test.ts
- packages/jira-adapter/e2e_test/instances/board.ts
- packages/jira-adapter/e2e_test/instances/field.ts
- packages/jira-adapter/e2e_test/instances/fieldConfigurationScheme.ts
- packages/jira-adapter/e2e_test/instances/index.ts
- packages/jira-adapter/e2e_test/instances/issueTypeScheme.ts
- packages/jira-adapter/e2e_test/instances/issueTypeScreenScheme.ts
- packages/jira-adapter/e2e_test/instances/screen.ts
- packages/jira-adapter/e2e_test/instances/workflow.ts
- packages/jira-adapter/e2e_test/utils.ts
- packages/jira-adapter/package.json
- packages/jira-adapter/src/filters/workflow/types.ts
- packages/jira-adapter/src/reference_mapping.ts
Added e2e for Jira deploy.
---
None
---
None
> SALTO-1817-jira-deploy-e2e

- packages/jira-adapter/src/filters/project.ts
- packages/jira-adapter/test/filters/project.test.ts
Added support for updating project `workflowScheme`, ` issueTypeScreenSchemeId`, `fieldConfigurationSchemeId`
---
None
---
None
> SALTO-1715: support updating project schemes

- packages/zendesk-support-adapter/src/filters/unordered_lists.ts
- packages/zendesk-support-adapter/test/filters/unordered_lists.test.ts
_Order trigger definition_
---
---
_None_
---
_trigger definitions items order could change_
> SALTO-1896: order trigger definition

- packages/jira-adapter/src/config.ts
- packages/jira-adapter/src/filters/issue_type_schemas/issue_type_scheme.ts
- packages/jira-adapter/src/filters/project.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/system_config_doc.md
- packages/jira-adapter/test/filters/issue_type_schemas/issue_type_scheme.test.ts
- packages/jira-adapter/test/filters/project.test.ts
Added issueTypeScheme to project instead of issueTypes and made it deployable
---
None
---
None
> SALTO-1906: added issueTypeScheme to project

- packages/adapter-components/src/deployment/change_validators/index.ts
- packages/adapter-components/src/deployment/change_validators/skip_parents_of_skipped_instances.ts
- packages/adapter-components/test/deployment/change_validators/skip_parents_of_skipped_instances.test.ts
- packages/zendesk-support-adapter/src/change_validator.ts
_Skipped instances that depends on skipped instances_
---
https://salto-io.slack.com/archives/C02A6Q4HW57/p1642036406018700
---
_None_
---
_None_
> SALTO-1902: skipped instances that depends on skipped instances

- packages/adapter-components/src/deployment/deployment.ts
- packages/zendesk-support-adapter/src/adapter.ts
- packages/zendesk-support-adapter/src/change_validator.ts
- packages/zendesk-support-adapter/src/change_validators/account_settings.ts
- packages/zendesk-support-adapter/src/change_validators/index.ts
- packages/zendesk-support-adapter/src/filters/account_settings.ts
- packages/zendesk-support-adapter/test/change_validators/account_settings.test.ts
- packages/zendesk-support-adapter/test/filters/account_settings.test.ts
_support zendesk account settings deploy_
---
None
---
_None (not released yet)_
---
_None_
> SALTO-1851: support zendesk account settings deploy

- packages/salesforce-adapter/README.md
The "selected OAuth Scopes" needed for salto is both full & refresh_token
> Updated connected app salesforce README

- packages/zendesk-support-adapter/src/config.ts
- packages/zendesk-support-adapter/system_config_doc.md
_omit macro attachments in zendesk_
---
---
_Zendesk_support_adapter_
* Macro attachments field will be omitted
---
_Macro attachments field in zendesk will be omitted_
> SALTO-1923: omit macro attachments in zendesk

- packages/jira-adapter/src/config.ts
- packages/jira-adapter/system_config_doc.md
Removed redundant fields from Jira NaCls
---
None
---
None
> SALTO-1715: removed redundant fields

- packages/adapter-components/src/deployment/deployment.ts
- packages/adapter-components/src/references/reference_mapping.ts
- packages/zendesk-support-adapter/e2e_test/adapter.test.ts
- packages/zendesk-support-adapter/e2e_test/mock_elements.ts
- packages/zendesk-support-adapter/src/adapter.ts
- packages/zendesk-support-adapter/src/config.ts
- packages/zendesk-support-adapter/src/deployment.ts
- packages/zendesk-support-adapter/src/filters/custom_field_options/creator.ts
- packages/zendesk-support-adapter/src/filters/custom_field_options/ticket_field.ts
- packages/zendesk-support-adapter/src/filters/custom_field_options/user_field.ts
- packages/zendesk-support-adapter/src/filters/field_references.ts
- packages/zendesk-support-adapter/src/filters/view.ts
- packages/zendesk-support-adapter/src/filters/workspace.ts
- packages/zendesk-support-adapter/src/group_change.ts
- packages/zendesk-support-adapter/test/filters/custom_field_options/ticket_field.test.ts
- packages/zendesk-support-adapter/test/group_change.test.ts
_support zendesk deploy of ticket and user fields_
---
---
_None (deploy not released yet)_
---
_add default_custom_field_option to ticket/user_field_
> SALTO-1900: support zendesk deploy of ticket and user fields

- packages/jira-adapter/src/config.ts
- packages/jira-adapter/src/filters/screen/screen.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/test/filters/screen/screen.test.ts
Removed list of available fields from `Screen`
---
None
---
None
> Removed list of available fields from screen

- packages/jira-adapter/src/filters/field_configuration_trashed_fields.ts
fixed log in field_configuration_trashed_fields
---
None
---
None
> Fixed log in field_configuration_trashed_fields

- packages/jira-adapter/src/filters/board.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/test/filters/board.test.ts
Added reference from board to fields
---
None
---
None
> SALTO-1931: added references to board

- packages/cli/src/commands/fetch.ts
- packages/cli/test/commands/fetch.test.ts
- packages/core/src/api.ts
- packages/core/src/core/fetch.ts
- packages/core/test/core/fetch.test.ts
---
*CLI*:
* Added the ability to fetch from the state to Fetch From Workspace
> SALTO-1947 - Add the ability to fetch from the state to Fetch From Workspace

- packages/zendesk-support-adapter/src/adapter.ts
- packages/zendesk-support-adapter/src/config.ts
- packages/zendesk-support-adapter/src/deployment.ts
- packages/zendesk-support-adapter/src/filters/custom_field_options/creator.ts
- packages/zendesk-support-adapter/src/filters/dynamic_content.ts
- packages/zendesk-support-adapter/src/filters/field_references.ts
- packages/zendesk-support-adapter/src/group_change.ts
- packages/zendesk-support-adapter/test/filters/dynamic_content.test.ts
- packages/zendesk-support-adapter/test/resolve_changes.test.ts
_support deploy of dynamic content_
---
---
_None_
---
_None_
> SALTO-1860: support deploy of dynamic content

- packages/jira-adapter/src/config.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/system_config_doc.md
Fixed Jira configuration to work after the swagger changed
---
None
---
None
> SALTO-1958: fixed jira config after swagger change

- packages/adapter-components/src/references/index.ts
- packages/adapter-components/src/references/reference_mapping.ts
- packages/zendesk-support-adapter/src/config.ts
- packages/zendesk-support-adapter/src/filters/field_references.ts
- packages/zendesk-support-adapter/system_config_doc.md
- packages/zendesk-support-adapter/test/filters/field_references.test.ts
- packages/zendesk-support-adapter/test/resolve_changes.test.ts
_Add more references_
---
None
---
* Add more references
---
_Add more references to zendesk adapter_
> SALTO-1950: add more references

- .circleci/config.yml
This is tidying up some configuration items
---
None
---
None
---
None
> Use salto context in main

- packages/zendesk-support-adapter/src/filters/field_references.ts
- packages/zendesk-support-adapter/test/filters/field_references.test.ts
- packages/zendesk-support-adapter/test/resolve_changes.test.ts
_add references to custom_field_options values
---
---
* Add references to custom_field_options values
---
_Add references to custom_field_options values in zendesk adapter_
> SALTO-1950: add references to values

- packages/jira-adapter/src/config.ts
- packages/jira-adapter/system_config_doc.md
- packages/jira-adapter/test/adapter.test.ts
Updated to work with new swagger (will have to create another PR the swagger URL back to main once this will be on prod)
---
None
---
None
> SALTO-1958: updated to new swagger

- packages/adapter-components/src/deployment/change_validators/check_deployment_based_on_config.ts
- packages/adapter-components/test/deployment/change_validators/check_deployment.test.ts
- packages/zendesk-support-adapter/src/adapter.ts
- packages/zendesk-support-adapter/src/change_validator.ts
- packages/zendesk-support-adapter/src/filters/field_references.ts
- packages/zendesk-support-adapter/src/filters/organization_field.ts
- packages/zendesk-support-adapter/src/group_change.ts
- packages/zendesk-support-adapter/test/change_validator.test.ts
- packages/zendesk-support-adapter/test/filters/organization_field.test.ts
_support deploy of organization field_
---
None
---
_None_
---
_None_
> SALTO-1929: support deploy of organization field

- packages/jira-adapter/e2e_test/instances/issueTypeScreenScheme.ts
- packages/jira-adapter/src/filters/sort_lists.ts
Sort lists in Jira to reduce noise between envs
---
None
---
None
> SALTO-1977: Sort lists in Jira to reduce noise

- packages/zendesk-support-adapter/src/filters/view.ts
- packages/zendesk-support-adapter/test/filters/view.test.ts
> SALTO-1954: fix bug in deploy of views

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/filters/user.ts
- packages/jira-adapter/test/filters/user.test.ts
Replaced the User object with its display name 
---
None
---
None
> SALTO-1979: replaced user info with the user display name

- packages/netsuite-adapter/src/filters/internal_ids/constants.ts
- packages/netsuite-adapter/src/filters/internal_ids/sdf_internal_ids.ts
- packages/netsuite-adapter/test/filters/internal_ids/sdf_internal_ids.test.ts
Some SuiteQls stopped working after the latest NetSuite upgrade, changed the queries to work and do the same 🤷‍♂️
---
None
---
None
> SALTO-2034: fixed suiteQLs to work with latest NetSuite

- packages/workato-adapter/src/filters/cross_service/netsuite/element_index.ts
- packages/workato-adapter/test/filters/recipe_references.test.ts
expect `customrecordtype.customrecordcustomfields.customrecordcustomfield` to be map instead of list 
---
- fix bug - iterate map values instead of lists items 
---
None
> SALTO-2041 fix netsuite references in workato

- docs/syntax.md
- docs/user_guide.md
Add details about nacl-case to OSS docs.
---
None
---
None
> SALTO-2040 Add documentation about nacl-case

- packages/jira-adapter/src/config.ts
- packages/jira-adapter/src/filters/project.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/test/filters/project.test.ts
Added issueSecurityScheme to project
---
None
---
None
> SALTO-2015: added issueSecurityScheme to project

- packages/netsuite-adapter/package.json
- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/test/client/soap_client.test.ts
- packages/netsuite-adapter/test/client/suiteapp_client.test.ts
added retries on SuiteApp requests (soap and axios)
---
- added retries on SuiteApp requests
---
None
> SALTO-1959 add retry for concurrency limit error

- packages/adapter-components/src/elements/index.ts
- packages/adapter-components/src/elements/instance_elements.ts
- packages/jira-adapter/e2e_test/instances/index.ts
- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/filters/fields/field_name_filter.ts
- packages/jira-adapter/src/filters/fields/field_structure_filter.ts
- packages/jira-adapter/test/filters/fields/field_name_filter.test.ts
Added __c to custom fields names in Jira
---
Jira Adapter:
- Added `__c` suffix to custom field names
---
None
> SALTO-2053: added __c to custom fields names

- packages/workato-adapter/src/filters/add_root_folder.ts
- packages/workato-adapter/test/adapter.test.ts
- packages/workato-adapter/test/filters/add_root_folder.test.ts
Switch https://github.com/salto-io/salto/pull/2786 from all caps
---
None
---
None
> SALTO-2060 Switch case

- packages/workspace/src/workspace/workspace.ts
> SAAS-4255: log validation errors with a log level that matches the validation severity

- packages/workato-adapter/src/config.ts
- packages/workato-adapter/test/adapter.test.ts
Temporarily remove elem id getter in workato
---
None
---
None
> Revert "SALTO-2059 Add elemIdGetter in Workato (#2784)"

- packages/jira-adapter/src/filters/fields/field_name_filter.ts
- packages/jira-adapter/test/filters/fields/field_name_filter.test.ts
Fixed usage of ElemIdGetter with fields
---
None
---
None
> SALTO-2065: Fixed fields elemIdGetter

- packages/netsuite-adapter/index.ts
export a function to use in the Saas
---
None
---
None
> SALTO-1975 export netsuite toCredentialsAccountId

- packages/jira-adapter/src/filters/workflow/transition_ids_filter.ts
- packages/jira-adapter/test/filters/workflow/transition_ids_filter.test.ts
Added sort by to transition keys so the order of the statuses id won't matter
---
None
---
None
> Added sort by to transition keys

- packages/netsuite-adapter/src/adapter_creator.ts
- packages/netsuite-adapter/test/adapter_creator.test.ts
> SALTO-2105: Netsuite - throw on accountId that contains whitespaces

- packages/core/index.ts
Needed for PR: [SAAS-3814](https://github.com/salto-io/salto_private/pull/3228)
> Exporting STATES_DIR_NAME from @salto/core

- packages/zendesk-support-adapter/src/change_validator.ts
- packages/zendesk-support-adapter/src/change_validators/index.ts
- packages/zendesk-support-adapter/src/change_validators/invalid_actions.ts
- packages/zendesk-support-adapter/test/change_validators/invalid_actions.test.ts
_Prevent creating trigger with unsupported actions_
---
None
---
_None_
---
_None_
> SALTO-2123: prevent creating trigger with unsupported actions

- packages/adapter-components/src/elements/ducktype/index.ts
- packages/adapter-components/src/elements/ducktype/transformer.ts
- packages/adapter-components/test/elements/ducktype/transformer.test.ts
- packages/workato-adapter/src/adapter.ts
- packages/zendesk-support-adapter/src/adapter.ts
- packages/zendesk-support-adapter/src/adapter_creator.ts
- packages/zendesk-support-adapter/src/config_change.ts
- packages/zendesk-support-adapter/test/adapter.test.ts
_Add config changes to zendesk_
---
---
_None_
---
_None_
> SALTO-1993: add config changes to zendesk

- packages/core/src/core/fetch.ts
> Add more information to debug logs on fetch conflicts

- packages/core/src/core/fetch.ts
> Add more information to fetch conflict logs

- packages/adapter-utils/src/collisions.ts
_Fix collision error log_
---
None
---
_None_
---
_None_
> SALTO-2139: fix collision error log

- packages/workspace/src/parser/internal/native/errors.ts
- packages/workspace/src/parser/internal/native/lexer.ts
- packages/workspace/test/parser/errors.test.ts
Change the content merge conflict's message
---
---
"Content merge conflict" -> "Merge conflict"
---
> update merge conflict error

- packages/zendesk-support-adapter/src/filters/field_references.ts
_add references to ticket fields in ticket form conditions_
---
None
---
* Add references to ticket fields in ticket form conditions
---
_References to ticket fields in ticket form conditions will appear_
> SALTO-2147: add references to ticket fields in ticket form conditions

- .circleci/config.yml
---
https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034#deprecated-images-3
---
_None_
---
_None_
> replace deprecated circle ci image

- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/types.ts
- packages/netsuite-adapter/src/filters/author_information/constants.ts
- packages/netsuite-adapter/src/filters/author_information/system_note.ts
- packages/netsuite-adapter/test/filters/author_information/system_note.test.ts
A better SuiteQL query for system notes - 10 times faster than before.
---
None
---
None
> SALTO-2127 improved system notes query

- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
add timeout to SuiteApp axios requests
---
- add timeout to SuiteApp axios requests
---
None
> SALTO-2172 add timeout to SuiteApp axios requests

- packages/workato-adapter/src/config.ts
- packages/workato-adapter/test/adapter.test.ts
Add back after reverting.
---
None (no changes since last major version)
---
None
> SALTO-2059 Set service id fields in workato

- packages/core/index.ts
- packages/core/src/local-workspace/workspace.ts
expose a function to use in saas
---
---
Expose adapter config creation that includes creating config types per account name, needed since the multiple accounts per service change.
---
no change
> expose adapter creation function through workspace

- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/test/client/suiteapp_client.test.ts
Add retries for 5xx errors in SuiteApp
---
- Add retries for 5xx errors in SuiteApp
---
None
> SALTO-2163 add retries for 5xx errors in SuiteApp

- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
Fix bug of `INVALID_LOGIN_ATTEMPT` error in long SuiteApp requests by generating an auth header before each request.
---
- Bug Fix - generate SuiteApp Auth header before each request
---
None
> SALTO-2184 generate suiteapp auth header before each request

- packages/jira-adapter/src/adapter_creator.ts
- packages/jira-adapter/src/config.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/system_config_doc.md
Added support for fetching and referencing issue events
---
- Added support for fetching IssueEvents
---
- After the next fetch, IssueEvent instances will be added to the workspace
> SALTO-2201: Fetch issue events

- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
Before this change each NaCl file would be checked separately, since checking
involves both IO (reading the file) and compute (comparing md5) this was inefficient.
increasing concurrency will improve workspace load times for workspaces with many NaCl files
---
---
Core:
- Improve workspace load time for workspaces with a large number of NaCl files
---
_None_
> SAAS-4128: Improve workspace load time by increasing file checking concurrency

- packages/workspace/src/serializer/elements.ts
When there is no static file reviver (this is the case currently in the state)
the code that clones all the elements after deserialization is redundant
not running it slightly improves the performance of accessing elements from the state
---
Reading data from rocksdb is fairly fast, but deserializing takes a very long time.
Seeing ~30% improvement when iterating all the elements from the state file locally.
Currently this does not affect the time it takes to access workspace elements since that would require a bigger change to the way static files are stored in elements.
---
Core:
- Improved performance of accessing state data
---
_None_
> Improve deserialize performance for state elements

- packages/zendesk-support-adapter/src/change_validators/order.ts
- packages/zendesk-support-adapter/src/change_validators/trigger_order.ts
- packages/zendesk-support-adapter/test/change_validators/order.test.ts
- packages/zendesk-support-adapter/test/change_validators/trigger_order.test.ts
> SALTO-2155: modified change validator messages for zd ordering

- packages/jira-adapter/e2e_test/instances/notificationScheme.ts
- packages/jira-adapter/src/filters/notification_scheme/notification_events.ts
- packages/jira-adapter/src/filters/sort_lists.ts
- packages/jira-adapter/test/filters/sort_lists.test.ts
Fixed inconsistency in the notifications order in NotificationScheme which fails the e2e sporadically
---
_Jira Adapter_: 
- Fixed inconsistency in the notifications order in NotificationScheme
---
- Order of notifications in NotificationScheme might change
> SALTO-2213: Fixed notification scheme order

- packages/zendesk-support-adapter/src/change_validators/brand_creation.ts
- packages/zendesk-support-adapter/test/change_validators/brand_creation.test.ts
Rephrasing the warning message of added brand in Zendesk for nicer output in the OSS
---
* Warning message is updated
> SALTO-2187 rephrasing warning message

- packages/netsuite-adapter/src/elements_source_index/elements_source_index.ts
- packages/netsuite-adapter/src/elements_source_index/types.ts
- packages/netsuite-adapter/src/filters/author_information/system_note.ts
- packages/netsuite-adapter/test/elements_source_index.test.ts
- packages/netsuite-adapter/test/filters/author_information/saved_searches.test.ts
- packages/netsuite-adapter/test/filters/author_information/system_note.test.ts
- packages/netsuite-adapter/test/filters/data_instances_references.test.ts
- packages/netsuite-adapter/test/filters/data_types_custom_fields.test.ts
- packages/netsuite-adapter/test/filters/internal_ids/sdf_internal_ids.test.ts
- packages/netsuite-adapter/test/filters/parse_saved_searches.test.ts
- packages/netsuite-adapter/test/filters/remove_unsupported_types.test.ts
- packages/netsuite-adapter/test/filters/service_urls.test.ts
- packages/netsuite-adapter/test/utils.ts
query systemnotes since last fetch only
---
- Query "author information" of elements that have been changed since last fetch to reduce query time 
---
None
> SALTO-2246 query systemnotes since last fetch only

- packages/workspace/src/serializer/elements.ts
Make deserialize faster by avoiding memory allocations and avoiding a JS callback in JSON.parse
---
A lot of the difference is indentation, very much recommended to review this with whitespace diff turned off
A few changes made here:
1. Not passing a "customizer" to JSON.parse. this is significant because without a customizer JSON.parse runs significantly faster
2. Given that we still need to revive classes, after the JSON.parse phase we add an iteration phase where we revive classes in-place to avoid unneeded (and slow) memory allocations
3. Track the location of static files so they can be resolved in-place later without having to iterate the whole value again
---
Core:
- Improve deserialize performance which should improve operation times like env compare and deploy …
> SALTO-2240: Improve deserialize performance

- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/filter.ts
- packages/netsuite-adapter/src/filters/service_urls.ts
- packages/netsuite-adapter/src/service_url/constant_urls.ts
- packages/netsuite-adapter/src/service_url/custom_field.ts
- packages/netsuite-adapter/src/service_url/custom_record_type.ts
- packages/netsuite-adapter/src/service_url/custom_transaction_type.ts
- packages/netsuite-adapter/src/service_url/emailtemplate.ts
- packages/netsuite-adapter/src/service_url/file_cabinet.ts
- packages/netsuite-adapter/src/service_url/role.ts
- packages/netsuite-adapter/src/service_url/script.ts
- packages/netsuite-adapter/src/service_url/sublist.ts
- packages/netsuite-adapter/src/service_url/types.ts
- packages/netsuite-adapter/src/suiteapp_file_cabinet.ts
- packages/netsuite-adapter/test/filter.test.ts
SALTO-2248 fix bug in `getPathToIdMap` and add logs to filters
---
- fix bug in `getPathToIdMap` that caused a very long fetch
---
None
> SALTO-2248 fix bug in getPathToIdMap and add logs to filters

- packages/zendesk-support-adapter/src/change_validators/order.ts
- packages/zendesk-support-adapter/src/change_validators/trigger_order.ts
- packages/zendesk-support-adapter/test/change_validators/order.test.ts
- packages/zendesk-support-adapter/test/change_validators/trigger_order.test.ts
_change order change validators to results warnings_
---
None
---
_None_
---
_None_
> SALTO-2244: change order change validators to results warnings

- packages/netsuite-adapter/src/config.ts
NetSuite Adapter: Modify the default adapter config to reduce the scope of default fetched FileCabinet folders for accelerated fetch
> SALTO-2249: NetSuite - Reduce the scope of default fetched FileCabinet folders

- packages/jira-adapter/src/config.ts
- packages/jira-adapter/src/filters/automation/automation_fetch.ts
- packages/jira-adapter/src/filters/statuses/missing_statuses.ts
- packages/jira-adapter/src/filters/webhook/webhook.ts
- packages/jira-adapter/test/filters/automation/automation_fetch.test.ts
- packages/jira-adapter/test/filters/statuses/missing_statuses.test.ts
- packages/jira-adapter/test/filters/webhook/webhook.test.ts
Added support for Automation and Webhook in the fetch config
---
Added support for including/excluding automations and webhooks
---
None
> SALTO-1792: added fetch configuration support for missing types in jira

- packages/zendesk-support-adapter/src/adapter.ts
- packages/zendesk-support-adapter/src/filters/tag.ts
- packages/zendesk-support-adapter/src/filters/user.ts
- packages/zendesk-support-adapter/src/filters/utils.ts
- packages/zendesk-support-adapter/test/filters/user.test.ts
_Fix warnings in zendesk fetch_
---
None
---
_None_
---
_None_
> SALTO-2271: fix warnings in zendesk fetch

- packages/adapter-api/src/element_id.ts
- packages/core/src/core/diff.ts
move createAllElemIdParents to be an ElemID method
---
None
---
None
> SALTO-2209 move createAllElemIdParents to be an ElemID method

- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/config.ts
- packages/jira-adapter/src/filters/service_url/service_url.ts
- packages/jira-adapter/src/filters/service_url/service_url_information.ts
- packages/jira-adapter/test/filters/service_url/service_url.test.ts
- packages/jira-adapter/test/filters/service_url/service_url_information.test.ts
reverted go to service to avoid reproducing a bug, but now its fixed.
---
---
---
> SALTO-1897/add go to service to jira unrevert

- packages/adapter-components/src/references/field_references.ts
_add safties for check missing ref function_
---
None
---
_None_
---
_None_
> SAAS-5086: add safties for check missing ref function

- packages/netsuite-adapter/src/change_validators/mapped_lists_indexes.ts
- packages/netsuite-adapter/src/mapped_lists/utils.ts
- packages/netsuite-adapter/test/change_validators/mapped_lists_indexes.test.ts
return warnings on wrong index attribute in mapped lists
---
- return warnings on wrong index attribute in mapped lists
---
None
> SALTO-2262 return warnings on wrong index attribute in mapped lists

- packages/adapter-components/src/filters/ducktype/hide_types.ts
- packages/adapter-components/src/filters/referenced_instance_names.ts
- packages/adapter-components/src/filters/service_url.ts
- packages/zendesk-support-adapter/src/filters/dynamic_content_references.ts
- packages/zendesk-support-adapter/src/filters/field_references.ts
- packages/zendesk-support-adapter/src/filters/macro_attachments.ts
- packages/zendesk-support-adapter/src/filters/remove_definition_instances.ts
- packages/zendesk-support-adapter/src/filters/tag.ts
- packages/zendesk-support-adapter/src/filters/unordered_lists.ts
- packages/zendesk-support-adapter/src/filters/user.ts
_add logs in some filters to debug zendesk fetch duration_
---
for debugging purposes
---
_None_
---
_None_
> SALTO-2270: add logs in some filters to debug zendesk fetch duration

- packages/adapter-api/src/dependency_changer.ts
- packages/core/src/core/plan/common.ts
- packages/core/src/core/plan/plan.ts
- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/change_validator.ts
- packages/netsuite-adapter/src/change_validators/client_validation.ts
- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/src/client/sdf_client.ts
- packages/netsuite-adapter/src/client/types.ts
- packages/netsuite-adapter/src/config.ts
- packages/netsuite-adapter/src/constants.ts
- packages/netsuite-adapter/src/errors.ts
- packages/netsuite-adapter/src/transformer.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/netsuite-adapter/test/adapter_creator.test.ts
- packages/netsuite-adapter/test/change_validator.test.ts
- packages/netsuite-adapter/test/change_validators/client_validation.test.ts
- packages/netsuite-adapter/test/client/client.test.ts
- packages/netsuite-adapter/test/client/sdf_client.test.ts
add NetSuite client validation
---
- add client validation
---
None
> SALTO-2263 add netsuite client validation

- packages/jira-adapter/src/filters/board/board_columns.ts
Added some logs to debug flaky e2e test
---
None
---
None
> SALTO-2213: added logs to debug e2e

- packages/adapter-utils/src/utils.ts
Resolved reference values can be fully resolved elements.
In such a case, using a naive compare would lead us to traversing all the references
in those elements, and in the case of a reference cycle, this traversal can be infinite.
Added custom logic for comparing elements in this scenario (when we know they are the value of a reference)
---
Might add unit tests in a separate PR, but not before manual tests.
~will update here once those manual tests are done.~
manual tests done
---
- Fixed issue where sometimes deployment of CPQ records would get stuck
---
_None_
> SAAS-4962: Fix possible infinite loop on restore values

- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/src/client/types.ts
Add axios error message on InvalidSuiteAppCredentialsError
---
- Add axios error message on InvalidSuiteAppCredentialsError
---
None
> SALTO-2325 Add axios error message on InvalidSuiteAppCredentialsError

- packages/workspace/src/expressions.ts
---
V8 has a limit of ~2 million promises in a single promise.all call.
when profiles are large enough and we try to resolve all of them it seems like we can pass this limit.
using `for await` through `awu` instead
---
Core:
- Resolve very unlikely scenario where resolve would crash with "too many elements passed to Promise.all"
---
_None_
> SALTO-2260: Avoid waiting for too many promises in a single call

- packages/core/src/local-workspace/adapters_config.ts
- packages/core/src/local-workspace/remote_map.ts
- packages/core/src/local-workspace/static_files_cache.ts
- packages/core/src/local-workspace/workspace.ts
- packages/core/test/workspace/local/static_files_cache.test.ts
> Revert "SAAS-4004: Move static files cache to RocksDB"

- packages/cli/test/mocks.ts
- packages/core/test/common/nacl_file_source.ts
- packages/workspace/src/workspace/nacl_files/multi_env/multi_env_source.ts
- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
- packages/workspace/src/workspace/workspace.ts
- packages/workspace/test/common/nacl_file_source.ts
- packages/workspace/test/workspace/multi_env/multi_env_source.test.ts
- packages/workspace/test/workspace/nacl_files/nacl_files_source.test.ts
- packages/workspace/test/workspace/workspace.test.ts
_expose elementsIndex from workspace_
---
None
---
_None_
---
_None_
> SALTO-2317: expose elementsIndex from workspace

- packages/core/src/local-workspace/adapters_config.ts
- packages/core/src/local-workspace/remote_map.ts
- packages/core/src/local-workspace/static_files_cache.ts
- packages/core/src/local-workspace/workspace.ts
- packages/core/test/workspace/local/remote_map_connection.test.ts
- packages/core/test/workspace/local/static_files_cache.test.ts
This reverts commit 8aa079a1aebb9a0e4b5354d1ac598ab47a0fb69c.
there are currently failing tests in saas over this pr and i need to merge a revert to a regression before the deploy.
---
---
---
> SAAS-4004: Move static files cache to RocksDB (#3074) - REVERT

- packages/cli/src/commands/element.ts
- packages/cli/test/commands/element.test.ts
- packages/workspace/src/workspace/static_files/index.ts
- packages/workspace/src/workspace/static_files/source.ts
- packages/workspace/test/workspace/static_files/source.test.ts
New CLI command allows printing specific values / elements from the workspace / state
---
Still missing tests for the command, will be added soon
---
CLI:
- Added new element print command
---
_None_
> Added element print command to CLI

- packages/salesforce-adapter/fetch-config-doc.md
Added a guide to be linked from docs.salto.io, containing Salesforce app connections configuration examples
> added packages/salesforce-adapter/fetch-config-doc.md

- yarn.lock
---
continuing with versions I missed in #3094 
---
_None_
---
_None_
> bump versions of ansi-regex

- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/test/client/suiteapp_client.test.ts
retry SuiteApp concurrency error
---
Netsuite-Adapter:
- retry SuiteApp concurrency error
---
None
> SALTO-2372 retry SuiteApp concurrency error

- packages/workspace/src/validator.ts
Fixed issue with the previous PR where lists were not validated with the correct type
---
---
_None_
---
_None_
> SALTO-2379: fix validator logic for lists

- packages/adapter-utils/src/utils.ts
- packages/adapter-utils/test/utils.test.ts
- packages/core/src/core/plan/change_validators/unresolved_references.ts
- packages/core/test/core/plan/change_validators/unresolved_references.test.ts
- packages/workspace/src/validator.ts
- packages/workspace/test/validator.test.ts
- packages/zendesk-support-adapter/src/adapter.ts
- packages/zendesk-support-adapter/src/filters/handle_template_expressions.ts
- packages/zendesk-support-adapter/test/filters/handle_template_expressions.test.ts
Handles macro actions that refer to fields as part of their formula
---
---
Zendesk:
Will now support references to fields in macro actions.
---
Nacls will now parse references to fields in macro actions. These will look like:
"Some message in macro action ${zendesk_support.referenced_field_type.instance.referencedfield}"
> Implement new template filter

- packages/salesforce-adapter/src/client/client.ts
- packages/salesforce-adapter/src/types.ts
Added log in Salesforce client for more visibility on stuck fetches
> SALTO-2143: Salesforce stuck fetches visibility

- packages/core/src/local-workspace/adapters_config.ts
- packages/core/src/local-workspace/remote_map.ts
- packages/core/src/local-workspace/static_files_cache.ts
- packages/core/src/local-workspace/workspace.ts
- packages/core/test/workspace/local/remote_map_connection.test.ts
- packages/core/test/workspace/local/static_files_cache.test.ts
This reverts commit d9049677a2c14268c1f90c5f4a0c182475cfb087.
---
None
---
None
---
None
> Revert "SAAS-4004: Move static files cache to RocksDB  (#3077)"

- packages/adapter-api/src/element_id.ts
- packages/adapter-api/test/elements.test.ts
_add getRelativePath to ElemID_
---
None
---
_None_
---
_None_
> add getRelativePath to ElemID

- packages/salesforce-adapter/package.json
- yarn.lock
Bump requestertry to resolve security alert
---
None
---
None
> SALTO-2437 bump requestretry

- packages/core/src/local-workspace/remote_map.ts
- packages/core/test/workspace/local/remote_map.test.ts
- packages/workspace/src/workspace/remote_map.ts
Added the ability to filter remoteMaps in keys/values/entries with a filtering function
---
* No user impact
> SALTO-2395 -  Remote Map filtering

- packages/netsuite-adapter/src/client/suiteapp_client/errors.ts
- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/src/suiteapp_file_cabinet.ts
- packages/netsuite-adapter/test/client/errors.test.ts
- packages/netsuite-adapter/test/client/suiteapp_client.test.ts
log and retry on invalid suiteapp results
---
- bugfix: log and retry on invalid suiteapp results
---
None
> SALTO-2450 log and retry on invalid suiteapp results

- packages/adapter-components/index.ts
- packages/adapter-components/src/elements/soap/index.ts
- packages/adapter-components/src/elements/soap/type_elements/types_generator.ts
- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/src/data_elements/data_elements.ts
- packages/netsuite-adapter/src/filters/remove_unsupported_types.ts
- packages/netsuite-adapter/test/client/soap_client.test.ts
- packages/netsuite-adapter/test/data_elements/data_elements.test.ts
Avoid the entire soap package export from https://github.com/salto-io/salto/pull/3167
---
None
---
None
> SALTO-2462 reduce soap export

- packages/netsuite-adapter/src/client/suiteapp_client/soap_client/soap_client.ts
- packages/netsuite-adapter/test/client/soap_client.test.ts
add retries for 5xx errors in SuiteApp SOAP
---
---
- add retries for 5xx errors in SuiteApp SOAP
---
None
> SALTO-2163 add retries for 5xx errors in SuiteApp SOAP

- packages/netsuite-adapter/src/change_validators/client_validation.ts
- packages/netsuite-adapter/test/change_validators/client_validation.test.ts
change SDF client validation error severity to warning
---
- change SDF client validation error severity to warning
> SALTO-2353 change SDF client validation error severity to warning

- packages/jira-adapter/src/filters/project.ts
- packages/jira-adapter/test/filters/project.test.ts
Fixed project creation failing with `Received an invalid field configuration scheme`
---
- Fixed cases of project creation failures with an error `Received an invalid field configuration scheme`
---
None
> SALTO-2506: fixed error of invalid field configuration scheme

- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
fixed log in case of failure to update nacl file
---
None.
---
None.
---
None.
> SALTO-2368 - fixed log in case of failure to update nacl file

- packages/netsuite-adapter/src/filters/author_information/system_note.ts
- packages/netsuite-adapter/test/filters/author_information/system_note.test.ts
Fixed system note query
---
- Fixed author information query not working in NetSuite 2022.2
---
None
> SALTO-2534: fixed system note query

- packages/netsuite-adapter/src/filters/author_information/constants.ts
- packages/netsuite-adapter/src/filters/author_information/system_note.ts
- packages/netsuite-adapter/test/filters/author_information/system_note.test.ts
sort system notes by date (netsuite)
---
None
---
None
> SALTO-2534 sort system notes by date (netsuite)

- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
Moved the calculation of the merged source map to a different function so it can be freed once we are done using it to find a location for each change.
Also added logs and some minor improvements to the calculation of which files are relevant to update
---
Hopefully this will provide more insight into the performance of updating nacl files in the workspace
---
_None_
---
_None_
> SALTO-2483, SALTO-2482: Improve potential memory consumption when updating nacl files

- packages/salesforce-adapter/src/types.ts
_Exclude Salesforce Layout "CaseInteraction_Case_Feed_Layout"_
---
None
---
* "CaseInteraction_Case_Feed_Layout" will not fetched by default.
---
None
> SALTO-2491 Exclude Salesforce Layout "CaseInteraction_Case_Feed_Layout"

- packages/core/src/core/fetch.ts
> SALTO-2571: Reduce the log level for super noisy log line

- packages/zendesk-adapter/e2e_test/adapter.test.ts
Add BRAND_LOGO support to Zendesk e2e
---
---
* Add brand_logo support to Zendesk e2e
> SALTO-2549-add-zendesk-brand-logo-to-e2e

- packages/workspace/src/workspace/nacl_files/nacl_files_source.ts
Parse sourceMaps instead of using cached sourceMaps in order to improve performance when updating nacl files.
---
Workspace:
- Improved performance when updating nacl files.
---
_None_
> SALTO-2483 Avoid using cached sourceMaps

- packages/netsuite-adapter/src/client/suiteapp_client/constants.ts
- packages/netsuite-adapter/src/client/suiteapp_client/suiteapp_client.ts
- packages/netsuite-adapter/src/client/suiteapp_client/types.ts
- packages/netsuite-adapter/src/types.ts
- packages/netsuite-adapter/test/client/suiteapp_client.test.ts
Reverts salto-io/salto#3235
---
Seems like this is causing issues with validating credentials in some scenarios
attempting to revert this to see if this is the reason for those issues
> Revert "Salto 2394 add suiteapp enabled check"

- packages/salesforce-adapter/cpq-config-doc.md
Add the types we added to the default exclude list to the CPQ example so users who use the example will exclude them as well.
---
-
---
-
> SALTO-1695, SALTO-2003, SALTO-2233, SALTO-1635, SALTO-2491 - Add new exclude default to CPQ example

- packages/zendesk-adapter/src/filters/field_references.ts
_add reference for group_ids_
---
None
---
_add reference for group_ids under user_segment_
---
None
> SALTO-2634: add reference for group_ids

- packages/salesforce-adapter/src/filters/field_references.ts
- packages/salesforce-adapter/src/transformers/reference_mapping.ts
- packages/salesforce-adapter/test/filters/field_references.test.ts
_Add reference to Custom fields in ReportType_
---
None
---
* Add reference to Custom fields in ReportType
---
* Add reference to Custom fields in ReportType
> SALTO-2136 Add reference to Custom fields in ReportType

- packages/zendesk-adapter/src/change_validators/automation_all_conditions.ts
- packages/zendesk-adapter/test/change_validators/automation_all_conditions.test.ts
change error for validator for automation conditions
---
None
---
_Zendesk_
* Change error message for automation condition validator
---
None
> SALTO-2151: add change validator for automation conditions error message change

- packages/jira-adapter/src/filters/workflow/workflow_properties_filter.ts
- packages/jira-adapter/src/reference_mapping.ts
- packages/jira-adapter/src/references/workflow_properties.ts
- packages/jira-adapter/test/filters/workflow/workflow_properties_filter.test.ts
Parsed references from workflow status properties
---
- Parsed references from properties values inside workflow statuses
---
- Parsed references from properties values inside workflow statuses
> SALTO-2385: Extract references from workflow status properties

- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/field_references.ts
- packages/zendesk-adapter/src/filters/tag.ts
- packages/zendesk-adapter/test/filters/tag.test.ts
_Add deploy for zendesk guide user_segment_
---
None
---
_None_
---
_None_
> SALTO-2593: add deploy for zendesk guide user_segment

- packages/jira-adapter/src/config/api_config.ts
Removed redundant values from project
---
- Removed redundant values from project
---
- Some values will be removed from projects on the next fetch
> SALTO-2356: Remove redundant values from project

- packages/okta-adapter/src/config.ts
Change config to clean okta nacls
---
main changes:
- Add fields to `fieldsToOmit` and `fieldsToHide`
- Extract `PolicyRule` to `standaloneFields`
---
> SALTO-2699 Clean Okta nacls

- packages/netsuite-adapter/config_doc.md
Document the ability to exclude features and objects from the manifest passed to SDF
> SALTO-2731: document exclude features and objects from SDF manifest

- packages/adapter-api/src/elements.ts
- packages/adapter-api/src/values.ts
- packages/adapter-api/test/values.test.ts
- packages/adapter-utils/src/compare.ts
- packages/adapter-utils/test/compare.test.ts
- packages/core/src/api.ts
- packages/core/src/core/plan/plan.ts
- packages/core/src/core/plan/plan_item.ts
- packages/core/test/core/plan/plan.test.ts
- packages/lang-server/src/workspace.ts
- packages/workspace/src/workspace/nacl_files/multi_env/routers.ts
Added `CompareOptions` type and added it to all the compare options
---
None
---
None
> SALTO-2667: Changed detailed compare to accept compareOptions object

- packages/salesforce-adapter/src/filters/custom_objects_to_object_type.ts
In case the metadata API can return the same custom object more than once somehow, this would prevent the adapter from returning the same object twice and causing a merge conflict
---
see INCIDENT-991
This is probably not the correct place to fix this, but if we need to push something quickly, this might do the trick
---
- Fix issue where the Account object would get conflicting values on fetch
---
_None_
> salesforce - remove duplicate custom objects

- packages/core/src/core/plan/change_validators/check_deployment_annotations.ts
- packages/core/test/core/plan/change_validators/check_deployment_annotations.test.ts
- packages/jira-adapter/src/change_validators/global_project_contexts.ts
- packages/jira-adapter/src/change_validators/read_only_project_role.ts
- packages/jira-adapter/test/change_validators/global_project_contexts.test.ts
- packages/jira-adapter/test/change_validators/read_only_project_role.test.ts
Improved changed validator messages
---
- Improved changed validator messages
---
None
> SALTO-2681: Improve change validators messages in Jira

- packages/netsuite-adapter/src/filters/omit_sdf_untyped_values.ts
- packages/netsuite-adapter/test/filters/omit_sdf_untyped_values.test.ts
set `strictInstanceStructure` config default value to false
---
- set `strictInstanceStructure` config default value to false
> SALTO-2422 set strictInstanceStructure config default value to false

- packages/netsuite-adapter/scripts/types_generation/types_generator.py
- packages/netsuite-adapter/src/autogen/types/standard_types/entryForm.ts
- packages/netsuite-adapter/src/autogen/types/standard_types/publisheddashboard.ts
- packages/netsuite-adapter/src/autogen/types/standard_types/transactionForm.ts
Add missing netsuite SDF subtypes. The missing types are generated using `types_generator.py`
---
- add missing netsuite SDF subtypes
---
The following subtypes & fields will be added in `Types` folder. The matching values will be added to instances in `Records` folder.
_entryForm.nacl_
```
type netsuite.entryForm_tabs_tab_subItems_subTab_subLists_subList {
string id {
_required = true
}
string label {
_required = true
}
boolean visible {
}
boolean neverEmpty {
}
}
type netsuite.entryForm_tabs_tab_subItems_subTab_subLists {
"List<netsuite.entryForm_tabs_tab_subItems_subTab_subLists_subList>" subList {
}
}
type netsuite.entryForm_tabs_tab_subItems_subTab {
...
"List<netsuite.entryForm_tabs_tab_subItems_subTab_subLists>" subLists { …
```
> SALTO-2555 add missing netsuite SDF subtypes

- packages/netsuite-adapter/src/filters/translation_converter.ts
- packages/netsuite-adapter/test/filters/translation_converter.test.ts
fix translation converter filter to work with custom record types
---
- Fix translation converter filter to work with custom record types
---
None
> SALTO-820 fix translation converter filter to work with custom record types

- packages/jira-adapter/src/filters/automation/automation_deployment.ts
- packages/jira-adapter/test/filters/automation/automation_deployment.test.ts
_The deploying of a Label in Automation did not work, therefore I added another internal end-point in order to support it_
---
_None_
---
_None_
> SALTO-2782: fixed a bug with deploying labels in automation - Jira

- packages/core/package.json
- packages/core/src/local-workspace/s3_dir_store.ts
- packages/core/test/workspace/local/s3_dir_store.test.ts
- yarn.lock
Added retries to ECONNREFUSED on S3 operations when flushing the state
---
_Core_:
- Added retries to ECONNREFUSED on S3 operations when flushing the state
---
None
> SALTO-2826: add retries to S3 operations

- packages/zendesk-adapter/src/adapter.ts
- packages/zendesk-adapter/src/change_validators/translation_for_default_locale.ts
- packages/zendesk-adapter/src/filters/help_center_fetch_section_and_category.ts
- packages/zendesk-adapter/src/filters/help_center_section_and_category.ts
- packages/zendesk-adapter/test/change_validators/translation_for_default_locale.test.ts
- packages/zendesk-adapter/test/filters/help_center_fetch_section_and_category.test.ts
_fix CR for adding deploy capabilities to section and category_
---
None
---
None
---
None
> SALTO-2592: fix CR for adding deploy capabilities to section and category

- packages/jira-adapter/src/product_settings/data_center.ts
_Add screen plugin urls_
---
_None_
---
_None_
> SALTO-2847: add screen plugin urls - Jira DC

- packages/zendesk-adapter/src/filters/help_center_locale.ts
- packages/zendesk-adapter/test/adapter.test.ts
Remove duplicate type - same fix as https://github.com/salto-io/salto/pull/3418/files#diff-0a0301b201caa33b88e569ee9af23aa068eedaf891c6290a9da5fab8e2d8d690R90
---
None
---
None
> remove duplicate locale

- packages/jira-adapter/src/product_settings/data_center.ts
_Add plugin urls for Screens Jira DC - post, put and delete_
---
_None_
---
_None_
> SALTO-2847: add plugin urls for Screens - Jira DC

- packages/zendesk-adapter/src/adapter.ts
- packages/zendesk-adapter/src/change_validators/translation_for_default_locale.ts
- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/article.ts
- packages/zendesk-adapter/src/filters/help_center_section_and_category.ts
- packages/zendesk-adapter/test/change_validators/translation_for_default_locale.test.ts
_add deploy capabilities to article translation_
---
None
---
None
---
None
> SALTO-2889: add deploy capabilities to article translation

- packages/salesforce-adapter/fetch-config-doc.md
> SALTO-2807 - Fix Fetch config doc to include sbaa as well

- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/product_settings/data_center.ts
_Fetch only. 
the plugin PR is available [here](https://github.com/salto-io/jira-dc-app/pull/15)_
---
---
_None_
---
_None_
> SALTO-2844: support IssueEvents in Jira DC

- packages/jira-adapter/src/product_settings/data_center.ts
Added endpoints to fetch field in Jira DC
Plugin PR: https://github.com/salto-io/jira-dc-app/pull/17
---
None
---
None
> SALTO-2843: Added endpoints to fetch fields in Jira DC

- packages/zendesk-adapter/src/adapter.ts
- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/help_center_guide_settings.ts
- packages/zendesk-adapter/test/filters/help_center_guide_settings.test.ts
_support deploy for zendesk guide settings_
---
None
---
None
---
None
> SALTO-2830: support zendesk guide settings

- packages/jira-adapter/src/product_settings/data_center.ts
_Add screenScheme plugin urls_
---
_None_
---
_None_
> SALTO-2848: add screenScheme plugin urls - Jira DC

- packages/core/src/core/fetch.ts
Improve FetchFromWorkspace's logging to be able to better understand performance issues in different scenarios
---
* None
---
* None
> SALTO-2921 - Add a lot of log.times to the FetchFromWorkspace flow

- packages/jira-adapter/src/auth.ts
Opened Jira DC login option
---
None
---
None
> Opened Jira DC login option

- packages/salesforce-adapter/test/adapter.discover.test.ts
Changed the functions from parameters of unknowns to mocks
---
related to https://salto-io.atlassian.net/browse/SALTO-2236?focusedCommentId=48981&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-48981
---
None
---
None
> SALTO 2236 - Updated the test to look better

- packages/zendesk-adapter/src/adapter.ts
- packages/zendesk-adapter/src/filters/brands_filter.ts
- packages/zendesk-adapter/test/filters/categories_order.test.ts
- packages/zendesk-adapter/test/filters/remove_brand_logo_field.test.ts
Disable order for guide
---
none
---
none
---
none
> SALTO-2950 - Disabled order fields

- packages/zendesk-adapter/src/config.ts
fix deployment url for article translation
---
None 
---
None
---
None
> SALTO-2954: fix deployment url for article translation

- packages/adapter-utils/src/utils.ts
- packages/adapter-utils/test/utils.test.ts
- packages/jira-adapter/src/filters/automation/automation_structure.ts
- packages/salesforce-adapter/e2e_test/adapter.test.ts
- packages/salesforce-adapter/test/mock_elements.ts
- packages/zendesk-adapter/src/adapter.ts
_Add E2E test to check empty field deploy_
---
None
---
* Add E2E test to check empty field deploy
---
None
> SALTO-2863 Add E2E test to check empty field deploy

- packages/aws-utils/.eslintignore
- packages/aws-utils/.eslintrc.js
- packages/aws-utils/.gitignore
- packages/aws-utils/.vscode/launch.json
- packages/aws-utils/.vscode/settings.json
- packages/aws-utils/README.md
- packages/aws-utils/index.ts
- packages/aws-utils/jest.config.js
- packages/aws-utils/package.json
- packages/aws-utils/src/index.ts
- packages/aws-utils/src/utils.ts
- packages/aws-utils/test/utils.test.ts
- packages/aws-utils/tsconfig.json
- packages/core/package.json
- packages/core/src/local-workspace/s3_dir_store.ts
- packages/core/test/workspace/local/s3_dir_store.test.ts
- packages/core/tsconfig.json
- packages/persistent-pool/package.json
- salto.code-workspace
- yarn.lock
Create aws-utils package.
In addition, upgrade the `@aws-sdk` packages version to `3.198.0`
---
---
New package - `@salto-io/aws-utils`
---
None
> Create aws-utils package

- packages/jira-adapter/src/product_settings/data_center/api_config.ts
- packages/jira-adapter/src/product_settings/data_center/data_center.ts
- packages/jira-adapter/src/product_settings/index.ts
- packages/jira-adapter/test/product_settings/data_center.test.ts
Adjust service urls for Jira DC
---
None
---
None
> SALTO-2880: Adjust service urls for Jira DC

- packages/jira-adapter/src/product_settings/data_center/data_center.ts
_Add  field configuration plugin urls_
---
link to the plugin PR: https://github.com/salto-io/jira-dc-app/pull/22
---
---
> SALTO-2584 add  field configuration plugin urls - Jira DC

- packages/jira-adapter/src/product_settings/data_center/data_center.ts
_Plugin PR is available [here](https://github.com/salto-io/jira-dc-app/pull/21)_
---
_The lines removed are not merge errors, they are duplicates (probably a previous bad merge)_
---
None
---
None
> SALTO-2845: Jira DC Security Scheme (get)

- packages/jira-adapter/e2e_test/instances/field.ts
- packages/jira-adapter/e2e_test/instances/index.ts
There is an issue with getting the default value in fields. This is for now to unblock the CI
---
None
---
None
> Fixed Jira e2e

- packages/salesforce-adapter/cpq-sbaa-config-doc.md
> SALTO-2807_remove_fetchAllCustomSettings

- packages/zendesk-adapter/src/client/connection.ts
- packages/zendesk-adapter/src/filters/brand_logo.ts
- packages/zendesk-adapter/test/filters/brand_logo.test.ts
Update Zendesk brand_logo url
---
---
none.
---
none.
> SALTO-3001 update Zendesk brand_logo url

- packages/adapter-components/test/config/merge.test.ts
- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/product_settings/cloud.ts
- packages/jira-adapter/src/product_settings/data_center/api_config.ts
- packages/jira-adapter/src/product_settings/data_center/data_center.ts
- packages/jira-adapter/src/product_settings/utils.ts
---
the plugin PR is available [here](https://github.com/salto-io/jira-dc-app/pull/24)
First commit is a leftover from the previous try, an increase to merge's test coverage
---
None
---
None
> SALTO-2973: Jira DC support priorities retry

- packages/netsuite-adapter/src/client/sdf_client.ts
> Add log of the objectId that failed to be fetched using SDF

- packages/netsuite-adapter/src/client/sdf_client.ts
---
---
- Throw error with the objectId that failed to be fetched using SDF 
---
None
> Throw error with the objectId that failed to be fetched using SDF

- packages/zendesk-adapter/src/filters/guide_create_element_translations.ts
_fix bug for article translation zendesk guide_
---
None
---
None
---
None
> SALTO-2962: fix bug for article translation zendesk guide

- packages/zendesk-adapter/src/change_validators/translation_for_default_locale.ts
- packages/zendesk-adapter/src/filters/guide_section_and_category.ts
- packages/zendesk-adapter/test/change_validators/translation_for_default_locale.test.ts
- packages/zendesk-adapter/test/filters/guide_section_and_category.test.ts
_fix translation for default locale validator_
---
None
---
None
---
None
> SALTO-3007: fix translation for default locale validator

- packages/netsuite-adapter/src/filters/author_information/system_note.ts
- packages/netsuite-adapter/test/filters/author_information/system_note.test.ts
add _changed_by annotation to custom records
---
---
- Add _changed_by annotation to custom records
---
None
> SALTO-2995 add _changed_by annotation to custom records

- packages/jira-adapter/src/product_settings/data_center/data_center.ts
_Fetch Issue Type Scheme and its mappings to Issue Types_
---
The PR for the plugin is available [here](https://github.com/salto-io/jira-dc-app/pull/27)
---
None
---
None
> SALTO-2993: Jira DC support Issue Type Scheme (get)

- packages/netsuite-adapter/src/client/sdf_client.ts
- packages/netsuite-adapter/src/client/types.ts
- packages/netsuite-adapter/src/client/utils.ts
- packages/netsuite-adapter/src/config.ts
- packages/netsuite-adapter/src/query.ts
- packages/netsuite-adapter/test/config.test.ts
SALTO-2994 make netsuite config typesafe
---
---
None
---
None
> SALTO-2994 make netsuite config typesafe

- packages/netsuite-adapter/src/change_validators/instance_changes.ts
---
---
Netsuite adapter:
- Return a change error on deletion of a type definition
---
None
> SALTO-3020 return a change error on deletion of a type definition

- packages/jira-adapter/src/product_settings/data_center/data_center.ts
_Plugin PR is available [here](https://github.com/salto-io/jira-dc-app/pull/32)_
---
---
None
---
None
> SALTO-2993: Jira DC support Issue Type Scheme

- packages/workspace/package.json
- packages/workspace/test/workspace/workspace.test.ts
- packages/workspace/tsconfig.json
_remove workspace package dependency on salesforce-adapter_
---
None
---
remove workspace package dependency on salesforce-adapter
---
None
> SALTO-3032 remove workspace package dependency on salesforce-adapter

- packages/jira-adapter/src/product_settings/data_center/data_center.ts
Fixed status deletions in Jira DC
---
None
---
None
> SALTO-2987: fixed status deletions in Jira DC

- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/change_validator.ts
- packages/netsuite-adapter/src/change_validators/client_validation.ts
- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/src/custom_records/custom_record_type.ts
- packages/netsuite-adapter/src/elements_source_index/elements_source_index.ts
- packages/netsuite-adapter/src/elements_source_index/types.ts
- packages/netsuite-adapter/src/mapped_lists/utils.ts
- packages/netsuite-adapter/test/adapter.test.ts
- packages/netsuite-adapter/test/change_validator.test.ts
- packages/netsuite-adapter/test/change_validators/client_validation.test.ts
- packages/netsuite-adapter/test/client/client.test.ts
- packages/netsuite-adapter/test/elements_source_index.test.ts
- packages/netsuite-adapter/test/mapped_lists/utils.test.ts
- packages/netsuite-adapter/test/utils.ts
Using hardcoded types so the transformed elements will have fields with List<> ref types.
---
---
- Fix bug in map to list transformation on a validate-then-deploy flow.
---
None
> Convert maps to lists on SDF deploy using hardcoded types

- packages/salesforce-adapter/src/client/client.ts
_add messages to the error retry list _
---
None
---
* Fetch stability improvements
---
None
> SALTO-2933 SALTO-2497 SALTO-2268 SF add messages to the error retry list 

- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/filters/avatars.ts
- packages/jira-adapter/src/product_settings/cloud.ts
- packages/jira-adapter/src/product_settings/data_center/api_config.ts
- packages/jira-adapter/src/product_settings/data_center/data_center.ts
- packages/jira-adapter/test/filters/avatars.test.ts
_Plugin available [here](https://github.com/salto-io/jira-dc-app/pull/37)_
---
None
---
None
---
None
> SALTO-2846: Jira DC Projects (get)

- packages/jira-adapter/jest.config.js
- packages/jira-adapter/src/filters/workflow/workflow_deploy_filter.ts
- packages/jira-adapter/test/filters/workflow/workflow_deploy_filter.test.ts
Added support for workflow triggers in Jira DC
---
None
---
None
> SALTO-3033: Support workflows triggers in Jira DC

- packages/netsuite-adapter/README.md
- packages/netsuite-adapter/e2e_test/adapter.test.ts
- added `console.log`s for a better DX
- test instances deletions with suiteapp
---
None
---
None
> Fix netsuite e2e test

- packages/jira-adapter/src/product_settings/data_center/data_center.ts
_Plugin part available [here_](https://github.com/salto-io/jira-dc-app/pull/40)
---
---
None
---
None
> SALTO-2846: Jira DC projects modify (part 1)

- packages/netsuite-adapter/src/filters/omit_fields.ts
- packages/netsuite-adapter/test/filters/omit_fields.test.ts
We currently support filtering fields from instances only, and we should support filtering custom record types annotations too.
Config example:
```
fieldsToOmit = [
// omit annotations under custom record types
{
type = "customrecordtype"
fields = [
"instances",
]
},
// omit inner annotation values
{
type = "customrecordtype_permissions_permission"
fields = [
".*level"
]
},
// omit custom record type fields annotations 
{
type = "customrecordcustomfield"
fields = [
"is.*"
]
}
]
```
---
---
- support fieldsToOmit for custom record types
---
None
> SALTO-3051 support fieldsToOmit for custom record types

- packages/zendesk-adapter/src/filters/article/article.ts
- packages/zendesk-adapter/src/filters/article/article_body.ts
- packages/zendesk-adapter/src/filters/collision_errors.ts
Added log.time to filters that should take long
---
None
---
None
---
None
> SALTO-3058 - Zendesk Adapter - Added log.time to filters that should take long

- packages/jira-adapter/src/filters/account_id/account_id_filter.ts
- packages/jira-adapter/src/product_settings/data_center/api_config.ts
- packages/jira-adapter/src/product_settings/data_center/data_center.ts
- packages/jira-adapter/test/filters/account_id/account_id_filter.test.ts
_add dashboard pluging urls - Jira DC_
---
_link to the plugin PR [here](https://github.com/salto-io/jira-dc-app/pull/38)_
---
_None_
---
_None_
> SALTO_2583: add dashboard pluging urls - Jira DC

- packages/netsuite-adapter/src/filters/custom_record_types.ts
- packages/netsuite-adapter/src/filters/remove_unsupported_types.ts
- packages/netsuite-adapter/test/filters/custom_record_types.test.ts
- packages/netsuite-adapter/test/filters/remove_unsupported_types.test.ts
fix custom record types quick fetch
---
---
- fix custom record type quick fetch
---
None
> fix custom record types quick fetch

- packages/netsuite-adapter/src/adapter.ts
- packages/netsuite-adapter/src/elements_source_index/elements_source_index.ts
- packages/netsuite-adapter/src/elements_source_index/types.ts
- packages/netsuite-adapter/src/filters/author_information/constants.ts
- packages/netsuite-adapter/src/filters/author_information/saved_searches.ts
- packages/netsuite-adapter/src/filters/author_information/system_note.ts
- packages/netsuite-adapter/test/elements_source_index.test.ts
- packages/netsuite-adapter/test/filters/author_information/saved_searches.test.ts
- packages/netsuite-adapter/test/filters/author_information/system_note.test.ts
- packages/netsuite-adapter/test/utils.ts
_Author information in netsuite now contains changed at date_
---
_None_
---
* _Author information contains the last modification date of the instance_
---
_None_
> SALTO 2550 - Add changed_at to netsuite

- packages/jira-adapter/src/product_settings/data_center/data_center.ts
Plugin part available [here](https://github.com/salto-io/jira-dc-app/pull/44)
---
---
None
---
None
> SALTO-2846: Jira DC deploy projects (part 2)

- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/article/article.ts
- packages/zendesk-adapter/src/filters/article/utils.ts
- packages/zendesk-adapter/test/filters/article/article.test.ts
- packages/zendesk-adapter/test/filters/article/utils.test.ts
Support article_attachment modification changes
---
* In the process of attachment modification we need to update all the translation's body so all of the URLs will be updated as well.
---
---
> SALTO-2938 zendesk article attachment modifications

- packages/zendesk-adapter/src/adapter.ts
- packages/zendesk-adapter/src/filters/guide_arrange_paths.ts
- packages/zendesk-adapter/test/filters/guide_arrange_paths.test.ts
_zendesk guide filesystem view improvements_
---
None
---
Zendesk:
* guide filesystem view improvements
---
none
> SALTO-3044: zendesk guide filesystem view improvements

- packages/salesforce-adapter/src/filters/split_custom_labels.ts
- packages/salesforce-adapter/test/filters/split_custom_labels.test.ts
Bugfix for `splitCustomLabels` filter.
---
When a single CustomLabel was defined in my org, I saw that the split didn't work. It happened to fail on the Joi validation.
Fixed the bug and added a UT.
---
_None_
---
_None_
> SALTO-2433: Fixed a bug that didn't split a non array CustomLabels::labels value

- packages/netsuite-adapter/src/suiteapp_file_cabinet.ts
- packages/netsuite-adapter/test/suiteapp_file_cabinet.test.ts
---
---
- Fix bug in suiteapp file cabinet where folder parent id is unknown
---
None
> Fix bug in suiteapp file cabinet where folder parent id is unknown

- packages/jira-adapter/jest.config.js
- packages/jira-adapter/src/filters/project.ts
- packages/jira-adapter/src/filters/project_component.ts
- packages/jira-adapter/test/filters/project.test.ts
- packages/jira-adapter/test/filters/project_component.test.ts
_Plugin PR available [here](https://github.com/salto-io/jira-dc-app/pull/48)_
---
---
None
---
None
> Salto-2846: Jira DC support Projects (part 3, last one)

- packages/netsuite-adapter/src/filters/element_references.ts
---
---
- Fix bug of maximum call stack size exceeded in element_references filter
---
None
> Fix bug of maximum call stack size exceeded in element_references filter

- packages/netsuite-adapter/src/filters/internal_ids/sdf_internal_ids.ts
- packages/netsuite-adapter/test/filters/internal_ids/sdf_internal_ids.test.ts
---
---
- fix bug in sdf_internal_ids filter
---
None
> fix bug in sdf_internal_ids filter

- packages/okta-adapter/system_config_doc.md
Populate system_config_doc.md with Okta's config
---
None
---
None
> SALTO-3049: Populate system_config_doc.md (Okta)

- packages/zendesk-adapter/src/filters/article/article_body.ts
- packages/zendesk-adapter/test/filters/article/article_body.test.ts
_support missing references in article bodies_
---
None
---
None
---
None
> SALTO-2937: support missing references in article bodies

- packages/zendesk-adapter/config_doc.md
Update config doc with guide config option
---
---
None
---
None
> SALTO-3071: Update config doc with guide config option

- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/src/filters/article/article.ts
_zendesk guide fix the failure received in deleting and article and its translation_
---
None
---
None
---
None
> SALTO-3172, SALTO-3153: zendesk guide fix the failure received in deleting and article and its translation

- packages/zendesk-adapter/src/filters/field_references.ts
_add references to custom status in ticket form_
---
None
---
Zendesk:
*add references to custom status in ticket form
---
None
> SALTO-3177: add references to custom status in ticket form

- packages/salesforce-adapter/src/change_validators/map_keys.ts
_Map_keys CV - add unresolved reference validation_
---
None
---
None
---
None
> SALTO-3081 Map_keys CV - add unresolved reference validation

- packages/netsuite-adapter/src/change_validators/currency_undeployable_fields.ts
- packages/netsuite-adapter/src/change_validators/not_yet_supported_values.ts
- packages/netsuite-adapter/src/change_validators/workflow_account_specific_values.ts
- packages/netsuite-adapter/test/change_validators/currency_undeployable_fields.test.ts
---
---
SALTO-3199 & SALTO-3201 & SALTO-3202: Add links to relevant docs in some NS Change Validators
---
> SALTO-3199 & SALTO-3201 & SALTO-3202: Add links to relevant docs in some NS Change Validators

- packages/jira-adapter/jest.config.js
- packages/jira-adapter/src/adapter.ts
- packages/jira-adapter/src/config/api_config.ts
- packages/jira-adapter/src/deployment/standard_deployment.ts
- packages/jira-adapter/src/filters/data_center/security_scheme.ts
- packages/jira-adapter/src/filters/security_scheme/security_scheme.ts
- packages/jira-adapter/src/product_settings/cloud.ts
- packages/jira-adapter/src/product_settings/data_center/api_config.ts
- packages/jira-adapter/src/product_settings/data_center/data_center.ts
- packages/jira-adapter/test/filters/security_scheme.test.ts
_Plugin available [here](https://github.com/salto-io/jira-dc-app/pull/54)_
---
Tests will be added later :-(
---
None
---
None
> SALTO-2845: Jira DC security scheme

- packages/adapter-utils/src/collisions.ts
- packages/adapter-utils/test/collisions.test.ts
- packages/salesforce-adapter/src/filters/custom_object_instances_references.ts
- packages/zendesk-adapter/src/filters/collision_errors.ts
- packages/zendesk-adapter/test/filters/collision_errors.test.ts
---
---
SALTO-3200: Add the URL of the CPQ-ID-collisions help article to its fetch warning
---
None
> SALTO-3200: Add the URL of the CPQ-ID-collisions help article to its fetch warning

- packages/salesforce-adapter/src/filters/field_permissions_enum.ts
- packages/salesforce-adapter/test/filters/field_permissions_enum.test.ts
_Reduce fieldPermission size on fetch_
---
None
---
* Reduce fieldPermission size on fetch
---
* will create change in most of the Profiles and PermissionSets
> SALTO-2929 Reduce fieldPermission size on fetch

- packages/zendesk-adapter/src/adapter.ts
Remove redundant client creation in guide deployment code
---
---
None
---
None
> SALTO-3332: Remove redundant client creation in guide deployment code

- packages/zendesk-adapter/src/filters/article/article.ts
- packages/zendesk-adapter/test/filters/article/article.test.ts
_fix error for deployment of a modification of an article with attachments_
---
None
---
None
---
None
> SALTO-3307: fix error for deployment of a modification of an article with attachments

- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/change_validators/flows.ts
- packages/salesforce-adapter/src/client/client.ts
- packages/salesforce-adapter/src/filters/deploy_flows.ts
- packages/salesforce-adapter/test/change_validators/flows.test.ts
- packages/salesforce-adapter/test/client.test.ts
- packages/salesforce-adapter/test/filters/deploy_flows.test.ts
_salesforce - fix flows CV_
---
None
---
* Add support off deploying flows as inactive
---
None
> SALTO-3102 salesforce - deploying flows as inactive

- packages/jira-adapter/jest.config.js
- packages/jira-adapter/src/filters/data_center/security_scheme.ts
- packages/jira-adapter/src/product_settings/data_center/api_config.ts
- packages/jira-adapter/src/product_settings/data_center/data_center.ts
- packages/jira-adapter/test/filters/data_center/issue_events.test.ts
- packages/jira-adapter/test/filters/data_center/security_scheme.test.ts
Completes older [PR](https://github.com/salto-io/salto/pull/3722) 
---
None
---
None
> SALTO-2845: Jira DC Security Scheme (added tests)

- packages/zendesk-adapter/src/deployment.ts
- packages/zendesk-adapter/src/errors.ts
- packages/zendesk-adapter/src/filters/article/utils.ts
- packages/zendesk-adapter/src/filters/brand_logo.ts
- packages/zendesk-adapter/src/filters/business_hours_schedule.ts
- packages/zendesk-adapter/src/filters/guide_default_language_settings.ts
- packages/zendesk-adapter/src/filters/guide_order/guide_order_utils.ts
- packages/zendesk-adapter/src/filters/macro_attachments.ts
- packages/zendesk-adapter/test/errors.test.ts
_present deploy errors in a reader-friendly way_
---
none
---
Zendesk:
* present deploy errors in a reader-friendly way
---
none
> SALTO-3112, SALTO-3100, SALTO-3362: present deploy errors in a reader-friendly way

- packages/core/src/core/deploy/deploy_actions.ts
change error message of deploy so it will also address validate
---
None
---
---
> SALTO-3130 change error message of deploy so it will also address validate

- packages/cli/src/commands/deploy.ts
- packages/cli/src/formatter.ts
- packages/cli/src/prompts.ts
change error message of deploy so it will also address validate
---
None
---
---
> SALTO-3130 change deploy cli outputs so it will also address validate

- packages/netsuite-adapter/src/type_parsers/report_definition_parsing/parsed_report_definition.ts
_path added to inner fields in report definition type_
---
_None_
---
_None_
---
_None_
> Add path to report definition fields

- packages/jira-adapter/src/filters/sort_lists.ts
- packages/jira-adapter/test/filters/sort_lists.test.ts
This reverts commit 9ded98d3c5798957f89ac92574a1542e47034b03.
---
---
None
---
None
> Revert "SALTO-2902/sort list fields (#3763)"

- packages/netsuite-adapter/src/filters/author_information/saved_searches.ts
- packages/netsuite-adapter/src/filters/author_information/system_note.ts
- packages/netsuite-adapter/test/filters/author_information/saved_searches.test.ts
_netsuite changedAt handles timezones_
---
_None_
---
_None_
---
_None_
> Fix NS changeAt timezone issue

- packages/okta-adapter/src/config.ts
Update Application idFields in Okta
---
None
---
None
> SALTO-2644: Update Application idFields in Okta

- packages/adapter-components/src/elements/ducktype/transformer.ts
- packages/zendesk-adapter/e2e_test/adapter.test.ts
- packages/zendesk-adapter/src/client/client.ts
- packages/zendesk-adapter/test/adapter.test.ts
- packages/zendesk-adapter/test/client/client.test.ts
support and handle 403 fetch errors
---
---
zendesk:
* support and handle 403 fetch errors
---
> SALTO-3301, SALTO-2674: gracefully handle 403 fetch errors

- packages/zendesk-adapter/e2e_test/adapter.test.ts
_flaky e2e in zendesk_
---
---
none
---
none
> SALTO-3480: flaky e2e in zendesk

- packages/zendesk-adapter/e2e_test/adapter.test.ts
_fix zendesk e2e_
---
---
None
---
None
> SALTO-3408: fix zendesk e2e

- packages/jira-adapter/src/filters/group_name.ts
- packages/jira-adapter/test/filters/group_name.test.ts
Fixed a bug when deploying a new group with an element that has a reference to it
---
- Fixed a bug when deploying a new group with an element that has a reference to it
---
None
> SALTO-3409: Fixed a bug when deploying a new group with an element that has a reference to it

- packages/jira-adapter/src/filters/dashboard/gadget.ts
- packages/jira-adapter/src/product_settings/data_center/data_center.ts
- packages/jira-adapter/test/filters/dashboard/gadget.test.ts
Fixed setting properties in Jira DC
---
None
---
None
> SALTO-3244: Some properties are missing from dashboard gadgets

- packages/zendesk-adapter/package.json
- packages/zendesk-adapter/src/filters/guide_arrange_paths.ts
- packages/zendesk-adapter/test/filters/guide_arrange_paths.test.ts
- packages/zendesk-adapter/tsconfig.json
_guide deeply nested sections are not nested correctly in the file tree_
---
---
None
---
None
> SALTO-3450: guide deeply nested sections are not nested correctly in the file tree

- packages/jira-adapter/src/filters/board/board_columns.ts
- packages/jira-adapter/src/filters/board/board_estimation.ts
- packages/jira-adapter/src/filters/board/board_subquery.ts
- packages/jira-adapter/test/filters/board/board_columns.test.ts
- packages/jira-adapter/test/filters/board/board_deployment.test.ts
- packages/jira-adapter/test/filters/board/board_estimation.test.ts
- packages/jira-adapter/test/filters/board/board_subquery.test.ts
Fixed an issue that a board without configuration would cause the fetch to fail 
---
__Jira adapter__:
- Fixed an issue that a board without configuration would cause the fetch to fail 
---
None
> SALTO-3476: Fetch failed because of a missing information in a board

- packages/jira-adapter/src/filters/share_permission.ts
- packages/jira-adapter/test/filters/share_permission.test.ts
Fixed a failure in updating project with contexts
---
- Fixed a failure in updating project with contexts
---
None
> SALTO-3482: Fixed project modification

- packages/jira-adapter/e2e_test/instances/cloud/filter.ts
- packages/jira-adapter/src/config/api_config.ts
will add a noise reduction PR as well
---
Jira Adapter:
Filters will now contain also Edit Permissions
---
Jira Adapter:
Filters will now contain also Edit Permissions
> SALTO-2861: Jira Add Edit Permissions to Filters in cloud

- packages/jira-adapter/e2e_test/instances/cloud/filter.ts
_Fixed a problem in the E2E_
---
---
None
---
None
> SALTO-3459: fixed E2E failure

- packages/jira-adapter/src/change_validators/masking.ts
- packages/jira-adapter/test/change_validators/masking.test.ts
reformat change validator with new values.
---
---
---
> SALTO-3403/refactor change validator

- packages/okta-adapter/test/client/client.test.ts
- packages/okta-adapter/test/client/connection.test.ts
- packages/okta-adapter/test/client/pagination.test.ts
Add client Uts to increase coverage in Okta
---
None
---
None
> SALTO-2747: Okta - Add client UTs

- packages/netsuite-adapter/src/change_validators/client_validation.ts
- packages/netsuite-adapter/test/change_validators/client_validation.test.ts
---
---
- Extract field errors on NS client validation
---
None
> Extract field errors on NS client validation

- packages/adapter-utils/src/utils.ts
- packages/salesforce-adapter/e2e_test/adapter.test.ts
- packages/salesforce-adapter/src/change_validators/picklist_promote.ts
- packages/salesforce-adapter/src/constants.ts
- packages/salesforce-adapter/src/filters/global_value_sets.ts
- packages/salesforce-adapter/src/filters/value_set.ts
- packages/salesforce-adapter/test/change_validators/picklist_promote.test.ts
- packages/salesforce-adapter/test/filters/global_value_sets.test.ts
- packages/salesforce-adapter/test/filters/value_set.test.ts
> Revert "SALTO-3479: Added restrictions on Picklist field values upon fetch"

- packages/netsuite-adapter/src/client/client.ts
_Fix "unresolved" issue when deploying/modifying both a custom record type and a field_
---
_A fix for incident-2845_
---
_None_
---
_None_
> SALTO-2926: Fix unresolved issue when deploying custom record type and a fields

- packages/core/src/core/plan/group.ts
- packages/core/src/core/plan/plan.ts
- packages/core/test/common/plan_generator.ts
- packages/core/test/core/plan/plan.test.ts
Today we remove redundant field changes (in type addition/removal) based on the final change groups of the plan - after the DAG splits groups with cycles.
We should remove redundant field changes before the DAG’s splits, because the DAG can split the type & fields to different groups and then we won’t remove the redundant field changes.
---
---
Core:
- Remove redundant field changes based on adapter's change groups
---
None
> SALTO-3539 remove redundant field changes based on adapter's change groups

- packages/jira-adapter/src/filters/fields/default_values.ts
- packages/jira-adapter/test/filters/fields/field_context_deployment.test.ts
Fixed deployment of a user filter in default values
---
---
- Fixed deployment of a user filter in default values
---
None
> SALTO-2939: fixed UserFilter deployment annotations

- packages/adapter-components/src/elements/ducktype/transformer.ts
- packages/adapter-components/src/elements/swagger/instance_elements.ts
- packages/adapter-components/test/elements/swagger/instance_elements.test.ts
- packages/zendesk-adapter/e2e_test/adapter.test.ts
- packages/zendesk-adapter/test/adapter.test.ts
Improve 403 change validator text to include the case of disabled features on business application side.
---
---
N/A
---
N/A
> SALTO-3618 Change CV text to include disabled features

- packages/jira-adapter/src/change_validators/active_workflow_scheme_change.ts
- packages/jira-adapter/src/change_validators/index.ts
- packages/jira-adapter/test/change_validators/active_workflow_scheme_change.test.ts
add change validator to block workflow modification to projects with issues 
---
---
jira_adapter:
* add change validator to block workflow modification to projects with issues 
---
> SALTO-3528/block workflow scheme change

- packages/workato-adapter/src/auth.ts
fix typo
---
---
None
---
None
> SALTO-3412 fix workato param name

- packages/zendesk-adapter/src/change_validators/webhook.ts
> SALTO-3468 - Zd webhook messages

- packages/okta-adapter/src/deployment.ts
Present Okta errors when deploy fails
---
Based on https://developer.okta.com/docs/reference/error-codes/
Currently we don't have unit tests for dpeloyment.ts, so I'll add tests to the entire file in a different PR
---
None
---
None
> SALTO-3657: Present Okta errors when deploy fails

- packages/jira-adapter/src/change_validators/automations.ts
- packages/jira-adapter/src/change_validators/dashboard_gadgets.ts
- packages/jira-adapter/src/change_validators/dashboard_layout.ts
- packages/jira-adapter/src/change_validators/default_field_configuration.ts
- packages/jira-adapter/src/change_validators/issue_type_scheme.ts
- packages/jira-adapter/src/change_validators/locked_fields.ts
- packages/jira-adapter/src/change_validators/private_api.ts
- packages/jira-adapter/src/change_validators/project_deletion.ts
- packages/jira-adapter/src/change_validators/screen.ts
- packages/jira-adapter/src/change_validators/status.ts
- packages/jira-adapter/src/change_validators/system_fields.ts
- packages/jira-adapter/src/change_validators/workflows/read_only_workflow.ts
- packages/jira-adapter/test/change_validators/automations.test.ts
- packages/jira-adapter/test/change_validators/dashboard_gadgets.test.ts
- packages/jira-adapter/test/change_validators/dashboard_layout.test.ts
- packages/jira-adapter/test/change_validators/default_field_configuration.test.ts
- packages/jira-adapter/test/change_validators/issue_type_scheme.test.ts
- packages/jira-adapter/test/change_validators/locked_fields.test.ts
- packages/jira-adapter/test/change_validators/private_api.test.ts
- packages/jira-adapter/test/change_validators/project_deletion.test.ts
- packages/jira-adapter/test/change_validators/screen.test.ts
- packages/jira-adapter/test/change_validators/status.test.ts
- packages/jira-adapter/test/change_validators/system_fields.test.ts
- packages/jira-adapter/test/change_validators/workflows/workflow.test.ts
changed multiple change validator texts according to this [notion page](https://www.notion.so/saltoio/0fc6a30bd892493cac8d1717e061f375?v=583116e1213c438e9caf79d2a49e92f3)
---
---
jira adapter: 
* updated multiple change validator error messages.
---
> SALTO-2940/reformat jira change validators

- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/test/adapter.crud.test.ts
SALTO-3454 add quick-deploy fallback to deploy
---
None
---
None
> SALTO-3454 add quick-deploy fallback to deploy

- packages/jira-adapter/src/change_validators/dashboard_layout.ts
- packages/jira-adapter/src/change_validators/field_contexts/field_contexts.ts
- packages/jira-adapter/src/change_validators/issue_type_scheme_migration.ts
- packages/jira-adapter/src/change_validators/status.ts
- packages/jira-adapter/src/change_validators/workflow_scheme_migration.ts
- packages/jira-adapter/test/change_validators/dashboard_layout.test.ts
- packages/jira-adapter/test/change_validators/field_contexts/field_contexts.test.ts
- packages/jira-adapter/test/change_validators/issue_type_scheme_migration.test.ts
- packages/jira-adapter/test/change_validators/status.test.ts
- packages/jira-adapter/test/change_validators/workflow_scheme_migration.test.ts
fixed bug that was caused over an unresolved reference for multiple change validators.
---
---
---
> SALTO-3690/fixed bug with unresolved references

- packages/netsuite-adapter/src/filters/author_information/saved_searches.ts
- packages/netsuite-adapter/src/filters/author_information/system_note.ts
- packages/netsuite-adapter/test/filters/author_information/saved_searches.test.ts
- packages/netsuite-adapter/test/filters/author_information/system_note.test.ts
This reverts commit 8a58de6f2fc785a12d28bbb2d265f158835db438.
---
---
---
> Revert "Salto-3671/validate saved searches dates (#3981)"

- packages/jira-adapter/src/adapter.ts
Fixed excluding FieldConfiguration
---
- Fixed an issue where excluding a FieldConfiguration would not exclude its items
---
None
> SALTO-3704: Fixed excluding FieldConfiguration

- packages/jira-adapter/e2e_test/adapter.ts
- packages/jira-adapter/e2e_test/instances/cloud/workflow.ts
- packages/jira-adapter/e2e_test/instances/datacenter/workflow.ts
Added e2e test for ScriptRunner
---
None
---
None
> SALTO-3634: Added e2e to ScriptRunner

- packages/netsuite-adapter/src/change_validators/remove_sdf_elements.ts
Change the message of SDF elements removal change validators
---
_None_
---
change-validator messages in case of a failure in removing an SDF element are different
---
_None._
> change validation messages for SDF elements removal

- packages/zendesk-adapter/src/adapter.ts
- packages/zendesk-adapter/src/filters/article/article.ts
- packages/zendesk-adapter/src/filters/article/utils.ts
- packages/zendesk-adapter/test/filters/article/article.test.ts
zendesk fix get of article attachment content
---
---
zendesk:
* zendesk fix get of article attachment content
---
Nonew
> SALTO-3728: zendesk fix get of article attachment content

- packages/zendesk-adapter/src/config.ts
- packages/zendesk-adapter/system_config_doc.md
Update the config with the latest changes
---
None
---
None
> SALTO-3775 update zendesk config doc

- packages/netsuite-adapter/src/client/language_utils.ts
- packages/netsuite-adapter/src/client/sdf_client.ts
- packages/netsuite-adapter/test/client/sdf_client.test.ts
---
---
Netsuite-adapter:
- Add SDF missing feature regex
---
None
> add SDF missing feature regex

- packages/jira-adapter/src/filters/security_scheme/members_deployment.ts
- packages/jira-adapter/src/filters/security_scheme/security_scheme.ts
- packages/jira-adapter/test/filters/security_scheme.test.ts
Fixed a bug where the fetch would fail when an holder is missing from a security level
---
- Fixed a bug where the fetch would fail when a holder is missing from a security level
---
None
> INCIDENT-3657: Fixed a bug where the fetch would fail when an holder is missing from a security level

- packages/netsuite-adapter/src/client/sdf_client.ts
---
---
- Fix SDF deploy errors identification
---
None
> Fix SDF deploy errors identification

- packages/salesforce-adapter/src/filters/formula_deps.ts
- packages/salesforce-adapter/src/filters/formula_utils/cpq.ts
- packages/salesforce-adapter/src/filters/formula_utils/grammar.ts
- packages/salesforce-adapter/src/filters/formula_utils/parse.ts
- packages/salesforce-adapter/src/filters/formula_utils/utils.ts
- packages/salesforce-adapter/test/filters/formula_utils/parse.test.ts
- packages/salesforce-adapter/test/filters/formula_utils/utils.test.ts
Refactor the code we copied from Forcemula
---
~This PR builds on top of https://github.com/salto-io/salto/pull/4005, so the first two commits should be ignored.~
I put each individual refactoring step into its own commit, which should hopefully make reviewing easier.
---
N/A
---
N/A
> SALTO-1730 - Salesforce: Refactor formula utils

- packages/okta-adapter/src/config.ts
Support NetworkZone deployment
---
None
---
None
> SALTO-3807: Deploy NetworkZone Type

- packages/jira-adapter/src/reference_mapping.ts
- packages/okta-adapter/src/reference_mapping.ts
- packages/zendesk-adapter/src/filters/field_references.ts
Resolve references by oktaSerializationStrategy
---
None
---
None
> SALTO-3798: Resolve references by oktaSerializationStrategy

- packages/salesforce-adapter/src/filters/formula_deps.ts
- packages/salesforce-adapter/test/filters/formula_deps.test.ts
Fix the check for invalid references
---
The current code checks a promise against `undefined`. This is a silly thing to do. It also appears that `ElementSource` doesn't handle references to fields, so we need to have special handling for references to field.
---
Salesforce: Formula references that don't refer to elements fetched by Salto will not be added as dependencies
---
N/A
> SALTO-3733 - Salesforce: Fix identification of invalid references in formulas

- packages/adapter-utils/src/compare.ts
- packages/adapter-utils/test/compare.test.ts
- packages/salesforce-adapter/src/adapter.ts
- packages/salesforce-adapter/src/metadata_deploy.ts
- packages/salesforce-adapter/src/transformers/xml_transformer.ts
- packages/salesforce-adapter/test/adapter.crud.test.ts
SALTO-7487 fix hash calculation for quick deploy
---
calc the hash on the xml package instead of the changes
---
None
---
None
> SALTO-7487 fix hash calculation for quick deploy

- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/src/client/sdf_client.ts
add logs on feature map update & log content of manifest.xml & deploy.xml on unknown sdf error.
---
---
None
---
None
> add logs on sdf errors

- packages/netsuite-adapter/src/client/client.ts
- packages/netsuite-adapter/src/client/types.ts
> ns client refactor

- packages/salesforce-adapter/src/change_validators/package.ts
- packages/salesforce-adapter/test/change_validators/package.test.ts
> SALTO-3826: Salesforce Package CV bugfix

- packages/jira-adapter/src/adapter.ts
_changed filters order_
---
The modification filter adds updateable to all the fields, it used to happen before the scriptrunner filter
---
None
---
None
> SALTO-3830 Add updateable to scriptRunner's added fields

- packages/netsuite-adapter/src/change_validator.ts
- packages/netsuite-adapter/src/change_validators/client_validation.ts
- packages/netsuite-adapter/test/change_validator.test.ts
> Remove unused argument in NS client validation

- packages/netsuite-adapter/src/client/client.ts
_fix for incident-3687_
---
_Link to the incident - https://salto-io.atlassian.net/browse/INCIDENT-3687_
---
_When creating the graph, edges are now created between top level changes only_
---
_None_
> INCIDENT-3687: problem fix, start node changed to top level element

- packages/adapter-components/src/references/field_references.ts
This log is extremely noisy
---
---
N/A
---
N/A
> SALTO-3863 - Remove redundant logs

- packages/salesforce-adapter/e2e_test/quick_deploy.test.ts
SALTO-3352 SF add E2E to check validation and quick deploy flow
---
None
---
None
---
None
> SALTO-3352 SF add E2E to check validation and quick deploy flow

- packages/netsuite-adapter/e2e_test/adapter.test.ts
- packages/netsuite-adapter/src/change_validators/account_specific_values.ts
- packages/netsuite-adapter/src/change_validators/client_validation.ts
- packages/netsuite-adapter/src/change_validators/config_changes.ts
- packages/netsuite-adapter/src/change_validators/data_account_specific_values.ts
- packages/netsuite-adapter/src/change_validators/dependencies.ts
- packages/netsuite-adapter/src/change_validators/file_changes.ts
- packages/netsuite-adapter/src/change_validators/immutable_changes.ts
- packages/netsuite-adapter/src/change_validators/instance_changes.ts
- packages/netsuite-adapter/src/change_validators/mapped_lists_indexes.ts
- packages/netsuite-adapter/src/change_validators/not_yet_supported_values.ts
- packages/netsuite-adapter/src/change_validators/remove_file_cabinet.ts
- packages/netsuite-adapter/src/change_validators/remove_list_item.ts
- packages/netsuite-adapter/src/change_validators/remove_standard_types.ts
- packages/netsuite-adapter/src/change_validators/report_types_move_environment.ts
- packages/netsuite-adapter/src/change_validators/safe_deploy.ts
- packages/netsuite-adapter/src/change_validators/standard_types_invalid_values.ts
- packages/netsuite-adapter/src/change_validators/subinstances.ts
- packages/netsuite-adapter/src/change_validators/suiteapp_config_elements.ts
- packages/netsuite-adapter/src/change_validators/undeployable_config_features.ts
- packages/netsuite-adapter/src/suiteapp_file_cabinet.ts
- packages/netsuite-adapter/test/change_validator.test.ts
- packages/netsuite-adapter/test/change_validators/client_validation.test.ts
- packages/netsuite-adapter/test/change_validators/config_changes.test.ts
- packages/netsuite-adapter/test/change_validators/file_changes.test.ts
- packages/netsuite-adapter/test/change_validators/mapped_lists_indexes.test.ts
- packages/netsuite-adapter/test/change_validators/remove_list_item.test.ts
- packages/netsuite-adapter/test/change_validators/report_types_move_environment.test.ts
- packages/netsuite-adapter/test/change_validators/safe_deploy.test.ts
- packages/netsuite-adapter/test/change_validators/suiteapp_config_elements.test.ts
---
---
SALTO-3374: Improve NS change validator messages
---
> SALTO-3374: Improve NS change validator messages

- packages/jira-adapter/e2e_test/instances/cloud/workflow.ts
- packages/jira-adapter/src/filters/sort_lists.ts
As the noise reduction does not work well, temp revert until fixed
---
None
---
None
> SALTO-3845: revert sort workflow order

- packages/salesforce-adapter/src/filters/fetch_flows.ts
SALTO-3877 add configChanges to the client call in fetch flows filter
---
None
---
None
---
None
> SALTO-3877 add configChanges to the client call in fetch flows filter

- packages/netsuite-adapter/src/filters/element_references.ts
- packages/netsuite-adapter/test/filters/element_references.test.ts
---
---
- Identify suitescripts without extension
---
None
> SALTO-2329 identify suitescripts without extension

- packages/jira-adapter/src/filters/field_configuration/field_configuration_dependencies.ts
- packages/jira-adapter/test/filters/field_configuration/field_configuration_dependencies.test.ts
Fixed fetch error when there are no tabs
---
- Fixed a fetch error when there is a screen with no tabs
---
None
> SALTO-3896: Fixed fetch error when there are no tabs

- packages/jira-adapter/src/config_creator.ts
- packages/jira-adapter/test/config_creator.test.ts
Fixed a name typo for the scriptrunner
---
None
---
None
> SAAS-7338: Enable Script Runner in the UI

- packages/okta-adapter/src/config.ts
Deploy BehaviorRule
---
None
---
None
> SALTO-3889: Deploy BehaviorRule

- packages/netsuite-adapter/src/filters/parse_report_types.ts
- packages/netsuite-adapter/test/filters/parse_report_types.test.ts
This reverts commit 779eb7a72acbd6aa688fa030f84ef5ccc554d7a4.
---
---
---
> Revert "SALTO-3725 improve parse-report-types filter (#4034)"

- packages/jira-adapter/src/filters/field_configuration/field_configuration_dependencies.ts
- packages/jira-adapter/test/filters/field_configuration/field_configuration_dependencies.test.ts
This was already merged but reverted in https://github.com/salto-io/salto/pull/4166
---
None
---
None
> SALTO-3896: Fetch failed to run in Jira due to "Cannot convert undefined or null to object"

- packages/jira-adapter/e2e_test/instances/cloud/workflow.ts
- packages/jira-adapter/src/filters/sort_lists.ts
Revert the revert.....
---
None
---
None
> SALTO-3845: cancel sorting of workflow post-functions

- packages/zendesk-adapter/src/filters/unordered_lists.ts
_fix log in unsorted lists filter zendesk_
---
---
None
---
None
> SALTO-3934: fix log in unsorted lists filter zendesk

- packages/okta-adapter/src/config.ts
Fix `Role` type definition to its type in the new swagger file
---
None
---
None
> SALTO-2735: Fix Role type definition

- packages/jira-adapter/src/filters/dashboard/gadget.ts
- packages/jira-adapter/test/filters/dashboard/gadget.test.ts
Fixed a bug where a permission issue when fetching a dashboard would fail the entire fetch
---
- Fixed a bug where a permission issue when fetching a dashboard would fail the entire fetch
---
None
> SALTO-3928: 403 when fetching a dashboard fails the entire fetch
